### ISSUE TITLE
3.18.7 breaks SimpleDb (v3-bridge)

### ISSUE THREAD

**Issue by mvanbaak** [aws/aws-sdk-php#1001]
After upgrading the aws-sdk-php from 3.18.6 to 3.18.7 the aws-sdk-php-v3-bridge is not working with EC2 instance roles and IAM permissions.

How to reproduce:
On an EC2 instance create the following composer.json:
```javascript
{
    "require": {
        "aws/aws-sdk-php-v3-bridge": "^0.1.0"
    }
}
```
create the following php code (test.php)
```php
<?php
require_once 'vendor/autoload.php';
$sdb = new \Aws\SimpleDb\SimpleDbClient(['region' => 'eu-west-1', 'version' => 'latest']);
var_dump($sdb->listDomains());
```
Run `composer install`
This will install `aws/aws-sdk-php 3.18.12` and `aws/aws-sdk-php-v3-bridge 0.1.0`

When running `php test.php` it gives output
```bash
PHP Fatal error:  Uncaught exception 'Aws\SimpleDb\Exception\SimpleDbException' with message 'Error executing "ListDomains" on "https://sdb.eu-west-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://sdb.eu-west-1.amazonaws.com` resulted in a `401 Unauthorized` response:
<?xml version="1.0"?>
<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to authenticate the req (truncated...)
 AuthFailure (client): AWS was not able to authenticate the request: access credentials are missing - <?xml version="1.0"?>
<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to authenticate the request: access credentials are missing</Message></Error></Errors><RequestID>XXXXXX-XXXX-XXXX-XXXX-2ca7ba551109</RequestID></Response>
```

Now if you do: `composer require "aws/aws-sdk-php:3.18.6"` and try again, everything will work.

**Comment by cjyclaire** [comment]
Thanks for catching that, since in aws/aws-sdk-php-v3-bridge, `SimpleDB` is supported with SignatureV2. Yet current endpoint in SDK require Signature V4 for `SimpleDB`, that's why you would have trouble for authentication. I'm working on adding support for it.

**Comment by cjyclaire** [comment]
@mvanbaak , a new [release](https://github.com/aws/aws-sdk-php-v3-bridge/releases/tag/0.2.0) for `aws/aws-sdk-php-v3-bridge` is out with fix. 
Once you `require aws/aws-sdk-php-v3-bridge:0.2.0` it should work. Cheers!
