### ISSUE TITLE
Checksum validation with putObject

### ISSUE THREAD

**Issue by vmpj** [aws/aws-sdk-php#1010]
I'm very confused about the checksum validation. I want to be sure the data was not corrupted during the upload.

Does the php client calculate the checksum automatically or should I calculate a md5 or sha256 when doing a `putObject` command?

Using  `ContentMD5` like so:

        $md5 = md5_file($image);
        $result = $s3->putObject([
            "Bucket" => $bucket,
            "Key" => $key,
            "image" => $image,
            "ACL" => "public-read",
            "ContentMD5" => $md5
        ]);

errors like this:

```
<Error><Code>InvalidDigest</Code><Message>The Content-MD5 you specified was inval (truncated...)
 InvalidDigest (client): The Content-MD5 you specified was invalid. - <?xml version="1.0" encoding="UTF-8"?>
<Error>
```

**Comment by cjyclaire** [comment]
@vmpj you're on the right track! yet the config should be `Content-MD5` instead of `ContentMD5 `.

**Comment by vmpj** [comment]
Sorry for the delay in getting back to you on this.

If I use `Content-MD5` it seems like it is being ignored. I can put anything to it and it will still work.
```
        $md5 = "boom";//md5_file($image);
        $result = $s3->putObject([
            "Bucket" => getenv("S3_BUCKET_NAME"),
            "Key" => $key,
            "image" => $image,
            "ACL" => "public-read",
            "Content-MD5" => $md5
        ]);
```
I'm not sure if I should perhaps put `Content-MD5` inside a Meta-data block...

**Comment by vmpj** [comment]
Got it working but only if I used sha265:
```
        $sha256 = hash_file("sha256", $image);
        $result = $s3->putObject([
            "Bucket" => getenv("S3_BUCKET_NAME"),
            "Key" => $key,
            "SourceFile" => $image,
            "ACL" => "public-read",
            "ContentSHA256" => $sha256
        ]);
```
Note in my first example I was using the key `image` instead of `SourceFile` which obviously would not work.

**Comment by MarkMurphy** [comment]
Same problem today using `"ContentMD5" => $checksum`
