### ISSUE TITLE
Aws\S3\S3Client\Transfer() method causing OOM errors when working with large numbers of files

### ISSUE THREAD

**Issue by genomachino17** [aws/aws-sdk-php#1011]
I am using the PHP SDK v3 API to download files from S3. The method I'm using is \Aws\S3\S3Client->Transfer(), a method which I prefer to the CLI because it downloads all files and maintains the S3 "folder structure" on the destination filesystem.

However, I am running into a major issue when trying to download collections of S3 objects that are fairly large (> 500,000 individual files) -- I am running out of memory in PHP. It seems that this is caused when the Transfer() method creates an array of GetObject commands (one command for each file, and thus one entry in the array for each command) and eventually that array becomes too large for memory (if there are a massive number of files, like in our EMR log stores in S3, for example).

Transfer() calls createDownloadPromise() which uses a commandPool(). The commandpool() appears to also accept an Iterator object, rather than the $commands[] array that is currently passed to it. If an Iterator was used instead, it seems that this would eliminate the OOM problems that happen when the file count becomes large.

Is this something that can be fixed/modified in the SDK? I can send an example of the modified code that I've used to get around this issue, if that would help. Thoughts?

Thanks!

**Comment by cjyclaire** [comment]
@genomachino17 Thanks for bringing this up! 
Originally, iterator is mapped in `createDownloadPromise()`, a similar issue popped up then `$command[]` is applied as a soft fix. #917 

Since enhancement has been made in `guzzle/promises`, I'd revert the command array change after reproducing the issue and fully testing it.

**Comment by genomachino17** [comment]
Thanks for the reply. I'll look up #917 to see if I can make use of the previous method.

**Comment by cjyclaire** [comment]
@genomachino17 Does the original iterator method resolve this issue? Since I couldn't reproduce the old issue to ensure that the guzzle enhancement is enough to bring iterator back. Any updates?

**Comment by cjyclaire** [comment]
I'll close this for no follow-ups available, yet feel free to reopen with any questions or updates :)

**Comment by genomachino17** [comment]
Sorry for no follow-up on this. Simply plugging in the original iterator method ended up working, and still works today (using the iterator instead of the array). I've been away from the case for a while, so I'm not certain that I can confirm that the guzzle enhancement was enough to bring the iterator back for good -- but I can confirm that it has worked for my purposes since then.

**Comment by joehoyle** [comment]
FWIW I also ran into this. This seems pretty easy to reproduce with a long file list (say 500k and lower memory limit). @cjyclaire I don't think there's much more description needed here, as I think it's pretty evident (from what I understand) that the `$commands` array is never reduced, therefore memory will only ever increase.
