### ISSUE TITLE
Waiter for InternetGatewayAvailable

### ISSUE THREAD

**Issue by adamjimenez** [aws/aws-sdk-php#1018]
Expected to see a waiter for this but there doesn't appear to be one.

**Comment by cjyclaire** [comment]
@adamjimenez , Could you provide the SDK version that is using? There is update in last release on EC2 models.

**Comment by adamjimenez** [comment]
3.18.19

or should the waiter be: "InternetGatewayExists"

I'm trying to create an internet gateway and then immediately tag it.
Sometimes this fails because the gateway is not yet created.

**Comment by cjyclaire** [comment]
@adamjimenez , I see. Could you try `wait()` on the promise? For example:
After you create InternetGateway like:
```
$promise = $client->createInternetGatewayAsync([/* ... */]);
```
Then you could force wait on the [promise](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/promises.html#waiting-on-promises) until it completes:

```
$promise->wait();
```

**Comment by adamjimenez** [comment]
that worked a treat, thank you.

**Comment by cjyclaire** [comment]
Awesome！
