### ISSUE TITLE
StreamWrapper does not support "touch()"

### ISSUE THREAD

**Issue by sattes-faction** [aws/aws-sdk-php#1019]
When using the StreamWrapper, it's currently not possible to use the native php function [touch()](http://php.net/manual/en/function.touch.php):

    touch('s3://bucket/file', time())

throws a warning:

**Warning: touch(): Aws\S3\StreamWrapper::stream_metadata is not implemented!**

**Comment by cjyclaire** [comment]
@sattes-faction , thanks for bringing this up. It's true that SDK stream wrapper doesn't has the `touch()` function right now, here is what are already [supported](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-stream-wrapper.html).

Before considering this feedback as a feature request, could you provide more information about the use case? There should be some work-arounds available with direct S3 client operations. So, could you share more about benefits of having `touch()` in stream wrapper?

**Comment by mtdowling** [comment]
I can't think of a way that we could support this with S3: http://php.net/manual/en/streamwrapper.stream-metadata.php

See also https://github.com/aws/aws-sdk-php/pull/776

**Comment by sattes-faction** [comment]
I'm using the SDK in combination with the pimcore CMS system, where it's used to store the images and generated thumbnails on S3. The touch-command is used for the thumbnail creation. This is the code line:

https://github.com/pimcore/pimcore/blob/6695c0348df6072938199c57255c8b56f7276037/pimcore/models/Asset/Image.php#L70

In the meantime the pimcore guys muted the touch command so it doesn't result in an error using the SDK stream wrapper.

**Comment by cjyclaire** [comment]
Cool, thanks for the follow-up information.

Closing, yet feel free to reopen if you have further questions :)
