### ISSUE TITLE
Possible to verify a presigned URL , like an s3 server would do? 

### ISSUE THREAD

**Issue by harveyslash** [aws/aws-sdk-php#1027]
I am able to generate URLS, but I am having the client send the signed url back to my server. 
Is there a way to verify if that Url has not been tampered with ?

**Comment by cjyclaire** [comment]
@harveyslash , that's an interesting feedback to know, thanks. 

First of all, SDK generates the presigned-URL on the client side, and leave verification job to s3 server as you mentioned. Server-side verification requires credentials and bucket/key information etc., which I couldn't see how client-side may help with that. If the Url has been tampered, server-side verification will fail.

**Comment by cjyclaire** [comment]
Closing due to ages, yet please feel free to reopen if you have further questions or thoughts :)

**Comment by hu-ang** [comment]
Hello! Not exactly the same issue, but jumping on to ask if you know of any service quotas or limitations for presigned URL verification? Especially if those requests are concurrent?
