### ISSUE TITLE
Package guzzle/guzzle is abandoned during composer update.

### ISSUE THREAD

**Issue by alexankit** [aws/aws-sdk-php#1028]
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

https://packagist.org/packages/guzzle/guzzle

**Comment by GrahamCampbell** [comment]
You need to upgrade to aws sdk v3.

**Comment by cjyclaire** [comment]
Closing, in SDK V3, `composer.json` uses `guzzlehttp/guzzle` instead of  ` guzzle/guzzle`, yet feel free to reopen if you have further questions :)
