### ISSUE TITLE
V3 SDK error: "cURL error 61: Unrecognized or bad HTTP Content or Transfer-Encoding"

### ISSUE THREAD

**Issue by sprosov** [aws/aws-sdk-php#1033]
Hello,
I use some script on PHP to get object from S3 and process it. I get object from S3 with next code:

```
$command = $this->s3Client->getCommand(
    'GetObject',
    [
        'Bucket'                  => $backetName,
        'Key'                     => $objectKey,
        'ResponseContentEncoding' => 'identity'
    ]
);
return $this->s3Client->execute($command)->toArray(); 
```

Yesterday I found that this script returns error:

> Error executing \"GetObject\" on \"https://s3.amazonaws.com/backet-name/object-key?response-content-encoding=identity\"; AWS HTTP error: cURL error 61: Unrecognized or bad HTTP Content or Transfer-Encoding".

This script has worked fine some months before. Objects are available in S3. I check his availability before call GetObject command with method doesObjectExist. 

I tried use another ResponseContentEncoding and finally remove this option, but result was same. 
I disabled 'decode_content' option in client initialization and in getCommand call, but that didn't help. 
Can someone help me to resolve this problem?

**Comment by cjyclaire** [comment]
@sprosov I couldn't reproduce the error locally with the code snippet provided with normal files.
> I disabled 'decode_content' option in client initialization and in getCommand call, but that didn't help. 

Are you suggesting that the file causing the issue is .bin file using .gzip? Could you try turn on [`debug`](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#debug) to provide more information about the error?

**Comment by sprosov** [comment]
Objects in S3 are binary files with special format.

Today I studied SDK code whole day and finally found decision. 

At first, we use GuzzleHttp v5 library. I found that for this version 'decode_content' option doesn't work. 'http' option (so 'decode_content' too) doesn't include to validOptions array in GuzzleV5 handler and it excluded from options array when handler initialize request.

We can't quickly move to Guzzle v6, so I create simple handler with required options and set it in 'http_handler' when initialize S3 client. It resolved my problem.

There is my code. 

```
$this->s3Client   = new S3Client(
			[
				'credentials'       => $credentials,
				'region'            => 'us-east-1',
				'version'           => '2006-03-01',
				'signature_version' => 'v4',
				'http_handler'      => function(RequestInterface $r, array $opts = []) {
					$client = new Client();
					$client->setDefaultOption('decode_content', false);
					$handler = new GuzzleHandler($client);
					return $handler($r, $opts);
				}
			]
		);
```
