### ISSUE TITLE
DynamoDB query combined with Limit and a queryFilter or a FilterExpression

### ISSUE THREAD

**Issue by paithalmi** [aws/aws-sdk-php#1040]
Hi i want to apply a query filter with query and limit. Right now what it does is it queries the data based on query parameters with limit and then it applies the filter on that. So if there are results which comes after the applied limit it doesn't returns the results.

Saw the thread in java sdk: https://github.com/aws/aws-sdk-java/issues/339. There we can do the same. Please suggest how we can do in php sdk.

**Comment by wreckingadm** [comment]
I believe you only get one limit on a query, so you may want to pick the most efficient for the DB call (such as the one that is going to end up using less bandwidth), then do your second filter directly in PHP on the query results. It's a bit more handling code-side rather than directly in the DB query, but it will give you more control for what your trying to do in the end.

**Comment by paithalmi** [comment]
If i do that in PHP, if the query result is less than the limit i need to do the query again and again until the result count reaches the limit or there are no more results.
If i do this way, number of queries i hit to db becomes huge. So its better if you return the results with the query filter values while applying the query.

**Comment by cjyclaire** [comment]
Thanks for the discussion going on, [the behavior](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/QueryAndScan.html#ScanQueryLimit) observed is true for dynamoDB, and as dynamoDB suggests, `LastEvaluatedKey` value will be presented if the operation did not return all matching items in the table, using `ExclusiveStartKey` in next request and repeat. API reference see [here](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-dynamodb-2012-08-10.html#query). The way that how Java SDK handles this with `query()` seems to be making requests lazily in the same way.

Perhaps the best way to handle this also has to do with your data, if data size is not huge, simple way like single query request with filter then perform limit locally might works better.
In customizing searching results, you might also be interested in [`JMESPath`](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/jmespath.html) pattern in PHP SDK.

**Comment by cjyclaire** [comment]
Closing due to ages, yet feel free to reopen if you have further comments or questions :)

**Comment by nikhil-uc** [comment]
We have 300+ million records in DynamoDB and doing a recursive calls just to get the limit on filters or getting a large set of data and applying filters programmatically is not so convenient and time consuming when the data needs to be displayed to the user.

Any hopes or suggestions?

**Comment by andybrand** [comment]
You might be able to get what you need by using a secondary index.  Using the classic RDB customer - order - line item example: you have one table for customers, one for orders and one for line items.  You have organized a Key consisting of Customer - HASH, Order - RANGE.  So if you wanted to get the latest10 orders, there would be no way to do it without a scan

But if you create a Global Secondary Index on orders of "Some Constant" -- HASH, Date RANGE, and queried against that index, they query would do what you want and only charge you for the RCUs involved with the records you actually returned.  

Now you have your original problem if you want to get the 10 biggest orders for a day larger than $1000.  The query would return the last 10 orders, and then filter out those less than $1000.
In this case, you could create a computed key of Date-OrderAmount, and queries against that index would return what you want.  

It's not as simple of SQL but it works.  If if you have a lot of data, you need to create Indexes in SQL or the DB will happily to table scans on your behalf, which will impair performance and raise your costs. 
 
Bear in mind that the CONSTANT as a HASH s subject to the 10GB per partition limit, so you would need to design around it if you had a lot of active data.  For example, depending on your expected access pattern, you could use Customer and not a constant as a HASH.
