### ISSUE TITLE
Ability to make CloudSearch Domain search using POST?

### ISSUE THREAD

**Issue by caschbre** [aws/aws-sdk-php#1044]
I believe I'm running into the character limit (mentioned [here](http://docs.aws.amazon.com/cloudsearch/latest/developerguide/submitting-search-requests.html)) with the $domainClient->search(...) method.

Is this method using GET to retrieve results?

Is there a way to make (or configure) search to use POST instead?

Edit: It appears the aws-sdk-js ran into a [similar issue](https://github.com/aws/aws-sdk-js/issues/614).

**Comment by cjyclaire** [comment]
@caschbre , thanks for reporting, it's using 'GET' in retrieving results, I'll tag it as a feature request of adding option in configuring 'POST' when performing the search.

**Comment by cjyclaire** [comment]
Closing, PR fix #1045 is merged, feel free to reopen if you have further questions or comments :)
