### ISSUE TITLE
Package guzzle/guzzle is abandoned [Composer] (SDK v2) 

### ISSUE THREAD

**Issue by cristiammercado** [aws/aws-sdk-php#1046]
Hi,

I'm using v2 of the library (I need to support PHP 5.4). I installed AWS PHP SDK with Composer. When I executed composer commands to install and update, It shows me the message:

`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.`

Could you update the guzzle library dependency in composer.json file and test it?

Thanks a lot!

**Comment by mtdowling** [comment]
You will need to migrate to the AWS SDK for PHP version 3 in order to use a maintained version of Guzzle. You can find out more information here: http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/migration.html
