### ISSUE TITLE
CloudSearch update broke requests.

### ISSUE THREAD

**Issue by Dayjo** [aws/aws-sdk-php#1047]
Hi guys,

Great work on the SDK, makes very light work of AWS. 

Not sure if this is known issue, or perhaps we are doing something wrong ourselves, but the following fix for https://github.com/aws/aws-sdk-php/pull/1045  (https://github.com/aws/aws-sdk-php/commit/b83971185672066bc230d16a1271cb20c3a6e18f) ended up breaking our CloudSearch requests.

We started getting the following error;
```
When Content-Type:application/x-www-form-urlencoded, URL cannot include query-string parameters (after '?')
```

We hadn't changed anything and assumed that it would just continue to work correctly.

The code we're using is along these lines (using Laravel);

```php
$this->client = new Aws\CloudSearchDomain\CloudSearchDomainClient([
		    'version' => Config::get('aws.version'),
		    'region'  => Config::get('aws.region'),
			'credentials' => [
				'key'    => Config::get('aws.credentials.key'),
        		'secret' => Config::get('aws.credentials.secret'),
			],

			'endpoint'	=> Config::get('aws.cloudsearch.endpoint'),
		]);


$search = [
            'query' => $phrase,
            'filterQuery' => $filter,
            'format' => 'json',
            'size' => 1000,
            'return' => '_score',
            'highlight' => '{ title: {}, tags: {}, content: {} }',
        ];

        // Grab the results
        $results = $this->client->search( $search );
```

On version `3.18.31` it works ok, but as soon as we updated to `3.18.32` we started getting those errors.

If it's just something we've missed it'd be great to know what so we can fix it for when we want to upgrade again! 

Thanks,

Joel

**Comment by moee** [comment]
I experienced a similar problem after the upgrade to `3.18.32`, as it also breaks CloudSearch for me in the eu-west-1 region (I'm not sure if it's only a problem of this particular region, though).

Consider this example:

```php
$sdk = new \Aws\Sdk();
$cloudsearch = $sdk->createClient(
    'CloudSearchDomain',
    [
        'endpoint' => 'https://***********.eu-west-1.cloudsearch.amazonaws.com',
        'region' => 'eu-west-1',
        'version' => '2013-01-01'
    ]
);
print_r($cloudsearch->search([ 'query' => 'test' ])['hits']['found']);
```

With `3.18.31` I get the correct result. However, if I update to `3.18.32` I get the following fatal error.

```
Fatal error: Uncaught exception 'Aws\CloudSearchDomain\Exception\CloudSearchDomainException' with message 'Error executing "Search" on "https://***********.eu-west-1.cloudsearch.amazonaws.com/2013-01-01/search?format=sdk&pretty=true&q=test"; AWS HTTP error: Client error: `POST https://***********.eu-west-1.cloudsearch.amazonaws.com/2013-01-01/search?format=sdk&pretty=true&q=test` resulted in a `403 Forbidden` response:
{"__type":"#IncompleteSignature","error":{"message":"[*Deprecated*: Use the outer message field] When Content-Type:appli (truncated...)
```

**Comment by cjyclaire** [comment]
Thanks for reporting, appreciate that! Working on investigating and fix.

**Comment by cjyclaire** [comment]
The  Fix PR is merged and will be tagged in tomorrow release, thanks!

**Comment by Dayjo** [comment]
Awesome, thank you @cjyclaire 

Once this release has gone out, I shall try and update once again and test it.

**Comment by cjyclaire** [comment]
@Dayjo 3.18.33 containing this fix is out, thank you for the patience :)

**Comment by Dayjo** [comment]
This is now working by the way 👍
