### ISSUE TITLE
Requests specifying Server Side Encryption with Customer provided keys must provide a valid encryption algorithm.

### ISSUE THREAD

**Issue by neophyt3** [aws/aws-sdk-php#1050]
I am using Laravel Aws wrapper, After initializing the client I grab the object of s3 client like below

```
$s3_disk = Storage::disk('s3');
$s3Client = $s3_disk->getDriver()->getAdapter()->getClient();

```
Now I want to use Amazon SSE-C, as per the documentation I am mapping s3.ssec middleware like below
```
$s3Client->getHandlerList()->appendInit(
  Middleware::mapCommand(function (CommandInterface $command) {
    $command['SSECustomerKey'] = 'test';//openssl_random_pseudo_bytes(256/8););
  return $command;
}),'s3.ssec');

```

After this I do 
`$s3_disk->put($file_path,file_get_contents($file_to_upload));`

Now I get error as below, stating to put encryption algorithm..
```
Error executing "PutObject" on "https://s3-ap-southeast-1.amazonaws.com/bucketdemo/userfiles/d0b88aaac2d58985ec1e680e10a858d8/memories/video/small.mp4"; AWS HTTP error: Client error response [url] https://s3-ap-southeast-1.amazonaws.com/bucketdemouserfiles/d0b88aaac2d58985ec1e680e10a858d8/memories/video/small.mp4 [status code] 400 [reason phrase] Bad Request InvalidArgument (client): Requests specifying Server Side Encryption with Customer provided keys must provide a valid encryption algorithm. - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidArgument</Code><Message>Requests specifying Server Side Encryption with Customer provided keys must provide a valid encryption algorithm.</Message><ArgumentName>x-amz-server-side-encryption</ArgumentName><ArgumentValue>null</ArgumentValue><RequestId>215A4AE10748E082</RequestId><HostId>lo5K2bYnUopRXUyTiaT1vHG1bWA6hEFZ3wREvqEFq4KC613q/jmbdeJmTUMJLNP6r6+AN8QKOfE=</HostId></Error>
```
How do I inject this header?
I tried injecting by mapping s3.head-object request headers but it is throwing same error

**Comment by cjyclaire** [comment]
@neophyt3 , the value passed in need to be appropriate for use with the algorithm specified in the `x-amz-server-side​-encryption​-customer-algorithm` header. You don't need to inject the header by yourself, you just need to make sure the SSE-C value is valid.

API doc [here](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#putobject).
AWS Public documentation about the algorithm [here](http://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html).

**Comment by neophyt3** [comment]
@cjyclaire I have gone through the docs earlier, in there it mentions that in order to use sse-c we need to pass headers while requesting which can be passed by injecting middleware into the aws client object
here is the guide [link](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/handlers-and-middleware.html)
when I tried injecting those custome algo and key headers it failed and throws error that it could not verify the signature coz those headers were not included in the signature creation when I injected it,
so I found other way, by adding 
```
$s3Client->getHandlerList()->appendInit(
  Middleware::mapCommand(function (CommandInterface $command) {
    $command['SSECustomerKey'] = md5('test');
    $command['SSECustomerAlgorithm'] => 'AES256';
    $command['SSECustomerKeyMD5'] => md5(md5('test'), true),
  return $command;
}),'s3.ssec');
```
But this also failed and throwed an error that it could not parse the response xml...


I can successfully put my  file with sse-c enctyption by doing this
```
$result = $client->putObject([
    'SSECustomerAlgorithm' => 'AES256',
    'SSECustomerKey' => md5('test'),
    'SSECustomerKeyMD5' => md5(md5('test'), true),
    ...
]);
```
But the problem is that I have to use client obbject directly, and I am using Laravel aws wrapper
So I thought that I could get the client object once and change the sse-c middleware by Middleware::mapcommand() so that I dont have to go everywhere and add those direct method codes..
