### ISSUE TITLE
ClientResolver returns "Missing required client configuration options" without listed properties

### ISSUE THREAD

**Issue by zelding** [aws/aws-sdk-php#1051]
I am trying to create a platform endpoint for a GCM application with the `Aws\Sdk::createSns`, but the ClientResolver throws an InvalidArgumentException with the message:
`"Missing required client configuration options: \n\n"`
There should be items after the `: \n\n` in the message.

here is a snippet from my code:

```
$sharedConfig = [
	'region'  => 'eu-central-1',
	 'version' => 'latest',
	 'credentials' => [
		'key'    => AMAZON_ACCESS_KEY_ID,
		'secret' => AMAZON_SECRET_ACCESS_KEY,
	],
	'scheme'  => 'http',
];

$sdk = new AmazonSDK($sharedConfig); // class alias for Aws\Sdk
$sns = $sdk->createSns();

$response = $sns->createPlatformEndpoint([
	"CustomUserData" => json_encode([
		"aiuid" => AIUD
	]),
	"PlatformApplicationArn" => AMAZON_PLATFORM_ARN_ANDROID,
	"Token" => TOKEN
]);
```
Edit:
The SDK version is 3.18.35.
`log_errors_max_len` is 1024 
The message is the caught InvalidArgumentExceptions message.

I have no idea atm.
Please help

**Comment by cjyclaire** [comment]
@zelding , I couldn't reproduce the issue with V3, could you use `try-catch` block to catch the exception then get the exception message by using `getMessage()` to get more information?

Also, may I ask which SDK version are you using? Is the `AmazonSDK` referring `\Aws\Sdk()` actually?

**Comment by mtdowling** [comment]
This truncation could be cased by the log_errors_max_len PHP ini setting: http://php.net/manual/en/errorfunc.configuration.php#ini.log-errors-max-len. Try to increase this setting to see if you can see more of the message. And, as @cjyclaire stated, you could also try/catch the exception and print out the message.

**Comment by zelding** [comment]
I am using the latest sable version, according to composer it is 3.18.33.
The message I showed is the caught exception message; i just left out the block, because i thought its not important.

`log_errors_max_len` is 1024 bytes, so i guess it should be enough; I've tried to throw and catch an Exception with the message `abcdefghijklmnopqrstuvwxyz-` copied 20 times, and it wasn't truncated.

I'll update the original post with these infos.

**Comment by cjyclaire** [comment]
Uh, interesting, I still couldn't reproduce, `region` and `version` are required parameters for any AwsClient. Out of curiosity, could you try creating an SNSClient by:
```
$sns = new Aws\Sns\SnsClient([
    'region'  => 'eu-central-1',
    'version' => 'latest',
    'scheme' => 'http',
]);
```
Will that also produce same error message?

**Comment by zelding** [comment]
@cjyclaire Yes it does. The exact same message :(

**Comment by cjyclaire** [comment]
When I'm trying to reproduce:
```
require __DIR__ . "/../vendor/autoload.php";

$sns = new Aws\Sns\SnsClient([
    'region'  => 'eu-central-1',
    'version' => 'latest',
    'scheme' => 'http',
]);

var_dump($sns->getConfig());
```
or by
```
$sharedConfig = [
    'region'  => 'eu-central-1',
    'version' => 'latest',
    'scheme'  => 'http',
];

$sdk = new \Aws\Sdk($sharedConfig);
$sns = $sdk->createSns();

var_dump($sns->getConfig());
```
both give correct output 
```
array(3) {
  ["signature_version"]=>
  string(2) "v4"
  ["signing_region"]=>
  string(12) "eu-central-1"
  ["signing_name"]=>
  string(3) "sns"
}
```

May I ask is this "Missing client configuration error" the only error thrown? Do you get same error message when creating other service client?

**Comment by zelding** [comment]
Something has changed. I've tried again with the `$sns = new Aws\Sns\SnsClient` method, and now it seems to call the AWS service, because now it gives me `bad request 400`, but if i try `$sns = $sdk->createSns()` it still produces the same error.

The new errorMessage is this.

```
Error executing "Subscribe" on "http://sns.eu-central-1.amazonaws.com";
AWS HTTP error: Client error: `POST http://sns.eu-central-1.amazonaws.com` resulted in a `400 Bad Request` response:
 
Sender
InvalidPara (truncated...)
InvalidParameter (client): Invalid parameter: Endpoint - 
 
Sender
InvalidParameter
Invalid parameter: Endpoint
 
SOME_LONG_STRING_OF_CODE
```

@cjyclaire Yes that was the only error. I haven't tried to create other clients. Would you recommend one, that requires the minimum effort to set up?

**Comment by cjyclaire** [comment]
@zelding thanks for the updates, so are you still using same configuration parameters in getting those errors?

From the error message, it seems to have trouble with 'Endpoint'? SDK configuration takes ['endpoint'](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#endpoint) parameter.

**Comment by cjyclaire** [comment]
@zelding Soft ping~ any updates so far?

**Comment by zelding** [comment]
Sry for not responding in a while. I left a company where I had the issue, but ive passed on the link to this thread so the ppl who take after me can continue.
I suggest you cose the thread for now, and I'm sure others will copmment, when they encounter the issue.

**Comment by cjyclaire** [comment]
No problem, thanks!

**Comment by RyanDwyer** [comment]
I've found the problem. I've got the same issue when setting up a production environment. The issue happens if one of the $args has a null value, and the argument is required and has no default.

While reading the below, keep in mind that isset() will return false if the key is set and has a null value, while array_key_exists() will return true if the key is set and has a null value.

See ClientResolver.php, resolve():

	if (!isset($args[$key])) {
		if (isset($a['default'])) {
			// Merge defaults in when not present.
			if (is_callable($a['default'])
				&& (
					is_array($a['default'])
					|| $a['default'] instanceof \Closure
				)
			) {
				$args[$key] = $a['default']($args);
			} else {
				$args[$key] = $a['default'];
			}
		} elseif (empty($a['required'])) {
			continue;
		} else {
			$this->throwRequired($args);
		}
	}

The above is using isset(), so the null argument triggers a call to throwRequired().

    private function throwRequired(array $args)
    {
        $missing = [];
        foreach ($this->argDefinitions as $k => $a) {
            if (empty($a['required'])
                || isset($a['default'])
                || array_key_exists($k, $args)
            ) {
                continue;
            }
            $missing[] = $this->getArgMessage($k, $args, true);
        }
        $msg = "Missing required client configuration options: \n\n";
        $msg .= implode("\n\n", $missing);
        throw new IAE($msg);
    }

Here, it's using array_key_exists(). This check returns true for the null argument, and the continue statement is run. The $missing array is ultimately empty.

The array_key_exists() check should be replaced with isset($args[$k]).

**Comment by bilmapay** [comment]
I Encounter the same error but I'm using Laravel, in my case it turns out that the env variable name for the region was SNS_DEFAULT_REGION and I was assuming its AWS_DEFAULT_REGION. I have to carefully check and Identify the problem then resolved. So, It turns out it was passing a Null value to the configs.
