### ISSUE TITLE
PHP5.5 and Throwable and your Retry implementation

### ISSUE THREAD

**Issue by bestis** [aws/aws-sdk-php#1055]
Hi,

AWS SDK PHP says >=5.5 but then you have this in RetryMiddleware.php:
`
    private function isThrowable($value)
    {
        return class_exists(\Throwable::class)
            ? $value instanceof \Throwable
            : $value instanceof \Exception ;
    }
`
What do you think happens if we have class loader that throws errors if you try that? It floods the error log with Failed to load class, Throwable errors :(

Could you do this in any other way that would not need loading the class? If not, then at least add autoload false to it?
`
    private function isThrowable($value)
    {
        return class_exists(\Throwable::class, false)
            ? $value instanceof \Throwable
            : $value instanceof \Exception ;
    }
`

**Comment by bestis** [comment]
Or should it even be:
`class_exists('Throwable', false)`

**Comment by cjyclaire** [comment]
@bestis thank you for pointing this out, I just open a PR contains the fix, a new release will be out containing once the PR is merged.

**Comment by GrahamCampbell** [comment]
You don;t need to check if a class exists. PHP won;t try to load it.

**Comment by cjyclaire** [comment]
Closing, fix PR is merged and will be tagged in tomorrow release.
