### ISSUE TITLE
2.8.31 - including guzzle/guzzle now throws deprecation warning

### ISSUE THREAD

**Issue by bmd** [aws/aws-sdk-php#1058]
Composer issues the following warning when installing `aws-sdk-php`: `Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.`

Updating composer.json to include in the next minor version should be sufficient to resolve the deprecation warning.

``` json   
"require": {
    "php": ">=5.3.3",
    "guzzlehttp/guzzle": "~3.7"
}
```

**Comment by cjyclaire** [comment]
[Guzzle Version](https://github.com/guzzle/guzzle#version-guidance)
In SDK V3, `composer.json` uses `guzzlehttp/guzzle` instead of  ` guzzle/guzzle`. You need upgrade to SDK V3. 

Closing, yet feel free to reopen if you have further questions.

**Comment by GrahamCampbell** [comment]
You should not try to use 3.x tags on guzzlehttp/guzzle since the idea of having two packages is that you can install them both at once, so if you want 3.x, you really do have to use the deprecated package. TBH, I'm not sure why the 3.x tags arn't deleted off the new repo? // cc @mtdowling
