### ISSUE TITLE
Critical Bug on SNS.

### ISSUE THREAD

**Issue by samukt** [aws/aws-sdk-php#1061]
Hello Guys,
AWS recently released the sms directly to phone number, right?

But there is a problem in PHP SDK.

Look at Javascript SDK: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SNS.html#publish-property
*"If you don't specify a value for the TopicArn parameter, you must specify a value for the PhoneNumber or TargetArn parameters."*

PHP doesn't have this option.
In PHP you must fill TargetArn or TopicArn, there is no *PhoneNumber*.
http://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.Sns.SnsClient.html#_publish

*I'm using the code:*
```
<?php
	require_once(ROOT.'/sdks/aws.phar');
	use Aws\Common\Credentials\Credentials;
	use Aws\Sns\SnsClient;

	class sms{
		public function __construct($con='default'){
			$this->client = SnsClient::factory(ANILHA_KEYS['amazon_array']);
		}
		public function publish(){
			$result = $this->client->publish(array(
				'PhoneNumber' => '+5551924565039',
				'Message' => 'string',
				'MessageStructure' => 'DefaultSMSType',
				'MessageAttributes' => array(
					'AWS.SNS.SMS.SMSType' => array('StringValue'=>'Promotional','DataType'=>'String'),
					'"AWS.SNS.SMS.SenderID' => array('StringValue' => "mySenderID", 'DataType' => 'String')
				),
			));
			return $result;
		}
	}
```

*Resulting in:* 
```
Fatal error: Uncaught exception 'Aws\Sns\Exception\SnsException' with message 'Error executing "Publish" on "https://sns.us-west-2.amazonaws.com"; AWS HTTP error: Client error: `POST https://sns.us-west-2.amazonaws.com` resulted in a `400 Bad Request` response: <ErrorResponse xmlns="http://sns.amazonaws.com/doc/2010-03-31/"> <Error> <Type>Sender</Type> <Code>InvalidPara (truncated...) InvalidParameter (client): Invalid parameter: TopicArn Reason: Both TopicArn and TargetArn specified. Use only one or the other. - <ErrorResponse xmlns="http://sns.amazonaws.com/doc/2010-03-31/"> <Error> <Type>Sender</Type> <Code>InvalidParameter</Code> <Message>Invalid parameter: TopicArn Reason: Both TopicArn and TargetArn specified. Use only one or the other.</Message> </Error> <RequestId>d829fab8-ccfd-5ca2-ba46-aaa57feec378</RequestId> </ErrorResponse> ' GuzzleHttp\Exception\ClientException: Client error: `POST https://sns.us-west-2.amazonaws.com` resulted in a `400 Bad Request` response: <ErrorResponse xmlm in phar:///var/www/html/master/sdks/aws.phar/Aws/WrappedHttpHandler.php on line 159
array(4) { ["type"]=> int(1) ["message"]=> string(1024) "Uncaught exception 'Aws\Sns\Exception\SnsException' with message 'Error executing "Publish" on "https://sns.us-west-2.amazonaws.com"; AWS HTTP error: Client error: `POST https://sns.us-west-2.amazonaws.com` resulted in a `400 Bad Request` response: Sender InvalidPara (truncated...) InvalidParameter (client): Invalid parameter: TopicArn Reason: Both TopicArn and TargetArn specified. Use only one or the other. - Sender InvalidParameter Invalid parameter: TopicArn Reason: Both TopicArn and TargetArn specified. Use only one or the other. d829fab8-ccfd-5ca2-ba46-aaa57feec378 ' GuzzleHttp\Exception\ClientException: Client error: `POST https://sns.us-west-2.amazonaws.com` resulted in a `400 Bad Request` response: string(68) "phar:///var/www/html/master/sdks/aws.phar/Aws/WrappedHttpHandler.php" ["line"]=> int(159) }
```

I lost all day in this before find the error.

**Comment by cjyclaire** [comment]
@samukt May I ask which SDK version is using? This `PhoneNumber` feature comes in since v3.18.22, our api doc [here](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-sns-2010-03-31.html#publish).

The doc link suggests v2, we do maintain SDK v2 with bug fix, yet we no longer provide API feature update for SDK v2.

**Comment by samukt** [comment]
Was the version...

I've downloaded from here: http://docs.aws.amazon.com/aws-sdk-php/v3/guide/getting-started/installation.html

It's working on last version.

**Comment by cjyclaire** [comment]
Thanks for the response, closing, yet please feel free to reopen with further questions :)

**Comment by ismaelirc** [comment]
@samukt It works yet? I've downloaded the v3 version in the same link that you post and use this code 

`$this->sns = SnsClient::factory(array(
                    'region' => 'us-west-2',
                    'version' => 'latest',
                    'credentials' => [
                        'key' => 'key',
                        'secret' => 'secret'
                    ]
        ));
 
        $result = $this->sns->publish(array(
                'PhoneNumber' => '+559999999',
                'Message' => 'string',
                'MessageStructure' => 'DefaultSMSType',
                'MessageAttributes' => array(
                    'AWS.SNS.SMS.SMSType' => array('StringValue'=>'Promotional','DataType'=>'String'),
                    '"AWS.SNS.SMS.SenderID' => array('StringValue' => "mySenderID", 'DataType' => 'String')
                ),
            ));
            return $result;`

and I recive this error:

`Message: Error executing "Publish" on "https://sns.us-west-2.amazonaws.com"; AWS HTTP error: Client error: `POST https://sns.us-west-2.amazonaws.com` resulted in a `403 Forbidden` response: Sender SignatureDo (truncated...) SignatureDoesNotMatch (client): The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`

I already created the IAM user and set de credentials on config array.

**Comment by Stafox** [comment]
@ismaelirc Did you find a reason why it happened? I face the same issue.

**Comment by ismaelirc** [comment]
Hi, Stas. I did not find the reason. I configured the AIM user again, I
changed the secret and key and works.

But I really wanna know whats was happen...

Em ter, 26 de set de 2017 às 13:51, Stas Kuryan <notifications@github.com>
escreveu:

**Comment by Stafox** [comment]
Thanks, I found a reason. The problem was in secret key. I added an extra symbol to it by mistake.

**Comment by ismaelirc** [comment]
Ok!

Em ter, 26 de set de 2017 às 16:03, Stas Kuryan <notifications@github.com>
escreveu:
