### ISSUE TITLE
Php Yii framework error

### ISSUE THREAD

**Issue by imadige** [aws/aws-sdk-php#1063]
include(Throwable.php): failed to open stream: No such file or directory 
var/www/html/organizetedarik/vendor/aws/aws-sdk-php/src/RetryMiddleware.php(212): class_exists()

**Comment by mtdowling** [comment]
This should have been fixed in a recent version. Have you updated to the latest version of the SDK?

**Comment by cjyclaire** [comment]
Closing, yet feel free to reopen if you have further questions.
