### ISSUE TITLE
php5.6.24 and aws sdk 3.18.37 putobject not working 

### ISSUE THREAD

**Issue by sureshcsk** [aws/aws-sdk-php#1064]
Hi.

Created a Folder called s3 and done the following inside the s3 folder
1.Installed Composer
2.Installed aws sdk using composer.
3. Set the composer
{
    "require": {
        "aws/aws-sdk-php": "3.*"
    }
}
but the path of Sdk.php of aws sdk is in 
/var/www/html/s3/vendor/aws/aws-sdk-php/src/

4.Upload file file to Mumbai Region ap-south-1
$s3 = new Aws\S3\S3Client([
		'key'=> $config['s3']['key'],
		'secret' => $config['s3']['secret'],
		'region' =>$config['s3']['region'],
		'version' => $config['s3']['version'],
		'signature' => $config['s3']['signature']
	]);
echo "after s3 client";
 $result = $s3->putObject(array(
		'Bucket' => 'my-mumbai-bucket',
    	'Key'    => 'data.txt',
    	'Body'   => 'Hello!',
    	'ACL' => 'public-read'
    	));
echo "after putobject";

**Not able to putobject and there is no echo  after putobject;**
**Also logging the log file in S3. Not able to fix.**

thanks
suresh

**Comment by cjyclaire** [comment]
@sureshcsk I just tested V3.18.37 and couldn't reproduce issue with `putObject()` in `ap-south-1`.

>but the path of Sdk.php of aws sdk is in ...

This file path looks good to me, is there any concerns with that?

>Not able to putobject and there is no echo after putobject; ...

Is there any error message or exceptions thrown? Could you double check that the bucket is available and your client is initialized without problem?

Using same configuration parameters as your `putObject`, I can call `putObject` and receive expected response.

**Comment by sureshcsk** [comment]
@cjyclaire 
Thanks for the reply.No concerns about the path.
There is no error message shown after the putobject is called.
How to check whether the client is initialized or not.We also used try and catch for the putobject,but no error is caught.
Bucket exits in the S3 and bucket permission is Any AWS Authenticated User,Everyone.
Thanks
suresh

**Comment by worldlyjohn** [comment]
make sure you have permission for both PutObject and PutObjectAcl

**Comment by sureshcsk** [comment]
@worldlyjohn 
I have permission for list,upload,delete.
Please check the attachment 
![s3permission](https://cloud.githubusercontent.com/assets/1390933/17518657/c5351f6c-5e83-11e6-91d0-f069a4b938a9.png)

**Comment by cjyclaire** [comment]
@sureshcsk Could you try to `var_dump()` the response for `PutObject`? Does the response make sense?

**Comment by sureshcsk** [comment]
@cjyclaire
Thanks for reply. 

Done var_dump(s3Client(.....)); 
For s3Client Worked. 
Also tried to var_dump($s3->putobject(array(....)));
Nothing displayed.Empty screen.

**Comment by cjyclaire** [comment]
@sureshcsk Are you suggesting `var_dump($result)` gives an empty array?
Could you try add `'debug' => true` in S3 Client configuration to see what's going on wire?

**Comment by sureshcsk** [comment]
@cjyclaire  All your great support appreciated.
I made a mistake with composer.
I installed the composer twice.
```
Installed the composer from https://getcomposer.org/download/ 
 ```
and again installed the composer from 
```
Install Composer
 curl -sS https://getcomposer.org/installer | php
```
Today created a new ec2 instance.Installed the composer only once from composer page directly and installed the aws-sdk-php.
Now able to put the object in S3 with no issues.
Once again great thanks for help and time.
Thanks
suresh

**Comment by sureshcsk** [comment]
@cjyclaire 
I got fixed because I installed the sdk under the html folder in ec2 aws linux.
When again tried to create new instance and installed the sdk in html/awsbucket/
The putobject is not working.Not able to var_dump (putrobject).

```
Success Use Case:
Installed sdk under html/
require PHP :
require 'vendor/autoload.php';
```

```
Issue Use case:
Installed sdk under html/awsbucket
require 'awsbucket/vendor/autoload.php';
```
Is there any aws sdk path need to be defined when sdk in html/awsbucket/ ?

**Comment by sureshcsk** [comment]
@cjyclaire 

Getting the below error from wire log :
Error retrieving credentials from the instance profile metadata server. (Client error: `GET http://169.254.169.254/latest/meta-data/iam/security-credentials/` resulted in a `404 Not Found` response: string(90)

**Comment by sureshcsk** [comment]
Hi.

I modified the S3 client initiate 
From 
```
$s3 = new Aws\S3\S3Client([
'key'=> $config['s3']['key'],
'secret' => $config['s3']['secret'],
'region' =>$config['s3']['region'],
'version' => $config['s3']['version'],
'signature' => $config['s3']['signature']
]);
```
To

```
$s3 = new Aws\S3\S3Client([
'credentials' => [
        'key'    => 'my-key',
        'secret' => 'my-secret'
    	],
'region' =>$config['s3']['region'],
'version' => $config['s3']['version'],
'signature' => $config['s3']['signature']
]);
```
