### ISSUE TITLE
Shouldn't the most recent release have been 3.19.0?

### ISSUE THREAD

**Issue by jeremeamia** [aws/aws-sdk-php#1069]
It seems like there is quite a bit of new code in this release. Any reason why the minor version wasn't bumped?

**Comment by cjyclaire** [comment]
@jeremeamia That's a fair point, I'll add some release note around that in next release with a minor version bump, thanks for catching!

**Comment by cjyclaire** [comment]
Closing, new release with minor version bump is out.
