### ISSUE TITLE
S3 Memory leak when encountering 404

### ISSUE THREAD

**Issue by jeroenbaas** [aws/aws-sdk-php#1070]
It seems there is some memory leaking whenever a getObject has a 404 error:

```php
$c_key='KEY HERE';
$c_sec='SECRET HERE';
$bucket='bucketname';
$key_prefix='a prefix like folder where we will write the temp files to within the bucket';

require '../composer/vendor/autoload.php';// > v3.0
use Aws\S3\S3Client;
$options=[
	'version'     => 'latest',
	'region'      => 'us-east-1',
	'credentials' => [
		'key'    => $c_key,
		'secret' => $c_sec,
	],
	'ssl.certificate_authority'=>false,
];
$s3Client=Aws\S3\S3Client::factory($options);

$i=0;
while(true) {
	$i++;
	$keyname=$key_prefix.'/'.$i;

	// Upload data.
	$result = $s3Client->putObject(array(
		'Bucket' => $bucket,
		'Key'    => $keyname,
		'Body'   => openssl_random_pseudo_bytes(1024)
	));

	// Get data
	$t=tempnam(sys_get_temp_dir(),'ZIP');
	$result = $s3Client->getObject(array(
		'Bucket' => $bucket,
		'Key'    => $keyname,
		'SaveAs' => $t
	));

	// try to get something non existent
	try {
		$result = $s3Client->getObject(array(
			'Bucket' => $bucket,
			'Key'    => $keyname.'NONEXISTENT',
			'SaveAs' => $t
		));
	} catch(Exception $e) {
	}
	unlink($t);
	
	// remove temp file
	$result = $s3Client->deleteObject(array(
		'Bucket' => $bucket,
		'Key'    => $keyname
	));

	echo($i.' '.memory_get_usage()."\n");

}
```

result:
1 3812184
2 3903528
3 3994712
4 4085904
5 4177120
6 4268312
7 4359504
8 4450976
9 4542168
10 4633360
11 4724560
12 4815752
13 4906944
14 4998136
15 5089328
16 5180520
17 5271712

Without the block of  9 lines below "try to get something non existent" (the 404 error) the memory usage is stable.

**Comment by cjyclaire** [comment]
@jeroenbaas I couldn't reproduce a memory leak issue with the code you provided, the memory usage looks normal to me. In the `while-true` loop, I can observe memory usage increase and free-up normally.

Do you have garbage collection enabled? I recorded memory usage cycling from 3 MB to 8 MB and then back again after garbage collection completed.
With garbage collection disabled, memory usage will slowly climb until it reaches the [configured](http://php.net/manual/en/ini.core.php#ini.memory-limit) limit and a fatal out-of-memory error is thrown.

May I ask the cURL and Guzzle version that is being used? 
I notice that `ssl.certificate_authority` is configured, are you referencing issue #957 ?
>  'ssl.certificate_authority'=>false,

In v3, you need to do `'scheme' => 'http'` instead.

**Comment by jeroenbaas** [comment]
re: ssl.certificate_authority: I was indeed trying to see if this issue was related to another issue and left that piece in the code while debugging.

If I leave the code running a little longer it indeed seems to reset. I've not come across this behavior before in my own applications. Adding gc_collect_cycles() at each iteration seems to kill the intermediate increase in memory.

**Comment by cjyclaire** [comment]
@jeroenbaas I see, it's not 404 that requires the garbage collection, it's this looping might requires the gc actaully. The pattern observed is similar in regardless of the 404 error.

**Comment by jeroenbaas** [comment]
It does seem that way with me. commenting out the lines 41-48 you get:
1 3620648
2 3620680
3 3620680
4 3620680
5 3620680
6 3620680
7 3620680
8 3620680
9 3620680
10 3620680
11 3620680
12 3620680

i.e. no excess memory used after each iteration. This only happens if you request a non-existent key from S3. So there is definitely something odd with server errors, at least with 404s.

**Comment by cjyclaire** [comment]
@jeroenbaas Interesting. Without the block causing 404 error, I still got that pattern, yet the increasing rate is slower:

1 3685784
2 3712640
3 3738824
4 3766288
5 3792472
6 3818656
7 3844840
8 3871024
9 3897208
10 3929024
11 3955208
12 3981392
13 4007576
14 4033760
15 4059944
16 4086128
17 4112312
18 4138496
19 4164680
20 4194960
 ...

With 404 error:
1 3788472
2 3878232
3 3969240
4 4058968
5 4148696
6 4238424
7 4333784
8 4423512
9 4513240
10 4602968
11 4692696
12 4782424
13 4872152
14 4965976
15 5055704
16 5153624
17 5243352
18 5333080
19 5422808
20 5512536
...

I also tested with http `verify` set to false, which makes no difference to me.

**Comment by jeroenbaas** [comment]
Not sure how I can find out on from my EC2 instance; I thought guzzle was installed by composer when installing the aws-sdk?

**Comment by cjyclaire** [comment]
@jeroenbaas Thanks for the information, looks like you're using a EC2 instance, could you provide the instance type? Then I could try to reproduce the issue there?

**Comment by cjyclaire** [comment]
Closing due to ages, yet please feel free to reopen if you have further question or comments :)

**Comment by jeroenbaas** [comment]
m4.large
