### ISSUE TITLE
Random (and very infrequent) cURL error on Lumen Worker

### ISSUE THREAD

**Issue by mimarcos** [aws/aws-sdk-php#1073]
Hi there, sorry, I am not exactly sure where to best drop this question. I'm working on a large webapp that distributes a lot of a very specific task to SQS. It seems like they are bailing, very intermittently, with a cURL error. Can't be terribly specific unfortunately, but here's the gist:

1) Super quick jobs that pretty much make a single network request (20ms RTT) and update a field in the DB.
2) 16 workers on a single box watching that queue (other lumen workers on DB queue)
3) Just recently started occurring as we shifted more work to this queue (there are requests of 1000 items that need a lookup processed, and previously, some indeterminite portion of these might not need to be queued).

Here are the two cURL error 56 (errno 104) errors that I'm intermittently seeing (at a rate of about .005% of total jobs).

```
[2016-08-19 15:30:31] lumen.ERROR: exception 'Aws\Sqs\Exception\SqsException' with message 'Error executing "SendMessage" on "https://sqs-queue-url"; AWS HTTP error: cURL error 56: SSL read: error:00000000:lib(0):func(0):reason(0), errno 104 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)'
GuzzleHttp\Exception\RequestException: cURL error 56: SSL read: error:00000000:lib(0):func(0):reason(0), errno 104 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /path/to/project/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:187
Next Aws\Sqs\Exception\SqsException: Error executing "SendMessage" on "https://sqs-queue-url"; AWS HTTP error: cURL error 56: SSL read: error:00000000:lib(0):func(0):reason(0), errno 104 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /path/to/project/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:192

[2016-08-19 15:40:49] lumen.ERROR: exception 'Aws\Sqs\Exception\SqsException' with message 'Error executing "ChangeMessageVisibility" on "https://sqs-queue-url"; AWS HTTP error: Client error: `POST https://sqs-queue-url` resulted in a `400 Bad Request` response:
GuzzleHttp\Exception\ClientException: Client error: `POST https://sqs-queue-url` resulted in a `400 Bad Request` response:
 in /path/to/project/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:107
#0 /path/to/project/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
Next Aws\Sqs\Exception\SqsException: Error executing "ChangeMessageVisibility" on "https://sqs-queue-url"; AWS HTTP error: Client error: `POST sqs-queue-url` resulted in a `400 Bad Request` response:
```

Again, these errors are occurring very intermittently and it doesn't seem like they're handled in the worker, in the AWS library, outside of the scope of the job, and it seems to be originating from this Library. Sorry if this is the wrong place to ask this question, but was curious if anyone can make sense of this. The jobs are being lost and causing problems downstream.

Thanks!

**Comment by cjyclaire** [comment]
@mimarcos Thanks for the information. To help us look more into this, could you provide the SDK version, Guzzle version and cURL version being used?

**Comment by mimarcos** [comment]
AWS: 3.18.39, cURL: 7.47.0, and Guzzle: 6.2.1.

I don't know if I'll be able to easily flip that switch for wire log and get you information, at least right now. If it were happening on every request I'd be OK doing this in a test environment, but since the issue seems to pop up so sporadically, and has only presented in production, I'm not sure this is feasible.

**Comment by cjyclaire** [comment]
@mimarcos I see, that's true, openSSL emits error 104 (ECONNRESET) when the connection is reset by a peer host, and this error is happening while cURL is attempting to read data. cURL is therefore surfacing this as a read error (cURL error 56 - CURLE_RECV_ERROR).

It sounds similar to issue #924 here, could you check the openssl version and CA bundle being used with instruction provided there? I couldn't reproduce the issue locally, I understand that it might be tricky to get more details about a failing request, yet it would be very helpful if you could. If you are still consistently seeing this issue, I'd be more that happy to engage the service team on this to see if they could help.

**Comment by cjyclaire** [comment]
Closing due to ages, yet please feel free to reopen with further comments or questions :)

**Comment by mwleinad** [comment]
We are also getting this, very sporadically (once a day). Any new idea of what could be causing this?

Aws\Sqs\Exception\SqsExceptionvendor/aws/aws-sdk-php/src/WrappedHttpHandler.php in parseError
errorError executing "ChangeMessageVisibility" on "https://sqs.us-east-1.amazonaws.com/231142459289/production_general"; AWS HTTP error: Client error: `POST https://sqs.us-east-1.amazonaws.com/231142459289/production_general` resulted in a `400 Bad Request` response: <?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>I (truncated...) InvalidParameterValue (client): Value AQEBTOZkqURu9XzHi+eHL4zOs/KvmSnWo2M2M7bKaetOdH4tEr5FN5+IlEfWDZFNTpYvYf/9A5X27i1oDMljNnxX1b1WabxomWiu6HOCi9y3+o4HlpLuLfUFe5dMJ8NIgjEMLtek0MFwDAYJqK7SyJW3jBpPtxrkdSS71DLg7lh9g4c6JOZSKAsmEbCzs3Qtb1M+IftmLgXLTr289w81KekRwJ6yLpzt+gtsJO00eCT+MvMPWRC6RMmN5cF+75zliMKDEFTqQ2sDEbUIvGpe7ksWrBvlwYup7bffobLaz8XZn2D3tAD7iuxyp4+lv8JZGKFpz0PFD6HJ93f2ql2R61ZGnMzFE/Th7tsmn8/rWipQJnfvGjJ1b0Nfh62HOUY2Q+c2jNMn4/MwfFpWqmDeOZMfuw== for parameter ReceiptHandle is invalid. Reason: Message does not exist or is not available for visibility timeout change. - <?xml version="1.0"?><ErrorResponse xml {clipped}

**Comment by cjyclaire** [comment]
@mwleinad , your error message indicates `InvalidParameterValue`, there appears to be invalid `ReceiptHandle`, could you double that? Should that be `ReceiptHandler` instead? Are you also seeing the cURL error there? Looks like your problem is different.
