### ISSUE TITLE
CouldNotCreateChecksumException doesn't extend AwsException

### ISSUE THREAD

**Issue by mcfedr** [aws/aws-sdk-php#1074]
This prevents it from being caught when it should have been, or in the case of my `CommandPool`, it causes PHP to crash because it cannot be passed to my callback with the signature

    'rejected' => function (
        AwsException $reason,
        $iterKey,
        PromiseInterface $aggregatePromise
    )

    Argument 1 passed to {closure}() must be an instance of Aws\Exception\AwsException

**Comment by cjyclaire** [comment]
@mcfedr `AwsException` is expected to represent an exception that is thrown when a AWS command fails at runtime with a failed request. Its context is part of design decision made by different AWS service models as you can see [here](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Exception.AwsException.html). Then, `CouldNotCreateChecksumException` is an exception thrown when the request body is not seekable, where the request should fail immediately and should not be made to server-side until the issue has been fixed.

In working around your case, you could check more general exception first, then checking if the exception is an `Aws\Exception` later.

**Comment by cjyclaire** [comment]
Closing due to ages, yet please feel free to reopen if you have further question or comments :)

**Comment by mcfedr** [comment]
I'm being a bit slow, It seems a shame there isn't a top-of-tree exception for all things that can go wrong in Aws SDK, this is a very common pattern in libraries, and very helpful. In the case where I noticed this problem, it didn't matter to me whether a request was made and failed, or this other problem, I just want to catch something that tells me the SDK couldn't do what I asked it to do.

Its nice not to have to just catch `\Exception` because that can have the side effect of catching other exceptions that really were unexpected.
