### ISSUE TITLE
Using the SDK for CloudSearch is a pain

### ISSUE THREAD

**Issue by assembledadam** [aws/aws-sdk-php#1081]
A snippet from a call like this:

```
$cloudSearchClient->search([
    'query' => "(phrase field=_id 'some-permalink')",
    'queryParser' => 'structured',
])->get('hits');
```

Gives me this result:

```
array:2 [
  "id" => "some-permalink"
  "fields" => array:10 [
    "category" => array:1 [
      0 => "screenshots"
    ]
    "permalink" => array:1 [
      0 => "some-permalink"
    ]
    "date" => array:1 [
      0 => "2016-06-21T11:25:22Z"
    ]
    "site_permalink" => array:1 [
      0 => "videogamer"
    ]
    "created_at" => array:1 [
      0 => "2016-06-21T11:24:40Z"
    ]
    "subtype" => array:1 [
      0 => "images"
    ]
    "keywords" => array:2 [
      0 => "dead by daylight"
      1 => "pc"
    ]
    "name_en" => array:1 [
      0 => "Dead by Daylight Screenshots"
    ]
    "type" => array:1 [
      0 => "content"
    ]
    "body_en" => array:1 [
      0 => "Check out these screenshots from Dead by Daylight"
    ]
  ]
]
```

Why on earth is every result field an array? Even single value fields (like INT fields) return an array with a single value, which is extremely unhelpful.  

It wouldn't be SO bad if you could put this straight back into CloudSearch with uploadDocument(), but you can't - the API complains that array types are not accepted for fields with single values, e.g.: `"Field "category" must have array type to have multiple values".`

**Comment by cjyclaire** [comment]
@assembledadam Appreciated your feedback, it's true that response organized in array format, it's a general model design decision. So, may I ask for more information before we move further to make the API experience better? 
>  put this straight back into CloudSearch with uploadDocument()

May I ask more about this behavior? Are you expecting using the result from search to `'document'` field in [`UploadDocuments`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-cloudsearchdomain-2013-01-01.html#uploaddocuments) as json format?

Is this use case the main reason why you find the array unhelpful?

**Comment by assembledadam** [comment]
It isn't helpful because you are returning an array for fields that could only possibly have a single value - the array datatype for values that are scalar or dates is not suitable. When trying to extract the results, how can I tell if the field is supposed to contain one or many values?  Here's my usecase, which I would expect is fairly common:

AWS CloudSearch does not have an 'update' operation, you can only 'add' and 'delete'. To have the same effect as an update, you have to use the 'add' operation with an ID which overwrites the existing document.

The gotcha here is that say you need to update a field in your document - by running 'add' with only the field you want to update, all the other fields are deleted (the whole document is entirely replaced).

So in order to update a value, we need to get the data from the original document. So I query CloudSearch.

Consider the following search index fields:

```
name: text
added_on: date
aliases: text-array
```

When I query the data, I would get back something like this:

```
array:2 [
  "id" => "some-permalink"
  "fields" => array:3 [
    "name" => array:1 [
      0 => "foo"
    ]
    "permalink" => array:1 [
      0 => "2016-06-21T11:25:22Z"
    ]
    "aliases" => array:1 [
      0 => "bar",
      1 => "baz
    ]
```

As you can see from the original post, this is not compatible with the format the SDK expects for 'add' operations, and generally isn't useful for anything for the reasons above.

So to make it useful, we must first reconstruct the document, figuring out a way to distinguish fields that have multiple values to fields that have just one, then update the value, and then 'add' the document.

It's of course impossible to determine if the field expects single or multiple values, so the best we can do is extract the data with this rather hacky snippet: 

```
$document = [];

foreach ($result['hit'][0]['fields'] as $field => $value) {
    if (count($value) == 1) {
        $document[$field] = $value[0];
    } else {
        $document[$field] = $value;
    }
}
```

This would be avoided if you only returned arrays for fields that could contain multiple values.

**Comment by cjyclaire** [comment]
@assembledadam Appreciate the clarification with details, I'll tag it as a feature request in our backlog. Since it's not appropriate for SDK to change the raw response, it's fair that `CloudSearch` client could have a helper formatter that handles the issue. Does that sounds good to you?

**Comment by assembledadam** [comment]
I haven't looked into the SDK code so I didn't realise it was the raw API response - that's not great!

It means that the SDK has no additional scope to identify the datatype of the fields over the SDK consumer, so the approach I outlined above to 'fix' the output is probably the best way.

Yes, in lieu of making the API output more useful (a different team I guess), a formatter helper would be great, thanks for the quick reply.  I could create this and submit a pull request but it's crunchtime on a project I'm working on at the moment, so would be later on this year.

**Comment by jaygurnani** [comment]
This is still an issue and I am currently using the .NET v3.3.0.0 SDK. I'm calling Search() using the AmazonCloudSearchDomainClient() and getting single valued items back in an array. This means it is then impossible to upload the exact same item into another domain easily. Is there an ETA for when this will be fixed?
