### ISSUE TITLE
composer.json requires non exstistent version of guzzlehttp/psr7

### ISSUE THREAD

**Issue by EagleEyeJohn** [aws/aws-sdk-php#1084]
There are no 1.3.x versions of  guzzlehttp/psr7, so the following fails

`
Problem 1
    - Installation request for aws/aws-sdk-php dev-master -> satisfiable by aws/aws-sdk-php[dev-master].
    - aws/aws-sdk-php dev-master requires guzzlehttp/psr7 ~1.3.1 -> no matching package found.
`

[https://github.com/guzzle/guzzle/releases?after=v2.0.2](https://github.com/guzzle/guzzle/releases?after=v2.0.2)

**Comment by cjyclaire** [comment]
@EagleEyeJohn [here](https://github.com/guzzle/psr7/releases/tag/1.3.1) is `guzzlehttp/psr7`.
