### ISSUE TITLE
Invalid parameter on CognitoIdentityProviderClient::listUsers()

### ISSUE THREAD

**Issue by jonshilton** [aws/aws-sdk-php#1088]
Hi,

I'm getting an InvalidParameterException when executing the following code:

```php
$client = new Aws\CognitoIdentityProvider\CognitoIdentityProviderClient($config)
$result = $client->listUsers(
  array(
    'AttributesToGet => array('custom:attr1'),
    'Filter' => 'foo',
    'UserPoolId' => 'myuserpoolid'
  )
);
```

Following error occurs: 

Error executing "ListUsers" on "https://cognito-idp.eu-west-1.amazonaws.com"; AWS HTTP error: Client error: POST https://cognito-idp.eu-west-1.amazonaws.com resulted in a 400 Bad Request response:
{"__type":"InvalidParameterException","message":"Error while parsing filter."}
 InvalidParameterException (client): Error while parsing filter. - {"__type":"InvalidParameterException","message":"Error while parsing filter."}

So the format of my filter param is incorrect. Can anyone tell me what I should be passing in here? The docs just say to use a string.

Thanks.

**Comment by cjyclaire** [comment]
@jonshilton Here is the AWS public guide for the `Filter` string in [Searching for Users Using the ListUsers API](http://docs.aws.amazon.com/cognito/latest/developerguide/how-to-manage-user-accounts.html), it needs to be a filter string of the form "AttributeName Filter-Type "AttributeValue"". Quotation marks within the filter string must be escaped using the backslash (\) character.

**Comment by jonshilton** [comment]
@cjyclaire fantastic, thanks for providing the info.

**Comment by vanerleo** [comment]
var params = {
            UserPoolId: 'XXXXX',
            Filter: 'email="Ashlee-Heathcote@xxxxxxx.com"',
            Limit: 1
        };
return cognitoIdentityServiceProvider.listUsers(params).promise()

throws
```
message: 'Unexpected key \'Filter\' found in params',
  code: 'UnexpectedParameter',
```

While Using command line (cli) with the same filter works

`cognito-idp list-users --user-pool-id xxxxxx --filter 'email="Ashlee-Heathcote@xxxxxx.com"' --limit 1`


running aws-sdk@2.21.0
