### ISSUE TITLE
Use of undefined constant "CURLE_OPERATION_TIMEOUTED" error on systems without CURL

### ISSUE THREAD

**Issue by steenbag** [aws/aws-sdk-php#1089]
Hi all,

I'm attempting to use the SDK on a system with Guzzle, but no CURL support (security restrictions). Guzzle is designed to work with or without CURL, and is working normally for our other web services. Additionaly, CURL is not listed as "not required" in the minimum requirements document (http://docs.aws.amazon.com/aws-sdk-php/v3/guide/getting-started/requirements.html#minimum-requirements).

However, when calling the factory method on any of the AwsClient subclasses, I am receiving this undefined constant error (CURLE_OPERATION_TIMEOUTED). According to the stack trace it is being raised by a call to RetrySubscriber::createCurlFilter() on line 226 of src/Common/ClientFactory.php.

My question is two-fold:
- Is it enough to just define the missing CURL constants? Or does the SDK make further use of the underlying CURL library?
- Is the missing ext-curl dependency in composer.json intentional?

Note: the issue can be worked around by setting "retries" => false in the configuration array passed to the client factory.

Thanks,
Andrew

**Comment by cjyclaire** [comment]
@steenbag May I ask a quick question first? Which version of SDK is used? The documentation you mentioned looks like V3 guide of [what's new](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/migration.html?highlight=guzzle#what-s-new), however the `src/Common/` structure is suggesting SDK V2.

**Comment by steenbag** [comment]
Ah, OK I believe I have found my issue.  I was using "~3.0" as my dependency (originally discovered the issue using "aws/aws-sdk-php": "*"). Based on that, it looks like composer was installing 432d49bc25014b3646512f2822b5e004dcff7f4b, which appears to be fairly outdated. Changing the version dependency to "aws/aws-sdk-php": "3.19.8" seems to fix the issue for me.

Thanks,
Andrew
