### ISSUE TITLE
Update Amazon SES SDK

### ISSUE THREAD

**Issue by bakura10** [aws/aws-sdk-php#109]
I just found this: http://sesblog.amazon.com/post/Tx2H36ZIFTEVXOZ/Goodbye-blacklist-Introducing-the-suppression-list

It appears this feature is not supported in current SDK.

**Comment by PhilETaylor** [comment]
2022 and I cannot find a way in the PHP SDK to list and remove emails from the Suppression List... maybe Im just blind?
