### ISSUE TITLE
Asynchronous request to cloud watch logs  

### ISSUE THREAD

**Issue by lastday154** [aws/aws-sdk-php#1090]
I am writing a function to log input to cloud watch logs.
I want it as fast as possible. Normally I use synchronous request, e.g putLogEvents, currently the time difference is about 40ms. My question is how to speed up my putLogEvents or using putLogEventsAsync instead.

Here is my code

public function writeToCloudWatch($line)
   {
        $microTime = $this->timeProvider->getMicroTime();

        if (!isset($this->nextSequenceToken)){
            $responseModel = $this->client->describeLogStreams([
                'logGroupName' => $this->logGroup,
                'logStreamNamePrefix' => $this->logStream,
            ]);
            $this->nextSequenceToken = $responseModel['logStreams']['0']['uploadSequenceToken'];
        }
        try {
            $responseModel = $this->client->putLogEvents([
                'logGroupName' => $this->logGroup,
                'logStreamName' => $this->logStream,
                'logEvents' => [
                    [
                        'message' => $line,
                        'timestamp' => $microTime,
                    ]
                ],
                'sequenceToken' => $this->nextSequenceToken
            ]);
            if (isset($responseModel['nextSequenceToken'])) {
                $this->nextSequenceToken = $responseModel['nextSequenceToken'];
            }
        } catch (CloudWatchLogsException $e) {
            // We don't want any exception when putLogEvents is not working
        }
    }

**Comment by cjyclaire** [comment]
@lastday154 using [asynchronous request](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/getting-started/basic-usage.html?#asynchronous-requests) would be helpful, you just need to add "Async" and handles [promise](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/promises.html). Could you provide more details about your usage case then we can see where could be enhanced?

If you are looking for deeper dive in `asynchronous request`, #621 is great thread to follow, especially the comments from @mtdowling. Feel free to let me know if you have further questions.

**Comment by mtdowling** [comment]
Sending a request as async in the SDK doesn't magically make it faster unless you are sending other requests concurrently.

You either need to architect your application to utilize an event loop and hook the SDK up through that, queue the request somehow using a faster mechanism like Gearman to do the actual request in a job queue, or you need to block until the request has finished sending.

**Comment by lastday154** [comment]
@cjyclaire . Thanks you for response.
Basically, We are running a online shopping website, and We want all the log writing to cloudwatch logs as fast as possible. The function above just let you upload the log directly to a log stream. So basically you have to get the token, and using putLogEvents to put the log into cloud. 
So if I change the putlogEvent to putLogEventAsync without calling promise->wait().
It is much faster but it does not upload to cloud watch log. like
 public function writeToCloudWatch($line)
    {
        $microTime = $this->timeProvider->getMicroTime();

        if (!isset($this->nextSequenceToken)){
            $responseModel = $this->client->describeLogStreams([
                'logGroupName' => $this->logGroup,
                'logStreamNamePrefix' => $this->logStream,
            ]);
            $this->nextSequenceToken = $responseModel['logStreams']['0']['uploadSequenceToken'];
        }
        try {
            $promise = $this->client->putLogEventsAsync([
                'logGroupName' => $this->logGroup,
                'logStreamName' => $this->logStream,
                'logEvents' => [
                    [
                        'message' => $line,
                        'timestamp' => $microTime,
                    ]
                ],
                'sequenceToken' => $this->nextSequenceToken
            ]);
        } catch (CloudWatchLogsException $e) {
            // We don't want any exception when putLogEvents is not working
        }
    }
So my first question is why we need to call wait to get Async working?
Because if we call wait it seems like Sync.

**Comment by lastday154** [comment]
@mtdowling I am really waiting your response after seeing all the excellent answers.
Kind of admire your talent. Coming back my problem.
I want to log my input directly to a cloud watch log stream AS FAST AS POSSIBLE.
It would be great if you can give me specific code to work with cloudwatch logs.
Here is the code I am using.
    /**
     * @param string $line
     */
    public function writeToCloudWatch($line)
    {
        $microTime = $this->timeProvider->getMicroTime();

        if (!isset($this->nextSequenceToken)){
            $responseModel = $this->client->describeLogStreams([
                'logGroupName' => $this->logGroup,
                'logStreamNamePrefix' => $this->logStream,
            ]);
            $this->nextSequenceToken = $responseModel['logStreams']['0']['uploadSequenceToken'];
        }
        try {
            $promise = $this->client->putLogEventsAsync([
                'logGroupName' => $this->logGroup,
                'logStreamName' => $this->logStream,
                'logEvents' => [
                    [
                        'message' => $line,
                        'timestamp' => $microTime,
                    ]
                ],
                'sequenceToken' => $this->nextSequenceToken
            ]);
            try {
                $result = $promise->wait();
            } catch (CloudWatchLogsException $e) {
                echo $e->getMessage();
            }
            if (isset($result['nextSequenceToken'])) {
                $this->nextSequenceToken = $result['nextSequenceToken'];
            }

        } catch (CloudWatchLogsException $e) {
            // We don't want any exception when putLogEvents is not working
        }
    }

**Comment by cjyclaire** [comment]
@lastday154 I think Michael's write-up explain the approach really well already, so if you are looking for exact detail code examples with `putLogEventsAsync`, you could try something like below:
``` php
// after $token is acquired

$promiseGenerator = function ($total) use ($client, $token) {
    for ($i = 0; $i < $total; $i++) {
        yield $client-> putLogEventsAsync([
            'logGroupName' => "logGroup",
            'logStreamName' => "logStream",
            'logEvents' => [
                [
                    'message' => "...",
                    'timestamp' => "timestamp",
                ]
            ],
            'sequenceToken' => $token
        ]);
    }
};

$fulfilled = function($result) {
    echo 'Got result: ' . var_export($result->toArray(), true) . "\n\n";
};
$rejected = function($reason) {
    echo 'Rejected: ' . $reason . "\n\n";
};

// Create the generator that yields 1000 total promises.
$promises = $promiseGenerator(1000);
// Create a promise that sends 50 promises concurrently by reading from
// a queue of promises.
$each = Promise\each_limit($promises, 50, $fulfilled, $rejected);
// Trigger a wait. Note that if you use an event loop then this is not
// necessary.
$each->wait();
```
Above is the code example for ensuring several promise in flight at any given time. If you are looking for get rid of `wait()`, you can try the code snippet provided by Michael in the second part with cURL, explore Guzzle handler or customize your handler.

Hope this helps.

**Comment by lastday154** [comment]
Hi @cjyclaire . I have implemented the code you share.
But it does not send all of my requests. Instead of sending requests to cloudwatch logs, it only sends first requests.
for ($i=0; $i<50; $i++) {

    $previousTime = microtime();
    $cloudWriter->writeToCloudWatch("hi$i"); //only send "hi0" to cloudwatch

    $currentTime = microtime();
    $interval = $currentTime - $previousTime;
    echo $interval * 1000;
    echo " #$i.\n";

}
it would be great if you give me a online chat time where we can use teamview.

**Comment by cjyclaire** [comment]
@lastday154 thanks for getting back, I'm a bit confused with 
> But it does not send all of my requests. Instead of sending requests to cloudwatch logs, it only sends first requests.

Could you explain why you find that? Are you suggesting the request with the initial token? The code snippet provided needs to be feed with tokens when it changes, it won't magically fetch token for you.

**Comment by lastday154** [comment]
@cjyclaire . Basically, you send asynchronous with the same token, it will only send the first request's data only.

But if you want to get the token, the only way to get it is from promise->wait when using Async, or from nextSequenceToken when using Sync. Either way, it is not truly asynchronous workflow.

`public function writeToCloudWatch($line)
    {
        $microTime = $this->timeProvider->getMicroTime();
        if (!isset($this->nextSequenceToken)) {
            $responseModel = $this->client->describeLogStreams([
                'logGroupName' => $this->logGroup,
                'logStreamNamePrefix' => $this->logStream,
            ]);
            $this->nextSequenceToken = $responseModel['logStreams']['0']['uploadSequenceToken'];
        }
        try {
            for($i=0; $i<10; $i++) {
                $this->client->putLogEventsAsync([
                    'logGroupName' => $this->logGroup,
                    'logStreamName' => $this->logStream,
                    'logEvents' => [
                        [
                            'message' => $line,
                            'timestamp' => $microTime,
                        ]
                    ],
                    'sequenceToken' => $this->nextSequenceToken,
                ]);
            }
        } catch (CloudWatchLogsException $e) {
            // We don't want any exception when putLogEvents is not working
            $e->getMessage().'\n';
        }
        $this->loop->run();
    }`

**Comment by cjyclaire** [comment]
@lastday154, in terms of fetching the token, there is also `describeLogStreamsAsync`, then you use the same approach with that method to ensure several promises in flight in enhancing the concurrency there. 

As I have mentioned, if you don't want to wait for any promise at all, you could follow the advice from thread:

>The SDK is designed to be able to work with any sort of HTTP client. Some clients might use an event loop that you can tick externally, while others might require you to call wait.

>The SDK will use cURL or the PHP stream wrapper by default if you do not configure a custom HTTP handler for the SDK. This is accomplished by using Guzzle by default. However, keep in mind that you can use any HTTP client with the SDK (more on that later).

>If you are using the PHP stream wrapper, then there's no way to send the requests other than to call wait. This is because the PHP stream does not allow concurrent requests.

>When using cURL, you would need to tick the cURL loop in order to asynchronously progress the transfers. Most non-blocking event loops require that they are ticked to progress the transfers. Using a cURL handler with the SDK is no different. Here's how you could use a Guzzle handler that is coupled to cURL to manually tick the cURL event loop:

```php
require 'vendor/autoload.php';

use Aws\Sdk;
use GuzzleHttp\Promise;
use GuzzleHttp\Handler\CurlMultiHandler;
use GuzzleHttp\HandlerStack;

$curl = new CurlMultiHandler();
$handler = GuzzleHttp\HandlerStack::create($curl);
$sdk = new Sdk([
    'http_handler' => $handler,
    'region' => 'us-west-2',
    'version' => 'latest',
]);

$client = $sdk->createS3();
$p1 = $client->listBucketsAsync()->then(function () { echo '-done 1-'; });
$p2 = $client->listBucketsAsync()->then(function () { echo '-done 2-'; });
$aggregate = Promise\all([$p1, $p2]);

// Tick the curl loop manually.
while (!Promise\is_settled($aggregate)) {
    $curl->tick();
}
```
>If you write HTTP handlers for other clients that use an event loop that is ticked automatically (because you are calling run or something on an event loop), then manually ticking an event loop or calling wait is unnecessary.

>Here are a couple examples of creating custom HTTP handlers for the SDK: https://github.com/aws/aws-sdk-php/tree/master/src/Handler. You could create a custom handler to bind the SDK to an event loop of your choice. Here is more information on SDK handlers: http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/handlers-and-middleware.html#creating-custom-handlers

**Comment by lastday154** [comment]
@cjyclaire 
But how can you get the token from describeLogStreamsAsync without calling wait. Because it returns you only promises object, isn't it ?

**Comment by cjyclaire** [comment]
@lastday154 It's true that the promise needs to be resolved first then to fetch result from. Yet how to resolve the promise is up to you. If you don't want to implement another handler, you need to call wait somehow, however, it's feasible to enhance the concurrency in resolving the promise there, which will make it faster.

**Comment by lastday154** [comment]
@cjyclaire , if you could be more specific about how to resolve the promise with describeLogStreamAsync so that it can directly fetch the token to putLogEventsAsync, my problem will be solved immediately. 
Here is the code I am using but cannot directly do the fetching.
```
public function writeToCloudWatch($line)
    {
        $microTime = $this->timeProvider->getMicroTime();
        if (!isset($this->nextSequenceToken)) {
            $responseModel = $this->client->describeLogStreams([
                'logGroupName' => $this->logGroup,
                'logStreamNamePrefix' => $this->logStream,
            ]);
            $this->nextSequenceToken = $responseModel['logStreams']['0']['uploadSequenceToken'];
        }
        try {
            for($i=0; $i<10; $i++) {
                $this->client->putLogEventsAsync([
                    'logGroupName' => $this->logGroup,
                    'logStreamName' => $this->logStream,
                    'logEvents' => [
                        [
                            'message' => $line,
                            'timestamp' => $microTime,
                        ]
                    ],
                    'sequenceToken' => $this->nextSequenceToken,
                ]);
            }
        } catch (CloudWatchLogsException $e) {
            // We don't want any exception when putLogEvents is not working
            $e->getMessage().'\n';
        }
        $this->loop->run();
    }
```

**Comment by cjyclaire** [comment]
@lastday154 Okay, the initial way you implemented without `Async` works with no problem, you want to make it faster. You have to make 2 API calls: `describeLogStreams`then `putLogEvents` to achieve that. To make each call faster, you can use the approach described above to enhance the concurrency for `Asyn` calls. Something look like this:

```php
if (!isset($token)) {
    $result = promiseResolveHelper(1000, 50, $client, 'describeLogStreamsAsync', [
        'logGroupName' => $logGroup,
        'logStreamNamePrefix' => $logStream,
    ]);
    $token = $result['logStreams']['0']['uploadSequenceToken'];
}
try {
    $response = promiseResolveHelper(1000,50, $client, 'putLogEventsAsync', [
        'logGroupName' => $logGroup,
        'logStreamName' => $logStream,
        'logEvents' => [
            [
                'message' => $line,
                'timestamp' => $microTime,
            ]
        ],
        'sequenceToken' => $token
    ]);
    if (isset($response['nextSequenceToken'])) {
        $token = $response['nextSequenceToken'];
    }
} catch (CloudWatchLogsException $e) {
    // do sth
}

function promiseResolveHelper($total, $concurrency, $client, $command, $params) {
    $promiseGenerator = function ($total) use ($client, $command, $params) {
        for ($i = 0; $i < $total; $i++) {
            $cmd = $client->getCommand($command, $params);
            yield $client-> execute($cmd);
        }
    };
    $fulfilled = function($result) {
        return $result;
    };
    $rejected = function($reason) {
        echo 'Rejected: ' . $reason . "\n\n";
        // You could throw exception here
    };

    $promises = $promiseGenerator($total, $command, $params);
    $each = Promise\each_limit($promises, $concurrency, $fulfilled, $rejected);
    return $each->wait();
}
```

Above code gives the idea there, you could do more refractor work to make it cleaner.

**Comment by cjyclaire** [comment]
Closing due to ages, feel free to reopen with further comments or questions.
