### ISSUE TITLE
Set custom URL

### ISSUE THREAD

**Issue by praditha** [aws/aws-sdk-php#1096]
Hello,
I'm sorry if this question is out of scope.

Currently I'm using Laravel 5.2 and the latest version of aws-sdk-php-laravel.
But I'm not using S3 from AWS, I use [CEPH](http://ceph.com/ceph-storage/) as my storage.

Based on this [tutorial](http://docs.ceph.com/docs/jewel/radosgw/s3/php/), I can use aws sdk to connect to my storage, but on that tutorial, it still use the SDK version 1. On that version we can see the base URL can be changed ( `$Connection->set_hostname($HOST);` ).
But I have no idea how to change it on the latest version and by default the base URL is `https://s3.us.amazonaws.com/s3://test`
I wanna change for example to be like this: `https://mycephstorage.com/s3://test`

can you guys please help me how to change the base URL..?

Thanks.

**Comment by cjyclaire** [comment]
@praditha s3 bucket URL still follows the path style. It's not changed, I believe aws/aws-sdk-php-laravel#109 is the same one, I'll close that one and track the issue here.

**Comment by praditha** [comment]
@cjyclaire , I mean I wanna change the `https://s3.us.amazonaws.com/s3://test` to my CEPH storage e.g. `https://mycephstorage.com/s3://test`

**Comment by cjyclaire** [comment]
@praditha Okay, thanks for editing the question to make it clear, I think this is a issue or question that you need to open with `CEPH` instead of us. Looks like they have the integration interface with `aws-sdk-php` on their side. There is nothing that `aws-sdk-php` could help to change that.

**Comment by cjyclaire** [comment]
Closing, since this is not a issue that could be fixed or configured from SDK side. AWS SDK will not help maintain those integration interfaces built upon us. Thanks.
