### ISSUE TITLE
segmentation fault when try to use sdk with symfony

### ISSUE THREAD

**Issue by nicolae-stelian** [aws/aws-sdk-php#1098]
In aws-sdk-php/src/TraceMiddleware.php function str line 254  and 
in aws-sdk-php/src/functions.php line 251 the 
`ob_start();`
` var_dump($input);`
Generate segmentation fault in symfony (symfony commands).
I create a test project that generate the error in https://github.com/nicolae-stelian/sf-sqs .
Please check if is posible to change ob_start to var_export or print_r.

Thank'you.

**Comment by cjyclaire** [comment]
@nicolae-stelian Thanks for reporting this, taking a look

**Comment by cjyclaire** [comment]
@nicolae-stelian may I ask a quick question before moving forward, which php version is used? Also, are you using [`aws-sdk-php-zf2`](https://github.com/aws/aws-sdk-php-zf2) ?

**Comment by nicolae-stelian** [comment]
Hi @cjyclaire.
I don't use aws-sdk-php-zf2  ( I use symfony and not zend framework). I install the library using composer in an symfony 3.1 project:
`composer.phar require aws/aws-sdk-php`

This is the code that generate the error https://github.com/nicolae-stelian/sf-sqs/blob/master/src/AppBundle/Command/SqsCommand.php


My php version is:
```
PHP 7.0.11-1+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.11-1+deb.sury.org~trusty+1, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0RC2, Copyright (c) 2002-2015, by Derick Rethans
```

My linux distribution is:
```
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.3
DISTRIB_CODENAME=rosa
DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

```

**Comment by cjyclaire** [comment]
@nicolae-stelian Interestingly, I clone you repo and couldn't reproduce the error.
My PHP version:
```
PHP 7.0.11 (cli) (built: Sep 22 2016 13:53:33) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```
My OS:
```
OS X 10.11.6
Kernel Version: Darwin 15.6.0
```
I'll try an Linux instance to see if I could reproduce it there.
Also, just as a reminder, you need to be really careful with the credential information in the script. Since I receive `session_token` expire, so I assume it's not the real credential bunds to your AWS account.

**Comment by cjyclaire** [comment]
@nicolae-stelian I just tried in ubuntu environment with your `SQS` code and still couldn't reproduce the issue there. It would be helpful if you could provide some error log with SDK specific behavior related. Then I can see how can I help from there.

**Comment by nicolae-stelian** [comment]
@cjyclaire I test and record the error. Please take a look https://youtu.be/VaXlLOoBVjA .
I will investigate more deeply this error.  I will check my environment and I will try to reproduce error in a virtual machine. After this I will send you more details.

**Comment by nicolae-stelian** [comment]
@cjyclaire apology for answering late. The problem is the xdebug extension. I don't know if is really a problem of sdk or xdebug. (In production environment nobody use xdebug). If you want to see my tests: https://youtu.be/yPdYWSqV6pE . 
Thank you very much for your time.

**Comment by cjyclaire** [comment]
No problem at all, thanks for getting back and providing information here ;)
