### ISSUE TITLE
Connection refused error

### ISSUE THREAD

**Issue by scottopolis** [aws/aws-sdk-php#1100]
I just started getting this error when using createUser():

Error executing "CreateUser" on "http://iam.amazonaws.com"; AWS HTTP error: cURL error 7: Failed connect to iam.amazonaws.com:80; Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

I am sending from an http site for development, so I have 'scheme' => 'http' set.  I have tried creating new credentials, updating the SDK to the latest release, changing the values I send, to no avail.

Calls to other services such as SNS using the same curl commands and AWS credentials work fine, it just seems to be the Iam service. 

My code worked a month ago and I didn't change anything, did something change in the API?

Thanks!

**Comment by cjyclaire** [comment]
@scottopolis The problem is with setting `http` at [scheme](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#scheme), for IAM, either their protocol or endpoints are `HTTPS` only. May I ask are you suggesting you succeed in using `http` previously?

**Comment by scottopolis** [comment]
Yes I was able to use http before successfully, this has only been in the last week or so that it stopped working.

**Comment by cjyclaire** [comment]
@scottopolis Hmm, interesting, IAM models haven't been updated for 2 months. May I ask the version that this works?

**Comment by scottopolis** [comment]
The SDK files were version 3.19.4, I also just updated to the latest and it didn't make a difference.  My API calls all use 'latest' for version.

**Comment by cjyclaire** [comment]
@scottopolis I just verified with several version of SDK, old and new, this won't succeed as well. IAM service doesn't change in the time frame you have mentioned. Different service has different protocol constraints, and I believe IAM service requires `https`. Also, I just verified with Ruby SDK, they won't allow this as well.

So, as you have mentioned:
> I am sending from an http site for development, so I have 'scheme' => 'http' set.

The `scheme` here is the URI scheme to use when connecting to AWS service instead of your development site, are you suggesting that your developing environment doesn't allow that? Could you provide more information there? Then I can see how can help.

**Comment by scottopolis** [comment]
Everything works fine if I use https, so I guess I'll just do that.

My only question would be: is it possible to make API calls without https, like from a development site? Is there a setting to allow that?

Thanks

**Comment by cjyclaire** [comment]
@scottopolis Good to know, so [`endpoint`](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#endpoint) and [`scheme`](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#scheme) are those parameters to change endpoint URL. Yet, there is a [list](http://docs.aws.amazon.com/general/latest/gr/rande.html) of endpoints supported by AWS services. You are on the right track to configure that, yet service varies in protocols and endpoints. If you are trying to apply different mechanism to different services, you could take a look at [`endpoint_provider`](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#endpoint-provider).

**Comment by scottopolis** [comment]
I'll take a look at that, thanks for your help!

**Comment by aalvarezcoco** [comment]
I am trying to create a user in for amazon chime and I get Error executing "CreateUser" on "https://service.chime.aws.amazon.com/accounts/355110919357/users?operation=create"; AWS HTTP error: Client error: `POST https://service.chime.aws.amazon.com/accounts/355110919357/users?operation=create` resulted in a `400 Bad Request` response: ◀
    {"Code":"BadRequest","Message":"Service received a bad request","RequestId":"9611d939-0cd9-4442-92b9-8b4de640f3dd","Reso (truncated...)
     BadRequestException (client): Service received a bad request - {"Code":"BadRequest","Message":"Service received a bad request","RequestId":"9611d939-0cd9-4442-92b9-8b4de640f3dd","Resource":null} ◀
