### ISSUE TITLE
All OpsWorks commands not working using api.

### ISSUE THREAD

**Issue by vrkansagara** [aws/aws-sdk-php#1104]
I am having following errors while connecting using library but while using cli it's works fine.

`Error executing "**DescribeLayers**" on "http://opsworks.us-east-1.amazonaws.com"; AWS HTTP error: cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

is there anything changed here?

the debug back trace
`
* Rebuilt URL to: http://opsworks.us-east-1.amazonaws.com/ * Found bundle for host opsworks.us-east-1.amazonaws.com: 0x5576932fe660 [serially] * Connection 2 seems to be dead! * Closing connection 2 * Hostname opsworks.us-east-1.amazonaws.com was found in DNS cache * Trying **IP**... * Connected to opsworks.us-east-1.amazonaws.com (**IP**) port 80 (#3) > POST / HTTP/1.1 Host: opsworks.us-east-1.amazonaws.com X-Amz-Target: OpsWorks_20130218.DescribeLayers Content-Type: application/x-amz-json-1.1 aws-sdk-invocation-id: c0f8a3af1841e66326460786a7be5395 aws-sdk-retry: 3/61 X-Amz-Date: 20161012T102530Z Authorization: AWS4-HMAC-SHA256 Credential=[KEY]/20161012/us-east-1/opsworks/aws4_request, SignedHeaders=aws-sdk-invocation-id;aws-sdk-retry;host;x-amz-date;x-amz-target, Signature=[SIGNATURE] User-Agent: aws-sdk-php/3.19.13 GuzzleHttp/6.2.1 curl/7.47.0 PHP/7.0.8-0ubuntu0.16.04.3 Content-Length: 102 * upload completely sent off: 102 out of 102 bytes * Empty reply from server * Connection #3 to host opsworks.us-east-1.amazonaws.com left intact <- Leaving step sign, name 'signer' ----------------------------------- error.instance changed from 000000005fb1e3820000000079bff221 to 000000005fb1e3b70000000079bff221 error.request.instance changed from 000000005fb1e39c0000000079bff221 to 000000005fb1e3810000000079bff221 error.request.headers.aws-sdk-retry.0 changed from 2/60 to 3/61 error.request.headers.Authorization.0 changed from AWS4-HMAC-SHA256 Credential=[KEY]/20161012/us-east-1/opsworks/aws4_request, SignedHeaders=aws-sdk-invocation-id;aws-sdk-retry;host;x-amz-date;x-amz-target, Signature=[SIGNATURE] Inclusive step time: 0.31069397926331 <- Leaving step sign, name 'retry' ---------------------------------- no changes Inclusive step time: 0.31213212013245 <- Leaving step sign, name 'invocation-id' ------------------------------------------ no changes Inclusive step time: 1.1296198368073 <- Leaving step build, name '' ------------------------------ no changes Inclusive step time: 1.130245923996 <- Leaving step build, name 'builder' ------------------------------------- no changes Inclusive step time: 1.1308441162109 <- Leaving step validate, name 'validation' ------------------------------------------- no changes Inclusive step time: 1.1320819854736 Error executing "DescribeLayers" on "http://opsworks.us-east-1.amazonaws.com"; AWS HTTP error: cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
`

**Comment by cjyclaire** [comment]
@vrkansagara Nothing changes in OpsWorks recently, I just test `describeLayers` and couldn't reproduce the issue there. May I ask are you suggesting those errors suddenly happened with `Opsworks` only? Could you double check your local network? Is there any proxy issues?

**Comment by vrkansagara** [comment]
I have double checked with the api and debug log still getting the same error and there is no proxy issue as far as I have already concern this issue with my head and he is already double checked with it.

**Comment by cjyclaire** [comment]
@vrkansagara Looks like you are using `http` instead of `https`, did you set [`scheme`](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#scheme) to `http` on purpose? Not all service allows for `HTTP`, refer protocol information [see](http://docs.aws.amazon.com/general/latest/gr/rande.html#opsworks_region).

**Comment by vrkansagara** [comment]
oh yes it's working find but don't know why still there is empty replay from the server even if there is stack and layers are there.

**Comment by vrkansagara** [comment]
@cjyclaire  It's working fine. Here is little suggestion from my side.
We require to push some message in exception using that correct your `endpoint` or say something use `http` or `https` so developer  quickly got notified there is something wrong with code base.

Also if later on endpoint changed it will also see documentation and correct it.

It will also helpfull for a developer to save 24 to 36 hours from the community support.

my suggestion as bellow

if there is wrong with code base  the response from aws-sdk would be

```
{
.....
'ref-link': 'https://docs.aws.amazon.com/general/latest/gr/rande.html'
....
}

```   


I am having too much load with work otherwise I will generate PR against this issue and improve it.

if you need more suggestion let me ping thanks :+1:  @cjyclaire

**Comment by cjyclaire** [comment]
@vrkansagara Appreciate the feedback, I'll track it in our backlog as a feature request, thank you. :)
