### ISSUE TITLE
react/promise

### ISSUE THREAD

**Issue by sm2017** [aws/aws-sdk-php#1105]
How can I have `\React\Promise` instead of `\GuzzleHttp\Promise\Promise` for Async methods?
https://github.com/reactphp/promise

Sometimes I have to throw exception on `$onFulfilled` or `$onRejected` callbacks , and  `\GuzzleHttp\Promise\Promise` will forward it as rejected promise , I dont want this behavior , sometimes I want to throw exception and it must be uncaught (So `fatal error` will be occurred or I can have a uncaught exception handler )

I think the solution is `\React\Promise` and it's `done()` function https://github.com/reactphp/promise#done-vs-then

1- How can I force  Async methods return `\React\Promise`
2- How can I throw uncaught exception in `\GuzzleHttp\Promise\Promise`  `$onFulfilled`

**Comment by cjyclaire** [comment]
@socketman2016 
> 1- How can I force Async methods return \React\Promise

You could configure [`handler`](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#handler) option per client to change it to a `React` handler instead of a guzzle one.

> 2- How can I throw uncaught exception in \GuzzleHttp\Promise\Promise $onFulfilled

If there is exception or error thrown, it won't be wrap into a `fulfilled promise`, it will be wrapped in a `rejected promise`. More details about promise [see](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/promises.html).

Hope these helps

**Comment by socketman2016** [comment]
Before asking question , I change handler in this way but Async methods always return ```\GuzzleHttp\Promise\Promise``` (Also some errors ocuured)

I extends ```\GuzzleHttp\Handler\CurlMultiHandler``` and override __invoke
```php
    public function __invoke(RequestInterface $request, array $options)
    {
        $easy = $this->factory->create($request, $options);
        $id = (int) $easy->handle;

        $promise = new \React\Promise\Promise(
            [$this, 'execute'],
            function () use ($id) { return $this->cancel($id); }
        );

        $this->addRequest(['easy' => $easy, 'deferred' => $promise]);

        return $promise;
    }
```

Can you show me how can I change handler for ```\Aws\S3\S3Client``` to do this?

**Comment by cjyclaire** [comment]
@socketman2016 Apology for rely late on this, good to know that you tried it at first place. Reading your issue opened at `reactphp\promise`, looks like you are having problems with surfacing exceptions? Since you are mentioning `Async` calls in particular, are you trying to use event loop like #901 ? You might also want to have a look at [`react-guzzle-psr7`](https://github.com/WyriHaximus/react-guzzle-psr7).

**Comment by socketman2016** [comment]
I try ```react-guzzle-psr7``` but any Async method returns ```GuzzleHttp\Promise\Promise```  
for example there is no ```done()``` function

If you run 
```php
<?php

require 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';

$loop = \React\EventLoop\Factory::create();
$handler = new \WyriHaximus\React\GuzzlePsr7\HttpClientAdapter($loop);

$client = new \GuzzleHttp\Client([
    'handler' => \GuzzleHttp\HandlerStack::create($handler),
]);

$client->getAsync('http://github.com/')->done(function ($response) {
    var_export($response);
    var_export((string) $response->getBody());
});

$loop->run();
```
this error will be occurred
```Fatal error: Call to undefined method GuzzleHttp\Promise\Promise::done() in C:\Users\WebMaster\Desktop\S3\react-guzzle-psr7.php on line 12```

As you can see the returned value of Async method is  ```GuzzleHttp\Promise\Promise``` Not ReactPHP Promise

Can you show me how is possible in this example to convert 404 error to uncaught exception?

**Comment by mtdowling** [comment]
One quick thing to point out: the SDK will always return a Guzzle promise regardless of the handler you use because that's what is specified in the SDK interfaces. You will need to convert the Guzzle promise to a React promise manually.

**Comment by socketman2016** [comment]
May be I'm in wrong 

Let me ask a question relative to my problem , this is an example 
```php 
use Aws\Exception\AwsException;

$promise = $client->listTablesAsync();

try {
    $result = $promise->wait();
} catch (AwsException $e) {
    // handle the error.
}
```

If I use Event Loop for this example I never can use ```$promise->wait()``` so ```try``` and ```catch``` is not meaning , Can you convert this example to use event loop and ```try``` ```catch``` for promise?

**Comment by cjyclaire** [comment]
@socketman2016 Apology for the late response, looks like your main concern is catching exceptions. So, it's true that `Guzzle` doesn't have `done()` method. Yet `then()` or [`reject()`](https://github.com/guzzle/promises/blob/master/src/Promise.php#L116) is sufficient for catching a `RejectedPromise` that contains exception or error.

You could do something like:
``` php
$promise->then(null, function ($reason) {
    echo $reason;
});
// OR
$promise->reject('Error!');
// Outputs "Error!"
```

**Comment by cjyclaire** [comment]
Closing due to ages, yet feel free to reopen with further comments or questions :)
