### ISSUE TITLE
CredentialProvider::cache() cache argument not optional?

### ISSUE THREAD

**Issue by tamc** [aws/aws-sdk-php#1107]
The API docs for CredentialProvider::cache (http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Credentials.CredentialProvider.html#_cache) say:

> Defaults to using a simple file-based cache when none provided. 
> ...
> Aws\CacheInterface	$cache	(optional) Cache to store credentials

But as far as I can tell, the $cache argument is required and it does not default to anything.

**Comment by cjyclaire** [comment]
@tamc Thanks for noticing, I'll fix it. 

So for [`cache`](https://github.com/aws/aws-sdk-php/blob/master/src/Credentials/CredentialProvider.php#L187), `$cache` represents 
` $cache (optional) Cache to store credentials`, and by saying `Defaults to using a simple file-based cache when none provided.`, it is talking about the updated cache type when no credentials found in cache.

**Comment by cjyclaire** [comment]
Closing the issue and tracking with  PR #1108 instead, yet feel free to reopen with further comments or questions :)
