### ISSUE TITLE
EcrClient::getAuthorizationToken yields The security token included in the request is invalid.

### ISSUE THREAD

**Issue by ondrejhlavacek** [aws/aws-sdk-php#1114]
aws-sdk-php version 3.19.11.

I'm trying to get authorization token for `docker login` command and I'm getting `The security token included in the request is invalid.`. If I use the same KEY_ID and SECRET_KEY in `aws ecr get-authorization-token --region us-east-1 --profile MYPROFILE` I get the token correctly. But this code

```
$awsCredentials = new Credentials(KEY_ID, SECRET_KEY);
$ecrClient = new EcrClient(array(
    'credentials' => $awsCredentials,
    'region' => 'us-east-1',
    'version' => '2015-09-21'
));
$ecrClient->getAuthorizationToken();
```

Throws an `UnrecognizedClientException`

```
"Error executing "GetAuthorizationToken" on "https://ecr.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://ecr.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response:
{"__type":"UnrecognizedClientException","message":"The security token included in the request is invalid."}
 UnrecognizedClientException (client): The security token included in the request is invalid. - {"__type":"UnrecognizedClientException","message":"The security token included in the request is invalid."}" at
...vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:107
...vendor/guzzlehttp/guzzle/src/Middleware.php:65
...vendor/guzzlehttp/promises/src/Promise.php:203
...vendor/guzzlehttp/promises/src/Promise.php:156
...vendor/guzzlehttp/promises/src/TaskQueue.php:61
...vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:96
...vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:123
...vendor/guzzlehttp/promises/src/Promise.php:246
...vendor/guzzlehttp/promises/src/Promise.php:223
...vendor/guzzlehttp/promises/src/Promise.php:266
...vendor/guzzlehttp/promises/src/Promise.php:225
...vendor/guzzlehttp/promises/src/Promise.php:269
...vendor/guzzlehttp/promises/src/Promise.php:225
...vendor/guzzlehttp/promises/src/Promise.php:62
...vendor/aws/aws-sdk-php/src/AwsClientTrait.php:60
...vendor/aws/aws-sdk-php/src/AwsClientTrait.php:79
```

Can't wrap my head around it... Am I doing anything wrong? Thanks!

**Comment by cjyclaire** [comment]
@ondrejhlavacek I just tried `getAuthorizationToken` API and it works fine for me, I suspect the issue is with your `$awsCredentials`. The error message suggests problem with security token, and your code `new Credentials(KEY_ID, SECRET_KEY` seems to ignore token parameter, that might be the problem. So you would need to do something like:
`$awsCredentials = new Credentials(KEY_ID, SECRET_KEY, SECURITY_TOKEN)`

Also, looking at your CLI command, a profile credentials is used. You could also try using [`profile`](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#profile) with instrcutions [here](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html#using-the-aws-credentials-file-and-credential-profiles)?

**Comment by ondrejhlavacek** [comment]
I have no security token, only the key id  and secret key from IAM. The
server I'm trying the aws-sdk-php on has no aws profiles set uo and
eventually will use STS to authenticate, but for development I opted for
manual creation via IAM. My local machine I ran the CLI on has aws
profiles, but they again only have key id and secret key (and they are the
same as on the dev server).

**Comment by cjyclaire** [comment]
@ondrejhlavacek Interesting, thanks for these information inputs. Could you try 
`$resp = $ecrClient->getCredentials()` to see whether the credential is resolved correctly? And perhaps error could be surfaced before making the request.

**Comment by ondrejhlavacek** [comment]
Oh my... Shame on me. You were right from the beginning. The KEY_ID was invalid, copied it from a test that tested invalid credentials and didn't notice it. I am so sorry, everything works fine now.
