### ISSUE TITLE
Amazon SNS

### ISSUE THREAD

**Issue by robertmylne** [aws/aws-sdk-php#1116]
Can I use this with SNS?

**Comment by cjyclaire** [comment]
@robertmylne Yes, you can, check out the `SNSClient` [here](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Sns.SnsClient.html), also you might also be interested in [`aws/aws-php-sns-message-validator`](https://github.com/aws/aws-php-sns-message-validator).

**Comment by cjyclaire** [comment]
Closing, yet feel free to reopen if you have further questions or comments :)
