### ISSUE TITLE
Facing PHP Fatal error occurred while uploading to Frankfurt bucket with php version 7

### ISSUE THREAD

**Issue by skuppuraj** [aws/aws-sdk-php#1117]
PHP Fatal error occurred: Uncaught Guzzle\Service\Exception\ValidationException: Validation errors: [Key] is a required string in /kunden/411759_81929/webseiten/e.de/wp-content/plugins/iwp-client/lib/amazon/guzzle/guzzle/src/Guzzle/Service/Command/AbstractCommand.php:357 Stack trace: #0 /kunden/411759_81929/webseiten/e.de/wp-content/plugins/iwp-client/lib/amazon/guzzle/guzzle/src/Guzzle/Service/Command/AbstractCommand.php(236): Guzzle\Service\Command\AbstractCommand->validate() #1 /kunden/411759_81929/webseiten/e.de/wp-content/plugins/iwp-client/lib/amazon/guzzle/guzzle/src/Guzzle/Service/Client.php(205): Guzzle\Service\Command\AbstractCommand->prepare() #2 /kunden/411759_81929/webseiten/e.de/wp-content/plugins/iwp-client/lib/amazon/guzzle/guzzle/src/Guzzle/Service/Client.php(136): Guzzle\Service\Client->prepareCommand(Object(Aws\S3\Command\S3Command)) #3 /kunden/411759_81929/webseiten/e.de/wp-content/plugins/iwp-client/lib/amazon/guzzle/guzzle/src/Guzzle/Service/Command/Abst in /kunden/411759_81929/webseiten/e.de/wp-content/plugins/iwp-client/lib/amazon/guzzle/guzzle/src/Guzzle/Service/Command/AbstractCommand.php on line 357.

This issue not come in other bucket while uploading .
can any one help me to resolve this issue .

**Comment by cjyclaire** [comment]
@skuppuraj Can you provide a Code snippet or some background information about this?
From your error code, it indicates that `Key` parameter is not set correctly in your command.

**Comment by cjyclaire** [comment]
Closing due to ages, yet feel free to open with further details or comments :)
