### ISSUE TITLE
S3 getObjectUrl not returning the subdomain version

### ISSUE THREAD

**Issue by simshaun** [aws/aws-sdk-php#1118]
I'm not sure if this is a bug or just a question, but I've been trying to figure it out for the past few hours to no avail.

I'm initializing a client like so:

    $client = new S3Client([
        'credentials' => [
            'key' => 'sdfsdf',
            'secret' => 'sdsds',
        ],
        'region' => 'us-east-1',
        'version' => 'latest',
        'scheme' => 'https',
    ]);

And getting an object URL like so:

    $client->getObjectUrl('mybucket', 'foo.jpg');

All the examples and docs I've found in the past few hours have shown that it's supposed to generate a URL of `https://mybucket.s3.amazonaws.com/foo.jpg`, yet no matter what I do it always returns `https://s3.amazonaws.com/mybucket/foo.jpg`. I understand that the latter is a valid URL, but I need the former. So far, I've only been able to get it by hard-coding the endpoint URL.

**Package Versions:**
aws/aws-sdk-php - 3.19.24
guzzlehttp/guzzle - 6.2.2

**Comment by cjyclaire** [comment]
@simshaun Thanks for the information. So first of all, it's true that SDK return path-style instead of  CNAME style(virtual host style). 

Using virtual hosted bucket URLs can affect application performance in two ways: 1) you need to do a DNS lookup on every single bucket, and 2) requests are routed by default to the region provided. Could you explain a bit why you would need the pattern? Could you also provide the documentation that you talking about having the pattern?

**Comment by simshaun** [comment]
@cjyclaire 

It looks like I'm an idiot and didn't notice I was looking at v2 docs at the time.
- http://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.S3.S3Client.html#_getObjectUrl
- http://docs.aws.amazon.com/aws-sdk-php/v2/guide/service-s3.html#creating-a-pre-signed-url

As far as the use-case, I'm integrating some legacy services that use the CNAME-style into a newer app which uses v3. The few clients still using the old system are being fed data that contains those URLs. My fear is that if I start sending a different URL format, stuff on their side might break. It's just easier for me to keep using the CNAME-style than try to coordinate with these companies. If I need to I'll just hard-code the endpoint in these special cases.

**Comment by cjyclaire** [comment]
@simshaun No problem at all, v2 allows this pattern due to old signature pattern. It is not recommended anyways. Thanks for the explain there, I see. So for work-arounds, it's possible to use these CNAME style like:
```php
$s3 = new \Aws\S3\S3Client([
    'version' => <version>,
    'region' => <region>,
    'endpoint' => '<bucketName>.s3.amazonaws.com',
    'bucket_endpoint' => true,
]);
```

**Comment by simshaun** [comment]
Thanks
