### ISSUE TITLE
\Aws\Sns\Exception\SnsException returns both plain text and XML

### ISSUE THREAD

**Issue by poisa** [aws/aws-sdk-php#1119]
I'm tidying up the errors returned in my application and noticed that `\Aws\Sns\Exception\SnsException::getMessage()` returns plain text and then XML both concatenated in the same string.
I can get the XML by itself with `::getResponse()` but can't seem to find the plain text by itself which is what I want.

Here's an example of what I'm getting:

```
Error executing "CreatePlatformApplication" on "https://sns.us-east-1.amazonaws.com"; AWS HTTP error: Client error response [url] https://sns.us-east-1.amazonaws.com [status code] 400 [reason phrase] Bad Request InvalidParameter (client): Invalid parameter: Attributes Reason: Invalid value for attribute: SuccessFeedbackSampleRate: value provided is not an integer between 0-100 - <ErrorResponse xmlns="http://sns.amazonaws.com/doc/2010-03-31/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidParameter</Code>
    <Message>Invalid parameter: Attributes Reason: Invalid value for attribute: SuccessFeedbackSampleRate: value provided is not an integer between 0-100</Message>
  </Error>
  <RequestId>// snip //</RequestId>
</ErrorResponse>

```

I realize I can manipulate the `getMessage()` string and strip the XML but that doesn't feel right, nor very future proof. 

Any idea how I can get to the plain text error?

**Comment by cjyclaire** [comment]
@poisa Thanks for the information, may I ask are you looking for catching the [error code](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/faq.html#how-to-handle-exception-with-error-code)? Or you want the plain txt message?  You might be interested in [`AwsException`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Exception.AwsException.html)

**Comment by poisa** [comment]
@cjyclaire I'm just interested in the plain text message. I originally tried every method in the suggested class since I saw that's where all the meat was but could only find the XML by itself, not the plain text.

**Comment by cjyclaire** [comment]
@poisa Thanks, you could use [`\Aws\Api\ErrorParser\XmlErrorParser`](https://github.com/aws/aws-sdk-php/blob/master/src/Api/ErrorParser/XmlErrorParser.php). You could do something like:
``` php
try {
   ...
} catch (Sns\Exception\SnsException $e) {
    $resp = $e->getResponse();
    $parser = new \Aws\Api\ErrorParser\XmlErrorParser();
    $msg = $parser($resp);
    var_dump($msg['message']);
}
```

**Comment by cjyclaire** [comment]
Closing due to ages, yet feel free to reopen with further details or questions :)

**Comment by poisa** [comment]
@cjyclaire Yes, that will definitely work for my use case. Thanks!
