### ISSUE TITLE
getSendStatistics args details

### ISSUE THREAD

**Issue by stavros-liaskos** [aws/aws-sdk-php#1128]
I failed to find what the argument array of getSendStatistic should look like. Neither here nor at the official docs of the Ses Client.

Here is the link from the docs though it's useless:
http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-email-2010-12-01.html#getsendstatistics

Does anyone have any ideas/links/examples to provide?

**Comment by cjyclaire** [comment]
@stavros-liaskos You just need to pass in an empty array, no parameters is needed for that API.

**Comment by stavros-liaskos** [comment]
@cjyclaire It is working with an empty array but I was expecting to pass some actual arguments! No wonder I never found a definition for that.. To be accurate, I was expecting to pass in the array an Id of a user so I can get the statistics only for that user, but that's probably another issue.

Thanks for the quick reply

**Comment by cjyclaire** [comment]
@stavros-liaskos I see, that's a fair impression to have at first glance. This `Get` API is per user actually. Then in distinguishing different users, you might need to have different client or playing around with identity operations. Thanks for the feedback, I'm closing this issue for now, yet feel free to reopen with further comments or questions. :)

**Comment by stavros-liaskos** [comment]
Actually I am really curious to now why set the argument of this function to an empty array. Why have an argument then in the first place?
