### ISSUE TITLE
createpresignedrequest expires time doesn't have any effect

### ISSUE THREAD

**Issue by hilmanrdn** [aws/aws-sdk-php#1130]
Hi, i'm using the latest version, which i believe 3.20

```
$cmd = $s3->getCommand('GetObject', [
    'Bucket' => $config['s3']['bucket'],
    'Key'    => $keyname
]);


$request = $s3->createPresignedRequest($cmd, '5 seconds');
$presignedUrl = (string) $request->getUri();
```

no matter what i put in expires time , 5 second,1 minutes or etc, i always can open the link without problem, even after the expires time i put.

**Comment by cjyclaire** [comment]
@hilmanrdn Could you try `+5 seconds` in your code?
For [`createPresignedRequest`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.S3.S3Client.html#_createPresignedRequest), when `$expires` is a string, it needs to follow [`strtotime`](http://php.net/manual/en/function.strtotime.php) converting rules.

**Comment by hilmanrdn** [comment]
i tried that, and still can visit the link after 5 seconds

**Comment by cjyclaire** [comment]
@hilmanrdn Hmm that's interesting, I couldn't reproduce the issue, I tried your code snippet with that change and it works for me (with correct expiration).

**Comment by hilmanrdn** [comment]
well if its work for others, than it's something wrong with me, i'll keep you update if i found the problem, thanks!

**Comment by cjyclaire** [comment]
Sound good, closing, yet feel free to reopen if you have further questions or more details :)
