### ISSUE TITLE
Annotation error : @http in method Aws\AwsClientInterface::getCommand()

### ISSUE THREAD

**Issue by GCalmels** [aws/aws-sdk-php#1134]
Hey,

I have this error : 
`The annotation "@http" in method Aws\AwsClientInterface::getCommand() was never imported.`
when I try to use S3.
Symfony thinks that "@http" is an annotation, is it possible to do otherwise?
I tried aws-sdk-php-symfony without any more success

Thanks

**Comment by cjyclaire** [comment]
@GCalmels Thanks for the information, I just tested when using SDK directly, and it is not a issue, I assume you have this issue with `symfony`. Just a quick check first, you should configure command something like this:
``` php
$command = $s3->getCommand('PutObject', [
    'Bucket' => $bucket,
    'Key' => $key,
    'Body' => 'foo bar',
]);

// Just an example for using '@'
$command['@http'] = [
    'debug' => true, 
];
$resp = $s3->execute($command);
```
Or this will work as well:
``` php
$s3->putObject([
   'Bucket' => $bucket,
    'Key' => $key,
    'Body' => 'foo bar',
    '@http' => [
        'debug' => true
    ]
]);
```
Or if the `@` really is the pain, you could try configure it at client level:
``` php
$s3 = new Aws\S3\S3Client([
    'region' => 'us-west-2',
    'version' => 'latest',
    'http' => [
       'debug' => true,
    ]
]);
```
Hope these helps.

**Comment by GCalmels** [comment]
Hey,
Thanks for the fast answer. I'm not using aws-php directly but with _flysystem-aws-s3-v3_
The "@http" is just an false annotation for Symfony and I have no clue about what I need to do to change this!

**Comment by cjyclaire** [comment]
@GCalmels I see, if the client level configuration doesn't work for you, sorry to say but where is nothing for SDK do there. Even if SDK changes the `@` behavior, it would easily break other customers. I'd say it's a issue need to bring up with `Symfony` or perhaps the thrid party repo instead of us.

**Comment by GCalmels** [comment]
Ok, I will try on an other level! Thank you again

**Comment by GCalmels** [comment]
Hi @cjyclaire,

Would it not be possible to change @http by "@http" on this [line](https://github.com/aws/aws-sdk-php/blob/master/src/AwsClientInterface.php#L32) because it is just documentation and there is no influence for the code, I guess?

And there are two other documentation like @http : @waiter on the same file : AwsClientInterface

**Comment by cjyclaire** [comment]
@GCalmels Of course that change won't affect code since it's just inside documentation block, yet I'm curious that, since it's only a documentation change, may I ask how will this helping the situation?

**Comment by GCalmels** [comment]
Hi @cjyclaire,
Because Symfony think that @http is an annotation and it does not know this (there are not "use .../http)...

**Comment by cjyclaire** [comment]
@GCalmels I understand, yet I mean even if this '@' lives in documentation? `@http` will be sourced in the code like [here](https://github.com/aws/aws-sdk-php/blob/master/src/AwsClient.php#L212) anyways?

**Comment by GCalmels** [comment]
@cjyclaire Yes but it is not a problem in the code! It is only the problem with `/** @http ... */` because Symfony sees it as annotation in the documentation but not in the code

**Comment by GCalmels** [comment]
Hi, I found my bug, in fact, it was Doctrine/Common/Annotation which does not like @http annotation. But it is possible to register false annotation on the autoload file!
Sorry!
