### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by jarrettj** [aws/aws-sdk-php#1136]
Hi,

Good day.

I'm struggling to find any examples on how to use the SES service. 

Could you maybe point me in the right direction? Thanks.

JJ

**Comment by cjyclaire** [comment]
@jarrettj API docs for [`SesClient`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Ses.SesClient.html), AWS developer guide for [SES](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/Welcome.html). Hope this helps!

**Comment by cjyclaire** [comment]
Provided above are official SDK API docs for `SES` service and official `SES` service guide. Closing, yet feel free to reopen with further questions or request in detail :)
