### ISSUE TITLE
Instantiating \Aws\S3\PostObjectV4 throws GuzzleHttp\Promise\RejectionException

### ISSUE THREAD

**Issue by jjmontgo** [aws/aws-sdk-php#1138]
Hi there!  

I'm just starting to use AWS and the PHP SDK and I'm wondering if you can help me out.

I'm following the instructions for PostObjectV4 here:

https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-presigned-post.html

I'm using Version 3.2 of the SDK.  The environment configuration is 64bit Amazon Linux 2016.09 v2.2.0 running PHP 7.0

Here is the code I'm running:

`include_once 'vendor/autoload.php';

$client = new Aws\S3\S3Client([
	'region' => 'us-east-1',
	'version' => 'latest',
]);

$bucketName = '<bucketname>';

// Set some defaults for form input fields
$formInputs = ['acl' => 'public-read'];

// Construct an array of conditions for policy
$options = [
    ['acl' => 'public-read'],
    ['bucket' => $bucketName],
    ['starts-with', '$key', ''],
];

// Optional: configure expiration time string
$expires = '+2 hours';

$postObject = new \Aws\S3\PostObjectV4(
    $client,
    $bucketName,
    $formInputs,
    $options,
    $expires
);`

And here are the results:

`
Fatal error: Uncaught GuzzleHttp\Promise\RejectionException: The promise was rejected with reason: Invoking the wait callback did not resolve the promise in /var/app/current/vendor/guzzlehttp/promises/src/functions.php:112
Stack trace:
#0 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(75): GuzzleHttp\Promise\exception_for('Invoking the wa...')
#1 /var/app/current/vendor/aws/aws-sdk-php/src/S3/PostObjectV4.php(57): GuzzleHttp\Promise\Promise->wait()
#2 /var/app/current/index.php(33): Aws\S3\PostObjectV4->__construct(Object(Aws\S3\S3Client), 'elasticbeanstal...', Array, Array, '+2 hours')
#3 {main}
  thrown in /var/app/current/vendor/guzzlehttp/promises/src/functions.php on line 112`

Does anyone know what I'm doing wrong here?

**Comment by cjyclaire** [comment]
@jjmontgo Thanks for the information, taking a looking to reproduce the issue ... It would be great if you could show me the [debug trace](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/faq.html#how-can-i-see-what-data-is-sent-over-the-wire) as the same time :)
Just a quick response, the error message show similar to #1125 , which might due to a guzzle issue, could you try down grade guzzle to 1.2.0 to see if it that works?

**Comment by jjmontgo** [comment]
Hi cjyclaire:

Thanks for the response.

I tried setting debug to true in the client on constructor but there was no new output.  

I also tried downgrading guzzlehttp/promises to 1.2.0 and there was no change in the error message.

Would really love to be able to execute upload files to S3 directly with form posts.  I've had problems with the guzzle library in the past and always ended up having to write my own functions with curl.

**Comment by cjyclaire** [comment]
@jjmontgo Thanks for the inputs, really appreciate that. Quick get back, I couldn't reproduce the issue locally, I'll try to see if I could reproduce it on the instance. The code snippet looks good to me though. Just to clarify, you are suggesting using `v3.20.X` right?

**Comment by jjmontgo** [comment]
Yup!

`{
    "require": {
        "aws/aws-sdk-php": "^3.20"
    }
}
`

**Comment by jjmontgo** [comment]
As an alternative I tried uploading the file directly to the instance and then using PutObject to send it to S3.

I received an authentication error:

`Fatal error: Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "PutObject" on "https://s3.amazonaws.com/elasticbeanstalk-us-east-1-853047570978/daybg-pdf.png"; AWS HTTP error: Client error: `PUT https://s3.amazonaws.com/elasticbeanstalk-us-east-1-853047570978/daybg-pdf.png` resulted in a `403 Forbidden` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>7F5EC1 (truncated...)
 AccessDenied (client): Access Denied - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>7F5EC1EEA8772404</RequestId><HostId>f1qjomNtlVuo0nFxN/f6fPdJ3uD5d2Vf4GX5iG8x1oY4oHc3D+HjfASo/WHKYrZK+jrEyMGAMCU=</HostId></Error>'

GuzzleHttp\Exception\ClientException: Client error: `PUT https://s3.amazonaws.com/elasticbeanstalk-us-east-1-853047570978/daybg-pdf.png` resulted in a `403 Forbidden` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied in /var/app/current/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 192`

Do you think this is causing the previous guzzle error?  Could you direct me to any resources for authorizing a beanstalk environment to an S3 bucket?  If I can figure out how to authorize myself to put objects into the bucket I'll see if the guzzle error goes away..

Thanks.

**Comment by cjyclaire** [comment]
@jjmontgo I cannot reproduce the issue at the instance environment either, looks like this is more a permission denied issue from your side. Here is some general documentation that you might be interested:
[Elasticbeanstalk PHP Example](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_PHP_eb.html)

So regarding permissions, 
1. The object policy
2. The credentials used in making the request

Could you tell me the 2 points above in your beanstalk environment? You need to make sure they both qualifies and matches.

**Comment by jjmontgo** [comment]
@cjyclaire Hmm! I'm going to have to read up on IAM.

I attached an AmazonS3FullAccess policy to my beanstalk EC2 role.  Then I went back to the PutObject attempt and re-ran it.  It worked, and uploaded the file to the S3 bucket.

So I went back to my code example with PostObject, and got the same Guzzle error as before.  

In both cases I'm instantiating the client the same:

`$client = new Aws\S3\S3Client([
	'region' => 'us-east-1',
	'version' => 'latest',
	'debug' => true,
]);`

The credentials would also be the same here.  I think it really is a problem with guzzle?

**Comment by cjyclaire** [comment]
@jjmontgo Thanks for getting back! Interesting, I'm curious why this will affect `PostObject` solo, since both behavior depends on sourcing qualified credentials for a `S3Client`. If gu.zle is the cause, both credential sourcing will be failed/

**Comment by jjmontgo** [comment]
@cjyclaire YES!  That definitely helps.  I added another key/secret pair (I didn't keep the old secret), added it directly to S3Client, and it WORKS!  It created all the form parameters, I posted a file to S3, and it redirected back to the page.  Perfect!

Of course I don't know why there's a guzzle issue, but I can check this off as working thanks to you.
