### ISSUE TITLE
Passing access credentials from JavaScript to PHP

### ISSUE THREAD

**Issue by amank12** [aws/aws-sdk-php#1144]
I am using following JavaScript code to authenticate a user :

<!DOCTYPE html>
<html>
<head>
	<script src="jsbn.js"></script>
	<script src="jsbn2.js"></script>
	<script src="sjcl.js"></script>
	<script src="https://sdk.amazonaws.com/js/aws-sdk-2.6.10.min.js"></script>
	<script src="aws-cognito-sdk.min.js"></script>
	<script src="amazon-cognito-identity.min.js"></script>
</head>

<body>
	  
    <script>

	AWS.config.region = 'ap-northeast-2';
        
    var poolData = { UserPoolId : 'ap-northeast-2_go0rGKVb5',
        ClientId : '6a0n8dqpi9i7be9mtve36u6klm'
    };
	
	var authenticationData = {
        Username : 'username',
        Password : 'Password1#',
    };
    var authenticationDetails = new AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails(authenticationData);
	
	if ( authenticationDetails != null)
		console.log('Got Authentication');
	
	var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);
	
	if ( userPool != null)
		console.log('Got userPool');	
	
	 var userData = {
        Username : 'username',
        Pool : userPool
    };
	
    var cognitoUser = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser(userData);
	
	if ( cognitoUser != null)
		console.log('Got cognitoUser');
		
	cognitoUser.authenticateUser(authenticationDetails, {
        onSuccess: function (result) {
            console.log('access token : ' + result.getAccessToken().getJwtToken());
            console.log('idToken : ' + result.getIdToken().getJwtToken());
			
			AWS.config.credentials = new AWS.CognitoIdentityCredentials({
				IdentityPoolId: 'ap-northeast-2:8ea060bb-dbb5-484d-b2cf-bd786c48a396',
					Logins: {
						'cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_go0rGKVb5':   result.getIdToken().getJwtToken()
					}
				});
				
				AWS.config.credentials.refresh(function (error) {
					if (error) {
						console.error(error);
					} else {
						console.log('Successfully logged!');
					}
				});
				
				console.log("ID", AWS.config.credentials.identityId);
				
				// Obtain AWS credentials
				AWS.config.credentials.get(function(){
					var accessKeyId = AWS.config.credentials.accessKeyId;
					var secretAccessKey = AWS.config.credentials.secretAccessKey;
					var sessionToken = AWS.config.credentials.sessionToken;
					
					console.log("Access Key:", AWS.config.credentials.accessKeyId);
					console.log("Secret Access Key:", AWS.config.credentials.secretAccessKey);
					console.log("Session Token:", AWS.config.credentials.sessionToken);
				});
        },

        onFailure: function(err) {
            alert(err);
        },

    });
	
	</script>
	
	</body>
</html>

Now I want to pass AWS access credentials to PHP file or function.  Please suggest how to do. Could I just pass then in URL bu that will not be secure.

**Comment by arosolino** [comment]
You are already using JavaScript to retrieve the credentials so they have already have been transferred through the clients connection. The best thing you could do is use a secure (https) connection.

**Comment by cjyclaire** [comment]
@amank12 Not sure what are you exactly asking for, are you asking integration credentials that you got from the javascript code to PHP SDK usage? Or you are just suggesting a PHP file/function?

Integrate credentials with [PHP SDK](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html), If you are not looking for PHP SDK integration, sorry to say but this is not the appropriate place for this question. StackOverflow would be a better place for this. Our github issue is used to tracking possible SDK bugs or feature request.

Closing, appreciate your attention anyways :)
