### ISSUE TITLE
Validate SQS message attributes

### ISSUE THREAD

**Issue by bakura10** [aws/aws-sdk-php#1148]
Hi !

Currently, the SQS SDK properly validates MD5 of message payloads to make sure the message has been received correctly (https://github.com/aws/aws-sdk-php/blob/master/src/Sqs/SqsClient.php#L119).

However, since the introduction of SQS message attributes, SQS also returns back a MD5OfMessageAttributes (https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-sqs-2012-11-05.html#sendmessage) which is simply not validated in the SDK (http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-attributes.html#sqs-attrib-md5)

It would be nice that this validation is carried on as well :).

**Comment by cjyclaire** [comment]
@bakura10 Appreciate the feedback, to clarify the feature request there, current `validateMd5()` only works for `ReceiveMessage` validation, with recent `MessageAttributes` introduced to `sendMessage`, SDK could help calculate the MD5 message digest for SQS message attributes there and helps with the validation. (Feel free to add more clarification there :))

I'll tag this as a feature request and have it in our backlog, it will be in our implementation queue soon :)

**Comment by bakura10** [comment]
Hey.

I couldn't make it any clearer :D.

**Comment by kstich** [comment]
Hi @bakura10, please see #1284 for an implementation of this request. Thanks!

**Comment by kstich** [comment]
@bakura10 We're pleased to say that this feature request has been integrated in to the SDK, [you can find the release here.](https://github.com/aws/aws-sdk-php/releases/tag/3.28.1)
