### ISSUE TITLE
getBucketPolicy php v2 not returning 

### ISSUE THREAD

**Issue by samueleastdev** [aws/aws-sdk-php#1151]
Hi All,

I am using the following code with the v2 api.
~~~
$result = $client->getBucketPolicy(array(
		    // Bucket is required
		    'Bucket' => MYBUCKET
		));

		echo json_encode(array(
    		'error' => false,
    		'message' => 'Successfully Returned',
    		'policy' => $result->toArray()
		));
~~~

and it is returning.
~~~
{"error":false,"message":"Successfully Returned","policy":{}}
~~~

I have a bucket policy set so cannot understand why its empty i can run.
~~~
aws s3api get-bucket-policy --bucket MYBUCKET
~~~

And i get this response.
~~~
{
    "Policy": "{\"Version\":\"2008-10-17\",\"Id\":\"Security\",\"Statement\":[{\"Sid\":\"1\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity 0000000000000\"},\"Action\":\"s3:GetObject\",\"Resource\":\"arn:aws:s3:::MYBUCKET/*\"}]}"
}
~~~

Any suggestions why the php version isn't working?

Thanks

**Comment by imshashank** [comment]
Hi,

Sorry that you received the error without an exception being thrown.

However, I tested the method and received no error messages. 

I would suggest that you please check the php error log for any errors.

Also, we suggest updating to the latest version of aws-sdk-php and reading the documentation.

Hope this response was helpful. Please let us know if we can do anything else for you.

**Comment by samueleastdev** [comment]
Hi @imshashank,

Does.
~~~
$result = $client->getBucketPolicy(array(
		    // Bucket is required
		    'Bucket' => MYBUCKET
		));

print_r($result->toArray());
~~~

return your bucket policy can you try that on a bucket that has a policy attached it definitely doesn't work.

**Comment by imshashank** [comment]
@samueleastdev I was able to get policy using the above method in v2.7.  Can u please make sure that the bucket name, region and other parameters are same when you call from code and when you call from CLI.

**Comment by samueleastdev** [comment]
@imshashank please close it was my fault i was running json encode on a already encoded json.

This works.
~~~
$check = $client->doesBucketPolicyExist($Bucket);

		if(isset($check)){

			$result = $client->getBucketPolicy(array(
			    // Bucket is required
			    'Bucket' => $Bucket
			));

			$policy = $result->toArray();

			echo json_encode(array(
	    		'error' => false,
	    		'message' => 'Successfully Returned',
	    		'policy' => json_decode($policy['Policy'])
			));

		}else{

			echo json_encode(array(
	    		'error' => false,
	    		'message' => 'Successfully Returned',
	    		'policy' => 'No Bucket Polcy Attached'
			));

		}
~~~

**Comment by imshashank** [comment]
I am glad the problem was fixed. :-)
