### ISSUE TITLE
errorGuzzle\Http\CachingEntityBody supports only SEEK_SET and SEEK_CUR seek operations

### ISSUE THREAD

**Issue by Thamaraiselvam** [aws/aws-sdk-php#1153]
guzzle/guzzle/src/Guzzle/Http/CachingEntityBody.php at 66th line
```
        if ($whence == SEEK_SET) {
            $byte = $offset;
        } elseif ($whence == SEEK_CUR) {
            $byte = $offset + $this->ftell();
        } else {
            throw new RuntimeException(__CLASS__ . ' supports only SEEK_SET and SEEK_CUR seek operations'); // this line makes warning
        }
```

**Comment by imshashank** [comment]
Hi,

Thanks for reaching out to us. Can you please elaborate your question, it will be really helpful if you can provide us more details.

**Comment by Thamaraiselvam** [comment]
I rarely get this exception `Guzzle\Http\CachingEntityBody supports only SEEK_SET and SEEK_CUR seek operations` while uploading files to S3.
I am not sure what is went wrong.

**Comment by cjyclaire** [comment]
@Thamaraiselvam It would be much more helpful if you could provide some code snippets that might help us to reproduce this issue.

Also could explain more about how you encounter the issue? Does "uploading files to S3" means using the `TransferManager` or simple `putObject` request? Also, could you provide more information about your use case? Such as, what's the version of SDK/Guzzle used? what's the OS environment?

**Comment by Thamaraiselvam** [comment]
Actually it happens while calling `listMultipartUploads` here is stack
`Guzzle\Common\Exception\RuntimeException: Unable to parse response body into XML: String could not be parsed as XML`

`#14 /S3/guzzle/guzzle/src/Guzzle/Http/Message/Response.php(899): xml`

`#13 /S3/guzzle/guzzle/src/Guzzle/Service/Command/LocationVisitor/Response/XmlVisitor.php(17): before`

`#12 /S3/guzzle/guzzle/src/Guzzle/Service/Command/OperationResponseParser.php(134): visitResult`

`#11 /S3/guzzle/guzzle/src/Guzzle/Service/Command/OperationResponseParser.php(86): handleParsing`

`#10 /S3/guzzle/guzzle/src/Guzzle/Service/Command/DefaultResponseParser.php(39): parse`

`#9 /S3/guzzle/guzzle/src/Guzzle/Service/Command/OperationCommand.php(87): process`

`#8 /S3/aws/aws-sdk-php/src/Aws/S3/Command/S3Command.php(58): process`

`#7 /S3/guzzle/guzzle/src/Guzzle/Service/Command/AbstractCommand.php(193): getResult`

`#6 /S3/guzzle/guzzle/src/Guzzle/Service/Client.php(138): execute`

`#5 /S3/guzzle/guzzle/src/Guzzle/Service/Command/AbstractCommand.php(153): execute`

`#4 /S3/guzzle/guzzle/src/Guzzle/Service/Command/AbstractCommand.php(189): getResult`

`#3 /S3/guzzle/guzzle/src/Guzzle/Service/Client.php(76): __call`

`#2 /S3/aws/aws-sdk-php/src/Aws/Common/Client/AbstractClient.php(104): __call`

`#1 $this->client->listMultipartUploads(array(
			'Bucket' => $this->as3_bucket,
		));`

**Comment by imshashank** [comment]
@Thamaraiselvam Can u please share the code you are using to call the method. Also which version of PHP and SDK are you using ?
