### ISSUE TITLE
S3 get free space

### ISSUE THREAD

**Issue by sm2017** [aws/aws-sdk-php#1154]
How can I calculate total free space available in s3 bucket ?

**Comment by Thamaraiselvam** [comment]
According to Amazon:


> Write, read, and delete objects containing from 1 byte to 5 terabytes of data each. The number of objects you can store is unlimited.

Reference:
http://stackoverflow.com/a/3981067/2975952
https://aws.amazon.com/s3/details/

**Comment by sm2017** [comment]
Thanks 
But I want to know , how can I get total free disk space of bucket in php??
Assume I have a bucket with 100GB total space and 10GB used space . so I have 90 GB free space in the bucket. Is there any way to get free space in php??

**Comment by Skarlso** [comment]
@sm2017 What @Thamaraiselvam was trying to say with this is, that there is no such concept in regards to S3. You don't have a bucket with 100GB total space, you have A Bucket, and that's it.

**Comment by sm2017** [comment]
OK , thanks a lot
