### ISSUE TITLE
Fail retrieving credentials from the instance profile metadata server upon massive amount of connection

### ISSUE THREAD

**Issue by kchan4** [aws/aws-sdk-php#1156]
I am doing a load test on my REST API that built on:
AWS EC2 + Apache + PHP 7.0.8 + AWS SDK PHP 3.18.25 + DynamoDB

The PHP code providing AWS Credentials by loading the credentials from instance profile metadata server, so the credentials can be rotated automatically.

            $credentialProvider = \Aws\Credentials\CredentialProvider::instanceProfile();
            $memoizedProvider = \Aws\Credentials\CredentialProvider::memoize($credentialProvider);
$config  = array(
                    'endpoint'  => 'https://dynamodb.us-west-1.amazonaws.com',
                    'region'    => 'us-west-1',
                    'version'   => 'latest',
                    'credentials' => $memoizedProvider
                )

$sdk = new \Aws\Sdk($config);

According to documentation [here](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html), this should caches the credential and retrieve new credential when the credential expired.

For amount of 50 virtual users per minute, I do not have any problems.
But for amount of **500** virtual users per minute for 10 mintues, during the 10 min, most of the time is working fine, but sometime the following error will occurs:

**Error retrieving credentials from the instance profile metadata server. (cURL error 52: Empty reply from server**
or
**Error retrieving credentials from the instance profile metadata server. (cURL error 28: Connection timed out after 1876 milliseconds** (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))\nStacktrace: #0
 /var/www/myapp/fuelphp/fuel/vendor/guzzlehttp/promises/src/Promise.php(203): Aws\Credentials\InstanceProfileProvider->Aws\Credentials\{closure}(Object(GuzzleHttp\Exception\ConnectException))\n#1
 /var/www/myapp/fuelphp/fuel/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(2, Array, Array)\n#2
 /var/www/myapp/fuelphp/fuel/vendor/guzzlehttp/promises/src/TaskQueue.php(61): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()\n#3
 /var/www/myapp/fuelphp/fuel/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\Promise\TaskQueue->run()\n#4 
 /var/www/myapp/fuelphp/fuel/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick()\n#5
 /var/www/myapp/fuelphp/fuel/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true)\n#6 /var/www/myapp/fuelphp/fuel/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()\n#7
 /var/www/myapp/fuelphp/fuel/vendor/guzzlehttp/promises/src/Promise.php(266): GuzzleHttp\Promise\Promise->waitIfPending()\n#8 /var/www/myapp/fuelphp/fuel/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()\n#9
 /var/www/myapp/fuelphp/fuel/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()\n#10 /var/www/myapp/fuelphp/fuel/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(59): GuzzleHttp\Promise\Promise->wait()\n#11
 /var/www/myapp/fuelphp/fuel/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(78): Aws\AwsClient->execute(Object(Aws\Command))\n#12 /var/www/myapp/fuelphp/fuel/app/classes/repository/dynamodb.php(57): Aws\AwsClient->__call('getItem', Array)\n#13 

So it seems at the moment when the credential expires, with a large amount of connection request at the same time will fail?
Is this limitation of the AWS SDK?  Or is AWS service side?

**Comment by cjyclaire** [comment]
@kchan4 Interesting, thank you for providing those information! A quick note first, I noticed that you are using SDK 3.18.X, it would be great if you could try upgrade to our latest version and latest guzzle version to see if any enhancement happens.

So from SDK side, it actually just making request to EC2 server for those metadata credentials. There could be certain possibilities that some limitation exists from server side. If you like, I can open a ticket internal with Ec2 with those data point to see if the limitation is the cause.

Meanwhile, to enhance the performance there, you might be interested in experimenting a bit around customizing the timeout behavior [there](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Credentials.InstanceProfileProvider.html). 

Does that sound good to you?

**Comment by cjyclaire** [comment]
Adding to my last comment, may I ask how do you cache those credentials? Are you sharing the cache across processes?

**Comment by kchan4** [comment]
If you can open the ticket for me, that will be great!
I will definitely try with a upgraded version of SDK as well.

Aside from that, I thought the \Aws\Credentials\CredentialProvider::memoize already caching the credentials across processes, no?

**Comment by jeskew** [comment]
@kchan4 
`CredentialProvider::memoize` caches credentials across operations, but not across processes. If you provide an instance of [`Aws\CacheInterface`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.CacheInterface.html) as your credentials, the SDK will use the default credential provider chain and store the result in the provided cache. The SDK ships with adapters for `Doctrine\Cache` and PSR-6 compliant caches.

**Comment by kchan4** [comment]
@jeskew  You are right!  I thought the memoize is write to a file and share across the process, but I was wrong.
I've implemented my own caching using CacheInterface and the errors is gone!
Thank you @jeskew  @cjyclaire !
