### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by sm2017** [aws/aws-sdk-php#1157]
1- How can I set S3Client request timeout?
2- What is default timeout?
3- If I set timeout to 1 sec and uploading of 100MB file takes 3 sec , (Just uploading not waiting to response from server , assume server can response less than a sec) , what happens?

**Comment by sm2017** [comment]
I found answer of question #1 here
> https://github.com/aws/aws-sdk-php/blob/33e8f7083fcb54fd926a8569cb81a0795e8c2633/docs/guide/configuration.rst#http

But I have an issue

When I send connect_timeout=5 , I see the error after 5 sec , when I set connect_timeout=0.1 , I see error after 0.1 sec but when I set connect_timeout=1 , it dont workes and I see error after 5 sec , why?

4- Whats is diffrence betwean ```connect_timeout``` and ```timeout``` exactly?

**Comment by imshashank** [comment]
Thanks for reaching out to us.

So to answer your questions:


3) I am not sure why would that happen, can you please share the logs and the error message you get.

4)
timeout is the total request time in connecting, uploading and downloading. This method has the same behavior as https://curl.haxx.se/libcurl/c/CURLOPT_TIMEOUT.html
 
connect_timeout is the amount of time to allow for connecting only (e.g., resolving DNS, establishing a connection, etc.). This method has the same behavior as https://curl.haxx.se/libcurl/c/CURLOPT_CONNECTTIMEOUT.html

Hope this answers your questions.

**Comment by sm2017** [comment]
> 3. I am not sure why would that happen, can you please share the logs and the error message you get

I don't try my self , I just ask a question


5- **When I send connect_timeout=5 , I see the error after 5 sec , when I set connect_timeout=0.1 , I see error after 0.1 sec but when I set connect_timeout=1 , it dont workes and I see error after 5 sec , why?**

6- Accodring to [aws guide](https://github.com/aws/aws-sdk-php/blob/33e8f7083fcb54fd926a8569cb81a0795e8c2633/docs/guide/configuration.rst#http) For ```connect_timeout``` and  ```timeout```
> Use 60 to wait indefinitely (the default behavior).

Accodring to [CURLOPT_TIMEOUT](https://curl.haxx.se/libcurl/c/CURLOPT_TIMEOUT.html) and [CURLOPT_CONNECTTIMEOUT](https://curl.haxx.se/libcurl/c/CURLOPT_CONNECTTIMEOUT.html)

 For ```connect_timeout``` 
> Set to zero to switch to the default built-in connection timeout - 300 seconds
 
 For ```timeout```
> Default timeout is 0 (zero) which means it never times out during transfer.


So , Which is correct for  aws-sdk-php and S3Client?

**Comment by imshashank** [comment]
@sm2017 Hi, Can you please try out uploading the file to S3. Timeouts also depend on network speed, OS and sytem configuration. 

Also is there a use-case where you want to specify a request timeout to a custom value. It will be really helpful if you can elaborate and share the code that you are trying to call.
