### ISSUE TITLE
Need configuration pagination form getPaginator

### ISSUE THREAD

**Issue by duythien** [aws/aws-sdk-php#1161]
Hello there,

When I need get all files from a directory I use method getPaginator that fine, but When I need a limit record it seem that the documents have not it, right?

```
$objects = $this->client->getPaginator('ListObjects', array(
            'Bucket' => $this->config->bucket,
            'Prefix' => $prefix'
           // Some thing config?
        ));
```

In version 2 I see it have this option http://docs.aws.amazon.com/aws-sdk-php/v2/guide/feature-iterators.html#basic-configuration. How to do this in version 3

Thanks

**Comment by cjyclaire** [comment]
@duythien Here is the [paginator](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/paginators.html) guide. The paginator is essentially an iterator of results and flexible for use.

For [`ListObject`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#listobjects) or [`ListObjectV2`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#listobjectsv2), you can specify the `MaxKeys` to limit number of keys returned in the response.
