### ISSUE TITLE
not-required attribute in Cookie Signer

### ISSUE THREAD

**Issue by hamadata** [aws/aws-sdk-php#1177]
Although the document says that the cookie attributes those are related to Cloudfront: Policy, Signature, and Key-Pair-Id,
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-setting-signed-cookie-custom-policy.html

But this test code includes the attributes of Cloudfront-Expire. 
https://github.com/aws/aws-sdk-php/blob/master/tests/CloudFront/CookieSignerTest.php#L74

Which is correct?

**Comment by jeskew** [comment]
Hi @hamadata,

CloudFront does not require a `Cloudfront-Expires` attribute when cookies are signed with custom policies, but [that attribute *is* required when signed cookies use canned policies](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-setting-signed-cookie-canned-policy.html). As demonstrated lower in the CookieSignerTest class, [the attribute is not included for custom policy-based cookies](https://github.com/aws/aws-sdk-php/blob/master/tests/CloudFront/CookieSignerTest.php#L89). 

Custom policies [must include a `DateLessThan` condition](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-setting-signed-cookie-custom-policy.html#private-content-custom-policy-statement-cookies-values), so the `Cloudfront-Expires` attribute is not included in those cookies.

**Comment by hamadata** [comment]
@jeskew 
Thanks, that was my misunderstanding (-_-;)
