### ISSUE TITLE
MultipartUpload with SDK v3: How to set StorageClass and ServerSideEncryption

### ISSUE THREAD

**Issue by dev4press** [aws/aws-sdk-php#1178]
I am migrating my project to SDK v3, and with v2 I used MultipartUpload\UploadBuilder to create MultiPart Uploader. It allowed setting options for StorageClass and ServerSideEncryption. How can I do the same with MultipartUpload with SD3 v3?

Example in [documentation](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-multipart-upload.html) list available options, but it doesn't say how to set StorageClass and ServerSideEncryption.

Does anyone have an example how to do that with MultipartUpload in SDK v3?

Milan

**Comment by jeskew** [comment]
Hi @dev4press,

You can accomplish this by providing customization callbacks as described in [the developer guide](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-multipart-upload.html#customizing-a-multipart-upload). A multipart upload's storage class is specified in the `CreateMultipartUpload` operation, so you customize the command in the `before_initiate` callback:
```php
$source = '/path/to/large/file.zip';
$uploader = new MultipartUploader($s3Client, $source, [
    'bucket' => 'your-bucket',
    'key'    => 'my-file.zip',
    'before_initiate' => function (\Aws\Command $command) {
        // $command is a CreateMultipartUpload operation
        $command['StorageClass'] = 'REDUCED_REDUNDANCY';
    },
]);
```

Server-side encryption is a bit trickier, as the type of SSE used will determine which commands should be modified. For KMS-based SSE, you would customize the `CreateMultipartUpload` command:
```php
$uploader = new MultipartUploader($s3Client, $source, [
    'bucket' => 'your-bucket',
    'key'    => 'my-file.zip',
    'before_initiate' => function (\Aws\Command $command) {
        // $command is a CreateMultipartUpload operation
        $command['ServerSideEncryption'] = 'aws:kms';
        $command['SSEKMSKeyId'] = $kmsKeyId;
    },
]);
```

If you're using server-side encryption with a customer-provided key, this key will need to be added to all uploaded parts:
```php
$secretSymmetricEncryptionKey = ...;
$uploader = new MultipartUploader($s3Client, $source, [
    'bucket' => 'your-bucket',
    'key'    => 'my-file.zip',
    'before_initiate' => function (\Aws\Command $command) {
        // $command is a CreateMultipartUpload operation
        $command['ServerSideEncryption'] = 'AES256';
        $command['SSECustomerAlgorithm'] = 'AES256';
        $command['SSECustomerKey'] = $secretSymmetricEncryptionKey;
    },
    'before_upload' => function (\Aws\Command $command) {
       // $command is an UploadPart operation
        $command['SSECustomerAlgorithm'] = 'AES256';
        $command['SSECustomerKey'] = $secretSymmetricEncryptionKey;
    },
]);
```

Hope that helps! Please feel free to reopen if you have any questions or concerns.

**Comment by dnizetic** [comment]
I posted a similar question on SO: https://stackoverflow.com/questions/51643372/aws-s3-php-sdk-how-to-specify-aes256-encryption-when-doing-multipart-upload. Found this issue which seems to confirm my assumption - thanks!

**Comment by GitLuca** [comment]
I'm sorry for commenting on an issue that old, but I'm having a problem with this. 
My first question: is the "SSEKMSKeyId" the ARN of the key?

I'm doing something like this:
`new MultipartCopy($s3Client, "bucket/$name", [
                'bucket'          => "bucket",
                'key'             => "$name",
                'before_initiate' => function (Command $command) {
                    // $command is a CreateMultipartUpload operation
                    $command['ServerSideEncryption'] = 'aws:kms';
                    $command['SSEKMSKeyId'] = 'key:arn';
                },
                'before_upload'   => function (\Aws\Command $command) {
                    // $command is an UploadPart operation
                    $command['ServerSideEncryption'] = 'aws:kms';
                    $command['SSEKMSKeyId'] = 'key:arn';
                },
            ]);`
The file is being copied, but the encryption is wrong
![Screenshot 2021-11-04 at 18 31 06](https://user-images.githubusercontent.com/18554637/140389776-2a060e8b-887b-4c86-bc20-864c99477542.png)

An additional difficulty is that I'm using two different accounts. Copying the file from Bucket A in account A to bucket B in account B. The key is in account B. The permissions are ok because doing it on the command line gives no error (using `--sse aws:kms --sse-kms-key-id key:arn)` options to the cp command
