### ISSUE TITLE
get json format

### ISSUE THREAD

**Issue by rizwandogar111** [aws/aws-sdk-php#1179]
how to get json format response instead of string format response ?

**Comment by jeskew** [comment]
Hi @rizwandogar111,

I'm not exactly sure what you mean. SDK operations should always return an instance of `Aws\ResultInterface` or throw an exception. Could you provide more detail as to which response you want to get in json format?

**Comment by imshashank** [comment]
Closing issue since there has been no response from customer for over 10 days now.
