### ISSUE TITLE
The request signature we calculated does not match the signature you provided. Check your key and signing method.

### ISSUE THREAD

**Issue by ankita-navtech** [aws/aws-sdk-php#1180]
From past 3 days I am stuck in the same issue of signature. I am not understanding how to come out of this. 

I am trying to get a pre signed url with this : s3.getSignedUrl('putObject',
event.pre_signed_url = {Bucket:config.awsBucket,Key:event.filename}
); in Node js.
And this pre signed url I am using to upload the image file in the s3 bucket by using :
request({
  method:'PUT', 
  url: event.pre_signed_url, 
  ContentType: 'image/png',
  body: fs.createReadStream('./image.png')}
, function(err, res, body)
{ if(err)console.log(err); return callback(body); }
);
And the file is getting successfully uploaded to the s3 bucket and I can see in aws s3 bucket console.

The issue is that the pre-signed url that I am getting if I am trying to PUT any other image file using curl from terminal or trying to open the url in the browser it is giving me signature mis match error. 

Please guide me if I am doing wrong or my understanding with pre signed url usage is wrong.

**Comment by mtdowling** [comment]
This is the issue tracker for the AWS SDK for PHP. You are looking for the AWS SDK for JS: https://github.com/aws/aws-sdk-js. Please open an issue there and the JavaScript team can help you.
