### ISSUE TITLE
Undefined index: partitionEndpoint

### ISSUE THREAD

**Issue by artifakt-io** [aws/aws-sdk-php#1190]
Hi guys,

When I instantiate ShieldClient(), I got an error :
=> Undefined index: partitionEndpoint

I have correctly specified region, version and credentials but it seems you have an issue in your SDK. To fix the problem, you need to add `'partitionEndpoint' => 'aws-global'` in your endpoints.json.php field for ShieldClient.

You can also do like that :
` if(!isset($this->data['services'][$service]['partitionEndpoint'])){
            return 'aws-global';
        }`
In the file => /aws-sdk-php/src/Endpoint/Partition.php (line 169)

Regards,
Aymeric

**Comment by cjyclaire** [comment]
@artifakt-io Thanks for reporting, taking a look ...

**Comment by cjyclaire** [comment]
@artifakt-io Quick question, what's the PHP SDK version that is used?
Could you show me some code snippets that could help reproduce the issue?

When I tried with latest version of SDK with:
``` php
$s = new \Aws\Shield\ShieldClient([
    'region' => 'us-east-1',
    'version' => 'latest'
]);

var_dump($s->listAttacks([]));
```
And it doesn't yell at me with errors? 
So `endpoint.json` file is shared across SDKs that is not appropriate for customization, yet if you have some interesting findings that suggests that this should be a global endpoint, I'm happy to see and try to fix this from root : )
