### ISSUE TITLE
Unknown Guzzle version: 4.2.2

### ISSUE THREAD

**Issue by AndyDunn** [aws/aws-sdk-php#1191]
I'm using Laravel 5.4 which includes aws-sdk-php for storing files via S3. The composer.json for Laravel contains:

`"guzzlehttp/guzzle": "6.2",`

However, when I try and access aws-sdk-php in my code by storing a file, it throws an exception with:

`Unknown Guzzle version: 4.2.2 in /Users/andy/Documents/Development/Projects/MobileIT/web/vendor/aws/aws-sdk-php/src/functions.php:271`

I've double checked the guzzle version installed and it does seem to be 6.2, so I've no idea where this 4.2.2 is coming from.

Any reason for this or any other information I could use to try and debug what the problem is?

**Comment by cjyclaire** [comment]
@AndyDunn Quick question, may I ask the PHP version used? PHP SDK V3 requires PHP >= 5.5

**Comment by AndyDunn** [comment]
@cjyclaire I'm using PHP 7.1.2 in Apache and 7.0.10 on the command line.

**Comment by cjyclaire** [comment]
@AndyDunn Interesting, are you install PHP SDK V3 freshly? (including Guzzle)? Would it be possible that you might have some old version guzzle installed somewhere?

**Comment by AndyDunn** [comment]
@cjyclaire I would have thought the only version would be in my laravel website folder, not from somewhere else on my hard drive. I installed PHP AWS SDK as part of the default Laravel 5.4 installation and after checking the guzzle installation, it is definitely 6.2.

I just don't understand why aws-sdk-php would be finding a guzzle which isn't within my laravel folder?

**Comment by imshashank** [comment]
@AndyDunn Sorry for the trouble you are experiencing. 

This is a strange issue and to be able to repro the issue, we would need more information. Can u help us understand what steps you followed to install the sdk and laravel. Also it would be great if you can send us the link to installation instructions that you followed so that we can repro the issue.

**Comment by AndyDunn** [comment]
@imshashank Okay, I have this narrowed down to an error when running phpunit from Laravel. If I call the API method via Postman it saves the file to S3 correctly.

Not sure how laravels phpunit uses an older version of guzzle, but I can at least live with skipping this test and only using it via a full API call.

**Comment by jeskew** [comment]
@AndyDunn Are you using a globally installed version of PHPUnit (installed with `composer require -g`)? That would cause the version of Guzzle installed with `composer require -g` to be prioritized over the one installed locally in your project.

I believe a few testing tools have Guzzle 4 as a dependency, so this situation can occur even if you didn't manually install Guzzle globally. The easiest remediation would be to use PHPUnit a package-local installation or a PHAR.

**Comment by AndyDunn** [comment]
@jeskew Wonderful idea. I just ran 'composer global show' and it came back with:

`guzzlehttp/guzzle                  4.2.2`

I also tried using the phpunit installed with Laravel and the tests executed perfectly. Thanks a lot for the help.
