### ISSUE TITLE
Aws\S3\StreamWrapper::stream_lock is not implemented!

### ISSUE THREAD

**Issue by edsonhoraciojunior** [aws/aws-sdk-php#1200]
I'm trying to put a object in S3 with lock management:

```
$s3Client->registerStreamWrapper();
file_put_contents('s3://bucket/key', 'some-data', FILE_APPEND | LOCK_EX);
```

And I get this error: 

> PHP Warning:  file_put_contents(): Aws\S3\StreamWrapper::stream_lock is not implemented!

**Comment by mtdowling** [comment]
Is the expectation here that we lock the S3 object somehow? How would the be possible?

**Comment by edsonhoraciojunior** [comment]
You asking that just made me realise that there's no such thing as edit a object at S3, which is why there's no reason for a lock. Thank you, i'll close the issue.
