### ISSUE TITLE
The requested version (2017-01-17) of service AWSMechanicalTurkRequester does not exist

### ISSUE THREAD

**Issue by JordanDalton** [aws/aws-sdk-php#1217]
The mechanical turk [website](http://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/Welcome.html) mentions of a new api version (2017-01-17). The [change log](https://github.com/aws/aws-sdk-php/blob/318b8a398761ac8114d54f5de6770cb1511f7256/.changes/3.23.0) mentions of a new MechanicalTurkRequesterService.
 In attempt to use it (with version 3.24.4) I'm encountering the following error:

````
<Response><Errors><Error><Code>NoSuchVersion</Code><Message>The requested version (2017-01-17) of service AWSMechanicalTurkRequester does not exist</Message></Error></Errors><RequestID>0a389ff0-8e23-48cc-bfca-cddebeebbd39</RequestID></Response>"}
````

Here's the url I'm attempting to work:

````
https://mechanicalturk.sandbox.amazonaws.com/  
````

Here's the request:
````
{"form_params":{"Operation":"RegisterHITType","Service":"MechanicalTurkRequesterService","Version":"2017-01-17","Timestamp":"2017-03-17T16:05:34Z","AWSAccessKeyId":"<Removed>","Signature":"<Removed>"}}
````

**Comment by imshashank** [comment]
@JordanDalton Hi, Can you please share the code to help us repro the issue.
