### ISSUE TITLE
aws sdk php throwing string length exception for valid SSM commandID length

### ISSUE THREAD

**Issue by mrityunjay308** [aws/aws-sdk-php#1220]
I am executing SendCommand request using ssmclient which executes fine and gives me a command id, which I am using in listcommandinvocations to check the output of executed command. The command is being executed as per below http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-ssm-2014-11-06.html#listcommandinvocations

SendCommand returns a 36 char length string which is used as input parameter in listcommandinvocations but getting error :

**_Found 1 error while validating the input provided for the ListCommandInvocations operation: [CommandId] expected string length to be >= 36, but found string length of 16 in C:\wamp64\www\aws\Aws\Api\Validator.php_**
The list-command-invocations works fine with the same command id when tried from aws cli.

Please help me on how can I fix this string length constraint from Validator.php

**Comment by imshashank** [comment]
@mrityunjay308 Have you tried checking the string length during runtime?

We have tried the operation but were not able to reproduce the error. Can you please share the code with us that is causing the error for you.
