### ISSUE TITLE
Auto requests to my S3 bucket even when i am not accessing it.

### ISSUE THREAD

**Issue by Thamaraiselvam** [aws/aws-sdk-php#1224]
I have enabled versioning in my bucket programmatically and uploaded some data programmatically after that I did not make any calls to that bucket. but when I see my reports I can see that lots of requests are made. this exceeds my free tier free requests. Can anyone explain what those requests mean? I suspect those are from amazon internal requests. Please reports data below
https://www.dropbox.com/s/7ub8gxvsqdqbo2u/requests.txt?dl=0

**Comment by imshashank** [comment]
@Thamaraiselvam Hi, thanks for reaching out. This looks more of an AWS S3 question. We would recommend that you contact the AWS S3 team and they will be able to help you better.

You can read the answer to your question in the FAQs on AWS S3 portal: https://aws.amazon.com/s3/faqs/

Also here are some docs on versioning: http://docs.aws.amazon.com/AmazonS3/latest/dev/Versioning.html

Here are few resources on how to reach AWS S3: https://aws.amazon.com/contact-us/

Please let me know if I can be of help.
