### ISSUE TITLE
Does CommandPool use SQS internally?

### ISSUE THREAD

**Issue by NinoSkopac** [aws/aws-sdk-php#1227]
I am using CommandPool in my Polly implementation, and I'm starting to see SQS requests in my Billing Console (on AWS website).

Does CommandPool use SQS internally?

**Comment by imshashank** [comment]
@NinoSkopac Hi, we would recommend contacting the Polly team on how they use SQS or charge the users.

**Comment by NinoSkopac** [comment]
So, you're saying that CommandPool in the SDK operates differently based on the service?

**Comment by imshashank** [comment]
@NinoSkopac Sorry If I misunderstood you. But if you haven't made any calls to the SQS service then the SDK will not implicitly call that service.

Hence if you are only making requests to Polly, then the requests are sent to only Polly Client.

It will really helpful if you can share your code with and we can have a look.

**Comment by NinoSkopac** [comment]
It doesn't really matter I guess, since SQS calls are free (I'd rather not share the code).

Thank you for your time Shashank.
