### ISSUE TITLE
Using phpleague/csv and S3's streamwrapper.

### ISSUE THREAD

**Issue by bs-thomas** [aws/aws-sdk-php#1230]
## Issue summary

Not allowing me to fetch data when I use phpleague/csv to read the first line of the CSV file.  It is returning an error saying cannot use r+ mode initially, and thus I'm opening it using r mode.  But when I fetch a line, it returns an error back to me.

### System informations

| Information | Description |
|--------------|---------|
| League\Csv version | 8.2.1 |
| PHP/HHVM version |  PHP 5.6.25 |
| OS Platform |  Windows 10 Pro |

## Standalone code, or other way to reproduce the problem

```
// Create the stream wrapper
$s3Client = \Aws\S3\S3Client::factory(array(
            'version' => 'latest',
            'region' => $region,
            'credentials' => array(
                'key'    => $key,
                'secret' => $secret,
            ),
        ));
$s3Client->registerStreamWrapper();

// Now read the data 
$filePath = s3://beamstyle-web-01/clients/www.polyauction.com.hk-localhost/auction/import/lots/import_lots_data_97d9b5e8-b659-4435-9e7f-640afbc19174.csv
$reader = \League\Csv\Reader::createFromPath($filePath, 'r');
$headers = $reader->fetchOne();
```

### Expected result
Can get the first row of the data.

### Actual result

RuntimeException in Reader.php line 120:
Cannot rewind file s3://beamstyle-web-01/clients/www.polyauction.com.hk-localhost/auction/import/lots/import_lots_data_97d9b5e8-b659-4435-9e7f-640afbc19174.csv

**Comment by jeskew** [comment]
[You'll need to set the `seekable` option to `true` when registering the stream wrapper.](https://github.com/aws/aws-sdk-php/blob/master/src/S3/StreamWrapper.php#L19) Otherwise, S3 streams cannot be rewound.

**Comment by bs-thomas** [comment]
@jeskew  Wow that helped a lot.  Thank you very much!  This is the final working code I have.  Thank you once again!

```
// Create the stream wrapper
$s3Client = \Aws\S3\S3Client::factory(array(
            'version' => 'latest',
            'region' => $region,
            'credentials' => array(
                'key'    => $key,
                'secret' => $secret,
            ),
        ));
$s3Client->registerStreamWrapper();

$context = stream_context_create(array(
    's3' => array(
        'seekable' => true
    )
));

$stream = fopen($filePath, 'r', false, $context);
$reader = \League\Csv\Reader::createFromStream($stream);
```
