### ISSUE TITLE
S3Client getObject() in combination with 'IfModifiedSince' and 'SaveAs' wipes local destination file if S3 returns 304

### ISSUE THREAD

**Issue by isegal** [aws/aws-sdk-php#1234]
Pre-Condition:
1. Have an existing file, that contains data, for example '/path/to/important_data.json'
2. Call getObject with 'SaveAs' set to '/path/to/important_data.json' AND  'IfModifiedSince' set to a date such that a 304 would be returned by S3.

Result: S3 returns a 304 'not-modified', the file '/path/to/important_data.json' will get truncated (data is wiped).
Expected result: When S3 returns a 304, the local SaveAs path should not be touched in any way.

```
$s3_client->getObject(['SaveAs' => '/path/to/important_data.json', 'IfModifiedSince' => time(), 'Bucket' => $bucket, 'Key' => $key]);

```

An example scenario where above is useful is caching. When you want to keep a locally cached copy of  '/path/to/important_data.json' but also want to minimize the number of requests to S3 (i.e. not send a HEAD followed by GET).

**Comment by jeskew** [comment]
Hi @isegal,

The `SaveAs` parameter directs Guzzle to use the file specified as the target in which to spool all response data, which in the case of a 304 happens to be an empty string. I'll open an issue on Guzzle to see if an extra branch should be added to [here](https://github.com/guzzle/guzzle/blob/dfadff37efcfd42230eef1350009898b7b9af40a/src/Handler/CurlFactory.php#L365) to only write if the data received has a length greater than 0.
