### ISSUE TITLE
Catch Error message only with the new version 3

### ISSUE THREAD

**Issue by s3bubble** [aws/aws-sdk-php#1237]
Hi All,

i am upgrading to the new version 3, before i was catching all my errors with the following code.
~~~
try {

		// run s3 code

    } catch (Exception $e) {
	    
	    echo json_encode(array(
			'error' => true,
			'message' => $e -> getMessage() . ''
		));

		die(); 

	}
~~~

which would give me the error message only but if i run this with the new version it doesnt just give me the message i get lots of other info aswell like this.
~~~
Error executing "CreateBucket" on "https://s3-us-west-2.amazonaws.com/sam"; AWS HTTP error: Client error: `PUT https://s3-us-west-2.amazonaws.com/testing` resulted in a `409 Conflict` response:

BucketAlreadyExistsThe requested bucket name is not  (truncated...)
 BucketAlreadyExists (client): The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again. - 
BucketAlreadyExistsThe requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.
~~~

Any help on how to just get the message only again?

Thanks

**Comment by imshashank** [comment]
@s3bubble Hi, thanks for reaching out to us. The above error message is returned by the service and we believe is more helpful for our users as they receive the full error now. Is there a reason that you would not want to log the full error?

**Comment by samueleastdev** [comment]
Hi @s3bubble,

Thanks for the response the before $e -> getMessage() was just catching the error message and i could return this via ajax to my users.

Take this for instance.
~~~
Error executing "CreateBucket" on "https://s3-us-west-2.amazonaws.com/sam"; AWS HTTP error: Client error: `PUT https://s3-us-west-2.amazonaws.com/testing` resulted in a `409 Conflict` response:

BucketAlreadyExistsThe requested bucket name is not  (truncated...)
 BucketAlreadyExists (client): The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again. - 
BucketAlreadyExistsThe requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.
~~~

Before I could just return the relevant error message to my users which from the example above would be.
~~~
The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again. 
~~~

Not sure how i could just get the message only from version 3?

Thanks

**Comment by s3bubble** [comment]
@imshashank,

Any update on this, how can I just display the message?

Thanks

Sam

**Comment by imshashank** [comment]
@s3bubble Hey, So PHP SDK uses a class called "AWSException" which is inherited by specific service classes.

Example: https://github.com/aws/aws-sdk-php/blob/master/src/S3/Exception/S3Exception.php

This is the main class https://github.com/aws/aws-sdk-php/blob/master/src/Exception/AwsException.php

You can get different parts of the message. But, we would strongly suggest `not` showing error messages directly to users as they are provided directly by service response.

I would suggest that you show errors based on error code returned and then show your own error string to the users based on the error code.

**Comment by s3bubble** [comment]
Hi @imshashank,

You say "You can get different parts of the message." can you explain on how to do this it does make sense for us to add custom error messages to every call when the sdk returns the correct one.

Take this error.
~~~
Error executing “ListBuckets” on “https://s3.amazonaws.com/”; AWS HTTP error: Client error: GET https://s3.amazonaws.com/ resulted in a 403 Forbidden response:
<?xml version=”1.0″ encoding=”UTF-8″?>
<Error>NotSignedUp<Message>Your account is not signed up for the S3 (truncated…)
NotSignedUp (client): Your account is not signed up for the S3 service. You must sign up before you can use S3. – <?xml version=”1.0″ encoding=”UTF-8″?>
<Error>NotSignedUp<Message>Your account is not signed up for the S3 service. You must sign up before you can use S3.</Message></Error>. Make sure you have the correct policy permissions set
~~~ 

We could just respond this which would work fine for our setup.
~~~
Your account is not signed up for the S3 service. You must sign up before you can use S3.
~~~

Thanks

**Comment by s3bubble** [comment]
Ok i have managed to get what we need by just editing line 176 in the WrappedHttpHandler.php 

~~~
$serviceError .= $parts['message'];
~~~ 

Thanks for you time

**Comment by kstich** [comment]
Hi @s3bubble, it looks like this is being worked on in the ["Add method to get service error message if available (like v2)" PR](https://github.com/aws/aws-sdk-php/pull/1241) as well.

**Comment by s3bubble** [comment]
Ah great thanks @kstich for the update ;)

**Comment by imshashank** [comment]
@s3bubble Hi, I have merged the PR https://github.com/aws/aws-sdk-php/pull/1241

Now you can get the concise error message using  `$e->getAwsErrorMessage()`

Hope this helps.

**Comment by samueleastdev** [comment]
@imshashank thanks very much ;)
