### ISSUE TITLE
Question: Why is src/functions.php excluded from PHPUnit coverage?

### ISSUE THREAD

**Issue by bradynpoulsen** [aws/aws-sdk-php#1242]
This observation was made when looking at this following configuration in the phpunit.xml.dist file https://github.com/aws/aws-sdk-php/blob/master/phpunit.xml.dist#L28

**Comment by imshashank** [comment]
@bradynpoulsen I just ran a coverage with the functions.php included and the report showed 0% coverage for functions.php. 

Although all of the method from functions.php are called in other classes and test classes.

I suspect this to be the reason that the file was excluded as it is incorrectly represented in coverage report.

**Comment by bradynpoulsen** [comment]
That's interesting. I added 2 functions and tests for them in PR #1243 and ran coverage with functions.php included and coverage was reported for the ones I added.

**Comment by imshashank** [comment]
@bradynpoulsen Thanks a lot for your work. I see the PR and will check the code.

**Comment by kstich** [comment]
It looks like many of the tests in FunctionsTest.php don't properly map to coverage, as @imshashank found, even though they have passing tests written. We could re-introduce the functions file, update the tests with `@covers` tags, and follow-up by increasing coverage with more tests. Thoughts?

**Comment by bradynpoulsen** [comment]
I agree, anytime coverage can be tracked for code that would be executed in the distributed package sounds like a winner.

**Comment by kstich** [comment]
This was merged a short while ago. Thanks again @bradynpoulsen!
