### ISSUE TITLE
Why every request and response is Array?

### ISSUE THREAD

**Issue by aftabnaveed** [aws/aws-sdk-php#1245]
Despite being feature rich, why does every request and response in PHP version of SDK is array? Java and .NET versions is more object oriented and has appropriate error handling. Is there any particular reason for using arrays here? Will it make sense to use Objects in PHP instead?

To support my question, I am trying to replicate the java like object oriented experience here without changing the core PHP SDK. Since I need to deal with EC2 instances that's what my starting point is. Here are some of the unit tests of my implementations. I am happy to share my full EC2 RunInstanceRequest implementation with 100% code coverage, only if it makes sense to have something similar in PHP?

Below implementation not only helps auto code completion when using IDE, but also makes it more readable. Moreover, with strict type checking and better error handling errors can be caught earlier in request. 

```php
class RunInstanceRequestTest extends \PHPUnit\Framework\TestCase
{
 public function testBlockDeviceMappingsCount()
	{
		$blockDeviceMapping1 = new BlockDeviceMapping();
		$blockDeviceMapping2 = new BlockDeviceMapping();
		$blockDeviceMapping1
			->withDeviceName('deviceName')
			->withNoDevice('no device');
		$blockDeviceMapping2
			->withDeviceName('deviceName2')
			->withNoDevice('no device2');	

		$this->request->setBlockDeviceMappings([
			$blockDeviceMapping1,
			$blockDeviceMapping2
		]);

		$this->assertCount(2, $this->request->toArray()['BlockDeviceMappings']);
	}

	public function testBlockDeviceMappingsReturnsArray()
	{
		$blockDeviceMapping1 = new BlockDeviceMapping();
		$blockDeviceMapping1
			->withDeviceName('deviceName')
			->withNoDevice('no device');

		$this->request->setBlockDeviceMappings([$blockDeviceMapping1]);	
		$this->assertInternalType('array', $this->request->toArray()['BlockDeviceMappings'][0]);	
	}

	public  function testSecurityGroupKeyExistsIfSet()
	{
		$expected = 'SecurityGroups';
		$this->request->setSecurityGroups(['default', 'restricted']);
		$this->assertArrayHasKey($expected, $this->request->toArray());
	}

	public function testSecurityGroupsArrayKeyReturnsArray()
	{
		$expected = 'array';
		$this->request->setSecurityGroups(['default', 'restricted']);
		$this->assertInternalType($expected, $this->request->toArray());
	}

	public function testSecurityGroupIdsKeyExistsIfSet()
	{
		$expected = 'SecurityGroupIds';
		$this->request->setSecurityGroupIds(['string id 1', 'string id 2']);
		$this->assertArrayHasKey($expected, $this->request->toArray());

	}

       //.... 
}

**Comment by imshashank** [comment]
@aftabnaveed Hi, Thanks for opening this issue. The choice to make every request/response an array of arrays is a design choice. We are thinking of changing the pattern in future. 

Is there a use-case in which treating request/response as object help you in certain ways that can not be achieved by arrays. We would love to hear about your thinking. Please elaborate on the enhancement so we can understand it better. Thanks.

**Comment by aftabnaveed** [comment]
I always found arrays to be more verbose and hard to read. In my use case I want to do some basic error checking like making sure all the required fields are provided before hitting the API server. It also makes it easy to read. Here is an example from my EC2 wrapper.

```php
try {

$runInstanceRequest = new RunInstancesRequest();
        $runInstanceRequest
            ->withImageId('ami-c9da80a9') 
            ->withInstanceType('t1.nano')
            ->withMinCount(1)
            ->withMaxCount(1)
            ->withKeyName('xxx-key')
            ->withTags(['Key' => 'Name', 'Value' => 'Ubuntu'])
            ->withSecurityGroups(['default']);

        $ec2Client->runInstances($runInstanceRequest->toArray());

} catch(InvalidArgumentException $e) {
   echo $e->getMessage();
}

**Comment by imshashank** [comment]
@aftabnaveed Thanks for the query again. So this is more of a design choice based on how the SDK actually works. 

If you look inside the SDK code you will realize we use models and the operations etc are loaded dynamically. So if we wanted to move to using classes it won't help your IDE as the code is dynamic and IDE wouldn't be able to help in that.

In terms of performance, we don't see an advantage of using methods and classes as first AWS has over 90 services hence would be a lot of code generated for the SDK.

We will keep your suggestion for future consideration. Thanks for the feedback. Please let me know if I can help you with something else.

**Comment by aftabnaveed** [comment]
> If you look inside the SDK code you will realize we use models and the operations etc are loaded dynamically. So if we wanted to move to using classes it won't help your IDE as the code is dynamic and IDE wouldn't be able to help in that.

If you explicitly define models like I did above. It for sure will help IDE auto suggest code. In case of arrays, one need to make sure keys are appropriately added and nested which apparently makes it hard to debug.
