### ISSUE TITLE
ClientResolver->throwRequired: empty variable $missing

### ISSUE THREAD

**Issue by literat** [aws/aws-sdk-php#1249]
Hi,
I was debugging my app because I forgot to fill AWS_REGION constant. But in logs I saw only 'Missing required client configuration options:' ClientResolver:365

So I try to investigate where the problem is and var_dump $missing variable from throwRequired:353 method. But the array of missing arguments was empty despite the aws region argument was missing.
So the log message was useless for me.

Please, check if there is really error or maybe I am doing something wrong.
Thank you

Version:3.25.6
PHP version: 7.0
Used with Laravel Filesystem

**Comment by kstich** [comment]
Hi @literat, I'm receiving an exception for the required-but-missing 'region' in my test configuration. I've not set it in the environment via AWS_REGION or in the arguments passed to the ClientResolver. Can you provide more details or a reproduction?

I'm on PHP 7.0.17 with aws-sdk-php 3.25.6 installed as well.
