### ISSUE TITLE
Specify storage class in S3 multipart upload

### ISSUE THREAD

**Issue by mwoodring** [aws/aws-sdk-php#1251]
I am trying to set a storage class of STANDARD_IA when using a MultipartUploader function but it does not work. The code I am using is:

```
$opt = [
    'acl' => 'private',
    'bucket' => BUCKET,
    'key' => "$currFileName",
    'part_size' => SEGSIZE,
    'StorageClass' => 'STANDARD_IA',
];

$s3Uploader = new MultipartUploader ($s3Client, $fileHndl, $opt);
$response = $s3Uploader->upload ();
```
Is there another parameter or method I should be using to make this work?

**Comment by imshashank** [comment]
@mwoodring Sorry you had the problem. You can read more documentation on how to use this here-> http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.S3.S3ClientInterface.html#_upload

It will be easier for us to help you if you can share the error with the stack trace.

**Comment by mwoodring** [comment]
imshashank,

The docs that you reference are for a whole file upload. I am talking about a multi part upload. There is no stack trace because the file upload completes successfully. Using the management console, looking at the files in the bucket shows that the files are in the storage class of STANDARD and not STANDARD-IA which is what I'm trying to achieve on upload.

**Comment by kstich** [comment]
Hi @mwoodring, the StorageClass property needs to be set on invocation of the `CreateMultipartUpload` call, which is the 'initiate' step of an upload. You can operate on this command by setting the `before_initiate` option for your MultipartUploader.

```
$opt = [
    ...
    'before_initiate' => function(\Aws\CommandInterface $command) {
        $command['StorageClass'] = 'STANDARD_IA';
    }
]
```

**Comment by imshashank** [comment]
@mwoodring Hi, is there any update on the issue? Closing this issue since there has been no update for over 15 days. Please feel free to reopen this in future is the issue comes again.

**Comment by guiperalta** [comment]
> Hi @mwoodring, the StorageClass property needs to be set on invocation of the [`CreateMultipartUpload`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#createmultipartupload) call, which is the 'initiate' step of an upload. You can operate on this command by setting the `before_initiate` option for your [MultipartUploader](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.S3.MultipartUploader.html).
> 
> ```
> $opt = [
>     ...
>     'before_initiate' => function(\Aws\CommandInterface $command) {
>         $command['StorageClass'] = 'STANDARD_IA';
>     }
> ]
> ```

this works, thank you
