### ISSUE TITLE
ClientResolver causes failing behaviors if globally namespaced functions have the same name as a default

### ISSUE THREAD

**Issue by bpicolo** [aws/aws-sdk-php#1257]
[Here's the line of code in question.](https://github.com/aws/aws-sdk-php/blob/514b86e97aa84cc7e30a218df4531ea758b9ba26/src/ClientResolver.php#L254)

The issue is mostly just that PHP is an insane language. Strings that are the name of some function in scope are is_callable==true, because php is happy to use strings as a function reference.

The case here is, say we've imported some file that's entirety is this:

```
<?php

function https($whatever) {
    return 'doesntmatter';
}
```

After this, trying to use SQS will hit the 'scheme' parameter, see that scheme['default'] == 'https'.
is_callable(scheme['default']) will return true, and the ClientResolver will proceed to call the globally namespaced function. And after this, SQS put URLs are suddenly `doesntmatter://aws....`.

This could feasibly (maybe?) introduce a security vulnerability if some suddenly-malicious external package decided to override https like so (either through a composer vulnerability or whatever):

```
<?php

function https($args) {
    return 'https://malicious-sqs-queue.com/?';
} 
```

That assumes the sdk isn't doing any certificate pinning, which I would imagine is the case purely because generally only browsers bother.

I'm not sure what the right fix is, because I have no idea where the sdk expects defaults to be callable. If they're actual php Closures, I suspect you could get away with either `$a['default'] instanceof Closure` or `is_callable($a['default']) && !is_string($a['default'])`.

If they're intended to be string references to functions, might be good to check if they're within the Aws namespace.

**Comment by imshashank** [comment]
@bpicolo Thanks for reporting this. I will create a PR soon to fix this probable flaw. I am trying to see if there are more places where the method is_callable is used.

**Comment by imshashank** [comment]
@bpicolo Hi, I have investigated this issue and there are a lot of fo places where this keyword is called. I'll apply a fix to the line specified. We are just taking the time to make sure that we don't break any of our customer's code.

**Comment by imshashank** [comment]
The fix has been merged. Closing this pull request.
