### ISSUE TITLE
Fatal Error Aws\CloudFront\CloudFrontClient Not Found

### ISSUE THREAD

**Issue by JasonNewton1** [aws/aws-sdk-php#1259]
Hi there,

I am getting the following error, when I run cloudfront.php

`Fatal error: Class 'Aws\CloudFront\CloudFrontClient' not found in /Library/WebServer/Documents/cloudfront.php on line 16`

Here is part of my script:

```
$cloudFront = new Aws\CloudFront\CloudFrontClient([
    'region'  => 'eu-west-1',
    'version' => 'latest',
    ]);
```

Please could someone advise me what is wrong?

Kind Regards

**Comment by kstich** [comment]
Hi @JasonNewton1,

It's possible your SDK files are failing to be included, see [this page](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/getting-started/basic-usage.html) for more information. If you're still having issues after verifying you've done the above inclusions, can you please provide some more detail about your file and project? Thanks!

**Comment by JasonNewton1** [comment]
Hi there,

I'm using Composer so I've made the change to now read:

```
<?php
	
use Aws\S3\S3Client;
use Aws\S3\Exception\S3Exception;

error_reporting(E_ALL);
ini_set('display_errors', 1);

require 'Library/WebServer/Documents/vendor/autoload.php';


$cloudFront = new Aws\CloudFront\CloudFrontClient([
    'region'  => 'eu-west-1',
    'version' => 'latest',
    ]);
```

**Comment by JasonNewton1** [comment]
But I now get the following error:

```

Warning: require(Library/WebServer/Documents/vendor/autoload.php): failed to open stream: No such file or directory in /Library/WebServer/Documents/cloudfront.php on line 9

Fatal error: require(): Failed opening required 'Library/WebServer/Documents/vendor/autoload.php' (include_path='.:') in /Library/WebServer/Documents/cloudfront.php on line 9

```

**Comment by kstich** [comment]
That's some progress! Now it looks like the path you're pointing to for the autoload.php is likely wrong. Try debugging with [get_include_path](http://php.net/manual/en/function.get-include-path.php) to see where your script is trying to include from and then adjust the require's path to the proper location.

**Comment by JasonNewton1** [comment]
This is the full path to auto upload.php

```require 'Library/WebServer/Documents/vendor/autoload.php';
```

So I don't know why it can't see it.

Here is the whole thing (screenshot) - I removed my keys.

https://dl.dropboxusercontent.com/content_link/cp5I506kFELKeZozkj1Set3AoxXxyckODXVuwMUtSMKMvzBAcya8zywxSBNonqbZ/file

**Comment by JasonNewton1** [comment]
I had the vendor in two locations.

Thanks
