### ISSUE TITLE
S3 Stream wrapper Writes don't ever indicate errors

### ISSUE THREAD

**Issue by McQaws** [aws/aws-sdk-php#1260]
The PHP function calls related to writing a file with S3 Stream wrapper never report an error.  I am using EB 2016.09 v2.3.1 with PHP 7.0 using latest SDK V3 (but this also occurs with SDK V2). Functions for reading are fine, it is the writes that are a problem.

This issue occurs in other circumstances but is most easily demonstrated with:

`$bytes = file_put_contents("s3://wrongbucketname/somefile.txt","12345");`

This should cause $bytes to be null as "wrongbucketname" does not exist but instead $bytes is 5 which is the length of the string as if it was written successfully.

Other write-related functions have a similar problem. For example:

```
$hndl = fopen("s3://wrongbucketname/newfile.txt","w");
if ($hndl)
  { echo "HNDL: {$hndl}  ";
    $wrote = fputcsv($hndl,array("1","2","3"));
    echo "WROTE: {$wrote}  ";
    $ok = fclose($hndl);
    if ($ok) { echo "CLOSE OK"; }
    else     { echo "CLOSE FAILED"; }
  }
```

What happens above is the fopen and fputcsv complete successfully. This is expected, even with a faulty bucket name, because the stream wrapper has to first build the temporary stream which is finally written to S3 when the handle is closed. Specifically, a valid handle is returned from the fopen and the fputcsv returns the number of bytes written.

The fclose causes a php error to be displayed/logged but the return value is always "true". A failed close operation should return false. The fclose error message is very long but starts like (in SDK V3):

`Warning: Error executing "PutObject" on "https://s3.amazonaws.com/wrongbucketname/newfile.txt"`

Now, I am not actually concerned what happens when I use a wrong bucket name. But I know that, rarely, S3 PutObject operations will fail but that condition is impossible to simulate in testing. So, I use the wrong bucket name to cause a failure. The same incorrect responses I describe occur with a correct bucket name but insufficient permissions for that bucket. That is perhaps more realistic but needs longer samples.

The same incorrect responses occur when using file_put_contents with "FILE_APPEND" and with fopen option "a" (for append).

Thanks

**Comment by kstich** [comment]
Hey @McQaws,
PHP automatically performs a stream flush before a close. No information is passed to the [stream_close](http://php.net/manual/en/streamwrapper.stream-close.php) portion of the stream wrapper. Instead, this message should be captured from the [stream_flush](http://php.net/manual/en/streamwrapper.stream-flush.php) related function: [fflush](http://php.net/manual/en/function.fflush.php).

Updating your sample to include this will produce the error and a `FLUSH FAILED` message:
```
$ok = fflush($hndl);
if ($ok) { echo "FLUSH OK"; }
else     { echo "FLUSH FAILED"; }
```

**Comment by McQaws** [comment]
OK, I'll try adding the fflush before fclose.  But, what about file_put_contents?

**Comment by kstich** [comment]
Sadly, it looks like that's going to run in to the same problem, since `file_put contents` likely also relies on the implicit `fflush` before `fclose` that doesn't pass along any error. From the [`file_put_contents()`](http://php.net/manual/en/function.file-put-contents.php) docs:

> This function is identical to calling fopen(), fwrite() and fclose() successively to write data to a file.

This was reported behavior all the way back in PHP5.3.8 and seems to be unpatched: https://bugs.php.net/bug.php?id=60110

**Comment by McQaws** [comment]
I confirm the fflush before an fclose catches the error.  Alas, I use file_put_contents far more often so - ouch.

I think my long-term solution is to create common functions for writing using the S3 API.  But, in the meantime I am going to use filesize() and filemtime() to detect errors in crucial spots.  Is there any care I need to take other than calling clearstatcache() before those functions?  Do I need to include an "s3://" prefixed filename with it, for example?  Thanks

**Comment by McQaws** [comment]
Nevermind on the clearstatcache().  I now realize that would only introduce failure scenarios using that with filesize and filemtime for error detection.

I have developed my own function for putting S3 objects using the API.  That gives me better control than even using fopen/fflush/fclose as I can process "5xx" class errors separately from the others.  That is, the class of responses for my function are "successful", "permanent error no retry", and "error - retry".

It would have been helpful to me to have seen something in the SDK docs that hinted at the problems identifying write failures.  I would have used the API when designing the app instead of the stream wrapper.  The failure rates for php writes with local files is so tiny it's rarely worth bothering.  But, S3 failures are more common so this is a larger exposure with the stream wrapper that could be better explained.  Until you clarified it with these comments I didn't know you hadn't added code in the sdk stream wrapper to overcome weaknesses in the php stream layer.

**Comment by kstich** [comment]
Given that it's an underlying PHP stream wrapper pattern, what would have been helpful for you in knowing this in advance? We can update the notes in [our StreamWrapper](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-stream-wrapper.html) documentation where the fwrite -> fclose pattern is shown, but I'm not sure if there are other references you used that we should also update.

**Comment by McQaws** [comment]
The nuances of your using the PHP stream wrapper "underneath" wasn't apparent to me.  One reason is I hadn't ever studied it before and, two, you never say you use it specifically in your docs :)  The names are similar, sure, but stream and wrapper are very common terms.  Your lead paragraph in the docs simply says the AWS stream wrapper allows use of the php file functions (...) and so I took that to mean the php semantics of those functions was supported.  I read plenty of helpful notes unique to S3 in those docs (the restriction on fopen modes, issues using temp streams, and so on) but never anything about error handling being any different.

So, something like the following would have helped me (thanks):

Detecting Upload Errors

Because of the underlying PHP Stream Wrapper interface, file_put_contents() will not return "false" when errors occur uploading a file.  Use fopen() or the SDK API PutObject if you need to identify these errors.

To identify upload errors when using fopen(), you must use an fflush() after all the writes and before the fclose().  The fflush() will return "false" for any errors.  An fclose() will return "true" even if there were preceding errors.

**Comment by kstich** [comment]
This is a helpful set of notes; we'll work to make this section more clear since I could see it tripping people up in the future as well. Thanks again!

**Comment by petertorelli** [comment]
Hi,
I didn't want to open a new issue because mine is related to this. What should be the correct pattern for handling errors when downloading a file from S3 through PHP to a web browser? My current flow checks if the object exists first, then downloads as a stream (still trying to figure out best buffer size).  However, during testing, if I use the wrong bucket name on the getObject, the download proceeds but the user gets an error message in their file. Shouldn't this throw an exception?

Thanks,
Peter

example:
~~~
// Existence check
if (! $client->doesObjectExist('RIGHTBUCKETNAME', $key)) {
	echo "This object does not exist";
	exit;
}
$client->registerStreamWrapper();
$filename = end(explode('/', $key));
header('Content-Description: File Transfer');
header('Content-Type: application/octet-stream');
header("Cache-Control: no-store, no-cache");
header('Content-Disposition: attachment; filename="'.$filename.'"');
// Force a fail here to check error handling
if ($stream = fopen('s3://WRONGBUCKETNAME/' . $key, 'rb')) {
    while (!feof($stream)) {
        echo fread($stream, 1024 * 4);
    }
    fclose($stream);
} else {
	echo "Failed to download";
	exit;
}
/// user got the error message in the file!
~~~
