### ISSUE TITLE
registerStreamWrapper problems when handling images (getimagesize)

### ISSUE THREAD

**Issue by rollsappletree** [aws/aws-sdk-php#1261]
Hi,
I used registerStreamWrapper for my project and all was fine with older release. Since the last one i had this problem:
when trying to get the image size for images on S3, sometimes values are completely wrong:
eg:

    print_r(getimagesize('s3://mybucket/mydir/image.jpg'));
I get

    Array
    (
        [0] => 160
        [1] => 91
        [2] => 2
        [3] => width="160" height="91"
        [bits] => 8
        [channels] => 3
        [mime] => image/jpeg
    )

those values are wrong. 
In fact if I use the php wrapper (thus calling the image with the public link) i obtain the correct values:

    print_r(getimagesize('https://s3.amazonaws.com/mybucket/mydir/image.jpg'));
i receive

    Array
    (
        [0] => 840
        [1] => 476
        [2] => 2
        [3] => width="840" height="476"
        [bits] => 8
        [channels] => 3
        [mime] => image/jpeg
    )

This do not happens always, only with some images. But before the libs update it never happened.

Some other times, instead, trying to retrieve those size, i receive an error like this: 

    PHP message: PHP Warning:  getimagesize(): corrupt JPEG data: 82 extraneous bytes before marker in /mycode/script.php on line TOT
    PHP message: PHP Warning:  getimagesize(): corrupt JPEG data: 95 extraneous bytes before marker in  /mycode/script.php on line TOT

How could I help in solving this issue?
Thanks
Carmelo

**Comment by rollsappletree** [comment]
![test_img](https://cloud.githubusercontent.com/assets/1379119/25283829/67f4c12c-26b5-11e7-8b3f-c120166c3152.jpg)
here one image to test this issue.

Cheers
C

**Comment by kstich** [comment]
Hi @rollsappletree, I'm unable to reproduce this issue with an image of my own. Given the warning that you're receiving about corrupt JPEG data, I believe that your image is likely corrupt in some way. That is subsequently affecting the data passed to `getimagesize`, which probably reports differently based on how much of the file has been read in before it is invoked.

**Comment by hkirsman** [comment]
I know it's a closed task but I was investigating why I get getimagesize() error with a particular image when streaming is enabled. I thought it needs to be a big (over 200 kb) image but doesn't seem to be the case (tried with 1mb image). I checked my image with few tools to verify it's ok and seems it is. The above image in this ticket also triggers the error. So I'll leave my image here if somebody is doing an investigation on their own. What those images have in common?

![17](https://user-images.githubusercontent.com/492375/111027713-9b918500-83fa-11eb-8eda-b898969aa0b0.jpeg)
