### ISSUE TITLE
Support the new RDS IAM authentication

### ISSUE THREAD

**Issue by mvanbaak** [aws/aws-sdk-php#1265]
As of today, RDS users can be created which use IAM to authenticate. The documentation shows a sample in Java, but since we are a PHP shop we need this support in here.

See http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html

**Comment by imshashank** [comment]
@mvanbaak We are working on this and you will see an update very soon. We don't have an sla as of now but I will keep this thread updated.

**Comment by imshashank** [comment]
@mvanbaak RDS IAM Auth has been merged. Updated the CHANGELOG-> https://github.com/aws/aws-sdk-php/blob/master/CHANGELOG.md

**Comment by sators** [comment]
@imshashank Is there any example / documentation on how to use somewhere?

**Comment by kstich** [comment]
@sators Check out the [Rds\AuthTokenGenerator](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Rds.AuthTokenGenerator.html) for generating your token.

**Comment by sators** [comment]
Thanks @kstich for your help - I did dig around and and find Rds\AuthTokenGenerator...I'm using this sample code below to try to obtain a token:

```
// Use the default credential provider
$provider = CredentialProvider::defaultProvider();

$RdsAuthGenerator = new Aws\Rds\AuthTokenGenerator($provider);

$token = $RdsAuthGenerator->createToken('<db endpoint omitted>', 'us-east-2', 'iamuser');

var_dump($token);
```

This is outputting:

```
string(1023) "Action=connect&DBUser=iamuser&X-Amz-Security-Token=<random token>&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=<random credential>&X-Amz-Date=20171012T162656Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Signature=<random signature>"
```

Is this entire string supposed to be the MySQL password/token? ...or is it only supposed to be the value from the `X-Amz-Security-Token` parameter?

**Comment by kstich** [comment]
Yes, that entire string should be used as the password.

**Comment by sators** [comment]
Anyone visiting in the future might find this gist helpful: https://gist.github.com/sators/38dbe25f655f1c783cb2c49e9873d58a

**Comment by mvanbaak** [comment]
Thanks!

**Comment by angshuman-agarwal** [comment]
> Thanks @kstich for your help - I did dig around and and find Rds\AuthTokenGenerator...I'm using this sample code below to try to obtain a token:
> 
> ```
> // Use the default credential provider
> $provider = CredentialProvider::defaultProvider();
> 
> $RdsAuthGenerator = new Aws\Rds\AuthTokenGenerator($provider);
> 
> $token = $RdsAuthGenerator->createToken('<db endpoint omitted>', 'us-east-2', 'iamuser');
> 
> var_dump($token);
> ```
> 
> This is outputting:
> 
> ```
> string(1023) "Action=connect&DBUser=iamuser&X-Amz-Security-Token=<random token>&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=<random credential>&X-Amz-Date=20171012T162656Z&X-Amz-SignedHeaders=host&X-Amz-Expires=900&X-Amz-Signature=<random signature>"
> ```
> 
> Is this entire string supposed to be the MySQL password/token? ...or is it only supposed to be the value from the `X-Amz-Security-Token` parameter?

Hi,
I see this token string in PHP which starts with `Action` and that does not authenticate for me whereas java sdk generates a different token pattern i.e. it prefixes `host:port/?` before the `Action=`  and that works for me and the token is shorter too from Java. But, PHP's create token generates what you are saying. If I try to manually prefix `host:port/?`, that does not work. 

Any idea what could be the issue i.e. why 2 different language SDKS generating token differently ? And, Java one matches what I generate from command line i.e. 
`aws rds generate-db-auth-token --host <host> --port <port> --region <region> --username <user>`

regards
Angshuman

**Comment by SamRemis** [comment]
Hi there @angshuman-agarwal,
This issue has been closed a while, so it's difficult to keep up with notifications for any discussion that happens here.  Please create a new issue since this originally was a feature request and now it sounds like you're reporting a bug.  This will also make it easier to find for any future users who have the same issue as you.  
In the meantime, I did verify that they are generating different headers and will look into the reason

**Comment by angshuman-agarwal** [comment]
Thanks, I will create a new issue. And, sorry about that.
Here it is - https://github.com/aws/aws-sdk-php/issues/2262

> In the meantime, I did verify that they are generating different headers and will look into the reason

This is great to know. Thanks
