### ISSUE TITLE
Support S3 Object Tagging

### ISSUE THREAD

**Issue by se-robapodaca** [aws/aws-sdk-php#1267]
Now that it appears that S3 supports object tagging, please add support in the php sdk.

**Comment by kstich** [comment]
Hi @se-robapodaca,

I believe this is already supported through the [PutObjectTagging](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#putobjecttagging) method of the S3Client. If you were referring to another action, can you please provide some extra details? Thanks!

**Comment by se-robapodaca** [comment]
My bad. I was looking at v2 sdk documentation instead of v3. Thanks!
