### ISSUE TITLE
How do I upload to the S3 Bucket folder?

### ISSUE THREAD

**Issue by tinonetic** [aws/aws-sdk-php#1271]
Hi,

I have an S3 bucket that I would like to upload to.

I have seen the example that's listed here and have gone through the **putObject** function in the API documentation (http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#putobject)

I see nothing that indicates how to specify the folder.

Apologies if I missed it.

Thanks in advance for your help!

**Comment by kstich** [comment]
Hi @tinonetic,

This question is a bit more appropriate for somewhere like [StackOverflow](http://stackoverflow.com/questions/24665062/putobject-into-directory-amazon-s3-php) than an issue with the SDK itself.

**Comment by tinonetic** [comment]
Thank-you @kstich . Sorry about that.
