### ISSUE TITLE
Option to get the object URL in a subdomain style

### ISSUE THREAD

**Issue by stof** [aws/aws-sdk-php#1276]
For our application, all our objects are living in the same bucket (we have separate buckets for other deployments).
Is it possible to have `getObjectUrl` (and the similar code using a presigned URL to give temporary access to private files) returning a subdomain-style URL rather than a path-style one (as was done in v2) ?

I found https://github.com/aws/aws-sdk-php/issues/1118 saying that it affects performance due to extra DNS lookup. But in my case, I have a single bucket, which means a single DNS lookup.
And I'm using these URLs in a webpage. So using the subdomain-style URL would allow me to allow only this bucket in CSP instead of allowing all S3 buckets.

**Comment by stof** [comment]
Note that I'm perfectly fine about using the path-style URL for all API calls performed by my backend server though.

**Comment by kstich** [comment]
As of [Version 3.28.5](https://github.com/aws/aws-sdk-php/releases/tag/3.28.5), host-style URLs are the default for S3 and will be returned as such for host-style valid names. The `use_path_style_endpoint` S3Client option can be used for path-style URLs.

**Comment by stof** [comment]
@kstich will it use `foo.s3.amazonaws.com` or `foo.s3-eu-west-1.amazonaws.com` by default for a bucket being in Ireland ? The doc linked in the release notes mention that both are valid

**Comment by stof** [comment]
OK, I got my answer. It uses `foo.s3-eu-west-1.amazonaws.com`.

**Comment by stof** [comment]
@kstich for a European bucket, is it better to use `foo.s3.amazonaws.com` or `foo.s3-eu-west-1.amazonaws.com` when referencing it ?

**Comment by kstich** [comment]
Where a region specific endpoint is available, it should reduce latency [according to this documentation](http://docs.aws.amazon.com/general/latest/gr/rande.html)
