### ISSUE TITLE
Cognito Signup with lambda

### ISSUE THREAD

**Issue by skworden** [aws/aws-sdk-php#1277]
I can not use the presignup functions in lambda that is hooked to my user pool for validation because the PHP-SDK is stopping it with it's own validation (Api/Validator).  This validation also does not match the actual user pool validation rules.  

For example if i send a signup() request without a password (a user forgot to type one) it will throw an error like 

`Found 1 errors while validating the input provided for the SignUp operation:
[Password] expected string length to be >= 6, but found string length of 0` 

Which happens before I can use my own validation in the pre sign-up lambda (like recommended in the documentation for pre sign-up).  This error also does not match my user pool requirements for password so it's essentially pointless (should be >8).   The signup() function shouldn't validate anything because the cognito is already validating the same input.  

I think the process is messed up 

1. I validate
2. AWS-SDK Validates (Returing inaccorate validation rules)
3. AWS-Cognito Validates

The sdk shouldn't validate something that is getting validated milliseconds later by the same provider.

I can validate on my side before the signup which is fine, however, there is no point to use lambda to validate the same input twice on my side (four times including the SDK and Cognito).  I want to do all of my validation in lambda so I only have to do it once for all of the platforms my apps support.  

Please let me know how to disable this validation that is stopping me from using lambda.

**Comment by kstich** [comment]
Hi @skworden, could you please provide us with sample of how you're setting up your Cognito access through the SDK? This will help us in both investigating your use case and identifying any potential changes to make. Thanks!

**Comment by skworden** [comment]
I'm using the Cognito signup call, if all of the input the user enters is correct then it works as exspected. The error won't be in the catch (it's in the try) as it's thrown by the actual signup function in the SDK before it sends to the Cognito API.   I think the SDK shouldn't try and validate, it should let the API endpoint do the validation or allow a way to catch the errors.  Also, it would be nice if the API endpoint sent back the Attribute that was throwing the validation error like this SDK does (it says password and the API just says userattribute and doesn't say which one).

`   private function secretHash($username) {
        $clientId = $app->cognito->clientId;
        $clientSecret = $app->cognito->clientSecret;
        $s = hash_hmac('sha256', $username . $clientId, $clientSecret, true);
        return base64_encode($s);
    }

    private function generateUsername() {
        $username = str_replace(['@', '.'], '', $this->email);
        if (strlen($username) > 128) {
            $username = substr($username, 0, 122) . mt_rand(10000, 99999);
        }
        return $username;
    }

    public function signUp() {
        $username = $this->generateUsername();
        try {
            $app->cognito->client->signUp([
                'ClientId' => $app->cognito->clientId, // REQUIRED
                'Password' => $this->password, // REQUIRED
                'SecretHash' => $this->secretHash($username),
                'UserAttributes' => [
                    [
                        'Name' => 'given_name',
                        'Value' => $this->given_name
                    ],
                    [
                        'Name' => 'family_name',
                        'Value' => $this->family_name
                    ],
                    [
                        'Name' => 'email',
                        'Value' => $this->email
                    ]
                ],
                'Username' => $username
            ]);
        } catch (CognitoIdentityProviderException $e) {
            return [$e->getAwsErrorMessage(), $e->getAwsErrorCode(), $e->getAwsErrorType()];
        }
    }`

**Comment by kstich** [comment]
@skworden Have you tried using [the `'validate'` toggle](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#validate) when creating your `CognitoIdentityProviderClient `?

**Comment by skworden** [comment]
How would using the validate option help this issue in the signup process? This process doesn't use the class you referenced.

**Comment by kstich** [comment]
@skworden The validate option can be passed to any of the clients through their config. The SDK doesn't pull your own requirements, it uses those supplied by the service itself. If you're performing your own validation, you may want to use the 'validate' option to disable the SDK supplied validations. This will send your request to the service without performing validation and potentially blocking on failure; what happens from there is dependent on the service.

**Comment by skworden** [comment]
Great! Thanks for your help.  I'll be honest we dumped the PHP SDK, Conginto, and Lambda due to these issues as well as a couple others and we made our own user management but I will see if this works now.
