### ISSUE TITLE
Lambda function invoke returning empty LogResult

### ISSUE THREAD

**Issue by felipefcm** [aws/aws-sdk-php#1280]
I'm calling the invoke function with that arguments:

```php
$result = $lambda->invoke([
            'FunctionName' => $functionName,
	    'InvocationType' => 'RequestResponse',
	    'LogType' => 'Tail',
	    'Payload' => $payload,
]);
```

The invoke itself works, CloudWatch have the entire logs. However the `$result` variable have `LogResult` empty. If I run the invoke command from the aws-cli I also get a response normally.

**Comment by kstich** [comment]
Hi @felipefcm, I'm unable to recreate your issue. Please note that the your `$result` is an instance of Aws\Result, not stdClass. LogResult should be accessible via `$result['LogResult']` or `$result->get('LogResult')`.

**Comment by felipefcm** [comment]
I could reproduce the issue by logging a big enough data. Here is the Node.js code of the lambda function:

```javascript
"use strict";

exports.handler = (event, context, callback) => {

	var data = '';

	for(let i = 0; i < 422; ++i)
		data += 'a';

	console.log(data);

	callback(null);
};
```

If I use `421` characters instead, `LogResult` is non-empty. In CloudWatch the data is always being logged, as expected. When invoking the function via aws-cli I always get the logs as well.

**Comment by kstich** [comment]
Hi @felipefcm, I'm unable to reproduce this issue with both your lambda and a similar one in Python2.7. I also see the log entries for the lambda invocations in CloudWatch. Can you please provide your SDK version, Guzzle version, and PHP version along with any other information you might deem relevant?

**Comment by felipefcm** [comment]
php: 5.6.30
guzzlehttp/guzzle: 6.2.3
aws-sdk-php: 3.27.0

Can't provide much more information at the moment, but when the issue happens I simply comment out some `console.log` calls and it works fine again.

**Comment by kstich** [comment]
@felipefcm, That's nearly the same environment I am reproducing against. At this point, I would recommend reaching out to the Lambda team and letting them know you are sometimes not receiving the LogResult field of your `invoke` calls and include the details we have gone over here.
