### ISSUE TITLE
downloadBucket download files only

### ISSUE THREAD

**Issue by paulvreyes** [aws/aws-sdk-php#1282]
Hi,

$s3Client->downloadBucket('/temp/endpath/', 'bucket', '/temp/s3folder/');

I want to download files inside "/temp/s3folder/" of bucketname "bucket" and place it inside "/temp/endpath/" of my localdirectory. but what happens is it download even the folders. Instead of /temp/endpath/[files downloaded] it gives me /temp/endpath/temp/s3folder/[files downloaded].

How can I download only the files to place it in my local folder.

**Comment by kstich** [comment]
Hi @paulvreyes, the third parameter to [`downloadBucket`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.S3.S3ClientInterface.html#_downloadBucket) is a keyPrefix, which translates to a sub-folder when downloading files if it resolves to a path. To get your desired behavior, you would need to interact with the [`Transfer`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.S3.Transfer.html) class and its promise directly.

**Comment by MarkVaughn** [comment]
This behavior changed, previously it was downloading the content. Now it's downloading the folder, breaking things.  How do you achieve the previous behavior?

**Comment by MarkVaughn** [comment]
I think this might be where the breaking changes happened. https://github.com/aws/aws-sdk-php/commit/3341425eada1461d23dc6a17249f72a03becca37

By reverting my sdk version back I'm able to get the desired behavior back. However that's not a long term solution. The changes you made in this file seem to be for the sake of fixing a "possible security issue" but ends up changing behavior of downloading the folder instead of the folder content.

**Comment by kstich** [comment]
@MarkVaughn Thank you for the extra information, we're working to resolve this as soon as possible.

**Comment by kstich** [comment]
@paulvreyes @MarkVaughn, a PR ( #1286 ) was just posted that we hope will resolve this issue. Thank you both for bringing this issue to our attention.

**Comment by kstich** [comment]
@paulvreyes @MarkVaughn We believe this issue is fixed in [3.27.3](https://github.com/aws/aws-sdk-php/releases/tag/3.27.3). Thank you both again for your assistance.
