### ISSUE TITLE
AssumeRoleCredentialProvider fails with confusing error when simplexml extension is not loaded

### ISSUE THREAD

**Issue by Tietew** [aws/aws-sdk-php#1285]
Ubuntu 16.04
php 7.1.5
aws-sdk-php 3.27.2

When simplexml extension is not loaded (php7.1-xml package is not installed),
AssumeRoleCredentialProvider fails with confusing error:
```
Argument 1 passed to Aws\Credentials\AssumeRoleCredentialProvider::Aws\Credentials\{closure}()
must be an instance of RuntimeException, instance of Error given, called in
.../vendor/guzzlehttp/promises/src/Promise.php on line 203
```
The original exception is:
```
PHP error:  Class 'SimpleXMLElement' not found in .../vendor/aws/aws-sdk-php/src/Api/Parser/PayloadParserTrait.php on line 39
```
but above error doesn't show it.

Reproduce code:
```php
# run without simplexml extension
$sts = new Aws\Sts\StsClient([
    'version' => 'latest',
    'region' => 'ap-northeast-1',
    'credentials' => Aws\Credentials\CredentialProvider::defaultProvider(),
]);
$assumeRole = [
    'ExternalId' => 'MyExternalId',
    'RoleArn' => 'MyRoleArn',
    'RoleSessionName' => 'RandomSessionName',
];
$provider = new Aws\Credentials\AssumeRoleCredentialProvider([
    'assume_role_params' => $assumeRole,
    'client' => $sts,
]);
$provider()->wait(); # get credentials
```

My suggestions are:
- add `ext-simplexml` in `require` of `composer.json`
- catch `Throwable` instead of `RuntimeException` in `Aws\Credentials\AssumeRoleCredentialProvider::__invoke()

**Comment by imshashank** [comment]
@Tietew Thanks for reporting this issue. Please give us some time to investigate the issue. I'll keep this thread updated with what I find.

**Comment by imshashank** [comment]
@Tietew Sorry for the delayed response.  I was able to send the request with no errors. 

Have you seen this error for any other requests as well?

**Comment by mtdowling** [comment]
@imshashank this error is occurring because @Tietew does not have the SimpleXML extension installed. When you tried to reproduce this, did you ensure that you did not have that installed? The proposed solution to the error seems appropriate to me:

1. we should add "ext-simplexml" as a require in our composer.json.
2. We cannot catch `Throwable` because it doesn't exist pre-PHP 7. I seem to remember there being a hacky way to make this work though...

**Comment by Tietew** [comment]
@mtdowling Thank you for explanation.

To unload SimpleXML extension:
* RedHat/CentOS: comment out `extension=simplexml.so` in `/etc/php.d/simplexml.ini`
* Debian/Ubuntu: run `phpdismod simplexml`

> We cannot catch `Throwable` because it doesn't exist pre-PHP 7. I

Oh, sorry I forgot PHP 5 doesn't have `Throwable`.

How about removing `RuntimeException` type declaration?
Guzzle doesn't assume argument types of rejection callable.

**Comment by kstich** [comment]
I think we probably need to move a few of the PHP extensions that are in 'require-dev' up in to 'require' to make this 100% consistent:
```
        "ext-pcre": "*",
        "ext-spl": "*",
        "ext-json": "*",
        "ext-simplexml": "*",
```

That leaves `ext-openssl` (which has `extension_loaded` checks; it remains in 'suggest') and `ext-dom` (which is used only for generating documentation and guides) in 'require-dev'. Thoughts?

**Comment by imshashank** [comment]
@Tietew My bad, I should have asked the question in a different way.

I looked up at the documentation for simplexml extensions and to disable it, I had to compile PHP from source and pass the flag `--disable-simplexml` specifically.

Also, did adding the `ext-simplexml` to composer fix your issue or you had to install the php extension for Ubuntu as well? I added the `simplexml` to my composer but I was getting a different error afterward.

It will be really helpful if you can provide us with the steps as where did you install PHP from ie. apt-get or compiled from source?

**Comment by Tietew** [comment]
@imshashank Sorry for late reply.
I had installed php from apt. Ubuntu's php package does not contain many extensions by default.

Detailed reproduce step:
1. Launch a new EC2 instance from AMI "Ubuntu Server 16.04 LTS (HVM), SSD Volume Type".
2. Run `sudo apt install php-cli composer unzip`. (PHP 7.0.18-0ubuntu0.16.04.1 will be installed)
3. Run `composer require aws/aws-sdk-php`.
4. Run the script first I wrote.
5. The error occurs.

Evidence of my suggestion:
1. Run `composer require ext-simplexml`.
2. Get an error `The requested PHP extension ext-simplexml * is missing from your system.`
3. Run `sudo apt install php-xml`.
4. Run `composer update`.
5. Run the script.
6. No errors occur.

Note: Don't forget to attach an EC2 role which allows to call sts:AssumeRole.

**Comment by imshashank** [comment]
Sorry for the delay, created a PR for the requirements -> https://github.com/aws/aws-sdk-php/pull/1342
