### ISSUE TITLE
Cognito Identity Pool User can be deleted by just knowing UserPoolId

### ISSUE THREAD

**Issue by Nokrosis** [aws/aws-sdk-php#1296]
I'm developing a Client-side App with React and amazon-cognito-identity-js, so the UserPoolId is exposed on the javascript configuration of the library. However I was able to list users and even delete a user only by knowing UserPoolId and Username (provided by the list api call)

```php
$client = new CognitoIdentityProviderClient([
  'region' => 'us-east-1',
  'version' => '2016-04-18'
]);

$result = $client->listUsers([
    'UserPoolId' => '[POOL_ID]'
]);

$client->adminDeleteUser([
    'UserPoolId' => '[POOL_ID]',
    'Username' => '[USERNAME]'
]);
```

The above code execution successfully returned the users list and deleted the user. Is this behavior OK, knowing that UserPoolId can be public on a javascript client-side app?

**Comment by kstich** [comment]
This should throw a `NotAuthorizedException` if you execute an [`adminDeleteUser`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-cognito-idp-2016-04-18.html#admindeleteuser) call without being authorized to do so.

**Comment by Nokrosis** [comment]
Just tried in a clean server, Exceptions are thrown correctly, the development server was using credentials file with enough permissions.
