### ISSUE TITLE
Default Region for Client Instantiation

### ISSUE THREAD

**Issue by justin-yan** [aws/aws-sdk-php#1301]
Tried to find existing or similar issues but didn't spot any - #1239 might be kind of similar.

The immediate problem I'm facing is that I would like to be able to have a default region that comes from the credential provider chain.  An example from the Java SDK: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html#default-region-provider-chain

Thanks!

**Comment by kstich** [comment]
Thank you for requesting this enhancement! Like with the similar #1239, there is a decent amount of design around standards and practices, as well as interoperability with the other SDKs. We will keep this thread up to date on changes in this area of the SDK. We'd love to hear if there are more requests for this enhancement, so let us know here.

**Comment by Lakshanz** [comment]
+1
