### ISSUE TITLE
Your document should update for use_path_style_endpoint

### ISSUE THREAD

**Issue by netroby** [aws/aws-sdk-php#1302]
Since 3.28.5, the new configure option  use_path_style_endpoint may affect how to let s3 client connect original path style endpoint.

https://github.com/aws/aws-sdk-php/blob/master/CHANGELOG.md#3285---2017-05-30

But your document not quite describe it. 
Please upgrade your document.

http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html

May be this document need changes

https://github.com/aws/aws-sdk-php/blob/master/docs/guide/configuration.rst

Thanks a lot

**Comment by kstich** [comment]
Thanks for the feedback @netroby. The `use_path_style_endpoint` option is for only the [`S3Client`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.S3.S3Client.html#___construct) and is documented with the constructor. While the links you shared above are for all Aws\Sdk based clients, we can likely improve the documentation around this new flag. What kind of additional information would you find helpful?

**Comment by netroby** [comment]
It need to be add to configure document. If is only S3Client, you can mark as [s3client only]

The following example shows how to pass options into an Amazon S3 client constructor. You using s3client as configure example. but not show us the addition configure option. That's not good for user.

Not every one will first to look at API document

**Comment by kstich** [comment]
According to the [Basic SDK Usage guide](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/getting-started/basic-usage.html)

>All of the general client configuration options are described in detail in the [configuration guide](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html). The array of options provided to a client may vary based on which client you are creating. These custom client configuration options are described in the [API documentation](http://docs.aws.amazon.com/aws-sdk-php/latest/) of each client.

We will consider adding a similar notation to the overall configuration guide, but it's not feasible to maintain all service-client specific configuration options in the main SDK configuration document. Thanks for your feedback.

**Comment by kstich** [comment]
I'm closing this issue since we've pulled in #1303, it will be updated to the documentation on the release.
