### ISSUE TITLE
Elastic Transcode createJob and readJob not returning Input DetectedProperties data

### ISSUE THREAD

**Issue by rampo83** [aws/aws-sdk-php#1306]
Hi, I need to get original video file dimensions, width and height. Reading documentation these data could be rietrieved by reading result structure from createJob and readJob functions, but in "Input" section I get only one parameter, "Key" as the original inpu file name. Anyone use this function?

I start from HLS sample php from AWS official site. I have functions to create job with DASH (fmp4 container) and HLS (ts container). I use 5 presets to make 5 different version of a video input. 5 version for 5 resolution, from 420 to 1920. Everithing works well, but I'm not able to get "DetectedProperties" information

Info about the returned structure at
[http://docs.aws.amazon.com/elastictranscoder/latest/developerguide/get-job.html](http://docs.aws.amazon.com/elastictranscoder/latest/developerguide/get-job.html)

Thanks to everyone could help

**Comment by kstich** [comment]
Hi @rampo83, Thank you for using the AWS SDK for PHP. Questions about using the AWS APIs are more suited for sites like [StackOverflow](https://stackoverflow.com) than as issues with the PHP SDK itself. In case you haven't already, please reference these pieces of API documentation: [CreateJob](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-elastictranscoder-2012-09-25.html#createjob), [ReadJob](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-elastictranscoder-2012-09-25.html#readjob), [Shape-JobInput](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-elastictranscoder-2012-09-25.html#shape-jobinput), and [Shape-JobOutput](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-elastictranscoder-2012-09-25.html#shape-joboutput).

If you believe there is an issue with the SDK itself, please provide some further clarity on the issue and sample code which we can use to reproduce the issue. Thanks!

**Comment by rampo83** [comment]
Hi  kstich thank you for the answer but I wrote here because is more focused than other. And reading documentation (that I link too) seems that informations I need to get about the source video must be placed in the response. But I get the response and the structure I expect to see is different. No "DetectedProperties" present.

This is the documentation aobut for example createObject:
[http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-elastictranscoder-2012-09-25.html#createjob](url)

My code is something like this:
$job = $elasticTranscoder->createJob(array(

    'PipelineId' => '',

    'OutputKeyPrefix' => 'Output prefix added to the file',

    'Input' => array(
        'Key' => 'the path from bucket to the file, with file name',
        'FrameRate' => 'auto',
        'Resolution' => 'auto',
        'AspectRatio' => 'auto',
        'Interlaced' => 'auto',
        'Container' => 'auto',
    ),

    'Outputs' => array(
        array(
            'Key' => 'myOutput.mp4',
            'Rotate' => 'auto',
            'PresetId' => '',
        ),
    ),
));

What I would ask for to anyone knows deeply the PHP SDK is why the documentation says that I will found DetectedProperties in the result, data that must be automatically added from the Elastic Transcoder using the source file to encode, and I get a result without it.

I think it something like an issue, or if not the documentation is really poor about this. I search in web for hours something usefull to solve the problem. And I write here because I found nothing...

**Comment by kstich** [comment]
[`CreateJob`](http://docs.aws.amazon.com/elastictranscoder/latest/developerguide/create-job.html#create-job-responses) does not specify a `DetectedProperties` field on response. You can pass the job ID in that response to [`GetJob`](http://docs.aws.amazon.com/elastictranscoder/latest/developerguide/get-job.html#get-job-responses) to receive the `DetectedProperties` field.

I see there is a discrepancy in how the [SDK docs display](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-elastictranscoder-2012-09-25.html#createjob) this with the ElasticTranscoder documentation referenced herein and will work on updating it.

**Comment by rampo83** [comment]
Thank you kstich, I already find an explanation too. I see on AWS web interface that jobs with error final status does not have these data about the source video in the final report. But success jobs have it. So I try something new: instead of read createJob and readJob response during the video processing, I call readJob on a completed job and finally I get DetectedProperties on the response.

I finally observe, as you do, that documentation really lacks about it, and this discrepancy made me waste really lot of time.
