### ISSUE TITLE
Crypto enabling timeout

### ISSUE THREAD

**Issue by webexpert4rv** [aws/aws-sdk-php#1310]
Every once in a while, I will see following error in log file. I have sdk with with Laravel 5.1. 

aws/aws-sdk-php 3.20.12

exception 'Aws\Sqs\Exception\SqsException' with message 'Error executing "ReceiveMessage" on "https://sqs.ap-southeast-1.amazonaws.com/*********/default"; AWS HTTP error: Error creating resource: [message] fopen(): SSL: crypto enabling timeout
[file] /var/www/nrgedge/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 312
[message] fopen(): Failed to enable crypto
[file] /var/www/nrgedge/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 312

**Comment by kstich** [comment]
Hi @webexpert4rv, sorry you've encountered this issue. Can you please post a code sample so we can try to reproduce this issue? Additionally, can you post what versions of Guzzle, Curl, and OpenSSL you are using? This will hopefully help us narrow things down a bit.

**Comment by kstich** [comment]
Closing due to age, please feel free to reopen if you have any updates.
