### ISSUE TITLE
S3 StreamWrappers should not call trigger_error

### ISSUE THREAD

**Issue by tblanchard** [aws/aws-sdk-php#1316]
The reason is trigger_error injects html into the output stream.  That might be great for debugging, but when making JSON calls, it prevents the response from being parsed by things like query and leads to bad user experience.

**Comment by mtdowling** [comment]
trigger_error is the standard way used to represent errors when creating PHP stream wrappers. When working with production PHP applications, you should disable error_reporting to prevent exposing error information in HTML: http://php.net/manual/en/security.errors.php

> One way of catching this issue ahead of time is to make use of PHP's own error_reporting(), to help you secure your code and find variable usage that may be dangerous. By testing your code, prior to deployment, with E_ALL, you can quickly find areas where your variables may be open to poisoning or modification in other ways. Once you are ready for deployment, you should either disable error reporting completely by setting error_reporting() to 0, or turn off the error display using the php.ini option display_errors, to insulate your code from probing. If you choose to do the latter, you should also define the path to your log file using the error_log ini directive, and turn log_errors on.

**Comment by wellu** [comment]
Spent hours on debugging why the heck echoing file_get_contents from an S3 bucket didn't work as expected. Internally it uses trigger_error and that surely messes the output.
