### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by TakesTheBiscuit** [aws/aws-sdk-php#1319]
See here:
http://docs.aws.amazon.com/aws-sdk-php/v2/guide/service-s3.html#creating-a-pre-signed-url

`createPresignedUrl` doesn't exist / isn't valid

`Guzzle\Http` is now `GuzzleHttp\`

Probably many other issues, a bit confusing in terms of quick-start access which i was using this document for.

**Comment by kstich** [comment]
Hi @TakesTheBiscuit, it looks like you're viewing the v2 guide. [Here's the `createPresignedUrl` guide for v3.](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-presigned-url.html)

**Comment by TakesTheBiscuit** [comment]
Appreciate that -- the public links on the front end link there (to v2), i didn't notice anything that said V2 until you just mentioned it, and then it's only in the address bar / URI -- ideally the document would say on it V2? 
<img width="1096" alt="screen shot 2017-07-05 at 16 47 17" src="https://user-images.githubusercontent.com/15122732/27872725-a1c922ae-61a1-11e7-92c1-3b6d0ef5e627.png">

**Comment by kstich** [comment]
Do you have a page that directed you to the v2 docs? We can look in to what's causing that and potentially improving the messaging around v2 -> v3 docs as well.

**Comment by kstich** [comment]
#1320 has been merged in.
