### ISSUE TITLE
Issue with MultipartUpload since 3.31.0. Getting timeout response.

### ISSUE THREAD

**Issue by graphem** [aws/aws-sdk-php#1326]
I am using the plugin https://github.com/spatie/laravel-backup to run upload to S3 using PUT method. Since 3.31.0 release, we are getting these errors from S3:

`<?xml version="1.0" encoding="UTF-8"?>
<Code>RequestTimeout</Code><Message>Your socket connection to the server w (truncated...)
 RequestTimeout (client): Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. - <?xml version="1.0" encoding="UTF-8"?>
<Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.</Message>`

Seems to only occuring when doing MultipartUpload. Anyone else experiencing this issue with any other integration using this aws package? Thanks!

**Comment by dvlpp** [comment]
I can confirm this issue. To be more specific, the spatie/laravel-backup package uses the well-known thephpleague/flysystem-aws-s3-v3 package under the hood, and the issue was also reported here: https://github.com/thephpleague/flysystem-aws-s3-v3/issues/113.

**Comment by abiturma** [comment]
I encountered the exact same problem.

**Comment by vkulov** [comment]
We are having the same issue. Had to downgrade to 3.30.4

**Comment by kstich** [comment]
Thanks everyone for bringing this to our attention. It looks like you end up with an internal `MultipartUploader` which is being passed a seekable stream, which is not setting the `ContentLength` on the part to the proper size. We will have a PR up shortly fixing this issue.

**Comment by HSken** [comment]
Same issue

**Comment by zlodes** [comment]
Same, last version, php 7.1.0

**Comment by kstich** [comment]
We believe this issue has been fixed as of [version 3.31.3](https://github.com/aws/aws-sdk-php/releases/tag/3.31.3). Thank you again for the reports.

**Comment by graphem** [comment]
Confirmed, this is fixed. Thanks!!!!
