### ISSUE TITLE
PostObjectV4 upload timing out after 30 seconds

### ISSUE THREAD

**Issue by cwhite92** [aws/aws-sdk-php#1329]
I'm experiencing an issue where uploads to S3 are timing out after 30 seconds. The HTML form fields I'm using are generated from the `PostObjectV4` class. I've created a reproducible test:

```php
<?php

require 'vendor/autoload.php';

use Aws\S3\S3Client;
use Aws\S3\PostObjectV4;

$s3Client = new S3Client([
    'region' => 'eu-west-1',
    'version' => 'latest'
]);

$options = [
    ['bucket' => 'cwhites3test'],
    ['starts-with', '$key', '']
];

$postObject = new PostObjectV4($s3Client, 'cwhites3test', [], $options, '+1 hour');

$formAttributes = $postObject->getFormAttributes();
$formData = $postObject->getFormInputs();
```

Using the `$formAttributes` and `$formData` values given back by `PostObjectV4`, I can successfully upload small files (that take less than 30s to upload) to S3. However, when uploading large files, the browser cancels the request after 30 seconds: 

![miugjtm](https://user-images.githubusercontent.com/2497626/28093337-c29f0b46-668e-11e7-9b36-7d8c6cdaef16.png)

This happens in both Chrome and Firefox. As far as I can tell, S3 doesn't give me an error message back.

I'm struggling to find detailed documentation on the `PostObjectV4` class, which is hindering my efforts to debug this. I was hoping there would be a `timeout` option or similar that I can use to override the default 30 seconds.

Any help is appreciated!

**Comment by imshashank** [comment]
@cwhite92 Can you please check the `max_execution_time` in your `php.ini` file, it is 30 seconds by default. Also, the file will have a `post_max_size` which is set to 8MB by default. 

Please let me know if changing these values in `php.ini` fixes the issue for you.

**Comment by cwhite92** [comment]
@imshashank Thanks for getting back to me. The request isn't actually going via PHP, so those configuration options aren't relevant here. PHP is just being used to create the signed upload URL - the browser sends the file directly to S3.

**Comment by agursoy** [comment]
Hi, I'm facing same issue. Is there any update for that?

**Comment by kstich** [comment]
@cwhite92 and @agursoy, I've not been able to reproduce this issue. I have successfully uploaded large files (over two minutes in upload time) using a bare bones file form with `PostObjectV4` data applied to it. How are you submitting your request (basic form, ajax, etc.)? Do you receive any information as to why the request fails? And are you or the browser modifying the request in any way? I've seen similar errors in the past when sending a `Content-Length` header that does not match the size of the object.

I'd also recommend seeking assistance through the [S3 Forum](https://forums.aws.amazon.com/forum.jspa?forumID=24) or [AWS Customer Support](https://aws.amazon.com/contact-us/).

**Comment by agursoy** [comment]
First we're getting pre-signed data then making ajax request with dropzonejs. Weird thing is I can upload file 5 mb or something but I can not upload file 1 gb etc because it pass 30 sec.

Here is my request payload:
<img width="963" alt="problem" src="https://user-images.githubusercontent.com/1447418/28560921-1dcb2068-7125-11e7-8027-4c3792f6fcfe.png">

**Comment by kstich** [comment]
Can you try after changing your `Content-Lenght` to `Content-Length`?

A little additional detail: My previous upload that was over 2 minutes was a 777mb file. I uploaded another today that was roughly 1.5gb and took roughly 5 minutes and also completed successfully.

**Comment by agursoy** [comment]
Sorry for late response, I found a problem after I commented here. Problem related to javascript library to upload S3. I also commented to @cwhite92 's blog page. You can delete this issue. 

Thanks

**Comment by cwhite92** [comment]
@agursoy Thanks for looking into it! Glad you found the problem.

It seems that this isn't related to S3 after all, so I'll close this issue. Thanks all.

**Comment by kstich** [comment]
Thanks @cwhite92 and @agursoy! Here's the [related issue on Dropzone](https://github.com/enyo/dropzone/issues/1594) for those that are interested.
