### ISSUE TITLE
Unable to create folder with StreamWrapper mkdir

### ISSUE THREAD

**Issue by gwilym** [aws/aws-sdk-php#133]
I understand folders are a pseudo- concept in AWS, however the AWS console's S3 UI allows you to create empty "folders" within a bucket or within other folders.

I looked briefly at the `mkdir` implementation in the StreamWrapper and noted it had support for creating buckets but it seems to fail for anything other than that (such as `mkdir('s3://bucket/folder')`.

Apps transitioning from a traditional file system which rely on `mkdir` returning `true` before proceeding to put some files in will fail if the StreamWrapper doesn't support the same functionality that the UI exposes.

I imagine the change to be fairly simple but I'm not familiar enough with the S3 API (yet) to simply go ahead and do it myself.

**Comment by ceefour** [comment]
Has this changed? i. e. #1779 seems to imply mkdir works for folders..
