### ISSUE TITLE
Support to generate RDS auth tokens through PHP SDK.

### ISSUE THREAD

**Issue by henry911** [aws/aws-sdk-php#1334]
I could just be missing the method, but I can't seem to find support for the RDS generate db auth token within the PHP SDK. (CLI: aws rds generate-db-auth-token --hostname <val> --port <val> --username <val>)

If it doesn't exist, could support for this get added into the SDK?
If it does exist, please point me to the call _(as I may have overlooked it)_ and close this issue.

Why? Trying to establish RDS connections using IAM authentication within PHP (Symfony/Doctrine). If there's another means of doing this through the API, please point me in the right direction. Currently I'm running the AWS CLI command through the shell, grabbing the output buffer and putting the connection string from the CLI response in with the connection parameters for the PDO connection.

**Comment by kstich** [comment]
@henry911 Is what you are looking in [`AuthTokenGenerator`](https://github.com/aws/aws-sdk-php/blob/master/src/Rds/AuthTokenGenerator.php)?

**Comment by henry911** [comment]
It appears so, not sure how I missed it. Thanks for the information!
