### ISSUE TITLE
CloudFront Signing URL's with cloufront-signer gem

### ISSUE THREAD

**Issue by rpradhi** [aws/aws-sdk-php#1336]
While using cloudfront-signer gem to generate a signed URL, I am finding that the URL string returned from Aws::CF::Signer.sign_url has query parameters of Expires, Signature, and Key-Pair-Id.
When submitted, CloudFront returns the following error "Query-string authentication requires the Signature, Expires and AWSAccessKeyId parameters". If I replace "Key-Pair-Id" with AWSAccessKeyId it will accept the query, but tell me "The AWS Access Key Id you provided does not exist in our records." as it shouldn't because I passed my CloudFront Key Id.

Essentially, it looks that the query string being generated should be passing the "AWSAccessKeyId" rather than the "Key-Pair-Id". Thoughts?

**Comment by kstich** [comment]
Hi @rpradhi, from the sound of it, you're looking for the [AWS SDK for Ruby](https://github.com/aws/aws-sdk-ruby).

Closing since this isn't related to the PHP SDK.
