### ISSUE TITLE
S3MultipartUploadException not extending S3Exception

### ISSUE THREAD

**Issue by ababkov** [aws/aws-sdk-php#1337]
I was under the (perhaps mistaken) impression that all exceptions thrown within the Aws SDK namespace would extend the base level AwsException at the lowest level. The documentation seems to imply this (https://docs.aws.amazon.com/aws-sdk-php/v3/guide/getting-started/basic-usage.html#synchronous-error-handling) though i may be reading it wrong.

MultipartUploader seem to be an exception to this rule - this throws the S3MultipartUploadException (seems like a service specific exception) which extends the MultipartUploadException exception which in turn  extends the \RuntimeException directly.

This is a bit inconvenient when using something like the ObjectUploader - we end up having to catch for both an S3Exception and an S3MultipartUploadException.

Maybe i'm missing something and this is intended behaviour in which case are there any rules to when the AwsException is not extended from... or do we have to try and check every execution path to see what other exceptions might be called?

Thanks in advance.

**Comment by kstich** [comment]
That is true for something like the ObjectUploader, since it's an abstraction over MultipartUploader and the direct S3Client commands. The S3Client follows the pattern you linked, the MultipartUploadException handles exceptions in any number of its subcommands.

>[When an error occurs during the multipart upload process, a MultipartUploadException is thrown.](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-multipart-upload.html#recovering-from-errors)

**Comment by ababkov** [comment]
Surely at the lowest level the ideal situation would be an extension of a common base level AWS namespaced exception rather than a built in?

**Comment by kstich** [comment]
An `AwsException` is a single instance of a failure. The `MultipartUploadException` handles potentially one or many AwsException instances, based on where in the abstraction it fails. The MultipartUploadException then allows you to do nice things like retrying specific parts of the upload or abort the upload on a true failure. There could technically be a layer between these and `RuntimeException`, but I'm not sure how much benefit it would provide as these as they're only surfaced when using an abstraction.

[PHP 7.1](http://php.net/manual/en/migration71.new-features.php) did add multi-catch exception handling via a `|` if you have that available.

**Comment by ababkov** [comment]
@kstich thanks for the dialog / back and forth on this one - appreciate it. 

Can understand the reason for the different exception format and the value of the additional information provided in the MultipartUploadException but still think there's a lost opportunity in terms of having a catchall at the top level (even if it wouldn't be particularly accurate). For my interest, and if the information is readily available to you, are there any other situations in the SDK (apart from Multipart uploads) where an exception that doesn't extend from AwsException is thrown?

**Comment by kstich** [comment]
This list is compiled from [the V3 documentation 'Exception Summary' section](http://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html).

Derivatives of `\RuntimeException`:
* `AwsException` - Has many other extending exceptions for services.
* `CouldNotCreateChecksumException`
* `CredentialsException`
* `MultipartUploadException` - Has the discussed S3MultipartUploadException extend it.
* `ParserException`
* `UnresolvedApiException`
* `UnresolvedEndpointException`
* `UnresolvedSignatureException`

Derivatives of `\Exception`:
* `DeleteMultipleObjectsException`

**Comment by ababkov** [comment]
So basically if we want to catch any generic AWS exception we should just be catching for \Exception in all cases? Not ideal, but good to know...

**Comment by kstich** [comment]
It's much more advisable to be targeting what exception you're catching and how you want to handle resolving it on an case by case basis. While some of these cases are similar, that could be handled (< 7.1) with separate catch blocks that send the exception out to a function or (>= 7.1) using the `|` operator mentioned above.

Something like:
```php
try {
    $result = $s3Client->upload(...);
} catch (AwsException $e) {
    markFailedUpload($e);
} catch (MultipartUploadException $e) {
    markFailedUpload($e);
    $params = $e->getState()->getId();
    $result = $s3Client->abortMultipartUpload($params);
}
```

**Comment by ababkov** [comment]
At any point with almost any request you could also get a CredentialsException, ParserException or CounldNotCreateChecksumException though right?
