### ISSUE TITLE
doesBucketExist/HeadBucket fails with 403 Forbidden though credentials are valid

### ISSUE THREAD

**Issue by lookitsatravis** [aws/aws-sdk-php#1338]
Currently using v3.32. When I make a `doesBucketExist` request, I always get a `false` return value. I've dumped out the result of the HeadBucket request, and it is getting a 403 Forbidden response (`403 Forbidden (Request-ID: 2077487B2B7086F2)`).

However, my IAM policy allows full access (this is just the `AmazonS3FullAccess` default policy):

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": "*"
        }
    ]
}
```

According to the docs, HeadBucket should be working. I've double checked region, bucket name, API keys, etc -- all are correct.

**Comment by lookitsatravis** [comment]
It looks like this is a similar problem to #1029. However, that was over a year ago and this problem still exists. Using v2.8.* solves it because it does not treat AccessDenied as a failure.

**Comment by kstich** [comment]
I'm able to make successful `doesBucketExist` and `headBucket` calls to existing and non-existing buckets using the same IAM policy as you are. Have you checked that [the Bucket specific permissions](http://docs.aws.amazon.com/AmazonS3/latest/user-guide/set-bucket-permissions.html) are what you expect and accessible to the User?

**Comment by lookitsatravis** [comment]
@kstich Thanks for the question. The bucket in question Access Control List has everything enabled for the owner. There is no bucket policy set. Using v2.8 of the SDK I am able to do everything I expect with my IAM creds. It's only when I use v3 that I start to have problems.

**Comment by kstich** [comment]
Can you please post a small sample of how you're building the S3Client and making your API calls?

**Comment by lookitsatravis** [comment]
@kstich Roughly, it looks like this. Keep in mind that the only thing that is failing is `doesBucketExist` all other read/write operations done via the SDK succeed as expected.

```php
$this->s3client = \Aws\S3\S3Client::factory([
    'key' => 'my_key',
    'secret' => 'my_secret',
    'region' => 'us-east-1',
    'scheme' => 'https',
    'version' => 'latest',
]);


// v2.8
function ensureBucketExists($bucketName)
{
    /*
    This check works as expected, and I realize the the `true` argument explicitly says 403
    is allowed which seems to be the differentiator.
    */
    if (!$this->s3Client->doesBucketExist($bucketName, true)) { 
        // create bucket
    }
}

// v3.latest
function ensureBucketExists($bucketName)
{
    /*
    This check fails with 403 Forbidden, so the block is executed even when the bucket exists
    */
    if (!$this->s3Client->doesBucketExist($bucketName)) {
        // create bucket
    }
}
```

I don't know enough about how the SDK and REST API work to know whether this is a configuration problem, an issue with this lib, or some kind of bug with the API. All I know at this point is that the IAM user should have full access to S3, so HeadBucket should work, but it is not despite all other operations succeeding. The reason this seems strange is that v2.8 does work, though it seems like someone explicitly added a way to skip 403 responses during HeadBucket for some reason.

Thanks for the assistance.

**Comment by kstich** [comment]
Is it possible that your `$bucketName` has a portion of a key in it? A raw test bucket as `'test-bucket'` call on doesBucketExist is working, but `'test-bucket/test'` is returning false through a 403.

**Comment by lookitsatravis** [comment]
@kstich I double checked that, and the bucket env var is correct. I also dumped it out at the point where the client makes the `doesBucketExist`and `$bucketName` is correct. Looking at the S3Exception message, the correct bucket path is listed. Full text of that message:

```
'Error executing "HeadBucket" on "https://nsc-dev.s3.amazonaws.com/"; AWS HTTP error: Client error: `HEAD https://nsc-dev.s3.amazonaws.com/` resulted in a `403 Forbidden` response  (client): 403 Forbidden (Request-ID: D0C64BE8CF22F24D) -
```

I mean, it really seems like there is something wrong with the IAM credentials at this point, or something weird about how that HeadBucket request is executed. Is there any other part of the S3Exception that would aid in figuring this out?

**Comment by kstich** [comment]
You can try adding the [`'debug'` flag](docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#debug) when creating your client to view the full debug log of your request.

**Comment by lookitsatravis** [comment]
@kstich - I gave that a shot, and there isn't really anything new that I have gleaned from the output. The signature is generated, and then the request is performed. The output of the request is indeed 403 Forbidden. Is there some specific information that can be off assistance? It seems like this is a configuration problem on my end, but there are so many potential points of failure, and I've checked the ones I know about, and they seem okay. What led me to post here instead of on the AWS forums is the fact that SDK v2 works as I would expect with the same credentials.

**Comment by kstich** [comment]
The difference for the V2 SDK is that, with the [`$accept403` option](http://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.S3.S3Client.html#_doesBucketExist), it's returning true on a 403 even if the bucket might not exist. This was probably it just masking your underlying issue. If you've verified the policy and ownership structure, credentials to the client you're using, and the permissions on the bucket, I'm not sure where the potential issue is.

I'd recommend seeking assistance through the [S3 Forum](https://forums.aws.amazon.com/forum.jspa?forumID=24) or [AWS Customer Support](https://aws.amazon.com/contact-us/) armed with the information you get when running with the `'debug'` flag if it's asked for.

**Comment by lookitsatravis** [comment]
Thanks for the assistance @kstich.
