### ISSUE TITLE
Help sending email attachment

### ISSUE THREAD

**Issue by thatryan** [aws/aws-sdk-php#1345]
Sorry to open an issue for this, but I cannot find any docs explaining how to do this. I need to send an email with attachment, random Googling says I have to use `send_raw_email()` but all I find are other peoples code, mostly that they say does not work. 

I see mentions that you have to set encoding and headers manually, but I do not see that told in the docs anywhere, or how to do it.

Can someone help me understand what I am missing, or where to go read how to do this?

Thank you.

**Comment by kstich** [comment]
Hi @thatryan, without a sample of your code or email, we can't help pinpoint any problem you're having. Here's the [PHP API Docs for SES' `SendRawEmail` operation](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-email-2010-12-01.html#sendrawemail), the [SES API Reference for `SendRawEmail`](http://docs.aws.amazon.com/ses/latest/APIReference/API_SendRawEmail.html), and an [SES provided Developer Guide](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-raw.html) in case they can offer some assistance.

**Comment by thatryan** [comment]
Well right now my code looks like this example ha, 

http://docs.aws.amazon.com/ses/latest/DeveloperGuide/examples-send-using-sdk.html#SDK for PHP

Which is great, I have it working yay. But having trouble finding examples in that format for setting MIME types, what is a boundary, all that stuff...

**Comment by thatryan** [comment]
Here is my current code, nothing is sending for me.

https://gist.github.com/thatryan/6076cb3165c559f66793745c5b9c9fa5

I tried `echo` and `error_log()` to output something, I have a file with `777` permissions named ses_errors.log that I am trying to output to when calling this script,

`php /mypath/ses-send-mail.php > /logs/ses_errors.log`

But nothing writes there.

Additionally, every time I run this, I get the following fatal error,

`PHP Fatal error:  Class 'SimpleXMLElement' not found in /home/ubuntu/vendor/aws/aws-sdk-php/src/Api/Parser/PayloadParserTrait.php on line 39`

Thank you much.

**Comment by thatryan** [comment]
Sorry, an update. Realized the server was on PHP 5.6 so I upgraded to 7.1 and ran again, this time it output a stack trace on that error,

    PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /home/ubuntu/vendor/aws/aws-sdk-php/src/Api/Parser/PayloadParserTrait.php:39
    Stack trace:
    #0 /home/ubuntu/vendor/aws/aws-sdk-php/src/Api/ErrorParser/XmlErrorParser.php(28): Aws\Api\ErrorParser\XmlErrorParser->parseXml(Object(GuzzleHttp\Psr7\Stream))
    #1 [internal function]: Aws\Api\ErrorParser\XmlErrorParser->__invoke(Object(GuzzleHttp\Psr7\Response))
    #2 /home/ubuntu/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(175): call_user_func(Object(Aws\Api\ErrorParser\XmlErrorParser), Object(GuzzleHttp\Psr7\Response))
    #3 /home/ubuntu/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(101): Aws\WrappedHttpHandler->parseError(Array, Object(GuzzleHttp\Psr7\Request), Object(Aws\Command), Array)
    #4 /home/ubuntu/vendor/guzzlehttp/promises/src/Promise.php(203): Aws\WrappedHttpHandler->Aws\{closure}(Array)
    #5 /home/ubuntu/vendor/guzzlehttp/promises/src/Promise.php(174): GuzzleHttp\Promise\Promise::callHandler(2, Array, Array)
    #6 /home/ubuntu/vendor/guzzlehttp/promises/sr in /home/ubuntu/vendor/aws/aws-sdk-php/src/Api/Parser/PayloadParserTrait.php on line 39

**Comment by kstich** [comment]
See #1341 for tracking the `SimpleXMLElement` dependency update. Will continue to look in to your issue as well.

**Comment by kstich** [comment]
Try removing the [`base64_encode` call around `$header` here](https://gist.github.com/thatryan/6076cb3165c559f66793745c5b9c9fa5#file-sesmail-php-L52) - via #1295.

Additionally, your [`'Source'` and `'Destinations'` parameters should not be inside `RawMessage`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-email-2010-12-01.html#sendrawemail).

**Comment by thatryan** [comment]
Got it, thank you!
