### ISSUE TITLE
Cannot get identity to verify

### ISSUE THREAD

**Issue by thatryan** [aws/aws-sdk-php#1347]
I have setup and enabled SPF and DKIM on my domain, and sent a test message from the console. It comes through properly and does not hit spam.

![ident-pass](https://user-images.githubusercontent.com/26583/29134717-81d13bec-7cec-11e7-9521-31b372cbd16a.png)

However when adding the ident info to the `sendRawEmail()` it does not get added proper and email goes to spam.

![ident-fail](https://user-images.githubusercontent.com/26583/29134755-9e176506-7cec-11e7-9939-cbe46182086c.png)

My attempt to add is like this,

	$source_email_id = 'verififed@mydomain.com';

	$result = $client->setIdentityMailFromDomain([
	    'BehaviorOnMXFailure' => 'UseDefaultValue',
	    'Identity' => $source_email_id,
	    'MailFromDomain' => 'bounces.mydomain.com',
	]);

	$result = $client->setIdentityDkimEnabled([
	    'DkimEnabled' => true,
	    'Identity' => $source_email_id,
	]);

Am I doing something wrong here?

Thank you!

**Comment by kstich** [comment]
@thatryan Are you specifying the identity you created via the `'SourceArn'` option to the `sendRawEmail()` parameters as [documented in the API docs](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-email-2010-12-01.html#sendrawemail) or specifying the `'X-SES-SOURCE-ARN'` as [stated in this guide](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/sending-authorization-delegate-sender-tasks-email.html)?

**Comment by thatryan** [comment]
No I did not, I suck at this documentation sorry. I thought my two functions above handled assigning it, so I should use the `sourceArn` instead of or in addition to?

**Comment by thatryan** [comment]
Yeah I took this function straight from the docs,

	$result = $client->sendRawEmail([
	    'Destinations' => [ $dest_email_id
	    ],
	    'RawMessage' => [
	        'Data' => $header,
	    ],
	    'Source' => $source_email_id,
	    'SourceArn' => $source_arn,
	]);

The `$sourceArn` variable is a string up top that I copy/pasted from the console here..

![arn](https://user-images.githubusercontent.com/26583/29141999-4aee6cb2-7d05-11e7-8425-328c89c5061a.png)

**Comment by kstich** [comment]
The operations you're performing above are adding information to the identity, the `sendRawEmail` needs to know which identity to grab its extra information from. That is the correct place to find the Identity ARN via the console. Has this solved your issue?

**Comment by thatryan** [comment]
No, I removed those two operations and changed my sendRawEmail function to the one I just posted using the arn. However, still goes to spam with the same identity info as in first post.
