### ISSUE TITLE
Can't Upload Directory

### ISSUE THREAD

**Issue by danielclariondoor** [aws/aws-sdk-php#1348]
The directory in question is 16GB.
My code look like this:
`$this->s3->uploadDirectory($ul, $this->s3Bucket);`

After some time, I always receive this error:
An exception occurred while uploading parts to a multipart upload. The following parts had errors:
\- Part 8: Error executing "UploadPart" on "https://iso-erc.s3-us-west-1.amazonaws.com/20170731104752770/GL-CW-04012017-V01/MN/ERC-GL-MN-04012017-V02/RC-GL-MN-04012017-V02/DS-GL-MN-04012017-V02.xls?partNumber=8&uploadId=nlf1AIXVP2U5xyt7j4.hn.OdvDaC429CGkxsc32ORYqrahMyUZuq0jZxuJXQIZgFsEO.93hBaTl8W0NIprWLMBCpGDKG3ujkSPpiGlPrKjk-"; AWS HTTP error: cURL error 55: SSL write: error -5961 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by imshashank** [comment]
@danielclariondoor Sorry to hear about this. Can you please share which version of SDK, you are using? 
And does this error occur on every request or just sometimes.

**Comment by danielclariondoor** [comment]
version 3.32.5
This does not occur when I'm uploading when a 6GB directory, but it happens every time I try to upload a 15GB directory.
I am able to upload the directory using the CLI however.

**Comment by kstich** [comment]
Is this inconsistent or the same file and part every time? Can you please also post how you're creating the client at `$this->s3`? Have you tried using [the `'debug'` option](docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#debug) to see more detail about the specific failure?

**Comment by kstich** [comment]
Do you have an update on this issue @danielclariondoor ?

**Comment by danielclariondoor** [comment]
Different files I believe. 
I'm creating my s3 client using a symfony framework service call:
  <service id="iso.erc.package.manager" class="Iso\RaterBundle\Erc\PackageManager">
            <argument type="service" id="aws.sdk3.s3" />
            <argument>%s3_erc_bucket%</argument>
        </service>
I do not know how to turn the debug option on.
As a workaround, I am deleting files I don't need from the directory before uploading.

**Comment by kstich** [comment]
You'll need to pass a `debug="true"` to wherever you define your aws service:

```xml
<aws:S3 version="2006-03-01" debug="true"/>
```

**Comment by danielclariondoor** [comment]
Thanks. This is helpful. I will try it.

**Comment by kstich** [comment]
Closing issue on lack of response, please reply with any update.
