### ISSUE TITLE
Use Inside a Class

### ISSUE THREAD

**Issue by thatryan** [aws/aws-sdk-php#1350]
Application I inherited is built on Code Igniter, there is a mail function inside of a class that I need to make work with this somehow. However, the 

	require '/home/ubuntu/vendor/autoload.php';
	use Aws\Ses\SesClient;
	use Aws\Ses\Exception\SesException;

That is PHP traits right? So cannot be used inside is that correct?

**Comment by kstich** [comment]
Those are use statements for namespaced classes, [PHP's namespace guide can be found here](http://php.net/manual/en/language.namespaces.php). You can find a [small sample of using SES with PHP here](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/examples-send-using-sdk.html#examples-send-using-sdk.php.title).

You can also ask a question on [StackOverflow](https://stackoverflow.com/) and tag it with [aws-php-sdk](http://stackoverflow.com/questions/tagged/aws-php-sdk) for further usage assistance.
