### ISSUE TITLE
Manually make public

### ISSUE THREAD

**Issue by felipedmz** [aws/aws-sdk-php#1354]
I've done a script to sync my CDN git reposiotry with s3' bucket through putObject action, but after that I have to manually access the console and execute a "make public" action.

Believe there is no method to do that by SDK.

**Comment by kstich** [comment]
You can use the [Access Control List (ACL) settings on PutObject](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html) by using the [`'ACL'` parameter on the `S3Client->putObject()` call](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#putobject). The 'Make Public' action is the equivalent of using [the `'public-read'` Canned ACL](http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#CannedACL).

**Comment by felipedmz** [comment]
Thank you @kstich
