### ISSUE TITLE
SNS Mobile push CreatePlatformApplication() does not work

### ISSUE THREAD

**Issue by doapp-ryanp** [aws/aws-sdk-php#136]
I am trying to do a [createPlatformApplication](http://docs.aws.amazon.com/aws-sdk-php-2/latest/class-Aws.Sns.SnsClient.html#_createPlatformApplication) and I keep getting the following cryptic error:

```
SNS: Top level element may not be treated as a list
```

Here is my code:

``` php
                $sns->createPlatformApplication(array(
                        'Name'=>"Tmp",
                        'Platform'=>'GCM',
                        'Attributes'=>array(
                            'PlatformPrincipal'=>'NA',
                            'PlatformCredential'=>'my valid api key'    
                        )                       
                ));
```

Has anyone else gotten this to work?  Here are api docs for more details:

http://docs.aws.amazon.com/sns/latest/api/API_CreatePlatformApplication.html
http://docs.aws.amazon.com/sns/latest/api/API_SetPlatformApplicationAttributes.html

I am successfully using getListPlatformApplicationsIterator() so I know I have things setup correctly.  Also creating platform apps via console is working just fine.

**Comment by biranchi2018** [comment]
Why this bug is closed ?
Its 2018 and the bug still exits......

sns.createPlatformApplication promise does not return anything, either success or failure.....
