### ISSUE TITLE
How to use generateSmtpPassword with PhpMailer

### ISSUE THREAD

**Issue by mandalm** [aws/aws-sdk-php#1361]
Hi team,
I was going through #833 and look like this feature is useful. But I am not sure how i can make use of it.

I am using PhpMailer with role based access model so i will not have any kind of access key and secret. I can generate password but still dont know how i can use it with php Mailer. 

All web reference tell me to use access key and secret in order to use PhpMailer SMTP. let me know if there is any other work around.

Thanks in advance.

Mithun Mandal

**Comment by kstich** [comment]
We use the GitHub issues for tracking bugs and feature requests. This would be best suited to a question on [StackOverflow](https://stackoverflow.com/) and tag it with [`aws-php-sdk`](http://stackoverflow.com/questions/tagged/aws-php-sdk).

Here's a guide on using [PHPMailer with SES](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-using-smtp-programmatically.html#send-using-smtp-php) and you can use [`$sesClient->generateSmtpPassword($credentials)`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Ses.SesClient.html#_generateSmtpPassword) to get SMTP information from a `CredentialsInterface`.
