### ISSUE TITLE
Issue with MultipartUpload in >= 3.34.2. Getting timeout response.

### ISSUE THREAD

**Issue by afust-pica9** [aws/aws-sdk-php#1363]
I am using the [league/flysystem](https://github.com/thephpleague/flysystem-aws-s3-v3) to run upload to S3 using upload method. In 3.34.2 we are getting these errors from S3:

The operation is basically reading from a url (opening a stream) which is then passed to the S3. 
This does not seem to happen all the time but at least 1/5 times.  We are not passing any custom parameters (defaults are used)

OS:  Amazon Linux AMI release 2016.03
Curl: curl 7.49.1 (x86_64-pc-linux-gnu) libcurl/7.49.1 NSS/3.24 Basic ECC zlib/1.2.8
Php: 7.0.9 (running php-fpm)

Note the curl 35 error. Not sure if that would be the issue, or just a derivative 

(**Note**: for clarity https/http prefixes were removed (they are not missing i.e. ://s3.* = https//s3.*))

`Uncaught Exception Aws\S3\Exception\S3MultipartUploadException: "An exception occurred while uploading parts to a multipart upload. The following parts had errors: - Part 3: Error executing "UploadPart" on "://s3.amazonaws.com/yyy/xxx/data/Approved/CD_3945_20170826185935.pdf?partNumber=3&uploadId=IQt.rBjwmGBoFD8_R_N_6lmYX3NObVG5pXgf9Bsooh7pqyVnDg994UiQI4I24BkuWFrwpbhf11BeapNryY8LJgY8E6uRkSoKy9wF8rUX0TClAddp.usiwYjh_IYFuMUB"; AWS HTTP error: cURL error 35: Encountered end of file (see ://curl.haxx.se/libcurl/c/libcurl-errors.html) - Part 2: Error executing "UploadPart" on "://s3.amazonaws.com/yyy/xxx/data/Approved/CD_3945_20170826185935.pdf?partNumber=2&uploadId=IQt.rBjwmGBoFD8_R_N_6lmYX3NObVG5pXgf9Bsooh7pqyVnDg994UiQI4I24BkuWFrwpbhf11BeapNryY8LJgY8E6uRkSoKy9wF8rUX0TClAddp.usiwYjh_IYFuMUB"; AWS HTTP error: cURL error 35: Encountered end of file (see ://curl.haxx.se/libcurl/c/libcurl-errors.html) - Part 1: Error executing "UploadPart" on "://s3.amazonaws.com/yyy/xxx/data/Approved/CD_3945_20170826185935.pdf?partNumber=1&uploadId=IQt.rBjwmGBoFD8_R_N_6lmYX3NObVG5pXgf9Bsooh7pqyVnDg994UiQI4I24BkuWFrwpbhf11BeapNryY8LJgY8E6uRkSoKy9wF8rUX0TClAddp.usiwYjh_IYFuMUB"; AWS HTTP error: Client error: PUT ://s3.amazonaws.com/yyy/xxx/data/Approved/CD_3945_20170826185935.pdf?partNumber=1&uploadId=IQt.rBjwmGBoFD8_R_N_6lmYX3NObVG5pXgf9Bsooh7pqyVnDg994UiQI4I24BkuWFrwpbhf11BeapNryY8LJgY8E6uRkSoKy9wF8rUX0TClAddp.usiwYjh_IYFuMUB resulted in a 400 Bad Request response:  RequestTimeoutYour socket connection to the server w (truncated...) RequestTimeout (client): Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. -  RequestTimeoutYour socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.F5E729A38A40DC4Btg62PcN1ACjdUQsGBFY1SNUDOdc0CRJ3BowcTgAcg5cavdFm70k/VxsNxC4sNTwdcKm6XAEVRtg= " at /srv/www/vendor/aws/aws-sdk-php/src/Multipart/AbstractUploadManager.php line 127 {"exception":"[object] (Aws\S3\Exception\S3MultipartUploadException(code: 0): An exception occurred while uploading parts to a multipart upload. The following parts had errors:\n- Part 3: Error executing \"UploadPart\" on \"://s3.amazonaws.com/yyy/xxx/data/Approved/CD_3945_20170826185935.pdf?partNumber=3&uploadId=IQt.rBjwmGBoFD8_R_N_6lmYX3NObVG5pXgf9Bsooh7pqyVnDg994UiQI4I24BkuWFrwpbhf11BeapNryY8LJgY8E6uRkSoKy9wF8rUX0TClAddp.usiwYjh_IYFuMUB\"; AWS HTTP error: cURL error 35: Encountered end of file (see ://curl.haxx.se/libcurl/c/libcurl-errors.html)\n- Part 2: Error executing \"UploadPart\" on \"://s3.amazonaws.com/yyy/xxx/data/Approved/CD_3945_20170826185935.pdf?partNumber=2&uploadId=IQt.rBjwmGBoFD8_R_N_6lmYX3NObVG5pXgf9Bsooh7pqyVnDg994UiQI4I24BkuWFrwpbhf11BeapNryY8LJgY8E6uRkSoKy9wF8rUX0TClAddp.usiwYjh_IYFuMUB\"; AWS HTTP error: cURL error 35: Encountered end of file (see ://curl.haxx.se/libcurl/c/libcurl-errors.html)\n- Part 1: Error executing \"UploadPart\" on \"://s3.amazonaws.com/yyy/xxx/data/Approved/CD_3945_20170826185935.pdf?partNumber=1&uploadId=IQt.rBjwmGBoFD8_R_N_6lmYX3NObVG5pXgf9Bsooh7pqyVnDg994UiQI4I24BkuWFrwpbhf11BeapNryY8LJgY8E6uRkSoKy9wF8rUX0TClAddp.usiwYjh_IYFuMUB\"; AWS HTTP error: Client error: PUT ://s3.amazonaws.com/xxx/yyy/data/Approved/CD_3945_20170826185935.pdf?partNumber=1&uploadId=IQt.rBjwmGBoFD8_R_N_6lmYX3NObVG5pXgf9Bsooh7pqyVnDg994UiQI4I24BkuWFrwpbhf11BeapNryY8LJgY8E6uRkSoKy9wF8rUX0TClAddp.usiwYjh_IYFuMUB resulted in a 400 Bad Request response:\n\nRequestTimeoutYour socket connection to the server w (truncated...)\n RequestTimeout (client): Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. - \nRequestTimeoutYour socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.F5E729A38A40DC4Btg62PcN1ACjdUQsGBFY1SNUDOdc0CRJ3BowcTgAcg5cavdFm70k/VxsNxC4sNTwdcKm6XAEVRtg=\n at /srv/www/vendor/aws/aws-sdk-php/src/Multipart/AbstractUploadManager.php:127)"}`

**Comment by imshashank** [comment]
@afust-pica9 Hi, I am not really familiar with league/flysystem. Please give us some time to analyze. It will be really helpful if you can share the code snippet used for uploading this file. Also, what is the average size of file that you are trying to upload.

**Comment by afust-pica9** [comment]
@imshashank see snippet. They about 10~ 15megabytes

```php
use GuzzleHttp\Psr7;
use League\Flysystem\File;
use Pica9\Core\Filesystem\FileLocator;
use League\Flysystem\FilesystemInterface;


//omited...
    public static function download($remoteFile, $localFile, FilesystemInterface $filesystem)
    {   
        $remote = Psr7\try_fopen($remoteFile, 'rb');
    
        $filesystem->putStream($localFile, $remote);
        if (is_resource($remote)) {
            fclose($remote);
        }
    }   

I believe though it might be related to cURL [curl google storage](https://github.com/GoogleCloudPlatform/google-cloud-php/issues/91)

For now I rebooted my php-fpm and changed cUrl to 
curl 7.40.0 (x86_64-redhat-linux-gnu) libcurl/7.40.0 NSS/3.21 Basic ECC zlib/1.2.8 libidn/1.18 libssh2/1.4.2


```

**Comment by imshashank** [comment]
@afust-pica9 Thanks for sharing the code but I don't see AWS PHP SDK being used in the example code you shared with us. 

I have tested multipartUploaded locally and did not see these errors. It will be helpful if you can share the multipartUploader code as well so I can try to reproduce the errors.

**Comment by afust-pica9** [comment]
@imshashank sure. 

Flysytem wraps aws; I dont call it directly.  [flysystem](https://github.com/thephpleague/flysystem)

Here is the relevant code from flystem:

https://github.com/thephpleague/flysystem/blob/master/src/Filesystem.php#L108

which calls the AWS Adapter, which is the included as a dependency [aws](https://github.com/thephpleague/flysystem-aws-s3-v3)

comoser.json looks like this
```
"league/flysystem": "^1.0",
"league/flysystem-aws-s3-v3": "^1.0"
``

**Comment by kstich** [comment]
I'm unable to recreate this issue by passing in a stream opened in the same way as your code and how flysystem uploads the file. Can you retrieve the contents of `$filesystem->getConfig()` before your call to `$filesystem->putStream($localFile, $remote);` please?

Additionally, #1326 was a similar issue related to flysystem and the S3 `MultipartUploader` functionality - please make certain you're running version 3.31.3 or higher of the SDK.

**Comment by fjmoralesp** [comment]
Hi!!

We have the same issue here, this code shows how is `flysystem-aws-s3-v3` using asw php sdk:

```
/**
     * Upload an object.
     *
     * @param        $path
     * @param        $body
     * @param Config $config
     *
     * @return array
     */
    protected function upload($path, $body, Config $config)
    {
        $key = $this->applyPathPrefix($path);
        $options = $this->getOptionsFromConfig($config);
        $acl = array_key_exists('ACL', $options) ? $options['ACL'] : 'private';

        if ( ! isset($options['ContentType'])) {
            $options['ContentType'] = Util::guessMimeType($path, $body);
        }

        if ( ! isset($options['ContentLength'])) {
            $options['ContentLength'] = is_string($body) ? Util::contentSize($body) : Util::getStreamSize($body);
        }

        if ($options['ContentLength'] === null) {
            unset($options['ContentLength']);
        }

        $this->s3Client->upload($this->bucket, $key, $body, $acl, ['params' => $options]);

        return $this->normalizeResponse($options, $key);
    }
```

The S3 Client es instanced in the constructor like this:

```
/**
     * Constructor.
     *
     * @param S3Client $client
     * @param string   $bucket
     * @param string   $prefix
     * @param array    $options
     */
    public function __construct(S3Client $client, $bucket, $prefix = '', array $options = [])
    {
        $this->s3Client = $client;
        $this->bucket = $bucket;
        $this->setPathPrefix($prefix);
        $this->options = $options;
    }
```
which is loaded before the class:

`use Aws\S3\S3Client;`

**Comment by kstich** [comment]
Can you please supply the versions of the AWS SDK for PHP, Flysystem, and Flysystem Aws S3 V3 adaptor you're using? Can you also update with a code sample of how you're invoking the `->upload()` function?

**Comment by fjmoralesp** [comment]
Sure:

`league/flysystem` version `1.0.40`
`aws/aws-sdk-php` version `3.31.2`
`league/flysystem-aws-s3-v3` version `1.0.18`

Example:

```
<?php
namespace MyProject\Reports;

use PublicDisk;
use TemporalDisk;

class class DataSerializer
{
    public function movetoAws($myFile)
    {
        $path = 'app/myfiles';
        $fileName = 'myTestFile';

        PublicDisk::put($path . $fileName, fopen($myFile, 'r'));
        TemporalDisk::delete($myFile);

        return $path . $fileName;
    }
}

```

**Comment by kstich** [comment]
@fjmoralesp Your issue is likely then the same as #1326 - please update to 3.31.3 or higher.

**Comment by fjmoralesp** [comment]
Thanks!!

**Comment by afust-pica9** [comment]
@kstich using 3.35.2.

**Comment by afust-pica9** [comment]
@kstich I'll get you this: `Can you retrieve the contents of $filesystem->getConfig() `

**Comment by afust-pica9** [comment]
@kstich 
Here is the  pattern that I'm seeing: 
We are running php-fpm; When we restart php-fpm, uploads are fine for a period of time. 
We are now using sdk 3.35.2. But after a while, the failures start (a few days). It seems that something is not cleaning up correctly or/and get corrupted. 

I'm wondering if I should pass a curl CURLOPT_FORBID_REUSE to close the connection. 

I looked at our logs and all the failures wrt to uploads stared just about the sdk 3.33.1 Aug 15. 

I don't believe we made substantial changes on our side.

**Comment by afust-pica9** [comment]
@kstich  here is the config. Nothing really: 

object(League\Flysystem\Config)#510 (2) {
  ["settings":protected]=>
  array(0) {
  }
  ["fallback":protected]=>
  NULL
}

What seems to solve it is 'rebooting' php-fpm. I set a minimal request, and then php-fpm re spawn a child

**Comment by kstich** [comment]
Thanks for all of the info @afust-pica9. I'll be taking another pass at attempting to reproduce your issue based on it.

However, it looks like there weren't any updates in 3.33.0 or 3.33.1 that affected S3 or the underlying layers. Do you happen to know what version of the SDK you were on before the issue arose?

**Comment by kstich** [comment]
I'm still unable to reproduce your issue @afust-pica9. Can you try [enabling debug logging](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#debug) and supplying the contents for a failed upload?

**Comment by kstich** [comment]
Closing due to lack of reply. Please let us know here if there's any new information.
