### ISSUE TITLE
3.35.2 release error in code

### ISSUE THREAD

**Issue by HowdyMedia** [aws/aws-sdk-php#1366]
Parse error: syntax error, unexpected '$value' (T_VARIABLE) in phar:///var/www/html/****/aws.phar/Aws/functions.php on line 36

**Comment by kstich** [comment]
[Generators were added in PHP 5.5](http://php.net/manual/en/migration55.new-features.php), which is the [minimum version for the PHP SDK](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/getting-started/requirements.html#minimum-requirements).

**Comment by HowdyMedia** [comment]
I see that the server instance was tripping on "yield" while using PHP version 5.4.34. Generators became available in PHP 5.5.0, so it is a requirement to use the latest version of the API.

**Comment by HowdyMedia** [comment]
Beat me to it kstich, Didn't respond soon enough...
