### ISSUE TITLE
Support for S3 Transfer Acceleration?

### ISSUE THREAD

**Issue by coredumperror** [aws/aws-sdk-php#1372]
Does this SDK support S3 Transfer Acceleration? The docs on AWS don't seem to indicate that it supports it directly. But it seems like it should be as easy as changing the domain name of the s3 service. Unfortunately, seeing a custom domain name within the S3 leads to some odd errors. 

Is there a better way to supports S3 Transfer Acceleration, or does that just not work in the PHP SDK?

**Comment by kstich** [comment]
[S3 Transfer Acceleration](http://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html) is done through `'use_accelerate_endpoint'` and `'use_dual_stack_endpoint'` [options on the S3Client that can also be configured at a per-operation level.](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.S3.S3Client.html#___construct)

**Comment by arijitdas7** [comment]
use Aws\S3\S3Client;
require_once 'plugins/aws_vendor/autoload.php'; // this is your aws-php-sdk autoload file path

// set the arguments properly        
$option_ar = array(
            'version'	=> 'latest',
            'region'    => 'eu-west-1',
            'credentials' => array(
                'key'    => awsAccessKey,
                'secret' => awsSecretKey,
            ),
            'use_accelerate_endpoint' => true // before use transfer accelerator, you must enabled this from your bucket properties.
        );
        $s3 = new S3Client($option_ar);
