### ISSUE TITLE
Check if the EC2 instance has permissions using roles

### ISSUE THREAD

**Issue by AdrianAntunez** [aws/aws-sdk-php#1374]
Hi there!

I am trying to check through my php app if my EC2 instance  is allowed to perform a set of actions using roles.
According to the AWS CLI documentation I could use the dryrun command which checks if the action being called is allowed or not. Unfortunately I didn't find the dryrun parameter in the aws sdk PHP. Is there something that I'm missing? Is there any alternative that I could use to check whether I have permission to perform some actions or not?

Thank you so much in advance and keep on going with the good work!

Adrian

**Comment by kstich** [comment]
Many of [the EC2 api operations provide their own 'DryRun' parameter](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-ec2-2016-11-15.html).

**Comment by AdrianAntunez** [comment]
Hi @kstich,

Thanks for the fast reply. The methods you pointed out are all EC2 related but what about the interaction with other services like S3, firehouse, SQS... These are the ones I am interested in but I couldn't find any dryrun implementation in those services.

Regards,

Adrian

**Comment by kstich** [comment]
The SDKs don't provide a separate 'DryRun' parameter aside from what services may provide. The `--dry-run` option [visible in the CLI documentation](http://docs.aws.amazon.com/cli/latest/userguide/getting-help.html) is an example to show the functionality that uses the EC2 operation `describe-instances`.

**Comment by AdrianAntunez** [comment]
In fact most S3 commands have the dryrun option as it is pointed out here: https://docs.aws.amazon.com/cli/latest/reference/s3/cp.html so I am wondering why it has not been implemented in aws-sdk-php

**Comment by kstich** [comment]
That documentation is for the CLI S3 custom commands (cp, mv, etc.) and it only prints the commands that it will attempt to run if you invoke it without `--dry-run`. It doesn't do any permissions checking to see if these operations could be performed with the current role.
