### ISSUE TITLE
Unexpected compilations when running make compile-json

### ISSUE THREAD

**Issue by rquadling** [aws/aws-sdk-php#1377]
I've only just started using aws-sdk-php. Needed to add a waiter for RDS DBSnapshot (https://github.com/aws/aws-sdk-php/pull/1370).

When running the `make compile-json` command to build the new waiter script, additional compilations took place. This would suggest that the .json and .php are out of step with each other.

I've created a PR to fix the mismatch - https://github.com/aws/aws-sdk-php/pull/1376

**Comment by kstich** [comment]
These occur due to differences in PHP versions for running compile-json in and would be rewritten by our process. Thanks for pointing them out though!

**Comment by rquadling** [comment]
Seems 0.0 is written rather than 0 for some values.
