### ISSUE TITLE
URI parsing for "s3://bucket/key" format

### ISSUE THREAD

**Issue by fitztrev** [aws/aws-sdk-php#1383]
The `Aws\S3\S3UriParser` only supports parsing of URIs [with `http` scheme](https://github.com/aws/aws-sdk-php/blob/master/tests/S3/S3UriParserTest.php).

I have a [stream URI](https://github.com/aws/aws-sdk-php/blob/master/docs/service/s3-stream-wrapper.rst) in the format of `s3://bucket/key` that I was trying to parse with it. Could support for that format be added?

**Comment by kstich** [comment]
It looks like `s3://` URIs are being sent to the custom endpoint parser, as they don't match the S3 pattern regex, where they fail to be parsed properly. I think we can add some support for this.
