### ISSUE TITLE
SDK v2 StsClient::createCredentials misaligned with API

### ISSUE THREAD

**Issue by mateusz** [aws/aws-sdk-php#1388]
StsClient in SDK v2 seems to have a bug in `createCredentials` function - `Credentials` constructor expects a UNIX timestamp as a fourth param, but the API seems to respnd with a date formatted like `1970-01-01T00:00:00Z` in Credentials/Expiration.

**Comment by kstich** [comment]
We are not currently writing updates for v2 of the AWS SDK for PHP. If you'd like to submit a fix, please create a pull request based on a [branch of v2.8](https://github.com/aws/aws-sdk-php/tree/2.8).

As a workaround, you can set the `'Credentials/Expiration'` value on the `$result` before passing it to `createCredentials`:

```php
$result->setPath(
    'Credentials/Expiration',
    strtotime($result->getPath('Credentials/Expiration'))
);
```
