### ISSUE TITLE
SDK for just S3

### ISSUE THREAD

**Issue by chumanfu** [aws/aws-sdk-php#1393]
Is there anyway that you can create separate releases for each AWS service as well as the full SDK.
I would like to use the SDK for just S3 operations.

I need to ship software to clients with the SDK included and I don't want to increase the footprint due to a 3rd party library. My customer downloading the SDK is not an option either.

**Comment by kstich** [comment]
Closing this as a duplicate of #808. Please chime in there with your use case(s).
