### ISSUE TITLE
ResultPaginator can't paginate when Marker supplied

### ISSUE THREAD

**Issue by origaminal** [aws/aws-sdk-php#1396]
Found out that if you try to launch pagination with `ResultPaginator` starting at a particular `Marker` it will loop infinitely returning the same set of results laying after the initial `Marker`. It is caused by the `createNextCommand` function:
https://github.com/aws/aws-sdk-php/blob/85b15fba8402f02c6804075a14df0f240a99b156/src/ResultPaginator.php#L144-L147

The code correctly defines a next marker value with the `NextMarker || Contents[-1].Key` expression but can't override the initial marker. The expression `$args + ($nextToken ?: [])` will preserve values of the first array when the corresponding keys exist in the both arrays. Could `array_merge` be used instead?

**Comment by kstich** [comment]
Can you please supply a small snippet of code that shows how you're setting up your pagination to run in to this issue?

**Comment by Flythe** [comment]
Ran into the same problem a couple of days ago.

Snippet:
        
```
$results = $s3->getPaginator('ListObjects', [
     'Bucket' => 'bucket',
     'Prefix' => 'prefix/',
     'Marker' => 'marker'
]);

$key_arr = [];
        
foreach ($results->search('Contents[].Key') as $key) {
     $key_arr[] = $key;
}

echo count(array_unique($key_arr));
echo count($key_arr);
```

**Comment by kstich** [comment]
Thanks for the extra information @Flythe, I've confirmed this issue.
