### ISSUE TITLE
Error when running getObject()

### ISSUE THREAD

**Issue by aas395** [aws/aws-sdk-php#1398]
I have a script that's looping through a list of the files outputted by a call to listObjectsV2() for one of my buckets and downloading them. On my local machine (Mac OSX 10.12.6, PHP 5.5.38, SDK version 3.36.28) this works fine, but on our production environment (AWS Linux 2016.09), I'm getting this error:

`Error executing "GetObject" on <full S3 file name>; AWS HTTP error: Directory <directory name> does not exist for sink value of <last folder and file name>.`

The production environment uses a different bucket than my local environment, but the permissions between these two buckets look equivalent and this error makes me think that the folder doesn't exist, when the path I'm using for the getObject() call is coming directly from the output of listObjectsV2().

If I can provide any other information to help get to the bottom of this, please let me know.

**Comment by kstich** [comment]
It looks like the directory that you're trying to save your file(s) to does not exist, as we pass [this error from Guzzle](https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L363). You can [try using the `Transfer` manager (based on `ListObjects`) that will create directories for you](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-transfer.html#downloading-an-amazon-s3-bucket).

**Comment by aas395** [comment]
Hi Kevin,

Thank you so much for your quick response. It turns out this was an issue on my end. I had looked in the appropriate Guzzle file before submitting this to you, but I had misunderstood what the "sink" represented.

Thanks again!
