### ISSUE TITLE
Setting use_path_style_endpoint on S3Client has no effect on PostObjectV4

### ISSUE THREAD

**Issue by frankroch** [aws/aws-sdk-php#1399]
So when i create a S3Client with use_path_style_endpoint set to true like this:

```php
$s3 = new Aws\S3\S3Client(array(
	'version' => 'latest',
	'region' => 'eu-west-1',
	'endpoint' => 'http://myendpoint',
	'use_path_style_endpoint' => true,
	'credentials' => array(
		'key' => $cfg['s3']['access'],
		'secret' => $cfg['s3']['secret']
	)
));
```

I expected the following use of PostObjectV4 return a path style endpoint for the action attribute like this http://myendpoint/mybucket

```php
$post = new Aws\S3\PostObjectV4($s3, 'mybucket', array('acl'=>$acl,'key'=>$prefix.'/${filename}'), $policy);
var_dump($post->getFormAttributes())
```

instead it still gives me a action attribute of http://mybucket.myendpoint

Am i missing something, is this intended?

**Comment by kstich** [comment]
It looks like `PostObjectV4` is [handling the uri generation itself](https://github.com/aws/aws-sdk-php/blob/master/src/S3/PostObjectV4.php#L142-L159). We should also look at other abstractions that take an `S3Client` object and update them to obey `$s3->getConfig['use_path_style_endpoint']`. Thanks for the report!
