### ISSUE TITLE
GetObject responding with wrong host

### ISSUE THREAD

**Issue by antonioribeiro** [aws/aws-sdk-php#1400]
I'm using Laravel, which uses Flysystem, which uses `"aws/aws-sdk-php":"^3.0.0"`

So when getting the remote file URL it sends a GetObject request, which is bringing back this response:

![image](https://user-images.githubusercontent.com/3182864/31726523-fb4fbfc0-b405-11e7-8aa9-4573fb544500.png)

As you can see it added the prefix `pragmarx`to the host, but if use this final URL, browser will tell: 

```
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
```

Because the actual public URL does not have it:

![image](https://user-images.githubusercontent.com/3182864/31726538-03c64dae-b406-11e7-9241-40e11cc4ffdd.png)

Is there a way to get the real public URL?

**Comment by kstich** [comment]
Those are pieces of the request object, not the response. After receiving the result from S3, you can find the URL at `$result['@metadata']['effectiveUri']`.

**Comment by antonioribeiro** [comment]
It's all happening inside the AWS sdk, so there's no "I can find the URL at...", but debugging it further we can see that the effectiveUri is coming to the sdk exactly the way I'm getting it in the "outside": 

![image](https://user-images.githubusercontent.com/3182864/31792404-ae50c516-b4fa-11e7-9e77-e554c07cd2e7.png)

This is from`Aws\WrappedHttpHandler::parseResponse()`.

**Comment by kstich** [comment]
Can you provide a sample piece of code, including the `'Bucket'` and `'Key'` parameters, that's resulting in the `GetObject` request you have in the original image? I'm unable to reproduce your issue without duplicating the bucket name into the 'Key' parameter as well.

**Comment by antonioribeiro** [comment]
This is how it's been executed:

![image](https://user-images.githubusercontent.com/3182864/31795860-2cc1f536-b506-11e7-91a5-0b83f612fd1c.png)

I'm adding the bucket to the path because, when I don't, I get an URL back without it:

![image](https://user-images.githubusercontent.com/3182864/31795989-aedd74c8-b506-11e7-89fe-e47897ead8b5.png)

**Comment by kstich** [comment]
You should not be including the bucket name in the key; that is likely the cause of your issue here.

The SDK uses virtual host style URIs for S3 by default, whereas the console shows path style. You can [read more on virtual host or path style URIs here](http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html). If you want the SDK to use path style URIs, try the [`'use_path_style_endpoint'` option when creating your `S3Client`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.S3.S3Client.html#___construct).

**Comment by antonioribeiro** [comment]
I've tried it before. Not including the bucket name in the key results in the same: bucket being added as subdomain of s3, but not added to the URL path:

![image](https://user-images.githubusercontent.com/3182864/31798757-5910c690-b514-11e7-9119-976a51aa3494.png)

This is how I'm testing it now:

``` php
Route::get('/backup/get', function () {
    $bucket = env('AWS_BUCKET'); // = pragmarx
    $key = 'backup/databases/most-recent/[removed].backup.sql.gz';
    try {
        //Create a S3Client
        $s3Client = new S3Client([
            'region' => env('AWS_REGION'), // us-east-1
            'version' => '2006-03-01',
            'credentials' => CredentialProvider::env()
        ]);
        $result = $s3Client->getObject([
            'Bucket'     => $bucket,
            'Key'        => $key,
        ]);
    } catch (S3Exception $e) {
        echo $e->getMessage() . "\n";
    }
});
```

**Comment by kstich** [comment]
That is the correctly rendered virtual host style URI. Getting explicitly the path style URI, matching what you see on the console, requires using the `'use_path_style_endpoint'` mentioned above.

The following URIs resolve to the same file:

S3 Console link (_path style_): 
```://s3.amazonaws.com/pragmarx/backup/databases/most-recent/[something].backup.sql.gz```
SDK `'effectiveUri'` (_virtual host style_): 
```://pragmarx.s3.amazonaws.com/backup/databases/most-recent/[something].backup.sql.gz```
