### ISSUE TITLE
Using MockHandler doesn't work when using SesClient

### ISSUE THREAD

**Issue by santigarcor** [aws/aws-sdk-php#1407]
I'm using the 3.36.26 sdk version, and I'm following what the [docs](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/handlers-and-middleware.html) say about mocking the handlers when writing tests:

```php
$mockHandler = new MockHandler();
$mockHandler->append(new Result(['result']));

$client = new SesClient([
    'region' => 'us-east-2',
    'version' => 'latest',
    'handler' => $mockHandler,
]);

$client->verifyEmailIdentity([
    'EmailAddress' => 'email@email.com'
]);

```

But I'm getting this exception `Aws\Exception\CredentialsException: Error retrieving credentials from the instance profile metadata server. `.

Am I missing something or is there a real problem with that mock?

**Comment by kstich** [comment]
This issue comes from not having your credentials set up correctly. The `MockHandler` will return the supplied response(s), but the SDK still needs a valid credential set to construct the requests. Please see [this guide for setting up your credentials](docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#credentials).

**Comment by tinpotnick** [comment]
I am researching this at the moment. But what if I don't want credentials in every test environment? For example, automated testing or other users who do not have access to a live AWS environment - ideally, you want to mock so they don't need AWS access or credentials.

**Comment by SamRemis** [comment]
@tinpotnick, 
Not sure exactly what you're trying to do, but if you're trying to initialize any client without credentials, the way we normally do it is by setting `'credentials' => false` on the client constructor.  I believe this would get rid of the error
