### ISSUE TITLE
Intermittent exceptions whilst pushing/popping items on queue

### ISSUE THREAD

**Issue by luukau** [aws/aws-sdk-php#1408]
Hi,

I get _intermittent_ exceptions whilst executing 'ReceiveMessage',  'SendMessage' and "DeleteMessage' calls to push/pop & delete messages from a test queue. Error messages are provided below, as they are 2 different exceptions at times.

Using the following components: 
- PHP 7
- CakePHP 3.5.4, using https://github.com/lorenzo/cakephp-sqs 
- AWS SDK 3.36.28
- Guzzle 6.3.0 (I think)
- curl 7.47.0
- OpenSSL 1.0.2g

Error 1 - failed to open stream
```
Exception: Error executing "ReceiveMessage" on "https://sqs.ap-southeast-2.amazonaws.com/***********/test-q1"; AWS HTTP error: Error creating resource: [message] fopen(https://sqs.ap-southeast-2.amazonaws.com/***********/test-q1): failed to open stream: HTTP request failed! 
[file] /var/local/rnd/source/worker-template/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 324 in [/var/local/rnd/source/worker-template/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php, line 192]
2017-10-20 05:47:11 Error: [Aws\Sqs\Exception\SqsException] Error executing "ReceiveMessage" on "https://sqs.ap-southeast-2.amazonaws.com/***********/test-q1"; AWS HTTP error: Error creating resource: [message] fopen(https://sqs.ap-southeast-2.amazonaws.com/***********/test-q1): failed to open stream: HTTP request failed! 
[file] /var/local/rnd/source/worker-template/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 324 in /var/local/rnd/source/worker-template/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 192
```

Error 2 - Failed to enable crypto
```
Error executing "ReceiveMessage" on "https://sqs.ap-southeast-2.amazonaws.com/***********/test-q1"; AWS HTTP error: Error creating resource: [message] fopen(): Failed to enable crypto
[file] /var/local/rnd/source/worker-template/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 324
[message] fopen(https://sqs.ap-southeast-2.amazonaws.com/***********/test-q1): failed to open stream: operation failed
[file] /var/local/rnd/source/worker-template/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 324 in [/var/local/rnd/source/worker-template/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php, line 192]
```

Any pointers would be most welcome :)

**Comment by kstich** [comment]
Error 1 is related to your call to `fopen` on a URL, it failed to make a request to the endpoint specified.

Error 2 looks like OpenSSL is having trouble starting up in your call to `fopen`.

Can you post a sample of your code where you're invoking the `receiveMessage()`, etc. calls?

**Comment by luukau** [comment]
Thanks @kstich.

So the CakePHP CLI calls the following:
```
    public function popAll()
    {
        $this->QueueWorker->addFunction('testQueue1', function ($item) {
            if ($this->params['verbose']) {
                debug($item);
            }            

            return true; // return true to delete the message upon processing, false to leave the message in the queue
        });
        $this->QueueWorker->work();
    }
```

which in turn calls the 'work' function
```
    public function work($name = 'default', $iterations = self::MAX_MESSAGES_PROCESSED)
    {
        $this->log(sprintf("Starting %s worker", $name), 'info', 'sqs');
        $simpleQueue = $this->getSimpleQueue();
        $i = 0;
        while ($i < $iterations) {
            foreach ($this->callbacks as $queue => $callback) {
                if (!$this->_triggerEvent('Queue.beforeWork')) {
                    break 2;
                }

                $job = $simpleQueue->receiveMessage($queue);
                if (!empty($job) && $job->get('Messages')) {
                    $this->_work($queue, $job);
                }

                if (!$this->_triggerEvent('Queue.afterWork')) {
                    break 2;
                }
            }
            if ($iterations > -1) {
                $i++;
            }
        }
    }
```
(part of the cakephp plugin https://github.com/lorenzo/cakephp-sqs) with the SimpleQueue class implementing:
```
    public function receiveMessage($taskName)
    {
        $url = $this->queueUrl($taskName);

        return $this->client()->receiveMessage(['QueueUrl' => $url]);
    }
```
And 'client' being an instance of the AWS SqsClient.

**Comment by luukau** [comment]
Any ideas @kstich?

**Comment by kstich** [comment]
It looks like these are both intermittent issues with spinning up either a cURL call or OpenSSL in a cURL call. I'd recommend starting with updating the cURL and OpenSSL installations to see if that helps resolve the issue.

**Comment by luukau** [comment]
From some strange reason the intermittent errors no longer appear. Still using the same components.
- PHP 7
- CakePHP 3.5.4, using https://github.com/lorenzo/cakephp-sqs
- Guzzle 6.3.0
- curl 7.47.0 (ubuntu 16.04)
- OpenSSL 1.0.2g
Although AWS PHP SDK is version - 3.36.34

Not sure if this newer SDK version has fixed the problem, or something else has changed (ie local machines, cloud backend). Anyway I can't replicate issue anymore so I would say it is safe to close. 

I will keep your suggestions in mind in case it pops up again (and will report back). Thanks

**Comment by luukau** [comment]
So I am getting similar errors again in our production fifo queue, albeit only on the "ReceiveMessage".

I haven't be able to establish an error pattern, other then it seems to occur randomly averaging at 4-5 times a month. 

Current s/w components:
- PHP 7
- CakePHP 3.5.17
- Guzzle 6.3.3
- AWS PHP SDK 3.82.6
- openSSL 1.02g
- curl 7.47.0

Error message is as follows:
`
Error: [Aws\Sqs\Exception\SqsException] Error executing "ReceiveMessage" on "https://sqs.us-west-2.amazonaws.com/.../....fifo"; AWS HTTP error: Error creating resource: [message] fopen(): SSL: Handshake timed out
[file] /opt/edi-handler/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 323
[message] fopen(): Failed to enable crypto
[file] /opt/edi-handler/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 323
[message] fopen(https://sqs.us-west-2.amazonaws.com/.../....fifo): failed to open stream: operation failed
[file] /opt/edi-handler/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 323 in /..../vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 191`

**Comment by diehlaws** [comment]
Hi @luukau apologies for the long delay in response on this from our end. Are you still running into these errors? Have you had a chance to update cURL and OpenSSL on your production server to see if this behavior changes?
