### ISSUE TITLE
Mulitple request at same time

### ISSUE THREAD

**Issue by vijay-webners** [aws/aws-sdk-php#1409]
Hi 

I am creating backend where one can view/download objects from AWS S3 bucket.
 
Below is Object download code snippet :
    $promise = $client->getObjectAsync(array(
        'Bucket'                     => $bucketName,
        'Key'                        => $key,
    ));   
    $result = $promise->wait();

Problem is while downloading an object, i can not retrieve other objects.
It seem requests are in queue.

I am not much familiar to AWS S3 storage.
Any solution to send multiple request to AWS.
 
TIA

**Comment by kstich** [comment]
Check out these guides on [Commands](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/commands.html) and [Promises](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/promises.html).

Closing as this isn't an issue with the SDK. Try asking a question on [StackOverflow](https://stackoverflow.com/) and tagging it with [aws-php-sdk](http://stackoverflow.com/questions/tagged/aws-php-sdk).

**Comment by vijay-webners** [comment]
:+1:
