### ISSUE TITLE
Are you sure you are using the correct region for this bucket?

### ISSUE THREAD

**Issue by m4tthumphrey** [aws/aws-sdk-php#1410]
Yes.

```php
<?php

require 'vendor/autoload.php';

$sdk = new Aws\Sdk([
    'version' => 'latest',
    'region'  => 'eu-west-1',
    'debug' => true,
    'credentials' => [
        'key'    => 'x',
        'secret' => 'x'
    ]
]);

$s3 = $sdk->createS3();

$result = $s3->getObject([
    'Bucket' => 'my-bucket',
    'Key'    => 'hello.txt',
]);

print_r($result);
```

> PHP Fatal error:  Uncaught Aws\S3\Exception\PermanentRedirectException: Encountered a permanent redirect while requesting https://my-bucket.s3.eu-west-1.amazonaws.com/hello.txt. Are you sure you are using the correct region for this bucket? in /vendor/aws/aws-sdk-php/src/S3/PermanentRedirectMiddleware.php:49

Bucket: https://www.dropbox.com/s/mk4w43b86tiy28x/Screenshot%202017-10-26%2013.54.21.png?dl=0

When I click "hello.txt" from the console it shows the (presumable) correct URL of `https://s3-eu-west-1.amazonaws.com/my-bucket/hello.txt` which when I click it returns the a 401 (which is correct).

First time using AWS so I may have missed something obvious....?

**Comment by kstich** [comment]
This 301 error can occur when accessing a bucket name that exists but you do not control. Please make sure that your `'Bucket'` field in `->getObject` is set to exactly the bucket name you created on S3.

**Comment by m4tthumphrey** [comment]
The bucket name is set correctly. What's odd is the fact that the URL is changing.

`https://s3-eu-west-1.amazonaws.com/my-bucket/hello.txt` is the correct URL but the client is looking for `https://my-bucket.s3.eu-west-1.amazonaws.com/hello.txt`

**Comment by kstich** [comment]
What URL do you receive if you force path style endpoints?

> use_path_style_endpoint: (bool) Set to true to send requests to an S3 path style endpoint by default. Can be enabled or disabled on individual operations by setting '@use_path_style_endpoint\' to true or false. Note: you cannot use it together with an accelerate endpoint.

**Comment by kstich** [comment]
Closing due to lack of reply. Please let us know here if there's any new information.
