### ISSUE TITLE
doesnot supports bucket name with subfolder

### ISSUE THREAD

**Issue by devRoshan** [aws/aws-sdk-php#1413]
Hello, 
I want to upload  files to specific directory (eg: bucketname/folder) for different features in my app and i have configured my configuration according to that pattern , but RestSerializer::buildEndpoint method returns relative path like /bucket-name%2Fsubfolder/key. Why this method checking "substr($matches[1], -1, 1) == '+'  " pattern in BucketName ?

**Comment by kstich** [comment]
In effect, 'subfolder' is just an extension of your key. You should be using the bucket name of 'bucket-name' and the key of 'subfolder/key'.
