### ISSUE TITLE
AWS HTTP error: cURL error 77: error setting certificate verify locations

### ISSUE THREAD

**Issue by Freid001** [aws/aws-sdk-php#1416]
Hi, I have built a php consumer which polls sqs for sns notifications, triggered by s3 file uploads. The consumer runs on a EC2 m3.mediam instance configured with a ASG which monitors the queue size. My consumer pulls down files from s3 and processes them. The sqs queue is configured to push to a DLQ when a message fails. 

Recently, I have noticed that some messages are showing up in the DLQ which should under normal circumstance process perfectly fine. And in fact when I re-run the consumer polling on the DLQ the messages do process with no problem.

Whilst looking through the consumer logs I was able to narrow the problem down to this error:
`<11>Oct 31 15:39:33 ip-172-31-46-230 prod-pixel-object-worker[29478]: prod-pixel-object-worker.ERROR: Error executing "GetObject" on "https://pixel-object.s3.amazonaws.com/59f85a3d2e53b.gz"; AWS HTTP error: cURL error 77: error setting certificate verify locations:   CAfile: /etc/ssl/certs/ca-certificates.crt   CApath: /etc/ssl/certs (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) {"file":"/var/www/consumer/src/MediaMath/Utils/PreProcessing.php","line":111""message_identifier":"AQEBfBNPx2AJ2j4Z5Ddq+ue6ur1petNZq+NxqQ1Pfs1N1OwsUXdDQ4DDCRQ32t9Rr7Oe4m9Xl/e2+l+QfLFhO6jeaGIwVZ/HPZLwaKY4g6PnWxMxEKtVr/clvIVQje2SdQ/6xghJKa7pBcOddcaVW/jy9i3pBrdIBVDm8shdjZaC8ilx/e1AD/NGNM1K6WYAW1FCAyzzdhhOw7CXdxFPFPcZJypO8njNi9OTOwL4gPXvlZjdpPMpgyWO80PNqnG80KzksYjbVLXMVrr0Azb0NyBY3FtRycy1vAerRfOJWlxJbL0Kr4+MqE3AwCkDgf+DCZjSV6b2lEDLN9kkMyfEL71sbXhRZEqK/GdQ8C/C2RrYrbEWBSyamykzQr7gRHrLF7Fqi9yulyFucWy0gwbVj+ESaCoKl/dly76vwQYFsT/micE="} []`

What is strange is that this seems to only happen about 2-5% of the time as the consumer is able to (under normal situations) retrieve objects and process them. 

I have checked that the CA certs are installed and configured correctly. After running `openssl_get_cert_locations()`: 
```bash
array(8) {
  ["default_cert_file"]=>
  string(21) "/usr/lib/ssl/cert.pem"
  ["default_cert_file_env"]=>
  string(13) "SSL_CERT_FILE"
  ["default_cert_dir"]=>
  string(18) "/usr/lib/ssl/certs"
  ["default_cert_dir_env"]=>
  string(12) "SSL_CERT_DIR"
  ["default_private_dir"]=>
  string(20) "/usr/lib/ssl/private"
  ["default_default_cert_area"]=>
  string(12) "/usr/lib/ssl"
  ["ini_cafile"]=>
  string(0) ""
  ["ini_capath"]=>
  string(0) ""
}
```` 

After looking for the error on the internet: I was able to narrow it down to a specific problem with SSL/TLS hand-shake. However, beyond that, I need more information.

The PHP which is executed can be found below: 
```php
     /**
     * @param $bucket
     * @param $filename
     * @param $targetDir
     * @param int $retry
     * @return \Aws\Result
     * @throws \Exception
     */
    public function fetchFile($bucket, $filename, $targetDir, $retry = 3)
    {
        try {
            //Fetch object from s3
            $result = $this->s3->getObject(array(
                'Bucket' => $bucket,
                'Key' => $filename,
                'SaveAs' => $targetDir . '/' . $filename
            ));
        }catch (AwsException $e){
            if($retry==0) {
                throw new \Exception($e->getMessage());
            }

            sleep(5); //Object may not be available yet so wait 5 second :(

            return $this->fetchFile($bucket,$filename,$targetDir,($retry-1));
        }

        return $result;
    }
````

**Comment by kstich** [comment]
Can you please provide the versions of the SDK, cURL, OpenSSL, and PHP that you're using?

**Comment by Freid001** [comment]
SDK: 3.30.4
cURL: 7.47.0
OpenSSL: 1.0.2g
PHP: 7.0.22

**Comment by kstich** [comment]
It looks like this is an issue with cURL specifically, not the SDK. I'd recommend updating cURL, verifying the permissions on your .pem file, and potentially reaching out [on StackOverflow](https://stackoverflow.com/questions/tagged/curl).

Closing since this isn't SDK related.

**Comment by shangdev** [comment]
In fact, by restarting PHP-FPM, this problem may be solved!
`# service php-fpm restart`
