### ISSUE TITLE
RDS downloadDBLogFilePortion

### ISSUE THREAD

**Issue by jellis** [aws/aws-sdk-php#1422]
I'm unsure if this is specifically an issue with the PHP SDK, or it's a larger problem with the API - I'm attempting to download log file portions from an RDS instance; here's an example of my code.

```
        $marker = 0;
        $moreData = true;

        while ($moreData) {

            $data = $rds->downloadDBLogFilePortion([
                'DBInstanceIdentifier' => 'rds-instance-name',
                'LogFileName' => 'error/postgresql.log.2017-11-06-03',
                'Marker' => $marker,
                'NumberOfLines' => 50,
            ]);

            $moreData = (bool) $data['AdditionalDataPending'];
            $marker = $data['Marker'];

            append_to_file('error/postgresql.log.2017-11-06-03', $data['LogFileData']);
        }
```

The general output that I'm getting is an overlap from the last request - so it feels as though the marker is incorrect. I've tried exploding the marker and modifying it to find some sort of pattern as to how far it is away from the required point; but it seems to blow out as it gets further down the file.

Here's an example of the result.

```
     END;
	--## Campaign and step function call for ALL campaigns- End of code 

ep function call for ALL campaigns- End of code 
	
	    -- Insert records where and what not
```

If you notice, the section `ep function call for ALL campaigns- End of code` is repeated (the new line in the middle I can deal with). Basically, `ep function call for ALL campaigns- End of code` comes out as part of the last line in the previous call, then when passing that marker back in it comes as the start of the next call - and to boggle the mind even further, it isn't even the beginning of a line.

Any advice would be most appreciated.

**Comment by kstich** [comment]
Can you please supply a few entries of what you receive from `$data['Marker']`? Also, what version of the SDK are you using?

**Comment by jellis** [comment]
Hi all - just so everybody is aware. This is a known bug with the AWS API. They've recommended I download and install the RDS CLI to download the log files.

There is no known date for when the problem will be addressed.

**Comment by jellis** [comment]
As an aside, @kstich though - is it possible the http method mentioned in these docs has been implemented? It refers to the following

```
GET /v13/downloadCompleteLogFile/sample-sql/log/ERROR.6
```

http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/RESTReference.html#RESTReference.DownloadCompleteDBLogFile.CLIversion

**Comment by kstich** [comment]
That endpoint is exposed solely through the RDS CLI. Can you let us know where you were informed that 'This is a known bug with the AWS API' so we can follow up? Thanks!

**Comment by jellis** [comment]
I had a ticket lodged with AWS support. I was advised not to bother using the AWS CLI/SDK's for downloading logs as they're aware there are issues with it. They advised to use the RDS CLI - which I hated.

Instead, I hacked around the SDK and leveraged the signing method to generate a request to the endpoint documented on that link. See below.

```
<?php

namespace DbAudit\Services\Aws\Rds;

use GuzzleHttp\Client;
use GuzzleHttp\Psr7\Request;
use Aws\Signature\SignatureV4;
use Aws\Credentials\Credentials;

class Logs
{

    /**
     * @var string
     */
    protected $service = 'rds';

    /**
     * @var SignatureV4
     */
    protected $signature;

    /**
     * @var Client
     */
    protected $client;

    /**
     * @var Request
     */
    protected $request;

    /**
     * @var string
     */
    protected $region;

    /**
     * @var string
     */
    protected $url = 'https://{service}.{region}.amazonaws.com/v13/downloadCompleteLogFile/{db_instance_identifier}/{log_file}';

    /**
     * Build up all the dependencies
     * A little complex, but gives a nice interface
     */
    public function __construct()
    {
        $this->region = config('aws.region');
        $this->client = new Client($this->getParams());
        $this->signature = new SignatureV4($this->service, $this->region);
        $this->credentials = new Credentials(config('aws.credentials.key'), config('aws.credentials.secret'));
    }

    /**
     * Build up the full URL with variable substitution
     *
     * @param $db_instance_identifier
     * @param $log_file
     *
     * @return mixed
     */
    protected function getUrl($db_instance_identifier, $log_file)
    {
        return str_replace(
            ['{service}', '{region}', '{db_instance_identifier}', '{log_file}'],
            [$this->service, $this->region, $db_instance_identifier, $log_file],
            $this->url
        );
    }

    /**
     * The external method for retrieving the log file
     *
     * @param $db_instance_identifier
     * @param $log_file
     *
     * @return bool|string
     */
    public function getLog($db_instance_identifier, $log_file)
    {
        $this->request = new Request('GET', $this->getUrl($db_instance_identifier, $log_file), [
            'Content-type' => 'application/json'
        ]);

        return $this->retrieveLogFile();
    }

    /**
     * Internal method for firing off the request and returning what's in the
     * response (if it exists)
     * @TODO: Download file straight to disk
     *
     * @return bool|string
     */
    protected function retrieveLogFile()
    {
        $response = $this->client->send($this->signature->signRequest($this->request, $this->credentials));

        return $response->getStatusCode() == 200
            ? $response->getBody()->getContents()
            : false;
    }

    /**
     * Configure proxy information if required
     *
     * @return array
     */
    protected function getParams()
    {
        $params = [];

        if (!empty(env('HTTP_PROXY')) && !empty(env('HTTPS_PROXY')) && !empty(env('NO_PROXY'))) {
            $params['proxy']['http_proxy'] = env('HTTP_PROXY');
            $params['proxy']['https_proxy'] = env('HTTPS_PROXY');
            $params['proxy']['no_proxy'] = env('NO_PROXY');
        }

        return $params;
    }

}
```

I hope this helps somebody else at some point.

**Comment by kstich** [comment]
Closing since this looks like an API issue with a couple posted workarounds. Thanks @jellis!
