### ISSUE TITLE
The provided 'x-amz-content-sha256' header does not match what was computed.

### ISSUE THREAD

**Issue by samusenkoiv** [aws/aws-sdk-php#1425]
SDK version: 3.38.5
php version: 7.0.25

What I do:
```

$fd = fopen('php://input', 'r+');
$result = $this->client->putObject( [
  'Bucket' => $this->bucket,
  'Body' => $fd,
  'Key' => $file->getPath(),
  'ACL' => 'public-read',
  'ContentLength' => $file->getSize(),
  'ContentType' => 'application/octet-stream',
]);
```

What I get:

> "Error executing \"PutObject\" on \"https://s3.amazonaws.com/mybucket/d687e9e0-a82f-41ee-b9df-82e298ae6c47/mytestsfile.jpg\"; AWS HTTP error: Client error: `PUT https://s3.amazonaws.com/mybucket/d687e9e0-a82f-41ee-b9df-82e298ae6c47/mytestsfile.jpg` resulted in a `400 Bad Request` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XAmzContentSHA256Mismatch</Code><Message>The provided 'x-amz-content (truncated...)\n XAmzContentSHA256Mismatch (client): The provided 'x-amz-content-sha256' header does not match what was computed. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XAmzContentSHA256Mismatch</Code><Message>The provided 'x-amz-content-sha256' header does not match what was computed.</Message><ClientComputedContentSHA256>b67f33b0b0b2dde2b0c95b7c7b3f0b4afd0e3c9a671c86e3f94a46a9c01b74f8</ClientComputedContentSHA256><S3ComputedContentSHA256>e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855</S3ComputedContentSHA256><RequestId>A5F1B24CDF8B010D</RequestId><HostId>N81zYMl+Gvjhmghs0nDLWWNaHTDSm7T2irmx3dRLAdymACkJodiWNuLAZ48rbe/Ae2lFkMZM9Oo=</HostId></Error>"

The content length is totally fine.
Do I do anything wrong? Thanks

**Comment by samusenkoiv** [comment]
FYI
The following sample works totally fine:
```
$body = EntityBody::factory(fopen('php://input', 'r+'));
$result = $this->client->putObject(
    [
        'Bucket' => $this->bucket,
        'Body' => $body,
        'Key' => $file->getPath(),
        'ACL' => 'public-read',
        'ContentType' => 'application/octet-stream',
    ]
);
```

**Comment by kstich** [comment]
In your first sample, where does the `$file` variable come from?

**Comment by samusenkoiv** [comment]
Why do you ask?
If your concern is about 'ContentLength', then this is not the issue. The ContentLength has the right value (same value I get in $result from aws) , I double checked that.

**Comment by kstich** [comment]
Thanks for the extra info, just trying to get a complete picture of your situation to work on reproducing the issue.

**Comment by kstich** [comment]
It seems like the use of `'php://input'` is the culprit here.

`stream_get_meta_data($fd)` will report that the stream is seekable, and invoking `fseek($fd, 0)` on it will set the pointer to 0, but a subsequent read will return no contents. None of this triggers any complaints. It looks like a new handle is needed each time.

Specific to this issue: Because we read the contents of the stream to generate the SHA, we do the first read mentioned above, and subsequent reads for sending to S3 return no contents. Your `EntityBody::factory` call must have some sort of local caching involved so that the subsequent read succeeds. Guzzle also provides this functionality through the [`CachingStream`](https://github.com/guzzle/psr7#cachingstream), you'll need to wrap the handle in a stream first though.

-----

```php
$fh = fopen('php://input', 'r+');
echo '0:' . json_encode(stream_get_meta_data($fh)) . '.' . PHP_EOL;
echo '1:' . fread($fh, 1000) . '.' . PHP_EOL;
echo '2:' . ftell($fh) . '.' . PHP_EOL;
fseek($fh, 0);
echo '3:' . ftell($fh) . '.' . PHP_EOL;
echo '4:' . fread($fh, 1000) . '.' . PHP_EOL;

$fh = fopen('php://input', 'r+');
$fs = GuzzleHttp\Psr7\stream_for($fh);
$cs = new \GuzzleHttp\Psr7\CachingStream($fs);
echo '6:' . $cs . '.' . PHP_EOL;
$cs->rewind();
echo '7:' . $cs . '.' . PHP_EOL;
```

```bash
$ curl -d "this is a 24 char string" -X POST {URL}
0:{"timed_out":false,"blocked":true,"eof":false,"wrapper_type":"PHP","stream_type":"Input","mode":"rb","unread_bytes":0,"seekable":true,"uri":"php:\/\/input"}.
1:this is a 24 char string.
2:24.
3:0.
4:.
6:this is a 24 char string.
7:this is a 24 char string.
```

**Comment by kstich** [comment]
Closing due to lack of reply. Please let us know here if there's any new information.
