### ISSUE TITLE
listObjects not returning NextContinuationToken when IsTruncated is true

### ISSUE THREAD

**Issue by jshrek** [aws/aws-sdk-php#1428]
When I use the following code, I get IsTruncated=1 but there is no NextContinuationToken included in the response. The code successfully returns the files in the bucket, and I can force IsTruncated=1 by setting MaxKeys=1.

Using latest version of SDK downloaded from here: https://aws.amazon.com/sdk-for-php/
v3.39.0 - 2017-11-20

```
require_once __DIR__."/amazon-aws-php-sdk/aws-autoloader.php";
use Aws\S3\S3Client;
use Aws\Exception\AwsException;
use Aws\S3\Exception\S3Exception;

$s3Client = new S3Client([ 'version' => 'latest', 'region' => 'us-west-1', 'credentials' => [ 'key' => 'my-key', 'secret' => 'my-secret', ], ]);

$s3Result = $s3Client->listObjects(array('Bucket' => 'my-bucket', 'MaxKeys' => '1')); //There are more than 1 files in this bucket, so MaxKeys=1 just insures IsTruncated will be true

//Show results
echo "<pre>";
print_r($s3Result);
echo "</pre>";

```

**Comment by kstich** [comment]
`'NextContinuationToken'` is for [`listObjectsV2`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#listobjectsv2), while `'NextMarker'` is for [`listObjects`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#listobjects). Is the `'NextMarker'` in the `$s3Result`?

**Comment by jshrek** [comment]
No NextMarker is not in the result either (see below). Do I need to include Marker in the original request to get a NextMarker back?

```
Aws\Result Object
(
    [data:Aws\Result:private] => Array
        (
            [IsTruncated] => 1
            [Marker] => 
            [Contents] => Array
                (
                    [0] => Array
                        (
                            [Key] => Some File Name.mp4
                            [LastModified] => Aws\Api\DateTimeResult Object
                                (
                                    [date] => 2017-11-25 19:22:11.000000
                                    [timezone_type] => 2
                                    [timezone] => Z
                                )

                            [ETag] => "blablabla"
                            [Size] => 69254403
                            [StorageClass] => STANDARD
                            [Owner] => Array
                                (
                                    [DisplayName] => webmaster
                                    [ID] => blablabla
                                )

                        )

                )

            [Name] => my-bucket-name
            [Prefix] => 
            [MaxKeys] => 1
            [EncodingType] => url
            [@metadata] => Array
                (
                    [statusCode] => 200
                    [effectiveUri] => https://my-bucket-name.s3.us-west-1.amazonaws.com/?max-keys=1&encoding-type=url
                    [headers] => Array
                        (
                            [x-amz-id-2] => blablabla
                            [x-amz-request-id] => blablabla
                            [date] => Sat, 25 Nov 2017 20:25:14 GMT
                            [x-amz-bucket-region] => us-west-1
                            [content-type] => application/xml
                            [transfer-encoding] => chunked
                            [server] => AmazonS3
                        )

                    [transferStats] => Array
                        (
                            [http] => Array
                                (
                                    [0] => Array
                                        (
                                        )

                                )

                        )

                )

        )

)

**Comment by jshrek** [comment]
As a side note, the documentation is confusing as nothing I have read so far ever suggested to me that there was a different command other than listObjects. This first link specifically references listObjects only:
http://docs.aws.amazon.com/AmazonS3/latest/dev/ListingObjectKeysUsingPHP.html

This second link makes mention of using v2 of listObjects but I just assumed that when I use the new SDK I am getting the v2 of listObjects. How would anybody know that there is actually a different command listObjectsv2 to use, when it is not even mentioned on the page anywhere:
http://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html

**Comment by jshrek** [comment]
Using listObjectsV2 instead of listObjects does correctly return NextContinuationToken.

So the only issue seems to be that listObjects does not return NextMarker

**Comment by kstich** [comment]
The AWS SDKs provide both versions of `ListObjects` under different operation names. It looks like, from the [S3 documentation on V1 of `ListObjects`](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html#RESTBucketGET-responses), that `'NextMarker'` is only returned if you've specified a `'Delimiter'`.

>This element is returned only if you specify a delimiter request parameter. If the response does not include the NextMaker and it is truncated, you can use the value of the last Key in the response as the marker in the subsequent request to get the next set of object keys.

The AWS SDK for PHP also has [paginators](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/paginators.html) that can handle the pagination of the [`ListObjects[V2]` operations](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#paginators) for you.
