### ISSUE TITLE
Empty file in MultipartUploader

### ISSUE THREAD

**Issue by ondrejhlavacek** [aws/aws-sdk-php#1429]
Uploading an empty file using MultipartUploader results in a 400 response.

```
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://***.s3.eu-central-1.amazonaws.com/test/empty-file?uploadId=***` resulted in a `400 Bad Request` response:
<Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed or did not validate against our publis (truncated...)
 in /code/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /code/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /code/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /code/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response),  in /code/vendor/aws/aws-sdk-php/src/Multipart/AbstractUploadManager.php on line 136
```

Here's code to reproduce the error using latest aws-sdk-php version (`3.41.0`)

```php
<?php
error_reporting(E_ALL);
require_once("./vendor/autoload.php");
$bucket = '***';

$filePath = '/tmp/emptyfile';
$fh = fopen($filePath, 'w');
// fputs($fh, 'this passes');
fclose($fh);

$s3options = [
    'version' => '2006-03-01',
    'region' => 'eu-central-1',
    'credentials' => [
        'key' => '***',
        'secret' => '***'
    ]
];
$s3Client = new \Aws\S3\S3Client($s3options);
$uploader = new \Aws\S3\MultipartUploader($s3Client, $filePath, [
    'Bucket' => $bucket,
    'Key' => 'test/empty-file'
]);
$uploader->upload();
```

Uncommenting `fputs($fh, 'this passes');` makes the upload successful.

Is there a way to fix this or should I detect the file size and use a different method? Sometimes the content length cannot be decided beforehand (streams).

Attaching logs of both successful and failing runs here https://gist.github.com/ondrejhlavacek/4be3af7deaa85e54c306f2ff685fd06b#file-failed-log
https://gist.github.com/ondrejhlavacek/4be3af7deaa85e54c306f2ff685fd06b#file-successful-log

**Comment by kstich** [comment]
You can use [the `ObjectUploader`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.S3.ObjectUploader.html) or [`$s3Client->upload($bucket, 'test/empty-file', $fh)`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.S3.S3ClientTrait.html#_upload), which creates an `ObjectUploader` for you, to properly handle fluctuating file sizes like this.
