### ISSUE TITLE
Issues with NFS mounts and S3

### ISSUE THREAD

**Issue by polothy** [aws/aws-sdk-php#1436]
Hello!

The root of the problem is that the SDK does not always close open file handlers.  This is not a problem with non-NFS mounts and it is only a problem if you attempt to delete the folder in which the open file handler is using.

**File download example use case:**
* Create a temporary directory on the NFS mount.
* Use `\Aws\S3\S3Client::getObject` to download an object *that does not exist in S3*.  Set `SaveAs` to a file path within the temporary directory on the NFS mount.
* Delete the temporary directory by iterating files and deleting each one.  Once the directory is empty, remove the directory.

*Workaround*: instead of passing in a file path into `SaveAs`, pass in the file `resource` handler itself and ensure it is closed after calling `\Aws\S3\S3Client::getObject`.

**Multipart upload example use case:**
* Create a temporary directory on the NFS mount.
* Use `\Aws\S3\S3ClientTrait::upload` to upload a large file which would trigger multipart upload (16Mb or larger).
* Delete the temporary directory by iterating files and deleting each one.  Once the directory is empty, remove the directory.

*Workaround*: None found, need to avoid using multipart uploads by using `\Aws\S3\S3Client::putObject`.

**Example error:**
Both of the above use cases result in an error that looks like this:
> Warning: unlink(/path/to/directory/being/deleted/.nfs676dc60d2899deb8000000c5): Device or resource busy in /path/to/script.php on line X

Some info about the `.nfs` files, http://nfs.sourceforge.net/#faq_d2

**Solutions:**
* Update the SDK to close these?
* Is it possible for me to add middleware or listen to some events to automatically close these?
* Others? Open to suggestions.

Cheers and thanks for the help.  This is likely an edge case, so I'll understand if there isn't much that can be done.

**Comment by kstich** [comment]
So we can work on reproducing the issues to investigate, can you provide some samples as to your `getObject` and `upload` calls? Additionally, when you say 
>to download an object that does not exist
do you mean the object does not exist locally or on S3?

**Comment by mrmark** [comment]
> do you mean the object does not exist locally or on S3?

Yes, the object does not exist in S3.  Sorry, updated the description.

**Example API calls:**

For the `getObject` call:
```php
$args = ['region' => 'us-east-2']; // For us, credentials could be key/secret, empty (for IAM) or an instance of \Aws\CacheInterface
$s3 = new \Aws\S3\S3Client($args);
$s3->getObject([
    'Bucket' => 'my-bucket',
    'Key'    => 'my-key-that-does-not-exist-in-s3',
    'SaveAs' => '/path/to/file/on/nfs/mount',
]);
```

For the `upload` call, the file being uploaded must be large enough to trigger a multipart upload:
```php
$args = ['region' => 'us-east-2']; // Credentials could be key/secret, empty (for IAM) or an instance of \Aws\CacheInterface
$s3 = new \Aws\S3\S3Client($args);

$resource = fopen('/path/to/file/on/nfs/mount', 'rb');
if ($resource === false) {
    throw new \Exception('Failed to open file');
}

$stream = \GuzzleHttp\Psr7\stream_for($resource);

try {
    $s3->upload('my-bucket', 'my-key', $stream);
} catch (\Aws\S3\Exception\S3Exception $e) {
    $stream->close();
    throw $e;
}

$stream->close();
```

In addition, remember that in order to see the error, you must attempt to delete the directory on the NFS mount in which the above files live.  The code for file deletion can be found [here](https://github.com/moodle/moodle/blob/MOODLE_33_STABLE/backup/util/helper/backup_helper.class.php#L86) and the specific line that causes the error is line [126](https://github.com/moodle/moodle/blob/MOODLE_33_STABLE/backup/util/helper/backup_helper.class.php#L126).

**Comment by kstich** [comment]
Can you supply the versions of PHP, the AWS SDK for PHP, Guzzle, and Guzzle/Psr7 you're using?

**Comment by mrmark** [comment]
* PHP: 7.1.10
* AWS SDK: 3.19.26
* guzzlehttp/guzzle: 6.2.2
* guzzlehttp/psr7: 1.3.1

**Comment by kstich** [comment]
I'm unable to reproduce either of these issues, I'd suspect there's something set in the NFS configurations that's causing this issue.

-----
`'SaveAs'` issue:
```php
$client = $sdk->createS3();
try {
    $client->getObject([
        'Bucket' => 'bucket',
        'Key' => 'filethatdoesntexist.txt',
        'SaveAs' => '/nfsmountdir/filethatdoesntexist.txt'
    ]);
} catch (Exception $e) {}

$output = [];
exec('ls /nfsmountdir', $output);
echo PHP_EOL . json_encode($output); // File exists in the directory

unlink('/nfsmountdir/filethatdoesntexist.txt');

$output = [];
exec('ls /nfsmountdir', $output);
echo PHP_EOL . json_encode($output); // File no longer exists
```

-----
`->upload` issue:
```php
$resource = fopen('/nfsmountdir/largefile.zip', 'rb');
if ($resource === false) {
    throw new \Exception('Failed to open file');
}

$stream = \GuzzleHttp\Psr7\stream_for($resource);

try {
    $output = [];
    exec('ls /nfsmountdir', $output);
    echo PHP_EOL . json_encode($output); // File exists in the directory

    $client->upload('bucket', 'largefile.zip', $stream);
} catch (Exception $e) {}

$stream->close();

$output = [];
exec('ls /nfsmountdir', $output);
echo PHP_EOL . json_encode($output); // File exists in the directory

unlink('/nfsmountdir/largefile.zip');

$output = [];
exec('ls /nfsmountdir', $output);
echo PHP_EOL . json_encode($output); // File no longer exists
```

**Comment by mrmark** [comment]
If I make the following changes:
* `ls -a` instad of `ls`
* Then attempt to delete the directory at the end

```php
$client = $sdk->createS3();
try {
    $client->getObject([
        'Bucket' => 'bucket',
        'Key' => 'filethatdoesntexist.txt',
        'SaveAs' => '/nfsmountdir/filethatdoesntexist.txt'
    ]);
} catch (Exception $e) {}

$output = [];
exec('ls -a /nfsmountdir', $output);
echo PHP_EOL . json_encode($output); // File exists in the directory

unlink('/nfsmountdir/filethatdoesntexist.txt');

$output = [];
exec('ls -a /nfsmountdir', $output);
echo PHP_EOL . json_encode($output); // File no longer exists

rmdir('/nfsmountdir');
```

I get this for the output:

```
[".","..","filethatdoesntexist.txt"]
[".","..",".nfs0000000001e099df00000008"]
Warning: rmdir(/nfsmountdir): Directory not empty in /path/to/s3test.php on line 46
```

It's interesting to note that the `.nsf` file didn't appear until the file was deleted, didn't know that was the case.

While testing, I was using my Vagrant mount, so was `/vagrant/nfsmountdir`.  Using default mounting options in our `Vagrantfile`: `config.vm.synced_folder ".", "/vagrant", type: "nfs"`

**Comment by mrmark** [comment]
Also, I'd like to add, I didn't file this issue to fix my Vagrant/dev environment :)  It can just be reproduced there.  We actually saw these errors in AWS where we are NFS mounting EBS to our web nodes.

**Comment by mrmark** [comment]
Hrm, I could reach out to our account support, see if we can bring in someone from EBS.  I can try to do that next week.

In the meantime, maybe it has something to do with Ubuntu?  Our Vagrant and web nodes are running Ubuntu.  You can try it yourself with https://github.com/moodlerooms/moodle-vagrant-example - follow the steps in **Vagrant install** section to get it setup.  It mentions installing specific versions of Vagrant/VirtualBox, but you can likely install latest versions if you have them already (we do this because in the past, they randomly break each other).  I know this is **asking a lot** for reproducing a bug, so no worries if you don't have time for pursuing this route.

**Comment by kstich** [comment]
The tests I ran above were on Debian Jessie, so I don’t expect much of a change but will give it a shot.

**Comment by kstich** [comment]
@mrmark Were you able to do any other investigating to resolve this issue? If not, I'll make another attempt soon on trying to reproduce the issue at hand.

**Comment by mrmark** [comment]
No, sorry, I haven't been able to.
