### ISSUE TITLE
Guzzle stream decorator trait is not found.

### ISSUE THREAD

**Issue by joshlopes** [aws/aws-sdk-php#1437]
It seems that guzzle stopped including stream as part of their package. And i am getting this error now:

```
PHP Fatal error:  Trait 'GuzzleHttp\Stream\StreamDecoratorTrait' not found in /var/www/amara/sf2/vendor/aws/aws-sdk-php/src/Handler/GuzzleV5/PsrStream.php on line 15
```

On my composer i'm requiring the guzzle v6. 

```
"guzzlehttp/guzzle": "^6.3",
"aws/aws-sdk-php": "^3.22",
```

I will include the stream repo from guzzle on my project for the time being, but i think it should be added as a dependency on your project

**Comment by kstich** [comment]
It looks like it's trying to find the GuzzleV5 `StreamDecoratorTrait` based on 'GuzzleV5/PsrStream.php' in that message. Guzzle is a [already listed as a dependency for the SDK](https://github.com/aws/aws-sdk-php/blob/master/composer.json#L20).

* What version of Guzzle is listed in your `composer.lock` file?
* What does the stack trace look like when this error occurs?

**Comment by joshlopes** [comment]
I'm sorry, i thought i was not using the guzzle http stream, but i seem to be using it on one of my tests. 

But the problem is basically that if i try to "new PsrStream()" from the aws vendor and i don't include the guzzlehttp/streams on my composer it will fail, because one dependency of PsrStream is the guzzlehttp/streams (DecoratorTrait). 

If that makes sense.

**Comment by kstich** [comment]
For this, you should be using the [`Guzzle\Psr7` namespaced classes, such as `Stream`](https://github.com/guzzle/psr7) that are a dependency of Guzzle v6, and not including [the separate `Guzzle\Stream` package](https://github.com/guzzle/streams).
