### ISSUE TITLE
SDK ver 2 & 3 conflict in PHP 7.0

### ISSUE THREAD

**Issue by shuhailshuvo** [aws/aws-sdk-php#1438]
```
require_once '../aws/aws-autoloader.php';

$config = [
    'region'  => 'ap-south-1',
    'version' => 'latest',
    'credentials' => [
        'key'    => '...',
        'secret' => '...'
    ]
];
$sdk = new Aws\Sdk($config);
$client = $sdk->createS3();
```

shows following error:

Fatal error: Uncaught TypeError: Argument 1 passed to Aws\Common\Client\AbstractClient::__construct() must be an instance of Aws\Common\Credentials\CredentialsInterface, array given, called in /var/www/html/webservice/vendor/aws3/Aws/Sdk.php on line 316 and defined in /var/www/html/aws-sdk/vendor/aws/aws-sdk-php/src/Aws/Common/Client/AbstractClient.php:75 Stack trace: #0 /var/www/html/webservice/vendor/aws3/Aws/Sdk.php(316): Aws\Common\Client\AbstractClient->__construct(Array) #1 /var/www/html/webservice/vendor/aws3/Aws/Sdk.php(291): Aws\Sdk->createClient('S3', Array) #2 index.php(14): Aws\Sdk->__call('createS3', Array) thrown in /var/www/html/aws-sdk/vendor/aws/aws-sdk-php/src/Aws/Common/Client/AbstractClient.php on line 75

**I have both AWS SDK version 2 & 3 in my project. this might be a issue of conflict. Then how to solve the conflict?**

**Comment by kstich** [comment]
Running version 2 and 3 of the AWS SDK for PHP together is not possible. You can follow the [upgrading guide](https://github.com/aws/aws-sdk-php/blob/master/UPGRADING.md) and use the [compatibility test](https://github.com/aws/aws-sdk-php/blob/master/compatibility-test.php) included in version 3 of the SDK to help update.
