### ISSUE TITLE
Update Guzzle to 6.3

### ISSUE THREAD

**Issue by philiplb** [aws/aws-sdk-php#1439]
Hi,
we are currently getting a lot of exceptions due to a bug in Guzzle 6.2.1: https://github.com/guzzle/guzzle/issues/1973
It would be great if Guzzle could be updated to 6.3 which fixes this issue.

**Comment by kstich** [comment]
How did you install the AWS SDK for PHP? If you used Composer, you can manage your version of Guzzle through that.

**Comment by philiplb** [comment]
Hi,
thank you for the reply.
Yes, we are using composer and the solution was to downgrade to Guzzle 5.3.1. First I thought your version settings at https://github.com/aws/aws-sdk-php/blob/master/composer.json#L20 would exclude 6.3.*, but actually they shouldn't. >= 6.2.1, < 7.0.0 should be fine with 6.3.*. Hm, will have to reinvestigate why just requiring 6.3 didn't work out.
