### ISSUE TITLE
I don't see the transcribe service. Will this work for amazon Transcribe service?

### ISSUE THREAD

**Issue by mwleinad** [aws/aws-sdk-php#1442]

**Comment by kstich** [comment]
[Amazon Transcribe](https://aws.amazon.com/transcribe/) is in preview, you can [request an invitation to the preview program here](https://pages.awscloud.com/amazon-transcribe-preview.html).

**Comment by kstich** [comment]
[Support for Amazon Transcribe was released in version 3.51.0](https://github.com/aws/aws-sdk-php/releases/tag/3.51.0).
