### ISSUE TITLE
Unable to install for PHP 5.6

### ISSUE THREAD

**Issue by MEGApixel23** [aws/aws-sdk-php#1447]
When trying to install through composer it returns the following error:
```
Problem 1
    - sebastian/recursion-context 3.0.0 requires php ^7.0 -> your PHP version (5.6.32) does not satisfy that requirement.
    - sebastian/recursion-context 3.0.0 requires php ^7.0 -> your PHP version (5.6.32) does not satisfy that requirement.
    - sebastian/recursion-context 3.0.0 requires php ^7.0 -> your PHP version (5.6.32) does not satisfy that requirement.
    - Installation request for sebastian/recursion-context (locked at 3.0.0) -> satisfiable by sebastian/recursion-context[3.0.0].
```

I'm tied with this version of PHP, so I can not update it to match the requirements. Maybe there is a version of the "aws-sdk-php" package working with PHP 5.6?

**Comment by kstich** [comment]
I'm unable to reproduce your issue without requiring an additional dependency outside of the AWS SDK for PHP.

The SDK dependency on `sebastian/recursion-context` comes via `phpspec/prophecy` via `phpunit/phpunit`. `phpspec/prophecy` requires `"sebastian/recursion-context": "^1.0|^2.0|^3.0"`, where `^2.0` satisfies the requirement for `"php": ">=5.3.3"`.

What packages in your `composer.lock` file require `sebastian/recursion-context`?

**Comment by MEGApixel23** [comment]
Looks like this issue is related to "phpunit/phpunit" v.6.2.2 package. I'll try to lower its version. Thanks for a quick response.
