### ISSUE TITLE
Route53 ListResourceRecordSets Paginator not setting max items

### ISSUE THREAD

**Issue by ravenbyron** [aws/aws-sdk-php#1450]
Hello,

I am using 3.48.3 when I try to use the paginator to get my Record Sets it only gets 100 at a time no matter what I set the MaxItems to. I have a Zone with like 14k records so this takes a very long time.  Is there any way to pass in the request size to the Paginator?

```
$results = $r53->getPaginator('ListResourceRecordSets',
['HostedZoneId' => 'XXXX','MaxItems' => '500',]);
```
Thanks

**Comment by kstich** [comment]
The [Route53 `ListResourceRecordSets` operation itself limits this to 100 per response](http://docs.aws.amazon.com/Route53/latest/APIReference/API_ListResourceRecordSets.html). `'MaxItems'` is for setting a sub-100 item response cap.

**Comment by ravenbyron** [comment]
ok that sucks... is there any way to do what the console does it seems to call `listResourceRecordSetWithPrefix`?  or should I just add the "StartRecordName" and then do filtering in my code from there? My goal is to find a record so I can update it...

**Comment by kstich** [comment]
Using `'StartRecordName'` reads that the output will be in ASCII order starting from that name. Your filtering would need to be passed what will be the first sorted name for that `'HostedZoneId'` for capturing.
