### ISSUE TITLE
What is default timeout?

### ISSUE THREAD

**Issue by kkopachev** [aws/aws-sdk-php#1452]
Hi!

SDK 3.36.8, Guzzle 6.3.0. PHP 7.1.
I am trying to set timeout/connect_timeout, but before coming up with exact number was trying to find out what default values are. I didn't seem to find clear answer to that.

[Docs](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html?highlight=timeout#connect-timeout) for both [state](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html?highlight=timeout#timeout) that default values for both is 60 (seconds) and this is in fact will cause it to wait infinite time. 
I looked up in the sources, but could not find any mentions of these arguments set anywhere. Seems like Guzzle does not set default values too. Which means timeouts are in fact indefinite. 
Is this right? Should documentation be changed? Should there be default timeout actually set to finite number of seconds?

**Comment by kstich** [comment]
Timeouts are not altered or supplied by the AWS SDK for PHP, just passed through to Guzzle. Guzzle applies the passed params in either `Handler\CurlFactory` or `Handler\StreamHandler`.

The SDK documentation you link to clearly states:
>Use 60 to wait indefinitely (the default behavior).

As this is for waiting to establish a connection and is configurable at runtime, I don't see a reason to change the default behavior here. Do you have any specific reasoning for a change?

**Comment by kkopachev** [comment]
Since timeout values are passed through to Guzzle, then docs should be changed to say:
> Use **0** to wait indefinitely (the default behavior).

Because statement "use 60 seconds to wait indefinitely" is ambiguous.


Additionally, and that's probably belongs to Guzzle issue tracker, Curl handler uses no timeout at all, while stream handler will use [default-socket-timeout](http://php.net/manual/en/context.http.php#context.http.timeout) ini-setting.

Now the issue this is all coming from is that we got some weird situation couple times, when a job which does few requests to ElasticTranscoder to submit a job and request status update hang for some long period. `strace`/`ltrace` showed same output as mentioned https://github.com/guzzle/guzzle/issues/1940
That was time-sensitive issue, so I didn't have time to figure out what connection it is waiting for. Job also does other requests, so it's possible that it was not caused by AWS SDK. 

From my point of view, it would be great to have default timeout set to some reasonable value. Otherwise with Curl handler request might hang forever (not 100% sure here).
