### ISSUE TITLE
SES - bulk mail sending

### ISSUE THREAD

**Issue by th4deu** [aws/aws-sdk-php#1454]
Sup!

I'm trying to send bulk emails using AWS but it's failing. Can you guys help me?

I set the AWS SDK Client config version to '2010-12-01' and i'm trying to use exactly the example I found here: http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-email-2010-12-01.html#sendtemplatedemail

In this case, I get the error "The template data is invalid", but even it's not defined as required in the documentation, I'm trying to set any value for this Key, but it's not working, returning the same error to me.

Here's the code I'm using (I've created the template before):

```
$email = [
        'Source' => SENDER,
        'Template' => 'Template1', 
        'ConfigurationSetName' => 'EnvioTeste',
        'Destinations' => [
          [
            'Destination' => [
                'ToAddresses' => ['my_verified_email@gmail.com'],

                'ReplacementTemplateData'=>[
                  'nome'=>'Thadeu'
                ],
            ],
          ],
          
          ],
          'DefaultTags' => [
            ['Name'=>'nome', 'Value'=>'NOME DEFAULT VALUE'],
            ['Name'=>'email', 'Value'=>'EMAIL DEFAULT VALUE'],
          ],
          'TemplateData' =>  'anything',
          'DefaultTemplateData' => 'anything',
      ];
```

Is there something I can do?

**Comment by kstich** [comment]
Sending a bulk templated email should be done via [`'->sendBulkTemplatedEmail()'`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-email-2010-12-01.html#sendbulktemplatedemail)

There is no `'TemplateData'` parameter for this operation. Also note that `'ReplacementTemplateData'` should be next to, not inside, `'Destination'`. `'DefaultTemplateData'` is documented as:
>Type: string
A list of replacement values to apply to the template when replacement data is not specified in a Destination object. These values act as a default or fallback option when no other data is available.
The template data is a JSON object, typically consisting of key-value pairs in which the keys correspond to replacement tags in the email template.

Similar applies for `'ReplacementTemplateData'`:
>Type: string
A list of replacement values to apply to the template. This parameter is a JSON object, typically consisting of key-value pairs in which the keys correspond to replacement tags in the email template.

**Comment by th4deu** [comment]
Thank you for your reply, @kstich .

Also, I've done these steps you detailed. Even using the "sendBulkTemplatedEmail" method, it continues requiring the TemplateData info.

Can you try it and send me a working case of use, please? 

I've tried almost all of the possibilities I had in mind and it keeps returning me an error with this message (attached to this post)
![ses-error](https://user-images.githubusercontent.com/5004595/34418985-52f60df0-ebe8-11e7-8daf-270a2b668121.png)

Thanks!

**Comment by kstich** [comment]
Please supply an updated version of the parameters you are passing to `->sendBulkTemplatedEmail()`.

**Comment by th4deu** [comment]
Alright.

Here's an array I'm passing into the method:

`$array = [
        'Source' => 'my_email@gmail.com',
        'Template' => 'Template1', 
        'ConfigurationSetName' => 'EnvioTeste',
        'Destinations' => [
          [
            'Destination' => [
                'ToAddresses' => ['my_email@gmail.com'],
                'ReplacementTemplateData'=>[['Name'=>'input1', 'Value'=>'My Name'],['Name'=>'input2', 'Value'=>'My Last Name']],
            ],
          ],
          
          ],
          // 'TemplateData' => 'test', // This is where the error happens. It requires this parameter even for bulk templated e-mail, and even sending this parameter in the array, it doesn't work.
          'DefaultTemplateData' => 'test',
      ];`

**Comment by kstich** [comment]
From my previous reply:

-----
Also, note that `'ReplacementTemplateData'` should be next to, not inside, `'Destination'`. 

`'DefaultTemplateData'` is documented as:
>Type: string
A list of replacement values to apply to the template when replacement data is not specified in a Destination object. These values act as a default or fallback option when no other data is available.
The template data is a JSON object, typically consisting of key-value pairs in which the keys correspond to replacement tags in the email template.

Similar applies for `'ReplacementTemplateData'`:
>Type: string
A list of replacement values to apply to the template. This parameter is a JSON object, typically consisting of key-value pairs in which the keys correspond to replacement tags in the email template.
-----
Both of these values are to be strings representing JSON objects (set them to `json_encode({CURRENT_VALUE})`). `'DefaultTemplateData'`'s value of 'test' is not a JSON object, and will likely also lead to the exception you're receiving.

**Comment by th4deu** [comment]
@kstich, thanks for your attention but I'm still not getting it.

I've placed the ReplacementTemplateData outside Destination (but still inside Destinations) and I did the same with the DefaultTemplateData, placing it outside Destinations and passing the Json value (I did it before, just replaced the text for when pasted it here).

Here's with the data, can you please help me to see what's wrong? I still get the "TemplateData is invalid" message.

```
$array = [
        'Source' => 'my_email@gmail.com',
        'Template' => 'Template1', 
        'ConfigurationSetName' => 'EnvioTeste',
        'DefaultTemplateData' => json_encode([['Name'=>'nome', 'Value'=>'Thadeu'], ['Name'=>'fulano', 'Value'=>'A.']]),   
        'Destinations' => [
          [
            'Destination' => [
                'ToAddresses' => ['my_email@gmail.com'],
            ],
            
            'ReplacementTemplateData'=> json_encode([['Name'=>'nome', 'Value'=>'Thadeu'], ['Name'=>'fulano', 'Value'=>'A']]), 
          ],
                     
          ],
          
      ];

        $result = $client->sendBulkTemplatedEmail($array);
```
By the way I've passed the replacement tag's names as key in the array too, and the error is the same.

**Comment by kstich** [comment]
It looks like you're trying to pass two sets of `'ReplacementTemplateData'` or `'DefaultTemplateData'` at a time instead of one.

```php
...
    'Destinations' => [
        [
            'Destination' => [
                'ToAddresses' => ['my_email@gmail.com'],
            ],
            // The replacement data is 'key'=>'value' where 'key' matches the {{key}} in your template.
            'ReplacementTemplateData'=> json_encode(['nome'=>'Thadeau', 'fulano'=>'A']), 
        ], // Another destination would go after this with different address(es) and data.
    ],
...
```

The same change should apply to `'DefaultTemplateData'`.

**Comment by th4deu** [comment]
It worked now! Thank you very much.

I've tested it before but I think it didn't work because the ReplacemenetTemplateData was inside Destination.

Thanks!
