### ISSUE TITLE
Keep alive connection

### ISSUE THREAD

**Issue by sm2017** [aws/aws-sdk-php#1456]
How can I keep alive s3 client connection?

**Comment by kstich** [comment]
Guzzle will attempt to keep the client connection alive if the same client is used for requests. This can be seen by using the [debug flag](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#debug) and observing the cURL output.

-----
```php
echo $s3->getObject([
    'Bucket' => $bucket,
    'Key' => 'test1.png',
]);

sleep(5);

echo $s3->getObject([
    'Bucket' => $bucket,
    'Key' => 'test2.png',
]);
```

outputs:

...`* Connected to {$bucket}.s3.us-west-2.amazonaws.com (52.218.160.40) port 443 (#0)`...
`* Connection #0 to host {$bucket}.s3.us-west-2.amazonaws.com left intact`...
`* Found bundle for host {$bucket}.s3.us-west-2.amazonaws.com: 0x7fb63265a010 [can pipeline]`...
`* Re-using existing connection! (#0) with host {$bucket}.s3.us-west-2.amazonaws.com`...
`* Connection #0 to host {$bucket}.s3.us-west-2.amazonaws.com left intact`...

**Comment by sm2017** [comment]
How many times it keep alive connection? 10 sec ? Minutes?

**Comment by kstich** [comment]
This will vary according to multiple factors, including your networking settings and the service's keep-alive settings. You can search for or ask for further information regarding S3's behavior [on their forum](https://forums.aws.amazon.com/forum.jspa?forumID=24).
