### ISSUE TITLE
Using Command Pools to get Presigned URIs for S3 objects is pain

### ISSUE THREAD

**Issue by khageshsaini** [aws/aws-sdk-php#1457]
I have been going through the SDK to find a way to figure out how to get URIs for Presigned requests in bulk using command pool. I tries using Middleware::requestBuilder method to transform command to request, but to no success. Is there a way to do this?

**Comment by kstich** [comment]
Please see [this guide for S3 Pre-Signed URLs](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-presigned-url.html). If you have further general usage questions, please ask on [StackOverflow](https://stackoverflow.com/) and tag it with [`aws-php-sdk`](http://stackoverflow.com/questions/tagged/aws-php-sdk).
