### ISSUE TITLE
AWIS and Alexa Top Sites Support

### ISSUE THREAD

**Issue by smartinec** [aws/aws-sdk-php#1472]
Per this email, do you plan to add support for AWIS and Alexa Top Sites?

In accordance with AWS security guidelines, the Alexa Web Information Service and Alexa Top Sites API’s now support the use of IAM credentials. The support for using root account credentials to access these services will be discontinued on January 31, 2018. 

In order to continue using the Alexa Web Information Service and Alexa Top Sites services, you will be required to create an IAM user in your AWS account and make slight code changes anywhere your applications make calls to these API’s. Our code samples (AWIS[1], Alexa Top Sites[2]) and documentation (AWIS[3], Alexa Top Sites[4]) have been updated to reflect these changes. 

Migration to the new request format must be completed by January 31, 2018. 

If you have any questions or concerns about these changes, you have 2 options for contacting Alexa.com support:

1. If you have an Alexa.com account, please login to https://www.alexa.com/help and submit a help request.
2. Post to the relevant API forum (AWIS, Alexa Top Sites).

We apologize for any inconvenience this may cause. Thank you for your continued use of Alexa's API and for helping us make this service more secure.

[1] https://aws.amazon.com/code/AWIS
[2] https://aws.amazon.com/code/Alexa-Top-Sites/
[3] https://aws.amazon.com/documentation/awis/
[4] https://aws.amazon.com/documentation/alexa-top-sites/

**Comment by kstich** [comment]
We currently do not support AWIS or Alexa Top Sites in the AWS SDK for PHP. Please voice your opinion via [alexa.com/help](https://www.alexa.com/help) or the [AWIS](https://forums.aws.amazon.com/forum.jspa?forumID=14) and [Alexa Top Sites](https://forums.aws.amazon.com/forum.jspa?forumID=13) forums.
