### ISSUE TITLE
Presigned PutObject URLs broken

### ISSUE THREAD

**Issue by MatthewBooth** [aws/aws-sdk-php#1476]
For some reason between 3.48 and 3.50 presigned URLs for uploading/PutObject are totally broken.

I get this error: `The request signature we calculated does not match the signature you provided. Check your key and signing method.`.

The key is fine and the signing method is fine. Zero code issues. How do I know this? Because it worked in 3.48 and the same code still generates valid presigned GetObject URLs.

Code that generates:

```php
       /**
     * Handles the request based on the given method
     *
     * @param string $objectKey The object key for the request
     * @param string $method    The method used in the request command
     *
     * @return string
     */
    private function handler(string $objectKey, string $method)
    {
        $bucket = $this->adapter->getBucket();

        $s3Cmd = $this->client->getCommand($method, [
            'Bucket' => $bucket,
            'Key'    => $objectKey,
        ]);

        $expiry = env('MEDIA_API_EXPIRY_TIME_SECONDS') ?: self::SIGNED_TIME_IN_SECONDS;

        $s3Request = $this->client->createPresignedRequest($s3Cmd, '+' . $expiry . ' seconds');

        return $s3Request->getUri()->__toString();
    }
```
`$method` is either "GetObject" or "PutObject":

```php
   /**
     * Creates a pre-signed URL to download/access a file that will expire after a given time
     *
     * @param string $objectKey The object key of the file that will be downloaded
     *
     * @return string
     */
    public function download(string $objectKey)
    {
        return $this->handler($objectKey, self::GET_OBJECT);
    }

    /**
     * Creates a pre-signed URL to upload a file that will expire after a given time
     *
     * @param string $objectKey The object key of the file that will be uploaded
     *
     * @return string
     */
    public function upload(string $objectKey)
    {
        return $this->handler($objectKey, self::PUT_OBJECT);
    }
```

Spent a couple of hours with this before realising the PHP AWS SDK library updated two days ago and now this is broken, so I suspect they're related.

For brevity, the constants:

```php
    const GET_OBJECT = "GetObject";
    const PUT_OBJECT = "PutObject";
    const SIGNED_TIME_IN_SECONDS = 300;
```

**Comment by kstich** [comment]
I am unable to reproduce your issue with the following code on version 3.50.0 of the AWS SDK for PHP:

```php
$cmd = $s3->getCommand('PutObject', [
    'Bucket' => $bucket,
    'Key' => $key,
]);

$uri = (string) $s3->createPresignedRequest($cmd, '+300 seconds')->getUri();

$request = new \GuzzleHttp\Psr7\Request(
    'PUT',
    $uri,
    [],
    'This is a test.'
);
$client = new \GuzzleHttp\Client();
$client->send($request);
```

Can you please provide the patch version of 3.48 of the AWS SDK for PHP that you were using? Was the AWS SDK for PHP the only dependency that updated for you in that time? Is it possible there were credentials or permissions changes that have been made that could cause the signature mismatch?

**Comment by MatthewBooth** [comment]
Hi

I am using 3.48.0 exactly.

There are no permission changes on the IAM role I'm using. It has the following policy attached:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1420044805001",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:ReplicateObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::bucket-name",
                "arn:aws:s3:::bucket-name/*",
                "arn:aws:s3:::another-bucket",
                "arn:aws:s3:::another-bucket/*"
            ]
        }
    ]
}
```

I'm using Laravel and FlySystem to abstract out the Filesystem on my project. I can get signed URLs to objects that are within the buckets, no issues, using the same credentials that fail on Put. There is no bucket policy assigned (I want everything private on there with only IAM access).

**Comment by kstich** [comment]
Was the AWS SDK for PHP the only dependency that updated for you in that time or were there others as well? Can you provide how you're then consuming the pre-signed URL?

Please note that when creating pre-signed URLs, the headers that are present when a request is signed must also be present when using the pre-signed URL. This means that creating things like pre-signed PUT requests with a content-type require that the actual PUT you send use the same content-type.

**Comment by MatthewBooth** [comment]
Hi,

Thanks for that last reply. The key was that I was POSTing the data rather than PUTing the data. As soon as I changed the HTTP method to PUT it worked no problem.

I'm an idiot.

Thanks!
