### ISSUE TITLE
PutObject make file double size

### ISSUE THREAD

**Issue by sm2017** [aws/aws-sdk-php#1479]
I create a script similar to https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/commands.html?highlight=commandpool#commandpool

```php 
<?php
require 'vendor/autoload.php';

use Aws\Exception\AwsException;
use Aws\S3\S3Client;
use Aws\CommandPool;
use Aws\CommandInterface;
use Aws\ResultInterface;
use GuzzleHttp\Promise\PromiseInterface;

// Create the client.
$client = new S3Client([
    'region'  => 'us-standard',
    'version' => '2006-03-01'
]);

$fromDir = '/path/to/dir';
$toBucket = 'my-bucket';

// Create an iterator that yields files from a directory.
$files = new DirectoryIterator($fromDir);

// Create a generator that converts the SplFileInfo objects into
// Aws\CommandInterface objects. This generator accepts the iterator that
// yields files and the name of the bucket to upload the files to.
$commandGenerator = function (\Iterator $files, $bucket) use ($client) {
    foreach ($files as $file) {
        // Skip "." and ".." files.
        if ($file->isDot()) {
            continue;
        }
        $filename = $file->getPath() . '/' . $file->getFilename();
        // Yield a command that will be executed by the pool.
        yield $client->getCommand('PutObject', [
            'Bucket' => $bucket,
            'Key'    => $file->getBaseName(),
            'Body'   => fopen($filename, 'rb')
        ]);
    }
};

// Now create the generator using the files iterator.
$commands = $commandGenerator($files, $toBucket);

// Create a pool and provide an optional array of configuration.
$pool = new CommandPool($client, $commands, [
    // Only send 5 files at a time (this is set to 25 by default).
    'concurrency' => 5,
    // Invoke this function before executing each command.
    'before' => function (CommandInterface $cmd, $iterKey) {
        echo "About to send {$iterKey}: "
            . print_r($cmd->toArray(), true) . "\n";
    },
    // Invoke this function for each successful transfer.
    'fulfilled' => function (
        ResultInterface $result,
        $iterKey,
        PromiseInterface $aggregatePromise
    ) {
        echo "Completed {$iterKey}: {$result}\n";
    },
    // Invoke this function for each failed transfer.
    'rejected' => function (
        AwsException $reason,
        $iterKey,
        PromiseInterface $aggregatePromise
    ) {
        echo "Failed {$iterKey}: {$reason}\n";
    },
]);

// Initiate the pool transfers
$promise = $pool->promise();

// Force the pool to complete synchronously
$promise->wait();

// Or you can chain then calls off of the pool
$promise->then(function() { echo "Done\n"; });
```

I found that sometimes , I have files that uploaded in S3 bucket in **EXACTLY DOUBLE SIZE** , If my local size is `A` then the S3 size is `A*2` exactly , I don't know why after uploading million files , just some file has double size in s3 , I think there is a bug in SDK that rewind position of `fopen($filename, 'rb')` stream pointer

I download double sized file  , and split it to 0-half and half-end , both are same file

**Comment by kstich** [comment]
I'm not able to reproduce your issue. Is there anything consistent about the files or timing (same file(s) over time, same size files, etc.)? What happens if you try to re-upload one of the double size files? Is this only files uploaded with 'rb' or does it occur with files uploaded with 'r' as well?

**Comment by sm2017** [comment]
> Is there anything consistent about the files or timing (same file(s) over time, same size files, etc.)?
No , there is no pattern

> What happens if you try to re-upload one of the double size files? 
Uploaded correctly , No double size

> Is this only files uploaded with 'rb' or does it occur with files uploaded with 'r' as well?
As reproduction is hard , I don't know , But I never use 'r' mode , I just use 'rb' mode

**Comment by kstich** [comment]
I'm still not able to reproduce this issue. Can you check the 'Content-Length' sent via [enabling the `'debug'` flag](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#debug)?

The SDK passes the resource from your `fopen` [call directly to `Psr7\stream_for()`](https://github.com/aws/aws-sdk-php/blob/master/src/Api/Serializer/RestSerializer.php#L117) and in to the `GuzzleHandler` via a `Psr7\Request` object. Can you please provide the versions of `GuzzleHttp\Guzzle` and `GuzzleHttp\Psr7` you are using?

**Comment by sm2017** [comment]
@kstich I try to reproduce issue , wait 24 hours for my reply

**Comment by kstich** [comment]
Closing due to lack of reply. Please let us know here if there's any new information and we can continue to discuss. If you do, can you please provide the versions of `GuzzleHttp\Guzzle` and `GuzzleHttp\Psr7` you are using?
