### ISSUE TITLE
Got CURLE_RECV_ERROR - assumed 'CURLE_RECV_ERROR'  error when using version 3.52.

### ISSUE THREAD

**Issue by loepa1994** [aws/aws-sdk-php#1480]
I got this error
`CURLE_RECV_ERROR - assumed 'CURLE_RECV_ERROR'`

I'm developing in PHP 7, Ubuntu 16.04, laravel 5.5 as framework.

Ever since updating the sdk to version 3.52, I got that error. I have since rolled back to version 3.48 and everything is back to normal.

The error stack head
`[2018-01-25 05:39:22] local.ERROR: Use of undefined constant CURLE_RECV_ERROR - assumed 'CURLE_RECV_ERROR' {"userId":4,"email":"admin@gmail.com","exception":"[object] (ErrorException(code: 0): Use of undefined constant CURLE_RECV_ERROR - assumed 'CURLE_RECV_ERROR' at /var/www/html/bla-bla/vendor/aws/aws-sdk-php/src/Middleware.php:185)`

Here's the code 
`$p = Storage::disk('s3')->put('image/user/'. Auth::user()->id_user .'/' . $image_name, file_get_contents($image), 'public');`

hopefully there will be a fix

**Comment by kstich** [comment]
The AWS SDK for PHP released an update in [version 3.52.0](https://github.com/aws/aws-sdk-php/releases/tag/3.52.0) that retries this specific CURLE code. [The AWS SDK for PHP requires cURL and its PHP extension to run.](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/getting-started/requirements.html) This error is because you do not have the cURL PHP extension installed or configured properly.

**Comment by kkopachev** [comment]
Documentation you referred to says cURL is not required, but recommended.

**Comment by kstich** [comment]
Apologies, this is from the Getting Started portion of the README file.

> Minimum requirements – To run the SDK, your system will need to meet the minimum requirements, including having PHP >= 5.5 compiled with the cURL extension and cURL 7.16.2+ compiled with a TLS backend (e.g., NSS or OpenSSL).

We'll work on updating the other relevant portions of the documentation or providing a compatibility layer.

**Comment by kkopachev** [comment]
@kstich I am confused. If cURL extension is required, then it must be in https://github.com/aws/aws-sdk-php/blob/master/composer.json#L18-L27
Guzzle itself provides stream handler wrapper to use if no cURL extension installed.

**Comment by kstich** [comment]
[This fix was released in 3.52.1](https://github.com/aws/aws-sdk-php/releases/tag/3.52.1).
