### ISSUE TITLE
Failed opening InvalidMessageContentsException.php

### ISSUE THREAD

**Issue by chungryan** [aws/aws-sdk-php#1484]
Hi, I had an instance of a file missing in the SQS SDK last week:
`Failed opening required 'xxxxxxxxx/vendor/aws/aws-sdk-php/src/Aws/Sqs/Exception/InvalidMessageContentsException.php'`

I'm using SDK v2.8.30
I know I should upgrade to the latest v3, but even the latest version doesn't seem to have that file
It seems to be in the java sdk though

Potential issue or am I missing something?
Thanks

**Comment by kstich** [comment]
V2 of the AWS SDK for PHP does not use modeled exceptions like in the Java SDK, the file and class do not exist. A `'InvalidMessageContentsException'` would be generated as a [`SqsException`](https://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.Sqs.Exception.SqsException.html) with `->getExceptionCode()` returning `'InvalidMessageContentsException'`.

**Comment by chungryan** [comment]
right... thanks
