### ISSUE TITLE
Elastic Transcoder. Audio control

### ISSUE THREAD

**Issue by MiragePresent** [aws/aws-sdk-php#1488]
Hello. I'm using Elastic Transcoder for edit videos in my project and I have a question: 
How can I use audio from first video and picture from second one?
Have I got an ability for it? As I understand no, but I hope to listen the other answer from you. 
Thanks

**Comment by kstich** [comment]
Based on [this forum thread](https://forums.aws.amazon.com/thread.jspa?threadID=144381), [the Elastic Transcoder FAQ](https://aws.amazon.com/elastictranscoder/faqs/), and no direct mention of support for this in [the API documentation](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-elastictranscoder-2012-09-25.html), I do no believe this is currently possible. You may wish to [ask on their forums for further details](https://forums.aws.amazon.com/forum.jspa?forumID=147).
