### ISSUE TITLE
s3 access denied 403

### ISSUE THREAD

**Issue by Himani-Bhatt** [aws/aws-sdk-php#1490]
Error executing "PutObject" on "https://my-shop1.s3.ap-south-1.amazonaws.com/products/b63c7e59ff9c6040161f80e436eaabab.jpg"; AWS HTTP error: Client error: `PUT  ▶
<?xml version="1.0" encoding="UTF-8"?>\n
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>E5EA21 (truncated...)\n
 AccessDenied (client): Access Denied - <?xml version="1.0" encoding="UTF-8"?>\n
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>E5EA2109F158B3BE</RequestId><HostId>ku8TuqbKq7fvjw5QenbrNDJx+beRZcqlEtLZICkHQEwgCJAqZ/l/qG6QV4RP+MODCFd80da0v9g=</HostId></Error>

**Comment by kstich** [comment]
Please make sure your account has access to write to the specified bucket. You can [read more on S3 Resource Permissions here](https://docs.aws.amazon.com/AmazonS3/latest/dev/s3-access-control.html).
