### ISSUE TITLE
Question : Hide url

### ISSUE THREAD

**Issue by sm2017** [aws/aws-sdk-php#1492]
I want to create a PHP script to hide s3 urls , I know the better way is described at https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html but my use case is different

At first attempt I use **Amazon S3 Stream Wrapper** but I see that **Opening Seekable streams** for my use case is not optimized as 
>Opening seekable streams allows you to seek only to bytes that were previously read. You cannot skip ahead to bytes that have not yet been read from the remote server

So I use
```php
$result = $client->getObject(array(
    'Bucket' => $bucket,
    'Key'    => 'data.txt'
));
```
When whole file is requested
Or the following code if `HTTP_RANGE` is set
```php
$result = $client->getObject(array(
    'Bucket' => $bucket,
    'Key'    => 'data.txt',
    'Range' => "bytes=$start-$end",
));
```

In both scenario 

```php
$result['Body']->rewind();

while ($data = $result['Body']->read(1024)) {
    echo $data;
}
```

My issue is when a user request to download a file with 5MB size , starting download takes long because The SDK will store the data in a temporary PHP stream and then echo to client so my download script has a long delay to starting download , the bad part is multi chunk download

**Comment by kstich** [comment]
The HTTP request for the contents is completed before we generate a response. You can check the transfer stats by [setting the `'stats' => true` config setting](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#stats).

Additionally, if your `$start` and `$end` are 0 and the file size, respectively, you will still be downloading the whole file.
