### ISSUE TITLE
eof issue

### ISSUE THREAD

**Issue by sm2017** [aws/aws-sdk-php#1493]
For `getObject` operation

```php
$result = $client->getObject(array(
    'Bucket' => $bucket,
    'Key'    => 'data.txt'
));
```

Why the output of the following codes is different? (removing `$result['Body']->rewind();` has no effect)

```php
$result['Body']->rewind();

while ($data = $result['Body']->read(1024)) {
    echo $data;
    flush();
}
```

```php
$result['Body']->rewind();

while (!$result['Body']->eof()) {
    echo $result['Body']->read(1024);
    flush();
}
```

in the second code , the last chunk is not printed

**Comment by kstich** [comment]
The `$result['Body']` for a `getObject` call is a `Psr7\Stream` object. I'd recommend asking on [that repository.](https://github.com/guzzle/psr7/issues)
