### ISSUE TITLE
isConnectionError

### ISSUE THREAD

**Issue by sm2017** [aws/aws-sdk-php#1495]
In the following code

```php
try {
    $client = new \Aws\S3\S3Client([
        'region' => 'us-west-2',
        'version' => 'latest',
        'http' => [
            'connect_timeout' => 5,
        ]
    ]);
   $result = $s3->getObject(array(
       'Bucket' => $bucket,
       'Key'    => $keyname
   ));
} catch (\Aws\Exception\AwsException $e) {
    var_dump($e->isConnectionError());
}
```

When connection timed out `isConnectionError` is `false` , I think it must be `true` 

* must be `isConnectionError` false?
* How can I detect from `\Aws\Exception\AwsException` that connection is timed out , the S3 server is down , there is a network issue ,...

**Comment by kstich** [comment]
`isConnectionError` returns `true` for [these cases if you use cURL](https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L154) and [these cases if you use file streams](https://github.com/guzzle/guzzle/blob/master/src/Handler/StreamHandler.php#L60). You can inspect the handler context [via `getHandlerContext`](https://github.com/guzzle/guzzle/blob/master/src/Exception/RequestException.php#L204) on the underlying exception.

**Comment by sm2017** [comment]
@kstich When I use cURL it returns `true` and when stream it returns `false` and `getHandlerContext` is empty array

**Comment by sm2017** [comment]
@kstich , I have a file located on multiple S3 servers
I want to create a script that detect server/network failure , When you request a file that located on server A , B and C , the script randomly pick a server for example B , the if B cannot serve file for any reason (Network failure , down time , ...) switch to server A

How can I detect it ? it seems  `isConnectionError` is not my response

**Comment by kstich** [comment]
It looks like you've already submitted guzzle/guzzle#2012 to update their list of file stream based connection errors.

Closing this issue as it doesn't seem to be an issue with the SDK itself.
