### ISSUE TITLE
is there still no way to perform a sync between local and s3 folder without using the CLI tool?

### ISSUE THREAD

**Issue by vesper8** [aws/aws-sdk-php#1498]
this question was asked in 2015 and the answer was.. using the Transfer method does a blind transfer.. if you want to actually do a sync and only transfer files that are not already there.. then use the AWS CLI

now in 2018.. is there still no way to perform a Sync function via the php sdk ?

Is using the AWS CLI the only way?

If so, why? Why isn't this feature available in the SDK too?

**Comment by kstich** [comment]
It looks like this is in reference to #839.The AWS SDK for PHP does not support the same sync functionality as the CLI. I'm going to leave this issue up for now for comment.

**Comment by Stadly** [comment]
This would be really nice to have!

**Comment by jeffkee** [comment]
My thoughts would be that such features such as syncing or file timestamp comparison etc. is up to each developer to create for their business purposes, not rely on Amazon. Amazon's SDK provides a gateway to perform the essential functions such as PUT requests to S3 securely and reliably, providing the framework. The rest of the work is up to each company. A file-sync module would essentially overstep the boundaries of what an SDK does, and become a utility of its own. Perhaps this is something a 3rd party developer can create & distribute as an open source framework to build upon, and still relying on the AWS provided SDK as the final tool.

**Comment by diehlaws** [comment]
Thanks for the updates on this, and I do apologize for the long delay in response from our end. As @jeffkee mentions, the AWS SDKs are intended to be wrappers for AWS service API calls in different languages with minimal customizations, as such this feature is not something we intend to implement in the AWS SDK for PHP.

That being said, the [S3 Stream Wrapper](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-stream-wrapper.html) for the AWS SDK for PHP allows you to use functions native to PHP (such as `file_get_contents`, `fread`, `fopen`, `is_file`, `is_dir`, etc) with S3 buckets and objects, which you could leverage to implement your own synchronization functionality between S3 and your host in a way that best fits your needs.
