### ISSUE TITLE
exponentialDelay in RetryMiddleware is a weighted random backoff, not an exponentialDelay

### ISSUE THREAD

**Issue by jeichorn** [aws/aws-sdk-php#1501]
The exponentialDelay RetryMiddleware is implemented like:

```
return mt_rand(0, (int) min(20000, (int) pow(2, $retries) * 100));
```

Since its just returning a random backoff from zero to an ever increasing value the chance of getting increasing backoffs is too low.

Some quick testing i did for example: https://gist.github.com/jeichorn/df14167d31932cbd850c0d846738b419

For both CloudFront and Route53 this will cause rate limiting errors in any batch operation.  CloudFront is especially bad since its update pattern requests a read before each update.

Something like:
```
return min(20000, (int) pow(2, $retries) * 100) + mt_rand(0, 100);
```

Where you have an exponential backoff plus 100ms of jitter seems to make more sense.
https://gist.github.com/jeichorn/ac1a06f6b5792c31324e84c97f367aff

**Comment by kstich** [comment]
Thanks for bringing this to our attention. For note, the `exponentialDelay` function uses [what we call "Full Jitter"](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/).

I'll be taking a look at reproducing this and making potential changes to it based on some discussions, [like we have for the `DynamoDbClient`](https://github.com/aws/aws-sdk-php/blob/master/src/DynamoDb/DynamoDbClient.php#L73).

**Comment by kstich** [comment]
@jeichorn Can you please provide which specific operations you're running in to issues with?

**Comment by jeichorn** [comment]
We see random failures on route53 on a regular basis, and I hit it every time I ran a batch job against a zone updating 10k cnames.

The worst offender is cloudfront.  To make an update you first need to read the config using
`getDistributionConfig` then update with `updateDistribution`.  Doing a batch of updates against 100 distributions I was never able to read and update them all without setting retries to 10.

**Comment by kstich** [comment]
It looks like [Route53 caps at 5 requests per second on their API](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html#limits-api-requests) before sending back [a `Throttling` message that we retry](https://github.com/aws/aws-sdk-php/blob/master/src/RetryMiddleware.php#L25). Can you please provide a sample of how you're invoking these API calls?

**Comment by jeichorn** [comment]
Missed this question.  In the route53 case, its using a paginator on a zone with 10k cnames, and doing update calls in each iteration.

```
$iterator = $api->getPaginator(...);
foreach($iterator as $item) {
   $api->changeResourceRecordSets(...);
}
```

Its a similar use case in Cloudfront, only you hit problems quicker since an each update request an extra get first.

But really this is basic math.  As long as my api calls are fast, when i'm paginating like I will hit backoff.  Your full jitter increases the chance of a long sleep but it doesn't guarantee it.  In any case where I get the short sleep 3 times in a row i'm done.  If i do batch operation where i'm going to see 2k 503s given the math, i'm pretty much guaranteed to fail on the default settings.
