### ISSUE TITLE
Stream Connection Timeout

### ISSUE THREAD

**Issue by sm2017** [aws/aws-sdk-php#1505]
@kstich according to https://github.com/aws/aws-sdk-php/issues/1452#issuecomment-353495709

>Timeouts are not altered or supplied by the AWS SDK for PHP, just passed through to Guzzle

I found that is wrong , in the following code `10.10.10.100` is not exists to simulate down time of server , As I set `'stream' => true`  , `connect_timeout` don't works so I use `ini_set`

```php
ini_set('default_socket_timeout', 1);
$client = new GuzzleHttp\Client();
try {
    $res = $client->request('GET', 'https://10.10.10.100', [
        'stream' => true,
        'synchronous' => true,
    ]);
} catch (Exception $e) {
   //JUST IGNORE ERRORS
}
```

The above mentioned code works well and timed out after a second

But the following , NOT , it just affect by `default_socket_timeout` and real timeout is between 4-12 seconds when I set  `default_socket_timeout` less than 4 it is 4 and when I set `default_socket_timeout` more than 12 it is 12 , and for example when I set default_socket_timeout equal to 2 real timeout is 6 seconds

I know that https://github.com/guzzle/guzzle/blob/master/src/Handler/StreamHandler.php#L322 is executed by SDK

```php
ini_set('default_socket_timeout', 1);
try {
    $s3= new \Aws\S3\S3Client([
        'region' => 'us-west-2',
        'version' => 'latest',
        'endpoint' => 'https://10.10.10.100',
    ]);
   $result = $s3->getObject(array(
       'Bucket' => $bucket,
       'Key'    => $keyname
   ));
} catch (Exception $e) {
       //JUST IGNORE ERRORS
}
```

**Comment by kstich** [comment]
Can you please clarify what the 'NOT' is prefacing in this paragraph?

>But the following , NOT , it just affect by default_socket_timeout and real timeout is between 4-12 seconds when I set default_socket_timeout less than 4 it is 4 and when I set default_socket_timeout more than 12 it is 12 , and for example when I set default_socket_timeout equal to 2 real timeout is 6 seconds

Also, can you please post the contents of `$e->getMessage()` from inside the `catch` block?

**Comment by sm2017** [comment]
@kstich sorry . I make a mistake , The following code can reproduce issue

```php
ini_set('default_socket_timeout', 1);
$start = microtime(true);
try {
    $s3 = new \Aws\S3\S3Client([
        'region' => 'us-east-1',
        'version' => 'latest',
        'endpoint' => 'https://10.10.10.100',
//        'credentials' => [
//            'key' => 'a',
//            'secret' => 'b'
//        ],
        'http' => [
            'stream' => true,
            'synchronous' => true,
        ]
    ]);
    $result = $s3->getObject(array(
        'Bucket' => 'a',
        'Key' => 'b'
    ));
} catch (Exception $e) {
    echo $e->getMessage()."\n";
}
```

If you execute the above mentioned code , execute time is about 1 second , and `$e->getMessage()` is 

>Error retrieving credentials from the instance profile metadata server. (cURL error 28: Connection timed out after 1000 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))

But when you uncommend `credentials` part , execute time is about 4 seconds while we want get timeout exception after 1 second , in this case `$e->getMessage()` is 

>Error executing "GetObject" on "https://10.10.10.100/a/b"; AWS HTTP error: Error creating resource: [message] fopen(https://10.10.10.100/a/b): failed to open stream: Connection timed out
[file] vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 324

As you know fopen timeout must be equal to`default_socket_timeout`

**Comment by kstich** [comment]
It looks like your additional time is being used by retries. When I set [the `'retries' => 0` option](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#retries), I receive the same roughly 1s timeout.

In your first case (credentials commented out), the process is failing to receive any credentials for the client and stopping there. In the second case (credentials uncommented), the process is attempting multiple getObject calls (1+[3 retries by default](https://github.com/aws/aws-sdk-php/blob/master/src/ClientResolver.php#L144)) and failing each time before the final failure.
