### ISSUE TITLE
Custom Domain for V2

### ISSUE THREAD

**Issue by RemoFiorentino** [aws/aws-sdk-php#1512]
First I don't if u are still giving support to V2 but asking does not hurt. 

I am trying to set a custom endpoint to test some features 
```
$aws = $aws = \AWS::factory(array(
            'endpoint' => "localhost:4572"
        ));
        $this->s3 = $aws->get('s3');
```

It is giving this error at the time to put images in the server with  this wrong url
//mybucket.localhost:4572/img.jpg

**Comment by kstich** [comment]
V2 of the AWS SDK for PHP [uses virtual host style bucket addressing by default](https://github.com/aws/aws-sdk-php/blob/2.8/src/Aws/S3/BucketStyleListener.php#L39). If you wish to switch to path style, removing the `'mybucket.'` from before the endpoint you set, include the `'PathStyle' => true,` option in your client configuration or S3 methods.
