### ISSUE TITLE
Improve usability around 'region' and 'version' parameters

### ISSUE THREAD

**Issue by atrauzzi** [aws/aws-sdk-php#1515]
Just getting started with this SDK for the first time and I noticed that I'm required to provide what version of certain APIs I'd like to use.

Any chance these can become constants as well as one that's something like "latest"?  Makes it easier than trying to hunt and peck around for magic strings like `"2006-03-01"`

Also, would love to see a page somewhere in the AWS docs that lists all the versions out for the various services.

**Comment by atrauzzi** [comment]
Heck, let's include regions in with this too.

**Comment by kstich** [comment]
Thanks for the enhancement request. In the mean time, the API versions are [listed under the Service APIs heading here](https://docs.aws.amazon.com/aws-sdk-php/v3/api/) and the region availability is listed [in the AWS docs](https://docs.aws.amazon.com/general/latest/gr/rande.html) and [in `src/data/endpoints.json(.php)` in the SDK](https://github.com/aws/aws-sdk-php/blob/master/src/data/endpoints.json).

**Comment by kstich** [comment]
Copy-over of comment from #1516:

>It would be nice if there was a utility class that was able to do lookups for things like regions and other instance metadata without having to be pre-configured ahead of time. Whether these are static calls or just an instance that doesn't require the region and other required parameters.

**Comment by atrauzzi** [comment]
@kstich - Awesome, thanks.  Is there any way for me to grab the region of the machine I'm currently on via the SDK?

**Comment by kstich** [comment]
Currently, that would be by reaching out to the [Instance Identity Document](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-identity-documents.html). We provide something like this for credentials via the [`InstanceProfileProvider`](https://github.com/aws/aws-sdk-php/blob/master/src/Credentials/InstanceProfileProvider.php), but not for region at this time.

**Comment by jschwarzwalder** [comment]
@atrauzzi Did the docs that kstich link help get you unstuck? 

Where did you expect to find the page that lists all the versions?

Is there other information you were looking for to help you get started?

Thanks for your feedback.

**Comment by atrauzzi** [comment]
Not quite, I think my suggestion here is to get everything gathered together, but through PHP rather than having to manually write http requests to the metadata service to get information.

Then, for the constants, I guess they don't exist..?  So, I'm somewhat in a position of doing workarounds for the time being.
