### ISSUE TITLE
ini provider doesn't respect AWS_SHARED_CREDENTIALS_FILE env variable

### ISSUE THREAD

**Issue by Nilithus** [aws/aws-sdk-php#1518]
## Issue
When using the `ini` credential provider I realized that `AWS_SHARED_CREDENTIALS_FILE` is not used to try and resolve the shared file (like how it does in the awscli) if no filename was provided. Code below:
https://github.com/aws/aws-sdk-php/blob/c414752f2f88a036958438a3d973475c6786a387/src/Credentials/CredentialProvider.php#L283-L286

## Expected
I expected the `AWS_SHARED_CREDENTIALS_FILE` would be used to resolve the correct credential filename as it does for awscli. Example implementation below:

```php
const ENV_SHARED_CREDENTIALS_FILE = 'AWS_SHARED_CREDENTIALS_FILE';


public static function ini($profile = null, $filename = null)
{
    if (!$filename) {
        $filename = getenv(self::ENV_SHARED_CREDENTIALS_FILE) ?: (self::getHomeDir() . '/.aws/credentials');
    }
}
```

I think that the `localCredentialProvider()` function should also try and use `AWS_SHARED_CREDENTIALS_FILE` env variable for consistency.

## Possible issues
Technically this could be breaking if people have come to rely on the sdk ignoring this environment variable but it seems unlikely to me since it'd be opposite of the awscli. 

Curious what you guys think. Thanks!

**Comment by Nilithus** [comment]
If you mean interoperability as in "do the other SDK's use `AWS_SHARED_CREDENTIALS_FILE` to determine their shared credentials file location?" I took the liberty of poking through some of the other sdks to check. It seems to be common practice:
- The Go sdk checks it [here](https://github.com/aws/aws-sdk-go/blob/master/aws/credentials/shared_credentials_provider.go#L122-L124)
- Nodejs looks like it checks [here](https://github.com/aws/aws-sdk-js/blob/4869c8769e3ed42391739022e8f53014d326f9fa/lib/credentials/shared_ini_file_credentials.js#L110-L113) and it specifically calls out that it does it in a code comment [above](https://github.com/aws/aws-sdk-js/blob/4869c8769e3ed42391739022e8f53014d326f9fa/lib/credentials/shared_ini_file_credentials.js#L7-L9)
- Ruby has a [determine_credentials_path](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/shared_config.rb#L267) method also calls out the expected behavior in code comment [above](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/shared_config.rb#L34-L36)

Granted I didn't check all of them but seems pretty clear that the `AWS_SHARED_CREDENTIALS_FILE` should be respected.

**Comment by kkopachev** [comment]
Botocore (python sdk) checks it at https://github.com/boto/botocore/blob/03234ba7528defa57de12426d578d94e17296910/botocore/session.py#L90-L92
