### ISSUE TITLE
S3 PutObject presigned url ContentType ignored

### ISSUE THREAD

**Issue by decebaldecebal** [aws/aws-sdk-php#1521]
Using version 3.2.6 from the Symfony Bundle.
I have the following code in my app:

`$cmd = $this->s3client->getCommand('PutObject', [
            'Bucket' => 'myBucket',
            'Key' => 'inputs/' . $movie->getId(),
            'ACL' => 'private',
            'ContentType' => 'video/mp4',
        ]);

        $request = $this->s3client->createPresignedRequest($cmd, '+30 minutes');

        $movie->setSignedUrl((string)$request->getUri());`

The uri generated is not correct because it does not include the Content-Type header at all so I am able to upload any type of file using this url.The X-Amz-SignedHeaders part of the url only contains the host header but not the content type or other headers.

**Comment by kstich** [comment]
[The `'content-type'` header is not signed](https://github.com/aws/aws-sdk-php/blob/master/src/Signature/SignatureV4.php#L210) because signing it would potentially cause a signature mismatch when sending a request through a proxy or if modified at the HTTP client level.

**Comment by decebaldecebal** [comment]
So how can I then restrict the ContentType of files that a user can upload to my S3 bucket?

There needs to be some sort of way to only allow a user to only upload video files for example.

**Comment by kstich** [comment]
S3 does not restrict the ContentType for you. [The `'content-type'` header is used to describe the contents](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html#RESTObjectPUT-requests) and is attached to the object as metadata. If you wish to restrict the content uploaded, you'd have to perform the restriction in your application.

**Comment by vamsideepak** [comment]
my problem is related to this . i mentioned contentType:'video/mp4' and uploading videos to s3 bucket after that getting that video urls those are working in web and android but not in safari can anyone tell me.
note: uploading video webm format.
var pet_signed_url = s3.getSignedUrl('putObject', {
    Bucket: AWSConfig.BUCKET_NAME,
    Key: pet_vedio_key,
    ContentType: 'video/mp4',
    Expires: parseInt(AWSConfig.PROFILE_VIDEO_EXPIRATION_TIME)
    
  })
