### ISSUE TITLE
Login Users via Facebook Identity Providers

### ISSUE THREAD

**Issue by engharb** [aws/aws-sdk-php#1522]
Hello,

is there a possibility to login a user using the FB, google account and automatically generate a user account in UserPool?

I have struggled to find such solution in AWS JS but I could not find any concreted implementation.

regards,

**Comment by kstich** [comment]
You can find the AWS SDK for PHP [API documentation for the Cognito Identity Provider service here](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-cognito-idp-2016-04-18.html) and [the service Developer Guide here](https://docs.aws.amazon.com/cognito/latest/developerguide/what-is-amazon-cognito.html). You should be able to find what you need from there or you can [reach out on the Cognito forums here](https://forums.aws.amazon.com/forum.jspa?forumID=173).

If you're looking for the AWS SDK for JS, [here's the link for that repository](https://github.com/aws/aws-sdk-js).
