### ISSUE TITLE
Changing config after instantiation

### ISSUE THREAD

**Issue by jonathanbull** [aws/aws-sdk-php#1524]
Is there any way to change the client’s config, e.g. the region or credentials, _after_ it’s been instantiated?

Thanks!

**Comment by kstich** [comment]
The [configuration options](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html) are only accessible through the constructor. You can use an `Aws\Sdk` object for [shared configuration](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html) across clients, but cannot mutate client configuration.
