### ISSUE TITLE
CredentialsProvider error parsing ini file

### ISSUE THREAD

**Issue by ejunker** [aws/aws-sdk-php#1526]
`CredentialsProvider::ini()` calls `parse_ini_file()` and I am getting an error because my `~/.aws/credentials` file has a value with a `=` character in it. Notice that the values are not enclosed in double quotes.

Example line from file:
```
aws_session_token = XdzEH4aDOeOsB1oDAJKSfqtuyLFAsK+/XW9Oyz4Xxe21gqG+DehCJwDJluIiEW2e3kcR6rAXK6nOh/yD5x5k478B/bDThMCrXzbNbVjPOKn91+InjsvlAxU9LOp/WZFMyUe8A/m/hcA6kJtlldtIZEYXMlzQKwG3FUliq34YLriSlUFO4HMHj7kVUuqMJ/cS/JRr+CJvuNqTRCItx6tRLv1iDDn9Ui2y1wmYy98CuuD2xxlaIEc4wrhNSfLbmFW9YAj2cHRZ150rZUAOLVWFbpAx0/c7ZwL9qgWWgPRDuK0jGb+Z4WduQv+sVbmzkV17umS+XvJOue+6tm3X2hEh/NUJ6YygYt7QcwuAve0MPL/fOaCag1RAbH0mSWA15G7pEdQlRfJSUol8u1ZZJNcd2WnMlHxsVME0dAylcc4NjpjhXrAoW3S0svnpkU3i7F0ZaGi0iuFFqCvDI0oxp+a1gU=
```

I found that it works if I add the `INI_SCANNER_RAW` option in `CredentialsProvider::ini()`
```
$data = parse_ini_file($filename, true, INI_SCANNER_RAW);
```

**Comment by holyspecter** [comment]
Any progress on this issue?

**Comment by jcolfej** [comment]
I confirm the problem is scanner mod : http://php.net/manual/en/function.parse-ini-file.php
If you set scanner mod to INI_SCANNER_RAW, I don't have problem like you @ejunker ;)

Can we patch it as soon as possible ?
