### ISSUE TITLE
How Do You Loop Through A CSV / XLS / XLSX File After Downloading File With getObject()?

### ISSUE THREAD

**Issue by pihish** [aws/aws-sdk-php#1529]
I have the following code that grabs a file from my S3 bucket and display its raw content :

```
$result = $this->s3_client->getObject(array(
    'Bucket' => env('AWS_S3_BUCKET'),
    'Key' => $file_key
));
// Display the object in the browser
header("Content-Type: {$result['ContentType']}");
echo $result['Body'];
```

The file I download will always be a CSV / Excel file. The above displays the contents of the file as a string.

How do I loop through each row of my file using the above - a la something similar to `fgetcsv()`?

I would like to avoid downloading the file onto my hard disk since I am assuming the AWS SDK stores the content of my file in memory when I call `getObject()`.

**Comment by jschwarzwalder** [comment]
It should return a string that you can parse.

Try using [str_getcsv()](https://secure.php.net/manual/en/function.str-getcsv.php), and write back if that doesn't help.
