### ISSUE TITLE
Connecting to KMS using EC2 instance profile?

### ISSUE THREAD

**Issue by dingo-d** [aws/aws-sdk-php#1530]
I'm running some tests and want to connect to the created KMS service that is set up to use instance profiles (so no `secret/key` combo needed).

I got the KMS details from my devops (region, ARN and Alias).

So I am trying with 

```php
use \Aws\Kms\KmsClient;
use \Aws\Credentials\CredentialProvider;

$provider = CredentialProvider::instanceProfile( array( 'profile' => 'alias-name' ) );

$memoized_provider = CredentialProvider::memoize( $provider );

$kms_client = KmsClient::factory( array(
    'region'      => 'eu-west-1',
    'version'     => 'latest',
    'credentials' => $memoized_provider,
    // 'debug'       => true,
));
```

I am trying to test a method that looks like this:

```php
public function get_key() {
  $result = $this->kms_client->generateDataKey( array(
      'KeyId' => 'key-id-here',
  ) );
  return $result;
}
```

And I get

> Aws\Exception\CredentialsException: Error retrieving credentials from the instance profile metadata server. (cURL error 28: Connection timed out after 1001 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))

How do I specify my instance? Where should that be provided? I put `alias` in the `instanceProfile`, but that's not working.

**Comment by dingo-d** [comment]
So the issue seems to be that I am not connecting to the server. 

Any way to do this? An example would help a lot.

**Comment by jschwarzwalder** [comment]
Thank you for reaching out.

There are many ways to connect to your ec2 instance depending on your ec2 configuration and which machine you are using to connect. Find detailed instructions at the [EC2 docs]( https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstances.html).

I have a Windows machine and used putty to connect to my Linux ec2 instance, but you might need to follow different steps.

If you authorized the ec2 itself, I do not believe that you need to specify credentials in the client construction.

Please message back if this does not resolve your issue.

**Comment by dingo-d** [comment]
Hmm not entirely sure about that. I think I'd need to provide some kind of credentials. I'll probably end up working on the EC2 server instance so to avoid all the mess of working with credentials (I am using IAM on the EC2 so might as well use it :D). Thanks for the help.
