### ISSUE TITLE
How to locally connect to EC2 instance?

### ISSUE THREAD

**Issue by dingo-d** [aws/aws-sdk-php#1532]
I'm trying to test the sdk locally, and the server setup I have is EC2 with credentials set up via IAM role attached to it. In the same way the S3 is set up, but I cannot connect to it either.

For S3 I know the region and the bucket name, but I always end up with the same error message:

> Aws\Exception\CredentialsException: Error retrieving credentials from the instance profile metadata server. (cURL error 28: Connection timed out after 1001 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))

I also need to connect to the KMS service, but this fails as well.

How do I write code if I cannot make unit tests to see if this will fail or not? :S

**Comment by jschwarzwalder** [comment]
See response to issue #1531
