### ISSUE TITLE
The SDK does not list all medialive channels, web interface does

### ISSUE THREAD

**Issue by norbert-yoimo** [aws/aws-sdk-php#1533]
The PHP SDK doesn't seem to list all the channels that are present in the account. Currently, I have 7 channels, that are listed correctly on the web interface, however, using the PHP SDK, I only get one channel back. The channels were created using the same access key as the one that is used when trying to list the channels. I'm attaching a file with some sample PHP code, and its output, that I'm trying to use. Using SDK version 3.54.6.

Sample code:

```php
<?php
require('vendor/autoload.php');
use Symfony\Component\Dotenv\Dotenv;

(new Dotenv())->load(__DIR__ . '/.env');

$sdk = new Aws\Sdk([
    'medialive' => [ 'version' => '2017-10-14' ],
    'mediastore' => [ 'version' => '2017-10-14' ],
    'region' => 'eu-west-1',
    'version' => 'latest'
]);

$client = $sdk->createClient('medialive');

$result = $client->listChannels();

var_dump($result['Channels']);

/*
 Outputs:

 array(1) {
  [0] =>
  array(10) {
    'Arn' =>
    string(56) "arn:aws:medialive:eu-west-1:486811772306:channel:8479850"
    'Destinations' =>
    array(2) {
      [0] =>
      array(2) {
        ...
      }
      [1] =>
      array(2) {
        ...
      }
    }
    'EgressEndpoints' =>
    array(2) {
      [0] =>
      array(1) {
        ...
      }
      [1] =>
      array(1) {
        ...
      }
    }
    'Id' =>
    string(7) "8479850"
    'InputAttachments' =>
    array(1) {
      [0] =>
      array(2) {
        ...
      }
    }
    'InputSpecification' =>
    array(3) {
      'Codec' =>
      string(3) "AVC"
      'MaximumBitrate' =>
      string(11) "MAX_10_MBPS"
      'Resolution' =>
      string(3) "UHD"
    }
    'Name' =>
    string(27) "norbert-team1-5add90f8aba36"
    'PipelinesRunningCount' =>
    int(0)
    'RoleArn' =>
    string(50) "arn:aws:iam::486811772306:role/MediaLiveAccessRole"
    'State' =>
    string(4) "IDLE"
  }
}
*/
```

**Comment by howardlopez** [comment]
It looks like the result set for your request is being split up - you should also see a `'NextToken'` attribute in the `Result` object that you can use to get the next result(s). 

One thing you can try is using a [paginator](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/paginators.html) for the `ListChannels` command:

```php
$results = $client->getPaginator('ListChannels');

foreach($results as $result) {
    var_dump($result->get('Channels'));
}
```

**Comment by norbert-yoimo** [comment]
You are correct, the result was split up, using the `NextToken` attribute solved the issue.

I'd suggest mentioning this in the docs, the result sets are split up in a surprising way, sometimes I get responses that contain 1 element (sometimes even 0 elements) that I have to iterate through.
