### ISSUE TITLE
Laravel Deprication

### ISSUE THREAD

**Issue by jakesyl** [aws/aws-sdk-php#1534]
[The Laravel SDK](https://github.com/aws/aws-sdk-php-laravel) does not work and appears to be completely deprecated. It doesn't work on anything past Laravel 5.2 and we're currently on Laravel 5.3. I'd suggest fixing it or removing links from the readme and deprecating the repo. 

Tagging @kstich @cjyclaire @jeskew as they seem to be maintainers. I was curious so I went through the [related projects](https://github.com/aws/aws-sdk-php#related-aws-projects). It looks like [Silex](https://github.com/aws/aws-sdk-php-silex) hasn't been updated since mid 2016 so it wouldn't surprise me if that was deprecated as well. A few of the other projects have several open prs/issues that are months or years old.

I'm not sure how these are managed, but it might be best to centralize issues since those repos get stale since most just wrap this repo. I'm also not entirely sure how those repos work (were they community repos brought into the @aws org?). but it's definitely worth considering a different way of managing these repos.

**Comment by kstich** [comment]
I am fully able to use the [AWS Service Provider for Laravel 5](https://github.com/aws/aws-sdk-php-laravel) in a new Laravel 5.4 project. The Service Provider provides access to the AWS SDK for PHP (this repo), which contains the AWS related updates. If you are having trouble with the Service Provider, I recommend filing an issue there.

Regarding the [AWS Service Provider for Silex](https://github.com/aws/aws-sdk-php-silex), this also provides access to the AWS SDK for PHP, which contains the AWS related updates. Additionally, [`"Silex is in maintenance mode."`](https://silex.symfony.com/).

The Service Providers themselves are typically low on maintenance unless the framework makes changes. The separation of repositories is meant to have issues with the SDK itself be filed on this repository, and issues with the various Service Providers specifically (configuration, etc.) be filed on their specific repositories.

**Comment by jakesyl** [comment]
Regarding laravel: https://github.com/aws/aws-sdk-php-laravel/issues/115. Let me try to duplicate on a fresh repository.

**Comment by vesper8** [comment]
the auto-discovery seems not to be working. But after adding the provider manually to the app.php then all works good
