### ISSUE TITLE
S3 getObjectUrl returning non secure URL

### ISSUE THREAD

**Issue by neoacevedo** [aws/aws-sdk-php#1548]
Hi.
This is a question more than a bug, _getObjectUrl_ is returning non secure URL (http instead https) but if I see in the aws console, the object URL has https. Could it to return a secure URL, or there is a mode inside SDK to achieve it?

Regards.

**Comment by kstich** [comment]
It's likely that, at some point in the client configuration, your [`'scheme'` configuration is set to `'http'`](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#scheme), overriding the default `'https'` value. Removing this, or setting it directly on the client (see below) should resolve your issue.

```php
$client = new S3Client([
    'version' => '2006-03-01',
    'region'  => 'us-west-2',
    'scheme'  => 'https'
]);
```

**Comment by neoacevedo** [comment]
I think the scheme key is the correct option. I unknew this option.
