### ISSUE TITLE
OpsWorksClient::describeLayers does not respect LayerIds parameter

### ISSUE THREAD

**Issue by iricketson** [aws/aws-sdk-php#1549]
PHP SDK 3.55.12: 

According to [the docs](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-opsworks-2013-02-18.html#describelayers), I should be able to pass the `LayerIds` parameter into the `describeLayers` method and return only those layers.  

Unfortunately it seems this this parameter is ignored.  The `StackId` parameter works as expected, but the `LayerIds` parameter doesn't work either on its own or in conjunction with the `StackId` parameter.

**Comment by kstich** [comment]
Can you please supply the code you're using to make the requests in question?

**Comment by iricketson** [comment]
@kstich 

```php
// Instance of Aws\OpsWorks\OpsWorksClient
$client = new OpsWorksClient($config);
$results = $client->describeLayers([
    'StackId' => 'stack-id-here',
    'LayerIds' => ['layer-id-here'],
]);
```

Regardless of `LayerIds` parameter, the request returns all layers for the stack.

**Comment by kstich** [comment]
The docs state that 'This call accepts only one resource-identifying parameter.' and the `OpsWorksException`'s message is 'Please provide one or more layer IDs **_or_** a stack ID' (emphasis added.)

I am able to use both of the following API calls successfully:

```php
$client->describeLayers([
    'StackId' => 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee',
]); // Returns all Layers in the Stack

$client->describeLayers([
    'LayerIds' => [
        'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee'
    ]
]); // Returns the specific Layer, regardless of Stack
```

If you still have issues after adopting the singular identifying parameter, please post the exact exception message you receive.
