### ISSUE TITLE
Machine Learning / Parameter syntax

### ISSUE THREAD

**Issue by reydajp** [aws/aws-sdk-php#1550]
Hi, 

PHP SDK 3.56.1;

According to the [docs](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-machinelearning-2014-12-12.html#predict), the parameter syntax for `predict` method should be able to

```
$client->predict([
    'MLModelId' => '<string>', // REQUIRED
    'PredictEndpoint' => '<string>', // REQUIRED
    'Record' => ['<string>', ...], // REQUIRED
]);

```

But when I pass an array with strings into `Record` parameter, I'm getting this error `message Found 1 error while validating the input provided for the Predict operation: [Record] must be an associative array. Found array(1)`.

here is my code:

```
$client = new MachineLearningClient([
    'credentials' => $aws,
    'region' => 'XXXX',
    'version' => '2014-12-12'
]);

$client->predict([
	'MLModelId' => 'ml-XXXXX',
	'PredictEndpoint' => 'https://XXXXXXXX',
	'Record' => ['Lorem Ipsum']
])
```
    
As the doc isn't really clear, Can anyone provide an example of the syntax for  `Record`  key please ?

**Comment by kstich** [comment]
The documentation you linked states the following for the `Record` parameter:

>**Record**
>_Type: Associative array of custom strings keys (VariableName) to strings_
>A map of variable name-value pairs that represent an observation.

Meaning something like this is required:

```php
$client->predict([
    'MLModelId' => 'ml-XXXXX',
    'PredictEndpoint' => 'https://XXXXXXXX',
    'Record' => ['ExampleData' => 'ExampleValue'],
])
```

**Comment by reydajp** [comment]
@kstich 

Thanks for you help.

The exception error gone but it's still weird.
1 . The prediction score is different between my request from the SDK response and the AWS console one.
2 . I noticed that even if I change the string value, this have not incidence on the prediction score and getting always the same.

From aws console:

![real_time](https://user-images.githubusercontent.com/6067762/40150378-42d9e254-59b4-11e8-9fcf-9dfe91e27472.png)

The score I supposed to have:
![score](https://user-images.githubusercontent.com/6067762/40150384-4aa5de8e-59b4-11e8-8857-5be072aebbb7.png)

My code:

```
$ml->predict([
            'MLModelId' => 'ml-ooDjE3HYpj5',
            'PredictEndpoint' => 'https://realtime.machinelearning.us-east-1.amazonaws.com',
            'Record' => [
                'Name' => 'Var2',
                'Type' => 'Text',
                'Value' => 'This is an apple.'
            ]
        ]);

```
The score from the SDK response:

```
object(Aws\Result) {
	[private] data => array(
		'Prediction' => array(
			'predictedLabel' => 'Diary',
			'predictedScores' => array(
				'Daily Essay' => (float) 0.3212323486805,
				'Diary' => (float) 0.44966238737106,
				'General/Others' => (float) 0.22910524904728
			),
			'details' => array(
				'Algorithm' => 'SGD',
				'PredictiveModelType' => 'MULTICLASS'
			)
		),
		'@metadata' => array(
			'statusCode' => (int) 200,
			'effectiveUri' => 'https://XXXXXXXXXX',
			'headers' => array(
				'x-amzn-requestid' => '0x4398adb',
				'content-type' => 'application/x-amz-json-1.1',
				'content-length' => '224',
				'date' => 'Wed, 16 May 2018 23:58:19 GMT'
			),
			'transferStats' => array(
				'http' => array(
					(int) 0 => array()
				)
			)
		)
	)
}
```

If i change the string value with `'The sky is blue.`

Score from AWS Console:

```
{
    "Prediction": {
        "details": {
            "Algorithm": "SGD",
            "PredictiveModelType": "MULTICLASS"
        },
        "predictedLabel": "Daily Essay",
        "predictedScores": {
            "Daily Essay": 0.383843332529068,
            "Diary": 0.3686932623386383,
            "General/Others": 0.2474634051322937
        }
    }
}
```

Score from the SDK response:
same as the first example of SDK response.

I think My Record parameter syntax is not valid. That is why I'm getting always the same score.
So what is the right syntax ?

**Comment by reydajp** [comment]
@kstich 

Yes I tried with the `'Name' => 'Value'` pair but getting the same result....
Ok I will take a look at the forum. 

Thanks for you help.
