### ISSUE TITLE
S3 deleteObject is not deleting "directories"

### ISSUE THREAD

**Issue by neoacevedo** [aws/aws-sdk-php#1553]
Hi.

I'm noticing _deleteObject_ for Amazon S3 in a non-versioned Bucket is not deleting "directories" (I know there is not actually any directory/folder on S3 but else files named wit a slash at the end) but is deleteing any other object.

I do as this:
```
$s3->deleteObject(array('Bucket' => BUCKET_S3, 'Key' => $object_file->filepath));
```
But when I call this code, I get a value like:

> DeleteMarker: 0
> VersionId: ""
> Requestharged: ""
> (a)metadata:
>    StatusCode: 204
>    effectiveUri: "http://mybucket.s3.amazonaws.com/my-folder-key"
>    headers: <array with headers values>
>    transferStatus:
>        http:
>             0:

If I check, the folder still exsists and is never deleted.

My code follows this guidline: https://docs.aws.amazon.com/AmazonS3/latest/dev/DeletingOneObjectUsingPHPSDK.html but as I mentioned, only deletes files, not directories.

**Comment by howardlopez** [comment]
You're right about S3's 'directory' representation, which means you can't simply delete them as you would a normal file directory. One simple way to delete a 'directory' is to get all the objects of a certain prefix (i.e. your 'directory' path) using [`listObjectsV2`](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#listobjectsv2) and then delete them with [`deleteObject`](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#deleteobject) or [`deleteObjects`](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#deleteobjects)

```php
$results = $s3->listObjectsV2([
    'Bucket' => 'your-bucket',
    'Prefix' => 'path/to/your/directory'
]);

if (isset($results['Contents'])) {
    foreach ($results['Contents'] as $result) {
        $s3->deleteObject([
            'Bucket' => 'your-bucket',
            'Key' => $result['Key']
        ]);
    }
}
```

**Comment by neoacevedo** [comment]
Good, my algorithm checks if the directory is empty. If isn't empty doesn't allow to delete it, if is empty, it can be deleted.
But in previous versions of aws SDK (phar version < 3.54) I was able to delete it calling deleteObject and passing as key the directory path, but from the phar version 3.55.12, I'm not able to achieve it.

**Comment by howardlopez** [comment]
@neoacevedo To delete an empty S3 'directory', a trailing slash is necessary at the end of the path. In the example below, `path/to/directory` would not work as the `Key`.

```php
$s3->deleteObject([
    'Bucket' => 'your-bucket', 
    'Key' => 'path/to/directory/'
]);
```

**Comment by neoacevedo** [comment]
Actually I make it but it simply, doesn't work.

**Comment by howardlopez** [comment]
@neoacevedo Just to clarify, you're adding a `/` to the end of the directory path, and the directory is empty (i.e. there are no files whose path begins with the directory path)? 

If so, I'd suggest doing an experiment by creating an empty blank directory in the S3 console, and then trying that `deleteObject` call on it, and letting us know how that goes.

**Comment by neoacevedo** [comment]
Yes, I add a `/`. The main problem was in:
```
$results = $s3->listObjects([
    'Bucket' => 'your-bucket',
    'Prefix' => 'path/to/your/directory/'
]);
```
in **$results** variable, _Contents_ array was returning as first element the Prefix (I don't know why, in the documentation is not any explanataion) with or witouh any other element inside _Contents_, adding or not _'Delimiter' => '/'_ I got the same result, so I had to delete that first element into Contents array and finally become deleted.

Same performance with iterator (it didn't delete the directory):
```
$results = $s3->listObjectsV2([
    'Bucket' => 'your-bucket',
    'Prefix' => 'path/to/your/directory'
]);

if (isset($results['Contents'])) {
    foreach ($results['Contents'] as $result) {
        $s3->deleteObject([
            'Bucket' => 'your-bucket',
            'Key' => $result['Key']
        ]);
    }
}
```
After removing the first element into Contents array, it could delete the directory.

**Comment by howardlopez** [comment]
The first element returned should be the prefix, as `ListObjectsV2` is finding both the directory (whose key is the prefix) and the objects inside. The way to get rid of the directory is to delete all of the objects returned, including the prefix (directory) object itself, which looks like it's working for you.

**Comment by nityaskashyap** [comment]
The S3 restricts the file deletion 1000 per DeleteObjectsRequest. Hence after fetching all KeyVersions List, I gave the check  if the keys are >1000, then partition the list into sublists and then pass it to the DeleteObjectsRequest with sublists as below- 


if(keys.size()>1000) {
				int count=0;
				List<List<KeyVersion>> partition = ListUtils.partition(keys, 1000);
				 for (List<KeyVersion> list : partition) {
					 count=count+list.size();
					 DeleteObjectsRequest request = new DeleteObjectsRequest(fileSystemConfiguration.getTrackingS3BucketName()).withKeys(list);
					 amazonS3Client.deleteObjects(request);
					 logger.info("Deleted the completed directory files "+ list.size()+ " from folder "+eventSpecificS3bucket);
				 }
				 logger.info("Deleted the total directory files "+ count+ " from folder "+eventSpecificS3bucket);
			}
			else {
				DeleteObjectsRequest request = new DeleteObjectsRequest(fileSystemConfiguration.getTrackingS3BucketName()).withKeys(keys);
				amazonS3Client.deleteObjects(request);
				logger.info("Deleted the completed directory files from folder "+eventSpecificS3bucket);
			}
