### ISSUE TITLE
Expired tokens with DoctrineCacheAdapter since some days

### ISSUE THREAD

**Issue by chregu** [aws/aws-sdk-php#1560]
Since some days (I unfortunately can't pinpoint exactly, if we updated the AWS SDK and that had some  effect, we do that regularly), we get `ExpiredTokenException` from time to time. After closer debugging, it looks like those Tokens just expired a second ago. I assume, we got it from the cache, but the request took longer than the token was valid (since it was invalid the next second) and then those request (to DynamoDB in our case) failed. 

- Is there a possibility to refresh the tokens in the cache a few seconds before they actually expire? In the code it looks like it's only refreshed at the exact second or after the token expired.
- Or is there a possibility to retry the request easily after such a response? Couldn't that be done on the API level? Or is there already a possibility for that?

The strange thing really is, that we had this code since months in our codebase and never had any problems, they just started a few days ago. The servers are also ntp synced with chrony, that shouldn't be the cause of the issues either.

We use
```
$credentials = new DoctrineCacheAdapter(new ApcuCache());
```
and an ec2 instance profile for the credentials.

**Comment by kstich** [comment]
Do you have any [debug logging](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#debug) for the requests that are failing due to stale cached credentials? That will help significantly in tracking down the issue here.
