### ISSUE TITLE
Object existence methods and delete markers

### ISSUE THREAD

**Issue by PabloWestphalen** [aws/aws-sdk-php#1561]
I think it would be nice if the [checkExistenceWithCommand ](https://github.com/aws/aws-sdk-php/blob/2d0508ddeac51bbb0e0f86465db6b7ac50a597fb/src/S3/S3ClientTrait.php#L283) method, in addition to returning true or false, threw a special exception or at least a specialized message in S3Exception for the uncovered, grey "object does exist but its latest version is a delete marker" area.

Maybe something in the lines of

        try {
            $this->execute($command);
            return true;
        } catch (S3Exception $e) {
            if ($e->getAwsErrorCode() == 'AccessDenied') {
                return true;
            }
            if ($e->getStatusCode() >= 500) {
                throw $e;
            }

    +       if (!empty($e->getResponse()->getHeaders()["x-amz-delete-marker"])) {
    +           throw new S3Exception('File exists, but its current version is a delete marker', $command, null, $e);
    +       }

            return false;
        }

**Comment by kstich** [comment]
Adding an exception here would be a behavior change and muddy the object being deleted. The object, having been previously deleted, does not exist in the current version of the bucket.

We could add a behavioral flag for `$includeDeleteMarkers = false` to `doesObjectExist` (and subsequently `checkExistenceWithCommand`) to return true if the object being checked is a delete marker. Would that fit what you're looking for?

**Comment by PabloWestphalen** [comment]
Oh absolutely. I'm new to the SDK, and my proposal was the first yet probably naive solution i could think of (which is why i created the issue instead of going straight for a PR). Sure a flag that like that would work too.

**Comment by stobrien89** [comment]
@PabloWestphalen,

Are you still interested in this feature? Currently working on a second version of the existence helper methods.

**Comment by stobrien89** [comment]
@PabloWestphalen,

This has been implemented in #2424 and will be available in tomorrow's release.
