### ISSUE TITLE
Add support for reverse proxy

### ISSUE THREAD

**Issue by LCamel** [aws/aws-sdk-php#1562]
We would like to pass our requests through a reverse proxy, so the contents could be cached locally.

Here is our current workaround. We hope the SDK could support this feature.

```php
// SEE: Aws\Middleware::contentType() and Aws\S3\S3Client::__construct()
function withReverseProxy($s3Client, array $proxyConf)
{
    $s3Client->getHandlerList()->appendBuild(function (callable $handler) use ($proxyConf) {
        return function ($command, $request = null) use ($handler, $proxyConf) {
            $origUri = $request->getUri();
            $request2 = $request
                ->withUri($origUri->withHost($proxyConf["ProxyHost"])
                                  ->withPort($proxyConf["ProxyPort"]))
                ->withHeader("Host", $origUri->getHost());
            return $handler($command, $request2);
        };
    }, "s3.with_reverse_proxy");
}

withReverseProxy($s3Client, ["ProxyHost" => "my-proxy.acme.com", "ProxyPort" => 8080]);
```

**Comment by kstich** [comment]
Could you instead use [the `['http']['proxy']` configuration option](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#http-proxy) available on the SDK clients?

**Comment by SansWord** [comment]
This issue did annoy me, too. Please add support so we don't have to use ad-hoc solution, too.

**Comment by kstich** [comment]
Thank you for your feature request. We regularly review suggestions like these to help prioritize what features we add to the SDK. But, currently, we do not plan to add direct support for a reverse proxy to the AWS SDK for PHP.
