### ISSUE TITLE
aws mediatailor php sdk

### ISSUE THREAD

**Issue by samueleastdev** [aws/aws-sdk-php#1564]
Hi All,

I cannot find any docs for the Media Tailor Client so I take this is still in development?

Just wanted to check this will be implemented at some point or am I not understanding how it works can you access it from another service?

https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.MediaConvert.MediaConvertClient.html

Thanks

**Comment by kstich** [comment]
[It doesn't look like MediaTailor has an API to expose through the SDK.](https://aws.amazon.com/documentation/mediatailor/), you can [reach out on their forum](https://forums.aws.amazon.com/forum.jspa?forumID=270) to let them know you're hoping for it.
