### ISSUE TITLE
whatsapp api to send message in php password creation error

### ISSUE THREAD

**Issue by deepak8484** [aws/aws-sdk-php#1566]
I have downloaded whatsapp api,and i am trying to register in WART i get the ID but When i click on Request Code i get the error saying "could not request code using either sms or voice".reason:old_version.Anyone have any idea what to do? i have already checked this links below.

http://www.wahelper.com/register-whatsapp-account-tool.html 
https://github.com/mgp25/WART 
https://github.com/mgp25/Chat-API/wiki/WhatsApp-Registration-Flow 

Please any one tell me another solution to create password for api

**Comment by howardlopez** [comment]
Unfortunately that is not our product. I would suggest contacting their support channels directly or looking for other community support around the product.
