### ISSUE TITLE
Cannot redeclare Aws\constantly

### ISSUE THREAD

**Issue by aftabnaveed** [aws/aws-sdk-php#1567]
In my project, I have a local dependency on Amazon AWS SDK v3. When the SDK is being installed I get this error:

`Cannot redeclare Aws\constantly() (previously declared in /srv/laravel/vendor/aws/aws-sdk-php/src/functions.php:19)`

I even tried to wrap it inside `function_exists` but it still did not work. It seems like the extension conflicts with already installed AWS SDK hence the error.

**Comment by kstich** [comment]
It looks like you have multiple installations of the AWS SDK for PHP enabled for your project. Please ensure you only have [one installation of the SDK in your project](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/getting-started_installation.html).

**Comment by yosus** [comment]
Seems that the old aws sdk was left in the vendor folder. I removed the `vendor/aws` folder, and install it again using composer `composer require aws/aws-sdk-php`. The newly created aws folder has only 2 folders; aws-crt-php, aws-sdk-php
