### ISSUE TITLE
CloudFront Signed URL/Cookie with AWS-MKS (SignatureV4)

### ISSUE THREAD

**Issue by dbpolito** [aws/aws-sdk-php#1568]
I'm trying to use `CloudFront Signed URL/Cookie` on an S3 with `AWS-KMS` encryption but i get this error:

````xml
<Error>
    <Code>KMS.UnrecognizedClientException</Code>
    <Message>No account found for the given parameters</Message>
    <RequestId>xxx</RequestId
    <HostId>xxx</HostId>
</Error>
````

Doing a lot of research on docs and on `aws-sdk-php` it seems it is not supported on php sdk, but looks like it is on `.net` and `java`.

It seems that S3 with KMS is only supported using `SignatureV4`.

Is there a manual way of doing it or any plans to support it on PHP SDK?

**Comment by kstich** [comment]
Can you provide a code sample for what is generating this issue for you? Also, can you please point to what you're looking at regarding the .Net and Java SDKs?

**Comment by dbpolito** [comment]
````php
$cloudFront = new CloudFrontClient([
    'region'  => $this->region,
    'version' => '2016-01-28',
]);

$url = $this->httpHost . '/' . $key;

$condition = [
    'DateLessThan' => [ 'AWS:EpochTime' => time() + $expiration ],
];

$cookies = $cloudFront->getSignedCookie([
    'private_key' => $this->pem,
    'key_pair_id' => $this->cloudfrontKey,
    'policy'      => json_encode([
        'Statement' => [
            [
                'Resource' => $url . '/*',
                'Condition' => $condition,
            ],
        ],
    ], JSON_UNESCAPED_SLASHES),
]);
````

This is working just fine when i change Encryption to: `None` or `AES-256`.

**Comment by kstich** [comment]
[It looks like someone else asked this issue on the CloudFront forums](https://forums.aws.amazon.com/thread.jspa?messageID=819324&tstart=0), you should express your request for this feature in that thread.

> "This is an expected behavior as CloudFront currently does not support KMS server-side encryption for S3. The reason this does not work is that viewer requests through CloudFront does not have access to the KMS credentials used to encrypt the s3 objects. We would recommend using signed URLs and Origin Access Identities without KMS. We are aware of this limitation and a feature request is submitted to the CloudFront team."
