### ISSUE TITLE
AWS SDK throws error when creating Route53Domains client

### ISSUE THREAD

**Issue by Genert** [aws/aws-sdk-php#1573]
Upon creating Route53Domains client as following:

```php
// Create Route53 Domains Client
$route53 = Aws::createClient('Route53Domains');
```

A following error is thrown:
> Unable to parse URI: https://route53domains.`{"Ref" : "AWS::Region"}`.amazonaws.com

Why?

This only appears in production environment (AWS Beanstalk), I checked the AWS env variables, but they are identical to those in dev env (except secret key).

**Comment by kstich** [comment]
The `Aws::createClient()` method is not provided by any the AWS SDK for PHP, so I'd recommend investigating with where you're getting that from.

[That said, it looks like your client needs a `'region'` configuration provided to it](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#cfg-region).
