### ISSUE TITLE
Imcompatibility with OVH API

### ISSUE THREAD

**Issue by JeremieDemarchez** [aws/aws-sdk-php#1574]
Hello,

There is a conflict if we use OVH PHP API and AWS PHP API.

The problem occur if we "require" firstly OVH API and then AWS API. The error is the following one : 
Fatal error: Cannot redeclare GuzzleHttp\uri_template() (previously declared in /opt/SecurAlerte/SecurAlerte-CoreConfig/OvhApi/vendor/guzzlehttp/guzzle/src/functions.php:17) in /opt/SecurAlerte/SecurAlerte-CoreConfig/AwsApi/AwsSdk/GuzzleHttp/functions.php on line 31

There is no problem if we include firstly AWS API and then OVH API, because OVH API include the file only if it is not already include : 
// Don't redefine the functions if included multiple times.
if (!function_exists('GuzzleHttp\uri_template')) {
    require __DIR__ . '/functions.php';
}

This verification should be added to AWS PHP API.

Best regards.

**Comment by kstich** [comment]
It looks like there are issues with the way you're packaging your dependencies. The AWS SDK for PHP [takes Guzzle as a dependency](https://github.com/aws/aws-sdk-php/blob/master/composer.json#L20). It appears as if you have multiple copies of this dependency included. This is not an issue with the SDK.
