### ISSUE TITLE
CloudWatchOutputConfig for ssm_client / send command does not seems to work

### ISSUE THREAD

**Issue by yogui** [aws/aws-sdk-php#1575]
I'm calling sendCommand method with CloudWatchOutputConfig parameters.
I don't receive anything into CloudWatch and I can't see any reference to CloudWatchOuput into call return.
I'm using 3.62.6 version
```
              $params = array(
			'InstanceIds'            => $instances_id,
			'DocumentName'     => 'AWS-RunShellScript',
			'Parameters'             => array(
				'commands' => array($command),
			),
			'CloudWatchOutputConfig' => array(
				'CloudWatchOutputEnabled' => true,
			),
		);

		$result = $this->get_ssm_client()->sendCommand($params);
```

**Comment by kstich** [comment]
I see the parameter being passed to the service with your same configuration. If you're not receiving an exception from this API call with more details, you should [open a support ticket with AWS Support](https://console.aws.amazon.com/support/home/). You may need information that can be found [by turning on the `'debug'` setting](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#debug).
