### ISSUE TITLE
ScanFilter on map field

### ISSUE THREAD

**Issue by ninoman** [aws/aws-sdk-php#1577]
I have this structure
![image](https://user-images.githubusercontent.com/25107388/42661309-deaf2a2a-863e-11e8-8f99-423f1909b383.png)

so how can I add condition on email field?

**Comment by kstich** [comment]
Can you please provide a code sample and the version of the AWS SDK for PHP you're using?

**Comment by ninoman** [comment]
SDK version: 3.55.4
code sample: 
![image](https://user-images.githubusercontent.com/25107388/42662215-d09f38dc-8641-11e8-808f-503e532a1e23.png)

![image](https://user-images.githubusercontent.com/25107388/42662220-d7435222-8641-11e8-9f96-a15d4c797c1d.png)

**Comment by kstich** [comment]
It looks like you're having trouble configuring your DynamoDB `Scan` call. I'd recommend [taking a look at the AWS SDK for PHP `DynamoDbClient::scan` documentation](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-dynamodb-2012-08-10.html#scan) and [the DynamoDB documentation around the `'ScanFilter'` parameter](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LegacyConditionalParameters.ScanFilter.html).

If you're still having issues, I'd recommend either [asking a question on StackOverflow tagged with `aws-php-sdk`](http://stackoverflow.com/questions/tagged/aws-php-sdk), [opening a support ticket with AWS Support](https://console.aws.amazon.com/support/home/), or [reaching out on the DynamoDB forums](https://forums.aws.amazon.com/forum.jspa?forumID=131).
