### ISSUE TITLE
Potentially incorrect retry logic

### ISSUE THREAD

**Issue by jonathanbull** [aws/aws-sdk-php#1580]
The `RetryMiddleware` states that the exponential backoff has a 100ms base:

`* Exponential backoff with jitter, 100ms base, 20 sec ceiling`
https://github.com/aws/aws-sdk-php/blob/master/src/RetryMiddleware.php#L126

However it looks like the base is in fact 0ms:

`return mt_rand(0, (int) min(20000, (int) pow(2, $retries) * 100));`
https://github.com/aws/aws-sdk-php/blob/master/src/RetryMiddleware.php#L134

Didn't create a PR as I'm unsure what the intention is here - is it the comment or the logic that's incorrect?

**Comment by bscutt** [comment]
Interesting, it does look like it should be `return mt_rand(100, (int) min(20000, (int) pow(2, $retries) * 100));` in that case 🤔

**Comment by kstich** [comment]
The discrepancy here is that you're skipping over the 'with jitter' section of the documentation. [You can read about exponential backoff with full jitter here.](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/). We can add an `@link` annotation to this documentation block.

**Comment by jonathanbull** [comment]
@kstich Ah, I did see the jitter but I didn't realise that the '100ms base' was referring to just that aspect of the logic, and not the output as a whole.
