### ISSUE TITLE
WafClient returns empty data

### ISSUE THREAD

**Issue by rvelhote** [aws/aws-sdk-php#1586]
Hello,

I'm trying to use the SDK to access the WAF API and add/remove IPs from a rule however the data returned by the WafClient (for any method) is always empty. Other APIs (S3, EC2) I've tried work well.

```
require '../vendor/autoload.php';

$sdk = new Aws\Sdk([
    'version' => 'latest',
    'region'  => 'us-east-1'
]);

$client = $sdk->createWaf();
var_dump($client->listWebACLs());
```

Any tips?

Best regards,
Ricardo Velhote

**Comment by kstich** [comment]
Is it possible you should be using `createWafRegional`? [You can read about the differences here](https://docs.aws.amazon.com/waf/latest/APIReference/Welcome.html).

**Comment by rvelhote** [comment]
Yessss. That's precisely it. Thank you very much! :1st_place_medal:
