### ISSUE TITLE
Json Parsing Error on Create Job (MediaConvertClient)

### ISSUE THREAD

**Issue by bitcine-darcy** [aws/aws-sdk-php#1587]
Looks like creating a job on the MediaConvertClient is receiving an error:

File: "/releases/20180731141842/vendor/aws/aws-sdk-php/src/Api/Parser/JsonParser.php"
Message: "DateTime::__construct(): Failed to parse time string (1533052292) at position 8 (9): Unexpected character"

**Comment by kstich** [comment]
Can you please provide a code sample for the call you're making?

**Comment by bitcine-darcy** [comment]
Note some fields get populated at runtime (INPUT, DESTINATION). And I removed some sensitive information.

`$client = MediaConvertClient::factory($credentials);

$config = array(    		
	'JobTemplate' => 'arn:aws:mediaconvert:us-east-1:xxxxxxxx:jobTemplates/DASH demux DRM',
	'Queue' => 'arn:aws:mediaconvert:us-east-1:xxxxxxxx:queues/Default',
	'UserMetadata' => array(),
	'Role' => 'arn:aws:iam::xxxxxxxx:role/mediaConvert',
	'Settings' => array(
		'OutputGroups' => array(
			array(
				'Outputs' => array(
					array(
						'Preset' => 'bitcine-DASH_v1080_6000',
						'NameModifier' => '_v1080_6000'
					),
					array(
						'Preset' => 'bitcine-DASH_v720_3000',
						'NameModifier' => '_v720_3000'
					),
					array(
						'Preset' => 'bitcine-DASH_v540_2000',
						'NameModifier' => '_v540_2000'
					),
					array(
						'Preset' => 'bitcine-DASH_v360_1200',
						'NameModifier' => '_v360_1200'
					),
					array(
						'Preset' => 'bitcine-DASH_v270_400',
						'NameModifier' => '_v270_400'
					),
					array(
						'Preset' => 'bitcine-DASH_a128',
						'NameModifier' => '_a128'
					)
		        ),
				'OutputGroupSettings' => array(
					'Type' => 'DASH_ISO_GROUP_SETTINGS',
					'DashIsoGroupSettings' => array(
						'SegmentLength' => 30,
						'FragmentLength' => 2,
						'SegmentControl' => 'SINGLE_FILE',
						'HbbtvCompliance' => 'NONE',
						'Destination' => 'DESTINATION',
						'Encryption' => array(
							'SpekeKeyProvider' => array(
								'ResourceId' => '36c8c333d0944f69b2569ce6aa6656a2',
								'SystemIds' => [
									'edef8ba9-79d6-4ace-a3c8-27dcd51d21ed',
									'9a04f079-9840-4286-ab92-e65be0885f95'
								],
								'Url' => 'https://xxxxxx.execute-api.us-east-1.amazonaws.com/EzDRMStage/copyProtection'
							)
						)
					)
				)
			)
		),			
		'Inputs' => array(
			array(
				'AudioSelectors' => array(
					'Audio Selector 1' => array(
						'Tracks' => array(
							1
						),
						'DefaultSelection' => 'DEFAULT',
						'SelectorType' => 'TRACK',
					)
				),
				'FileInput' => 'INPUT'
			)
		)
	)
)	

$result = $client->createJob($jobBody);`

**Comment by howardlopez** [comment]
It looks like there was an internal issue resulting in the declared timestamp format issued by MediaConvert not matching the actual timestamp value being sent. We worked with the service team to push out a fix and have released a [new version of the SDK](https://github.com/aws/aws-sdk-php/blob/master/.changes/3.64.2), which should rectify this problem. Let us know if you have any further issues.

Thanks for bringing this to our attention!
