### ISSUE TITLE
aws-autoloader.php produce parse error on functions.php line 36 when used with php-cli

### ISSUE THREAD

**Issue by zubair72** [aws/aws-sdk-php#1588]
I have to include aws-autoloader.php in my config file during php-cli calling script for execution. when config is called by php-cli using shell_exec it logs an error saying parse error for '$value' in functions.php of sdk file

to produce this error

create config.php file as following
```
require_once("path-to-aws-sdk/aws-autoloader.php");
use Aws\Ssm\SsmClient;
```
--------------
create a cron_exe.php file as following
```
$pid = shell_exec("ps -A | grep php-cli | awk '{print $1}'");
if(empty($pid)) {
	shell_exec("php-cli /path-to-script-to-run/cron.php > /path-to-log-file/err.txt 2>&1 & echo $!");
}
```
-------------------
create a file cron.php with following content
```
require_once("path-to-config/config.php");
```
--------------------------
create a file call.php which will call cron_exe.php file
```
include("path-to-cron_exec-file/cron_exec.php");
```
--------------------------------------
place call.php in you public folder and call it from web browser and then view err.txt file to see error

Please note that in aws we can use php with shell command but on my current hosting we must use php-cli to run scripts through shell command.

**Comment by zubair72** [comment]
Hello pls find the information as required.
1- I am executing php under two enviroments i-Aws, ii, Standard shared hotsing
2- I am using shell_exec to run php command line
3- Under aws I use shell_exec and use php executable
4- Under standard hosting I use shell_exec and php-cli executable
5- I am using PHP 7.0 running on 64bit Amazon Linux/2.7.0 on aws
7- I am using php 7.0 running on linux kernel 3.10.0-693.11.6.1.ELK.el6.x86_64 under shared hosting

To answer your question if I am getting php work properly on aws environment but not on shared hosting environment, to add to this answer, I am using CLI from shell_exec and not directly from for command line. The loader also works fine from php-cli under windows environment.

I'll be glad to provide any additional required information that can help.

regards

**Comment by diehlaws** [comment]
Hey @zubair72, thanks for reaching out to us about this. Unfortunately I wasn't able to reproduce this on PHP 7.0 and the AWS SDK for PHP version 3.64.7.

Could you give us the exact error message you're seeing from your shared hosting environment? Knowing more details about the hosting provider you're using, specifically their php configuration and/or a link to the specs of the host you're using (if available), would be helpful.

**Comment by zubair72** [comment]
Hi,
I am using php version 7.025 with AWS SDK version 3.64.4

exact error message is "[16-Aug-2018 01:18:36 America/Chicago] PHP Parse error:  syntax error, unexpected '$value' (T_VARIABLE) in /home/smartap1/public_html/app062/include/aws/Aws/functions.php on line 36"

I am attaching the package error_log and err.txt under cron logs this error

pacakge is deployed to http://app062.smartapps4free.com

Let me know if you  require the phpinfo access for any further information about server, I am using a shared account with hostgator.
[html-20180816001.zip](https://github.com/aws/aws-sdk-php/files/2292646/html-20180816001.zip)

I'll be glad to provide any further information required

regards

**Comment by diehlaws** [comment]
Thanks for the additional information. I'm able to reproduce the error `Parse error: syntax error, unexpected '$value' (T_VARIABLE) in /var/www/html/html/include/aws/Aws/functions.php on line 36`, but only when using a PHP version older than 5.5. Please keep in mind that the current major version of the AWS SDK for PHP only supports PHP versions 5.5 and newer.

This sounds like a case where your hosting provider may be using an older version of PHP, either for your entire site or specific directories. I'd suggest checking the [PHP Selector plugin](https://support.hostgator.com/articles/php-configuration-plugin) in cPanel and looking for PHP versions older than 7.0 defined in your .htaccess file.

**Comment by zubair72** [comment]
I double checked the php version selected on cpanel that is version 7 and also my .htaccess file is clean for any such directive.
Is there a possibility that php-cli version remains old no matter what version we select on cpanel?

**Comment by zubair72** [comment]
Thanks its php version mismatch issue
