### ISSUE TITLE
CommandPool with commands created by clients with different credentials

### ISSUE THREAD

**Issue by poisa** [aws/aws-sdk-php#1591]
When sending to SES I currently use the CommandPool to parallelize my API calls and so far it works wonderfully because I'm always using the same SES credentials. In an upcoming refactor my email pool will contain mixed email from different clients which will need to be sent using different credentials. Is it possible to send a batch of commands generated with different clients?

For example (pseudo code):

```php
<?php
// Instead of doing:
$commands[] = $sesClient->getCommand('SendEmail', [etc]);
$commands[] = $sesClient->getCommand('SendEmail', [etc]);
$commands[] = $sesClient->getCommand('SendEmail', [etc]);
$pool = new CommandPool($client, $commands, [etc, etc]);
$pool->promise->wait()

// Can the SDK handle this?
$commands[] = $sesClient1->getCommand('SendEmail', [etc]); // $sesClient1
$commands[] = $sesClient2->getCommand('SendEmail', [etc]); // $sesClient2
$commands[] = $sesClient3->getCommand('SendEmail', [etc]); // $sesClient3
$pool = new CommandPool($client, $commands, [etc, etc]);
$pool->promise->wait()
```

In the above, each sesClient is configured with a different set of credentials and very possibly a different region.

UPDATE: After posting I realized I didn't word my pseudo-code properly. I realize the `CommandPool` requires a `$client` and in this particular case I have many clients. My question is more in terms of "is there a way to make this work?" regardless of what the actual syntax is.

**Comment by kstich** [comment]
Could you collect all the `$pool->promise()` return values and wrap them in an [`EachPromise`](https://github.com/guzzle/promises/blob/master/src/EachPromise.php)?

**Comment by poisa** [comment]
@kstich that's a good idea! I wasn't aware that Guzzle contained all those JS goodies.
