### ISSUE TITLE
RetryMiddleware: What step should it be set on?

### ISSUE THREAD

**Issue by poisa** [aws/aws-sdk-php#1592]
I'm trying to use the RetryMiddleware but the [middleware docs](http://docs.amazonaws.cn/aws-sdk-php/v3/guide/guide/handlers-and-middleware.html) don't mention what "step" it should be configured on (actually, there is no example for this middleware on the docs).

Attaching it to either the `init` and `validate` steps throws an exception but on the `build` or `sign` it seems to work. Is there any harm on using either of these for this particular middleware? My gut tells me that `build` is the right place to put this in but I don't know...

**Comment by howardlopez** [comment]
You can take a look at the [ClientResolver](https://github.com/aws/aws-sdk-php/blob/14a8d1499450a755d6c1f147ea76eabdc1666a9d/src/ClientResolver.php) class, which [adds the default RetryMiddleware implementation](https://github.com/aws/aws-sdk-php/blob/14a8d1499450a755d6c1f147ea76eabdc1666a9d/src/ClientResolver.php#L374).

If you're simply looking to change the max number of retries, you can [set this in the client constructor](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#config-retries).

**Comment by poisa** [comment]
@howardlopez Thanks for the links. According to the ClientResolver class the retry middleware is added in the `sign` step. I wasn't aware of how the default clients were created.

(I'm still amazed at how well put together this SDK is!)
