### ISSUE TITLE
how to remove the [AWS] suffix?

### ISSUE THREAD

**Issue by mirror222** [aws/aws-sdk-php#1593]
Each SMS has an [AWS] suffix, is it possible to remove it?

**helllo world! [AWS]**

**Comment by howardlopez** [comment]
Can you provide a complete code sample of what you're trying?

**Comment by mirror222** [comment]
sorry the delayed response. here are the codes:

`<?php
require './vendor/autoload.php';
error_reporting(E_ALL);
ini_set("display_errors", 1);

$params = array(
    'credentials' => array(
        'key' => 'XXXXXX',
        'secret' => 'R/XXXXXXXX/Qc+XXXXXXXXXX',
    ),
    'region' => 'us-east-1', // < your aws from SNS Topic region
    'version' => 'latest',
    'debug'     => false,
);
$sns = new \Aws\Sns\SnsClient($params);

$args = array(
    "MessageAttributes" => [
                'AWS.SNS.SMS.SenderID' => [
                    'DataType' => 'String',
                    'StringValue' => 'EOS'
                ],
                'AWS.SNS.SMS.SMSType' => [
                    'DataType' => 'String',
                    'StringValue' => 'Transactional'
                ]
            ],
    "Message" => "[xxxxx] 您的验证码是：987651，10分钟内有效。请妥善保护好验证码，防止泄露。",  
    "PhoneNumber" => "+86xxxxxxxxxxxx"
);

$result = $sns->publish($args);
var_dump($result);`
