### ISSUE TITLE
DescribeDBClusters API supports pagination but this SDK doesn't

### ISSUE THREAD

**Issue by bangpound** [aws/aws-sdk-php#1596]
For RDS, the DescribeDBClusters command [supports pagination](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBClusters.html) but this SDK does not define it.

I can construct a ResultPaginator object manually like this:

```php
$client = new \Aws\Rds\RdsClient();
$paginator = new \Aws\ResultPaginator($client, 'DescribeDBClusters', [], [
    'input_token' => 'Marker',
    'limit_key' => 'MaxRecords',
    'output_token' => 'Marker',
    'result_key' => 'DBClusters',
    'more_results' => null,
]);
```

Can this be added to the SDK?

**Comment by kstich** [comment]
Thanks for your request, [this was added in Version 3.65.1](https://github.com/aws/aws-sdk-php/releases/tag/3.65.1).
