### ISSUE TITLE
S3 createPresignedURl does not create bucketstylelistener for custom request object

### ISSUE THREAD

**Issue by simkimsia** [aws/aws-sdk-php#160]
When using custom request object to create presigned url, the following url is not returned

`bucket.s3.amazonaws.com` is not returned.

This works for command object though.

See https://github.com/aws/aws-sdk-php/issues/94#issuecomment-25675081 for more details.

Note to self:
update this stackoverflow answer once this issue is resolved.
http://stackoverflow.com/questions/19173224/generate-pre-signed-object-url-using-aws-sdk-for-php-2/19173225#19173225

**Comment by EricP** [comment]
Half the links on this page are broken. I find the location for certain versions and their corresponding docs confounding...
