### ISSUE TITLE
AWS SQS error : SignatureDoesNotMatch HTTP error: 403

### ISSUE THREAD

**Issue by pranavansp** [aws/aws-sdk-php#1612]
I'm working on a face tracking thought video AWS Rekognition (`StartFaceSearch`). It will return the job id. I have setup everything `SQS ``SNS `parts. Here my problem is I can't able to get a message from `SQS `using `receiveMessage()`. Even `listQueues()` also not working. It gives this below error.

> 
> "ListQueues" on "https://sqs.us-east-1.amazonaws.com"; AWS HTTP error: Client error: POST https://sqs.us-east-1.amazonaws.com resulted in a 403 Forbidden response: < ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">Sender< Code >S (truncated...) SignatureDoesNotMatch (client): The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
> 
> The Canonical String for this request should have been 'POST / ....... < continue.............

The code as follow. AWS PHP SDK ver 3.64.11. Laravel 3.0

```
$queueUrl = "https://sqs.us-east-1.amazonaws.com/xxxxxxx/facetrackingreceive";
        // Get the client from the builder by namespace
        $sqs_client = new SqsClient(array(
            'credentials' => array(
                'key'    => 'xxxxxxxxxx',
                'secret' => 'xxxxxxxxxxxxxxxxxxxxxxx',
            ),
            'version' => '2012-11-05',
            'region'  => 'us-east-1',
            'http' => [ 'verify' => false ],

        ));

        $result = $sqs_client->listQueues();

        foreach ($result->get('QueueUrls') as $queueUrl) {
            echo "$queueUrl\n";
        }
```

**Comment by diehlaws** [comment]
Hey @pranavansp, thanks for reaching out about this. This error typically comes up as a result of a typo in your credentials so I suggest double checking your `key` and `secret` values to make sure there aren't any spaces or other unexpected characters at the beginning or end of these. If you've double-checked that these values are correct, please enable [wire logging](https://aws.amazon.com/blogs/developer/wire-logging-in-the-aws-sdk-for-php/) and provide the output for our review.

**Comment by pranavansp** [comment]
Hi, @diehlaws Thanks for your replay. I have already double checked with credentials values with same error but I have **solved the problem** by regenerating access key. There is something issue on it. my suggestion to investigate that. I found that idea from this [issue](https://github.com/albogdano/elasticsearch-river-amazonsqs/issues/7). 

After regenerating keys. SQS works fine with all methods. Thanks (Y)

**Comment by pranavansp** [comment]
@kstich @diehlaws its want to close but may i know your response for this issue?

**Comment by diehlaws** [comment]
@pranavansp Thanks for getting back to us, and I'm glad you were able to solve the issue. Please keep in mind that issues in this repository address problematic behaviors specific to the AWS SDK for PHP, not issues relating to the services themselves.

The issue you linked suggests this behavior is caused by special characters being present in the secret key, however I've tested your code with several IAM users' credential sets that contain non-alphanumeric characters ( `/` and `+`) in the secret key and was unable to elicit a SignatureDoesNotMatch exception from SQS. Since I'm not able to reproduce this behavior from my end, I cannot determine the conditions under which it can occur. I suggest reaching out to our Premium Support team by [opening a support case](https://console.aws.amazon.com/support/v1?#/case/create) under the SQS service since they will have a better idea of what to look for when reproducing a service issue like this.

**Comment by jkdilunika** [comment]
@diehlaws  This is 2020 and still reproducible. I reproduced this using Java SDK and Node SDK (SQS). My initial secret key had '/'. If AWS has no plan to fix this issue in their core, the best solution is not to generate secret keys with '/'. It will save lots of developer's time.

**Comment by buvinghausen** [comment]
@jkdilunika you mean the same developers who can't be bothered to put the queue name in the QueueDoesNotExistException

LOL

**Comment by recoverjp** [comment]
For me the problem continues.
Even with a key without + or /

**Comment by giriakshay** [comment]
I am facing same issue. I have a Lambda function which perform some operations and put response in SQS. I have assigned execution role to Lambda with Full Access to SQS but still getting SignatureDoesNotMatch. SQS and Lambda are in same environment. Can anybody help please?

**Comment by mad-ambi** [comment]
Hi @diehlaws @kstich  This is still happening - went on a wild goose chase for 2 weeks and we still face the issue. Funny thing is i couldn't replicate this on my mac, but on my customers laptop they couldn't push the message to my SQS queue. Kindly look into this
