### ISSUE TITLE
php7 Compatibility problem v3.24.4

### ISSUE THREAD

**Issue by oasfuyou** [aws/aws-sdk-php#1613]
.Function each() is deprecated since PHP 7.2; Use a foreach loop instead

**Comment by kstich** [comment]
Version 3.24.4 of the SDK was released before PHP 7.2 was available. The last pull request to remove `each()` calls (#1419) was included in release [3.36.36](https://github.com/aws/aws-sdk-php/releases/tag/3.36.36). Please upgrade to that version to clean up these deprecation warnings.
