### ISSUE TITLE
Support for S3 Select

### ISSUE THREAD

**Issue by rayzor65** [aws/aws-sdk-php#1615]
Hi I am wondering if there are any plans to add S3 Select to the PHP SDK similarly to python SDK? https://docs.aws.amazon.com/AmazonS3/latest/dev/SelectObjectContentUsingOtherSDKs.html

**Comment by diehlaws** [comment]
Thanks for reaching out to us about this @rayzor65. This seems like a reasonable feature request so I have labeled the issue as such. We will keep the thread updated as more information is made available for this feature.

**Comment by diehlaws** [comment]
Thanks for your patience on this @rayzor65. We are actively working on implementing this feature, unfortunately I cannot provide an ETA for its release but it will be available soon.
