### ISSUE TITLE
Sdk is generating a 403 error on sqs resource using iam roles.

### ISSUE THREAD

**Issue by edersonbadeca** [aws/aws-sdk-php#1620]
Often , the application does not reach the resource when iam role is used, but when I have pass  an  env credentials it works fine.

Resource configuration:

Allow | Everybody (*) | All SQS Actions (SQS:*) | ArnLikeaws:SourceArn: "arn:aws:sns:us-east-1:<account-id>:*"

The source of consumer:
```php
$result = $this->client->receiveMessage([
    'QueueUrl' => $this->queueUrl,
     'MaxNumberOfMessages' => $maxMessages //Limited to 10 by request
        ]);
```

Aws config:
```php
return [
  'version' => 'latest',
  'region'  => 'us-east-1',
];
```
Is there  something that I`m missing?

**Comment by howardlopez** [comment]
Can you provide your code for assuming the IAM role, as well as any error message you're receiving when it fails to reach the resource?

**Comment by edersonbadeca** [comment]
I don't provide any of credentials configuration but the arnRole in the ecs task-definition which is already attached SqsFullAccess Policy.

The source that initializes the client is:
```php
$this->client = $sqsClient ?: SqsClient::factory(\Config::get('aws'));
```
 The `Config::get('aws')` have this values:
```php
return [
  'version' => 'latest',
  'region'  => 'us-east-1',
];
```
The full response is:
```
04 Sep 2018 21:11:00.615[7373]: ip-<company>/master-<company-tag> [2018-09-04 21:11:00]
production.ERROR: exception 'Aws\Sqs\Exception\SqsException' with message 
'Error executing "ReceiveMessage" on "https://sqs.us-east-1.amazonaws.com/<queue-URL>"; 
AWS HTTP error: Client error: `POST https://<queue-URL>` resulted in a `403 Forbidden` 
response:
```

**Comment by edersonbadeca** [comment]
Note: This scenario happens sometimes, in the most cases the resource is well consumed.

Another usefull informations:
Policy used: *arn:aws:iam::aws:policy/AmazonSQSFullAccess*
```js
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "sqs:*"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}
```

**Comment by diehlaws** [comment]
Since the behavior you're describing does not happen consistently, this does not sound like a bug in the AWS SDK for PHP but rather unexpected behavior with the ECS task role. It is very possible that the ECS Container Agent is failing to talk to the ECS Task Metadata endpoint when you're seeing these 403's. 

For further guidance with this, I suggest reaching out to our Premium Support team by [opening a support case](https://console.aws.amazon.com/support/v1?#/case/create) under the `Container Service (ECS)` service, or posting in the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=187).

**Comment by edersonbadeca** [comment]
@diehlaws I will open a case for that. I thought that could be a behavior from sdk because I used the same strategy with python-sdk, in the same ec2 cluster and the same policy and it works good. 

Thank you for your time and I will let you in touch.
