### ISSUE TITLE
CloudSearchDomainException when search with 0 (q=0)

### ISSUE THREAD

**Issue by tranthienbinh1989** [aws/aws-sdk-php#1625]
I receive this error when try to search '0' as a query string.
here is the message:
"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."

**Comment by diehlaws** [comment]
Thanks for reaching out to us about this @tranthienbinh1989. The error message you're receiving sounds like the API keys you're using are either invalid (typo) or missing (deleted from IAM). Can you double check that the AWS SDK for PHP is receiving the correct credentials from the [credential provider](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials.html)? 

If you can confirm the API key you're using with the AWS SDK for PHP should work for this call, can you please provide a code sample for us to reproduce this behavior?

**Comment by tranthienbinh1989** [comment]
@diehlaws Thank for your response. I'm pretty sure that my credentials are correct. Because it works with another query string example: q=1, q="0" but q=0 throw an exception.

**Comment by diehlaws** [comment]
Thanks for the clarification, that definitely doesn't sound like an issue with your credentials if other queries work as expected. Unfortunately I'm not able to reproduce this behavior on my end using the code attached below with PHP v7.2.8 and the AWS SDK for PHP v3.67.5. 

```php
  $client = CloudSearchDomainClient::factory(array(
      'endpoint' => 'http://search-test-gbhs3sykvj2ajcnajyf2tdwcky.us-west-2.cloudsearch.amazonaws.com',
      'version' => '2013-01-01',
      'credentials' => new Credentials($key, $secret),
      'debug' => true
  ));

  $result = $client->search([
  'query' => '0',
  ]);

  echo $result;
  ```
  
I tested `0`, `'0'`, `'"0"'`, `'q=0'`, and `q="0"` for the `query` value, all of which returned a successful (albeit empty) response. If this approach is not similar to the manner in which you are executing your search queries, can you please provide a code sample so we can get a better idea of how you're using the AWS SDK for PHP to interact with your CloudSearch domain?

**Comment by tranthienbinh1989** [comment]
@diehlaws We are running PHP v7.2.9 and AWS SDK for PHP v2.7.27
I think we can fix this issue by updating aws sdk but we won't do it at this moment. I go ahead to close this ticket. Thank you for your support.
