### ISSUE TITLE
SNS: Verifying the Signatures of Amazon SNS Messages in .net

### ISSUE THREAD

**Issue by talk2alie** [aws/aws-sdk-php#1626]
Good day folks,

I do not see any means to verify messages that SNS Topics send to a subscribed HTTP endpoint. I see a sample Java servlet here, https://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.example.java.html, but none for .Net. Is this supported in .net?

Thanks.

**Comment by diehlaws** [comment]
Hi @talk2alie, it looks like you may have posted this in the wrong repository - I'm not seeing anything related to PHP in your question. You can open a new issue under the repository for the AWS SDK for .NET [here](https://github.com/aws/aws-sdk-net/issues/new).
