### ISSUE TITLE
How to validate the i.e Facebook (secretAccessKey, accessKeyId, sessionToken)

### ISSUE THREAD

**Issue by engharb** [aws/aws-sdk-php#1631]
Hi,

the user can log in using his FaceBook account from his mobile and using Amplify API I used to get (secretAccessKey, accessKeyId, sessionToken). I want to validate and verify these credential keys in my backend server using PHP-SDK. Is that possible?

Thanks,

**Comment by jschwarzwalder** [comment]
It is possible.

There are instructions in the developer guide about varifying credentials.

I think this article will be the most helpful:
https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_temporary.html

**Comment by engharb** [comment]
@jschwarzwalder 
I did not find a solution how to verify the credentials and I do not want to do that using S3Client class.

**Comment by jschwarzwalder** [comment]
In any credentials example you can change the client and it should work the same.

You need to use an Identity Access Management Role to give users permission to access or use any AWS resources.

This article from IAM might be more helpful: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_enable-console-custom-url.html

**Comment by engharb** [comment]
@jschwarzwalder thanks a lot, I really have tried it does not work as I want.

**Comment by jschwarzwalder** [comment]
Thank you for your patience. I am reaching out to someone who knows how to use IAM policies better, and I will see if they have any further guidance for you.

**Comment by engharb** [comment]
Hello @jschwarzwalder,

as I explained before I used to login to Federated Identity pool using my FB account and I need a way to validate the Keys in my Php-backend server (kind of PHP SDK which only verifies the keys I do not want to touch any AWS services). Currently Iam using AWS-SDK-PHP but I did not find a method that has the same functionality as I expect.

Regards,

**Comment by diehlaws** [comment]
Thanks for the clarification @engharb. The AWS SDK for PHP does not have a way to check a set of AWS credentials without issuing a request to an AWS service. 

The easiest way to verify a set of AWS credentials is to grant permission to the IAM entity associated with these credentials to issue a request that does not return sensitive information about your account (EC2 [`DescribeRegions`](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-ec2-2016-11-15.html#describeregions) is a good example), then have your PHP backend server issue the API request you've chosen for credential verification and look for the error returned by the service when it receives invalid credentials (e.g. HTTP 401 `AuthFailure` response for EC2).

**Comment by engharb** [comment]
Thanks a lot, I will try it soon.
