### ISSUE TITLE
Less tagged releases

### ISSUE THREAD

**Issue by ruudk** [aws/aws-sdk-php#1633]
While I am all in for lots of releases, I feel like a release every 2 days is a bit much. We use @dependabot to automatically create PR's when packages change, and this is what happened:

<img width="938" alt="screenshot 2018-09-21 at 08 26 20" src="https://user-images.githubusercontent.com/104180/45863849-36ec9680-bd78-11e8-9942-f45174d89191.png">

Maybe I should see if @dependabot has a way of reducing updates for given packages?

**Comment by greysteil** [comment]
👋 Maintainer of Dependabot here.

We should be able to add something in Dependabot that makes this customisable. It'll take a couple of weeks, as I want to ship new dashboards first (so the feature has somewhere to live) but we'll get there.

**Comment by howardlopez** [comment]
Most of our SDK releases support new features being released by services, which as you can imagine come out quite frequently. Hopefully the upcoming updates by @greysteil will help reduce the PR noise on your end.
