### ISSUE TITLE
Strange behaviour when removing multiple faces from Rekognition Collection

### ISSUE THREAD

**Issue by zoomphoto** [aws/aws-sdk-php#1637]
I am trying to remove multiple faces from a collection (the blurry ones) in a single command, otherwise I get throttled.

The strange part is when I send the command with a hardcoded string, it works perfectly.

```
$result = $rek->deleteFaces([
'CollectionId' => "{$workingEvent}", 
'FaceIds' => [ 'f4a4001e-0881-4d60-a143-44f5898307f6','133391cf-d837-43cc-9acb-5e81925add38','20769223-6be2-4274-a92c-bfd06f74edd1','8af7e6bc-aec2-4e40-abbe-4dd8dc83f861','ba1b1524-88ec-4d69-8a75-43689f78a305' ],
]);
```

Code with Variable:

```
$cleanFaces = "'f4a4001e-0881-4d60-a143-44f5898307f6','133391cf-d837-43cc-9acb-5e81925add38','20769223-6be2-4274-a92c-bfd06f74edd1','8af7e6bc-aec2-4e40-abbe-4dd8dc83f861','ba1b1524-88ec-4d69-8a75-43689f78a305'";         

$result = $rek->deleteFaces([
'CollectionId' => "{$workingEvent}", 
'FaceIds' => [ $cleanFaces ],
]);
```

When I try the exact same code, but using a variable, it does not work, giving me this error:

`1 validation error detected: Value '['f4a4001e-0881-4d60-a143-44f5898307f6','133391cf-d837-43cc-9acb-5e81925add38','20769223-6be2-4274-a92c-bfd06f74edd1','8af7e6bc-aec2-4e40-abbe-4dd8dc83f861','ba1b1524-88ec-4d69-8a75-43689f78a305']' at 'faceIds' failed to satisfy constraint: Member must satisfy constraint: [Member must satisfy regular expression pattern: [0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}]`

If I echo the variable and hardcode it back in, it works.. I've tried everything I can think of... I've force the variable to a string, I've tried parsing an array... I've searched google... maybe this is a bug, maybe I'm missing something very simple?

**Comment by diehlaws** [comment]
Thanks for reaching out to us @zoomphoto. While I'm able to reproduce the error you're encountering, it seems like this behavior is caused by the manner in which you're specifying the `FaceIds` value. The `$cleanFaces` variable is being initialized as a string, then added as the sole element to the array corresponding to the value for `FaceIds`. This results in the service treating the full list of Face IDs as a single ID, which fails validation for the regular expression specified in the error message.

Instead of passing the list of Face IDs as a single string in the array, you could initialize `$cleanFaces` as an array with each of the Face IDs as an element in the array and then specify the variable as the `FaceIds` value as shown below.

```php
$cleanFaces = [
'f4a4001e-0881-4d60-a143-44f5898307f6',
'133391cf-d837-43cc-9acb-5e81925add38',
'20769223-6be2-4274-a92c-bfd06f74edd1',
'8af7e6bc-aec2-4e40-abbe-4dd8dc83f861',
'ba1b1524-88ec-4d69-8a75-43689f78a305' 
];

$result = $rek->deleteFaces([
'CollectionId' => "{$workingEvent}", 
'FaceIds' => $cleanFaces,
]);
```

**Comment by zoomphoto** [comment]
Thanks, I'll test.  The documentation is a little vague.. so for example:

https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-rekognition-2016-06-27.html#deletefaces

It shows that I can send:

`$result = $client->deleteFaces([
    'CollectionId' => '<string>', // REQUIRED
    'FaceIds' => ['<string>', ...], // REQUIRED
]);`

Which shows as a string, and when I echo the string the variable, and just paste it in, it works. 

I'll try out your method and let you know how it works... so many little nit-picky things to learn!

Thanks,

**Comment by zoomphoto** [comment]
I was able to get this to work, sending the payload as an array.... but you have to remove the square braces to make it work.

So using mySQL to populate an array:

```
while mysql{
 $variable[] = $mysql['response'];
}
```

The once I have that array, I can just pass the array as the payload:

```
		$rek->deleteFaces([
		    'CollectionId' => "{$workingEvent}", 
		    'FaceIds' => $faceIdString,
		]);
```
That worked!
