### ISSUE TITLE
API errors when an empty structure option is passed

### ISSUE THREAD

**Issue by downsider** [aws/aws-sdk-php#1638]
I think I have found a bug in the way that the API serializer works.

I was using `\Aws\Batch\BatchClient` to submit a job. In the options array, I passed through an empty array for the key `containerOverrides`. When running the script, I get an error returned from the API endpoint:

```
In RequestException.php line 113:
                                                                                                                     
  Client error: `POST https://batch.eu-west-1.amazonaws.com/v1/submitjob` resulted in a `400 Bad Request` response:  
  {"message":"An error occurred during JSON parsing","__type":"ClientException"} 
```

After a bit of digging, I found that the JSON payload being sent in the request was this:

```json
{
  "jobDefinition": "## REDACTED ##",
  "jobName": "BatchRunnerTask",
  "jobQueue": "## REDACTED ##",
  "containerOverrides": [],
  "parameters": {}
}
```
I noted that the `parameters` key is using curly braces, whereas `containerOverrides` is using square brackets and I think this is the cause of the bug. The class `Aws\Api\Serializer\JsonBody` is meant to replace square brackets with curly braces ([line 46](https://github.com/aws/aws-sdk-php/blob/master/src/Api/Serializer/JsonBody.php#L46)), but for some reason does not if the option being processed is of type `structure`.

If I remove `containerOverrides` from the request options completely, or put a valid key/value pair inside it (`vcpus` or `command`, for example) then the request works. If I then add another empty `structure` option, such as `retryStrategy`, the request fails again (and subsequently works, if I add the `attempts` key to `retryStrategy`)

Is this desired behaviour or is there a bug in the way structure options are serialised?

**Comment by howardlopez** [comment]
@downsider Thank you for your PR. Code looks good and it's now been merged.

**Comment by downsider** [comment]
Thanks Howard. Appreciated :)
