### ISSUE TITLE
S3Client doesn't retry for Aws\Common\Exception\TransferException

### ISSUE THREAD

**Issue by lox** [aws/aws-sdk-php#164]
I'm possibly overlooking something, but we are seeing random errors along the lines of:

```
Aws\Common\Exception\TransferException
[curl] 18: transfer closed with 80690 bytes remaining to read [url] https://xxxx.s3.amazonaws.com/xxxx/0/xxxxxx.pdf
```

From my reading of the default BACKOFF configuration for the S3 client it seems like this error isn't retried, is there a reason for this?

**Comment by matisoffn** [comment]
Just ran into this error.  Still no solution?  I haven't changed anything and all of the sudden I'm getting this exception thrown.

**Comment by jeremeamia** [comment]
What version of the SDK are you using?

**Comment by matisoffn** [comment]
@jeremeamia I'm using aws/aws-sdk-php-laravel.  I believe it uses the aws-sdk-php repo as well.  It's aws/aws-sdk-php-laravel v1.1.2

**Comment by jeremeamia** [comment]
The exact SDK version can be found by echoing `\Aws\Common\Aws::VERSION`.

You might consider doing a composer update if you haven't in a while, in case there have been fixes for this problem in Guzzle of the SDK.

But let's also determine if this is a problem. What operation are you performing? What does the exception message you are getting tell you? How often does it happen?

You could also gather the cURL verbose output of a failed request, which could give us more information about what might be happening. To set that up, you could do something like this:

```php
// Assumes you are using the Laravel service provider as mentioned by @matisoffn
$client = Aws::get('s3', [
    'curl.options' => [CURLOPT_VERBOSE => true],
]);
```

**Comment by matisoffn** [comment]
Prior to commenting on the issue I ran a `composer self-update` and a `composer update` and the problem persisted.

I've echoed out `\Aws\Common\Aws::VERSION` and it output `2.8.1`.  I'll try getting the cURL output and post back here.

**Comment by matisoffn** [comment]
I added the array as a second parameter to my `AWS::get('s3');` line.  It's `AWS::get('s3')` for me, not `Aws::get('s3')`

**Comment by jeremeamia** [comment]
You're right, it is `AWS`. However, you still haven't told me anything about the error (e.g., what is the message) or provided the cURL verbose output. Are you having trouble getting this information?

Also, does the error happen every time? What code are you actually running?

**Comment by matisoffn** [comment]
The snippet of code that's throwing the error can be seen below.

One error: [curl] 60: [url] https://my-bucket.s3-us-west-2.amazonaws.com/{dynamic_id_here}.png

There's also this: ` Aws\Common\Exception\TransferException
…/­vendor/­aws/­aws-sdk-php/­src/­Aws/­Common/­Client/­AbstractClient.php258`

```php
$s3 = AWS::get('s3', [
	'curl.options' => [CURLOPT_VERBOSE => true]
]);

$s3->putObject(array(
	'Bucket' 	=> 'my-bucket',
	'Key'		=> $id . '.png',
	'Body'	    => fopen('avs/' . $id . '.png', 'r')
));```

**Comment by jeremeamia** [comment]
Could you catch the exception, so we can get more information about it?

```php
try {
    $s3->putObject(...);
} catch (\Exception $e) {
    echo $e->getMessage(); // <-- what does this echo?
}
```

**Comment by matisoffn** [comment]
@jeremeamia did that and got the `[curl] 60: [url] https://my-bucket.s3-us-west-2.amazonaws.com/{dynamic_id_here}.png` back from it.

**Comment by jeremeamia** [comment]
Does just `echo $e;` give you any more info?

Well, curl error 60 means: "CURLE_SSL_CACERT (60) Peer certificate cannot be authenticated with known CA certificates". That would make sense why it is happening every time and not retrying. Where are you running this code? Does your bucket name have a "." in it?, and have you specified a region in your config? Also, check out the `ssl.certificate_authority` setting in our [SDK user guide](http://docs.aws.amazon.com/aws-sdk-php/v2/guide/configuration.html#client-configuration-options).

**Comment by matisoffn** [comment]
The code was being run in a production application.  Bucket name does not have a "." in it, but it does have a hyphen "-" in it.

I've specified the correct region.  Any idea why I'm still having this error?

**Comment by mtdowling** [comment]
@matisoffn Can you provide verbose curl output of the failure?

```php
$s3->getConfig()->set('curl.options' => [CURLOPT_VERBOSE => true]);
```

**Comment by mtdowling** [comment]
@matisoffn Any update here?

**Comment by matisoffn** [comment]
Same problem, just abandoned trying to fix it.
