### ISSUE TITLE
Sockets and PCNTL extensions break BC

### ISSUE THREAD

**Issue by joshuaadickerson** [aws/aws-sdk-php#1648]
First, adding a required extension is considered a backwards incompatible change. This should have bumped the major version but you did it on a minor version.

Second, why did you do this? You could've added this as a suggestion and allowed us to add it if we want. You should check if the extensions are enabled and use them if they are. If not, use the older methods.

**Comment by howardlopez** [comment]
`ext-pcntl` and `ext-sockets` were added to [`require-dev`](https://getcomposer.org/doc/04-schema.md#require-dev), and are thus only needed if you're going to be developing for the SDK itself. The standard Composer workflow is to create a `composer.json` file for your own project and then declare dependencies therein. For example:

```
{
    "require": {
        "aws/aws-sdk-php": "3.*"
    }
}
```

Packages declared as dependencies will only add the packages declared in their own `require` property, and ignore `require-dev`. The above composer file will work in an environment without `ext-pcntl` or `ext-sockets` when running a `composer install`. 

Let us know if you have a use case that can't be resolved with the above.

**Comment by joshuaadickerson** [comment]
In a development environment where this package is used, all of the require-dev packages are required from the dependencies. Thus the aws-sdk-php package breaks my development environment because I don't have sockets and pcntl extensions.

This is a BC break. How can it not be? You use dev requirements to run tests. This makes it so you can't even composer install.

A lot of people disable or don't install those extensions for security purposes. Why not just check if they exist and use them if they do? Seems like a much safer way of doing it.

**Comment by howardlopez** [comment]
Is there any reason you're not just declaring the SDK as a dependency in your project's composer file? The `require-dev` packages only apply to the root project, [as outlined by the Composer docs](https://getcomposer.org/doc/04-schema.md#require-dev), so if the SDK is listed as a project dependency, the `require-dev` packages won't be considered. This happens regardless of what environment you're in. `composer install` shouldn't be run on the SDK directory itself unless you're planning to do development work on the SDK itself.
