### ISSUE TITLE
What is the correct way to handle errors with try...catch?

### ISSUE THREAD

**Issue by shangdev** [aws/aws-sdk-php#1652]
This is my code, Based on wordpress:
```
/**
 * List distributions.
 *
 * @return array|\WP_Error
 */
public function listDistributions()
{
    try {
        $result = $this->client->listDistributions();
    } catch (\Aws\Exception\AwsException $e) {
        return new \WP_Error($e->getAwsErrorCode(), $e->getAwsErrorMessage(), ['status' => $e->getStatusCode()]);
    }

    return $result->toArray();
}
```

If an error occurs, I need to get the error code (403,401,404...)  and the error message.

In the example I used getAwsErrorCode and getAwsErrorCode.

Is this the right way?

**Comment by diehlaws** [comment]
Hi @shangdev, thanks for reaching out to us. The way in which you are separating the error code, message, and HTTP status code in your `new WPError()` call is correct. If you were to, for example, run this with working credentials that do not have the correct permissions to list the CloudFront distributions on your account, the first argument to `new WPError()` would be "AccessDenied", the second would be "User: arn:aws:iam::ACCOUNT-ID:user/USERNAME is not authorized to perform: cloudfront:ListDistributions" and the third would be "403" as you are expecting.

**Comment by shangdev** [comment]
👌，Thanks.
