### ISSUE TITLE
How Using IAM roles for Amazon EC2 instances ?

### ISSUE THREAD

**Issue by shangdev** [aws/aws-sdk-php#1653]
It return some message:
![image](https://user-images.githubusercontent.com/15621520/47306260-81ef1780-d65e-11e8-876d-89d4ad2aa0de.png)

And this is my code:
```
$args = [
    'version' => 'latest',
    'region'  => 'us-east-1',
 ];

$client = new CloudFrontClient($args);

try {
    $result = $client->listDistributions();
} catch (AwsException $e) {
    return new \WP_Error($e->getAwsErrorCode(), $e->getAwsErrorMessage(), ['status' => $e->getStatusCode()]);
}

return $result->toArray();
```

Obviously, I used IAM credentials.

Now, what should I do? Please help me!

@cjyclaire

**Comment by diehlaws** [comment]
Hi @shangdev, thanks for reaching out to us. Looking at the provided screenshot it appears your code is being executed with the IAM Role `AdWords` as expected, however that role does not have the correct IAM permissions to issue the `ListDistributions` API call. You'll want to review the IAM policies attached to this role to ensure it is allowed to perform this action.
