### ISSUE TITLE
Cannot redeclare Aws\manifest()

### ISSUE THREAD

**Issue by tbarry-eminence** [aws/aws-sdk-php#1655]
## Issue Overview
`Cannot redeclare Aws\manifest() (previously declared in /vendor/aws/aws-sdk-php/src/functions.php:341)`

## Expected Behavior
`src/functions.php` included once.

## Current Behavior
`src/functions.php` included twice.

This is possibly related to the fact that the composer.json file defines an autoload for both the `Aws` classmap at `src/` and the files at `src/functions.php`.

```json
"autoload": {
    "psr-4": {
        "Aws\\": "src/"
    },
    "files": ["src/functions.php"]
}
```

## Possible Solution
I'm not entirely certain if composer will autoload namespaced functions if they are in the namespaced directory, but perhaps this would resolve it? (I really only have a fundamental understanding of composer package management).

Alternatively, functions inside of `src/functions.php` could be wrapped in a `function_exists()` if check eg.

```php
if (!function_exists('manifest'))
{
    function manifest($service = null)
    {
       //  ...
    }
}
```

## Steps to Reproduce
1. `composer require aws/aws-sdk-php`
2. `require_once 'vendor/autoload.php';`

## Context (Environment)
OS: Ubuntu 16.04
PHP: 7.1.22-1
Composer: 1.7.2

## Detailed Description
I've seen a couple variants of this posted either as issues here or on stackoverflow, but most seem to be caused be including composers `vendor/autoload.php` multiple times. I've been quite thorough within my companies web project to confirm that this is not the case here. I am certain we are *only including composers vendor/autoload.php once*.

I've attempted to recreate this issue as it's own project, but admit that it does seem to work fine outside of my companies environment. Unfortunately I cannot share my business code, and while I fully admit this then has to be an issue on my end I am at a loss for how to resolve it without altering the `aws/aws-sdk-php` package.

I do not believe this to be a big request, but it would certainly resolve my issue of implementing the AWS PHP SDK into my companies application.

Thanks,

Tony B.

**Comment by howardlopez** [comment]
First of all, thank you for your well-structured issue report. 

A couple of things to try:
- Delete your `composer.lock` file and your `vendor` directory, and then run `composer update` again. This will basically reinstall all your dependencies from scratch and could help clear up any funkiness in your composer install.
- Make sure that the SDK (or individual components) are not installed anywhere else in your company's codebase. If there are multiple Composer installations that both bring in the SDK, for instance, it could cause this. This could also be happening if SDK components are brought in from a source directory, in addition to the Composer `vendor` directory.

**Comment by tbarry-eminence** [comment]
I gave your first suggestion of deleting the `composer.lock` and `vendor` directories, then running `composer update`, but unfortunately it fails in exactly the same manner.

I've done a search against my entire project (dependencies included) for the `aws/aws-sdk-php` line in my composer.json, and only turned up one result. To be completely certain, I then ran an equivalent search for the `function manifest` declaration only to come up with one result.

The only thing that has resolved my issue has been the pull request which wraps all function declarations in a valid `if (!function_exists())` check.

**Comment by howardlopez** [comment]
I haven't been able to reproduce your issue - if I had, the SDK would be broken for all our customers. As a basic test, you can try creating a new directory in your environment and running:
```
composer require aws/aws-sdk-php
```
Then create a new PHP file with your require:
```
require_once 'vendor/autoload.php';
```
If this works in your environment, then you know that something about your project is creating the conflict. 

At this point you can try testing with your full project's `composer.json` file in this directory and see if that works. If it does, then you know the issue is related to other code or imports in your project. 

If it doesn't, could you post your project's `composer.json` file?

**Comment by tbarry-eminence** [comment]
I also wasn't able to recreate this issue in a controlled environment. Both using a new project with only `aws/aws-sdk-php` and with my companies `composer.json`, the built in PHP server served my PHP script with `vendor/autoload.php` successfully.

This does tell me that it has to relate to other code or imports in my project; however, it tells me that while knowing that at no point is the `aws/aws-sdk-php` package being pulled in more than once. That leaves me with very little direction to go. If I am unable to find declarations of the `src/functions,php` functions anywhere else in my project then I am left without much I can do.

If you have any other testing ideas feel free to let me know. Otherwise, the most effective solution I have is my pull request.

Thanks, by the way. I hope I don't come across as rude; it's just extremely difficult to debug a problem when all your leads turn up empty. It's basically debugging blindly.

**Comment by howardlopez** [comment]
Unfortunately we cannot merge in your PR which addresses an issue specific to your environment.

Is it possible that there may be code being brought in outside the scope of your search? Could code be being brought in from above your project root, or from another volume or somewhere else on your network? 

If you have access to a file-searching utility like [grep](http://man7.org/linux/man-pages/man1/grep.1.html), you could run a search for any declaration of the Aws namespace:

```
grep -R "namespace Aws" *
```

I would recommend running searches like that from the root of your environment (i.e. `/`), and from any distinct location you suspect your project may be bringing in code.

**Comment by tbarry-eminence** [comment]
Unfortunately, did not turn up anything unexpected. Within my entire environment, the only declarations of the `namespace Aws` string are within the `vendor/aws/aws-sdk-php` directory of my site project. It's painful to admin but I think the best course of action for now is to maintain and use my fork of the `aws/aws-sdk-php` repository.

Thanks again for your patience and support. Feel free to reject my pull request and close this issue; I'll just have to continue investigations on my own and hopefully find a solution at a later date.

**Comment by howardlopez** [comment]
One last thing I would suggest is to see if anything in your codebase is requiring the `functions.php` file directly. That would trigger a "Cannot redeclare" error as well. Good luck!

**Comment by tbarry-eminence** [comment]
Fantastic call on that last point, that did it!

This site is a legacy Drupal 7 site. It can be a bit daunting to try and figure out how things work at times. Turns out, there's a module called [xautoload](https://www.drupal.org/project/xautoload) for Drupal 7 which attempts to scan the entire code base and build up a composer autoload of the potentially many `composer.json` files.

It's not even being used by any code, so by removing the module I am now able to require `aws/aws-sdk-php` without issue.

I appreciate all the help once again, thanks!

**Comment by theasteve** [comment]
I'm having the same issue. After running `grep -R "namespace Aws" *` I see that `namespace Aws` is being called from another plugging
```
wp-content/mu-plugins/send-me-nyc/third-party/AWS/Aws/Ec2/Ec2Client.php:namespace Aws\Ec2;
wp-content/plugins/s3-uploads/lib/aws-sdk/Aws/Lambda/LambdaClient.php:namespace Aws\Lambda;
```
When running the `s3-uploads` verify command I get the following.

```
PHP Fatal error:  Cannot redeclare Aws\manifest() (previously declared in /var/www/html/vendor/aws/aws-sdk-php/src/functions.php:342) in /var/www/html/wp-content/mu-plugins/send-me-nyc/third-party/AWS/Aws/functions.php on line 320
Fatal error: Cannot redeclare Aws\manifest() (previously declared in /var/www/html/vendor/aws/aws-sdk-php/src/functions.php:342) in /var/www/html/wp-content/mu-plugins/send-me-nyc/third-party/AWS/Aws/functions.php on line 320
```
How can I solve this issue so both plugins don't conflict with each other when declaring  `Aws\manifest()`?

**Comment by TBPixel** [comment]
@theasteve This issue is caused by those function declarations being either literally declared twice or being autoloaded for declaration twice.

The only way to solve this issue is to remove one of the declarations. If the plugin is causing a declaration issue then either the plugin or the package defined via composer should be removed. Personally while I would lean towards removing the plugin I know that WordPress can be a bit annoying to work with so which you choose to remove is up to you.

This was also similar to my issue in Drupal 7. There was a plugin which searched for and autoloaded composer packages, and then there was the generated composer `vendor/autoload.php` file. Since both found the `aws/aws-sdk-php` package, both attempted to autoload it and the functions were considered re-declared. I removed the Drupal 7 plugin which autoloaded composer packages in favour of using composer and resolved my issue.
