### ISSUE TITLE
I can't set 1 week expiration date in V4 signature when timezone is New York

### ISSUE THREAD

**Issue by haoxi911** [aws/aws-sdk-php#1660]
Steps to reproduce the issue:

1- Set your PHP timezone to New York via `date_default_timezone_set('America/New_York')`
2- Create a pre-signed URL 
```
$s3Client = new S3Client([
            'region' => 'us-east-1',
            'version' => 'latest',
            'credentials' => [
                'key' => env('S3_AWS_KEY'),
                'secret' => env('S3_AWS_SECRET')
            ]
        ]);
$cmd = $s3Client->getCommand('GetObject', [
            'Bucket' => $bucket,
            'Key' => $fileKey
        ]);
$s3Client->createPresignedRequest($cmd, '+7 days')
```

Then you will receive an exception `The expiration date of a signature version 4 presigned URL must be less than one week`. However, what I passed in exactly 1 week.

By digging into the SDK source, I realized the problem is with `strtotime` method, see the following output in my PHP console. Note: 1 week is 604800 seconds, not 608400 seconds.

```
>>>date_default_timezone_set('America/New_York')
>>> $startTimestamp = time();
=> 1540780462
>>> $timestamp = strtotime('+7 days', $startTimestamp)
=> 1541388862
>>> $timestamp - $startTimestamp
=> 608400

>>>date_default_timezone_set('UTC')
>>> $startTimestamp = time();
=> 1540780462
>>> $timestamp = strtotime('+7 days', $startTimestamp)
=> 1541388862
>>> $timestamp - $startTimestamp
=> 604800

>>> 7 * 24 * 60 * 60
=> 604800
```

It is probably because of US Daylight Saving Time: https://www.timeanddate.com/time/change/usa

**Comment by haoxi911** [comment]
More information...

```
>>> date_default_timezone_set('America/New_York')
>>> $startTimestamp = time();
>>> $timestamp = strtotime('+6 days 3 hours', $startTimestamp)
=> 1541318214
>>> $timestamp - $startTimestamp
=> 532800
>>> $timestamp = strtotime('+6 days 2 hours', $startTimestamp)
=> 1541311014
>>> $timestamp - $startTimestamp
=> 525600
```

**Comment by haoxi911** [comment]
Hi @diehlaws, thanks for your explanation. I think I will want to keep my server time same as New York time (we are in GA). Do you know if there is a best practice or something that discourage us to do so?

For now, I am using `+6 days 23 hours`. Thanks!

**Comment by diehlaws** [comment]
No problem! I'm not aware of any common/best practices that advise against using any given timezone, but keeping the presign duration at the maximum value of 1 week with a timezone that observes DST would result in this issue resurfacing once a year when the clock is set back an hour for that timezone. 

If changing the presign duration works better for your use case I advise changing that instead of the timezone. Please don't hesitate to reach out again if you run into other issues!

**Comment by haoxi911** [comment]
@diehlaws Thank you!
