### ISSUE TITLE
PHP Fatal Error: UsesServiceTrait not found

### ISSUE THREAD

**Issue by dreamer-89** [aws/aws-sdk-php#1668]
Get below error message:
`PHP Fatal error:  Trait 'Aws\Test\UsesServiceTrait' not found in /.../AwsV3/vendor/aws/aws-sdk-php/tests/DynamoDb/WriteRequestBatchTest.php on line 20

No error comes up when including UsesServiceTrait definition in same test class (WriteRequestBatchTest)

**Comment by diehlaws** [comment]
Thanks for reaching out to us about this @dreamer-89, it certainly sounds like unexpected behavior stemming from the SDK. Can you provide complete code samples showing the error and success cases so that we can verify this behavior on our end?
