### ISSUE TITLE
load_compiled_json includes using @ hiding out of memory errors

### ISSUE THREAD

**Issue by jeichorn** [aws/aws-sdk-php#1675]
In functions.php there is a `load_compiled_json` function.  This does a file include with an @.

```
if ($compiled = @include("$path.php")) {
        return $compiled;
}
```

The obvious reason for failure is the file not existing.  However including those files allocates memory since they are returning arrays.  So if that include puts you over the memory limit you die silently in a really hard to trace way.

**Comment by howardlopez** [comment]
The error suppression in this function has been refactored and merged in, so memory errors should now be emitted. It's currently available on the master branch and will be in the next release.
