### ISSUE TITLE
getIterator versus Scan

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [aws/aws-sdk-php#1686]
Hi all,
I'm trying to get results from a table into DynamoDb.

I have tried this way:

```
      $iterator = $this->client->scan(array(
            'TableName' => $this->table
        ));
```

In this case I retrieve results.

If I try to use getIterator it returns an empty object.

```
      $iterator = $this->client->getIterator('Scan', array(
            'TableName' => $this->table
        ));
```

Why?

**Comment by diehlaws** [comment]
Hi @AlessandroMinoccheri, thanks for reaching out to us. When using `getIterator`, the object returned is a Generator upon which you need to iterate to retrieve the results it contains (e.g. with `foreach`) as shown below.

```php
$iterator = $this->client->getIterator('Scan', array(
    'TableName' => $this->table
));

foreach($iterator as $item) {
    var_dump($item);
}
```

**Comment by AlessandroMinoccheri** [comment]
ok, but why the results are different? I thought that the response could be a different object but data I was expected that will be the same.. different object but same data inside, or not?

**Comment by diehlaws** [comment]
The response from both methods should contain the same dataset that DynamoDB provided as a response to the API call, however using the generator eliminates the need to allocate memory for the complete response so that memory is only allocated for the components you want to retrieve from this response. 

In the example below you can see that scanning a table via `scan` and invoking `getIterator` to scan the same table returns different output (for example metadata for the request is not included in the iterator), however the returned table contents are the same.

```php
root@362f454aeab1:/var/www/html/GH/1686# cat ddbIterator.php
<?php

require_once("/var/www/html/aws-sdk/aws-autoloader.php");   

use Aws\DynamoDb\DynamoDbClient;      
     
$client = new DynamoDbClient([        
    'region' => 'us-west-2',          
    'version' => 'latest', 
    // 'debug' => true,    
]);  
     
$scan = $client->scan([    
    'TableName' => 'go-2223'          
]);  
     
echo "Scan results:\n";    
var_dump($scan);
     
$iterator = $client->getIterator('Scan', [       
    'TableName' => 'go-2223'          
]);  
     
echo "\nDumping iterator result:\n";  
var_dump($iterator);       
     
echo "\nIterating over iterator result:\n";      
foreach($iterator as $item) {         
    var_dump($item);       
}    
root@362f454aeab1:/var/www/html/GH/1686# php ddbIterator.php
Scan results:   
object(Aws\Result)#152 (2) {
  ["data":"Aws\Result":private]=>
  array(4) {
    ["Items"]=>
    array(1) {
      [0]=>
      array(3) {
        ["key"]=>
        array(1) {
          ["S"]=>
          string(5) "value"
        }
        ["go-2223"]=>
        array(1) {
          ["S"]=>
          string(4) "test"
        }
        ["test"]=>
        array(1) {
          ["S"]=>
          string(4) "true"
        }
      }
    }
    ["Count"]=>
    int(1)
    ["ScannedCount"]=>
    int(1)
    ["@metadata"]=>
    array(4) {
      ["statusCode"]=>
      int(200)
      ["effectiveUri"]=>
      string(40) "https://dynamodb.us-west-2.amazonaws.com"
      ["headers"]=>
      array(7) {
        ["server"]=>
        string(6) "Server"
        ["date"]=>
        string(29) "Thu, 13 Dec 2018 21:57:26 GMT"
        ["content-type"]=>
        string(26) "application/x-amz-json-1.0"
        ["content-length"]=>
        string(3) "103"
        ["connection"]=>
        string(10) "keep-alive"
        ["x-amzn-requestid"]=>
        string(52) "T0GOQ6BAI074ITRG0U12BGN54BVV4KQNSO5AEMVJF66Q9ASUAAJG"
        ["x-amz-crc32"]=>
        string(10) "1031448073"
      }
      ["transferStats"]=>
      array(1) {
        ["http"]=>
        array(1) {
          [0]=>
          array(0) {
          }
        }
      }
    }
  }
  ["monitoringEvents":"Aws\Result":private]=>
  array(0) {
  }
}

Dumping iterator result:
object(Generator)#120 (0) {
}

Iterating over iterator result:
array(3) {
  ["key"]=>
  array(1) {
    ["S"]=>
    string(5) "value"
  }
  ["go-2223"]=>
  array(1) {
    ["S"]=>
    string(4) "test"
  }
  ["test"]=>
  array(1) {
    ["S"]=>
    string(4) "true"
  }
}
```

**Comment by AlessandroMinoccheri** [comment]
Thanks for the explanation, now I have to understand why results are different, but now is clear the difference between these methods.
Thanks

**Comment by sijoph** [comment]
@diehlaws
 Can you please help me with, how to write a query like sql in dynamoDB. I want search 'cities' from a cities table having country,cityname,type.  The cityname is searchable like 'houston' or 'illinois' etc. I need the result from the dynamoDb, mysql conditions given below: 
"((city=US AND type=Seller) AND ( cityname LIKE "%houst%" OR cityname LIKE '%illio%' ))  "
Please give me a solution to write a program for dynamodb-php with above condition.
