### ISSUE TITLE
S3 putObject `CacheControl` Option Not Respected On Pre-Signed Request

### ISSUE THREAD

**Issue by taylorotwell** [aws/aws-sdk-php#1691]
Hello!

I am creating a pre-signed request for the `putObject` command:

```php
$command = $client->getCommand('putObject', array_filter([
    'Bucket' => $bucket,
    'Key' => $key,
    'ACL' => $acl,
    'CacheControl' => 'max-age=2628000',
    'Expires' => $expires,
]));

// Create signed request...
```

However, only the "Expires" header is showing up in responses and in the meta-data for the S3 object when I view it in the S3 dashboard.

When I inspect the request headers on the signed request object... I see the Expires header but no Cache-Control header:

```
array:3 [
  "Host" => array:1 [
    0 => "my-bucket-name.s3.amazonaws.com"
  ]
  "x-amz-acl" => array:1 [
    0 => "public-read"
  ]
  "Expires" => array:1 [
    0 => "Fri, 11 Jan 2019 00:02:28 GMT"
  ]
]
```

**Comment by diehlaws** [comment]
Thanks for reaching out to us @taylorotwell. Unfortunately there is no way to force a given value for the Cache-Control header when creating a pre-signed PUT URL for S3. The PUT call that is issued using the pre-signed URL must include the desired Cache-Control header value, if this header is not present in the PUT request issued with the pre-signed URL it will not be included in the object's metadata.

While a pre-signed PUT URL cannot dictate the value of the Cache-Control header for the resultant PUT request, you can create a pre-signed POST request that uses a POST policy restricting what the request can and cannot contain as shown [here](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-presigned-post.html). More information on uploads to S3 using HTTP POST can be found on [this](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html) page of the S3 API reference.

**Comment by taylorotwell** [comment]
OK Thanks!
