### ISSUE TITLE
Waf client listIpSets returns "Operation not found"

### ISSUE THREAD

**Issue by fedor-softgrad** [aws/aws-sdk-php#1693]
I'm using aws-sdk-php version 3.81.6.
I run something like this
```php
    $sdk = new Aws\Sdk([
        'version' => 'latest',
        'region' => 'us-east-1',
    ]);

    $wafClient = $sdk->createWafRegional();
    $ipSets = $wafClient->listIpSets();
```
and get an exception: "Operation not found: ListIpSets".

**Comment by diehlaws** [comment]
Hi @fedor-softgrad, thanks for reaching out to us. Service operations in the AWS SDK for PHP are case sensitive, so while `listIPSets` is a valid operation for the `WafRegional` client there is no `listIpSets` operation for this client. I was able to run your code with successful output after capitalizing `listIpSets` to match its [documentation](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-waf-regional-2016-11-28.html#listipsets).

**Comment by fedor-softgrad** [comment]
It works, thank you! I used the IDE autocomplete feature and didn't pay attention to this.
