### ISSUE TITLE
MockHandler breaking change when passing aws/aws-sdk-php from 3.67.15 to 3.82.1

### ISSUE THREAD

**Issue by fredericbarthelet** [aws/aws-sdk-php#1696]
Hi,

I ran into an issue on my project when updating composer. One of my PHPunit test using AWS MockHandler to mock calls to S3 went bad after upgrading aws/aws-sdk-php from 3.67.15 to 3.82.1. Fixed this issue by requiring aws/aws-sdk-php with version strict @ 3.67.15

**Comment by howardlopez** [comment]
Can you provide a complete sample of the test code that is failing?
