### ISSUE TITLE
deleteMessageBatchAsync does not work

### ISSUE THREAD

**Issue by achertovsky** [aws/aws-sdk-php#1697]
Doing async action for deleteMessageBatch and it not getting to work smooth. I notice that messages is getting back to queue after visibility timeout.
In case of usage deleteMessageBatch (non-async) everything works smooth and messages geting removed
My code can be revieved in https://github.com/achertovsky/yii2-sqs/blob/master/src/handlers/SQSHandler.php deleteMessageBatchAsync func

**update**
happening on 3.81.5 and just updated to 3.82.1 - same

**Comment by diehlaws** [comment]
Thanks for reaching out to us @achertovsky. Asynchronous commands such as `deleteMessageBatchAsync` return a [promise](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_promises.html) that must be adressed separately from the asynchronous command in order for the corresponding API call to be sent to the service. If you are performing these asynchronous calls one at a time you can synchronously force their promises to complete via `$promise->wait()`, however if you are performing multiple asynchronous calls that you want to complete simultaneously you can chain their corresponding promises or combine them as shown in the documentation page linked above.

**Comment by achertovsky** [comment]
@diehlaws first of all i would like to say thanks!
Also i would be happy to know if its possible to gain this info from phpdocs or from docs. Is there some info?

Thanks! After the answer topic may be closed.

**Comment by achertovsky** [comment]
@diehlaws first of all i would like to say thanks!
Also i would be happy to know if its possible to gain this info from phpdocs or from docs. Is there some info?

Thanks! After the answer topic may be closed.

**Comment by diehlaws** [comment]
No problem! The PHP SDK documentation has a [page](https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-GuzzleHttp.Promise.Promise.html) for the Promise class that details the methods associated with it, however I find the SDK's developer guide page for [Promises](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_promises.html) to be more comprehensive in explaining what they are and how they should be used within the context of the SDK. The package the SDK uses for promises can be found [here](https://github.com/guzzle/promises), and Guzzle's [quickstart](http://docs.guzzlephp.org/en/stable/quickstart.html) documentation page goes into more detail on Promises for more general use cases.
