### ISSUE TITLE
S3 client getObject() with SaveAs => stream breaks as of v2.3.4

### ISSUE THREAD

**Issue by mpdude** [aws/aws-sdk-php#170]
Hi all,

I haven't had time yet to investigate this or provide a test for it, but here's the quick sketch:

The following code was working at least in the 2.2.1 version of this SDK:

```
<?php

use Aws\S3\S3Client;

$bucket = '...';
$keyname = '...';

// Instantiate the client.
$s3 = S3Client::factory(array(
    'key'    => '...',
    'secret' => '...'
));

$r = fopen('php://temp/', 'wb');

// Save object to a file.
$result = $s3->getObject(array(
    'Bucket' => $bucket,
    'Key'    => $keyname,
    'SaveAs' => $r
));

assert(is_resource($r));
$result = null;
assert(is_resource($r));
```

At least in version 2.3.4, the second assertion fails because at the time the $result is unset, eventually the destructor of an underlying Guzzle stream wrapping the $r resource will be called and closes $r.

Was this a deliberate change?

Where should I put a test for it? Is there bootstrapping documentation available for running the tests?

**Comment by thecosss** [comment]
Sorry lame here. I've got an error
"Fatal error: Class 'Guzzle\Http\EntityBody' not found in..."
What should I do?
