### ISSUE TITLE
Missing Handle Reject Promise of Provider

### ISSUE THREAD

**Issue by darkpsart** [aws/aws-sdk-php#1701]
Hi,

We have an issue about the credential exception. The queue worker of Laravel always throw an credential exception when it cannot get credential from IAM (response code=500). However, when call an API, it work correctly (AWS Client too).

I found in **aws\aws-sdk-php\src\Credentials\CredentialProvider.php**. The _$result_ is stored in static variable and it does not call provider() again when the promise is rejected.

When I comment _if(null===$result)_ , it work correctly.

![image](https://user-images.githubusercontent.com/11676691/50419433-69b89600-0863-11e9-8e93-af63af78137b.png)

**Comment by MattStypa** [comment]
# Problem
If the `InstanceProfileProvider` throws an error the `CredentialProvider` will get stuck in an infinite loop of errors. 

# Prerequisites
- Using instance metadata to provide credentials to `aws-sdk-php`

# How to replicate
1. Start the demo code with DISABLED network connection.
2. Enable network connection.
3. The code will continue FAILING indefinitely.

# Real world scenario
1. Laravel worker is processing Queue.
2. AWS credentials expire after few hours.
3. HTTP request to `http://169.254.169.254/latest/meta-data/iam/security-credentials/` times out.
4. Infinite loop of failures.

# Proposed solution
The `CredentialProvider` should clean up when Promise is rejected.

# Demo code
```
<?php

require __DIR__ . '/vendor/autoload.php';

$client = new Aws\Sqs\SqsClient([
    'region' => 'us-east-1',
    'version' => 'latest'
]);

while(true) {
    try {
        echo $client->getQueueUrl(['QueueName' => my_queue_name'])->get('QueueUrl') . "\n";
    } catch(Exception $e) {
        echo "FAIL\n";
    }

    sleep(1);
}
```

# Solution code
`CredentialProvider` `line 147`
```
return $result->then(
    function (CredentialsInterface $creds) use ($provider, &$isConstant, &$result) {
        // Determine if these are constant credentials.
        if (!$creds->getExpiration()) {
            $isConstant = true;
            return $creds;
        }

        // Refresh expired credentials.
        if (!$creds->isExpired()) {
            return $creds;
        }
        // Refresh the result and forward the promise.
        return $result = $provider();
    },
    function($reason) use (&$result) {
        $result = null;
        return new Promise\RejectedPromise($reason);
    }
);
```

**Comment by darkpsart** [comment]
Thanks @MattStypa for clarify the problem and how to fix it.

**Comment by howardlopez** [comment]
@MattStypa Thanks for the PR. It's been approved and merged.
