### ISSUE TITLE
feature: AppSync Client can't execute graphql query.

### ISSUE THREAD

**Issue by tmizuma** [aws/aws-sdk-php#1710]
Hello,

We would like to execute graphql(mutation) from PHP as migration from legacy architecture to new architecture.

**Comment by diehlaws** [comment]
Thanks for reaching out to us @tmizuma! Can you give us some more context on what you are trying to do with the AWS SDK for PHP that is not currently available? 

It sounds like you want to use the AWS SDK for PHP as a GraphQL client to invoke functions configured in your GraphQL API in AppSync, however please do correct me if I misinterpreted your request. Unfortunately, the [AppSync API](https://docs.aws.amazon.com/appsync/latest/APIReference/Welcome.html) does not support invoking functions created in a GraphQL API within AppSync so you won't be able to use the AWS SDK for PHP for this purpose. That being said, there are other PHP libraries you can use as GraphQL clients, some of which are listed on [this](https://graphql.org/code/#php) page.

**Comment by jinjingbo** [comment]
@diehlaws 
I am facing the same issue. I have tried the third party php GraphQL clients you listed above. 

My AppSync is using Cognito token for authorization. I can generate Cognito token successfully using AWS PHP SDK.

However I cannot find PHP equivalent of `Amplify federatedSignIn()`.  Without it, I cannot signing the query request from PHP server to AppSync.

Could you give me some information/direction on:
1. Is it possible to utilise AWS php SDK to implement `federatedSignIn()` ?
2. If change the AppSync auth method to `API_KEY Authorization` (https://docs.aws.amazon.com/appsync/latest/devguide/security.html#aws-appsync-security), can we use any PHP SDK method to make the request?
