### ISSUE TITLE
AWS SDK Class not found on production server

### ISSUE THREAD

**Issue by ihabzee** [aws/aws-sdk-php#1712]
I installed AWS SDK via composer along with Facebook and Google SDKs. All of them are working with no problem on my local MacOs environment. But once I pushed to our server all AWS clients are not working. FB and Google still working on production.

```
include_once(__DIR__ . "/../../../vendor/autoload.php");
use Aws\Rekognition\RekognitionClient;
use Aws\Sdk;
class RekognitionTest extends CI_Controller
{
private $client;

function __construct()
{
    $sharedConfig = [
        'version' => 'latest',
        'region' => 'us-east-1',
        'credentials' => [
            'key' => "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            'secret' => "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        ]
    ];
    $sdk = new Sdk($sharedConfig);
    $this->client = $sdk->createRekognition();
 }
}
```
in the above code I am getting error:

> PHP Fatal error: Class 'Aws\Sdk' not found

Also tried different ways to initiate the client using:

```
$this->client = new RekognitionClient([
            'version' => 'latest',
            'region' => 'us-east-1',
            'credentials' => [
                'key' => "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                'secret' => "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
            ]
        ]);
```
With the second way I am getting :

> PHP Fatal error: Class 'Aws\Rekognition\RekognitionClient' not found

SDK version: "aws/aws-sdk-php": "^3.82"

I am not sure what I am doing wrong here.

**Comment by diehlaws** [comment]
Hello @ihabzee, thanks for reaching out to us. It sounds like the AWS SDK for PHP is not present in the expected location when you're pushing your code to your server. You'll want to verify that the `vendor` directory specified in the path for your `include_once` command is present on the server. If it is, You should see the contents of [`src/`](https://github.com/aws/aws-sdk-php/tree/master/src) from our repository in `aws/aws-sdk-php/src/` within this `vendor/` directory (where `autoload.php` is located) on your server. 

Depending on your specific use case, it you may find it to be a more consistent experience to install the AWS SDK for PHP on your server either via the prepackaged phar of the SDK or via the ZIP file of the SDK as outlined in [this](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/getting-started_installation.html) documentation page.
