### ISSUE TITLE
SesClient SendEmail Invalid ARN

### ISSUE THREAD

**Issue by DennMonn** [aws/aws-sdk-php#1716]
Hi.
I try to implement the Amazon SES features on my small project.
I installed the aws-sdk-php, now, when I try to test it, I'm getting this error:

> Error executing "SendEmail" on "https://email.eu-west-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://email.eu-west-1.amazonaws.com` resulted in a `400 Bad Request` response: Sender InvalidPara (truncated...) InvalidParameterValue (client): Invalid ARN <>. - Sender InvalidParameterValue Invalid ARN <>. 77f37a6e-1c99-11e9-accb-45d83c363ac6 Invalid ARN <>.

I use a verified email address for "Source", "ReturnPath" and "ReplyToAddresses" params.

Can you help to fix this bug?

Thanks.

**Comment by diehlaws** [comment]
Hi @DennMonn, thanks for reaching out to us. Can you provide a code sample showing how the SES client and `SendEmail` parameters are being initialized, as well as how the `SendEmail` call is being issued? Providing sanitized debug output for calls returning this error would also be helpful - you can enable debug logging by setting the parameter `'debug' => true` in the service client's configuration as shown [here](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#debug).
