### ISSUE TITLE
I get an error with cloudfront signed urls

### ISSUE THREAD

**Issue by alaaNabawy** [aws/aws-sdk-php#1718]
Hello, I am trying to create signed urls in php but i have an issue that i can't handle 

`<Error><Code>KMS.UnrecognizedClientException</Code><Message>No account found for the given parameters</Message><RequestId>0F0A772FE67F0503</RequestId><HostId>juuIQZKHb1pbmiVkP7NVaKSODFYmBtj3T9AfDNZuXslhb++LcBsw9GNjpT0FG8MxgeQGqbVo+bo=</HostId></Error>`

this is the code

this is start.php
```
<?php


require 'vendor/autoload.php';

use Aws\S3\S3Client;
use Aws\CloudFront\CloudFrontClient;

$config = require('config.php');


// S3


	$client = new Aws\S3\S3Client([
	    'version'     => 'latest',
	    'region'      => 'us-east-2',
	    'credentials' => [
		    'key'      => '/*Redacted*/',
		    'secret'   => '/*Redacted*/',
		]
	]);

// CloudFront


	$cloudfront = CloudFrontClient::factory([
		
		'version'     => 'latest',
	    'region'      => 'us-east-2',

	]);
```

and this is config.php

```
<?php



return [

	's3'=>[

		'key'		=> '/*Redacted*/',
		'secret'	=> '/*Redacted*/',
		'bucket'	=> 'hdamovies',
		'region'	=> 'us-east-2',

	],

	'cloudFront'	=>	[
		'url'	=>	'https://d2t7o0s69hxjwd.cloudfront.net',
	],

];
```

index.php

```
<?php
   


   require 'config/start.php';


   $video = 'The Conjuring 2013.720p.BluRay - HDA.mp4';
   $expiry = new DateTime( '+1 hour' );

   $url = $cloudfront->getSignedUrl([

   		'private_key'	=> 'pk-/*Redacted*/.pem', 
		'key_pair_id'	=> '/*Redacted*/',
   		'url'	=> "{$config['cloudFront']['url']}/{$video}",
   		'expires'	=> strtotime('+10 minutes'),

   ]);

   echo "<a href=".$url.">Downlod</a>";
```

When i click in the link i get the error i attached, What is the problem?

**Comment by diehlaws** [comment]
Hi @alaaNabawy, thanks for reaching out to us. Is the object for which you are trying to generate a pre-signed URL encrypted with `AWS-KMS`? If so,  this looks to be a duplicate of #1568; unfortunately CloudFront has not yet implemented support to pre-sign URLs for KMS-encrypted S3 objects. Other CloudFront users have commented on [this post](https://forums.aws.amazon.com/thread.jspa?messageID=819324&tstart=0) in the CloudFront forums regarding this behavior, I'd suggest adding a comment on there expressing interest in this feature being implemented on the service.

In the meantime, changing the object's encryption to `None` or `AES-256` in S3 should allow your pre-signed URLs to work as expected.
