### ISSUE TITLE
A non well formed numeric value encountered 

### ISSUE THREAD

**Issue by sordev** [aws/aws-sdk-php#1719]
on line 19
aws-sdk-php/src/Api/DateTimeResult.php

I guess it's because some dates are coming with different format.

API call was 
https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-dlm-2018-01-12.html#getlifecyclepolicy

php 7.1

**Comment by sordev** [comment]
work around was to check if it's actually unix timestamp or not. If not just return as is for now.

**Comment by diehlaws** [comment]
Hi @sordev, thanks for reaching out to us about this. This behavior looks to be caused by a mismatch between the timestamp format provided in DLM's API model and the format the SDK is expecting in the response for this call. We are actively working with the service team to get this resolved.

**Comment by howardlopez** [comment]
@sordev We published a release [3.87.7](https://github.com/aws/aws-sdk-php/releases/tag/3.87.7) that includes a fix for the service model. This error should be resolved now, but let us know if you run into any more issues.

**Comment by sordev** [comment]
Thank you will check and let you know 👍
