### ISSUE TITLE
PHP5.6 Fatal Error: Memory exhausted in sdk v3.87

### ISSUE THREAD

**Issue by sharanyaa** [aws/aws-sdk-php#1723]
On updating to v3.87,  a fatal error occurs when attempting to publish to SNS.
Code:
```
$snsClient = new SnsClient([
            'version' => $version,
            'region'  => $region,
            'endpoint' => $endpoint,
            'credentials' => $credentials,
        ]);

$snsClient->publish([
                'Message'  => $message,
                'TopicArn' => $topicArn,
            ]);
```

> Allowed memory size of 268435456 bytes exhausted (tried to allocate 130968 bytes) in .../aws-sdk-php/src/Credentials/InstanceProfileProvider.php on line 52

points to`$json = (yield $this->request(self::CRED_PATH . $this->profile));` 
This error did not occur with a previous version of the sdk (v3.21).

Expected behavior:
Publish to SNS without any errors

**Comment by diehlaws** [comment]
Hi @sharanyaa, thanks for reaching out to us about this. Memory usage of the AWS SDK for PHP has increased slightly between versions 3.21.0 and 3.87.7 - publishing the same message to the same SNS topic using these two versions I can see that 3.87.7 uses approximately 950KB more RAM than 3.21.0.

```
root@efd7432844c8:/var/www/html/GH/1723# php snsPublish3.21.php
Using AWS SDK for PHP version 3.21.0
Allocated RAM before initializing SNS client: 670856 bytes.
Allocated RAM before initializing message: 2501960 bytes.
Allocated RAM before publishing to topic: 2504304 bytes.
Allocated RAM after publishing message: 3058408 bytes.
root@efd7432844c8:/var/www/html/GH/1723# php snsPublishLatest.php 
Using AWS SDK for PHP version 3.87.7
Allocated RAM before initializing SNS client: 645384 bytes.
Allocated RAM before initializing message: 3429016 bytes.
Allocated RAM before publishing to topic: 3431360 bytes.
Allocated RAM after publishing message: 4048592 bytes.
```

It sounds like your application is running just below the 256MB memory size you've allowed, and updating the SDK to the latest version is pushing the application's memory usage over this limit. If there's no way to reduce memory usage in other areas of your application I'd suggest raising the memory limit by a few MB to accommodate the additional memory usage of the newer version of the SDK.

**Comment by sharanyaa** [comment]
Hi @diehlaws , thank you for your response. I tried increasing the memory limit like you suggested, but the fatal error reoccured when the allocated memory was exhausted. 
I was noticing the same issue occur when assuming a role with StsClient - Here's a test script I used to look into the issue. [aws/aws-sdk-php v3.87.2, guzzlehttp/guzzle v6.3.3]

```
<?php
require 'vendor/autoload.php';

use Aws\Exception\AwsException;
use Aws\Sts\StsClient;

function stsAssumeRole() {
    $config = [
        'version' => 'latest',
        'region' => 'us-east-1',
    ];
    try {
        $stsClient = new StsClient($config);
        $result = $stsClient->assumeRole([
            'RoleArn' => 'role_arn',
            'RoleSessionName' => 'role_session_name',
            'DurationSeconds' => 3600,
        ]);
        var_dump($result);
    } catch (AwsException $e) {
        // output error message if fails
        var_dump($e->getMessage());
    }
}

stsAssumeRole();
?>
```
Here's the stacktrace from running this code with a memory limit of 512M.
<img width="1250" alt="screen shot 2019-02-14 at 12 24 18 pm" src="https://user-images.githubusercontent.com/3313711/52815434-85fed500-3053-11e9-9b3d-a55fdd99b1f4.png">

Looking into this further, it looks like more memory is used with each retry to read .aws/credentials and config.
```
clock_gettime(CLOCK_MONOTONIC, {8437328, 61741166}) = 0
access("~/.aws/credentials", R_OK) = -1 ENOENT (No such file or directory)
access("~/.aws/config", R_OK) = -1 ENOENT (No such file or directory)
brk(0)                                  = 0x55f6628fe000
brk(0x55f662922000)                     = 0x55f662922000
clock_gettime(CLOCK_MONOTONIC, {8437328, 62741526}) = 0
access("~/.aws/credentials", R_OK) = -1 ENOENT (No such file or directory)
access("~/.aws/config", R_OK) = -1 ENOENT (No such file or directory)
clock_gettime(CLOCK_MONOTONIC, {8437328, 63633096}) = 0
access("~/.aws/credentials", R_OK) = -1 ENOENT (No such file or directory)
access("~/.aws/config", R_OK) = -1 ENOENT (No such file or directory)
clock_gettime(CLOCK_MONOTONIC, {8437328, 64496996}) = 0
access("~/.aws/credentials", R_OK) = -1 ENOENT (No such file or directory)
access("~/.aws/config", R_OK) = -1 ENOENT (No such file or directory)
clock_gettime(CLOCK_MONOTONIC, {8437328, 65356329}) = 0
access("~/.aws/credentials", R_OK) = -1 ENOENT (No such file or directory)
access("~/.aws/config", R_OK) = -1 ENOENT (No such file or directory)
brk(0)                                  = 0x55f662922000
brk(0x55f662946000)                     = 0x55f662946000
clock_gettime(CLOCK_MONOTONIC, {8437328, 66404422}) = 0
access("~/.aws/credentials", R_OK) = -1 ENOENT (No such file or directory)
access("~/.aws/config", R_OK) = -1 ENOENT (No such file or directory)
clock_gettime(CLOCK_MONOTONIC, {8437328, 67295000}) = 0
access("~/.aws/credentials", R_OK) = -1 ENOENT (No such file or directory)
access("~/.aws/config", R_OK) = -1 ENOENT (No such file or directory)
clock_gettime(CLOCK_MONOTONIC, {8437328, 68217803}) = 0
access("~/.aws/credentials", R_OK) = -1 ENOENT (No such file or directory)
access("~/.aws/config", R_OK) = -1 ENOENT (No such file or directory)
clock_gettime(CLOCK_MONOTONIC, {8437328, 69185933}) = 0
access("~/.aws/credentials", R_OK) = -1 ENOENT (No such file or directory)
access("~/.aws/config", R_OK) = -1 ENOENT (No such file or directory)
brk(0)                                  = 0x55f662946000
brk(0x55f66296a000)                     = 0x55f66296a000
```  

Please let me know if you you need additional information. Thanks!

**Comment by sharanyaa** [comment]
Hi @diehlaws, have you been able to reproduce this behavior? Please let me know if you'll require more info to investigate.

**Comment by sharanyaa** [comment]
Update: On debugging the issue further, it looks like when there are no local credential providers, CredentialProvider infinitely loops on rejected promises (from #1705) and doesn't hit remoteCredentialProviders. The issue was resolved by downgrading to v3.83.0 of the aws sdk.

**Comment by diehlaws** [comment]
@sharanyaa Thanks for the update on this, and I do apologize for the long delay in response from our end. We are investigating improvements in memory management of the AWS SDK for PHP and will be tracking progress on this in #1273. Please don't hesitate to contribute to the discussion on that issue with your findings relating to this behavior.

**Comment by howardlopez** [comment]
@sharanyaa We haven't been able to replicate what you've run into with the infinitely looping CredentialProvider on rejected promises when there are no local credential providers, for the PHP, Guzzle, and SDK versions specified. Have you been able to replicate this issue on another environment? Would you be able to share any other relevant information about your configuration?
