### ISSUE TITLE
assumeRoleWithWebIdentity fails

### ISSUE THREAD

**Issue by martinssipenko** [aws/aws-sdk-php#1725]
When using SDK the `assumeRoleWithWebIdentity` operation fails with `couldn't retrieve verification key from your identity provider,  please reference AssumeRoleWithWebIdentity documentation for requirements` error message. If I perform the same operation using AWS CLI everything works as expected, if I try to make a POST request to STS api using postman, it also works.

Here is the code I use (variables removed):

```php
<?php

require_once __DIR__.'/vendor/autoload.php';

$sts = new \Aws\Sts\StsClient([
    'region'      => 'us-east-1',
    'version'     => 'latest',
    'credentials' => false,
]);

$r = $sts->assumeRoleWithWebIdentity([
    'RoleArn'          => '<role arn here>',
    'RoleSessionName'  => 'test',
    'WebIdentityToken' => '<jwt token here>',
]);


var_dump($r);
```

**Comment by martinssipenko** [comment]
Update: I belive this is because SDK adds `X-Amz-Security-Token` header, if I add this header to post request I make using postman, I get the same error as with SDK.

**Comment by diehlaws** [comment]
Hi @martinssipenko, thanks for reaching out to us. Unfortunately I'm not able to reproduce the described behavior on my end using PHP 7.2.9 and version 3.87.13 of the AWS SDK for PHP. I'm using a Cognito Identity pool with a Cognito User pool as the Identity pool's authentication provider and was able to issue the `assumeRoleWithWebIdentity` call successfully using a JWT token retrieved from a [`getOpenIdToken`](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-cognito-identity-2014-06-30.html#getopenidtoken) call.

What is the origin of the JWT token you're using on this call? It's possible that this behavior is specific to the authentication provider you're using. In addition to this, where are you seeing the `X-Amz-Security-Token` header set for this call? Looking at the `assumeRoleWithWebIdentity` request as it is sent in the debug output on my end does not appear to include the `X-Amz-Security-Token` header you mention:

```
> POST / HTTP/1.1
Host: sts.amazonaws.com
Content-Type: application/x-www-form-urlencoded
aws-sdk-invocation-id: 9b1a1cf859a7733aeaf0bd6f5cdbcfae
aws-sdk-retry: 0/0
User-Agent: aws-sdk-php/3.87.13 GuzzleHttp/6.3.3 curl/7.54.0 PHP/7.2.9
Content-Length: 1066

* upload completely sent off: 1066 out of 1066 bytes
< HTTP/1.1 200 OK
```

**Comment by martinssipenko** [comment]
Hi @diehlaws,

Looks like I got this wrong, the issue was indeed our own OIDC which took more than 5 seconds to respond to AWS STS with configuration and jwks, which lead to timeouts on STS side.

On a related topic, if I don't specify `'credentials' => false,` when constructing StsClient, the `assumeRoleWithWebIdentity` call fails in case there are no credentials present. At the end SDK tries to get credentials from EC2 meta and fails with exception. This API call does not require auth, so perhaps this could be fixed?

**Comment by diehlaws** [comment]
Apologies for the delay in response on this @martinssipenko. The behavior you're describing is expected of the SDK - when you initialize a new service client without providing any credential arguments, the SDK uses the default credential provider chain to find AWS credentials. If you want to construct clients to make anonymous calls to a service specifying `'credentials' => false` is the correct way to do so.
