### ISSUE TITLE
Problem with self-closing CommonPrefixes Element in ListObjects

### ISSUE THREAD

**Issue by kevinulrich** [aws/aws-sdk-php#1726]
When calling ListObjects (V1 and V2) and receiving back a self-closing `<CommonPrefixes/>` element, the SDK will return the following array struct as the result. This in turn will make the `is_dir()` call when using the streamwrapper implementation always return true as long as the given prefix does not contain any objects.

```
["CommonPrefixes"]=>
    array(1) {
      [0]=>
      array(0) {
      }
    }
```

I'm not sure if this behaviour is documented in any way but it is valid XML and the SDK response and the subsequently wrong behaviour of is_dir() is currently breaking my implementation when using a local mock S3 using adobe/s3mock. 

Thanks

**Comment by diehlaws** [comment]
Hi @kevinulrich, thanks for reaching out to us. Unfortunately I haven't been able to reproduce the behavior you're describing - `is_dir` calls to S3 paths that are either nonexistent or object keys return `false` as expected in my tests.

Can you provide a code sample that exhibits this behavior?

**Comment by kevinulrich** [comment]
Hey, sorry I wasn't responding earlier, I'm a little tied up these days.

So this behaviour does absolutely **not** happen wenn the AWS SDK is used with the actual AWS S3 API. It does however occur when using other S3 API implementations such as adobe/s3mock.

When querying a nonexistant path, the AWS API will not return any `<Contents>` or `<CommonPrefixes>`. The problem that I'm having not is that the implementation of adobe/s3mock actually returns a self-closing `<CommonPrefixes />` tag, which will in turn cause the PHP SDK to return an array of 1 empty array which then again will cause `is_dir()` to return true.
