### ISSUE TITLE
AttributesToGet don't retrieve preferred_username Cognito

### ISSUE THREAD

**Issue by ThomasBuisson** [aws/aws-sdk-php#1727]
Hello,
I'm trying to retrieve data from cognito with the listUser api's.
it works when i don't specify AttributesToGet parameter, also when i used AttributedToGet parameter with an array list containing my custom parameters and the email parameter but, when i tried to get  preferred_username, it doesn't retrieve any data.
Note that when i don't used AttributesToGet of the listUsers API, i retrieved the preferred_username.

Thanks

**Comment by diehlaws** [comment]
Hi @ThomasBuisson, thanks for reaching out to us. Which versions of PHP and the AWS SDK for PHP are you using when you encounter this behavior? Seeing a code sample would also help us get a better idea of how you're interacting with Cognito with our SDK.

Unfortunately I'm not able to reproduce this using PHP 7.2.9 and version 3.87.13 of the AWS SDK for PHP - calling `listUsers` with `preferred_username` as the sole string in `AttributesToGet` returns the expected output as shown below.

```php
$client = new Aws\CognitoIdentityProvider\CognitoIdentityProviderClient([
    'region' => 'us-west-2',
    'version' => 'latest',
]);

$users = $client->listUsers([
    'UserPoolId' => $pool,
    'AttributesToGet' => [
        'preferred_username'
    ]
]);
echo "{$users}\n";
```

```
$ php listUsers.php 
Model Data
----------
Data can be retrieved from the model object using the get() method of the
model (e.g., `$result->get($key)`) or "accessing the result like an
associative array (e.g. `$result['key']`). You can also execute JMESPath
expressions on the result data using the search() method.

{
    "Users": [
        {
            "Username": "diehlaws",
            "Attributes": [
                {
                    "Name": "preferred_username",
                    "Value": "alex"
                }
            ],
            "UserCreateDate": "2019-02-19T18:29:22+00:00",
            "UserLastModifiedDate": "2019-02-19T18:29:42+00:00",
            "Enabled": true,
            "UserStatus": "FORCE_CHANGE_PASSWORD"
        }
    ],
    
```
