### ISSUE TITLE
passing in CurlMUltiHandle and calling tick() does not fire requests

### ISSUE THREAD

**Issue by joshkaplan** [aws/aws-sdk-php#1728]
I am attempting to use asynchronous requests to SQS _without_ using `wait()`. To do this, I pass in a `CurlMultiHandler` and tick it myself. This code works fine on my local test environment. However, on production servers, the promises never resolve no matter how often I tick. We do pass in different credentials, but not sure why that would make a difference. Installed curl version is the same. 

Here is (roughly) the code
```php
use Aws\Sqs\SqsClient;
use GuzzleHttp\Handler\CurlMultiHandler;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Promise as P;
use GuzzleHttp\Promise\Promise;

$timeout = 30;
$t = microtime(true);

$curl = new CurlMultiHandler();
$handler = HandlerStack::create($curl);

$client = new SqsClient([
	'http_handler' => $handler,
	'version' => '2012-11-05',
	'region' => $region,
	'credentials' => $credentials
]);

$promise = $client->receiveMessageAsync([
	'QueueUrl' => $queue_url,
	'MaxNumberOfMessages' => 10,
	'WaitTimeSeconds' => 1,
])->then(function($value) use ($t) {
        // never gets here!
	$duration = microtime(true) - $t;
	echo "finished in $duration"; 
});

while (!P\is_settled($promise) && ((microtime(true) - $t) < $timeout)) {
	$curl->tick();
	usleep(10);
}
```

I have also confirmed that sending requests with Guzzle asynchronously _do_ resolve as expected when ticking the CurlMultiHandler:
```php
// same as above, but with 
$client = new GuzzleHttp\Client(['handler' => $handler]);
```

So I have concluded there is something happening internally with the SDK. My best guess is there is something in the waitList that is not being triggered with the `->tick()`.  Any ideas on what could be causing the issue?

***
__Refs:__
* https://github.com/guzzle/guzzle/issues/1127
* https://github.com/aws/aws-sdk-php/issues/621

**Comment by joshkaplan** [comment]
Update: it's `$credentials.` On production, `$credentials` are `null`, and the SDK automatically fetches the creds using STS. The request to STS does not appear to use the passed in `CurlMultiHandler`, so the `tick()` does nothing.  If I perform one synchronous call with `$sqs_client` before queueing up the promises and ticking curl, ticking processes the requests as expected (since the creds have already been fetched and cached.)

1. Is this a bug? Should the AWS SDK use the passed in http_handler for internal requests like this?
2. For now, how should I handle? I _think_ I need to override `credentials` with a new `CredentialProvider` which will either use the same `CurlMultiHandler`, or somehow manually fetch and re-fetch the tokens from STS when I need them.

**Comment by howardlopez** [comment]
Unfortunately, custom handlers aren't currently supported with the [default credential provider chain](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials.html#default-credential-chain). The default provider shouldn't be checking STS on its own, but perhaps you're referring to the [instance profile provider](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_provider.html#instanceprofile-provider)? 

In any case, you should be able to [supply your own custom provider](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_provider.html#creating-a-custom-provider) using your handler.

**Comment by joshkaplan** [comment]
We are using the default provider. I guess I’m misunderstanding exactly what it does. Does it send requests at all? My understanding was it does so lazily when assuming an IAM role. 

Custom provider makes sense to me.

**Comment by howardlopez** [comment]
Yes, the default provider will call other providers as part of its chain (including `InstanceProfileProvider`), some of which can send requests.
