### ISSUE TITLE
[Documentation bug] Deep links (via anchors) not working.

### ISSUE THREAD

**Issue by poisa** [aws/aws-sdk-php#1729]
Deep linking is not working. For example:

https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-logs-2014-03-28.html#filterlogevents

The above should take you to the filterLogEvents() anchor but it takes you to the top of the page. 

The same goes if you search for a specific method on the searchbox, it only goes to the exact location if you are already in the page for that Class (eg. looking for an S3 method in the S3 page). If you look for a method in another class it doesn't work (eg. looking for an S3 method in the EC2 page).

**Comment by diehlaws** [comment]
Thanks for reaching out to us about this @poisa. I've added a backlog item to have this behavior corrected and will bring it up during our next sprint.

**Comment by howardlopez** [comment]
A PR was merged addressing this issue, but keeping this open until release and propagation to the hosted docs occurs.

**Comment by howardlopez** [comment]
The fix should now be propagated to the docs pages: https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-logs-2014-03-28.html#filterlogevents

Note you may have to clear your browser cache to see the change.

**Comment by poisa** [comment]
This works beautifully now. Thanks!
