### ISSUE TITLE
HTTP code 417 from proxy after CONNECT - add config option to remove Expect header?

### ISSUE THREAD

**Issue by gman-wa** [aws/aws-sdk-php#1733]
Our application connects to AWS through a proxy server.  The proxy server isn't the best but application teams can't change it.

As it is, trying to upload files greater than 1MB using putObject() fail with

`AWS HTTP error: cURL error 56: Received HTTP code 417 from proxy after CONNECT (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)  (client): 417 Expectation Failed`

We can fix this by adding a line to the the SDK:

GuzzleHTTP/Handler/CurlFactory.php -> getDefaultConf()

Add `unset($conf['_headers']['Expect']);`

before `return $conf;`

Can you provide a configuration flag in the http section of the S3Client configuration array - maybe

```
    'http' => [
    'proxy' => MY_PROXY,
    **'proxy_remove_expect' => TRUE**
    ]
```
This would help with upgrading to the latest SDK without remembering to update this core file.

**Comment by diehlaws** [comment]
Hello @gman-wa, thanks for reaching out to us about this. Implementing an HTTP configuration option to remove the `Expect` HTTP request header from requests such as S3's `PutObject` seems like a reasonable feature request. I've marked the issue as such and will bring this up during our next sprint.

**Comment by srchase** [comment]
@gman-wa,

With the release today, ```expect``` can be set as an HTTP configuration option.  This will be forwarded to the underlying Handler.

By default, that Handler will include an Expect header on any request with a payload larger than 1MB.

The expect option can be set as follows:
```false```: disables ```Expect``` on all requests
```true```: enables ```Expect```  on all requests
Integer value: changes the payload size threshold from 1MB

For your use case, you can do the following:
```
'http' => [
    'proxy' => MY_PROXY,
    'expect' => FALSE
]
```

Disabling or altering the default behavior should be done with caution.  Disabling the Expect header can prevent the service from returning authentication or other errors.

**Comment by gman-wa** [comment]
@srchase - thank you very much!  We will try to get this into an upcoming sprint and test it out.
