### ISSUE TITLE
Amazon Textract

### ISSUE THREAD

**Issue by siarheipashkevich** [aws/aws-sdk-php#1739]
Could you please tell me how I can use Amazon Textract using this SDK?

**Comment by diehlaws** [comment]
Thanks for reaching out to us @siarheipashkevich. Unfortunately the AWS SDK for PHP does not have a service client available for Amazon Textract at this time - only the AWS CLI, Boto3, and the AWS SDK for Java can currently interact with this service; once the service is fully released it will be usable with more of our SDKs including the AWS SDK for PHP.

**Comment by diehlaws** [comment]
@siarheipashkevich [today's release](https://github.com/aws/aws-sdk-php/releases/tag/3.88.0) includes a service client for the Amazon Textract Preview program:

- Aws\Textract - This release is intended ONLY for customers that are officially part of the Amazon Textract Preview program. If you are not officially part of the Amazon Textract program THIS WILL NOT WORK. Our two main regions for Amazon Textract Preview are N. Virginia and Dublin. Also some members have been added to Oregon and Ohio. If you are outside of any of these AWS regions, Amazon Textract Preview definitely will not work. If you would like to be part of the Amazon Textract program, you can officially request sign up here - https://pages.awscloud.com/textract-preview.html. To set expectations appropriately, we are aiming to admit new preview participants once a week until General Availability.

Documentation for the service client is also now available on [this page](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-textract-2018-06-27.html). Please let us know if you have additional questions about this!

**Comment by siarheipashkevich** [comment]
Thanks for an awesome and up-to-date release @diehlaws!!!

**Comment by tvnr690** [comment]
when will be the PHP API for aws textract is released
