### ISSUE TITLE
Issue with S3Client class uploadDirectory method

### ISSUE THREAD

**Issue by mosesristo** [aws/aws-sdk-php#174]
Hi I was running this code on my php class

```
    $s3client = S3Client::factory(array(
                'key' => awsAccessKey,
                'secret' => awsSecretKey
    ));

                $s3client->uploadDirectory(
                        BASE_FILE . "/tmp/", $bucket, NULL, array(
                    'params' => array(
                        'acl' => 'public-read'
                    )
                        )
                );
```

but it gives an error:
[Wed Oct 30 18:24:23 2013] [error] [client 127.0.0.1] PHP Catchable fatal error:  Argument 2 passed to Guzzle\Service\Client::getCommand() must be of the type array, string given, called in /var/www/PrioritiesBranch/vendor/guzzle/guzzle/src/Guzzle/Service/Client.php on line 81 and defined in /var/www/PrioritiesBranch/vendor/guzzle/guzzle/src/Guzzle/Service/Client.php on line 98, referer: http://localhost/PrioritiesBranch/

I was confused as I tried to follow the api to the letter http://docs.aws.amazon.com/aws-sdk-php-2/latest/class-Aws.S3.S3Client.html#_uploadDirectory but it does not seems to work.

**Comment by jdgriffith** [comment]
I'm having the same issue. What is the correct method for setting pulic-read or make public on a directory upload? I am currently attempting the code below:

```
$s3->uploadDirectory($directory, $this->bucket, $path, ['params' => ['ACL' => 'public-read']])
```

**Comment by werdender** [comment]
Having tha same issue. In sources ACL not configuring, as I see:

````
    private function getS3Args($path)
    {
        $parts = explode('/', str_replace('s3://', '', $path), 2);
        $args = ['Bucket' => $parts[0]];
        if (isset($parts[1])) {
            $args['Key'] = $parts[1];
        }

        return $args;
    }
````
