### ISSUE TITLE
How to check response in s3 client?

### ISSUE THREAD

**Issue by SerikK** [aws/aws-sdk-php#1740]
I want to transfer folder, but error shows on server(gitlab ci): Error parsing response for PutObject: AWS parsing error: Error parsing XML: String could not be parsed as XML. My code:
`
$manager = new Transfer($client, $source, $dest);
$manager->transfer();
` 

I tried guzzle history middleware, but no luck:
`$container = [];
 $history = Middleware::history($container);
 $stack = HandlerStack::create();
 // Add the history middleware to the handler stack.
 $stack->push($history);
echo count($container); // 0`

**Comment by diehlaws** [comment]
Thanks for reaching out to us @SerikK. Is this an error that you receive consistently when trying to use the S3 Transfer Manager to upload objects to S3? Can you enable [debug logging](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#debug) on the SDK and provide the resultant output here?

**Comment by SerikK** [comment]
So, yes. Debug helped me to understand what is the problem. I have seen in debug that it is trying to put file, but server responses with 301 redirect. So I changed host to https and it is worked. I was trying to connect guzzle log and history plugins long time, but no luck. It did not stored requests. So, thanks.
