### ISSUE TITLE
Error: Error executing "PutObject" on "https://fpg22ly.s3.ap-south-1.amazonaws.com/250px-Phoenix_Sun_model.cur"; AWS HTTP error: cURL error 77: error setting certificate verify locations: CAfile: C:\xampp\apache\bin\curl-ca-bundle.crt CApath: none (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by GodfallentheCelestial** [aws/aws-sdk-php#1741]
Fatal error: Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "CopyObject" on "https://user1000.s3.ap-south-1.amazonaws.com/dfd1.jpg-copy"; AWS HTTP error: cURL error 77: error setting certificate verify locations: CAfile: C:\xampp\apache\bin\curl-ca-bundle.crt CApath: none (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' GuzzleHttp\Exception\RequestException: cURL error 77: error setting certificate verify locations: CAfile: C:\xampp\apache\bin\curl-ca-bundle.crt CApath: none (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\Users\Aks\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:186 Stack trace: #0 C:\Users\Aks\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\Users\Aks\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHa in C:\Users\Aks\vendor\aws\aws-sdk-php\src\WrappedHttpHandler.php on line 191

-not very experienced in all this.

**Comment by diehlaws** [comment]
Hi @GodfallentheCelestial, thanks for reaching out to us. This sounds like a problem with the certificate cURL is using on the host on which you are running XAMPP. As suggested by the error message, checking the presence of the certificate at `C:\xampp\apache\bin\curl-ca-bundle.crt` and the permissions for this file and the folder in which it resides would be a good place to start troubleshooting this behavior.

**Comment by GodfallentheCelestial** [comment]
@diehlaws I got a fix. Since I was using xampp I checked the apache/bin directory and found that the cUrl file was missing. I added a certificate file there. Thank you so much.

**Comment by mayoalexander** [comment]
This just happened to me, I'm using vagrant to run an Apache server. All I did was restart the server and it was all good to go. Checking the presence of the certificate at `C:\xampp\apache\bin\curl-ca-bundle.crt` is key for this bug
