### ISSUE TITLE
sendMessageAsync stopped working when php7.0-curl was installed

### ISSUE THREAD

**Issue by ellllllen** [aws/aws-sdk-php#1745]
Hi,
We had a situation in the last couple of days, where we installed php7.0-curl library on our server and SQS stopped receiving our messages. We have since fixed this by replacing `sendMessageAsync()` with `sendMessage()`.
There were no errors in our logs, just nothing being sent.

Versions we are using of aws-sdk-php:
aws/aws-sdk-php v3.88.0
aws/aws-sdk-php-laravel v3.3.1 

We would appreciate any input into this issue and let me know if you need more info.
Thanks

**Comment by diehlaws** [comment]
Thanks for reaching out to us @ellllllen. Unfortunately I haven't been able to reproduce this behavior with php7.0-curl. Can you provide a code sample so we can better understand how you're using the SDK to call `sendMessageAsync`?

**Comment by ellllllen** [comment]
Hi
Thanks for the response, this is our code:

`use Aws\Sdk;
use Aws\Sqs\SqsClient;

class SqsService
{
    /**
     * @var SqsClient
     */
    private $client;

    public function __construct(Sdk $sdk, array $config)
    {
        $this->client = $sdk->createSqs($config);
    }

    public function sendMessage($message, $url, $groupId, $dedupeId)
    {
        $this->client->sendMessageAsync([
            'MessageBody' => $message,
            'QueueUrl' => $url,
            'MessageGroupId' => $groupId,
            'MessageDeduplicationId' => $dedupeId,
        ]);
    }
}`

**Comment by ellllllen** [comment]
We also believe this affecting any emails we are sending async as well. Using method `sendEmailAsync()`.

**Comment by ellllllen** [comment]
Might be related to: https://github.com/guzzle/guzzle/issues/1899

**Comment by diehlaws** [comment]
Thanks for the additional information @ellllllen, this is indeed related to https://github.com/guzzle/guzzle/issues/1899. As mentioned in that issue, Guzzle starts to use cURL as the handler when cURL extension for PHP is installed, and at this point your async calls can be executed in parallel. Your `sendMessageAsync` call will return a promise that needs to be handled after the API call is issued in your `sendMessage` function.

This could be done by resolving the promise within your `sendMessage` function, however this would have the same effect as replacing the `sendMessageAsync` call with the `sendMessage` call as you mentioned for your fix in that the API call would not be truly asynchronous.

```php
    public function sendMessage($message, $url, $groupId, $dedupeId)
    {
        $promise = $this->client->sendMessageAsync([
            'MessageBody' => $message,
            'QueueUrl' => $url,
            'MessageGroupId' => $groupId,
            'MessageDeduplicationId' => $dedupeId,
        ]);

        $promise->wait();
    }
}
```

Alternately, You could have your `sendMessage` function return the promise returned by the `sendMessageAsync` call to resolve it later in your code, either after something else happens once your `sendMessage` function is called or batching multiple promises to resolve at the same time as shown below.

```php
    public function sendMessage($message, $url, $groupId, $dedupeId)
    {
        $promise = $this->client->sendMessageAsync([
            'MessageBody' => $message,
            'QueueUrl' => $url,
            'MessageGroupId' => $groupId,
            'MessageDeduplicationId' => $dedupeId,
        ])->then(function($response) {
           echo "Message sent with ID {$response['MessageId']}\n";
        });

        return $promise;
    }
}
```

```php
$sdk = new Sdk();

$config = array(
    'region' => 'us-west-2',
    'version' => 'latest',
);

$service = new SqsService($sdk, $config);

$promises = [];

for ($i = 1; $i < 10; $i++) {
    $message = "message".$i;
    $dedupeId = "xyz".$i;
    $promise = $service->sendMessage($message, $url, $groupId, $dedupeId);

    $promises[$i] = $promise;
}

foreach ($promises as $promise) {
    $promise->wait();
}
```

**Comment by ellllllen** [comment]
Thanks for your help! That has cleared everything up.
This issue can be closed 👍
