### ISSUE TITLE
Get all dynamodb queries executed in current request

### ISSUE THREAD

**Issue by sahilsharma011** [aws/aws-sdk-php#1746]
Is there a way to get all queries executed in current request. For example, Laravel has `DB::getQueryLog()` which returns an array of all the executed queries and their bindings.  
This feature can be used for logging and improved debugging in dev and test environments. If there is no such feature I'd like to create a PR if someone can guide me a little bit.

**Comment by diehlaws** [comment]
Hi @sahilsharma011, thanks for reaching out to us. At this time the SDK does not provide a way to list queries executed in a given request to DynamoDB. The AWS SDKs serve primarily as a wrapper for API calls to AWS services with minimal customizations, that being said if you have a particular implementation of this feature in mind for which you'd like to submit a PR our contribution guidelines are available [here](https://github.com/aws/aws-sdk-php/blob/master/CONTRIBUTING.md). Please don't hesitate to follow up with any questions you may have for us.
