### ISSUE TITLE
Get presigned URL without expiration of private bucket files. 

### ISSUE THREAD

**Issue by kamran-jabbar** [aws/aws-sdk-php#1747]
I would like to ask, I have created an API to upload images/files on S3 bucket(private) using PHP SDK. I want to get the image/files with the authorization of access token and key. I got pre-signed URL which allows accessing the file, but that expires after the time limit we have provided. 
**Problem:**
I want to access AWS S3 private file access URL without expiry. Is this possible or is there any way to create pre-signed URL without expiry?

**Comment by diehlaws** [comment]
Hi @kamran-jabbar, thanks for reaching out to us. Unfortunately you cannot create a pre-signed S3 URL without an expiration date - [Signature Version 4](http://docs.aws.amazon.com/general/latest/gr/sigv4_signing.html) allows a maximum expiry time of 7 days.

**Comment by kamran-jabbar** [comment]
@diehlaws thanks for your response. Is there any other way to get file access URL from the private bucket with an access token and key or only way to make the file permission as public?

**Comment by kamran-jabbar** [comment]
In my app scenario, I just want to get file within my application, if any other person has the URL of the file that shouldn't be accessible. What is the recommended solution for this?

**Comment by diehlaws** [comment]
If the files are being uploaded to a private bucket to which the IAM user/role corresponding to your API keys has permission to access (either via the IAM policies attached to the user/role or the bucket policy attached to the S3 Bucket) you should be able to issue a `GetObject` call to download objects that have been uploaded to the bucket.

If you need to access the object via its S3 URL instead of issuing an API call with the SDK, then you'll need to generate a pre-signed URL to access it - in this case the best approach would be to have your application generate pre-signed URLs with a short expiration time (e.g. 30-120 seconds) each time you need to retrieve objects from this bucket.

**Comment by kamran-jabbar** [comment]
@diehlaws I have uploaded with access token and key. 
After calling the `GetObject` with the same access token and key getting the following response, is that due to the user has no access with that key and access token, and I have to give permission to that user readability/access from AWS settings? Right?
```
Aws\Result Object
(
    [data:Aws\Result:private] => Array
        (
            [Body] => GuzzleHttp\Psr7\Stream Object
                (
                    [stream:GuzzleHttp\Psr7\Stream:private] => Resource id #6
                    [size:GuzzleHttp\Psr7\Stream:private] => 
                    [seekable:GuzzleHttp\Psr7\Stream:private] => 1
                    [readable:GuzzleHttp\Psr7\Stream:private] => 1
                    [writable:GuzzleHttp\Psr7\Stream:private] => 1
                    [uri:GuzzleHttp\Psr7\Stream:private] => php://temp
                    [customMetadata:GuzzleHttp\Psr7\Stream:private] => Array
                        (
                        )

                )

            [DeleteMarker] => 
            [AcceptRanges] => bytes
            [Expiration] => 
            [Restore] => 
            [LastModified] => Aws\Api\DateTimeResult Object
                (
                    [date] => 2019-03-13 10:42:08.000000
                    [timezone_type] => 2
                    [timezone] => GMT
                )

            [ContentLength] => 291073
            [ETag] => "xxxx"
            [MissingMeta] => 
            [VersionId] => 
            [CacheControl] => 
            [ContentDisposition] => 
            [ContentEncoding] => 
            [ContentLanguage] => 
            [ContentRange] => 
            [ContentType] => application/octet-stream
            [Expires] => Aws\Api\DateTimeResult Object
                (
                    [date] => 2019-03-13 23:51:55.892883
                    [timezone_type] => 3
                    [timezone] => xxxx
                )

            [WebsiteRedirectLocation] => 
            [ServerSideEncryption] => 
            [Metadata] => Array
                (
                )

            [SSECustomerAlgorithm] => 
            [SSECustomerKeyMD5] => 
            [SSEKMSKeyId] => 
            [StorageClass] => 
            [RequestCharged] => 
            [ReplicationStatus] => 
            [PartsCount] => 
            [TagCount] => 
            [ObjectLockMode] => 
            [ObjectLockRetainUntilDate] => Aws\Api\DateTimeResult Object
                (
                    [date] => 2019-03-13 23:51:55.893702
                    [timezone_type] => 3
                    [timezone] => xxx
                )

            [ObjectLockLegalHoldStatus] => 
            [@metadata] => Array
                (
                    [statusCode] => 200
                    [effectiveUri] => xxxxx
                    [headers] => Array
                        (
                            [x-amz-id-2] => xxxx
                            [x-amz-request-id] => xxx
                            [date] => Wed, 13 Mar 2019 18:52:29 GMT
                            [last-modified] => Wed, 13 Mar 2019 10:42:08 GMT
                            [etag] => "xxxx"
                            [accept-ranges] => bytes
                            [content-type] => application/octet-stream
                            [content-length] => 291073
                            [server] => AmazonS3
                        )

                    [transferStats] => Array
                        (
                            [http] => Array
                                (
                                    [0] => Array
                                        (
                                        )

                                )

                        )

                )

        )

    [monitoringEvents:Aws\Result:private] => Array
        (
        )

)
```

**Comment by diehlaws** [comment]
In order for a given IAM user to access an object in an S3 Bucket they must be allowed the action `s3:GetObject` on the object in question 
(`"Resource": "arn:aws:s3:::bucketname/path/to/object.txt`), the path in which the object exists (`"Resource": "arn:aws:s3:::bucketname/path/to/*`), or a larger portion of the bucket that includes the path to the object (`"Resource": "arn:aws:s3:::bucketname/*`). This can be granted by an [IAM policy](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html#policies_id-based) attached to the user (or to a group the user is a part of), or by a [Bucket Policy](https://docs.aws.amazon.com/AmazonS3/latest/dev/using-iam-policies.html) attached to the S3 Bucket.

That being said, the response you've provided looks like the `GetObject` call worked - I see that the HTTP status code is 200 (if the user didn't have appropriate permissions that would be a 403), and the ContentLength looks to be substantially larger than the XML response that S3 would return for an HTTP 403 response.

If you're looking to use `getObject` to save the file you're trying to download to the host that is running the code issuing this API call, you'll want to specify the path to which you want to save this file locally as the value for `SaveAs` in the parameters for the call.

**Comment by kamran-jabbar** [comment]
In my case I have larger images like size will be greater than 30MB, so the thing is I only want to access image via S3 URL like I have to use image tag with src with in my APP. 
```<img src="s3path" />```
If I download the image that will be costly, how can I do that without downloading and URL should be allowed on my web and mobile APP only(If that access URL requires authrization that is fine), in that scenario AWS S3 recommend which ways?

**Comment by JCole45** [comment]
> Hi @kamran-jabbar, thanks for reaching out to us. Unfortunately you cannot create a pre-signed S3 URL without an expiration date - [Signature Version 4](http://docs.aws.amazon.com/general/latest/gr/sigv4_signing.html) allows a maximum expiry time of 7 days.

How do we set the expiration time for pre signed urls?

**Comment by kamran-jabbar** [comment]
@JCole45 
`PHP` in this way. 
```
public function getPreSignedUrl()
{
        $command = $this->getClient()->getCommand(
            'GetObject',
            [
                'Bucket' => 'bucketname',
                'Key' => 'key',
            ]
        );
        $request = $this->getClient()->createPresignedRequest($command, '+120 minutes');
        $preSignedUrl = (string)$request->getUri();

        return $preSignedUrl;
}
```
