### ISSUE TITLE
Path-style URL switches to virtual host style URL after changing scheme to HTTP in S3 client config

### ISSUE THREAD

**Issue by liubo1985** [aws/aws-sdk-php#1749]
Hi, 
We are trying to upgrade the aws sdk from v2 to v3 (v3.91). For S3 URL, It used to be path-style url, e.g. s3.us-west-2.amazonaws.com/bucket_name/key. After we changed scheme in S3 client config, I found that the URL is changed to virtual host style, e.g. bucket_name.s3.amazonaws.com/key. Is it expected? I took a look at this #1129 , seemed like it's a bug and already fixed. Does it mean it shows up again?
The S3 client config we used before was
`
$config = array();
$credentials = new Credentials($key, $secret);
$config['credentials'] = $credentials;
$config['scheme'] = 'https';
$config['signature'] = 'v4';
$config['region']    = 'us-west-2';
$config['version']   = '2006-03-01';
$client = new S3Client($config);

`
Then I removed 'signature' field and changed 'scheme' to 'http'. I found the url changed to virtual host style.

**Comment by diehlaws** [comment]
Hi @liubo1985, thanks for reaching out to us. The issue you mention refers to prepending the bucket name to the virtual-style endpoint, resulting in the endpoint containing the bucket name twice when the endpoint is specified in the client config parameters. `S3Client` for Version 3 of the AWS SDK for PHP defaults to using virtual-style URLs when building the endpoint for a given request, so this behavior is expected for the current major version of the SDK. 

That being said, if your use case requires using path-style URLs instead you can specify this behavior by setting `use_path_style_endpoint` to `true` in the client [configuration parameters](https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.S3.S3Client.html#___construct) as shown below.

```
$credentials = new Credentials($key, $secret);

$client = new S3Client([
    'credentials' => $credentials,
    'region' => 'us-west-2',
    'version' => '2006-03-01',
    'scheme' => 'http',
    'use_path_style_endpoint' => true,
]);
```

**Comment by liubo1985** [comment]
Thank you for your reply. It works now.
