### ISSUE TITLE
DateTime::__construct(): Failed to parse time string (XXXX) at position: Unexpected character

### ISSUE THREAD

**Issue by liubo1985** [aws/aws-sdk-php#1753]
Recently, we migrated to AWS SDK V3, but got this error sometimes. Seems like the error is from parsing s3 response. Could someone give some help? Thanks in advance. 

DateTime::__construct(): Failed to parse time string (511301473873) at position 11 (3): Unexpected character

The stack trace:
../vendor/aws/aws-sdk-php/src/Api/Parser/
in DateTime::__construct called at ../vendor/aws/aws-sdk-php/src/Api/Parser/AbstractRestParser.php
AbstractRestParser.php (123)
…/vendor/aws/aws-sdk-php/src/Api/Parser/
AbstractRestParser.php (46)
…/vendor/aws/aws-sdk-php/src/S3/
RetryableMalformedResponseParser.php (37)
…/vendor/aws/aws-sdk-php/src/S3/
AmbiguousSuccessParser.php (58)
…at /vendor/aws/aws-sdk-php/src/S3/
GetBucketLocationParser.php (29)
… called at ../vendor/aws/aws-sdk-php/src/
WrappedHttpHandler.php (125)
… called at ../vendor/aws/aws-sdk-php/src/
WrappedHttpHandler.php (92)
…losure} called at ../vendor/guzzlehttp/promises/src/
Promise.php (203)
…Handler called at /vendor/guzzlehttp/promises/src/
Promise.php (156)
…sure} called at /vendor/guzzlehttp/promises/src/
TaskQueue.php (47)
…at /vendor/guzzlehttp/guzzle/src/Handler/
CurlMultiHandler.php (98)
…at /vendor/guzzlehttp/guzzle/src/Handler/
CurlMultiHandler.php (125)
…execute called at /vendor/guzzlehttp/promises/src/
Promise.php (246)
…eWaitFn called at /vendor/guzzlehttp/promises/src/
Promise.php (223)
…Pending called at /vendor/guzzlehttp/promises/src/
Promise.php (267)
…aitList called at /vendor/guzzlehttp/promises/src/
Promise.php (225)
…Pending called at /vendor/guzzlehttp/promises/src/
Promise.php (267)
…aitList called at /vendor/guzzlehttp/promises/src/
Promise.php (225)
…Pending called at /vendor/guzzlehttp/promises/src/
Promise.php (62)
…wait called at /vendor/aws/aws-sdk-php/src/
AwsClientTrait.php (58)

**Comment by diehlaws** [comment]
Hi @liubo1985, thanks for reaching out to us. The error and stack trace provided do seem to point to the SDK receiving a response from S3 that includes a timestamp which it is unable to parse correctly, however it is unclear which field in the response is returning this timestamp. The following information will help us better assist with this behavior.

- Which versions of PHP and the AWS SDK for PHP are you using when encountering this error?
- What S3 operation is being issued when receiving the response that causes this error?
- Does this occur with a specific object in S3 or has it occurred with different objects?
- Are you able to reproduce this consistently or is it sporadic behavior?
- Can you retrieve the request ID pair (`x-amz-request-id` and `x-amz-id-2` headers) from the response before the exception is thrown? You may have to enable [debug logging](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#debug) in your S3 client to do so.

**Comment by liubo1985** [comment]
Hi, @diehlaws, thank you for your prompt reply. Please take a look at my inline answers to your questions.

1. Which versions of PHP and the AWS SDK for PHP are you using when encountering this error?
   The PHP version we are using is 7.2.16 with OpCache(v7.2.16) enabled . AWS SDK version is 3.90.5 which is installed via Composer.

2. What S3 operation is being issued when receiving the response that causes this error?
   For this part, it's hard to tell. We also want to figure out this operation caused the error. The stack trace only shows the error from SDK, no errors from high level.
   What I can tell is we can narrow down two operations using sdk. One is getObject(), the other one is putObject(). 
   
3. Does this occur with a specific object in S3 or has it occurred with different objects?
   It occurred with different objects. We get/put objects all the time and I kept seeing such errors. 
   
4. Are you able to reproduce this consistently or is it sporadic behavior?
   I am able to reproduce this consistently. We have a worker to consume SQS and process the job. Every time running the worker, This error shows up.
   
5. Can you retrieve the request ID pair (x-amz-request-id and x-amz-id-2 headers) from the response before the exception is thrown? You may have to enable debug logging in your S3 client to do so.
   Because we already shipped it to our product. If I enable debug logging, will the performance be affected? Also, where can I get the logs?

**Comment by liubo1985** [comment]
Just continue my reply, I did not see this error on my dev box. But after deploying to prod, that error showed up. I am not sure if it's due to the throughput. For question 4, I should say not reproduce on dev but see many such errors on prod. 

For question 5, I think I can make the changes and collect some data on our prod.

**Comment by liubo1985** [comment]
Hi, @diehlaws, 
What I did was I logged the debug info into our log system. You can think of it as a log file. I found there were a huge of debug info in our log files. Is there a way I could modify sdk to filter out debug info as we only want x-amz-request-id and x-amz-id-2 headers, other info are unnecessary.

**Comment by SamRemis** [comment]
@liubo1985 This should have been fixed by the above pull requests, can you confirm that you haven't seen it since?  I will set this to auto-close; it will close in a few days if you don't respond.
