### ISSUE TITLE
Is the AWS config file an INI file?

### ISSUE THREAD

**Issue by oshdev** [aws/aws-sdk-php#1754]
I have a config file that looks similar to the following:
```
# This file is managed by puppet, do not edit manually!

[profile live]
region=eu-west-1

[profile test]
region=eu-west-1
```
This produces a warning per http://uk3.php.net/manual/en/function.parse-ini-file.php:
>  PHP Warning:  syntax error, unexpected '!' in /var/lib/jenkins/.aws/config on line 1
 in /path/vendor/aws/aws-sdk-php/src/ClientSideMonitoring/ConfigurationProvider.php on line 235

The question is - should my provider not use hash for a comment in the config file, cause it's not a valid comment (should be `;`) or is the config file **not** an `ini` file, but a shell or similar and the SDK is using invalid parser for the file?

**Comment by srchase** [comment]
@oshdev 

Thanks for opening this issue.  The AWS config file closely resembles an INI file, but it is intended to support comments with a hash.  The SDK is currently uses ```parse_ini_file()```, which unfortunately stopped accepting hashes for comments in 7.0.0.

As a workaround, you can use semi-colons, but this does need to be addressed in the SDK.

**Comment by oshdev** [comment]
It's not a big issue, I guess we should just try to avoid invalid characters for the keys.
Worth noting that the _# comments_ are still parsed:
```[profile live]
region=eu-west-2
# this is a long comment spread over multiple lines
# to keep them not too long and it's about explaining
# to the user that the application will break if they do
# region = some invalid value
```
```
array(1) {
  'profile live' =>
  array(2) {
    'region' =>
    string(9) "eu-west-2"
    '# region' =>
    string(18) "some invalid value"
  }
}
```
So because there was `=`, the parser created a key-value pair, where key starts with `#`, but I don't suppose this would break anything down the line and would be simply ignored. Feel free to close this.

**Comment by howardlopez** [comment]
#1757 adds support for full-line hash comments, though note that in-line hash comments will still be interpreted as part of the value for PHP 7+.
