### ISSUE TITLE
TypeError: Argument 1 of Aws\Multipart\AbstractUploadManager::Aws\Multipart\{closure}() must be an instance of Exception, instance of Error given

### ISSUE THREAD

**Issue by bradynpoulsen** [aws/aws-sdk-php#1755]
The `AbstractUploadManager` is catching `Exception` types, however, if a PHP 7.0+ `Error` is thrown, the actual error that occurred is suppressed by the registered error handler of the promise. 

https://github.com/aws/aws-sdk-php/blob/bccb5b3509ed7517e50a75bba6b19ac4506aae70/src/Multipart/AbstractUploadManager.php#L140-L146

**Comment by bradynpoulsen** [comment]
This appears to be an oversight since the `Error` could have been produced by the coroutine itself. I'll write a PR with a proposal on how to fix this

**Comment by diehlaws** [comment]
Thanks for bringing this to our attention @bradynpoulsen. This is certainly unexpected behavior so I've marked the issue as a bug. Please feel free to leave more comments with any additional information you find on this.
