### ISSUE TITLE
Using S3Client->copyObject leads to inconsistent stream wrapper cache

### ISSUE THREAD

**Issue by maechler** [aws/aws-sdk-php#1758]
When using the method `S3Client->copyObject` to copy an object onto itself the corresponding stream wrapper cache gets not cleared although the `modified time` of the object has changed. That is not much of a problem using the `LruArrayCache` but it is a big issue if you use a cache that has a longer lifetime. We use a database cache that has effectively an infinite lifetime, thus cache consistency becomes very important.

We can reproduce this issue by using two different clients with two different stream wrappers. We use `$clientA` to add a file to the bucket, sleep for 10 seconds and then use `copyObject` on `$clientA`. The file in the S3 bucket now has an updated modified time. When reading from the stream wrapper of `$clientA`, we still get the file create time as modified time.  When reading from the stream wrapper of `$clientB`, we get the correct modified time as it uses a separate, empty cache.

```php
$clientA = new Aws\S3\S3Client([/** options **/]);
$clientB = new Aws\S3\S3Client([/** options **/]);
$key = 'some/path/test.txt';
$bucket = 'your-bucket';
$streamWrapperAKey = 's3.a://' . $bucket . '/' . $key;
$streamWrapperBKey = 's3.b://' . $bucket . '/' . $key;

Aws\S3\StreamWrapper::register($clientA, 's3.a');
Aws\S3\StreamWrapper::register($clientB, 's3.b');

file_put_contents($streamWrapperAKey, 'Hello!');

$stats = [
    'created' => filemtime($streamWrapperAKey)
];

sleep(10);

$clientA->copyObject(array(
    'Bucket' => $bucket,
    'CopySource' => $bucket . '/' . Aws\S3\S3Client::encodeKey($key),
    'Key' => $key,
    'MetadataDirective' => 'REPLACE',
));

$stats['modifiedA'] = filemtime($streamWrapperAKey);
$stats['modifiedA delta'] = $stats['modifiedA'] - $stats['created'];
$stats['modifiedB'] = filemtime($streamWrapperBKey);
$stats['modifiedB delta'] = $stats['modifiedB'] - $stats['created'];

var_dump($stats);

//array (size=5)
//  'created' => int 1554126000
//  'modifiedA' => int 1554126000
//  'modifiedA delta' => int 0
//  'modifiedB' => int 1554126010
//  'modifiedB delta' => int 10
```

Note that I just used two separate stream wrappers to make the issue reproducible easily. The problem also exists when using only one stream wrapper and a long living cache.

I would be happy to prepare a pull request that clears the stream wrapper cache after a copy operation. However I do not know how this could be cleanly implemented as the `S3Client` does not seem to be aware of any registered stream wrappers.

**Comment by diehlaws** [comment]
Hi @maechler, thanks for reaching out to us. S3 Stream Wrappers unfortunately are not aware of actions taken against S3 resources outside of the stream wrapper even if these actions are performed with the same client with which the stream wrapper has been registered, or another stream wrapper registered with the same client. As a result, if you are using a long running cache like you have suggested it would be best to use the same stream wrapper for any operations involving resources with which this stream wrapper is interacting.

Was the `copyObject` in your example used due to a lack of a proper `copy` function available for the S3 Stream Wrapper? Or was it merely used to illustrate any action taken by a given S3 client outside of the registered stream wrapper? Knowing more details about your use case would help us better understand your pain point to take appropriate action on this.

**Comment by maechler** [comment]
Thanks @diehlaws for your response! I discovered this issue because we use `t3ext-fal_s3`, which depends on `aws-sdk-php`. See also https://github.com/MaxServ/t3ext-fal_s3/issues/49 
I have to admit I am not entirely sure why `copyObject` is used there, to me it looks like it is used to update metadata in the S3 bucket. It is used within a method called `updateCacheControlDirectivesForRemoteObject`. Maybe @arnoschoon can join the discussion and help us out here?

Nevertheless it would be nice if this could also be addressed within `aws-sdk-php` itself.

**Comment by macjohnny** [comment]
@diehlaws do you need any further information?

**Comment by arnoschoon** [comment]
Hi Markus, Esteban and Alex,

Please refer to https://github.com/MaxServ/t3ext-fal_s3/issues/49 for an explanation for the use of the `copyObject` method outside of the stream wrapper.

I wasn't able to find a way to (reliably) set the objects' metadata through the stream wrapper, so we chose that (possibly unconventional) option.
