### ISSUE TITLE
SDK v2.6.9 and Signature v4

### ISSUE THREAD

**Issue by crazyfree** [aws/aws-sdk-php#1759]
Hi,
Hope you are doing well.

I have a question, i am using SDK v2.6.9 and i heard about signature v2 will be deprecated on June 24.
I've changed signature to v4 by adding signature when creating an instance
```
S3Client::factory(array(
    'key' => $key,
    'secret' => $secret,
    'region' => $region,
    'signature' => 'v4',
));
```
But i also saw a table, that told me have to [update SDK to v3 to adopt the signature v4](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html#UsingAWSSDK-move-to-Sig4). It make me confused, because i am using SDK v2 and also can send v4 signature to server by the code piece above.
My system was made from 2013 so, it's really heavy and difficult to change

So my question is: Do I have to change SDK to v3? or can continuously using SDK v2?

Thank you for reading and answer

**Comment by diehlaws** [comment]
Thanks for reaching out to us @crazyfree. Version 2 of the AWS SDK for PHP does support signing requests using Signature Version 4 by including the `signature` parameter in the client configuration as you've shown, so an upgrade to version 3 is not required to continue interacting with S3 once Signature Version 2 has been deprecated. 

That being said, we do recommend upgrading to version 3 of the AWS SDK for PHP if you need to use features implemented after [the most recent 2.x release](https://github.com/aws/aws-sdk-php/blob/master/CHANGELOG.md#287---2015-05-26) of the SDK.

**Comment by crazyfree** [comment]
Thank you for the answer, very clear. 
Please close this.
