### ISSUE TITLE
[DOC] SesClient::sendRawEmail needs clear details about base64 changes on upgrade doc

### ISSUE THREAD

**Issue by igorsantos07** [aws/aws-sdk-php#1761]
This is directly related to #1295.

I've spent a good deal of time in a simple upgrade from v2 to v3 exactly because of the base64 encoding change; this change is _not_ highlighted on the upgrading docs and it should be!
The error received if the developer doesn't remove the `base64_encode()` from their own code is completely unrelated - it complains about the lack of `From:`, while probably the entire message is garbage for the SDK.

Please, update the [migration guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/getting-started_migration.html) to v3!

**Comment by srchase** [comment]
@rquadling Opened a PR to get this mentioned on that upgrade guide.

**Comment by rquadling** [comment]
Hi @srchase , I'm not sure I did. :-)

**Comment by srchase** [comment]
@rquadling 

Sorry to @ you!

I opened the PR and meant to notify @igorsantos07.  It's been merged and released, so closing this out.

**Comment by rquadling** [comment]
NP.
