### ISSUE TITLE
S3 Multipart Upload php://input stream bug

### ISSUE THREAD

**Issue by LC-DirkPritchard** [aws/aws-sdk-php#1767]
- issue: Using the `php://input` resource stream the first chunk of data (5242880 bytes) is lost on a multipart upload automatically initiated for large files
- PHP version: 7.2
- environment: Laravel Homestead (v7.20.0) running on Virtualbox (v5.2.18) via Vagrant (v2.1.4)
- file: aws-sdk-php/src/S3/ObjectUploader.php
- function: requiresMultipart()
- line number: 126

- relevant stack trace: 
    ```#0  Aws\S3\ObjectUploader->requiresMultipart() called at 
    [/home/vagrant/code/vendor/aws/aws-sdk-php/src/S3/ObjectUploader.php:66]
    #1  Aws\S3\ObjectUploader->promise() called at [/home/vagrant/code/vendor/aws/aws-sdk- 
   php/src/S3/S3ClientTrait.php:48]
    #2  Aws\S3\S3Client->uploadAsync() called at [/home/vagrant/code/vendor/aws/aws-sdk- 
   php/src/S3/S3ClientTrait.php:33]
    #3  Aws\S3\S3Client->upload() called at [/home/vagrant/code/vendor/league/flysystem-aws- 
   s3-v3/src/AwsS3Adapter.php:597]
    #4  League\Flysystem\AwsS3v3\AwsS3Adapter->upload() called at 
    [/home/vagrant/code/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php:380]
    #5  League\Flysystem\AwsS3v3\AwsS3Adapter->writeStream() called at 
    [/home/vagrant/code/vendor/league/flysystem/src/Filesystem.php:122]
    #6  League\Flysystem\Filesystem->putStream()/```


details:  when providing a `fopen('php://input')` stream resource to `S3Client->uploadAsync()` the function requiresMultipart() moves the streams pointer to determine if it should be a multipart upload or not. The issue is the if statement here...

```php
        // If body >= 5 MB, then use multipart. [YES]
        if ($body->isSeekable()) {
            // If the body is seekable, just rewind the body.
            $body->seek(0);
        } else {
            // If the body is non-seekable, stitch the rewind the buffer and
            // the partially read body together into one stream. This avoids
            // unnecessary disc usage and does not require seeking on the
            // original stream.
            $buffer->seek(0);
            $body = new Psr7\AppendStream([$buffer, $body]);
        }
```

...fails to set the pointer back to position 0. The cause of this is a quirk in PHP itself and php://input. When opening php://input the stream begins as seekable as reflected in the metadata. After interacting with it however, it is no longer seekable (unless one were to open another `php://input` stream and restart reading. However this does not work for certain request methods such as PUT). The fact that the stream is no longer seekable is not reflected in the metadata. Becasue of this the `$body->isSeekable()` check returns true, `$body->seek(0)` does nothing, and the first 5242880 bytes of data are lost, resulting in corrupted files.

reproduction steps:
1. `fopen()` a `php://input` stream containing > 5242880 (if using the default settings)
2. use `upload()` off of an `S3Client` with the $body parameter being the input stream from step 1
3. in the s3 bucket compare size of upload to the original input. it should be missing the first chunk of data.

suggested fix:
Change the if statement to the following:
```php
        // If body >= 5 MB, then use multipart. [YES]
        if ($body->isSeekable() && $body->getMetadata('uri') !== 'php://input') {
            // If the body is seekable, just rewind the body.
            $body->seek(0);
        } else {
            // If the body is non-seekable, stitch the rewind the buffer and
            // the partially read body together into one stream. This avoids
            // unnecessary disc usage and does not require seeking on the
            // original stream.
            $buffer->seek(0);
            $body = new Psr7\AppendStream([$buffer, $body]);
        }
```
This would drop into the else and allow the unseekable input stream to have the missing chunk appended to it; making it once again complete in spite of the falsehoods in the stream's metadata.

**Comment by LC-DirkPritchard** [comment]
[PR for suggested fix](https://github.com/aws/aws-sdk-php/pull/1768)

**Comment by srchase** [comment]
#1768 has been merged.  Fix will go out with next release.
