### ISSUE TITLE
getPaginator not returning all results?

### ISSUE THREAD

**Issue by karl-dessol** [aws/aws-sdk-php#1788]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
3.38.4

### Version of PHP (`php -v`)?
5.5.9

### What issue did you see?
This may be working as intended, or just simply my own ignorance (I have not seen any other issues to this end, so). However a bucket of ours which has ~105k objects (as reported through CloudWatch) seems to be only be returning ~46k objects through the getPaginator function.

The purpose of the script is to delete unused objects from the bucket. When I do this, the total number returned by the process does seem to reduce by that number (i.e., if it returned ~46500 and I delete 200, it will return ~46300 on the next run). However these figures are of course still below the total number as reported by the bucket.

The bucket is a versioned bucket but versioning is suspended and has never been enabled (files in the bucket do not show any versioning information).

There are no folders in the bucket (all simply root level files).

It's possible that there is simply a discrepancy between that returned by CloudWatch and getPaginator (i.e., ListObjects), but I have not been able to determine this.

Any help or pointers would be greatly appreciated.

### Steps to reproduce
It's essentially the same script in the example (https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_paginators.html), except it also includes some code to count the number of objects checked, which is returning less than the total objects in the bucket.

For reference, the actual script I am running looks like:

```php
use Aws\S3Client etc;
$s3 = new S3Client([
    'version' => 'latest',
    'region'  => $region, (i.e., eu-west-1)
    'credentials' => new Aws\Credentials\Credentials($accessKey, $secretKey),
    'debug', true
]);

$totalObjects = 0;

try {
    $results = $s3->getPaginator('ListObjects', [
        'Bucket' => $bucket
    ]);

    foreach ($results as $result) {
        foreach ($result['Contents'] as $object) {
            // Business Logic. Issue remains with or without this.
            $totalObjects++;
        }
    }
}

// Prints "Finished searching ~46k objects";
echo "Finished searching $totalObjects objects\n";
```

### Additional context
No frameworks. Just a simple script I run from the command line.

**Comment by diehlaws** [comment]
Hi @karl-dessol, thanks for reaching out to us. The CloudWatch metric [`NumberOfObjects`](https://docs.aws.amazon.com/AmazonS3/latest/dev/cloudwatch-monitoring.html#s3-cloudwatch-metrics) includes the total number of objects stored in all storage classes except for Glacier, as well as the total number of parts for all incomplete multipart uploads to the bucket. If you are not receiving an error when using the paginator for `ListObjects` I suspect the paginator is working as expected and your bucket contains parts associated with incomplete multipart uploads that are showing up in CloudWatch but not in the `ListObjects` response. You can check your bucket for incomplete multipart uploads with [`ListMultiPartUploads`](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#listmultipartuploads) and check the parts present for these incomplete multipart uploads with [`ListParts`](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#listparts) using the `Key` and `UploadId` values from the output of your `ListMultiPartUploads` call.

Incomplete multipart uploads can be aborted with [`AbortMultipartUpload`](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#abortmultipartupload), however if you see that this bucket frequently ends up with incomplete multipart uploads you can create a [Lifecycle Configuration](https://docs.aws.amazon.com/AmazonS3/latest/dev/lifecycle-configuration-examples.html#lc-expire-mpu) to automatically clean up incomplete multipart uploads after a given number of days.

**Comment by karl-dessol** [comment]
That makes sense. I had a hunch there was a discrepancy, but I felt like I was going in circles a little bit trying to determine what it was.

It will likely just be the incomplete multipart I think. The original developer on this didn't clean these up at all and everything is just in the standard tier. I'll add a Lifecycle rule for them and hopefully that should clear up some of these unused objects.

Thanks again.
