### ISSUE TITLE
You are submitting requests too quickly. Please retry your requests at a slower rate

### ISSUE THREAD

**Issue by akbet** [aws/aws-sdk-php#1796]
Hello

Please help

We  use Amazon  Product Advertising API.

Last time very many our users wrote about error:
"You are submitting requests too quickly. Please retry your requests at a slower rate"
This error not depend is this first request per day or not.

We check manual from here, and created test page - it also returned same error:
https://docs.aws.amazon.com/AWSECommerceService/latest/DG/rest-signature.html

We created tested page: 
https://www.marvelousmessages.com/test.php 
We try another code example from https://www.patchesoft.com/amazon-affiliate-api-php
Error same ...

Regards
Andrew

**Comment by diehlaws** [comment]
Hi @akbet, thanks for reaching out to us. Unfortunately the AWS SDK for PHP does not implement a service client that interacts with the Amazon Product Advertising API, as a result this request falls outside of the scope for this GitHub repository.

That being said, the error returned by your application suggests that you are exceeding the allowed request rate for this service. I suggest reviewing the [Product Advertising API efficiency guidelines](https://docs.aws.amazon.com/AWSECommerceService/latest/DG/TroubleshootingApplications.html#efficiency-guidelines) to ensure your application does not issue more requests per second than what is allowed per the service's documentation. Your application may benefit from implementing [exponential backoff and random jitter](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/) when retrying requests that return a `RequestThrottled` exception.
