### ISSUE TITLE
Textract improving results

### ISSUE THREAD

**Issue by Kojji** [aws/aws-sdk-php#1808]
Hi, I've been using Textract since the beginning of the month,
I've been running some tests, and i've found out that some images are more difficult to get a clear reading than others, reason being brightness, size of letters, contrast between background and letters, image size(width and height).
Now i'm wondering ... Is there any kind of peculiar image pre proccessing that would give me a clearer reading, or if general image pre processing stuff like reduce noise, aplly transformations in color to make the text more visible... so on, would do?

**Comment by Kojji** [comment]
I've just seeing this page for [best practices](https://docs.aws.amazon.com/textract/latest/dg/textract-best-practices.html), but i was wondering if there are anything else that i should take into consideration.

**Comment by diehlaws** [comment]
Thanks for reaching out to us @Kojji. Please keep in mind this repository is for the AWS SDK for PHP, so this is not the best avenue for seeking guidance on using a specific service outside of the context of interacting with the service using the AWS SDK for PHP. I recommend visiting the [AWS Forums for Textract](https://forums.aws.amazon.com/forum.jspa?forumID=338) or reaching out to our Premium Support team by opening a [new support case](https://console.aws.amazon.com/support/cases#/create) under the Textract service as they will have more intimate knowledge of how the service works and what can be done to improve text recognition on the images you provide to the service.
