### ISSUE TITLE
 File uploading more than 5G error

### ISSUE THREAD

**Issue by s092568962** [aws/aws-sdk-php#1811]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
V3

### Version of PHP (`php -v`)?
7.3

### What issue did you see?

Fatal error: Uncaught Error: Class 'Aws\Exception\CredentialsException' not found in /www/wwwroot/yzm/vendor/aws/aws-sdk-php/src/Credentials/CredentialProvider.php:486 Stack trace: #0 /www/wwwroot/yzm/vendor/aws/aws-sdk-php/src/Credentials/CredentialProvider.php(305): Aws\Credentials\CredentialProvider::reject(''default' not f...') #1 /www/wwwroot/yzm/vendor/aws/aws-sdk-php/src/Middleware.php(121): Aws\Credentials\CredentialProvider::Aws\Credentials\{closure}() #2 /www/wwwroot/yzm/vendor/aws/aws-sdk-php/src/RetryMiddleware.php(264): Aws\Middleware::Aws\{closure}(Object(Aws\Command), Object(GuzzleHttp\Psr7\Request)) #3 /www/wwwroot/yzm/vendor/aws/aws-sdk-php/src/Middleware.php(206): Aws\RetryMiddleware->__invoke(Object(Aws\Command), Object(GuzzleHttp\Psr7\Request)) #4 /www/wwwroot/yzm/vendor/aws/aws-sdk-php/src/S3/S3EndpointMiddleware.php(102): Aws\Middleware::Aws\{closure}(Object(Aws\Command), Object(GuzzleHttp\Psr7\Request)) #5 /www/wwwroot/yzm/vendor/aws/aws-sdk-php/src/Middleware.php(238): Aws\S3\S3EndpointMiddleware-> in /www/wwwroot/yzm/vendor/aws/aws-sdk-php/src/Credentials/CredentialProvider.php on line 486

### Steps to reproduce
If you have a runnable example, please include it as a snippet or link to a repository/gist for larger code examples.

### Additional context
Any additional information relevant to the issue. Examples include any framework you may be using (e.g. Laravel, Wordpress) in conjunction with the AWS SDK for PHP, or PHP/environment config settings if the issue is related to memory or performance.

**Comment by srchase** [comment]
@s092568962 

Thanks for opening this issue.

Which specific version of the SDK are you using?

If you're using composer, you can run the following to get details on the installed version of the SDK:
```
composer show aws/aws-sdk-php
```

**Comment by s092568962** [comment]
name     : aws/aws-sdk-php
descrip. : AWS SDK for PHP - Use Amazon Web Services in your PHP project
keywords : amazon, aws, cloud, dynamodb, ec2, glacier, s3, sdk
versions : * 3.93.5
type     : library
license  : Apache License 2.0 (Apache-2.0) (OSI approved) https://spdx.org/licenses/Apache-2.0.html#licenseText
source   : [git] https://github.com/aws/aws-sdk-php.git e9cfeb39ad6bc7c9ead2a40ce4fc23029ff1e17a
dist     : [zip] https://api.github.com/repos/aws/aws-sdk-php/zipball/e9cfeb39ad6bc7c9ead2a40ce4fc23029ff1e17a e9cfeb39ad6bc7c9ead2a40ce4fc23029ff1e17a
names    : aws/aws-sdk-php

autoload
psr-4
Aws\ => src/
files

requires
ext-json *
ext-pcre *
ext-simplexml *
guzzlehttp/guzzle ^5.3.3|^6.2.1
guzzlehttp/promises ~1.0
guzzlehttp/psr7 ^1.4.1
mtdowling/jmespath.php ~2.2
php >=5.5

requires (dev)
andrewsville/php-token-reflection ^1.4
aws/aws-php-sns-message-validator ~1.0
behat/behat ~3.0
doctrine/cache ~1.4
ext-dom *
ext-openssl *
ext-pcntl *
ext-sockets *
nette/neon ^2.3
phpunit/phpunit ^4.8.35|^5.4.3
psr/cache ^1.0
psr/simple-cache ^1.0

suggests
aws/aws-php-sns-message-validator To validate incoming SNS notifications
doctrine/cache To use the DoctrineCacheAdapter
ext-curl To send requests using cURL
ext-openssl Allows working with CloudFront private distributions and verifying received SNS messages
ext-sockets To use client-side monitoring

**Comment by diehlaws** [comment]
Thanks for the additional information @s092568962, and I do apologize for the long delay in response from our end. Unfortunately I have not been able to reproduce this on my end, however looking at the provided stack trace it appears the SDK is not able to locate valid credentials for your S3 client. Seeing [debug logs](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#debug) for your request as well as a code sample showing how the S3 client is being initialized and how your object upload is being executed would allow us to better understand how you're interacting with S3 using the AWS SDK for PHP so we can better troubleshoot this behavior.
