### ISSUE TITLE
S3 putObject Memory Leak

### ISSUE THREAD

**Issue by rnjailamba** [aws/aws-sdk-php#1816]
### Version of AWS SDK for PHP
3.99.4

### Version of PHP (`php -v`)? 
5.6.37

### What issue did you see?
Continuous increase in ram on an ec2 instance. https://i.imgur.com/tJdzmJy.png
I need to restart the php application to reduce memory usage but it increases continuously.
Removing all S3 sdk code from the application makes the memory usage non increasing.

### Steps to reproduce
https://gist.github.com/rnjailamba/fd4a87c68ef263ac967994bddbbd99c3

### Additional context
Some data from memory profiler is - https://i.imgur.com/4PIAGEb.png
Also using gc_collect_cycles() provided no noticeable improvement.

**Comment by srchase** [comment]
@rnjailamba 

The SDK requires PHP 5.5.0 or later.

Is that the correct version number?

**Comment by rnjailamba** [comment]
@srchase im sorry just updated my mistake. It is actually 5.6.37.

**Comment by srchase** [comment]
Thanks for following up.

Have you run [compatibility-test.php](https://github.com/aws/aws-sdk-php/blob/master/compatibility-test.php)?

**Comment by rnjailamba** [comment]
@srchase yes i ran it on a browser and got an empty page.

**Comment by srchase** [comment]
@rnjailamba 

Can you run it on the command line?

```php compatibility-test.php```

**Comment by rnjailamba** [comment]
@srchase  here is the output of the compatibility test - https://pastebin.com/LbxgXwaU

**Comment by diehlaws** [comment]
Thanks for the additional info @rnjailamba. Unfortunately I haven't been able to reproduce this behavior on a t2.micro EC2 instance with PHP 5.6 - I ran your `saveResourcesToS3` function in a loop (full repro code available [here](https://gist.github.com/diehlaws/29e7ac52108573cd12fd878a544fd484)) and found that memory usage remained at 7680 kb after the second iteration of the loop as long as `gc_collect_cycles` is called between each `PutObject` operation.

```bash
$ php -v
PHP 5.6.40-8+ubuntu18.04.1+deb.sury.org+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
$ BUCKETNAME=alex-sdk php repro.php 
Uploaded object php/1816/upload0	Memory used: 5632 kb
Memory usage changed at iteration 0!
Uploaded object php/1816/upload1	Memory used: 6656 kb
Memory usage changed at iteration 1!
Uploaded object php/1816/upload2	Memory used: 7680 kb
Memory usage changed at iteration 2!
Uploaded object php/1816/upload3	Memory used: 7680 kb
Uploaded object php/1816/upload4	Memory used: 7680 kb
Uploaded object php/1816/upload5	Memory used: 7680 kb
Uploaded object php/1816/upload6	Memory used: 7680 kb
Uploaded object php/1816/upload7	Memory used: 7680 kb
[...]
Uploaded object php/1816/upload363896	Memory used: 7680 kb
Uploaded object php/1816/upload363897	Memory used: 7680 kb
Uploaded object php/1816/upload363898	Memory used: 7680 kb
^C
```

I do see in your gist that the `garbageCollectionForce` function that runs `gc_collect_cycles` is commented out in both locations in which it is called - are you seeing the described behavior when these lines are uncommented as well?
