### ISSUE TITLE
Can't get bucket region

### ISSUE THREAD

**Issue by dkaraatanasov** [aws/aws-sdk-php#1823]
I'm using your REST API and I'm trying to get bucket region but without any success. Every time when I'm trying to do that I get the exact same error - 400 Bad Request (error code: AuthorizationHeaderMalformed). No matter what I do I get this error. When I parse the response I'm able to see that the region is there. My question is why does that happen? We have an error but at the same time, we can get the region. 

One more question:  What I should do in order to get a normal response and not 400 Bad Request? Can you give me some advice? 
```
* Closing connection 0
*   Trying 52.218.244.186...
* TCP_NODELAY set
* Connected to servmasltest123455.s3.amazonaws.com (52.218.244.186) port 80 (#0)
> GET /?location HTTP/1.1
Host: servmasltest123455.s3.amazonaws.com
Accept: */*
User-Agent: All-in-One WP Migration
x-amz-date: 20190617T121859Z
x-amz-content-sha256: signature

< HTTP/1.1 400 Bad Request
< x-amz-request-id: B391493327CE3B63
< x-amz-id-2: x-amz-id
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Date: Mon, 17 Jun 2019 12:18:59 GMT
< Connection: close
< Server: AmazonS3
```

**Comment by diehlaws** [comment]
Hi @dkaraatanasov, thanks for reaching out to us. Seeing the full [debug log](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#debug) for this request would help us better understand why you're receiving an `AuthorizationHeaderMalformed` exception when attempting to issue a GET Bucket location call to S3.

The `User-Agent` request header in the provided output suggests this is occurring with the WordPress plugin [All-in-One WP Migration](https://wordpress.org/plugins/all-in-one-wp-migration/), which falls beyond the scope of our support in this GitHub repository. If you are an end user of this WordPress plugin I suggest opening a new support thread under the plugin's [Support](https://wordpress.org/support/plugin/all-in-one-wp-migration/) page, however if you are a developer of this plugin and need assistance integrating the AWS SDK for PHP with your plugin please provide a code sample showing how the S3 client is being initialized and how the `GetBucketLocation` command is being executed so we can reproduce your scenario more accurately and further investigate this behavior.

**Comment by dkaraatanasov** [comment]
Yes, indeed I'm a developer. I'm developing a custom plugin without using the AWS SDK for PHP. 
From your SDK I'm able to see this:
```
public function determineBucketRegionAsync($bucketName)
    {
        $command = $this->getCommand('HeadBucket', ['Bucket' => $bucketName]);
        $handlerList = clone $this->getHandlerList();
        $handlerList->remove('s3.permanent_redirect');
        $handlerList->remove('signer');
        $handler = $handlerList->resolve();
        return $handler($command)
            ->then(static function (ResultInterface $result) {
                return $result['@metadata']['headers']['x-amz-bucket-region'];
            }, function (AwsException $e) {
                $response = $e->getResponse();
                if ($response === null) {
                    throw $e;
                }
                if ($e->getAwsErrorCode() === 'AuthorizationHeaderMalformed') {
                    $region = $this->determineBucketRegionFromExceptionBody(
                        $response
                    );
                    if (!empty($region)) {
                        return $region;
                    }
                    throw $e;
                }
                return $response->getHeaderLine('x-amz-bucket-region');
            });
    }
```
As you see there is a code which checks for error code 'AuthorizationHeaderMalformed' and from there you get the region. The question is why? And is this the correct way to get bucket region?

**Comment by diehlaws** [comment]
Thanks for the additional information! Please keep in mind that issues in this repository are intended to cover problems with the AWS SDK for PHP - questions about using the REST API for a given service outside of the context of the AWS SDKs are more appropriate to post in the [AWS Forums](https://forums.aws.amazon.com/index.jspa) or on StackOverflow.

That being said, the `determineBucketRegionAsync` function you mention has a case to handle `AuthorizationHeaderMalformed` exceptions just in case the `Authorization` header created during the SigV4 signing process for the [GET Bucket Location](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETlocation.html) API call is not properly calculated - this case triggers the function `determineBucketRegionFromExceptionBody` which parses the XML document in the response body for this exception to retrieve its `Region` value. The correct way to get the region of a bucket is to issue a GET Bucket Location call with a correctly calculated SigV4 signature and retrieve the region name from the response body's `LocationConstraint` value.

Receiving an `AuthorizationHeaderMalformed` exception could be the result of a number of things revolving around the SigV4 signature not being calculated correctly, including the credentials involved in the request being incorrect (or missing altogether), or the region used to sign the request not matching the region to which the request is being sent. For more information regarding signing S3 requests with SigV4 I suggest reviewing [this portion](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html) of S3's API reference documentation.
