### ISSUE TITLE
Retry on TooManyRequestsException

### ISSUE THREAD

**Issue by teohhanhui** [aws/aws-sdk-php#1825]
### Is this related to a problem?
Some actions in Cognito return the `TooManyRequestsException` error.

### Feature description
`RetryMiddleware` should handle the `TooManyRequestsException` error.

### Describe alternatives you've considered
* It's impossible to pass custom `$additionalRetryConfig` through the `AwsClient` constructor `$args`.
* It's impossible to modify the `$additionalRetryConfig` on the registered `RetryMiddleware` ("retry").
* It's impossible to retrieve the registered "retry" middleware.
* It's impossible to replace the registered "retry" middleware by the same name.
* It's impossible to access the `AwsClient` constructor `$args` in order to correctly configure a replacement `RetryMiddleware`.

### Additional context
* https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ListUsers.html#API_ListUsers_Errors
* https://docs.aws.amazon.com/cognito/latest/developerguide/limits.html#limits-soft
* https://github.com/aws/aws-sdk-php/blob/3.100.7/src/ClientResolver.php#L390-L399
* https://github.com/aws/aws-sdk-php/pull/1672

**Comment by howardlopez** [comment]
Thanks for bringing this up. `TooManyRequestsException` is being added in #1827.
