### ISSUE TITLE
Athena StartQueryExecution ignores workgroup configuration

### ISSUE THREAD

**Issue by leslieascott** [aws/aws-sdk-php#1828]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
3.54.0

### Version of PHP (`php -v`)?
7.2.19

### What issue did you see?
I am sending a request from our php application to our aws athena account. We had set up a workgroup about a month ago, and successfully tested sending the request, querying Athena in the correct workgroup, and storing the results in S3. However, I've recently noticed that our query doesn't use our workgroup anymore, it uses the primary workgroup. I've tried using invalid values for the workgroup, wanting to see the request fail, but it still successfully ran the query with the primary workgroup. When I look in our cloudtrail logs for the event today vs at the beginning of the month, the workgroup is missing from the request parameters. I am guessing that the workgroup is not being send along anymore.

### Steps to reproduce

PHP Athena Request
```
  $result = $this->athena->startQueryExecution([
            'QueryExecutionContext' => [
                'Database' => 'selfaudit',
            ],
            'QueryString' => 'SELECT * FROM audittrail',
            'ResultConfiguration' => [
                'EncryptionConfiguration' => [
                    'EncryptionOption' => 'SSE_S3'
                ],
                'OutputLocation' => 's3://selfaudit-results/' ,
            ],
            'WorkGroup' => 'sandbox-selfaudit',
        ]);
```

The request parameters from our view event in CloudTrail
```
"requestParameters": {
	"queryString":"SELECT * FROM audittrail",
	"clientRequestToken": "0abf8efa-d8bc-4178-ad21-772c6ee059bf",
	"queryExecutionContext": {
	    "database": "selfaudit"
	},
	"resultConfiguration": {
	    "outputLocation": "s3://selfaudit-results/" ,
	    "encryptionConfiguration": {
	        "encryptionOption": "SSE_S3"
	    }
	}
},
```

compared with the same request but from the beginning of the month:
```
    "requestParameters": {
	"queryString": "SELECT * FROM audittrail",
        "clientRequestToken": "e70fce0c-b05d-4539-851b-2cec8f814066",
        "queryExecutionContext": {
            "database": "selfaudit"
        },
        "resultConfiguration": {
            "outputLocation": "s3://selfaudit-results/" ,
        },
        "workGroup": "sandbox-selfaudit"
    },
```

**Comment by diehlaws** [comment]
Hi @leslieascott, thanks for reaching out to us. Which client was used for the second `startQueryExecution` CloudTrail event you provided that includes the workgroup inside of `requestParameters`? Per our [changelog](https://github.com/aws/aws-sdk-php/blob/master/CHANGELOG.md#38713---2019-02-18) support for Athena Workgroups was added to the AWS SDK for PHP in version 3.87.13, so this parameter is not expected to work in versions earlier than that.

Using version 3.100.0 of the AWS SDK for PHP, I'm able to see the WorkGroup parameter included in the request body of a `startQueryExecution` request when I enable [debug logging](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#debug) for the service client, however when using 3.54.0 of the SDK this parameter is not present in the request body for the same request. Do you see this behavior when updating the AWS SDK for PHP to version 3.87.13 or higher?

**Comment by leslieascott** [comment]
It was the same client.. Something might have gotten screwed up on my end. That's why I thought there was an issue, since we hadn't changed anything on our side with infrastructure. I will try upgrading tomorrow and test it out. Sorry! I shall close this issue. Thanks.
