### ISSUE TITLE
Cannot read credentials from /usr/share/httpd/.aws/credentials

### ISSUE THREAD

**Issue by zorangagic** [aws/aws-sdk-php#1840]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
3.104.1 

### Version of PHP (`php -v`)?
PHP 7.3.7 on Centos 7.6

### What issue did you see?
On linux bash prompt I can use AWS CLI and I can perform 'php describe.php' and it uses AWS credentials in (~/.aws/credentials) to list all my EC2 instances. Yet when I try to use my browser to get output from describe.php it fails with error:
Fatal error:  Uncaught Aws\Exception\CredentialsException: Cannot read credentials from /usr/share/httpd/.aws/credentials in /var/www/html/vendor/aws/aws-sdk-php/src/Credentials/CredentialProvider.php:611

I have tried setting the HOME environment variable in httpd.conf: setenv home /usr/share/httpd.

Here is my PHP code:
<?php
require 'vendor/autoload.php';
use Aws\Ec2\Ec2Client;

$ec2Client = new Aws\Ec2\Ec2Client([
    'region' => 'ap-southeast-2',
    'version' => 'latest',
    'profile' => 'default'
]);
$result = $ec2Client->describeInstances();
exit(0);

It seems that there is problem accessing the ~/.aws/credentials file as I could not even perform:
echo exec('ls -l /usr/share/httpd/.aws/credentials');
echo "<br>";
echo exec('cat /usr/share/httpd/.aws/credentials');

Thanks for any help, Zoran

**Comment by srchase** [comment]
@zorangagic 

What error do you get with the ```echo exec...``` commands?  This looks like a permission issue and not anything with the SDK.  Once you're able to execute the ```echo exec``` commands, the SDK should also be able to read the ```credentials``` file from that location.

**Comment by zorangagic** [comment]
Thanks for the feedback. I could not execute exec('ls -l /usr/share/httpd/.aws/credentials'); 

After checking selinux log /var/log/audit/audit.log I could see this was denied by selinux. I tested this with setenforce 0 and then everything worked...so the issue was with selinux. Thanks for your help!
