### ISSUE TITLE
s3 upload - uploads a file with 0 bytes length

### ISSUE THREAD

**Issue by aghan** [aws/aws-sdk-php#1851]
Hello All,

I'm using the AWS SDK (version 3.54) to upload pdf files to a S3 bucket. Usually, it works fine but in some random cases (apparently), it creates an empty file on s3 which is of 0 bytes. Whereas locally the file has a proper and expected length. Could you please help me out? The result of the API call is a 200 always. Below is my code:

```
$s3 = new S3Client(
      [
        "credentials" => [
         "key" => 'xxxx',
          "secret" => "xxxx"
        ],
        "version" => "latest",
        "region"  => "xxxx",
      ]
    );

  if (isset($this->s3folder)) {
        $key = $this->s3folder . "/" . $filename;
      }
      else {
        $key = $filename;
      }
      // Upload an object to Amazon S3
      $result = $s3->putObject([
        "Bucket" => $bucketName,
        "Key"    => $key,
        "Body"   => $body,
      ]);
```

**Comment by diehlaws** [comment]
Hello @aghan, thanks for reaching out to us. While version 3.54 of the AWS SDK for PHP is fairly old, this should not impact your ability to upload objects to S3 with the appropriate length. That being said, the following information would help us better troubleshoot the behavior you're seeing:

1. Unfortunately it is not clear how your `$body` variable is being initialized, I'm guessing something along the lines of `fopen($filename, 'r');` is being used but I'd like to confirm how this is being done. 
2. Enabling [debug logging](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#debug) in the service client and providing the debug output for a PutObject call that returns an OK 200 response but uploads a 0-byte object would allow us to see more details about the interaction between the SDK and S3. 
3. How are you checking the size of the object in S3 once it has been uploaded? 
4. Printing the size of the file being used to populate your `$body` (e.g. using `filesize($filename)`) before the PutObject call takes place would help confirm that PHP is able to read the file's contents as expected and would help rule out potential environment related issues.

**Comment by bkarv** [comment]
@aghan have found a solution? I am having the same issue in my angular project when using the safari browser. Chrome no issues.

**Comment by aghan** [comment]
@bkarv Nope, I haven't found anything yet. Do let me know if you have any updates too.

**Comment by bkarv** [comment]
@aghan  I found the problem it is do with with Service workers being enabled in Angular. For some reason it causes the issue. If you are like me I only run service workers in production only hence why I was getting random cases (ie upload works in dev mode). To fix the problem you have to bypass the service worker on upload. I still haven't worked this out but please my comments in this link below for further information. If you do figure out a way to bypass service workers for S3 calls please let me know. https://github.com/aws/aws-sdk-js/issues/2738

**Comment by bkarv** [comment]
@aghan I have a solution now. See link:
https://github.com/aws/aws-sdk-js/issues/2738#issuecomment-523779919

**Comment by aghan** [comment]
Thanks @bkarv , Glad you found a solution. Though, my issue was with the AWS PHP library.

**Comment by shudhanshu-projects** [comment]
@aghan did you find the solution for the problem related to your AWS PHP SDk?

**Comment by JefferyHus** [comment]
I am having the same issue right now.

**Comment by xclydes** [comment]
I was experiencing this same issue. It turned out to be a combination of insufficient IAM permissions and the bucket's public access settings need to be adjusted.
![image](https://user-images.githubusercontent.com/1414724/99917615-5fb5a100-2cdf-11eb-8b7b-9b809c8404d5.png)
![image](https://user-images.githubusercontent.com/1414724/99917579-2ed56c00-2cdf-11eb-82bd-86d07046d5e3.png)

These settings currently work for me along with a `cloudfront` url for rewriting.

**Comment by ajredniwja** [comment]
Hi there is this still an issue with the latest version of the SDK?

**Comment by goplinto** [comment]
I had the same issue and I was setting the "SourceFile" or the "File" param. But The "Body" param needs to be set as the content to be uploaded to S3

          ```
 //write content to the S3 object / file
            $result = $s3Client->putObject([
                    "Bucket" => $s3BucketName,
                    "Key" => $fileName,
                    "Body" => $content,
            ]);
```

This worked for me and now I am generating non-empty files on S3 bucket
