### ISSUE TITLE
Textract PHP SDK: while analyzeDocument cURL timeout. 

### ISSUE THREAD

**Issue by immoien** [aws/aws-sdk-php#1855]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
Latest Version

### Version of PHP (`php -v`)?
PHP 7.2.19

### What issue did you see?

Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28: (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in phar:///var/www/html/healthplix/ehr/aws.phar/GuzzleHttp/Handler/CurlFactory.php:185 Stack trace: #0 phar:///var/www/html/healthplix/ehr/aws.phar/GuzzleHttp/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 phar:///var/www/html/healthplix/ehr/aws.phar/GuzzleHttp/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 phar:///var/www/html/healthplix/ehr/aws.phar/GuzzleHttp/Handler/CurlMultiHandler.php(181): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 phar:///var/www/html/healthplix/ehr/aws.phar/GuzzleHttp/Handler/CurlMultiHandler.php(110): GuzzleHttp\Ha in phar:///var/www/html/healthplix/ehr/aws.phar/GuzzleHttp/Handler/CurlFactory.php on line 185

### Steps to reproduce
use Aws\Textract\TextractClient;

$textract_client = new TextractClient([
	'version' => 'latest',
      'region'  => '<##>',
	'service_name' => 'textract',
      'endpoint_url' => '<##>',
      'aws_access_key_id' => '<##>',
      'aws_secret_access_key' => '<##>',
      'curl.options' => array(
         CURLOPT_CONNECTTIMEOUT => 5,
         CURLOPT_TIMEOUT => 10,
     )
]);

$result = $textract_client->analyzeDocument([
  'Document' => ['Bytes' => (doc url | base64 | binary)],
  'FeatureTypes' => ['TABLES']
]);

### Additional context
I used the python SDK, working very fine.

**Comment by diehlaws** [comment]
Hi @immoien, thanks for reaching out to us about this. Can you please provide the exact version of the AWS SDK for PHP that you're using when you encounter this problem?
When using version 3 of the AWS SDK for PHP you'll want to format your HTTP client's options as shown [here](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#config-http) instead of using the `'curl.options'` parameters that were used for V2 of the SDK. In addition to this, you don't need to specify the `'service_name'` parameter if you're initializing a named service client, nor do you need the `'endpoint_url'` parameter to use the standard endpoint for a given AWS service if you're specifying the region. That being said, I'm not able to reproduce the behavior you describe using the correct HTTP connection and read timeout config parameters for the service client as shown below.

```php
// Retrieving credentials from shared credentials file.
$client = new TextractClient([
    'region' => 'us-west-2',
    'version' => 'latest',
    'http' => [
        'timeout' => 10,
        'connect_timeout' => 5
    ]
]);
```

Unfortunately the error you've provided doesn't mention exacly what went wrong with the request (i.e. whether the client timed out connecting to the endpoint or timed out waiting for a response to the request once the connection was established), however it does appear to be consistent with a connection timeout. Are you running this code on an EC2 instance? If not, what is the geographical distance between the host running this code and the region you're using to interact with Textract?

As far as Boto3 working as expected, can you provide a code snippet showing how you're initializing the service client and how you're interacting with the service using that SDK? This will help us identify any differences in configuration/API calls between your usage of the AWS SDK for PHP and your usage of Boto3.

**Comment by immoien** [comment]
Hi @diehlaws, Thanks for the response. I'm using version 3 of the SDK. I'm running this on my local machine (in India).

Here is my code snippet
![Screenshot from 2019-07-30 11-41-01](https://user-images.githubusercontent.com/22579541/62105377-db583700-b2bf-11e9-82ab-060e736599c3.png)

and the error
![Screenshot from 2019-07-30 11-41-46](https://user-images.githubusercontent.com/22579541/62105429-f7f46f00-b2bf-11e9-8198-6ea99aa409ea.png)

**Comment by diehlaws** [comment]
Thanks for the additional information @immoien! Version 3 of the SDK encompasses minor versions ranging from 3.0.0 released on May 27 2015 to the current version 3.108.2 released yesterday (July 30 2019). If you're not sure which version you're using you can print the version being used in your script with `Aws\Sdk::VERSION` (e.g. `echo "Using AWS SDK for PHP version " . Aws\Sdk::VERSION . "\n";`). In addition to this, seeing a code snippet of the python script you're using that works as expected would help us identify any functional differences between the two to better understand the difference in behavior you're seeing between the two SDKs.

That being said, it sounds like your script is timing out on the host that it's running on, however it is unclear which portion of the request is timing out (establishing a connection to the service, waiting for a response after the request is sent successfully...). Does the SDK actually wait for the configured 40 seconds before it times out or does it appear to time out well before the timeout options specified in the service client's parameters? Can you try running this script on an EC2 instance to see if there is any difference in behavior? If you see this behavior both on your local host as well as on an EC2 instance can you provide the debug output for a request that times out as you describe for further review on our end? you can enable [debug logging](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#debug) by setting `'debug' => true` in your service client's options.

**Comment by vivekdbit** [comment]
I enabled debug status and i am getting following message,
Here under my code,
`require 'vendor/autoload.php';
   use Aws\SageMakerRuntime\SageMakerRuntimeClient;

	$client = new SageMakerRuntimeClient([
		'aws_access_key_id' => 'XXXXXXXXXx',
		'aws_secret_access_key' => 'XXXXXXXXXXXX',
	    'region' => 'ap-south-1',
	    'version' => 'latest',
	    'debug'   => true
	]);


	$data = json_encode(["instances" => [1.0,2.0,5.0]]);

 	$result = $client->invokeEndpoint([
	    'Accept' => 'application/json',
	    'Body' => $data, 
	    'ContentType' => 'application/json',
	    'CustomAttributes' => '',
	    'EndpointName' => 'https://runtime.sagemaker.ap-south-1.amazonaws.com/endpoints/XXXXXXXXXXXx/invocations', 
	]);

   print_r($result);`

Here under the error message

`-> Entering step init, name 'idempotency_auto_fill' --------------------------------------------------- command was set to array(3) { ["instance"]=> string(32) "00000000485a10f3000000006dfbe68c" ["name"]=> string(14) "InvokeEndpoint" ["params"]=> array(6) { ["Accept"]=> string(16) "application/json" ["Body"]=> string(21) "{"instances":[1,2,5]}" ["ContentType"]=> string(16) "application/json" ["CustomAttributes"]=> string(0) "" ["EndpointName"]=> string(115) "https://runtime.sagemaker.ap-south-1.amazonaws.com/endpoints/XXXXXXXXXX/invocations" ["@http"]=> array(1) { ["debug"]=> resource(4) of type (stream) } } } request was set to array(0) { } -> Entering step validate, name 'validation' -------------------------------------------- no changes -> Entering step build, name 'builder' -------------------------------------- request.instance was set to 00000000485a1071000000006dfbe68c request.method was set to POST request.headers was set to array(5) { ["X-Amz-Security-Token"]=> string(7) "[TOKEN]" ["Host"]=> array(1) { [0]=> string(42) "runtime.sagemaker.ap-south-1.amazonaws.com" } ["Accept"]=> array(1) { [0]=> string(16) "application/json" } ["Content-Type"]=> array(1) { [0]=> string(16) "application/json" } ["X-Amzn-SageMaker-Custom-Attributes"]=> array(1) { [0]=> string(0) "" } } request.body was set to {"instances":[1,2,5]} request.scheme was set to https request.path was set to /endpoints/https%3A%2F%2Fruntime.sagemaker.ap-south-1.amazonaws.com%2Fendpoints%2XXXXXXXXXXXXXXXXXXXX%2Finvocations/invocations -> Entering step build, name 'ApiCallMonitoringMiddleware' ---------------------------------------------------------- no changes -> Entering step build, name '' ------------------------------- request.instance changed from 00000000485a1071000000006dfbe68c to 00000000485a107b000000006dfbe68c request.headers.User-Agent was set to array(1) { [0]=> string(19) "aws-sdk-php/3.117.0" } -> Entering step build, name 'endpoint_parameter' ------------------------------------------------- no changes -> Entering step build, name 'EndpointDiscoveryMiddleware' ---------------------------------------------------------- no changes -> Entering step sign, name 'StreamRequestPayloadMiddleware' ------------------------------------------------------------ no changes -> Entering step sign, name 'invocation-id' ------------------------------------------- request.instance changed from 00000000485a107b000000006dfbe68c to 00000000485a1067000000006dfbe68c request.headers.aws-sdk-invocation-id was set to array(1) { [0]=> string(32) "679c96b44bcfafe7beeaa1ea65ba5efb" } -> Entering step sign, name 'retry' ----------------------------------- request.instance changed from 00000000485a1067000000006dfbe68c to 00000000485a1066000000006dfbe68c request.headers.aws-sdk-retry was set to array(1) { [0]=> string(3) "0/0" } <- Leaving step sign, name 'retry' ---------------------------------- error was set to array(6) { ["instance"]=> string(32) "00000000485a1020000000006dfbe68c" ["class"]=> string(37) "GuzzleHttp\Exception\ConnectException" ["message"]=> string(116) "cURL error 28: Connection timed out after 1001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)" ["file"]=> string(72) "/var/www/html/sagem/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php" ["line"]=> int(200) ["trace"]=> string(2801) "#0 /var/www/html/sagem/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 /var/www/html/sagem/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 /var/www/html/sagem/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(187): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 /var/www/html/sagem/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(116): GuzzleHttp\Handler\CurlMultiHandler->processMessages() #4 /var/www/html/sagem/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(131): GuzzleHttp\Handler\CurlMultiHandler->tick() #5 /var/www/html/sagem/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true) #6 /var/www/html/sagem/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn() #7 /var/www/html/sagem/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending() #8 /var/www/html/sagem/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList() #9 /var/www/html/sagem/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #10 /var/www/html/sagem/vendor/guzzlehttp/promises/src/Coroutine.php(65): GuzzleHttp\Promise\Promise->wait() #11 /var/www/html/sagem/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\Coroutine->GuzzleHttp\Promise\{closure}(true) #12 /var/www/html/sagem/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn() #13 /var/www/html/sagem/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #14 /var/www/html/sagem/vendor/guzzlehttp/promises/src/Coroutine.php(85): GuzzleHttp\Promise\Promise->wait(false) #15 /var/www/html/sagem/vendor/guzzlehttp/promises/src/Promise.php(273): GuzzleHttp\Promise\Coroutine->wait(false) #16 /var/www/html/sagem/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList() #17 /var/www/html/sagem/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #18 /var/www/html/sagem/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): GuzzleHttp\Promise\Promise->wait() #19 /var/www/html/sagem/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(86): Aws\AwsClient->execute(Object(Aws\Command)) #20 /var/www/html/sagem/test.php(26): Aws\AwsClient->__call('invokeEndpoint', Array) #21 {main}" } Inclusive step time: 1.0032839775085 <- Leaving step sign, name 'invocation-id' ------------------------------------------ no changes Inclusive step time: 1.0034601688385 <- Leaving step sign, name 'StreamRequestPayloadMiddleware' ----------------------------------------------------------- no changes Inclusive step time: 1.0035581588745 <- Leaving step build, name 'EndpointDiscoveryMiddleware' --------------------------------------------------------- no changes Inclusive step time: 1.0036361217499 <- Leaving step build, name 'endpoint_parameter' ------------------------------------------------ no changes Inclusive step time: 1.0037128925323 <- Leaving step build, name '' ------------------------------ no changes Inclusive step time: 1.0038249492645 <- Leaving step build, name 'ApiCallMonitoringMiddleware' --------------------------------------------------------- no changes Inclusive step time: 1.0039241313934 <- Leaving step build, name 'builder' ------------------------------------- no changes Inclusive step time: 1.0044429302216 <- Leaving step validate, name 'validation' ------------------------------------------- no changes Inclusive step time: 1.0048108100891 <- Leaving step init, name 'idempotency_auto_fill' -------------------------------------------------- no changes Inclusive step time: 1.0052030086517`

**Comment by ravindraibusinesssoftware** [comment]
I am facing the same issues 
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 1000 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\xampp\htdocs\test\awssdk\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:200 Stack trace: #0 C:\xampp\htdocs\test\awssdk\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\xampp\htdocs\test\awssdk\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\xampp\htdocs\test\awssdk\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(187): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 C:\xampp\htdocs\test\awssdk\vendor\guzzlehttp\guzzle\sr in 
C:\xampp\htdocs\test\awssdk\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 200

Please help me to solved it out

**Comment by vivekdbit** [comment]
> I am facing the same issues
> Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 1000 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\xampp\htdocs\test\awssdk\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:200 Stack trace: #0 C:\xampp\htdocs\test\awssdk\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\xampp\htdocs\test\awssdk\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\xampp\htdocs\test\awssdk\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(187): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 C:\xampp\htdocs\test\awssdk\vendor\guzzlehttp\guzzle\sr in
> C:\xampp\htdocs\test\awssdk\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 200
> 
> Please help me to solved it out

@ravindraibusinesssoftware ,

I was getting this issue because of the $client instantiation. I updated the following and it gets solved.

`$client = SageMakerRuntimeClient::factory(array(
                        'region' => 'ap-south-1',
                        'version' => 'latest',
                        'credentials' => [
                            'key'    => 'XXXXX',
                            'secret' => 'XXXXX',
                        ],
                    )); `

And I wanted to add one tip here as, if you are running this on AWS instance then no need to provide credentials. You have to create Role with said credentials and assign that role to your instance.

I hope the above changes will resolve your issue.

Thanks,
Vivek
