### ISSUE TITLE
release of aws textract for php

### ISSUE THREAD

**Issue by tvnr690** [aws/aws-sdk-php#1873]
When aws textract php api will be released

**Comment by howardlopez** [comment]
Are you referring to a Textract client in the SDK? This currently exists: https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-textract-2018-06-27.html

**Comment by diehlaws** [comment]
Hi @tvnr690, what version of the AWS SDK for PHP are you using? Version [3.88.0](https://github.com/aws/aws-sdk-php/releases/tag/3.88.0) introduced the API for Textract within the AWS SDK for PHP, if you're using an older version you'll want to update to at least this version or newer to use this service with the SDK.
