### ISSUE TITLE
SSECustomerAlgorithm or ServerSideEncryption not working with localstack

### ISSUE THREAD

**Issue by crimson-med** [aws/aws-sdk-php#1874]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?

3.112.1

### Version of PHP (`php -v`)?

7.1

### What issue did you see?

Trying to use encryption on the files I upload on a localstack but they are not encrypted.

### Steps to reproduce
I have tried the following:
```php
$result = $s3->putObject(array_merge($s3FileOptions, [
    'Bucket' => "xxxx-dev-bucket",
    'Key' => 'a348065c2afb8f61230ccb60147fdcd0f2d19140344.obj',
    'SSECustomerAlgorithm' => 'AES256',
    'SSECustomerKey' => substr(hash('sha256', openssl_random_pseudo_bytes(64)), 0, 32),
    'SSECustomerKeyMD5' => base64_encode(md5($salt, true)),
    'SourceFile' => $filepath,
    'ContentType' => $mimetype,
    'Metadata' => [
        'version' => '1.0.0',
        'tag' => $relTag ?? '',
    ]
]));
```
Also tried
```php
$result = $s3->putObject(array_merge($s3FileOptions, [
    'Bucket' => "xxxx-dev-bucket",
    'Key' => 'a348065c2afb8f61230ccb60147fdcd0f2d19140344.obj',
    'SSECustomerAlgorithm' => 'AES256',
    'SSECustomerKey' => substr(hash('sha256', openssl_random_pseudo_bytes(64)), 0, 32),
    'SSECustomerKeyMD5' => md5($salt, true),
    'SourceFile' => $filepath,
    'ContentType' => $mimetype,
    'Metadata' => [
        'version' => '1.0.0',
        'tag' => $relTag ?? '',
    ]
]));
```
And tried
```php
$result = $s3->putObject(array_merge($s3FileOptions, [
    'Bucket' => "xxxx-dev-bucket",
    'Key' => 'a348065c2afb8f61230ccb60147fdcd0f2d19140344.obj',
    'ServerSideEncryption' => 'AES256',
    'SourceFile' => $filepath,
    'ContentType' => $mimetype,
    'Metadata' => [
        'version' => '1.0.0',
        'tag' => $relTag ?? '',
    ]
]));
```

### Additional context

I am trying to simply encrypt my uploaded file. But whenever I check it on my localstack either by copying locally or downloading it from the url the file isn't encrypted.

After deploying this to our dev infrastructure it seems to be working on the live buckets. However for testing purposes, functionality development we would need it to work on localstack too.

**Comment by diehlaws** [comment]
Hi @crimson-med, thanks for reaching out to us. Please keep in mind that localstack is a third party product that may or may not have 1:1 feature parity with AWS services. After uploading the object to your localstack does a headObject to the corresponding key show that the object is encrypted using your customer key? You'll want to look for the `x-amz-server-side-encryption-customer-algorithm` and `x-amz-server-side-encryption-customer-key-md5` HTTP headers in the response to this call to check whether the object appears to be encrypted.

Are you able to reproduce this behavior using another AWS SDK when interacting with localstack? Do you see this behavior when uploading objects in the same manner to an S3 Bucket in AWS?

**Comment by crimson-med** [comment]
@diehlaws This issue appears only on localstack. On a real bucket there seems to be no issue apart from the signature mismatched when getting information. 

I pass the same values I used on `putObject` to the `getObject` but I only get a signature mismatch on the `getObject`

**Comment by diehlaws** [comment]
Thanks for the additional information @crimson-med. Since the described behavior is not occurring on S3 this is most likely occurring on localstack's end, if you haven't already I'd suggest opening an issue in their [GitHub repo](https://github.com/localstack/localstack/issues) to confirm and raise awareness of this behavior.

As far as the signature mismatch is concerned, are you using one of the above snippets to pass the same values to `putObject` and `getObject` in S3? If so, the signature likely isn't matching because the `SSECustomerKey` value is being re-generated for the `getObject` call which will result in the key (and thus the request's signature) not matching the expected value. If you generate the key outside of the `putObject` parameters and re-use this key for the `getObject` call things should work as expected:

```php
$ssecKey = openssl_random_pseudo_bytes(32);
$ssecKeyMD5 = md5($ssecKey, true);

try {
    $resp = $client->putObject([
        'Bucket' => $bucket,
        'Key' => $object,
        'SSECustomerAlgorithm' => 'AES256',
        'SSECustomerKey' => $ssecKey,
        'SSECustomerKeyMD5' => $ssecKeyMD5,
        'SourceFile' => $filepath,
        'ContentType' => $mimetype,
        'Metadata' => [
            'version' => '1.0.0',
        ]
    ]);
    echo "putObject succeeded:\n{$resp}\n";
} catch (AwsException $e) {
    echo "Failed to upload object:\n{$e->getMessage()}\n";
}

try {
    $get = $client->getObject([
        'Bucket' => $bucket,
        'Key' => $object,
        'SSECustomerAlgorithm' => 'AES256',
        'SSECustomerKey' => $ssecKey,
        'SSECustomerKeyMD5' => $ssecKeyMD5,

    ]);
    echo "getObject succeeded:\n{$get}\n";
} catch (AwsException $e) {
    echo "Failed to get object:\n{$e->getMessage()}\n";
}

```

**Comment by crimson-med** [comment]
We have managed to make it work with `putObject` and `getObject` is there any ways to work the decryption for pre-authorized urls?

**Comment by diehlaws** [comment]
As mentioned in #314, it is possible to create presigned URLs for objects that are encrypted with SSE-C but the request that uses the presigned URL will need to include some of the SSE-C related headers so the presigned URL cannot be used as a standalone link to the object.

That being said, if your use case calls for using presigned URLs within your PHP code [this](https://aws.amazon.com/blogs/developer/generating-amazon-s3-pre-signed-urls-with-sse-c-part-4/) blog post details how to make use of a presigned GET URL with Java - the same process can be done with Guzzle's HTTP client as shown below (using the above code snippet as a starting point):

```php
$cmd = $client->getCommand('GetObject', [
    'Bucket' => $bucket,
    'Key' => $object,
    'SSECustomerAlgorithm' => 'AES256',
    'SSECustomerKey' => $ssecKey,
    'SSECustomerKeyMD5' => $ssecKeyMD5,
]);

$req = $client->createPresignedRequest($cmd, '+20 minutes');

$url = (string)$req->getUri();

$httpClient = new GuzzleHTTP\Client();

$headers = [
    'x-amz-server-side-encryption-customer-algorithm' => 'AES256',
    'x-amz-server-side-encryption-customer-key-md5' => base64_encode($ssecKeyMD5),
    'x-amz-server-side-encryption-customer-key' => base64_encode($ssecKey)
];

$request = new GuzzleHTTP\Psr7\Request('GET', $url, $headers);

try {
    $getResp = $httpClient->send($request);
    print_r($getResp);
} catch (GuzzleHTTP\Exception\ClientException $e) {
    $err = (string)$e;
    echo "Error getting object from presigned URL:\n{$err}\n";
}
```

**Comment by crimson-med** [comment]
Thanks for the help and the fast response throughout this issue.
