### ISSUE TITLE
Credentials by process provider won't cache

### ISSUE THREAD

**Issue by yh1224** [aws/aws-sdk-php#1877]
Using Process provider(`CredentialProvider::process()`) with caching by `CredentialProvider::memoize()`, it execute process for every API calls even if the credential 
 is not expired yet.

### Version of AWS SDK for PHP?

3.112.10

### Version of PHP (`php -v`)?

PHP 7.2.21

### Steps to reproduce

PHP code

```
$provider = CredentialProvider::process('test-credential-process');
$provider = CredentialProvider::memoize($provider);

$client = new S3Client([
    'version' => '2006-03-01',
    'region' => 'ap-northeast-1',
    'credentials' => $provider,
]);
while (true) {
    $result = $client->listBuckets();
    sleep(3);
}
```

~/.aws/credentials

```
[test-credential-process]
credential_process = /path/to/provide_credential.sh
```

/path/to/provide_credential.sh (for test)

```
#!/usr/bin/env bash
cat << EOF
{
  "Version": 1,
  "AccessKeyId": "XXXXXXXXXXXXXXXXXXXX",
  "SecretAccessKey": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "SessionToken": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "Expiration": "2019-09-30T06:47:04Z"
}
EOF
```

**Comment by yh1224** [comment]
Creating `Credentials` object with Expiration string (like "2019-09-30T06:47:04Z") [here](https://github.com/aws/aws-sdk-php/blob/3.112.10/src/Credentials/CredentialProvider.php#L561), but it must be UNIX timestamp (not string). `$expiration->getTimestamp()` may correct.

**Comment by diehlaws** [comment]
Hi @yh1224, thanks for reaching out to us about this. I'm able to reproduce the described behavior and can confirm this is a bug. We'll be reviewing your PR shortly to ensure it can be safely merged.
