### ISSUE TITLE
Amazon SQS keeps returning a 403 error

### ISSUE THREAD

**Issue by Supacoco** [aws/aws-sdk-php#188]
Hi there,

No matter what I do with the SqsClient, it keeps throwing a SqsException with error code 403.

I've double checked the key and the secret key I provided to the SqsClient. I also ensured it wasn't a problem of firm's proxy or firewall.

Find below the error message I got :

> AWS Error Code: AccessDenied, Status Code: 403, AWS Request ID: > a8156b52-2952-53fa-87d3-2043726a2bb8, AWS Error Type: client, AWS Error > Message: Access to the resource https://sqs.us-west-2.amazonaws.com/ is > denied., User-Agent: aws-sdk-php2/2.3.4 Guzzle/3.6.0 curl/7.25.0 PHP/5.4.3

I'm feeling really dumb for not being able to achieve the first step...

What seems strange here it's that I tried with the aws-php-sdk sample projet and it worked fine.

**Comment by muhammad-sannan-confiz** [comment]
I able to access sqs console from the browser, is there any thing extra that I am missing to access the sqs. 
M trying to push a message from my lambda to sqs. Here is the exception. 
PS  IAM policy that m using has the access right on lambda for sqs. 

{
  "errorMessage": "Access to the resource https://sqs.us-west-2.amazonaws.com/ is denied. (Service: AmazonSQS; Status Code: 403; Error Code: AccessDenied; Request ID: c61c0698-505c-50fe-8c67-5602cb84e824)",
  "errorType": "com.amazonaws.services.sqs.model.AmazonSQSException",
  "stackTrace": [
    "com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1543)",
    "com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1181)",
    "com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:962)",
    "com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:675)",
    "com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:649)",
    "com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:632)",
    "com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$300(AmazonHttpClient.java:600)",
    "com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:582)",
    "com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:446)",
    "com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:1504)",
    "com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1480)",
    "com.amazonaws.services.sqs.AmazonSQSClient.listQueues(AmazonSQSClient.java:1010)",
    "com.amazonaws.services.sqs.AmazonSQSClient.listQueues(AmazonSQSClient.java:1022)",
    "S3EventHandler.handleRequest(S3EventHandler.java:76)",
    "S3EventHandler.handleRequest(S3EventHandler.java:28)"
  ]
}

**Comment by muhammad-sannan-confiz** [comment]
hi, 

I found out the issue, IAM policy that i was using has access to only east region where as my sqs was on west. So  before using  sqs from lambda make sure you have correct policy attached.

**Comment by Prateek13727** [comment]
Hi, 
Also please check the **SNS topic** in your SQS policy. In my case, the SNS topic in my SQS queue policy was different from the one from which was publishing the messages to my SQS queue.

you can view your SQS queue policy by clicking on the Edit button on the corresponding. queue detail page.

**Comment by Prateek13727** [comment]
Hello folks,

Also please check the SNS topic in your SQS policy. In my case, the SNS topic in my SQS queue policy was different from the one from which was publishing the messages to my SQS queue.

you can view your SQS queue policy by clicking on the Edit button on the corresponding. queue detail page.
