### ISSUE TITLE
Apache log errors about S3ClientTrait.php, Undefined index: x-amz-bucket-region

### ISSUE THREAD

**Issue by tannerchung** [aws/aws-sdk-php#1880]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?

3.103.1

### Version of PHP (`php -v`)?

PHP 7.3.9 (cli) (built: Sep 18 2019 14:01:26) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9, Copyright (c) 1999-2018, by Zend Technologies

### What issue did you see?

Apache logs are showing this: [client xxx.xxx.xxx.xxx:0] AH01071: Got error 'PHP message: PHP Notice: Undefined index: x-amz-bucket-region in /home/site/webapps/site/wp-content/plugins/ilab-media-tools/vendor/ilab/ilab-aws-media-cloud-sdk/src/S3/S3ClientTrait.php on line 219'

### Steps to reproduce
If you have a runnable example, please include it as a snippet or link to a repository/gist for larger code examples.

It's hard to say, this plugin for WordPress is using the library and they are pointing to the library itself: https://talk.mediacloud.press/topic/96/apache-log-errors-about-s3clienttrait-php-from-media-cloud

### Additional context
Any additional information relevant to the issue. Examples include any framework you may be using (e.g. Laravel, Wordpress) in conjunction with the AWS SDK for PHP, or PHP/environment config settings if the issue is related to memory or performance.

WordPress

**Comment by diehlaws** [comment]
Hi @tannerchung, thanks for reaching out to us. The `x-amz-bucket-region` header mentioned in the PHP notice you provided is being parsed by the `determineBucketRegionAsync` function in [S3ClientTrait.php](https://github.com/aws/aws-sdk-php/blob/master/src/S3/S3ClientTrait.php#L209) - this function is only used in the `createPresignedRequest` and `getObjectUrl` functions in [S3MultiRegionClient.php](https://github.com/aws/aws-sdk-php/blob/master/src/S3/S3MultiRegionClient.php). Unfortunately I haven't been able to reproduce the described behavior with these two fuctions, I've used both the aws/aws-sdk-php package (version 3.112.17) from this repo  and the ilab/ilab-aws-media-cloud-sdk package (version 0.3.1) from https://github.com/Interfacelab/ilab-aws-media-cloud-sdk. 

Is there anything this notice is preventing the plugin from doing? Or is the plugin performing as expected, just with this notice in the Apache logs whenever a particular action takes place? Can you identify the action the plugin is taking when this notice is logged within Apache? Does this behavior occur consistently for any given bucket used for the plugin, or are you able to narrow this behavior down to a specific bucket (or set of buckets)? If you can narrow it down to one or more specific buckets, what commonalities to these buckets share? If they all share the same region, what region do you see affected by this behavior?
