### ISSUE TITLE
API for Route53 domain pricing, or a reference file

### ISSUE THREAD

**Issue by alphametric** [aws/aws-sdk-php#1882]
Presently, it does not seem to be possible to obtain pricing information for relevant API calls using the `Route53DomainClient`. For example, when calling `checkDomainAvailability()`, in addition to the response containing availability, ideally, we'd also see the price...

```php
$client->checkDomainAvailability(['DomainName' => 'example.com']);

// returns a response, which includes...

[
    'Availability' => 'AVAILABLE',
    'PricePerYear' => '$12.00'
]
```

Other APIs such as `getDomainSuggestions()` and `checkDomainTransferability()` would also benefit from this treatment. 

Failing that, is there an official, online and maintained file e.g. JSON or XML, that includes the prices for registering / renewing / transferring TLDs? I'm aware of [this PDF file](https://d32ze2gidvkk54.cloudfront.net/Amazon_Route_53_Domain_Registration_Pricing_20140731.pdf) from the docs, but I need something I can programmatically parse.

I did find [this issue](https://github.com/aws/aws-sdk-java/issues/1468) on the Java repository,  in which they link to [this JSON file](https://s3.amazonaws.com/ris-public/TldCatalog/v1/latest.json), but since the file only seems to be referenced in that one issue and nowhere else on the internet, I've no idea if it is official or maintained.

Thanks in advance!
Matt

**Comment by diehlaws** [comment]
Hi @alphametric, thanks for reaching out to us. What you're requesting is a new feature for the Route 53 service, which falls outside of the scope of the AWS SDK for PHP and its GitHub repo. I suggest posting on the [AWS Forums for Route 53](https://forums.aws.amazon.com/forum.jspa?forumID=87), or reaching out to our Premium Support team by opening a [new technical support case](https://console.aws.amazon.com/support/cases#/create) under the Route 53 service and the Feature Request category for further support on the service end.

To answer your question regarding a maintained source for domain pricing, the PDF file you linked is the only source I'm aware of that is maintained by AWS. The URL for the JSON file you mention shows a bucket name of 'ris-public' which suggests it is used for RIPE's [Routing Information Service](https://www.ripe.net/analyse/internet-measurements/routing-information-service-ris), however I have no way of verifying the ownership of this bucket so I cannot confirm that this JSON file is accurate or consistently updated.

**Comment by alphametric** [comment]
Okay, thank you for the reply :)
