### ISSUE TITLE
KinesisVideoArchivedMediaClient cant get DASH Streaming Session URL

### ISSUE THREAD

**Issue by Th0ru5** [aws/aws-sdk-php#1883]
Hello i'm trying to get DASH Streaming Session URL via php sdk 3.0.
But i can't find any information in Your documentation.

So i'm trying to do something like this:
```php
require_once("../AmazonSDK/aws-autoloader.php");

  use Aws\KinesisVideoArchivedMedia\KinesisVideoArchivedMediaClient;

  $client = new Aws\KinesisVideoArchivedMedia\KinesisVideoArchivedMediaClient(array(
    "region" => "eu-central-1",
    "version" => "2017-09-30"
  ));
  $result = $client->getDASHStreamingSessionURL(array(
    "DASHFragmentSelector" => array(
      "FragmentSelectorType" => "SERVER_TIMESTAMP"
    ),
    "DisplayFragmentNumber" => "NEVER",
    'DisplayFragmentTimestamp' => 'NEVER',
    'Expires' => 3000,
    'MaxManifestFragmentResults' => 5,
    'PlaybackMode' => 'LIVE',
    'StreamARN' => 'xxx,
    'StreamName' => 'xxx',
  ));
```

And i'm getting this Exception:
`Fatal error: Uncaught InvalidArgumentException: Operation not found: GetDASHStreamingSessionURL in /admin/AmazonSDK/Aws/AwsClient.php:215 Stack trace: #0 /admin/AmazonSDK/Aws/AwsClientTrait.php(77): Aws\AwsClient->getCommand('GetDASHStreamin...', Array) #1 /admin/videoplatform/getVideoEndPoint.php(11): Aws\AwsClient->__call('getDASHStreamin...', Array) #2 {main} thrown in /admin/AmazonSDK/Aws/AwsClient.php on line 215`

I don't want to put any credentials on client side.

Can you tell me how i can do this? Maybe i missed some part of documentation if so please let me know.

SDK VERSION: 3.67.2

**Comment by diehlaws** [comment]
Hi @Th0ru5, thanks for reaching out to us. The version of the SDK that you're using does not support this API call; per our [changelog](https://github.com/aws/aws-sdk-php/blob/master/CHANGELOG.md#31060---2019-07-09) support for the `GetDASHStreamingSessionURL` API was introduced in version 3.106.0 of the SDK. Updating your SDK package to this version or newer will allow you to use this API call as expected.

**Comment by Th0ru5** [comment]
I updated the SDK to version 3.112.19 - 2019-10-10 and now i'm geting this exception

`Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 1003 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /admin/AmazonSDK/GuzzleHttp/Handler/CurlFactory.php:185 Stack trace: #0 /admin/AmazonSDK/GuzzleHttp/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 /admin/AmazonSDK/GuzzleHttp/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 /admin/AmazonSDK/GuzzleHttp/Handler/CurlMultiHandler.php(181): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 /admin/AmazonSDK/GuzzleHttp/Handler/CurlMultiHandler.php(110): GuzzleHttp\Handler\CurlMultiHandler->processMessages() #4 /admin/AmazonSDK/GuzzleHttp/Handler/CurlMultiHandle in /admin/AmazonSDK/GuzzleHttp/Handler/CurlFactory.php on line 185`

Yes, I have network connection.
What can causing it?

**Comment by diehlaws** [comment]
Thanks for the aditional information @Th0ru5. Are you able to reach the endpoint `kinesisvideo.eu-central-1.amazonaws.com` on port 443 from the host running this code via a method different from the AWS SDK for PHP? E.g. issuing an HTTP HEAD request via `curl` or an HTTP client within PHP, or just establishing a connection to port 443 via `nc` or PHP's [`socket_connect()`](https://www.php.net/manual/en/function.socket-connect.php) function. 

If your host can reach the endpoint but it takes more than a full second to do so, you can measure how long it takes to reach the endpoint and adjust the `connect_timeout` value accordingly in the [http](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#config-http) options for the service client within the AWS SDK for PHP to avoid connection timeouts. By contrast, if your host is unable to reach this endpoint altogether it sounds like some network troubleshooting needs to be done from the host end to determine why it cannot reach this endpoint.

**Comment by Th0ru5** [comment]
Yes i'm able to reach the endpoint from my host.
I added the http=>[connect_timeout=>5]
My options:
```php
array(
    "region" => "eu-central-1",
    "version" => "latest",
    "http" => array(
      "connect_timeout" => 10
    )
  )
```
And nothing changed. Still the timeout appears after 1s.

**Comment by diehlaws** [comment]
Thanks for the additional information @Th0ru5! If you're able to reach the service's endpoint, the SDK is likely timing out trying to reach the instance metadata service to retrieve an instance profile at the end of the [default credential provider chain](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials.html). You'll need to use one of the methods specified on that page to provide credentials to the service client. 

You can try using an [anonymous client](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_anonymous.html) however I would expect some form of authentication for your account to be required in order for this API call to succeed.

**Comment by Th0ru5** [comment]
Ok, i added the credentials to AWSClient configs and all is working.
Thank you for your time and help.
