### ISSUE TITLE
Fatal Error : Error parsing JSON

### ISSUE THREAD

**Issue by matrixmediaAmit** [aws/aws-sdk-php#1887]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
3.0

### Version of PHP (`php -v`)?
7.2

### What issue did you see?
```
Fatal error:  Uncaught Aws\Api\Parser\Exception\ParserException: Error parsing JSON: Syntax error in /home/mywpjelly/public_html/aws-domain-check/Aws/Api/Parser/PayloadParserTrait.php:21
Stack trace:
#0 /home/mywpjelly/public_html/aws-domain-check/Aws/Api/Parser/JsonRpcParser.php(49): Aws\Api\Parser\JsonRpcParser->parseJson(Object(GuzzleHttp\Psr7\Stream), Object(GuzzleHttp\Psr7\Response))
#1 /home/mywpjelly/public_html/aws-domain-check/Aws/Api/Parser/JsonRpcParser.php(38): Aws\Api\Parser\JsonRpcParser->parseMemberFromStream(Object(GuzzleHttp\Psr7\Stream), Object(Aws\Api\StructureShape), Object(GuzzleHttp\Psr7\Response))
#2 /home/mywpjelly/public_html/aws-domain-check/Aws/WrappedHttpHandler.php(125): Aws\Api\Parser\JsonRpcParser->__invoke(Object(Aws\Command), Object(GuzzleHttp\Psr7\Response))
#3 /home/mywpjelly/public_html/aws-domain-check/Aws/WrappedHttpHandler.php(92): Aws\WrappedHttpHandler->parseResponse(Object(Aws\Command), Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), Array)
#4 /home/mywpjelly/pub in /home/mywpjelly/public_html/aws-domain-check/Aws/Api/Parser/PayloadParserTrait.php on line 21
```

### Steps to reproduce
Try to call like,

```php
require 'aws-domain-check/aws-autoloader.php';

use Aws\Route53Domains\Route53DomainsClient;

$client = Route53DomainsClient::factory(array(
    //'debug'       => true,
    'credentials' => array(
            'key' => "XXXXX",
            'secret'  => "XXXXXXX"
    ),
    'region'  => 'us-east-2',
    'version' => 'latest',
    'http'    => [
        'verify' => false
    ]
    
));
$client->checkDomainAvailability(['DomainName' => 'xxxx.com', 'IdnLangCode' => 'eng']);
```

### Additional context
Into WordPress theme

**Comment by diehlaws** [comment]
Hi @matrixmediaAmit, thanks for reaching out to us. Unfortunately I'm not able to reproduce the described behavior, however the error returned suggests that there is a problem with the syntax of the JSON object being received by the JSON RPC parser. Can you clarify what you mean by 'Into WordPress theme'? Are you able to reproduce this behavior in an environment that does not have WordPress installed?

Looking at the provided code snippet I see you're setting your client region to us-east-2, however the Route53Domains service has only [one endpoint](https://docs.aws.amazon.com/general/latest/gr/rande.html#r53_region) in us-east-1. Do you still see this error when changing your client's region accordingly?

**Comment by matrixmediaAmit** [comment]
" however the Route53Domains service has only one endpoint in us-east-1 "
-- This line solves the issue.
A ton of thanks for your help.
May god bless you.
