### ISSUE TITLE
fseek not working correctly after fread on s3 bucket

### ISSUE THREAD

**Issue by sourabhbajaj** [aws/aws-sdk-php#1890]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
^3.109

### Version of PHP (`php -v`)?
7.1.9

### What issue did you see?
On s3 bucket sdk, if you read the file with fread() and then reset the cursor using fseek() and then read the file again with fread(), content of the file is different. 

### Steps to reproduce
```
$s3=new S3();
$s3->registerStreamWrapper();
$filename="s3://mybucket/docs/5c66cd2879.pdf";
$file = fopen($filename,"rb");
echo "\n\nBefore fseek:\n\n";
echo fread($file,"100");

echo "\n\nAfter fseek:\n\n";
fseek($file, "0");
echo fread($file,"100");

```

### Output

Before fseek:

```
%PDF-1.4
%�쏢
5 0 obj
<</Length 6 0 R/Filter /FlateDecode>>
stream
x�+T0�3T0A(��˥d��^�U�`jii�g

After fseek:

$T�":a�G�Dt�	$H4�$�8A
eI]�L����#�:QZ@��XM*A���?H4��l	4���%a��!p�莘�>�4P��D
```

### Additional context
When FPDF, phps PDF editing library is used with S3 bucket PHP SDK, it's showing error because of this issue:

`Uncaught setasign\Fpdi\PdfParser\PdfParserException: Unable to find PDF file header.`

**Comment by diehlaws** [comment]
Hi @sourabhbajaj, thanks for reaching out to us about this. Looking at the provided code, it appears the file is not being opened in a seekable manner as detailed in [our docs](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-stream-wrapper.html#opening-seekable-streams). The behavior you describe is expected when opening the file in a non-seekable manner, however when setting `'s3' => ['seekable' => true]` in the context provided to `fopen()` the SDK should behave as expected:

```php
$context = stream_context_create([
    's3' => ['seekable' => true]
]);

echo "Opening file without context:\n---";
$file = fopen($filename,"rb");
echo "\n\nBefore fseek:\n\n";
echo fread($file,"100").PHP_EOL;

echo "\n\nAfter fseek:\n\n";
fseek($file, "0");
echo fread($file,"100").PHP_EOL;

echo "\n---\nOpening file with context:\n---";
$file = fopen($filename,"rb", false, $context);
echo "\n\nBefore fseek:\n\n";
echo fread($file,"100").PHP_EOL;

echo "\n\nAfter fseek:\n\n";
fseek($file, 0, 0);
echo fread($file,"100").PHP_EOL;
```

```
$ php seekable.php 
Using AWS SDK for PHP version 3.110.0
Opening file without context:
---

Before fseek:

%����1.3
<</ViewerPreferences<</Direction/L2R>>/Metadata 463 0 R/Pages 2 0 R/Type/Cat


After fseek:

n>72.00</xapMM:placedXResolution>
                  <xapMM:placedYResolution>72.00</xapMM:placedYRes

---
Opening file with context:
---

Before fseek:

%����1.3
<</ViewerPreferences<</Direction/L2R>>/Metadata 463 0 R/Pages 2 0 R/Type/Cat


After fseek:

%����1.3
<</ViewerPreferences<</Direction/L2R>>/Metadata 463 0 R/Pages 2 0 R/Type/Cat
```

Please do let us know if you continue to see this behavior after passing the appropriate context to your `fopen()` call.
