### ISSUE TITLE
Undefined method named "getAwsErrorCode" of class "InvalidArgumentException"

### ISSUE THREAD

**Issue by mattrx** [aws/aws-sdk-php#1891]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
3.112.31

### Version of PHP (`php -v`)?
7.1.32

### What issue did you see?
`Attempted to call an undefined method named "getAwsErrorCode" of class "InvalidArgumentException".`

Shouldn't there be a check if the `getAwsErrorCode` exists?

https://github.com/aws/aws-sdk-php/blob/master/src/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php#L113

**Comment by diehlaws** [comment]
Hi @Valve, thanks for bringing this to our attention. I've submitted PR #1893 to account for generic exceptions when assuming a role using a web identity token. Once this PR is merged you should no longer see the described behavior.
