### ISSUE TITLE
s3Client::getSignatureProvider() method shall be public

### ISSUE THREAD

**Issue by oakad** [aws/aws-sdk-php#1896]
In some cases it is desirable to fine tune the structure of the signed url. This is not difficult to do by modifying the Guzzle request prior to passing it to signer.

However, for some reason, `getSignatureProvider` method is protected, unnecessarily complicating the signature customization process. Making it public will make life a little bit nicer.

**Comment by SamRemis** [comment]
Hello @oakad,  

Thank you for reaching out to us, and I apologize for the delay.  I'm looking into this right now, having more details about your use case would help us better understand the need to expose the method

Thank you,
-Sam

**Comment by SamRemis** [comment]
Just to follow up, we discussed it and it and went ahead and changed the method to be public.  Thank you for the feedback!
