### ISSUE TITLE
Make Content-MD5 available in S3 HeadObject

### ISSUE THREAD

**Issue by TrashF** [aws/aws-sdk-php#1903]
### Is this related to a problem?
No, it's just something that S3 documentation mentions and is not included in actual output. https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-metadata lists "Content-MD5" as a system-defined metadata. However, it is not returned along with other system-defined metadata fields.

### Feature description
I want the S3 object metadata output to contain also "Content-MD5". Other choice I would be okay with but not nearly as happy is if the S3 documentation is updated to not mention anything about Content-MD5.

The reason I would like to have the Content-MD5 is to check if a big file has been downloaded correctly. ETag does not always contain MD5 of file contents (this is the case with at least multipart uploads) and is therefore not useful enough.

I am aware that even aws-cli does not return the said information - at least by calling `aws s3api head-object`, which really makes me wonder how it is listed as "system-defined" if it cannot be seen. All other metadata fields (system-defined and custom) seem to be in place.

### Describe alternatives you've considered
Downloading the file and calculating the MD5 myself, then probably storing it to x-amz-meta-something. This would be troublesome and slow.

### Additional context
![kuva](https://user-images.githubusercontent.com/3194440/69146667-feaa2a80-0ad8-11ea-831e-6053dbdb1f4b.png)

**Comment by diehlaws** [comment]
Hi @TrashF, thanks for reaching out to us. Unfortunately this behavior is not specific to the AWS SDK for PHP but rather part of how S3 works. As you mentioned, the current best approach to work around this behavior is to calculate the MD5 hash on your end and adding it as metadata to the object when it is uploaded. 

Submitting this feature request under the [S3 section of the AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=24), or reaching out to our Premium Support team by opening a [new technical support case](https://console.aws.amazon.com/support/cases#/create) under the S3 service would be the best approach to ensure this is received and considered by the S3 team.
