### ISSUE TITLE
Import terminology error

### ISSUE THREAD

**Issue by marumehrts** [aws/aws-sdk-php#1909]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
3.91.3

### Version of PHP (`php -v`)?
PHP 7.1.26

### What issue did you see?
When trying to import a terminology, I get the following error `The provided terminology is not formatted correctly. Check the contents of your file to ensure that it follows the correct CSV format.`

### Steps to reproduce
```php
$result2 = $client->importTerminology([
	'Description' => 'Terminology for '.$ct,
	'EncryptionKey' => [
		'Id' => '***', // REQUIRED
		'Type' => 'KMS', // REQUIRED
	],
	'MergeStrategy' => 'OVERWRITE', // REQUIRED
	'Name' => $ct.'Term', // REQUIRED
	'TerminologyData' => [ // REQUIRED
		'File' => 'custom_terminologies/custom_terminology_'.$ct.'.csv', // REQUIRED
		'Format' => 'CSV', // REQUIRED
	],
]);
```

**Comment by diehlaws** [comment]
Hi @marumehrts, thanks for reaching out to us about this. Unfortunately the parameter name for 'TerminologyData'->'File' is a bit confusing - the name alone suggests (to me at least) that one should provide the filename for the .csv or .tmx file being imported. However, looking at the documentation for [this call](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-translate-2017-07-01.html#importterminology) it looks like this parameter actually takes in the contents of the file from which you want to import terminology, so your code should work as expected with minor changes:

```php
$filename = 'custom_terminologies/custom_terminology_'.$ct.'.csv';
$file = fread(fopen($filename, 'r'), filesize($filename));

$result2 = $client->importTerminology([
	'Description' => 'Terminology for '.$ct,
	'EncryptionKey' => [
		'Id' => '***',
		'Type' => 'KMS',
	],
	'MergeStrategy' => 'OVERWRITE', 
	'Name' => $ct.'Term',
	'TerminologyData' => [ 
		'File' => $file,
		'Format' => 'CSV', 
	],
]);
```

**Comment by marumehrts** [comment]
Thank you, that clarifies a lot, there's no much documentation about this, so it was confusing. I had to do it another way, but it'll be good for future references.

**Comment by Bhagwanta1997** [comment]
I have same issue , I'm trying to implement in javascript but not resolve.
@diehlaws Could you please help me in that ?
