### ISSUE TITLE
Dynamodb PHP Sdk exemplo return error

### ISSUE THREAD

**Issue by marcelosboeira** [aws/aws-sdk-php#1913]
Please fill out the sections below to help us address your issue.
I try to do exemplo in the document: [https://docs.aws.amazon.com/pt_br/amazondynamodb/latest/developerguide/GettingStarted.PHP.03.html](https://docs.aws.amazon.com/pt_br/amazondynamodb/latest/developerguide/GettingStarted.PHP.03.html)

### Version of AWS SDK for PHP?
 "aws/aws-sdk-php": "^3.123"

### Version of PHP (`php -v`)?
PHP Group Zend Engine v3.3.11
Zend OPcache v7.3.11-1+ubuntu18.04.1+deb.sury.org+1

### What issue did you see?
I try to do exemplo in the document:

```php
$tableName = 'Movies';

$eav = $gMarshaler->marshalJson('
	{
		":yyyy": 1985 
	}
');

$params = [
	'TableName' => $tableName,
	'KeyConditionExpression' => '#yr = :yyyy',
	'ExpressionAttributeNames'=> [ '#yr' => 'year' ],
	'ExpressionAttributeValues'=> $eav
];

echo "Querying for movies from 1985.\n";

try {
	$result = $gDynamodb->query($params);

	echo "Query succeeded.\n";

	foreach ($result['Items'] as $movie) {
		echo $marshaler->unmarshalValue($movie['year']) . ': ' .
			$marshaler->unmarshalValue($movie['title']) . "\n";
	}

} catch (DynamoDbException $e) {
	echo "Unable to query:\n";
	echo $e->getMessage() . "\n";
}
```

And to return error:
```
Querying for movies from 1985.
Fatal error: Uncaught exception 'Aws\DynamoDb\Exception\DynamoDbException' with message 'Error executing "Query" on "https://dynamodb.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://dynamodb.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response: {"__type":"com.amazonaws.dynamodb.v20120810#ResourceNotFoundException","message":"Requested resource not found"} ResourceNotFoundException (client): Requested resource not found - {"__type":"com.amazonaws.dynamodb.v20120810#ResourceNotFoundException","message":"Requested resource not found"}' GuzzleHttp\Exception\ClientException: Client error: `POST https://dynamodb.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response: {"__type":"com.amazonaws.dynamodb.v20120810#ResourceNotFoundException","message":"Requested resource not found"} in /usr/share/nginx/html/controller.instaweb.com/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /usr/share/nginx/html/controller.instaweb.com/vendor/guzzlehttp/guzzle/src/M in /usr/share/nginx/html/controller.instaweb.com/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 195
```

### Steps to reproduce
Shown above

### Additional context
N/A

**Comment by diehlaws** [comment]
Hi @marcelosboeira, thanks for reaching out to us. The error you're receiving suggests that you do not have a DynamoDB table named 'Movies' in us-east-1 on your AWS account. Have you completed steps 1 and 2 on the same guide to create this table in us-east-1? Please keep in mind that the code sample for step 1 initializes the SDK using the us-west-2 region, so executing this code without changing the region will create the DynamoDB table in us-west-2 rather than us-east-1.
