### ISSUE TITLE
I can't connect to Amazon AWS from windows local environment.

### ISSUE THREAD

**Issue by robertmylne** [aws/aws-sdk-php#1919]
From windows computer whenever I try to do a request using the SDK:
cURL error 7: Failed to connect to 169.254.169.254 port 80: Network unreachable (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

Can't ping

Works from ubuntu server. Can ping.

Exact same code base. Basically a copy paste. Works if I move code between ubuntu servers, won't work from other windows 10 computers though.

**Comment by robertmylne** [comment]
`The SDK uses the getenv() function to look for the AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN environment variables.`

The `getenv()` function doesn't find the environment variables on a Windows PC, but does on linux. So that's the issue.

**Comment by diehlaws** [comment]
Hi @robertmylne, thanks for reaching out to us. Unfortunately I haven't been able to reproduce the described behavior in Windows 10 or Windows Server 2019, tested with PHP 7.3 and 7.4. `getenv()` works as expected in both operating systems for the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables, and using the SDK's default credentials chain to retrieve my environment variables works as expected on an STS `getCallerIdentity` call.

Can you provide some additional context to the behavior you're seeing? 
- What versions of Windows, PHP, and the AWS SDK for PHP are you using? 
- Do you encounter this when running your script via CLI or when serving the script as a web page? If it's the latter, which web server are you using when you encounter this behavior? 
- How are you setting your environment variables before the SDK attempts to retrieve credentials? 
- Are you using the SDK's default credential provider or did you implement your own specifically for environment variables?
