### ISSUE TITLE
Curl Error 7 But Aws Cli Works

### ISSUE THREAD

**Issue by mdeering24** [aws/aws-sdk-php#1920]
We have our application in ECS FARGATE. 

We are trying to have our application retrieve a secret from the SecretsManager. The sdk is getting a permission error while the aws cli is working and able to retrieve the secret fine. 

```
cURL error 7:  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
#0 /tmp/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /tmp/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /tmp/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(181): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /tmp/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(110): GuzzleHttp\Handler\CurlMultiHandler->processMessages()
#4 /tmp/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(125): GuzzleHttp\Handler\CurlMultiHandler->tick()
#5 /tmp/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#6 /tmp/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#7 /tmp/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#8 /tmp/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#9 /tmp/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#10 /tmp/vendor/guzzlehttp/promises/src/Coroutine.php(65): GuzzleHttp\Promise\Promise->wait()
#11 /tmp/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\Coroutine->GuzzleHttp\Promise\{closure}(true)
#12 /tmp/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#13 /tmp/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#14 /tmp/vendor/guzzlehttp/promises/src/Coroutine.php(85): GuzzleHttp\Promise\Promise->wait(false)
#15 /tmp/vendor/guzzlehttp/promises/src/Promise.php(273): GuzzleHttp\Promise\Coroutine->wait(false)
#16 /tmp/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#17 /tmp/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#18 /tmp/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): GuzzleHttp\Promise\Promise->wait()
#19 /tmp/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(86): Aws\AwsClient->execute(Object(Aws\Command))
#20 /app/lib/Fibroblast/Handler/GetSecretKeyHandler.php(71): Aws\AwsClient->__call('getSecretValue', Array)
#21 /app/lib/Fibroblast/Bus/StandardBus.php(76): Fibroblast\Handler\GetSecretKeyHandler->handleCommand(Object(Fibroblast\Command\GetSecretKeyCommand))
#22 /app/lib/Fibroblast/Controller/AbstractApplication.php(350): Fibroblast\Bus\StandardBus->execute(Object(Fibroblast\Command\GetSecretKeyCommand))
#23 /app/lib/Fibroblast/Controller/AbstractApplication.php(456): Fibroblast\Controller\AbstractApplication->afterCheckCurrentUser()
#24 /app/lib/Fibroblast/Controller/AbstractApplication.php(553): Fibroblast\Controller\AbstractApplication->after()
#25 /tmp/vendor/digintent/mefworks/lib/MVC/Dispatcher.php(141): Fibroblast\Controller\AbstractApplication->respond(Object(mef\MVC\MatchedRoute))
#26 /tmp/vendor/digintent/mefworks/lib/MVC/Dispatcher.php(92): mef\MVC\Dispatcher->handleRequest(Object(mef\HTTP\Request), Object(mef\MVC\MatchedRoute))
#27 /app/lib/Fibroblast/Application.php(348): mef\MVC\Dispatcher->process(Object(mef\HTTP\Request))
#28 /app/app/index.php(54): Fibroblast\Application->run(Object(mef\HTTP\Request))
#29 {main}
```

Our application sets up a container with the secrets manager inside it:
```
$this->container['SecretsManagerClient'] = function ($c) {
                try {
                    $provider = \Aws\Credentials\CredentialProvider::defaultProvider();
                    return new \Aws\SecretsManager\SecretsManagerClient([
                            'version' => '2017-10-17',
                            'region' => 'us-east-1',
                            'credentials' => $provider
                        ]);
                } catch (AwsException $e) {
                    echo $e->getMessage() . "\n";
                    echo $e->getAwsRequestId() . "\n";
                    echo $e->getAwsErrorType() . "\n";
                    echo $e->getAwsErrorCode() . "\n";
                }
        };
```

We then have a Command Bus call on the SecretsManager:
```
$key = $command->getKey();

if (strlen($key) < 1) {
	return;
}
		
$cachePath = APPPATH.'cache/'.$key.'.php';
$this->setTempValues();

//if file exists decrypt and send back
if (file_exists($cachePath)) {
	$credentials = include $cachePath;
	return $this->decryptData($credentials);
}

//else get credentials and save encrypted copy
try {
    $result = $this->SecretsManagerClient->getSecretValue([ 'SecretId' => $key ]);

    $fp = @fopen($cachePath, 'w');
    if (is_resource($fp)) {
	$enryptedData = $this->encryptData($result);
	fwrite($fp, '<?php return unserialize('.var_export(serialize($enryptedData), true).');');
	fclose($fp);
     }
} catch (AwsException $e) {
    $error = $e->getAwsErrorCode();
    if ($error == 'DecryptionFailureException') {
	// Secrets Manager can't decrypt the protected secret text using the provided AWS KMS key.
	throw $e;
	}
	if ($error == 'InternalServiceErrorException') {
	       // An error occurred on the server side.
	        throw $e;
	 }
	 if ($error == 'InvalidParameterException') {
	     // You provided an invalid value for a parameter.
	     throw $e;
	  }
	  if ($error == 'InvalidRequestException') {
	      // You provided a parameter value that is not valid for the current state of the resource.
	      throw $e;
	   }
	   if ($error == 'ResourceNotFoundException') {
	      // We can't find the resource that you asked for.
	      throw $e;
	   }
}
// Decrypts secret using the associated KMS CMK.
// Depending on whether the secret is a string or binary, one of these fields will be populated.
if (isset($result['SecretString'])) {
    $secret = $result['SecretString'];
} else {
    $secret = base64_decode($result['SecretBinary']);
}

return json_decode($secret, true);
```

Can you please help me understand why this issue is happening. Does Fargate store role credentials in a different area? Does the sdk not check that area?
My current understanding of the sdk is that it will know to curl the container/instance metadata for the credentials but that obviously doesn't seem to be the case.

**Comment by mdeering24** [comment]
Switched the credential provider to use ecsCredentials but still getting a 404.
```
$this->container['SecretsManagerClient'] = function ($c) {
                try {
                    $provider = \Aws\Credentials\CredentialProvider::ecsCredentials();
                    return new \Aws\SecretsManager\SecretsManagerClient([
                            'version' => '2017-10-17',
                            'region' => 'us-east-1',
                            'credentials' => $provider
                        ]);
                } catch (AwsException $e) {
                    echo $e->getMessage() . "\n";
                    echo $e->getAwsRequestId() . "\n";
                    echo $e->getAwsErrorType() . "\n";
                    echo $e->getAwsErrorCode() . "\n";
                }
        };
```
```Error retrieving credential from ECS (Client error: `GET http://169.254.170.2` resulted in a `404 Not Found` response:
404 page not found
)
#0 /tmp/vendor/guzzlehttp/promises/src/Promise.php(203): Aws\Credentials\EcsCredentialProvider->Aws\Credentials\{closure}(Object(GuzzleHttp\Exception\ClientException))
#1 /tmp/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(2, Array, Array)
#2 /tmp/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#3 /tmp/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(98): GuzzleHttp\Promise\TaskQueue->run()
#4 /tmp/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(125): GuzzleHttp\Handler\CurlMultiHandler->tick()
#5 /tmp/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#6 /tmp/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#7 /tmp/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#8 /tmp/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#9 /tmp/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#10 /tmp/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): GuzzleHttp\Promise\Promise->wait()
#11 /tmp/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(86): Aws\AwsClient->execute(Object(Aws\Command))
#12 /app/lib/Fibroblast/Handler/GetSecretKeyHandler.php(71): Aws\AwsClient->__call('getSecretValue', Array)
#13 /app/lib/Fibroblast/Bus/StandardBus.php(76): Fibroblast\Handler\GetSecretKeyHandler->handleCommand(Object(Fibroblast\Command\GetSecretKeyCommand))
#14 /app/lib/Fibroblast/Controller/AbstractApplication.php(350): Fibroblast\Bus\StandardBus->execute(Object(Fibroblast\Command\GetSecretKeyCommand))
#15 /app/lib/Fibroblast/Controller/AbstractApplication.php(456): Fibroblast\Controller\AbstractApplication->afterCheckCurrentUser()
#16 /app/lib/Fibroblast/Controller/AbstractApplication.php(553): Fibroblast\Controller\AbstractApplication->after()
#17 /tmp/vendor/digintent/mefworks/lib/MVC/Dispatcher.php(141): Fibroblast\Controller\AbstractApplication->respond(Object(mef\MVC\MatchedRoute))
#18 /tmp/vendor/digintent/mefworks/lib/MVC/Dispatcher.php(92): mef\MVC\Dispatcher->handleRequest(Object(mef\HTTP\Request), Object(mef\MVC\MatchedRoute))
#19 /app/lib/Fibroblast/Application.php(350): mef\MVC\Dispatcher->process(Object(mef\HTTP\Request))
#20 /app/app/index.php(54): Fibroblast\Application->run(Object(mef\HTTP\Request))
#21 {main}
```

**Comment by mdeering24** [comment]
`curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` gives me the correct object back with RoleArn, AccessKeyId, SecretAccessKey

But if I do `shell_exec(\`curl` 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI\`)` it does not work with a 404 page not found.

**Comment by mdeering24** [comment]
I have followed the advice posted by aws on this issue here: https://forums.aws.amazon.com/thread.jspa?threadID=273767

The two suggested workarounds do not help with the sdk.

**This first option worked for getting the aws cli working but that is it.**
> 1. Export in the .profile file
>
> By exporting the environment variables in the .profile file additional processes can access the environment variable. This can be accomplished in the Dockerfile, for example, a RUN parameter can be used to add the export command to /root/.profile during the build of the container image.
>
> RUN echo 'export $(strings /proc/1/environ)' >> /root/.profile
>
> This statement would export all environment variables. Alternatively, to reduce this to only export AWS_CONTAINER_CREDENTIALS_RELATIVE_URI.
>
> RUN echo 'export $(strings /proc/1/environ | grep AWS_CONTAINER_CREDENTIALS_RELATIVE_URI)' >> /root/.profile
>
> Please note: this solution has a dependency on the strings and grep commands.

**This solution did not work as well**
>2. Export in the wrapper script
>If a wrapper script is being used, by modifying it to first export the AWS_CONTAINER_CREDENTIALS_RELATIVE_URI variable, it will be set in the environment of child processes.
>
>#!/bin/bash
>export AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
>#Run other processes
>/root/start.sh

**Comment by diehlaws** [comment]
Hi @mdeering24, thanks for reaching out to us. If you're relying on instance profile credentials, this behavior is likely caused by recent changes in the [Instance Metadata Service](https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/). You should be able to use EC2's [ModifyInstanceMetadataOptions](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-ec2-2016-11-15.html#modifyinstancemetadataoptions) call to increase the hop limit to allow the SDK to retrieve instance profile credentials from IMDS as expected.

**Comment by at-bachhuynh** [comment]
I got the same error with @mdeering24 
I create issue here:
https://github.com/aws/aws-sdk-php-laravel/issues/176

It makes me crazy :(

**Comment by at-bachhuynh** [comment]
hi @diehlaws , we are using ECS Fargate, no any ec2 instance here. how could be ?

**Comment by mdeering24** [comment]
Hi @at-bachhuynh,

I actually figured out my issue and forgot to post the solution and close this ticket. We were running a monolithic application in the container with Supervisor as a wrapper for everything. The two steps that we did to overcome this issue were:

1) Export in the .profile file
>By exporting the environment variables in the .profile file additional processes can access the environment variable. This can be accomplished in the Dockerfile, for example, a RUN parameter can be used to add the export command to /root/.profile during the build of the container image.
>
>    RUN echo 'export $(strings /proc/1/environ)' >> /root/.profile
>
>  Please note: this solution has a dependency on the strings and grep commands.

2) Update PHP ini file
> Change the php ini to allow worker processes to have access to environmental variables. By default php does not allow workers to access this information for security reasons. But we felt comfortable turning this feature off.
> All we added  was *clear_env = no*
> See this link: https://www.php.net/manual/en/install.fpm.configuration.php and look up 'clear_env'

**Comment by at-bachhuynh** [comment]
Hi @mdeering24 
Really happy when getting your response.
I try to add `clear_env = no`
but still not working.
Could you please take a look on my issue: https://github.com/aws/aws-sdk-php-laravel/issues/176
Could you have time to chat with me via facebook, or what's app?

**Comment by at-bachhuynh** [comment]
here is the result of command:
```ps e -p 1```
It lists all process with PID 1 and export env:
```
```

**Comment by Pi-George** [comment]
Why is this closed, this still seems to be an issue. Your steps are very helpful @mdeering24 but this should be working without having to make these convoluted steps.

**Comment by Pi-George** [comment]
Turns out that those steps don't work anyway, I believe it's simply due to the fact that /root/.profile won't be run when apache2 fires off against php-fpm.

**Comment by Pi-George** [comment]
Looks like things were moved to https://github.com/aws/aws-sdk-php-laravel/issues/176

**Comment by Pi-George** [comment]
I ended up putting this in my entrypoint, super hacky

```
if [ -f /proc/1/environ ]; then
    # Get the ECS environment variables
    export $(strings /proc/1/environ)
    # Set the AWS_CONTAINER_CREDENTIALS_RELATIVE_URI environment variable if it isn't already set
    if ! grep -q 'env[AWS_CONTAINER_CREDENTIALS_RELATIVE_URI]' /etc/php/7.2/fpm/pool.d/www.conf; then
        echo "clear_env = no" >> /etc/php/7.2/fpm/pool.d/www.conf
        echo "env[AWS_CONTAINER_CREDENTIALS_RELATIVE_URI] = $AWS_CONTAINER_CREDENTIALS_RELATIVE_URI" \
            >> /etc/php/7.2/fpm/pool.d/www.conf
    fi
else
    echo "Warning, couldn't find ECS environ file"
fi
```

**Comment by matthewsuan** [comment]
I also have this error. artisan commands that interacts with aws services works fine whereas fpm fails.
we are using fargate
