### ISSUE TITLE
What is the default protocol ?

### ISSUE THREAD

**Issue by kazi-shahin** [aws/aws-sdk-php#1922]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
Latest 

### Version of PHP (`php -v`)?
7.2

### What issue did you see?
What is the default protocol that files transfer ? How do I send file using SSH or SFTP ?

### Steps to reproduce
If you have a runnable example, please include it as a snippet or link to a repository/gist for larger code examples.

### Additional context
Any additional information relevant to the issue. Examples include any framework you may be using (e.g. Laravel, Wordpress) in conjunction with the AWS SDK for PHP, or PHP/environment config settings if the issue is related to memory or performance.

**Comment by diehlaws** [comment]
Hi @kazi-shahin, thanks for reaching out to us. The AWS SDKs interact with AWS services over HTTPS by default but they can be configured to use HTTP - the method to do this for the AWS SDK for PHP is shown [here](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#scheme). It is possible to transfer files to EC2 instances using SSH or SFTP provided the instance is configured to listen over the appropriate ports for these protocols. If you need to transfer files to S3 over SFTP you can use [AWS Transfer](https://aws.amazon.com/blogs/aws/new-aws-transfer-for-sftp-fully-managed-sftp-service-for-amazon-s3/), a fully managed SFTP service for S3.

**Comment by kazi-shahin** [comment]
Thanks. Instead of HTTPS / HTTP can I set SSH [here](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#scheme)
