### ISSUE TITLE
StreamWrapper problems when handling images exported from Photoshop

### ISSUE THREAD

**Issue by Shebo** [aws/aws-sdk-php#1923]
### Version of AWS SDK for PHP?
3.128.1

### Version of PHP (`php -v`)?
7.2.3

### What issue did you see?
The issue is with exported image files from Photoshop CC 2017 (Windows).
With the SDK, when trying to use getimagesize on a jpg image with custom stream wrapper (`getimagesize( "s3://s3.eu-west-1.amazonaws.com/bucket-name/imagePhotoshopDuplicate.jpg" )`) the function will return an error, but when using a standard stream wrapper (`getimagesize( "https://s3.eu-west-1.amazonaws.com/bucket-name/imagePhotoshopDuplicate.jpg" )`) the function will work as expected.

This issue is caused because Photoshop is adding some metadata headers to the original file upon export/save.

I don't know why exactly this is happening, but clearly the `StreamWrapper` is failing in handling these special headers. This looks like a bug with Photoshop but I think the `StreamWrapper` needs to know how to handle it.

### Steps to reproduce
1. Get an uncorrupted image from any source, duplicate it, import the duplicate to Photoshop CC 2017 Windows (maybe other versions will work too) and export/save it as a jpeg file.
2. Upload the photoshop duplicate and the original image to an S3 bucket.
3. Using the SDK, create an S3 client and register a custom Stream Wrapper (`s3` will suffice).
4. try to run `getimagesize` on both of the images with and without the custom stream wrapper. You can use the following code as an example:
```
var_dump(getimagesize( "https://s3.eu-west-1.amazonaws.com/bucket-name/imageOriginal.jpg" ));
var_dump(getimagesize( "s3://s3.eu-west-1.amazonaws.com/bucket-name/imageOriginal.jpg" ));
var_dump(getimagesize( "https://s3.eu-west-1.amazonaws.com/bucket-name/imagePhotoshopDuplicate.jpg" ));
var_dump(getimagesize( "s3://s3.eu-west-1.amazonaws.com/bucket-name/imagePhotoshopDuplicate.jpg" ));
```
5. The `getimagesize` function will fail on the photoshop duplicate image when using the custom stream wrapper (showing an error about corrupted bytes), but the https will read it perfectly.
6 (optional). Use a tool like ExifTool to compare the headers and metadata of the original image and the one exported by Photoshop.
Run `exiftool -all= imagePhotoshopDuplicate.jpg` to remove all the headers from the Photoshop exported image, and then re-upload it to S3 and run the same tests again (as in step 4).
You should now get a perfect result on all 4 tests.

### Additional context
I found a closed issue from 2017 ( #1261 ) with exactly the same problem. The image that was uploaded to that issue was indeed an image with Photoshop CC 2017 (Windows) headers, it can be used for a test if there's no Photoshop CC 2017 software available.

I hope that now with enough evidence this issue can be solved.

**Comment by ryangittings** [comment]
I'm also seeing this, are there any workarounds/fixes?

**Comment by Shebo** [comment]
@ryangittings 
So I'm not working on said project anymore, but if I remember correctly I used an image optimizer plugin (like wp-smush or EWWW) that will strip down metadata of the image(that means all EXIF headers in the image file) on user upload.
Those of course some Wordpress plugins. If your project isn't using Wordpress or in case you need a more custom-made solution, you can write an EXIF stripper (you can do it rather easily with PHP graphic libraries like GD or ImageMagick (ex. [https://stackoverflow.com/questions/19812383/php-remove-exif-data-from-images](https://stackoverflow.com/questions/19812383/php-remove-exif-data-from-images)).  Just add this step in the image upload flow before sending it to S3.


Finally, I needed to deal with all the corrupted images and data I already had in my S3. I've written a migration process that followed these steps:

1. Fetch and test all of my images with `getimagesize` to find which of the images are "corrupted".
2. Download every corrupted image, run it through the EXIF CLI tool I mentioned above, and then re-upload it back to the S3 bucket (ex. `shell_exec('exiftool -all= ../s3-images/' . $image)`).
3. Test all of the stripped images again with `getimagesize` just to make sure the migration went smoothly.

I also suggest that you backup all of the corrupted images before striping down the EXIF data, and also consider tagging the new images with some relevant metadata header. I highly recommend these steps, especially if you have a large number of images like I had.

That's the best solution that I came up with. Until this issue will be fixed the images with these headers should be considered corrupted and broken, and the only way to fix that is to strip down all of their metadata.

**Comment by ajredniwja** [comment]
The workaround mentioned above holds correct, I did a lot of testing using photoshop, the error is not coming from the SDK but inherent to how PHP parses files, the image is not corrupt and can be used with photoshop.

**Comment by du365** [comment]
@ajredniwja 
I also confirmed this issue.
for same image , if I  use local storage like 
`getimagesize( "/var/www/html/image/a.jpg")`
I can get the right info:
```
^ array:7 [▼
  0 => 3072
  1 => 2304
  2 => 2
  3 => "width="3072" height="2304""
  "bits" => 8
  "channels" => 3
  "mime" => "image/jpeg"
]
```

but if I use "s3://',then get false.
`s3://.../a.jpg`

`Warning (2): getimagesize(): corrupt JPEG data: 495 extraneous bytes before marker`
