### ISSUE TITLE
1 second delay in authentication

### ISSUE THREAD

**Issue by jderusse** [aws/aws-sdk-php#1924]
### Version of AWS SDK for PHP?
>= 3.119

### Version of PHP (`php -v`)?
not relevant

### What issue did you see?
In some serveur running on an AWS EC2 instance, the first call to AWS service takes more than 1second

### Steps to reproduce
Create a swarm stack using https://docs.docker.com/docker-for-aws/

### Additional context
Issue introduced in #1905, for some reason calls to `http://169.254.169.254/latest/api/token` are blocked (instance running the default swarm-for-aws stack) which ends to a timeout, and 1 second delay in call processing.

Given the "modeSecure" flag is optionnal, I suggest to define an option for it.

**Comment by Kuijkens** [comment]
@jderusse I think this is the same issue as described here: https://github.com/aws/aws-sdk-php/issues/1908

**Comment by jderusse** [comment]
indeed.. that's the same issue.. thanks
