### ISSUE TITLE
EC2 RequestSpotFleet cause exception A non-numeric value encountered

### ISSUE THREAD

**Issue by bolovdor** [aws/aws-sdk-php#1926]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
`aws-sdk-php:                       3.128.3`
`aws-sdk-php-laravel:               3.4.0`
`laravel/framework:                     v6.7.0`

### Version of PHP (`php -v`)?
`PHP 7.2.24-0ubuntu0.18.04.1`

### What issue did you see?

`A non-numeric value encountered` on line 36 in vendor/aws/aws-sdk-php/src/Api/Serializer/**Ec2ParamBuilder**.php

Full stack trace - https://flareapp.io/share/omwAzX7E#F51

### Steps to reproduce

```
$client = App::make('aws')->createClient('ec2');

    $instance = $client->requestSpotFleet([

        'SpotFleetRequestConfig' => [

            'IamFleetRole' => 'arn:aws:iam::552724291356:role/aws-ec2-spot-fleet-tagging-role',

            'LaunchSpecifications' => [

                'LaunchTemplateConfigs' => [

                    'LaunchTemplateSpecification' => [

                        'LaunchTemplateId' => 'lt-0783abcs2655143b',

                    ],

                ],

            ],

            'TerminateInstancesWithExpiration' => true,

            'ValidUntil' => Carbon::now()->toDateTimeString(), // work with 5 min instances

            'TargetCapacity' => 1

        ],

    ]);
```

### Additional context
I was trying to create EC2 Spot fleet request using LaunchTemplateId. 
On line 37 we can see that "$this->format($items, $v, $prefix . '.' . **($k + 1)**, $query);"  variable is been increased by 1, but dumping ```$k``` variable returns ```LaunchTemplateConfigs``` string

**Comment by diehlaws** [comment]
Hi @bolovdor, thanks for reaching out. I see a couple of minor misconfigurations in your call's input parameters, the second one is most likely causing the behavior you're running into:

1. `LaunchTemplateConfigs` is not a valid member of `LaunchSpecifications`, both of these parameters should be members of the parent `SpotFleetRequestConfig` array. Additionally, the two parameters are mutually exclusive (you cannot specify `LaunchTemplateConfigs` and `LaunchSpecifications` within the input of the same `requestSpotFleet` call)
2. Your `LaunchTemplateSpecification` parameters should be inside of an array inside `LaunchTemplateConfigs` as shown below
3. A `LaunchTemplateId` specified inside a `LaunchTemplateSpecification` should be accompanied by a `Version` parameter (this can be a string representing the version number, `$Latest`, or `$Default`), also shown below

```php
$client->requestSpotFleet([
    'SpotFleetRequestConfig' => [
        'IamFleetRole' => 'arn:aws:iam::123456789012:role/rolename',
        'LaunchTemplateConfigs' => [
                [
                    'LaunchTemplateSpecification' => [
                        'LaunchTemplateId' => 'lt-1a23b4567cd890f12',
                        'Version' => '1'
                    ]
                ]
            ],
        'TargetCapacity' => 1
    ]
]);
```

I hope this helps! Please do let us know if you still run into problems launching your spot fleet instances after fixing the issues mentioned above.

**Comment by bolovdor** [comment]
Hi Alex @diehlaws , thank you for looking into this issue. Using the provided code snipped above I've manage to request spot fleet instances. Looking through docs again I've realize that I've mix match submitted wrong  launch template configuration. 
I guess I was tired and excised about Christmas holidays and rush this one. Anyway I would like to apologize for wasting time on this (I bet there are more important this to do and my issue :smile:  ) and Thank you for helping me resolve this issue. 
Happy incoming holidays.
