### ISSUE TITLE
GuzzleHttp\ClientInterface::VERSION deprecated

### ISSUE THREAD

**Issue by furester** [aws/aws-sdk-php#1927]
Using GuzzleHttp and aws-sdk from master we get this error:
```
"Undefined class constant 'VERSION' at vendor/aws/aws-sdk-php/src/functions.php:265)"
```
cause they removed the deprecated VERSION constant.

### Version of AWS SDK for PHP?
aws/aws-sdk-php                     3.3.4

### Version of PHP (`php -v`)?
PHP 7.3.3 (cli) (built: Mar  9 2019 00:59:08) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.3, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.3, Copyright (c) 1999-2018, by Zend Technologies

### What issue did you see?
as previous since Dec 8th from Guzzle's ClientInterface VERSION constant is removed

### Steps to reproduce
this is the function that cause the issue:
```function default_http_handler()
{
    $version = (string) ClientInterface::VERSION;
    if ($version[0] === '5') {
        return new \Aws\Handler\GuzzleV5\GuzzleHandler();
    } elseif ($version[0] === '6') {
        return new \Aws\Handler\GuzzleV6\GuzzleHandler();
    } else {
        throw new \RuntimeException('Unknown Guzzle version: ' . $version);
    }
}
```

### Additional context
as in copied function it could be necessary create a new v7 GuzzleHandler

**Comment by diehlaws** [comment]
Hi @furester, thanks for reaching out and I do apologize for the delay in response on our end. PR #1940 introduced support for Guzzle 7 and changed the way in which we determine the version of Guzzle that is being used by the SDK. Using version 3.131.0 or newer of the AWS SDK for PHP should resolve this behavior.

**Comment by pluc** [comment]
This is happening with 3.3.4 @diehlaws 


```
Message: Undefined constant GuzzleHttp\ClientInterface::VERSION
File: vendor/aws/aws-sdk-php/src/functions.php
Line: 265
```

**Comment by SamRemis** [comment]
@pluc, 3.131.0 was released on 1/16/20, 3.3.4 is prior to 2017.  The version numbers are rising; how do you figure that 3.3.x is higher than 3.131.x?

**Comment by pluc** [comment]
Yeah that's my bad. I can't justify how 3.3x was installed on a project that was started a few weeks ago.

**Comment by jfmario** [comment]
I am running to this issue today. Can this issue be reopened?

**Comment by SamRemis** [comment]
@jfmario, which version of the SDK are you running?  This should have been fixed in 3.131.x when we added a check for if the function exists

**Comment by jfmario** [comment]
@SamRemis thank you for the response! i think i am depending on something that is depending on an older version (i'll investigate that). I'm using laravel which is using flysystem to access s3, and hitting the error when trying to get a temporary URL for an S3 file.

**Comment by JonLaliberte** [comment]
Started receiving this error recently. 
Running aws-sdk-php v3.275.6
PHP 7.4.33

```
Fatal error: Uncaught Error: Undefined class constant 'VERSION'in /html/app/library/composer/guzzlehttp/guzzle/src/functions.php: 136 

Stack trace: 
#0/html/app/library/composer/aws/aws-sdk-php/src/Handler/GuzzleV6/GuzzleHandler.php(40): GuzzleHttp\default_user_agent()
#1/html/app/library/composer/aws/aws-sdk-php/src/WrappedHttpHandler.php(88): Aws\Handler\GuzzleV6\GuzzleHandler->__invoke(Object(GuzzleHttp\Psr7\Request),
Array)
#2/html/app/library/composer/aws/aws-sdk-php/src/ClientSideMonitoring/AbstractMonitoringMiddleware.php(126): Aws\WrappedHttpHandler->__invoke(Object(Aws\Command),
Object(GuzzleHttp\Psr7\Request))
#3/html/app/library/composer/aws/aws-sdk-php/src/S3/PermanentRedirectMiddleware.php(43): Aws\ClientSideMonitoring\AbstractMonitoringMiddleware->__i in /html/app/library/composer/guzzlehttp/guzzle/src/functions.php on line 136
```

composer show guzzlehttp/guzzle:
```
name     : guzzlehttp/guzzle
descrip. : Guzzle is a PHP HTTP client library
keywords : client, curl, framework, http, http client, rest, web service
versions : * 6.5.8
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : http://guzzlephp.org/
source   : [git] https://github.com/guzzle/guzzle.git a52f0440530b54fa079ce76e8c5d196a42cad981
dist     : [zip] https://api.github.com/repos/guzzle/guzzle/zipball/a52f0440530b54fa079ce76e8c5d196a42cad981 a52f0440530b54fa079ce76e8c5d196a42cad981
path     : /html/app/library/composer/guzzlehttp/guzzle
names    : guzzlehttp/guzzle

autoload
files
psr-4
GuzzleHttp\ => src/

requires
ext-json *
guzzlehttp/promises ^1.0
guzzlehttp/psr7 ^1.9
php >=5.5
symfony/polyfill-intl-idn ^1.17

requires (dev)
ext-curl *
phpunit/phpunit ^4.8.35 || ^5.7 || ^6.4 || ^7.0
psr/log ^1.1

suggests
psr/log Required for using the Log middleware
```
