### ISSUE TITLE
File Path for PEM file vs. Loading into PHP Variable

### ISSUE THREAD

**Issue by RaviJayagopal** [aws/aws-sdk-php#1928]
Until recently, I was able to store the contents of the .pem file into the database, and then load it in real-time into a PHP variable, and then use that to create a CloudFront signed URL.

```php
//$cfprivkey is contents of the RSA private key stored in db
$privateKey = openssl_get_privatekey($cfprivkey);

$signedURL = $cloudFront->getSignedUrl([
    'url'         => $filename,
    'expires'     => $expires,
    'key_pair_id' => $cfpubkey,
   'private_key' => $privateKey
]);
```

But of late, I'm getting an error:

`Warning: file_exists() expects parameter 1 to be a valid path, resource given in /path/to/vendor/aws/aws-sdk-php/src/CloudFront/Signer.php on line 33
PK file not found: Resource id #262`

Did something change in a recent version of the CloudFront API's in AWS PHP SDK? How was this possible before and why is this breaking now? And more importantly, how can I create a signed URL without having to store the .pem contents into an actual file, and instead load it from the database and pass it as a variable?

All AWS docs are suggesting that I store it as a file and give the path to the file when creating the signed URL, but that's not what I want. Is there no choice any more but to do that?

Thanks!

**Comment by RaviJayagopal** [comment]
Hi @srchase and @diehlaws , just wanted to check what's going to happen with this. Is this a fix you're going to be making to the AWS PHP SDK? What should I expect?

Thanks for your help!

**Comment by diehlaws** [comment]
Hi @RaviJayagopal, thanks for bringing this to our attention. Which version of the AWS SDK for PHP were you using that allowed you to pass your private key as a variable? The most recent change I see to the SDK's CloudFront signer came from PR #1752, however even before this change the signer required the path to the private key file to be used in the signing process.

That being said, this is a change we should be able to implement in a non-breaking manner. Once we get a PR out for this I'll associate this issue so it can close out once the PR is merged.

**Comment by RaviJayagopal** [comment]
Hi @diehlaws,

See attached a screenshot of the Signer.php I have from my previous version when it worked. You can see that it doesn't have the file_exists check.
![signer](https://user-images.githubusercontent.com/58879484/71136014-3d0a3680-21b8-11ea-8f11-4aea831a95cc.png)

That's the version I've been using with my WordPress plugin for a long time.

And then I started running into conflicts with other plugins using the SDK, so I started using Composer, and added a 3.x version dependency, and that's when my plugin's CloudFront calls to get a signed URL started failing, because the latest version of the file has that check:
![signer2](https://user-images.githubusercontent.com/58879484/71136068-6cb93e80-21b8-11ea-97de-57ec69361be8.png)

How would I find out which version of AWS SDK that original file is from? I don't see any version numbers in the files. And I originally downloaded it from either Github or AWS website, can't remember exactly.

**Comment by srchase** [comment]
@RaviJayagopal 

Did you modify your version of Signer.php?

When that Signer class was added to the SDK, it included the file_exists check.  See this commit for the refactor where this class was added:
https://github.com/aws/aws-sdk-php/commit/96ad7073bef47c58b03abab824588337ba6d6551#diff-d519b3d68d95285e04623f6ae4236096

**Comment by RaviJayagopal** [comment]
@srchase,

No, I did not modify anything. In fact, I didn't even know the existence of any of these files or API's until I started getting the file_exists error recently, and only then did I started digging in the old files to see what changed because it was working previously and doesn't work now.

And now, in my latest version of Signer.php, I have commented out the file_exists part so my plugin can continue working the way it was before.

**Comment by RaviJayagopal** [comment]
Just so you guys know: I made a custom change to comment out the file_exists part, and it works fine by itself. And it works fine with some other plugins which use the SDK as well, but there are other plugins that it still conflicts with, those that are using the original SDK as is. So I'm still having issues with getting it to play well with other plugins that are using the unmodified SDK.  

cc: @srchase and @diehlaws

**Comment by RaviJayagopal** [comment]
Thank you!!
