### ISSUE TITLE
Incorrect detection of host-style endpoint pattern while using IP address 

### ISSUE THREAD

**Issue by sigalx** [aws/aws-sdk-php#1953]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?

Latest (3.132.5). Error has began to reproduce since updating from version 3.18.28 to 3.132.5

### Version of PHP (`php -v`)?

Various (reproduced on 7.1 and 7.4 branches)

### What issue did you see?

> exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "PutObject" on "http://test.192.168.74.111:9000/files/76/762b7dc27c00d9243e60361b6b29e865b036d2ec"; AWS HTTP error: cURL error 6: Could not resolve host: test.192.168.74.111 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)'

> GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: test.192.168.74.111 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/html/timebook-dev/protected/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200
Stack trace:
. . .

### Steps to reproduce

Try to upload any object to the storage with this config to bucket named «test»:
>                            'endpoint' => 'http://192.168.74.111:9000',
>                            'credentials' => [
>                                'key' => '***',
>                                'secret' => '***',
>                            ],
>                            'region' => 'us-east-1',
>                            'version' => 'latest',

### Additional context

Possible error in S3EndpointMiddleware.php on line 144 (109) — we only check if bucket name is DNS-compatible but not host too (IP address case)

**Comment by diehlaws** [comment]
Hi @sigalx, thanks for reaching out to us. Starting with [version 3.28.5](https://github.com/aws/aws-sdk-php/blob/master/CHANGELOG.md#3285---2017-05-30) of the AWS SDK for PHP, S3 calls are performed with host-style URLs by default. You can change this behavior by setting `use_path_style_endpoint` to `true` in the service client options as shown below.

```php
$client = new S3Client([
    'region' => 'us-east-1',
    'version' => 'latest',
    'endpoint' => 'http://192.168.74.111:9000',
    'use_path_style_endpoint' => true,
    ]);
```

**Comment by sigalx** [comment]
> Hi @sigalx, thanks for reaching out to us. Starting with [version 3.28.5](https://github.com/aws/aws-sdk-php/blob/master/CHANGELOG.md#3285---2017-05-30) of the AWS SDK for PHP, S3 calls are performed with host-style URLs by default. You can change this behavior by setting `use_path_style_endpoint` to `true` in the service client options as shown below.
> 
> ```
> $client = new S3Client([
>     'region' => 'us-east-1',
>     'version' => 'latest',
>     'endpoint' => 'http://192.168.74.111:9000',
>     'use_path_style_endpoint' => true,
>     ]);
> ```

Thanks for answer, I know about this option, but in this case I mean that option 'use_path_style_endpoint' is unnecessary, because anyway we can't using host-style URLs with endpoint specified by IP address. Like we check bucket name I think we should check host name, m?

**Comment by diehlaws** [comment]
Thanks for the feedback @sigalx. This seems like a reasonable change, and looking at your pull request this doesn't look like a breaking change. I'm relabeling this issue as a feature request, I see @howardlopez is marked as a reviewer for the PR so this should close automatically if the PR is accepted and merged.
