### ISSUE TITLE
postToConnection wrong endpoint, results in a 403 response

### ISSUE THREAD

**Issue by avirdz** [aws/aws-sdk-php#1955]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
3.133.1

### Version of PHP (`php -v`)?
7.4

### What issue did you see?
I can't post a message to a websocket apigateway using the postToConnection method, I always get 403 error.

### Steps to reproduce
```
$config = [
    'region' => $_ENV['AWS_DEFAULT_REGION'],
    'version' => 'latest',
    'endpoint' => 'https://------.execute-api.-----.amazonaws.com/dev',
];

$connectionId = $request->header('x-connection-id');
$apiClient = new ApiGatewayManagementApiClient($config);
$apiClient->postToConnection([
     'ConnectionId' => $connectionId,
     'Data' => json_encode(['status' => 'ok']),
]);
```

### Additional context
This is the error output.
```
Error executing "PostToConnection" on "https://------.execute-api.------.amazonaws.com/@connections/CONNECTION_ID";
AWS HTTP error: Client error: `POST https://------.execute-api.----.amazonaws.com/@connections/CONNECTION_ID` resulted in a `403 Forbidden` response:
{"message":"Forbidden"}....
```

What I'm seeing there is that the method is using the endpoint url without the stage part,
`POST https://------.execute-api.----.amazonaws.com/@connections/CONNECTION_ID` I tried the same request with awscli and it works properly.

**Comment by avirdz** [comment]
Using the endpoint with slash at the end works correctly.

```
$config = [
    'region' => $_ENV['AWS_DEFAULT_REGION'],
    'version' => 'latest',
    'endpoint' => 'https://------.execute-api.-----.amazonaws.com/dev/',
];
```

🤦‍♂

**Comment by tristankelley** [comment]
HI @avirdz - I am working on some similar code and I'm stuck on how to get the connectionId. Would you mind share your code snippet on how you are retrieving it? Thanks.

**Comment by avirdz** [comment]
You can get the connection Id via Header.

`$connectionId = $request->header('X-Connection-Id');`

**Comment by abranasays** [comment]
Check Below link for Connection ID in HTTP Protocol:
https://stackoverflow.com/a/65639742/12571947

I tried above link method and I'm now getting connection id in header.
