### ISSUE TITLE
Basedir restriction

### ISSUE THREAD

**Issue by Ewwe** [aws/aws-sdk-php#1956]
Maybe its duplicate but w/o any working solution 

### Version of AWS SDK for PHP?

3.133.2

### Version of PHP (`php -v`)?
7.4.1

### What issue did you see?
is_readable(): open_basedir restriction in effect. File(**/var/www/clients/client20/web51/.aws/config**) is not within the allowed path(s): (/var/www/clients/client20/web51/web:/var/www/clients/client20/web51/private:/var/www/clients/client20/web51/tmp:/var/www/dev.arkastic.cz/web:/srv/www/dev.arkastic.cz/web:/usr/share/php5:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin:/dev/random:/dev/urandom:**/var/www/clients/client20/web51/.aws/config**)

### Steps to reproduce
Just tryied to upload any image to S3

### Additional context
Im using same application on windows and then when i want to move to production linux , sdk wants me to set open_basedir. But even if i add path to base dir sdk keeps giving me error.
nginx/1.10.3

I found some similiar issues but w/o funciton solution for me.
In any case i dont see any reason why aws wants to get outside of application where its running. website have no reason and no intention to get outside of its assigned space...

**Comment by diehlaws** [comment]
Hi @Ewwe, thanks for reaching out to us about this. as @srchase mentions in [#1931](https://github.com/aws/aws-sdk-php/issues/1931#issuecomment-566681500) the SDK is looking for config options related to CSM, `AWS_S3_US_EAST_1_REGIONAL_ENDPOINT` and `AWS_S3_USE_ARN_REGION` in the config file located at `~/.aws/config` by default. Version 3.132.1 of the AWS SDK for PHP introduced the environment variable `AWS_CONFIG_FILE` which allows you to specify the location in which the SDK will look for the config file. You can point this environment variable to a location within the path(s) allowed in your `open_basedir` config setting and copy your config file to the same location if your use case requires this file so you no longer run into this error.

**Comment by Finesse** [comment]
Copy-paste solutions:

- Set the environment variable to any path (including not existing) inside `open_basedir`. To do it, add this line before creating an `S3Client` object:
    ```php
    putenv('AWS_CONFIG_FILE='.__DIR__.'/dirtyHack.ini');
    ```
- Or if you don't want the SDK to scan the disk, you can provide configurations explicitly:
    ```php
    $s3Client = new Aws\S3\S3Client([
        // ...

        // Works for version 3.137.8
        'use_arn_region' => \Aws\S3\UseArnRegion\ConfigurationProvider::fallback(),
        'csm' => \Aws\ClientSideMonitoring\ConfigurationProvider::fallback(),
        'retries' => \Aws\Retry\ConfigurationProvider::fallback(),
    ]);
    ```
    The default configurations are provided in this example.
