### ISSUE TITLE
How to connect MongoDB srv？ 

### ISSUE THREAD

**Issue by xialamp** [aws/aws-sdk-php#1969]
How to use srv to connect to mogodb in thinkphp6？What should be filled in the database address？

**Comment by diehlaws** [comment]
Hi @xialamp, thanks for reaching out to us. Unfortunately I'm not familiar with thinkphp6 or how it relates to the AWS SDK for PHP.

That being said, you should be able to retrieve the cluster endpoint and reader endpoint for a DocumentDB cluster using a [`describeDBClusters`](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-docdb-2014-10-31.html#describedbclusters) call as shown in the example below.

```php
$resp = $client->describeDBClusters([
    'DBClusterIdentifier' => 'clusterName'
]);

foreach($resp["DBClusters"] as $cluster) {
    echo "Cluster name: {$cluster["DBClusterIdentifier"]}" . PHP_EOL;
    echo "Cluster endpoint: {$cluster["Endpoint"]}" . PHP_EOL;
    echo "Reader endpoint: {$cluster["ReaderEndpoint"]}" . PHP_EOL;
}
```

```
$ php docDB.php 
Cluster name: clusterName
Cluster endpoint: clusterName.cluster-cnofyoxzkvrj.us-west-2.docdb.amazonaws.com
Reader endpoint: clusterName.cluster-ro-cnofyoxzkvrj.us-west-2.docdb.amazonaws.com
```

Please do let us know if you require any assistance using the AWS SDK for PHP.
