### ISSUE TITLE
How to change ACl ?

### ISSUE THREAD

**Issue by coinbreze** [aws/aws-sdk-php#1970]
Hi,
  I need to change the ACL for my existing files.
  How to update the existing files public- read acl to private ?

**Comment by diehlaws** [comment]
Hi @coinbreze, thanks for reaching out to us. You can update the ACL for an object using the [`PutObjectAcl`](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#putobjectacl) call with the appropriate 'ACL' parameter. Please don't hesitate to reach back out if you need assistance with this call.
