### ISSUE TITLE
Route53 checkDomainAvailability don´t work....

### ISSUE THREAD

**Issue by marcelosboeira** [aws/aws-sdk-php#1972]
Hello everyone, 
I'm trying to use checkDomainAvailability  "https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Route53.Route53Client.html" but it doesn't work. 

My code is...

```php
use Aws\Route53Domains\Route53DomainsClient;
use Aws\Exception\AwsException;
use Aws\Credentials\Credentials;
$credentials = new Credentials(gS3ClientKey, gS3ClientSecret);
$gRoute53Domains = Route53DomainsClient::factory(array(
	'region'      => 'us-east-2',
	'version'     => '2014-05-15',
       'credentials' => $credentials
));
$domain = (isset($_POST['domain']) ? $_POST['domain'] : ''); 
if ($domain) {
        try {
          $result = $this->gRoute53Domains->checkDomainAvailability([
            'DomainName' => $domain,
          ]);
        } catch (Exception $e) {
          echo 'Exceção capturada: ',  $e->getMessage(), "\n";
        }
}
```

*And the result is:* 
`Error executing "CheckDomainAvailability" on "https://route53domains.us-east-2.amazonaws.com"; AWS HTTP error: cURL error 6: Could not resolve host: route53domains.us-east-2.amazonaws.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

**Comment by marcelosboeira** [comment]
I found the problem .... these services only work with the us-east-1 region.. 
So the code is: 
$gRoute53Domains = Route53DomainsClient::factory(array(
	'region'      => 'us-east-1',
	'version'     => '2014-05-15',
    'credentials' => $credentials
));

**Comment by diehlaws** [comment]
Hi @marcelosboeira, thanks for reaching out to us. Per the [Amazon Route 53 Endpoints and Quotas](https://docs.aws.amazon.com/general/latest/gr/r53.html) documentation page, the only available endpoint for a `Route53DomainsClient` is in us-east-1. Calls for the `Route53Client` and `Route53ResolverClient` can be made to the AWS regions mentioned in the link above.
