### ISSUE TITLE
Need method to generate SRP_A for authflow USER_SRP_AUTH for InitiateAuth.

### ISSUE THREAD

**Issue by vivekpipaliya** [aws/aws-sdk-php#1979]
### Is this related to a problem?
I want to use USER_SRP_AUTH for InitiateAuth in my application to log the user's device info into Cognito. But I need to pass "SRP_A" as AuthParameters in the request. And we don't have any method in SDK to generate "SRP_A" in the **current** SDK.

### Feature description
It is better if we have the method to generate "SRP_A" in SDK so we can generate it easily.

**Comment by vivekpipaliya** [comment]
Any response on this?

**Comment by sdrenth** [comment]
@vivekpipaliya Do you know how the SRP_A value can be generated by yourself?

**Comment by vivekpipaliya** [comment]
@sdrenth No, I don't know that. Let me know if you know that I am still finding the solution for it.

**Comment by sdrenth** [comment]
@vivekpipaliya I'm not able yet to connect using initiateAuth, but I believe that might have a different cause. I keep receiving this error:

> Error retrieving credentials from the instance profile metadata service. (cURL error 7:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html))

I believe this might work, but due to the error above I'm not sure if this works or not:

**SRP flow scheme:**
https://code.falk-m.de/srp/

**Source code:**
https://github.com/falkmueller/srp/

Please let me know if that works for you.

**Comment by vivekpipaliya** [comment]
Thanks for that... I will try to generate SRP_A using this library and let you know if it works.

**Comment by sdrenth** [comment]
@vivekpipaliya The initiateAuth method is working for me now:
```
$client = new CognitoIdentityProviderClient([
    'version' => 'latest',
    'region'  => 'eu-west-1',
    'credentials' => false,
]);

$srp = new Srp();
$a = $srp->getRandomSeed();
$A = $srp->generateA($a);

$result = $client->initiateAuth([
    'UserPoolId'     => 'USER_POOL_ID',
    'ClientId'       => 'CLIENT_ID',
    'AuthFlow'       => 'USER_SRP_AUTH',
    'AuthParameters' => [
        'USERNAME' => 'USERNAME',
        'SRP_A'    => $A
    ]
]);
```

Currently I'm struggling to find out how I should implement the `respondToAuthChallenge`. I'll let you know if I've found out how that should be done.

**Comment by vivekpipaliya** [comment]
What is the "[ChallengeName](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_RespondToAuthChallenge.html#CognitoUserPools-RespondToAuthChallenge-request-ChallengeName)" you are receiving in the response of initiateAuth method?

**Comment by sdrenth** [comment]
@vivekpipaliya PASSWORD_VERIFIER is the challenge name I received and believe that that is correct. 

I'm currently stuck at the PASSWORD_CLAIM_SIGNATURE parameter in the respondToAuthChallenge.

**Comment by vivekpipaliya** [comment]
What did you pass for TIMESTAMP?

**Comment by vivekpipaliya** [comment]
I am on the same stage and getting this error.
Unable to verify secret hash for client xxxxxxxx

**Comment by vivekpipaliya** [comment]
@sdrenth I am getting **Unable to verify secret hash for client xxxxxxxx** on respondToAuthChallenge request.

**Comment by sdrenth** [comment]
@vivekpipaliya This is what I used for the date:
```$date = date('D M d H:i:s T Y');```

I'm using the code below for the respondToAuthChallenge method:
```
$date = date('D M d H:i:s T Y');

$srp = new Srp();
$a = $srp->getRandomSeed();
$A = $srp->generateA($a);

$challengeParameters = $result->get('ChallengeParameters');

$s = $srp->getRandomSeed();
$x = $srp->generateX($s, 'MY_USERNAME', 'MY_PASSWORD');
$S = $srp->generateS_Client($A, $challengeParameters['SRP_B'], $a, $x);
$K = $srp->generateK($S);

$response = $client->respondToAuthChallenge([
    'ChallengeName'      => 'PASSWORD_VERIFIER',
    'ClientId'           => 'CLIENT_ID',
    'ChallengeResponses' => [
        'TIMESTAMP'                   => $date,
        'USERNAME'                    => $challengeParameters['USER_ID_FOR_SRP'],
        'PASSWORD_CLAIM_SECRET_BLOCK' => $challengeParameters['SECRET_BLOCK'],
        'PASSWORD_CLAIM_SIGNATURE'    => hash_hmac('sha256', $K, $challengeParameters['SALT'])
    ]
]);
```
This gives me this error:

> Bad Request` response:
> {"__type":"NotAuthorizedException","message":"Incorrect username or password."}

This will probably because because my PASSWORD_CLAIM_SIGNATURE is incorrect, I haven't really found out what this key should contain as a value.

**Comment by vivekpipaliya** [comment]
Maybe you can take help of this Java code to generate PASSWORD_CLAIM_SIGNATURE

https://github.com/aws-samples/aws-cognito-java-desktop-app/blob/master/src/main/java/com/amazonaws/sample/cognitoui/AuthenticationHelper.java#L266

**Comment by vivekpipaliya** [comment]
@sdrenth Did you find any solution to generate PASSWORD_CLAIM_SIGNATURE? We are both on the same page.

**Comment by sdrenth** [comment]
@vivekpipaliya Unfortunately not yet

**Comment by sdrenth** [comment]
@vivekpipaliya Thank you for creating the thread on Amazon Forums, I was just going to do that when I noticed your thread. If anyone else is interested in this, the thread is found here:
https://forums.aws.amazon.com/thread.jspa?threadID=321244&tstart=0

**Comment by vivekpipaliya** [comment]
@sdrenth I am trying to use USER_SRP_AUTH to remember devices functionality. Is there any reason you are using USER_SRP_AUTH? If you just want to login user then you can use adminInitiateAuth with ADMIN_NO_SRP_AUTH

**Comment by sdrenth** [comment]
@vivekpipaliya It's a requirement from the client that I implement the `initiateAuth` method, according to them the adminInitiateAuth` method is not an option. Also they've implemented it for Java/Python before and are helping me as well.

I'm unable to find any documentation about how to generate the PASSWORD_CLAIM_SIGNATURE.

**Comment by vivekpipaliya** [comment]
@sdrenth You can move to the bottom of the page from below link and check this thing if that helps you to generate PASSWORD_CLAIM_SIGNATURE.

[https://aws.amazon.com/premiumsupport/knowledge-center/cognito-user-pool-remembered-devices/](https://aws.amazon.com/premiumsupport/knowledge-center/cognito-user-pool-remembered-devices/
)

![image](https://user-images.githubusercontent.com/60814309/80583791-4f319680-8a2e-11ea-8e0a-b1b48763cf55.png)

Actually I have also tried different methods to generate PASSWORD_CLAIM_SIGNATURE but was not able to generate it correctly. That's why I posted this thing on both AWS Forum and StackOverflow

Here is the link for StackOverflow question

[https://stackoverflow.com/questions/61495005/couldnt-generate-correct-password-claim-signature-in-php-for-cognito](https://stackoverflow.com/questions/61495005/couldnt-generate-correct-password-claim-signature-in-php-for-cognito)

**Comment by sdrenth** [comment]
@vivekpipaliya I think it would need to be something like this (untested):
SHA256_HMAC(K_USER, USERPOOL_ID (without region) + USERID_FOR_SRP + base64 decoded PASSWORD_CLAIM_SECRET_BLOCK + TIMESTAMP), base64-encoded

**Comment by vivekpipaliya** [comment]
Hi, @sdrenth Did you found any solution?

**Comment by sdrenth** [comment]
@vivekpipaliya I haven't had any time yet to test the value of my previous comment yet.

**Comment by lukecleland-myfiziq** [comment]
I found the Capless Warrant Python code very helpful in understanding the whole process.

https://github.com/capless/warrant/blob/ff2e4793d8479e770f2461ef7cbc0c15ee784395/warrant/aws_srp.py#L93

**Comment by chuelsmann** [comment]
@sdrenth Any updates here? I'm running into the exact same issue. Just receiving "Incorrect username or password." Also tried several different generated signatures without success.

**Comment by sdrenth** [comment]
@chuelsmann I ended up using a workaround with calling a JAR file that was provided to me by a third-party, so I cannot be of help here. When calling the JAR file I had some issues with the password encoding, by using a password with only **!** and no weird characters helped me getting it to work. So maybe that is something for you to consider as well. Hopefully, you'll be able to get it to work.

**Comment by SANiMirrorOfLight** [comment]
I've implemented the PASSWORD_CLAIM_SIGNATUR calculation on PHP and compare it with CognitoUser.js of my Amplify application.

The PHP application generates the same PASSWORD_CLAIM_SIGNATUR as the CognitoUser.js library for the same input properties.

But anyway in the PHP I receive "Incorrect username or password." response while JS application passes authentication successfully.

Is there something wrong with the PHP SDK? Is it possible to receive any details about what is going wrong from AWS?

**Comment by sdrenth** [comment]
@SANiMirrorOfLight I've had the same issue. I tested on my Windows machine where I was able to login using the same credentials and on my Macbook I was unable to, this was due to:

> When calling the JAR file I had some issues with the password encoding, by using a password with only ! and no weird characters helped me getting it to work. So maybe that is something for you to consider as well. Hopefully, you'll be able to get it to work.

**Comment by SANiMirrorOfLight** [comment]
@sdrenth I've tried using a password without "!" but anyway Cognito returned "Incorrect username or password.". Also, I don't think that there is an encoding issue in my case because it seems like my PHP program code generates the same PASSWORD_CLAIM_SIGNATUR hash as CognitoUser.js library.

> @SANiMirrorOfLight I've had the same issue. I tested on my Windows machine where I was able to login using the same credentials and on my Macbook I was unable to, this was due to:

**Comment by sdrenth** [comment]
@SANiMirrorOfLight I removed all weird characters from my password except "!", because at least 1 character was required, so I ended up with a password with looks something like:
**1234abcdefgh!**

But I can't help you any further unfortunately because I was unable to find out how to generate it using PHP (as in, it would take way to much time). So I ended up calling a JAR file in PHP which handled the AWS authentication part for me using JAVA. Maybe something like that would work for you as well.

So I ended up with something like this, where I pass the authentication details to the JAR file as parameters:
`exec('/my_jar_file.jar param1 param2', $response);`

**Comment by jviney** [comment]
I converted the Python version linked above to Ruby. Here is the gist in case anyone finds it useful.

https://gist.github.com/jviney/5fd0fab96cd70d5d46853f052be4744c

This could be translated to PHP as well quite easily.

**Comment by jenky** [comment]
Just in case if you guys still need it. I converted Capless Warrant Python code to PHP. 

https://gist.github.com/jenky/a4465f73adf90206b3e98c3d36a3be4f

It supports only `USER_SRP_AUTH` flow, feel free to edit or make any changes you deem necessary.

**Comment by SANiMirrorOfLight** [comment]
> Just in case if you guys still need it. I converted Capless Warrant Python code to PHP.
> 
> https://gist.github.com/jenky/a4465f73adf90206b3e98c3d36a3be4f
> 
> It supports only `USER_SRP_AUTH` flow, feel free to edit or make any changes you deem necessary.

It is a good idea to use the BigInteger here, I have used the DC Math function in my lib. But anyway both variants, your and my, do not work in my case because I have negative` $intValue2` and `bcpowmod` cannot work correctly with a negative value. In the case of using the BigInteger library, I received positive ` $intValue2` but the `s` value is calculated with the wrong value in this case.

This way, in my lib I use the python script for calculating the correct `s` value.

Maybe I am missing anything? Have anyone tested this with AWS SRP authorization?

**Comment by jenky** [comment]
It worked for me, maybe you could try to debug the calculated a, A, s, u values from both `python` and `php` to see the differences.

**Comment by dilshanfupay** [comment]
Did someone found any solution?

**Comment by dilshanfupay** [comment]
> Did someone found any solution?



> We have noticed this issue has not recieved attention in 1 year. We will close this issue for now. If you think this is in error, please feel free to comment and reopen the issue.

Please reopen this issue

**Comment by YashvirGaming** [comment]
@vivekpipaliya
@jenky @sdrenth @SANiMirrorOfLight @marco3211  @

![image](https://user-images.githubusercontent.com/64865096/195914122-0bb5ea6b-15c4-4fdf-8ada-299c1839e259.png)
So in my case here is the SALT , and Secret_BLOCK
Now I simply do and HMAC SHA256 on this
![image](https://user-images.githubusercontent.com/64865096/195914734-f8c29bf2-39cc-4494-998d-062ee4d5060c.png)
![image](https://user-images.githubusercontent.com/64865096/195914912-516991b1-0898-4915-b453-30309fc98779.png)

Then in POST DATA just replaced the Variable name 
EASY SOOOO EASY 
![image](https://user-images.githubusercontent.com/64865096/195915273-eb468079-0692-4e72-8b65-f2abb1efd375.png)


**Result success Full Capture** 
![image](https://user-images.githubusercontent.com/64865096/195915564-78f955a4-355b-458a-834c-37f57aecb5b2.png)

**Comment by abubakarberete8** [comment]
> @vivekpipaliya @jenky @sdrenth @SANiMirrorOfLight @marco3211 @
> 
> ![image](https://user-images.githubusercontent.com/64865096/195914122-0bb5ea6b-15c4-4fdf-8ada-299c1839e259.png) So in my case here is the SALT , and Secret_BLOCK Now I simply do and HMAC SHA256 on this ![image](https://user-images.githubusercontent.com/64865096/195914734-f8c29bf2-39cc-4494-998d-062ee4d5060c.png) ![image](https://user-images.githubusercontent.com/64865096/195914912-516991b1-0898-4915-b453-30309fc98779.png)
> 
> Then in POST DATA just replaced the Variable name EASY SOOOO EASY ![image](https://user-images.githubusercontent.com/64865096/195915273-eb468079-0692-4e72-8b65-f2abb1efd375.png)
> 
> **Result success Full Capture** ![image](https://user-images.githubusercontent.com/64865096/195915564-78f955a4-355b-458a-834c-37f57aecb5b2.png)

Hello! Im trying to generate password_claim_signature and use your values, please tell me, what the hmac key did you use? How did you generate your hmac key?
