### ISSUE TITLE
File not found.. 

### ISSUE THREAD

**Issue by iiLearner** [aws/aws-sdk-php#1980]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
latest

### Version of PHP (`php -v`)?
7.1.32

### What issue did you see?
Hey, so basically I just started using aws sdk to upload files to amazon S3 so I grabbed sample code just to test but apparently even that does not work...bellow's the code: 
```php
<?php

	if(isset($_FILES['image'])){

		$file_name = $_FILES['image']['name'];   
		$temp_file_location = $_FILES['image']['tmp_name']; 
        require 'vendor/autoload.php';

        // Instantiate an Amazon S3 client.
        $s3 = new S3Client([
            'version' => 'latest',
            'region'  => 'eu-west-3',
            'credentials' => [
                'key'    => "hidden",
                'secret' => "hidden",
            ],
        ]);
        try {
            $result = $s3->putObject([
                'Bucket' => 'bucapp',
                'Key'    => $file_name,
                'SourceFile' => $temp_file_location
            ]);
            var_dump($result);
        } catch (Aws\S3\Exception\S3Exception $e) {
            echo "There was an error uploading the file.\n";
        }
		;
	}
?>

<form action="<?= $_SERVER['PHP_SELF']; ?>" method="POST" enctype="multipart/form-data">         

	<input type="file" name="image" />

	<input type="submit"/>

</form>
```

I'm getting this: 

> Warning: require(D:\xampp\htdocs\bukapp\vendor\composer/../../src/add_bucket_acl.php): failed to open stream: No such file or directory in D:\xampp\htdocs\bukapp\vendor\composer\autoload_real.php on line 66

> Fatal error: require(): Failed opening required 'D:\xampp\htdocs\bukapp\vendor\composer/../../src/add_bucket_acl.php' (include_path='D:\xampp\php\PEAR') in D:\xampp\htdocs\bukapp\vendor\composer\autoload_real.php on line 66

**Comment by diehlaws** [comment]
Hi @iiLearner, thanks for reaching out to us. This sounds like an issue with the packages required via composer. The file `add_bucket_acl.php` mentioned in the error does not exist within the AWS SDK for PHP, you'll need to determine where this file is coming from. Reviewing the packages listed in `composer.json` in the directory above your `vendor` directory is a good place to start. 

If you're just testing the functionality of the SDK, this file should only contain `"aws/aws-sdk-php": "^3.133"` in the `require` object of your `composer.json` file. If this file contains other required packages you may want to ensure these packages work as expected.
