### ISSUE TITLE
PHP Warning:  session_set_save_handler(): Cannot change save handler when session is active

### ISSUE THREAD

**Issue by carlo-fontanos** [aws/aws-sdk-php#1981]
Hi,

I just installed the SDK v3 and attempted to setup the DynamoDB Session Handler as seen bellow:

```
<?php 
error_reporting(1);

require_once('vendor/autoload.php');

use Aws\DynamoDb\DynamoDbClient;
use Aws\DynamoDb\SessionHandler;

$dynamoDb = new DynamoDbClient(array(
	'key' 		=> 'AWS_CRED_KEY',
	'secret' 	=> 'AWS_CRED_SECRET',
	'region' 	=> 'AWS_CRED_REGION',
	'version' 	=> '2012-08-10'
));

$sessionHandler = SessionHandler::fromClient($dynamoDb, array(
	'table_name'		=> 'AWS_SESSIONS_TBL',
	'automatic_gc'		=> false,
	'locking'    		=> true
));

$sessionHandler->register();

session_start();
```

But I am getting the following error: 

```
PHP message: PHP Warning:  session_set_save_handler(): Cannot change save handler when session is active in /var/www/mysite/vendor/aws/aws-sdk-php/src/DynamoDb/SessionHandler.php on line 93"
```

I am using PHP 7.4

How do I fix this error please? 

Thanks,
Carl

**Comment by carlo-fontanos** [comment]
Any update on this please?

**Comment by diehlaws** [comment]
Hi @carlo-fontanos, thanks for reaching out to us about this and I do apologize for the long delay in response on our end. When reproducing this, I saw similar warnings if I included any echo statements in the script used to test this. After removing these echo statements the following snippet worked as expected, and I was able to see the changes to the session in the DynamoDB table being used for sessions:

 <details><summary>Code:</summary>
 
```php
<?php

require_once('..\..\vendor\autoload.php');

use Aws\DynamoDb\DynamoDbClient;
use Aws\DynamoDb\SessionHandler;

$dynamoDb = new DynamoDbClient(array(
    'region' 	=> 'us-west-2',
    'version' 	=> '2012-08-10',
));

$sessionHandler = SessionHandler::fromClient($dynamoDb, array(
	'table_name'		=> 'session_test_2',
	'automatic_gc'		=> false,
	'locking'    		=> true
));

$sessionHandler->register();

session_start();
$_SESSION['some.value'] = 'foo';
$_SESSION['another.value'] = 'bar';


session_write_close();
```
</details>

[This](https://bugs.php.net/bug.php?id=75628) bug report should help shed additional light on the cause for this behavior.
