### ISSUE TITLE
S3EncryptionClient breaking in PHP >= 7.4.2 due to EncryptionTrait and AbstractCryptoClient class defining same method with different visibility

### ISSUE THREAD

**Issue by ingluisjimenez** [aws/aws-sdk-php#1983]
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for PHP?
3.133.33

### Version of PHP (`php -v`)?
7.4.3, 7.4.2

### What issue did you see?
`PHP Fatal error:  Access level to Aws\Crypto\EncryptionTrait::encrypt() must be public (as in class Aws\Crypto\AbstractCryptoClient) in vendor/aws/aws-sdk-php/src/S3/Crypto/S3EncryptionClient.php on line 51`

### Steps to reproduce
Any attempts to use S3EncryptionClient in PHP >= 7.4.2 run into the issue above, as both the EncryptionTrait and the AbstractCryptoClient class are defining the `encrypt` method, but 

### Additional context
Seems like due to some internal changes as part of this bugfix https://bugs.php.net/bug.php?id=78776, the setup in the S3EncryptionClient is no longer supported, where both the AbstractCryptoClient class and the EncryptionTrait are defining the encrypt() method, but one is public and the other one is protected.

**Comment by diehlaws** [comment]
Hi @ingluisjimenez, thanks for bringing this to our attention. I've marked this as a bug, it seems like PR #1984 should fix this so we'll work toward merging this in as appropriate.

**Comment by diehlaws** [comment]
As the fix for this was implemented in version 3.133.38 I'll be closing out the issue. Please do let us know if you continue running into this behavior.
