### ISSUE TITLE
Provide ordering (query?) features to describeImages

### ISSUE THREAD

**Issue by ktecho** [aws/aws-sdk-php#1987]
I would like to use the SDK to ask for all the AMIs that starts with a name (I can already do that) but ordered by CreationDate, the same as you can do with the command line SDK:

[https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/finding-an-ami.html](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/finding-an-ami.html)

(search for "Example: Find the current Red Hat Enterprise Linux 7.5 AMI")

That way I could use the latest AMI starting with a name without having to sort by date manually.

Thanks!

**Comment by diehlaws** [comment]
Hi @ktecho, thanks for reaching out to us. The [`query` option](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-output.html#cli-usage-output-filter) for the AWS CLI uses [JMESPath](https://jmespath.org/) to extract elements from the service's response according to the expression used. The same expressions can be used with the `search()` method on the response to a service call as shown [here](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_jmespath.html).

**Comment by ktecho** [comment]
@diehlaws Works great. Didn't knew that JMESPath stuff. Thanks!
