### ISSUE TITLE
How to get configuration value in the AWS config file.

### ISSUE THREAD

**Issue by nvcken** [aws/aws-sdk-php#2005]
Likes CLI built-in supported
`aws configure get role_arn --profile=abc`

My ~/.aws/config
```
[default]
region = ap-southeast-1
output = json

[profile dev]
role_arn = ROLE_WANT_TO_ASSUME
source_profile = default
role_session_name = my_role_name
mfa_serial = MY_MFA_SERIAL
```
Because I want to get the `role_arn` and `role_session_name` in config file for `assumeRole` call
```
$result = $stsClient->assumeRole(array(
    'RoleArn' => <get role_arn of dev profile in config file>,
    'RoleSessionName' => <get role_arn of dev profile in config file>,
...)
```

**Comment by cuongngoz** [comment]
My ~/.aws/config
```
[default]
region = ap-southeast-1
output = json

[profile dev]
role_arn = ROLE_WANT_TO_ASSUME
source_profile = default
role_session_name = my_role_name
mfa_serial = MY_MFA_SERIAL
```
Because I want to get the `role_arn` and `role_session_name` in config file for `assumeRole` call

$result = $stsClient->assumeRole(array(
    'RoleArn' => <get role_arn of dev profile in config file>,
    'RoleSessionName' => <get role_arn of dev profile in config file>,
...)

**Comment by diehlaws** [comment]
Hi @nvcken, thanks for reaching out to us. Unfortunately the AWS SDK for PHP does not have a class similar to the CLI's `configure` with a function that retrieves a given value for the specified profile. That being said, you can use the SDK's [`INI parser`](https://docs.aws.amazon.com/aws-sdk-php/v3/api/function-Aws.parse_ini_file.html) on your shared config file to retrieve these values as shown below.

```php
$filename = '~/.aws/config';
$process_sections = true;
$profiles = Aws\parse_ini_file($filename, $process_sections);

$roleArn = $profiles['dev']['role_arn'];
$sessionName = $profiles['dev']['role_session_name'];
$mfaSerial = $profiles['dev']['mfa_serial'];

$client = new StsClient([
    'region' => 'us-east-1',
    'version' => 'latest',
]);

$resp = $stsClient->assumeRole(array(
    'RoleArn' => $roleArn,
    'RoleSessionName' => $sessionName,
    'SerialNumber' => $mfaSerial,
...)
```

**Comment by nvcken** [comment]
Thanks
