### ISSUE TITLE
guzzle version wrong? undefined function

### ISSUE THREAD

**Issue by LiamDawe** [aws/aws-sdk-php#2006]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
Just doesn't seem to work. I'm trying to query my current file list on a Digital Ocean Space. Looks like it's trying to get a function that doesn't exist.

> Warning: Use of undefined constant IDNA_DEFAULT - assumed 'IDNA_DEFAULT' (this will throw an Error in a future version of PHP) in /media/storage/website/public_html/includes/aws/GuzzleHttp/Client.php on line 219
> 
> Fatal error: Uncaught Error: Call to undefined function GuzzleHttp\idn_to_ascii() in /media/storage/website/public_html/includes/aws/GuzzleHttp/Utils.php:35 Stack trace: #0 /media/storage/website/public_html/includes/aws/GuzzleHttp/Client.php(220): GuzzleHttp\Utils::idnUriConvert(Object(GuzzleHttp\Psr7\Uri), 'IDNA_DEFAULT') #1 /media/storage/website/public_html/includes/aws/GuzzleHttp/Client.php(113): GuzzleHttp\Client->buildUri(Object(GuzzleHttp\Psr7\Uri), Array) #2 /media/storage/website/public_html/includes/aws/Aws/Handler/GuzzleV6/GuzzleHandler.php(43): GuzzleHttp\Client->sendAsync(Object(GuzzleHttp\Psr7\Request), Array) #3 /media/storage/website/public_html/includes/aws/Aws/WrappedHttpHandler.php(87): Aws\Handler\GuzzleV6\GuzzleHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array) #4 /media/storage/website/public_html/includes/aws/Aws/ClientSideMonitoring/AbstractMonitoringMiddleware.php(126): Aws\WrappedHttpHandler->__invoke(Object(Aws\Command), Object(GuzzleHttp\Psr7\Request)) #5 /media/storage/website/public_h in /media/storage/website/public_html/includes/aws/GuzzleHttp/Utils.php on line 35

**Version of AWS SDK for PHP?**
Example: 3.137.6

**Version of PHP (`php -v`)?**
7.4.5

**To Reproduce (observed behavior)**
Download the aws php package, include as normal using _aws-autoloader_ and try to do anything.

Looking around, other projects had the same issue. It appears to happen in later versions of Guzzle. MediaWiki had the issue too, so they seemed to [force a specific](https://github.com/edwardspec/mediawiki-aws-s3/commit/32c80a2511425db537c589f39f8ce98bec913587) older Guzzle version.

Testing myself, by overwriting with Guzzle 6.3.3 it now works. So something needs to be done here.

**Comment by Nyholm** [comment]
Hey. Guzzle maintainer here. 

The problem is that you have two different guzzle versions installed and loaded. 

This error is fixed if you update one of them to 6.5.3.

**Comment by LiamDawe** [comment]
Nothing else in my project uses Guzzle.

**Comment by Nyholm** [comment]
That is not what I said. 

I said that you have two version of Guzzle loaded in your PHP runtime at the same time. That is why you are getting the error. 

--- 

Also, did you try my solution?

**Comment by LiamDawe** [comment]
> That is not what I said.

Apologies, it wasn't overly clear you meant loaded into PHP and not the project I am on.

> Also, did you try my solution?

Yes, doesn't work. 6.3.3 does.

**Comment by bluusun** [comment]
I can confirm the same issue under PHP 7.3 when using AWS SDK (accessing an S3 bucket). Downgrading guzzlehttp to 6.3.3 worked for me.

**Comment by diehlaws** [comment]
Thanks for reaching out to us about this @LiamDawe and @bluusun (and thanks for chiming in on this @Nyholm!). While I'm unable to reproduce this when downloading the AWS SDK for PHP via composer, I do see this behavior if I import version 3.137.6 of the SDK via the .phar and .zip releases. 

Looking further into this it seems like our .zip and .phar packages aren't including the package `symfony/polyfill-intl-idn` required by Guzzle 6.5.3 which is where the constant `IDNA_DEFAULT` is being defined for this version of Guzzle. I'll submit a PR that includes this package in our build shortly.

In the meantime, `IDNA_DEFAULT` is a constant defined in the [Intl](https://www.php.net/manual/en/intl.constants.php) extension, enabling this extension in PHP should resolve this behavior.

**Comment by marcioarp** [comment]
Hi, I put this line on my script, and works fine. (copied from symfony/polyfill-intl-idn) 

define('IDNA_DEFAULT',0);

**Comment by saruman** [comment]
Thank you @Nyholm ! your suggestion help me a lot.
I had another module using guzzle in the same project.

**Comment by mdevbd** [comment]
> 6.3.3

Yes it also worked for me when downgraded, it was happening with Magento, when Magento default vendor guzzle was loaded with custom module's third-party AWS SDK library guzzle and conflicted both version.
