### ISSUE TITLE
How to send bulk email to user

### ISSUE THREAD

**Issue by iamanupammaity** [aws/aws-sdk-php#2009]
How to send 'html_body' emails to different users in a single hit without sendEmailBulkWithTemplate. 
The same content to many recipients.

**Comment by diehlaws** [comment]
Thanks for reaching out to us @iamanupammaity. Please keep in mind that guidance requests for a given service should be submitted to our Premium Support team via a [new technical support case](https://console.aws.amazon.com/support/home#/case/create) as they will have a better understanding of how to effectively interact with the service itself. 

That being said, while the [`SendEmail`](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-email-2010-12-01.html#sendemail) call does support multiple addresses in each `Destination` field in the input, the SES documentation for [sending email](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/choose-email-sending-method.html) recommends sending emails to one recipient at a time:

> When you send an email to multiple recipients (recipients are "To", "CC", and "BCC" addresses) and the call to Amazon SES fails, the entire email is rejected and none of the recipients will receive the intended email. We therefore recommend that you send an email to one recipient at a time.

**Comment by iamanupammaity** [comment]
Thank you.
Using BccAddresses how many recipient emails address I can add in one time?
