### ISSUE TITLE
How can I get email send history

### ISSUE THREAD

**Issue by iamanupammaity** [aws/aws-sdk-php#2011]
Using hit an API call can I get the last 1 days or 2 days email sent history in SES. The data output link email sent id, email id, subject, time etc.

**Comment by diehlaws** [comment]
Hi @iamanupammaity, as with #2009 this question is better geared toward our [Premium Support team](https://console.aws.amazon.com/support/home#/case/create). As far as I'm aware, SES does not make sent email history available via the API or the web console. You can retrieve statistics for your sent emails via the [`GetSendStatistics`](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-email-2010-12-01.html#getsendstatistics) call but this will not show the data you're looking for regarding individual emails you've sent via SES. 

Looking through our Premium Support Knowledge Center I see the [Store and Visualize Your Amazon SES Email Sending History](https://aws.amazon.com/premiumsupport/knowledge-center/ses-email-sending-history/) article that explains how to use Amazon ElasticSearch and Amazon Kinesis to store and visualize your SES sending history, this should help you find the data you're looking for regarding emails you've sent via SES.
