### ISSUE TITLE
Incorrect path for .aws credentials - double slashes

### ISSUE THREAD

**Issue by kkmuffme** [aws/aws-sdk-php#2012]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
In AWS/Credentials/CredentialProvider.php there are multiple `self::getHomeDir() . '/.aws/...'` which leads to incorrect paths containing 2 slashes, as getHomeDir already contains a trailing slash.

To fix this (must be changed in all places in this file that uses getHomeDir), the leading slash of /.aws must be removed:
![image](https://user-images.githubusercontent.com/11071985/81778101-7c804900-94f2-11ea-86d0-15fd5238a8fa.png)

**Version of AWS SDK for PHP?**
v3.137.3

**Version of PHP (`php -v`)?**
7.3.5

**To Reproduce (observed behavior)**
Not necessary/just run any command and you see it

**Expected behavior**
No double slashes

**Screenshots**
See above

**Comment by diehlaws** [comment]
Hi @kkmuffme, thanks for reaching out to us. Which OS are you using where the current behavior results in the shared config file loading properly? The default $HOME location in Ubuntu and OSX does not contain a trailing slash, and the only case in which `getHomeDir` returns a path with a trailing slash in Windows is if the $HOMEPATH is set to the root of a drive - even then, the OS should ignore the second slash and the shared config file should load as expected. It looks like there are varied opinions ([1](https://stackoverflow.com/questions/980255/should-a-directory-path-variable-end-with-a-trailing-slash), [2](https://serverfault.com/questions/876317/what-to-do-with-trailing-slash-in-home-on-centos), [3](https://unix.stackexchange.com/questions/212805/should-i-use-a-slash-at-the-end-of-path-variables-in-shell-script-or-not)) on whether a path in an environment variable should contain a trailing slash, however the general concensus seems to be that even if it does the OS should ignore multiple successive slash characters in a path.

I modified [`loadDefaultProfiles`](https://github.com/aws/aws-sdk-php/blob/master/src/Credentials/CredentialProvider.php#L665) locally (`echo "Config file is at {$configFile}\nConfig file present: "; echo file_exists($configFile) ? 'yes' : 'no'; echo PHP_EOL;`) to show the config file location retrieved via `getHomeDir` and determine whether the file exists, this appears to load the shared config file as expected in OSX, Ubuntu 18.04, and Windows 10 using the following script.

<details><summary>Code</summary>

```php
<?php


require_once("./vendor/autoload.php");

use Aws\Sts\StsClient;
use Aws\Exception\AwsException;

echo "Using AWS SDK for PHP version " . Aws\Sdk::VERSION . PHP_EOL;
$home = getenv('HOME');
$homedrive = getenv('HOMEDRIVE');
$homepath = getenv('HOMEPATH');
echo "Environment variables:" . PHP_EOL;
echo "HOME: {$home}\nHOMEDRIVE: {$homedrive}\nHOMEPATH: {$homepath}" . PHP_EOL;


$client = new StsClient([
    'region' => 'us-west-2',
    'version' => 'latest',
    // 'debug' => true,
    ]);


try {
    $resp = $client->getCallerIdentity();
    echo $resp['Arn'] . PHP_EOL;

} catch (AwsException $e) {
    echo "Sts error: {$e->getMessage()}" . PHP_EOL;
}
```

</details>

<details><summary>Output</summary>

OSX:

```
$ php homeDir.php 
Using AWS SDK for PHP version 3.138.0
Environment variables:
HOME: /Users/diehlaws
HOMEDRIVE: 
HOMEPATH: 
Config file is at /Users/diehlaws/.aws/config
Config file present: yes
arn:aws:iam::<account-id>:user/diehlaws
```

Ubuntu:

```
$ php homeDir.php
Using AWS SDK for PHP version 3.138.0
Environment variables:
HOME: /home/ubuntu
HOMEDRIVE:
HOMEPATH:
Config file is at /home/ubuntu/.aws/config
Config file present: yes
arn:aws:iam::<account-id>:user/diehlaws
```

Windows:

```
>php homeDir.php
Using AWS SDK for PHP version 3.138.0
Environment variables:
HOME:
HOMEDRIVE: H:
HOMEPATH: \
Config file is at H:\/.aws/config
Config file present: yes
arn:aws:iam::<account-id>:user/diehlaws
```

</details>

As a result, the current implementation should work as expected, however if you have found a case in which it doesn't please do provide more details so we can account for this case in the `getHomeDir` function.
