### ISSUE TITLE
well my question is how is this? why ? and improve?

### ISSUE THREAD

**Issue by thesunisgas** [aws/aws-sdk-php#2016]
Confirm by changing [ ] to [x] below:
- [ ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
Example: v3.133.6
* get SDK version by printing the output of `Aws\Sdk::VERSION` in your code 
* if the SDK was installed via composer you can see the version installed with `composer show -i` 

**Version of PHP (`php -v`)?**

**Describe the question**

**Comment by diehlaws** [comment]
Thanks for reaching out to us @thesunisgas. Can you provide some additional context for your questions? Unfortunately what you're asking for here is not entirely clear.
