### ISSUE TITLE
Consecutive API calls return curl error code 35 on CentOS 6.5

### ISSUE THREAD

**Issue by bikegriffith** [aws/aws-sdk-php#202]
After initializing the S3Client with just a key and secret, I can only make 1 API call before getting curl error code 35.

E.g.

``` php
$s3->putObject([
    'Bucket'=>'MyBucket',
    'Key'=>'MyFolder/',
    'Body'=>'',
    'ContentLength'=>0
]);
```

The 2nd time results in the following error:

```
PHP Fatal error:  Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 35:  [url] https://s3.amazonaws.com/MyBucket/MyFolder/' in /home/mike/src/awstest/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:338
Stack trace:
#0 /home/mike/src/awstest/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(279): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#1 /home/mike/src/awstest/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(244): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#2 /home/mike/src/awstest/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(227): Guzzle\Http\Curl\CurlMulti->processMessages()
#3 /home/mike/src/awstest/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(211): Guzzle\Http\Curl\CurlMulti->executeHandles()
#4 /home/mike/src/awstest/vendor/guzzle/guz in /home/mike/src/awstest/vendor/aws/aws-sdk-php/src/Aws/Common/Client/AbstractClient.php on line 286
```

I'm hitting a bucket in the US East Region.

I've tried passing several combinations of curl.options to the factory constructor, but no luck

``` php
$s3 = S3Client::factory([
    'key' => '****',
    'secret' => '****',
    'curl.options' => [
        'CURLOPT_SSLVERSION' => 3,
    ]
]);
```

Server package details:
CentOS 6.5
php 5.4.23-29
curl 7.19.7-37
openssl 1.0.1e-16

```
$ curl --version
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.14.0.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz
```

Edit: renamed and updated details based on latest findings.

**Comment by varunwy** [comment]
I am getting the same error and I have some idea on what's going on here.

Below are the steps to reproduce this problem while using PHP aws sdk.
1. make an aws api call
2. use pcntl to fork a child process
3. In the child process make another aws api call
You will get error:
Aws\Common\Exception\TransferException: [curl] 35: A PKCS #11 module returned CKR_DEVICE_ERROR, indicating that a problem has occurred with the token or slot.

This problem will happen only if you use curl with NSS. Curl with Openssl works fine.

According to this discussion (https://bugzilla.mozilla.org/show_bug.cgi?id=331096), the following 
is illegal: A parent process uses PKCS11 module, then forks a child and the child tries to use PKCS11 module

The solution is to reinitialise all PKCS#11 modules in the child process. Any idea how do we do that?

**Comment by jeremeamia** [comment]
Hmmm... that is an interesting lead, but makes sense since @bikegriffith was only seeing the issue when using Boris, which does use pcntl.

What happens if, instead of using the same client to make the 2nd request, you instantiate a new client object to make that request?

**Comment by varunwy** [comment]
I am already creating a new client object in every child process. Same error.
Sent using CloudMagic
On Fri, Feb 27, 2015 at 9:56 PM, Jeremy Lindblom <notifications@github.com> wrote:Hmmm... that is an interesting lead, but makes sense since @bikegriffith was only seeing the issue when using Boris, which does use pcntl.

What happens if, instead of using the same client to make the 2nd request, you instantiate a new client object to make that request?

**Comment by varunwy** [comment]
Any updates?

**Comment by allella** [comment]
If you happen to be connecting to a server utilizing CloudFlare then error 35 may be due to an out of date version of libcurl. [Solution to error 35 on CentOS 6.x](https://github.com/guzzle/guzzle/issues/1000#issuecomment-214971414)

**Comment by techouse** [comment]
I can confirm that this is a Tinker Shell issue. Running the same in PHP's interactive shell everything works fine.

**Comment by rgjodekerken** [comment]
I came across this thread while looking for a solution for this problem. 
I just found the solution so I'm sharing it with you guys.

Starting tinker with the environment variable NSS_STRICT_NOFORK=DISABLED solves the issue.
Source: https://cohanrobinson.com/php-curl-libcurl-error-on-subsequent-requests/
