### ISSUE TITLE
mkdir - No client in stream context

### ISSUE THREAD

**Issue by neoacevedo** [aws/aws-sdk-php#2020]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
I try to create a directory just with a simple mkdir call, but I get the error described in the title. I can run rmdir, fopen/fclose, is_dir, is_file, unlink, but the only one that doesn't work is mkdir.

**Version of AWS SDK for PHP?**
v3.138.4

**Version of PHP (`php -v`)?**
7.4.5

**To Reproduce (observed behavior)**
`mkdir('s3://myBucket/myDirectory/");`

**Expected behavior**
Directory created.

**Comment by diehlaws** [comment]
Thanks for reaching out to us @neoacevedo. The error you're getting suggests the S3 client being used to register the streamwrapper is not being initialized properly. Can you provide a more complete code sample showing how you're creating your S3 client and registering your streamwrapper? I'm not able to reproduce this behavior on my end, using the code snippet below creates a directory in my S3 Bucket as expected.

```php
use Aws\S3\S3Client;

$client = new S3Client([
    'region' => 'us-west-2',
    'version' => 'latest',
    // 'debug' => true,
    ]);

$client->registerStreamWrapper();

mkdir('s3://my-bucket/path/to/directory');
```

**Comment by neoacevedo** [comment]
Almost same code you have posted, only I passed the credentials.

**Comment by neoacevedo** [comment]
I will close it. I have a suspicious about a network issue.
