### ISSUE TITLE
Aws\Exception\CredentialsException Timeout

### ISSUE THREAD

**Issue by Tbone542** [aws/aws-sdk-php#2022]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
Occasionally get the following error message.

`Aws\Exception\CredentialsException: Error retrieving credentials from the instance profile metadata server. (cURL error 28: Connection timed out after 1000 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)) in /var/www/mysite/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php:240`

Seems to be fine most of the time, but we randomly get the error messages above in our logs.

**Version of AWS SDK for PHP?**
v3.135.3

**Version of PHP (`php -v`)?**
7.0.33

**To Reproduce (observed behavior)**

**Expected behavior**

**Screenshots**

**Additional context**
It is running on EC2 and we are using the instance profile to provide the credentials.

**Comment by diehlaws** [comment]
Thanks for reaching out to us @Tbone542. By default, the instance profile provider has a timeout of 1 second with 3 retries before returning the exception you're seeing. It sounds like your application is attempting to retrieve credentials from the instance's metadata service more frequently than it can handle returning credentials within the given timeout. There's a couple of things you could do to avoid this behavior.

- Initialize an [instance profile provider](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_provider.html#instanceprofile-provider) with increased values for timeout and/or retries

This will allow the instance metadata service more time to respond with credentials before the SDK returns an error, but will result in longer times to initialize a service client and issue API calls to the service in question. You can review the parameters the instance profile provider accepts [here](https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Credentials.InstanceProfileProvider.html#___construct). Depending on your use case (whether you're initializing multiple service clients within the same script) you may want to memoize the credentials returned by the instance profile provider to reduce the amount of calls to the instance metadata service

```php
use Aws\Sts\StsClient;
use Aws\Credentials\CredentialProvider;

$provider = CredentialProvider::instanceProfile([
    'timeout' => 5, // Timeout after waiting for 5 seconds instead of 1
    'retries' => 5, // Retry 5 times before returning an error instead of 3
]);

/* 
Useful if initializing service client multiple times 
or initializing multiple service clients within the same script. 
*/
$memoizedProvider = CredentialProvider::memoize($provider);


$client = new StsClient([
    'region' => 'us-west-2',
    'version' => 'latest',
    'credentials' => $memoizedProvider
    // 'debug' => true,
    ]);

```

- Cache a provider's credentials in a [CacheInterface](https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.CacheInterface.html) and retrieve credentials from the cache

This will result in the SDK only retrieving credentials from the instance metadata service when the cached credentials have expired. You'll still need to specify a provider to use when caching credentials, but you shouldn't have to provide special configuration parameters to account for the rate at which the instance metadata service can respond to requests. While the example below shows usage for a [Doctrine](https://www.doctrine-project.org/projects/doctrine-cache/en/1.8/index.html) filesystem cache, the CacheInterface also supports [Psr\Cache\CacheItemPoolInterface](https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.PsrCacheAdapter.html), [Psr\SimpleCache\CacheInterface](https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Psr16CacheAdapter.html) and [LruArrayCache](https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.LruArrayCache.html).

```php
use Aws\Sts\StsClient;
use Aws\Credentials\CredentialProvider;
use Aws\DoctrineCacheAdapter;
use Doctrine\Common\Cache\FilesystemCache;

$cache = new DoctrineCacheAdapter(new FilesystemCache('/path/to/filesystem/cache'));

/* 
You can either use the default credential provider as shown here or specify 
the instanceProfile provider shown in the example above
*/
$provider = CredentialProvider::defaultProvider();
$cachedProvider = CredentialProvider::cache($provider, $cache);

$client = new StsClient([
    'region' => 'us-west-2',
    'version' => 'latest',
    'credentials' => $cachedProvider
    // 'debug' => true,
    ]);
```

**Comment by Tbone542** [comment]
That certainly makes sense. Thank you for your detailed description.
