### ISSUE TITLE
How Can I mock S3 client to make unit tests?

### ISSUE THREAD

**Issue by gapinto** [aws/aws-sdk-php#2023]
Confirm by changing [ ] to [x] below:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
3.2.6
**Version of PHP (`php -v`)?**
7.3.14

Hy guys,

I'm trying to make unit tests for upload operation, but work with a concrete class instead of an interface is not so good to create mocks.

For example, I want to mock the `abortMultipartUpload` function, but I can't found this function in `S3ClientInterface`.

I'm following the documentation and there is showing that it is possible to use this function.

Do you have some ideas?

**Comment by diehlaws** [comment]
Thanks for reaching out to us @gapinto. Our [S3 tests](https://github.com/aws/aws-sdk-php/tree/master/tests/S3) use a test client in the Aws\Test namespace that can be bootstrapped from the files in our repo's [features/bootstrap/Aws/Test](https://github.com/aws/aws-sdk-php/tree/master/features/bootstrap/Aws/Test) directory. Reviewing our [S3 multi-part uploader tests](https://github.com/aws/aws-sdk-php/blob/master/tests/S3/MultipartUploaderTest.php) should help get you started mocking out responses for different calls via the S3 client. Please do let us know if you need further guidance on this and we'll be happy to assist.
