### ISSUE TITLE
404 not found link in Static Client Facades

### ISSUE THREAD

**Issue by bagage** [aws/aws-sdk-php#2029]
**Describe the issue with documentation**
[Feature facades docs](https://docs.aws.amazon.com/aws-sdk-php/v2/guide/feature-facades.html) ends with: 

> you might consider using the [Guzzle Mock Plugin](http://guzzlephp.org/plugins/mock-plugin.html). 

However this links does not exist anymore. I found the proper one for [Guzzle 3](https://guzzle3.readthedocs.io/plugins/mock-plugin.html) though. Maybe [that](http://docs.guzzlephp.org/en/stable/testing.html?highlight=mock) for Guzzle6?

**Comment by diehlaws** [comment]
Thanks for reaching out to us about this @bagage. Please keep in mind that version 2 of the AWS SDK for PHP is not actively maintained - while we do continue to push bug fixes and security patches to this version of the SDK it has not had any new features added for some time. We strongly recommend upgrading to version 3 of the AWS SDK for PHP.

That being said, we will update this documentation page to fix the broken link in question.
