### ISSUE TITLE
copyObject error semantics are unclear

### ISSUE THREAD

**Issue by nicofff** [aws/aws-sdk-php#2059]
**Describe the issue with documentation**
The api documentation for [copyObject](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#copyobject) states that:  
`A copy request might return an error when Amazon S3 receives the copy request or while Amazon S3 is copying the files. If the error occurs before the copy operation starts, you receive a standard Amazon S3 error. If the error occurs during the copy operation, the error response is embedded in the 200 OK response. This means that a 200 OK response can contain either a success or an error. Design your application to parse the contents of the response and handle it appropriately.`. 

That is copied verbatim from the [s3 api documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html)

Neither the api docs, nor the examples have any indication of where that error response is embedded, so it's not clear from the perspective of someone using the sdk what the error handling for that method should be. 

Based on some testing, it seems to throw an `S3Exception`, like most other methods. but it's unclear if there are some error scenarios where that might not be the case.

**Comment by diehlaws** [comment]
Thanks for reaching out to us about this @nicofff. Errors received on 200 OK responses from S3 should always be an `S3Exception` and will be included in the XML body of the response. Descriptions for a service's calls in the SDK's API reference are retrieved from the API model provided to us by the service team, which is the same source used for the service's API reference documentation. 

While we cannot modify the description for the `copyObject` operation, we can create a customization for this operation's d to mention error handling in the case of an error on a 200 OK response below the description for the API call. Once we have additional information on this we'll update the issue accordingly.

**Comment by nicofff** [comment]
Thanks for the response @diehlaws.  
Another thing that is unclear is if these errors will be retried automatically or not. Looking at the RetryMiddleware it's not immediately obvious if it will be.

**Comment by diehlaws** [comment]
Apologies for the delay in response on our end here @nicofff. The RetryMiddleware does indeed catch and retry `S3Exception` errors from S3 that are returned in a `200 OK` response. We'll be sure to include this information in the customization for the S3Client docs in the API Reference for the AWS SDK for PHP.

**Comment by SamRemis** [comment]
@nicofff we have added some notes to the docs to clarify this as well; it should appear in the documentation within 24 hours.

**Comment by nicofff** [comment]
@diehlaws @SamRemis Thanks!
