### ISSUE TITLE
How to use S3Client with Role and Token File Env Vars present (service account)

### ISSUE THREAD

**Issue by kickthemooon** [aws/aws-sdk-php#2063]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
v3.143.0

**Question**
Pods are configured with a service account and have the env variables AWS_ROLE_ARN / AWS_WEB_IDENTITY_TOKEN_FILE.

I read the docs and tried to find a solution on how to use `\Aws\S3\S3Client` with the above env variables present.
How do I instantiate the `\Aws\S3\S3Client` so it uses the service account env vars for authentication?

**Comment by kickthemooon** [comment]
https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#credentials
"If you don’t provide a credentials option, the SDK attempts to load credentials from your environment"

**Comment by aradhell** [comment]
Hello, having similar issue, if I remove credentials, it is trying to use nodeInstanceRole instead of service account. Any suggestions? Thanks!
