### ISSUE TITLE
SES api signature version

### ISSUE THREAD

**Issue by al3x88** [aws/aws-sdk-php#2064]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
Example: v3.87.4

**Version of PHP (`php -v`)?**
PHP 7.2.24

**Describe the question**
AWS will disabling SES Signature version3 from  October 1, 2020.
Does this library will support Signature version4?
Of no, any workaround ?

**Comment by diehlaws** [comment]
Hi @al3x88, thanks for reaching out to us. The AWS SDK for PHP uses Signature Version 4 by default, so the deprecation of SES Signature Version 3 should not affect code that uses this SDK. That said, you can specify the signature version used by the SDK in the service client's configuration as shown [here](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#signature-version).

**Comment by al3x88** [comment]
@diehlaws thanks for the reply!!
My SDK is of version 3.87.4. Does it support signature v4 as well? 
Or I need to update the SDK?

**Comment by diehlaws** [comment]
@al3x88 No problem! Version 3.87.4 should use SigV4 by default without having to specify the `signature_version` parameter in the client config. You can verify that your requests are being signed with SigV4 by enabling [debug logging](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#debug) and looking for `aws4_request` in the `Authorization` header value of the HTTP request.

**Comment by al3x88** [comment]
@diehlaws thanks so much for ur help!
