### ISSUE TITLE
php media stream encoding

### ISSUE THREAD

**Issue by Cherchercher** [aws/aws-sdk-php#2065]
Hi, I want to encode media stream to sent to aws transcribe streaming.

I found a package in node.js:
https://github.com/aws/aws-sdk-js-v3/tree/master/packages/eventstream-marshaller

Is similar features available yet in PHP?

Thank you

**Comment by diehlaws** [comment]
Hi @Cherchercher, thanks for reaching out to us about this. Unfortunately the AWS SDK for PHP does not support streaming audio to the Transcribe service at this time. Once we have additional information on this we'll update the issue accordingly.

**Comment by diehlaws** [comment]
Streaming audio to Transcribe requires HTTP/2 support which is not implemented in version 3 of the AWS SDK for PHP. The next major version of the AWS SDK for PHP should introduce support for HTTP/2, once this is introduced the SDK will support Transcribe streaming.
