### ISSUE TITLE
how to get all NextToken from getDocumentTextDetection

### ISSUE THREAD

**Issue by ebrahimpleite** [aws/aws-sdk-php#2066]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP? 3.110.3**

**Version of PHP (`php -v`)? 7.3**

I'm using the textractor to return the text from documents

I have a document with many pages and the api returns a NextToken for every 1000 results

what's the best way to get all the results with using the NextToken in the right way?

**Comment by diehlaws** [comment]
Hi @ebrahimpleite, thanks for reaching out to us about this. You can wrap your `getDocumentTextDetection` call in a do/while loop until the `NextToken` value for your result variable is empty. I've included a code sample below for your review.

```php
$params = [
    'JobId' => $jobId,
];
do {
    try {
        $resp = $client->getDocumentTextDetection($params);
        $params['NextToken'] = $resp['NextToken'];

        // Process response as needed
    } catch (AwsException $e) {
        echo "Error calling getDocumentTextDetection: {$e->getMessage()}" . PHP_EOL;
    }
} while ($resp['NextToken'] != '');
```

**Comment by ebrahimpleite** [comment]
thanks @diehlaws
