### ISSUE TITLE
Can we use ProductAdvertisingAPI with the help of this SDK

### ISSUE THREAD

**Issue by indiandeveloper2020** [aws/aws-sdk-php#2067]
Hi, sorry for asking question but I do not find answer anywhere that's why I ask here. I want to know Can we use ProductAdvertisingAPI with the help of this SDK. 
I read somewhere 
` $awsv4 = new AwsV4 ($amazon_access_key, $amazon_secret_key);`
`$awsv4->setRegionName("us-east-1");`
`$awsv4->setServiceName("ProductAdvertisingAPI");`

**Comment by diehlaws** [comment]
Hi @indiandeveloper2020, thanks for reaching out to us. The AWS SDK for PHP does not support interacting with the Amazon Product Advertising API. The AWS services supported by this SDK are listed in our [SDK API Reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html). 

That said, it looks like there is a PHP SDK for the Amazon Product Advertising API as mentioned [here](https://webservices.amazon.com/paapi5/documentation/quick-start/using-sdk.html). Please keep in mind that this software is completely unrelated to the AWS SDK for PHP, and is not maintained by the same team internally. If you require assistance using the Product Advertising API SDK you'll want to follow the instructions on their [Contact Us](https://webservices.amazon.com/paapi5/documentation/contact-us.html) page.
