### ISSUE TITLE
Update / install issue of new version

### ISSUE THREAD

**Issue by DmytroShumeyko** [aws/aws-sdk-php#2076]
Hello, i'm getting an error from 2020-10-08 :

Package operations: 0 installs, 3 updates, 0 removals
  - Updating aws/aws-sdk-php (3.147.14 => 3.148.1): The following exception is caused by a lack of memory or swap, or not having swap configured
Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details

                                                     
  [ErrorException]                                   
  proc_open(): fork failed - Cannot allocate memory

**Comment by seleznevaksenia** [comment]
Hi! I have the same error in my project.

**Comment by ajredniwja** [comment]
Hey @DmytroShumeyko Thank-you for reaching out to us with your issue. I was not quite able to get a similar results, have you tried following the steps mentioned [here](https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors) to solve the problem?

**Comment by DmytroShumeyko** [comment]
> Hey @DmytroShumeyko Thank-you for reaching out to us with your issue. I was not quite able to get a similar results, have you tried following the steps mentioned [here](https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors) to solve the problem?

All manipulating of extending memory helps in this situation. Thanks
