### ISSUE TITLE
use DocDB copyDBClusterSnapshot command cross region  copy snapshot with encrypted snapshot. error : PreSignedurl could not be authenticated

### ISSUE THREAD

**Issue by YouYII** [aws/aws-sdk-php#2077]
**Describe the bug**
Use DocDB copyDBClusterSnapshot command cross region  copy snapshot with encrypted snapshot.

**Version of AWS SDK for PHP?**
v3.130.3

        $client_config = null;
        $args = [
            'credentials' =>FailoverHelper::getCredentials(),
            'signature'   => 'v4' ,
            'version'     => '2014-10-31' ,
            'region'      => 'us-west-2',
            'with_resolved'=>function($c)use(&$client_config){
                $client_config = $c;
            }
        ];

        $target_client = new \Aws\DocDB\DocDBClient($args);
        $target_client->getHandlerList()->appendInit(
            PresignUrlMiddleware::wrap(
                $target_client,
                $client_config['endpoint_provider'],
                [
                    'operations' => [
                        'CopyDBClusterSnapshot',
                    ],
                    'service' => 'docdb',
                    'presign_param' => 'PreSignedUrl',
                ]
            ),
            'docdb.copy-db-cluster-snapshot'
        );

        $args = [
            'KmsKeyId'=>'arn:aws:kms:us-west-2:xxxx:key/xxxx',//master key
            'SourceRegion'=> 'us-east-1',
            'DestinationRegion'=>'us-west-2',
            'SourceDBClusterSnapshotIdentifier' => 'arn:aws:rds:us-east-1:xxxx:cluster-snapshot:rds:xxxxxxx',
            'TargetDBClusterSnapshotIdentifier' => 'xxxxxxx-copy',
        ];

        echo "snapshot copy params ".print_r($args,1)."\n";
        try{
            echo "snapshot copy result";
            $result = $target_client->copyDBClusterSnapshot($args);
            print_r($result);
        }catch(Exception $e){
            print_r($e->getMessage());
        }

Exception : 

        snapshot copy resultError executing "CopyDBClusterSnapshot" on "https://rds.us-west-2.amazonaws.com"; AWS HTTP error: Client error: `POST https://rds.us-west-2.amazonaws.com` resulted in a `400 Bad Request` response:
        <ErrorResponse xmlns="http://rds.amazonaws.com/doc/2014-10-31/">
          <Error>
            <Type>Sender</Type>
            <Code>InvalidPara (truncated...)
         InvalidParameterValue (client): PreSignedurl could not be authenticated - <ErrorResponse xmlns="http://rds.amazonaws.com/doc/2014-10-31/">
          <Error>
            <Type>Sender</Type>
            <Code>InvalidParameterValue</Code>
            <Message>PreSignedurl could not be authenticated</Message>
          </Error>
          <RequestId>xxxxx</RequestId>
        </ErrorResponse>

**Comment by diehlaws** [comment]
Hi @YouYII, thanks for reaching out to us. The arguments provided for the `copyDBClusterSnapshot` command being issued are incorrect - the 'PresignedUrl' parameter is missing, and the 'DestinationRegion' parameter is not needed for the command that's actually sent to the service - instead the DocDBClient that issues the call should be initialized using the destination region as its 'region' parameter. The 'SourceRegion' parameter is not valid for this command so this can be omitted altogether.

As far as your presign middleware is concerned, it seems like the request to be presigned is missing some parameters which is likely resulting in an invalid presigned URL for the desired `CopyDBClusterSnapshot` request. Per the [command's documentation](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-docdb-2014-10-31.html#copydbclustersnapshot), the request that must be presigned needs to include the `KmsKeyId`, `DestinationRegion`, and `SourceDBClusterSnapshotIdentifier` parameters. Once the request is correctly presigned it must be passed as the 'PreSignedUrl' parameter for the ` CopyDBClusterSnapshot` command sent to the service.

I hope this information helps you properly copy your encrypted DocumentDB cluster snapshots across regions as expected! Please do let us know if you continue running into problems with this so we can further assist in this matter.

**Comment by YouYII** [comment]
Thank you for your reply, but when copying DocDB snapshots across regions, if you use awscli, you can complete the work by adding the SourceRegion. I investigated the internal source code of AWS PHP SDK, and it will automatically add the DestinationRegion parameter. I have also tried to remove the DestinationRegion, but it also does not work. For cross regional replication of RDB, The PesignedUrl will be automatically created by the PreseignUrlMiddleware, but the PHP AWS SDK of docdb does not do this, so I added a middleware to generate the PesignedUrl myself, but it doesn't work. I have tried to generate the DesignedUrl manually, but it still doesn't work

**Comment by diehlaws** [comment]
Thanks for the additional context @YouYII. Looking more closely at the source for our RdsClient it looks like there is a customization to automatically create a presigned URL for cross-region `CopyDBClusterSnapshot` operations that was not implemented in the DocDBClient for the AWS SDK for PHP. We'll work on implementing this customization in the DocDBClient to automate the population of the `PresignedUrl`, once we have additional information on this we'll update the issue accordingly.

**Comment by SamRemis** [comment]
@YouYII Sorry for the delay in updating this; we added this with PR #2161
