### ISSUE TITLE
Add tag when create topic on sns doesn't working

### ISSUE THREAD

**Issue by thuongmh** [aws/aws-sdk-php#2086]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
I want to add tags when create topic but I uses the function createTopic and config as in the document , it doesn't seem to work.

**Version of AWS SDK for PHP?**
aws-sdk-php 3.1.0

**Version of PHP (`php -v`)?**
php 7.2

**To Reproduce (observed behavior)**
```
$config = [
            'credentials' => [
                'key' => env('AWS_SNS_KEY'),
                'secret' => env('AWS_SNS_SECRET'),
            ],
            'region' => env('AWS_SNS_REGION'),
            'version' => env('AWS_VERSION'),
            'scheme' => env('AWS_SNS_SCHEME', 'http'),
        ];
        $this->client = new SnsClient ($config);
$result = $this->client->createTopic(
                [
                    'Name' => $topicName,
                    'Tags' => [
                        [
                            'Key' => 'TagCode',
                            'Value' => 'Test',
                        ]
                    ]
                ]);
```

**Screenshots**
![Screen Shot 2020-08-26 at 11 38 24 AM](https://user-images.githubusercontent.com/22080236/91256111-aeab7300-e790-11ea-92f7-d798e0417a6c.png)

**Additional context**
Laravel 5.5

**Comment by diehlaws** [comment]
Thanks for reaching out to us @thuongmh. While I'm able to reproduce the described behavior in version 3.1.0 of the AWS SDK for PHP, tagging SNS topics on creation works as expected using version 3.145.3. Looking at our [changelog](https://github.com/aws/aws-sdk-php/blob/master/CHANGELOG.md) it seems support for tagging topics was added in version 3.92.4 of the SDK, so you'll want to update to at least that version to tag your SNS topics.
