### ISSUE TITLE
sendEmail gets stuck forever

### ISSUE THREAD

**Issue by yellow1912** [aws/aws-sdk-php#2091]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
The sendEmail keeps on running forever without returning any error.

**Version of AWS SDK for PHP?**
3.151.3

**Version of PHP (`php -v`)?**
7.2.14

**To Reproduce (observed behavior)**

Below is a sample message:
```

$client = new SesClient(
                                    [
                                     'http' => [
                                            'connect_timeout' => 10,
                                            'timeout' => 10,
                                        ],
                                     'region' => SES_APIREGION,
                                     'key' => SES_APIKEY,
                                     'secret' => SES_APISECRET,
                                     'version' => '2010-12-01'   
                                    ]
                            );

$client->sendEmail([
    "Source" => "someemail@someemail.com",
    "Destination" => [
        "ToAddresses" => ["someemail@somehost.com"],
    ],
    "Message" => [
        "Subject" => [
            "Data" => "Hi Eric Jones",
            "Charset" => "UTF-8"
        ],
        "Body" => [
            "Text" => [
                "Data" => "this is a test",
                "Charset" => "UTF-8"
            ]
        ]
    ],
    "ReplyToAddresses" => ["someemail@somehost.com"]
])
```

In my case, this call will run forever if php timeout is not set.

**Expected behavior**
sendEmail should return some error or success.

**Screenshots**

**Additional context**
I updated to the latest sdk version recently, everything was fine before. 

Edit 1:
I found this similar issue:
https://github.com/aws/aws-sdk-php/issues/1669

Tried to set the connection timeout, nothing happened.
Tried to run `sudo ntpdate pool.ntp.org`, didn't help.

Edit 2:
Downgrade to 2.8.31 fixes the issue. So something in v3 that causes this issue.

**Comment by yellow1912** [comment]
I found out why, hidden inside the migration note is the change that requires you to put the key and secret inside the credentials option key. I think it's still a bug, because there should be some error thrown instead of keeping the script running forever.

**Comment by SamRemis** [comment]
@yellow1912 Thank you so much for bringing this to our attention.  Currently I am unable to reproduce the issue.  To make sure I'm following, I took the following steps

- copied and pasted your code exactly but deleted the http section of the client constructor
- replaced the two email addresses with real, verified email addresses
- set 'use_aws_shared_config_files' to false to ensure it wouldn't grab the real credentials from my environment
- replaced the constants of region, key, and secret with hardcoded, working values

Other than that, our code was identical.  When I ran it, I got a credential error which tells me that the credentials didn't work unless I placed them inside the 'credentials' option key.  

We can certainly look into showing a warning when a key is provided as you did above.  I would like to reproduce your error though to make sure we get it fixed, so please look over the steps I took and see if they appear correct.
