### ISSUE TITLE
SNS fails silently and my code returns a http 200

### ISSUE THREAD

**Issue by tyharg** [aws/aws-sdk-php#2093]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
3.67.13 (Not installed using composer)

**Version of PHP (`php -v`)?**
7.3.12

**Describe the question**

I am hitting a strange error when I attempt to call $sns->createPlatformEndpoint(), it never returns, the code execution completely stops and the page loads as a blank http 200.  I could not catch an exception or get a return code. I was able to track this down to happen when device for the token (endpoint) appears to be already created with different user data.

There's a couple of other people asking the same thing, but no answers it seems.

* https://stackoverflow.com/questions/28731461/aws-sns-publish-silently-dies-when-device-is-disabled
* https://forums.aws.amazon.com/click.jspa?searchID=12872836&messageID=916696

Thanks in advance for the help.

**Comment by sardok** [comment]
I have see similar behavior on .Net package. `CreatePlatformEndpointAsync` blocks in my case.

**Comment by SamRemis** [comment]
Hi @tyharg,
Sorry for the delay.  Are you still seeing this issue?  The first thing I would suggest is upgrading to a more recent version of the SDK- we are currently on 3.170, and it is likely that one of the timeout and retry updates would have fixed your issue.  

If that isn't an option, could you set `'debug' => true ` in the client constructor and post the output?  That may give us some idea of what is going on.
