### ISSUE TITLE
PHP>=5.5 does not support any method declared static inside local function

### ISSUE THREAD

**Issue by giandv** [aws/aws-sdk-php#2095]
I Confirm:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
PHP 5 doesn't support which any method declared as static is accessible without the creation of an object.

**Version of AWS SDK for PHP?**
From 3.0.0 to 3.152.0

**Version of PHP (`php -v`)?**
PHP 5.6.31 (cli) (built: Jul  5 2017 22:25:39)

**To Reproduce (observed behavior)**
`$resolver = static function (
            CommandInterface $c
        ) use ($api, $provider, $name, $region, $version) {
           .....
        };`

**Expected behavior**
Instatation of S3Client.

**Additional context**
I can't upgrade aws/aws-sdk-php over 3.0.0-beta.1. My web application require PHP>=5.5 and Laravel framework 4.2.

**Comment by howardlopez** [comment]
@giandv I'm not sure I quite follow what the bug you're describing is. Can you give a more complete code sample, as well as the error message that you're encountering? What exactly is it you're trying to do?

**Comment by giandv** [comment]
The instruction written in the issue generate a syntax error on an application based on PHP 5.6, but the package "aws-php" promises to be compatible with PHP> = 5.5 ([https://packagist.org/packages/aws/aws-sdk-php](https://packagist.org/packages/aws/aws-sdk-php)).

**Comment by howardlopez** [comment]
@giandv I'm still not sure what compatibility error you're getting - can you please add a complete code sample, as well as the full text of the error message?

The SDK includes PHP 5.5 and 5.6 environments on its Travis CI tests and currently passes all the unit tests, so please give additional clarification about exactly what you're facing.

**Comment by giandv** [comment]
![unreachable-statement](https://user-images.githubusercontent.com/18395021/93451246-36d7f080-f8d7-11ea-9d27-110de18f383e.PNG)
The code shown below generate an unreachable statement, for this reason I cannot instantiate S3Client object.

**Comment by howardlopez** [comment]
@giandv Can you copy/paste the code you're using yourself to produce the error (i.e. your code that is consuming the S3 client), as well as the exact error message?

**Comment by giandv** [comment]
Snippets that generate errors:

```

 private function getLocationConstraintMiddleware()
    {
        $region = $this->getRegion();
        return static function (callable $handler) use ($region) {
            return function (Command $command, $request = null) use ($handler, $region) {
                if ($command->getName() === 'CreateBucket') {
                    $locationConstraint = isset($command['CreateBucketConfiguration']['LocationConstraint']) $command['CreateBucketConfiguration']['LocationConstraint']: null;

                    if ($locationConstraint === 'us-east-1') {
                        unset($command['CreateBucketConfiguration']);
                    } elseif ('us-east-1' !== $region && empty($locationConstraint)) {
                        $command['CreateBucketConfiguration'] = ['LocationConstraint' => $region];
                    }
                }

                return $handler($command, $request);
            };
        };
    }

    private function getHeadObjectMiddleware()
    {
        return static function (callable $handler) {
            return function (
                CommandInterface $command,
                RequestInterface $request = null
            ) use ($handler) {
                if ($command->getName() === 'HeadObject'
                    && !isset($command['@http']['decode_content'])
                ) {
                    $command['@http']['decode_content'] = false;
                }

                return $handler($command, $request);
            };
        };
    }

    private function getEncodingTypeMiddleware()
    {
        return static function (callable $handler) {
            return function (Command $command, $request = null) use ($handler) {
                $autoSet = false;
                if ($command->getName() === 'ListObjects'
                    && empty($command['EncodingType'])
                ) {
                    $command['EncodingType'] = 'url';
                    $autoSet = true;
                }

                return $handler($command, $request)
                    ->then(function (ResultInterface $result) use ($autoSet) {
                        if ($result['EncodingType'] === 'url' && $autoSet) {
                            static $topLevel = [
                                'Delimiter',
                                'Marker',
                                'NextMarker',
                                'Prefix',
                            ];
                            static $nested = [
                                ['Contents', 'Key'],
                                ['CommonPrefixes', 'Prefix'],
                            ];

                            foreach ($topLevel as $key) {
                                if (isset($result[$key])) {
                                    $result[$key] = urldecode($result[$key]);
                                }
                            }
                            foreach ($nested as $steps) {
                                if (isset($result[$steps[0]])) {
                                    foreach ($result[$steps[0]] as $key => $part) {
                                        if (isset($part[$steps[1]])) {
                                            $result[$steps[0]][$key][$steps[1]]
                                                = urldecode($part[$steps[1]]);
                                        }
                                    }
                                }
                            }

                        }

                        return $result;
                    });
            };
        };
    }
```

The specific instruction that generate error is: **return static function**

**Comment by howardlopez** [comment]
@giandv Sorry if I didn't make it clear, but I was looking for your code that you're running, not the SDK code. The SDK code you posted has been run through our unit tests on PHP 5.5 and 5.6 for a long time and not encountered the issues you're describing, so I'm looking for your specific code that is using the SDK. Also, can you paste the full error message you are receiving?
