### ISSUE TITLE
AssumeRoleWithWebIdentityCredentialProvider: failed to open stream, permission denied

### ISSUE THREAD

**Issue by nesar77** [aws/aws-sdk-php#2097]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
Trying to delete or putobject on S3 storage using PODs credential: it works but I'm getting a warning 
<b>Warning</b>:  file_get_contents(/var/run/secrets/eks.amazonaws.com/serviceaccount/token): failed to open stream: Permission denied in <b>/usr/local/backend/vendor/aws/aws-sdk-php/src/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php</b> on line <b>97</b><br />
<br />

**Version of AWS SDK for PHP?**
v3.151.6

aws/aws-sdk-php                    3.151.6 AWS SDK for PHP - Use Amazon Web Services in your PHP project

**Version of PHP (`php -v`)?**

PHP 7.4.10 (cli)

**To Reproduce (observed behavior)**

`<?php

namespace BackEnd\Services;

define('PROJECT_ROOT', realpath(__DIR__ . '/..'));
require PROJECT_ROOT . '/../../vendor/autoload.php';

use Aws\S3\S3Client;
use Aws\Exception\AwsException;
use Aws\Credentials\CredentialProvider;
use Aws\S3\Exception\S3Exception;

class AWSS3
{

    // ACL flags
    const ACL_PRIVATE = 'private';
    const ACL_PUBLIC_READ = 'public-read';
    const ACL_PUBLIC_READ_WRITE = 'public-read-write';
    const ACL_AUTHENTICATED_READ = 'authenticated-read';

    const STORAGE_CLASS_STANDARD = 'STANDARD';
    const STORAGE_CLASS_RRS = 'REDUCED_REDUNDANCY';
    const STORAGE_CLASS_STANDARD_IA = 'STANDARD_IA';

    const SSE_NONE = '';
    const SSE_AES256 = 'AES256';

    /**
     * The AWS Access key
     *
     * @var string
     * @access private
     * @static
     */
    private static $__accessKey = null;

    /**
     * AWS Secret Key
     *
     * @var string
     * @access private
     * @static
     */
    private static $__secretKey = null;

    /**
     * SSL Client key
     *
     * @var string
     * @access private
     * @static
     */
    private static $__sslKey = null;

    /**
     * Default delimiter to be used, for example while getBucket().
     * @var string
     * @access public
     * @static
     */
    public static $defDelimiter = null;

    /**
     * AWS URI
     *
     * @var string
     * @acess public
     * @static
     */
    public static $endpoint = 's3.amazonaws.com';

    /**
     * Proxy information
     *
     * @var null|array
     * @access public
     * @static
     */
    public static $proxy = null;

    /**
     * Connect using SSL?
     *
     * @var bool
     * @access public
     * @static
     */
    public static $useSSL = false;

    /**
     * Use SSL validation?
     *
     * @var bool
     * @access public
     * @static
     */
    public static $useSSLValidation = true;

    /**
     * Use SSL version
     *
     * @var const
     * @access public
     * @static
     */
    public static $useSSLVersion = CURL_SSLVERSION_TLSv1;

    /**
     * Use PHP exceptions?
     *
     * @var bool
     * @access public
     * @static
     */
    public static $useExceptions = false;

    /**
     * Time offset applied to time()
     * @access private
     * @static
     */
    private static $__timeOffset = 0;

    /**
     * SSL client key
     *
     * @var bool
     * @access public
     * @static
     */
    public static $sslKey = null;

    /**
     * SSL client certfificate
     *
     * @var string
     * @acess public
     * @static
     */
    public static $sslCert = null;

    /**
     * SSL CA cert (only required if you are having problems with your system CA cert)
     *
     * @var string
     * @access public
     * @static
     */
    public static $sslCACert = null;

    /**
     * Bucketname
     *
     * @var string
     * @access public
     * @static
     */
    public static $bucketname = '';

    /**
     * Basepath
     *
     * @var string
     * @access public
     * @static
     */
    public static $basepath = '';

    /**
     * AWS Key Pair ID
     *
     * @var string
     * @access private
     * @static
     */
    private static $__signingKeyPairId = null;

    /**
     * Key resource, freeSigningKey() must be called to clear it from memory
     *
     * @var bool
     * @access private
     * @static
     */
    private static $__signingKeyResource = false;

    private static $__client = null;

    public static $region = null;
    /**
     * Constructor - if you're not using the class statically
     *
     * @param string $accessKey Access key
     * @param string $secretKey Secret key
     * @param boolean $useSSL Enable SSL
     * @param string $endpoint Amazon URI
     * @return void
     */
    public function __construct($accessKey = null, $secretKey = null, $useSSL = false, $endpoint = null, $bucketname = null, $basepath = null, $region = 'eu-west-1')
    {
        if ($accessKey !== null && $secretKey !== null)
            self::setAuth($accessKey, $secretKey);
        self::$useSSL = $useSSL;
        self::$endpoint = $endpoint;
        if ($basepath !== null)
            self::setBasepath($basepath);

        if ($bucketname !== null)
            self::setBucketname($bucketname);

        if ($region !== null)
            self::setRegion($region);

        $this->setClient();
    }

    public function getRegion()
    {
        return self::$region;
    }

    public function getBasepath()
    {
        return self::$basepath;
    }

    public function getBucketname()
    {
        return self::$bucketname;
    }

    public function getEndpoint()
    {
        return self::$endpoint;
    }

    public static function setBucketname($name)
    {
        self::$bucketname = $name;
    }

    public static function setBasepath($base)
    {
        self::$basepath = $base;
    }

    public function setClient()
    {
        try {

            //Create a S3Client
            self::$__client = new S3Client([
                'version'     => 'latest',
                'region'      => 'eu-west-1',
            ]);

        } catch (AwsException $e) {
            echo $e->getMessage();
            echo "\n";
        }
    }

    public static function setRegion($region)
    {
        self::$region = $region;
    }

    /**
     * Set the service endpoint
     *
     * @param string $host Hostname
     * @return void
     */
    public function setEndpoint($host)
    {
        self::$endpoint = $host;
    }

    /**
     * Set AWS access key and secret key
     *
     * @param string $accessKey Access key
     * @param string $secretKey Secret key
     * @return void
     */
    public static function setAuth($accessKey, $secretKey)
    {
        self::$__accessKey = $accessKey;
        self::$__secretKey = $secretKey;
    }

    /**
     * Check if AWS keys have been set
     *
     * @return boolean
     */
    public static function hasAuth()
    {
        return (self::$__accessKey !== null && self::$__secretKey !== null);
    }

    /**
     * Set SSL on or off
     *
     * @param boolean $enabled SSL enabled
     * @param boolean $validate SSL certificate validation
     * @return void
     */
    public static function setSSL($enabled, $validate = true)
    {
        self::$useSSL = $enabled;
        self::$useSSLValidation = $validate;
    }

    /**
     * Set SSL client certificates (experimental)
     *
     * @param string $sslCert SSL client certificate
     * @param string $sslKey SSL client key
     * @param string $sslCACert SSL CA cert (only required if you are having problems with your system CA cert)
     * @return void
     */
    public static function setSSLAuth($sslCert = null, $sslKey = null, $sslCACert = null)
    {
        self::$sslCert = $sslCert;
        self::$sslKey = $sslKey;
        self::$sslCACert = $sslCACert;
    }

    /**
     * Set proxy information
     *
     * @param string $host Proxy hostname and port (localhost:1234)
     * @param string $user Proxy username
     * @param string $pass Proxy password
     * @param constant $type CURL proxy type
     * @return void
     */
    public static function setProxy($host, $user = null, $pass = null, $type = CURLPROXY_SOCKS5)
    {
        self::$proxy = array('host' => $host, 'type' => $type, 'user' => $user, 'pass' => $pass);
    }

    public static function putObjectFile($file, $bucket, $uri, $acl = self::ACL_PRIVATE)
    {
        if (self::$__client == null) return false;
        try {
            $result = self::$__client->putObject(['Bucket' => $bucket, 'Key' => $uri, 'Body' => file_get_contents($file), 'ACL' => $acl]);
            return $result['ObjectURL'];
        } catch (S3Exception $e) {
            echo "There was an error uploading the file.\n";
            echo $e->getMessage() . "\n";
            echo $e->getTraceAsString();
            return false;
        }
    }

    public static function deleteObject($bucketName, $bucketfile)
    {
        if (self::$__client == null) return false;
        try {
            self::$__client->deleteObject(['Bucket' => $bucketName,  'Key' => $bucketfile]);
            return true;
        } catch (S3Exception $e) {
            echo "There was an error deleting the file.\n";
            echo $e->getMessage() . "\n";
            echo $e->getTraceAsString();
            return false;
        }
    }

    public static function getBucket($bucketname, $path)
    {
        $objects = self::$__client->getIterator('ListObjects', array(
            'Bucket' => $bucketname,
            'Prefix' => $path . (substr($path, -1) == '/' ? '' : '/')
        ));
        return $objects;
    }
}`

**Comment by nesar77** [comment]
Hi @SamRemis your suggestion works fine.

**Comment by SamRemis** [comment]
Hi @nesar77,
Just wanted to update you- we have merged a PR that should fix this issue.  Please let us know if you continue to experience it.
-Sam
