### ISSUE TITLE
i cant install composer and php mailer on my centos 7

### ISSUE THREAD

**Issue by mobaid-eg** [aws/aws-sdk-php#2105]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
Example: v3.133.6
* get SDK version by printing the output of `Aws\Sdk::VERSION` in your code 
* if the SDK was installed via composer you can see the version installed with `composer show -i` 

**Version of PHP (`php -v`)?**

**Describe the question**
I cant install phpmailer class after installing php composer on my centos 7 its not generated autoload files and phpmailer class when trying to use the simple script to send using amazon ses smtp i get error phpmailer class not found
just i want the full documentation to install it correctly 
i followed this document to install it but this not working with me

https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-using-sdk-php.html
but i followed this to install composer but not working 
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-using-smtp-php.html
but this documentation not working on my centos 7 
please send me the right way to install it and use it on my server

**Comment by ajredniwja** [comment]
Hey @mobaid-eg thanks for reaching out to us with your issue, I am little confused here but the way to install composer:

1. Install PHP, https://linuxize.com/post/install-php-7-on-centos-7/
2. Install composer, https://linuxize.com/post/how-to-install-and-use-composer-on-centos-7/
3. Install PHP SDK, https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/getting-started_installation.html

Can you try following all those steps? 

Note: 1 and 2 are not official AWS docs but they should work correctly for centos 7
