### ISSUE TITLE
PHP notice: undefined index in CredentialProvider.php

### ISSUE THREAD

**Issue by franksl** [aws/aws-sdk-php#2110]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  

Hello,
I'm using the sdk to execute a put to S3. I'm creating a client instance where the 'credentials' configuration parameter is represented by a custom class that basically retrieves the credentials from a redis instance.
After one of the lates updates I now receive this notice:

PHP Notice:  Undefined index: profile default in vendor/aws/aws-sdk-php/src/Credentials/CredentialProvider.php on line 319

**Version of AWS SDK for PHP?**
3.157.0

**Version of PHP (`php -v`)?**
7.1

**To Reproduce (observed behavior)**
Try to create and use an S3 client by passing a custom class as the 'credentials' configuration parameter.

**Comment by SamRemis** [comment]
@franksl Thank you for reporting the issue- that line is part of a function that gets cached credentials from the single sign on service from the CLI.  I'm looking into it today.  If you arent using the credentials or config file to authenticate, the easiest way to bypass this for now would be to set the 'use_aws_shared_config_files' config parameter to false.

**Comment by SamRemis** [comment]
@franksl We just merged a PR that should have fixed the issue.  Any further details you could give me would still be helpful so that I can make sure I understand what caused the error to occur and that there isn't a bug with the sso credential provider.  

Thank you,
-Sam

**Comment by franksl** [comment]
Hi Sam, 
I had a better look at our code because I didn't remember a couple of details.
We are using the Assume Role policy to retrieve aws credentials and we also store these credentials in a redis instance, so basically when creating an instance of S3Client we pass an instance of \Aws\DoctrineCacheAdapter as the 'credentials' parameter. I noticed that something has changed since we developed this solution, for example I don't remember the existence of the CredentialProvider::defaultProvider() and other builtin providers at that time.
Hope this helps,
Frank

**Comment by SamRemis** [comment]
@franksl 
Hi Frank,
Thanks, it does!  That makes a lot more sense now, I was concerned you were trying to used cached SSO credentials and it was somehow being stored to a different profile, but it doesn't seem like that's the case.  I appreciate the extra info.  
-Sam
