### ISSUE TITLE
Error copying files over 5GB

### ISSUE THREAD

**Issue by crwh05** [aws/aws-sdk-php#2113]
Localhost and Windows server issues resulting in files larger than 5GB not being copied using S3Client::copy()

Localhost:

`"Error executing \"CopyObject\" on \"https:\/\/example.s3.eu-west-1.amazonaws.com\/...\"; AWS HTTP error: Client error: `PUT https:\/\/example.s3.eu-west-1.amazonaws.com\/...` resulted in a `400 Bad Request` response:\n<Error><Code>InvalidRequest<\/Code><Message>The specified copy source is larger than the maximum allowable size for a cop (truncated...)\n InvalidRequest (client): The specified copy source is larger than the maximum allowable size for a copy source: 5368709120 - <Error><Code>InvalidRequest<\/Code><Message>The specified copy source is larger than the maximum allowable size for a copy source: 5368709120<\/Message><RequestId>...<\/RequestId><HostId>...<\/HostId><\/Error>"`

Windows EC2 server:
This is the error when trying to copy a file >5GB on S3 from one folder to another in the same bucket.

    Aws\Exception\MultipartUploadException: An exception occurred while uploading parts to a multipart upload. The following parts had errors:
    - Part 1: Error executing "UploadPartCopy" on "https://example.s3.eu-west-1.amazonaws.com/folder/6gbfile.txt?*"; AWS HTTP error: Client error: `PUT https://example.s3.eu-west-1.amazonaws.com/folder2/6gbfile.txt?*` resulted in a `404 Not Found` response:
    <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>folder%252F6gbfile.txt%252Fen (truncated...)
     NoSuchKey (client): The specified key does not exist. - <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>folder%252F6gbfile.txt</Key><RequestId>*</RequestId><HostId>*</HostId></Error>

It is repeated for over 400 parts.

- AWS SDK: 3.154
- PHP: 7.2.34
- CURL: 7.67.0
- OpenSSl: 1.1.1g

This error is also logged from the same request multiple times

    - Part 706: Error executing \"UploadPartCopy\" on \"https:\/\/example.s3.eu-west-1.amazonaws.com\/folder\/6gbfile.txt?*\"; AWS HTTP error: cURL error 77: error setting certificate verify locations:\n  CAfile: C:\\PHP7234\\cacert.pem\n  CApath: none (see https:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html)\n

**Comment by ajredniwja** [comment]
Hey @crwh05, thanks for opening this issue, can you please share the code that you are using?

**Comment by crwh05** [comment]
Hi @ajredniwja 

Thanks for having a look at this.

Here is the code that is being run in the console, not in a hosted server like apache:

```
$stsConnectionDetails = [
    'credentials' => [
        'key' => KantanSTS::DEV_AWS_ACCOUNT_ACCESS_KEY,
        'secret' => KantanSTS::DEV_AWS_ACCOUNT_SECRET_ACCESS_KEY
    ],
    'region' => 'eu-west-1',
    'version' => 'latest'
];
$s3Client = new S3Client($stsConnectionDetails);
$result = $s3Client->copy(
    'kantan-dev',
    'folder1/5.7MB.tar',
    'kantan-dev',
    'folder2/5.7MB.tar'
);
```


Here is the IAM policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::kantan-dev",
                "arn:aws:s3:::kantan-dev/*"
            ]
        }
    ]
}
```



Files <5GB copy perfectly, anything >5GB fails with this error:
https://kantan-dev.s3-eu-west-1.amazonaws.com/5.7GB+file+copy+error.txt

Windows server hosted on an EC2 instance running:

- AWS SDK PHP: 3.154
- PHP: 7.2.34
- CURL: 7.67.0
- OpenSSl: 1.1.1g

https://kantan-dev.s3-eu-west-1.amazonaws.com/php.ini-windows-server.txt

**Comment by crwh05** [comment]
[php.ini-windows-server.txt](https://github.com/aws/aws-sdk-php/files/5339256/php.ini-windows-server.txt)
[5.7GB file copy error.txt](https://github.com/aws/aws-sdk-php/files/5339257/5.7GB.file.copy.error.txt)
Copying files here for history for the issue, the hosted files will be removed once this issue is resolved.

**Comment by ajredniwja** [comment]
I ran this locally and was not able to reproduce it, I will discuss this with the team what might be wrong.

**Comment by ajredniwja** [comment]
Might be not related to the SDK but curl, can you try updating it to the latest version?
