### ISSUE TITLE
Could not resolve host: dynamodb.us-east-2.amazonaws.com

### ISSUE THREAD

**Issue by yusufdemir2012** [aws/aws-sdk-php#2116]
`GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: dynamodb.us-east-2.amazonaws.com (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /home/dilkvhx97ol8/public_html/RCPPRO/DynamoDB/GuzzleHttp/Handler/CurlFactory.php:200
Stack trace:
#0 /home/dilkvhx97ol8/public_html/RCPPRO/DynamoDB/GuzzleHttp/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /home/dilkvhx97ol8/public_html/RCPPRO/DynamoDB/GuzzleHttp/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /home/dilkvhx in /home/dilkvhx97ol8/public_html/RCPPRO/DynamoDB/Aws/WrappedHttpHandler.php on line 195`

Hello. Error occurs sometimes (it seems to happen randomly). The Php file is hosted on GoDaddy web hosting. 

Can anyone help me? Thanks

**Comment by ajredniwja** [comment]
Hey @yusufdemir2012 thanks for opening this issue, would you be able to share the code for minimal repro?

**Comment by yusufdemir2012** [comment]
> Hey @yusufdemir2012 thanks for opening this issue, would you be able to share the code for minimal repro?

Of course. But first of all I just want to mention, I use[ this wrapper](https://github.com/pluginscart/dynamodb-php) for DynamoDB communication.

**Describe**
In the game I developed in Unity3D, I use DynamoDB to keep users data. Users make requests to the php file on the web server. Php processes those requests and communicates with DynamoDB. Currently, about 30 thousand players are saving their data on DynamoDB. I think these error logs occur in 1%(Or less) of users. 

**And a simple sample of the code I use in php**
`<?php
	require_once 'DynamoDB/aws-autoloader.php'; // provided by AWS
	require_once 'DynamoDB/DynamoDBWrapper.php'; // this module

	$tableName = "XXXXXXXXXXXXX";
	
	$ddb = new DynamoDBWrapper(array(
      'version' => 'latest',
	  'region'  => "us-east-2",
	  'credentials' => array(
		'key' => "XXXXXXXXXXXXXXXXXXXX",
		'secret'  => "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
	  )
	));
	
	$authID = $_POST["authID"];
	
	$key = array(
	'AuthID' => $authID,
	);
	
	$result = $ddb->get($tableName, $key);
	if($result)
	{//Player founded,
		$json = json_encode($result);
		echo "((Successful))".$json;
		exit();
	}
	else
	{//Player not founded in database
		echo "((WebServerError))PlayerNotFound";
		exit();
	}
?>`

**Comment by ajredniwja** [comment]
@yusufdemir2012 I am actually not able to reproduce this, do you see similar errors with other endpoints as well? 

If you may try us-west-2 or some other region?
