### ISSUE TITLE
PHP DynamoDB DAX Client

### ISSUE THREAD

**Issue by dtbarne** [aws/aws-sdk-php#2118]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
3.147.4

**Version of PHP (`php -v`)?**
7.4.9

**Describe the question**

I can't seem to find any PHP DAX client. I found the DaxClient which allows you to create and modify DAX clusters, but not an actual client for communicating with those clusters. This seems like a major omission. Am I missing something?

**Comment by SamRemis** [comment]
@dtbarne Sorry, I'm not sure I understand the question.  What do you mean by 'communicate' with the clusters?  What sort of info are you looking to send/receive?  If you're looking to communicate with the host, could you just use Ec2Client to communicate with the EC2 instance that the DAX client is hosted on?

**Comment by dtbarne** [comment]
There doesn't seem to be any PHP SDK for it like there are for JS, Java, .NET, etc.

http://dax-sdk.s3-website-us-west-2.amazonaws.com/

**Comment by SamRemis** [comment]
@dtbarne That makes more sense.  No, we have not implemented that yet.  We will look into implementing it, so I will mark this as a feature request.

**Comment by martinbutt** [comment]
@SamRemis does this mean there is no way currently to connect to a DAX cluster from PHP?

**Comment by iNviNho** [comment]
Any progress on supporting DAX protocol from PHP?

**Comment by ValkyrieUK** [comment]
Any updates on this issue?

**Comment by stadskle** [comment]
Are there no plans to support DAX from PHP?

**Comment by raphaelcangucu** [comment]
Any updates on this issue?

**Comment by raphaelcangucu** [comment]
Hi @SamRemis , any plan to update the LIB to support DAX?

I was studying this and it seems to be a hard challenge, since curl don't support the DAX protocol directly.

Can you point to me the correct direction, so I can at least try to connect and pool some data with PHP using the DAX protocol?

Thanks in advance

**Comment by go-redrock-nicolas** [comment]
I am also looking for this
