### ISSUE TITLE
Fetching the statusCode of request for method calls on S3 Client

### ISSUE THREAD

**Issue by qwertynik** [aws/aws-sdk-php#2123]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**: 3.154.6

**Version of PHP (`php -v`)?**:  7.4.6

**Describe the question**

```
        $downloadResult = $s3Client->getObject([
          'Bucket' => 'bucket',
          'Key' => 'key',
          'SaveAs' => "$folderPath/$feedFileName"
        ]);
```

The above code snippet returns and instance of `\Aws\Result`. However, there are no methods on this instance of fetch the status code. `get` and `search` does not work.
```
        var_dump($downloadResult->search('statusCode'));
        var_dump($downloadResult->get('statusCode'));
        var_dump($downloadResult->search('metadata.statusCode'));
        var_dump($downloadResult->get('metadata.statusCode'));
```

Is there a way to get the statusCode? The last resort is to use Reflection. Seems like overkill.

**Comment by ajredniwja** [comment]
Hey @qwertynik thanks for opening the issue, I did something like: 

```php
$result = $client->getObject([
    'Bucket'=> 'bucket',
    'Key'=> 'key',
]);

$statuscode =  $result['@metadata']['statusCode'];

echo $statuscode;
```

Which works, so you can try that. 

Closing this issue now, please reach out if that doesn't solve your problem.

**Comment by qwertynik** [comment]
Thanks, @ajredniwja this worked. If possible, would be great if there is a method available on the ResultClass to get generic information like this.
