### ISSUE TITLE
Region must be a valid RFC host label.

### ISSUE THREAD

**Issue by satishjunghareewebcore** [aws/aws-sdk-php#2126]
I am passing credentials to env file and installed this sdk still getting following issue.

AWS_ACCESS_KEY_ID=************
AWS_SECRET_ACCESS_KEY=************
AWS_DEFAULT_REGION=************
AWS_BUCKET=************

**Version of AWS SDK for PHP?**
Example: "league/flysystem-aws-s3-v3": "^1.0"

**Version of PHP?**
7.4.10

> {
"message": "Region must be a valid RFC host label.",
"exception": "Aws\Exception\InvalidRegionException",
"file": "/var/www/unsold/nmiwebsite/vendor/aws/aws-sdk-php/src/ClientResolver.php",
"line": 543,
"trace": [

**Comment by OldRustyDayton** [comment]
Was this ever answered/solved? I am also experiencing this issue.

**Comment by alepee** [comment]
Same here. @OldRustyDayton did you get an answer ?

**Comment by timstrawbridge** [comment]
Are actually using a region? 
e.g: 
us-west-2
us-east-1

**Comment by SamRemis** [comment]
Here's a list of some of the valid regions which may be helpful for anyone looking at this thread: https://docs.aws.amazon.com/general/latest/gr/rande.html

The SDK takes in the format as a string, and should be in the value in the "code" column of the chart
