### ISSUE TITLE
[BUG] [MultipartCopy] Can't copy file with「?」mark

### ISSUE THREAD

**Issue by razielvamp666** [aws/aws-sdk-php#2130]
`src/S3/MultipartCopy.php` → `fetchSourceMetadata()`

```
private function fetchSourceMetadata()
{
    if ($this->config['source_metadata'] instanceof ResultInterface) {
        return $this->config['source_metadata'];
    }

    list($bucket, $key) = explode('/', ltrim($this->source, '/'), 2);
    $headParams = [
        'Bucket' => $bucket,
        'Key' => $key,
    ];
    if (strpos($key, '?')) {
        list($key, $query) = explode('?', $key, 2);
        $headParams['Key'] = $key;
        $query = Psr7\parse_query($query, false);
        if (isset($query['versionId'])) {
            $headParams['VersionId'] = $query['versionId'];
        }
    }
    return $this->client->headObject($headParams);
}
```

If `?` in `$key`, it's determined as query separator.
And `$key` is splitted to `$key` and `$query`.
But how can I copy file with source key is `path/ololo?imnotaquery.jpg` (Yes, it is possible to create file with ? mark in S3)

So characters after `?` can be both file name and query parameters

Why here `Key` is reassigned? Is there any reasons?
```
$headParams['Key'] = $key;
```

AWS working fine even if pass `headParams['Key']` with query string as is.

Looks like it will be better to remove this line.
In other case you need to separate `$this->source` and `$this->query`.

Here is my logs when I try to copy `/BUCKET/somepath/coc?py.mpg` (source) file
```
Error executing "HeadObject" on "https://BUCKET.s3.ap-northeast-2.amazonaws.com/somepath/coc"; AWS HTTP error: Client error: `HEAD https://BUCKET.s3.ap-northeast-2.amazonaws.com/somepath/coc` resulted in a `404 Not Found` response NotFound (client): 404 Not Found (Request-ID: D3B81271BF4D2891) - 
```

**Comment by SamRemis** [comment]
Hi @razielvamp666,
Thanks for your issue- a '?' character is currently one of the characters that is considered to require special handling by the sdk and should be URL encoded for the time being.  We will look into removing that line- if the headObject call works with query params, we should be able to remove it and fix the issue.

**Comment by SamRemis** [comment]
@razielvamp666 Sorry for the delay; I tried a few ways but couldn't get this to work reliably.  Since there isn't documentation stating otherwise, the SDK can't rely on parsing the query string server side and should remove the query parameters from the key.  Since query params don't have any strict requirements, we also can't reliably know where the query starts and the bucket ends and have to take the best guess with the '?'.

**Comment by razielvamp666** [comment]
I see.

But I think you should allow to choose where is file name and where is query string. Because "?"-bug in current version is a big limitation.
Adding optional `query` parameter to constructor may be good solution. If `query` is `null` the logic is the same, in other case code relies filename and query separation on user parameters in constructor.

**Comment by SamRemis** [comment]
@razielvamp666, that's a good idea, I will talk to the team about implementing that.

**Comment by SamRemis** [comment]
Hi @razielvamp666,
The PR is done and will be merged ASAP.  The new parameter is 'copy_file_path', and is the filename itself and not the query.  So for instance, to copy a file with the name 'the-fil?e-name' and a version id of 'xyz', you would call: 
```
$copier = new Aws\S3\MultipartCopy(
    $s3Client,
    '/sourceBucket/the-fil?e-name',
    [
        'Bucket' => 'destinationBucket',
        'copy_file_path' => 'the-fil?e-name',
        'Key' => 'destinationKey',
    ]
);
$result = $copier->copy();
```
