### ISSUE TITLE
Ec2 DescribeInstances results coming from incorrect account when using SDK, but not CLI.

### ISSUE THREAD

**Issue by gageleblanc** [aws/aws-sdk-php#2138]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
Results returned by the PHP SDK are not the same as results returned by the aws cli even when using the same credentials and same region. I was not able to find a way to configure the SDK or CLI to use a specific aws account. It seems the cli does this automatically but the SDK does not. 

**Version of AWS SDK for PHP?**
`aws/aws-sdk-php                      3.158.19           AWS SDK for PHP - Use Amazon Web Services in your PHP project`

**Version of PHP (`php -v`)?**
```
PHP 7.4.12 (cli) (built: Oct 31 2020 17:04:25) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologies
```

**To Reproduce (observed behavior)**

1. Have multiple AWS accounts under one organization (I.e. account 1, account 2, account 3)
2. Use Ec2Client in PHP SDK to describeInstances with no filters and max results set to 1000 using IAM credentials for account 2
3. Do the same thing using the cli
4. Observe inconsistent results

**Expected behavior**
I expect the returned instances between the cli and php sdk to be the same. I am completely unable to get instances from account 2 through the sdk and am only able to get instances from account 1. From the cli, I am able to get instances from account 2 as expected. The CLI and SDK are using the same credentials.

**Additional context**
See SO question asked here. After some additional testing between the cli and SDK, I am more inclined to believe this is a bug.
https://stackoverflow.com/questions/64685377/php-aws-sdk-returning-different-results-than-aws-cli

**Comment by gageleblanc** [comment]
I also want to note that I was able to achieve the expected functionality by using the python library boto3.

**Comment by ajredniwja** [comment]
Hey @gageleblanc thanks for opening this issue, can you please share the PHP code that you are using to reproduce the issue?
