### ISSUE TITLE
Error executing "CompleteMultipartUpload" operation resulting in `400 Bad request` response

### ISSUE THREAD

**Issue by omadoyeabraham** [aws/aws-sdk-php#2140]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [*] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [*] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [*] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
Trying to upload a file to S3 with size greater that ObjectUploader::DEFAULT_MULTIPART_THRESHOLD = 16777216 results in a 400 error with the following error message: 

`'An exception occurred while completing a multipart upload: Error executing "CompleteMultipartUpload"`

N.B The error only occurs when uploading files using the MultiPartUploader. For smaller file sizes (i.e < 16mb) the upload works fine because the MultiPartUploader is not used.

**Version of AWS SDK for PHP?**
 v3.160.0

**Version of PHP?**
PHP 7.3.10

**To Reproduce (observed behavior)**
1. Setup a sample project with `yes | composer init && composer require aws/aws-sdk-php`
2. Create a file called upload.php `touch upload.php`
3. Copy the code snippet below into the file

```php
<?php

require('vendor/autoload.php');

$filename = tempnam(sys_get_temp_dir(), 'test-file');

file_put_contents($filename, str_repeat('l', 20 * 1048576));

$key    = 'KEY'; // Replace key with your AWS key
$secret = 'SECRET'; // Replace secret with your AWS secret

$credentials = new Aws\Credentials\Credentials($key, $secret);

$client = new \Aws\S3\S3Client([
    'credentials' => [
        'key'    => $key,
        'secret' => $secret,
    ],
    'region'  => 'us-east-1',
    'version' => 'latest',
]);

$client->upload('trackstreet', 'test-file/20mb', fopen($filename, 'r')); // replace bucket-name with the name of your S3 bucket
```

**Expected behavior**
The file should be uploaded to S3 using the MultipartUploader, and a success response returned.

**Additional context**
This error was initially observed in a Laravel 7 project

**Comment by ajredniwja** [comment]
Hey @omadoyeabraham thanks for opening this issue, I was not able to reproduce this issue

The code I used: 
```php
<?php
require 'vendor/autoload.php';

use Aws\S3\S3Client;
use Aws\S3\Exception\S3Exception;


$s3 = new S3Client([
    'version' => 'latest',
    'region'  => 'us-west-2'
]);

$filename = tempnam(sys_get_temp_dir(), 'test-file');
file_put_contents($filename, str_repeat('l', 20 * 1048576));

try {
    $result = $s3->upload('testBucket', 'testObjectV2', fopen($filename, 'r'));
    echo $result['ObjectURL'] . PHP_EOL;
} catch (S3Exception $e) {
    echo $e->getMessage() . PHP_EOL;
}

echo Aws\Sdk::VERSION;
```

The file size I used was around 500MB. 

Output:
```
https://testBucket.s3.us-west-2.amazonaws.com/testObjectV2

3.158.6 //sdk version

```

With php -v: `PHP 7.4.10`

Can you make sure you have the correct SDK version?

**Comment by pablomoreno61** [comment]
I have the exact same issue with version 3.158.21
