### ISSUE TITLE
changeResourceRecordSets - >SenderAccessDeniedUser Error

### ISSUE THREAD

**Issue by azaddeveloper** [aws/aws-sdk-php#2141]
I  am getting this error. When I am creating a subdomain 

Error executing "ChangeResourceRecordSets" on "https://route53.amazonaws.com/2013-04-01/hostedzone/Z38NKT9BP95V3O/rrset/"; AWS HTTP error: Client error: `POST https://route53.amazonaws.com/2013-04-01/hostedzone/Z38NKT9BP95V3O/rrset/` resulted in a `403 Forbidden` response: Sender SenderAccessDeniedUser: arn:aws:iam::457910130955:user/ is not authorized to access this resourceaa78f434-adcc-4438-bc94-3ffed143a74f

This code I am using 

            try {

		    $dns = 'mydomainname.us';
		    $HostedZoneId = 'O38NKT9BP9586O'; // this is my elastic beanstalk zoneId
		    $name = 'test.mydomainname.us'; //eg. subdomain name i want to create 
		    $ip = '12.226.219.18'; // this is my elastic beanstalk IP 
		    $ttl = 600;
		    $recordType = 'A';
		    $result = $client->changeResourceRecordSets(array(
			    'HostedZoneId' => $HostedZoneId,
			    'ChangeBatch' => array( 
			        'Comment' => 'string',
			        'Changes' => array(
			            array(
			               'Action' => 'CREATE',
			                'ResourceRecordSet' => array(
			                    'Name' => $name,
			                    'Type' => $recordType,
			                    'TTL' => $ttl, 
			                    'ResourceRecords' => array(
			                        array(
			                            'Value' =>  $ip,
			                        ),
			                    ),
			                ),
			            ),
			        ),
			    ),
			));
		} catch (Exception $e) {
		        echo $e->getMessage();
		}

My aim is I want to create a subdomain and assign it to the Elastic Beanstalk. Like we do From the AWS Interface.

Thanks

**Comment by azaddeveloper** [comment]
@ajorg-aws  Can you please help me to solve this issue?

**Comment by ajorg-aws** [comment]
Hello!

I'm not on the team that supports this SDK, but I'll ensure that they take a look.

**Comment by ajredniwja** [comment]
@azaddeveloper thanks for the issue, this error occurs when you don't have the correct permissions, can you check the user has correct permissions?
