### ISSUE TITLE
AWS SNS sending text messgae is not working with same credentials in multiple servers.

### ISSUE THREAD

**Issue by djlithin** [aws/aws-sdk-php#2142]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
v3.150.2

**Version of PHP ?**
v7.3.5

**Describe the question**
I am using aws-sdk-php for sending  text messages from my one server. When I tried the same API with same credentials from a clone of this server, I got following error. 
Please note that both instances are running in google cloud platform.
I took a image of the working instance and created another instance using that image file in same region. My intention was to keep one as test and other as live. But all the functionalities are working except aws-sdk-php library in newly the created one.

An uncaught Exception was encountered
Type: Aws\Sns\Exception\SnsException

Message: Error executing "Publish" on "https://sns.ap-south-1.amazonaws.com "; AWS HTTP error: cURL error 7: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html ) for https://sns.ap-south-1.amazonaws.com 

Filename: /usr/share/nginx/html/serviceFinderAPI/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php

please see the code

`

     use Aws\Sns\SnsClient; 
     use Aws\Exception\AwsException;

    class Sms {

    private $client = null;

    public function __construct()
    {
	   	 $this->client = new SnsClient([
		    'region' => 'ap-south-1',
		    'version' => 'latest',
		    'credentials' => [
		        'key' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx',
		        'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
			  ]
		]);
    }

    public function send_sms( $PhoneNumber, $message)
    {
       
        return $this->client->publish(['Message' => $message,'PhoneNumber' => $PhoneNumber]);
     }
     }`

**Comment by ajredniwja** [comment]
Hey @djlithin, thanks for opening this issue, while I was not able to reproduce the issue, is it possible got you to share the complete stack trace?

**Comment by djlithin** [comment]
> 
> 
> Hey @djlithin, thanks for opening this issue, while I was not able to reproduce the issue, is it possible got you to share the complete stack trace?

Please see the complete stack trace.

An uncaught Exception was encountered
Type: Aws\Sns\Exception\SnsException

Message: Error executing "Publish" on "https://sns.ap-south-1.amazonaws.com"; AWS HTTP error: cURL error 7: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://sns.ap-south-1.amazonaws.com

Filename: /usr/share/nginx/html/serviceFinderAPI/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php

Line Number: 195

Backtrace:

File: /usr/share/nginx/html/serviceFinderAPI/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php
Line: 97
Function: parseError

File: /usr/share/nginx/html/serviceFinderAPI/vendor/guzzlehttp/promises/src/Promise.php
Line: 204
Function: Aws\{closure}

File: /usr/share/nginx/html/serviceFinderAPI/vendor/guzzlehttp/promises/src/Promise.php
Line: 169
Function: callHandler

File: /usr/share/nginx/html/serviceFinderAPI/vendor/guzzlehttp/promises/src/RejectedPromise.php
Line: 42
Function: GuzzleHttp\Promise\{closure}

File: /usr/share/nginx/html/serviceFinderAPI/vendor/guzzlehttp/promises/src/TaskQueue.php
Line: 48
Function: GuzzleHttp\Promise\{closure}

File: /usr/share/nginx/html/serviceFinderAPI/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php
Line: 158
Function: run

File: /usr/share/nginx/html/serviceFinderAPI/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php
Line: 183
Function: tick

File: /usr/share/nginx/html/serviceFinderAPI/vendor/guzzlehttp/promises/src/Promise.php
Line: 248
Function: execute

File: /usr/share/nginx/html/serviceFinderAPI/vendor/guzzlehttp/promises/src/Promise.php
Line: 224
Function: invokeWaitFn

File: /usr/share/nginx/html/serviceFinderAPI/vendor/guzzlehttp/promises/src/Promise.php
Line: 269
Function: waitIfPending

File: /usr/share/nginx/html/serviceFinderAPI/vendor/guzzlehttp/promises/src/Promise.php
Line: 226
Function: invokeWaitList

File: /usr/share/nginx/html/serviceFinderAPI/vendor/guzzlehttp/promises/src/Promise.php
Line: 269
Function: waitIfPending

File: /usr/share/nginx/html/serviceFinderAPI/vendor/guzzlehttp/promises/src/Promise.php
Line: 226
Function: invokeWaitList

File: /usr/share/nginx/html/serviceFinderAPI/vendor/guzzlehttp/promises/src/Promise.php
Line: 62
Function: waitIfPending

File: /usr/share/nginx/html/serviceFinderAPI/vendor/aws/aws-sdk-php/src/AwsClientTrait.php
Line: 58
Function: wait

File: /usr/share/nginx/html/serviceFinderAPI/vendor/aws/aws-sdk-php/src/AwsClientTrait.php
Line: 86
Function: execute

File: /usr/share/nginx/html/serviceFinderAPI/application/libraries/Sms.php
Line: 30
Function: __call

File: /usr/share/nginx/html/serviceFinderAPI/application/libraries/Auth.php
Line: 214
Function: send_sms

File: /usr/share/nginx/html/serviceFinderAPI/application/controllers/Customer.php
Line: 149
Function: send_otp

File: /usr/share/nginx/html/serviceFinderAPI/application/controllers/Customer.php
Line: 33
Function: send_otp

File: /usr/share/nginx/html/serviceFinderAPI/index.php
Line: 315
Function: require_once

**Comment by ajredniwja** [comment]
Hey @djlithin this does seem to be a configuration error on the other instance, can you make sure that there is no environment variables set incorrectly or any other configurational changes? 

Can you also check if you are able to call any service at all, for example you can try calling `S3.ListBuckets`.
