### ISSUE TITLE
Test error handling of S3Client uploadAsync method

### ISSUE THREAD

**Issue by matjazmav** [aws/aws-sdk-php#2143]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
`3.80.3`

**Version of PHP (`php -v`)?**
```
PHP 7.4.11 (cli) (built: Oct  8 2020 17:31:46) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies
```

**Describe the question**

Method `uploadAsync` automatically decides and uploads object in single or multiple chunks. And we can expect 2 different kind of expectations `S3Exception` and `S3MultipartUploadException` in our `$result['reason']`. I'm trying to mock part of the S3 client to throw the exception, I have done this by MockHandler:

```
$s3->getHandlerList()->setHandler(new MockHandler([$result], null, null)); 
```

And the `$result` is:
```
new S3Exception("", new Command("mockCommand"), [
                    'code' => 'mockCode',
                    'response' => new Response(401)
                ])
```

Or either this:
```
new S3MultipartUploadException(new UploadState(['testid']))
```

Since the `S3MultipartUploadException` is not instance of `AwsException` I got this exception:
`InvalidArgumentException: Expected an Aws\ResultInterface or Aws\Exception\AwsException.`

How can I handle such scenario?

**Comment by ajredniwja** [comment]
Hey @matjazmav thanks for opening this issue, created a PR for this which should fix this issue.

**Comment by matjazmav** [comment]
Great news, thank you :)
