### ISSUE TITLE
getCostAndUsage filtering by tag is not working for some tags

### ISSUE THREAD

**Issue by ktecho** [aws/aws-sdk-php#2145]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
Some tags cannot be used in the Cost Management API but they work using the EC2 API and the AWS Console:

Here I'm looking for one specific instance with tag `LX_Instance_ID_Main_Node` = `39`:
```
$describedAMIs = (new AWS($this->ci))->getEC2Client('us-east-1')->describeInstances([
    'Filters' => [
        [
            'Name' => 'tag:LX_Instance_ID_Main_Node',
            'Values' => [
                '39',
            ],
        ],
    ],
]);
```

It works without problem:

```
    [data:Aws\Result:private] => Array
        (
            [Reservations] => Array
                (
                    [0] => Array
                        (
                            [Groups] => Array
                                (
                                )

                            [Instances] => Array
                                (
                                    [0] => Array
                                        (
                                            [AmiLaunchIndex] => 0
                                            [ImageId] => ami-0864165c49d93fbb3
                                            [InstanceId] => i-0ad52e3ae3479e39c
[...]
                                            [Tags] => Array
                                                (
                                                    [0] => Array
                                                        (
                                                            [Key] => LX_Instance_ID_Main_Node
                                                            [Value] => 39
                                                        )
[...]
                                                    [2] => Array
                                                        (
                                                            [Key] => LX_Instance_ID
                                                            [Value] => 39
                                                        )
                                                )
```

There you can see that the object has both tags that I'll use to search for the cost of the instance: `LX_Instance_ID_Main_Node` and `LX_Instance_ID`. I can use both of them with `describeInstances` and they will all work. Now I'll try to get the cost for that instance using the first tag (`LX_Instance_ID_Main_Node`):

```
$result = ($this->getCostExplorerClient())->getCostAndUsage([
            'Metrics' => [
                'UsageQuantity',
                'BlendedCost'
            ],
            'Granularity' => 'DAILY',
            'TimePeriod' => [
                'Start' => $yesterday,
                'End' => $today,
            ],
            'Filter' => [
                'Tags' => [
                    'Key' => 'LX_Instance_ID_Main_Node',
                    'Values' => [39]
                ],
            ],
            "GroupBy" =>[
                [
                    'Type' => 'TAG',
                    'Key' => 'LX_Instance_ID_Main_Node'
                ],
                [
                    'Type' => 'DIMENSION',
                    'Key' => 'USAGE_TYPE'
                ]
            ],
        ];;
```

This returns no usage at all (0 cost, 0 quantity):

```
Aws\Result Object
(
    [data:Aws\Result:private] => Array
        (
            [GroupDefinitions] => Array
                (
                    [0] => Array
                        (
                            [Type] => TAG
                            [Key] => LX_Instance_ID_Main_Node
                        )

                    [1] => Array
                        (
                            [Type] => DIMENSION
                            [Key] => USAGE_TYPE
                        )

                )

            [ResultsByTime] => Array
                (
                    [0] => Array
                        (
                            [TimePeriod] => Array
                                (
                                    [Start] => 2020-11-21
                                    [End] => 2020-11-22
                                )

                            [Total] => Array
                                (
                                    [BlendedCost] => Array
                                        (
                                            [Amount] => 0
                                            [Unit] => USD
                                        )

                                    [UsageQuantity] => Array
                                        (
                                            [Amount] => 0
                                            [Unit] => N/A
                                        )

                                )

                            [Groups] => Array
                                (
                                )

                            [Estimated] => 1
                        )

                )
[...]
```

But if I do the very same request, just changing from one of the tags `LX_Instance_ID_Main_Node` to the other one `LX_Instance_ID`, I get all the costs:

```
Aws\Result Object
(
    [data:Aws\Result:private] => Array
        (
            [GroupDefinitions] => Array
                (
                    [0] => Array
                        (
                            [Type] => TAG
                            [Key] => LX_Instance_ID
                        )

                    [1] => Array
                        (
                            [Type] => DIMENSION
                            [Key] => USAGE_TYPE
                        )

                )

            [ResultsByTime] => Array
                (
                    [0] => Array
                        (
                            [TimePeriod] => Array
                                (
                                    [Start] => 2020-11-21
                                    [End] => 2020-11-22
                                )

                            [Total] => Array
                                (
                                )

                            [Groups] => Array
                                (
                                    [0] => Array
                                        (
                                            [Keys] => Array
                                                (
                                                    [0] => LX_Instance_ID$39
                                                    [1] => BoxUsage:m5.2xlarge
                                                )

                                            [Metrics] => Array
                                                (
                                                    [BlendedCost] => Array
                                                        (
                                                            [Amount] => 0.653333376
                                                            [Unit] => USD
                                                        )

                                                    [UsageQuantity] => Array
                                                        (
                                                            [Amount] => 1.701389
                                                            [Unit] => Hrs
                                                        )

                                                )

                                        )

                                    [1] => Array
                                        (
                                            [Keys] => Array
                                                (
                                                    [0] => LX_Instance_ID$39
                                                    [1] => BoxUsage:m5.4xlarge
                                                )

                                            [Metrics] => Array
                                                (
                                                    [BlendedCost] => Array
                                                        (
                                                            [Amount] => 2.610346752
                                                            [Unit] => USD
                                                        )

                                                    [UsageQuantity] => Array
                                                        (
                                                            [Amount] => 3.398889
                                                            [Unit] => Hrs
                                                        )

                                                )

                                        )
[...]
```

If I try to see if tags are known by the Cost Explorer API, it seems just one of the two tags (`LX_Instance_ID`) is present, but the other one (`LX_Instance_ID_Main_Node`) is not:

```
$result = ($this->getCostExplorerClient())->getTags([
    'TimePeriod' => [
        'Start' => Carbon::yesterday()->subDays(2)->toDateString(),
        'End' => Carbon::today()->toDateString(),
    ],
]);

(
    [0] => aws:createdBy
    [1] => aws:ec2launchtemplate:id
    [2] => aws:ec2launchtemplate:version
    [3] => aws:ec2spot:fleet-request-id
    [4] => Author
    [5] => Environment
    [6] => LX_Instance_ID
    [7] => LX_User_ID
    [8] => Name
    [9] => UsedBy
    [10] => firstname
    [11] => creator
    [12] => gitlab
    [13] => version
    [14] => runner
)
```
So, no wonder why the filtering by one of the tags doesn't work: the Cost Explorer API cannot see that tag.

But again, if you look at the EC2 instance in the AWS console, you can see both tags (both were created at creation time (more than 24 hours ago) and not modified later):

![image](https://user-images.githubusercontent.com/547169/99937687-971b6080-2d66-11eb-8660-fc3fed078361.png)

The Tag explorer in the EC2 explorer also can see both tags with its value:

![image](https://user-images.githubusercontent.com/547169/99939333-1cecdb00-2d6a-11eb-8e20-d14b7226b2ca.png)

**Version of AWS SDK for PHP?**
3.163.2

**Version of PHP (`php -v`)?**
7.4.3

**To Reproduce (observed behavior)**
1- Create an EC2 instance with several tags [LX_Instance_ID, LX_Instance_ID_Main_Node, xxxxxx, ...]
2- Go to AWS Console and check that all the tags are there (see screenshot).
3- Wait more than 24 hours
4- Try `describeInstances` filtering by tag `LX_Instance_ID`, it works and shows the instance
5- Try `describeInstances` filtering by tag `LX_Instance_ID_Main_Node`, it works and shows the instance
6- Try `getCostAndUsage` filtering by tag `LX_Instance_ID`, it works and gets the cost
7- Try `getCostAndUsage` filtering by tag `LX_Instance_ID_Main_Node`, doesn't work (doesn't show anything)
8- Try `getTags` and I can only get `LX_Instance_ID` but not `LX_Instance_ID_Main_Node` for the same time period

**Expected behavior**
I expect `getCostAndUsage` filtering that works based on any of the tags on the instance, and `getTags` seeing all the tags that I'm using.

**Comment by ktecho** [comment]
@diehlaws Hey Alex. Could you give a look to this issue? It's similar to #2073 that I reported some months ago. It got fixed, but using a new tag it's happening again. Could it be that new tags don't appear in the Cost Explorer until the end of the month or something like that? Thanks!

**Comment by SamRemis** [comment]
Hi @ktecho,
Thank you for bringing this to our attention; Alex hasn't been with amazon for a few months, he moved on to the next opportunity. @ajredniwja, could you look at this?  
I took a glance at it and it appears to be an issue with the service, not the SDK, but this will need more invesigation to confirm

**Comment by ktecho** [comment]
@SamRemis This time I didn't test it with the CLI, but it seems the problem is the same one. It should be time-related. It's like it doesn't work at first, but then at some point it starts working for that tag. But if you put a new tag, doesn't work again.

**Comment by ktecho** [comment]
Hi @ajredniwja Have you seen something related with this issue? Thanks!

**Comment by ajredniwja** [comment]
> Hi @ajredniwja Have you seen something related with this issue? Thanks!

Hey @ktecho, apologies for late reply here, I see that PHP SDK doesn't have any customizations around this service which means it is most likely a service API issue, I have reached out to the respective team, will have an update for you soon.

**Comment by ktecho** [comment]
@ajredniwja Thanks a lot, I'll keep awaiting your reply.

**Comment by ajredniwja** [comment]
> @ajredniwja Thanks a lot, I'll keep awaiting your reply.

Hey @ktecho, can you please provide with `accountId` and `resourceId`?

**Comment by ktecho** [comment]
Hi @ajredniwja  I can provide the account id (231967442015), but I didn't save the resourceId. I don't know if you can use the InstanceId provided in the logs to search for it.

**Comment by ajredniwja** [comment]
From the team

1. Tags needs to be manually activated in billing console, before they appear on any reports.
2. Tags will only be applied to usages that occurred after the tag is activated. For example, If customer enabled a tag at the end of the month at 22:00, a resource will be only tagged from 22:00 to 00:00

Also found that `LX_Instance_ID_Main_Node` and `LX_Instance_ID` were not active which might be the reason why those are not working when filtering using tags.

**Comment by ktecho** [comment]
> From the team
> 
> 1. Tags needs to be manually activated in billing console, before they appear on any reports.
> 2. Tags will only be applied to usages that occurred after the tag is activated. For example, If customer enabled a tag at the end of the month at 22:00, a resource will be only tagged from 22:00 to 00:00
> 
> Also found that `LX_Instance_ID_Main_Node` and `LX_Instance_ID` were not active which might be the reason why those are not working when filtering using tags.

Well, in the end it started working by itself. But anyways, thanks for the reply and I'll create the tags in the console.
