### ISSUE TITLE
Email Tracking 

### ISSUE THREAD

**Issue by ichtrojan** [aws/aws-sdk-php#2146]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP? v3.155.19**
Example: v3.133.6
* get SDK version by printing the output of `Aws\Sdk::VERSION` in your code 
* if the SDK was installed via composer you can see the version installed with `composer show -i` 

**Version of PHP (`php -v`)?  v7.4**

**Describe the question**

How can I enable email tracking on this SDK, Ive seen some implement other packages, I just want to know if its possible on this.

**Comment by ajredniwja** [comment]
Hey @ichtrojan, thanks for opening this issue, I don't know if I understand your question. 

Are you looking for information on [SES](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-using-sdk-php.html)?

**Comment by ichtrojan** [comment]
Yes, SES email tracking, does this package support it?

**Comment by ajredniwja** [comment]
> Yes, SES email tracking, does this package support it?

Yes, SES service is supported by the PHP SDK please check:

https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-using-sdk-php.html

https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/ses-examples.html
