### ISSUE TITLE
MediaConvert Json Validation returns HTTP 400

### ISSUE THREAD

**Issue by webciter** [aws/aws-sdk-php#2148]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
Json Validation in MediaConvert Returns HTTP 400 
/outputGroups/0/outputs/0/videoDescription/codecSettings: Should have at least 2 properties

The Value of CodecSettings is
```
"CodecSettings" => [
    "Codec" => "VP9",
    "Vp9Settings" => [
      "QualityTuningLevel"=> "MULTI_PASS_HQ",
      "RateControlMode"=> "VBR",
      "GopSize"=> 90,
      "MaxBitrate"=> 1512000,
      "Bitrate"=> 932400,
      "HrdBufferSize"=> 22680000,
      "FramerateControl"=> "INITIALIZE_FROM_SOURCE",
      "FramerateConversionAlgorithm"=> "DUPLICATE_DROP",
      "ParControl"=>"INITIALIZE_FROM_SOURCE"
    ]
  ],
```
Version of AWS SDK
v3.133.46

PHP Version
PHP 7.3.21-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Aug  7 2020 14:44:10) ( NTS )

**Expected behavior**
send video file from s3 to MediaConvert Queue, my h264 code is functioning correctly, iv tried to copy the code from MediaConvert Front End Aswell, this works ok on the aws website but not on my own product.

**Comment by ajredniwja** [comment]
Hey @webciter, thanks for opening this issue can you please share the complete code that you are using and what API you are talking about?

**Comment by webciter** [comment]
this bug was fixed with upgrading the package
