### ISSUE TITLE
Env vars not accessible via getenv()

### ISSUE THREAD

**Issue by mheki** [aws/aws-sdk-php#2154]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
Hello,
we have an issue with `EcsCredentialProvider` getting env variables by a non-thread save `getenv()`.
The same code works fine when reached by a browser, but doesn't work when triggered by a cron.
Our use case was to push CSV file to S3 bucket in another AWS account.
The error from a cronjob was 
```
Aws\Exception\CredentialsException Error retrieving credentials from the instance profile metadata service. (cURL error 7:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://169.254.169.254/latest/meta-data/iam/security-credentials/
```
This meant `EcsCredentialProvider` wasn't used to provide credentials. When I investigated the issue I realised `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`  env var returned by `getenv()` was false, but was available in both `$_SERVER` and `$_ENV` variables.
I'll create a PR with the code change which helped us fix the issue.

**Version of AWS SDK for PHP?**
3.164.0
**Version of PHP (`php -v`)?**
7.4.9

**To Reproduce (observed behavior)**
- Create an S3 bucket on `A` AWS account.
- Add relevant permissions to the `A` account bucket allowing adding files by `B` AWS role/account.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::xxxxxxxxx:role/foo"
            },
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl"
            ],
            "Resource": "arn:aws:s3:::test-bucket-upload/*",
            "Condition": {
                "StringEquals": {
                    "s3:x-amz-acl": "bucket-owner-full-control"
                }
            }
        }
    ]
}
```
- send CSV file from PHP code triggered by cron (I use FlySystem lib abstraction for that)

**Expected behavior**
CSV file should land on S3 bucket owned by account A (bucket owner needs to be able to read that file)

**Comment by ajredniwja** [comment]
Hey @mheki thanks for opening this issue, I see you have a PR related to the issue, thanks for that, I will have someone from the team review it.

**Comment by SamRemis** [comment]
For future reference: the PR was merged and had to be reverted because of tests failing on certain set ups.  The PR changes were recreated by PR #2176.  Thank you to @mheki and your team for being so responsive and for your contribution to the SDK.
