### ISSUE TITLE
[BUG?] Does S3 MulipartUploader closes source streams properly?

### ISSUE THREAD

**Issue by razielvamp666** [aws/aws-sdk-php#2159]
I need to
1. temporarily mount partition at Linux
2. write file in this partition
3. upload file to S3
4. unmount partition

**Problem** → after creating `$uploader = new Aws\S3\MultipartUploader(...)` I don't able to unmount partition inside running script because of `target is busy`. 

I added code fragment for better understanding of process:

```php
$client = new Aws\S3\S3Client($config);

// Try to unmount
// ABLE TO UNMOUNT PARTITION HERE
print_r("\n ------------ BEFORE UPLOADER --------------\n");
print_r(get_resources('stream'));

$uploader = new Aws\S3\MultipartUploader($client, $source, [
    'bucket' => $BUCKET,
    'key' => $KEY,
]);

// Try to unmount
// FROM HERE PARTITION IS BUSY
print_r("\n ------------ AFTER UPLOADER --------------\n");
print_r(get_resources('stream'));
$retry = 0;
while (!isset($upload_result)) {
    try {
        $upload_result = $uploader->upload();
    } catch (Aws\Exception\MultipartUploadException $e) {
        if ($retry <= 10) {
            sleep(1);
            $retry += 1;
            $uploader = new Aws\S3\MultipartUploader($client, $source, [
                'state' => $e->getState(),
            ]);
        } else {
            $params = $e->getState()->getId();
            $upload_result = $client->abortMultipartUpload($params);
            throw new Exception('Output file upload error: '.$upload_result);
        }
    }
}

// Try to unmount
// PARTITION STILL BUSY
print_r("\n ------------ AFTER UPLOAD --------------\n");
print_r(get_resources('stream'));
unset($client);
unset($uploader);

// Try to unmount
// PARTITION BUSY AND OPENED RESOURCES STILL PRESENT EVEN IF OBJECTS DELETED
print_r("\n ------------ AFTER UNSET UPLOADER --------------\n");
print_r(get_resources('stream'));
```

Output is

```shell
 ------------ BEFORE UPLOADER --------------
Array
(
    [1] => Resource id #1
    [2] => Resource id #2
    [3] => Resource id #3
    [157] => Resource id #157
    [158] => Resource id #158
)

 ------------ AFTER UPLOADER --------------
Array
(
    [1] => Resource id #1
    [2] => Resource id #2
    [3] => Resource id #3
    [157] => Resource id #157
    [158] => Resource id #158
    [175] => Resource id #175
)

 ------------ AFTER UPLOAD --------------
Array
(
    [1] => Resource id #1
    [2] => Resource id #2
    [3] => Resource id #3
    [157] => Resource id #157
    [158] => Resource id #158
    [175] => Resource id #175
    [181] => Resource id #181
    [182] => Resource id #182
    [198] => Resource id #198
    [202] => Resource id #202
    [203] => Resource id #203
)

 ------------ AFTER UNSET UPLOADER --------------
Array
(
    [1] => Resource id #1
    [2] => Resource id #2
    [3] => Resource id #3
    [157] => Resource id #157
    [158] => Resource id #158
    [175] => Resource id #175
    [181] => Resource id #181
    [182] => Resource id #182
    [198] => Resource id #198
    [202] => Resource id #202
    [203] => Resource id #203
)
```
So we can see that opened resources is opened before script ends.
I checked `AbstractUploadManager` class and there is no `close()` like methods.

Any ideas? Is that is usual PHP behavior?

**Comment by SamRemis** [comment]
@razielvamp666 Good catch, it does look like we have some unclosed resources.  So far, I've only been able to pinpoint and close one of them- the one that actually points to the open file; in your case, I believe it's #157.  I am working on finding the others and will see if they are able to be closed as well.  It looks like they're mostly opened when initiating the upload.  

I will also discuss adding a close method to the abstract upload manager with the team.  Thank you for bringing this to our attention

**Comment by SamRemis** [comment]
@razielvamp666 On closer inspection, most of the stream references you're seeing are made by guzzle automatically.  Like the AWS SDK's code, the garbage collector will close the stream and remove the reference when the __destruct() method is called on the resource.  I think this is normal behavior for PHP.  How are you attempting to unmount it and what is the output of LSOF?

**Comment by razielvamp** [comment]
> How are you attempting to unmount it?

That was something like

```
$mount_point = '/path/to/mounted/directory';
shell_exec("sudo mount -t tmpfs -o size=128m,mode=0750,uid=1000,gid=1000 tmpfs '$mount_point'");
...
$umount_result = shell_exec("sudo umount $mount_point");
echo $umount_result;
```

> and what is the output of LSOF?

Sorry, I'm working on another project now, so don't able to rerun code and reproduce behaviour

**Comment by razielvamp666** [comment]
> How are you attempting to unmount it?

That was something like

```
$mount_point = '/path/to/mounted/directory';
shell_exec("sudo mount -t tmpfs -o size=128m,mode=0750,uid=1000,gid=1000 tmpfs '$mount_point'");
... SOME CODE ...

// workaround to properly run umount ----
array_map('fclose', get_resources('stream'));
// ----------------------------------------
$umount_result = shell_exec("sudo umount $mount_point");
echo $umount_result;
```

> and what is the output of LSOF?

Sorry, I'm working on another project now, so don't able to rerun code and reproduce behaviour

> the garbage collector will close the stream and remove the reference when the __destruct() method is called on the resource

So is there any way to call `__destruct()` method? As I understanding I can't access guzzle resources directly from my code , so looks like there is needed some `destruct()` or `close()` public method.
