### ISSUE TITLE
How I can get size of folder in my bucket?

### ISSUE THREAD

**Issue by Artem2710** [aws/aws-sdk-php#2160]
**Version of AWS SDK for PHP?**
v3.24.6

**Version of PHP (`php -v`)?**
7.1

**Describe the question**
How I can get size of folder in my bucket?

I use this code
`$s3 = new S3Client([
            'version' => $aws['version'],
            'region'  => $aws['region'],
            'credentials' => $credentials
        ]);`

`$results = $s3->getPaginator('ListObjects', [
                'Bucket' => $bucket,
            ]);`

but I dont need the whole list of my folders, just one specific folder

**Comment by SamRemis** [comment]
Hi @Artem2710,
There isn't an API call for that since S3 doesn't have a true folder hierarchy ([you can read more here](https://docs.aws.amazon.com/AmazonS3/latest/user-guide/using-folders.html) )

However, this can be easily accomplished by listing all of the objects in your folder and adding them up like so
```

$s3 = new S3Client([
    'version' => 'latest',
    'region'  => 'us-east-2'
]);
$totalSize = 0;
try {
    $results = $s3->getPaginator('ListObjects', [
        'Bucket' => $bucket,
        'Prefix' => 'exampleFolder/'
    ]);

    foreach ($results as $result) {
        foreach ($result['Contents'] as $object) {
            echo "Size of current object: " . $object['Size'] . PHP_EOL;
            $totalSize += $object['Size'];
        }
    }
    echo "**************************************" . PHP_EOL;
    echo "Total size: " . $totalSize . PHP_EOL;

} catch (S3Exception $e) {
    echo $e->getMessage() . PHP_EOL;
}

```

Hope that helps!
-Sam

**Comment by SamRemis** [comment]
I also have set this issue to closing-soon, so it will close in 4 days if you don't have any further questions

**Comment by ajredniwja** [comment]
Closing this issue now, please reach out if you have any other questions.
