### ISSUE TITLE
Class EcsCredentialProvider Doesn't Support Customized Guzzle Handler

### ISSUE THREAD

**Issue by deminy** [aws/aws-sdk-php#2162]
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**

Class _\Aws\Credentials\EcsCredentialProvider_ doesn't support customized Guzzle handler.

**Version of AWS SDK for PHP?**

v3.166.2

**Version of PHP (`php -v`)?**

PHP 7.4.12

**To Reproduce (observed behavior)**

We used to call some AWS APIs with credentials hardcoded. e.g.,

```php
use Aws\Ses\SesClient;
use GuzzleHttp\HandlerStack;

new SesClient(
    [
        'region'       => 'us-east-1',
        'version'      => 'latest',
        'credentials'  => ['key' => '', 'secret' => ''],
        'http_handler' => HandlerStack::create(new CustomizedGuzzleHandler()),
    ]
);
```

Please note that here we use a customized Guzzle handler.

Recently we switched to use [IAM Roles for Tasks](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html),
 and started calling the AWS APIs like following:

 ```php
 use Aws\Ses\SesClient;
 use GuzzleHttp\HandlerStack;
 
 new SesClient(
     [
         'region'       => 'us-east-1',
         'version'      => 'latest',
         'http_handler' => HandlerStack::create(new CustomizedGuzzleHandler()),
     ]
 );
```

The problem is that, the API call starts using the default handler, but not the customized one we specified.

**Expected behavior**

Here is the constructor in class [\Aws\Credentials\EcsCredentialProvider](https://github.com/aws/aws-sdk-php/blob/3.166.2/src/Credentials/EcsCredentialProvider.php#L37):

```php
class EcsCredentialProvider {
    public function __construct(array $config = []) {
        // ...
        $this->client = isset($config['client'])
            ? $config['client']
            : \Aws\default_http_handler();
    }
}
```

I patched it like following to make it work for us:

```diff
diff --git a/vendor/aws/aws-sdk-php/src/Credentials/EcsCredentialProvider.php b/vendor/aws/aws-sdk-php/src/Credentials/EcsCredentialProvider.php
index 915673512..7d116068f 100644
--- a/vendor/aws/aws-sdk-php/src/Credentials/EcsCredentialProvider.php
+++ b/vendor/aws/aws-sdk-php/src/Credentials/EcsCredentialProvider.php
@@ -32,9 +32,15 @@ class EcsCredentialProvider
     public function __construct(array $config = [])
     {
         $this->timeout = (float) getenv(self::ENV_TIMEOUT) ?: (isset($config['timeout']) ? $config['timeout'] : 1.0);
-        $this->client = isset($config['client'])
-            ? $config['client']
-            : \Aws\default_http_handler();
+        if (isset($config['client'])) {
+            $this->client = $config['client'];
+        } elseif (isset($config['http_handler'])) {
+            $this->client = $config['http_handler'];
+        } elseif (isset($config['handler'])) {
+            $this->client = $config['handler'];
+        } else {
+            $this->client = \Aws\default_http_handler();
+        }
     }
 
     /**
```

I'm not sure if the patch is the proper way to address the issue, and I don't have unit tests added, thus I'm submitting a bug report instead of a PR.

**Screenshots**

N/A

**Additional context**

Same issue could also happen on class [\Aws\Credentials\InstanceProfileProvider](https://github.com/aws/aws-sdk-php/blob/3.166.2/src/Credentials/InstanceProfileProvider.php#L62).

**Comment by ajredniwja** [comment]
Hey @dminy, thanks for opening this issue, trying to understand the issue a bit more here so you are trying to make sure whether the credential provider uses your guzzle handler or not? 

Looking at the code it seems your custom handler must be used elsewhere.

**Comment by deminy** [comment]
Ideally, the customized handler should be used by package `aws/aws-sdk-php` when using ECS credentials to call AWS APIs, just like how class `\Aws\AwsClient` does.

The bug had been verified in our backend microservices, and we had made a patch to make it work for us. I'm reporting a bug, and hoping that you guys could make a proper fix for it (although the patch I included did work in our case). Thanks

**Comment by pflueg** [comment]
Hi everyone,

i was about to report the exact same issue, but in my case it affects the class `InstanceProfileProvider`. That one and the mentioned `EcsCredentialProvider` above are not using any custom handler given by the option `http_handler`. Instead they fallback to the `GuzzleHttp\HandlerStack` due to the `\Aws\default_http_handler();` call.

```php
$this->client = isset($config['client'])
    ? $config['client']
    : \Aws\default_http_handler();
```

As a workaround it is possible to set the `http_handler` option **and** the undocumented `client` option with the same custom handler, but beware of possible sideeffects. I couldnt see any until now though.

**Comment by yenfryherrerafeliz** [comment]
Hi @deminy, @pflueg, this behavior is actually expected since http_handler is a client parameter, which means that it will just apply to the client. If you want to pass a custom handler to the ECS or InstanceProfile provider, you can either or create an instance of the provider separated or pass a parameter called "client" in the arguments you provide when instancing the client. 
Please see my examples below:
<details>
<summary>Creating a separated instance of the provider:</summary>

```php
<?php

require '../vendor/autoload.php';

use Aws\Credentials\CredentialProvider;
use Aws\S3\S3Client;

$provider = CredentialProvider::ecsCredentials([
    'client' => new CustomizedGuzlleHandler()
]);
$memoizedProvider = CredentialProvider::memoize($provider);
$client = new S3Client([
    'region' => getenv('TEST_REGION'),
    'credentials' => $memoizedProvider
]);
$client->listBuckets();
```
</details>

<details>
<summary>Providing the custom handler in the parameter called "client":</summary>

```php
<?php

require '../vendor/autoload.php';

use Aws\S3\S3Client;

$client = new S3Client([
    'region' => getenv('TEST_REGION'),
    'client' => new CustomizedGuzzleHandler()
]);
$client->listBuckets();
```
</details>

Please let me know if that helps!

Thanks!
