### ISSUE TITLE
An exception occurred while completing a multipart upload: Error executing "CompleteMultipartUpload"

### ISSUE THREAD

**Issue by pablomoreno61** [aws/aws-sdk-php#2165]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
I'm trying to upload a file to an S3 bucket, but If I try to upload a file bigger than mup_threshold, then the following exception is raised:

`An exception occurred while completing a multipart upload: Error executing "CompleteMultipartUpload" on "https://s3.amazonaws.com/bucket/file?uploadId=uploadid"; AWS HTTP error: Client error: `POST https://s3.amazonaws.com/bucket/file?uploadId=uploadid` resulted in a `400 Bad Request` response:
<Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed or did not validate against our publis (truncated...)
 MalformedXML (client): The XML you provided was not well-formed or did not validate against our published schema - <Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed or did not validate against our published schema</Message><RequestId>requestid</RequestId><HostId>hostid</HostId></Error>`

**Version of AWS SDK for PHP?**
aws/aws-sdk-php                                         3.158.21           AWS SDK for PHP - Use Amazon Web Services in your PHP project
aws/aws-sdk-php-symfony                                 2.2.2              A Symfony bundle for v3 of the AWS SDK for PHP

**Version of PHP (`php -v`)?**
PHP 7.2.31

**To Reproduce (observed behavior)**

`$s3Client->upload(
            'bucket_name',
            'file.csv',
            fopen($filepath, 'r+'),
            'private',
            ['mup_threshold' => 104857600]
        );`

Where $s3Client is defined in the config.yml from Symfony:
`aws:
  version: latest
  S3:
    version: '2006-03-01'
    endpoint: '%s3_endpoint%'
    region: '%s3_region%'
    use_path_style_endpoint: true`

**Expected behavior**
I expect the file to be correctly uploaded to S3 using multipart.

**Additional context**
I've tried using default mup_threshold and it raises the same error. Once I've increased the threshold the error is raised with bigger files, depending on the defined threshold.

**Comment by SamRemis** [comment]
Hi @pablomoreno61,
Thank you for your issue- unfortunately, I haven't been able to reproduce it yet.  I followed your steps to reproduce it, but every time, it seems to have succeeded.  Is there anything that may have been left out here?  Maybe special characters in the filename or bucket_name?  If not, could you provide us with a debug log so that we can take a look at the XML that is sent to S3?
Thank you,
-Sam

**Comment by pablomoreno61** [comment]
Hi @SamRemis!

Thanks for you answer! filename is a random string and bucketname follow a pattern like this one "prefix-bucketname", so I guess there is nothing wrong in their names. How can I get the full XML response? Because an exception is thrown and I can only get the error message/code.

**Comment by pablomoreno61** [comment]
I've zipped the content of the uploaded file and the issue disappeared.

**Comment by SamRemis** [comment]
But it still doesn't work without the file being zipped?

**Comment by pablomoreno61** [comment]
Yep, it didnt work without the zip. The file was a csv comma separated...I guess it was breaking somehow the xml format, but I cannot confirm it.

**Comment by SamRemis** [comment]
I'm wondering if it was something specifically with the values you were using- I have tried with both downloaded and generated CSV files and have been unable to replicate it.

**Comment by stephenstephensonukraine** [comment]
This error appears when the argument $source is pointing to an existing directory instead of a file.

This is not an error in the SDK library! To any one who is experiencing the same issue: check your $source argument.

```
$uploader = new MultipartUploader($s3Client, **$source**, [
    'bucket' => 'your-bucket',
    'key' => 'my-file.zip',
]);
```
