### ISSUE TITLE
Process Provider does not honor 'use_aws_shared_config_files' boolean similar to ini provider

### ISSUE THREAD

**Issue by cuppett** [aws/aws-sdk-php#2171]
It appears there is a conditional against the iniProvider here:

https://github.com/aws/aws-sdk-php/blob/5b59db8d5d3d5ce1e93b8c4de5908437cc2eb40f/src/Credentials/CredentialProvider.php#L89-L103

And it is not honored in the same way when evaluating for processes:

https://github.com/aws/aws-sdk-php/blob/5b59db8d5d3d5ce1e93b8c4de5908437cc2eb40f/src/Credentials/CredentialProvider.php#L108-L112

It is not clear why the ecsProvider is nestled between the two.

I'll file a PR to add the conditional to both stanzas. I can amend it if somebody feels the process method should be adjacent to the iniProvider method.

**Comment by SamRemis** [comment]
Hi @cuppett,
The PR looks good to me and I can merge soon- I just want to make sure your original issue with the Process Provider has been resolved, since merging it will close this issue

**Comment by cuppett** [comment]
Yes. That will resolve it. It puts all the logic which considers ~/.aws/credentials and ~/.aws/config underneath the 'use_aws_shared_config_files' boolean check.
