### ISSUE TITLE
PostObjectV4 possible bug

### ISSUE THREAD

**Issue by Keitio** [aws/aws-sdk-php#2180]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
Basic `\Aws\S3\PostObjectV4` use returns a 400 error when attempting to cretate a presigned POST

**Version of AWS SDK for PHP?**
v3.160.0

**Version of PHP (`php -v`)?**
php 7.4.13

**To Reproduce (observed behavior)**
[Minimal code - without secret keys](https://gist.github.com/Keitio/beb45f21dda7e4628ad60b41d5070dbf)

**Expected behavior**

**Screenshots**

**Additional context**
I'm in talks with AWS support, and they recommended that I create this issue

If this is not a bug, I think a minimal working exemple of PostObjectV4 use should be available, as I wasted quite some time trying to debug this already

**Comment by SamRemis** [comment]
Hi @Keitio,
Thank you for bringing this to our attention.  I could use a bit more context to help me figure out what is going on here.  Do you have any more data on the error returned?  When I use the same code, I get the following error: 
```
<Code>MaxPostPreDataLengthExceeded</Code>
<Message>
Your POST request fields preceeding the upload file was too large.
</Message>
```

Is that the same issue you're seeing, or is it a different 400 error?

**Comment by Keitio** [comment]
Thanks for the quick reply
I'm sorry I totally forgot to include the returned error, here it is, it's been this exact return code for a few weeks now (it had been a 500 for a few days before)
```php
<Error>
<Code>InvalidArgument</Code>
<Message>Malformed Unicode code sequence in the field.</Message>
<ArgumentName>formField</ArgumentName>
<RequestId>...</RequestId>
<HostId>...</HostId>
</Error>
```

**Comment by SamRemis** [comment]
@Keitio, are you using unicode for the file names/metadata by any chance?  I got it to break by using some foreign characters in the file name, but so far have been unable to reproduce your exact issue.
