### ISSUE TITLE
The S3 StreamWrapper fails to correctly show a directory named '/' in readdir()

### ISSUE THREAD

**Issue by nedt** [aws/aws-sdk-php#2182]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
The S3 StreamWrapper fails to correctly show a directory named '/', instead returning an empty string in `readdir()`.

If the S3 storage was used to upload a file with a key/pathname `/some/path/file.txt` instead of `some/path/file.txt` there would then in the mapping to a file tree structure a directory in the root of the bucket named '/'.

Reading the root of this bucket would return an empty string in `readdir()` and break `DirectoryIterator`.

**Version of AWS SDK for PHP?**
3.171.14

**Version of PHP (`php -v`)?**
7.3.24

**To Reproduce (observed behavior)**
```php
<?php
// setup client and stream wrapper
$wrapperPrefix = 's3://bucket/';
$filename = '/some/path/file.txt';
file_put_contents($wrapperPrefix . $filename, 'test');
$dh = opendir($wrapperPrefix);
echo "---\n";
while (($entry = readdir($dh)) !== false) {
  echo "$entry\n";
}
echo "---\n";
```

**Expected behavior**
Example code should output:
```
---
/
---
```

instead of:
```
---

---
```

**Additional context**
The reason is `StreamWrapper::dir_readdir()` removes trailing slashes in `Prefix` with `rtrim()`, even if `Prefix` is nothing but slash(es). 

Of course the best would be do not have a directory called '/', but it's easy to create it by accident, because of not normalized pathnames, like in the example code.

**Comment by ajredniwja** [comment]
Hey @nedt, thanks for opening this issue, I am not sure if I understand your question correctly, [the document](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-key-guidelines) mentions that "There is no hierarchy of subbuckets or subfolders. However, you can infer logical hierarchy using key name prefixes and delimiters as the Amazon S3 console does."

Moreover I was not able to create a folder which contains `/` in the name (mentioned in above document as well), which means it would make sense fro what `rtrim()` is doing. 

Please let us know if you think differently or if you still have questions.

**Comment by nedt** [comment]
The logic to infer a hierarchy is done in the StorageWrapper already by implementing `opendir()` & `readdir()` methods. I do know it's done by search for a Prefix and grouping with a / Delim. Furthermore the StreamWrapper creates empty objects with a / suffix to simulate directories. That's all clear.

Maybe one reason why it can't always be replicated is me having here a StorageGRID from Netapp with S3. If not all servers would return a '/' Prefix in the bucket root it wouldn't break anything, but fix this use case.

Actually it's necessary do have something to differentiate in the `readdir()` if there are two different objects, one with the key `/some/path/file.txt` and the other with `some/path/file.txt`. And the response needs to be something that can be used  to `opendir()` to get further down the hierarchy.

The biggest issues isn't even using `readdir()` on the StreamWrapper, because the consumer can assume an empty string should be a / to recurse. But `DirectoryIterator` stops working if there is a directory with an empty string. Returning '/' instead fixes that and `RecursiveDirectoryIterator` then correctly traverses both objects mentioned above (of course it's not very efficient, but a PHP stream should be somewhat transparent).

I'll happily provide a PR with tests. What made it work for me is returning the original Prefix if the rtrim() results in an empty string.

**Comment by ajredniwja** [comment]
Hey @nedt apologies for late reply here, we would appreciate a PR if you want to work on it, otherwise the team can take it up according to the priority.
