### ISSUE TITLE
On signin it give this error User pool client {id} does not exist

### ISSUE THREAD

**Issue by faizanktk** [aws/aws-sdk-php#2183]
Fatal error: Uncaught exception 'Aws\CognitoIdentityProvider\Exception\CognitoIdentityProviderException' with message 'Error executing "AdminInitiateAuth" on "https://cognito-idp.us-west-2.amazonaws.com"; AWS HTTP error: Client error: `POST https://cognito-idp.us-west-2.amazonaws.com` resulted in a `400 Bad Request` response: {"__type":"ResourceNotFoundException","message":"User pool client {id} does not exist."}

https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-authentication-flow.html#amazon-cognito-user-pools-admin-authentication-flow

**Comment by ajredniwja** [comment]
Hey @faizanktk, thanks for opening the issue, looking at the issue it seems to be a client side issue, you can use console to make sure you have the resources that you are trying to access. 

If it is still a problem to help you further, I would need more information so please fill out the issue template [found here](https://github.com/aws/aws-sdk-php/issues/new?assignees=&labels=needs-triage%2C+bug&template=bug-report.md&title=)

**Comment by faizanktk** [comment]
@ajredniwja thanks for reply. It client side issue. I remove credential and use profile => default
Thanks
