### ISSUE TITLE
PresignedURL AWSIGNV4

### ISSUE THREAD

**Issue by healthlynked** [aws/aws-sdk-php#2185]
**Is your feature request related to a problem? Please describe.**
There is no method to create a PresignedURL for sending message to connections in AWS API Gateway

**Describe the solution you'd like**
A method in the AWSMaintenaceAPI Class to get presigned URL. A similar method exists in Python and GO SDK.

**Comment by ajredniwja** [comment]
Hey @healthlynked, thanks for opening this, I am not sure if I understand the question correctly, can you link to pages from Python or Go SDK for the function?

**Comment by nuttyroll** [comment]
Hi, Please refer to this url

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/apigatewaymanagementapi.html#ApiGatewayManagementApi.Client.generate_presigned_url

**Comment by stobrien89** [comment]
Hi @nuttyroll  and @healthlynked,

Apologies for the delay!  Boto3/Botocore recently fixed an issue with their docs where documentation was generated for `generate_presigned_url` on services where presigned urls are not officially supported.  There was also a `generate_presigned_url` method for each boto3 client, but I'm not sure if they've fixed that issue yet or not.

The only services that officially support presigned urls at the moment are S3 and Cloudfront. It is technically possible to hand-roll your own presigned URLs for many AWS services, but this isn't a feature request we'd entertain until API Gateway officially supports them.
