### ISSUE TITLE
Does it support SES V4?

### ISSUE THREAD

**Issue by zachary** [aws/aws-sdk-php#2192]
Does the latest version support SES V4?
if yes, how to use it?
Thanks

**Comment by ajredniwja** [comment]
Hey @zachary thanks for opening this issue, not sure if I understand the question correctly.

How to use SES: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-using-sdk-php.html

And the SDK uses Signature version 4 by default for all the requests.

To specify it manually you can use the code mentioned here. 

https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#signature-version
