### ISSUE TITLE
Issue integrating with chime-sdk-js

### ISSUE THREAD

**Issue by gsudhanshu** [aws/aws-sdk-php#2197]
I am using laravel server application to createMeeting using amazon chime client and createAttendee

I am passing these responses to meetingSessionConfiguration using aws-chime-sdk-js and getting the following error:

https://github.com/aws/amazon-chime-sdk-js/issues/1052

No error when using aws-java-sdk instead of aws-php-sdk

**Comment by SamRemis** [comment]
Hi @gsudhanshu, 
It looks to me like you managed to fix your issue, but I will contact the team who owns the linked repo to determine how our SDK differs from the java SDK in its behavior.  If a fix is viable without making a breaking change, we will publish it ASAP.  I will leave this issue open for now while I investigate

**Comment by gsudhanshu** [comment]
Thanks, That would be great

**Comment by gsudhanshu** [comment]
Any update on this issue?

**Comment by ajredniwja** [comment]
Issue fixed in original repo, closing this issue now. Please reach out if you have any other questions. 

https://github.com/aws/amazon-chime-sdk-js/issues/1052
