### ISSUE TITLE
S3 getObjectAsync not really async

### ISSUE THREAD

**Issue by ktecho** [aws/aws-sdk-php#2198]
- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

I'm using AWS PHP SDK to try and download a small quantity of files from S3. I need them to download at once, or the user experience will be bad. I'm currently trying with this code:

```
$promises = [];

foreach($files as $file) {
      $promises[] =  S3::getClient($ci)->getObjectAsync([
           'Bucket' => $bucketName,
           'Key'    => $filePath
      ]);
      
      Log::debug("Request sent");
}

$results = Promise\all($promises)->wait();
```

It gives the appearance that all the requests are made at once because I get all the "Request sent" messages at once, but when I'm iterating over `$results`, I think it's lazy-doing the requests sequentially, so I'm getting times of 11 seconds instead or 1 or 2 seconds.

Am I doing something wrong? Can this be improved so all the requests are made at once?

**Comment by SamRemis** [comment]
@ktecho Unfortunately, the PHP SDK doesn't currently support true async calls. We have had customers integrate with async HTTP handlers with some success, but you have to set retries to 1 so that it doesn't have the exponential jitter and cause delays.

Since this is a commonly requested feature, we are looking at integrating it into the next version of the SDK.

**Comment by ktecho** [comment]
@SamRemis can you recommend me an alternative? I've seen AsyncAws, but I don't know if it has the same problems...

**Comment by ktecho** [comment]
Just in case someone needs to do file downloads in parallel, I've made it work using AsyncAws:

https://async-aws.com/clients/s3.html

https://async-aws.com/features/async.html#batch-requests

**Comment by ajredniwja** [comment]
@ktecho Seems like you have found the solution. I will close this issue now.

**Comment by LosD** [comment]
@ajredniwja It's a workaround., not a solution. aws-sdk still doesn't work properly.
