### ISSUE TITLE
What's the oldest safe version of the AWS SDK for the upcoming Mar 23 CA migration for S3/Cloudfront?

### ISSUE THREAD

**Issue by joelclermont** [aws/aws-sdk-php#2200]
Confirm by changing [ ] to [x] below:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
No specific version - this question is actually about which versions are affected.

**Version of PHP (`php -v`)?**
Not PHP version specific.

**Describe the question**
With the upcoming Mar 23 Amazon CA migration for S3 and Cloudfront, I'm trying to determine what is the oldest safe version of the AWS PHP SDK that will work. 

From my research, every release of v3 includes a bundled certificate and uses it by default, so I think all v3 releases should be safe, but I'd like confirmation. Is there any 3.x release that will not work post-Mar 23 CA migration?

For v1 and v2, the default behavior of v1 and v2 was to use the system certificates, so for those versions you'd have to either switch configuration for the SDK to use bundled, or confirm that the system root store is up to date. Is that correct? And can you confirm the oldest versions of v1 and v2 that came bundled with certificates that will continue to work after Mar 23?

**Comment by SamRemis** [comment]
@joelclermont, backwards compatibility is one of our top priorities, and I haven't been notified of any affects that the migration will have on any of the SDKs.  You should still be safe with any version you were using before the migration going forward.  

I have followed the instructions [here](https://aws.amazon.com/blogs/storage/reminder-amazon-s3-and-amazon-cloudfront-migrating-service-certificates-to-amazon-trust-services-starting-march-23-2021/) for testing the most recent client, and there were no issues.

To ensure that your code will still work, you can follow the same instructions.  I dont think you will, but if you do happen to experience any issues after the migration, feel free to make another issue here and we will fix it ASAP.
