### ISSUE TITLE
Access Key in constructor not being used as the X-Amz-Credential (SignatureDoesNotMatch)

### ISSUE THREAD

**Issue by louiswol94** [aws/aws-sdk-php#2201]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
The AWS access key that I am using in the constructor when creating a new Aws\WorkDocs\WorkDocsClient(), is not being used in subsequent requests.

```php
$client = new Aws\WorkDocs\WorkDocsClient([
    //'profile' => 'default',
    'version' => '2016-05-01',
    'region' => 'eu-west-1',
    'credentials' => array(
        'key'=>'AKIAWXUQVOI5TU7.....',
        'secret'=>'yb3sCyfqlpLjK3HtSIlUTpRaTvTGnN..........,
    )
]);
```

But when trying to upload a document to WorkDocs the upload url is as follow:
```
..........X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20210304T091550Z&X-Amz-SignedHeaders=content-type;host;x-amz-server-side-encryption&X-Amz-Expires=900&X-Amz-Credential=AKIAJVOSVFCTFL24..../20210304/eu-west-1/s3/aws4_request&X-Amz-Signature=9097d23ebe834fc08ad20e423246bc6b18a3c9fb056acf08942cd9c02c9aade5
```
The key being used in the parameter "X-Amz-Credential" is not the key in the WorkDocsClient constructor. I do not know this key at all.

**Version of AWS SDK for PHP?**
Example: 3.173.20
* get SDK version by printing the output of `Aws\Sdk::VERSION` in your code 
* if the SDK was installed via composer you can see the version installed with `composer show -i` 

**Version of PHP (`php -v`)?**
7.4.2

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)
```php
<?php
//ini_set('display_errors', 1); ini_set('display_startup_errors', 1); error_reporting(E_ALL);
//date_default_timezone_set('Europe/Dublin');
require 'aws/aws-autoloader.php';

use Aws\Exception\AwsException;
use Aws\WorkDocs\WorkDocsClient;
use GuzzleHttp\Client as httpClient;
use GuzzleHttp\Exception\ClientException;

echo Aws\Sdk::VERSION."<br><br>";

$client = new Aws\WorkDocs\WorkDocsClient([
    //'profile' => 'default',
    'version' => '2016-05-01',
    'region' => 'eu-west-1',
    'credentials' => array(
        'key'=>'AKIAWXUQVOI5TU7S....',
        'secret'=>'yb3sCyfqlpLjK3HtSIlUTpRaTvTGnNI.......',
    )
]);

$fileToUpload = 'test.txt';

try {

    print("Create Document:<br><br>");
    $result = $client->initiateDocumentVersionUpload([
        'ParentFolderId' => 'fa8aa336aee33129d630b0c3434fd5025e81d2539c51c845cfece.....',
        'Name' => 'test.txt',
    ]);
    var_dump($result);
    $documentID = $result['Metadata']['Id'];
    $documentVersionID = $result['Metadata']['LatestVersionMetadata']['Id'];
    $uploadurl = $result['UploadMetadata']['UploadUrl'];

    echo "<br><br>Upload URL: ".urldecode($uploadurl)."<br><br>";

} catch (AwsException $e) {
    // output error message if fails
    echo $e->getMessage() . "\n";
}
try {
    print("<br><br>Upload Document<br><br>");
    $body = fopen($fileToUpload, 'r');

    $guzzle = new httpClient();
    $upload = $guzzle->put($uploadurl, [
        'body' => $body,
    ]);

    var_dump($upload);

} catch (ClientException $e) {
    // output error message if fails
    echo $e->getMessage() . "\n";
}
try {
    print("<br><br>Update Document Version<br><br>");
    $updateResult = $client->updateDocumentVersion([
        //'AuthenticationToken' => $authToken,
        'DocumentId' => $documentID,
        'VersionId' => $documentVersionID,
        'VersionStatus' => 'ACTIVE',
    ]);

    var_dump($updateResult);
} catch (AwsException $e) {
    // output error message if fails
    echo $e->getMessage() . "\n";
}
```

**Expected behavior**
For the key used in the WorkDocsClient constructor to be the same key used in the "X-Amz-Credential" parameter.

**Screenshots**

**Additional context**
Any additional information relevant to the issue. Examples include any framework you may be using (e.g. Laravel, Wordpress) in conjunction with the AWS SDK for PHP, or PHP/environment config settings if the issue is related to memory or performance.

**Comment by louiswol94** [comment]
Sample: https://geekabyte-testing.co.za/awstests/index.php

**Comment by ajredniwja** [comment]
Hi @louiswol94, thanks for opening this issue,Unfortunately,  I was not able to reproduce the issue. I used the code with something like: 

```php
$credentials = new Aws\Credentials\Credentials('access_key', 'secret_key');

$s3 = new Aws\WorkDocs\WorkDocsClient([
    'version'     => 'latest',
    'region'      => 'us-east-2',
    'credentials' => $credentials,
]);
```

Can you try if that works for you?
