### ISSUE TITLE
how to add custom params in s3 presigned url

### ISSUE THREAD

**Issue by xuetaofeng** [aws/aws-sdk-php#2203]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
"aws/aws-sdk-php": "^3.173"

**Version of PHP (`php -v`)?**
PHP 7.4.5

**Describe the question**
By aws dotnet sdk, I could add custom params in s3 presigned url by following sample code:
```
            // Create a CopyObject request
            GetPreSignedUrlRequest request = new GetPreSignedUrlRequest
            ...
            request.Parameters.Add("userEmail", "hello@c.c"); // here I can add custom parameter "userEmail"

            // Get path for request
            return client.GetPreSignedURL(request);
```
And I saw this feature is also supported in aws go sdk (https://github.com/aws/aws-sdk-go/issues/3380)
But I did not find a method to do this in php:
```
$cmd = $s3Client->getCommand('GetObject', [
    'Bucket' => 'my-bucket',
    'Key' => 'testKey'
]);

$request = $s3Client->createPresignedRequest($cmd, '+20 minutes'); // how to add a custom parameter ?
```

Could anyone help me on this?

**Comment by ajredniwja** [comment]
Hi @xuetaofeng thanks for opening this issue, you can use the middleware to add custom params, an example on how to use the middleware can be found [here](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_handlers-and-middleware.html).

For this particular case:
```php
$client = new S3Client([
    'region' => 'us-east-2',
    'version' => 'latest',
]);
$cmd = $client->getCommand('GetObject', [
    'Key' => '000',
    'Bucket' => 'test-bucket',
]);
$cmd->getHandlerList()->appendBuild(
    Middleware::mapRequest(function (RequestInterface $request) {
        // Return a new request with the added header
        return $request->withUri(
            $request->getUri()->withQuery(
                $request->getUri()->getQuery() . "key=val"
            )
        );
    }),
    'add-custom-param'
);
$request = $client->createPresignedRequest($cmd, '+20 minutes');
$presignedUrl = (string)$request->getUri();
echo $presignedUrl;
```

I'd close this issue now, please reach out if you have any other questions.
