### ISSUE TITLE
sdk doesn't use service account

### ISSUE THREAD

**Issue by aradhell** [aws/aws-sdk-php#2204]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
I don't provide credentials to client and expecting it to use service account but it tries to use nodeInstanceRole instead of service account.

**Version of AWS SDK for PHP?**
3.173.25

**Version of PHP (`php -v`)?**
7.4.3

**To Reproduce (observed behavior)**
```php
$firehose = new FirehoseClient([
        'version' => 'latest',
        'region' => env('AWS_REGION'),
    ]);
```

```
prod-nodegroup-m-NodeInstanceRole-xxx/i-xxx is not authorized to perform: firehose:PutRecord on resource
```

describe pod
```
AWS_ROLE_ARN: arn:aws:iam::XXXX:role/eksctl-c-prod-addon-iamserviceaccoun-Role1-XXXX
AWS_WEB_IDENTITY_TOKEN_FILE: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

**Expected behavior**
To use service account.

**Comment by ajredniwja** [comment]
Hey @aradhell thanks for opening this issue, what method are you using to provide the credentials? 

[Here](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials.html) are a few ways to how to provide credential for whatever method you are using, can you make sure you are following the steps given for your preferred method?

**Comment by aradhell** [comment]
Hi @ajredniwja , I found out that it was a k8s issue. If you dont provide credentials it is using service account from pod as expected. Thanks!
