### ISSUE TITLE
StreamWrapper does not support writing files larger than 5GB.

### ISSUE THREAD

**Issue by cmlara** [aws/aws-sdk-php#2207]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
StreamWrapper can not upload files larger than 5GB due to use of putObject
```
<Error><Code>EntityTooLarge</Code><Message>Your proposed upload exceeds the maximum allowed size</Message><ProposedSize>6000000008</ProposedSize><MaxSizeAllowed>5368709120</MaxSizeAllowed>
```

I am aware of no documentation or published limitation that specifically lists 5gb as a limit for the StreamWrapper.to handle (though I will admit the StreamWrappers need to create a duplicate copy of a file in the buffer could get unwieldy with really large files) 

**Version of AWS SDK for PHP?**
Example: v3.174.3

**Version of PHP (`php -v`)?**
7.2.19-0ubuntu0.18.04.2

**To Reproduce (observed behavior)**
```
<?php
ini_set('display_errors', 1);
error_reporting(E_ALL);

require './vendor/autoload.php';

$credentials = new Aws\Credentials\Credentials('access_key', 'secret_key');

$s3 = new Aws\S3\S3Client([
    'version'     => 'latest',
    'region'      => 'us-east-2',
    'credentials' => $credentials,
]);

// Register the stream wrapper from an S3Client object
$s3->registerStreamWrapper();

stream_context_set_default([
        's3' => [
                'seekable' => true
        ]
]);

$source = '/tmp/largefile.zip';
$f = fopen($source, 'wb');
fseek($f, 6 * 1000 * 1000 * 1000, SEEK_SET); // 4GB
fwrite($f, 'after GB');
fclose($f);

$result = copy($source, 's3://bucket/largefile.zip');
var_dump($result);
unlink($source);
```

**Expected behavior**
The StreamWrapper should be able to upload files using multipart uploads.

**Additional context**
#763 appears to be relevant. That issue resolved fact that rename() used copyObject which had a single part limit, while this issue looks related to the single part limit of putObject() in StreamWrapper::stream_flush()

**Comment by ajredniwja** [comment]
Hi @cmlara thanks for opening this issue, the issue seems to be a duplicate of https://github.com/aws/aws-sdk-php/issues/1717, the https://github.com/aws/aws-sdk-php/issues/1717#issuecomment-457764901 mentions the explanation about the same. I see you also have a comment there, do you still have questions?

**Comment by cmlara** [comment]
Hello @ajredniwja  #1717 was an issue with 4gb (a full 1gb below the 5gb discussed here) that was never determined an actual cause. My testing for that issue implies that it could possibly have been an Out of Disk Space issue but I can't guarantee that was the actual root cause of that support ticket.  

The issue in this ticket is confirmed to NOT be a disk space issue and has been tracked to a line of AWS code.  The issue is that StreamWrapper::stream_flush() does not use multipart copy operations, so it is stuck by the 5gb limit of putObject() which is (as far as I can tell) not a documented intended limitation of the StreamWrapper.

in src/S3/StreamWrapper.php note the use of putObject()
```
        $this->clearCacheKey("{$this->protocol}://{$params['Bucket']}/{$params['Key']}");
        return $this->boolCall(function () use ($params) {
            return (bool) $this->getClient()->putObject($params);
        });
``` 

#763 seems to imply that multipart (>5gb objects) should be supported by the StreamWrapper so the reliance on only putObject() would be out of place.

**Comment by ajredniwja** [comment]
@cmlara thanks for the detailed explanation there. I would say this is a limitation of the StreamWrapper which is not documented and can take this issue as a documentation issue.

**Comment by cmlara** [comment]
I'm passing the info along on my side as a documentation error in the SDK.

Also a note I believe this limit will also impact stream_open() in append mode calls for files over 5gb because  openAppendStream() downloads the body, sets the cursor to the end of the file, and than returns TRUE but when the attempt to write it is done it would fail due to stream_flush() so this may be another place for users to be aware of the limitation that they can' trust append mode to know the file is below 5gb  Its relativity minor but worth noting, maybe a content-size check before downloading the file would help the issue (no point downloading the entire file if we won't be allowed to append to it due to size)
