### ISSUE TITLE
Step to send a POST_ORDER_ACKNOWLEDGEMENT_DATA feed

### ISSUE THREAD

**Issue by lionalex** [aws/aws-sdk-php#2208]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
Example: v3.133.6
* get SDK version by printing the output of `Aws\Sdk::VERSION` in your code 
* if the SDK was installed via composer you can see the version installed with `composer show -i` 

3.171.21

**Version of PHP (`php -v`)?**

7.1.32

**Describe the question**
How can I send a FEED type POST_ORDER_ACKNOWLEDGEMENT_DATA?
In API documentation is explain that I must upload a file encrypted...how can I do that with sdk php?

Thanks

**Comment by ajredniwja** [comment]
Hey @lionalex, thanks for opening this issue, I am a little confused about the ask here, can you link the API documentation that you are referring to?

**Comment by lionalex** [comment]
Hi, thanks for answer.
I would like to update some order's data. So I must send a FEED with file encrypt. The documentation that i read is https://github.com/amzn/selling-partner-api-docs/blob/main/guides/use-case-guides/feeds-api-use-case-guide-2020-09-04.md.
With old system (MWS amazon documentation) I sent an xml as that:

```
<?xml version="1.0" encoding="UTF-8"?>
<AmazonEnvelope xsi:noNamespaceSchemaLocation="amzn-envelope.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Header>
        <DocumentVersion>1.01</DocumentVersion>
        <MerchantIdentifier>APJ6JRA9NG5V4</MerchantIdentifier>
    </Header>
    <MessageType>OrderAcknowledgement</MessageType>
    <Message>
        <MessageID>1</MessageID>
        <OrderAcknowledgement>
            <AmazonOrderID>171-XXXXXXX-XXXXXXX</AmazonOrderID>
            <MerchantOrderID>AA0001</MerchantOrderID>
            <StatusCode>Success</StatusCode>
        </OrderAcknowledgement>
    </Message>
</AmazonEnvelope>
```
to update MerchatOrderId of an amazon order. 
How can do that with new selling amazon api in php? And what are the step to follow for this request?

Thanks

**Comment by ajredniwja** [comment]
@lionalex can you refer to the comment here? https://github.com/amzn/selling-partner-api-docs/issues/97#issuecomment-728033073
