### ISSUE TITLE
How To Set the Domain/Path For S3 Buckets, Similar To s3ForcePathStyle In Other Language SDKs? 

### ISSUE THREAD

**Issue by nickpoulos** [aws/aws-sdk-php#2210]
Confirm by changing [ ] to [x] below:

- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**: v3.161.1
**Version of PHP (`php -v`)?** 7.4

**Describe the question**

I am trying to control the domain/path of my bucket, similar to the issues described here: 

https://stackoverflow.com/questions/57346922/use-path-style-amazon-aws-sdk-go/57347250#57347250

https://stackoverflow.com/questions/64969756/how-to-prevent-aws-sdk-from-setting-bucket-as-subdomain-for-an-ip-address-as-end/64982126#64982126

https://stackoverflow.com/questions/20305877/how-to-configure-aws-s3-sdk-for-node-js-to-use-fakes3/27796925#27796925

How can I set the `s3ForcePathStyle` option for the PHP SDK? I could not find any relevant documentation or examples for this use case. Sorry if i missed it!

**Comment by SamRemis** [comment]
@nickpoulos, I'm not positive because I do not know the ins and outs of the options of the java SDK, but I think you're looking for what use_path_style_endpoint.  If you'd like it on an individual command instead, it's @use_path_style_endpoint.  Can you confirm that this is what you were looking for?
