### ISSUE TITLE
v3.175.0 Breaks S3 operations when using a custom endpoint

### ISSUE THREAD

**Issue by mattgrayisok** [aws/aws-sdk-php#2211]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
The URI for S3 commands is lost when using a custom endpoint resulting in arbitrary errors.

This seems to have occurred due to the addition of:

https://github.com/aws/aws-sdk-php/blob/335ed5a956f096bc56842ffe8b0461ef96ff3739/src/S3/S3Client.php#L369-L371

Which is now causing custom endpoint requests to return true to this conditional:

https://github.com/aws/aws-sdk-php/blob/335ed5a956f096bc56842ffe8b0461ef96ff3739/src/S3/S3EndpointMiddleware.php#L92-L93

Where it wasn't previously. The `applyEndpoint()` function contains this line:

https://github.com/aws/aws-sdk-php/blob/335ed5a956f096bc56842ffe8b0461ef96ff3739/src/S3/S3EndpointMiddleware.php#L324

Which creates a brand new URI with an empty path. Erasing the URI included in the original request, thus resulting in any operations performed on a non-root URI failing.

I have fixed this temporarily by changing the line to:

`$uri = $request->getUri();`

So that it will inherit the existing URI from the request, rather than completely erase it.

**Version of AWS SDK for PHP?**
v3.175.0

**Version of PHP (`php -v`)?**
7.4

**To Reproduce (observed behavior)**
Attempt to perform an S3 PUT whilst using a custom endpoint.

I came across this error when using the SDK against the BackBlaze S3 compatible API (s3.eu-central-003.backblazeb2.com)

**Expected behavior**
Be able to use S3 commands with a custom endpoint set

**Comment by cbl4** [comment]
same problem with
```
        $sharedConfig = [
            'credentials' => [
                'key'      => KEY,
                'secret'   => SECRET,
            ],
            'region'   => 'ru-central1',
            'endpoint' => 'https://storage.yandexcloud.net',
            'use_path_style_endpoint' => false, // or true
            'debug'   => true,
            'version'  => 'latest',
        ];
        $sdk = new \Aws\Sdk($sharedConfig);
        $s3Client = $sdk->createS3();

        $command = $s3Client->getCommand('PutObject', [
            'Bucket' => '***[mybucketname]***',
            'Key'    => 'test.txt',
            'Body'   => 'setsetsdfs'
        ]);
        $result = $s3Client->execute($command);
```

i dont fully understand what \Aws\S3\S3EndpointMiddleware::applyEndpoint() do, but i change https://github.com/aws/aws-sdk-php/blob/master/src/S3/S3EndpointMiddleware.php#L318
```
        $host = ($this->pathStyleByDefault) ?
            $this->endpoint :
            $this->getBucketStyleHost(
                $command,
                $this->endpoint
            );
        $uri = new Uri($host);
        $scheme = $uri->getScheme();
        if(empty($scheme)){
            $request = $request->withUri(
                $uri->withHost($host)
            );
        } else {
            $request = $request->withUri($uri);
        }

        return $request;
```
to

 ```
        $uriEndpoint = new Uri($this->endpoint);
        if ($this->pathStyleByDefault) {
            return $request;
        } else {
            $uri = $request->getUri();
            $request = $request->withUri(
                $uri->withHost($this->getBucketStyleHost(
                    $command,
                    $uriEndpoint->getHost()
                ))
                    ->withPath($this->getBucketlessPath(
                        $uri->getPath(),
                        $command
                    ))
            );
            return $request;
        }
```

**Comment by cbl4** [comment]
a think this fix can fix [issue with bucket name protocol](https://github.com/aws/aws-sdk-php/issues/2209)

**Comment by SamRemis** [comment]
Hi @mattgrayisok,

Thanks for bringing this to our attention as well as the detailed analysis which helped push the fix out faster.  I just pushed #2214, which should fix the issue.  Please confirm when you are able that it is working for you again

**Comment by mstaack** [comment]
thanks! this works for me

**Comment by mattgrayisok** [comment]
@SamRemis Tested against master and all looks ok now. I'll also retest when the next release is cut.

Thanks for the quick fix :sparkles:
