### ISSUE TITLE
Guzzle/Psr7 function uri_for backport issue in aws-sdk-php

### ISSUE THREAD

**Issue by hkmekala** [aws/aws-sdk-php#2213]
**PHP version**: 7.3.14.-1

**Description**
Updating to Guzzle/Psr7 to 1.8 causes the aws-sdk-php to call an undefined function. The function uri_for was removed in Latest version of Guzzle.

**How to reproduce**
Update the Guzzle/Psr7 to ^1.8

**Possible Solution**
In Guzzle's changelog, it was mentioned that we need to use Util class for the uri_for method which was used in the RestSerializer constructor for the endpoint variable.

**Additional context**
https://github.com/aws/aws-sdk-php/blob/31baa9e0c4330f01eb74b8a7ef086e9d34f8391e/src/Api/Serializer/RestSerializer.php#L35

**Comment by VincentLanglet** [comment]
it's used two times https://github.com/aws/aws-sdk-php/search?q=uri_for
Can you provide a PR @hkmekala ?

**Comment by hkmekala** [comment]
@VincentLanglet, There is a table to change all the functions to a class of static functions. 
I think all the functions that are about to be depreciated should be changed using the table from the link to support for future versions of Guzzle\Psr7

https://github.com/guzzle/psr7/blob/ff1b0eae41c6bc0b03ef657f29d8a9eea7ee75eb/README.md#upgrading-from-function-api

**Comment by hkmekala** [comment]
@VincentLanglet I have changed all the files using the table provided by Guzzle\Psr7. please review my PR if possible.

**Comment by ajredniwja** [comment]
Closing this issue since the PR was merged.
