### ISSUE TITLE
Returns empty instead of ARN

### ISSUE THREAD

**Issue by kemalatila** [aws/aws-sdk-php#2223]
Confirm by changing [ ] to [x] below:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
3.172.3 

**Version of PHP (`php -v`)?**
PHP 7.4.11 

**Describe the question**

I use ElasticLoadBalancingV2Client class with createRule and  addListenerCertificates methods but the methods returns empty.
I want to access ARN of created or added items. 

Any idea?

**Comment by ajredniwja** [comment]
Hi @kemalatila, thanks for opening the issue, so lookin at the docs https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-elasticloadbalancingv2-2015-12-01.html#createrule, you can check whats the result like, you can get `ruleArn` out of it when you create a rule or even `TargetGroupArn`. I am not sure what you mean by method returns empty, I can look at the code to check if I can get to know what exactly you are looking for.

**Comment by kemalatila** [comment]
Solved. I just skipped using ->toArray() method.
