### ISSUE TITLE
s3->putObjectAsync with CurlMultiHandler is not working without curl->execute()

### ISSUE THREAD

**Issue by SVynnytska** [aws/aws-sdk-php#2230]
Confirm by changing [ ] to [x] below:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
**Version of AWS SDK for PHP?**
```composer show -i 
aws/aws-sdk-php                    3.154.1            AWS SDK for PHP - Use Amazon Web Services in your PHP project
guzzlehttp/guzzle                  6.5.5              Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1             Guzzle promises library
guzzlehttp/psr7                    1.6.1              PSR-7 message implementation that also provides common utility methods
```
**Version of PHP (`php -v`)?**
`PHP 7.3.24`

**Describe the question**

I tried to upload files asynchronously using:
```    
 $curl = new CurlMultiHandler();
 $httpHandler = HandlerStack::create($curl);       
 $s3 = new S3Client([
            'version' => 'latest',
            'region' => 'us-west-2',
            'http_handler' => $httpHandler
        ]);
$promise = $s3->putObjectAsync([
            'Bucket' => $s3Bucket,
            'Key' => $sDestinationPath,
            'Body' => $content,
            'ACL' => $aclType,
            'ContentType' => $contentType);
```   
but it'ss doing nothing. No upload. no error. nothing.
After spending a week on this issue I figured out myself that to make it upload ```curl->execute();``` should be added.
But it's not written anywhere. Fix your SDK or at least update your documentation

**Comment by ajredniwja** [comment]
Hi there, curl-execute(); surely is a workaround however in this case the $promise will will either with successful result or rejected with an exception. 

You would need to add another step to your code, you can follow this guide [here](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_promises.html#promises-in-the-sdk)

Please reach out if you have any other questions.
