### ISSUE TITLE
Infinite loop in GetLogEvents paginator

### ISSUE THREAD

**Issue by pagelypete** [aws/aws-sdk-php#2237]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
When using the `GetLogEvents` paginator in the `CloudWatchLogsClient`, the end of the log stream is not properly detected and there is an infinite loop requesting the last page of the log stream.

It seems like a similar bug existed in the Java client - https://github.com/aws/aws-sdk-java-v2/issues/1045

**Version of AWS SDK for PHP?**
v3.178.3

**Version of PHP (`php -v`)?**
7.4.9

**To Reproduce (observed behavior)**

```php
$cwClient = new CloudWatchLogsClient();
$logPaginator = $cwClient->getPaginator("GetLogEvents", [
    "logGroupName" => "/test/group",
    "logStreamName" => "test/stream",
    "startFromHead" => true
]);

foreach ($logPaginator as $logPage) { // Infinite loop here
    foreach ($logPage["events"] ?? [] as $logEvent) {
        echo $logEvent["message"];
    }
}
```

**Expected behavior**
Loop ends when no more events are present.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by stobrien89** [comment]
Hi @pagelypete,

Apologies for the delay here. We've merged a fix for this— it will be available in tomorrow's release.  Let us know if you're still having issues!
