### ISSUE TITLE
Could you make the "data" folder optional?

### ISSUE THREAD

**Issue by martinkrcho** [aws/aws-sdk-php#2240]
**Is your feature request related to a problem? Please describe.**
I am trying to make the size of my software product as small as possible. The AWS SDK contains a `data` folder that is 2 MB in size when zipped up. I believe this could be avoided.

**Describe the solution you'd like**
I would like the AWS SDK work even without the `data` folder. Ideally the files would be available online and the SDK would  download them when needed. Perhaps a new configuration option to specify a a path to a writable folder on the server would be handy. It would default to the current location within the `src` folder.

**Describe alternatives you've considered**
I considered using the SDK without the data folder, but that doesn't work. I also examined the code that included files from this folder. There was not much in terms to extending it.

**Additional context**
No additional context.

**Comment by stobrien89** [comment]
Hi @martinkrcho,

Apologies for the delayed response here. This is not something we're able to prioritize for this major version of the SDK, but we have committed to modularization in the next major version, which should solve this issue.  Also, we've just implemented a [feature which allows you to remove unused services](https://github.com/aws/aws-sdk-php/tree/master/src/Script/Composer) that should help with the overall size of the SDK.  Let us know if you have any questions!
