### ISSUE TITLE
Failed to get AWS credentials from cache

### ISSUE THREAD

**Issue by dsentker** [aws/aws-sdk-php#2253]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP**
v3.150.3

**Version of PHP**
7.4.3

**Describe the question**
I am using this package in a Symfony project. I keep seeing the message "Failed to get AWS credentials from cache" in the log files. In the documentation mentioned above, I found the information that a cache file ( `~/.aws/cli/cache/` ) is being used, but I cannot find any information on how to configure this path or what i have to do to monitor the cache behaviour.

Do you have any suggestions?

**Comment by SamRemis** [comment]
Hi @dsentker,
I am happy to help, but need a bit more information. What is your initial credential provider that is supposed to be caching the credentials?  Also, what log level are you using, that may just be the default provider trying to access some cached credentials and failing.  
Based on the `/cli` in the path, are you trying to sign in using the SSO in the CLI and it's not working?  Or are you just looking to improve performance using credentials caching?

**Comment by dsentker** [comment]
Sorry, i confused the source of the log entry with another package ([aws-async](https://async-aws.com/authentication/credentials-file.html)).
