### ISSUE TITLE
S3EncryptionMultipartUploaderV2 in PHP does not support SSECustomerKey

### ISSUE THREAD

**Issue by zishanj** [aws/aws-sdk-php#2255]
I have checked its documentation and it seems like `S3EncryptionMultipartUploaderV2` in PHP does not support `SSECustomerKey`, `SSECustomerAlgorithm` which is available in `putObject`.

Is there any hidden workaround I am missing?

**Comment by SamRemis** [comment]
Hi @zishanj, 
The parameters you are referring to are for Server Side Encryption, but the S3EncryptionMultipartUploaderV2 is meant to be used for Client Side Encryption.  Are you attempting to use both client and server side encryption at once?    
-Sam

**Comment by zishanj** [comment]
I was just checking different upload features in AWS and came around these 2 functions `MultipartUloader` and `S3EncryptionMultipartUploaderV2`. I have received your response for [`MultipartUloader`](https://github.com/aws/aws-sdk-php/issues/2254) though and will give it a try now. I would like to know how to use this client side encryption without KMS using `S3EncryptionMultipartUploaderV2`. I am using HashiCorp Vault server which is opensource to generate secure keys, I was expecting to use these keys for local encryption.

Any guidance will be appreciated.

**Comment by SamRemis** [comment]
I can point you to the documentation guide on the class: https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-encryption-client.html:

"'@KmsEncryptionContext' is a key-value pair which can be used to add an extra layer of security to your encrypted object. The encryption client must pass in the same key, which it will automatically do on a get call. If no additional context is desired, pass in an empty array. "

Does that answer your question?

**Comment by zishanj** [comment]
Thanks @SamRemis for your valuable input. I will have a look to this client side encryption in detail later but I think this relies on AWS KMS only as mentioned in the link you shared while I was expecting to use some non-KMS solution. I will rely on server side encryption for the time being as it have option to use SSE-C with own customer key and algo besides KMS.
