### ISSUE TITLE
How secure is SSE-C

### ISSUE THREAD

**Issue by zishanj** [aws/aws-sdk-php#2257]
Any idea how much secure is SSE-C when used with `MultipartUploader` or `putObject`? When we pass below args:
```
'SSECustomerKey' => $my_32_chars_key,
'SSECustomerAlgorithm' => 'AES256'
```
will it save the `SSECustomerKey` somewhere on AWS servers and how this `SSECustomerKeyMD5` is used? I have seen that if I don't pass this `SSECustomerKeyMD5` arg then server returns this arg with encrypted value.

**Comment by ajredniwja** [comment]
Hi there, I believe it should be pretty secure, the sole purpose of this is to encryption is about data encryption at rest, that is, Amazon S3 encrypts your data as it writes it to disks in its data centers and decrypts it for you when you access it.

You can find more about it here: 
https://docs.aws.amazon.com/AmazonS3/latest/userguide/serv-side-encryption.html

The `SSECustomerKey` I believe is not stored anywhere which is accessible to any unauthorized user.

**Comment by ajredniwja** [comment]
Closing this now, please reach out if you have any other questions.
