### ISSUE TITLE
Does aws glue schema registry support PHP?

### ISSUE THREAD

**Issue by heungh** [aws/aws-sdk-php#2258]
Confirm by changing [ ] to [x] below:
- [] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
Example: v3.133.6
* get SDK version by printing the output of `Aws\Sdk::VERSION` in your code 
* if the SDK was installed via composer you can see the version installed with `composer show -i` 

**Version of PHP (`php -v`)?**

**Describe the question**
Customer wants to use AWS Glue Schema Registry, but I've read it supports only Java 8.
If possible, I want to know work around using it.  
I also saw the text here  and think it may be possible.
https://newreleases.io/project/github/aws/aws-sdk-php/release/3.163.1
"Aws\Glue - Adding support for Glue Schema Registry. The AWS Glue Schema Registry is a new feature that allows you to centrally discover, control, and evolve data stream schemas."
Can you answer YES/NO or suggest workaround?

**Comment by ajredniwja** [comment]
Hi @heungh thanks for opening the issue, I think what you are looking for is the API reference, https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Glue.GlueClient.html

You can find different functions there, which you can use when using the PHP SDK. 

Does that answer your question?

**Comment by heungh** [comment]
>  you are looking for is the API refere

Thank you for the answer. But I wonder if PHP support AWS Glue Schema Registry.  According to the document, https://docs.aws.amazon.com/glue/latest/dg/schema-registry-gs.html#schema-registry-gs-serde 
it seems to support  only Java 8. However customer wants to use it, I try to find the work around instead.

**Comment by SamRemis** [comment]
If you're referring to this line:
```
Note

Prerequisites: Before completing the following steps, you will need to have a Managed Streaming for Apache Kafka (MSK) or Apache Kafka cluster running. Your producers and consumers need to be running on Java 8 or above.
```

I believe that is only referring to the SerDe library.  The client in the above docs contains all of the relevant methods, including createRegistry, createSchema, etc.  What exactly are you trying to do with glue?
