### ISSUE TITLE
SignatureDoesNotMatch with one of the key-pair from the same IAM (latest SDK)

### ISSUE THREAD

**Issue by stefanolissa** [aws/aws-sdk-php#2260]
Hi, I'm experiencing this sort of weird issue: with a specific pair of keys, generated from the same IAM user, I get the SignatureDoesNotMatch error. I'm using the latest SDK and signature version 4.
Different key-pair generated from the same IAM user are all working.

I can note that the secret of the not working key-pair has a couple of slashes (/).

Could be an SDK internal problem? We deeply check what is provided to the new \Aws\Ses\SesClient(...) construct and the keys are perfectly matching the ones from the AWS console.

Thank you, Stefano.

**Comment by SamRemis** [comment]
Hi @stefanolissa,

Thanks for opening an issue.  It certainly could be the SDK.  Can you post the exact error you're getting (with any keys redacted if they're in the error of course)?  Also, are you using any custom signing code?  And if not, is this an S3 request? 
S3 requests use slightly different signing methods.

**Comment by stefanolissa** [comment]
Hi, the full error is reported below. The issue appears using the SES service and with those problematic keys the same problem appears using a WP plugin that includes the SDK to send emails via Amazon SES.

As said the only thing we can note is the presence of "/" in the secret.

```
Error executing "SendRawEmail" on "https://email.eu-west-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://email.eu-west-1.amazonaws.com` resulted in a `403 Forbidden` response:
<ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">
  <Error>
    <Type>Sender</Type>
    <Code>SignatureDo (truncated...)
 SignatureDoesNotMatch (client): The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
The Canonical String for this request should have been
'POST
/
host:email.eu-west-1.amazonaws.com
x-amz-date:20210615T071256Z
host;x-amz-date
e873152ab9c0d326b5b3518d27c05b64462fcb0abc8499ac11a576f600145610'
The String-to-Sign should have been
'AWS4-HMAC-SHA256
...
```

Is that snippet enough?

Thank you very much for your support.

Stefano.
