### ISSUE TITLE
Some chime:AttendeeLeft Events missing

### ISSUE THREAD

**Issue by tonydub** [aws/aws-sdk-php#2261]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**

Our video conferencing system uses the Amazon Chime SDK JS and PHP and uses the CreateMeeting API  to send Amazon Chime SDK meeting event notifications to one Amazon SQS queue.

The system does receive Chime events via a consumer listening to the configured SQS queue.

We have found that sometimes `chime:AttendeeLeft` events are missing, which results in not updating the presence status of some participants correctly.

Do you have any clues as to why this is happening?

**Version of AWS SDK for PHP?**
3.154.2

**Version of PHP (`php -v`)?**
7.4.15

**To Reproduce (observed behavior)**

Below is a sample of the PHP code used to create meeting the messages:

```php

// ...

// The SQS client use region `us-east-1`

try {
    $result = $this->sqsClient->getQueueAttributes([
        'QueueUrl' => $queueUrl,
        'AttributeNames' => [
            'QueueArn',
        ],
    ]);
} catch (AwsException $e) {
    if ($e->getAwsErrorCode() === 'AWS.SimpleQueueService.NonExistentQueue') {
        $result = $this->sqsClient->createQueue([
            'QueueName' => $queueName,
            'Attributes' => [
                'DelaySeconds' => 0, // The length of time, in seconds, for which the delivery of all messages in the queue is delayed. Valid values: An integer from 0 to 900 seconds (15 minutes).
                'MessageRetentionPeriod' => $messageRetentionPeriod, // The length of time, in seconds, for which Amazon SQS retains a message. Valid values: An integer from 60 seconds (1 minute) to 1,209,600 seconds (14 days).
                'ReceiveMessageWaitTimeSeconds' => 0,
            ],
        ]);
        $result = $this->sqsClient->getQueueAttributes([
            'QueueUrl' => $queueUrl,
            'AttributeNames' => [
                'QueueArn',
            ],
        ]);    
    }

    throw $e;
}

$queueArn = $result->get('Attributes')['QueueArn'];

$parameters = [
    'ClientRequestToken' => Uuid::uuid4(),  // The unique identifier for the client request. Use a different token for different meetings.
    'ExternalMeetingId' => $externalMeetingId, // The external meeting ID.
    'MediaRegion' => 'eu-west-3',
    'NotificationsConfiguration' => ['SqsQueueArn' => $queueArn],
];

/** @see https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-chime-2018-05-01.html#createmeeting */
$awsResult = $this->chimeClient->createMeeting($parameters);

// ...
```

Below is a sample of the PHP code used to consume the messages:

```php

// ...

$result = $this->sqsClient->receiveMessage([
    'AttributeNames' => ['SentTimestamp'],
    'MaxNumberOfMessages' => 10,
    'MessageAttributeNames' => ['All'],
    'QueueUrl' => $queueUrl, 
    'WaitTimeSeconds' => 20,
]);
if (!empty($result->get('Messages'))) {
    $messages = $result->get('Messages');

    foreach ($messages as $message) {
        yield $message;
    }
}
```

**Expected behavior**

I expect to receive all 'chime:AttendeeLeft' events, for all participants who left a Chime Meeting using the Chime JS SDK.

**Comment by stobrien89** [comment]
Hi @tonydub,

Apologies for the delayed response.  Were you able to find a resolution to this, or are you still having issues?  If the latter is true, it would help to have a reproducible example, although I know that may be difficult to produce given there are a few different components at play.  Let us know either way!
