### ISSUE TITLE
Access Denied : Header of the Token generated via PHP SDK is not matching that of aws rds generate-db-auth-token 

### ISSUE THREAD

**Issue by angshuman-agarwal** [aws/aws-sdk-php#2262]
**Describe the bug**
Token generated via PHP SDK is not same as what is generated via `aws rds generate-db-auth-token --host <host> --port <port> --region <region> --username <user>` which causes Access Denied.

**Version of AWS SDK for PHP?**
Example: v3.133.6

**SDK installed via zip**
https://docs.aws.amazon.com/aws-sdk-php/v3/download/aws.zip

**Version of PHP (`php -v`)?**
8.0

**php -m shows mbstring module is there**

**To Reproduce (observed behavior)**
Install this Docker Wordpress image - `docker pull wordpress:php8.0-fpm` in a `EKS cluster`
Put the createToken code in the /var/www/html/wp-includes/wp-db.php code (just before mysqli_connect(...))
It fails. But if I use `aws rds generate-db-token....` and hardcode the token generated from that cmd, it passes & connects.

I had used this code for createToken : https://gist.github.com/sators/38dbe25f655f1c783cb2c49e9873d58a 

I see this token generated from PHP SDK does not authenticate for me whereas `aws rds generate-db-auth-token` cmd line generates a different token pattern and that token is also shorter than PHP, does authenticates successfully. I noticed that the `X-AMZ-Security-Token` part is larger when generated via PHP SDK code (`createToken`). 

Expected should be same Output as :
`aws rds generate-db-auth-token --host <host> --port <port> --region <region> --username <user>`

And this one works for me but not the PHP one !

NB: I installed the SDK via the zip option as composer is not an option for me. And I also checked php -m, I see mbstring module is enabled. 

**Expected behavior**
Token should be same as `aws rds generate-db-auth-token --host <host> --port <port> --region <region> --username <user>`

**Comment by KAJed82** [comment]
@yenfryherrerafeliz Were you able to sort this out? I'm having similar issues and unable to connect to RDS with PHP. I suspect the token because I can connect from the mysql client on the same instance using the CLI to generate a token.
