### ISSUE TITLE
Polly Neural Voices Not Working for PHP SDK v. 3.185

### ISSUE THREAD

**Issue by winterroberts** [aws/aws-sdk-php#2274]
**Issue Description**
Using Polly with AWS SDK PHP v 3.185 (installed from composer with dependencies) on PHP 7.4.3 neural voices are not working.

**Steps to Reproduce**
The below code is used:
```php
$result = $awsClient->synthesizeSpeech([
    'Text' => $text,
    'OutputFormat' => $format, // mp3 
    'VoiceId' => $voice, // Joanna (supports neural voice)
    'Engine' => 'neural', // sounds better
]);
```

When this code is used an output is produced, but it uses the standard engine rather than the neural engine. In the case that I switch to using a voice which only supports the neural engine (I chose to use `Kevin`), I receive the error below.
```
Error executing "SynthesizeSpeech" on "https://polly.us-west-2.amazonaws.com/v1/speech"; AWS HTTP error: Client error:
`POST https://polly.us-west-2.amazonaws.com/v1/speech` resulted in a `400 Bad Request` response:
{"message":"This voice does not support the selected engine: standard"}
ValidationException (client): This voice does not support the selected engine: standard - {"message":"This voice does
not support the selected engine: standard"}
```

**Expected Behavior**
An output which uses the neural engine is expected.

**Additional context**
The AWS SDK is included directly (through autoload file from composer `vendors/autoload.php`), and called from a Controller in CakePHP.

**Comment by SamRemis** [comment]
Hi @winterroberts,
I tried the exact code you wrote above, and it worked without a problem.  My first suggestion is adding `'debug' => true` to your client parameters, and check that something else isn't changing it- maybe cake.php?

I will post my results so you can compare:
 ```
-> Entering step build, name 'builder'
--------------------------------------

  request.instance was set to 0000000051d28f1a0000000015db548c
  request.method was set to POST
  request.headers was set to array(3) {
    ["X-Amz-Security-Token"]=>
    string(7) "[TOKEN]"
    ["Host"]=>
    array(1) {
      [0]=>
      string(29) "polly.us-west-2.amazonaws.com"
    }
    ["Content-Type"]=>
    array(1) {
      [0]=>
      string(16) "application/json"
    }
  }
  
  request.body was set to {"Text":"test speech","OutputFormat":"mp3","VoiceId":"Joanna","Engine":"neural"}
  request.scheme was set to https
  request.path was set to /v1/speech

```

**Comment by winterroberts** [comment]
My output running the same code is as follows:
```
-> Entering step build, name 'builder'
--------------------------------------

request.instance was set to 000000004f00d42a0000000072d151f8
request.method was set to POST
request.headers was set to array(3) {
["X-Amz-Security-Token"]=>
string(7) "[TOKEN]"
["Host"]=>
array(1) {
[0]=>
string(29) "polly.us-west-2.amazonaws.com"
}
["Content-Type"]=>
array(1) {
[0]=>
string(26) "application/x-amz-json-0.0"
}
}

request.body was set to {"Text":"test speech":"mp3","VoiceId":"Joanna"}
request.scheme was set to https
request.path was set to /v1/speech
```

It looks like the `Engine` option is being dropped but not really clear to me as to where.

**Comment by SamRemis** [comment]
That's really odd- I wish I could reproduce this to help out.  If you scroll through the rest of the debug, does it say engine is dropped anywhere?

Worst case scenario you can write a middleware to add it back in if you want a hacky fix.  Not sure what your usecase here is

**Comment by winterroberts** [comment]
Here is the total relevant debug information, but still no indication that Engine was dropped other than its inclusion in the first step and not in the next ones.
```
-> Entering step init, name 'idempotency_auto_fill'
---------------------------------------------------

command was set to array(3) {
["instance"]=>
string(32) "000000004f00d46b0000000072d151f8"
["name"]=>
string(16) "SynthesizeSpeech"
["params"]=>
array(5) {
["Text"]=>
string(890) "test speech"
["OutputFormat"]=>
string(3) "mp3"
["VoiceId"]=>
string(6) "Joanna"
["Engine"]=>
string(6) "neural"
["@http"]=>
array(1) {
["debug"]=>
resource(187) of type (stream)
}
}
}

request was set to array(0) {
}



-> Entering step validate, name 'validation'
--------------------------------------------

no changes


-> Entering step build, name 'builder'
--------------------------------------

request.instance was set to 000000004f00d42a0000000072d151f8
request.method was set to POST
request.headers was set to array(3) {
["X-Amz-Security-Token"]=>
string(7) "[TOKEN]"
["Host"]=>
array(1) {
[0]=>
string(29) "polly.us-west-2.amazonaws.com"
}
["Content-Type"]=>
array(1) {
[0]=>
string(26) "application/x-amz-json-0.0"
}
}

request.body was set to {"Text":"test speech","OutputFormat":"mp3","VoiceId":"Joanna"}
request.scheme was set to https
request.path was set to /v1/speech
```

**Comment by SamRemis** [comment]
That's really odd, looking at that, it suggests the removal is happening somewhere in our code.  

I also noticed your content type is changed- that should say "application/json", not x-amz-json.  I'm wondering if they could be related.  Can you tell me a few more things to help get to the root cause of the issue:

- What OS are you on
- Can you show me the values you're using to initialize awsClient
- Is this running on your local machine or some sort of server that could explain the odd behavior?

**Comment by winterroberts** [comment]
This is running on my machine in docker for WSL 2 (with Windows Desktop control) to simulate the production environment accurately.

Initialized client with the following code:
```php
$awsClient = new Aws\Polly\PollyClient([
                //'profile' => 'default', // commented out to use hard-coded creds below
                //'version' => '2016-06-10',
                'version' => 'latest',
                'region' => 'us-west-2',
                'credentials' => [
                    'key' => 'api_key', // This is changed so as to prevent revealing login info here.
                    'secret' => 'api_secret' // This is changed so as to prevent revealing login info here.
                ]
            ]);
```

**Comment by SamRemis** [comment]
It could have something to do with the machine; it will take me some time to set up an example container to work in, so I don't think I'll be able to troubleshoot it myself today.  Other than that, we are running the same code, version of the SDK, and php language version.  I can get back to this ASAP if you don't want to debug further.  

There's also really only one line which I could think might be removing a value.  If you don't mind helping me out and have an IDE or something that makes editing the SDK code not too difficult, then maybe you could try adding a few lines to help me debug sooner:

In src/Api/Serializer/RestSerializer.php on line 82, just inside the foreach loop:    
` echo "$name\n";`

And above that on line 80 just before the loop you could add 
```
        echo "\nmember names:\n";
        foreach ($input['members'] as $memberShape) {
            echo $memberShape['shape'] . "\n";
        }
        echo "\ninputs:\n";
```

It should output 
```
member names:
Engine
LanguageCode
LexiconNameList
OutputFormat
SampleRate
SpeechMarkTypeList
Text
TextType
VoiceId

inputs:
Text
OutputFormat
VoiceId
Engine
@http
@context

```

My only guess without debugging further is that something went wrong and the value of 'Engine' won't match on the top and bottom.

**Comment by winterroberts** [comment]
Turns out composer doesn't like to rebuild dependencies. Even when the docker images were deleted and their volumes were removed composer wouldn't reimport vendor information for the next image until the operating system (Ubuntu, WSL 2) was completely restarted. Basically, my installation was still stuck on SDK v. 3.58 but composer would report the newer version from its config when asked.

**Comment by SamRemis** [comment]
@winterroberts that makes a ton of sense!  That would totally happen if the 'Engine' parameter were added later.  Thank you for your patience and help with debugging that, as well as for following up and closing out the issue.  I'll keep that in mind in case anyone else brings a similar issue to our attention.
