### ISSUE TITLE
Unable to create or delete digital ocean spaces

### ISSUE THREAD

**Issue by ashu555** [aws/aws-sdk-php#2275]
Hi. When I try to create spaces on Digital Ocean using the laterst version of this SDK , it gives `Error executing \"CreateBucket\" on \"https://fra1.digitaloceanspaces.com/test.faveocloud.com\"; AWS HTTP error: Client error: `PUT https://fra1.digitaloceanspaces.com/test.faveocloud.com` resulted in a `403 Forbidden` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>SignatureDoesNotMatch</Code><RequestId>tx000000000000001bfbcf5-0060f6 (truncated...)\n SignatureDoesNotMatch (client):  - <?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>SignatureDoesNotMatch</Code><RequestId>tx000000000000001bfbcf5-0060f65201-17d69921-fra1b</RequestId><HostId>17d69921-fra1b-fra1-zg02</HostId></Error>`
However, when I revert back to the older version it works just fine. Can you please release a patch with this fix.

**Comment by SamRemis** [comment]
Hi there, 
I wish I could help you, but digital ocean isn't an AWS service or product, and we have no references to it in this repo.  Are you looking for [this repo](https://github.com/DigitalOceanPHP/Client)? 
-Sam

**Comment by ashu555** [comment]
But we use AWS-sdk APIs to create s3 bucket on digital ocean. When we revert back to the older version of this package it creates buckets on DO. However, with latest version it does not work.

**Comment by SamRemis** [comment]
Please send me some reproduction code so that I can take a look; it's hard to get an idea of what could be going on from an error alone?  What SDK methods are you calling?
