### ISSUE TITLE
SQS client stuck on message polling

### ISSUE THREAD

**Issue by Rastusik** [aws/aws-sdk-php#2280]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
We experience a same problem as described in this #1662 and this issue aws/aws-sdk-js#367
We're using symfony messenger and enqeue sqs client. We've been using this setup for at least a year now without any problems, everything worked correctly. But last week we've been starting to experience a weird issue - the php workers got stuck while polling for messages without throwing a timeout exception or anything similar. The first time this happened, they were stuck for cca. 7 hours. This happened on July 27th and 28th and today (August 2nd). One weird thing is that it always happened between 06:00 AM - 06:12 AM UTC. There are no special jobs running in our project at that time. I've been looking for a timeout option in the PHP SDK but I haven't found any. It would be great to have one for such an occasion. In #1662 it is written that this situation only happens in docker environment. I'm not sure about this, because we're running in kubernetes for at least two years and this problem occurred only now.

I suspect there is an network issue somewhere when the problem occurs. The main part of the problem is that the workers won't get unstuck after such network error, so our async processing is stopped this way and we need to code non-systematic workarounds for this issue.

**Version of AWS SDK for PHP?**
Example: 3.176.2q
* get SDK version by printing the output of `Aws\Sdk::VERSION` in your code 
* if the SDK was installed via composer you can see the version installed with `composer show -i` 

**Version of PHP (`php -v`)?**
7.4.10

**To Reproduce (observed behavior)**
I can't say anything special about this, just run the Symfony messenger:consume command with enqueue sqs client ... This happens very rarely, almost not at all ... We've recorder only 3 occurrences in over a year.

But I was actually able to reproduce this using mitmproxy:
1) change the `Aws\Handler\GuzzleV6\GuzzleHandler` constructor to this:
```php
$this->client = $client ?: new Client([
            'proxy' => 'host.docker.internal:8080', // i run the proxy from docker through a mapped port to localhost
            'verify' => false,
        ]);
```
2) stop the request in the mitm proxy interface (an intro to this can be found here https://docs.mitmproxy.org/stable/mitmproxytutorial-modifyrequests/ , you just won't be modyfying anything, you'll just wait)... press `i` in the interface, type `~u /{userId}/{queue_name}` and type enter and the next poll request will get stuck and no exception will be thrown

When I hacked some timeouts manually into the Client constructor, everything worked well, but I'm not sure if I won't break anything with such modification.

**Expected behavior**
There should be a polling connection timeout which should throw an exception when there wouldn't be any response in some configured time span

**Screenshots**
Not applicable

**Additional context**
- Symfony Messenger v5.2.5
- enqueue/sqs: 0.10.9

**Comment by alok87** [comment]
We are also facing this. The long running php worker pods needs to be deleted for them able to pick jobs, otherwise it's stuck.

**Comment by dsantuc** [comment]
Make sure you're setting a request timeout.

As described in [this thread](https://github.com/aws/aws-sdk-php/issues/1662#issuecomment-899767739), there are no connection or request timeouts by default, so if you're doing long polling, and there's an interruption of network connectivity after the client has connected but before the server responds with messages, the `receiveMessage()` call will wait forever.

You can set the timeouts with these `'http'` options passed to the constructor:

```
$client = new SqsClient([
    'region' => 'us-east-1',
    'version' => 'latest',
    'http' => [
        'connect_timeout' => 5, // how many seconds to wait for a connection
        'timeout' => 60 // max seconds for the entire request
    ]
]);
```
Also, make sure `'timeout'` is longer than your `'WaitTimeSeconds'` when polling.

**Comment by Rastusik** [comment]
@dsantuc yeah, I have written the same thing in general above:

> When I hacked some timeouts manually into the Client constructor, everything worked well, but I'm not sure if I won't break anything with such modification.

but the problem is that the whole AWS SDK uses the `default_http_handler()` function to instantiate the SqsClient, so this feels a little hacky. I would like to be able to set the timeouts using some official way.

**Comment by stobrien89** [comment]
Apologies for the lack of interaction here— I hope @dsantuc's answer was helpful.  Our guidance here would be to set these configuration options like mentioned above to suit your use case. We won't be extending this functionality any further as these are already [documented client configuration options](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#config-http).  Let us know if you have any additional questions!
