### ISSUE TITLE
How to use in PHP5.3 Version

### ISSUE THREAD

**Issue by rajivPHP** [aws/aws-sdk-php#2287]
Confirm by changing [ ] to [x] below:
- [ ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [ ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
Example: v3.133.6
* get SDK version by printing the output of `Aws\Sdk::VERSION` in your code 
* if the SDK was installed via composer you can see the version installed with `composer show -i` 

**Version of PHP (`php -v`)?**

**Describe the question**

**Comment by ajredniwja** [comment]
hi @rajivPHP, I am not sure if I understand the question here, https://github.com/aws/aws-sdk-php#getting-started mentions that you'll need to have PHP >= 5.5 to run the SDK. So unfortunately PHP version 5.3 wont work with the SDK. 

Closing this issue now, let us know if you have any other questions.
