### ISSUE TITLE
Symlink Incompatible With Some Deployment Mechanisms

### ISSUE THREAD

**Issue by MathSmath** [aws/aws-sdk-php#2289]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
Not strictly a bug in the package, but the file `tests/Credentials/testlink` is a symlink, which breaks many deployment mechanisms (including CodeDeploy and Elastic Beanstalk) when the file it references does not exist. The symlink _seems_ superfluous, and possibly committed by accident? I can't find a legitimate reason for it, and it seems to point to a file unique to someone's local environment--but potentially someone here has context for why it exists. It was added in this commit: https://github.com/howardlopez/aws-sdk-php/commit/0ea03fd6ade07a52d3bc36a25dd1d90c66d43c4d#diff-916e8de261805d4949eae1ba9e1b8a416f3eb42013eccbd6b0c45bc821a10a9d

**Version of AWS SDK for PHP?**
v3.54.6

**Version of PHP (`php -v`)?**
Not related to PHP

**To Reproduce (observed behavior)**
Try to deploy any project using the aws-sdk-php package via CodeDeploy, and the deploy will fail with the message "No such file or directory: '[project root]/vendor/aws/aws-sdk-php/tests/Credentials/testlink'".

**Expected behavior**
The deploy should complete without issue, and should not encounter any dead-end symlinks.

**Additional context**
I'm currently working around this by explicitly deleting this file from the deployment artifact before running CodeDeploy. Again, I realize this is not a bug in the package, but just seems like a mistake with some unintended side-effects.

**Comment by SamRemis** [comment]
@MathSmath Thanks for bringing this to our attention- that doesn't look familiar to me, and I didn't know it was there.  It also doesn't appear to be relevant to that particular commit in any way.  When I get some more time, I will definitely do a search through the code to make sure it's not used anywhere and get rid of it.  

-Sam

**Comment by nbennett25** [comment]
2nd this - the symlink presumes a directory structure that may or may not exist:
```
www-data@atlas-php-fpm:/var/www/html/vendor/aws/aws-sdk-php/tests/Credentials$ ls -lrta
total 144
lrwxrwxrwx  1 www-data www-data    66 Sep  8 14:39 testlink -> /var/folders/1z/q59hjnz16ss1kbsy4cfmsggc7ywn62/T/.aws/my-token.jwt
```
why not just put it in the same directory as the module..?

**Comment by stobrien89** [comment]
Hi all, 

It seems #2340 fixed this.  Let us know if you're still having issues!
