### ISSUE TITLE
Operation not found: CreateMediaCapturePipeline ref AWS CHIME service

### ISSUE THREAD

**Issue by gsudhanshu** [aws/aws-sdk-php#2296]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
I am trying to call the createMediaCapturePipeline service of ChimeClient using aws php sdk
[reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-chime-2018-05-01.html?cx=&ie=UTF-8&q=media+capture+pipeline#createmediacapturepipeline)

**Version of AWS SDK for PHP?**
"aws/aws-sdk-php-laravel": "^3.6"

**Version of PHP (`php -v`)?**
7.4.21

**To Reproduce (observed behavior)**
            ```
            \Log::debug("In start recording, meetingId:".$meeting->id);
            
            $chimeClient = AWS::createClient('chime');
            
            $result = $chimeClient->createMediaCapturePipeline([
                'ClientRequestToken' => "Meeting".$meeting->id,
                'SinkArn' => 'arn:aws:s3:::'.env('AWS_BUCKET'), // REQUIRED
                'SinkType' => 'S3Bucket', // REQUIRED
                'SourceArn' => "arn:aws:chime::".env('AWS_ACCOUNT_ID').":meeting:"."Meeting".$meeting->id, // REQUIRED
                'SourceType' => 'ChimeSdkMeeting', // REQUIRED
            ]);
```

**Expected behavior**
chime meeting recording starts and we get a result as stated in aws docs:
[
    'MediaCapturePipeline' => [
        'CreatedTimestamp' => <DateTime>,
        'MediaPipelineId' => '<string>',
        'SinkArn' => '<string>',
        'SinkType' => 'S3Bucket',
        'SourceArn' => '<string>',
        'SourceType' => 'ChimeSdkMeeting',
        'Status' => 'Initializing|InProgress|Failed|Stopping|Stopped',
        'UpdatedTimestamp' => <DateTime>,
    ],
] 

logs attached
[laravel.log](https://github.com/aws/aws-sdk-php/files/7013978/laravel.log)

**Comment by adeelnawaz** [comment]
Hi, any update on this?

**Comment by stobrien89** [comment]
Hi @gsudhanshu,

Apologies for the lack of contact here.  I did some digging and found that this operation was added to the `chime` models on 7/7/2021, meaning you'll need to retrieve version >= `3.185.8` from the Laravel service container.  Closing for now, but let me know if this is still an issue!
