### ISSUE TITLE
Textract analyzeExpenseAsync() not returning anything in the promise for a PDF file

### ISSUE THREAD

**Issue by georgewoofbates** [aws/aws-sdk-php#2302]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
When using the analyzeExpenseAsync function for a Textract client to analyse a PDF, the promise never returns to the then() function. The page loads, with no output or error

**Version of AWS SDK for PHP?**
3.191.7

**Version of PHP (`php -v`)?**
7.2

**To Reproduce (observed behavior)**
`    $bucket = 'BUCKET_NAME';

    $client = new TextractClient([
        'region' => 'ap-southeast-2',
        'version' => 'latest',
        'credentials' => array(
            'key' => 'KEY',
            'secret'  => 'SECRET',
        )
    ]);

    $promise = $client->analyzeExpenseAsync([
        'Document' => [
            'S3Object' => [
                'Bucket' => $bucket,
                'Name' => 'invoice.pdf'
            ]
        ]
    ]);

    $promise->then(
        function ($value) {
            echo "The promise was fulfilled with {$value}";
        },
        function ($reason) {
            echo "The promise was rejected with {$reason}";
        }
    );`

**Expected behavior**
Return a document object

**Additional context**
Just using plain PHP, Composer for required.

**Comment by NextSteps79** [comment]
update PHP/AWS so what promise talk abouth my Beta program 
needs Rules on my Beta branch DevSecOps investigation true

**Comment by yenfryherrerafeliz** [comment]
Hi @georgewoofbates thank you for reaching out and sorry for the delayed response. Is this still a persistent issue?, if so, have you tried calling the "wait function" since this will force the promise to wait for a resolution. 
Please see my example below: 

<details>

```php
$promise->then(
    function ($value) {
        echo "The promise was fulfilled with {$value}";
    },
    function ($reason) {
        echo "The promise was rejected with {$reason}";
    }
)->wait();
```
</details>

Thank you!

**Comment by georgewoofbates** [comment]
This worked with the ->wait() command.
