### ISSUE TITLE
Field "ContentMD5" not listed for S3 PutObject operation

### ISSUE THREAD

**Issue by TheJosh** [aws/aws-sdk-php#2304]
**Describe the issue with documentation**
The `ContentMD5` field is not listed for the S3 PutObject operation.

This is a required field for using Object Lock, which creates further confusion. The documentation mentions the requirement for the `Content-MD5` header, but the field which creates this header isn't documented; in fact this makes it look like "metadata" should be used, but this isn't correct either.

**To Reproduce (observed behavior)**
https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#putobject

**Expected behavior**
In the overview, above `ContentSHA256` there should be:
```
'ContentMD5' => '<string>',
```

In the list of arguments, above `ContentSHA256` there should be:
> **ContentMD5**
> Type: string
> A MD5 hash of the body content of the request. This field is required if Object Lock is used.
> Specified as the base64-encoded version of the binary md5 hash, which can be generated using the php example of `base64_encode(md5($body, true))`

**Comment by SamRemis** [comment]
@TheJosh Thanks for bringing this up :)
It appears this was done on purpose in this commit: https://github.com/aws/aws-sdk-php/commit/e671f28842f5e3fc0248ccf6c1c8b869114b5778#diff-850aaf548a36b64042d2ddaa1c7d26afe884fd61b5e63cf9548fb7551df97ebbR521

I'm not sure why he would have done that, potentially for some legacy reason that no longer apply?  I will do some research and testing around it, and update when I'm able

**Comment by stobrien89** [comment]
Linking https://github.com/aws/aws-sdk-php/issues/2256
