### ISSUE TITLE
composer Conflict with introduction of aws-crt-php

### ISSUE THREAD

**Issue by pascallap** [aws/aws-sdk-php#2310]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
`composer update` doesn't work anymore with the introduction of aws-crt-php.
aws-crt-php is a new require dependency. But this dependency has conflicts with `phpunit/php-timer > 2`.
The actual version of phpunit requires a version higher than 2.
Is this aws-crt-php really a required, or should it be a suggested dependency?

**Version of AWS SDK for PHP?**
v3.192.0

**Version of PHP (`php -v`)?**
8.0.10

**To Reproduce (observed behavior)**
Simply a composer file that require "aws/aws-sdk-php": "^3.147"
And in require-dev "phpunit/phpunit": "^9"

**Expected behavior**
Version 3.192.0 is installed

**Comment by SamRemis** [comment]
@pascallap Thanks for bringing this issue up; unfortunately it is required going forward.  It's our common runtime dependency that is our only way of accessing cryptography algorithms that are needed for signatures on some new features.

I can talk to the CRT team about removing the dependency conflict

**Comment by SamRemis** [comment]
I personally think it's okay to remove, I'll see if the team agrees with me.  Made a PR here: https://github.com/awslabs/aws-crt-php

**Comment by SamRemis** [comment]
@pascallap This should be fixed by https://github.com/aws/aws-sdk-php/pull/2312 where we have removed the conflict.  I will merge later today after the tests pass, and it should be included in the next tagged composer release tomorrow at 2pm EST.  I was unable to replicate the conflict error, so I hope you don't mind confirming the fix when you're able.

**Comment by stof** [comment]
> I was unable to replicate the conflict error, so I hope you don't mind confirming the fix when you're able.

it probably depend on which PHPUnit version is used by the project itself.

**Comment by pascallap** [comment]
I confirm that problem is solved with the removal of the conflicting dependency. Thanks a lot!
