### ISSUE TITLE
PHP-FPM processes get stuck fetching S3 objects on massive loads

### ISSUE THREAD

**Issue by kaktusas2598** [aws/aws-sdk-php#2317]
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**

On Sundays our system processes massive amounts of data which include intelligence reports. They make many calls to S3, fetching multiple objects from our main production bucket. We noticed that very often some of these calculations gets stuck fetching S3 objects.

Now each reports is processed on a single ECS task, so we have multiple ECS tasks running on Sunday, each one of them processing a single report. On some of these Sundays I had to ssh into each ECS task and debug the problem. We use PHP-FPM for our application and all the background processing, so I used low-overhead sampling profiler (phpspy) to debug some of the php-fpm worker threads and they always produce same stacktrace: 

0 curl_multi_select <internal>:-1
1 GuzzleHttp\Handler\CurlMultiHandler::tick /srv/www/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:141
2 GuzzleHttp\Handler\CurlMultiHandler::execute /srv/www/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:174
3 GuzzleHttp\Promise\Promise::invokeWaitFn /srv/www/vendor/guzzlehttp/promises/src/Promise.php:243
4 GuzzleHttp\Promise\Promise::waitIfPending /srv/www/vendor/guzzlehttp/promises/src/Promise.php:219
5 GuzzleHttp\Promise\Promise::invokeWaitList /srv/www/vendor/guzzlehttp/promises/src/Promise.php:262
6 GuzzleHttp\Promise\Promise::waitIfPending /srv/www/vendor/guzzlehttp/promises/src/Promise.php:219
7 GuzzleHttp\Promise\Promise::invokeWaitList /srv/www/vendor/guzzlehttp/promises/src/Promise.php:262
8 GuzzleHttp\Promise\Promise::waitIfPending /srv/www/vendor/guzzlehttp/promises/src/Promise.php:219
9 GuzzleHttp\Promise\Promise::wait /srv/www/vendor/guzzlehttp/promises/src/Promise.php:60
10 GuzzleHttp\Promise\EachPromise::GuzzleHttp\Promise\{closure} /srv/www/vendor/guzzlehttp/promises/src/EachPromise.php:109
11 GuzzleHttp\Promise\Promise::invokeWaitFn /srv/www/vendor/guzzlehttp/promises/src/Promise.php:243
12 GuzzleHttp\Promise\Promise::waitIfPending /srv/www/vendor/guzzlehttp/promises/src/Promise.php:219
13 GuzzleHttp\Promise\Promise::wait /srv/www/vendor/guzzlehttp/promises/src/Promise.php:60
14 PiExt\S3Client\S3Client::fetchObjectsInParallel /srv/www/library/pi-ext/s3-client/src/S3Client.php:169
15 PiExt\S3Client\S3Client::getObjects /srv/www/library/pi-ext/s3-client/src/S3Client.php:99

I have done this a few times on all stuck reports and these lines are always the same so we believe it's an issue with fetching S3 objects using the PHP SDK's S3Client.php.

**Version of AWS SDK for PHP?**
3.191.7

**Version of PHP (`php -v`)?**
8.0.9

**To Reproduce (observed behavior)**
We cannot reproduce this issue as it only happens on Sunday when we are processing most of the data for our production system.

**Expected behavior**
PHP-FPM processes get stuck and can only be fixed by restarting php-fpm service.

**Comment by SamRemis** [comment]
@kaktusas2598 Does the log say the error being thrown, or is it just limited to the stack trace provided?   It certainly could be an issue on our side; also, has this always happened, or was it a recent change that caused it?

**Comment by kaktusas2598** [comment]
@SamRemis First of all, thank you for your reply. As you have mentioned, stack trace is indeed cut, but this is only because our reports always get stuck while processing different components but the rest of it is always the same, so we know it's always ends up stuck fetching s3 objects, but from different places in code. 

We definitely haven't changed any code related to this and this issue have been happening since July 17.

**Comment by SamRemis** [comment]
@kaktusas2598, the only significant code change pushed that week had to do with government cloud regions, and it was very unlikely to affect your code.  Just to be sure though, this doesn't happen to be on a FIPS region, does it?  If you're not sure, all FIPS regions have "fips" in the name, so you be able to tell pretty quickly if it were.  

I was hoping the stack trace was more descriptive a bit earlier than what you posted, but it sounds like it probably wasn't.  I'm wondering if it could be some sort of race condition on the CURL multi handler.  I did find [a new issue](https://githubmemory.com/repo/guzzle/guzzle/issues) with an infinite loop on the CURL multi handler that uses a deprecated option called "save_to".  

Would you be able to post the code where this is called from?  I'd ideally like to see the initialization of the S3Client, as well as any custom handlers or middleware you add to it, then whichever method you're using to retrieve the object (probably getObject?).

**Comment by stobrien89** [comment]
Hi @kaktusas2598,

Closing for now, but please let us know if this is still an issue!
