### ISSUE TITLE
Required extension is not available on Windows machines.

### ISSUE THREAD

**Issue by bobsort** [aws/aws-sdk-php#2318]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
I checked all above but I'm not sure how that would be related. 

Trying to install SDK on windows machine, running composer update fails since sdk requires an extension [ext-pcntl](https://www.php.net/manual/en/pcntl.installation.php) which is not available on windows machines.

Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - The requested PHP extension ext-pcntl * is missing from your system. Install or enable PHP's pcntl extension.

**Version of AWS SDK for PHP?**
* get SDK version by printing the output of `Aws\Sdk::VERSION` in your code 
* if the SDK was installed via composer you can see the version installed with `composer show -i` 
If I could run the sdk I would, but it won't install to be able to run it from `my code`
But I can read from `aws-sdk-php/src/Sdk.php`  that it is 3.194.0

**Version of PHP (`php -v`)?**
I'm not sure how that would help since extension is not even available on OS, but here it is 7.4.11 , 8.1

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)
Try installing SDK via composer on a windows machine

**Expected behavior**
Installation success?!!

**Screenshots**
N/A

**Additional context**
I did remove the requirement from composer file but I'm still not sure what they will break. since it is not easy task to go through  almost 16 million lines of code!

**Comment by Petah** [comment]
`ext-pcntl` is only required in the dev dependancies.

**Comment by ajredniwja** [comment]
Hi there, you can use `--dev` flag when doing composer install. That should resolve this issue, please reach out if that doesnt help or if you have questions.
