### ISSUE TITLE
While installing API Management v3.11, Error curl: (7) Failed connect to 169.254.169.254:80; Connection timed out

### ISSUE THREAD

**Issue by fynmanoj** [aws/aws-sdk-php#2322]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
while installing API Management v3.11  using `curl -L https://bit.ly/install-apim-3x | bash`   it is throwing this error:

curl: (7) Failed connect to 169.254.169.254:80; Connection timed out.

all the dependenices installtion were successful,  but at the end the installer wait for the above curl to return and then throw the timeout error.

Operating system: CentoS 7

**Version of AWS SDK for PHP?**
Example: v3.133.6
* get SDK version by printing the output of `Aws\Sdk::VERSION` in your code 
* if the SDK was installed via composer you can see the version installed with `composer show -i` 

**Version of PHP (`php -v`)?**

**To Reproduce (observed behavior)**
curl -L https://bit.ly/install-apim-3x | bash

**Expected behavior**
installation to be successfull
**Screenshots**

**Additional context**
Any additional information relevant to the issue. Examples include any framework you may be using (e.g. Laravel, Wordpress) in conjunction with the AWS SDK for PHP, or PHP/environment config settings if the issue is related to memory or performance.

**Comment by stobrien89** [comment]
Hi @fynmanoj,

Sorry to hear about the issues.  I'm not certain you're using the AWS PHP SDK, and I'm not sure the package you're attempting to install is supported by AWS.  Closing this for now, but we'd be happy to take another look if this is in fact an issue with the AWS PHP SDK.
