### ISSUE TITLE
AWS CloudShell `Error retrieving credentials from the instance profile metadata service.`

### ISSUE THREAD

**Issue by kuettai** [aws/aws-sdk-php#2323]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
Background: The cloudshell environment does not have "aws configure" setup.

I created a python file p.py with the following

```python
import boto3
s3 = boto3.client('s3')
resp = s3.list_buckets()
print(resp)
```

Python3 successfully returns me the list of buckets.

However in PHP SDK, (the scripts work in EC2, with InstanceProfile) but in CloudShell, i get this error: "Error retrieving credentials from the instance profile metadata service"

This is the sample code:

```php
use Aws\Rds\RdsClient;
$o = new RdsClient([
    'signature_version' => 'v4',
    'region' => 'ap-southeast-1',
    'version' => '2014-10-31'
]);
$o->describeDBInstances();
```

What is the recommended workaround for PHP SDK to follow CloudShell IAM-User permission? The expectation on permission granting in PHP SDK should behave the same as Python SDK.

**Version of AWS SDK for PHP?**
v3.192.1

**Version of PHP (`php -v`)?**
PHP 7.2.34 (cli)

**To Reproduce (observed behavior)**
IAM User with readOnlyPermission in RDS, login to AWS Console. Launch cloudshell (in any available region). Install php.
```bash
if(sudo yum list installed  | grep php-cli > /dev/null) then echo 'PHP installed ,skipped'; else sudo amazon-linux-extras install -y php7.2; fi
##aws-sdk requires mbstring and xml
if(sudo yum list installed | grep php-mbstring > /dev/null) then echo 'php-mbstring installed, skipped'; else sudo yum install php-mbstring -y; fi
if(sudo yum list installed | grep php-xml > /dev/null) then echo 'php-xml installed, skipped'; else sudo yum install php-xml -y; fi
```

Install php-sdk, and create a sample php test file with the above source code and execute in cloudshell.

**Expected behavior**
The code should run successfully in Cloudshell as per the Python3-boto3 example

**Additional context**
CloudShell environment

**Comment by kuettai** [comment]
Pull requested created.
https://github.com/aws/aws-sdk-php/pull/2324

**Comment by stobrien89** [comment]
Hi @kuettai,

Thanks for raising this and opening a PR to address it. Sorry for the delayed response. I requested some changes in the PR, but I think it would be great if we could get this merged.

**Comment by stobrien89** [comment]
PR has been merged and changes will be available in tomorrow's release.  Please let us know if you're still having issues!
