### ISSUE TITLE
Feature was deprecated in doctrine/dbal 2.x and is not supported by installed doctrine/dbal:3.x

### ISSUE THREAD

**Issue by sylvainfloride** [aws/aws-sdk-php#2338]
**Describe the bug**
Failed to generate ConfigBuilder for extension Aws\Symfony\DependencyInjection\AwsExtension.

**Version of AWS SDK for PHP?**
v3.198.6

**Version of PHP (`php -v`)?**
PHP 7.4.19

**To Reproduce (observed behavior)**
composer install or composer update

**Screenshots**
 [KO]
Script cache:clear returned with error code 1
!!
!!   // Clearing the cache for the dev environment with debug true
!!
!!  07:45:19 WARNING   [app] Failed to generate ConfigBuilder for extension Aws\Symfony\DependencyInjection\AwsExtension. ["exception" => LogicException { …},"extensionClass" => "Aws\Symfony\DependencyInjection\AwsExtension"]
!!
!!  In NotSupported.php line 16:
!!                                                                                                                                                                                
!!    Feature was deprecated in doctrine/dbal 2.x and is not supported by installed doctrine/dbal:3.x, please see the doctrine/deprecations logs for new alternative approaches.  
!!                                                                                                                                                                                
!!
!!  cache:clear [--no-warmup] [--no-optional-warmers]
!!
!!
Script @auto-scripts was called via post-update-cmd

**Additional context**
Framework : Symfony 5.3.9

**Comment by stobrien89** [comment]
Hi @sylvainfloride,

Closing this for now, but let us know if this is still an issue!
