### ISSUE TITLE
Memory Leak w/ Failed Permission

### ISSUE THREAD

**Issue by markgroove3** [aws/aws-sdk-php#2339]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
If you are using invalid Key/Secret for a bucket to which you are attempting upload - the S3 Client->uploadFile() fills available memory to limit, never allowing for 'permission denied' to be returned.  'Permission denied' ascertained by utilizing StreamWrapper instead, which works correctly.  

**Version of AWS SDK for PHP?**
3.199.0

**Version of PHP (`php -v`)?**
PHP 8.0.12

**To Reproduce (observed behavior)**
Attempt any upload w/ a valid key/secret that does not have access to the bucket you are uploading to

**Expected behavior**
Fatal error: Allowed memory size of XXXXXXXXX bytes exhausted (tried to allocate XXXXXXXXX bytes)

**Screenshots**
It would just be a picture of that error.

**Additional context**
No frameworks used.  Direct AWS SDK usage.

**Comment by stobrien89** [comment]
Hi @markgroove3,

Closing this for now, but more than happy to re-visit if this is still an issue.  Sorry for the delay!
