### ISSUE TITLE
ParserException in Api/DateTimeResult with float timestamp

### ISSUE THREAD

**Issue by gtux** [aws/aws-sdk-php#2346]
After update my composer the SDK begin to fail for any call to any service. The root of those exceptions is when Api/JsonParser tries to parse a timestamp from a TimestampShape. 

Example: v3.199.6

**Version of PHP (`php -v`)?**
PHP 7.3.29

**To Reproduce (observed behavior)**
Call any service with after this php setting:

```php
setlocale(LC_ALL, 'es_PE.UTF-8');
```

**Expected behavior**
The response of that service

**Screenshots**
None

**Additional context**
The problem is with the code added since 3.199.6:

```php

// Api/DateTimeResult lines 36:40

        $dateTime = DateTime::createFromFormat('U.u', sprintf('%0.6f', $unixTimestamp), new DateTimeZone('UTC'));

        if (false === $dateTime) {
            throw new ParserException('Invalid timestamp value passed to DateTimeResult::fromEpoch');
        }

```

Example:

```php
$unixTimestamp = 1617751251,098;
# sprintf('%0.6f', $unixTimestamp) => "1617751251,098000"
DateTime::createFromFormat('U.u', sprintf('%0.6f', $unixTimestamp), new DateTimeZone('UTC')) === false
```

My locale and date.timezone it's setted to Peru, so the internal value of $unixTimestamp (that it is a float) do have a comma, so sprintf will maintain the comma, and the static method createFromFormat will fail to false; and do throw the ParserException.

All this code could be tested in any plain php with other locale than US.

**Comment by SamRemis** [comment]
@gtux Thanks for bringing this to our attention; I'm a bit confused as to how you got this problem to begin with.  It's my understanding that PHP parsers will only accept a `.` as a valid input for a float ([source](https://php.watch/versions/8.0/float-to-string-locale-independent)).  I even found an [RFC to change that](https://wiki.php.net/rfc/locale_independent_float_to_string) in the PHP website, which further supports my understanding of this behavior.

Even after setting the locale and double checking that it was set properly, I still get `PHP Parse error:  syntax error, unexpected ','` when running the code sample.  Do you have any sort of library installed that overrides this behavior?  It's also possible I'm missing some sort of default poorly-documented behavior or something else entirely.  As of right now, I can't reproduce this, so I can't make a PR to fix it.  

Which service are you calling?  And from what OS?

**Comment by thomasdv** [comment]
Same problem here after SSM sendCommand.

Version: v3.200.0
PHP version: 7.4.25

Response data from sendCommand:
```
...
'ExpiresAfter' => 1636115537.312
'RequestedDateTime' => 1636108337.312
...
```

Results in:
```
Aws\Api\Parser\Exception\ParserException
Invalid timestamp value passed to DateTimeResult::fromTimestamp
```

Arguments:
```
$timestamp: 1636115537.312
$expectedFormat: null
```

**Comment by SamRemis** [comment]
@thomasdv, that's strange; do you have a different locale as well?  When I passed the timestamp in to fromTimestamp, it gave me `2021-11-05 12:32:17.312000`.   The other date gave me `2021-11-05T10:32:17+00:00`.  Do you have any additional instructions so I can reproduce your issue?

**Comment by gtux** [comment]
Hi @SamRemis for your replay

  Respect from my OS, I'm using Amazon Linux 2, PHP 7.3.27, Nginx 1.18.0.

  The RFC that you mention it's for PHP 8.0, that means in previous versions it does not work, so in my current version the float number it's changed to use comma in place to point. 

  I have a system that use AWS SDK PHP from years ago, and suddenly after an update to 3.199.1 it fails in every call. I took the work to go back version by version in order to find the right. The 3.199.5 is the correct.

**Comment by SamRemis** [comment]
@gtux Exactly, the RFC says that a comma can't be used as a float separator yet, so I'm wondering how you're doing it.  Whenever I tried to set my locale or do anything else, I still always got the parser exception.

**Comment by SamRemis** [comment]
As far as I can tell, there's no way to make this line parse:
`$unixTimestamp = 1617751251,098;`
at least without a library or something

**Comment by gtux** [comment]
@SamRemis 

That's just the issue, I don't do anything! simply call any method for any client service and it's fails. Fails at evaluate the response from AWS.

As I said, just update the package from composer and my system begun to fail

**Comment by SamRemis** [comment]
I get that you didn't _change_ anything, I'm trying to ask if there were any initial configurations you did with your PHP or your system to get it to accept the comma as valid formatting for a float.

**Comment by gtux** [comment]
@SamRemis 

Yes, one of the first commands in my system is:

```php
setlocale(LC_ALL, 'es_PE.UTF-8');
```

When I do comment that line, everything back to work as always, uncomment that line, and everything fails again

**Comment by thomasdv** [comment]
Hi @SamRemis,

found the issue. I am using Europe/Prague locale and we also use commas as decimal delimiter.

What broke it was commit #2337. 

`DateTime::createFromFormat('U.u', sprintf('%0.6f', $unixTimestamp), new DateTimeZone('UTC'));` returns false.

Because `sprintf('%0.6f', 1636115537.312)` will cause `$unixTimestamp` to be converted to string "1636115537,312000" and such a string cannot be converted to DateTime.

**Comment by SamRemis** [comment]
@thomasdv @gtux Thank you for your patience, and sorry for the confusion.  It seems like my parser is playing tricks on me; it wouldn't allow me to call  `$unixTimestamp = 1617751251,098;`, but when I call ` $unixTimestamp = 1617751251.098;` after setting the locale, it appears the value is properly being set to  `1617751251,098`.  

Now that I'm able to reproduce it, I'll treat this as a high severity issue and get a fix out ASAP.

**Comment by gtux** [comment]
@SamRemis 

Thanks to you

**Comment by SamRemis** [comment]
@gtux I'm going to try to get #2347 out in today's release, as long as I can test it sufficiently by then.  Please keep a close eye on how it may change behavior.  I can't think of any strange ways this may impact anyone, but when it comes to things like timestamps, weird behaviors can sometimes arise in PHP

**Comment by gtux** [comment]
@SamRemis yeah! of course! I'll be watching it!

**Comment by SamRemis** [comment]
@gtux, would you be willing to try the latest version and see if it's fixed so I can be confident that it's working in production?  It should have been live since Friday

**Comment by thomasdv** [comment]
@SamRemis I have already updated and the fix is working great for me.

**Comment by SamRemis** [comment]
@thomasdv Thank you so much :)
