### ISSUE TITLE
Uncaught Error: Class 'GuzzleHttpHandlerHeaderProcessor' not found in <path>/vendor/guzzlehttp/guzzle/src/Handler/EasyHandle.php:211

### ISSUE THREAD

**Issue by RaviJayagopal** [aws/aws-sdk-php#2364]
Error shown in server logs:

Uncaught Error: Class 'GuzzleHttpHandlerHeaderProcessor' not found in <path>/vendor/guzzlehttp/guzzle/src/Handler/EasyHandle.php:211

Fails at line shown below:

$s3Client = new Aws\S3\S3MultiRegionClient([
                    'version'     => 'latest',
                    'region'      => 'us-east-1',
                    'credentials' => [
                        'key'    => $accessKey,
                        'secret' => $secretKey,
                    ],
                ]);

$region = $s3Client->determineBucketRegion($bucketname); //<---------fails here

**Comment by SamRemis** [comment]
@RaviJayagopal That seems to be an issue with one of our consumed library; there are no references to the class 'GuzzleHttpHandlerHeaderProcessor' within the SDK.  If you installed via composer, could you run a composer update and see if that fixes it?  And if you didn't, could you tell me how you installed?

**Comment by RaviJayagopal** [comment]
@SamRemis, thank you for your response. 

I originally updated my existing sdk via composer update. Got the above error. 

Then I tried to manually unzip and overwrite the aws php sdk library. That didn't resolve it either.

SDK Version 3.208.5
PHP: 7.4.26

**Comment by SamRemis** [comment]
@RaviJayagopal, you don't have to worry about aws-crt-php; it's an opt-in C library that does a few specific things for us.  It's not packaged by default with the SDK for a few reasons.  Either way, the CRT doesn't call Guzzle, so that's not where the issue lies.  
To me this sounds like it's more likely an issue with how you've configured your install, and not with the SDK itself.  I suggest removing the SDK install, then re-installing it and updating again via composer.  Before and after you do that, run  `composer show guzzlehttp/guzzle` and check if the version number changes.

After you do that, if it still doesn't work, please let me know which version of guzzlehttp/guzzle you are using

**Comment by RaviJayagopal** [comment]
@SamRemis , composer version 7.4.1. Will try the remove and re-install via composer now.

composer show guzzlehttp/guzzle
name     : guzzlehttp/guzzle
descrip. : Guzzle is a PHP HTTP client library
keywords : client, curl, framework, http, http client, psr-18, psr-7, rest, web                                                                                                                                                                                                                                              service
versions : * 7.4.1
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#l                                                                                                                                                                                                                                             icenseText
homepage :
source   : [git] https://github.com/guzzle/guzzle.git ee0a041b1760e6a53d2a39c8c3                                                                                                                                                                                                                                             4115adc2af2c79
dist     : [zip] https://api.github.com/repos/guzzle/guzzle/zipball/ee0a041b1760                                                                                                                                                                                                                                             e6a53d2a39c8c34115adc2af2c79 ee0a041b1760e6a53d2a39c8c34115adc2af2c79
path     : /home/customer/www/techiiies.com/public_html/wp-content/plugins/S3Med                                                                                                                                                                                                                                             iaVaultPro/vendor/guzzlehttp/guzzle
names    : guzzlehttp/guzzle, psr/http-client-implementation

support
issues : https://github.com/guzzle/guzzle/issues
source : https://github.com/guzzle/guzzle/tree/7.4.1

autoload
psr-4
GuzzleHttp\ => src/
files

requires
ext-json *
guzzlehttp/promises ^1.5
guzzlehttp/psr7 ^1.8.3 || ^2.1
php ^7.2.5 || ^8.0
psr/http-client ^1.0
symfony/deprecation-contracts ^2.2 || ^3.0

requires (dev)
bamarni/composer-bin-plugin ^1.4.1
ext-curl *
php-http/client-integration-tests ^3.0
phpunit/phpunit ^8.5.5 || ^9.3.5
psr/log ^1.1 || ^2.0 || ^3.0

suggests
ext-curl Required for CURL handler support
ext-intl Required for Internationalized Domain Name (IDN) support
psr/log Required for using the Log middleware

provides
psr/http-client-implementation 1.0

**Comment by RaviJayagopal** [comment]
Did a composer remove, deleted the vendor/aws/aws-php-sdk folder, did a composer update.

composer update
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing aws/aws-sdk-php (3.208.6): Extracting archive
Generating autoload files
5 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Still same error:
Uncaught Error: Class 'GuzzleHttpHandlerHeaderProcessor' not found in /home/customer/www/techiiies.com/public_html/wp-content/plugins/S3MediaVaultPro/vendor/guzzlehttp/guzzle/src/Handler/EasyHandle.php:211

**Comment by RaviJayagopal** [comment]
Issue resolved. Turns out to be a FTP related issue when downloading the composer updates via FTP to local machine and then uploading to another server. Thanks for your help @SamRemis!
