### ISSUE TITLE
AWS Pinpoint VerifyOtpMessage method missing

### ISSUE THREAD

**Issue by miradnan** [aws/aws-sdk-php#2366]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
The Pinpoint client contains method sendOtpMessage to send OTP message, but no methods to verify OTP. The method verifyOtpMessage is missing from the client.

**Version of AWS SDK for PHP?**
v3.208

**Version of PHP 8

Client documentation url: https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Pinpoint.PinpointClient.html

**Comment by ajredniwja** [comment]
Hi @miradnan thanks for bringing this up, I doubt if it is not mentioned in the docs. As I see here: https://github.com/aws/aws-sdk-php/blob/59d4d6a58ed7da541aa0ed75cc1944f8d6ca2d1c/src/data/pinpoint/2016-12-01/api-2.json#L12680

Can you try invoking the method with the required parameters?

**Comment by ajredniwja** [comment]
Seems like the client doesnt have the required method which should usually be added if it is modeled. Will look more into this.

**Comment by miradnan** [comment]
thanks @ajredniwja

**Comment by ajredniwja** [comment]
@miradnan turns out to be a problem with our models, in contact with the team to work on a fix.

**Comment by ajredniwja** [comment]
This should have been fixed with today’s release, @miradnan please reach out if its still an issue in the latest version.
