### ISSUE TITLE
Possibility cleaning up unused services

### ISSUE THREAD

**Issue by ojooss** [aws/aws-sdk-php#2369]
It would be nice to have a composer task for cleanup unused serives (e.g. like Google provides https://github.com/googleapis/google-api-php-client#cleaning-up-unused-services)
My vendors directory exploded after installing aws-sdk-php :-(

**Comment by SamRemis** [comment]
Hi there,
This is a separate but similar feature request to one of our oldest requests https://github.com/aws/aws-sdk-php/issues/808.  That is likely (though not definitely) going to be implemented in the next major version.  If it is, this won't be necessary.

I'll leave this open for now and talk to the team about if this is feasible to do in this major version

**Comment by GrahamCampbell** [comment]
In the meanwhile, is a good https://github.com/async-aws/ third party alternative SDK.

**Comment by stobrien89** [comment]
Hi @ojooss,

Thanks again for the feature request.  This has been implemented in https://github.com/aws/aws-sdk-php/pull/2456!
