### ISSUE TITLE
Can not get shadow document data

### ISSUE THREAD

**Issue by monicse09ku** [aws/aws-sdk-php#2370]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
v3.209.10

**Version of PHP (`php -v`)?**
7.3.8

**Describe the question**
I am using AWS SDK for IotDataPlaneClient, I have successfully created the client. I have also successfully retrieved the list of shadows using **ListNamedShadowsForThing** as well as updated the shadow document using **updateThingShadow**. But I am failing to get the state saved in the Shadow Document. I have used following code

    use Aws\Sqs\SqsClient;
    use Aws\Exception\AwsException;

    $thing_name = "MY_THING_NAME";
    $shadow_name = "MY_SHADOW_NAME";
    $public_key = "MY_PUBLIC_KEY";
    $private_key = "MY_PRIVATE_KEY";
 
    $client = new Aws\IotDataPlane\IotDataPlaneClient([
        'endpoint' => 'MY_ENDPOINT',
        'version' => 'latest',
        'region'  => 'eu-central-1',
        //'tls'  => false,
        'credentials' => [
            'key'    => $public_key,
            'secret' => $private_key,
        ],
    ]);

    try{
        $result1 = $client->getThingShadow([
            'thingName' => $thing_name,
            'shadowName' => $shadow_name,
        ]);

        print "<pre>"; 
        print_r($result);
    } catch(Exception $e) {
        echo 'Message: ' .$e->getMessage();
    }

I am getting only **payload** and **@metadata** in the result, but not the state in my document. I have tried a lot of things but can not find anything.

    What I am doing wrong?

**Comment by stobrien89** [comment]
Hi @monicse09ku,

Sorry to hear you're having issues.  It doesn't appear you're doing anything wrong— the [API docs](https://docs.aws.amazon.com/iot/latest/apireference/API_iotdata_GetThingShadow.html#API_iotdata_GetThingShadow_ResponseSyntax) say the response body only will only contain the payload, but it appears state information should be included.  Are you seeing any state information? or is this the metadata you're referring to?

**Comment by monicse09ku** [comment]
Dear @stobrien89, thanks for response. I am receiving both **payload** and **metadata** but in my payload, I am expecting the state which is missing. I have created the shadow document naming **test_shadow** with following data

    {
         "state": {
            "desired": {
                "AM..4:1-2": "0148003C",
                "AM..4:2-2": "023C068B",
                "AM..4:3-2": "028B0664",
                "AM..4:4-2": "02640047",
                "AM..4:5-2": "032700E7",
                "AM..4:6-2": "00E70294"
            }
        }
    }
Following is my response
![image](https://user-images.githubusercontent.com/11867107/152025691-db7d9c98-b390-4a1f-b056-a5bbb69cd664.png)

**Comment by stobrien89** [comment]
Hi @monicse09ku,

Thanks for the additional information. I'd test this myself, but I do not currently have any test devices/things that I can register.  It appears you may need to deserialize the payload, similar to [this issue](https://github.com/aws/aws-sdk-cpp/issues/1028) from the C++ SDK repository.  Let me know if that helps!

**Comment by monicse09ku** [comment]
Dear @stobrien89, it worked just by using **json_decode**. Thank you so so much.

**Comment by stobrien89** [comment]
Glad to hear it worked!  Closing for now, but let us know if you need anything else.
