### ISSUE TITLE
Lightsail: API does not return IPv6 address(s)

### ISSUE THREAD

**Issue by elindydotcom** [aws/aws-sdk-php#2373]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
The Lightsail PHP api docs indicate that the API should return the IPv6 address(es) in an 'ipv6Addresses' array element.  But it does not.

[AWS PHP API Documentation we're using.](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-lightsail-2016-11-28.html#getinstance)

**Version of AWS SDK for PHP?**
v3.209.15

**Version of PHP (`php -v`)?**
7.4.27

**To Reproduce (observed behavior)**
Call the getInstance method on an instance of the LightSail client and examine the array output.  

**Expected behavior**
The 'ipv6Addresses' array element should be present in the returned array but it's missing.

**Comment by SamRemis** [comment]
Hi @elindydotcom,
Thanks for the issue; can you post the code you're using?  I find it odd that it's missing, we don't have any customizations on that client, so nothing seems to be going wrong on our end.  The service may not be returning it for one reason or another, but when I did a print_r on the result, I got the ipv6Addresses returned without issue.  It was between `publicIpAddress` and `ipAddressType`
Can you look at [this documentation](https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-enable-disable-ipv6#disable-ipv6) and double check that ipv6 is enabled on your instance as well?

**Comment by elindydotcom** [comment]
Well, I'll be. 

I was just preparing sample code to add to this ticket as requested and IPv6 addresses started to show up.  

I know it's not my imagination because I still have the dumps from yesterday's debugging session and the elements are not there.

In addition to that, there are a couple of additional elements that are showing up now as well.

Maybe it was a temporary glitch?  

I guess I'll close this issue out.  Sorry for the bother.

(If you'd like to see the output from yesterday vs today let me know and I'll add to this issue).

**Comment by stobrien89** [comment]
Thanks for the update @elindydotcom, glad to hear it's working now.  It's possible the Lightsail team was working on that component of the API yesterday and temporarily disabled the feature.  Let us know if you need anything else!
