### ISSUE TITLE
Amazon Connect method describeContact not worked 

### ISSUE THREAD

**Issue by eugeneletuchy** [aws/aws-sdk-php#2374]
This is method not worked https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-connect-2017-08-08.html#describecontact 

Error:
<b>Fatal error</b>:  Uncaught InvalidArgumentException: Operation not found: DescribeContact in /var/www/aws/vendor/aws/aws-sdk-php/src/AwsClient.php:260
Stack trace:
#0 /var/www/aws/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(86): Aws\AwsClient-&gt;getCommand('DescribeContact', Array)
#1 /var/www/html/aws/connect/index_status.php(24): Aws\AwsClient-&gt;__call('describeContact', Array)
#2 {main}
  thrown in <b>/var/www/aws/vendor/aws/aws-sdk-php/src/AwsClient.php</b> on line <b>260</b><br />

Do you have any ideas?

**Comment by stobrien89** [comment]
Hi @eugeneletuchy,

Sorry to hear you're having issues.  It's possible the operation may not be available in the version you're using— this operation was added to the `connect` models on 11/12/2021, meaning it is only available in >= `3.202.2`.  If this not an issue with versioning, please provide a code example.  Thanks!

**Comment by eugeneletuchy** [comment]
O, thanks. I will update the version.

**Comment by stobrien89** [comment]
I'll close this for now, but let us know if that doesn't work!
