### ISSUE TITLE
Decoding ION values

### ISSUE THREAD

**Issue by nicolas255** [aws/aws-sdk-php#2380]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers

**Version of AWS SDK for PHP?**
3.209.23

**Version of PHP (`php -v`)?**
8.0.12

**Describe the question**
We are currently trying to implement a service that interacts with QLDB and, while we are nearly done, we still haven't found a solution to decode or make any use of the returned ION values from QLDB. Are we at a dead end or is there any way to handle these at this time?

**Comment by SamRemis** [comment]
Hi @nicolas255,
Just got to check in on this, and we as SDKs don't natively support ION.  It's a topic of discussion, but work hasn't been started on it yet.  The ION team has a few tools they've distributed to decode ION at the bottom of [this page](https://amzn.github.io/ion-docs/), but none of them are in PHP.
Sorry this doesn't exist yet, it definitely should.  I'll mark this as a feature request and do some more prodding to see if we can get started on it.

**Comment by nicolas255** [comment]
Thank you for your response !

In the meantime, we've found this PHP extension : https://github.com/awesomized/ext-ion. It's not perfect but it'll do for our use case for now.
