### ISSUE TITLE
SignatureDoesNotMatch with presigned URL

### ISSUE THREAD

**Issue by AnzeR** [aws/aws-sdk-php#239]
I have the following code

```
$client = S3Client::factory(array('region' => 'eu-west-1','key' => 'xxx','secret' => 'xxx',));

$command = $client->getCommand('PutObject', array(
    'Bucket' => 'myBucket',
    'Key' => 'testing/signed_'.time(),
    'ContentType' => 'image/jpeg',
    'Body' => 'dump' //it's mandatory, it's not needed here
));
$signedUrl = $command->createPresignedUrl('+5 minutes');
$signedUrl .= '&Content-Type=image%2Fjpeg';
echo("\n\nThe URL is: ". $signedUrl . "\n");
echo("Now run from console for upload:\ncurl -v -H \"Content-Type: image/jpeg\" -T /tmp/temp.jpg '" . $signedUrl . "'");
```

When trying to use curl command I'm getting and error _SignatureDoesNotMatch_ with message _The request signature we calculated does not match the signature you provided. Check your key and signing method._

The similar code in aws-sdk for Javascript is working, so I thing there is an issue in aws-sdk-php.

Please help me. It's urgent :+1:

**Comment by ihorbovkit** [comment]
Hi have next error  - 

```bash
Fatal error: Call to undefined method Aws\Command::createPresignedUrl()
```
with this code - 

```bash
$s3Creds = array('key' => AWS_KEY, 'secret' => AWS_SECRET, 'region' => 'ap-northeast-1');
$s3 = S3Client::factory($s3Creds);

//$photo->hashId is a 8 character alpha numeric string
$command = $s3->getCommand('PutObject', array(
    'Bucket'      => S3_BUCKET_NAME,
    'Key'         => $photo->hashId . '/raw.jpg',
    'ContentType' => 'image/jpeg',
    'Body'        => ''
));
$signedUrl = $command->createPresignedUrl('+50 minutes');
echo urldecode($signedUrl);
```

I'm using AWS SDK S3 - Release v2.1.39

**Comment by shooding** [comment]
@ihorbovkit 
You will have to call createPresignedRequest in AWS SDK for PHP 3.x
Are you sure it's really v2.1.39 (which is SDK for Javascript)?

**Comment by ihorbovkit** [comment]
@shooding 
Using s3.0.0 v3 - I did the following to get this to work.
$command = $s3->getCommand('GetObject', array(
            'Bucket'      => $this->customerBucket,
            'Key'         => $fileName,
            'ContentType' => 'image/png',
            'ResponseContentDisposition' => 'attachment; filename="'.$fileName.'"'
        ));
$signedUrl = $s3->createPresignedRequest($command, "+1 week");

**Comment by nxmohamad** [comment]
In case someone else is looking at this, for some reason the setup was not complete, I got a similar SignatureDoesNotMatchError when my s3 bucket's CORS Configuration did not contain `    <AllowedHeader>*</AllowedHeader>`

**Comment by renschler** [comment]
Struggled with this for a while, was getting the same Signature Does Not Match Error.

The change that fixed my issue was going from

`fetch(presignedURL, { method: "PUT", body: svg })`

to 

`fetch(presignedURL, { method: "PUT", body: new Blob([svg], {type: file.type})})`

where svg was a variable storing the result of an uploaded svg file.

```
let reader = new FileReader();
reader.onload = (e) => {
	let svg = atob(e.target.result.split(/[,;]/).pop()); // decode svg file from base64
        
        // perform fetch
}
```

**Comment by evan-10e** [comment]
I solved this by adding `'Content-Type: text/plain'` to my curl command

eg:  `curl -H 'Content-Type: text/plain' -X PUT -T fgl-template.txt <upload url>`

**Comment by Huandv** [comment]
@mtdowling
Could you help me ?
I got a similar SignatureDoesNotMatchError
- aws php sdk version 3.209.4
- php 8.1
```
$command = $this->client->getCommand('PutObject', [
    'Bucket' => $this->bucket,
    'Key' => $key,
]);
$request = $this->client->createPresignedRequest($command, '+20 minutes');
$presignedUrl = (string)$request->getUri();
```
