### ISSUE TITLE
AWS S3 putObject() vs upload() multipart upload

### ISSUE THREAD

**Issue by adrianbecker013** [aws/aws-sdk-php#2409]
Could you please help us to clear the following points for these putObject() or upload() multipart upload options?

1) What is the cost difference between putObject() or upload() multipart upload?
2) In which case we should go with upload() multipart upload?
3) Our file size is 50MB or less than 50MB  -> Should we go with putObject() or upload() multipart upload?
4) How we can know that file is uploaded successfully using putObject() in S3 bucket
```
try {
    $this->storage->putObject(array(
        'Bucket'    => 'temp',
        'Key'       => 'temp/file.csv.gpg',
        'Body'      => fopen('temp/file.csv.gpg', 'r'),
        'CacheControl' => 'max-age=31536000',
    ));
} catch (\Aws\S3\Exception\S3Exception $e) {
    return $e;
}
```
5) How we can know that file is uploaded successfully using upload() multipart upload in S3 bucket?

Thanks in advance!

**Comment by yenfryherrerafeliz** [comment]
Hello @adrianbecker013, I hope you are doing well.

In regards with your questions here are the answers:

1.	**What is the cost difference between putObject() or upload() multipart upload?**
	If by cost difference you mean which operation will take longer; from my understanding this has to be measured based on the data being load rather the method being used.
2.	**In which case we should go with upload() multipart upload?**
	According with the documentation it is recommended that when your objects size reaches 100 MB, you should consider using multipart uploads instead of uploading the object in a single operation. However, you should know that putObject operation handle files up to 5 GB in size, while multipart uploads, handle files that comes from 5 MB to 5 TB in size. 
	I also found in the documentation that if you are not sure about whether to use single upload “PutObject” or multipart uploads, you can use ObjectUploader, which based on the payload size will chose the best operation to use (PutObject or MultipartUploader).
3.	**Our file size is 50MB or less than 50MB -> Should we go with putObject() or upload() multipart upload?**
	Probably PutObject would be your best option since with PutObject operation you can upload files up to 5 GB in size. However, is your decision to pick one or another. 
4.	**How we can know that file is uploaded successfully using putObject() in S3 bucket?**
	You have different options to validate this, and the first one is assuming that you are allocating the response into a variable called $result, you can use the following condition “$result[‘@metadata’][‘statusCode’] == 200”, and another option is to validate that the object exists in the bucket after the upload operation. You can accomplish this by calling the doesObjectExists method, which is a member of the S3Client class “maybe inherited”. Ex: $s3Client->doesObjectExist($bucket, $key);  
	Note: this answer also cover question 5.
I also encourage you to take a look to the documentation which contains great information about those operations. The documentation can be found [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html).

If you have any questions, please just let me know.

Thank you!

**Comment by yenfryherrerafeliz** [comment]
Hi @adrianbecker013 , I hope you are doing well today. 

You are more than welcome.

Unfortunately, we do not support both the SDK and PHP version that you are using. However, from my personal opinion I can tell you that if something fails during the upload process it should generate an exception, which you could catch. You also have the last option I mentioned to you, which is to validate that the object uploaded exists, after your upload process, but again this is just my personal advice.

Thank you!
