### ISSUE TITLE
Type Error while using http.debug with a bool value: rewind(): Argument #1 ($stream) must be of type resource, bool given

### ISSUE THREAD

**Issue by Dgame** [aws/aws-sdk-php#2412]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-php-sdk) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-php/issues) and didn't find any solution
  
**Describe the bug**
If I'm using the `http.debug` option with the value `true` like this:
```php
$sdk->createFirehose(
    [
        'http' => [
            'debug' => true
        ]
    ]
);
```

I get the error:
> rewind(): Argument #1 ($stream) must be of type resource, bool given

**Version of AWS SDK for PHP?**
AWS SDK is 3.218.0 and PHP is 8.1.4

**To Reproduce (observed behavior)**
I used to send the request with the `http.debug = true` to Firehose

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/2406877/161287359-96eae8df-1e24-4eb6-a12c-47c1fb1a0aa2.png)

**Comment by SamRemis** [comment]
Hi there @Dgame,

Here's the code I used to try to reproduce the issue:
```
$sdk = new \Aws\Sdk();
$firehose = $sdk->createFirehose(
    [
        'region' =>'us-east-1',
        'version' =>'latest',
        'http' => [
            'debug' => true
        ]
    ]
);
$firehose->listDeliveryStreams();
```
Not sure how you got to that codepath; it should only go into `TraceMiddleware` if you set it like so without the `'http'` surrounding debug:
```
$firehose = $sdk->createFirehose(
    [
        'region' =>'us-east-1',
        'version' =>'latest',
         'debug' => true
    ]
);
```
Putting `'debug'` inside the `'http'` parameter means it is going to use guzzle's debug and skip the SDK's debugging and therefore skip `TraceMiddleware`.   As your debug is showing symfony, I even tried doing the same thing in a symfony project, but was unable to reproduce the error.  

Could you please give us more reproduction instructions or fill in any missing config options your setting?

**Comment by Dgame** [comment]
>  As your debug is showing symfony, I even tried doing the same thing in a symfony project, but was unable to reproduce the error.

I'm using Lumen (Laravel Micro-Framework). We were using the global debug option as well as the http debug option:
```php
$sdk = new \Aws\Sdk(
    [
        'credentials' => [
            'key'    => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
        ],
        'region'      => env('AWS_REGION', default: 'eu-central-1'),
        'version'     => 'latest',
        'endpoint'    => env('AWS_ENDPOINT'), // was null; only for local work with e.g. localstack
        'debug'       => env('AWS_DEBUG', default: false) // was set to true
        ]
]);
$firehose = $sdk->createFirehose(
    [
        'http' => [
            'debug' => true
        ]
    ]
);
$firehose->putRecord($data);
```

**Comment by stobrien89** [comment]
Hi @Dgame,

Is there a reason you're using both the global and the http debug option? I wouldn't recommend using both in most cases. The global debug option should provide the lower level (`http`) debug output as well. 

If by chance you wanted to write the lower level http debug output to a separate location, you could pass a resource to the http option instead: 

```
$resource = Psr7\Utils::tryFopen('test.dat', 'w');

$client = new SomeClient([
    'http' => [
        'debug' => $resource
    ],
])
```

**Comment by Dgame** [comment]
> Hi @Dgame,
> 
> Is there a reason you're using both the global and the http debug option? I wouldn't recommend using both in most cases. The global debug option should provide the lower level (`http`) debug output as well.

I didn't know that at the time, so I just wanted to make sure. 🙂  

> If by chance you wanted to write the lower level http debug output to a separate location, you could pass a resource to the http option instead:
> 
> ```
> $resource = Psr7\Utils::tryFopen('test.dat', 'w');
> 
> $client = new SomeClient([
>     'http' => [
>         'debug' => $resource
>     ],
> ])
> ```

Yes, I learned that the hard way and had to debug for a few hours until I figured that out. If only resources are allowed, it should be an error if something that is not a resource is defined there. Or only if it is a resource, it should be closed with fclose.

**Comment by stobrien89** [comment]
Sorry you had to spend so much time to figure it out— I think it would be worth documenting that the global debug option is essentially an extension of the `http` (Guzzle) debug configuration option and it is not recommended to use both simultaneously unless redirecting the guzzle debug output to another location.  Although in that case (both debug options being used), the resource will be closed automatically by `flushHttpDebug`.

**Comment by Dgame** [comment]
> Sorry you had to spend so much time to figure it out— I think it would be worth documenting that the global debug option is essentially an extension of the `http` (Guzzle) debug configuration option and it is not recommended to use both simultaneously unless redirecting the guzzle debug output to another location. Although in that case (both debug options being used), the resource will be closed by `flushHttpDebug`.

No problem as long as it will be fixed. How about a check / early return in `flushHttpDebug` like `if (!is_resource($res)) { return; }` to make sure it can`t happen?

**Comment by stobrien89** [comment]
I think that's a good idea. We'd be open to accepting a change like that if you want to submit a PR.

**Comment by Dgame** [comment]
> I think that's a good idea. We'd be open to accepting a change like that if you want to submit a PR.

Did that by using the Github UI. Hope that's fine.
