### ISSUE TITLE
'Rotate' and "CannedACL" options do not come through in Elemental MediaConvert

### ISSUE THREAD

**Issue by WarrenHullStunts** [aws/aws-sdk-php#2415]
### Describe the bug

Passing a mediaConvert job with the sdk drops the "Rotate" option in the Inputs->VideoSelector array. No error is thrown, but the job does not contain the Rotate parameter. If I duplicate the job in the AWS Console, I can add the Rotate parameter and the job JSON shows the rotate parameter exactly where it should be. It is listed as in the same level in the array as "ColorSpace", so I added ColorSpace to my job and that shows up, but "Rotate" does not.

Also the "OutputGroupSettings" -> "DestinationSettings" -> "S3Settings" -> "AccessControl" -> "CannedACL" is not coming through. I have not tested how high up the tree these options are not coming through, but "CannedACL" is not in the Job JSON accessible after the job completes even though it was passed in.

### Expected Behavior

Passing in: 
`
            "VideoSelector" => [
                "Rotate" => "AUTO"
            ],`
inside of the inputs parameter in a createJob call for MediaConvert would create a job that would have a "Rotate" parameter in its settings json.

Passing in: 
`"FileGroupSettings"=> [
        'DestinationSettings' => [
              'S3Settings' => [
                  'AccessControl' => [
                      'CannedAcl' => 'PUBLIC_READ',
                  ],
              ]
          ]
]`
inside of the output group settings parameter in a createJob call for MediaConvert would create a job that would have a "CannedACL" parameter in its settings json.

### Current Behavior

No logged errors or warnings occur. 

A job created with the "Rotate" parameter passed in does not contain the "Rotate" parameter in the console.
A job created with the "CannedACL" parameter passed in does not contain the "CannedACL" parameter in the console.

### Reproduction Steps

```

use Aws\MediaConvert\MediaConvertClient;

$transcoderClient = new MediaConvertClient([
	'version' => "latest",
	'region' => "us-east-1",
	'credentials' => [
		'key' => $S3_PUBLIC_KEY,
		'secret' => $S3_SECRET_KEY
	],
	'endpoint' => $AWS_MEDIACONVERT_ENDPOINT
]);

$outputGroups = array(
	[
		"Name"=> "File Group",
		"OutputGroupSettings"=> [
			"Type"=> "FILE_GROUP_SETTINGS",
			"FileGroupSettings"=> [
				"Destination"=> "s3://nlm-distribute/$projectID/",
				'DestinationSettings' => [
                          'S3Settings' => [
                              'AccessControl' => [
                                  'CannedAcl' => 'PUBLIC_READ',
                              ],
                          ]
                      ]
			]
		],
		"Outputs"=> [
			[
				"ContainerSettings"=> [
					"Container"=> "MP4",
					"Mp4Settings"=> []
				],
				"VideoDescription"=> [
					"Width"=> 854,
					"Height"=> 480,
					"CodecSettings"=> [
						"Codec"=> "H_264",
						"H264Settings"=> [
							"MaxBitrate"=> 4000000,
							"RateControlMode"=> "QVBR",
							"SceneChangeDetect"=> "TRANSITION_DETECTION"
						]
					]
				],
				"AudioDescriptions"=> [
					[
						"CodecSettings"=> [
							"Codec"=> "AAC",
							"AacSettings"=> [
								"Bitrate"=> 96000,
								"CodingMode"=> "CODING_MODE_2_0",
								"SampleRate"=> 48000
							]
						]
					]
				],
				"Extension"=> "mp4",
			],
		]
	]
);

$jobSettings = [
	"OutputGroups"=> $outputGroups,
	"Inputs"=> [
	         [
                       "AudioSelectors"=> [
                              "Audio Selector 1"=> [
                                     "DefaultSelection"=> "DEFAULT"
                              ]
                ],
                "VideoSelector" => [
                         "ColorSpace" => "FOLLOW",
                         "Rotate" => "AUTO"       // This option right here does not come in
                ],
	       "TimecodeSource"=> "ZEROBASED",
	       "FileInput"=> "s3://nlm-transcode/$filename"
	]
],
	"TimecodeConfig"=> [
			"Source"=> "ZEROBASED"
	]
];


$create_job_result = $transcoderClient->createJob([
	      "Role" => $AWS_MEDIACONVERT_ROLE,
	      "Settings" => $jobSettings,
	      "Queue" => $AWS_MEDIACONVERT_QUEUE,
	  ])
```

### SDK version used

3.81.5

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.0.17

**Comment by yenfryherrerafeliz** [comment]
Hi @WarrenHullStunts ,

You’re a few versions shy of what you need.  Rotate was added in [3.87.19](https://github.com/aws/aws-sdk-php/commit/8c9c56ea6cc7b487e15cbc23179abe37a04f6c43) and CannedAcl was added in [3.117.2](https://github.com/aws/aws-sdk-php/commit/19bb64f08bff8b1213ae7e89a64c3a56402153f4).  Please bump your minor version to at least 3.117.2 and that should fix it :slightly_smiling_face:
GitHubGitHub
[Update models for release · aws/aws-sdk-php@8c9c56e](https://github.com/aws/aws-sdk-php/commit/8c9c56ea6cc7b487e15cbc23179abe37a04f6c43)
Official repository of the AWS SDK for PHP (@awsforphp) - Update models for release · aws/aws-sdk-php@8c9c56e (48 kB)
https://github.com/aws/aws-sdk-php/commit/8c9c56ea6cc7b487e15cbc23179abe37a04f6c43[](https://github.com/aws/aws-sdk-php/commit/8c9c56ea6cc7b487e15cbc23179abe37a04f6c43)

[Update models for release · aws/aws-sdk-php@19bb64f](https://github.com/aws/aws-sdk-php/commit/19bb64f08bff8b1213ae7e89a64c3a56402153f4)
Official repository of the AWS SDK for PHP (@awsforphp) - Update models for release · aws/aws-sdk-php@19bb64f (47 kB)

If you have any questions please let me know.

Thank you!

**Comment by WarrenHullStunts** [comment]
Thank you! I really appreciate the help.
