### ISSUE TITLE
Autoloader not working from .zip => Class 'Aws' not found

### ISSUE THREAD

**Issue by nodesocket** [aws/aws-sdk-php#242]
I downloaded the `.zip` of the Amazon SDK and extracted it into `lib/aws` and then doing:

```
require_once(dirname(__DIR__) . "/lib/aws/aws-autoloader.php");
$aws = Aws::factory(array(
    'key'    => getenv('ec2_key'),
    'secret' => getenv('ec2_secret')
));
```

However, I am getting  `Class 'Aws' not found`. It is requiring `aws-autoloader.php`, but does not seem to be requiring the rest.

Any ideas?

**Comment by deepak8484** [comment]
( ! ) Fatal error: Class 'Aws\Sns\SnsClient' not found in E:\wamp\www\sms\mail.php on line 30
--


 what should i do.
