### ISSUE TITLE
Operation not found: GenerateEmbedUrlForAnonymousUser

### ISSUE THREAD

**Issue by rohittb** [aws/aws-sdk-php#2425]
### Describe the bug

we are using aws SDK PHP 3 while calling "GenerateEmbedUrlForAnonymousUser " and "generateEmbedUrlForRegisteredUser" for quick sight showing operations not found error while "getDashboardEmbedUrl" or other methods working fine.

### Expected Behavior

[
    'EmbedUrl' => '<string>',
    'RequestId' => '<string>',
    'Status' => <integer>,
]

### Current Behavior

Operations not found

### Reproduction Steps

$result = $client->generateEmbedUrlForAnonymousUser([
    'AuthorizedResourceArns' => ['<string>', ...], // REQUIRED
    'AwsAccountId' => '<string>', // REQUIRED
    'ExperienceConfiguration' => [ // REQUIRED
        'Dashboard' => [
            'InitialDashboardId' => '<string>', // REQUIRED
        ],
    ],
    'Namespace' => '<string>', // REQUIRED
    'SessionLifetimeInMinutes' => <integer>,
    'SessionTags' => [
        [
            'Key' => '<string>', // REQUIRED
            'Value' => '<string>', // REQUIRED
        ],
        // ...
    ],
]);

### SDK version used

3

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 7.2.24

**Comment by rohittb** [comment]
Hi @yenfryherrerafeliz 

sdk version 3.130.3

the error message is "operation not found"

**Comment by yenfryherrerafeliz** [comment]
Hi @rohittb, thank you for providing this information. Those methods were added in the version 3.186.0, which is a few versions above where you are. You would need to update your SDK version to at least 3.186.0 in order to get this fixed.

Thank you!
