### ISSUE TITLE
S3: file permission mapping to ACL is unexpected

### ISSUE THREAD

**Issue by manarth** [aws/aws-sdk-php#2446]
### Describe the bug

The API determines an ACL based on the file-mode being requested.

```php
    /**
     * Determine the most appropriate ACL based on a file mode.
     *
     * @param int $mode File mode
     *
     * @return string
     */
    private function determineAcl($mode)
    {
        switch (substr(decoct($mode), 0, 1)) {
            case '7': return 'public-read';
            case '6': return 'authenticated-read';
            default: return 'private';
        }
    }
```

File modes are bitwise flags covering "Read" (4), "Write" (2), and "Execute" (1) permissions for owner, group, then everyone.

The above method determines read-access according to the permissions assigned to the file _owner_.

- **0700**
  Linux mode interpretation: file owner can read, write, and execute the file. Group and Public cannot do anything.
  AWS interpretation: file owner can read, group can read, public can read.
- **0600**
  Linux mode interpretation: file owner can read and write the file. Group and Public cannot do anything.
  AWS interpretation: file owner can read, and group can read.
- **0400**
  Linux mode interpretation: file owner can read,. Group and Public cannot do anything.
  AWS interpretation: file owner can read.

### Expected Behavior

ACL is determined by the read-permission of the mode-definition for the relevant component of the mode.

### Current Behavior

ACL is determined by the mode definition of the owner permissions.

### Reproduction Steps

The `determineAcl()` method is private, which prevents a direct reproduction.

`mkdir ('s3://foo/bar', 0700)` can be used as a proxy, when used with a non-public bucket.

The permission `0700` restricts access to the file owner. The AWS API interprets this as a PUBLIC ACL.

### Possible Solution

Use bitwise operations in the `determineAcl()` method, reflecting the read-access of the relevant file-mode.

```php
/**
 * Determine the most appropriate ACL based on a file mode.
 *
 * @param int $mode File mode
 *
 * @return string
 */
function determineAclV2($mode)
{
    $readOwner  = 0400;
    $readGroup  = 0040;
    $readPublic = 0004;

    if ($mode & $readPublic) {
      return 'public-read';
    }
    if ($mode & $readGroup) {
      return 'authenticated-read';
    }
    return 'private';
}
```

### Additional Information/Context

This would be a breaking-change, so worth introducing as a `V2` function or appropriate version increment.

### SDK version used

3.222.6

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 7.4.29 (cli), on Ubuntu Bionic 18.04.

**Comment by jackthomasatl** [comment]
I'm also having an issue with this. It would be preferred if StreamWrapper did not set an ACL at all, and left it up to the bucket to set the ACL.

**Comment by stobrien89** [comment]
Hi all,

Sorry for the delayed response.  I don't have the history on why this particular mapping of permissions was chosen when the S3 StreamWrapper was first implemented, but we will not be prioritizing any further work to this.  

[S3 has already disabled ACLs by default on newly created buckets](https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/), which has forced us to stop applying ACLs upon bucket creation in the S3 Streamwrapper. Their [current security best practices](https://docs.aws.amazon.com/AmazonS3/latest/userguide/security-best-practices.html) recommend against using ACLs. We will continue to support the S3 Steamwrapper and any customizations that use ACLs by default.  Please let us know if you have any additional questions.
