### ISSUE TITLE
Add support for retries to EcsCredentialsProvider

### ISSUE THREAD

**Issue by annuh** [aws/aws-sdk-php#2457]
### Describe the feature

We are using this PHP SDK in an AWS ECS (via EC2) environment.

Sometimes we see errors like this when making signed requests to AWS using this SDK:
```
Error retrieving credential from ECS (cURL error 28: Connection timed out after 5001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://169.254.170.2/v2/credentials/0fa84058-9780-492a-8a3b-xxxx)
```

We already use `memory::()` to reduce the number of requests to the task metadata server, but still sometimes (during peak moment) some requests fail.

It looks like the InstanceProfileProvider has support to retry these failed requests:
https://github.com/aws/aws-sdk-php/blob/master/src/Credentials/InstanceProfileProvider.php

It would be great if the ECS credentials provider could also support this
https://github.com/aws/aws-sdk-php/blob/master/src/Credentials/EcsCredentialProvider.php

### Use Case

This would reduce the number of failed requests

### Proposed Solution

Implement a similar retry logic as exists in the https://github.com/aws/aws-sdk-php/blob/master/src/Credentials/InstanceProfileProvider.php

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.224.3

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

8.1.6

**Comment by yenfryherrerafeliz** [comment]
Hi @annuh, thanks for opening this feature request. We will review this as soon as we can and we will use this thread to provide an answer regarding. I want to let you know that we prioritize feature requests based on community engagement and reactions.

Thanks!
