### ISSUE TITLE
Fix deprecated use of "self" in callables (PHP 8.2)

### ISSUE THREAD

**Issue by jnoordsij** [aws/aws-sdk-php#2467]
### Describe the bug

At various places, callables are using syntax deprecated in PHP 8.2, for e.g. the call `'self::chain'` [here](https://github.com/aws/aws-sdk-php/blob/3.225.1/src/S3/RegionalEndpoint/ConfigurationProvider.php#L83).

Reference: https://wiki.php.net/rfc/deprecate_partially_supported_callables

### Expected Behavior

No deprecation notices

### Current Behavior

Deprecation notices on PHP 8.2 and up, which be errors on PHP 9.0 and up.

### Reproduction Steps

Run any code with deprecated syntax, e.g. https://github.com/aws/aws-sdk-php/blob/3.225.1/src/S3/RegionalEndpoint/ConfigurationProvider.php#L83

### Possible Solution

Probably a global search for occurences of `'self::` (and maybe also `'parent::` and `'static::`) will show most occurences.

Also running tests on the PHP 8.2 alpha might yield a pretty complete list.

### SDK version used

3.225.1

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.2.0alpha1 (cli)

**Comment by stobrien89** [comment]
Hi @jnoordsij,

Thanks for the report!  We don't officially support PHP 8+ at this time, but 8.0 are 8.1 support are currently in the works. This is something we'll keep in mind when further modernizing the SDK.

**Comment by shyim** [comment]
And why not fixing it just now? It's a simple fix and annoys me, using the next version already to prepare projects

**Comment by Mubasher-iqbal** [comment]
Any updates on this ? 
I am getting below mentioned Errors
`
ERROR - 2023-07-24 08:17:34 --> Severity: 8192 --> Use of "self" in callables is deprecated vendor/aws/aws-sdk-php/src/S3/RegionalEndpoint/ConfigurationProvider.php 83

ERROR - 2023-07-24 08:17:34 --> Severity: 8192 --> Use of "self" in callables is deprecated vendor/aws/aws-sdk-php/src/DefaultsMode/ConfigurationProvider.php 85

ERROR - 2023-07-24 08:17:34 --> Severity: 8192 --> Use of "self" in callables is deprecated vendor/aws/aws-sdk-php/src/Endpoint/UseFipsEndpoint/ConfigurationProvider.php 82

ERROR - 2023-07-24 08:17:34 --> Severity: 8192 --> Use of "self" in callables is deprecated vendor/aws/aws-sdk-php/src/Endpoint/UseDualstackEndpoint/ConfigurationProvider.php 83

ERROR - 2023-07-24 08:17:34 --> Severity: 8192 --> Use of "self" in callables is deprecated vendor/aws/aws-sdk-php/src/EndpointDiscovery/ConfigurationProvider.php 86

ERROR - 2023-07-24 08:17:34 --> Severity: 8192 --> Use of "self" in callables is deprecated vendor/aws/aws-sdk-php/src/Retry/ConfigurationProvider.php 88

ERROR - 2023-07-24 08:17:34 --> Severity: 8192 --> Use of "self" in callables is deprecated vendor/aws/aws-sdk-php/src/ClientSideMonitoring/ConfigurationProvider.php 90

ERROR - 2023-07-24 08:17:34 --> Severity: 8192 --> Use of "self" in callables is deprecated vendor/aws/aws-sdk-php/src/S3/UseArnRegion/ConfigurationProvider.php 83
`

**Comment by stobrien89** [comment]
Re-opening this.  In hindsight, we should have addressed this when it was first reported.  We'll try to have a fix out for this by next week.

**Comment by yenfryherrerafeliz** [comment]
Hi @jnoordsij, @shyim, @zz, @gitnik, @Mubasher-iqbal, sorry for any confusion on this. This issue seems to be already fixed by the following [commit](https://github.com/aws/aws-sdk-php/commit/9f12e1d99d8e09593702878e8a4aff52f8bf3775). This fix was applied on version 3.235.0, but is recommended to update to the latest version. So please bump your SDK version to either, the latest or at least version 3.235.0 to have this fixed at your end.

Please let me know if that helps!

Thanks!

**Comment by jnoordsij** [comment]
I don't think I've seen any deprecations recently, so I suspect the mentioned commit indeed has solved the issue.

**Comment by stobrien89** [comment]
Closing again based on the above comment.  Let us know if you're still having issues after updating your SDK version.
