### ISSUE TITLE
Call to undefined function Aws\boolean_value()

### ISSUE THREAD

**Issue by e2fletcher** [aws/aws-sdk-php#2471]
### Describe the bug

Fatal error: Call to undefined function Aws\boolean_value() in /var/www/piedrasaustrales/vendor/aws/aws-sdk-php/src/Endpoint/UseFipsEndpoint/Configuration.php on line 14

### Expected Behavior

In previous versions it worked, the weird thing is that I try to go to a previous version and I still get the same problem.

### Current Behavior

When I try to clear client s3

`  $s3 = new Aws\S3\S3Client([
      'version' => 'latest',
      'region'  => 'us-east-1',
      'credentials' => [

      ],
      'stats'   => [
          'retries'      => true,
          'timer'        => false,
          'http'         => true,
      ]
  ]);
`

### Reproduction Steps

`$s3 = new Aws\S3\S3Client([
    'version' => 'latest',
    'region'  => 'us-west-2',
    'debug'   => true
]);`

### SDK version used

3.225.4

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

5.6.40

**Comment by SamRemis** [comment]
Hi there @e2fletcher,
This is a pretty interesting issue you're getting.  If multiple people report this, I'll assume something is wrong with the SDK, but for now, I'm guessing your system somehow accidentally has two copies of the SDK installed.  Multiple other customers have reported issues with that functions file being uncallable with multiple versions of the SDK on their system.  

If you check and see that I'm right, I'd really appreciate you getting back to us with any info on how your system may have gotten two copies of the SDK.  I haven't been able to reproduce this specific bug, and that's the first step to fixing it.  Unfortunately, this is all the info I have for now.  

If it is more widespread, I will just move that function out of that file into a static file or the files from where it's called.

**Comment by far666** [comment]
same issue

`Fatal error:  Uncaught Error: Call to undefined function Aws\boolean_value() in vendor/aws/aws-sdk-php/src/Endpoint/UseFipsEndpoint/Configuration.php:14`

**Comment by rafasashi** [comment]
Most probably due to an incompatibility issue between 2 versions of Guzzle installed in the same environment.

**Comment by usmcsaluki** [comment]
> Hi there @e2fletcher, This is a pretty interesting issue you're getting. If multiple people report this, I'll assume something is wrong with the SDK, but for now, I'm guessing your system somehow accidentally has two copies of the SDK installed. Multiple other customers have reported issues with that functions file being uncallable with multiple versions of the SDK on their system.
> 
> If you check and see that I'm right, I'd really appreciate you getting back to us with any info on how your system may have gotten two copies of the SDK. I haven't been able to reproduce this specific bug, and that's the first step to fixing it. Unfortunately, this is all the info I have for now.
> 
> If it is more widespread, I will just move that function out of that file into a static file or the files from where it's called.

@SamRemis -

I know this is an older issue, but your suggestion on duplicate installations of the SDK was the issue for me today; I encountered the same fatal error, but realized I had two SDKs installed - removing one did the trick.  I appreciate your suggestion!

**Comment by BrianKopp** [comment]
I ran across this recently as well. We thought surely we only have 1 version of the SDK installed!

It turns out that the command we were running which caused this error, was going thru a PHING executable which we had downloaded. That Phing executable had AWS SDK PHP 3.110.7 installed, which does NOT have the `boolean_value` function.

Solution for us - don't use phing.
