### ISSUE TITLE
Very slow initialisation in development environment. 

### ISSUE THREAD

**Issue by Scott-J-McMullan** [aws/aws-sdk-php#2474]
### Describe the bug

Hello,

My team has been using this SDK with CodeIgniter for a couple of years with no issues until now. I recently transitioned to a Mac Mini & set up my local development environment on the machine & now the SDK is being painfully slow. Initialising it via the `Aws\S3\S3Client` constructor takes around 18 seconds. It's very consistent with this; almost always 18 seconds. Every so often it takes 17 seconds, but the rest is 18. 
I'm the only one in my team using macOS & the only one having this problem; we even recreated the environment on a Windows machine & there is no problems with the SDK. Same project structure, same environment variables. The only difference is the operating system using XAMPP on Windows.

### Expected Behavior

The SDK should initialise in a timely manner. 

### Current Behavior

The SDK takes a lengthy amount of time to initialise. 

### Reproduction Steps

1. Install SDK via Composer: `composer require aws/aws-sdk-php`
2. Add a script to the project to use the SDK
```php
<?php

use Aws\Exception\AwsException;
use Aws\S3\Exception\S3Exception;

class Aws_sdk
{
    private $s3;

    public function __construct()
    {
        try {
            $t        = time();
            $this->s3 = new Aws\S3\S3Client([
                'version'     => 'latest',
                'region'      => 'ap-southeast-2',
                'credentials' => [
                    // I'm obviously using the proper keys in my project.
                    'key'    => 'AWS_ACCESS_KEY_ID',
                    'secret' => 'AWS_SECRET_ACCESS_KEY',
                ]
            ]);
            printf('Took %d seconds', time() - $t);
            exit;
        } catch (Throwable $t) {
            echo $t->getMessage();
            exit;
        }
    }
}
```
3. Run project.
![Screen Shot 2022-06-20 at 13 49 04](https://user-images.githubusercontent.com/93307071/174521949-6c3d3bab-e590-4172-b821-cac7b164cfbe.png)

### Additional Information/Context

As I stated, this is only happening on my machine across projects. All projects we have that is using this SDK will take approximately 18 seconds to initialise on my machine, but works as expected on all others. It's also consistent; I can reproduce it every time. 

What I've done to investigate & try to fix the issue:
1. Set up brand new local development environment. 
2. Reinstalled/reinitialised everything a couple of times: CodeIgniter, composer, the SDK, the project etc.
3. Flushed caches were applicable. 
4. Tried to replicate the issue on different machines/operating systems.

Also, I don't know if it's relevant, but I've tried every approach possible to defining the credentials as outlined [here in the Using the Default Credential Provider Chain](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials.html). For the sake of removing layers of code for this issue, I've hard coded the credentials until I've gotten it fixed. 

### SDK version used

3.227

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP version: 7.4.28
OS: macOS Monterey 12.4
Composer version: 2.1.9 2021-10-05 09:47:38
CodeIgniter version: 3.1.11

**Comment by yenfryherrerafeliz** [comment]
Hi @Scott-J-McMullan, thanks for opening this issue. This seems to be environment related rather than an issue with our SDK. I also use Mac and I do not have any delay issues.
Could you please try this:
- Create an empty project with composer (not with codeigniter).
- Then, install the SDK
- Then, create a php file and try to use the SDK. You could use the same code that you provided.
- Then, run your code with php, and check if you get the same behavior.

Please let me know if you have any questions.

Thanks!

**Comment by Scott-J-McMullan** [comment]
Thanks @yenfryherrerafeliz, I will do that this weekend.

**Comment by Scott-J-McMullan** [comment]
Hi @yenfryherrerafeliz,

I set up a new bare-bones composer project & yes, the SDK works fine.

Here's my folder structure:
![Screen Shot 2022-06-27 at 13 06 07](https://user-images.githubusercontent.com/93307071/175852587-10a16fa9-9762-42f1-bd4a-bde488d32b70.png)

And here is my `index.php`:
```
<?php

require 'vendor/autoload.php';

try {
    $s3 = new Aws\S3\S3Client([
            'version'     => 'latest',
            'region'      => 'ap-southeast-2',
            'debug'   => true,
            'credentials' => [
                // I'm obviously using the proper keys in my project.
                'key'    => '{key}',
                'secret' => '{secret}',
            ]
        ]);
    printf("Took %d seconds\n\r", time() - $t);
        
    $buckets = $s3->listBuckets();
    foreach ($buckets['Buckets'] as $bucket) {
        echo $bucket['Name'] . "\n";
    }
} catch (Throwable $t) {
    echo $t->getMessage();
}
```
 
This is working as expected with normal execution times. Perhaps there's an issue with CodeIgniter & the SDK?
