### ISSUE TITLE
Undefined class constant 'VERSION'(short issue description)

### ISSUE THREAD

**Issue by saschaende** [aws/aws-sdk-php#2480]
### Describe the bug

Error Undefined class constant 'VERSION'

### Expected Behavior

No error

### Current Behavior

Error

### Reproduction Steps

Upload a file via s3

### Possible Solution

 Replace \GuzzleHttp\default_user_agent() with Utils::defaultUserAgent()

.../vendor/aws/aws-sdk-php/src/Handler/GuzzleV6/GuzzleHandler.php      | 3 ++-

@@ -37,7 +38,7 @@ class GuzzleHandler
         $request = $request->withHeader(
             'User-Agent',
             $request->getHeaderLine('User-Agent')
-                . ' ' . \GuzzleHttp\default_user_agent()
+                . ' ' . Utils::defaultUserAgent()
         );
 
         return $this->client->sendAsync($request, $this->parseOptions($options))

### SDK version used

latest

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

8

**Comment by saschaende** [comment]
No, solution is to replace \GuzzleHttp\default_user_agent() with Utils::defaultUserAgent() in "Handler/GuzzleV6/GuzzleHandler.php" because "default_user_agent()" is deprecated with latest guzzlehttp version.

**Comment by yenfryherrerafeliz** [comment]
Hi  @saschaende, I think the problem could be that you were using a non updated guzzle version, which probably by calling composer update would fix. You can check [here](https://github.com/guzzle/guzzle/blob/ca5c743d20730d1a129a9ee04cbe854df7304b96/src/functions.php#L71) that Utils::defaultUserAgent() is called internally when making default_user_agent call. I know this function is deprecated but by using the version 7.4.3 of guzzle I got not issues.

Thanks!

**Comment by saschaende** [comment]
I ran composer update today. Dont know why but this fixed it for me.

**Comment by yenfryherrerafeliz** [comment]
Here is why:
> Hi @saschaende, I think the problem could be that you were using a non updated guzzle version, which probably by calling composer update would fix. You can check [here](https://github.com/guzzle/guzzle/blob/ca5c743d20730d1a129a9ee04cbe854df7304b96/src/functions.php#L71) that Utils::defaultUserAgent() is called internally when making default_user_agent call. I know this function is deprecated but by using the version 7.4.3 of guzzle I got not issues.
> 
> Thanks!

Thanks!

**Comment by saschaende** [comment]
I called composer update BEFORE and THEN i got the error. After fixing the error it was solved. I am not stupid :D

**Comment by SamRemis** [comment]
Great :) I wish I knew what happened there so I could get to the bottom of it next time.  @saschaende, on the off chance this happens again, please save the current state of your vendor folder (at least aws-sdk-php and guzzle) so I can try to reproduce it on my my machine?  

Thanks for following up as well!

**Comment by saschaende** [comment]
@SamRemis No problem, here is it:

{
    "require": {
        "aws/aws-sdk-php": "^3.67",
        "twilio/sdk": "^6.7",
        "google/cloud-dialogflow": "^0.15.1",
        "defuse/php-encryption": "^2.2",
        "tholu/php-packer": "^0.2.0",
        "matthiasmullie/minify": "^1.3",
        "symfony/panther": "^0.8.0",
        "google/cloud-automl": "^1.3",
        "2captcha/2captcha": "^1.0",
        "php-curl-class/php-curl-class": "^9.2",
        "scssphp/scssphp": "^1.6",
        "google/cloud-bigquery": "^1.23",
        "phpoffice/phpspreadsheet": "^1.20"
    }
}

It is used in TYPO3.

Today i used it for the first time in a LARAVEL project and had no problems. Really strange thing.
