### ISSUE TITLE
Deprecated use of strlen() with PHP 8.1.7

### ISSUE THREAD

**Issue by benshawuk** [aws/aws-sdk-php#2481]
### Describe the bug

When creating a new S3Client object using PHP 8.1.7, I get this error:
strlen(): Passing null to parameter #1 ($string) of type string is deprecated in file vendor/aws/aws-sdk-php/src/S3/S3Client.php on line 432

### Expected Behavior

Error does not occur

### Current Behavior

strlen(): Passing null to parameter #1 ($string) of type string is deprecated in file vendor/aws/aws-sdk-php/src/S3/S3Client.php on line 432

### Reproduction Steps

$s3 = new \Aws\S3\S3Client([
            'version' => 'latest',
            'region'  => REGION,
            'debug'   => false,
            'credentials' => [
                'key'    => ACCESS_KEY,
                'secret' => SECRET
            ],
        ]);

        print_r($s3->listBuckets());

### Possible Solution

//$bucketLen = strlen($bucket);
$bucketLen = 0;

This temporarily resolves the issue, but I don't understand what the function is actually doing.
I'm guessing it needs to not get "null" passed to strlen function.

### SDK version used

3.228

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.1.7, MacOS12.4

**Comment by yenfryherrerafeliz** [comment]
Hi @benshawuk, thanks for opening this issue. 

We do not support PHP 8.1.7 yet, nonetheless I expect to post a PR to prevent this warning.

Thanks!
