### ISSUE TITLE
Not found the new feature “remove unused AWS services” in v3.230.0

### ISSUE THREAD

**Issue by kayw-geek** [aws/aws-sdk-php#2489]
### Describe the bug

I want to use the new feature “remove unused AWS services”, I already upgraded my `aws/aws-sdk-php` package in my project, but I not found any related file.  

I saw the new feature related file in master branch

### Expected Behavior

Has new feature related file in version v3.230.0

### Current Behavior

Not any new feature related file in version v3.230.0

### Reproduction Steps

`composer update aws/aws-sdk-php`

### SDK version used

3.230.0

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

8.1.7

**Comment by yenfryherrerafeliz** [comment]
Hi @kayw-geek, thanks for opening this issue. The version that contains that feature has not been released yet to composer. However, I will use this thread to let you know once the release is done.

Thanks!

**Comment by stobrien89** [comment]
Hi @kayw-geek,

Apologies for any confusion.  The feature is available in  `3.231.0`, which is now available via Composer.  Let us know if you have any questions!
