### ISSUE TITLE
Rename Elastic Beanstalk application or environment

### ISSUE THREAD

**Issue by andy3rdworld** [aws/aws-sdk-php#249]
Is it possible to programmatically rename an Elastic Beanstalk application or an application's environment?

To kick the tires, I tried the following exercise which returned a successful response, but it's not clear what changed when I look at AWS management console:

http://docs.aws.amazon.com/aws-sdk-php/latest/class-Aws.ElasticBeanstalk.ElasticBeanstalkClient.html#_updateApplication

```
 Guzzle\Service\Resource\Model\updateApplication
Updates the specified application to have the specified properties.
If a property (for example, description ) is not provided, the value remains unchanged. To clear these properties, specify an empty string.
```

``` php
// using Laravel PHP SDK here...
$client = AWS::get('ElasticBeanstalk');
        $result = $client->updateApplication(array(
            // ApplicationName is required
            'ApplicationName' => 'my-current-name',
            'Description' => 'my-new-name'
        ));
```

I understand that I've changed "description" rather than somethine like "NewApplicationName", but is there a way to do the re-naming?

**Comment by wonjun27** [comment]
👍

**Comment by dkathan** [comment]
Best way I found was to clone the environment to a new name and remove the old one.   The site URL will change however.

**Comment by christianbradley** [comment]
You can keep the old url by swapping the cnames after the clone, and before destroying the original (using eb cli):

```
eb swap original-environment-name -n new-environment-name
```
