### ISSUE TITLE
Remove Unused AWS services: Cannot redeclare `Aws\constantly() previously declared in aws-sdk-php/src/functions.php `

### ISSUE THREAD

**Issue by kayw-geek** [aws/aws-sdk-php#2492]
### Describe the bug

When I used the new feature “Remove unused AWS services”, I got a PHP fatal error that “PHP Fatal error:  Cannot redeclare `Aws\constantly()` (previously declared in `vendor/aws/aws-sdk-php/src/functions.php:20`)” and it printed twice.
I wonder if we need to regenerate autoload files in the static method `removeUnusedServices()`

### Expected Behavior

No error

### Current Behavior

Cannot redeclare `Aws\constantly()`

### Reproduction Steps

Put the “Aws\\Script\\Composer\\Composer::removeUnusedServices” to Composer event `pre-autoload-dump` 

### SDK version used

3.231.0

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

8.1.7

**Comment by stobrien89** [comment]
Hi @kayw-geek,

Thanks for the report and sorry about the issues.  Could you provide some reproduction steps?

**Comment by kayw-geek** [comment]
> 
I tried in locally  and CI, I got same results.
 I used Laravel framework, so my composer script have executed the`Illuminate\\Foundation\\ComposerScripts::postAutoloadDump` static method on post-autoload-dump event, it will require autoload file.

**Comment by kayw-geek** [comment]
https://github.com/aws/aws-sdk-php/pull/2495 The PR will solve this problem

**Comment by stobrien89** [comment]
Thanks again for reporting and the comments on #2495 @kayw-geek. The fix will be available in today's release!
