### ISSUE TITLE
Operation not found: CreateCloudFrontOriginAccessIdentity

### ISSUE THREAD

**Issue by RaviJayagopal** [aws/aws-sdk-php#2500]
### Describe the bug

When I try to create a CloudFront distribution, I get the error "Operation not found: CreateCloudFrontOriginAccessIdentity".

But if I refresh and try it again, it goes through the 2nd time without any issues.

Always errors first time, always goes through 2nd time.

Don't know where to begin looking for the issue.

Thanks for your help.

### Expected Behavior

Work the first time without any errors.

### Current Behavior

I get the error "Operation not found: CreateCloudFrontOriginAccessIdentity".

### Reproduction Steps

Standard code.

### SDK version used

Don't know how to find from existing code. Please help.

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

7.4.30

**Comment by yenfryherrerafeliz** [comment]
Hi @RaviJayagopal, thanks for reaching out. I did try to reproduce the reported inconvenient, but I got successful results when creating a cloudfront distribution. For my test I used the example code found in the following [link](https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/php/example_code/cloudfront/CreateDistributionS3.php). So, could you please provide more details about your current implementation so we can better help you?, we would need at least the following:
- Reproducible code snippet
- SDK minor version used. You could do ```composer show aws/aws-sdk-php```, and the version should be in the output.

Thanks!

**Comment by RaviJayagopal** [comment]
Thank you. This has been resolved. Was a coding issue.
