### ISSUE TITLE
Guzzle Error, when creating an LambdaClient object

### ISSUE THREAD

**Issue by berndwagner-movamo** [aws/aws-sdk-php#2504]
### Describe the bug

When I try generate an object of a new "LambdaClient", I got follow guzzle error:
`InvalidArgumentException: 
Magic request methods require a URI and optional options array`

### Expected Behavior

I expected to get an valid object

### Current Behavior

InvalidArgumentException: Magic request methods require a URI and optional options array
#55 /vendor/guzzlehttp/guzzle/src/Client.php(87): GuzzleHttp\Client::__call
#54 /vendor/aws/aws-sdk-php/src/Handler/GuzzleV6/GuzzleHandler.php(26): Aws\Handler\GuzzleV6\GuzzleHandler::__construct
#53 /vendor/aws/aws-sdk-php/src/functions.php(279): Aws\default_http_handler
#52 /vendor/aws/aws-sdk-php/src/ClientResolver.php(776): Aws\ClientResolver::_default_handler
#51 /vendor/aws/aws-sdk-php/src/ClientResolver.php(324): Aws\ClientResolver::resolve
#50 /vendor/aws/aws-sdk-php/src/AwsClient.php(199): Aws\AwsClient::__construct
#49 /vendor/aws/aws-sdk-php/src/Lambda/LambdaClient.php(145): Aws\Lambda\LambdaClient::__construct
#48 /app/Providers/AwsLambdaServiceProvider.php(29): App\Providers\AwsLambdaServiceProvider::getAwsLambdaClient
#47 /app/Providers/AwsLambdaServiceProvider.php(15): App\Providers\AwsLambdaServiceProvider::App\Providers\{closure}
#46 /vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\Container\Container::build
#45 /vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\Container\Container::resolve
#44 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Foundation\Application::resolve
#43 /vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\Container\Container::make
#42 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Foundation\Application::make
#41 /vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): app
#40 /vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(719): resolve
#39 /src/Domain/Messaging/Dispatcher/SendBulkMessageDispatcher.php(125): Domain\Messaging\Dispatcher\SendBulkMessageDispatcher::handle
#38 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
#37 /vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\Util::unwrapIfClosure
#36 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\BoundMethod::callBoundMethod
#35 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::call
#34 /vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\Container::call
#33 /vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Bus\Dispatcher::Illuminate\Bus\{closure}
#32 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#31 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline::then
#30 /vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Bus\Dispatcher::dispatchNow
#29 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\Queue\CallQueuedHandler::Illuminate\Queue\{closure}
#28 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#27 /app/Console/Middleware/Throttle.php(40): App\Console\Middleware\Throttle::App\Console\Middleware\{closure}
#26 /vendor/laravel/framework/src/Illuminate/Redis/Limiters/DurationLimiter.php(90): Illuminate\Redis\Limiters\DurationLimiter::block
#25 /vendor/laravel/framework/src/Illuminate/Redis/Limiters/DurationLimiterBuilder.php(113): Illuminate\Redis\Limiters\DurationLimiterBuilder::then
#24 /app/Console/Middleware/Throttle.php(43): App\Console\Middleware\Throttle::handle
#23 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#22 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline::then
#21 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\Queue\CallQueuedHandler::dispatchThroughMiddleware
#20 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\Queue\CallQueuedHandler::call
#19 /vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\Jobs\Job::fire
#18 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\Queue\Worker::process
#17 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\Queue\Worker::runJob
#16 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\Queue\Worker::daemon
#15 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Console\WorkCommand::runWorker
#14 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand::handle
#13 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
#12 /vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\Util::unwrapIfClosure
#11 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\BoundMethod::callBoundMethod
#10 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::call
#9 /vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\Container::call
#8 /vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Console\Command::execute
#7 /vendor/symfony/console/Command/Command.php(298): Symfony\Component\Console\Command\Command::run
#6 /vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Illuminate\Console\Command::run
#5 /vendor/symfony/console/Application.php(1024): Symfony\Component\Console\Application::doRunCommand
#4 /vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application::doRun
#3 /vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application::run
#2 /vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Illuminate\Console\Application::run
#1 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Foundation\Console\Kernel::handle
#0 /artisan(37): null`
`

### Reproduction Steps

``` php
$client = new LambdaClient([
                'version' => 'latest',
                'region' => config('aws.region'),
                'credentials' => [
                    'key' => config('aws.lambdauser.credentialkey'),
                    'secret' => config('aws.lambdauser.credentialsecret')
                ],
            ]);
```

### SDK version used

3.231.18

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 7.3 - Laravel 7.30.6

**Comment by yenfryherrerafeliz** [comment]
Hi @berndwagner-movamo, thanks for opening this issue.  I tried to reproduce the reported error but I was not able to. By looking at the error I feel that it could be that you could be using an outdated guzzle version. So, could you please try running composer update?

Thanks!

**Comment by stobrien89** [comment]
Hi @berndwagner-movamo,

Closing this for now.  Please let us know if you're still having issues.
