### ISSUE TITLE
[PHP8.1] RuntimeException in Api/Validator::check_string

### ISSUE THREAD

**Issue by quentin-tin** [aws/aws-sdk-php#2524]
### Describe the bug

In the [Api/Validator::check_string(...)](https://github.com/aws/aws-sdk-php/blob/69ffb3ce48cd8db0e266caed67e5fd1c7c898b26/src/Api/Validator.php#L219) method, a `RuntimeException` is possible when calling the `$this->validateRange(..., strlen($value), ...);`, because the above test `if (!$this->checkCanString($value))` allows `null` as possible value for `$value`.

I'm not sure if it's a problem on my side, regarding my AWS settings..

### Expected Behavior

Maybe `null` shouldn't be considered as a valid string ? Not sure..

### Current Behavior

```
   ┐
   ├ RuntimeException: strlen(): Passing null to parameter #1 ($string) of type string is deprecated
   │
   ╵ /Volumes/repository/devbox-web/web/vendor/aws/aws-sdk-php/src/Api/Validator.php:219
   ╵ /Volumes/repository/devbox-web/web/vendor/aws/aws-sdk-php/src/Api/Validator.php:87
   ╵ /Volumes/repository/devbox-web/web/vendor/aws/aws-sdk-php/src/Api/Validator.php:124
   ╵ /Volumes/repository/devbox-web/web/vendor/aws/aws-sdk-php/src/Api/Validator.php:87
   ╵ /Volumes/repository/devbox-web/web/vendor/aws/aws-sdk-php/src/Api/Validator.php:52
   ╵ /Volumes/repository/devbox-web/web/vendor/aws/aws-sdk-php/src/Middleware.php:78
   ╵ /Volumes/repository/devbox-web/web/vendor/aws/aws-sdk-php/src/IdempotencyTokenMiddleware.php:77
   ╵ /Volumes/repository/devbox-web/web/vendor/aws/aws-sdk-php/src/AwsClientTrait.php:64
   ╵ /Volumes/repository/devbox-web/web/vendor/aws/aws-sdk-php/src/AwsClientTrait.php:58
   ╵ /Volumes/repository/devbox-web/web/vendor/aws/aws-sdk-php/src/AwsClientTrait.php:86
   ╵ /Volumes/repository/devbox-web/web/classes/Lib/Aws/AwsCFClient.php:71
   ```

### Reproduction Steps

Here is the code I use to reproduce the error:
```php
$client = new CloudFrontClient([
    'credentials' => [
        'key' => 'xxx',
        'secret' => 'yyy',
    ],
    'private_key' => 'zzz',
    'key_pair_id' => 'foobar',
    'region' => '<region>',
    'version' => '2015-07-27',
]);
$results = $this->_client->listDistributions([
    'Marker' => null,
    'MaxItems' => 20, // Line 71
]);
```

### SDK version used

3.235.9

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

MacOS // PHP 8.1.8 (cli) (built: Jul  7 2022 02:58:10) (NTS) // Zend Engine v4.1.8, Copyright (c) Zend Technologies     with Zend OPcache v8.1.8, Copyright (c), by Zend Technologies

**Comment by yenfryherrerafeliz** [comment]
Hi @quentin-tin, thanks for opening this issue. I was able to reproduce the reported behavior, and I expect to post  a PR for fixing this soon.

Thanks!

**Comment by TheMY3** [comment]
@yenfryherrerafeliz same error, waiting for fix

**Comment by yenfryherrerafeliz** [comment]
Hi, the PR for fixing this issue has been merged so that I will close this issue now.

Thanks!
