### ISSUE TITLE
PHP8 is_resource behavioral change affects AbstractMonitoringMiddleware

### ISSUE THREAD

**Issue by mhsdef** [aws/aws-sdk-php#2527]
### Describe the bug

`AbstractMonitoringMiddleware::prepareSocket`'s `is_resource` check ([#](https://github.com/aws/aws-sdk-php/blob/a3a5711c00673d18b571199858ffee95296c5f0d/src/ClientSideMonitoring/AbstractMonitoringMiddleware.php#L238)):

```
private function prepareSocket($forceNewConnection = false)
{
    if (!is_resource(self::$socket)
        || $forceNewConnection
        || socket_last_error(self::$socket)
    ) {
        self::$socket = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);
        socket_clear_error(self::$socket);
        socket_connect(self::$socket, $this->getHost(), $this->getPort());
    }

    return self::$socket;
} 
```

Looks affected by https://www.php.net/manual/en/migration80.incompatible.php#migration80.incompatible.resource2object

### Expected Behavior

The check to cover both PHP7 and PHP8 behaviors.

### Current Behavior

The check only covers <PHP8 behavior.

### Reproduction Steps

See this:
https://onlinephp.io/c/3574d

### Possible Solution

Check for `!self::$socket instanceof Socket` as well to cover PHP8.

### SDK version used

master

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.0.23

**Comment by yenfryherrerafeliz** [comment]
Hi @hewsut, thanks for opening this issue. I agree with the suggested change. I will mark this issue to be reviewed so we can address it further.

Thanks!

**Comment by MattPearce** [comment]
@yenfryherrerafeliz this issue is blocking our PHP v8 upgrade, this patch will fix the issue if you could please merge it:

[0001-Switch-resource-check-to-class-check-for-PHP-v8-comp.patch](https://github.com/aws/aws-sdk-php/files/13983101/0001-Switch-resource-check-to-class-check-for-PHP-v8-comp.patch)

**Comment by yenfryherrerafeliz** [comment]
Hi @MattPearce, I have left a comment on the PR. Would you please be able to take look to it.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
This issue has been fixed by the following [PR](https://github.com/aws/aws-sdk-php/pull/2865). Closing for now.

Thanks!
