### ISSUE TITLE
(Deprecation notice when using php 8.1)

### ISSUE THREAD

**Issue by josephmo** [aws/aws-sdk-php#2536]
### Describe the bug

Trying to call the SDK to describe security groups, I get the following warning:

    PHP Deprecated:  Implicit conversion from float 53985.96404120326 to int loses precision

This could be fixed, by modifying GuzzleHttp/Handler/CurlMultiHandler.php:

    private function timeToNext()
    {
        $currentTime = Utils::currentTime();
        $nextTime = PHP_INT_MAX;
        foreach ($this->delays as $time) {
            if ($time < $nextTime) {
                $nextTime = $time;
            }
        }

        return max(0, $nextTime - $currentTime) * 1000000;
    }

to:

    private function timeToNext()
    {
        $currentTime =round(Utils::currentTime());
        $nextTime = PHP_INT_MAX;
        foreach ($this->delays as $time) {
            if ($time < $nextTime) {
                $nextTime = $time;
            }
        }

        return max(0, $nextTime - $currentTime) * 1000000;
    }

### Expected Behavior

See bug description

### Current Behavior

See bug description

### Reproduction Steps

See bug description

### Possible Solution

See bug description

### SDK version used

3.0

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.1

**Comment by ostrolucky** [comment]
GuzzleHttp/Handler/CurlMultiHandler.php is not in this project though? You are looking for https://github.com/guzzle/guzzle and this looks to be alredy changed there. Update your dependencies.

**Comment by yenfryherrerafeliz** [comment]
Hi @josephmo, what @ostrolucky has commented is correct. Thanks @ostrolucky.

I am closing this as completed now, but if you have any questions feel free to reach out back.

Thanks!
