### ISSUE TITLE
ApiProvider construct php error

### ISSUE THREAD

**Issue by Sergiobop** [aws/aws-sdk-php#2553]
### Describe the bug

I'm getting this error when using composer update in my project:

PHP Fatal error:  Cannot use null as default value for parameter $manifest of type array in /vendor/aws/aws-sdk-php/src/Api/ApiProvider.php on line 204

### Expected Behavior

No errors

### Current Behavior

The problem is the parameter declaration:
```
private array $manifest = null
```

### Reproduction Steps

Just composer update

### Possible Solution

The parameter should be:
```
private ?array $manifest = null
```

### SDK version used

3.240.10

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

php 8.1.7

**Comment by Sergiobop** [comment]
Hi @yenfryherrerafeliz , thank you for taking a look. It happens to in Api\Service ( maybe in more classes?)

Cannot use null as default value for parameter $service of type Aws\Api\Service
```
 public function __construct(protected Service $service = null)
```

**Comment by yenfryherrerafeliz** [comment]
Hi @Sergiobop, thanks for opening this issue. I understand your problem description, basically by putting the question mark we say the parameter is nullable, but also by making the default value to null we do the same, however it is not the recommended way. So, I am not able to reproduce the error you reported in my environment, so that could you please provide other details that could help in reproducing the error on my end?

> Hi @yenfryherrerafeliz , thank you for taking a look. It happens to in Api\Service ( maybe in more classes?)
Cannot use null as default value for parameter $service of type Aws\Api\Service
 public function __construct(protected Service $service = null)

I can confirm that the syntax above is not allowed, but I could not find in the current code base where that declaration is done. Which version of the SDK are you currently on?

Thanks!

**Comment by Sergiobop** [comment]
Hi @yenfryherrerafeliz , i'm using the latest version (3.240.10)

For example, you can find a similar error here in the constructor:
https://github.com/aws/aws-sdk-php/blob/master/src/Api/ErrorParser/AbstractErrorParser.php

I'm using the laravel ide helper too, and looks like it can't generate the meta file because of this errors

**Comment by yenfryherrerafeliz** [comment]
Hi @Sergiobop, I am still not able to reproduce this issue. I could not find either declarations in the way you mentioned in our code base, so that I am wondering if you are using an outdated version of the SDK. Could you please do the following:
- run ```composer show aws/aws-sdk-php`` from the project's folder
- post the results here

Thanks!

**Comment by Sergiobop** [comment]
Hi @yenfryherrerafeliz, first of all, thank you for your time here.

```
name     : aws/aws-sdk-php
descrip. : AWS SDK for PHP - Use Amazon Web Services in your PHP project
keywords : amazon, aws, cloud, dynamodb, ec2, glacier, s3, sdk
versions : * 3.240.11
type     : library
license  : Apache License 2.0 (Apache-2.0) (OSI approved) https://spdx.org/licenses/Apache-2.0.html#licenseText
homepage : http://aws.amazon.com/sdkforphp
source   : [git] https://github.com/aws/aws-sdk-php.git 4ab7d004ca11298bf400f3291f144d820fb97cd6
dist     : [zip] https://api.github.com/repos/aws/aws-sdk-php/zipball/4ab7d004ca11298bf400f3291f144d820fb97cd6 4ab7d004ca11298bf400f3291f144d820fb97cd6
path     : /Users/sergio/Desktop/aumentur/backend/vendor/aws/aws-sdk-php
names    : aws/aws-sdk-php

support
forum : https://forums.aws.amazon.com/forum.jspa?forumID=80
issues : https://github.com/aws/aws-sdk-php/issues
source : https://github.com/aws/aws-sdk-php/tree/3.240.11

autoload
files
psr-4
Aws\ => src/

requires
aws/aws-crt-php ^1.0.2
ext-json *
ext-pcre *
ext-simplexml *
guzzlehttp/guzzle ^6.5.8 || ^7.4.5
guzzlehttp/promises ^1.4.0
guzzlehttp/psr7 ^1.8.5 || ^2.3
mtdowling/jmespath.php ^2.6
php >=5.5

requires (dev)
andrewsville/php-token-reflection ^1.4
aws/aws-php-sns-message-validator ~1.0
behat/behat ~3.0
composer/composer ^1.10.22
dms/phpunit-arraysubset-asserts ^0.4.0
doctrine/cache ~1.4
ext-dom *
ext-openssl *
ext-pcntl *
ext-sockets *
nette/neon ^2.3
paragonie/random_compat >= 2
phpunit/phpunit ^4.8.35 || ^5.6.3 || ^9.5
psr/cache ^1.0
psr/simple-cache ^1.0
sebastian/comparator ^1.2.3 || ^4.0
yoast/phpunit-polyfills ^1.0

suggests
aws/aws-php-sns-message-validator To validate incoming SNS notifications
doctrine/cache To use the DoctrineCacheAdapter
ext-curl To send requests using cURL
ext-openssl Allows working with CloudFront private distributions and verifying received SNS messages
ext-sockets To use client-side monitoring
```


I just did composer update again, the package updated to 3.242.0
And the error... is gone now! I don't know how or how to explain this.. 

Anyway feel free to close this one.

THANKS AGAIN!
