### ISSUE TITLE
aws/aws-sdk-php/src/S3/BucketEndpointArnMiddleware.php has Invalid PHP Syntax

### ISSUE THREAD

**Issue by taka-oyama** [aws/aws-sdk-php#2558]
### Describe the bug

`Aws\S3\BucketEndpointArnMiddleware`'s 4th arugument has a default value but the 5th argument does not, which doesn't work in PHP. 

### Expected Behavior

`BucketEndpointArnMiddleware` can be instantiated.

### Current Behavior

```
Optional parameter $config declared before required parameter $isUseEndpointV2 is implicitly treated as a required parameter

/Users/t-oyama/Projects/github/laravel/framework/vendor/aws/aws-sdk-php/src/S3/BucketEndpointArnMiddleware.php:59
```

### Reproduction Steps

I don't think this is necessary to identify the issue.

### Possible Solution

Add a default value to `$isUseEndpointV2`  or remove the default value for `$config`.

### SDK version used

3.243.1

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

v8.1.8 Alpine Linux 3.16

**Comment by yenfryherrerafeliz** [comment]
Hi @taka-oyama, thanks for opening this issue. I can confirm that the syntax needs to be changed, so that in order to address this further I will mark this for review.

Thanks!

**Comment by driesvints** [comment]
I sent in a PR for this: https://github.com/aws/aws-sdk-php/pull/2560

**Comment by stobrien89** [comment]
Hi all,

I've created a PR which addresses both this issue and #2558.  We should have a release cut shortly.  Many apologies for the disruption here.

**Comment by stobrien89** [comment]
Version `3.243.2` is live— can those affected upgrade and confirm this is no longer an issue? Thanks!

**Comment by driesvints** [comment]
Looks good for us 👍

**Comment by stobrien89** [comment]
Going to close this, but more than happy to take another look if anyone is still having issues.

**Comment by stobrien89** [comment]
@taka-oyama, @driesvints

Would you be able to tell me if your CI was catching this in all of 8+, or just 8.2?
