### ISSUE TITLE
Cannot Upload to S3 with prefix / in path

### ISSUE THREAD

**Issue by kawakibi** [aws/aws-sdk-php#2563]
### Describe the bug

Hello

Since [3.243.0](https://github.com/aws/aws-sdk-php/releases/tag/3.243.0) , our build was failing when uploading file for key that starts with `/` (example : `/private/image.gif` ). 

We must provide `'endpoint_provider' => PartitionEndpointProvider::defaultProvider()` when initializing `S3Client`. 

is it the correct behaviour ?

I try to debug what the difference is. It is because the bucket value move to the host value when using default endpoint provider `EndpointProviderV2` so Guzzle's Uri class parses the relative path as host replacing aws host. 

### Expected Behavior

With PartitionEndpointProvider::defaultProvider()
```
string(72) "GuzzleHttp\Psr7\Uri Construct -> https://s3.ap-southeast-3.amazonaws.com"
string(72) "GuzzleHttp\Psr7\Uri Construct -> https://s3.ap-southeast-3.amazonaws.com"
string(70) "GuzzleHttp\Psr7\Uri Construct -> /bucket//private/image.gif"
string(109) "GuzzleHttp\Psr7\Uri Construct -> https://s3.ap-southeast-3.amazonaws.com/bucket//private/image.gif"
<p>File successfully uploaded to https://bucket.s3.ap-southeast-3.amazonaws.com//private/image.gif.</p>Model Data
```

### Current Behavior

With EndpointProviderV2 
```
string(72) "GuzzleHttp\Psr7\Uri Construct -> https://s3.ap-southeast-3.amazonaws.com"
string(72) "GuzzleHttp\Psr7\Uri Construct -> https://s3.ap-southeast-3.amazonaws.com"
string(90) "GuzzleHttp\Psr7\Uri Construct -> https://bucket.s3.ap-southeast-3.amazonaws.com"
string(52) "GuzzleHttp\Psr7\Uri Construct -> //private/image.gif"
string(58) "GuzzleHttp\Psr7\Uri Construct -> https://private/image.gif"
PHP Fatal error:  Uncaught exception 'Aws\S3\Exception\S3Exception'
 with message 'Error executing "PutObject" on "https://private/image.gif"; 
AWS HTTP error: cURL error 6: Could not resolve: private (Domain name not found)
 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://private/image.gif'
```

### Reproduction Steps

Try run sample script below
```php

<?php

use Aws\Endpoint\PartitionEndpointProvider;
use Aws\Exception\MultipartUploadException;
use Aws\S3\ObjectUploader;
use Aws\S3\S3Client;

require 'vendor/autoload.php';

$config = [
	'region' => 'ap-southeast-3',
	'bucket' => '<bucket>',
	'secret' => 'xxx',
	'key' => 'yyyy'
];

$s3Client = new S3Client([
	'version' => '2006-03-01',
	'region' => $config['region'],
	'credentials' => [
		'key' => $config['key'],
		'secret' => $config['secret']
	],
]);

$keyPath = '/private/image.gif';
$filename = 'non-animated.gif';
$file = '/tmp/test-file/' . $filename;
$key = $keyPath . $filename;

$source = fopen($file, 'rb');
$uploader = new ObjectUploader($s3Client, $config['bucket'], $key, $source);

do {
	try {
		$result = $uploader->upload();
		if ('200' == $result['@metadata']['statusCode']) {
			echo '<p>File successfully uploaded to ' . $result['ObjectURL'] . '.</p>';
		}
		echo $result;
	} catch (MultipartUploadException $e) {
		rewind($source);
		$uploader = new MultipartUploader($s3Client, $source, [
			'state' => $e->getState(),
		]);
	}
} while (!isset($result));

fclose($source);
```

### Possible Solution

using `'endpoint_provider' => PartitionEndpointProvider::defaultProvider()` fixes the problem

```php
$s3Client = new S3Client([
	'version' => '2006-03-01',
	'region' => $config['region'],
	'credentials' => [
		'key' => $config['key'],
		'secret' => $config['secret']
	],
	'endpoint_provider' => PartitionEndpointProvider::defaultProvider()
]);
```

### SDK version used

3.243.2

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 7.4.33 - Debian Buster

**Comment by stobrien89** [comment]
Hi @kawakibi,

Thank you for reporting this.  Taking a look now

**Comment by stobrien89** [comment]
Hi @kawakibi,

I was able to confirm what you reported.  We have a fix staged for this, but our test environments are down for scheduled maintenance.  

For the time being, I'd recommend either pinning your version or doing what you mentioned above: passing 

`'endpoint_provider' => PartitionEndpointProvider::defaultProvider()`

into your client constructor.  I'll let you know when we're able to get a fix out for this.

**Comment by stobrien89** [comment]
Hi @kawakibi,

We were able to get a fix out for this— could you try upgrading to `3.244.1` and let us know if this is still occurring? Thanks!

**Comment by kawakibi** [comment]
looks good to us @stobrien89 ... thanks !

**Comment by stobrien89** [comment]
Great, closing now.  Let us know if you run into any more issues!

**Comment by labomatik** [comment]
Hello, we are having more or less the same issue (at lease the workaround provided by @kawakibi is working for us)
We are currently using a filesystem that is hosted at DigitalOcean (space), we are using an AWS adapter requiring a few packages, one of the packages: aws/aws-sdk-php

By upgrading from 3.242.1 to 3.243.0 we suddenly got issues in our system (a nasty Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames)

The latest release 3.245.0 doesn't solve the issue 

Do you have any idea what we can do to further debug and provide you with useful insight?
