### ISSUE TITLE
Invalid configuration value provided for token

### ISSUE THREAD

**Issue by georgeboot** [aws/aws-sdk-php#2567]
### Describe the bug

Updated to 3.245.0 last night and ever since I'm getting errors like these:

`
Invalid configuration value provided for \"token\". Expected Aws\\Token\\TokenInterface|Aws\\CacheInterface|array|bool|callable, but got string(912)
`
We create clients in 2 ways:

```php
$client = new SomeSdkClient([
    'version' => 'latest',
    'region' => $_ENV['AWS_REGION'] ?? $_ENV['AWS_DEFAULT_REGION'],
]);
```

```php
$client = new SomeSdkClient([
    'version' => 'latest',
    'region' => $_ENV['AWS_REGION'] ?? $_ENV['AWS_DEFAULT_REGION'],
    'credientials' => [
        'key' => $_ENV['AWS_ACCESS_KEY_ID'],
        'secret' => $_ENV['AWS_SECRET_ACCESS_KEY'],
        'token' => $_ENV['AWS_SESSION_TOKEN'],
    ],
]);
```

Since the new version, this _sometimes_ errors. I still need to investigate when exactly.

### Expected Behavior

No error

### Current Behavior

Sometimes errors with above mentioned error

### Reproduction Steps

Not really sure yet, will update once figured out

### Additional Information/Context

Using Laravel

### SDK version used

3.245.0

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

8.1

**Comment by SamRemis** [comment]
Hi @georgeboot,
Thank you for opening the issue, is it possible you're ever providing "token" on the top level of the array initialization?

So for instance:
```
$client = new SomeSdkClient([
    'version' => 'latest',
    'region' => $_ENV['AWS_REGION'] ?? $_ENV['AWS_DEFAULT_REGION'],
    'credientials' => [
        'key' => $_ENV['AWS_ACCESS_KEY_ID'],
        'secret' => $_ENV['AWS_SECRET_ACCESS_KEY'],
    ],
        'token' => $_ENV['AWS_SESSION_TOKEN'],
]);
```
or 

```
$client = new SomeSdkClient([
    'version' => 'latest',
    'region' => $_ENV['AWS_REGION'] ?? $_ENV['AWS_DEFAULT_REGION'],
    'token' => $_ENV['AWS_SESSION_TOKEN'],
     ]);
```

**Comment by georgeboot** [comment]
This can probably be closed as soon as the fix in Laravel is confirmed to be working.

**Comment by SamRemis** [comment]
Thank you :) 
I will set this to auto-close so that it closes in a few days.  We should leave it open for now for visibility in case anyone else was inadvertently passing in 'token' at the top level of the array, since this was a new valid config value added in the latest version.

**Comment by stobrien89** [comment]
I think the auto-close bot wasn't triggered due to the `bug` label being applied to this beforehand.  Closing now, but let us know if you have any questions!
