### ISSUE TITLE
SNS Subscribe not working - EndpointV2 ?

### ISSUE THREAD

**Issue by drekinov** [aws/aws-sdk-php#2572]
### Describe the bug

not possible to use SnsClient to execute http/https subscribe

### Expected Behavior

to subscribe http/https endpoints as with 3.242.1 or older

### Current Behavior

I assume that EndpointV2 is confusing `Endpoint` key as AWS API url and sends post data from command to subscriber URL instead AWS SNS rest api.

### Reproduction Steps

```php
$endpoint = 'https://where-all-data-will-be-send.com/';
$protocol = 'https';
$topicArn = 'arn:::::';
$command = $this->snsClient->getCommand(
            'subscribe',
            [
                'Endpoint' => $endpoint,
                'Protocol' => $protocol, // REQUIRED
                'TopicArn' => $topicArn, // REQUIRED
            ]
        );

        $result = $this->snsClient->execute($command);
```

### Additional Information/Context

I want to credit that SO topic because it was the first indicating that my issue might be SDK related: https://stackoverflow.com/questions/74475524/aws-sdk-sns-subscribe-to-https-endpoint

And that is current documentation confirming my syntax should be fine: https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-sns-2010-03-31.html#subscribe

### SDK version used

 \>= 3.243.0

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

8.1.12, ubuntu 20.04 LTS

**Comment by stobrien89** [comment]
Hi @drekinov,

Thanks for raising this! You are correct— the value for `Endpoint` passed into the command is being used for endpoint ruleset evaluation.  Should have a fix out shortly.  In the meantime, you can provide `endpoint_provider => partitionEndpointProvider::defaultProvider()` into your client config or pin your version to `3.242.1` to mitigate this.

**Comment by stobrien89** [comment]
Hi @drekinov,

This should be resolved on `3.246.1`. Could you try upgrading and confirm? Thanks!

**Comment by Khel** [comment]
Hello @drekinov,

Author from the StackOverflow post here :)

Many thanks. We are currently in contact with AWS support and they have not been able to provide any insight. They say it works.

@stobrien89 Will try to see if it works with the updated SDK.

Regards!

**Comment by Khel** [comment]
@stobrien89 @drekinov I can confirm v3.246.1 fixes this :)

Many thanks. It has been hell the last 4 days :)

**Comment by stobrien89** [comment]
Hi @Khel and @drekinov,

Glad to hear it's working!  Many apologies for the issues— this was an oversight on my part. Please don't hesitate to reach out if anything else comes up.
