### ISSUE TITLE
S3 ListObjects broken with Aws\EndpointV2

### ISSUE THREAD

**Issue by kovshenin** [aws/aws-sdk-php#2575]
### Describe the bug

When using an `endpoint` + `bucket_endpoint` with `Aws\EndpointV2` the `listObjects` method of an S3 Client doesn't seem to work as expected. It results in a double-slash URL:

```
GET https://bucket-name.endpoint.dev/bucket-name//?prefix=%2F&encoding-type=url
```

Removing the trailing slash from the `endpoint` argument resolves the error, however the returned results are always empty, as the bucket name path is completely stripped from the effective URL:

```
https://bucket-name.endpoint.dev/?prefix=%2F&encoding-type=url
```

### Expected Behavior

The `ListObjects` call should work with a trailing slash on the endpoint and return the items from the S3 bucket.

### Current Behavior

`ListObjects` produces an invalid URL.

### Reproduction Steps

```php
use Aws\Endpoint\PartitionEndpointProvider;
use Aws\S3\S3Client;

require 'vendor/autoload.php';

$s3Client = new S3Client( [
	'version' => '2006-03-01',
	'endpoint' => 'https://bucket-name.endpoint.dev/bucket-name/',
	'signature' => 'v4',
	'bucket_endpoint' => true,
	'region' => 'us-east-1',
	'credentials' => [
		'key' => 'admin',
		'secret' => 'password',
	],
] );

var_dump( $s3Client->listObjects( [
	'Bucket' => 'bucket-name',
	'Prefix' => '/',
] ) );
```

### Possible Solution

I do not have suggestions on how to fix `ListObjects` with `Aws\EndpointV2`, but current workarounds are:

* Use `ListObjectsV2` instead
* Use `PartitionEndpointProvider::defaultProvider()` for `endpoint_provider`

### SDK version used

3.246.1

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.0.24

**Comment by stobrien89** [comment]
Hi @kovshenin,

Thanks for raising this!  Sincere apologies for the issues. Should hopefully be able to get a fix out today.

**Comment by stobrien89** [comment]
Hi @kovshenin,

Sorry for the delay— I'll have a fix ready for today's release.  This (and other EndpointV2-related S3 issues) have been the result of our need to pre-process the S3 model to remove `Bucket` from the request uri.  It is now modeled in the S3 endpoint ruleset.  This has caused some unexpected behavior when joining paths with trailing and/or leading forward slashes.  

For what it's worth, while we do still support `ListObjects`, S3 recommends using ListObjectsV2 when possible.

**Comment by kovshenin** [comment]
Thanks @stobrien89, no worries about the delay! Yeah we're working on switching to ListObjectsV2 for some of our projects, thanks for confirming that's the recommended one.

**Comment by kovshenin** [comment]
Thanks for working on this @stobrien89!

**Comment by stobrien89** [comment]
Happy to help! Let us know if anything else comes up.
