### ISSUE TITLE
Sdk makes subfolders in bucket while upload files

### ISSUE THREAD

**Issue by phyzerbert** [aws/aws-sdk-php#2585]
### Describe the bug

I had tried to upload files to s3 bucket in laravel8 project.
When I upload files, this sdk makes sub folders in bucket then store files in there.
For example:
https://usc1.contabostorage.com/5ad9e197778e466fb7de773d30bfed5d:fliconn-posts-usa/fliconn-posts-usa/fliconn-posts-usa/status/EpkJnoINeTozMyXrjF93IwTks.jpg

I expect this:

https://usc1.contabostorage.com/5ad9e197778e466fb7de773d30bfed5d:fliconn-posts-usa/status/EpkJnoINeTozMyXrjF93IwTks.jpg

The sdk version was 3.250.0

On the 3.242.1 everything works well.

### Expected Behavior

https://usc1.contabostorage.com/5ad9e197778e466fb7de773d30bfed5d:fliconn-posts-usa/status/EpkJnoINeTozMyXrjF93IwTks.jpg

### Current Behavior

https://usc1.contabostorage.com/5ad9e197778e466fb7de773d30bfed5d:fliconn-posts-usa/fliconn-posts-usa/fliconn-posts-usa/status/EpkJnoINeTozMyXrjF93IwTks.jpg

### Reproduction Steps

No

### SDK version used

3.250.0

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

7.4

**Comment by stobrien89** [comment]
Hi @phyzerbert,

Closing for now, but let us know if you're still having issues.  I have a feeling this may be related to #2588, so feel free to comment there too.
