### ISSUE TITLE
awsforphp twitter handle is not suspended

### ISSUE THREAD

**Issue by AvinashDalvi89** [aws/aws-sdk-php#2586]
### Describe the issue

[@awsforphp](https://twitter.com/awsforphp) – Follow us on Twitter - This handle need to create new or remove for now until account get settled. 

<img width="658" alt="Screenshot 2022-12-01 at 4 48 58 PM" src="https://user-images.githubusercontent.com/3996105/205039748-f8a0019a-2c7b-44c5-98df-6f7f8f93f59f.png">

### Links

https://github.com/aws/aws-sdk-php/blob/master/README.md

**Comment by yenfryherrerafeliz** [comment]
Hi @AvinashDalvi89, thanks for bringing this to us. I have posted a PR updating the README, however, it needs to be reviewed and approved by the team.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Hi @AvinashDalvi89, again thanks for reporting this. The PR that updates our README is now merged, so that I will close this as complete.

Thanks!
