### ISSUE TITLE
S3 Endpoint >  Not able to use custom endpoint 

### ISSUE THREAD

**Issue by janavenkat** [aws/aws-sdk-php#2588]
### Describe the bug

Since release of `3.242.0` version custom endpoints for S3 not working. We use https://github.com/adobe/S3Mock for local tests, so we have to use custom endpoint for tests. 

Now I get the error bucket doesn't not exist and tried to trace the requests in S3 Mock it doesn't get any request.

So the problem is not is listening to custom endpoint. 

There is related issue https://github.com/aws/aws-sdk-php/issues/2575 but fix seems not working

### Expected Behavior

Should use custom endpoint and to be able to do S3 operations

### Current Behavior

Bucket not found because SDK not listening custom endpoint

### Reproduction Steps

1. Start S3 Mock https://github.com/adobe/S3Mock
2. Configure PHP request to use endpoint that listen to S3 [Mock](https://github.com/adobe/S3Mock) and bucket that configured in S3 mock service
3. Make the request to upload file to S3.
4. You should get the error that bucket not exist

### SDK version used

3.252.1

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

8.1.13

**Comment by yenfryherrerafeliz** [comment]
Hi @janavenkat, thanks for opening this issue. Could you please provide a sample code of the operation that you are doing, so we can better replicate this issue?

Thanks!

**Comment by janavenkat** [comment]
@yenfryherrerafeliz thank you for investigating, here is the config I used.


1. Start S3 Mock `docker run -p 9090:9090 -p 9191:9191 -e debug=true -e initialBuckets=testbucket -t adobe/s3mock` 
2. Make request to S3 with this config
```
$services->set(S3Client::class)  
    ->args([[  
        'region' => 'eu-west-1',  
        'version' => '2006-03-01',  
        'signature_version' => 'latest',  
        'credentials' => false,  
        'endpoint' => http://localhost:9090/testbucket/,  
        'bucket_endpoint' => true,  
    ]]);
```
Expected S3 operation should work, but currently am getting bucket not found error

**Comment by janavenkat** [comment]
@stobrien89 @yenfryherrerafeliz  sorry for the delay

Debug response from new version 3.247.1 and it's happening same still latest release
```php

-> Entering step build, name 'builderV2'
----------------------------------------

  request.instance was set to xxxxx
  request.method was set to HEAD
  request.headers was set to array(2) {
	["X-Amz-Security-Token"]=>
	string(7) "[TOKEN]"
	["Host"]=>
	array(1) {
	  [0]=>
	  string(28) "testbucket.localhost:9090"
	}
  }
  
  request.scheme was set to http
  request.port was set to 9090
  request.path was set to /testbucket/testbucket/original.txt


xxxxx

* Could not resolve host: testbucket.localhost
* Closing connection 0

```


Debug response from old version 3.241.0
```php


-> Entering step build, name 'builder'
----------------------------------------

  request.instance was set to xxxxx
  request.method was set to HEAD
  request.headers was set to array(2) {
	["X-Amz-Security-Token"]=>
	string(7) "[TOKEN]"
	["Host"]=>
	array(1) {
	  [0]=>
	  string(28) "localhost:9090"
	}
  }
  
  request.scheme was set to http
  request.port was set to 9090
  request.path was set to /testbucket/testbucket/original.txt




```

Seems new version is adding the bucket name in host

**Comment by stobrien89** [comment]
@janavenkat,

Thank you so much for the additional information.  Could you add `'use_path_style_endpoint' => true` to your client config and let me know if that solves the issue for you? Thanks!

**Comment by janavenkat** [comment]
> @janavenkat,
> 
> Thank you so much for the additional information. Could you add `'use_path_style_endpoint' => true` to your client config and let me know if that solves the issue for you? Thanks!

Thank you for the response. Still not working i got the same error, but it's sets the hosts properly

```php
$services->set(S3Client::class)  
    ->args([[  
        'region' => 'eu-west-1',  
        'version' => '2006-03-01',  
        'signature_version' => 'latest',  
        'credentials' => false,  
        'endpoint' => http://localhost:9090/testbucket/,  
        'bucket_endpoint' => true,  
        'use_path_style_endpoint' => true,
    ]]);
```

Response 
```php

-> Entering step build, name 'builderV2'
----------------------------------------

  request.instance was set to xxxxx
  request.method was set to HEAD
  request.headers was set to array(2) {
	["Host"]=>
	array(1) {
	  [0]=>
	  string(28) "localhost:9090"
	}
  }
  
  request.scheme was set to http
  request.port was set to 9090
  request.path was set to /testbucket/testbucket/testbucket/original.txt


```

If you see the path bucket name is added and my using latest release of SDK.

**Comment by stobrien89** [comment]
Hi @janavenkat,

Thanks for confirming.  Should have a fix out for this soon, but in the meantime you can work around this by providing `'endpoint_provider' => EndpointProvider::defaultProvider()` to your client config.

**Comment by stobrien89** [comment]
Hi @janavenkat and @YutakaOkabe,

#2601 should address this— We'll hopefully have it out in tomorrow's release.  Apologies for the delay- just wanted to make sure we got this right since there have been a few other issues with the `bucket_endpoint` customization.  Moving forward, we'll require users be more specific about the type of endpoint they are using/expecting, meaning if you are using a path-style endpoint like `http://localhost:9090/testbucket/`, you'll need to set `use_path_style_endpoint` to `true`.
