### ISSUE TITLE
sso credentials provider not picking up profile 

### ISSUE THREAD

**Issue by stephen-barrow** [aws/aws-sdk-php#2591]
### Describe the bug

Whenever i try and get credentials using ```$provider = CredentialProvider::sso('qc-int');```  I get the following error ```Profile qc-int does not exist in /home/www/.aws/config``` even though it is in my configuration file. 

### Expected Behavior

I expect ```$provider = CredentialProvider::sso('qc-int');``` to work with 

```
[profile qc-int]
sso_start_url=https://XXXXXX.awsapps.com/start
sso_region=eu-west-1
sso_account_id=XXXXXXXXXX 
```

### Current Behavior

I get the following error 

```Aws\Exception\CredentialsException at /app/vendor/aws/aws-sdk-php/src/Credentials/CredentialProvider.php:880 - Profile qc-int does not exist in /home/www/.aws/config. [{"file":"/app/vendor/aws/aws-sdk-php/src/Credentials/CredentialProvider.php","line":334,"function":"reject","class":"Aws\\Credentials\\CredentialProvider","type":"::","args":["Profile qc-int does not exist in /home/www/.aws/config."]},{"file":"/app/vendor/aws/aws-sdk-php/src/Middleware.php","line":147,"function":"Aws\\Credentials\\{closure}","class":"Aws\\Credentials\\CredentialProvider","type":"::","args":[]},{"file":"/app/vendor/aws/aws-sdk-php/src/RetryMiddleware.php","line":275,"function":"Aws\\{closure}","class":"Aws\\Middleware","type":"::","args":["[object] (Aws\\Command: {})","[object] (GuzzleHttp\\Psr7\\Request: {})"]},{"file":"/app/vendor/aws/aws-sdk-php/src/Middleware.php","line":233,"function":"__invoke","class":"Aws\\RetryMiddleware","type":"->","args":["[object] (Aws\\Command: {})","[object] (GuzzleHttp\\Psr7\\Request: {})"]},{"file":"/app/vendor/aws/aws-sdk-php/src/StreamRequestPayloadMiddleware.php","line":83,"function":"Aws\\{closure}","class":"Aws\\Middleware","type":"::","args":["[object] (Aws\\Command: {})","[object] (GuzzleHttp\\Psr7\\Request: {})"]},{"file":"/app/vendor/aws/aws-sdk-php/src/Middleware.php","line":304,"function":"__invoke","class":"Aws\\StreamRequestPayloadMiddleware","type":"->","args":["[object] (Aws\\Command: {})","[object] (GuzzleHttp\\Psr7\\Request: {})"]},{"file":"/app/vendor/aws/aws-sdk-php/src/EndpointParameterMiddleware.php","line":87,"function":"Aws\\{closure}","class":"Aws\\Middleware","type":"::","args":["[object] (Aws\\Command: {})","[object] (GuzzleHttp\\Psr7\\Request: {})"]},{"file":"/app/vendor/aws/aws-sdk-php/src/ClientResolver.php","line":900,"function":"__invoke","class":"Aws\\EndpointParameterMiddleware","type":"->","args":["[object] (Aws\\Command: {})","[object] (GuzzleHttp\\Psr7\\Request: {})"]},{"file":"/app/vendor/aws/aws-sdk-php/src/ClientSideMonitoring/AbstractMonitoringMiddleware.php","line":126,"function":"Aws\\{closure}","class":"Aws\\ClientResolver","type":"::","args":["[object] (Aws\\Command: {})","[object] (GuzzleHttp\\Psr7\\Request: {})"]},{"file":"/app/vendor/aws/aws-sdk-php/src/Middleware.php","line":111,"function":"__invoke","class":"Aws\\ClientSideMonitoring\\AbstractMonitoringMiddleware","type":"->","args":["[object] (Aws\\Command: {})","[object] (GuzzleHttp\\Psr7\\Request: {})"]},{"file":"/app/vendor/aws/aws-sdk-php/src/Middleware.php","line":89,"function":"Aws\\{closure}","class":"Aws\\Middleware","type":"::","args":["[object] (Aws\\Command: {})",null]},{"file":"/app/vendor/aws/aws-sdk-php/src/IdempotencyTokenMiddleware.php","line":77,"function":"Aws\\{closure}","class":"Aws\\Middleware","type":"::","args":["[object] (Aws\\Command: {})",null]},{"file":"/app/vendor/aws/aws-sdk-php/src/AwsClientTrait.php","line":64,"function":"__invoke","class":"Aws\\IdempotencyTokenMiddleware","type":"->","args":["[object] (Aws\\Command: {})"]},{"file":"/app/vendor/aws/aws-sdk-php/src/AwsClientTrait.php","line":58,"function":"executeAsync","class":"Aws\\AwsClient","type":"->","args":["[object] (Aws\\Command: {})"]},{"file":"/app/vendor/aws/aws-sdk-php/src/AwsClientTrait.php","line":86,"function":"execute","class":"Aws\\AwsClient","type":"->","args":["[object] (Aws\\Command: {})"]},{"file":"/app/web/public_html/sign-in.php","line":107,"function":"__call","class":"Aws\\AwsClient","type":"->","args":["adminSetUserPassword",[{"Password":"Testpass3","Permanent":true,"UserPoolId":"eu-west-XXXXXXXX","Username":"mjb@XXXX.com"}]]}```. 

### Reproduction Steps

Create a CognitoIdentityProviderClient using sso credentials provider and try and set a user password

```
$provider = CredentialProvider::sso('qc-int');
$awsRegion = getenv('AWS_COGNITO_REGION');

if (!$awsRegion) {
    throw new RuntimeException('AWS_COGNITO_REGION is required for AWS Cognito client');
}

$cognitoClient =  $new CognitoIdentityProviderClient([
                    'region'  => $awsRegion,
                    'version' => 'latest',
                    'credentials' => $provider
                ]);
$result = $cognitoClient->adminSetUserPassword([
            'Password' => 'Testpass3', // REQUIRED
            'Permanent' => true,
            'UserPoolId' => 'eu-west-XXXXXXXX', // REQUIRED
            'Username' => 'mjb@XXXX.com', // REQUIRED
           ]);
```
aws config

```
[profile qc-int]
sso_start_url=https://XXXXXX.awsapps.com/start
sso_region=eu-west-1
sso_account_id=XXXXXXXXXX 
```

### Possible Solution

If i update my config with an additional profile without the word profile works as expected

```
[profile qc-int]
sso_start_url=https://XXXXXX.awsapps.com/start
sso_region=eu-west-1
sso_account_id=XXXXXXXXXX 

[qc-int]
sso_start_url=https://XXXXXX.awsapps.com/start
sso_region=eu-west-1
sso_account_id=XXXXXXXXXX 

```
Also if i add profile to the profile name  ``` CredentialProvider::sso('profile qc-int');```  this is what the default provider is doing under the hood.

I propose that the sso function should prefix the profile name being passed to it with profile as makes the method more intuitive 

### SDK version used

3.252

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 7.2.26

**Comment by yenfryherrerafeliz** [comment]
Hi @stephen-barrow, thanks for opening this issue. We will investigate this and I will get back to you as soon as possible. I reviewed the PR you proposed but I think it will cause other problems, for example [here](https://github.com/aws/aws-sdk-php/blob/badab73e791c38410756388968b151e0e395105a/src/Credentials/CredentialProvider.php#L800) the profile name is standardized (the word "profile" is removed from the name) if the condition in the following [line](https://github.com/aws/aws-sdk-php/blob/badab73e791c38410756388968b151e0e395105a/src/Credentials/CredentialProvider.php#L793) is met. Probably, we need to standardized the profile name also when that [condition](https://github.com/aws/aws-sdk-php/blob/master/src/Credentials/CredentialProvider.php#L793) is not met as well. I will discuss this with the team and then I will update this thread.

Thanks!

**Comment by stobrien89** [comment]
Hi @stephen-barrow,

Thanks for reaching out.  I'd make sure your first profile is `[default]`.  The remainder of the profiles will need to start with the `profile` identifier.  You can read more about this [here](https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html#section-types). Hope this helps!

**Comment by stobrien89** [comment]
Hi @stephen-barrow,

My apologies, I skimmed through this one a little too quickly.  I think the initial intent here was to avoid any confusion and use the literal definition of profiles in the config file, but I see how this could be unintuitive. We'll mark this as a feature request for now to see what kind of traction this gets, but if we decide to implement this, we'd have to be very careful about not changing the default behavior so as to not break customers currently relying on it.

**Comment by stobrien89** [comment]
Hi @stephen-barrow, 

Thanks for raising the PR, as well as the feature request.  We had some improvements on the docket for the SSO provider, so we ended up taking care of this in #2628.  This should be available in today's release.  Let us know if you have any questions!
