### ISSUE TITLE
TimestreamWrite returns 404 after update from 3.240.7 to 3.252.3

### ISSUE THREAD

**Issue by erikdebruin** [aws/aws-sdk-php#2593]
### Describe the bug

After we updated our systems from 3.240.7 to 3.252.3 we noticed that we got the following error response:

> Error executing "WriteRecords" on "https://ingest.timestream.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://ingest.timestream.us-east-1.amazonaws.com` resulted in a `404 Not Found` response:
{"__type":"com.amazon.coral.service#UnknownOperationException"}
 UnknownOperationException (client):  - {"__type":"com.amazon.coral.service#UnknownOperationException"}

### Expected Behavior

A success result like:

```
object(Aws\Result)#997 (2) {
  ["data":"Aws\Result":private]=>
  array(2) {
    ["RecordsIngested"]=>
    array(3) {
      ["Total"]=>
      int(1)
      ["MemoryStore"]=>
      int(1)
      ["MagneticStore"]=>
      int(0)
    }
    ["@metadata"]=>
    array(4) {
      ["statusCode"]=>
      int(200)
      ["effectiveUri"]=>
      string(55) "https://ingest-cell2.timestream.us-east-1.amazonaws.com"
      ["headers"]=>
      array(4) {
        ["x-amzn-requestid"]=>
        string(26) "C734AUW5JCV4OMNAH5E7SL57BU"
        ["content-type"]=>
        string(26) "application/x-amz-json-1.0"
        ["content-length"]=>
        string(2) "65"
        ["date"]=>
        string(29) "Wed, 07 Dec 2022 13:02:24 GMT"
      }
      ["transferStats"]=>
      array(1) {
        ["http"]=>
        array(1) {
          [0]=>
          array(0) {
          }
        }
      }
    }
  }
  ["monitoringEvents":"Aws\Result":private]=>
  array(0) {
  }
}
```

### Current Behavior

The request fails with the response: 

```
Error executing "WriteRecords" on "https://ingest.timestream.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://ingest.timestream.us-east-1.amazonaws.com` resulted in a `404 Not Found` response:
{"__type":"com.amazon.coral.service#UnknownOperationException"}
 UnknownOperationException (client):  - {"__type":"com.amazon.coral.service#UnknownOperationException"}
```

### Reproduction Steps

Using SDK version 3.252.3, make a call like '$timestream_client->writeRecords([... valid options ...]) and look at the result.

### Additional Information/Context

I have not done a regression through previous releases to see which version between 3.240.7 and 3.252.3 introduced the issue. All I can tell is that it does NOT exist in version 3.240.7

### SDK version used

3.252.3

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 7.3.33, MacOS 13.0.1 + AWS Linux 2

**Comment by stobrien89** [comment]
Hi @erikdebruin,

Thanks for raising this. Sorry to hear about the issues.  I've identified the issue and will have a fix out ASAP.  In the meantime, you can either pin your version or provide `'endpoint_provider' => EndpointProvider::defaultProvider()` to your client config to work around this.  Thanks!

**Comment by stobrien89** [comment]
Hi @erikdebruin,

Fix is out and should be available in today's release.  Let me know if you're still having issues then.

**Comment by stobrien89** [comment]
Closing this for now, but let us know if anything else comes up.
