### ISSUE TITLE
Behavior of `proxy` configuration directive changed and broke in 3.243.0

### ISSUE THREAD

**Issue by onethumb** [aws/aws-sdk-php#2596]
### Describe the bug

In versions prior to `3.243.0`, including `3.242.1` using `proxy` through our service mesh worked as expected. 

We proxy local `http` requests on-instance in our service mesh to `https` requests remotely against S3. (This provides large performance benefits by avoiding TCP & TLS handshaking, while still maintaining end-to-end network encryption).

Starting in `3.243.0`, `cURL` appears to be using a different proxy mechanism, resulting in `400` response codes from our service mesh, rather than response codes from the upstream service.

### Expected Behavior

This is the behavior in `3.242.1`: 

```
-> Entering step attempt, name 'ApiCallAttemptMonitoringMiddleware'
-------------------------------------------------------------------

  no changes

*   Trying 127.0.0.1:9080...
* Connected to 127.0.0.1 (127.0.0.1) port 9080 (#0)
> HEAD http://my-bucket.s3.amazonaws.com/my-key HTTP/1.1
Host: my-bucket.s3.amazonaws.com
Proxy-Connection: Keep-Alive
X-Amz-User-Agent: aws-sdk-php/3.242.1 OS/Linux/5.15.0-1014-aws lang/php/8.1.6
aws-sdk-invocation-id: 57d1a4860ec6e894a61b9a47574cbc64
aws-sdk-retry: 0/0
User-Agent: aws-sdk-php/3.242.1 OS/Linux/5.15.0-1014-aws lang/php/8.1.6 GuzzleHttp/7

* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< x-amz-request-id: 1X9P79YW86AFJ322
< x-amz-id-2: KVfRqS49yYXJeARavEmCURYbpF89KGTBNrd9tpH0QLYPPJP7fI+wTtPjsqdPibdrGYMIF7kNmY4=
< content-type: application/xml
< date: Sun, 11 Dec 2022 17:25:30 GMT
< server: AmazonS3
<
* Connection #0 to host 127.0.0.1 left intact

<- Leaving step attempt, name 'ApiCallAttemptMonitoringMiddleware'
```

### Current Behavior

This is the behavior in `3.243.0`:

```
-> Entering step attempt, name 'ApiCallAttemptMonitoringMiddleware'
-------------------------------------------------------------------

  no changes

*   Trying 127.0.0.1:9080...
* Connected to 127.0.0.1 (127.0.0.1) port 9080 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to my-bucket.s3.amazonaws.com:443
> CONNECT my-bucket.s3.amazonaws.com:443 HTTP/1.1
Host: my-bucket.s3.amazonaws.com:443
Proxy-Connection: Keep-Alive

< HTTP/1.1 400 Bad Request
< server: nginx
< date: Sun, 11 Dec 2022 17:23:53 GMT
< content-type: text/html
< content-length: 150
<
* Received HTTP code 400 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 0

<- Leaving step attempt, name 'ApiCallAttemptMonitoringMiddleware'
```

### Reproduction Steps

```php
$proxyConfig = [
    'credentials' => false,
    'debug'       => true,
    'version'     => 'latest',
    'region'      => 'us-east-1',
    'scheme'      => 'http',
    'http'        => [
        'proxy' => 'http://127.0.0.1:9080',
    ],
];

$s3Client = new \Aws\S3\S3Client($proxyConfig);

$s3Client->headObject(
    [
        'Bucket' => 'my-bucket',
        'Key'    => 'my-key',
    ]
);
```

### Possible Solution

Not sure what the solution looks like, but it seems like maybe `cURL` is being used with the `proxy` option, rather than simply pointing at a different IP+port with the correct `Host` header like it used to?

Trying to use a config with more specific proxies, such as this, doesn't work and produces the same errors.

```
$proxyConfig = [
    'credentials' => false,
    'debug'       => true,
    'version'     => 'latest',
    'region'      => 'us-east-1',
    'scheme'      => 'http',
    'http'    => [
        'proxy' => [
            'http' => 'http://127.0.0.1:9080',
            'https' => 'http://127.0.0.1:9080',
        ]
    ]
];
```

### Additional Information/Context

Command-line `cURL` executions appear to confirm the hypothesis that the `proxy` option with `cURL` may be involved.

```
curl -vvvv -H 'Host: my-bucket.s3.amazonaws.com' http://127.0.0.1:9080/

*   Trying 127.0.0.1:9080...
* Connected to 127.0.0.1 (127.0.0.1) port 9080 (#0)
> GET / HTTP/1.1
> Host: my-bucket.s3.amazonaws.com
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< x-amz-bucket-region: us-east-1
< x-amz-request-id: RYQ4ZZR4GVRVHRFY
< x-amz-id-2: ydW49s86TQ63sJzEJHmriBHGTWYqyyt4xYdy4CtZsWfP3d2l9E9S5RXkyTPdfIzQiC13nDrp2Z4=
< content-type: application/xml
< transfer-encoding: chunked
< date: Sun, 11 Dec 2022 17:52:11 GMT
< server: AmazonS3
<
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host 127.0.0.1 left intact
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>RYQ4ZZR4GVRVHRFY</RequestId><HostId>ydW49s86TQ63sJzEJHmriBHGTWYqyyt4xYdy4CtZsWfP3d2l9E9S5RXkyTPdfIzQiC13nDrp2Z4=</HostId></Error>
```

vs 

```
curl -vvvv --proxy http://127.0.0.1:9080 https://my-bucket.s3.amazonaws.com/
*   Trying 127.0.0.1:9080...
* Connected to 127.0.0.1 (127.0.0.1) port 9080 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to my-bucket.s3.amazonaws.com:443
> CONNECT my-bucket.s3.amazonaws.com:443 HTTP/1.1
> Host: my-bucket.s3.amazonaws.com:443
> User-Agent: curl/7.81.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 400 Bad Request
< server: nginx
< date: Sun, 11 Dec 2022 17:51:59 GMT
< content-type: text/html
< content-length: 150
<
* Received HTTP code 400 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 0
curl: (56) Received HTTP code 400 from proxy after CONNECT
```

### SDK version used

3.243.0

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.1.6 on Ubuntu 22.04 'jammy' on t4g.large (graviton2)

**Comment by stobrien89** [comment]
Hi @onethumb,

Thanks a lot for reporting this—sorry to hear about the issues.  I believe this is related to #2550.  If that's the case, you can add `'endpoint_provider' => EndpointProvider::defaultProvider()` to your client config to mitigate this while we're working on a solution.

**Comment by stobrien89** [comment]
Hi @onethumb, @shandrew,

My initial debugging doesn't seem to indicate that we've affected proxies in any way, but it would be a tremendous help if you could let me know if this is still occurring on  >= `2.248.0` and if so, if using the config option I mentioned above resolves the issue.  Thanks!

**Comment by onethumb** [comment]
@stobrien89 Thanks for the speedy reply! I can confirm we see this behavior on `3.252.6` (the latest) as well. I can also confirm that `'endpoint_provider' => EndpointProvider::defaultProvider()` appears to resolve the issue. Thanks, and let me know if we can assist with debugging or validating any further.

**Comment by stobrien89** [comment]
@onethumb, 

Likewise!  Good to know.  Would you also be able to tell me which `guzzlehttp` (guzzle, psr7, promises) versions you have installed? Thanks again

**Comment by onethumb** [comment]
@stobrien89 

Sure. Here's the output of `composer show`:

```
guzzlehttp/guzzle                    7.5.0              Guzzle is a PHP HTTP client library
guzzlehttp/promises                  1.5.2              Guzzle promises library
guzzlehttp/psr7                      2.4.3              PSR-7 message implementation that also provides common utility methods
```

**Comment by stobrien89** [comment]
@onethumb, @shandrew, 

Figured out this was the result of client-provided schemes being overwritten by our endpoint rulesets.  This should be resolved in today's release, but please let me know if you're still running into issues.  Sorry again for the trouble!

**Comment by onethumb** [comment]
@stobrien89 Fix looks good over here. Thanks!
