### ISSUE TITLE
Token generated from Aws\Rds\AuthTokenGenerator->createToken() does not get accepted by pg_connect()

### ISSUE THREAD

**Issue by dreaddesign** [aws/aws-sdk-php#2597]
### Describe the bug

using direct CLI, this sample would work:

DBENDPOINT="my-rds.cn1tffyvlovu.us-east-2.rds.amazonaws.com" DBPORT=5432 DBREGION="us-east-2" DBUSER="iam_username" DBNAME="pg_db"; PGPASSWORD=$(aws rds generate-db-auth-token --region "$DBREGION" --hostname "$DBENDPOINT" --port "$DBPORT" --username "$DBUSER") PGSSLMODE=require psql -h "$DBENDPOINT" -U "$DBUSER" -d "$DBNAME" -p "$DBPORT"

taking the output of "echo $PGPASSWORD" and using that as the password in pgAdmin will also allow me to connect.

however, when using the php SDK, the token generated does not seem to work.

### Expected Behavior

the token generated from 

```php
$provider = CredentialProvider::env(); 

  $RdsAuthGenerator = new Aws\Rds\AuthTokenGenerator($provider);

  $token = $RdsAuthGenerator->createToken($endpoint, $region, $username, $lifetime = 15);
```

would successfully authenticate pg connection when used as the password for pg_connect()

### Current Behavior

passing the token generated to pg_connect always results in 
"Warning: pg_connect(): Unable to connect to PostgreSQL server: FATAL: PAM authentication failed for user "iam_dbuser"" when token is issued via Aws\Rds\AuthTokenGenerator 's createToken() method.

### Reproduction Steps

```php
use Aws\RDS\AuthTokenGenerator;
use Aws\Credentials\CredentialProvider;
use GuzzleHttp\Promise;
use GuzzleHttp\Promise\RejectedPromise;

$provider = CredentialProvider::env();
$RdsAuthGenerator = new Aws\Rds\AuthTokenGenerator($provider);
$token = $RdsAuthGenerator->createToken($endpoint, $region, $username, $lifetime = 15);
```

### SDK version used

3.252.5

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.0.24 (cli) (built: Sep 29 2022 22:26:26) ( NTS ) - Ubuntu 18.04

**Comment by dreaddesign** [comment]
An additional note that may not have been clear. i can run 

```
DBENDPOINT="my-rds.cn1tffyvlovu.us-east-2.rds.amazonaws.com" DBPORT=5432 DBREGION="us-east-2" DBUSER="iam_username" DBNAME="db_name"; PGPASSWORD=$(aws rds generate-db-auth-token --region "$DBREGION" --hostname "$DBENDPOINT" --port "$DBPORT" --username "$DBUSER")
echo $PGPASSWORD
```

taking the output from CLI and hardcoding that into pg_connect() successfully authenticates.

**Comment by yenfryherrerafeliz** [comment]
Hi @dreaddesign, thanks for opening this issue. I tried to reproduce the reported behavior, but I do not have any issues on my end. I was able to successfully generate a token a connect to a postgres instance. 

Here is a list of things to verify and that can cause the authentication to fail:
- Please make sure you are specifying the correct region to generate the token
- Please make sure that the endpoint parameter is composed of the host and the port. Example: testinstace.someid.region.rds.amazonaws.com:5432
- Please make sure that the  given credentials are the correct one. I see you are specifying credentials from the environment, but did you make sure those are the correct one?, are those the ones the cli is using to generate the token?

Here is the code snippet I used:
```php
$key = 'YOUR_ACCESS_KEY';
$secret = 'YOUR_SECRET_ID';
$cred = new Credentials($key, $secret);
$tokenGenerator = new AuthTokenGenerator($cred);
$host = 'YOURHOST';
$port = 5432;
$user = "YOURUSER";
$region = "YOURREGION";
$token = $tokenGenerator->createToken(
    $host.":".$port,
    $region,
    $user
);
$connectionString = "host=$host port=$port dbname=test_db user=$user password=$token";
$conn = pg_connect($connectionString);
if (!$conn) {
    echo "Connection failed!";
    die('Bye');
}

echo "Connected!";
$result = pg_query($conn, "select * from testtable");
var_dump(pg_fetch_all($result));
pg_close($conn);
```

Thanks!
