### ISSUE TITLE
Waiter for ELB registration / deregistration

### ISSUE THREAD

**Issue by SteveEdson** [aws/aws-sdk-php#260]
Now that ELBs support [Connection Draining](http://aws.typepad.com/aws/2014/03/elb-connection-draining-remove-instances-from-service-with-care.html?sc_channel=sm&sc_campaign=service&sc_publisher=tw&sc_medium=std&sc_content=elgderegister&sc_category=launch), it is difficult to know when an ELB has fully been deregistered. It would be nice if a waiter could be added, like the ones available for EC2, S3 etc, rather than having to poll the status, or sleep for a fixed amount of time.

Thanks

**Comment by jeremeamia** [comment]
We've added this to our internal backlog.
