### ISSUE TITLE
Error when trying to revoke token

### ISSUE THREAD

**Issue by chamra** [aws/aws-sdk-php#2604]
### Describe the bug

I'm trying to use `revokeToken()` to revoke a token and I'm getting this error,

```
Operation not found: RevokeToken
```

I have these auth flows enabled,

```
ALLOW_CUSTOM_AUTH
ALLOW_REFRESH_TOKEN_AUTH
ALLOW_USER_PASSWORD_AUTH
ALLOW_USER_SRP_AUTH
```

### Expected Behavior

refresh token to revoked 

### Current Behavior

throwing an error

### Reproduction Steps

1. create an object of `CognitoIdentityProviderClient` with passing relevant credentials 
2. call `revokeToken()` and pass in the refresh token 

### SDK version used

3.33.4

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 7.4.26, Linux alpine

**Comment by stobrien89** [comment]
Hi @chamra,

Sorry to hear about the issues.  The PHP SDK version you provided was released on 8/21/2017.  The operation you're trying to use was released on 6/10/2021. This means you'll need to be using version `>= 3.184.1` in order to use it.  Hope this helps!
