### ISSUE TITLE
Even when 'bucket_endpoint' is true, it started adding bucket name to URL

### ISSUE THREAD

**Issue by sentiasa** [aws/aws-sdk-php#2615]
### Describe the bug

My endpoint is https://s3.example.com and I am using `'bucket_endpoint' => true` in my config.

In v3.242.1, it does the call to the proper endpoint:
https://s3.example.com

However, starting from v3.243.0 onwards, it tries to call:
https://bucket_name.s3.example.com

I did some debugging in BucketEndpointMiddleware, on L75 
```
// 3.242.1 (working)
$uri = $request->getUri(); // host is s3.example.com

// 3.243.0 (not working)
$uri = $request->getUri(); // host is bucket_name.s3.example.com
```

### Expected Behavior

When `'bucket_endpoint' => true`, it should return the endpoint without bucket name appended to the beginning.

### Current Behavior

Even when `'bucket_endpoint' => true`, it appended the bucket name to the beginning

### Reproduction Steps

I'm using Laravel. In your filesystem.php config set `'bucket_endpoint' => true` and `'url' => https://s3.example.com`

- Install v3.242.1

```
$storage = Storage::disk('s3')->url('test.pdf');
dd($storage);  // https://s3.example.com/test.pdf
```

- Change version to v3.243.0
```
$storage = Storage::disk('s3')->url('test.pdf');
dd($storage);  // https://bucket_name.s3.example.com/test.pdf
```

### SDK version used

3.243.0

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

8.0

**Comment by stobrien89** [comment]
Hi @sentiasa,

Sorry to hear about the issues.  I think this is a result of our defaulting to host-style uris for S3 buckets when we made a change to how endpoints are resolved. 

This may be resolved by adding `'use_path_style_endpoint` => true` to your client config. If not, I'd be happy to dig into this a bit further if you could provide a reproducible example.

**Comment by sentiasa** [comment]
This fixes the issue indeed.

Thank you

**Comment by stobrien89** [comment]
Sorry you were bitten by that.  I'll see about getting some updates to our docs, but there were certain legacy behaviors we were unable to retain as a part of the endpoint resolution change.  This basically means that users will need to be more declarative about the type of endpoint they are expecting. Let us know if you have any questions!

**Comment by WillNilges** [comment]
Turns out that extension was using v 3.67 of this sdk. I updated it and am now getting 403's. Still weird but it's progress!

**Comment by WillNilges** [comment]
Fixed my issues! Forking the extension and updating the SDK was the solution. I also had to remove the temp dir specification.
