### ISSUE TITLE
Uncaught exception: 'InvalidArgumentException' in Aws\S3\S3Client->createPresignedRequest

### ISSUE THREAD

**Issue by ars-oliveira** [aws/aws-sdk-php#2624]
### Describe the bug

Cannot sign any s3 file

### Expected Behavior

Get a signed s3 url

### Current Behavior

ERROR: Uncaught exception: 'InvalidArgumentException' 

Stack trace:
Uncaught exception: 'InvalidArgumentException' with message 'Found 1 error while validating the input provided for the GetObject operation:
[Key] must be a string or an object that implements __toString(). Found array(8)'
Stack trace: #0 /vendor/aws/aws-sdk-php/src/Middleware.php(84): Aws\Api\Validator->validate('GetObject', Object(Aws\Api\StructureShape), Array)
#1 /vendor/aws/aws-sdk-php/src/S3/S3Client.php(594): Aws\Middleware::Aws\{closure}(Object(Aws\Command), NULL)
#2 /vendor/aws/aws-sdk-php/src/S3/S3Client.php(617): Aws\S3\S3Client::Aws\S3\{closure}(Object(Aws\Command), NULL)
#3 /vendor/aws/aws-sdk-php/src/S3/S3Client.php(551): Aws\S3\S3Client::Aws\S3\{closure}(Object(Aws\Command), NULL)
#4 /vendor/aws/aws-sdk-php/src/S3/S3Client.php(570): Aws\S3\S3Client::Aws\S3\{closure}(Object(Aws\Command), NULL)
#5 /vendor/aws/aws-sdk-php/src/Middleware.php(57): Aws\S3\S3Client::Aws\S3\{closure}(Object(Aws\Command), NULL)
#6 /vendor/aws/aws-sdk-php/src/S3/SSECMiddleware.php(59): Aws\Middleware::Aws\{closure}(Object(Aws\Command), NULL)
#7 /vendor/aws/aws-sdk-php/src/IdempotencyTokenMiddleware.php(77): Aws\S3\SSECMiddleware->__invoke(Object(Aws\Command), NULL)
#8 [internal function]: Aws\IdempotencyTokenMiddleware->__invoke(Object(Aws\Command))
#9 /vendor/aws/aws-sdk-php/src/functions.php(363): call_user_func(Object(Aws\IdempotencyTokenMiddleware), Object(Aws\Command))
#10 /vendor/aws/aws-sdk-php/src/S3/S3Client.php(475): Aws\serialize(Object(Aws\Command))

### Reproduction Steps

```php
<?php

function S3_signURL($objectKey, $zone = 'us-east-2') {
    $bucket = 'my-bucket';

    $clientS3 = new Aws\S3\S3Client(['profile' => 'default', 'version' => '2006-03-01', 'region' => $zone]);

    $cmd = $clientS3->getCommand('GetObject', [ 'Bucket' => $bucket, 'Key' => $objectKey ]);
    $request = $clientS3->createPresignedRequest($cmd, '+10 minutes');

    // Get the actual presigned-url
    return (string)$request->getUri();
}

echo S3_signURL('/path/to/my/s3/bucket/file');

?>
```

### SDK version used

3.257.3

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.2.0 (cli) (built: Dec  9 2022 16:55:44) (NTS) Copyright (c) The PHP Group Zend Engine v4.2.0, Copyright (c) Zend Technologies     with Xdebug v3.2.0, Copyright (c) 2002-2022, by Derick Rethans     with Zend OPcache v8.2.0, Copyright (c), by Zend Technologies

**Comment by SamRemis** [comment]
Hi @ars-oliveira,
Thank you for opening this issue.  Your code looks right to me, and when I copied/pasted the above, I was able to successfully get a pre-signed URL that allowed me to fetch the object.  

The error you're getting would have been due to a syntax error; is it possible that whatever you're passing in as $objectKey is an array with a length of 8?

**Comment by ars-oliveira** [comment]
You're right. The problem was in my code. Sorry for reporting a problem that doesn't actually exists.
