### ISSUE TITLE
Symfony 6.2 require

### ISSUE THREAD

**Issue by BudayPavel** [aws/aws-sdk-php#2629]
### Describe the bug

Method “Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()” might add “TreeBuilder” as a native return type declaration in the future. Do the same in implementation “Aws\Symfony\DependencyInjection\Configuration” now to avoid errors or add an explicit @return annotation to suppress this message.

### Expected Behavior

Without notice 

### Current Behavior

Method “Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()” might add “TreeBuilder” as a native return type declaration in the future. Do the same in implementation “Aws\Symfony\DependencyInjection\Configuration” now to avoid errors or add an explicit @return annotation to suppress this message.

### Reproduction Steps

Run phpunit

### SDK version used

~2.0

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP >=8.1 (Ubuntu 22.04)

**Comment by stobrien89** [comment]
Hi @BudayPavel,

Sorry to hear about this issues.  Version 2 of the SDK has been deprecated for some time— We don't currently support it.  I have not seen or heard of this issue occurring with version 3 of the SDK.  The best we're able to do is recommend upgrading when possible.
