### ISSUE TITLE
Is PHP8 supported? All attempts to use this lib fail because of guzzlehttp errors

### ISSUE THREAD

**Issue by Gelembjuk** [aws/aws-sdk-php#2636]
### Describe the bug

I was not able to use this lib for simples operation.

I have PHP8 (PHP 8.0.20 (cli))

I have created new project, downloaded actual composer and installed only this AWS lib

When i try to use for some basic Amazon S3 operation i have the error

`PHP Fatal error:  Uncaught Error: Undefined constant GuzzleHttp\ClientInterface::MAJOR_VERSION in /var/www/smestorage/NAA_Tools/application/src/vendor/guzzlehttp/guzzle/src/Utils.php:116
Stack trace:
#0 /var/www/smestorage/NAA_Tools/application/src/vendor/guzzlehttp/guzzle/src/functions.php(71): GuzzleHttp\Utils::defaultUserAgent()
#1 /var/www/smestorage/public_html/build/vendor/guzzlehttp/guzzle/src/Client.php(278): GuzzleHttp\default_user_agent()
#2 /var/www/smestorage/public_html/build/vendor/guzzlehttp/guzzle/src/Client.php(76): GuzzleHttp\Client->configureDefaults(Array)
#3 /var/www/smestorage/NAA_Tools/application/src/vendor/aws/aws-sdk-php/src/Handler/GuzzleV6/GuzzleHandler.php(26): GuzzleHttp\Client->__construct()
#4 /var/www/smestorage/NAA_Tools/application/src/vendor/aws/aws-sdk-php/src/functions.php(279): Aws\Handler\GuzzleV6\GuzzleHandler->__construct()
#5 /var/www/smestorage/NAA_Tools/application/src/vendor/aws/aws-sdk-php/src/ClientResolver.php(824): Aws\default_http_handler()
#6 /var/www/smestorage/NAA_Tools/application/src/vendor/aws/aws-sdk-php/src/ClientResolver.php(335): Aws\ClientResolver::_default_handler(Array)
#7 /var/www/smestorage/NAA_Tools/application/src/vendor/aws/aws-sdk-php/src/AwsClient.php(221): Aws\ClientResolver->resolve(Array, Object(Aws\HandlerList))
#8 /var/www/smestorage/NAA_Tools/application/src/vendor/aws/aws-sdk-php/src/S3/S3Client.php(358): Aws\AwsClient->__construct(Array)
#9 /var/www/smestorage/NAA_Tools/application/Tools/Defstorexport/S3.php(41): Aws\S3\S3Client->__construct(Array)
`

I tried to fix this error with small edit in guzzlehttp files. I fixed guzzlehttp/guzzle/src/Utils.php . But the next error is 

`PHP Fatal error:  Uncaught Error: Call to undefined method GuzzleHttp\Promise\Coroutine::of() in /var/www/smestorage/NAA_Tools/application/src/vendor/aws/aws-sdk-php/src/Multipart/AbstractUploadManager.php:97
Stack trace:
#0 /var/www/smestorage/NAA_Tools/application/src/vendor/aws/aws-sdk-php/src/Multipart/AbstractUploadManager.php(83): Aws\Multipart\AbstractUploadManager->promise()
#1 /var/www/smestorage/NAA_Tools/application/Tools/Defstorexport/S3.php(52): Aws\Multipart\AbstractUploadManager->upload()
#2 /var/www/smestorage/NAA_Tools/application/Tools/Defstorexport/S3.php(31): NAATools\Tools\Defstorexport\S3->uploadFileWithMPU('gelembjuk1', 'archive_export/...', '../tmp/archive_...', 1048576)
#3 /var/www/smestorage/NAA_Tools/application/Tools/Defstorexport.php(140): NAATools\Tools\Defstorexport\S3->uploadFile('gelembjuk1', 'archive_export/...', '../tmp/archive_...')
#4 /var/www/smestorage/NAA_Tools/application/Tools/Defstorexport.php(94): NAATools\Tools\Defstorexport->uploadArchive()
#5 /var/www/smestorage/NAA_Tools/application/Application.php(65): NAATools\Tools\Defstorexport->run()
#6 /var/www/smestorage/NAA_Tools/run.php(5): NAATools\Application->action()
#7 {main}
  thrown in /var/www/smestorage/NAA_Tools/application/src/vendor/aws/aws-sdk-php/src/Multipart/AbstractUploadManager.php on line 97`

Also, i tried to downgrade guzzlehttp to 6.5.8 version and i got same error as above 

Is there ay solution just to try this library?

### Expected Behavior

No error should happen

### Current Behavior

Error happens

### Reproduction Steps

- Get php 8 on Centos 7
- Create simplest php file. Init composer and add "composer require aws/aws-sdk-php" .
- Try to execute any simplest AWS amazon s3 php script like https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-multipart-upload.html 

### SDK version used

3.258.6

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.0.20 (cli) (built: Jun  8 2022 00:33:06) ( NTS gcc x86_64 ) Copyright (c) The PHP Group Zend Engine v4.0.20, Copyright (c) Zend Technologies. Centos 7

**Comment by stobrien89** [comment]
Hi @Gelembjuk,

Sorry to hear about the issues.  It sounds like you might have more than one installation of guzzle loaded.  You might want to check the `application` directory's composer.json file to see if there's a conflict.  If that's the case, I suspect the version that the other installation has resolved to is lower than what we require.

**Comment by Gelembjuk** [comment]
I do not have more 1 installation. I have installed only aws-sdk-php and it pulled guzzle as dependency . I didn't install guzzle separately . In my config.json there is only aws-sdk-php, nothing else.
When i run 
"composer show" i see only 1 guzzle installed and it is the current latest version

**Comment by yenfryherrerafeliz** [comment]
Hi @Gelembjuk, I tried to reproduce the behavior that you reported but I was unable to. Everything is working fine on my end. I have seen this issue before and it happens when there are two guzzle versions conflicting, but I am not sure if this is your case as well, however, would it be possible for you to run ``` composer update ``` and see if the problem get fixed after this?

Thanks!
