### ISSUE TITLE
API Gateway – createUsagePlan method and the relevant stack is not implemented in the SDK

### ISSUE THREAD

**Issue by izharaazmi** [aws/aws-sdk-php#2641]
### Describe the bug

According to the [documentation page here](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-apigateway-2015-07-09.html#createusageplan) we should be able to invoke the `createUsagePlan` method. However the SDK does not support that method call yet.

### Expected Behavior

The Method should work as mentioned in the documentation

### Current Behavior

Returns an exception that this method is not supported.

```
Uncaught InvalidArgumentException: Unknown operation: CreateUsagePlan 
```

### Reproduction Steps

Not actually a bug in any existing feature, instead a whole feature is missing. 
So I don't think a code sample would be necessary. 

Just looking into the repo should make it clear. Let me know if more information is still required.

### Possible Solution

Implement this feature

### SDK version used

3.258.12

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 7.4.27 (cli), MacOS Ventura 13.1 (22C65)

**Comment by izharaazmi** [comment]
Hi @stobrien89, Thanks for the quick response.

I am using `ApiGatewayV2Client` instead of `ApiGatewayClient`

```php
$client = new ApiGatewayV2Client([
	'region'      => $region,
	'version'     => '2018-11-29',
	'credentials' => $credentials,
]);
```

As the rest of my implementations use the v2 client only, switching clients might be impossible.

Shouldn't `ApiGatewayV2Client` also support it, or I am missing something here?

**Comment by izharaazmi** [comment]
If I understand correctly, I was expecting the model entry in the file `src/data/apigatewayv2/2018-11-29/api-2.json.php`

**Comment by izharaazmi** [comment]
I tried looking up the model file you mentioned, but that file seems to be nonexistent in the `master` branch.

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/6706189/220457382-640e93f6-ba6c-493e-9742-6cdef76c6249.png">

The `src/data/apigateway/` only contains the version `2015-07-09`

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/6706189/220458162-774c4e41-9ae8-40a9-8a76-aaa6b94c2719.png">

**Comment by stobrien89** [comment]
Hi @izharaazmi,

My apologies, `2015-07-09` is the version I meant to provide there.  Unfortunately, it doesn't appear that usage plans are supported with HTTP (and Websocket) APIs at this time, meaning usage plans are not available with APIs created/managed using the `ApiGatewayV2Client`.

Their docs don't do a great job at explicitly mentioning this, but you can see in their [Developer Guide](https://docs.aws.amazon.com/apigateway/latest/developerguide/rest-api-distribute.html) that this is only documented as being supported with REST APIs.  If you expand the "Working with HTTP APIs" and "Working with WebSocket APIs" sections on the sidebar, you can see neither of those API types have "Distribute" sections in their documentation. It's possible that they could add support for this in the future.

Closing for now, but let us know if you have any additional questions.
