### ISSUE TITLE
S3 retry overrides retry decider for client exceptions (e.g. 404 not found)

### ISSUE THREAD

**Issue by mrtus** [aws/aws-sdk-php#2650]
### Describe the bug

When a request returns a client exception (400 => 499), the "default decider" of retries is completely overridden.

The default decider configures checks for >=500 status codes, but afterwards the `SClient::825` checks for `RequestException` anyway.

![image](https://user-images.githubusercontent.com/8998239/222216939-0b6752b2-b2c1-464f-b51f-1691b441a570.png)

Or am I simply expecting the wrong behaviour?

### Expected Behavior

When a request returns 404 there should be no retries.
And maybe even 40x should never have retries?

### Current Behavior

When a request returns 40x there are retries.

### Reproduction Steps

- Configure retries on the S3Client
- Try to fetch an unfindable file

### SDK version used

3.257.5

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

n/a

**Comment by yenfryherrerafeliz** [comment]
Hi @mrtus, thanks for opening this issue. I can confirm this is a bug. We are aware of this issue and I expect to post a PR in the following weeks for fixing this.

Thanks!

**Comment by mrtus** [comment]
@yenfryherrerafeliz Thank you for getting back to me so quickly!

I'm happy to hear this is indeed a bug and not expected behaviour. I'm looking forward to the fix!

**Comment by stobrien89** [comment]
Hi @mrtus,

A fix for this has been merged and is available in the latest release. Please let us know us know if you have any additional questions.
