### ISSUE TITLE
ImageId requried despite using a launch template

### ISSUE THREAD

**Issue by 4am-martin** [aws/aws-sdk-php#2653]
### Describe the bug

When calling runInstances with LaunchTemplate structure specified, the call doesn't pass local validation due to missing ImageId parameter.

### Expected Behavior

Validation should take Launch Templates into consideration. The request itself is valid.

### Current Behavior

Running the following code will result in an immediate error:

```
$result = $ec2->runInstances([
            'DryRun' => false,
            'LaunchTemplate' => [
                'LaunchTemplateName' => 'test-template',
                'Version' => 1
            ],
            'MinCount' => 1,
            'MaxCount' => 1
        ]);
```

The specified Launch Template does have an ImageId specified and works fine when interacted with via CLI. Upon executing the above code the following error message is generated:

> Found 1 error while validating the input provided for the RunInstances operation: [ImageId] is missing and is a required parameter 

### Reproduction Steps

Running the following code will result in an immediate error:

```
$result = $ec2->runInstances([
            'DryRun' => false,
            'LaunchTemplate' => [
                'LaunchTemplateName' => 'test-template',
                'Version' => 1
            ],
            'MinCount' => 1,
            'MaxCount' => 1
        ]);
```

### Possible Solution

Use CLI:

```
aws --profile XXXXX ec2 run-instances --launch-template LaunchTemplateName=test-template --region eu-west-2
```

### SDK version used

3.33.4

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.1.2-1ubuntu2.11 / Ubuntu Jammy 22.04.02 LTS

**Comment by 4am-martin** [comment]
I resolved the issue, for some reason "composer require aws/aws-sdk-php" installed an ancient version of the SDK

**Comment by stobrien89** [comment]
Hi @4am-martin, 

Thanks for letting us know!
