### ISSUE TITLE
Deprecated: Creation of dynamic property `Aws\HashingStream::$stream` is deprecated

### ISSUE THREAD

**Issue by ruudk** [aws/aws-sdk-php#2660]
### Describe the bug

https://github.com/aws/aws-sdk-php/blob/9c38c82b7d3fb2b15957e71cae3957450e131ed8/src/HashingStream.php#L31

But there is no property defined.

### Expected Behavior

Initialize the property, to remove the dynamic property creation.

### Current Behavior

Property does not exist but is created dynamically.

### Reproduction Steps

See above.

### Possible Solution

It should define 

```
private \Psr\Http\Message\StreamInterface $stream;
```

### Additional Information/Context

[Dynamic Properties are deprecated in PHP 8.2](https://php.watch/versions/8.2/dynamic-properties-deprecated)

### SDK version used

3.261.7

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

8.2.3

**Comment by stobrien89** [comment]
Hi @ruudk,

Thanks for raising this.  We actually have a PR in our backlog for this that I'll try to get merged today.  We don't 'officially' support 8.2 just yet, but we've added it to our CI to get ahead of breaking other libraries that do.

**Comment by stobrien89** [comment]
#2649 has been merged and this should be resolved after today's release.  Let us know if anything else comes up!
