### ISSUE TITLE
PHP8.2: utf8_encode deprecated

### ISSUE THREAD

**Issue by noodle69** [aws/aws-sdk-php#2667]
### Describe the bug

from https://github.com/aws/aws-sdk-php/blob/f5c8142d43846194bbb3bb40b18e7f6df2788409/src/Token/SsoTokenProvider.php#L157-L163

you use utf8_encode that is deprecated since PJP8.2

### Expected Behavior

having correct sso token location

### Current Behavior

error when trying to get sso token location

### Reproduction Steps

calling getTokenLocation from SsoTokenProvider

### Possible Solution

prefer using 
```
- utf8_encode($string);
+ mb_convert_encoding($string, 'UTF-8', mb_list_encodings());
```

### SDK version used

3.262.3

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP8.2

**Comment by stobrien89** [comment]
Hi @noodle69,

Thanks for raising this.  We should be able to get a fix out sometime this week.
