### ISSUE TITLE
AWS SSO Credential Provider expects sso_region be configured in the profile, not the sso-session

### ISSUE THREAD

**Issue by tim-hitchins-ekkosense** [aws/aws-sdk-php#2668]
### Describe the bug

The aws config file generated by `aws configure sso` (version `aws-cli/2.11.6 Python/3.11.2 Linux/5.10.102.1-microsoft-standard-WSL2 exe/x86_64.ubuntu.20 prompt/off`) looks like the following:

```
[profile dev]
sso_session = SessionName
sso_account_id = 123456789123
sso_role_name = ReadOnlyAccess
region = eu-west-1
output = json
[sso-session SessionName]
sso_start_url = https://example.awsapps.com/start/
sso_region = eu-west-1
sso_registration_scopes = sso:account:access
```

But in [`\Aws\Credentials\CredentialProvider::getCredentialsFromSsoService` line 939](https://github.com/aws/aws-sdk-php/blob/master/src/Credentials/CredentialProvider.php#L939) as of version 3.262.3 it expects `sso_region` to be configured in the profile.

### Expected Behavior

`getCredentialsFromSsoService` should either look for an existent profile key.

### Current Behavior

`getCredentialsFromSsoService` looks for non-existent profile key `sso_region`.

### Reproduction Steps

```
tim@wsl:~/critical-master$ aws configure sso
SSO session name (Recommended): SessionName
SSO start URL [None]: https://example.awsapps.com/start/
SSO region [None]: eu-west-1
SSO registration scopes [sso:account:access]:
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://device.sso.eu-west-1.amazonaws.com/

Then enter the code:

JQWD-TBFQ
tcgetpgrp failed: Not a tty
There are 5 AWS accounts available to you.
Using the account ID 123456789123
There are 2 roles available to you.
Using the role name "ReadOnlyAccess"
CLI default client Region [eu-west-1]:
CLI default output format [json]:
CLI profile name [123456789123_ReadOnlyAccess]: dev

To use this profile, specify the profile name using --profile, as shown:

aws s3 ls --profile dev
```

```
use Aws\Credentials\CredentialProvider;

putenv('HOME=/home/tim');
$provider = CredentialProvider::sso('dev', null);
$credentials = $provider()->wait();
```

### Possible Solution

I'm not exactly sure what the fix is, but `getCredentialsFromSsoService` should either look at `$ssoProfile['region']`, or be passed in the `$ssoSession` as well. Alternatively, `$ssoProfile['sso_region']` could be set to `$ssoSession['sso_region']`.

### Additional Information/Context

Introduced in https://github.com/aws/aws-sdk-php/releases/tag/3.257.9 when new SSO structure was implemented I think.

I'm happy to open a PR if given guidance on the preferred possible solution

### SDK version used

3.262.3

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

```
aws-cli/2.11.6 Python/3.11.2 Linux/5.10.102.1-microsoft-standard-WSL2 exe/x86_64.ubuntu.20 prompt/off
```

```
PHP 8.1.16 (cli) (built: Feb 14 2023 18:34:53) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.16, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.16, Copyright (c), by Zend Technologies
    with Xdebug v3.2.0, Copyright (c) 2002-2022, by Derick Rethans
```

```
tim@wsl:~/tools/release-tickets$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```

**Comment by SamRemis** [comment]
Hi @tim-hitchins-ekkosense , 
Just to update, I've confirmed this is a bug and am working on a fix.  Hoping to get this out in tomorrow's release.  Thank you for bringing this to our attention.  I'll tag this issue in the PR once it's up.  
-Sam

**Comment by yenfryherrerafeliz** [comment]
Hi @tim-hitchins-ekkosense, the fix has now been merged. Your issue should be fixed by now, but would it be possible for you to confirm?

Thanks!

**Comment by yenfryherrerafeliz** [comment]
@tim-hitchins-ekkosense, sorry, the fix should be available after today's release, so that you can test after.

Thanks!
