### ISSUE TITLE
Expection Error Code is wrong for Unconfirmed User

### ISSUE THREAD

**Issue by azamalvi** [aws/aws-sdk-php#2685]
### Describe the bug

I am using this package in my Symfony project. The scenario is that I have registerd a new user and it is created successfully but it's status is `unconfirmed`. Now that user tries to login with valid credentials using `AdminInitiateAuth` api then error code should be `UserNotConfirmedException` but it is returning `NotAuthorizedException`

### Expected Behavior

Error code with a valid credentials and unconfirmed user should be `UserNotConfirmedException`

### Current Behavior

I am using `AdminInitiateAuth` with `AuthFlow` as `ADMIN_NO_SRP_AUTH` and it throws error code `NotAuthorizedException` with a valid credentials and unconfirmed user.

### Reproduction Steps

Just Register a new user and do not confirmed it's status. It should be unconfirmed. Now try to login with valid credentils. 

### SDK version used

3.252.3

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.1

**Comment by yenfryherrerafeliz** [comment]
Hi @azamalvi, sorry to hear about your issues. Could you please provide a sample code that we can use to reproduce this issue.

Thanks!

**Comment by azamalvi** [comment]
> Hi @azamalvi, sorry to hear about your issues. Could you please provide a sample code that we can use to reproduce this issue.
> 
> Thanks!

Here is the basic code that I'm using in my application. Unfortunately, there are no testing credentials, so you need to change the code accordingly..


```
<?php

........
use Aws\CognitoIdentityProvider\CognitoIdentityProviderClient;
.........

class MyClass{
....
    function getCognitoClient(): CognitoIdentityProviderClient
    {
        return new CognitoIdentityProviderClient([
            'version' => $this->awsVersion,
            'region' => $this->awsRegion,
            'credentials' => [
                'key' => $this->awsKey,
                'secret' => $this->awsSecret
            ]
        ]);
    }

    function cognitoSecretHash($username): string
    {
        $hash = hash_hmac(
            'sha256',
            $username . $this->clientId,
            $this->clientSecret,
            true
        );

        return base64_encode($hash);
    }

    function loginUser($data): array
    {
        try {
            $result = $this->getCognitoClient()->AdminInitiateAuth([
                'ClientId' => $this->clientId,
                'UserPoolId' => $this->poolId,
                'AuthFlow' => 'ADMIN_NO_SRP_AUTH',
                'AuthParameters' => [
                    'USERNAME' => $data['username'],
                    'PASSWORD' => $data['password'],
                    'SECRET_HASH' => $this->cognitoSecretHash($data['username'])
                ]
            ]);
            .......
        } catch (CognitoIdentityProviderException $e) {
            var_dump($e); // you can check the error code and respose here            
            $response = [
                'error' => $e->getAwsErrorMessage(),
                'code' => $e->getAwsErrorCode()
            ];
        }

        .........
    }
```

**Comment by yenfryherrerafeliz** [comment]
@azamalvi seems like you are providing a wrong password to the unconfirmed used and that is why you are getting a "NotAuthorizedException". I just tried on my end with an unconfirmed user and see below:
```console
﻿GuzzleHttp\Exception\ClientException: Client error: `POST https://cognito-idp.us-east-2.amazonaws.com` resulted in a `400 Bad Request` response:
{"__type":"UserNotConfirmedException","message":"User is not confirmed."}
```
But if I provide wrong user credentials see what I get:
```console
GuzzleHttp\Exception\ClientException: Client error: `POST https://cognito-idp.us-east-2.amazonaws.com` resulted in a `400 Bad Request` response:
{"__type":"NotAuthorizedException","message":"Incorrect username or password."}
```

So, can you please confirm that you are providing the right credentials?, if so, then could you please provide debug logs so we can investigate this further?. You can enable debug logs by passing debug parameter set to true to the client. Please see below:

```php
$client = new CognitoIdentityProviderClient([
    'version' => 'latest',
    'region' => getenv('TEST_REGION'),
    'debug' => true
]);
```

Thanks!

**Comment by azamalvi** [comment]
> @azamalvi seems like you are providing a wrong password to the unconfirmed used and that is why you are getting a "NotAuthorizedException". I just tried on my end with an unconfirmed user and see below:
> 
> ```
> GuzzleHttp\Exception\ClientException: Client error: `POST https://cognito-idp.us-east-2.amazonaws.com` resulted in a `400 Bad Request` response:
> {"__type":"UserNotConfirmedException","message":"User is not confirmed."}
> ```
> 
> But if I provide wrong user credentials see what I get:
> 
> ```
> GuzzleHttp\Exception\ClientException: Client error: `POST https://cognito-idp.us-east-2.amazonaws.com` resulted in a `400 Bad Request` response:
> {"__type":"NotAuthorizedException","message":"Incorrect username or password."}
> ```
> 
> So, can you please confirm that you are providing the right credentials?, if so, then could you please provide debug logs so we can investigate this further?. You can enable debug logs by passing debug parameter set to true to the client. Please see below:
> 
> ```
> $client = new CognitoIdentityProviderClient([
>     'version' => 'latest',
>     'region' => getenv('TEST_REGION'),
>     'debug' => true
> ]);
> ```
> 
> Thanks!

I enabled the debug mode and now this is the output when I try to login with a valid credentials



`-> Entering step init, name 'idempotency_auto_fill' --------------------------------------------------- command was set to array(3) { ["instance"]=> string(32) "000000004fc6aef80000000001423bb8" ["name"]=> string(17) "AdminInitiateAuth" ["params"]=> array(7) { ["ClientId"]=> string(26) "4p......iu" ["UserPoolId"]=> string(19) "us-.....NU" ["AuthFlow"]=> string(17) "ADMIN_NO_SRP_AUTH" ["AuthParameters"]=> array(3) { ["USERNAME"]=> string(23) "tes....or.com" ["PASSWORD"]=> string(8) "A...2" ["SECRET_HASH"]=> string(44) "3sfOK....wzpYloS4YdHvo/o5/pFU20=" } ["ClientMetadata"]=> array(1) { ["HOST_TYPE"]=> string(2) "MT" } ["@http"]=> array(1) { ["debug"]=> resource(29) of type (stream) } ["@context"]=> array(0) { } } } request was set to array(0) { } -> Entering step validate, name 'validation' -------------------------------------------- no changes -> Entering step build, name 'builderV2' ---------------------------------------- request.instance was set to 000000004fc6a94b0000000001423bb8 request.method was set to POST request.headers was set to array(4) { ["X-Amz-Security-Token"]=> string(7) "[TOKEN]" ["Host"]=> array(1) { [0]=> string(35) "cognito-idp.us-east-1.amazonaws.com" } ["X-Amz-Target"]=> array(1) { [0]=> string(51) "AWSCognitoIdentityProviderService.AdminInitiateAuth" } ["Content-Type"]=> array(1) { [0]=> string(26) "application/x-amz-json-1.1" } } request.body was set to {"ClientId":"4p......kbiu","UserPoolId":"us....U","AuthFlow":"ADMIN_NO_SRP_AUTH","AuthParameters":{"USERNAME":"test......com","PASSWORD":"A...2","SECRET_HASH":"3s....5\/pFU20="},"ClientMetadata":{"HOST_TYPE":"MT"}} request.scheme was set to https -> Entering step build, name 'ApiCallMonitoringMiddleware' ---------------------------------------------------------- no changes -> Entering step build, name '' ------------------------------- request.instance changed from 000000004fc6a94b0000000001423bb8 to 000000004fc6a9520000000001423bb8 request.headers.X-Amz-User-Agent was set to array(1) { [0]=> string(105) "aws-sdk-php/3.252.3 OS/Linux/5.15.77-amd64-desktop lang/php/7.3.33-10+0~20230409.104+debian10~1.gbp88ff76" } request.headers.User-Agent was set to array(1) { [0]=> string(105) "aws-sdk-php/3.252.3 OS/Linux/5.15.77-amd64-desktop lang/php/7.3.33-10+0~20230409.104+debian10~1.gbp88ff76" } -> Entering step build, name 'endpoint_parameter' ------------------------------------------------- no changes -> Entering step build, name 'recursion-detection' -------------------------------------------------- no changes -> Entering step sign, name 'StreamRequestPayloadMiddleware' ------------------------------------------------------------ no changes -> Entering step sign, name 'invocation-id' ------------------------------------------- request.instance changed from 000000004fc6a9520000000001423bb8 to 000000004fc6a94e0000000001423bb8 request.headers.aws-sdk-invocation-id was set to array(1) { [0]=> string(32) "730c3a9ae95ac31d08fdee569ed121bb" } -> Entering step sign, name 'retry' ----------------------------------- request.instance changed from 000000004fc6a94e0000000001423bb8 to 000000004fc6a9510000000001423bb8 request.headers.aws-sdk-retry was set to array(1) { [0]=> string(3) "0/0" } -> Entering step sign, name 'signer' ------------------------------------ request.instance changed from 000000004fc6a9510000000001423bb8 to 000000004fc6a93f0000000001423bb8 request.headers.X-Amz-Date was set to array(1) { [0]=> string(16) "20230509T061901Z" } request.headers.Authorization was set to array(1) { [0]=> string(229) "AWS4-HMAC-SHA256 Credential=[KEY]/20230509/us-east-1/cognito-idp/aws4_request, SignedHeaders=host;x-amz-date;x-amz-target;x-amz-user-agent, Signature=[SIGNATURE] } -> Entering step attempt, name 'ApiCallAttemptMonitoringMiddleware' ------------------------------------------------------------------- no changes * Expire in 0 ms for 6 (transfer 0x55a2b48efce0) * Expire in 150000 ms for 2 (transfer 0x55a2b48efce0) * Expire in 1 ms for 1 (transfer 0x55a2b48efce0) * Expire in 0 ms for 1 (transfer 0x55a2b48efce0) * Expire in 1 ms for 1 (transfer 0x55a2b48efce0) * Expire in 0 ms for 1 (transfer 0x55a2b48efce0) * Expire in 0 ms for 1 (transfer 0x55a2b48efce0)........... Expire in 50 ms for 1 (transfer 0x55a2b48efce0) * Expire in 2 ms for 1 (transfer 0x55a2b48efce0) * Expire in 50 ms for 1 (transfer 0x55a2b48efce0) * Expire in 50 ms for 1 (transfer 0x55a2b48efce0) * Expire in 50 ms for 1 (transfer 0x55a2b48efce0) * Trying 3.208.79.10... * TCP_NODELAY set * Expire in 74934 ms for 3 (transfer 0x55a2b48efce0) * Expire in 200 ms for 4 (transfer 0x55a2b48efce0) * Trying 2600:1f18:257:8001:4f83:d602:a09d:614a... * TCP_NODELAY set * Expire in 74934 ms for 3 (transfer 0x55a2b48efce0) * Immediate connect fail for 2600:1f18:257:8001:4f83:d602:a09d:614a: Network is unreachable * Trying 2600:1f18:257:8002:d27c:20cf:e20c:7700... * TCP_NODELAY set * Expire in 74934 ms for 3 (transfer 0x55a2b48efce0) * Immediate connect fail for 2600:1f18:257:8002:d27c:20cf:e20c:7700: Network is unreachable * Trying 2600:1f18:257:8000:a290:85b5:3163:467b... * TCP_NODELAY set * Expire in 74934 ms for 3 (transfer 0x55a2b48efce0) * Immediate connect fail for 2600:1f18:257:8000:a290:85b5:3163:467b: Network is unreachable * Trying 2600:1f18:257:8002:c0ab:82bd:7c47:e544... * TCP_NODELAY set * Expire in 74934 ms for 3 (transfer 0x55a2b48efce0) * Immediate connect fail for 2600:1f18:257:8002:c0ab:82bd:7c47:e544: Network is unreachable * Trying 2600:1f18:257:8000:3f9c:cc77:df17:7a3d... * TCP_NODELAY set * Expire in 74934 ms for 3 (transfer 0x55a2b48efce0) * Immediate connect fail for 2600:1f18:257:8000:3f9c:cc77:df17:7a3d: Network is unreachable * Trying 2600:1f18:257:8000:5c5:31c8:140c:b3b5... * TCP_NODELAY set * Expire in 74934 ms for 3 (transfer 0x55a2b48efce0) * Immediate connect fail for 2600:1f18:257:8000:5c5:31c8:140c:b3b5: Network is unreachable * Trying 2600:1f18:257:8002:158:37ac:6830:5716... * TCP_NODELAY set * Expire in 74934 ms for 3 (transfer 0x55a2b48efce0) * Immediate connect fail for 2600:1f18:257:8002:158:37ac:6830:5716: Network is unreachable * Trying 2600:1f18:257:8001:6daf:79d7:670:6cf6... * TCP_NODELAY set * Expire in 74934 ms for 3 (transfer 0x55a2b48efce0) * Immediate connect fail for 2600:1f18:257:8001:6daf:79d7:670:6cf6: Network is unreachable * Connected to cognito-idp.us-east-1.amazonaws.com (3.208.79.10) port 443 (#0) * ALPN, offering http/1.1 * successfully set certificate verify locations: * CAfile: none CApath: /etc/ssl/certs * SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256 * ALPN, server accepted to use http/1.1 * Server certificate: * subject: CN=cognito-idp.us-east-1.amazonaws.com * start date: Apr 25 00:00:00 2023 GMT * expire date: May 23 23:59:59 2024 GMT * subjectAltName: host "cognito-idp.us-east-1.amazonaws.com" matched cert's "cognito-idp.us-east-1.amazonaws.com" * issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M02 * SSL certificate verify ok. > POST / HTTP/1.1 Host: cognito-idp.us-east-1.amazonaws.com X-Amz-Target: AWSCognitoIdentityProviderService.AdminInitiateAuth Content-Type: application/x-amz-json-1.1 X-Amz-User-Agent: aws-sdk-php/3.252.3 OS/Linux/5.15.77-amd64-desktop lang/php/7.3.33-10+0~20230409.104+debian10~1.gbp88ff76 aws-sdk-invocation-id: 730c3a9ae95ac31d08fdee569ed121bb aws-sdk-retry: 0/0 X-Amz-Date: 20230509T061901Z Authorization: AWS4-HMAC-SHA256 Credential=[KEY]/20230509/us-east-1/cognito-idp/aws4_request, SignedHeaders=host;x-amz-date;x-amz-target;x-amz-user-agent, Signature=[SIGNATURE] User-Agent: aws-sdk-php/3.252.3 OS/Linux/5.15.77-amd64-desktop lang/php/7.3.33-10+0~20230409.104+debian10~1.gbp88ff76 GuzzleHttp/7 Content-Length: 285 * upload completely sent off: 285 out of 285 bytes < HTTP/1.1 400 Bad Request < Date: Tue, 09 May 2023 06:19:03 GMT < Content-Type: application/x-amz-json-1.1 < Content-Length: 79 < Connection: keep-alive < x-amzn-RequestId: 4e5f7192-df30-46e0-8544-68c0271f2c0d < x-amzn-ErrorType: NotAuthorizedException: < x-amzn-ErrorMessage: Incorrect username or password. < * Connection #0 to host cognito-idp.us-east-1.amazonaws.com left intact <- Leaving step attempt, name 'ApiCallAttemptMonitoringMiddleware' ------------------------------------------------------------------ error was set to array(13) { ["instance"]=> string(32) "000000004fc6a9750000000001423bb8" ["class"]=> string(70) "Aws\CognitoIdentityProvider\Exception\CognitoIdentityProviderException" ["message"]=> string(436) "Error executing "AdminInitiateAuth" on "https://cognito-idp.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://cognito-idp.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response: {"__type":"NotAuthorizedException","message":"Incorrect username or password."} NotAuthorizedException (client): Incorrect username or password. - {"__type":"NotAuthorizedException","message":"Incorrect username or password."}" ["file"]=> string(88) "/home/azam/projects/localhost/aws-auth/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php" ["line"]=> int(195) ["trace"]=> string(3314) "`

**Comment by yenfryherrerafeliz** [comment]
@azamalvi we clearly can see in the error that you are receiving that the issue is due to an incorrect user or password. Please check the error below that you are getting:
>"__type":"NotAuthorizedException","message":"Incorrect username or password."} NotAuthorizedException (client): Incorrect username or password. - {"__type":"NotAuthorizedException","message":"Incorrect username or password."}" ["file"]=> string(88) "/home/azam/projects/localhost/aws-auth/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php" ["line"]=> int(195) ["trace"]=> string(3314) "`

So please make sure you provide valid credentials. Or maybe you are using the incorrect operation and what you should be using is initiateAuth instead of adminInitiateAuth. So, you could maybe try with initiateAuth function.

Thanks!

**Comment by azamalvi** [comment]
@jacobbednarz the credentails are valid and i also try with copy paste the same password while registration and login but same issue. Second I also tried with the `initiateAuth` as well, also i tried with some different `AuthFlow`
