### ISSUE TITLE
status code 400 IllegalLocationConstraintException The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.

### ISSUE THREAD

**Issue by mordechaihorowitz** [aws/aws-sdk-php#2696]
### Describe the bug

status code 400 IllegalLocationConstraintException The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.

Using SDK PHP I am setting the LocationConstraint

My account is setup for eu-west-2. I am able to retrieve from an existing bucket setup through the console using this location

I have tested with known duplicated bucket name and unique names and received the same error. I have also tried without setting location constraint.  

I have verified through the amazon console I can create a bucket there.

### Expected Behavior

I expected either a 200 response that the bucket is successfully created or an error telling me the bucket already exists. 

### Current Behavior

 Error received
 
 [reasonPhrase:protected] => Bad Request
    [statusCode:protected] => 400
    [info:protected] => Array
        (
            [url] => https://substitutedbucketname.s3.eu-west-2.amazonaws.com/
            [content_type] => application/xml
            [http_code] => 400
            [header_size] => 287
            [request_size] => 531
            [filetime] => -1
            [ssl_verify_result] => 0
            [redirect_count] => 0
            [total_time] => 0.117092
            [namelookup_time] => 0.018298
            [connect_time] => 0.020491
            [pretransfer_time] => 0.03748
            [size_upload] => 0
            [size_download] => 362
            [speed_download] => 3094
            [speed_upload] => 0
            [download_content_length] => -1
            [upload_content_length] => -1
            [starttransfer_time] => 0.116574
            [redirect_time] => 0
            [redirect_url] =>
            [primary_ip] => 52.95.144.34
            [certinfo] => Array
                (
                )

            [primary_port] => 443
            [local_ip] => 139.162.211.229
            [local_port] => 58610
        )

As you can see while my code sets location constraint I do not see it in the log as being sent which is where I think the error is.I am concerned instead of being a code error on my part its a sdk bug

          [LocationConstraint] => Guzzle\Service\Description\Parameter Object
10725                                                                         (
10726                                                                             [name:protected] => LocationConstraint
10727                                                                             [description:protected] =>
10728                                                                             [serviceDescription:protected] => Guzzle\Service\Description\ServiceDescription Object
10729  *RECURSION*
10730                                                                             [type:protected] => string
10731                                                                             [required:protected] =>
10732                                                                             [enum:protected] =>
10733                                                                             [pattern:protected] =>
10734                                                                             [minimum:protected] =>
10735                                                                             [maximum:protected] =>
10736                                                                             [minLength:protected] =>
10737                                                                             [maxLength:protected] =>
10738                                                                             [minItems:protected] =>
10739                                                                             [maxItems:protected] =>
10740                                                                             [default:protected] =>
10741                                                                             [static:protected] =>
10742                                                                             [instanceOf:protected] =>
10743                                                                             [filters:protected] =>
10744                                                                             [location:protected] => xml
10745                                                                             [sentAs:protected] =>
10746                                                                             [data:protected] => Array
10747                                                                                 (
10748                                                                                 )
10749
10750                                                                             [properties:protected] => Array
10751                                                                                 (
10752                                                                                 )
10753
10754                                                                             [additionalProperties:protected] =>
10755                                                                             [items:protected] =>
10756                                                                             [parent:protected] => Guzzle\Service\Description\Operation Object
10757  *RECURSION*
10758                                                                             [ref:protected] =>
10759                                                                             [format:protected] =>
10760                                                                             [propertiesCache:protected] =>
10761                                                                         )

### Reproduction Steps

 $response = $s3Client->createBucket(['Bucket' => $bucket_name,
       'CreateBucketConfiguration' => [
'LocationConstraint' => 'eu-west-2']
]);

### Possible Solution

Three choices

1) My code setting LocationConstraint is incorrect
2) SDK has a bug setting the LocationConstraint  and I need to upgrade to 3x.  

### SDK version used

 2.8.31

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

php -v PHP 7.2.34-31+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Jun 25 2022 08:05:14) ( NTS ) Copyright (c) 1997-2018 The PHP Group Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies     with Zend OPcache v7.2.34-31+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by yenfryherrerafeliz** [comment]
Hi @mordechaihorowitz, sorry to hear about your issues. The error that you are getting is just telling you that the endpoint used to create the bucket is on a region different than the one set in the LocationConstraint, and therefore you get an exception. I understand that you would expect to get a bucket already exists error "if bucket exists", but what happen is that the region validation is in front of the creation process that will generate that message for you. What you can do here is to, either or set the same region used in LocationConstraint to the client, or use the s3 global endpoint by doing the following:
```php
$client = new S3Client([
        'region' => 'us-east-1',
        'version' => 'latest',
        'endpoint' => 'https://s3.amazonaws.com'
    ]);
    $response = $client->createBucket([
        'Bucket' => 'herrergy-test-bucket',
        'CreateBucketConfiguration' => [
            'LocationConstraint' => 'us-east-2'
        ],
    ]);

    var_dump($response);
```
Note: make sure that the region is 'us-east-1' if using the global s3 endpoint.

I also want to mention that if you try to create a bucket, and that bucket already exists, and is owned by you, then the error that you will get is the following:
```console
 BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.
 ```
 
 I hope this helps!
 
 Thanks!
