### ISSUE TITLE
PHP 8.2 GuzzleHttp dynamic property is deprecated

### ISSUE THREAD

**Issue by chaiyot** [aws/aws-sdk-php#2702]
### Describe the bug

On PHP8.2 AWS SDK PHP show deprecated warning from Guzzle as followed
<b>Deprecated</b>:  Creation of dynamic property GuzzleHttp\Handler\CurlMultiHandler::$_mh is deprecated in <b>/aws/GuzzleHttp/Handler/CurlMultiHandler.php</b> on line <b>58</b><br />

### Expected Behavior

No deprecated warning

### Current Behavior

<b>Deprecated</b>:  Creation of dynamic property GuzzleHttp\Handler\CurlMultiHandler::$_mh is deprecated in <b>/aws/GuzzleHttp/Handler/CurlMultiHandler.php</b> on line <b>58</b><br />

### Reproduction Steps

Run AWS SDK PHP on PHP 8.2.6 server

### SDK version used

3.271.7

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.2.6 on Ubuntu 22.04

**Comment by AtillaSE** [comment]
For now I patched it by adding:

`#[\AllowDynamicProperties]`

one line 18, just before the class definition

**Comment by GrahamCampbell** [comment]
This is happening because you are using an out of date version of Guzzle. Make sure the latest version of Guzzle 7 and the latest version of it's psr7 and promises dependencies are installed, also (latest in 1.x or 2.x series is fine).

**Comment by yenfryherrerafeliz** [comment]
Hi @chaiyot, sorry to hear about your issues. I agree with the suggestion that @GrahamCampbell made [here](https://github.com/aws/aws-sdk-php/issues/2702#issuecomment-1587732383). Would you be able to please run ``` composer update ``` in order to update your dependencies?

Thanks!

**Comment by stobrien89** [comment]
Thanks for the response @GrahamCampbell.  Closing this now, but please let us know if anything else comes up.

**Comment by 925dk** [comment]
Getting the notice also when using directly `https://github.com/aws/aws-sdk-php/releases/download/3.277.8/aws.phar`. So maybe you need to update GuzzleHttp in your own repos/archive?

`PHP Deprecated:  Creation of dynamic property GuzzleHttp\Handler\CurlMultiHandler::$_mh is deprecated in phar:///usr/share/php/aws.phar/GuzzleHttp/Handler/CurlMultiHandler.php on line 58`

**Comment by GrahamCampbell** [comment]
This is because the phars they provide are not compatible with PHP 8.1 or 8.2.

**Comment by 925dk** [comment]
@GrahamCampbell Ah, I see. Many thanks for the info.
