### ISSUE TITLE
S3 UploadPartCopy fails with spaces in object name

### ISSUE THREAD

**Issue by mzur** [aws/aws-sdk-php#2704]
### Describe the bug

If I want to copy an object that is larger than 5 GB and has spaces in the object name (e.g. `i contain spaces.mp4`), the action fails with 404 "NoSuchKey" errors for the request of each part.

### Expected Behavior

The copy operation should succeed (as it does with Python and boto3, see below).

### Current Behavior

Here is a file with the full error: [error.txt](https://github.com/aws/aws-sdk-php/files/11664899/error.txt)

### Reproduction Steps

This is the PHP code I used:

```php
<?php

require 'vendor/autoload.php';

use Aws\S3\S3Client;

$s3Client = new S3Client([
    'region' => 'us-west-2',
    'version' => 'latest',
    'endpoint' => 'https://example.com',
    'credentials' => [
        'key' => '...',
        'secret' => '...',
    ],
]);

$s3Client->copy(
    'MyBucket',
    'source/i contain spaces.mp4',
    'MyBucket',
    'path/spaces-are-not-ok-with-php.mp4'
);
```

The following Python code succeeds with the same object:

```python
import boto3

client = boto3.client(
    's3',
    aws_access_key_id='...',
    aws_secret_access_key='...',
    endpoint_url='https://example.com'
)

client.copy(
    {
        'Bucket': 'MyBucket',
        'Key': 'source/i contain spaces.mp4'
    },
    'MyBucket',
    'path/spaces-are-ok-with-python.mp4'
)
```

### Possible Solution

Use `rawurlencode` here:

https://github.com/aws/aws-sdk-php/blob/46250f9947768c102052a6650a0a09405e77ee0a/src/S3/MultipartCopy.php#L144

My example provided above succeeds with this change. I'm happy to send a PR with the change if you give me a :+1: 

### SDK version used

3.261.1

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.1.13 (cli) in a php:8.1-alpine Docker container

**Comment by SamRemis** [comment]
Hi there @mzur,
Thanks for opening up this issue; so far, I haven't been able to reproduce it.  I made sure it was a multipart upload so it would hit the above line of code, and tried this on an object that was uploaded using both putObject() and upload().  

What method did you use to upload this object?  
Thanks,
-Sam

**Comment by mzur** [comment]
Thank you for having a look! I did not think it was relevant but I'm talking to an OpenStack instance using the [Ceph Object Gateway S3 API](https://docs.ceph.com/en/latest/radosgw/s3/). Maybe AWS S3 supports an `urlencode`-encoded CopySource and the Ceph Gateway requires `rawurlencode`? The S3 [API docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPartCopy.html#API_UploadPartCopy_RequestSyntax) are quite vague on this and say only "The value must be URL-encoded."

Unfortunately I don't have access to AWS S3 so I can't test it there.

> What method did you use to upload this object?

I uploaded the object with `s3cmd put` which uses [`object_put`](https://github.com/s3tools/s3cmd/blob/2db79e5449b6069639847164ddd630ceec332d1a/s3cmd#L463) I think.

**Comment by mzur** [comment]
I've also asked in the Ceph bug tracker for an opinion on their side: https://tracker.ceph.com/issues/61670

**Comment by stobrien89** [comment]
Hi @mzur,

We're sorry to hear about the issues. S3 will accept either a url-encoded or rawurlencoded string as far as the PHP SDK is concerned.  This is almost certainly a consistency error on our part, but changing this now would risk breaking AWS customers.  We as an SDK can only guarantee compatibility with AWS services, so a change would need to be made on the Ceph side to address this.

**Comment by mzur** [comment]
@stobrien89 Thank you for your considerate response, I fully understand. Given that an update of Ceph and the deployment of the update will be much harder to achieve for me as a PaaS user (compared to an update of the SDK), would you be open for some kind of feature flag in the `S3Client` config that enables `rawurlencode` instead of `urlencode`? This will be fully backwards-compatible.
