### ISSUE TITLE
Upgraded to Php 7.2 to 8.0 and aws sdk stopped working.

### ISSUE THREAD

**Issue by uqayyumsac** [aws/aws-sdk-php#2709]
### Describe the bug

Hi guys,

I was working on upgrading a legacy project from php v7.2 to 8.0 and my sdk version is unchanged at 3.271.10.

When i try one of my apis, it goes into gateway timeout.  I have tried to debug and went a bit deeper to find out where my code is dying. It turns out that when we initiate the S3Client and the constructor calls the parent's (AwsClient) constructor. It gets lost in the following piece of code.

       `$resolver = new ClientResolver(static::getArguments());
        $config = $resolver->resolve($args, $this->handlerList);   // here`

I have all the dependencies installed correctly and everything else seems to be working fine except for this one. Hope I was able to clearly explain the issue.

Looking forward to the support, cheers!

### Expected Behavior

Should work fine with the newer version.

### Current Behavior

Request takes so much time because no response from AwsClient and goes into gateway timeout.

### Reproduction Steps

Simple initiating th e S3Client isn't working.

### Possible Solution

ClientResolver function resolve is the key here.

### SDK version used

3.271.10

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

Php 8.0 on intel mac running docker php-fpm container

**Comment by yenfryherrerafeliz** [comment]
Hi @uqayyumsac, sorry to hear about your issues. I do not know why this happen at your end. I just tried a simple operation with the SDK, using php8.0, and I did not have any issues. Please see below:
```console
DIR$ issue-2709 % php -v
PHP 8.0.28 (cli) (built: Feb 14 2023 15:42:52) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.28, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.28, Copyright (c), by Zend Technologies
```
Code:
```php
<?php
require '../vendor/autoload.php';

use Aws\S3\S3Client;

$client = new S3Client([
    'version' => 'latest',
    'region' => getenv('TEST_REGION')
]);
$response = $client->listBuckets([]);

var_dump($response);
```
Output:
```php
array(4) {
  ["statusCode"]=>
  int(200)
  ["effectiveUri"]=>
  string(35) "https://s3.us-east-2.amazonaws.com/"
  ["headers"]=>
  array(6) {
    ["x-amz-id-2"]=>
    string(76) ""
    ["x-amz-request-id"]=>
    string(16) "Z3CBWK3CKR74PRE2"
    ["date"]=>
    string(29) "Fri, 09 Jun 2023 15:56:14 GMT"
    ["content-type"]=>
    string(15) "application/xml"
    ["transfer-encoding"]=>
    string(7) "chunked"
    ["server"]=>
    string(8) "AmazonS3"
  }
  ["transferStats"]=>
  array(1) {
    ["http"]=>
    array(1) {
      [0]=>
      array(0) {
      }
    }
  }
}
```

Could you please try creating an empty project, install the SDK, and do a simple operation as I did before, and if that works then the problem could be something else related with your configuration. 

I hope this helps.

Thanks!

**Comment by uqayyumsac** [comment]
Hi @yenfryherrerafeliz , thanks a lot for the support.

I downgraded to the exact version where the php 8.0 support started and it appears to be working fine now.

What I'll do is go up the versions carefully and will check why that weird issue came in the first place. 

Cheers!
