### ISSUE TITLE
rekognition s3 object not work

### ISSUE THREAD

**Issue by gotostar** [aws/aws-sdk-php#2710]
### Describe the bug

I am unable to retrieve files from S3 using Rekognition's CompareFaces.

### Expected Behavior

I want to find similar files among the files inside an S3 bucket, so I wanted to use Rekognition's CompareFaces to search through the images in a specific folder within the bucket. However, I'm currently unable to even retrieve the objects from S3.

### Current Behavior

Type: Aws\Rekognition\Exception\RekognitionException

Message: Error executing "CompareFaces" on "https://rekognition.ap-northeast-2.amazonaws.com"; AWS HTTP error: Client error: `POST https://rekognition.ap-northeast-2.amazonaws.com` resulted in a `400 Bad Request` response: {"__type":"InvalidS3ObjectException","Code":"InvalidS3ObjectException","Message":"Unable to get object metadata from S3. (truncated...) InvalidS3ObjectException (client): Unable to get object metadata from S3. Check object key, region and/or access permissions. - {"__type":"InvalidS3ObjectException","Code":"InvalidS3ObjectException","Message":"Unable to get object metadata from S3. Check object key, region and/or access permissions."}

Filename: /vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php

Line Number: 196

### Reproduction Steps

$objects = $s3Client->getPaginator('ListObjects', [
            'Bucket' => $bucketName,
            'Prefix' => $folderName . '/',
        ]);
        
        foreach ($objects as $result) {
            foreach ($result['Contents'] as $object) {
                $targetImage = $object['Key'];
                
                $result = $rekognitionClient->compareFaces([
                    'SimilarityThreshold' => $similarityThreshold,
                    'SourceImage' => [
                        'S3Object' => [
                            'Bucket' => $bucketName,
                            'Name' => $sourceImage,
                            'Key' => $sourceImage,
                        ],
                    ],
                    'TargetImage' => [
                        'S3Object' => [
                            'Bucket' => $bucketName,
                            'Name' => $targetImage,
                            'Key' => $targetImage,
                        ],
                    ],
                ]);
                
                if (!empty($result['FaceMatches'])) {
                    $matches[] = $targetImage;
                }
            }
        }

### SDK version used

3.272.0

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

7.4.30

**Comment by yenfryherrerafeliz** [comment]
Hi @gotostar, sorry for the delay on this. Can you please confirm that the region used for the rekognition client is the same where S3 bucket lives, if not then, you need to use the same region from the S3 bucket. We can confirm this by looking at the documentation [here](https://docs.aws.amazon.com/rekognition/latest/dg/images-s3.html#images-s3-request).

I hope this helps!

Thanks!
