### ISSUE TITLE
Missing support for psr/http-message ^2.0

### ISSUE THREAD

**Issue by IanSimpson** [aws/aws-sdk-php#2715]
### Describe the feature

The package psr/http-message v2.0 was released on the 2023-04-17. Could you consider adding support for this version?

### Use Case

Compatibility with psr/http-message

### Proposed Solution

Update composer json from `"psr/http-message": "^1.0"` to `"psr/http-message": "^1.0 || ^2.0"`. This will preserve compatibility with PHP5.5 by using the 1.x releases, but ensure users running modern version of PHP can install the latest version of the library.

I don't believe there are any breaking changes in the updated version - the only change noted in the changelog is declared return types.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.273.3

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.1 (all platforms)

**Comment by stobrien89** [comment]
Hi @IanSimpson,

Sorry for the confusion.  I commented in the other issue, but for those who don't see that— A few classes of ours implement psr7 interfaces, which means allowing V2 is a breaking change for some customer.  This will be changing in August.  Keep an eye on #2707 for updates.
