### ISSUE TITLE
Make compatible with latest major version of guzzle/promises

### ISSUE THREAD

**Issue by rohnjeynolds** [aws/aws-sdk-php#2721]
### Describe the feature

The SDK has a dependency on guzzle/promises v1.4, which is a major version behind the latest, 2.0. Please update the SDK to be compatible with guzzle/promises v2.0.

### Use Case

Projects using Drupal 10.0 and the Amazon S3 Filesystem (s3fs) module cannot upgrade to Drupal 10.1 because that version depends on guzzle/promises v2.0, while the s3fs module depends on this SDK, which in turn is only compatible with guzzle/promises v1.4.

### Proposed Solution

Test and release a new version of the SDK that relies on guzzle/promises v2.0.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### SDK version used

3.275.1

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.2.6, Apache/2.4.38, Debian 11 Bullseye

**Comment by SamRemis** [comment]
Hi @rohnjeynolds,
Thanks for opening this; this is a common request so I will pin this issue for visibility.  This is something we are looking forward to doing, and will be merged with [this PR](https://github.com/aws/aws-sdk-php/pull/2707) on August 15th.  We [announced the deprecation](https://github.com/aws/aws-sdk-php/discussions/2638) that will make this possible back in February.

-Sam

**Comment by stobrien89** [comment]
Hi all,

This was implemented in #2760.  Let us know if you have any questions!
