### ISSUE TITLE
Use of "self" in callables is deprecated - PHP 8.2

### ISSUE THREAD

**Issue by Mubasher-iqbal** [aws/aws-sdk-php#2734]
### Describe the bug

Following are the version details i am using.
aws/aws-sdk-php : "^3.226"
PHP version 8.2
I am getting below mentioned Errors.

### Expected Behavior

While accessing the Controller where i am using the AWS S3 service. It should load page without any errors in console.

### Current Behavior

ERROR - 2023-07-24 08:25:52 --> Severity: 8192 --> Use of "self" in callables is deprecated /vendor/aws/aws-sdk-php/src/S3/RegionalEndpoint/ConfigurationProvider.php 83
ERROR - 2023-07-24 08:25:52 --> Severity: 8192 --> Use of "self" in callables is deprecated /vendor/aws/aws-sdk-php/src/DefaultsMode/ConfigurationProvider.php 85
ERROR - 2023-07-24 08:25:52 --> Severity: 8192 --> Use of "self" in callables is deprecated /vendor/aws/aws-sdk-php/src/Endpoint/UseFipsEndpoint/ConfigurationProvider.php 82
ERROR - 2023-07-24 08:25:52 --> Severity: 8192 --> Use of "self" in callables is deprecated /vendor/aws/aws-sdk-php/src/Endpoint/UseDualstackEndpoint/ConfigurationProvider.php 83
ERROR - 2023-07-24 08:25:52 --> Severity: 8192 --> Use of "self" in callables is deprecated /vendor/aws/aws-sdk-php/src/EndpointDiscovery/ConfigurationProvider.php 86
ERROR - 2023-07-24 08:25:52 --> Severity: 8192 --> Use of "self" in callables is deprecated /vendor/aws/aws-sdk-php/src/Retry/ConfigurationProvider.php 88
ERROR - 2023-07-24 08:25:52 --> Severity: 8192 --> Use of "self" in callables is deprecated /vendor/aws/aws-sdk-php/src/ClientSideMonitoring/ConfigurationProvider.php 90

### Reproduction Steps

Load AWS sdk instance for S3 in php8.2 app.

### SDK version used

3.226

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

8.2.8

**Comment by yenfryherrerafeliz** [comment]
Hi @Mubasher-iqbal, thanks for taking the time to open this issue. At this time we do not officially support PHP 8. We are currently working on supporting 8.0 and 8.1, but it is still work in progress. We also would consider supporting PHP 8.2.+ when further modernizing the SDK.

Related: https://github.com/aws/aws-sdk-php/issues/2467

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Hi @Mubasher-iqbal, again thanks for reporting this. We have re-opened [this](https://github.com/aws/aws-sdk-php/issues/2467) issue so we can address the reported behavior in the near future. Please, for any updates regarding getting this fixed, could you please follow up there in that linked issue?.

Thanks!
