### ISSUE TITLE
s3 copyObject does not work to update metadata

### ISSUE THREAD

**Issue by doapp-ryanp** [aws/aws-sdk-php#274]
`copyObject()` is the only way I know of to update and exsting s3 object's metadata. When updating an object to add the `Cache-Control` header I get the following error. I also tried adding `'Metadata'=>array('updated'=>'1')` but get same error:

```
This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes
```

Its simple to re-produce:

```
    $s3->copyObject(array(
        'Bucket' => 'mybucket',
        'CopySource'=> 'mybucket/test.gz',
        'Key' => 'test.gz',
        'ACL' => CannedAcl::PUBLIC_READ,
        'CacheControl' => "max-age=60, public",
        'Metadata'=>array('updated'=>'1')
    ));
```

For what its worth, this bug also exists in the aws cli tool. see https://github.com/aws/aws-cli/issues/652

**Comment by jrochkind** [comment]
This seems to no longer be supported for v3 SDK?  copy_object can no longer update metadata at all?

**Comment by Zaky7** [comment]
@jrochkind what we should  do in v3 sdk to avoid `This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata` exception any idea?

**Comment by skyzyx** [comment]
I would **strongly** recommend opening a fresh issue rather than commenting on one that was closed in 2014.
