### ISSUE TITLE
Couldn't get the credentials in ECS fargate container using AWS-SDK-PHP 

### ISSUE THREAD

**Issue by ecom-street** [aws/aws-sdk-php#2751]
### Describe the bug

Hi all,
I am using this SDK and it is working fine with EC2 and I am able to fetch the credentials and use the AWS services like Cognito, S3 etc.
But when I am deploying the same code in the container (ECS fargate), it is unable to fetch the credentials and I am not able to use AWS services like Cognito, S3.

I am getting the below error:
Error retrieving credentials from the instance profile metadata service. (cURL error 7: Failed to connect to 169.254.169.254 port 80 after 0 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://169.254.169.254/latest/meta-data/iam/security-credentials/)

When I researched in internet and try to implement other solution then I got the below error:
Error retrieving credential from ECS (Client error: `GET http://169.254.170.2` resulted in a `404 Not Found` response: 404 page not found )

Please suggest me what I am missing in my code and how to resolve it.

Thanks in advance.

### Expected Behavior

It should connect with the AWS services using task role. But I am not able to get the credentials.

### Current Behavior

Getting error while fetching the credentails

### Reproduction Steps

I am trying with multiple solution by doing research on Internet.

use Aws\Credentials\CredentialProvider;
$provider = CredentialProvider::ecsCredentials();

$memoizedProvider = CredentialProvider::memoize($provider);

### SDK version used

SDK 3.2

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.1, OS: Linux

**Comment by yenfryherrerafeliz** [comment]
Hi @ecom-street, can you please provide more details about your Dockerfile configuration?, are you working with php-fpm?, if so, are you using nginx as reverse proxy?

Please let me know.

Thanks!

**Comment by HaidarZ** [comment]
Similar issue here

```txt
Aws\Exception\CredentialsException: Error retrieving credentials from the instance profile metadata service. (Client error: `GET http://169.254.169.254/latest/meta-data/iam/security-credentials/` resulted in a `404 Not Found` response: <?xml version="1.0" encoding="iso-8859-1"?> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://ww (truncated...) )
```

I've downgraded back to `aws/aws-sdk-php:3.278.1` and everything is normal now.

**Comment by yenfryherrerafeliz** [comment]
@HaidarZ the error that you are getting is not specifically related to the issue reported here. Are you running on ECS?, if so, could you please specify the credential provider when instancing the client as  in the following example:
```php
use Aws\Credentials\CredentialProvider;
use Aws\S3\S3Client;

$provider = CredentialProvider::ecsCredentials();
$memoizedCredentials = CredentialProvider::memoize($provider);
$client = new S3Client([
    'version' => 'latest',
    'region' => 'us-east-2',
    'credentials' => $memoizedCredentials
]);
$response = $client->listBuckets();
```

Thanks!

**Comment by yenfryherrerafeliz** [comment]
@ecom-street thanks for this information. I think the issue is related to that laravel uses dotenv for dealing with environment variables, and somehow it is ignoring the variables injected by the task definition when deploying the service. By looking at the implementation [here](https://github.com/aws/aws-sdk-php/blob/7b3d38cfccd393add0ea0ce281de91846967c61e/src/Credentials/EcsCredentialProvider.php#L104), for how credentials are fetched from ECS, we observe that there are two necessary variables that are AWS_CONTAINER_CREDENTIALS_RELATIVE_URI or AWS_CONTAINER_CREDENTIALS_FULL_URI. At least one of those variables need to exist so the credentials are fetched correctly, but, when deploying a laravel application, even if we do not use the SDK we will see that those variables are never defined.

I also have gotten another report regarding to this, and also using laravel, so that I am trying to find a workaround that can be used. I have not been lucky yet, but as soon as I get something that can helps, I will make sure to update this ticket here.

Note: I have assumed that your task definition has a task role associated to it?

Thanks!

**Comment by yenfryherrerafeliz** [comment]
@HaidarZ could you please confirm if you use laravel as well?

**Comment by SamRemis** [comment]
@HaidarZ, did you encounter this issue for the first time yesterday/today with 3.279.0?  And what version of PHP are you using?  

These are likely two separate issues if this was working for you on 3.278.1.

**Comment by ecom-street** [comment]
> @ecom-street thanks for this information. I think the issue is related to that laravel uses dotenv for dealing with environment variables, and somehow it is ignoring the variables injected by the task definition when deploying the service. By looking at the implementation [here](https://github.com/aws/aws-sdk-php/blob/7b3d38cfccd393add0ea0ce281de91846967c61e/src/Credentials/EcsCredentialProvider.php#L104), for how credentials are fetched from ECS, we observe that there are two necessary variables that are AWS_CONTAINER_CREDENTIALS_RELATIVE_URI or AWS_CONTAINER_CREDENTIALS_FULL_URI. At least one of those variables need to exist so the credentials are fetched correctly, but, when deploying a laravel application, even if we do not use the SDK we will see that those variables are never defined.
> 
> I also have gotten another report regarding to this, and also using laravel, so that I am trying to find a workaround that can be used. I have not been lucky yet, but as soon as I get something that can helps, I will make sure to update this ticket here.
> 
> Note: I have assumed that your task definition has a task role associated to it?
> 
> Thanks!

@yenfryherrerafeliz, thanks for your update. I will be waiting for your positive reply.
You are right, I have associated the task role to it.

**Comment by HaidarZ** [comment]
> @HaidarZ could you please confirm if you use laravel as well?

Yes I'm using Laravel v10





> @HaidarZ, did you encounter this issue for the first time yesterday/today with 3.279.0? And what version of PHP are you using?
> 
> These are likely two separate issues if this was working for you on 3.278.1.

The issue was faced on August 16th once I updated to v3.278.3
PHP 8.1.2

**Comment by onursahindur** [comment]
Hello, same here. 
Laravel 9.x

**Comment by yenfryherrerafeliz** [comment]
Hi @ecom-street, @HaidarZ, @onursahindur, could you please try the following:
Create a script as entry point with the following content:
**entrypoint.sh**
```
#!/bin/bash

for env in $(printenv); do
    if [[ $env == "AWS"* ]]; then
        echo "$env" >> .env
    fi;
done;

```

then in your docker file make sure you add this script as entry point. Example:
**Dockerfile**
```
.....

COPY ./entrypoint.sh /scripts

ENTRYPOINT ["/scripts/entrypoint.sh"]
```

Please adjust this according to your implementation, and let me know if that works.

Thanks!
