### ISSUE TITLE
InstanceProfileProvider doesn't handle connection issues with IMDS well when IMDSv1 is disabled

### ISSUE THREAD

**Issue by umesecke** [aws/aws-sdk-php#2769]
### Describe the bug

Unfortunately from time to time we are having connection issues with IMDS on some of our instances and I think there are some problems with the `InstanceProfileProvider` when handling those issues. Instead of retrying connection timeouts in the initial token request, the provider switches to the insecure mode (a.k.a. IMDSv1) and continues. In the next step the IMDS returns a 401 because we had IMDSv1 disabled for those instances. But instead of returning to the first token request, the provider just switches back to secure mode and then returns the 401 response as a credential exception.

After re-enabling IMDSv1 we can see a rise in the MetadataNoToken Cloudwatch metric and instead of multiple 401 errors as before, we now get a small amount of connection timeout errors because the provider continued to retry requests in insecure mode.

### Expected Behavior

I'd expect the provider to correctly detect connection timeouts for the initial token request and retry the requests instead of switching to insecure mode.

### Current Behavior

We found the following error messages in our logfile:

> Error retrieving credentials from the instance profile metadata service. (Client error: `GET http://169.254.169.254/latest/meta-data/iam/security-credentials/` resulted in a `401 Unauthorized` response)

```
/home/worker/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php:139, 
/home/worker/vendor/guzzlehttp/promises/src/Coroutine.php:160, 
/home/worker/vendor/guzzlehttp/promises/src/Promise.php:204, 
/home/worker/vendor/guzzlehttp/promises/src/Promise.php:153, 
/home/worker/vendor/guzzlehttp/promises/src/TaskQueue.php:48, 
/home/worker/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:159, 
/home/worker/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:185, 
/home/worker/vendor/guzzlehttp/promises/src/Promise.php:248, 
/home/worker/vendor/guzzlehttp/promises/src/Promise.php:224, 
/home/worker/vendor/guzzlehttp/promises/src/Promise.php:269, 
/home/worker/vendor/guzzlehttp/promises/src/Promise.php:226, 
/home/worker/vendor/guzzlehttp/promises/src/Promise.php:62, 
/home/worker/vendor/guzzlehttp/promises/src/Coroutine.php:67,
[...]
```

This likely means that the credentials endpoint was called without a token which should only happen in insecure mode (we have disabled IMDSv1 for our instances). The token is never reused between calls to the provider's `__invoke()` method so it should not have expired (also the process never runs for more than one hour).

This means that the first request retrieving the token switched the provider into insecure mode.

In our case we disabled IMDSv1 and therefore the response of the profile request is 401 and the provider throws an exception.

After enabling IMDSv1 we see a changed behavior. The insecure requests without a token now work again (increasing the MethodNoToken metric) and we only get an error message if all retry-attempts failed with connection timeouts, reducing the number of errors compared to running without IMDSv1:

> Error retrieving credentials from the instance profile metadata service. (cURL error 28: Connection timed out after 1001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://169.254.169.254/latest/meta-data/iam/security-credentials/REDACTED)

```
/home/worker/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php:180,
/home/worker/vendor/guzzlehttp/promises/src/Coroutine.php:160, 
/home/worker/vendor/guzzlehttp/promises/src/Promise.php:204, 
/home/worker/vendor/guzzlehttp/promises/src/Promise.php:153, 
/home/worker/vendor/guzzlehttp/promises/src/TaskQueue.php:48, 
/home/worker/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:159, 
/home/worker/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php:185, 
/home/worker/vendor/guzzlehttp/promises/src/Promise.php:248, 
/home/worker/vendor/guzzlehttp/promises/src/Promise.php:224, 
/home/worker/vendor/guzzlehttp/promises/src/Promise.php:269, 
/home/worker/vendor/guzzlehttp/promises/src/Promise.php:226, 
/home/worker/vendor/guzzlehttp/promises/src/Promise.php:62, 
/home/worker/vendor/guzzlehttp/promises/src/Coroutine.php:67,
[...]
```

### Reproduction Steps

This issue only occurs when the metadata service is having trouble resulting in connection timeouts. So it is difficult to reproduce manually.

### Possible Solution

I think the problem lies in the catch block of the initial token request when checking whether the response has one of the provided list of status codes ([InstanceProfileProvider.php line 91](https://github.com/aws/aws-sdk-php/blob/master/src/Credentials/InstanceProfileProvider.php#L91)). The if-condition should check whether the exception has a `getResponse()` method, actually has a response and the response status code is in the list.

Instead the condition also matches exceptions that don't have a `getResponse()` method like `ConnectException` after a connection timeout. Following this faulty condition the provider disables secure mode instead of going into the else-block which would retry the request.

Additionally the exception handling for the profile and credentials requests could be changed in a way that when the provider detects that secure mode should be enabled again, the code jumps back to the top and tries to retrieve a token again. But maybe the current behavior is intended because a shouldn't happen if the initial token request would have been retried correctly.

### SDK version used

3.277.2, but the code in master is the same

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.1.18 (cli) (built: Apr 14 2023 04:39:44) (NTS), Ubuntu 22.04

**Comment by yenfryherrerafeliz** [comment]
Hi @umesecke, we have introduced a new option for the InstanceProfileProvider for disabling the fallback to IMDSv1. You can achieve this by using one of the following options:
- Explicitly with the config parameter of the provider, as follow:
```php
<?php

use Aws\Credentials\CredentialProvider;
use Aws\S3\S3Client;

require '../vendor/autoload.php';

$provider = CredentialProvider::instanceProfile([
    'ec2_metadata_v1_disabled' => true
]);
$memoizedProvider = CredentialProvider::memoize($provider);
$s3 = new S3Client([
    'region' => getenv('TEST_REGION'),
    'credentials' => $provider
]);
$response = $s3->listBuckets();

print_r($response);

```
- By setting up an environment variable called ```AWS_EC2_METADATA_V1_DISABLED``` and setting its value to true.
- By defining a property called ```ec2_metadata_v1_disabled``` in the config file, and setting its value to true.

[Here](https://github.com/aws/aws-sdk-php/blob/568f0f770b8b26afce41ff93348b248c3a7090c9/src/Credentials/InstanceProfileProvider.php#L308) you can find more details about this new option.

I hope that helps!

Thanks!

**Comment by umesecke** [comment]
Hi @yenfryherrerafeliz, sounds good! We will try this in our application and monitor the Cloudwatch metric.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
@umesecke sounds good. 

Thanks!
