### ISSUE TITLE
presigned url is broken: signature does not match

### ISSUE THREAD

**Issue by Hazem-Ben-Abdelhafidh** [aws/aws-sdk-php#2772]
### Describe the bug

i'm trying to generate a presigned url using this code : 
```php
public function generatePresignedUrl(string $bucket, string $objectKey, int $expiresInSeconds = 3600): string
    {
        // Generate a pre-signed URL for the S3 object
        $cmd = $this->s3Client->getCommand('GetObject', [
            'Bucket' => $bucket,
            'Key'    => $objectKey
        ]);

        $presignedRequest = $this->s3Client->createPresignedRequest($cmd, "+{$expiresInSeconds} seconds");

        // Extract the pre-signed URL from the request
        return (string)$presignedRequest->getUri();
    } 
```    
    and it generates a broken url with:  X-Amz-Content-Sha256=UNSIGNED-PAYLOAD
  
![image_2023_09_07T11_25_56_375Z](https://github.com/aws/aws-sdk-php/assets/71515892/9b3840f3-4976-4140-8b51-146fc94f30a6)

### Expected Behavior

the function should return a valid presigned url

### Current Behavior

the function generates a broken url

### Reproduction Steps
```php
public function generatePresignedUrl(string $bucket, string $objectKey, int $expiresInSeconds = 3600): string
    {
        // Generate a pre-signed URL for the S3 object
        $cmd = $this->s3Client->getCommand('GetObject', [
            'Bucket' => $bucket,
            'Key'    => $objectKey
        ]);

        $presignedRequest = $this->s3Client->createPresignedRequest($cmd, "+{$expiresInSeconds} seconds");

        // Extract the pre-signed URL from the request
        return (string)$presignedRequest->getUri();
    } 
```

### SDK version used

3.281.1

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

php version : 7.4, os: ubuntu 20

**Comment by yenfryherrerafeliz** [comment]
Hi @Hazem-Ben-Abdelhafidh, I am not sure what could be wrong at your end. I just tried to reproduce this issue by using the following code below, and everything works fine.
*Code:*
```php
<?php
require '../vendor/autoload.php';

use Aws\S3\S3Client;

$client = new S3Client([
    'version' => 'latest',
    'region' => getenv('TEST_REGION'),
]);
$cmd = $client->getCommand('GetObject', [
    'Bucket' => getenv('TEST_BUCKET'),
    'Key' => getenv('TEST_KEY'),
]);
$request = $client->createPresignedRequest($cmd, '+1 minutes');
$url = (string) $request->getUri();

echo "PresignedURL: " . $url;

```

Regarding this:
>and it generates a broken url with:  X-Amz-Content-Sha256=UNSIGNED-PAYLOAD

when the this header is set to UNSIGNED-PAYLOAD it means that the signature is not including the hash of the body, because in this case there is not a body present in the request, which means that this is expected.

Would you be able to please try with my code and see if the issue still persists?

Thanks!
