### ISSUE TITLE
MediaConvert issue - Uncaught TypeError: method_exists()

### ISSUE THREAD

**Issue by RaviJayagopal** [aws/aws-sdk-php#2774]
### Describe the bug

Hi,

I'm using version 3.173.19 of the SDK (pretty recent one).

And I'm getting this error:

Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, array given in /home/path.../wp-content/plugins/pluginname/vendor/guzzlehttp/promises/src/RejectedPromise.php:16

When I execute this code:

$mediaConvert = new MediaConvertClient([
        'version' => 'latest',
        'region'  => $region,
        'credentials' => [
            'key'    => $accessKey,
            'secret' => $secretKey,
        ]
    ]);
    
    $result = $mediaConvert->listJobs(); // <--fails here and exits with above error.

---------------------------------------------------------

I also tried the listJobsAsync method below, which also results in the same error.

$promise = $mediaConvert->listJobsAsync();

    $promise->then(
        function ($result) {
            $jobs = $result['Jobs'];

            foreach ($jobs as $job) {
                echo "Job ID: " . $job['Id'] . "\n";
                echo "Status: " . $job['Status'] . "\n";
                
                if (isset($job['ErrorCode'])) {
                    echo "Error Code: " . $job['ErrorCode'] . "\n";
                }
                echo "-----------------------\n";
            }
        },
        function ($reason) {
            // Handle rejection (error)
            echo "Error retrieving jobs: " . $reason->getMessage();
        }
    )->wait();

Please help.

Thanks in advance!

### Expected Behavior

List of MediaConvert jobs should be displayed.

### Current Behavior

I'm getting this error:

Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, array given in /home/path.../wp-content/plugins/pluginname/vendor/guzzlehttp/promises/src/RejectedPromise.php:16

### Reproduction Steps

$mediaConvert = new MediaConvertClient([
        'version' => 'latest',
        'region'  => $region,
        'credentials' => [
            'key'    => $accessKey,
            'secret' => $secretKey,
        ]
    ]);
    
    $result = $mediaConvert->listJobs(); // <--fails here and exits with above error.

### Additional Information/Context

PHP Version: 8.2.10

AWS SDK Version 3.173.19
"guzzlehttp/guzzle": "^5.3.3|^6.2.1|^7.0",
"guzzlehttp/promises": "^1.0",
"guzzlehttp/psr7": "^1.4.1",
"mtdowling/jmespath.php": "^2.5",

"name": "guzzlehttp/promises",
"version": "v1.3.1",

"name": "guzzlehttp/psr7",
"version": "1.9.1",

### SDK version used

3.173.19

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP Version: 8.2.10

**Comment by GrahamCampbell** [comment]
This is happening because you are using a too old version of Guzzle that does not support PHP 8.2.

**Comment by RaviJayagopal** [comment]
@GrahamCampbell thank you so much!! Issue resolved. Thanks!
