### ISSUE TITLE
Duplicating S3 URL path

### ISSUE THREAD

**Issue by yurih567** [aws/aws-sdk-php#2785]
### Describe the bug

When using a custom path, the endpoint is becoming duplicated

ENVs:
endpoint = "https://br-ne-1.api.{custom domain}.cloud/domainobjects"
use_path_style_endpoint = true

Generated url: "https://br-ne-1.api.{custom domain}.cloud/domainobjects/domainobjects/{bucket name}/images/customers/image.png"

The path "domainobjects" is duplicated.

### Expected Behavior

Expected url: https://br-ne-1.api.{custom domain}.cloud/domainobjects/{bucket name}/images/customers/image.png

### Current Behavior

https://br-ne-1.api.{custom domain}.cloud/domainobjects/domainobjects/{bucket name}/images/customers/image.png

### Reproduction Steps

enable the option "use_path_style_endpoint = true" and define a custom bucket endpoint.
Example: "https://us-east-1.mycompany.com/customendpoint"
Generated URL: "https://us-east-1.mycompany.com/customendpoint/customendpoint"

### SDK version used

3.273.0

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.1.6 (cli) (built: May 13 2022 22:52:41) (NTS) Copyright (c) The PHP Group Zend Engine v4.1.6, Copyright (c) Zend Technologies     with Xdebug v3.2.1, Copyright (c) 2002-2023, by Derick Rethans

**Comment by stobrien89** [comment]
Hi @yurih567,

Thanks for reaching out.  Can you provide a snippet of your client initialization and operation invocation? 

In this case, it seems you shouldn't be providing the path in your custom endpoint, as the `use_path_style_endpoint` without the `bucket_endpoint` option just tells the SDK to construct a path-style endpoint.

**Comment by yurih567** [comment]
I'm using the "league/flysystem-aws-s3-v3" lib, if I don't provide the "use_path_style_endpoint" flag, the bucket name is added by default at the beginning of the URL, but it shouldn't

with use_path_style_endpoint: https://us-east-1.mycompany.com/customendpoint/customendpoint/bucketname/...

without use_path_style_endpoint: https://bucketname.us-east-1.mycompany.com/customendpoint/bucketname/...

expected: https://us-east-1.mycompany.com/customendpoint/bucketname/...

**Comment by stobrien89** [comment]
Hi @yurih567,

Thanks for the additional info.  Can you provide a snippet of your client initialization and operation invocation?

**Comment by yurih567** [comment]
I just call the "temporaryUrl" method of laravel's "Illuminate\Support\Facades\Storage" class

![image](https://github.com/aws/aws-sdk-php/assets/45864246/ec7755ae-93c0-4691-8012-4f8be5badf00)

**Comment by eduard-sukharev** [comment]
I have this exact same problem. The S3 endpoint I am trying to connect to looks like following:
```
https://cdn.company.com/api/v2/s3/bucketname
```
I use `league/flysystem` with `league/flysystem-aws-s3-v3` adapter, which basically requires preconfigured S3 Client instance:

```php
                $client = new S3Client([
                    'endpoint' => $uri,
                    'credentials' => $s3credentials,
                    'region' => $s3region,
                    'version' => 'latest',
                    'debug' => true,
                    'use_path_style_endpoint' => true,
                ]);
                $adapter = new AwsS3Adapter($client, $s3bucket);

                $filesystems[] = new Filesystem($adapter);
```

When I set `$uri` to be `https://cdb.company.com/` I get the following in debug output:
```
-> Entering step build, name 'builder'
--------------------------------------
  request.instance was set to 0000000057fcd5aa00000000776072f9
  request.method was set to GET
  request.headers was set to array(2) {
    ["X-Amz-Security-Token"]=>
    string(7) "[TOKEN]"
    ["Host"]=>
    array(1) {
      [0]=>
      string(11) "cdn.company.com"
    }
  }
  
  request.scheme was set to https
  request.path was set to /bucketname
  request.query was set to list-type=2&prefix=&delimiter=%2F
```
which fails, as the S3 service is not on `https://cdn.company.com/bucketname` (I get XML parse error, since S3Client cannot parse the HTML of a login page of our CDN service).

When I set `$uri` to be `https://cdb.company.com/api/v2/s3/` I get the following in debug output:
```
-> Entering step build, name 'builder'
--------------------------------------
  request.instance was set to 000000006c2de9360000000072467425
  request.method was set to GET
  request.headers was set to array(2) {
    ["X-Amz-Security-Token"]=>
    string(7) "[TOKEN]"
    ["Host"]=>
    array(1) {
      [0]=>
      string(11) "cdn.company.com"
    }
  }
  
  request.scheme was set to https
  request.path was set to /api/v2/s3/api/v2/s3/bucketname
  request.query was set to list-type=2&prefix=&delimiter=%2F
```
which fails with 403, as it probably assumes that I am attempting to access a `/v2/s3/bucketname` file in an `api` bucket (for which credentials do not match as it does not actually exists).

**Comment by stobrien89** [comment]
Hi @eduard-sukharev,

Sorry to hear about the issues.  This is an atypical path for what our rules-based endpoint provider expects, so I think in this case, adding `'endpoint_provider' => \Aws\Endpoint\PartitionEndpointProvider::defaultProvider()` should resolve this for you.

**Comment by eduard-sukharev** [comment]
@stobrien89 Thanks for the tip. That indeed did the trick! Although, it's unclear to me how and why.

**Comment by cirolosapio** [comment]
@eduard-sukharev are you using laravel? 

If yes, where did you pur the ’endpoint_provider’ config?

**Comment by freefreeP** [comment]
> @eduard-sukharev are you using laravel?
> 
> If yes, where did you put the `endpoint_provider` config?
> 
> UPDATE puting it in `config/filesystems.php` works, but on laravel `config:cache` command it throws a `LogicException: Your configuration files are not serializable`

same issue here using laravel 11

**Comment by cirolosapio** [comment]
> > @eduard-sukharev are you using laravel?
> > If yes, where did you put the `endpoint_provider` config?
> > UPDATE puting it in `config/filesystems.php` works, but on laravel `config:cache` command it throws a `LogicException: Your configuration files are not serializable`
> 
> same issue here using laravel 11

i've added `config(['filesystems.disks.s3.endpoint_provider' => \Aws\Endpoint\PartitionEndpointProvider::defaultProvider()]);` to the `AppServiceProvider.php`
