### ISSUE TITLE
Reducing package size

### ISSUE THREAD

**Issue by tamedevelopers** [aws/aws-sdk-php#2786]
### Describe the bug

Under this discussion: https://github.com/aws/aws-sdk-php/discussions/2420

```
{
   "scripts": {
        "pre-autoload-dump": "Aws\\Script\\Composer\\Composer::removeUnusedServices"
    },
    "extra": {
        "aws/aws-sdk-php": [
            "Ec2",
            "CloudWatch"
        ]
    }
}
```

When you run the composer update it throws the `Current Behavior` section.

But when you run again the second time, it goes through without no error. AM trying to use this on my project and having this error for now.

### Expected Behavior

Should update or install smoothly without any errors

### Current Behavior

Generating autoload files
> Aws\Script\Composer\Composer::removeUnusedServices
Script Aws\Script\Composer\Composer::removeUnusedServices handling the pre-autoload-dump event terminated with an exception

In Filesystem.php line 200:

  Failed to remove directory "C:\xampp\htdocs\Github\file/vendor/aws/aws-sdk-php/src/data/runtime.sagemaker": rmdir(C:\xampp\htdocs\Github\file/vendor/aws/aws-sdk-php/src/data/runtime.sagemaker): Directory not empty  

### Reproduction Steps

{
    "name": "tamedevelopers/file",
    "description": "PHP Library for uploading files",
    "type": "library",
    "require": {
        "php": ">=8.0",
        "tamedevelopers/support": "^1.0.2",
        "aws/aws-sdk-php": "^3.281.13"
    },
    "autoload": {
        "psr-4": {
            "Tamedevelopers\\File\\": "src/"
        },
        "files": [
            "src/helpers.php"
        ]
    },
    "scripts": {
        "pre-autoload-dump": "Aws\\Script\\Composer\\Composer::removeUnusedServices"
    },
    "extra": {
        "aws/aws-sdk-php": [
            "Ec2",
            "CloudWatch"
        ]
    },
    "minimum-stability": "stable"
}

### SDK version used

3.282.1.0

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

8.1

**Comment by stobrien89** [comment]
Hi @tamedevelopers,

Sorry to hear about the issues.  Does this always fail on the first attempt with the `runtime.sagemaker` service, or does it occur with a different service each time? Also, are you using your app on a shared filesystem?

**Comment by tamedevelopers** [comment]
Am not using on a shared system.

The error always occur on first trial and when u run composer update again. It'll go smoothly without any errors.

Am using it on a Custom composer package am building and have required it by default.

But content too judge of about 30mb. But using the above method reduces it to 8+mb. Which is reasonable.

Only that error issue is what is at hand now.

Thanks

**Comment by stobrien89** [comment]
Thanks for the additional info.  What I was trying to ask is whether or not this always fails on the 1st attempt with the directory `C:\xampp\htdocs\Github\file/vendor/aws/aws-sdk-php/src/data/runtime.sagemaker`.  I'm curious to know if it's always `runtime.sagemaker`, or if it is sometimes another service, like `codebuild` for example.

In either case, this might be happening because the directory is still being populated at the time the script is attempting to delete it.

**Comment by tamedevelopers** [comment]
Issue is always with 1st attempt.

- In either case, this might be happening because the directory is still being populated at the time the script is attempting to delete it. (Correct)

This is the Error response
```
 Failed to remove directory "C:\xampp\htdocs\Github\file/vendor/aws/aws-sdk-php/src/data/ssm": rmdir(C:\xampp\htdocs\Github\file/vendor/aws/aws-sdk-php/src/data/ssm): Directory not empty
```

And when i check the [data/ssm] folder. I can see the service is trying to remove the ssm folder and it's not empty (it has a child folder as well). 

The ssm folder has another child folder called [2014-11-06] and trying to delete the ssm folder, without deleting the child folder throws this error.

Folder path
vendor/aws/aws-sdk-php/src/data/ssm/2014-11-06.

The vendor update still push through on notice, but it always throws that error on first time after we update composer.json file with the provided code.


```
"scripts": {
        "pre-autoload-dump": "Aws\\Script\\Composer\\Composer::removeUnusedServices"
    },
    "extra": {
        "aws/aws-sdk-php": [
            "Ec2",
            "CloudWatch"
        ]
    },
```

**Comment by stobrien89** [comment]
Hi @tamedevelopers,

Thanks for the detailed response. I think a retry mechanism might help here— Let me see what I can come up with.

**Comment by stobrien89** [comment]
Hi @tamedevelopers,

Just added a retry mechanism to the script.  Could you update to the latest version and let me know if anything has changed?
