### ISSUE TITLE
Blocking error using LambdaClient::invokeWithResponseStream()

### ISSUE THREAD

**Issue by paoloconi96** [aws/aws-sdk-php#2787]
### Describe the bug

When trying to use `invokeWithResponseStream` method of the `LambdaClient` an exception is raised: "ErrorException:
Notice: Undefined index: ErrorCode".
The problem is due to the fact that the library expects a wrong structure in the last part of the stream (`InvokeWithResponseStreamCompleteEvent` array in `api-2.json.php` file descriptor).

### Expected Behavior

When calling the client method it should not throw any exception.
After a completed request I should be able to build a complete response from the stream, containing the content or, if something failed, a JSON representation of the object documented here: https://docs.aws.amazon.com/lambda/latest/dg/API_InvokeWithResponseStreamCompleteEvent.html.

### Current Behavior

The method consistently throws an exception, whether the Lambda execution succeeds or fails.

### Reproduction Steps

```php
        $lambdaClient = new LambdaClient([
            'region' => 'eu-west-1',
            'version' => '2015-03-31',
            'credentials' => [REDACTED],
        ]);

        $lambdaClient->invokeWithResponseStream([
            'FunctionName' => 'function-name',
            'Payload' => json_encode([], JSON_THROW_ON_ERROR),
        ]);

        foreach($result['EventStream'] as $event) {
            if (isset($event['InvokeComplete'])) {
                var_dump($event['InvokeComplete']);
            } else if (isset($event['PayloadChunk'])) {
                var_dump($event['PayloadChunk']);
            }
        }
``` 

### Possible Solution

I'm available to open a pull request to fix this issue but I would like to have you opinion about the best way to solve the issue.
I investigated the issue a bit and discovered the following. 

The issue is mainly related to the fact that currently `EventParsingIterator::parseEvent()` handles the main structure members only in a limited number of cases, mainly:
1. the member is in the header;
2. the member is in the payload AND is a blob
3. the member is in the payload AND is a `StructureShape`

For `InvokeWithResponseStreamCompleteEvent` the members are actually in the payload, which is a stream containing the serialised JSON object. Also, if no error is thrown by the Lambda, the `InvokeComplete` event will contain an empty body `{}`.

I tried both the following solutions, I think that they are suboptimal but would actually fix the issue.
1. Describe the members of `InvokeWithResponseStreamCompleteEvent` as `shapes`.
Using a structure similar to the following it is possible to obtain a structure like this:
<img width="272" alt="image" src="https://github.com/aws/aws-sdk-php/assets/4281228/b553f4c8-cf55-4236-b1b6-b95192c28f74">

```php
    'InvokeWithResponseStreamCompleteEventErrorCode' => [
        'type' => 'structure',
        'members' => [
            'ErrorCode' => [
                'shape' => 'String',
            ],
        ],
    ],
    'InvokeWithResponseStreamCompleteEventErrorDetails' => [
        'type' => 'structure',
        'members' => [
            'ErrorDetails' => [
                'shape' => 'String',
            ],
        ],
    ],
    'InvokeWithResponseStreamCompleteEventLogResult' => [
        'type' => 'structure',
        'members' => [
            'LogResult' => [
                'shape' => 'String',
            ],
        ],
    ],
    'InvokeWithResponseStreamCompleteEvent' => [
        'type' => 'structure',
        'members' => [
            'ErrorCode' => [
                'shape' => 'InvokeWithResponseStreamCompleteEventErrorCode',
                'eventpayload' => true,
            ],
            'ErrorDetails' => [
                'shape' => 'InvokeWithResponseStreamCompleteEventErrorDetails',
                'eventpayload' => true,
            ],
            'LogResult' => [
                'shape' => 'InvokeWithResponseStreamCompleteEventLogResult',
                'eventpayload' => true,
            ],
        ],
        'event' => true,
    ],
``` 
2. Describe `InvokeWithResponseStreamCompleteEvent` similarly to `InvokeResponseStreamUpdate` delegating the consumer of the library to deserialise and decode the content of the response
<img width="324" alt="image" src="https://github.com/aws/aws-sdk-php/assets/4281228/148fff84-8e8b-4034-9af1-6f58ae66403c">

```php
    'InvokeWithResponseStreamCompleteEvent' => [
        'type' => 'structure',
        'members' => [
            'Payload' => [
                'shape' => 'Blob',
                'eventpayload' => true,
            ],
        ],
        'event' => true,
    ],
```

Obviously there would be an third solution that would be a pretty large (I think) refactoring of the `EventParsingIterator::parseEvent()` to support this particular type of structures.

### Additional Information/Context

Useful links: 
- https://docs.aws.amazon.com/lambda/latest/dg/API_InvokeWithResponseStreamResponseEvent.html
- https://docs.aws.amazon.com/lambda/latest/dg/API_InvokeWithResponseStreamCompleteEvent.html

### SDK version used

3.282.2

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 7.4.33 - Debian GNU/Linux 11 (bullseye)

**Comment by stobrien89** [comment]
Hi @paoloconi96,

https://github.com/aws/aws-sdk-php/pull/2829 has been merged and is available in the latest release. Can you give this a try now and let us know whether or not you're still having issues?

**Comment by mnapoli** [comment]
I'm not sure if this is related but `invokeWithResponseStream` does not stream the function's response. Instead it waits until the invocation is finished, and then we get the chunks.

I did test with a function returning an invocation response with multiple chunks, so the function does return a response stream (with `sleep()` in-between some of those chunks).

```php
$result = $lambda->invokeWithResponseStream([
    'FunctionName' => 'bref-demo-dev-function',
    'InvocationType' => 'RequestResponse',
    'Payload' => json_encode([]),
]);
foreach ($result['EventStream'] as $a) {
    if (isset($a['PayloadChunk']['Payload'])) {
        echo "Payload chunk\n";
//      echo "Payload chunk: " . (string) $a['PayloadChunk']['Payload'] . "\n";
    }
}
```

**Comment by stobrien89** [comment]
Hi @mnapoli, 

What you mentioned isn't related, but you can try enabling streaming responses in the HTTP handler by adding the `stream` configuration to your command input:

```php
$result = $lambda->invokeWithResponseStream([
    'FunctionName' => 'bref-demo-dev-function',
    'InvocationType' => 'RequestResponse',
    'Payload' => json_encode([]),
    '@http' => [
         'stream' => true
    ]
]);
```

If you're using the default (Guzzle) HTTP handler, this is the functional equivalent of enabling the [`stream` configuration](https://docs.guzzlephp.org/en/stable/request-options.html#stream) on the Guzzle client.
