### ISSUE TITLE
Unseekable S3 StreamWrapper says it is seekable

### ISSUE THREAD

**Issue by driskell** [aws/aws-sdk-php#2788]
### Describe the bug

When using a S3 stream wrapper and opening a file, without setting seekable, so it is unseekable, the stream meta data says it is seekable.

### Expected Behavior

Stream metadata should say not seekable

### Current Behavior

Stream metadata says it is seekable when it is not

### Reproduction Steps

```
$file = fopen('s3://...', 'r');
echo json_encode(stream_get_meta_data($file));
```

```
{"timed_out":false,"blocked":true,"eof":false,"wrapper_data":{"context":null},"wrapper_type":"user-space","stream_type":"user-space","mode":"r","unread_bytes":0,"seekable":true,"uri":"s3://..."}
```

### SDK version used

3.279.1

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.0.30 (cli) (built: Aug  3 2023 17:13:08) ( NTS ) / MacBook Apple Sillicon M1

**Comment by stobrien89** [comment]
Hi @driskell,

Thanks for reaching out.  This is an unfortunate quirk of the streamwrapper customization and it doesn't look like there's a great way for us to override this.  

We've [documented](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-stream-wrapper.html#opening-seekable-streams) our reasoning behind making streams opened in `r` unseekable by default and outline the steps needed to make a stream opened in `r` mode seekable.
