### ISSUE TITLE
Retire PEAR Channel?

### ISSUE THREAD

**Issue by jeremeamia** [aws/aws-sdk-php#280]
[PHPUnit is retiring their PEAR channel](https://github.com/sebastianbergmann/phpunit/issues/1229) by the end of this year. Since both version 1 and 2 of the AWS SDK for PHP can be installed via [Composer](https://getcomposer.org/)/[Packagist](https://packagist.org/), is it OK if we do the same thing? Does anyone use [the PEAR channel](http://pear.amazonwebservices.com/) as part of their production deployment process?

**Comment by tgskiv** [comment]
Hello, guys.
Can you recommend what to do for CakePHP`users that can`t automatically install PHPUnit 3.7 with all dependencies.
Any PEAR mirror? 
Maybe some packages?
