### ISSUE TITLE
 A \"region\" configuration value is required for the \"ivs\" service

### ISSUE THREAD

**Issue by khoanld-98** [aws/aws-sdk-php#2801]
### Describe the bug

aws-sdk-php seems to take its own configuration to create the instance, how to clear it?

i runned config:clear, cache:clear but it's stilled error

/vendor/aws/aws-sdk-php/src/ClientResolver.php(358): Aws\\ClientResolver->throwRequired(Array)
vendor/aws/aws-sdk-php/src/AwsClient.php(222): Aws\\ClientResolver->resolve(Array, Object(Aws\\HandlerList))

### Expected Behavior

clear configuration 

### Current Behavior

aws-sdk-php seems to take its own configuration to create the instance, how to clear it?

### Reproduction Steps

update aws-sdk-php
create ivsService and create instance ivs_chat in contructor
run php config:clear
rollback and delete ivsService

### SDK version used

3.173.17

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

7.4.33

**Comment by yenfryherrerafeliz** [comment]
Hi @khoanld-98, thanks for opening this issue. Can you please confirm if you are working with Laravel or any other PHP framework?, so I can better reproduce your issue.

Thanks!
