### ISSUE TITLE
Pinpoint JSON Body Isn't JSON

### ISSUE THREAD

**Issue by aronduby** [aws/aws-sdk-php#2808]
### Describe the bug

I'm using Pinpoint to send web push notifications through FCM. When I set the GCMMessage.Data parameter in sendMessage it comes through to the frontend as pinpoint.jsonBody but it's not JSON encoded.

```
pinpoint.jsonBody:  ""{greeting=Hello, how are you?, notification_hash=aron-TestNotification-18-65412f684d1373.42976821, target=World}""
```

### Expected Behavior

It would be fully json encoded and I could just call JSON.parse and it would work

### Current Behavior

It comes through not json encoded

### Reproduction Steps

```php
<?php
$pinpointClient->sendMessages([
    'ApplicationId' => self::getPinpointProjectId(),
    'MessageRequest' => [
        'GCMMessage' => [
            'Data' => [
                'greeting' => 'Hello, how are you?',
                'target' => 'World',
                'notification_hash' => 'aron-TestNotification-18-65412f684d1373.42976821'
            ]
        ]
    ],
]);
```

### SDK version used

3.261.14

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

php 8.2 Ubuntu 20.04.6 LTS

**Comment by yenfryherrerafeliz** [comment]
Hi @aronduby, sorry to hear about your issues. You need to specify the GCMMessage parameter under the MessageConfiguration parameter as follow:
```php
$pinpointClient->sendMessages([
    'ApplicationId' => self::getPinpointProjectId(),
    'MessageRequest' => [
        'MessageConfiguration' => [
            'GCMMessage' => [
                'Data' => [
                    'greeting' => 'Hello, how are you?',
                    'target' => 'World',
                    'notification_hash' => 'aron-TestNotification-18-65412f684d1373.42976821'
                ]
            ]
        ]
    ],
]);
```

Could you please try with the previous code and confirm if the issue still persists?

Thanks!

**Comment by aronduby** [comment]
Apologies, that was a mistake on my behalf when trying to get to the smallest reproducible code without a lot of project related stuff. I have confirmed that it is sent under the `MessageConfiguration` key.

```php
// in the notification class

public function toPinpointPush($notifiable): array {
    $msg = parent::toPinpointPush($notifiable);

    $msg['Data'] = [
        'target' => 'World',
        'greeting' => 'Hello',
    ];

    return $msg;
}
```

```php
// in my sending class

$messageRequest['Endpoints'][$endpoint['pinpoint']['endpoint_id']] = [];
$gcmMessage = $notification->toPinpointPush($notifiable);

// Pinpoint won't send the url if it doesn't have an action of URL, so make sure it has that
if (array_key_exists('Url', $gcmMessage) && !array_key_exists('Action', $gcmMessage)) {
    $gcmMessage['Action'] = 'URL';
}

// add the notification hash into the data
$gcmMessage['Data'] = array_merge($gcmMessage['Data'] ?? [], ['notification_hash' => $notificationHash]);

// Data does not work right - so we are going to dance around it
// https://github.com/aws/aws-sdk-php/issues/2808
// $gcmMessage['Data'] = [
//     '::JSON::' => json_encode($gcmMessage['Data'])
// ];

$messageRequest['MessageConfiguration']['GCMMessage'] = $gcmMessage;

// ...

$pinpointClient = self::getPinpointClient();
$results = $pinpointClient->sendMessages([
    'ApplicationId' => self::getPinpointProjectId(),
    'MessageRequest' => $messageRequest
]);
```

Then on the front end I have the following code receiving the message through FCM

```javascript
onMessage(messaging, (payload) => {
    console.log('Message received. ', payload);
});
```

Which results in this in the console:
![image](https://github.com/aws/aws-sdk-php/assets/650070/a9cb3eaf-9c2c-4a32-81e4-05bb1dad0a4b)

**Comment by yenfryherrerafeliz** [comment]
@aronduby thanks for clarifying. I have opened a ticket against the service team to better investigate this. I will get back to you once I get an answer from them.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
V1109454414

**Comment by yenfryherrerafeliz** [comment]
Hi @aronduby, I have gotten confirmation from the service that this has been fixed now. Can you please check and confirm is working for you?

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Closing for now. Please reopen if the issue still persists or open a new issue for anything else that we can help with.

Thanks!

**Comment by aronduby** [comment]
@yenfryherrerafeliz I have confirmed this is working as expected for me now, thank you!
