### ISSUE TITLE
SQSClient receiveMessage JSON Parse error

### ISSUE THREAD

**Issue by xto** [aws/aws-sdk-php#2821]
### Describe the bug

Calling `receiveMessage` on an instance of SqsClient throws an exception. We found this through a library upgrade triggered by Dependabot as it failed our CI. Here's the most minimal code to that triggers the exception.

```php
    public function testJsonFailure(): void
    {
        $awsSdk = $this->client->getContainer()->get(AwsSdk::class);
        $sqsClient = $awsSdk->createSqS();
        $result = $sqsClient->receiveMessage(
            [
                'MaxNumberOfMessages' => 1,
                'QueueUrl' => "http://aws:4566/000000000000/internal_job_queue_dlq",
                'WaitTimeSeconds' => 0
            ]
        );
        $this->assertNull($result->get('Messages'));
    }
```

I did some digging and at https://github.com/aws/aws-sdk-php/blob/3.285.1/src/Api/Parser/PayloadParserTrait.php#L18, `$json` holds a  `GuzzleHttp\Psr7\Stream` object and calling `getContents` on that object revealed that it does not contain a JSON string but rather an XML string. This is the result of `dump($json->getContents())`:

```xml
 "<ReceiveMessageResponse><ReceiveMessageResult></ReceiveMessageResult><ResponseMetadata><RequestId>4PDN22TK8BPVAKSD643TKWBWUD8BHMKZIF8VNGJ3JLXTCLH8811J</RequestId></ResponseMetadata></ReceiveMessageResponse>"
```

This issue was not present in 3.285.0

### Expected Behavior

The expected behaviour is that the parser receives a JSON payload and parses it successfully

### Current Behavior

An exception happens with the following message gets thrown: 
`Aws\Api\Parser\Exception\ParserException: Error parsing JSON: Syntax error`

### Reproduction Steps

```php
<?php

namespace MyApp\IntegrationTest;

use Aws\Sdk;
use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class InternalJobQueueTest extends WebTestCase
{
    protected KernelBrowser $client;

    /**
     * @test
     */
    public function testJsonFailure(): void
    {
        self::createKernel();
        $this->client = self::createClient();

        $awsSdk = $this->client->getContainer()->get(Sdk::class);
        $sqsClient = $awsSdk->createSqS();
        $result = $sqsClient->receiveMessage(
            [
                'MaxNumberOfMessages' => 1,
                'QueueUrl' => "http://aws:4566/000000000000/internal_job_queue_dlq",
                'WaitTimeSeconds' => 0
            ]
        );
        $this->assertNull($result->get('Messages'));
    }
}

```

### SDK version used

3.285.1

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.2.4

**Comment by yenfryherrerafeliz** [comment]
Hi @xto, sorry to hear about your issues. I am not sure what could be causing this at your end. I just tried to reproduce this but I was not able to.
Here is the code I have used:
```php
<?php

use Aws\Sqs\SqsClient;

require '../vendor/autoload.php';

$client = new SqsClient(['region' => 'us-east-2']);
$response = $client->receiveMessage([
    'QueueUrl' => 'test-queue',
    'MaxNumberOfMessages' => 1,
    'WaitTimeSeconds' => 0
]);

print_r($response);
```
Here is the response:
<details>
<summary>Response</summary>

```text
Aws\Result Object
(
    [data:Aws\Result:private] => Array
        (
            [Messages] => Array
                (
                )

            [@metadata] => Array
                (
                    [statusCode] => 200
                    [effectiveUri] => https://sqs.us-east-2.amazonaws.com/test-queue
                    [headers] => Array
                        (
                            [x-amzn-requestid] => REQ-ID
                            [date] => Tue, 14 Nov 2023 17:32:57 GMT
                            [content-type] => application/x-amz-json-1.0
                            [content-length] => 15
                            [connection] => keep-alive
                        )

                    [transferStats] => Array
                        (
                            [http] => Array
                                (
                                    [0] => Array
                                        (
                                        )

                                )

                        )

                )

        )

    [monitoringEvents:Aws\Result:private] => Array
        (
        )

)
```
</details>

Could you please try to create new project from scratch and test it?, also, could you please make sure the SDK dependency is up to date?.

I look forward to your response.

Thanks!

**Comment by stobrien89** [comment]
@xto,

Also, could you could provide debug logs from the offending test by adding `debug` => `true` to your client config? Please make sure to obscure any sensitive information.

**Comment by bentsku** [comment]
It seems the PHP SDK is still sending `SendMessage` and other queue related requests to the Queue URL when using the `json` protocol, when it should target the root path of the domain as per the documentation and the other SDKs.

It works with AWS, but it does not really follow the `json` protocol specifications.

**Comment by bentsku** [comment]
Hello, I believe this issue might be related to LocalStack, see https://github.com/localstack/localstack/issues/8267

@xto this should now be fixed in the latest version of LocalStack, you can read about it in the linked issue.

**Comment by xto** [comment]
@bentsku thanks for the info. I'll report back on my issue after trying updating `localstack`.

**Comment by stobrien89** [comment]
@xto,

Sorry for the confusion.  #2822 prompted an investigation on our side into how we were sending requests with `QueueUrl`.  That issue has been fixed now and will be available in today's release.  Localstack's changes should resolve the xml response issue, but you may need to update your code to expect an empty `Messages` in the response as opposed to null.

**Comment by ziyanli-amazon** [comment]
@xto @stobrien89 Thanks guys. SQS is also fixing the `Messages` being returned as `null` as opposed to an empty array if no messages exist.

**Comment by ziyanli-amazon** [comment]
@bentsku Thanks for fixing the LocalStack.

**Comment by xto** [comment]
I'm going to close this. Upgrading to the latest localstack version seems to have resolved the error. Thanks for the assist @bentsku @stobrien89 @yenfryherrerafeliz 🙇
