### ISSUE TITLE
SqsClient sending requests to Queue URL with json protocol

### ISSUE THREAD

**Issue by bentsku** [aws/aws-sdk-php#2822]
### Describe the bug

It seems the PHP SDK is still sending `SendMessage` and other queue related requests to the Queue URL when using the `json` protocol, when it should target the root URL as per the documentation and the other SDKs behavior.

It works with AWS, but it does not really follow the `json` protocol specifications. 

From the Smithy specs:
https://smithy.io/2.0/aws/protocols/aws-json-1_0-protocol.html#protocol-behaviors
> Every request for the awsJson1_0 protocol MUST be sent to the root URL (/) using the HTTP "POST" method.

I believe this should be fixed to be in compliance with the Smithy specification for the `awsJson1_0` protocol. 

### Expected Behavior

The AWS PHP SDK should send all requests to the root URL when targeting SQS with the `json` protocol. 

### Current Behavior

The PHP SDK is still sending requests to the Queue URL, as shown by this log:

```php
Aws\Result Object
(
    [data:Aws\Result:private] => Array
        (
            [Messages] => Array
                (
                )

            [@metadata] => Array
                (
                    [statusCode] => 200
                    [effectiveUri] => https://sqs.us-east-2.amazonaws.com/test-queue
                    [headers] => Array
                        (
                            [x-amzn-requestid] => REQ-ID
                            [date] => Tue, 14 Nov 2023 17:32:57 GMT
                            [content-type] => application/x-amz-json-1.0
                            [content-length] => 15
                            [connection] => keep-alive
                        )

                    [transferStats] => Array
                        (
                            [http] => Array
                                (
                                    [0] => Array
                                        (
                                        )

                                )

                        )

                )

        )

    [monitoringEvents:Aws\Result:private] => Array
        (
        )

)

```

Especially this part: `[effectiveUri] => https://sqs.us-east-2.amazonaws.com/test-queue`

### Reproduction Steps

```php
<?php

use Aws\Sqs\SqsClient;

require '../vendor/autoload.php';

$client = new SqsClient(['region' => 'us-east-2']);
$response = $client->receiveMessage([
    'QueueUrl' => 'test-queue',
    'MaxNumberOfMessages' => 1,
    'WaitTimeSeconds' => 0
]);

print_r($response);
```

### Possible Solution

Maybe the issue lies here, for the new protocol we don't need to append the `QueueUrl` anymore to the endpoint?
https://github.com/aws/aws-sdk-php/blob/f3276ecb6e5202452d4b64237e6dc1bc9d350ae6/src/Sqs/SqsClient.php#L67

### SDK version used

3.286.1

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.2.12 / macOS Sonoma 14.1

**Comment by stobrien89** [comment]
@bentsku,

Thanks for letting us know.  SQS recently migrated from query to json protocol— looks like the culprit is [this middleware](https://github.com/aws/aws-sdk-php/blob/f3276ecb6e5202452d4b64237e6dc1bc9d350ae6/src/Sqs/SqsClient.php#L101,L117) we add to the SQS client's handler list.  This is no longer needed.

**Comment by bentsku** [comment]
Awesome, thanks for investigating!

**Comment by bentsku** [comment]
Thank you for providing such a quick fix!
