### ISSUE TITLE
Operation not found: GetHLSStreamingSessionURL  

### ISSUE THREAD

**Issue by libaipengl** [aws/aws-sdk-php#2832]
### Describe the bug

composer require aws/aws-sdk-php  ,
  Get live streaming push pull, Encountering current problems
What should I do
Or the latest method for obtaining push pull streams

### Expected Behavior

Output push pull stream address

### Current Behavior

Operation not found: GetHLSStreamingSessionURL  

### Reproduction Steps

Operation not found: GetHLSStreamingSessionURL  

### SDK version used

composer require aws/aws-sdk-php

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

php 7.4

**Comment by stobrien89** [comment]
Hi @libaipengl,

Sorry to hear about the issues.  This operation has been available to the `KinesisVideoArchivedMedia` client for several years now.  Which version of the SDK are you using?

**Comment by libaipengl** [comment]
"aws/aws-sdk-php": "^3.287"

**Comment by libaipengl** [comment]
hello @stobrien89 
Current version:

Aws/aws sdk php ":" ^ 3.287 ",

Can you provide the development code required to obtain the address of the push pull stream?

And related documents Thank you

**Comment by stobrien89** [comment]
Hi @libaipengl,

You can find the documentation for this operation [here](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-kinesis-video-archived-media-2017-09-30.html#gethlsstreamingsessionurl).  Here's an example of what it might look like:

```
<?php

require 'vendor/autoload.php';

use Aws\KinesisVideoArchivedMedia\KinesisVideoArchivedMediaClient;

$kinesisClient = new KinesisVideoArchivedMediaClient([
    'region' => <your_region_here>
]);

//Define your arguments based on the documented operation arguments
$args = [<your_args_here>]

$result = $kinesisClient->getHLSStreamingSessionURL($args);
```

Hope this helps!

**Comment by libaipengl** [comment]
Error executing "GetStreamSession" on "https://ivs.ap-northeast-1.amazonaws.com/GetStreamSession"; AWS HTTP error: Client error: `POST https://ivs.ap-northeast-1.amazonaws.com/GetStreamSession` resulted in a `400 Bad Request` response:
{"Code":"ValidationException","Message":"GetStreamSession.channelArn does not match the required pattern ^arn:aws:[is]vs (truncated...)
ValidationException (client): GetStreamSession.channelArn does not match the required pattern ^arn:aws:[is]vs:[a-z0-9-]+:[0-9]+:channel/[a-zA-Z0-9-]+$ - {"Code":"ValidationException","Message":"GetStreamSession.channelArn does not match the required pattern ^arn:aws:[is]vs:[a-z0-9-]+:[0-9]+:channel/[a-zA-Z0-9-]+$","RequestID":"OqomrF4xtjMEWnQ

**Comment by libaipengl** [comment]
`        $kinesisVideoArchivedMediaClient = new KinesisVideoArchivedMediaClient([
            'version' => 'latest',
            'region' => 'ap-northeast-1',
            'credentials' => [
                'key' =>'xxxxx',
                'secret' => 'xx/xx',
            ],
        ]);
        $channelArn = 'arn:aws:ivs:ap-northeast-1:526972394711:playback-key/XRefx2bj2AOP';
        $streamKey = 'Playback-key-live'; // Replace with your actual stream key

        $streamName = 'live001';
        $startTimestamp = '2023-11-20T00:00:00Z';
        $endTimestamp = '2023-12-19T00:00:00Z';
        try {

        $result = $kinesisVideoArchivedMediaClient->getHLSStreamingSessionURL([
            'StreamName' => $streamName,
            'StartTime' => strtotime($startTimestamp) * 1000, // Convert to milliseconds
            'EndTime' => strtotime($endTimestamp) * 1000, // Convert to milliseconds
            'PlaybackMode' => 'LIVE',
        ]);
        $hlsPlaybackUrl = $result['HLSStreamingSessionURL'];
        if ($hlsPlaybackUrl) {
            echo "HLS Playback URL: $hlsPlaybackUrl\n";
        } else {
            echo "Error: Empty HLS Playback URL\n";
        }
        } catch (AwsException $e) {
            echo "AWS Error: " . $e->getMessage() . "\n";
            echo "AWS Error Code: " . $e->getAwsErrorCode() . "\n";
            echo "AWS Error Type: " . $e->getAwsErrorType() . "\n";
        }`


Return the result Error through the above code: Empty HLS Playback URL

May I ask what to do if I don't understand the document? Thank you

**Comment by libaipengl** [comment]
Can you provide a complete example or address

**Comment by stobrien89** [comment]
Hi @libaipengl,

If I'm understanding correctly, you're getting an empty `HLSStreamingSessionURL`? I'm not entirely sure why that would be the case.  [The Kinesis Video Archived Media API reference](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_reader_GetHLSStreamingSessionURL.html) might contain additional context that we don't share in our documentation.  

If the documentation linked above doesn't help, please provide debug logs for the call by adding `'debug' => true` your client code.  Please make sure to obscure any sensitive information such as account numbers.

**Comment by libaipengl** [comment]
How to obtain video sources with different resolutions, such as 480, 720, and 1080


Please advise. Thank you

快点闪开了
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aws/aws-sdk-php"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月30日(星期四) 凌晨5:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aws/aws-sdk-php] Operation not found: GetHLSStreamingSessionURL   (Issue #2832)





 
Hi @libaipengl,
 
If I'm understanding correctly, you're getting an empty HLSStreamingSessionURL? I'm not entirely sure why that would be the case.  The Kinesis Video Archived Media API reference might contain additional context that we don't share in our documentation.
 
If the documentation linked above doesn't help, please provide debug logs for the call by adding 'debug' =&gt; true your client code.  Please make sure to obscure any sensitive information such as account numbers.
