### ISSUE TITLE
AwsS3S3Client::AwsS3{closure}(): Argument #1 ($e) must be of type AwsExceptionAwsException

### ISSUE THREAD

**Issue by RaviJayagopal** [aws/aws-sdk-php#2845]
### Describe the bug

The following code is resulting in the error:
AwsS3S3Client::AwsS3{closure}(): Argument #1 ($e) must be of type AwsExceptionAwsException, TypeError given, called in /home/customer/www/<domain>/<pluginpath>/vendor/guzzlehttp/promises/src/Promise.php on line 203

$s3Client = new Aws\S3\S3MultiRegionClient([
	'version'     => 'latest',
	'region'      => 'us-east-1',
	'credentials' => [
		'key'    => $accessKey,
		'secret' => $secretKey,
	],
]);
            
$region = $s3Client->determineBucketRegion($bucketname);

The script crashes at the last line above at the determineBucketRegion call, and $region is null after the statement.

This works fine in PHP 7.x (tested up to v7.4.33), but crashes in all versions of PHP 8.x (tested up to v8.2.12).

AWS SDK: 
"aws/aws-sdk-php": "3.x",
"guzzlehttp/guzzle": "7.8.*",
"guzzlehttp/promises": "2.0.*",

TIA for your help.

### Expected Behavior

$region should have a valid region value, and the code should not crash.

### Current Behavior

Code crashes at:

$region = $s3Client->determineBucketRegion($bucketname);

### Reproduction Steps

$s3Client = new Aws\S3\S3MultiRegionClient([
	'version'     => 'latest',
	'region'      => 'us-east-1',
	'credentials' => [
		'key'    => $accessKey,
		'secret' => $secretKey,
	],
]);
            
$region = $s3Client->determineBucketRegion($bucketname);

### SDK version used

3.x

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.x

**Comment by RaviJayagopal** [comment]
The above issue still remains, but I found a workaround. So noting it here FWIW.

So instead of $s3Client->determineBucketRegion($bucketname), I used the following code to get the region, and I was able to get the region:

$result = $s3Client->getBucketLocation([
    'Bucket' => $bucketname,
]);
            
$region = $result['LocationConstraint'];

**Comment by yenfryherrerafeliz** [comment]
Hi @RaviJayagopal, can you please confirm the SDK version that you are using? since you probably would need to update. You can verify this by running: ``` composer show aws/aws-sdk-php | grep "versions :" ```. I just did a test using the version 3.291.0 and I did not have any issues.

My code:
```php
<?php
require '../vendor/autoload.php';

use Aws\S3\S3Client;

$client = new S3Client(['region' => getenv('TEST_REGION')]);
$response = $client->determineBucketRegion(getenv('TEST_BUCKET'));

print_r([$response]);
```
Response I got:
```php
Array
(
    [0] => us-east-2
)
```
My PHP version:
```console
USER@3c0630413e17 issue-2845 % php -v
PHP 8.3.0 (cli) (built: Nov 24 2023 13:21:02) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.0, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.0, Copyright (c), by Zend Technologies

```
Please let me know.

Thanks!
