### ISSUE TITLE
no longer possible to use ElasticMQ since 3.286.2

### ISSUE THREAD

**Issue by ppaulis** [aws/aws-sdk-php#2846]
### Describe the bug

We re using lots of AWS SQS queues in our production environments. But in our builds (BDD with Behat) we are using ElasticMQ which simulates the AWS SQS API. This is necessary because we are parallelizing test suites.

Since [3.286.2](https://github.com/aws/aws-sdk-php/releases/tag/3.286.2) however (more precisely this [commit](https://github.com/aws/aws-sdk-php/commit/7148ad1ce3d9d7494a55071e34b864739f220636)), it is no longer possible to use ElasticMQ :

```
// Create SQS client
$sqsClient = new SqsClient([
    'version'     => '2012-11-05',
    'region'      => $this->awsRegion,
    'credentials' =>
        [
            'key'    => $this->awsKey,
            'secret' => $this->awsSecret,
        ]
]);

$sqsClient->purgeQueue(['QueueUrl' => 'http://elasticmq:9324/000000000000/myQueue.fifo']);
```

The problems seems to be, that the hostname is ignored and the request is redirected to AWS servers :
```
Error executing "PurgeQueue" on "https://sqs.eu-central-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://sqs.eu-central-1.amazonaws.com` resulted in a `404 Not Found` response: {"__type":"com.amazonaws.sqs#InvalidAddress","message":"The address https://sqs.eu-central-1.amazonaws.com/ is not valid (truncated...)
InvalidAddress (Sender): The address https://sqs.eu-central-1.amazonaws.com/ is not valid for this endpoint. - {"__type":"com.amazonaws.sqs#InvalidAddress","message":"The address https://sqs.eu-central-1.amazonaws.com/ is not valid for this endpoint."} (Aws\Sqs\Exception\SqsException)
```

If there's an alternative to specifying the Hostname in the QueueUrl, we would gladly change our code. But no longer being able to contact ElasticMQ (or similar containerized services) would be a real show stopper to do Acceptance testing in applications.

### Expected Behavior

Expected behaviour is that the SqsClient contacts the endpoint contained in the QueueUrl, instead of always contacting SQS servers.

### Current Behavior

Despite having a complete Queue URL with hostname (different from AWS SQS servers) in the SqsClient configuration, the SqsClient contacts AWS SQS servers.

### Reproduction Steps

```
// Create SQS client
$sqsClient = new SqsClient([
    'version'     => '2012-11-05',
    'region'      => $this->awsRegion,
    'credentials' =>
        [
            'key'    => $this->awsKey,
            'secret' => $this->awsSecret,
        ]
]);

$sqsClient->purgeQueue(['QueueUrl' => 'http://elasticmq:9324/000000000000/myQueue.fifo']);
```

To reproduce this, a docker container with ElasticMQ is needed on `http://elasticmq:9324`.

### Possible Solution

In our case, the problem would be solved by re-adding the possibility to use SQS-compatible queues outside of AWS.
However, if there is a possibility in the configuration, that we are currently missing, any hint is appreciated.

### SDK version used

3.286.2

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.1.23 / Alpine linux docker container

**Comment by yenfryherrerafeliz** [comment]
Hi @ppaulis, sorry to hear about your issues. While we investigate this further, would you please be able to try setting the endpoint in the client as follow:

```php
<?php

require '../vendor/autoload.php';

use Aws\Sqs\SqsClient;

$client = new SqsClient([
    'region' => getenv('TEST_REGION'),
    'endpoint' =>  'YOUR_CUSTOM_ENDPOINT' // in this case I guess it would be "http://elasticmq:9324"
]);
$response = $client->purgeQueue([
    'QueueUrl' => 'YOUR_QUEUE_URL'
]);

print_r([$response]);

```

I look forward to your response.

Thanks!

**Comment by stobrien89** [comment]
Hi @ppaulis,

Thanks for raising this.  SQS recently migrated from query to json protocol, which also required changes from 3rd party SQS implementations— the change you referenced was necessary to align with AWS json protocol specification, as mentioned in #2822.  

Passing a custom endpoint using the client `endpoint` argument should suffice as a workaround for now, but ultimately ElasticMQ will have to align with our json specification in order to remain compatible.
