### ISSUE TITLE
SignatureV4 mismatch on some requests

### ISSUE THREAD

**Issue by IrisJasonStanley** [aws/aws-sdk-php#2858]
### Describe the bug

I am using the aws-php-sdk to sign requests. We are signing requests to an API Gateway with the default IAM Authorizor.

```
$credentials = new Credentials(env('AWS_ACCESS_KEY_ID', ''), env('AWS_SECRET_ACCESS_KEY', ''));
$signer = new SignatureV4('execute-api', env('AWS_DEFAULT_REGION', ''));
$request = $signer->signRequest($request, $credentials);
```

We are finding that for some requests the requests are signed correctly and for others, they aren't. I am struggling to determine why this sometimes succeeds and sometimes fails.

### Expected Behavior

Request signing should always work.

### Current Behavior

Request to this URL works:
https://[redacted].execute-api.eu-west-1.amazonaws.com/dev-ew1/api/v1/users?userId[]=34129&userId[]=2405&userType=student&oktaId=[redacted]

A request to this URL fails:
https://[redacted].execute-api.eu-west-1.amazonaws.com/dev-ew1/api/v1/users?userId[]=2405&userId[]=196624&userType=student&oktaId=[redacted]

Both use the same headers and the same credentials:
```
{
    "Host": [
        "[redacted].execute-api.eu-west-1.amazonaws.com"
    ],
    "X-Platform": [
        "messaging"
    ],
    "X-Platform-Organisation": [
        "55"
    ],
}
```

Both requests are generating a signature. However, for the latter, we receive the following message:

```
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. 
Consult the service documentation for details.

The Canonical String for this request should have been
'GET
/dev-ew1/api/v1/users
oktaId=[redacted]&userId%5B%5D=196624&userId%5B%5D=2405&userType=student
host:[redacted].execute-api.eu-west-1.amazonaws.com
x-amz-date:20231218T101701Z
x-platform:messaging
x-platform-organisation:55

host;x-amz-date;x-platform;x-platform-organisation
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20231218T101701Z
20231218/eu-west-1/execute-api/aws4_request
3400b7c56695b319d050d264522b645bf19346449c2147768fc0ca10b36001cf'
```,

### Reproduction Steps

```
-- Fetch user 2405 - Works
https://[redacted].execute-api.eu-west-1.amazonaws.com/dev-ew1/api/v1/users?userId[]=2405&userType=student&oktaId=[redacted]

-- Fetch user 196624 - Works
https://[redacted].execute-api.eu-west-1.amazonaws.com/dev-ew1/api/v1/users?userId[]=196624&userType=student&oktaId=[redacted]

-- Fetch users 2405 + 196624 at the same time - Signing Error
https://[redacted].execute-api.eu-west-1.amazonaws.com/dev-ew1/api/v1/users?userId[]=2405&userId[]=196624&userType=student&oktaId=[redacted]

-- Fetch users 2405 + 34129 at the same time and this works...
https://[redacted].execute-api.eu-west-1.amazonaws.com/dev-ew1/api/v1/users?userId[]=34129&userId[]=2405&userType=student&oktaId=[redacted]
```

### Possible Solution

_No response_

### Additional Information/Context

I suspect we are doing something wrong but I cannot figure out what. With all of the debugging, everything being passed into the signing method is the same apart from the URL. I don't see anything of issue with the URLs being used.

### SDK version used

3.294.1

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

8.1

**Comment by GrahamCampbell** [comment]
This is because the encoding of the list parameters is not in a supported format. Try with:

```
https://[redacted].execute-api.eu-west-1.amazonaws.com/dev-ew1/api/v1/users?userId%5B0%5D=2405&userId%5B1%5D=196624&userType=student&oktaId=[redacted]
```

**Comment by GrahamCampbell** [comment]
(the difference being the encoding of the brackets and the use of 0 and 1 for the indices)

**Comment by IrisJasonStanley** [comment]
Thanks for taking the time to respond. Yesterday I was looking at how query string parameters were being encoded by the library and I was thinking that maybe there is a problem maintaining the order.

I had assumed that `param[]=1&param[]=2` was part of the query string spec as this is how it is handled by PHP but now I read up on it I can see this is framework specific. I will change this up today and see if it resolved the problem

**Comment by IrisJasonStanley** [comment]
That has solved the issue. Adding multiple parameters with a [] prevents the requests from being signed in a consistent way. Thanks for help with this.

**Comment by GrahamCampbell** [comment]
Yeh, there is "the query string spec", however in practice is is not followed. Many browsers and servers all do different things not in the spec. It's unfortunately pretty common (coming from someone who maintains an HTTP client). 😆

**Comment by stobrien89** [comment]
Thanks @GrahamCampbell,

I think this could be documented better.  The closest thing I could find was [this blog post](https://aws.amazon.com/blogs/compute/support-for-multi-value-parameters-in-amazon-api-gateway/) from when they first introduced support for multi-value parameters.  I'll reach out to the Api Gateway team and see if they're able to make this more visible in their developer guide.
