### ISSUE TITLE
Deprecated: Using ${var} in strings is deprecated

### ISSUE THREAD

**Issue by AJenbo** [aws/aws-sdk-php#2862]
### Describe the bug

For PHP 8.3 i get the following warning:

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in src/Api/DocModel.php on line 93

https://github.com/aws/aws-sdk-php/blob/326eb6c26e2be9d896c4aeb025e20980c06779af/src/Api/DocModel.php#L93C58-L93C58

### Expected Behavior

No warnings or errors

### Current Behavior

When this file is loaded php will emit deprecation warnings

### Reproduction Steps

`php -l src/Api/DocModel.php`

### SDK version used

3.288.1

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.3.0

**Comment by GrahamCampbell** [comment]
There is already an open PR to fix this: https://github.com/aws/aws-sdk-php/pull/2813.

**Comment by yenfryherrerafeliz** [comment]
This issue has been fixed by the following [PR](https://github.com/aws/aws-sdk-php/pull/2813). Closing for now.

Thanks!
