### ISSUE TITLE
Support 'OriginationNumber' when sending SMS.

### ISSUE THREAD

**Issue by vicreinhart** [aws/aws-sdk-php#2863]
### Describe the feature

I send many SMS messages using SNS, and the PHP V3 API.
I have multiple Origination Numbers in my Northern Virginia region.  I asked AWS Support how to specify a number.  The answer was: " I've clarified that if you are using SDK, then you can make use of the attribute - 'OriginationNumber' to specify it. I've also shared the SDK examples for your quick reference [4]."  However, when I follow that link, the 'OriginationNumber' is not mentioned in the documentation.  Please advise.  Is 'OriginationNumber' available in the PHP 3.0 SDK?  If so, can you please update the documentation?

### Use Case

I have set up a 10DLC Campaign which is only available for one of my two Origination Numbers.  I would like to be able to specify my Origination Number so that I can use the Campaign.

### Proposed Solution

Update the documentation and the API to support 'OriginationNumber' in the 'Publish' method of of the class SnsClient to send texts via SNS.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.0

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.3 on Ubuntu Linux

**Comment by yenfryherrerafeliz** [comment]
Hi @vicreinhart, this seems to be a lack of documentation from service itself. I checked the API reference documentation [here](https://docs.aws.amazon.com/sns/latest/api/API_Publish.html), and I see that they do not specify where or how a OriginationNumber attribute can be used either. I would need to reach out to them and ask regarding this.

Thanks!

**Comment by RanVaknin** [comment]
Hi @vicreinhart ,

I see that this is documented [here](https://docs.aws.amazon.com/sns/latest/dg/sms_publish-to-phone.html#sms_publish_sdk). Can you please take a look and see if it solves your issue?

Thanks,
Ran~
