### ISSUE TITLE
IRSA for Kubernetes not working

### ISSUE THREAD

**Issue by clayrisser** [aws/aws-sdk-php#2872]
### Describe the bug

Won’t connect to s3 using irsa. 

### Expected Behavior

Should connect to s3 using irsa without having to provide an access key and secret key.

### Current Behavior

Failed to connect to s3 using irsa. 

### Reproduction Steps

Use the client in an AWS pod with irsa and try to access an s3 bucket that the iam role has access to.

### SDK version used

latest

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

latest

**Comment by stobrien89** [comment]
Hi @clayrisser,

Sorry to hear about the issues.  Could you provide a bit more context in terms of a reproducible example and debug logs? For debug logs, just set `'debug' => true` in the S3 client constructor and provide us with the output of a failed call.  Please be sure to obscure any sensitive information, such as account numbers.

**Comment by clayrisser** [comment]
It turns out I misconfigued my AWS role. Sorry for the confusion.
