### ISSUE TITLE
Argument 4 passed to Aws\Exception\AwsException::__construct() must be an instance of Exception or null

### ISSUE THREAD

**Issue by dgastudio** [aws/aws-sdk-php#2874]
### Describe the bug

Argument 4 passed to Aws\Exception\AwsException::__construct() must be an instance of Exception or null

### Expected Behavior

it should work

### Current Behavior

TypeError: Argument 4 passed to Aws\Exception\AwsException::__construct() must be an instance of Exception or null, instance of Error given, called in /lib/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 205 in Aws\Exception\AwsException->__construct() (line 47 of /lib/vendor/aws/aws-sdk-php/src/Exception/AwsException.php).

### Reproduction Steps
```php
use Aws\Sqs\SqsClient; 
use Aws\Exception\AwsException;
$client = new SqsClient([
    'region' => 'us-west-2',
]);

try {
    $result = $client->listQueues();
    foreach ($result->get('QueueUrls') as $queueUrl) {
        echo "$queueUrl\n";
    }
} catch (AwsException $e) {
    // output error message if fails
    error_log($e->getMessage());
}

```

### SDK version used

3.278

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP version: 7.1.33-5 (sorry, we can't update)

**Comment by yenfryherrerafeliz** [comment]
Hi @dgastudio, sorry to hear about your issues. I tried to reproduce the reported error but I am not able to. Could you please provide any other details that could help for reproducing this issue?, could you please also enable debug logs in the client by passing the parameter 'debug' set to true.

Please make sure you redact any sensitive information.

I look forward to your response.

When working on reproducing this issue I used the following docker image:
Dockerfile
```Dockerfile
FROM php:7.1

RUN apt-get update && \
    apt-get install -y \
    git \
    unzip

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /usr/src/app

COPY . /usr/src/app

RUN composer install

RUN chmod +x src/issue.2874.php

WORKDIR /usr/src/app/src

ENV AWS_ACCESS_KEY_ID ACCESS_KEY_ID_VALUE
ENV AWS_SECRET_ACCESS_KEY SECRET_ACCESS_KEY_VALUE
ENV AWS_SESSION_TOKEN  SESSION_TOKEN_VALUE

CMD ["php", "issue.2874.php"]

```

Thanks!
