### ISSUE TITLE
Yum package

### ISSUE THREAD

**Issue by hduerkop** [aws/aws-sdk-php#2886]
### Describe the feature

This sdk available as a yum package

### Use Case

To make launch templates for EC2's more straight forward it would be helpful to have a yum package to install the aws-sdk-php globally, e.g. yum install php8.2-aws-sdk-php

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.300.4

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.2.9 (cli) (built: Aug  3 2023 11:39:08) (NTS gcc x86_64)

**Comment by RanVaknin** [comment]
Hi @hduerkop ,

Thanks for taking the time to cut us a feature request. We have discussed this as a team and have decided not to move forward with this feature. At this point in time the only package manager we are publishing to is composer.

Thanks again,
Ran~
