### ISSUE TITLE
What version  should I specify  for MediaPackage and MediaPackageVod client?

### ISSUE THREAD

**Issue by lechatthecat** [aws/aws-sdk-php#2899]
### Describe the issue

For s3 client, document says I must specify API version "2006-03-01" for production:
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/locking-api-versions.html

But on document of Media Package and Media Package Vod, there is no such version information. Should I always use "latest" for the version?

### Links

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/locking-api-versions.html
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/mediapackage/
https://docs.aws.amazon.com/mediapackage-vod/latest/apireference/what-is-mp-vod.html

**Comment by stobrien89** [comment]
Hi @lechatthecat,

Assuming you're opening this issue for PHP SDK (your links reference the JS SDK), Generally speaking, you're fine to use `latest` as your api version.  Recently we removed `version` as required argument in client constructors and set an implicit default of `latest`.  Nowadays services will just release an entirely new service when they want drastically change their API.

**Comment by lechatthecat** [comment]
@stobrien89 
Thank you for your information. Yes, I am using PHP SDK.
OK, I will use "latest" for Media Package and Media Package VOD even in Production. And I'm closing this issue.
