### ISSUE TITLE
PostObjectV4 with Custom Domain

### ISSUE THREAD

**Issue by CatoriClothing** [aws/aws-sdk-php#2905]
### Describe the bug

Hey Team,

Currently we have a domain that points directly to our bucket like bucket.x.com. We initialize the S3Client with bucket_endpoint true and endpoint as bucket.x.com and this works great when using presigned url's for GetObject. When creating pre-signed url's for PostObjectV4 however the action attribute is always bucket.x.com/bucket. use_path_style_endpoint or any other option has no effect. 

Given that GetObject works with this setup maybe it is a bug with PostObjectV4? Not sure where we are going wrong. 

### Expected Behavior

Presigned url returned from PostObjectV4 as bucket.x.com

### Current Behavior

Presigned url is always returned as bucket.x.com/bucket

### Reproduction Steps

```php
 public function getPresignedUpload()
    {

        header('Content-Type: multipart/form-data; charset=utf-8');
        $formInputs = ['acl' => 'private', 'key' => $user . '/${filename}'];

        $options = [
            ['acl' => 'private'],
            ['bucket' => $this->bucket],
            ['starts-with', '$key', $user . '/'],
            ["content-length-range", 10240, 10485760],
        ];


        $postObject = new PostObjectV4(
            $this->S3Client,
            $this->bucket,
            $formInputs,
            $options,
            '+5 minutes'
        );

 
        return response()->json([
            'attributes' => $postObject->getFormAttributes(),
            'additionalData' => $postObject->getFormInputs()
        ]);
    }
```

### SDK version used

^3.302.0

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.1

**Comment by yenfryherrerafeliz** [comment]
Hi @CatoriClothing, sorry to hear about your issues. I am not sure why you are seeing this behavior but, I just did a quick test, and I was able to get the desired bucket as the action. Please see below:
Code snippet:
```php
$s3Bucket = 'mybucket.test.com';
$user = 'TestUser';
$formInputs = ['key' => $user . '/${filename}'];
$options = [
    ['acl' => 'private'],
    ['bucket' => $s3Bucket],
    ['starts-with', '$key', $user . '/'],
    ["content-length-range", 10240, 10485760],
];
$s3Client = new S3Client([
    'endpoint' => $s3Bucket,
    'region' => 'us-east-1',
    'use_path_style_endpoint' => true
]);
$postObject = new PostObjectV4(
    $s3Client,
    $s3Bucket,
    $formInputs,
    $options,
    '+5 minutes'
);


print_r([
    'attributes' => $postObject->getFormAttributes(),
    'additionalData' => $postObject->getFormInputs()
]);
```
Output:
```console
Array
(
    [attributes] => Array
        (
            [action] => /mybucket.test.com
            [method] => POST
            [enctype] => multipart/form-data
        )

    [additionalData] => Array
        (
            [key] => TestUser/${filename}
            [X-Amz-Security-Token] => REDACTED
            [X-Amz-Credential] => REDACTED
            [X-Amz-Algorithm] => AWS4-HMAC-SHA256
            [X-Amz-Date] => 20240402T053007Z
            [Policy] => REDACTED
            [X-Amz-Signature] => REDACTED
        )

)
```

This may have been an issue in the past, therefore, would you be able to either:
- Create a new test project from scratch and test?
- Make sure the AWS SDK for PHP dependency is fully updated?.
    - You could delete composer.lock and then run ```composer update ```
    
I look forward to your response.

Thanks!

**Comment by CatoriClothing** [comment]
Hey @yenfryherrerafeliz !

Thanks for your help thus far. It seems the issue is within how the endpoint gets parsed either with the https:// prefix or without. PostObjectv4 seems to return the correct value with no https:// prefix on the endpoint when using a custom domain but then GetObject throws this error due to the lack of https:// "Custom endpoint `bucket.x.com` was not a valid URI". 

The GetObject is resolved when appending https:// back to the endpoint but then PostObjectv4 has the same issue. 

More testing needed on our end to confirm this but I suspect this is where the problem lies with us being able to only get either PostObject or GetObject to work correctly.

**Comment by stobrien89** [comment]
Hi @CatoriClothing,

It sounds like you don't need a path style (where the bucket is targeted in the request path), so I definitely wouldn't recommend setting `use_path_style_endpoint` to `true`.

Are you expecting the resulting URI to be a host without a scheme?  The SDK will default to `https` if one isn't provided in either the endpoint or explicitly in the client constructor.  If you want to use `http`, you can prepend that to your endpoint or provide it in the client config as `'scheme' => 'http'`.

**Comment by stobrien89** [comment]
Hi @CatoriClothing,

Apologies for the delay.  I think what's happening here is some conflicting behavior between `PostObjectV4` and our newer rules-based endpoint provider.  Could you set `'endpoint_provider'` to `\Aws\Endpoint\PartitionEndpointProvider::defaultProvider()` (our legacy endpoint provider) and let me know if that resolves this?
