### ISSUE TITLE
fopen() throws Error executing "GetObject"

### ISSUE THREAD

**Issue by RafficMohammed** [aws/aws-sdk-php#2909]
### Describe the bug

In StreamWrapper.php

![Screenshot from 2024-04-17 14-27-31](https://github.com/aws/aws-sdk-php/assets/88606418/ea18cd63-e96f-4fdc-985a-8c2f550cf2d1)

Because of this line =>  $command['@http']['stream'] = true;
I'm getting bellow error

![Screenshot from 2024-04-17 14-28-02](https://github.com/aws/aws-sdk-php/assets/88606418/c6a95a73-0902-4fad-abe1-42d4e529dff3)

If I set stream as true or remove the line, it's working as expected.

### Expected Behavior

I need @http.stream to be true. Because our file can have large data.

### Current Behavior

@http.stream  => true is not working

### Reproduction Steps

Create S3 Private Bucket and try this operation

### SDK version used

3.29

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

Ubuntu 22

**Comment by stobrien89** [comment]
hi @RafficMohammed,

Assuming you resolved this, but let us know if you have any additional questions.
