### ISSUE TITLE
Class 'XMLWriter' not found

### ISSUE THREAD

**Issue by dv1r** [aws/aws-sdk-php#291]
I am getting this error when trying to upload to S3 using multi-part upload:

`PHP Fatal error:  Class 'XMLWriter' not found in aws/Guzzle/Service/Command/LocationVisitor/Request/XmlVisitor.php on line 198`

I am using SDK version 2.6.3

**Comment by abovemarket** [comment]
Followed by an `apachectl restart`. Thank you for posting the fix!
