### ISSUE TITLE
GetObject() command @http stream issue

### ISSUE THREAD

**Issue by RafficMohammed** [aws/aws-sdk-php#2910]
### Describe the bug

In StreamWrapper.php

![Screenshot from 2024-04-17 14-27-31](https://github.com/aws/aws-sdk-php/assets/88606418/ea18cd63-e96f-4fdc-985a-8c2f550cf2d1)

Because of this line =>  $command['@http']['stream'] = true;
I'm getting bellow error

![Screenshot from 2024-04-17 14-28-02](https://github.com/aws/aws-sdk-php/assets/88606418/c6a95a73-0902-4fad-abe1-42d4e529dff3)

If I set stream as true or remove the line, it's working as expected.

### Expected Behavior

I need @http.stream to be true. Because our file can have large data.

### Current Behavior

@http.stream  => true is not working

### Reproduction Steps

Create S3 Private Bucket and try this operation

### SDK version used

3.29

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

Ubuntu 22, Php => 8.1

**Comment by yenfryherrerafeliz** [comment]
Hi @RafficMohammed, sorry to hear about your issue. The only issue I can I see here is that you are using an old version of the SDK. Would you be able to update to a most recent version?, and then see if the issue persists there?. If after updating the issue persists then, could you please try with my code example below, and provide the results here?.

By running the code below and using the latest version I had not issues:
```php
<?php
require '../vendor/autoload.php';

use Aws\S3\S3Client;


$s3Client = new S3Client([
    'region' => 'us-east-2',
    'debug' => true
]);
$result = $s3Client->getObject([
    'Bucket' => getenv('TEST_BUCKET'),
    'Key' => getenv('TEST_KEY'),
    '@http' => [
        'stream' => true
    ]
]);
```
Result:
```console
Array
(
    [statusCode] => 200
    [effectiveUri] => https://herrergy-sample-bucket.s3.us-east-2.amazonaws.com/herrergy-sample-key.txt
    [headers] => Array
        (
            redacted
        )
)
This is a test file for getObject!
```

_Note:_ In the scenario that the issue persists after updating to a most recent version of the SDK, please make sure you redact any sensitive information in any new information provided and please make sure you replace the values given to Bucket and Key in my code with your own bucket and key values.

I hope this helps!

Thanks!

**Comment by RafficMohammed** [comment]
@yenfryherrerafeliz I will try and get back to you soon
