### ISSUE TITLE
Elastic transcoder service

### ISSUE THREAD

**Issue by hlherrera** [aws/aws-sdk-php#296]
Im trying to consume elastic transcoder service to createjob in pipeline, But im have an error in curl connection. Curl failed. Error code: 6 Message: Could not resolve host.
Do you provide me an example for creating transcoding job, I need to convert a video recently uploaded to S3.

**Comment by sobytes** [comment]
Hi i am also getting this issue.

~~~
{"error":true,"message":"[curl] 6: Could not resolve host: elastictranscoder.sa-east-1.amazonaws.com [url] https:\/\/elastictranscoder.sa-east-1.amazonaws.com\/2012-09-25\/pipelines"}
~~~

**Comment by cjyclaire** [comment]
@sobytes, It looks like this issue is more about your host. So, could you provide more information for troubleshooting? e.g. How often does this occurs? Is there any other host that could be connect without issue? Is your DNS working correctly?

**Comment by sobytes** [comment]
Sorry please close this I should have got back aws elastic transcoder doesn't support that region yet.
