### ISSUE TITLE
'ACL' statement on default in ObjectUploader, not supported anymore by AWS S3.

### ISSUE THREAD

**Issue by JortJacobs** [aws/aws-sdk-php#3008]
### Describe the bug

Creating a folder via OctoberCMS results in ACL complaints since it is not being supported anymore.
This is related to the following file + line-item, containing 'ACL' statements: https://github.com/aws/aws-sdk-php/blob/058611bd22a81c873b1399892672861848e1d466/src/S3/ObjectUploader.php#L89.

Please remove that.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

ObjectUploader to work.

### Current Behavior

It does not work.

### Reproduction Steps

Call the function.

### SDK version used

Latest.

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

8.3.6

**Comment by RanVaknin** [comment]
Hi @JortJacobs ,

ACLs being disabled by default is the expected and documented behavior and is controlled via the S3 service, not the SDK.

Please refer to:
[Blogpost ](https://aws.amazon.com/jp/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/)
[S3 Notice](https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/)
[S3 docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/acls.html)

Thanks,
Ran~

**Comment by stobrien89** [comment]
Just wanted to chime in: the SDK still sets a default ACL of `private` in the `ObjectUploader` class, which is legacy behavior that still works. S3 still allows `private` ACLs.  We left this in place for backward compatibility reasons.  

It sounds like OctoberCMS has a high-level filesystem abstraction over the SDK/S3 that relies on ACLs.  If they are defaulting to anything other than `private`, they'll need to change that.
