### ISSUE TITLE
Unexpected T_CONST

### ISSUE THREAD

**Issue by ryandavern** [aws/aws-sdk-php#3023]
### Describe the bug

<br />
<b>Parse error</b>:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in <b>/var/www/rhythmUtils/RhythmWebApp/frontend/api/profile/aws/Aws/S3/S3Client.php</b> on line <b>237</b><br />

This issue arises when I go to upload an image via the SDK.

Heres my code:
require 'aws/aws-autoloader.php';

    use Aws\S3\S3Client;
    use Aws\S3\Exception\S3Exception;

    // Replace these variables with your own details
    $spaceName = '';
    $region = '';
    $accessKey = '';
    $secretKey = '';
    $endpoint = '';

    if ($_SERVER['REQUEST_METHOD'] == 'POST') {
        if (isset($_FILES['file']) && $_FILES['file']['error'] == UPLOAD_ERR_OK) {
            $uploadDir = 'uploads/';  // Make sure this directory exists and is writable

            // Get the file extension
            $fileExtension = pathinfo($_FILES['file']['name'], PATHINFO_EXTENSION);

            // Generate a unique random file name
            $newFileName = uniqid('file_', true) . '.' . $fileExtension;

            // Set the full path for the uploaded file
            $uploadFile = $uploadDir . $newFileName;

            if (move_uploaded_file($_FILES['file']['tmp_name'], $uploadFile)) {
                try {
                    // Initialize the S3 client with your credentials
                    $s3 = new S3Client([
                        'version' => 'latest',
                        'region'  => $region,
                        'endpoint' => $endpoint,
                        'credentials' => [
                            'key'    => $accessKey,
                            'secret' => $secretKey,
                        ],
                    ]);

                    // Path to the file you want to upload
                    $filePath = $uploadFile;
                    // Name of the file in the space
                    $keyName = 'image/a/' . basename($filePath);

                    // Upload the file to the space
                    $result = $s3->putObject([
                        'Bucket' => $spaceName,
                        'Key'    => $keyName,
                        'SourceFile' => $filePath,  // Local path on the server
                        'ACL'    => 'public-read', // Optional: Make the file publicly accessible
                    ]);

                    echo json_encode(basename($filePath));

                } catch (S3Exception $e) {
                    echo "There was an error uploading the file.\n";
                    echo $e->getMessage() . "\n";
                }

            } else {
                echo 'Error: Unable to move the uploaded file.';
            }
        } else {
            echo 'Error: No file uploaded or there was an upload error.';
        }
    } else {
        echo 'Error: Invalid request method.';
    }

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Image should have uploaded correctly, however, that error is produced when i go to upload. I have attached a copy of the code i used to recreate this issue

### Current Behavior

<br />
<b>Parse error</b>:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in <b>/var/www/rhythmUtils/RhythmWebApp/frontend/api/profile/aws/Aws/S3/S3Client.php</b> on line <b>237</b><br />

### Reproduction Steps

I attached the code I used to upload the image

### SDK version used

3.325.4

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 7.0.33-0ubuntu0.16.04.16 (cli) ( NTS ) Copyright (c) 1997-2017 The PHP Group Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies     with Zend OPcache v7.0.33-0ubuntu0.16.04.16, Copyright (c) 1999-2017, by Zend Technologies

**Comment by stobrien89** [comment]
Hi @ryandavern,

Sorry to hear about the issues.  This is happening because PHP 7.0 doesn't support visibility modifiers on class constants.  We deprecated PHP runtimes below 7.2.5 in August of last year; version [3.279.0](https://github.com/aws/aws-sdk-php/releases/tag/3.279.0) and below are fully compatible with PHP 7.0.
