### ISSUE TITLE
Invalid requestUri on GeoPlacesClient > getPlace

### ISSUE THREAD

**Issue by SiMoSiMo2** [aws/aws-sdk-php#3030]
### Describe the bug

I am trying to use `Amazon Location Service Places V2` but following the documentation (https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-geo-places-2020-11-19.html) I cannot get the `GetPlace` call to work.

I successfully instantiate the `GeoPlacesClient` client and then call `GetPlace` passing `Language` and `PlaceId` parameters (I also tried adding the `Key` parameter).

However, the call throws an `GeoPlacesException` exception:
```
AccessDeniedException (client): Unable to determine service/operation name to be authorized - {"Message":"Unable to determine service/operation name to be authorized"}
```

Parsing the requested URL it seems that `v2` is missing from the URI
client request: `https://places.geo.eu-central-1.amazonaws.com/place/AQAAADg...`
working request: `https://places.geo.eu-central-1.amazonaws.com/v2/place/AQAAADg...`

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

I expect to get `Result` object.

### Current Behavior

I have this exception:

AccessDeniedException (client): Unable to determine service/operation name to be authorized - {"Message":"Unable to determine service/operation name to be authorized"}

### Reproduction Steps

Instantiate the client (https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.GeoPlaces.GeoPlacesClient.html):
```
$client = new GeoPlacesClient([
    'credentials' => $credentials,
    'region'      => $region,
    'version'     => 'latest',
]);
```

call the method (https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-geo-places-2020-11-19.html#getplace):
```
$result = $awsClient->getPlace([
    'PlaceId'  => $placeId,
    'Key'      => $key,
]);
```

### Additional Information/Context

I've tried to add `v2` to the `requestUri` inside `vendor/aws/aws-sdk-php/src/data/geo-places/2020-11-19/api-2.json.php` and I've got the expected response

### SDK version used

3.328.0

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.3.6

**Comment by yenfryherrerafeliz** [comment]
Hey @SiMoSiMo2, sorry to hear about your issues. We are currently working on a fix for this. In the meantime, would you please use the following workaround:

```php
$client = new GeoPlacesClient([
    'region' => 'us-east-2',
]);
$client->getHandlerList()->appendBuild(
    \Aws\Middleware::mapRequest(function (RequestInterface $request) {
        $uri = $request->getUri();
        $uri = $uri->withPath(
            '/v2' . $uri->getPath()
        );

        return $request->withUri($uri);
    })
);
... ANY REQUEST with the client created previously
```

I know you mentioned you were able to get it working by editing the model file `geo-places/2020-11-19/api-2.json.php` but it will get overriding anytime you update your SDK dependency.

Please let me know if that helps!

Thanks!

**Comment by SiMoSiMo2** [comment]
Hi @yenfryherrerafeliz thanks for your workaround. It works!

**Comment by stobrien89** [comment]
Hi @SiMoSiMo2,

Thanks for your patience.  This should be fixed as of today's release.  Could you let us know if this is resolved after upgrading? Thanks!

**Comment by SiMoSiMo2** [comment]
Hi @stobrien89 it seems that everything works fine.
Thank you so much for the support
