### ISSUE TITLE
Add support for psr/cache:^3.0

### ISSUE THREAD

**Issue by issakujitsuk** [aws/aws-sdk-php#3036]
### Describe the feature

Currently, `aws-sdk-php` specifies `psr/cache:^1.0` in the composer.json. Please add support for `psr/cache:^3.0`.

### Use Case

I want to update `web-token/jwt-library` from version 3.3.x to 3.4.x, but I'm unable to do so because `aws/aws-sdk-php` locks `psr/cache` to version 1.0.

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

3.324.13

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.2.8, Amazon Linux 2

**Comment by yenfryherrerafeliz** [comment]
Hi @issakujitsuk, thanks for this feature request. We will be open to accept a PR contribution for this, if you are willing to provide one?
It will be something like:
```json
"psr/cache": "^1.0 || ^2.0 || ^3.0",
```
Thanks!

**Comment by issakujitsuk** [comment]
Thank you for merging as well, @stobrien89 😄
