### ISSUE TITLE
[S3] Invalid path in request when endpoint has subpath

### ISSUE THREAD

**Issue by Rezrazi** [aws/aws-sdk-php#3037]
### Describe the bug

I'm trying to use an S3-compatible service (Supabase) with the S3 client using Laravel.

Supabase provides endpoints that look like this `https://xxxxx.supabase.com/storage/v1/s3`
When using a configuration that looks like this

```php
        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'endpoint' => env('AWS_ENDPOINT'),
            'root' => null,
            'use_path_style_endpoint' => true,
            'throw' => true,
            'endpoint_provider' => \Aws\Endpoint\PartitionEndpointProvider::defaultProvider(),
        ],
```

```
Unable to write file at location: file.txt. Error executing "PutObject" on "https://xxxxxx.supabase.co/storage/v1/s3/storage/v1/s3/my-bucket/file.txt"; AWS HTTP error: Client error: `PUT https://xxxxxx.supabase.co/storage/v1/s3/storage/v1/s3/my-bucket/file.txt` resulted in a `404 Not Found`
```

As you can see the path is invalid here  
`storage/v1/s3/storage/v1/s3/my-bucket/file.txt`

Related to https://github.com/aws/aws-sdk-php/issues/2785 

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

I'm expecting the S3 client to work seamlessly with any provider as long as it is S3-compliant. 

### Current Behavior

```
->Entering step build, name 'builder' -------------------------------------- request.instance was set to 0000000000000f170000000000000000 request.method was set to GET request.headers was set to array(2) { ["X-Amz-Security-Token"]=> string(7) "[TOKEN]" ["Host"]=> array(1) { [0]=> string(32) "xxxxx.supabase.co" } } request.scheme was set to https request.path was set to /storage/v1/s3/storage/v1/s3/my-bucket/dauphine.jpg 
```

### Reproduction Steps

Can be reproduced in this sandbox https://phpsandbox.io/e/x/bzdwa?layout=EditorPreview&defaultPath=%2F&theme=dark&showExplorer=no&openedFiles=#routes/web.php

Just needs `config/filesystems.php` credentials to be set.

### Possible Solution

Avoid duplicating the path in the request path builder

### SDK version used

3.330.0

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

PHP 8.3.13 (cli) (built: Oct 22 2024 18:39:14) (NTS)

**Comment by Rezrazi** [comment]
This is perhaps a regression
I just downgraded randomly to 3.318.0 and it is working with `endpoint_provider`

**Comment by stobrien89** [comment]
Hi @Rezrazi,

This should be resolved in today's release.  We made a change to path handling that shouldn't have touched S3, but that has now been corrected.

**Comment by cirolosapio** [comment]
i'm facing again the same issue
the latest version that seems to work is 3.318
