### ISSUE TITLE
ApiGatewayManagementApiClient endpoint issue

### ISSUE THREAD

**Issue by matteo-guardini** [aws/aws-sdk-php#3040]
### Describe the bug

Since version 3.329.0 we have an error in writing messages to the web socket. This is the error:

```
Error executing "PostToConnection" on
"https://XXX.execute-api.eu-west-1.amazonaws.com/production/production/@connections/CN5VTdWEDoECImg%3D"; AWS HTTP
error: Client error: `POST
https://XXX.execute-api.eu-west-1.amazonaws.com/production/production/@connections/CN5VTdWEDoECImg%3D` resulted
in a `404 Not Found` response:
{"message":"No method found matching route production/@connections/CN5VTdWEDoECImg= for http method POST."}
NotFoundException (client): No method found matching route production/@connections/CN5VTdWEDoECImg= for http method
POST. - {"message":"No method found matching route production/@connections/CN5VTdWEDoECImg= for http method POST."}

```
This is the function:

```
			$config = [
				'endpoint' => 'https://XXX.execute-api.eu-west-1.amazonaws.com/production/',
				'version' => 'latest'
			];
			$credentials = new Aws\Credentials\Credentials("aaa", "bbb");
			$config["credentials"] = $credentials;
			$apiGatewayClient = new Aws\ApiGatewayManagementApi\ApiGatewayManagementApiClient($config);
			$websocketPayload = '{
				"action": "' . $action . '",
				"payload": ' . $payload . '
			}';
			try {
				$result = $apiGatewayClient->postToConnection([
					'ConnectionId' => "xxx",
					'Data' => "yyy",
				]);
				$result = $result->get("@metadata")["statusCode"];
			} catch (\Exception $e) {
				$result = $e->getMessage();
			}
```

From the exception it seems that the word "production" in the endpoint is replaced with "production/production"
We detect the issue only in Fargate tasks and not local ones.
The docker image used is webdevops/php-apache:8.3 both locally and in production (Fargate).
With sdk versions<= 3.328.0 the problem does not exist

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

That the endpoint set in 

```
new Aws\ApiGatewayManagementApi\ApiGatewayManagementApiClient([
    'endpoint' => 'https://xxx.execute-api.eu-west-1.amazonaws.com/production/',
    'credentials' => $credentials,
    'version' => 'latest'
]);
```
 is not changed

### Current Behavior

Error executing "PostToConnection" on
"https://XXX.execute-api.eu-west-1.amazonaws.com/production/production/@connections/CN5VTdWEDoECImg%3D"; AWS HTTP
error: Client error: `POST
https://XXX.execute-api.eu-west-1.amazonaws.com/production/production/@connections/CN5VTdWEDoECImg%3D` resulted
in a `404 Not Found` response:
{"message":"No method found matching route production/@connections/CN5VTdWEDoECImg= for http method POST."}
NotFoundException (client): No method found matching route production/@connections/CN5VTdWEDoECImg= for http method
POST. - {"message":"No method found matching route production/@connections/CN5VTdWEDoECImg= for http method POST."}

### Reproduction Steps

FROM webdevops/php-apache:8.3
in fargate task

### SDK version used

3.332.2

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

php 8.3, ENV environment='production'

**Comment by matteo-guardini** [comment]
errata corrige: the problem is also present locally in the docker container

**Comment by yenfryherrerafeliz** [comment]
Hi @matteo-guardini, thanks for reaching out. I am currently investigating this and will reach out back soon.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Hey @matteo-guardini, while we investigate this deeper, please remove the last slash at the end of the endpoint. 
Instead of:
```
https://XXX.execute-api.eu-west-1.amazonaws.com/production/
```
Please use:
```
https://XXX.execute-api.eu-west-1.amazonaws.com/production
```

And that should workaround this issue for you. I will investigate to see if that behavior is expected or if we need to fix it. I will get back to you soon.

Thank you!

**Comment by matteo-guardini** [comment]
> Hey @matteo-guardini, while we investigate this deeper, please remove the last slash at the end of the endpoint. Instead of:
> 
> ```
> https://XXX.execute-api.eu-west-1.amazonaws.com/production/
> ```
> 
> Please use:
> 
> ```
> https://XXX.execute-api.eu-west-1.amazonaws.com/production
> ```
> 
> And that should workaround this issue for you. I will investigate to see if that behavior is expected or if we need to fix it. I will get back to you soon.
> 
> Thank you!

Yes, I tried it a little while ago and it works

**Comment by stobrien89** [comment]
Hi @matteo-guardini,

Apologies for the issues.  This should be fixed as of today's release.  Closing for now, but please let us know if anything else comes up.
