### ISSUE TITLE
curl_multi_add_handle(): Argument #2 ($handle) must be of type CurlHandle, Swoole\Curl\Handler given

### ISSUE THREAD

**Issue by arvinyan86** [aws/aws-sdk-php#3044]
### Describe the bug

When I integrated AWS SDK using Hyperf framework (swoole 5.0) and used DynamoDB for data querying, the result returned an error.
curl_multi_add_handle(): Argument #2 ($handle) must be of type CurlHandle, Swoole\Curl\Handler given . . . 
so，how to fix it

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

fix it

### Current Behavior

curl error

### Reproduction Steps

Execute the following code

### Additional Information/Context

$client = self::getClient();

        $marshaler = new Marshaler();
        $items = [];
        try {
            $params = [
                'TableName' => $tableName, // 替换为你的 DynamoDB 表名
                'KeyConditionExpression' => 'uid = :partition_value', // AND create_time BETWEEN :start_sort_value AND :end_sort_value
                'ExpressionAttributeValues' => [
                    ':partition_value' => ['N'=>'20549'], // 替换为你的分区键值，注意类型要与 DynamoDB 中的一致
                    //':start_sort_value'=>['N'=>'1733133075'],
                    //':end_sort_value'   => ['N'=>'1792541253']
                ]
                // 如果你的表有排序键，并且你想基于排序键进行范围查询，可以添加 SortKeyConditionExpression 和相应的 ExpressionAttributeValues
            ];

            // 执行查询
            $result = $client->query($params);
            // 处理查询结果
            foreach ($result['Items'] as $k=>$item) {
                $items[$k] = $marshaler->unmarshalItem($item);
            }

        } catch (DynamoDbException $e) {
            PublicHelper::catchExceptionInfo($e,'AwsDynamoDb:拉取数据失败1');
        } catch (\Throwable $exception){
            PublicHelper::catchExceptionInfo($exception,'AwsDynamoDb:拉取数据失败2');
        }

### SDK version used

3.333

### Environment details (Version of PHP (`php -v`)? OS name and version, etc.)

centos, php8.0

**Comment by yenfryherrerafeliz** [comment]
Hi @arvinyan86, sorry to hear about your issues. Unfortunately this seems to be a third party problem. I did not see how you instanced your client, however, It looks like you are having some dependencies conflicts. This error is not coming directly from the SDK, but instead from guzzle which is a library we use for HTTP operations. I recommend you to make sure the dependencies you are using are the ones required by the SDK [here](https://github.com/aws/aws-sdk-php/blob/master/composer.json).

Thanks!
