### ISSUE TITLE
How to set S3 vhost?

### ISSUE THREAD

**Issue by dmyers** [aws/aws-sdk-php#347]
In a previous PHP SDK for S3 there was a way to [set the virtual host](http://docs.aws.amazon.com/AWSSDKforPHP/latest/index.html#m=AmazonS3/set_vhost) so if you had a CNAME of `s3.yourdomain.com` and it was pointed to `s3.amazonaws.com.` you could set the vhost option and it `getObjectUrl` calls would use the correct URL.

It appears to have worked by setting region to null and setting the base_url to say `http://s3.yourdomain.com`, but I'm having trouble getting that to work either.

http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html

Do you know how to set this in the current SDK?

**Comment by yellow1912** [comment]
This workaround does allow me to use getObjectUrl correctly, but the upload feature won't work till I applies another trick posted also by @jeremeamia 
https://gist.github.com/leftnode/e3107493f078516555f3

Hopefully this will help someone saves hours of fiddling with the code.

**Comment by yellow1912** [comment]
Unfortunately I celebrated too early. It seems like by setting host I generate another error:

"The request signature we calculated does not match the signature you provided. Check your key and signing method."
