### ISSUE TITLE
version 3.0 and custom endpoint for S3

### ISSUE THREAD

**Issue by krzaczek** [aws/aws-sdk-php#366]
Hi,

Version 2 of sdk allowed to set a custom endpoint and use the sdk with s3 comatibnile services like LeoFS (http://docs.aws.amazon.com/aws-sdk-php/guide/latest/configuration.html#setting-a-custom-endpoint).

Version 3 implements something like S3UriParser that checks the url against 

``` php
 private $pattern = '/^(.+\\.)?s3[.-]([a-z0-9-]+)\\./';
```

which results in an error

``` php
500 Error executing Aws\S3\S3Client::headObject() on "https://leofs.localhost/avatars/22/0/9/5196265.jpg"; Not a valid S3 endpoint: https://leofs.localhost/avatars/22/0/9/5196265.jpg
```

Does this mean it cannot be used with other compatibile services. It would be great if we could override the default signature object ... by calling $s3->setSignature(new Object) so I could rewrite the S3UriParser to allow other url's.

Best regards,
Pawel

**Comment by netroby** [comment]
Add use_path_style_endpoint => true may help
