### ISSUE TITLE
 Error completing request - (Guzzle\Http\Exception\RequestException)

### ISSUE THREAD

**Issue by atlok** [aws/aws-sdk-php#394]
I try upload multiple images on cloud, in process uploading i have next message error.
Guzzle\Http\Exception\RequestException
Error completing request

it's mine example
public function parseArticleData($url, $xpathQuery)
    {
        $dir = Yii::getAlias('@frontend/web/funny_images/');

```
    $content = '';
    $nodes = $this->createDomXPath($url)->query($xpathQuery);
    if ($nodes->length === 0) {
        return $this;
    }
    for($i = 0; $i < $nodes->length; $i++){
        $fileExtansion = Yii::$app->yadisk->getImageType($nodes->item($i)->nodeValue); 
        $fileContent = file_get_contents($this->checkDomain($url, $nodes->item($i)->nodeValue)); 
        $fileName = md5(time() . $nodes->item($i)->nodeValue) . "." . $fileExtansion; 
        file_put_contents($dir . $fileName, $fileContent, LOCK_EX); 

            Yii::$app->yadisk->disk->uploadFile(
                '/funny_images/',
                array(
                    'path' => $dir . $fileName,
                    //'size' => filesize($fileName),
                    'name' => $fileName
                )
            );
                //Yii::$app->yadisk->disk->showImage();
                $content .= BaseUrl::toRoute(['cloud/images', 'path' => '/funny_images/'. $fileName]);
    }
    return $content;
}
```

it's stack trace
 in D:\Programs\OpenServerMini\OpenServer\domains\funsite-lc.ru\vendor\guzzle\http\Guzzle\Http\Message\Request.php at line 569
560561562563564565566567568569570571572573574575576577578     \* Process a received response
     *
     \* @param array $context Contextual information
     \* @throws RequestException|BadResponseException on unsuccessful responses
     */
    protected function processResponse(array $context = array())
    {
        if (!$this->response) {
            // If no response, then processResponse shouldn't have been called
            $e = new RequestException('Error completing request');
            $e->setRequest($this);
            throw $e;
        }

```
    $this->state = self::STATE_COMPLETE;

    // A request was sent, but we don't know if we'll send more or if the final response will be successful
    $this->dispatch('request.sent', $this->getEventArray() + $context);
```

**Comment by ducnguyenhuy** [comment]
Hi,

I'd like to open this issue again because I got the same issue on SDK version 2.7.24.
Please take a look at screenshot below and let me know your thoughts.
![guzzle-http-exception-requestexception](https://cloud.githubusercontent.com/assets/3691894/6861508/b3edafe4-d469-11e4-926a-083defcb16db.png)

Thanks.
