### ISSUE TITLE
[S3] 404 on headObject request

### ISSUE THREAD

**Issue by frankdejonge** [aws/aws-sdk-php#396]
I'm getting an unexpected error from an HeadObject request.

``` php
$client = S3Client::factory([
    'key'    => 'my-key',
    'secret' => 'my-secret',
    'region' => 'eu-west-1',
    'version' => 'latest',
    // 'debug' => true,
]);

var_dump($client->headObject([
    'Bucket' => 'my-bucket',
    'Key' => 'my-key',
]));
```

Results in the following exception being thrown

```
Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message
'Client error response
[url] https://s3-eu-west-1.amazonaws.com/%7BBucket%7D/%7BKey%2B%7D
[status code] 404
[reason phrase] Not Found'
in ./vendor/aws/aws-sdk-php/src/Common/AwsClient.php on line 272
```

The part that confuses me is that the URL doesn't seem to be formatted correctly, the placeholders don't seem to be properly replaced.

**Comment by NobleUplift** [comment]
I kept getting a variation of `Guzzle\\Common\\Exception\\InvalidArgumentException 0 Unable to open phar://./aws.phar/Aws/S3/Resources/s3-latest.php for reading in phar://./aws.phar/Guzzle/Service/AbstractConfigLoader.php on line 120` while trying to debug an old branch of code, and then discovered that `'version' => 'latest'` had made its way into my test environment. Thank you very much @benmadin for helping me find the solution!
