### ISSUE TITLE
v3: Call to undefined method Command::search() from AwsClient::getIterator()

### ISSUE THREAD

**Issue by radford** [aws/aws-sdk-php#419]
when calling:
```php
     $ec2client->getIterator('DescribeInstances');
```

I notice that this failing code is only reached because ```DescribeInstances``` does not have ```input_token```  and ```output_token``` defined in the ec2 paginators, though it looks like it could.

**Comment by mtdowling** [comment]
Closed by https://github.com/aws/aws-sdk-php/commit/fbaa02d06ccea42fc177df5bda9e2ee27f321240
