### ISSUE TITLE
Error executing Aws\S3\S3Client::putObject()

### ISSUE THREAD

**Issue by ChrisTerBeke** [aws/aws-sdk-php#427]
I get this error when using the s3 client streaming wrapper on Google App Engine:

`Error executing Aws\S3\S3Client::putObject(); No system CA bundle could be found in any of the the common system locations`

I think has to do with php not able to find the cacert.pem file on Google's servers? Any idea how to fix this?

**Comment by samuelhenshaw2020** [comment]
i have tried uploading an image to s3 server  but not working. telling me putObject denial and ssl issue

**Comment by diehlaws** [comment]
Hi @samuelhenshaw2020, can you please open a new issue with the information requested in the [Questions / Help](https://github.com/aws/aws-sdk-php/issues/new?assignees=&labels=needs-triage%2C+guidance&template=questions-help.md&title=) template along with the exact error you're receiving so we can better assist you with the behavior you're experiencing? Including a code snippet showing how you're attempting to upload your image to S3 would help us better troubleshoot this behavior.
