### ISSUE TITLE
 Fatal error: Uncaught exception 'Guzzle\Http\Exception\CurlException' with message ' in vendor\guzzle\guzzle\src\Guzzle\Http\Curl\CurlMulti.php on line 561

### ISSUE THREAD

**Issue by anextro** [aws/aws-sdk-php#433]
I have been trying to do multiple uploads from my local machine to my s3 bucket  but always get this error message.

**Comment by mtdowling** [comment]
I'll go ahead and close this for now. Feel free to reopen with a network capture if necessary. Thanks!

**Comment by mizuluffyhwang** [comment]
Have the same problem when increase the number of jobs. I'm using eBay API, think it may related to time out issue
