### ISSUE TITLE
DynamoDB unmarshaller does not unbase64 binary types

### ISSUE THREAD

**Issue by Sazpaimon** [aws/aws-sdk-php#436]
I don't know if this is an intentional thing because the marshaller explicitly does not support the binary type, or just an oversight, but the unmarshaller doesn't unbase64 binary types. This should be a pretty trivial thing to fix, though (I can make a PR if need be).

**Comment by jeremeamia** [comment]
Your thoughts @Sazpaimon?

**Comment by Sazpaimon** [comment]
I'm not a fan of having to make it a configurable setting, instead of having a way for it to automagically just work. Maybe if the class required the client to be passed in instead, and have the marshaller figure it out from there, but that's only marginally better. Since V3 is just beyond the horizon, I can also accept this as just a quirk of the marshaller wait for V3 for it to be fixed.

**Comment by jeremeamia** [comment]
I hear ya, and I know it's not ideal at the moment. I'll go ahead and close this issue then, since it will be fixed in V3.
