### ISSUE TITLE
s3->putBucketAcl() => This request does not support content

### ISSUE THREAD

**Issue by DrySs** [aws/aws-sdk-php#441]
Hi there,

I'm trying for HOURS to make **s3->putBucketAcl()** works, without any success.

I'm having various exception errors, and I'm currently stuck on this one:

**400 - Bad Request - This request does not support content**

Here are params I'm using:

![aws](https://cloud.githubusercontent.com/assets/230791/5570039/2f21326e-8f7b-11e4-9556-a1e21d066633.png)

By the way, what is the difference between 'ACL' => 'string' asked and grantees permissions?
What I want is just to update my buckect ACLs (add new ACL access).

**Comment by DrySs** [comment]
Hey jeremeamia,

And thanks for your reply.

But if I remove param 'ACL' and I only use 'Grants' and 'Owner' (like in screenshot I provide in my first post), then I get the following error:

The XML you provided was not well-formed or did not validate against our published schema

Is there any way in PHP SDK to get the XML sent to Amazon, this way I'll be able to understand where the XML is not well-formed?

Thanks for your help

**Comment by jeremeamia** [comment]
> Is there any way in PHP SDK to get the XML sent to Amazon, this way I'll be able to understand where the XML is not well-formed?

Definitely! You can [attach a wire logger](http://docs.aws.amazon.com/aws-sdk-php/guide/latest/faq.html#how-can-i-see-what-data-is-sent-over-the-wire) to see the raw request and response. Doing that will definitely help us debug.

**Comment by DrySs** [comment]
Hmm trying to use LogPlugin, but not sure this is the best way to understand why AWS reply a bad request, because I cannot get XML details :

# Request: PUT /?acl HTTP/1.1
Host: kaemo.s3.eu-central-1.amazonaws.com
User-Agent: aws-sdk-php2/2.7.12 Guzzle/3.9.2 curl/7.30.0 PHP/5.5.9
Content-Type: application/xml
x-amz-content-sha256: cb6d4e0e5d5b0186531053b3b01aef3ff18762da6f414f04203a4ae6c55b4c0a
x-amz-date: 20150107T214224Z
Authorization: AWS4-HMAC-SHA256 Credential=[xxx]/20150107/eu-central-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=[xxx]
Content-Length: 416 4b8a4b559d9121e0254f5e39377633447b1b1d597eac28141c49c82dc133f204f6dbb96a891470d147d831fa34b8da79FULL_CONTROL

# Response: HTTP/1.1 400 Bad Request
x-amz-request-id: 74BAFDA99D6BA941
x-amz-id-2: K6D/8oQ891rGNcv1tu2m7BmN4dwARUatXj3VE1jTg72qd5WAkN2Y79sC4gBa+xOBYtlZxjiAdvM=
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Wed, 07 Jan 2015 21:42:24 GMT
Connection: close
Server: AmazonS3 MalformedACLErrorThe XML you provided was not well-formed or did not validate against our published schema74BAFDA99D6BA941K6D/8oQ891rGNcv1tu2m7BmN4dwARUatXj3VE1jTg72qd5WAkN2Y79sC4gBa+xOBYtlZxjiAdvM=

**Comment by mtdowling** [comment]
Can you show us the code you used to attach the logger? We need to see the XML body of the request in order to see why/if it was malformed.

**Comment by jeremeamia** [comment]
I just noticed that a potential problem could be that "Id" under "Owner" should be uppercase: "ID".

**Comment by jeremeamia** [comment]
I just wrote some test code to check my "Id" vs. "ID" theory, and I'm almost positive that is your problem. "ID" should be uppercase.

**Comment by DrySs** [comment]
@jeremeamia: WON-DER-FULL !!!
You're amazing, you found my bug :-)
Many many many thanks for your help.
