### ISSUE TITLE
Incompatible in PHP5.6

### ISSUE THREAD

**Issue by chiukit** [aws/aws-sdk-php#442]
When I upgraded the PHP version from 5.5 to 5.6, the PHP Notice happen:

PHP Notice:  Use of undefined constant CURLOPT_CLOSEPOLICY - assumed 'CURLOPT_CLOSEPOLICY' ....
lib/requestcore/requestcore.class.php on line 626

This constant has been removed in PHP5.6
http://php.net/manual/en/function.curl-setopt.php

Please update the SDK. Thank you so much!

**Comment by kit1989** [comment]
Thanks for your reply. I am using 2.7.11 which is not Version 1 of the SDK. BTW, I have fixed this issue by myself and just to report what happen after PHP upgraded.

**Comment by skyzyx** [comment]
The file `lib/requestcore/requestcore.class.php` only exists in v1.x.

**Comment by ratilalispl** [comment]
remove line curl_setopt($curl_handle, CURLOPT_CLOSEPOLICY, CURLCLOSEPOLICY_LEAST_RECENTLY_USED) from  file lib/requestcore/requestcore.class.php
