### ISSUE TITLE
[v3] Response simplification

### ISSUE THREAD

**Issue by skyzyx** [aws/aws-sdk-php#443]
According to “[Some API results have changed](https://github.com/aws/aws-sdk-php/blob/v3/UPGRADING.md#some-api-results-have-changed)”, you note that “The wrapping element in each operation is named after the name of the operation followed by the ‘Result’.”

I'm guessing that subtle differences in the internal models created a quirk in how the external models (used by the SDK) were generated. However, since (IIRC) all model responses (except for gets from S3) have a wrapper, couldn't the `$response` object be representative of that wrapping node?

For example:
```php
// More typing
$result['DescribeCacheClustersResult']['CacheClusters']

// Less typing; preferred
$result['CacheClusters']
```

Am I forgetting about cases where that built-in simplification might break the responses of another service?

**Comment by mtdowling** [comment]
Doh: the docs you referenced was actually an incorrect example (I'll update that today). The "result" wrapper shown in these incorrect docs is still removed (meaning "DescribeCacheClustersResult" is stripped from the result).

The wrapper that I meant to write about that is no longer removed is a different kind of wrapper. It's a wrapper that is a shape reference that has a "wrapper" value set to true. We previously would look at the shape reference of an output shape and see that if the reference contained a "wrapper" attribute then we would merge the referenced shape up one level. Here's an example from RDS's DescribeEngineDefaultParameters:

The operation has an output shape reference with a `wrapper` set to true (note that this is different than having a `resultWrapper`): https://github.com/aws/aws-sdk-php/blob/v3/src/Common/Resources/api/rds-2014-09-01.api.php#L1345. This output shape references the [DescribeEngineDefaultParametersResult](https://github.com/aws/aws-sdk-php/blob/v3/src/Common/Resources/api/rds-2014-09-01.api.php#L5967) shape. The DescribeEngineDefaultParametersResult shape is a structure that has a single key, EngineDefaults, in which the key value is a reference to a EngineDefaults shape. In v2, we got the value of "EngineDefaults" and merged it up to the root level of the result, while in v3 we are no longer doing this. This is to be consistent with the other SDKs and CLI, and to prevent any breaking changes if a service team ever adds a new shape to an output structure that has a `wrapper` attribute.

There are 3 services that utilize this attribute:

- elasticache
- rds
- redshift

**Comment by mtdowling** [comment]
Here's the updated upgrade guide with a complete list of affected operation results: https://github.com/aws/aws-sdk-php/commit/790bc4d06809df907de6008f99adb853d08dd912
