### ISSUE TITLE
Cannot use Route 53 changeResourceRecordSets

### ISSUE THREAD

**Issue by itecedor** [aws/aws-sdk-php#444]
I am trying to automate the addition of ALIAS records for certain subdomains for our app. I can instantiate the Route53 client and it responds to a getServerTime() request just fine. However any time I try to make changes using changeResourceRecordSets, it appears to go into an infinite loop as I get a memory error.

I've tried adjusting the array in various ways, including using the XML version of the payload (found here: http://docs.aws.amazon.com/Route53/latest/APIReference/API_ChangeResourceRecordSets_Requests.html#API_ChangeResourceRecordSets_RequestAliasSyntax) but have not gotten anywhere. I even tried using the change that is in the Route 53 Integration test BasicOperationsTest.php and THAT threw the memory error:

    Exception: Error 1: Allowed memory size of 134217728 bytes exhausted (tried to allocate 131334144 bytes) 

Can someone please confirm that the operation is still supported and that the format of the changeRequest array still conforms to the documentation? Documentation link: http://docs.aws.amazon.com/aws-sdk-php/latest/class-Aws.Route53.Route53Client.html#_changeResourceRecordSets

Thank you.

**Comment by mtdowling** [comment]
Yes it's still supported and the call in the integration test should not fail.

Can you ensure that garbage collection is enabled? If you increase the maximum allowed memory size, does the example operation complete? What's the amount of memory consumed by your process before invoking the operation?

**Comment by itecedor** [comment]
Yes gc is enabled. Memory used before the changeResourceRecordSets call is 2883584. Increasing the memory limit does seem to allow the request to complete... didn't occur to me to try that as this is the limit we have set on production! Will ask the sysadmin. Thank you, sorry for the stupid question.

**Comment by mtdowling** [comment]
Not a problem. Increasing the memory should work. Some of these responses can get rather large as they are kept in memory as both parsed and un-parsed data. This is something that is different in the WIP v3 SDK (we do not hang on to the HTTP response when you are provided with a result object).
