### ISSUE TITLE
NextToken ignored when using Simpledb select query in PHP 

### ISSUE THREAD

**Issue by otggroup** [aws/aws-sdk-php#445]
I have ran into an issue where the NextToken is ignored when issuing a select query against a SimpleDB domain.

First a little background:
AWS-SDK-PHP: Version 2.7.12 
PHP 5.5.11

Starting off I will issue a simple count query to obtain the total number of records in my case I have ~300 records stored in SimpleDB. I should have no problems obtaining a NextToken since this exceeds 100 and I am manually limiting the queries to 2 records.

 // my count query I will set this at 2 to ensure I receive a NextToken
> $countquery .= "select count(*) from mydomain WHERE City like 'Dallas%' LIMIT 2";
 // now I will execute this:
> $resultb = $client->select(array('SelectExpression' => $countquery));

#### At this point I do see the NextToken along with the count query results. So far so good!

//I will build two arrays one to hold the Query one to hold the NextToken
> $SelectExpression = array('SelectExpression' => "select * from mydomain WHERE City like 'Dallas%' LIMIT 2");
> $nexttoken = array('NextToken' => $resultb['NextToken']);

//Now I will execute the query. At this point my expectation is that I will receive records 3 and 4
> $result = $client->select($SelectExpression,$nexttoken);

The records received are exactly the same if I omit the $nexttoken. 

Reading over http://awsdocs.s3.amazonaws.com/SDB/latest/sdb-dg.pdf (page 84) indicates this should work but it doesn't. 

I have seen a number of resources showing how to perform this type of query in Java, C# and other languages. I am not sure why it is not working in PHP. Perhaps it is my code (I hope it is) if not then it could be a bug in the SDK.

**Comment by mtdowling** [comment]
Have you tried placing the "NextToken" parameter inside of the parameters of the call? The code you've provided looks incorrect because you are passing in two parameter arrays. Try something like this:

```php
$params = array('SelectExpression' => "select * from mydomain WHERE City like 'Dallas%' LIMIT 2");
$params['NextToken'] = $resultb['NextToken'];
$result = $client->select($params);
```

**Comment by otggroup** [comment]
Michael you are a genius!!!! that was my issue.  

The AWS PHP docs show the select query separated by a comma as if you had to pass the NextToken separately.
http://docs.aws.amazon.com/AWSSDKforPHP/latest/index.html#m=AmazonSDB/select
And http://docs.aws.amazon.com/AWSSDKforPHP/latest/index.html#m=AmazonSDB/select

Man maybe I just totally misread it but I am so happy you found my error. A million thanks to you...

Louis
