### ISSUE TITLE
Problem with searching inside cloudsearchdomain-2013-01-01.php

### ISSUE THREAD

**Issue by vjroby** [aws/aws-sdk-php#448]
There is a problem inside the file, I spend 2 hours figuring out what it is. When you do a search with cloud search it makes a POST request instead of GET, line 13 inside that file ('httpMethod' => 'POST',) . It supposed to be GET . So it throws an error of an unset Content-Type because a GET request doesn't have a body.
Also there is an error with displaying this type of error in class `JsonQueryExceptionParser` it doesn't find an index `__type` at line 31.

**Comment by jeremeamia** [comment]
Hmmm... yeah, that POST thing is definitely a regression. Sorry that it caused you trouble, but thank you for letting us know. You are using version 2.7.13, right? I'm going to tag a new release with the fix some time today.

**Comment by jeremeamia** [comment]
[Tagged a release](https://github.com/aws/aws-sdk-php/releases/tag/2.7.14) with the fix.

**Comment by vjroby** [comment]
Come a bit late, I was using 2.7.13. Thanks.
Best regards.
