### ISSUE TITLE
v3: s3 stream wrapper may throw S3Exception on nonexistent object

### ISSUE THREAD

**Issue by eXtreme** [aws/aws-sdk-php#449]
See related liip/LiipImagineBundle#531

There is a suggestion that may be a stream wrapper shouldn't throw exceptions.

The exception message is also misleading:

> Error executing Aws\S3\S3Client::getObject() on ""; String could not be parsed as XML

**Comment by mtdowling** [comment]
Thanks for the report. This has now been fixed in the v3 branch.
