### ISSUE TITLE
Any way to extract resource name for disallowed request?

### ISSUE THREAD

**Issue by Danack** [aws/aws-sdk-php#460]
When a Ec2Exception is thrown because the credentials used to make a request don't have the correct permissions to access a resource, is there a way to get the resource name so that it can be tested in the IAM policy simulator?

For context I'm trying to call `$ec2->describeInstances([]);` and I believe the policy for the user is:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1421790554000",
            "Effect": "Allow",
            "Action": [
                "ec2:*"
            ],
            "Resource": [
                "arn:aws:ec2:*:*:*/*"
            ]
        }
    ]
}
```

Which seems to work in the simulator, with the 'Resource name format' set to 'arn:aws:ec2:*:*:*/*' 

So possibly I'm testing against the wrong 'resource name'....but I can't see a way to find out what I should be testing the policy against, to ensure the credentials are allowed to call describeInstances.

**Comment by Danack** [comment]
Well I found the problem:

http://docs.aws.amazon.com/AWSEC2/latest/APIReference/ec2-api-permissions.html#d0e52225

> The following Amazon EC2 API actions currently do not support resource-level permissions. To use these actions in an IAM policy, you must grant users permission to use all resources for the action by using a * wildcard for the Resource element in your statement.

I still think it would be nice to have the required resource to be discoverable or listed in the exception message....

I guess maybe I should report the policy simulator has a bug in it if the above policy is saying 'allowed' in the policy simulator for the 'describeInstances' access, even though the resource element is incorrect?

**Comment by mtdowling** [comment]
Thanks for letting us know about the issue with the policy simulator. I'll pass this along to the relevant IAM team.

The documentation page you linked to provides all of the information you need for constructing ARNs, but it would be nice if the service would return this information in the error message so that it could be automatically extracted by the client. I'll pass this along as a feature request to the IAM team.
