### ISSUE TITLE
S3 getObjectUrl without any scheme?

### ISSUE THREAD

**Issue by yellow1912** [aws/aws-sdk-php#467]
This is not a bug report but rather a question (and also feature request if applicable). I'm using s3 to host my css/js files and thus when I get the link I don't want to have the http or https in it (the browsers can automatically determine which scheme to use). Right now I'm using str_replace to take out the part but it's rather ugly so I wonder if there is already a way to do it?

**Comment by mtdowling** [comment]
No, there's no other way to do it. Creating a relative URI is not supported by the SDK because it is meant to return an absolute URI.
