### ISSUE TITLE
Missing AllAccessDisabledException class

### ISSUE THREAD

**Issue by hostep** [aws/aws-sdk-php#469]
Hi there

I got this error while trying to use the S3 copyObject method:
`Exception: Warning: include(Aws\S3\Exception\AllAccessDisabledException.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory`

So, this class is missing apparently...

**Comment by mtdowling** [comment]
Hm. Can you provide a stack trace? We *attempt* to load specific exception classes by name by checking if a class exists. This triggers autoloaders to try to load the given class name. If the class is not found, then the autoloaders should not raise an error, and we will throw the generic service specific exception.

Are you using other autoloaders that are causing this error?

**Comment by hostep** [comment]
Ow ok, I didn't knew this.

Yes there is another autoloader in the picture: the one from the Magento e-commerce system.
I tried to use your library in a Magento system and Magento uses its own autoloader. So I had to adapt your autoloader a little bit by adding a third 'true' param to the `spl_autoload_register` function, which prepends your autoloading to the default autoloader from Magento. (I'm using the zip version btw)

Is this enough info?
It's not a big problem for us, I simply noticed it while testing something out.

**Comment by mtdowling** [comment]
That's enough info. Thanks. This sounds like a bug in Magento's autoloader. When an autoloader cannot find a class, it should not raise an error, but rather let other autoloaders in the chain attempt to load the class. You can see that they're just calling include in the Simple autoloader: http://svn.magentocommerce.com/source/branches/1.9/lib/Magento/Autoload/Simple.php.

Glad you got it working.
