### ISSUE TITLE
Route53 documentation error for changeResourceRecordSets

### ISSUE THREAD

**Issue by codeaken** [aws/aws-sdk-php#475]
The documentation for this function does not specify that the TTL-value is **required**. 

If you leave out the TTL-value (in ResourceRecordSet) when submitting a CREATE change an "Invalid request" exception will be thrown.

**Comment by mtdowling** [comment]
TTL is conditionally required, which means we cannot flag it as a required parameter (it's not required for Alias resource record sets). The Route53 documentation provides more information on TTL here: http://docs.aws.amazon.com/Route53/latest/APIReference/API_ChangeResourceRecordSets_Requests.html. The PHP SDK generates API documentation using a service description that contains all of the inputs, outputs, and API documentation. Unfortunately, the information that's described in the link I provided is not present in the service description. I'll pass this information along to the Route53 team.

**Comment by marcelodornelas** [comment]
Hi, 

I'm creating CNAME records programatically and I'm using 'changeResourceRecordSets'

I'm using the latest stable SDK3 and the 'SetIdentifier' parameter should not be required but the call doesn't work without it (it return an invalid request / InvalidInput error). 

Any ideas?

Many thanks,

Marcelo



 Aws\Route53\Exception\Route53Exception: Error executing "ChangeResourceRecordSets" on "https://route53.amazonaws.com/2013-04-01/hostedzone/Z3OG2D51K8XHLI/rrset/"; AWS HTTP error: Client error: 400 InvalidInput (client): Invalid request - <?xml version="1.0"?> <ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>InvalidInput</Code><Message>Invalid request</Message></Error><RequestId>7bc3f118-2bb2-11e5-aa40-9b497bc5150b</RequestId></ErrorResponse> in /Applications/MAMP/htdocs/admin.local/httpdocs/aws/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 152

![screen shot 2015-07-16 at 13 02 12](https://cloud.githubusercontent.com/assets/13365175/8722306/090f876a-2bbb-11e5-86ee-5fd71cee718c.png)

**Comment by jeskew** [comment]
@marcelodornelas I see that you're specifying a region. Is this request creating a latency resource record set? A `SetIdentifier` is used to distinguish weighted, latency, failover, and geolocation resource record sets. As mentioned above, some parameters are conditionally required depending on what kind of record set you're creating.

**Comment by mooseh** [comment]
Im experiencing an issue when sending a delete to an A record when there is more than 1 with the same name just weighted difference. I get "InvalidChangeBatch</Code><Message>Tried to delete resource record set [name='~REMOVED~.', type='A'] but it was not found" although that was generated from A listResourceRecordSets

**Comment by cjyclaire** [comment]
@mooseh Could you provide more information about the issue? Are you seeing the same trouble with original issue? It would be nice if you could provide some code snippet that help me to reproduce the issue to see where might go wrong?
