### ISSUE TITLE
Trying To Catch Error

### ISSUE THREAD

**Issue by jaydens** [aws/aws-sdk-php#476]
Hi,

Im trying to catch an error if the keys used to connect are invalid. However, I just keep getting a fatal error - I have looked at #86 but still cannot catch the exception.

require '../vendor/autoload.php';
use Aws\Ses\SesClient;
use Aws\Ses\SesClient\SesException;
.....
try{
    $client = SesClient::factory(array(
      'key'     => $this->aws_key,
      'secret'  => $this->aws_secret,
      'region'  => 'eu-west-1'
    ));
  } catch (SesException $e){ SesException $e) {
     $this->returnError($e->getMessage());
  } 

[Mon Feb 02 19:03:39 2015] [error] [client 109.231.201.34] PHP Fatal error:  Uncaught Aws\\Ses\\Exception\\SesException: AWS Error Code: InvalidClientTokenId, Status Code: 403, AWS Request ID: 32a69fe6-ab0e-11e4-9c40-2b4484def9d3, AWS Error Type: client, AWS Error Message: The security token included in the request is invalid., User-Agent: aws-sdk-php2/2.7.17 Guzzle/3.9.2 curl/7.19.7 PHP/5.3.3\n  thrown in /var/www/html/ses/vendor/aws/aws-sdk-php/src/Aws/Common/Exception/NamespaceExceptionFactory.php on line 91

If anyone could help that would much be appreciated.

Thanks!

**Comment by mtdowling** [comment]
You need to make sure that you're catching the exception properly by using the fully-qualified class name. You have used the wrong class name of the exception.

`use Aws\Ses\SesClient\SesException;` -> replace with -> `use Aws\Ses\Exception\SesException;`

**Comment by jaydens** [comment]
Hi @mtdowling - I had tried that prior as I read in docs however it still doesn't catch the error.

**Comment by TiagoGouvea** [comment]
Worked to me:

        try {
            /* @var $result \Aws\Result */
            $result = $sesClient->sendEmail($args);
        } catch (\Aws\Ses\Exception\SesException $e) {
            // Ok
        }
