### ISSUE TITLE
[curl] 3: <url> malformed [url]

### ISSUE THREAD

**Issue by auralon** [aws/aws-sdk-php#477]
I'm trying to upload to an S3 bucket using temporary credentials.

The temp credentials provide an Access Key ID, a Secret Access Key and a Token (amongst other things).  I then use these in the S3Client factory method like so

```
$s3 = \Aws\S3\S3Client::factory(array(
	'key'    => $accessKeyID,
	'secret' => $secretAccessKey,
	'region' => 'eu-west-1',
	'scheme' => 'https',
	'base_url' => 's3.amazonaws.com',
	'token' => $token
));

$s3->putObject(array(
	'Bucket'     => "auralonbucket",
	'Key'        => "test.png",
	'SourceFile' => '/www/auralon/test.png',
));
```

... from which I receive:

"[curl] 3: <url> malformed [url] //auralonbucket./test.png"

```
$wrapped = new TransferException($e->getMessage(), null, $e);
            $wrapped->setCurlHandle($e->getCurlHandle())
                ->setCurlInfo($e->getCurlInfo())
```

If I remove the region and/or base_url from the factory method, I receive:

"The AWS Access Key Id you provided does not exist in our records."

Any ideas why this isn't working, is there a misconfiguration, or is there an issue with the package?

**Comment by auralon** [comment]
OK, it seems that the Access Key ID was in fact being incorrectly passed to the factory method.  Meaning the "The AWS Access Key Id you provided does not exist in our records." message was the one I needed to pay attention to.  By adding the base_url/region I thought I was moving in the right direction, but it was a red herring.  Once I retrieve the credentials, I simply pass them to the s3 client factory method, as below:

```
$s3 = \Aws\S3\S3Client::factory(array(
	'key'    => $credentials->AccessKeyID,
	'secret' => $credentials->SecretAccessKey,
	'token' => $credentials->SessionToken
));

$result = $s3->putObject(array(
	'Bucket'     => $credentials->BucketName,
	'Key'        => $credentials->Key,
	'SourceFile' => '/www/auralon/test.png',
	'ACL'        => 'public-read',
));
```

This seems to have worked, sorry to waste your time!

**Comment by auralon** [comment]
Hopefully someone might find this post useful at some point, if they encounter the same problem!

**Comment by Maykonn** [comment]
I'm with the same error here
