### ISSUE TITLE
Can't unset ELB policies using this SDK

### ISSUE THREAD

**Issue by mateusz** [aws/aws-sdk-php#479]
It's doesn't seem possible currently to unset LB policies using this SDK (neither latest 2.7 nor master). We need to remove all policies from the LB.

[SDK spec](http://docs.aws.amazon.com/aws-sdk-php/latest/class-Aws.ElasticLoadBalancing.ElasticLoadBalancingClient.html#_setLoadBalancerPoliciesOfListener) implies ELBClient's "setLoadBalancerPoliciesOfListener" needs to be used for this (and indeed, can successfully be used from command line). The spec says that one needs to pass an empty list as `PolicyNames`.

HOWEVER this throws up an API exception "Policy Name cannot be empty":

	$elbClient->setLoadBalancerPoliciesOfListener(array(
		'LoadBalancerName' => $loadBalancer,
		'LoadBalancerPort' => $port,
		'PolicyNames' => array()
	);

If one tries setting `PolicyNames` to null, empty strings, or variants of thereof, Guzzle spits out validation error instead.

I've debugged the actual Guzzle HTTP request structures, and this SDK produces:

      string(33) "SetLoadBalancerPoliciesOfListener"
      'Version' =>
      string(10) "2012-06-01"
      'LoadBalancerName' =>
      string(21) "platformers-test-dev1"
      'LoadBalancerPort' =>
      int(80)
      'PolicyNames.member' =>
      string(0) ""

If I hack the magic special case for this API call in AwsQueryVisitor::resolveArray to do `$query['PolicyNames'] = ''` instead of what it currently does, then it produces something that seems to work with the API:

      'PolicyNames =>
      string(0) ""

(note ".member" is now gone).

Is it a bug with this SDK? Or am I just plain stupid and can't figure out the proper way to do this? :-)

Many thanks.

**Comment by mtdowling** [comment]
Thanks for the thorough report. I think this might be related to another issue we had with empty list serialization in these query protocol services. I'll check on how we can address this and if the previous solution (IIRC) can be applied more generically.

**Comment by mtdowling** [comment]
Fixed in https://github.com/aws/aws-sdk-php/commit/b358d67b0e75195914799f5755f78d2bb37fdb69
