### ISSUE TITLE
Connect to local dynamoDB not working in v3

### ISSUE THREAD

**Issue by benmadin** [aws/aws-sdk-php#485]
G'day,

I have (had) a configuration that looks something like:

```php
use Aws\Sdk; #B replaces Aws\Common?
use Aws\Common; #B maybe not needed anymore?
use GuzzleHttp\Command; #B Trying to get the search() to work...
use Aws\Common\Credentials\Credentials;
use Aws\DynamoDb\DynamoDbClient;
use Aws\Exception\DynamoDbException;

$dsn = array(
    			'credentials' => [
					'key'    => 'bounces',
					'secret' => 'YOUR_AWS_SECRET_ACCESS_KEY',
				],
				'region' => 'ap-southeast-1',
				'version' => 'latest',
				'base_url'=> 'http://localhost:8000',
				'debug' => true
);
$this->client = new DynamoDbClient($dsn);
```

but now when I try to connect, (updated to latest v3), I am seeing in the debug output

    Host: dynamodb.ap-southeast-1.amazonaws.com 

If I don't specify a region at all, I get an error:
```
InvalidArgumentException

Missing required client configuration options: 

region: (string)
```

if I specify '', I get an error:
```
"https://dynamodb..amazonaws.com"
```

and if I put the base_url into the region, I get an error :

```
Aws\DynamoDb\Exception\DynamoDbException

Error executing Aws\DynamoDb\DynamoDbClient::scan() on "https://dynamodb.http//localhost:8000.amazonaws.com"
; cURL error 6: Could not resolve host: dynamodb.http
```

Have I missed something?

cheers

Ben

**Comment by mtdowling** [comment]
Hi Ben. ``base_url`` has been deprecated in favor of ``endpoint``.  V2 supports both ``endpoint`` and ``base_url``, while v3 only supports ``endpoint``.

I'm currently working on the documentation of v3, so hopefully we'll be able to clear up any confusion about configuration settings.
