### ISSUE TITLE
The request signature we calculated does not match the signature you provided. Check your key and signing method.

### ISSUE THREAD

**Issue by ryanmc2033** [aws/aws-sdk-php#489]
I am just getting started with AWS and I am trying to upload some images using this sdk. I have been following the examples and I am now getting the error listed in the title. 

I have checked my aws_access_key_id and aws_secret_access_key and they are both correct. I have stepped through the code and made sure the request contained the correct keys and data. 

I have tried both listing buckets and uploading an image but they both return the same message.

```
$client = S3Client::factory(array(
            'profile' => 'default',
            'base_url' => xxx.s3.amazonaws.com/'
        ));

        $result = $client->listBuckets();

        try {
            $resource = fopen($path, 'r');
            $client->upload($bucket, $name, $resource, 'public-read');
        } catch (S3Exception $e) {
            echo "There was an error uploading the file.\n";
        }
```

I have also Search online for answers and followed a couple ideas, but still have not found a solution.

If anyone has a tip I would appreciate it.

Thanks

**Comment by mtdowling** [comment]
Setting base_url is likely causing problems with the signature. Can you remove that option? Instead, you can just specify a region if needed.

**Comment by ryanmc2033** [comment]
Interesting, before I added base_url, I got a message like this "The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint: "xxx.s3.amazonaws.com"." The xxx is the name of my bucket. That message made me think I needed the base_url. 

However, when I added 
```
$client = S3Client::factory(array(
            'profile' => 'default',
            'region' => 'us-west-2'
        ));
```
it seems to be working.

Thanks

It would be great if the error message actually provided useful information. As it is they are misleading and confusing.
