### ISSUE TITLE
Cognito Register Device 

### ISSUE THREAD

**Issue by robert-dinu** [aws/aws-sdk-php#494]
Hello!
I am trying to register a device with cognito to get the Cognito Device Id. 
I keep getting this error: "These credentials are not valid for accessing this resource", requestId: 21114989-bbf5-11e4-86fd-c7870ca1664a ,exceptionCode="NotAuthorizedException" , host="cognito-sync.us-east-1.amazonaws.com", path="/identitypools/us-east-1:identityPoolID/identity/us-east-1:identityId/device".

I created an assume role for the Amazon SNS service for Cognito, I created an App in SNS and assigned it to that Cognito Identity Pool.

Everything works fine, creating identties, datasets, update and delete dataset.

Thanks!

Regards,
Robert.

**Comment by robert-dinu** [comment]
It wasn't an SDK issue. AWS API is poor documented.

**Comment by kensupermen** [comment]
I have the same issue, have anyone fixed?
