### ISSUE TITLE
Unable to use SDK to upload files over 2.15G on Windows

### ISSUE THREAD

**Issue by klasalvia** [aws/aws-sdk-php#506]
PHP has a limitation on windows when reading file sizes. File sizes above approximately 2.1G (PHP_INT_MAX on Windows) return a negative number, which makes multipart upload fail.

The first instance this was noticed was here: 
https://github.com/aws/aws-sdk-php/blob/master/src/Aws/S3/Sync/UploadSync.php#L61

Further down you can see the $file object is passed and there are other calls to getSize() that will fail.

A possible workaround is to use sprintf and cast to a double data type, but I would rather not diverge my SDK if possible. Ex:
`$fileSize = (double) sprintf("%u", $file->getSize());`

**Comment by mtdowling** [comment]
This is a known issue with Windows builds of PHP. I don't think there's a simple fix that we can make to the SDK to support 64-bit integers on Windows or any other 32-bit build.

Even trying to read from a file on a Windows build that's bigger than PHP_INT_MAX is unpredictable. For example, calling ftell on a stream resource after seeking past PHP_INT_MAX will return unpredictable results. In your example,  I don't even think `$file->getSize()` will return the right result once you've gone past PHP_INT_MAX.

**Comment by klasalvia** [comment]
I see what you are saying - this could be a bigger issue than just file size. I also tried the example on larger file sizes (66G) and it did not work. Since this is a PHP limitation, I might be better off using another SDK. Thanks for your quick response.

**Comment by mtdowling** [comment]
I think there are experimental 64-bit builds of PHP for Windows. But, yeah, if you have to use Windows are using files > than the 32-bit cutoff, then you may need to use a different language's SDK.
