### ISSUE TITLE
CloudFront 'The parameter originPath is null'

### ISSUE THREAD

**Issue by lonnylot** [aws/aws-sdk-php#507]
I receive 'The parameter originPath is null' when making the call to `createDistribution` even though I'm not using the 'originPath' and it is not required.

**Comment by mtdowling** [comment]
Can you provide an example of when you encountered this error? Which version of the SDK are you using?

**Comment by lonnylot** [comment]
Versions:
```
lonnykapelushnik:~/Development/bond/aws-test  (master) ⚡  composer show -i
aws/aws-sdk-php               2.7.22  AWS SDK for PHP - Use Amazon Web Services in your PHP project
aws/aws-sdk-php-laravel       1.1.2   A simple Laravel 4 service provider for including the AWS SDK for PHP.
```

Error:
```
[2015-03-18 18:41:45] production.ERROR: Aws\CloudFront\Exception\InvalidArgumentException: AWS Error Code: InvalidArgument, Status Code: 400, AWS Request ID: 6d38e6da-cd9e-11e4-8f00-dd185ddb5737, AWS Error Type: client, AWS Error Message: The parameter originPath is null., User-Agent: aws-sdk-php2/2.7.22 Guzzle/3.9.2 curl/7.37.1 PHP/5.5.22 Laravel/4.2.17 L4MOD/1.1.0 [] []
```

Example code: https://github.com/lonnylot/aws-test

You'll need to add a `.env.php` file to the root dir w/:
```
<?php
return [
	'aws_key' => '',
	'aws_secret' => '',
	'bucket_name' => ''
];
```

**Comment by lonnylot** [comment]
And to run the example:

`php artisan test:aws`

**Comment by mtdowling** [comment]
Thanks. I'll get in contact with the CloudFront team and see if there is an issue.

**Comment by mtdowling** [comment]
The CloudFront API had an issue related to the originPath parameter. They have a fix that will be deployed in their next release. They will update this forum issue when it is deployed: https://forums.aws.amazon.com/thread.jspa?threadID=172288

In the meantime, you can pass originPath as '' to work around the issue.

**Comment by lonnylot** [comment]
@mtdowling thanks for the response. IIRC I had tried passing in the originPath as '' and it threw some sort of error. I'll test it out and if there are more problems I can open up a support ticket.
