### ISSUE TITLE
DynamoDb putItem response is empty

### ISSUE THREAD

**Issue by alexz707** [aws/aws-sdk-php#508]
HI!
I just wanted to try the example on 
http://docs.aws.amazon.com/aws-sdk-php/guide/latest/service-dynamodb.html#adding-items
But after a successful add the response is empty!?

$result->getPath('ConsumedCapacity/CapacityUnits') <- will return nothing
The response from Guzzle is {}

To be sure I have tried the describeTable method and that one returns a result. So i think its maybe an API change ?

I'm using 2.7.22
thanks for fixing ;-)

regards Alex

**Comment by mtdowling** [comment]
Thanks for pointing this out. Consumed capacity and various other information in the putItem response are only returned conditionally if the client asks for the information. You can get the ConsumedCapacity data by passing the following into the operation:

```php
$result = $client->putItem(array(
    'ReturnConsumedCapacity' => 'TOTAL',
    'TableName' => 'errors',
    'Item' => array(
        'id'      => array('N' => '1201'),
        'time'    => array('N' => $time),
        'error'   => array('S' => 'Executive overflow'),
        'message' => array('S' => 'no vacant areas')
    )
));
```

I'll push an update to the documentation shortly.
