### ISSUE TITLE
SNS: How to verify incoming notification's authenticity

### ISSUE THREAD

**Issue by poisa** [aws/aws-sdk-php#51]
I've set up an HTTP endpoint and confirmed it. I'm wondering if the PHP 2 SDK has any means of checking whatever comes through the endpoint and verifying the notification's signature so that we know it's legit.

(note that at the time of this writing the sdk's sns docs are still under construction that's why I'm asking)

**Comment by abhyudayasrinet** [comment]
I don't see `MessageValidator` in the latest version of the PHP sdk. Is this deprecated now?

**Comment by poisa** [comment]
@abhyudayasrinet This can now be found here: https://github.com/aws/aws-php-sns-message-validator
