### ISSUE TITLE
S3 Stream Wrapper - Downloading chunk - infinite loop

### ISSUE THREAD

**Issue by eveyrat** [aws/aws-sdk-php#510]
Hi,
I can't make this code sample work. I get an infinite loop, any idea ?

http://docs.aws.amazon.com/aws-sdk-php/guide/latest/feature-s3-stream-wrapper.html#opening-seekable-streams 

    // Open a stream in read-only mode
    if ($stream = fopen('s3://bucket/key', 'r')) {
        // While the stream is still open
        while (!feof($stream)) {
            // Read 1024 bytes from the stream
            echo fread($stream, 1024);
        }
        // Be sure to close the stream resource when you're done with it
        fclose($stream);
    }

Use case : upload from s3 to Youtube using Resumable upload:
https://developers.google.com/youtube/v3/code_samples/php#resumable_uploads

Thanks a lot !

**Comment by jeremeamia** [comment]
I'm not able to reproduce this error, and I've tested your code on several different sized files. Are you using the latest version of the SDK? How do you know you are getting an infinite loop?

**Comment by eveyrat** [comment]
In fact i'm wrong about infinite loop but i can't make bigger chunks just like this :
    
    echo fread($stream, 5 * 1024 * 1024 );

It's working perfectly when using a local file instead of the s3 stream.

**Comment by eveyrat** [comment]
The following snippet should return the same length for the chunk and the actual filesize of my object.

        $filename = 's3://bucket/sample.mp4';
        //$filename = '/var/www/sample/web/uploads/sample.mp4';
        $stream = fopen($filename, 'r');
        printf('chunkSize: %d - filesize: %d', 
            strlen(fread($stream, filesize($filename))),
            filesize($filename)
        );

Output :

    s3 wrapper : chunkSize: 8192 - filesize: 16121660
    local file : chunkSize: 16121660 - filesize: 16121660

**Comment by jeremeamia** [comment]
No, I don't think it should. PHP behaves a little differently when doing `fread` on a remote stream vs. a local file. In the [PHP Manual entry for `fread`](http://php.net/manual/en/function.fread.php) it says:

> if the stream is read buffered and it does not represent a plain file, at most one read of up to a number of bytes equal to the chunk size (usually 8192) is made; depending on the previously buffered data, the size of the returned data may be larger than the chunk size.
