### ISSUE TITLE
SES sendEmail() to handle attachments

### ISSUE THREAD

**Issue by zang** [aws/aws-sdk-php#514]
Everything works find with sendEmail() function to handle basic emails.
However, I couldn't find a way to have attachments with the emails.

Any suggestions?

thanks in advanced,
Lucy

**Comment by jeremeamia** [comment]
To include an attachment in your email, you must _manually_ create a multipart email message, with all of the necessary data. This includes a MIME part that contains an appropriate Content-Type header, along with the MIME-encoded content, and a Content-Disposition header, to specify whether the content is to be displayed inline or treated as an attachment.

Once you have constructed your message, you can send it using the [SendRawEmail API](http://docs.aws.amazon.com/ses/latest/APIReference/API_SendRawEmail.html), which can be done using the the [`SesClient::sendRawEmail` method](http://docs.aws.amazon.com/aws-sdk-php/latest/class-Aws.Ses.SesClient.html#_sendRawEmail) in the SDK.
