### ISSUE TITLE
Grabbing information on a existing ELB

### ISSUE THREAD

**Issue by BardiaAfshin** [aws/aws-sdk-php#515]
Via this SDK, I'd like to grab some information from a existing ELB via some predefined parameter, a good example would be LoadBalancerName. Is that possible? I'm ultimately going going to feed this into Route53, and create A record to some friendly predefined name.

Thoughts?

**Comment by jeremeamia** [comment]
The [`ElasticLoadBalancingClient::describeLoadBalancers() method`](http://docs.aws.amazon.com/aws-sdk-php/latest/class-Aws.ElasticLoadBalancing.ElasticLoadBalancingClient.html#_describeLoadBalancers) would be the way to get information about a load balancer.

**Comment by jeremeamia** [comment]
Closing. Feel free to reopen if needed.
