### ISSUE TITLE
Error completing request

### ISSUE THREAD

**Issue by ducnguyenhuy** [aws/aws-sdk-php#520]
Hi,

I got an error with same issue #394 on SDK version 2.7.24.
Please take a look at screenshot below and let me know your thoughts.
![guzzle-http-exception-requestexception](https://cloud.githubusercontent.com/assets/3691894/6861508/b3edafe4-d469-11e4-926a-083defcb16db.png)

Thanks.

**Comment by mtdowling** [comment]
Can you provide verbose cURL output?

Almost every case of this that I've seen is the result of cURL not receiving a response or error. This is likely cause by a bad network connection. Verbose cURL output might be able to provide supporting evidence.

I suggest wrapping your call in a try/catch and retrying to the request if it fails with this particular error.

**Comment by ducnguyenhuy** [comment]
Could you tell me how to get "verbose cURL output"?

Thanks.

**Comment by mtdowling** [comment]
Sure, just supply this configuration to your client:

```php
$client = Aws\S3\S3Client::factory([
    // other options...,
    'curl.options' => [CURLOPT_VERBOSE => true],
]);
```

**Comment by nhitran** [comment]
So this will help to output more details about error, right?

I have tried to use a loop and try/catch to retry calling. Max of retrying is 3 times. Do you think it's good?

Thanks

**Comment by ducnguyenhuy** [comment]
So this will help to output more details about error, right? 

I have tried to use a loop and try/catch to retry calling. Max of retrying is 3 times. Do you think it's good? 

Thanks

**Comment by mtdowling** [comment]
Yes, this will give debug information from curl and will hopefully tell us what is going wrong in curl.

Retrying 3 times sounds good. Retrying failed requests is mostly base on application specific thresholds (i.e., number of retries, delays between retries, etc.).

**Comment by ducnguyenhuy** [comment]
Ok, thanks.

I will check again and let you know.

**Comment by ducnguyenhuy** [comment]
Thanks for suggestion.

Adding retry works and try/catch to show error in log. But the error's still "Error completing request". Does that mean the server takes so long to response?


Duc.

**Comment by mtdowling** [comment]
> Adding retry works and try/catch to show error in log.

Great!

> But the error's still "Error completing request". Does that mean the server takes so long to response?

That's possible. I suspect that there's a bug in cURL or the PHP libcurl bindings. One possible way to determine that would be to see the verbose curl output of a failed request.

**Comment by mtdowling** [comment]
Just wanted to quickly follow up on this. Did you ever get the verbose curl output?

**Comment by ducnguyenhuy** [comment]
Not yet, this issue happens somtime. So I need more time to check if it shows or not.

Thanks.

**Comment by mtdowling** [comment]
By adding the retry from https://github.com/aws/aws-sdk-php/issues/520#issuecomment-89995392, you will probably not see this error again. However, if you do, please provide us with the verbose curl output so that we can investigate further. Closing until then.
