### ISSUE TITLE
SignatureDoesNotMatchException in NamespaceExceptionFactory.php line 91

### ISSUE THREAD

**Issue by JustinLien** [aws/aws-sdk-php#521]
Error occurs when bucket is created with a period, e.g., app.test

Changing the folder name into a hyphen seems to fixed it.

**Comment by mtdowling** [comment]
Which signature version is being utilized (v4 or s3)? If you don't know that, then what region are you connecting to?

**Comment by JustinLien** [comment]
@mtdowling region us-west-1.
How do I find out which signature version being utilized?

I tested it again this morning and everything seem to be resolved. Sorry, for your trouble. I spend the whole day yesterday and this was what I concluded, however; as of now, it seem to be working fine.

**Comment by JustinLien** [comment]
I'm going to close this issue since I cannot replicate it today.

Thanks again!

**Comment by codivist** [comment]
I am getting the same error
```
Aws\S3\Exception\SignatureDoesNotMatchException: AWS Error Code: SignatureDoesNotMatch, Status Code: 403, AWS Request ID: DF90119C6E86B26D, AWS Error Type: client, AWS Error Message: The request signature we calculated does not match the signature you provided. Check your key and signing method., User-Agent: aws-sdk-php2/2.8.1 Guzzle/3.9.3 curl/7.35.0 PHP/5.5.9-1ubuntu4.7 Laravel/4.2.17 L4MOD/1.1.0
```
Not sure what signature version I'm using, but I am using us-east-1
The bucket is already created, but the bucket name is ps-scores/data (so no periods in it).
The filename being uploaded is basically a uuid: fbf7bb3a-ba6f-41dc-a27f-e69955553F31.psc

This was happening in 2.8.0 and 2.8.1
I can replicate the error every time.

**Comment by jeremeamia** [comment]
The bucket name is probably "ps-scores", and "data/" should be part of the key (filename). If that doesn't work you will need to provide us the code you are running that is causing the error.

-- Jeremy Lindblom
PHP Software Engineer, AWS

**Comment by codivist** [comment]
Yes, my bad, the bucket is ps-scores and data/ is the folder that it is getting uploaded to (in the key name)

**Comment by codivist** [comment]
my putObject code:
```php
$upload = $s3->putObject(
							array(
								'Bucket'      => 'ps-scores',
								'Key'         => 'data/uuidFileName.psc',
								'Body'        => \File::get('S3Files/' . Input::get('matchUUID') . '.psc'),
								'ContentType' => 'binary/octet-stream',
								'Metadata'    => [
									'matchType'   => 'type III',
									'matchName'   => 'uuidFileName',
									'matchDate'   => 2015/04/19,
									'inputMethod' => 'uploaded from device',
								]
							)
						);
```

**Comment by codivist** [comment]
bah! Nevermind. Just sat down with our iOS developers and they introduced an issue in the matchName that was causing only certain uploads to fail.  They are fixing their code and we can move on happy and care free knowing it wasn't us! 

Thanks
