### ISSUE TITLE
Deprecated guzzle/guzzle lib is still in use

### ISSUE THREAD

**Issue by Im0rtality** [aws/aws-sdk-php#527]
`guzzle/guzzle:3.*` is deprecated in favour of `guzzlehttp/guzzle:5.*`. Would be nice to not use deprecated libs.

https://github.com/guzzle/guzzle   <- guzzlehttp
https://github.com/guzzle3/guzzle  <- guzzle

https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

Could this migration be possible?

**Comment by GrahamCampbell** [comment]
https://github.com/aws/aws-sdk-php/tree/v3

**Comment by GrahamCampbell** [comment]
Also, moving to guzzle 5 is non-trivial for the aws sdk.

**Comment by Im0rtality** [comment]
That's great. Do you guys have any estimates/guestimates on v3 release?

**Comment by GrahamCampbell** [comment]
As I understand, the plan was to have it ready in May - it's nothing to do with me though. :)

Ping @jeremeamia.

**Comment by mtdowling** [comment]
We are blocked on PSR-7 acceptance. We will ship shortly thereafter.
