### ISSUE TITLE
Unable to delete S3 Notifications

### ISSUE THREAD

**Issue by MichaelShilling** [aws/aws-sdk-php#528]
I am unable to delete all SQS notifications through the PHP SDK. Per the REST documentation ( http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTnotification.html ) sending a message with a message body of `<NotificationConfiguration />` should delete all notifications from the S3 Bucket.

However, when executing code that does the following:

```php
$params['Bucket'] = '<bucketname>';

$S3Client->putBucketNotification($params);
```

An error is thrown:
```
[Aws\S3\Exception\MissingRequestBodyErrorException]
Request Body is empty
```

This is unexpected since per the documentation listed above, an empty `NotificationConfiguration` is valid (and is in fact, the default configuration). 

There is no mention of deleting notifications in the PHP SDK documentation, though the PHP documentation refers to the REST documentation for additional information which states that this is possible.

I have tried all of the following which all produce the same error:
```php
$params['Bucket'] = '<bucketname>';
$params['QueueConfiguration'] = array();

$S3Client->putBucketNotification($params);
```
```php
$params['Bucket'] = '<bucketname>';
$params['QueueConfiguration'] = array(
    'id' => '<existing Id>'
);

$S3Client->putBucketNotification($params);
```
```php
$params['Bucket'] = '<bucketname>';
$params['QueueConfiguration'] = array(
    'id' => '<existing Id>',
    'Events' => array()
);

$S3Client->putBucketNotification($params);
```
And finally, 
```php
$params['Bucket'] = '<bucketname>';
$params['QueueConfiguration'] = array(
    'id' => '<existing Id>',
    'Events' => array(),
    'Queue' => '<same queue ARN>'
);

$S3Client->putBucketNotification($params);
```
and
```php
$params['Bucket'] = '<bucketname>';
$params['QueueConfiguration'] = array(
    'id' => '<existing Id>',
    'Queue' => '<same queue ARN>'
);

$S3Client->putBucketNotification($params);
```
both return the following error:
```
Aws\S3\Exception\MalformedXMLException]
The XML you provided was not well-formed or did not validate against our published schema
```

For now, as a workaround, I have modified the code to only remove the SQS permission that allows the bucket to submit a message, but this is not a clean solution, and should be rectified before we hit production.

**Comment by mtdowling** [comment]
Thanks for reporting. I've pushed a fix that now allows for an empty XML body for this operation. It is now sent over the wire successfully like this (sans signature):

```
PUT /?notification HTTP/1.1
Host: my-bucket.s3.amazonaws.com
User-Agent: aws-sdk-php2/2.7.27 Guzzle/3.9.3 curl/7.39.0 PHP/5.6.3
Content-Type: application/xml
Content-Length: 99

<?xml version="1.0"?>
<NotificationConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"/>
```

**Comment by MichaelShilling** [comment]
Awesome! I'll keep an eye out for this in the next minor release!

Thank you!
