### ISSUE TITLE
Download Bucket issue

### ISSUE THREAD

**Issue by incipio-swetha** [aws/aws-sdk-php#529]
Hi,

I am having issues with downloadBucket() functionality, when I call the function    $client->downloadBucket(), the files are being downloaded to the "server", but I want them to be downloaded to my computer downloads folder. Any help is appreciated here.

when I am using the below code - nothing is being downloaded to my computer:

    require 'aws-autoloader.php';
    use Aws\S3\S3Client;
    use Aws\Common\Aws;
     $client = S3Client::factory(array(
                                      'key'    => 'jskskds',
                                      'secret' => 'jkkskkds'
                                      ));
 $client->downloadBucket('/Users/home/Downloads/', 'bucket', 'prefix/');

Thanks,
Swetha.

**Comment by mtdowling** [comment]
Hi. If you are running the code from your server, then the files will be downloaded to your server. You will need to run the code from your computer in order for the files to be downloaded to your computer. Alternatively, you could set up NFS or some other kind of shared disk to connect your server to your computer.

Please let me know if I misunderstood the question.

**Comment by mtdowling** [comment]
I'll go ahead and close this issue. Let me know if you still need assistance.
