### ISSUE TITLE
Lambda invoke

### ISSUE THREAD

**Issue by bjornbos** [aws/aws-sdk-php#530]
The 'location' argument for the 'Payload' parameter in the invoke method of the Lambda class is missing:
https://github.com/aws/aws-sdk-php/blob/master/src/Aws/Lambda/Resources/lambda-2015-03-31.php#L421

**Comment by mtdowling** [comment]
Based on the API documentation, I think the 'location' argument is just part of the raw JSON payload: http://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html. You need to provide a raw JSON document as a string parameter here.

**Comment by bjornbos** [comment]
So wouldn't it need

    'location' => 'body'

then (just like with the InvokeAsync method)? It's not working at the moment because it's not receiving any payload...

**Comment by mtdowling** [comment]
Ah yes, you're right. I'll fix this up and have it ready to go for our next release.
