### ISSUE TITLE
Specify the protocol name

### ISSUE THREAD

**Issue by JoniJnm** [aws/aws-sdk-php#531]
Could Aws\S3\S3Client::registerStreamWrapper accept a protocol name?

To work with two clients is a lite hard. Having different (s3Custom1, s3Custom2) will help us.

**Comment by mtdowling** [comment]
I suppose that is possible. We'll add this as a feature request.

**Comment by mtdowling** [comment]
Support for using a custom protocol will be added in v3 of the PHP SDK which will likely ship in the next few weeks.
