### ISSUE TITLE
eu-central-1 : createPresignedUrl with putObject gives SignatureDoesNotMatch

### ISSUE THREAD

**Issue by fustundag** [aws/aws-sdk-php#534]
When I want to use eu-central-1 region to use createPresignedUrl for putObject, api gives error "SignatureDoesNotMatch".
I can use putObject direclty with same credentials for eu-central-1.

I can also use createPresignedUrl for any eu-west-1 bucket with same credentials

AWS-SDK-PHP Version : 2.8.1 installed via composer

$s3Client = S3Client::factory([
            'key'    => 'mykey',
            'secret' => 'mysecret',
            'region' => 'eu-central-1'
        ]);

$command = $s3Client->getCommand('PutObject', [
            'Bucket'        => 'mybucket',
            'Key'           => 'user1/abc',
            'ContentType'   => 'image/jpeg',
            'ContentLength' => 5776,
            'Body'          => ''
        ]);

$command->createPresignedUrl('+10 Minutes');

**Comment by mtdowling** [comment]
Sorry to hear that. I'll take a look and see if I can reproduce the issue.

**Comment by fustundag** [comment]
To clear misunderstanding  : I can create presigned url successfully but if I want to use it, it gives SignatureDoesNotMatch error

curl -v -H "Content-Type: image/jpeg" -T myimage.jpg "<presigned_url>"

**Comment by fustundag** [comment]
I think I found problem : 

When eu-central-1 region used, S3SignatureV4 is required. S3SignatureV4 extends Aws/Common/Signature/SignatureV4 class.

At Aws/Common/Signature/SignatureV4.php:273, all createPresignedRequest calls cloned with GET method. But if request is for "PutObject", "PUT" should be used.

**Comment by fustundag** [comment]
To test it, I chnaged Aws/Common/Signature/SignatureV4.php:273 line to 

$sr = RequestFactory::getInstance()->cloneRequestWithMethod($request, 'PUT');

and I added "Expires: 600" header to curl cmd:

curl -v -H "Expires: 600" -H "Content-Type: image/jpeg" -T myimage.jpg "[presignedUrl]"

I put image file successfully to bucket.

**Comment by mtdowling** [comment]
Fixed in https://github.com/aws/aws-sdk-php/pull/538
