### ISSUE TITLE
Also Using Zip Install, trouble with Autoload

### ISSUE THREAD

**Issue by cgltower** [aws/aws-sdk-php#539]
Hi

Im also using the Zip installation like issue [#496](https://github.com/aws/aws-sdk-php/issues/496) Using this code

	<?php
	 
	require_once LIBS_PATH .  'aws-sdk-php/aws-autoloader.php' ;

	use Aws\Common\Aws;
	use Aws\Common\Enum\Region;
	use Aws\Ec2\Ec2Client;

	class AppsAwsModel 
	{
		public function createAWSApp($app_id)
		{
			// Setup the EC2 object
			$this->ec2client = Ec2Client::factory(array(
				//'profile' => '<profile in your aws credentials file>',
				'key' => AWS_ACCESS_KEY_ID,
				'secret' => AWS_SECRET_ACCESS_KEY,
				'region'  => $this->app->aws_region
			));
			...

The response is formatted by the [framework php-login aka Huge](https://github.com/panique/huge)

     The file Aws\Ec2\Ec2Client.php is missing in the libs folder.

I think the autoloader runs ok. Why would it not like the namespace - is this related to the framework?  The files are there in correct path, LIBS_PATH is correct too.

thx

For reference, framework's autoload is:

		function autoload($class) {
			// if file does not exist in LIBS_PATH folder [set it in config/config.php]
			if (file_exists(LIBS_PATH . $class . ".php")) {
				require LIBS_PATH . $class . ".php";
			} else {
				exit ('The file ' . $class . '.php is missing in the libs folder.');
			}
		}

**Comment by mtdowling** [comment]
The SDK requires that other autoloaders will play nicely and not error out if they cannot find the script to autoload. This allows you to stack autoloaders so that multiple autoloaders can handle different libraries and requirements. If the framework you are using does not allow multiple autoloaders, then you will need to open an issue on their project. Taking a look at the "huge" framework, it looks like they now use [PSR-4 autoloading](https://github.com/panique/huge/blob/master/composer.json#L15), so perhaps you just need to update that dependency.

**Comment by mtdowling** [comment]
So the answer to this question is that you need to use the SDK with a library that works with other autoloaders. If the library you are using does not allow this, then you may need to disable their built-in autoload() function and instead add an autoloader based on PHP's spl_autoload_register(): http://php.net/manual/en/function.spl-autoload-register.php

**Comment by cgltower** [comment]
Yes, I agree.  I will try that, its just a load of work.
For now Ive worked around this version of framework's autoload with a hack
		function autoload($class) {
			// if file does not exist in LIBS_PATH folder [set it in config/config.php]
			$pathnclass = str_replace("\\" , DIRECTORY_SEPARATOR , $class);
			if (file_exists(LIBS_PATH . $class . ".php")) {
				require LIBS_PATH . $class . ".php";
			} elseif (file_exists(LIBS_PATH . 'aws-sdk-php' . DIRECTORY_SEPARATOR . $pathnclass . ".php")) {	
				require LIBS_PATH . 'aws-sdk-php' . DIRECTORY_SEPARATOR . $pathnclass . ".php";
			} else {
				exit ('The file ' . $class . '.php is missing in the libs folder. ' . LIBS_PATH . 'aws-sdk-php' . DIRECTORY_SEPARATOR . $pathnclass );
			}
		}
