### ISSUE TITLE
Missing last character in base 64 encoded text files

### ISSUE THREAD

**Issue by gangadhar** [aws/aws-sdk-php#540]
We are having a very weird issue with PHP's stream conversion filter (base64_encode). The goal is to read file from S3 bucket using AWS S3 SDK's streamWrapper and base64 encode it, echo it to response. For this we are using the following code,

```php
@ob_flush();
@flush();
$fh = fopen(<FILE_PATH>, 'r');
stream_filter_append($fh, 'convert.base64-encode');
fpassthru($fh);
fclose($fh);
```
This works for all types of files (image, audio, video etc), but for a text file it drops the last character. When we decode the base64 response, last character is missing.

For example,

```Hello, world! ```which encodes to ```SGVsbG8sIHdvcmxkIQ==```

But the above function omits last character while encoding, producing the following

```SGVsbG8sIHdvcmxk``` which decodes to ```Hello, world```

We tested some scenarios to isolate the issue:

* We tested streaming the text file from a different location and the encoding works fine. For eg.,

```php
<?php
//$fh = fopen("./test.txt", 'r');
$fh = fopen("https://gmail.com/robots.txt", 'r');
stream_filter_append($fh, 'convert.base64-encode');
fpassthru($fh);
fclose($fh);
```
* We tried a different stream filter also and we got the output with no problem.

```php
<?php
//$fh = fopen("./test.txt", 'r');
$fh = fopen("https://gmail.com/robots.txt", 'r');
//stream_filter_append($fh, 'convert.base64-encode');
stream_filter_append($fh, 'string.toupper');
fpassthru($fh);
fclose($fh);
```

So the issue seems to be with the streaming of text files from S3. Does anyone know how to solve this issue?

**Comment by mtdowling** [comment]
Some stream filters require buffering the data as it passes through. In order for remaining characters in the buffer to pass through the stream, you need to flush the buffer. For example, this can be done by removing the stream filter with http://php.net/manual/en/function.stream-filter-remove.php. The example in the linked documentation shows how to store the ID of the filter and remove the filter from the stream.

**Comment by gangadhar** [comment]
@mtdowling Thanks for the reply. We tried the following two methods and it did not work! Do you have any other ideas?
```php
$fh = fopen("s3://$s3_bucket/$file", "r");
$filter = stream_filter_append($fh, "convert.base64-encode", STREAM_FILTER_READ);
fpassthru($fh);
stream_filter_remove($filter);
fclose($fh);
```
new approach for reading file:
```php
readfile("php://filter/read=convert.base64-encode/resource=s3://$s3_bucket/$file");
```

**Comment by mtdowling** [comment]
Did you try calling `fpassthru()` again after removing the filter?

**Comment by mtdowling** [comment]
I tested it out and confirmed that my suggestion is correct: you will need to remove the filter and then call fpassthru again in order to actually consume and emit the data that was flushed from the base64 filter's buffer.

By removing the filter from the stream, you flush the buffer of the filter and place it into the buffer of the stream such that a subsequent call to read from the stream will read the previously buffered data.

**Comment by gangadhar** [comment]
@mtdowling : Thanks! I confirm. Your fix is working for us. Appreciate your quick response.

**Comment by kkopachev** [comment]
for people coming from search engines: there is php's bug report on that issue https://bugs.php.net/bug.php?id=75910
