### ISSUE TITLE
CloudHsmClient getConfig not working

### ISSUE THREAD

**Issue by hacfi** [aws/aws-sdk-php#544]
The method `getConfig` has to be renamed:
`Aws\CloudHsm\CloudHsmClient` extends `Aws\Common\Client\AbstractClient` which extends `Guzzle\Service\Client` which extends `Guzzle\Http\Client` which has a final method called getConfig so the request is never sent: 
https://github.com/guzzle/guzzle3/blob/master/src/Guzzle/Http/Client.php#L99

**Comment by jeremeamia** [comment]
Ouch, that is an unfortunate naming collision.

The operation is still executable by using command objects though.

```php
$result = $cloudHsmClient->getCommand('GetConfig', [...])->getResult();
```

We'll discuss what we want to do about the naming collision long-term.

Are these issues you are submitting things you are running into while using the SDK, or are you doing an audit of the code?

**Comment by hacfi** [comment]
@jeremeamia I created (yet another) Symfony bundle for the SDK (see https://github.com/hacfi/aws-bundle) and spent several hours debugging the code to find new feature ideas (wouldn’t call that a proper audit). The main reason for creating this bundle was adding the option to specify a "default parameters file" so irrelevant (static) parameters don’t clutter the application code.

**Comment by jeremeamia** [comment]
Yeah, we'll address the issue. Thank you for bringing it to our attention.
