### ISSUE TITLE
Unused errorResponses from service description

### ISSUE THREAD

**Issue by hacfi** [aws/aws-sdk-php#546]
On master I noticed that the `errorResponses`  from the service description aren’t actually used. I think this is because the `Guzzle\Plugin\ErrorResponse\ErrorResponsePlugin` isn’t used and the Aws error handling doesn’t take the error responses into account. This is at least valid for the s3 service..haven’t checked the others.

**Comment by jeremeamia** [comment]
You are right, we don't use these. Error data is parsed from the response based on the service's over-the-wire format. See https://github.com/aws/aws-sdk-php/tree/master/src/Aws/Common/Exception/Parser. The lists of errorResponses in the service descriptions are not really significant.

**Comment by hacfi** [comment]
@jeremeamia Thanks for the clarification! I only noticed this because I tried using `errorResponses` to fix #545 and noticed it didn’t work.
