### ISSUE TITLE
Create TravisCI test matrix for v3 that uses Guzzle 5 and 6

### ISSUE THREAD

**Issue by mtdowling** [aws/aws-sdk-php#547]
We need to setup travis to somehow run our unit tests using Guzzle 5 and then Guzzle 6 for each supported PHP version.

**Comment by GrahamCampbell** [comment]
Can be done by just running `composer require` on travis, getting the version from an environment variable.

**Comment by mtdowling** [comment]
Ah, true. Good idea.

**Comment by GrahamCampbell** [comment]
We used to do this in flysystem to require deps for php that weren't installable on hhvm due to unmet extension requirements. :)
