### ISSUE TITLE
createSnapshot : "Name" option  | Feature Request

### ISSUE THREAD

**Issue by aobermueller** [aws/aws-sdk-php#553]
Right now you can just specify a description.  It would be great if you could also name the snapshot when creating.  

![ec2_snapshots](https://cloud.githubusercontent.com/assets/3652302/7320161/4ed9b708-ea60-11e4-9b6b-b5007010de60.PNG)

**Comment by mtdowling** [comment]
This parameter is not currently part of the API, so we can't do anything here client-side: http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateSnapshot.html.

We'll pass the feedback along, but the best place to currently leave feedback for a specific service is on the service's forum: https://forums.aws.amazon.com/forum.jspa?forumID=30.

**Comment by aobermueller** [comment]
Makes sense.  Thanks.
