### ISSUE TITLE
"EOF" error on kinesis PutRecord, only if request repeated every 6-7s

### ISSUE THREAD

**Issue by mateusz** [aws/aws-sdk-php#559]
I'm getting "EOF" errors (url.Error, Op=Post, URL=https://kinesis.ap-southeast-2.amazonaws.com/, Err="EOF") when doing repeated kinesis PutRecord requests. The data is not coming through.

This seems only to happen when I repeat the put requests every 6 or 7 seconds (with 7 seconds being more severe). I'm fairly certain it's not a throttling error (I'm the sole user of that stream, and I'm putting a single byte every 6-7 seconds). When I started handling this error and retrying these EOF requests, I never had to retry more than once.

I have distilled the code on my side to allow to reliably replicate this problem from an EC2 instance in us-west-1, putting into a stream in ap-southeast-2 (I have not experimented with other regions). The authentication is done through ~/.aws/credentials, but I have also used STS and temporary creds and the behaviour does not change.

This error does not seem to happen when I make put-record requests using the aws cli tool from a bash script from the same EC2 box. I'm out of ideas :-) Help?

```go
package main

import (
	"github.com/awslabs/aws-sdk-go/aws"
	"github.com/awslabs/aws-sdk-go/service/kinesis"
	"log"
	"time"
)

func main() {
	kinesisClient := kinesis.New(&aws.Config{
		Region: "ap-southeast-2",
	})

	for {
		_, err := kinesisClient.PutRecord(&kinesis.PutRecordInput{
			Data:         []byte("a"),
			PartitionKey: aws.String("1"),
			StreamName:   aws.String("some-stream"),
		})

		if err != nil {
			// Send has failed - drop the record and proceed.
			log.Printf("Sender failed to put record: %s, %v, %#v\n", err, err, err)
		} else {
			log.Printf("Sending successful.\n")
		}

		time.Sleep(6 * time.Second)
	}
}
```

**Comment by jeremeamia** [comment]
This is the issue tracker for the AWS SDK for PHP. Are you looking for the [Go SDK](https://github.com/awslabs/aws-sdk-go/issues)?

**Comment by mateusz** [comment]
LOL :-) Thanks!
