### ISSUE TITLE
Unable to set expires in URLs when altering an S3 command

### ISSUE THREAD

**Issue by deviantintegral** [aws/aws-sdk-php#560]
I have the following setup in the 2.x SDK, but it looks to be an issue in the v3 branch as well.

When we create an S3 client, we replace the command factory with one that lets developers alter command arguments before the command is returned. This works really well for anything that lives in the command arguments - but it <a href="https://github.com/aws/aws-sdk-php/blob/v3/src/S3/S3Client.php#L216">breaks when generating URLs</a>. For example, a developer might alter a command based on the bucket and key to set a response-cache-control parameter. However, that will break unless the caller to getObjectUrl() is already signing the request, which we can't know or change from within the command object.

I see two ways forward with this:

1. Add a 'ObjectUrlExpires' key to the command arguments, defaulting to whatever $expires is.
1. In getObjectUrl(), check $args for any arguments that require a presigned request, and automatically set $expires to something safe like 30 days.

Thoughts?

**Comment by mtdowling** [comment]
I'm having a hard time conceptualizing the problem. Can you provide an example of the problem?

**Comment by deviantintegral** [comment]
Lets see if this clears things up.

1. [When we construct an S3 client](https://github.com/justafish/drupal_amazons3/pull/10/files#diff-cbdb14e7ec3ff06696c5a111ec3b3580L39), we use setCommandFactory() to use our own CompositeFactory instead.
1. [We override factory()](https://github.com/justafish/drupal_amazons3/pull/10/files#diff-d41227707cd49d252ff1fdfdbf44d9a3R15), so that we can call out to Drupal hooks (the module_invoke_all and drupal_alter()) before and after creating the command. It's a Drupalism for sure, but it's what Drupal 7 devs will expect when making small changes for actual site builds.
1. When we call S3Client::getObjectUrl(), our custom factory works fine, but it has no knowledge of the $expires parameter and can't pass one back.

And [here's a few very simple examples](https://github.com/justafish/drupal_amazons3/pull/10/files#diff-21779b3b7b2760b74b89f0add07b2800L15) we'll be shipping with our docs of where we've seen this functionality used on existing sites with the old module / SDK.

The nice thing about this new implementation is that it works for any S3 command that is created, and gives developers direct access to the command object if they need it. We could add additional Drupal hooks to wrap around calling getObjectUrl(), but that won't work if anyone wants to use the SDK directly. I could also subclass S3Client, but I ran into relative directory issues with includes when I subclassed into a different namespace.

**Comment by mtdowling** [comment]
Ok, so you are using a custom command factory that add parameters to the command when it's created.

> For example, a developer might alter a command based on the bucket and key to set a response-cache-control parameter. However, that will break unless the caller to getObjectUrl() is already signing the request, which we can't know or change from within the command object.

Why would your command factory or the getObjectUrl() method need to know about each other? If you are just adding custom parameters to the command (i.e., `ResponseCacheControl`), then those custom parameters should be signed when calling `getObjectUrl()`.

> Add a 'ObjectUrlExpires' key to the command arguments, defaulting to whatever $expires is.

I don't think we'll do this because `ObjectUrlExpires` is not related to an API operation, but rather to a specific serialization format for a command (e.g., a signed URL). The expiration of a signed URL is provided using an argument to `getObjectUrl()`.

> In getObjectUrl(), check $args for any arguments that require a presigned request, and automatically set $expires to something safe like 30 days.

`getObjectUrl` does not always sign the URL it creates. It only signs the URL if you provide an `$expires` argument. Otherwise, it just serializes the request.

**Comment by deviantintegral** [comment]
Another way to think of this is that it's possible to send invalid arguments to getObjectUrl() and get a broken URL back. If I add ResponseCacheControl to $args, the only way I know I need to set $expires to a non-zero value is from the API docs.

Perhaps this isn't really about the command factory, but the returned request from prepare(). That object can cause a URL to be *required* to be presigned to be functional, but those query params are ignored.

I'm going to do a PR to unblock some of my other work; hopefully that will make things clearer.

**Comment by mtdowling** [comment]
Ok, I see what you are saying now. If we start signing `getObjectUrl` calls in certain cases, then it doesn't adhere to the same interface that is described in the docblock:

```
Returns the URL to an object identified by its bucket and key. If an expiration time is provided, the URL will be signed and set to expire at the provided time.
```

If we were to make a change, then I would rather throw an exception when no `$expires` is provided and an option is set that would require the URL to be signed.

**Comment by deviantintegral** [comment]
That works, and for now I can manage the small patch to do what we need on the Drupal side.

On the v3 branch I think I can use event emitters in Guzzle instead, avoiding the AWS sdk component entirely.

**Comment by mtdowling** [comment]
With v3, we've actually separated the SDK from Guzzle such that Guzzle is just one of (and the default) HTTP adapters you can plug into the SDK. The extension mechanism in v3 is the middleware system (e.g., https://github.com/aws/aws-sdk-php/blob/v3/src/Middleware.php). I'll hopefully get to write some docs for the middleware system in the next few days.

**Comment by mtdowling** [comment]
The fix here will be documentation added to the `getObjectUrl()` method. I've added information that the URL may not be valid in all cases, and that if you need to use parameters that require a signature, then you need to either provide an expires argument or sign the URL in some other manner (e.g., passing it to a signature object). If we started throwing an exception now, then it could potentially be a breaking change for users who might be signing the URL outside of this method.
