### ISSUE TITLE
InvalidArgumentException with message 'Invalid resource type' on DynamoDb putItem.

### ISSUE THREAD

**Issue by grepollo** [aws/aws-sdk-php#574]
Hi, 

I dont know if it is an issue you can just close this one if not.

I'm having issue on inserting a data on dynamodb with Simplified Chinese character on it. 
I always end up on that 'Invalid resource type' exception on Guzzle see error log below: 

'Guzzle\Common\Exception\InvalidArgumentException' with message 'Invalid resource type' in /var/www/html/project/api/vendor/guzzle/guzzle/src/Guzzle/Http/EntityBody.php:50

	Stack trace:
	#0 /var/www/html/project/api/vendor/guzzle/guzzle/src/Guzzle/Http/Message/EntityEnclosingRequest.php(59): Guzzle\Http\EntityBody::factory(false)
	#1 /var/www/html/project/api/vendor/guzzle/guzzle/src/Guzzle/Service/Command/LocationVisitor/Request/JsonVisitor.php(59): Guzzle\Http\Message\EntityEnclosingRequest->setBody(false)
	#2 /var/www/html/project/api/vendor/guzzle/guzzle/src/Guzzle/Service/Command/DefaultRequestSerializer.php(93): Guzzle\Service\Command\LocationVisitor\Request\JsonVisitor->after(Object(Aws\DynamoDb\DynamoDbCommand), Object(Guzzle\Http\Message\EntityEnclosingRequest))
	#3 /var/www/html/project/api/vendor/guzzle/guzzle/src/Guzzle/Service/Command/OperationCommand.php(79): Guzzle\Service\Command\DefaultRequestSerializer->prepare(Object(Aws\DynamoDb\DynamoDbCommand))
	#4 /var/www/html/project/api/vendor/aws/aws-sdk-php/src/Aws/Common/Command/JsonCommand.php(32): Guzzle\Service\Command\OperationCommand->build()
	#5 /var/www/html/project/api/vendor/aws/aws-sdk-php/src/Aws/DynamoDb/DynamoDbCommand.php(22): Aws\Common\Command\JsonCommand->build()
	#6 /var/www/html/project/api/vendor/guzzle/guzzle/src/Guzzle/Service/Command/AbstractCommand.php(238): Aws\DynamoDb\DynamoDbCommand->build()
	#7 /var/www/html/project/api/vendor/guzzle/guzzle/src/Guzzle/Service/Client.php(205): Guzzle\Service\Command\AbstractCommand->prepare()
	#8 /var/www/html/project/api/vendor/guzzle/guzzle/src/Guzzle/Service/Client.php(136): Guzzle\Service\Client->prepareCommand(Object(Aws\DynamoDb\DynamoDbCommand))
	#9 /var/www/html/project/api/vendor/guzzle/guzzle/src/Guzzle/Service/Command/AbstractCommand.php(153): Guzzle\Service\Client->execute(Object(Aws\DynamoDb\DynamoDbCommand))
	#10 /var/www/html/project/api/vendor/guzzle/guzzle/src/Guzzle/Service/Command/AbstractCommand.php(189): Guzzle\Service\Command\AbstractCommand->execute()
	#11 /var/www/html/project/api/vendor/guzzle/guzzle/src/Guzzle/Service/Client.php(76): Guzzle\Service\Command\AbstractCommand->getResult()
	#12 /var/www/html/project/api/vendor/aws/aws-sdk-php/src/Aws/Common/Client/AbstractClient.php(104): Guzzle\Service\Client->__call('PutItem', Array)

Thanks.

**Comment by mtdowling** [comment]
Can you provide a snippet of code that we can use to reproduce this issue?

**Comment by grepollo** [comment]
Hi, 

The scenario is I can save the data with Chinese character, then when I get that data and use putItem to another Table the issue will occur, I already found some way around, it has something to do with character encoding. 

So what I did is convert to utf8 the text first before saving it to the table and it seems working. 

Do you have better suggestion on how to do it? Or is there an option in getItem to set it to utf8 character encoding always? 

Thanks.

**Comment by mtdowling** [comment]
Ah, yes that makes sense. The SDK uses JSON for DynamoDB. The json_encode function requires that the data provided is UTF-8 encoded, so it makes sense to UTF-8 encode strings when necessary.
