### ISSUE TITLE
S3 putObject 

### ISSUE THREAD

**Issue by benmadin** [aws/aws-sdk-php#577]
Since a composer update last night, I have been unable to upload files to s3 using the putObject command. 

I am using Yii2, and looking through the debug log, I find that the correct parameters seem to be getting to guzzle:

```
GuzzleHttp\Command\AbstractClient::__call('putObject', [['Bucket' => 'files.ausvet.com.au', 'Key' => 'publications/5e5NMJOH0Txu-Er1Wh_...', 'SourceFile' => '/tmp/phphZ9Uyv', 'ContentDisposition' => 'attachment; filename=Publication...', ...]])
```

but - the reported error is:
```
Aws\S3\Exception\S3Exception

Error executing Aws\S3\S3Client::putObject() on "https://s3-ap-southeast-2.amazonaws.com/%7BBucket%7D/%7BKey%2B%7D"; NoSuchBucket (client error): The specified bucket does not exist
↵
Caused by: GuzzleHttp\Exception\ClientException

Client error response [url] https://s3-ap-southeast-2.amazonaws.com/%7BBucket%7D/%7BKey%2B%7D [status code] 404 [reason phrase] Not Found

in /Library/WebServer/Documents/ausvet/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php at line 89
```

I'm not sure about this bit 
```
[url] https://s3-ap-southeast-2.amazonaws.com/%7BBucket%7D/%7BKey%2B%7D [status code] 404
```

should not the bucket [url] be 

```
https://s3-ap-southeast-2.amazonaws.com/files.ausvet.com.au/publications/5e5NMJOH0Txu-Er1Wh_...
```

or is it only giving me general feedback?

PS Although it is a 404, I tested and command line upload works from the same instance.

cheers

Ben

**Comment by mtdowling** [comment]
Can you provide the output of `composer.phar show -i`? It looks like you're using a really old version of SDK v3.

**Comment by benmadin** [comment]
Hi Michael,

$ composer show -i
aws/aws-sdk-php                         3.0.0-beta.1 AWS SDK for PHP - Use Amazon Web Services in your PHP project
bower-asset/bootstrap                   v3.3.4       The most popular front-end framework for developing responsive, m...
bower-asset/jquery                      2.1.4        
bower-asset/jquery-ui                   1.11.4       
bower-asset/jquery.inputmask            3.1.63       jquery.inputmask is a jquery plugin which create an input mask.
bower-asset/punycode                    v1.3.2       
bower-asset/typeahead.js                v0.10.5      
bower-asset/yii2-pjax                   v2.0.4       
cebe/markdown                           1.1.0        A super fast, highly extensible markdown parser for PHP
ezyang/htmlpurifier                     v4.6.0       Standards compliant HTML filter written in PHP
fzaninotto/faker                        v1.4.0       Faker is a PHP library that generates fake data for you.
guzzlehttp/command                      0.7.0        Provides the foundation for building command based web service cl...
guzzlehttp/guzzle                       5.2.0        Guzzle is a PHP HTTP client library and framework for building RE...
guzzlehttp/log-subscriber               1.0.1        Logs HTTP requests and responses as they are sent over the wire (...
guzzlehttp/message-integrity-subscriber 0.2.0        Verifies the integrity of HTTP responses using customizable valid...
guzzlehttp/retry-subscriber             2.0.0        Retries failed HTTP requests using customizable retry strategies ...
guzzlehttp/ringphp                      1.0.7        Provides a simple API and specification that abstracts away the d...
guzzlehttp/streams                      3.0.0        Provides a simple abstraction over streams of data
kartik-v/yii2-krajee-base               v1.7.6       Base library and foundation components for all Yii2 Krajee extens...
kartik-v/yii2-widget-select2            v2.0.0       Enhanced Yii2 wrapper for the Select2 jQuery plugin (sub repo spl...
mtdowling/jmespath.php                  1.1.1        Declaratively specify how to extract elements from a JSON document
phpspec/php-diff                        v1.0.2       A comprehensive library for generating differences between two ha...
psr/log                                 1.0.0        Common interface for logging libraries
react/promise                           v2.2.0       A lightweight implementation of CommonJS Promises/A for PHP
swiftmailer/swiftmailer                 v5.4.0       Swiftmailer, free feature-rich PHP mailer
yiisoft/yii2                            2.0.4        Yii PHP Framework Version 2
yiisoft/yii2-bootstrap                  2.0.4        The Twitter Bootstrap extension for the Yii framework
yiisoft/yii2-codeception                2.0.4        The Codeception integration for the Yii framework
yiisoft/yii2-composer                   2.0.3        The composer plugin for Yii extension installer
yiisoft/yii2-debug                      2.0.4        The debugger extension for the Yii framework
yiisoft/yii2-faker                      2.0.3        Fixture generator. The Faker integration for the Yii framework.
yiisoft/yii2-gii                        2.0.3        The Gii extension for the Yii framework
yiisoft/yii2-jui                        2.0.4        The Jquery UI extension for the Yii framework
yiisoft/yii2-swiftmailer                2.0.4        The SwiftMailer integration for the Yii framework


and the composer.json file has:

        "aws/aws-sdk-php": "3.x@dev"

cheers

Ben

**Comment by mtdowling** [comment]
@GrahamCampbell Do you know how to install the SDK v3 using the latest commit on GitHub? using `3.*@dev` is always pulling in the 3.0-beta.1 tag.

@benmadin In the meantime, you will need to set `"minimum-stability": "dev"` in your composer.json. That said, we are shipping a stable v3 release next week.

**Comment by mtdowling** [comment]
I'm going to close this as there is a workaround, and we're shipping a stable release next week.

Sorry for the inconvenience.

**Comment by benmadin** [comment]
Thanks Michael,

Confusing... If I set it on the entire composer, I have three other packages that won't load. but if I put the git commit on the sdk only, it won't pull it. 

I'll try a git pull instead.

cheers

Ben

**Comment by mtdowling** [comment]
I may have cleared up other issues earlier today. I'm tagging the psr7 package tomorrow which may also make the min stability setting unnecessary.

**Comment by benmadin** [comment]
Okidoki - I'll leave it for now, I tried pulling the v3 branch straight into the vendor directory in my project, but I seem to be having some sort of problem with loading a function from the \Aws space:

```php
 public static function defaultProvider()
    {
        $data = \Aws\load_compiled_json(__DIR__ . '/../data/endpoints.json');
 
        return new PatternEndpointProvider($data['endpoints']);
    }
```

is throwing `Call to undefined function Aws\load_compiled_json()` 

so I'll wait. Thanks for that!

do I continue to use "3.x@dev" in composer?
