### ISSUE TITLE
PostObject class - AWS4-HMAC-SHA256 - signature 4 support

### ISSUE THREAD

**Issue by berlindev** [aws/aws-sdk-php#586]
Looks like the PostObject S3 class uses the old signatue version 2 to sign.
This is not compatible with the new eu-central-1 region which only supports signature version 4.

The returned error is
"The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256."

**Comment by mtdowling** [comment]
Thanks for opening this issue. We will add this to our backlog for both v2 and v3.

**Comment by jeremeamia** [comment]
Tracking this internally now.
