### ISSUE TITLE
getimagesize() fails when seeking is required

### ISSUE THREAD

**Issue by deviantintegral** [aws/aws-sdk-php#587]
<a href="https://php.net/getimagesize">`getimagesize()`</a> is a GD function to return metadata for an image. If it seeks on an S3 stream, it fails for two reasons:

1. The function takes a URI, so we can't pass in any stream context options. The extension code is assuming that seeking is available, but the <a href="https://php.net/manual/en/streamwrapper.stream-seek.php">StreamWrapper docs explicitly state that seeking is not required to be supported</a>.
1. If we force seeking to be enabled in the stream wrapper, `getimagesize()` still fails because it seeks without first reading the stream. <a href="https://guzzle3.readthedocs.org/http-client/entity-bodies.html">CachingEntityBody documents that it can only seek on read bytes</a>, but this is an implementation detail we can't expect calling code to be aware of.

I can get a successful image size call if I hack in a few stream_read() calls inside of stream_seek(). Strangely, $length always seems to be in 8K segments even when I pass in another value, but I haven't dug any deeper.

I haven't isolated exactly where seeking becomes required, if it's based off of the internal JPEG structure or if it's simply due to file size. I could see this breaking for other image formats if they store metadata at the end of a large file.

At this point, this looks like two bugs to me - one in GD for not handling unseekable streams and falling back to loading the whole file into memory, and one in the SDK to handle calls to seek without previous reads.

**Comment by deviantintegral** [comment]
Turns out this is triggered by some subset of EXIF info. When the <a href="https://github.com/php/php-src/blob/php-5.5.9/ext/standard/image.c#L535">M_APP15</a> JPEG marker is found, php_skip_variable() calls _php_stream_seek(). I was just able to trigger this issue with an 85KB image, while a 6MB image with no EXIF data works fine. It's not just "having EXIF" either - images from my Nexus 5 work fine, but images from my standalone camera fail.

**Comment by mtdowling** [comment]
> The function takes a URI, so we can't pass in any stream context options. The extension code is assuming that seeking is available, but the StreamWrapper docs explicitly state that seeking is not required to be supported.

There's nothing we can do here in the SDK, but you could use the default stream options features from PHP to work around this: http://php.net/manual/en/function.stream-context-set-default.php

> If we force seeking to be enabled in the stream wrapper, getimagesize() still fails because it seeks without first reading the stream. CachingEntityBody documents that it can only seek on read bytes, but this is an implementation detail we can't expect calling code to be aware of.

The only solution I can think of for this would be to load the entire response body into memory if "seekable" is set to true. That would be a breaking change IMO for the v2 of the SDK, but it could be a change that we make before shipping the v3 that is going out next week.

**Comment by deviantintegral** [comment]
I've filed an upstream report over at https://bugs.php.net/bug.php?id=69706

I'd be concerned about the memory load if someone tries to seek on a large file like a video asset. Would it be better to back the response body on disk instead?

**Comment by mtdowling** [comment]
I've pushed a fix for CachingStream that allows forward seeking. This should take care of your second issue when working with V3. As the other issue is something that can only be fixed in PHP itself, I'll close this issue. See https://github.com/guzzle/psr7/pull/23
