### ISSUE TITLE
Dynamodb / putItem and updateItem failing with GnuTLS/2.12.14

### ISSUE THREAD

**Issue by shadiakiki1986** [aws/aws-sdk-php#588]
Hi. I've been having trouble with dynamodb php sdk usage passing on travis-ci, so I set up a git [project](https://github.com/shadiakiki1986/just-want-to-pass-dynamodb-travisci) specifically for this.

The project only has 3 tests:
* one for getItem
* one for updateItem
* one for putItem

The problem is that my ***putItem*** and ***updateItem*** phpunit tests pass on a machine where php curl uses "OpenSSL/1.0.1f" but fail on the [travis-ci](https://travis-ci.org/shadiakiki1986/just-want-to-pass-dynamodb-travisci/builds) workers that have php curl using "GnuTLS/2.12.14". 

Note that sometimes retrying the same build alternates between a pass and a fail at random, 
e.g. [build 33](https://travis-ci.org/shadiakiki1986/just-want-to-pass-dynamodb-travisci/builds/63951116)
* This build only runs the tests for getItem and updateItem
* [This](https://s3-us-west-2.amazonaws.com/zboota-server/j2p_issue/j2p_build33_pass.txt) is an example log of build 33 showing it passing, and [here](https://s3-us-west-2.amazonaws.com/zboota-server/j2p_issue/j2p_build33_fail.txt) is one showing it failing
 * both logs include output from ```var_dump(curl_version())```

Retries of a build whose test includes putItem exhibits the same behavior of failing sometimes and passing at other times.

I tried different combinations to get around the problem, but in vain, probably because I'm not well versed in this. This is sort of like taking a shot in the dark for me.
* I tried to use php version 5.4 hoping that it would be compiled to use openssl, but it also used gnutls
* setting in php curlopt_verifyhost and verifypeer to false
* curlopt sslversion to sslv3 
* using the [ssh_known_hosts](http://docs.travis-ci.com/user/ssh-known-hosts/) addon in the travis yml file to add 
* installing libssl1.0.0 
* upgrading curl from ~~1.22~~ 7.22 to ~~1.36~~ 7.36 using the [package whitelist](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise), but I think the fact that the VMs run Ubuntu 12.04 left curl at ~~1.22~~ 7.22
 * anyway, I tested that curl ~~1.22~~ 7.22 with Openssl works with dynamodb putItem, so the problem really is openssl versus gnutls and not the curl library itself

I'm not sure what to make of all this. I'd like to have my phpunit tests pass on travis-ci without having to build php to use openssl

**Comment by mtdowling** [comment]
This could be related to this issue in cURL that I believe was fixed in 7.28: https://github.com/bagder/curl/commit/ee3551e45e60856eb0b779aa6cd34d77f16208a5

Have you tried updating your version of cURL during the travis setup to be >= 7.28? I noticed the output in your travis build was 7.22: https://travis-ci.org/shadiakiki1986/just-want-to-pass-dynamodb-travisci/builds/63951116#L316

> upgrading curl from 1.22 to 1.36 using the package whitelist, but I think the fact that the VMs run Ubuntu 12.04 left curl at 1.22

Is this some kind of version indirection? cURL is at 7.42.1.

**Comment by shadiakiki1986** [comment]
Hi Michael. Thanks for your feedback.
My bad, I meant 7.22 and 7.36 instead of 1.22 and 1.36.
The tests pass on my machine with cURL 7.22, which is why I didn't try updating cURL during the travis setup to be >= 7.28. The difference between my machine and the travis machine is that the travis worker is using gnutls, as you can see [here](https://travis-ci.org/shadiakiki1986/just-want-to-pass-dynamodb-travisci/builds/63951116#L203) whereas my machine is using OpenSSL/1.0.1.

I really think that this is a matter of php compiled with gnutls (doesn't work) versus openssl (works). It seems to me that since the AWS dynamodb connection falls back to a different server IP with each connection (54.239.20.120 [here](https://travis-ci.org/shadiakiki1986/just-want-to-pass-dynamodb-travisci/builds/63951116#L136) in build 33, 176.32.101.251 [here](https://travis-ci.org/shadiakiki1986/just-want-to-pass-dynamodb-travisci/builds/63958128#L176) in build 34), some of the AWS dynamodb servers are setup to allow the connection to go through, and some others not. For example, I just repeated build 34 a few times. The first couple of times both the testUpdateItem and testPutItem were failing. In the [last time](https://travis-ci.org/shadiakiki1986/just-want-to-pass-dynamodb-travisci/builds/63958128), the testUpdateItem passed and only the testPutItem failed. What's special about 176.32.101.251 versus 54.239.20.120 so that the former would pass for the updateItem test?

PS: I have yet to try to compile php with openssl on the travis worker and show that the tests pass, but I think that would require sudo. I've been avoiding using sudo so as not to have to wait long between builds, as described [here](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/)

**Comment by mtdowling** [comment]
I wasn't sure based on your last response, but just to be clear: have you tried updating cURL to >= 7.28 on Travis? The reason I ask is because it looks like the commit I linked to specifically fixes the problem you are encountering with gnutls and cURL.

> I really think that this is a matter of php compiled with gnutls (doesn't work) versus openssl (works).

I think it will work if you upgrade to cURL >= 7.28. I'll try this out myself as well.

**Comment by shadiakiki1986** [comment]
No I didn't. Let me try and get back to you

**Comment by shadiakiki1986** [comment]
So I installed curl 7.35. Still, [some builds](https://travis-ci.org/shadiakiki1986/just-want-to-pass-dynamodb-travisci/builds/64708348) are passing and [other builds](https://travis-ci.org/shadiakiki1986/just-want-to-pass-dynamodb-travisci/builds/64708619) are not, but now instead of getting the error message "gnutls fatal error", I get '''illegal parameter url''' ([ref line](https://travis-ci.org/shadiakiki1986/just-want-to-pass-dynamodb-travisci/builds/64708619#L1130)). I read somewhere that it's because I'm using gnutls 2.* ([ref line](https://travis-ci.org/shadiakiki1986/just-want-to-pass-dynamodb-travisci/builds/64708619#L1078) ), so I tried to upgrade gnutls to 3.1.28 by compiling from source, but I failed at making this work. With apt-get I managed to upgrade gnutls from '''2.12.14''' to '''2.12.23'''. Here is the [log file](https://s3.amazonaws.com/archive.travis-ci.org/jobs/64715372/log.txt). You can see this by searching for the text "2.12.23" (sorry, no direct link to the line because the log file is too long to be displayed in travis-ci). But since I need to go up to gnutls 3.*, I compiled it from source. If you search for "pkg-config --modversion gnutls", you can see that the library is being installed as 3.1.28, but the '''curl_version''' still gives ssl_version being "GnuTLS/2.12.23" after the install. So my problem now is getting php to use the gnutls I compiled. I launched a [separate project](https://travis-ci.org/shadiakiki1986/gnutls-3.1-travisci/) to focus on the php-gnutls issue, which would help solve this issue here. I'll post to the gnutls mailing list to ask for some help

**Comment by shadiakiki1986** [comment]
I compiled curl 7.42.1 with gnutls 3.1.28 from source. On a vanilla ubuntu 12.04 installation, php automatically links to the newly compiled libraries and my phpunit tests to dynamodb pass without any gnutls fatal errors. However, I couldn't get php on the travis-ci worker (which uses ubuntu 12.04 and phpenv) to link to my newly compiled libraries, so my same code with the same phpunit tests fail on travis-ci. My log file on [line 2327](https://travis-ci.org/shadiakiki1986/gnutls-3.1-travisci/builds/65896199#L2327) shows php using gnutls 2.12. Line [2371](https://travis-ci.org/shadiakiki1986/gnutls-3.1-travisci/builds/65896199#L2371) shows that gnutls 3.1.28 is correctly installed. Line [2384](https://travis-ci.org/shadiakiki1986/gnutls-3.1-travisci/builds/65896199#L2384) shows the library that I suspect is keeping php from using my compiled version. Any thoughts on this? I feel that I'm stuck on something that will turn out to be fundamentally silly

**Comment by shadiakiki1986** [comment]
I just managed to pass the project on travis-ci. The problem was the php from phpenv. Once I installed php5-cli and specified /usr/bin/php5 to be used in the .travis.yml file, I managed to use my compiled gnutls and curl. More on this later

**Comment by shadiakiki1986** [comment]
I pretty much have nothing to add to this. [Here](https://travis-ci.org/shadiakiki1986/just-want-to-pass-dynamodb-travisci/builds/66033147)'s the build that passes. I'm closing this issue as I'm content with my workaround of installing a separate CLI for php and using that.
