### ISSUE TITLE
Error in S3 Transfer documentation

### ISSUE THREAD

**Issue by vuchl** [aws/aws-sdk-php#596]
I just read through a couple of things and noticed this section: http://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-transfer.html#async-transfers

The code example is incomplete:
```php
$source = '/path/to/source/files';
$dest = 's3://bucket';
$manager = new \Aws\S3\Transfer($client, $source, $dest);

// Initiate the transfer and get a promise.
$promise = $transfer->promise();

// Do something when the transfer is complete using the then() method.
$promise->then(function () {
    echo 'Done!';
});
```
There is no ```$transfer``` object but it gets used. The little heading states:
>The ```Transfer``` object is an instance of ```GuzzleHttp\Promise\PromisorInterface```, which means that the transfer can occur asynchronously and is initiated by calling the ```promise``` method of the object.

I have no time to look at the code right now but I get from the other examples it should something like this maybe:
```php
$source = '/path/to/source/files';
$dest = 's3://bucket';
$transfer = new \Aws\S3\Transfer($client, $source, $dest);

// Initiate the transfer and get a promise.
$promise = $transfer->promise();

// Do something when the transfer is complete using the then() method.
$promise->then(function () {
    echo 'Done!';
});

**Comment by mtdowling** [comment]
Thanks for the issue report. The `$transfer` object just needs to be renamed to `$manager`. We'll make the change.

**Comment by vuchl** [comment]
Yepp, that's what I thought.
