### ISSUE TITLE
CloudFront - getSignedURL with blank space in filename?

### ISSUE THREAD

**Issue by DrySs** [aws/aws-sdk-php#597]
Hi there,

I cannot use getSignedURL of CloudFront SDK when a filename has special characters inside, like blank space.

For example, with following request:

$args = array(
    'url'  => 'https://mycloudfront.net/my file name.mp4',
    'expires' => (time() + 3600)
);
return $cdn->getSignedUrl($args);

=> https://mycloudfront.net/my%20file%20name.mp4?Expires=1432815339&Signature=xXxXx&Key-Pair-Id=xXxxXx

Results an 403 error.

Same request with a filename without any blank space works:

$args = array(
    'url'  => 'https://mycloudfront.net/my_file_name.mp4',
    'expires' => (time() + 3600)
);
return $cdn->getSignedUrl($args);

=> https://mycloudfront.net/my_file_name.mp4?Expires=1432815339&Signature=xXxXx&Key-Pair-Id=xXxxXx

Is it possible to use CloudFront with blank space in filename or other special chars?

Thanks for helping,
Philippe

**Comment by mtdowling** [comment]
Which version of the SDK are you using? Have you tried percent encoding special characters like ' ' with '%20'?

**Comment by DrySs** [comment]
Hi @mtdowling :)

You're right, using urlencode before sending string to getSignedUrl make it works!

Thanks :)
