### ISSUE TITLE
When using SesClient it try to locate this file which is missing

### ISSUE THREAD

**Issue by wisoot** [aws/aws-sdk-php#599]
aws/aws-sdk-php/src/Api/../data/ses/2010-12-01/api-2.json

In fact the whole ses folder went missing. Is that needed? or did I miss something.

**Comment by jeremeamia** [comment]
Latest stable version of the SDK has the file here: https://github.com/aws/aws-sdk-php/tree/master/src/data/email/2010-12-01

However, depending on how you are instantiating the SesClient, you might be hitting a bug, that I just fixed here: https://github.com/aws/aws-sdk-php/commit/c66b1cfa66feee34cc589a8c4583691b14f89c28

**Comment by jeremeamia** [comment]
This fix is included in [v3.0.2](https://github.com/aws/aws-sdk-php/releases/tag/3.0.2).
