### ISSUE TITLE
[DOCS:v3] key and secret options (outside credentials array) not supported.

### ISSUE THREAD

**Issue by frankdejonge** [aws/aws-sdk-php#600]
The docs say supplying the key and secret are deprecated, while when supplying them it'll result in an error. The deprecation suggests it's not advised but still "supported" and will be removed later on, while it seems it's already removed now.

Docs reference: http://docs.aws.amazon.com/aws-sdk-php/guide/latest/configuration.html

**Comment by jeremeamia** [comment]
Those are the V2 docs, but they still need to be updated. Here's the [V3 User Guide](http://docs.aws.amazon.com/aws-sdk-php/v3/guide).

**Comment by jeremeamia** [comment]
Fixed by e9b8623c1e23f533d969ef2269a043f7d4838e18

**Comment by frankdejonge** [comment]
:+1:
