### ISSUE TITLE
Network interfaces and an instance-level security groups may not be specified on the same request

### ISSUE THREAD

**Issue by PSiAU** [aws/aws-sdk-php#601]
When attempting to launch an instance in a VPC with a public IP address, the following error is thrown:

"Network interfaces and an instance-level security groups may not be specified on the same request"

The code i'm launching it with:
```
$response = $ec2Client->runInstances([
	'ImageId' => 'ami-fd9cecc7',
	'MinCount' => '1',
	'MaxCount' => '1',
	'InstanceType' => 'c4.xlarge',
	'KeyName' => 'mykey',
	'NetworkInterfaces' => [[
		'DeviceIndex' => 0,
		'SubnetId' => 'subnet-xxxxxxxx',
		'AssociatePublicIpAddress' => true
	]],
	'SecurityGroupIds' => ['sg-xxxxxxxx','sg-xxxxxxxx'],
]);
```

I'm able to do the same through the AWS CLI with no problems.

**Comment by mtdowling** [comment]
Which version of the SDK are you using? Can you provide the equivalent CLI command you used that worked?

**Comment by PSiAU** [comment]
I'm using 3.0.1.

Here's the equivalent CLI command:

```
aws --profile myprofile ec2 run-instances --image-id ami-fd9cecc7 --count 1 --instance-type c4.xlarge --key-name mykey --security-group-ids sg-xxxxxxxx sg-xxxxxxxx --subnet-id subnet-xxxxxxxx --associate-public-ip-address
```

**Comment by PSiAU** [comment]
I found the problem. The documentation states that AssociatePublicIpAddress goes under NetworkInterfaces, but in actual fact it needs to be above that. In fact both SubnetId and AssociatePublicIpAddress both need to be specified at that level.
http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-ec2-2015-04-15.html#runinstances

This works:
```
$response = $ec2Client->runInstances([
	'ImageId' => 'ami-fd9cecc7',
	'MinCount' => '1',
	'MaxCount' => '1',
	'InstanceType' => 'c4.xlarge',
	'KeyName' => 'mykey',
	'SubnetId' => 'subnet-xxxxxxxx',
	'AssociatePublicIpAddress' => true,
	'SecurityGroupIds' => ['sg-xxxxxxxx','sg-xxxxxxxx'],
]);
```
No need to use NetworkInterfaces as the document suggests.
How do I log a bug against the doco?

**Comment by PSiAU** [comment]
Got it.
I should have been doing this instead:
```
$response = $ec2Client->runInstances([
	'ImageId' => 'ami-fd9cecc7',
	'InstanceType' => 'c4.xlarge',
	'KeyName' => 'mykey',
	'MaxCount' => '1',
	'MinCount' => '1',
	'NetworkInterfaces' => [[
		'DeviceIndex' => 0,
		'SubnetId' => 'subnet-xxxxxxxx',
		'AssociatePublicIpAddress' => true,
		'Groups' => ['sg-xxxxxxxx','sg-xxxxxxxx'],
	]],
]);
```
The security groups should be specified under NetworkInterfaces using "Groups".
