### ISSUE TITLE
getObjectUrl doesn't return a singed URL

### ISSUE THREAD

**Issue by sinky** [aws/aws-sdk-php#603]
Hi,
``getObjectUrl`` returns only plain urls, without querystring.

```
require 'vendor/autoload.php';

$bucket = 'mybucket';

use Aws\S3\S3Client;

$client = S3Client::factory([
    'version' => 'latest',
    'region'  => 'eu-central-1',
    //'signature'    => 'v4',
    'credentials' => [
        'key'    => 'xxxx',
        'secret' => 'xxxx'
    ]
]);

$plainUrl = $client->getObjectUrl($bucket, 'test.dat');
$signedUrl = $client->getObjectUrl($bucket, 'test.dat', '+10 minutes');
```
$plainUrl and $signedUrl have the same value. Like https://my-bucket.s3.amazonaws.com/test.dat

Using the current version, installed with
```
curl -sS https://getcomposer.org/installer | php
php composer.phar require aws/aws-sdk-php
```

**Comment by sinky** [comment]
Ahhhh,
``getObjectUrl`` no longer has a third parameter.
This Works:
```
$cmd = $client->getCommand('GetObject', [
    'Bucket' => $bucket,
    'Key'    => 'test1G.dat'
]);

$request = $client->createPresignedRequest($cmd, '+20 minutes');
$presignedUrl = (string) $request->getUri();
```

**Comment by haoxi911** [comment]
Hi @sinky,

I met exactly same issue when upgrade from sdk v2 to v3, and also, I realized that v2 API allows us to sign a URL with a maximum expiration date up to 80+ years, and I used such way to make a permanent link.

However, the v3 SDK only allows us to set expiration date up to 1 week, so I didn't see a workaround to create a permanent accessible signed URL.

Do you have any ideas? Note: I am able to configure the bucket policy to make it public read only, but want to know if there is another way.

Thanks,
Kevin
