### ISSUE TITLE
SHA256 client mismatch server when using s3:// resource

### ISSUE THREAD

**Issue by stuartcarnie** [aws/aws-sdk-php#604]
```php
$resource = fopen('s3://some/object', 'rb')
```

followed by

```php
$obj = [
    'ACL'    => 'public-read',
    'Body'   => $resource,
    'Key'    => '<key>',
    'Bucket' => '<bucket>',
];
$s3->putObject($obj);
```

Fails due to the client and server calculated SHA256 mismatching. When stepping through, the client does calculate the correct SHA256 when `\GuzzleHttp\Psr7\hash` is called, suggesting the data sent to the server is incorrect. I have not dug in to the stream wrappers, but I suspect an issue with the caching stream wrapper…

Worth noting that if I create a temporary stream via `fopen('php://temp)` and then `stream_copy_to_stream`, from the `$resource` to the temporary stream, the `putObject` call succeeds.

**Comment by mtdowling** [comment]
When executing commands with the SDK (v3), you can use the `debug` option to get a much more detailed view into what's going on. To enable debug mode, pass the `debug` option in to the client's constructor:

```php
$s3 = new Aws\S3\S3Client([
    'region' => 'my-region',
    'version' => '2006-03-01',
    'debug' => true
]);
```

Can you please run your test with debug mode enabled and post the debug output?

**Comment by stuartcarnie** [comment]
I added that, and received an error:

`fprintf(): 51 is not a valid stream resource` in `/var/www/develop/odin/core/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php:367`:

Which is [here](https://github.com/guzzle/guzzle/blob/6d2bab840c2e1fb0b6dd6ac9b72009c6b74ba36f/src/Handler/StreamHandler.php#L367)

**Comment by mtdowling** [comment]
I made several enhancements to the SDK based on this issue. Here's the related pull request: https://github.com/aws/aws-sdk-php/pull/605.

To solve your immediate issue, you will need to create a seekable stream with the PHP stream wrapper. This can be done through a stream context that sets `seekable` to true.

Here's a working example of how this would work (I also forced the use of the PHP stream wrapper as well in case you are using the stream wrapper as your client. Note that you could omit the `http_handler` option altogether and this will still work).

```php
<?php
require 'vendor/autoload.php';

$streamHandler = new \GuzzleHttp\Handler\StreamHandler();

$s3 = new \Aws\S3\S3Client([
    'region'  => 'us-east-1',
    'version' => 'latest',
    'debug'   => true,
    'http_handler' => $streamHandler
]);

$s3->registerStreamWrapper();
$context = stream_context_create(['s3' => ['seekable' => true]]);
$resource = fopen('s3://t1234/test', 'rb', null, $context);

if (!$resource) {
    die('Could not open s3 resource');
}

$s3->putObject([
    'Bucket' => 't1234',
    'Key'    => 'stream-test',
    'Body'   => $resource
]);
```

**Comment by stuartcarnie** [comment]
:+1:
