### ISSUE TITLE
s3 get , put , delete from folders withing bucket

### ISSUE THREAD

**Issue by nikunjtrapasiya** [aws/aws-sdk-php#608]
Hi Guys,

I have s3 bucket called say my-bucket and inside it i have folder called development which holds objects

I have changed the bucket name for questions.

I want to get object 1.txt which and I am using below code and it doesnt work. but if i copy the same object to my-bucket and run the same code than it works.
```
require 'vendor/autoload.php';
use Aws\S3\S3Client;
$sdk = new Aws\Sdk([
	'region'  => 'ap-southeast-2',
	'version'  => 'latest',
]);
$S3client = $sdk->createS3();
try {
	$result =$S3client->getObject([
		'Bucket' => 'my-bucket\development',
		'Key'    => 'test.txt',
]);
} catch (Aws\Exception\S3Exception $e) {
	echo "There was an error.\n";
}
```

can you please help and let me know what i am doing wrong to get the object from development folder? I am using latest 3.0.3 sdk and run the comparability test and it all went fine.

Before lunch today the below code was working and now it's not working as well and not cosidering KeyPrefix as well

```
try {
	$result =$S3client->getObject([
        	'Bucket' => 'my-bucket',
		'Key'    => 'test.txt',
		'KeyPrefix'    => 'development',

	]);
} catch (Aws\Exception\S3Exception $e) {
	echo "There was an error uploading the file.\n";
}
```

**Comment by jeremeamia** [comment]
Does this work?

```php
$result = $S3client->getObject([
    'Bucket' => 'my-bucket',
    'Key'    => 'development/d2f78c44-3206-4718-95d5-3c84f45b49c4.txt',
]);
```

Subfolders should be a part of the key, not the bucket.

**Comment by nikunjtrapasiya** [comment]
yup that work. But surprisingly the KeyPrefix code was working 2 hours ago and not any more.

I will try all the methods and report any issues.

**Comment by nikunjtrapasiya** [comment]
All the methods are working fine with above suggestion by @jeremeamia

**Comment by jeremeamia** [comment]
By the way, `KeyPrefix` is not a valid parameter. Make sure you are using the correct [API documentation](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html). I'm glad you have it working now. :smile:
