### ISSUE TITLE
Wrong path normalization in JsonCompiler.php 

### ISSUE THREAD

**Issue by smagnaschi** [aws/aws-sdk-php#610]
Hello all,
I think I've found a problem in the normalize function of JsonCompiler.php.
Whenever the path given to normalize is in the form of '\\xxx\sd' for example in a VirtualBox Windows Server + Apache + network shared folder, the normalize functions spits out a resolved pattern in the form of '\xxx\sd' which is wrong and this raises an InvalidArgumentException since PHP cannot locate the right files (manifest.json / endpoints.json) and so on.

**Comment by mtdowling** [comment]
The example you gave shows the same path for both the input and output. Can you provide an actual file path input that failed to load, what the compiler tried to load, and what it should have loaded? (This should all show up in a stack trace or warning)

**Comment by smagnaschi** [comment]
Sorry for being late.
The problem in the path was due to github textbox stripping slashes.
The problem happens when the path starts with a double slash \\\\ (a UNC path for example), this gets translated and normalized to a single slash \\ which breaks the path.
I've used the modified JsonCompiler class from your last commit but the problem remains.
Here is a stack trace


	<b>Fatal error</b>:  Uncaught exception 'InvalidArgumentException' with message 'File not found: \\SIMONE-PC\USERS\Simone\Documents\WebProjects\devel.rockol.it\app\vendor\aws\aws-sdk-php\src\Api/../data/manifest.json, realpath: /SIMONE-PC/USERS/Simone/Documents/WebProjects/devel.rockol.it/app/vendor/aws/aws-sdk-php/src/data/manifest.json' in \\SIMONE-PC\USERS\Simone\Documents\WebProjects\devel.rockol.it\app\vendor\aws\aws-sdk-php\src\JsonCompiler.php:151
	Stack trace:
	#0 \\SIMONE-PC\USERS\Simone\Documents\WebProjects\devel.rockol.it\app\vendor\aws\aws-sdk-php\src\JsonCompiler.php(79): Aws\JsonCompiler-&gt;loadJsonFromFile('\\\\SIMONE-PC\\USE...', '/SIMONE-PC/USER...')
	#1 \\SIMONE-PC\USERS\Simone\Documents\WebProjects\devel.rockol.it\app\vendor\aws\aws-sdk-php\src\functions.php(157): Aws\JsonCompiler-&gt;load('\\\\SIMONE-PC\\USE...')
	#2 \\SIMONE-PC\USERS\Simone\Documents\WebProjects\devel.rockol.it\app\vendor\aws\aws-sdk-php\src\Api\ApiProvider.php(96): Aws\load_compiled_json('\\\\SIMONE-PC\\USE...')
	#3 \\SIMONE-PC\USERS\Simone\Documents in <b>\\SIMONE-PC\USERS\Simone\Documents\WebProjects\devel.rockol.it\app\vendor\aws\aws-sdk-php\src\JsonCompiler.php</b> on line <b>151</b><br />

**Comment by mtdowling** [comment]
Ah I see thanks. This seems to be a very specific case -- I wonder if PHP's built-in realpath would support this type of path. I'll reopen the issue, and we'll see if there's a solution.

**Comment by smagnaschi** [comment]
I tried this and it seems to work ok for my case: https://github.com/aws/aws-sdk-php/pull/613
