### ISSUE TITLE
AWS HTTP error: Client error: 403 RequestTimeTooSkewed

### ISSUE THREAD

**Issue by mascreativa** [aws/aws-sdk-php#612]
Hello! ... How i can solve this problem?

My server time: 59America/SantiagoThu, 04 Jun 2015 19:25:59 -0400vAmerica/SantiagoThu, 04 Jun 2015 19:25:59 -0400

Fatal error: Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "PutObject" on "https://s3.amazonaws.com/backupebrain/my-backupfile"; AWS HTTP error: Client error: 403 RequestTimeTooSkewed (client): The difference between the request time and the current time is too large. - <?xml version="1.0" encoding="UTF-8"?> <Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the request time and the current time is too large.</Message><RequestTime>20150604T232559Z</RequestTime><ServerTime>2015-06-04T22:26:16Z</ServerTime><MaxAllowedSkewMilliseconds>900000</MaxAllowedSkewMilliseconds><RequestId>9E09E2E8D09D863C</RequestId><HostId>CQl85Ol1ejSfxwCFffw880W3OsDNI+FtTYPrQFjJVtM6vmd4pWJaOCuNEWtZPUfjhYRHByziBxg=</HostId></Error>' exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: 403' in /Users/juandonoso/Dropbox/Servidor/web/varios/aws/class.aws/GuzzleHttp/Middleware.php:68 Stack trace: #0 /Users/juandonoso/Dropbox/Servidor/web/varios/aws/class.aws/GuzzleHttp/Promi in /Users/juandonoso/Dropbox/Servidor/web/varios/aws/class.aws/Aws/WrappedHttpHandler.php on line 152

**Comment by jeremeamia** [comment]
You need to sync your server's time to an ntp server. As the error indicates: "`RequestTimeTooSkewed` The difference between the request time and the current time is too large."

**Comment by mascreativa** [comment]
It worked! Thank you.

**Comment by jeremeamia** [comment]
:smile:
