### ISSUE TITLE
Append zip files in amazon using s3 php sdk

### ISSUE THREAD

**Issue by thamaraiselvam-revmakx** [aws/aws-sdk-php#614]
Can we add some files(append) inside zip file which is already uploaded into amazon s3 ? using php sdk?

  $result = $s3->uploadPart(array(
                                    'Bucket'     => $as3_bucket,
                                    'Key'        => $as3_file,
                                    'UploadId'   => $uploadId,
                                    'PartNumber' => $partNumber,
                                    'Body'       => fread($file, 5 * 1024 * 1024),
                                ));
This is from client side. What I'm trying is that after uploaded 5 MB  'Body'       => fread($file, 5 * 1024 * 1024) I cut the call then again open the file uploading from another 5MB. like this I'm uploading data. problem is the last only 5Mb of data gets stored in that file(after finished connection i checked the file size in s3 ). I'm reading 5MB from the file according to the how many times called .

so no problems in fread , problem is in multipart upload ,I cannot continue uploading where I stopped. Whenever I tried for next call , the fresh zip created even i'm using same upload ID , but in Amazon s3.php file we have 'seekTo' option , to append files ! like this amazon s3 sdk php also having any function like this?

**Comment by jeremeamia** [comment]
If I understand you correctly, you are:

* Doing a multipart upload
* Doing it is several parts, potentially across multiple requests
* Having trouble uploading the correct part of the file (i.e., starting in the right place)

First, make sure you are setting the `PartNumber` correctly. Parts uploaded with the same `PartNumber` overwrite each other.

Second, you can use some of Guzzle's stream helpers (see [the `Guzzle\Http` namespace](http://docs.aws.amazon.com/aws-sdk-php/v2/api/namespace-Guzzle.Http.html)) to get the desired part of the file.

```php
use Guzzle\Http\EntityBody;
use Guzzle/Http/ReadLimitEntityBody;

$body = new ReadLimitEntityBody(EntityBody::factory($file), 5 * 1024 * 1024, $seekTo);

// Then later pass this in to the uploadPart operation
// ...
    'Body' => $body,
// ...
```

Does this help?

_Note: This code assumes you are using Version 2 of the SDK. If you are using Version 3, let me know._

**Comment by thamaraiselvam-revmakx** [comment]
Thank You @jeremeamia for your reply 
I found my mistake !
whenever a part is uploaded it returns the  'ETag' , I should update Etag with partnumber in an array for every part uploading.  but I did not do that , so last Etag only was sent to completeMultipartUpload so last part only saved !

**Comment by mtdowling** [comment]
Glad it's working now.
