### ISSUE TITLE
Why Must I Redeclare the Version # when Calling the SDK after Upgrading to Version 3?

### ISSUE THREAD

**Issue by NoahTwine** [aws/aws-sdk-php#617]
We are using the AWS PHP SDK with composer. Previously, with version 2 we declared the version in the composer.json file. We then did not have to declare it when we connected to the API in our code.

After upgrading to version 3 we receive an error saying that we must declare a version number each time we try to connect to the SDK within our code. (Sadly, this means we have to add in the versioning at dozens of places within our code.)

How can we go back to the version 2 method?

**Comment by mtdowling** [comment]
Web services that the SDK connects to are also versioned, and these APIs may introduce breaking changes between versions. V2 automatically utilized the latest version, which has the negative effect of potential breakage in your application when taking a minor update of the SDK.

V3 of the SDK is more resilient against this type of breakage by explicitly requiring a service specific API version number when creating a client. We do allow you to set the "version" number to "latest", however, keep in mind that you may inadvertently begin to use a newer version of an API that may cause your application to break at runtime. Using "latest" as the version is a way to opt into convenience of not choosing a version number, but it come with additional risk.

**Comment by NoahTwine** [comment]
Thanks for the super-quick answer! So I guess we will have to change every instance were we call the SDK.

One other question: After declaring the version number at an instance of the SDK, we get another error saying that the AWS credentials under .aws/credentials could not be accessed.

Specifically:

Uncaught exception 'Aws\Exception\CredentialsException' with message 'Error retrieving credentials from the instance profile metadata server. (cURL error 28: Connection timed out after 1005 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))' in /Users/MYUSER/DIRECTORY-OF-PROJECT/lib/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php

Currently these credentials are in the root under  ~.aws/credentials. Does version 3 of the SDK expect these credentials to have a different level or permissions or be placed in a different location?

That would be help to know. Thanks.

**Comment by mtdowling** [comment]
Credential loading should work the same way. Can you confirm that your user has permission to access the file, that the HOME directory is exported to this user, and that credentials file is valid? If you are running as the root user, then you may need to manually export a HOME directory as this is sometimes not declared.

**Comment by mtdowling** [comment]
Do you have any more information on this issue or is it ok to close?

**Comment by NoahTwine** [comment]
@mtdowling thanks much for your help. Yes we are good to close.

**Comment by smkhawaja** [comment]
I have the same issue. Running a php job on my vmware workstation guest and getting the following error

`[Aws\Exception\CredentialsException]
  Error retrieving credentials from the instance profile metadata server. (cURL error 28:
  Connection timed out after 1002 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-
  errors.html))`

aws s3 ls commands working fine.
