### ISSUE TITLE
Surprising is_dir() behaviour in S3 StreamWrapper

### ISSUE THREAD

**Issue by UlrichEckhardt** [aws/aws-sdk-php#619]
We're currently migrating a file-based storage to one based on S3. For ease of use and flexibility, we are using the StreamWrapper class to access S3. During the migration, we have found an issue concerning the handling of directories. Testing various directories using PHP's `is_dir()` function, we got these results:
```
s3://my-bucket exists
s3://my-bucket is a directory
s3://my-bucket/ exists
s3://my-bucket/ is a directory:
s3://my-bucket/test doesn't exist
s3://my-bucket/test is NOT a directory
s3://my-bucket/test/ exists
s3://my-bucket/test/ is a directory:
s3://my-bucket/var doesn't exist
s3://my-bucket/var is NOT a directory
s3://my-bucket/var/ exists
s3://my-bucket/var/ is a directory:
s3://my-bucket/var/test exists
s3://my-bucket/var/test is a directory:
s3://my-bucket/var/test/ exists
s3://my-bucket/var/test/ is a directory:
```
The issue is the different treatment of `s3://my-bucket/test` and `s3://my-bucket/test/`, i.e. with and without trailing backslash. In my eyes, the trailing slash should be ignored, like it is both for the bucket itself (e.g. `s3://my-bucket/`) and for subdirectories (`s3://my-bucket/var/test/`).

Notes:
 * I haven't even tried nasty stuff like `s3://my-bucket/var/test/.`, `s3://my-bucket/var//test` or `s3://my-bucket/../some-other-bucket/secret-stuff`.
 * We initially used a commandline utility to sync some directories, which created `s3://my-bucket/var/foo` and `s3://my-bucket/var/bar`, but without the empty object `s3://my-bucket/var` that seems to be required to recognize this as directory at all. Needless to say that this added to our frustration with our new toy. However, I don't want to call this an issue with the SDK, because it might as well have been our fault or the commandline utility's. Still, if you see any way to handle this case more gracefully, I would appreciate it.
 * In general, I wonder which permissions are required to create a directory with `mkdir()`? I would expect it to only require `s3:putObject`, but that didn't work. This might be related to what the `StreamWrapper` tries to do but I can't tell because I don't understand enough what's going on.
 * There is also surprising behaviour concerning the function `file_get_contents()` (see also https://github.com/aws/aws-sdk-php/issues/609), in that its result differs between `s3://my-bucket/test/` (empty string and no warning or error from PHP) and `s3://my-bucket/test` (error message "The specified key does not exist." as return value, like in issue #609). On other dirs but the root dir, it always returns the error string, only on the root dirs it depends on the trailing slash.
 * Another interesting thing is the `scandir()` behaviour, which in turn completely ignores the trailing slash on a directory. However, it ignores when the object in question is not a directory, in which case it returns an empty array instead of the expected `false`.

**Comment by jeremeamia** [comment]
Thanks for bringing this up. We are working on a response.

**Comment by jeskew** [comment]
@UlrichEckhardt do you still have a script that tests this behavior? I believe it has been addressed since this ticket was opened.

**Comment by jeskew** [comment]
Closing, as all the test cases listed in the original ticket now respond correctly to `is_dir`.
