### ISSUE TITLE
Use of undefined constant CURLOPT_PROTOCOLS error when using Laravel and S3

### ISSUE THREAD

**Issue by EwanValentine** [aws/aws-sdk-php#620]
I'm using the Storage mechanism in Laravel 5.1 which utilises this SDK. I raised an issue with Laravel, who told me to raise an issue on this repo instead. 

I have the following code:

```
    $file = $request->file('file');

    $extension = $file->getClientOriginalExtension();

    $filename = date('d-m-Y').'_'.$request->get('author').'.'.$extension;
    Storage::put($filename, $file);
```

However I get the following error:

S3Exception in WrappedHttpHandler.php line 162: Error executing "HeadObject" on "https://s3-eu-west-1.amazonaws.com/[REDACTED]/10-06-2015_my%20file.jpg"; AWS HTTP error: Use of undefined constant CURLOPT_PROTOCOLS - assumed 'CURLOPT_PROTOCOLS'

I have cURL installed along with php5-curl on Ubuntu 14.04. I'm using HHVM 3.7.

Cheers in advance!

**Comment by EwanValentine** [comment]
curl setopt's are unsupported by HHVM 3.7, upgrading to nightly builds (3.8.0-dev) resolved this for the time being.

**Comment by jeremeamia** [comment]
I was just going to suggest you do that. See https://github.com/guzzle/guzzle/issues/1107. Glad that worked out.
