### ISSUE TITLE
AbstractClient::setRegion() not working as documented

### ISSUE THREAD

**Issue by datibbaw** [aws/aws-sdk-php#623]
According to the [documentation](http://docs.aws.amazon.com/aws-sdk-php/latest/class-Aws.Common.Client.AbstractClient.html#_setRegion), to set a region on a client you would do:

    $client->setRegion('us-east-1');

However, from the [implementation](https://github.com/aws/aws-sdk-php/blob/master/src/AwsClient.php#L156) it seems to expect an array argument. Furthermore, actually using an array argument such as `->setRegion(['us-east-1']);` fails due to the operation `SetRegion` not being found.

See also [this question](http://stackoverflow.com/q/30793291/1338292) on SO.

**Comment by jeskew** [comment]
Hi datibbaw -- the documentation you've linked to covers version 2 of the SDK, which does offer a [`setRegion` method](https://github.com/aws/aws-sdk-php/blob/2.8/src/Aws/Common/Client/AbstractClient.php#L162). The SDK's master branch is version 3, which doesn't support changing the region on an already instantiated client. You would need to create a new client and pass the desired region in as a constructor argument.

I'm going to go ahead and close the issue, but please feel to reopen it if you have any questions.
