### ISSUE TITLE
Best way to bulk copy objects

### ISSUE THREAD

**Issue by joehoyle** [aws/aws-sdk-php#624]
Hi There,

I'm trying to find the most performant way of bulk copy objects within the same bucket. At first I was using `getIterator( 'ListObjects' )` with `copyObject` to serially copy them between locations. I'm presuming there is a quicker way to do with with Async calls, as I don't actually care about the response for the request - I just want to fire off the copyObject request and move on. 

I then started trying to use `copyObjectAsync` - it appears to use that, I'd need to collect promises for all the objects, and `wait` them to actually kick the request off - without that, `copyObjectAsync` doesn't appear to do anything. However, I'm worried this approach is going to eat a lot of memory, copy 100,000 objects for example, I don't want to call `wait` on 100,000 promises.

It seems I could also batch async requests in say chunks of 30, but not sure if that's a good idea.

I also took a look at `\Aws\S3\Transfer` but it appears that's for copy to/from local disk - which I don't want to do.

Any guidance on the most performance way to do this would be great, bearing in mind I am copy 100,000+ objects.

Thanks!

**Comment by jeremeamia** [comment]
The [Command Pool](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/commands.html#commandpool) feature would probably be your best route. Check that out and let us know if you have any questions.

**Comment by joehoyle** [comment]
Thanks, will take a look!

**Comment by jeremeamia** [comment]
Closing for now. Let us know if you run into questions.
