### ISSUE TITLE
Missing Aws\Sns\MessageValidator\MessageValidator classes

### ISSUE THREAD

**Issue by pako-pl** [aws/aws-sdk-php#625]
The SNS MessageValidator classes did not get included in version 3 of AWS PHP SDK. So after upgrading to v3 there is no way to validate incoming SNS messages. Do you offer any alternative? The migration guide does not mention this issue at all, we discovered the problem during migration.

**Comment by jeremeamia** [comment]
We actually _did_ mention it in the migration guide in [this section](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/migration.html#many-higher-level-abstractions-have-changed). We plan on releasing it as a separate package, since it is useful on its own and doesn't really need to depend on the SDK. I'll try to get that repo published soon (this week?), and I'll make sure to ping this isue.

**Comment by pako-pl** [comment]
Sorry, I missed the note about SNS Message Validator (probably because the specific class name wasn't mentioned there). Great to hear that the package will be released soon.

**Comment by StevenBullen** [comment]
@jeremeamia 
Any update on this? :)

**Comment by jeremeamia** [comment]
Yeah, we've extracted it out and completed the code, and it is now under internal review.

**Comment by StevenBullen** [comment]
Thanks

**Comment by jeremeamia** [comment]
The repository is here: https://github.com/aws/aws-php-sns-message-validator. We are still working on it before we release a stable version. Not much is changing though from what there was in the V2 SDK. I'm going to close this issue. Feel free to take the new package for a test drive if you want to help out, and open any issues on that repo that you might encounter. Thanks.

**Comment by StevenBullen** [comment]
Great news and will do. Thanks again.

**Comment by melusom** [comment]
Glad I stumbled upon this post. I had been scouring the Internet trying to find out why I couldn't load AWS\Sns\Message for close to 2 hours. If it is no longer included in the SDK AWS *really* needs to update the documentation.

**Comment by jeremeamia** [comment]
Sorry that tripped you up. Where in the documentation would that have been the most useful to you?

**Comment by melusom** [comment]
@jeremeamia right about here: [http://docs.aws.amazon.com/aws-sdk-php/v3/api/namespace-Aws.Sns.html](http://docs.aws.amazon.com/aws-sdk-php/v3/api/namespace-Aws.Sns.html). I found it a little misleading as if it was still part of the SDK

**Comment by jeremeamia** [comment]
Yeah, I could see how you would find that misleading. I was also thinking some modifications [here](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/migration.html#many-higher-level-abstractions-have-changed) and [here](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/index.html) might be helpful too. I no longer work on the SDK, but I'm sure @jeskew could make something good happen.

**Comment by melusom** [comment]
Absolutely. I'm up and running by using the aws/aws-php-sns-message-validator repo. I appreciate the help!

**Comment by jeskew** [comment]
@melusom The validator classes included in the phar and zip distributions, which are what we use to generate the API docs. PSR-7 interfaces and Guzzle classes are documented as well, though it is more clear in those cases that the code isn't part of the SDK.

Would it have helped if the aws/aws-php-sns-message-validator were suggested by composer?

**Comment by melusom** [comment]
@jeskew Ah I see. I did the composer install. Yeah, the suggestion would've helped.
