### ISSUE TITLE
getObject with SaveAs not working in sdk v3?

### ISSUE THREAD

**Issue by mwoodring** [aws/aws-sdk-php#627]
I am using the getObject command with the SaveAs parameter. I receive a successful response from the command but no file is at the path given in the command. I am using this code:

$response = $s3Client->getObject ( [
				'Bucket' => $cloudBucket,
				'Key' => $currFileName,
				'SaveAs' => "$tempFullFile"
				]);

This same code worked in sdk v2. Is this a bug or do I need to change my params?

**Comment by jeremeamia** [comment]
It looks like this was missing, so I've added support via #629.

Until then, you can achieve the same affect using the ["sink" HTTP option](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#sink):

```php
$result = $s3Client->getObject([
    'Bucket' => $cloudBucket,
    'Key'    => $currFileName,
    '@http'  => ['sink' => $tempFullFile]
]);
```
