### ISSUE TITLE
SQS DeleteMessageBatch Errors

### ISSUE THREAD

**Issue by danielfharmonic** [aws/aws-sdk-php#630]
I was trying to use SQS's DeleteMessageBatch but it failed with the following error:

    Aws\Sqs\Exception\SqsException: Error executing "DeleteMessageBatch" on "<url removed>"; AWS HTTP error: Client error: 400 AWS.SimpleQueueService.EmptyBatchRequest (client): There should be at least one DeleteMessageBatchRequestEntry in the request. - <?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>AWS.SimpleQueueService.EmptyBatchRequest</Code><Message>There should be at least one DeleteMessageBatchRequestEntry in the request.</Message><Detail/></Error><RequestId>d26e8772-3036-5dfb-a868-ca8ba22a0a63</RequestId></ErrorResponse>

Some debugging shows this is identical to this issue in the AWS SDK for Go:

https://github.com/aws/aws-sdk-go/issues/161

Thanks!

**Comment by jeskew** [comment]
Thanks for bringing this to our attention. We are working on a response.

**Comment by jeskew** [comment]
PR #638 has been merged into master and should fix this.

I'm going to go ahead and close the issue, but please feel to reopen it if you have any questions.
