### ISSUE TITLE
File not found: /var/app/current/php/vendor/aws/aws-sdk-php/src/Endpoint/../data/endpoints.json

### ISSUE THREAD

**Issue by IBleSSeDI** [aws/aws-sdk-php#632]
I have a project launched on AWS Beanstalk and I use php aws sdk. I have a CLI script which does some actions with SQS. It processes a queue all the time. And time to time I see an error 
>File not found: /var/app/current/php/vendor/aws/aws-sdk-php/src/Endpoint/../data/endpoints.json, realpath: /var/app/current/php/vendor/aws/aws-sdk-php/src/data/endpoints.json
#0 /var/app/current/php/vendor/aws/aws-sdk-php/src/JsonCompiler.php(79): Aws\JsonCompiler->loadJsonFromFile('/var/app/curren...', '/var/app/curren...')
#1 /var/app/current/php/vendor/aws/aws-sdk-php/src/functions.php(157): Aws\JsonCompiler->load('/var/app/curren...')
#2 /var/app/current/php/vendor/aws/aws-sdk-php/src/Endpoint/EndpointProvider.php(79): Aws\load_compiled_json('/var/app/curren...')
#3 /var/app/current/php/vendor/aws/aws-sdk-php/src/ClientResolver.php(446): Aws\Endpoint\EndpointProvider::defaultProvider()
#4 /var/app/current/php/vendor/aws/aws-sdk-php/src/ClientResolver.php(210): Aws\ClientResolver::_default_endpoint_provider(Array)
#5 /var/app/current/php/vendor/aws/aws-sdk-php/src/AwsClient.php(136): Aws\ClientResolver->resolve(Array, Object(Aws\HandlerList))
#6 /var/app/current/php/vendor/aws/aws-sdk-php/src/Sqs/SqsClient.php(17): Aws\AwsClient->__construct(Array)
#7 /var/app/current/php/components/processors/PostProcessor.php(40): Aws\Sqs\SqsClient->__construct(Array)
#8 /var/app/current/php/commands/ProcesspostController.php(19): app\components\processors\PostProcessor->start()
#9 [internal function]: app\commands\ProcesspostController->actionIndex('-env=staging')
#10 /var/app/current/php/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#11 /var/app/current/php/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#12 /var/app/current/php/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('', Array)
#13 /var/app/current/php/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('', Array)
#14 /var/app/current/php/vendor/yiisoft/yii2/console/Application.php(161): yii\base\Module->runAction('processpost', Array)
#15 /var/app/current/php/vendor/yiisoft/yii2/console/Application.php(137): yii\console\Application->runAction('processpost', Array)
#16 /var/app/current/php/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#17 /var/app/current/php/yii(52): yii\base\Application->run()
#18 {main}

I see this error in my logs (it throws an Exception) ~once per hour. Why that endpoints.json file is sometimes missing? Not all the time, but sometimes? And how to fix this? Thanks.

**Comment by jeskew** [comment]
The endpoints,json file is part of the repository, so it should always be present. Does the exception occur at a certain time every hour, and is there a cron job running at the same interval that would somehow interfere with file access?

**Comment by IBleSSeDI** [comment]
No, the exception is not on the certain time. Also it is not because of any cron jobs. I have one php CLI script with receives data from the SQS and does some actions with the messages. So, I am not sure why I see that error.

**Comment by jeremeamia** [comment]
What type of instances are you using? How is the load on the server? Any other similar errors for other files in your application? Any other patterns or information to share?

The error is clearly not caused by the file actually missing. I suspect that you may be hitting the system's limit on maximum open [file descriptors](http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/). This is known to cause sporadic "file not found" type errors.

**Comment by IBleSSeDI** [comment]
We use m1.small instance type. Load on the server is not high. However we have Jenkins installed there,so it may be that Jenkins CI causes much load on server (not sure). We do not see such errors on any other parts of our project. So, how can we fix this issue?

**Comment by jeskew** [comment]
Jenkins might be using up a significant percentage of your open files limit. Try increasing your system's limit on file descriptors.

**Comment by IBleSSeDI** [comment]
Yes, it helped. However not I get the following error:
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 1048577 bytes) in /var/app/current/php/vendor/guzzlehttp/psr7/src/Stream.php on line 211
PHP Fatal Error 'yii\base\ErrorException' with message 'Allowed memory size of 134217728 bytes exhausted (tried to allocate 1048577 bytes)'
So, seams like that's smth wrong inside of the sdk?

**Comment by jeremeamia** [comment]
Well, not necessarily. All this means is that something you did used more memory than you have. 134217728 bytes is 128MB. You might consider checking the memory_limit INI setting and increasing it. 

Do you have any code to share about what you are doing? We could take a look at how you are using the SDK if there is anything to optimize.

**Comment by IBleSSeDI** [comment]
I have a CLI script which receives messages from the SQS and does some actions with that. However right now the queue is empty and an error raises with empty queue. I do smth like this:

while(true){
                if(self::$_quitSignal){
                    exit;
                }
                $client = new \Aws\Sqs\SqsClient([
                    'version'  => Yii::$app->params['aws']['sdkVersion'],
                    'region'  => Yii::$app->params['aws']['defaultRegion'],
                    'credentials' => [
                        'key' => Yii::$app->params['aws']['accessKey'],
                        'secret' => Yii::$app->params['aws']['accessSecret'],
                    ],
                ]);
                $result = $client->receiveMessage(array(
                    'QueueUrl' => Yii::$app->params['aws']['sqs']['postQueue']
                )); 
                if($result->getPath('Messages')) {
                    foreach ($result->getPath('Messages') as $message) {
                        try {
                            $body = \yii\helpers\Json::decode($message['Body']);
                            Handler::handle($body['url'], $body['data'], $body['headers'], $body['ip']);
                            $client->deleteMessage(array(
                                'QueueUrl' => Yii::$app->params['aws']['sqs']['postQueue'],
                                'ReceiptHandle' => $message['ReceiptHandle'],
                            ));
                        } catch (app\handlers\HandlerException $e){
                            $client->deleteMessage(array(
                                'QueueUrl' => Yii::$app->params['aws']['sqs']['postQueue'],
                                'ReceiptHandle' => $message['ReceiptHandle'],
                            ));
                            Yii::error($e->getMessage() . PHP_EOL . $e->getTraceAsString(), 'processor');
                        }
                    }
                } else {
                    sleep(1);
                }
            }
        } catch (\Exception $e){
            Yii::error($e->getMessage() . PHP_EOL . $e->getTraceAsString(), 'processor');
            $this->start();
        }

**Comment by mtdowling** [comment]
You should definitely not create a new client in each iteration of the loop. Move client creation out of the loop for performance and to mitigate and circular references that would only be cleaned up from a periodic call to `gc_collect_cycles`.

**Comment by IBleSSeDI** [comment]
Definetely! I will try to create client before the loop and return here. Thanks!

**Comment by IBleSSeDI** [comment]
Yes, that fixed the problem. Thank you!
