### ISSUE TITLE
CloudSearchDomainException from sample code on documentation

### ISSUE THREAD

**Issue by UnbrandedTech** [aws/aws-sdk-php#634]
I love the look of the [new documentation](http://docs.aws.amazon.com/aws-sdk-php/guide/latest/service-cloudsearchdomain.html) and I followed it TO THE T and got this exception.
````php
$client = CloudSearchDomainClient::factory(array(
'version' => '2013-01-01', // This caused an error if I didn't add it someone should put something in the documentation but w/e
'endpoint' => '<my super secret search endpoint>.cloudsearch.amazonaws.com'
));
$res = $client->search(array('query' => 'foobar'));
````
I run it and BOOM!

````
PHP message: PHP Fatal error:  Uncaught exception 'Aws\CloudSearchDomain\Exception\CloudSearchDomainException' with message 'Error executing "Search" on "/2013-01-01/search?format=sdk&pretty=true&q=foobar"; AWS HTTP error: cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)'

exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in /var/www/app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:162
Stack trace:
#0 /var/www/app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(125): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /var/www/app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(90): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /var/www/app/vendor/guzzlehttp/guzzle/src/Handler/CurlMult"
````

Any Ideas? The almighty Google has failed me.

**Comment by jeremeamia** [comment]
> Any Ideas?

Make sure you have `https://` or `http://` in your URL. I think that should fix your issue.

> `'version' => '2013-01-01', // This caused an error if I didn't add it someone should put something in the documentation but w/e`

Here are the [docs on `'version'`](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#version). Where were you reading that might benefit from some clarification?

**Comment by UnbrandedTech** [comment]
This is the page I was reading
http://docs.aws.amazon.com/aws-sdk-php/guide/latest/service-cloudsearchdomain.html

**Comment by jeskew** [comment]
Those are actually the docs for v2 of the SDK (please excuse the "latest" in the URL; we're working on that). The v3 documentation can be found [here](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/).

**Comment by UnbrandedTech** [comment]
Is there a irc channel or a gitter that I can ask questions? There are a lot of really confusing things in the Documentation. Like 
````
CloudSearchDomainClient->search(
    'highlight' => '<string>' //this is a string
)
````

but in the api documentation 
http://docs.aws.amazon.com/cloudsearch/latest/developerguide/highlighting.html

It's in a dot notation:

````
highlight.field={"max_phrases":<int>,"format":<text / html>,"pre_tag":"*<string>*","post_tag":"*%*"}
````

How would you do this in the SDK?

**Comment by UnbrandedTech** [comment]
BTW, @jeremeamia you were right. It works, now I have different Issues.

**Comment by jeskew** [comment]
As we discussed in the Gitter chat, `highlight` takes a JSON string with the fields mentioned in the CloudSearch developer guide.

I'm going to go ahead and close the issue, but please feel to reopen it if you have any questions.
