### ISSUE TITLE
S3: putObjectAcl produces malformed XML

### ISSUE THREAD

**Issue by janvennemann** [aws/aws-sdk-php#643]
I'm trying to set an access control policy on an existing object via putObjectAcl. This is the code snippet i use to test the issue:

```php
[...]
$bucketName = 'static.jayvee';
$objectKey = 'test.jpg';
$sourceStream = fopen($objectKey, 'r');
$s3Client = $awsSdk->createClient('S3', ['debug' => TRUE]);
$s3Client->upload($bucketName, $objectKey, $sourceStream);

$acp = [
    'Grants' => [[
        'Grantee' => [
            'DisplayName' => 'Everyone',
            'Type' => 'Group',
            'URI' => 'http://acs.amazonaws.com/groups/global/AllUsers'
        ],
        'Permission' => 'READ'
    ]]
];
$s3Client->putObjectAcl([
	'Bucket' => $bucketName,
	'Key' => $objectKey,
	'AccessControlPolicy' => $acp
]);
```

And this is the XML generated by the AWS SDK (examined with the debug parameter):

```xml
<AccessControlPolicy xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
	<AccessControlList>
		<Grant>
			<Grantee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
				<DisplayName>Everyone</DisplayName>
				<URI>http://acs.amazonaws.com/groups/global/AllUsers</URI>
			</Grantee>
			<Permission>READ</Permission>
		</Grant>
	</AccessControlList>
</AccessControlPolicy>
```

I noticed that xsi:type="Group" is missing from the Grantee Node. Do i miss something in my access control policy definition or is this maybe a bug?

**Comment by jeskew** [comment]
Thanks for reporting this, @janvennemann . Looks like `XMLWriter` won't add attributes to a node once any children have been written, so I added a sorting step to make sure attributes precede child nodes in the data passed to the writer. 

This fix has been merged into master and will go out with our next release.
