### ISSUE TITLE
Failure when receiving data from the peer

### ISSUE THREAD

**Issue by BruceWouaigne** [aws/aws-sdk-php#644]
Hey guys, since I've update to the v3.0.5 i'm getting - not always but quite often - the error below

<code>
AWS HTTP error: cURL error 56: Failure when receiving data from the peer" at /var/www/____/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php line 152 {"exception":"[object] (Aws\\S3\\Exception\\S3Exception(code: 0): Error executing \"PutObject\" on \"https://s3-eu-west-1.amazonaws.com/____/____\"
</code>

I don't believe it's s3 related because I never had any error using the v2.4

Any ideas?

**Comment by jeskew** [comment]
Hi Bruce,

How large is the object you're trying to put, and are there any proxy servers you might be hitting (e.g., Squid boxes)?

**Comment by BruceWouaigne** [comment]
Files are around 2MB. I also tried using a multipart upload, same thing. And no proxies at all.

Again, with a previous version of the aws php wrapper (2.4) everything was fine.

**Comment by jeskew** [comment]
Sorry for the delay on addressing this, but v3.2.6 contains a fix that should eliminate this error. Please feel free to reopen if it comes up again.

**Comment by josef-diazlop** [comment]
Hey guys, i have the same problem, i'm on 3.2.6 version, it happens 40% of times.

Do you have any workaround?

**Comment by cjyclaire** [comment]
@josef-diazlop , could you provide more information about your problem? When did you see this happen? Is this a problem that happened after some version upgrade? In last fix, retries are enhanced in handling the original issue.

**Comment by josef-diazlop** [comment]
I uploaded to s3 a bulk collection around 60 files, some are about 50 MB, 5 or 6, but most are about 650 KB, all compressed in zip format. I get this error in 40% of the uploads. I try to reproduce it but it seems to be totally random. This happens in previous version as in actual.
Today I'll try to gather more information. If I find something I'll let you know.

**Comment by josef-diazlop** [comment]
@cjyclaire 
I uploaded to production and the problem persists. On ubuntu 14.04 and ubuntu 16.04 (our development environment ) goes fine, but in debian jessie we have this problems.
All the environments are updated.

we have this additional info in the error:
Upload of dump contents to remote directory failed with message An exception occurred while uploading parts to a multipart upload. The following parts had errors:
- Part 7: Error executing "UploadPart" on "https://{domain}/Attachment.chunks.bson.gz.04?partNumber= [status code] 500 [reason phrase] Internal Server Error InternalError (server): We encountered an internal error. Please try again. - <?xml version="1.0" encoding="UTF-8"?>
<Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>{requestid}</RequestId><HostId>{hostid}</HostId>

Thanks for the help.

**Comment by cjyclaire** [comment]
@josef-diazlop  , thank you for following up. Since on ubuntu works fine, and the error message is 500 on server-side, I'd consider it has less to do with SDK. Your feedback is of great value, I'd recommend [aws forum](https://forums.aws.amazon.com/index.jspa) for direct conversation with service team ;)
