### ISSUE TITLE
UnresolvedApiException in ApiProvider.php line 82:

### ISSUE THREAD

**Issue by EwanValentine** [aws/aws-sdk-php#645]
Apologies, me again! 

I'm using CloudFront and I'm getting errors regarding the API version? I have the following code:

```
        $expires = time() + $expires;
        $host = 'http://cdn.myurl.com';

        return CloudFrontClient::factory(array(
            'private_key' => '../pk-[REDACTED].pem',
            'key_pair_id' => '[REDACTED]',
            'url'         => $host . '/' . $key,
            'expires'     => $expires,
            'region'      => 'eu-west-1',
            'version'     => '2015-06-17', 
        ));

```

I've removed sensitive data from that code, but you get the idea. I've tried several different combinations, but I keep getting the following exception:

```
UnresolvedApiException in ApiProvider.php line 82:
The cloudfront service does not have version: 2015-06-17.
```

Cheers in advance!

**Comment by jeskew** [comment]
The latest version of CloudFront available to the SDK looks like `2014-11-06`. Are you trying to use features released on the 17th?

**Comment by EwanValentine** [comment]
No I don't believe so. I upgraded the aws php sdk and the instantiation of the signed CloudFront url factory changed and I wasn't sure where to find the CloudFront API version. I'll try the version you just suggested and report back, cheers!

**Comment by EwanValentine** [comment]
That's kind of worked, but now I'm getting 
```
\nFatal error: syntax error, unexpected T_YIELD in /home/forge/default/vendor/aws/aws-sdk-php/src/Credentials/InstanceProfileProvider.php on line 50
```

**Comment by EwanValentine** [comment]
Sorry, I think that's HHVM related. Thanks for the help!
