### ISSUE TITLE
Error with cURL on Heroku

### ISSUE THREAD

**Issue by Hakadel** [aws/aws-sdk-php#648]
Hello,

I use Heroku to host a Symfony2 application, but when I want to send any file to S3 I have this error : 

> Error retrieving credentials from the instance profile metadata server. (cURL error 28: Connection timed out after 1000 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))

and sometimes this one : 

> Error retrieving credentials from the instance profile metadata server. (cURL error 7: Failed to connect to 161.252.139.214 port 80: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))

But I use the same code and same access in my local server and everything is working, so I think it's a Heroku issue but I don't know what to do...

Any idea ?

Thanks.

**Comment by jeskew** [comment]
Hi Hakadel,

That error can occur when the SDK is unable to locate credentials in the usual places and tries to authenticate using an instance profile, which can only be done on EC2.

Are you using environment variables or a credentials file to authenticate?

**Comment by Hakadel** [comment]
Hello @jeskew,

Ok i see, I just set ENV variables and it's working now, but it's strange because my config was on the code.

AWS_ACCESS_KEY_ID, AWS_BUCKET, AWS_REGION and AWS_SECRET_ACCESS_KEY

So with env vars all is working.

Thank you ;)

**Comment by GS-ThiagoVieira** [comment]
gosto de pau
