### ISSUE TITLE
2.8.11 backwards compatibility with 2.8.10

### ISSUE THREAD

**Issue by ragboyjr** [aws/aws-sdk-php#649]
It seems as though 2.8.11 is not a backwards compatible version with 2.8.10. I don't know if the 2.0 is using semantic versioning or not (I saw that 3.0 was); however, after upgrading from 2.8.10 to 2.8.11 threw was an error in my project because the `Aws\Common` module is missing.

I'm using the `Aws\Common` module for setting up credentials as mentioned [in the docs](http://docs.aws.amazon.com/aws-sdk-php/guide/latest/credentials.html#passing-credentials-into-a-client-factory-method).

Personally, I'm just going to change my `composer.json` to read `"aws/aws-sdk-php": "2.8.10"` instead of `"aws/aws-sdk-php": "~2.0"`

I just wanted to report this in case it the version update was supposed to be backwards compatible, and it accidentally got overlooked.

**Comment by jeskew** [comment]
Hi @ragboyjr,

Do you have stack trace or something that could help us debug your issue? [`Aws\Common`](https://github.com/aws/aws-sdk-php/tree/2.8/src/Aws/Common) appears to be present in the latest release.

**Comment by jeremeamia** [comment]
Yeah, we have a bad tag. Will be pushing 2.8.12 momentarily.

**Comment by mpoiriert** [comment]
You should delete the tag or replace but don't leave it there because it could break a lot of project base on the fact a tag is suppose to be stable...

**Comment by ragboyjr** [comment]
@jeskew, No stack trace, just a fatal error: `Fatal error: Class 'Aws\Common\Credentials\Credentials' not found in /data/gitsites/tige/mywake-cms/master/vendor/tige-mywake/lib/app/config/s3.php on line 7`. It looks like you've already released 2.8.12, and that looks like it'll be compatible

Thanks for the quick responses!

**Comment by jeremeamia** [comment]
Thanks for the heads up! The 2.8.11 release was accidentally tagged to a commit from Version 3 of the SDK, which is why things appeared to be missing. We've removed the 2.8.11 release completely, and 2.8.12 should work for you. Closing.

**Comment by ragboyjr** [comment]
Yup, works great, thanks!
