### ISSUE TITLE
SimpleDB support removed?

### ISSUE THREAD

**Issue by ArthurGuy** [aws/aws-sdk-php#651]
I have just upgraded to v3 for use with Laravel 5 and the Simple DB service has gone.
It appears the change happened with the 2.8.11 tag when the folder structure changed.

I really hope this is an oversight as I can't find any mention of it in any of the release notes.

**Comment by jeremeamia** [comment]
We just tagged 2.8.11, and it was a bad tag. We are fixing that in just a minute. Version 3 of the SDK does not support SimpleDB anymore though, since the service does not support authentication with Signature Version 4.

**Comment by ArthurGuy** [comment]
Crap, now to figure out how to run two versions :cry: 

Thanks

**Comment by ArthurGuy** [comment]
Ohh, could the removal be added to the release notes? It might save someone else from having to search through the various updates.

**Comment by jeremeamia** [comment]
> Crap, now to figure out how to run two versions.

Not necessarily. If you *really* need SimpleDB in V3, you can get the code from before [this commit](https://github.com/aws/aws-sdk-php/commit/2e476c68e3d4794b15c7b8ed72a2eaa6741b6a28). I'll also make a note that you asked for it.

> Ohh, could the removal be added to the release notes? It might save someone else from having to search through the various updates.

Ummm... yeah, I will do it. I'm not sure why we missed doing that beforehand. Thanks.

**Comment by ArthurGuy** [comment]
I found a very old single file library for the sqs service, it has a few bugs but is perfect for now.

Thanks for your quick response with this.

**Comment by jeskew** [comment]
Hi @ArthurGuy,

There's a preview release of a SimpleDB client for v3 of the SDK [here](https://github.com/aws/aws-sdk-php-v3-bridge/releases/tag/0.0.1). If you're still looking for this functionality, would you mind taking a look and letting me know if it meets your needs?
