### ISSUE TITLE
Aws\Api\Parser\Crc32ValidatingParser throws strange exception "crc32 mismatch. Expected 123, found 123"

### ISSUE THREAD

**Issue by kamichidu** [aws/aws-sdk-php#652]
I run a simple php app. with php 5.6.10, IIS8 under windows server 2012R2 64bit, I get a strange error "crc32 mismatch. Expected 123, found 123" it was thrown from Crc32ValidatingParser.php L32.
I don't have any ideas that how to fix it.

I think it is a bug.
Can I avoid it?

**Comment by jeskew** [comment]
Are you using DynamoDb local? If not, do you know how large of a response from DDB you were expecting?

**Comment by kamichidu** [comment]
I'm using DynamoDB, not a local.
I know how large of the response. It is lower than 100kb.

I tried to reproduce it under my mac osx yosemite or ubuntu, but I couldn't reproduce it.
My production env. is under win server 2012R2, I always get the strange exception.

**Comment by jeskew** [comment]
Thanks for reporting this. We're working on a fix.

**Comment by kamichidu** [comment]
Thanks a lot!

There are things I can help, I'll help for fixing.

**Comment by jeskew** [comment]
The fix has been merged into master and will go out with the next release. Please let me know if the issue persists or if you have any questions.
