### ISSUE TITLE
Unable to manually set x-amz-content-sha256 header for unseekable payloads

### ISSUE THREAD

**Issue by dstevenson** [aws/aws-sdk-php#655]
I am making a PutObject command using an unseekable stream for the body so I receive the following exception:

```
Aws\\Exception\\CouldNotCreateChecksumException(code: 0): A sha256
checksum could not be calculated for the provided upload body, because
it was not seekable. To prevent this error you can either 1) include
the ContentMD5 or ContentSHA256 parameters with your request, 2) use a
seekable stream for the body, or 3) wrap the non-seekable stream in a
GuzzleHttp\\Stream\\CachingStream object. You should be careful though
and remember that the CachingStream utilizes PHP temp streams. This
means that the stream will be temporarily stored on the local disk.
```

Looking at the docs, PutObject does not accept a ContentSHA256 so the S3 Signature throws exception when x-amz-content-sha256 header is not present or it cannot calculate one.

Should this be an available PutObject parameter or is there another way I should be manually setting this parameter?

**Comment by jeremeamia** [comment]
I believe setting the `'ContentSHA256'` parameter should work. We'll work on fixing the docs.

**Comment by dstevenson** [comment]
@jeremeamia I attempted to set the `ContentSHA256` but it's not part of the `StructureShape` definition for the PutObjectRequest so it's dropped by the time the `RequestInterface` makes it way to the signature step.

I think a potential workaround might be to use a middleware that prepends the sign step and adds the header, trying that out now

**Comment by dstevenson** [comment]
Anyone having this issue can use this workaround:

```
$hash = 'CALCULATED';
/** @var $client \Aws\S3\S3Client */
$client->getHandlerList()->prependSign(
    \Aws\Middleware::mapRequest(function(\Psr\Http\Message\RequestInterface $req) use ($hash) {
        return $req->withHeader('x-amz-content-sha256', $hash);
    }),
    'add-x-amz-content-sha256'
);
```

**Comment by jeremeamia** [comment]
@dstevenson 

>  I attempted to set the ContentSHA256 but it's not part of the StructureShape definition for the PutObjectRequest

You're right. My mistake. It is for Glacier upload operations, and we plan on adding support for it in S3 now as well.

> I think a potential workaround might be to use a middleware that prepends the sign step and adds the header

Yep. Your code for that looks great.

Thanks for letting us know about this issue.

**Comment by jeremeamia** [comment]
Closing this now. Improvements related to this issue are being made in #661.

**Comment by swayam01** [comment]
I am currently facing the same issue, Where this workaround should be stored
