### ISSUE TITLE
Permission denied on aws-cache folder

### ISSUE THREAD

**Issue by grepollo** [aws/aws-sdk-php#660]
Hi,

We migrated from v2 sdk to v3. 

I've been struggling this week about this one. I always got the following error:

ErrorException: /var/www/html/itq-api/api/vendor/aws/aws-sdk-php/src/JsonCompiler.php line 93
file_put_contents(/tmp/aws-cache/data_manifest.json.php): failed to open stream: Permission denied

So my initial thinking is just permission issue, I'm using centos 6.6 on the server with LEMP, so I change the owner to nginx and even change the permission to 777, still cannot write to that path. 

Is there any workaround on this one? strange is on my local environment using Homestead, it is working but on our staging server its not. 

Thanks.

**Comment by grepollo** [comment]
Hi, 

I tried to check the JsonCompiler code, I saw the above code which has an option to set cache directory:

const CACHE_ENV = 'AWS_PHP_CACHE_DIR';

So what I did is add that variable on my env files and set the new path, and its now working. If someone has the same issue with this, just change the path and make sure that directory is writeable. 

Thanks.

**Comment by jeremeamia** [comment]
Yep, that sounds like the best solution. I'll make a note that we need to add something to our docs about this.
