### ISSUE TITLE
Version 2.8.11 or 2.8.12

### ISSUE THREAD

**Issue by remicollet** [aws/aws-sdk-php#665]
According to https://github.com/aws/aws-sdk-php/releases/tag/2.8.12 this is 2.8.12
According to https://github.com/aws/aws-sdk-php/commit/69cf65438b99051ce4d599f1611dea5d50551b3f this is 2.8.11

Can you please clarify ?

**Comment by jeremeamia** [comment]
We messed up the 2.8.11 release, so we created 2.8.12 and removed 2.8.11. Sorry about the confusion.
