### ISSUE TITLE
Using AWS SDK along with AWS KPL

### ISSUE THREAD

**Issue by BardiaAfshin** [aws/aws-sdk-php#666]
Is there any show case example that shows how to use AWS SDK along with KPL. 

Quote from http://docs.aws.amazon.com/kinesis/latest/dev/developing-producers-with-kpl.html:
"It acts as an intermediary between your producer application code and the Amazon Kinesis API actions"

You can use both the AWS KPL and the AWS SDK side by side for more robust production of a message? Maybe this belongs on a forum, but if you have showcase code to share with the above statement, it would be helpful.

**Comment by jeskew** [comment]
Hi @BardiaAfshin,

The KPL is currently only recommended for use through the [java wrapper library](https://github.com/awslabs/amazon-kinesis-producer). Their [platform recommendations](http://docs.aws.amazon.com/kinesis/latest/dev/kinesis-kpl-integration.html) assume your producer code is written in Java.

Would you be interested in seeing something similar for PHP?

**Comment by BardiaAfshin** [comment]
Definately.

**Comment by jeskew** [comment]
I've added a note to our internal backlog. Please feel free to reopen if you have any further questions.
