### ISSUE TITLE
Cloudsearch format = json instead of sdk

### ISSUE THREAD

**Issue by mayrop** [aws/aws-sdk-php#671]
Is there any option to change format = `json` instead of `sdk`?
https://github.com/aws/aws-sdk-php/blob/master/src/data/cloudsearchdomain/2013-01-01/api-2.json#L17

**Comment by jeskew** [comment]
It's not currently configurable. Are you running into an issue?

**Comment by mayrop** [comment]
It's just hard to handle response since `sdk` format returns different structure. On `sdk` format, every field is returned as an array, even though that field is not configured as an array in the "Index Fields". On `json` format, all the fields are returned in the same structure they are defined in the "Index Fields". When you handle the data returned from SDK, it is hard to know if the field was actually an array initially or not...

**Comment by jeskew** [comment]
Just to clarify, are all fields being returned as arrays (even ones that are supposed to contain scalar values), or is the issue that both lists and maps are represented as arrays in the response?

**Comment by mayrop** [comment]
Not sure which option would be... but below is an example of both responses, with `sdk` format & `json` format.

So for example... a request to cloudsearch in JSON format would look like this:

```
hits: {
	found: 20993,
	start: 0,
	hit: [
		{
			id: "case_37bfcab9-380e-4e2b-ab9a-4b560527b666",
			fields: {
				field1: "etc",
				field2: "etc2",
				field3: "This is a description",
				account_status: [
					"New"
				],
...			
```

If you notice, I get scalar valies for field1, field2, field3... since those fields are either literal, integer or text in my Index Fields configuration (exactly what I would expect).

A request to cloudsearch in SDK format would look like this:

```
hits: {
	found: 20993,
	start: 0,
	hit: [
		{
			id: "case_37bfcab9-380e-4e2b-ab9a-4b560527b666",
			fields: {
				field1: [
					"etc"
				],
				field2: [
					"etc2"
				],
				field3: [
					"This is a description"
				],
				account_status: [
					"New"
				],
...
```

So from the response, there's no way to know which fields are actually configured as array and which ones are literal/text/integer/etc, since all of them are returned as arrays.

Hope it makes sense :)

**Comment by jeskew** [comment]
That definitely makes sense. Is your CloudSearch domain protected by any kind of authentication? If not, the easiest solution for you might be to use an HTTP client outside of the context of the SDK.

**Comment by mayrop** [comment]
Yes it is protected... I actually had my own system to query cloudsearch... but thought it was better to start using the `sdk` after version 3 was released.... 

I assume there is no plan to make the format flexible...

**Comment by jeskew** [comment]
Unfortunately there is not. Cloudsearch's json format isn't something that any of the SDKs can understand natively.

**Comment by mayrop** [comment]
Uhm ok, that's sad. I thought it was a matter of being able to do the requestUri flexible here: 
https://github.com/aws/aws-sdk-php/blob/master/src/data/cloudsearchdomain/2013-01-01/api-2.json#L17

Though some code here:
https://github.com/aws/aws-sdk-php/blob/master/src/Api/Operation.php#L22

Oh well.

**Comment by mayrop** [comment]
Also.. sorry... but by hardcoding the `pretty` to true.. the requests are slower since requests size is bigger...

I'm getting 1,121KB request (when I fetch for example 1000 results from a search) with pretty=true, and I get 746KB without pretty=true. It is a very significative difference when you're talking about big searches... and I get 1,196KB when I add format=sdk since it adds more characters for arrays.

Anyway.

**Comment by jeskew** [comment]
Let me do some investigation on this -- the json files are auto-generated, so any changes would get wiped out in an update. I'll need to check to find out why `pretty=true` is being added to those endpoints.

**Comment by jeskew** [comment]
I still don't have an answer for you about why `pretty=true` is hardcoded into the cloudsearch endpoints, but it's a lot easier to sign an arbitrary request in v3 than it was in v2. You can use the SDK to manage your domain and then do something like the following to execute a search:
```php
use Aws\Credentials\CredentialProvider;
use Aws\Signature\SignatureV4;
use GuzzleHttp\Client;
use GuzzleHttp\Psr7\Request;

// Prepare a CloudSearchDomain request
$request = new Request('GET', 'https://<your-domain>.<region-of-domain>.cloudsearch.amazonaws.com/2013-01-01/search?q=star+wars&return=title');

// Get your credentials from the environment
$credentials = call_user_func(CredentialProvider::defaultProvider())->wait();

// Construct a request signer
$signer = new SignatureV4('cloudsearch', '<region-of-domain>');

// Sign the request
$request = $signer->signRequest($request, $credentials);

// Send the request
$response = (new Client)->send($request);
$results = json_decode($response->getBody());
if ($results->hits->found > 0) {
    echo $results->hits->hit[0]->fields->title . "\n";
}
```

**Comment by jeskew** [comment]
I've added addressing the hardcoded `pretty=true` query parameter to our team's internal backlog. Please feel free to reopen this if you have any further questions.
