### ISSUE TITLE
Lambda CreateFunction : Could not unzip uploaded file.

### ISSUE THREAD

**Issue by yukulelix** [aws/aws-sdk-php#673]
Hi, I'm unable to upload a zip via the PHP SDK of Lambda. It keeps on giving me this error : Could not unzip uploaded file. The zip file works great when uploaded directly from the console.

I tried :
```php
'Code' => array(
    'ZipFile' => base64_encode(file_get_contents($target_path))
)
```
```php
'Code' => array(
    'ZipFile' => $target_path
)
```
```php
'Code' => array(
    'ZipFile' => 'fileb://'.base64_encode(file_get_contents($target_path))
)
```
But nothing seems to work...
Any hints ?

**Comment by jeskew** [comment]
The SDK should be calling `base64_encode` for you, so you might be sending doubly encoded data in your first example. Did you try `'ZipFile' => file_get_contents($target_path)`?

**Comment by yukulelix** [comment]
This works, thanks !
The documentation said you need a base64 encoded zip so I didn't even think of it !

**Comment by Lickwid** [comment]
Mine requires that I have base64_encode or I get the error...Which version was this changed in?
