### ISSUE TITLE
Bug in Waiters documentation

### ISSUE THREAD

**Issue by neochief** [aws/aws-sdk-php#677]
Hello.

I'm not sure this is the right place to report the problem with docs on aws website, but there's a problem in waiters documentation on this page: http://docs.aws.amazon.com/aws-sdk-php/guide/latest/feature-waiters.html

It says:
> If the Waiter has to poll the bucket too many times, it will throw an Aws\Common\Exception\RuntimeException exception.

But apparently such exception does not exist anymore. Can you advice which exception I should handle in this case?

Also, you might update waiters definition of AWS Glasier on the bottom of that page, since it has changed. Plus, it might be super helpful if you place a [link to the actual waiter definition file](https://github.com/aws/aws-sdk-php/blob/master/src/data/glacier/2012-06-01/waiters-2.json) somewhere on the bottom of that example on documentation page. This way people like me will skip few hours of googling for where these definitions actually live.

Thanks!

**Comment by jeremeamia** [comment]
If you are using Version 3 of the SDK (V3), you should be looking at this page: http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/waiters.html. You can find the available waiters for a service in the V3 API docs, for example, here are Glacier's: http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-glacier-2012-06-01.html#waiters

All the links with "latest" in the URL are actually for V2, we are working on fixing links and adding redirects to clear up confusion there.

**Comment by neochief** [comment]
Ah, my bad, you're right. I was confused by going back and forth between google results and docs navigation. Thanks for the prompt reply, anyway!

**Comment by jeremeamia** [comment]
:smile:
