### ISSUE TITLE
Can't create a S3 client using sdk

### ISSUE THREAD

**Issue by jarrettj** [aws/aws-sdk-php#678]
Traced issue to line 105 in Sdk.php. It can't find the manifest() function.

```
$sdk = new Aws($config['aws']);
$s3Client = $sdk->createS3();
```

My composer file:
```
    "require": {
        "php": ">=5.5",
        "zendframework/zendframework": "2.5.*",
        "doctrine/doctrine-orm-module": "0.*",
        "doctrine/orm": "2.5.*@dev",
        "gedmo/doctrine-extensions": "2.4.*",
        "widmogrod/zf2-assetic-module": "dev-master",
        "doctrine/migrations": "1.0.*@dev",
        "zf-commons/zfc-user": "1.*",
        "zf-commons/zfc-user-doctrine-orm": "1.*",
        "bjyoungblood/bjy-authorize": "1.5.*@dev",
        "neilime/zf2-twb-bundle": "2.*@stable",
        "neilime/zf2-assets-bundle": "3.4.*",
        "natxet/CssMin": "3.0.*@dev",
        "linkorb/jsmin-php": "dev-master",
        "neeckeloo/newrelic": "dev-master",
        "aws/aws-sdk-php": "3.*",
        "aws/aws-sdk-php-zf2": "2.*"
    },
```

I've tried $s3 = new \Aws\S3\S3Client($config['aws']); as well. Same error.

Any help would be much appreciated.

Thanks.

Cheers.

**Comment by jeskew** [comment]
Loading the file containing that function is handled by composer, not the SDK. In what context are you seeing this issue?

**Comment by jarrettj** [comment]
Using zend framework 2. With composer. Very weird. Php version 5.5. Must be my environment.

**Comment by jeskew** [comment]
Is this by any chance happening during a composer-triggered script? They have a few outstanding issues related to the fact that files are not automatically loaded during composer scripts.

**Comment by jarrettj** [comment]
Nope. 

It's a normal controller in zend framework. I use composer install -o and I load the autoloader file as normal. Then I followed your sample docs on how to set up s3 client.

When I step through the code with a debugger it for some reason fails and can't find any functions in that function.php file.


Crap!

**Comment by jeskew** [comment]
Maybe running `composer self-update` would take care of this?

**Comment by jarrettj** [comment]
I did that already. Will try using another major version rather. A coworker used v2 with no problems. Will try that first. Thanks.

**Comment by jeskew** [comment]
You might also want to raise an issue with composer. v2 does not use Composer's files autoloader, you wouldn't run into this issue if you went that route.

**Comment by mtdowling** [comment]
We utilize Composer's autoload/files feature to automatically require the necessary PHP files when the Composer autoloader is required: https://github.com/aws/aws-sdk-php/blob/master/composer.json#L43. If Composer is working correctly and you are including the autoloader correctly, then it should work normally and include the files. If it is not working, then there may be something weird going on, possibly Composer or environment specific.

Here are a few questions I have:

1. What OS are you running?
2. Are you running any "global" composer installs of anything?
3. Can you show us the code you are using to require the composer autoloader?
4. Can you try setting up a basic test to see if you can create an empty project that uses the SDK?

**Comment by jarrettj** [comment]
I've been using composer with zend framework 2 since the beginning of this project. Composer is not an issue. Using many packages via composer.

1.) Ubuntu 13.10
2.) No. I don't even know what that is.
3)
```
Zend\Loader\AutoloaderFactory::factory(array(
    'Zend\Loader\ClassMapAutoloader' => array(
        'Composer' => __DIR__ . '/vendor/composer/autoload_classmap.php',
    )
));
```

I use composer update -o to generate the autoload_classmap.php file. It's a zf2 optimization. That way all the files needed are preloaded. 

I checked the composer vendor folder to see if the functions.php file is loaded, and it is. In the autoload_files.php file.

In my controller I do the following:
```
use Aws\Sdk as Aws;

$sdk = new Aws\Sdk($config['aws']);
$s3Client = $sdk->createS3();
```

The $config['aws'] has the following in it:
```
     'aws' => [
         'credentials' => [
             'key'    => '*****',
             'secret' => '*****'
         ],
         'region'   => 'us-east-1',
         'version'  => 'latest',
     ]
```

4.) I will try this. Like I said before, a coworker used v2.* in composer. And had no issues. Our projects use similar stacks. I will try that as well.

Thanks for the prompt responses.

Cheers.

**Comment by jeskew** [comment]
You will need to replace your custom autoloader with the standard composer autoloader (i.e., `vendor/autoload.php`). Only using the classmap is not compatible with the AWS SDK (or the Guzzle libraries it depends on). The composer autoloader will still use the optimized classmap generated by `composer update -o`.

**Comment by jarrettj** [comment]
Sorry for late reply. @jeskew you were correct.

For anyone using the same zf2 autoloader optimisation, add the following to your init_autoloader.php:
```
$includeFiles = require __DIR__ . '/vendor/composer/autoload_files.php';
foreach ($includeFiles as $file) {
    require $file;
}
```

Thanks to all. It's working now :)

Cheers.

**Comment by e-oz** [comment]
It's frustrating this library only works with Composer. Composer is too awful to use.

**Comment by jeremeamia** [comment]
@e-oz 

> It's frustrating this library only works with Composer.

Where did you get that impression? The README says:

> You can get started in minutes by [installing the SDK through Composer][docs-installation] or by *downloading a single zip or phar file from our [latest release][latest-release]* (emphasis added).

And further down it says:

> Using Composer is the recommended way to install the AWS SDK for PHP. (...) Please see the [Installation section of the User Guide][docs-installation] for more detailed information about *installing the SDK through Composer and other means.* (emphasis added)

And then when you go to the ["Installation section of the User Guide"][docs-installation], it has 3 sections: 

* Installing via Composer
* Installing via Phar
* Installing via Zip

-----

> Composer is too awful to use.

I think you might be in the minority on that opinion. Most would say that Composer makes it easier, not harder, to use third-party code. AFAIK, every major PHP library and framework has moved to using Composer for installation and autoloading. So, if you are interesting in using others' libraries, you better get used to the idea of using Composer. Also, the [Packagist stats][stats] are pretty interesting.

[docs-installation]: http://docs.aws.amazon.com/aws-sdk-php/v3/guide/getting-started/installation.html
[latest-release]: https://github.com/aws/aws-sdk-php/releases
[stats]: https://packagist.org/statistics

**Comment by e-oz** [comment]
@jeremeamia thanks, Phar fixed all issues! Sorry for taking your time and thanks for help.

**Comment by jeremeamia** [comment]
Happy to help. While I'll still believe Composer is the best option, the phar and zip options are good if you have an existing project that is setup in a way that makes Composer difficult to incorporate. I'm glad you have it working now.

**Comment by ferozfirru** [comment]
hi the autoloader is taking around 2mb memory and 0.5 to 0.7 seconds loading time, i want to use only S3 client, i dont want all other sdk classes how can i ?
