### ISSUE TITLE
PHP-FPM crashes with SIGSEGV on IamClient methods

### ISSUE THREAD

**Issue by ceedob** [aws/aws-sdk-php#683]
I'm working on a script to manipulate IAM users, and calling methods on IamClient crash php-fpm.
here's a specific example of code that triggered this behaviour:

```PHP
try{
    $client = IamClient::factory(array(
        'profile' => 'default', 
        'region' => 'us-west-2', 
        'version' => "2010-05-08" ));
    $groups = $client->listGroupsForUser(array('UserName' => "Chris")); // Crashes here
    var_dump($groups);
}
catch(Exception $e){
    var_dump($e);   
}
```
Note that I tried the above code on it's own in the cli php and it worked as expected, it's only when it's run through php-fpm that it crashes.

I haven't tried any other APIs beyond IAM on this particular setup yet. I did try downgrading to the 2.8 version of the api with composer with no success.

I'm running PHP-fpm 5.6 with nginx/1.8.0 from homebrew on OSX 10.11 Beta 3 (15A216g) 
```
$ php-fpm -v
PHP 5.6.10 (fpm-fcgi) (built: Jul  9 2015 12:22:41) (DEBUG)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

At first I thought it was an issue in the SDK, but upon further investigation it seems that the php-fpm process itself is crashing with a segfault which as far as I know shouldn't be possible with a bug PHP code alone, as opposed to in PHP itself.

I've got the phalcon framework, otherwise it's a pretty standard php config. Here's my phpinfo:
http://chrisdobson.ca/phpinfo.html

And here's the php-fpm crash log:
http://chrisdobson.ca/php-fpm_2015-07-10-123112_Chriss-MacBook-Pro.txt

Has anyone encountered this before? Can anyone recommend some known good versions of anything or a work-around for me to try? I realize this may be beyond the scope of this forum, if so please point me to a better place to ask about this.

**Comment by jeskew** [comment]
Do you see the same issue if you disable phalcon?

**Comment by mtdowling** [comment]
> I did try downgrading to the 2.8 version of the api with composer with no success.

This tells me that it's unlikely that this is an issue with the PHP SDK.

The only thing I can think of off the top of my head is that you could monitor the memory usage of the process to see if it's climbing. You could also step through using http://phpdbg.com/ to understand why it is segfaulting.

We haven't heard from you, so I'll go ahead and close this issue.
