### ISSUE TITLE
locationName is not being used

### ISSUE THREAD

**Issue by duncan3dc** [aws/aws-sdk-php#687]
It looks like when the [XmlParser](https://github.com/aws/aws-sdk-php/blob/c66b1cfa66feee34cc589a8c4583691b14f89c28/src/Api/Parser/XmlParser.php#L62) tries to get the `locationName`, the [ListShape](https://github.com/aws/aws-sdk-php/blob/c66b1cfa66feee34cc589a8c4583691b14f89c28/src/Api/ListShape.php#L28) class doesn't return it, because it's using the `member` element of the definition, and `locationName` is at the same level as `member` and not it's child.

This was discovered by calling the `S3Client::listObjectVersions()` method, and not getting any `DeleteMarkers` or `Versions` in the `Result` (because their location name is singular).

I tried to create a pull request, or even a failing test but couldn't get anything useful together sorry

**Comment by jeskew** [comment]
A likely fix was merged into master. Please reopen if you encounter this error again.
