### ISSUE TITLE
S3Client::doesBucketExist() always return true using GuzzleHandler with StreamHandler

### ISSUE THREAD

**Issue by okinaka** [aws/aws-sdk-php#693]
I try to use GuzzleHandler with StreamHandler for avoiding to use curl module.
But  S3Client::doesBucketExist() and doesObjectExist() return invalid results.

```php
$handler = new \Aws\Handler\GuzzleV6\GuzzleHandler(
  new \GuzzleHttp\Client(['handler' => new \GuzzleHttp\Handler\StreamHandler()])
);
$client = new \Aws\S3\Client(['http_handler' => $handler, ...]);

$actual = $client->doesBucketExist('invalid bucket name'); // => return true (always).
```

Because GuzzleHandler (using StreamHandler)  is fulfilled when response status code is 404 .
here: https://github.com/aws/aws-sdk-php/blob/master/src/Handler/GuzzleV6/GuzzleHandler.php#L42

**Comment by mtdowling** [comment]
You need to ensure that the handler you use with the SDK is throwing an exception when a non-200/300 response is received. This can be done when creating the Guzzle handler.

```php
use Aws\Handler\GuzzleV6\GuzzleHandler;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Handler\StreamHandler;

$handler = HandlerStack::create(new StreamHandler);
$wrappedHandler = GuzzleHandler($handler);
$client = new \Aws\S3\Client(['http_handler' => $wrappedHandler]);
```

**Comment by okinaka** [comment]
Thank you!
