### ISSUE TITLE
Sqs: The request must contain non-empty message attribute name.

### ISSUE THREAD

**Issue by MagicalTux** [aws/aws-sdk-php#694]
This looks a lot like error in https://github.com/aws/aws-sdk-go/issues/178

Using aws sdk v3.2

Demo code:
```php
$sqs = \Controller::Api('Aws')->spawn('Sqs', 'default', '2012-11-05');
$sqs->sendMessage([
        'QueueUrl' => $url,
        'MessageBody' => json_encode(['op' => 'noop']),
        'DelaySeconds' => 0,
        'MessageAttributes' => [
                'Format' => [
                        'StringValue' => 'json',
                        'DataType' => 'String',
                ],
        ],
]);
```

Result: "<?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>InvalidParameterValue</Code><Message>The request must contain non-empty message attribute name.</Message><Detail/></Error><RequestId>ab82bc9c-9b94-5ea2-afb3-f2bd1ce0c9ce</RequestId></ErrorResponse>"

Sent request: "Action=SendMessage&Version=2012-11-05&QueueUrl=https%3A%2F%2Fsqs.ap-northeast-1.amazonaws.com%2F133293341851%2Fplatform-i-f37160ea&MessageBody=%7B%22op%22%3A%22noop%22%7D&DelaySeconds=0&MessageAttributes.1.key=Format&MessageAttributes.1.value.StringValue=json&MessageAttributes.1.value.DataType=String"

As pointed out in the report on the Go version, it should be `MessageAttribute.1.name` rather than `MessageAttribute.1.key`.

**Comment by jeskew** [comment]
This has been merged to master. Thanks for reporting and testing out the change!
