### ISSUE TITLE
EC2 API pagination bug?

### ISSUE THREAD

**Issue by recipe** [aws/aws-sdk-php#699]
I am sure this is not right place for such questions but I think it worth at least ask for your opinion. What is wrong with this API query? Otherwise it should be bug on the AWS side. 

http://pastebin.com/DbQDiyzJ

**Comment by jeskew** [comment]
This does not appear to be a bug in the SDK. Filtering seems to happen after snapshots have been chunked into pages, so you can expect a finite number of zero-result pages if you use a filter that returns no results.

Perhaps if you try increasing the `MaxResults` value to something larger you should be able to verify that pagination does not continue infinitely.
