### ISSUE TITLE
Fatal error: Call to undefined method Aws\Command::createPresignedUrl()

### ISSUE THREAD

**Issue by ihorbovkit** [aws/aws-sdk-php#702]
I have 
```bash
Fatal error: Call to undefined method Aws\Command::createPresignedUrl()
```
with next code
```bash
$s3Creds = array('key' => AWS_KEY, 'secret' => AWS_SECRET, 'region' => 'ap-northeast-1');
$s3 = S3Client::factory($s3Creds);

//$photo->hashId is a 8 character alpha numeric string
$command = $s3->getCommand('PutObject', array(
    'Bucket'      => S3_BUCKET_NAME,
    'Key'         => $photo->hashId . '/raw.jpg',
    'ContentType' => 'image/jpeg',
    'Body'        => ''
));
$signedUrl = $command->createPresignedUrl('+50 minutes');
echo urldecode($signedUrl);
```
I'm using AWS SDK S3 - Release v2.1.39
Any advice?

**Comment by jeskew** [comment]
I don't have a copy of that release and am unable to reproduce. The closest I could find is [2.1.2](https://github.com/aws/aws-sdk-php/tree/2.1.2), which came out in February of 2013. Is there any chance you could upgrade? Our latest v2 release is [2.8.14](https://github.com/aws/aws-sdk-php/tree/2.8.14), and v3 (currently at [3.2.0](https://github.com/aws/aws-sdk-php/tree/3.2.0/)) came out a couple months ago.

**Comment by ihorbovkit** [comment]
Using s3.0.0 v3 - I did the following to get this to work.
$command = $s3->getCommand('GetObject', array(
            'Bucket'      => $this->customerBucket,
            'Key'         => $fileName,
            'ContentType' => 'image/png',
            'ResponseContentDisposition' => 'attachment; filename="'.$fileName.'"'
        ));
$signedUrl = $s3->createPresignedRequest($command, "+1 week");

**Comment by jeskew** [comment]
Glad upgrading helped. Please feel free to reopen if you have any further questions.
