### ISSUE TITLE
Lambda invoke fails at Guzzle's StatusCodeVisitor: Illegal string offset 'StatusCode'

### ISSUE THREAD

**Issue by bensigma** [aws/aws-sdk-php#704]
Hi,

We are using the 2.8.14 sdk (cannot move to 3.* b/c of php version requirements). There seems to be a bug in the aws lambda / guzzle code base: When i call our aws lambda function in the requestResponse mode as follows:
```
  $result = $this->lambda->invoke(array(
				// FunctionName is required
				'FunctionName' => $myFunctionArn,
				'InvocationType' => 'RequestResponse',
				'LogType' => 'None',
				'Payload' => '{"bar":"' . $bar . '"}',
			));
```
I get:
```
 Backtrace from E_WARNING 'Illegal string offset 'StatusCode'' at D:\foo\src\lib\vendor\guzzle\guzzle\src\Guzzle\Service\Command\LocationVisitor\Response\StatusCodeVisitor.php 25:

  D:\foo\tests\integration\AWSLambdaTestIT.php 17 calling myfunction()
  D:\foo\src\services\integration\AWSLambda.php 53 calling invoke()
  D:\foo\src\services\integration\AWSLambda.php 53 calling __call()
  D:\foo\src\lib\vendor\aws\aws-sdk-php\src\Aws\Common\Client\AbstractClient.php 104 calling __call()
  D:\foo\src\lib\vendor\guzzle\guzzle\src\Guzzle\Service\Client.php 76 calling getResult()
  D:\foo\src\lib\vendor\guzzle\guzzle\src\Guzzle\Service\Command\AbstractCommand.php 189 calling execute()
  D:\foo\src\lib\vendor\guzzle\guzzle\src\Guzzle\Service\Command\AbstractCommand.php 153 calling execute()
  D:\foo\src\lib\vendor\guzzle\guzzle\src\Guzzle\Service\Client.php 138 calling getResult()
  D:\foo\src\lib\vendor\guzzle\guzzle\src\Guzzle\Service\Command\AbstractCommand.php 193 calling process()
  D:\foo\src\lib\vendor\guzzle\guzzle\src\Guzzle\Service\Command\OperationCommand.php 87 calling parse()
  D:\foo\src\lib\vendor\guzzle\guzzle\src\Guzzle\Service\Command\DefaultResponseParser.php 39 calling handleParsing()
  D:\foo\src\lib\vendor\guzzle\guzzle\src\Guzzle\Service\Command\OperationResponseParser.php 86 calling visitResult()
  D:\foo\src\lib\vendor\guzzle\guzzle\src\Guzzle\Service\Command\OperationResponseParser.php 148 calling visit()
  D:\foo\src\lib\vendor\guzzle\guzzle\src\Guzzle\Service\Command\LocationVisitor\Response\StatusCodeVisitor.php 25 calling errorHandler()

```

My tmp fix in StatusCodeVisitor before the assignment:
```

		if (is_string($value)){
			$value = json_decode($value,true);
		}
```

Any ideas? Thxs!

**Comment by jeskew** [comment]
This looks related to #664. What return value are you sending back in your lambda call to `context.succeed`, and would it be possible to emit an object instead of a string?

**Comment by bensigma** [comment]
I'm using the node.js environment and there i'm returning a string currently. 
If i return a json object the conversion works. Have not seen that this is a requirement somewhere in the documentation. Thanks for the hint.

In case others stumble upon that: 
I get json data from an external php executable so that needs to be converted from bytes into its a string, which needs to be converted to a js JSON object - apparently:


php.stdout.on('data', function (data) {
        var mdata = data.toString();
        // must return json object - string will not be converted correctly in aws-sdk
        context.succeed(JSON.parse(mdata));
    });

**Comment by jeskew** [comment]
I don't believe it's mentioned anywhere in the PHP SDK documentation, but [Lambda passes all return values through `JSON.stringify`](http://docs.aws.amazon.com/lambda/latest/dg/programming-model.html#programming-model-context-object-succeed), so you were actually ending up with double-encoded values (on which the SDK was only calling `json_decode` once).
