### ISSUE TITLE
Port InstanceMetadataClient to v3 [Migrated from AWS forums]

### ISSUE THREAD

**Issue by jeskew** [aws/aws-sdk-php#711]
In v2, we provided an InstanceMetadataClient the could be used to fetch information from the EC2 metadata service about an instance. The major use case was IAM credentials, which has been ported to `Aws\Credentials\InstanceProfileProvider`, but other information was made available to instances, notably in which availability zone an instance was located and public and local hostnames and ipv4 addresses. 

Developers can still access the metadata service using a Guzzle client, but the experience isn't as smooth as it was in v2.

**Comment by jeremeamia** [comment]
If we had a model, we wouldn't have to handwrite it, and we could generate docs.

**Comment by jeskew** [comment]
The service doesn't implement a supported protocol, so a model would be of limited value. (Also, we would have to handwrite the model.)

**Comment by jeskew** [comment]
Without a model, this would just be an instance of `GuzzleHttp\Client` with the appropriate base url set. Since this URL is available as a constant on `Aws\Credentials\InstanceProfileProvider`, this client would be little more than:

```php
class InstanceMetadataClient
{
    private $client;

    public function __construct()
    {
        $this->client = new \GuzzleHttp\Client([
            'base_uri' => \Aws\Aws\Credentials\InstanceProfileProvider::SERVER_URI
        ]);
    }

    public function get($path)
    {
        return $this->client->get($path);
    }
}
```

I'm not sure how much value that adds. Closing for now, but it can be revisited if demand exists.

**Comment by benconnito** [comment]
The value it might have is that it would be compatible with 2.* versions of the SDK
