### ISSUE TITLE
__call definition

### ISSUE THREAD

**Issue by iam-merlin** [aws/aws-sdk-php#715]
Hi,
Simple request to drop default values for __call in Aws\Sdk.

The `__call` method's `$args` parameter is required and will always be present as an array (http://www.php.net/manual/en/language.oop5.overloading.php#object.call), adding a default value (like `$args = array()`) is not needed and even causes problems, as described in padraic/mockery#263.

Removing this allows us to manipulate the object as expected with mock.

Thank you (I can PR if you want)

**Comment by iam-merlin** [comment]
For reference (same issue on a different class with merge) : https://github.com/aws/aws-sdk-php/pull/92

**Comment by jeskew** [comment]
Thanks for reporting; the attached PR will go out in the next release.
