### ISSUE TITLE
Is MetaData ignored in Aws\S3\S3Client::putObject() ?

### ISSUE THREAD

**Issue by r3wt** [aws/aws-sdk-php#717]
```php
$s3->putObject([
	'Bucket'=>$bucket,
	'Key'=>$key,
	'Body'=>$body,
	'CacheControl'=>'max-age=172800',
	'MetaData'=>[
		'Content-Type'=>$mime
	]
]);
```
Object always show up with `application/octet-stream` instead of the correct values.

**Comment by jeremeamia** [comment]
You should be using the `ContentType` parameter, not `MetaData` for this, as documented in the [V2](http://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.S3.S3Client.html#_putObject) and [V3](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#putobject) API reference for `PutObject`. Example: 
```php
$s3->putObject([
	'Bucket'=>$bucket,
	'Key'=>$key,
	'Body'=>$body,
	'CacheControl'=>'max-age=172800',
	'ContentType'=>$mime
]);
```

**Comment by r3wt** [comment]
@jeremeamia It is still not working

**Comment by jeskew** [comment]
@r3wt Can you share the code that isn't working? If I execute the following:
```php
$firstVersion = $s3->putObject([
    'Bucket' => <my-bucket>,
    'Key' => 'response.xml',
    'Body' => fopen(__DIR__ . '/response.xml', 'r'),
    'ContentType' => 'application/xml',
]);
```
then responses to a `GetObject` operation come back with a header of `Content-Type: application/xml`.

**Comment by r3wt** [comment]
```php
$s3->putObject([
	'Bucket'=>$bucket,
	'Key'=>$key,
	'Body'=>$body,
	'CacheControl'=>'max-age=172800',
	'Content-Type'=>$mime
]);
```

where `$bucket` is the target bucket, `$key` is a string, `$body` is a blog, and `$mime` is one of following possible types:

```
image/png
image/jpeg
image/gif
```
When accessing image directly, the browser prompts for a file download. this is not correct file serving.

**Comment by jeskew** [comment]
The content type should be provided to putObject as `ContentType`, not `Content-Type`. Does making that change fix the issue?

**Comment by r3wt** [comment]
@jeskew i can make the change, but what can i do about images that are uploaded already? we have around 10k files uploaded already.

**Comment by jeskew** [comment]
To change the metadata on an object in S3, you'll need to copy the object over itself and pass in a `MetadataDirective` of `REPLACE`. This script would replace the content type on a single object:
```php
use PHPUnit_Framework_Assert as Assert;

$s3 = new \Aws\S3\S3Client([
    'region' => '<region>',
    'version' => 'latest',
]);
$bucket = '<bucket>';
$key = '<key>';

$s3->putObject([
    'Bucket' => $bucket,
    'Key' => $key,
    'Body' => fopen(__FILE__, 'r'),
]);

$metadata = $s3->headObject([
    'Bucket' => $bucket,
    'Key' => $key,
]);

Assert::assertEquals('application/octet-stream', $metadata['ContentType']);

$s3->copyObject([
    'Bucket' => $bucket,
    'Key' => $key,
    'CopySource' => "$bucket/$key",
    'ContentType' => 'image/png',
    'MetadataDirective' => 'REPLACE',
]);

$metadata = $s3->headObject([
    'Bucket' => $bucket,
    'Key' => $key,
]);

Assert::assertEquals('image/png', $metadata['ContentType']);
```

**Comment by yvele** [comment]
@jeskew I'm glad I found your answer here because [the doc](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#copyObject-property) is not clear about that.

It's so confusing :
 * There is a **Metadata**, a **ContentType** and a  **MetadataDirective** field
 * If I only pass a **ContentType** nothing appends.. Not even an error
 * Even I don't pass  **Metadata**, I have to pass **MetadataDirective** in order to update **ContentType**
 * **ContentType** update does not have the same behaviour as other header (eg ContentEncoding)
