### ISSUE TITLE
Flush redis / memcached

### ISSUE THREAD

**Issue by keithbmcd** [aws/aws-sdk-php#720]
Hi,

Is there any example of flushing redis / memcached?

should it be class MemcachedCache extends CacheProvider or class RedisCache extends CacheProvider
 ?

thanks

**Comment by jeskew** [comment]
Hi,

This project provides support for creating and managing Redis and Memcached instances through Amazon ElastiCache but does not ship with any clients for interacting with them. `CacheProvider` looks like it's from the `doctrine/cache` package, which comes with prebuilt implementations of Redis- and Memcached-based cache clients, both of which are flushable. You can read more in [their documentation](http://doctrine-orm.readthedocs.org/en/latest/reference/caching.html).

**Comment by keithbmcd** [comment]
thanks jeskew!
