### ISSUE TITLE
Cannot install from zip

### ISSUE THREAD

**Issue by Dynamo6** [aws/aws-sdk-php#721]
Hi guys, I'm having some problems installing the SDK from the zip version. The instructions on Amazon 's website (http://docs.aws.amazon.com/aws-sdk-php/v3/guide/getting-started/installation.html) tell me to download the latest zip from https://github.com/aws/aws-sdk-php/releases then include autoloader.php .... however this file does not appear in the latest zip (3.2.5) Can anyone point me in the right direction please?

I'd really rather not have to use Composer if possible. Thanks, Mike

**Comment by jeskew** [comment]
The autoloader file will only appear in the `aws.zip` file, not the download labelled `Source Code (Zip)`. `Aws.zip` also contains the SDK's resolved dependencies so that you don't have to rely on composer to pull those down.
