### ISSUE TITLE
Fatals on Waiters occasionally

### ISSUE THREAD

**Issue by onethumb** [aws/aws-sdk-php#726]
We see intermittent PHP crashes with `Call to member function getStatusCode() on null` from this line:  https://github.com/aws/aws-sdk-php/blob/master/src/Waiter.php#L245

Since `$result->getResponse()` can return a `ResponseInterface` or `NULL`, checking the result first alleviates the problem.  Example:

```php 
$response = $result->getResponse(); // this sometimes returns NULL
    if(isset($response)) {
        return $acceptor['expected'] == $response->getStatusCode();
    }
```

**Comment by jeskew** [comment]
If the response is null, that would generally mean that an error was raised by the HTTP handler. I added a separate check to make sure that exceptions without responses are retried within the waiter's maxAttempts limit.
