### ISSUE TITLE
Route53 API error - Credential should be scoped to a valid region

### ISSUE THREAD

**Issue by pako-pl** [aws/aws-sdk-php#732]
I cannot access Route53 Health Checks list using AWS SDK for PHP v3. The following code:

```
$route53Client = new Aws\Route53\Route53Client([
        'credentials' => [ ... ],
        'region' => 'eu-central-1',
        'version' => '2013-04-01'
    ]);
    $result = $route53Client->listHealthChecks([
        'MaxItems' => '100',
    ]);
```

causes this error:

```
Error executing "ListHealthChecks" on "https://route53.amazonaws.com/2013-04-01/healthcheck?maxitems=100"; AWS HTTP error: Client error: 403 SignatureDoesNotMatch (client): Credential should be scoped to a valid region, not 'eu-central-1'.```

**Comment by pako-pl** [comment]
Edit: Changing "region" to "us-east-1" fixed the problem. Maybe it should be included in the documentation?

**Comment by jeskew** [comment]
There are a few services that have global endpoints and have to be signed with the `us-east-1` region, including Route53, CloudFront, IAM, and STS. Let me make sure I have a complete listing, and I'll add this information to the documentation.

**Comment by jeskew** [comment]
I added this to the SDK guide in #739. Please feel free to reopen if you have any further questions.

**Comment by deepikaguptasi** [comment]
I am using php curl and sending region us-east-1 in route 53 and getting the error message "Credential should be scoped to correct service: 'route53'".
Please help me out asap.
Thanks
