### ISSUE TITLE
Delete all files in a bucket

### ISSUE THREAD

**Issue by yukulelix** [aws/aws-sdk-php#740]
Hi,
In previous versions, to clear all files in a bucket, I just had to do :
```php
$clearBucket = new ClearBucket($s3Client, $slug);
$clearBucket->clear();
```
Is there a simple way to do that now that ClearBucket has been removed ?
Cheers !

**Comment by jeskew** [comment]
There's a `Aws\S3\BatchDelete` class that will clear a bucket with a static method call. Try calling `BatchDelete::fromListObjects($s3Client, ['Bucket' => $bucketName])->delete();`
