### ISSUE TITLE
Debugging using a StreamHandler with S3 doesn't work

### ISSUE THREAD

**Issue by onethumb** [aws/aws-sdk-php#745]
If we enable `debug` with a `logfn` in our SDK config, like the example here (http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#debug) and then call `S3::getObject()` with `['@http']['stream']=true` such that it uses the Guzzle StreamHandler, we get a ton of log spew on each request that looks like:

```
[10-Aug-2015 14:56:10 America/Los_Angeles]  Warning: trigger_error 'fprintf(): 4 is not a valid stream resource'  in Composer/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php on line 380 
[10-Aug-2015 14:56:10 America/Los_Angeles]  Warning: trigger_error 'fwrite(): 4 is not a valid stream resource' in /Composer/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php on line 382
[10-Aug-2015 14:56:10 America/Los_Angeles]  Warning: trigger_error 'fwrite(): 4 is not a valid stream resource' in /Composer/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php on line 382
... etc ...
```

A quick look at the closure there suggests that `$value` is a stream resource at some point, but then changes.  We haven't dug any deeper at this point.

**Comment by onethumb** [comment]
Current working theory is that it's being cast to a string at some point, but it doesn't look like our code is doing the casting, so might be in the SDK somewhere?

**Comment by jeskew** [comment]
`$value` should be a handle on `php://temp` opened in [`Aws\TraceMiddleware`](https://github.com/aws/aws-sdk-php/blob/master/src/TraceMiddleware.php#L269). Is there any chance the commands are being serialized and executed later?

**Comment by onethumb** [comment]
I don't think so, we're getting & executing the command immediately, and I don't see any way it could be getting serialized.  This chunk of code is pretty simple.  If you're not able to reproduce, I'll see if I can extract the relevant bits into a standalone test case.

**Comment by jeskew** [comment]
@onethumb That would be great if you could.

**Comment by jeskew** [comment]
@onethumb Any chance you could provide a test case?

**Comment by jeskew** [comment]
@onethumb I was taking a look at old issues today and think I found what's going on with this one: I believe that the script generating the error is closing the resource at `STDOUT`. Guzzle's `debug_resource` function will use `STDOUT` if it is available but assumes it will not be closed, as the CLI SAPI is supposed to open `STDOUT` at the start of a script and close it at the end. The general error can reproduced by running the following:

```php
<?php

defined('STDOUT') || define('STDOUT', fopen('php://stdout', 'w'));
define('STDOUT2', fopen('php://stdout', 'w'));

function checkStdOut() {
    if (is_resource(STDOUT)) {
        fwrite(STDOUT2, "Resource!<br/>\n");
    } else {
        fwrite(STDOUT2, "Not a resource: " . (int) STDOUT . "<br/>\n");
    }
}

checkStdOut();

fclose(STDOUT);

checkStdOut();
```
