### ISSUE TITLE
Please use guzzlehttp/guzzle on the 2.8 branch

### ISSUE THREAD

**Issue by fbm-static** [aws/aws-sdk-php#746]
Instead of guzzle/guzzle, it appears deprecated.

**Comment by skyzyx** [comment]
At a very fundamental level, it's not going to happen. The guts of SDK v2 are tied tightly to Guzzle v3.

Instead, the current release of the SDK (v3) supports Guzzle v5 and Guzzle v6.

**Comment by GrahamCampbell** [comment]
Exactly. The 2.8 branch is deprecated too tbh.

**Comment by fbm-static** [comment]
You can use https://packagist.org/packages/guzzlehttp/guzzle#v3.8.1. It sucks having the need to make our app 5.3.x compatible

**Comment by GrahamCampbell** [comment]
TLDR is nobody should be starting a new app using anything less than php 5.5.

**Comment by jeskew** [comment]
Is there a particular reason you need to use the 2.8 branch? Migrating from guzzle 3 required a complete rewrite, which is what's in the master branch.

**Comment by GrahamCampbell** [comment]
I think he means the 2.8 of the aws sdk, not guzzle?

**Comment by fbm-static** [comment]
I was assuming that the 2.8 branch (where a new version was released 9 days ago) was for 5.3 compatibility, I checked newer versions but they're requiring newer PHP versions. I was just hoping the `guzzle/guzzle` dependency could be renamed to `guzzlehttp/guzzle` of the same version since other packages are now using that package instead of the now deprecated one (of which I don't know the reason why).

https://github.com/aws/aws-sdk-php/blob/2.8/composer.json#L20

**Comment by jeskew** [comment]
It's not just for 5.3 compatibility; it's the source for all v2 releases. As much as we'd like everybody to have already upgraded to v3, it only came out a few months ago, so a large number of projects are still relying stable 2.8.* releases. 

The original reason for renaming `guzzle/guzzle` to `guzzlehttp/guzzle` was so that you could use both in a composer-managed project. I've seen several applications in the wild use v2 of the AWS SDK (and thus rely on Guzzle 3) as well as a more modern version of Guzzle (for instance, as a dependency of Goutte), so a legitimate purpose is being served by using `guzzle/guzzle`.

**Comment by fbm-static** [comment]
I think you are misunderstanding my point here, I just wanted `guzzle/guzzle` to be renamed to `guzzle/guzzlehttp` ( no version change).

**Comment by jeskew** [comment]
I get it, but having v2 of the SDK use `guzzle/guzzle` means that your application can depend on other libraries (such as [Goutte](https://packagist.org/packages/fabpot/goutte), [Payum](https://packagist.org/packages/payum/payum), [Elastica](https://packagist.org/packages/ruflin/elastica), or SDKs for other APIs like [Auth0](https://packagist.org/packages/auth0/auth0-php)) that require a different version of Guzzle. 

If 2.8 switched its dependency from `guzzle/guzzle` to `guzzlehttp/guzzle`, it would no longer with any of those libraries.

**Comment by GrahamCampbell** [comment]
> I think you are misunderstanding my point here, I just wanted guzzle/guzzle to be renamed to guzzle/guzzlehttp ( no version change).

That's no possible.

**Comment by skyzyx** [comment]
@fbm-static: That will absolutely not happen. Sorry.

Having said that, security fixes for PHP 5.4 end in approximately 2 weeks. Running any version of PHP earlier than 5.5 is simply irresponsible at this point.

**Comment by fbm-static** [comment]
Thanks guys.
