### ISSUE TITLE
Get headers of multipart upload 

### ISSUE THREAD

**Issue by Sensirex** [aws/aws-sdk-php#747]
Hello
After updating aws php sdk from 2.3 to 2.8 I received some errors:
-You must specify a non-null value for the body...
-something about the secret key

Found a couple of places responsible for these errors
Made a small change and now all is well:

\Aws\Common\Client\UploadBodyListener.php line 72   function onCommandBeforePrepare
changed it
```php
if (null !== $body) {
		$command->remove($this->sourceParameter);
		$command->set($this->bodyParameter, EntityBody::factory($body));
} else {
		throw new InvalidArgumentException("You must specify a non-null value for the {$this->bodyParameter} or {$this->sourceParameter} parameters.");
}
```					
to
```php
if (null !== $body)
	$body = EntityBody::factory($body);
$command->remove($this->sourceParameter);
$command->set($this->bodyParameter, $body);
```
\Aws\S3\S3Signature.php  line 64  function signRequest
changed it
```php
$request->removeHeader('x-amz-date');
$request->setHeader('Date', gmdate(\DateTime::RFC2822));
```				
to
```php
if (!$request->hasHeader('date') && !$request->hasHeader('x-amz-date')) {
		$request->setHeader('Date', gmdate(\DateTime::RFC2822));
}
```

Can anyone tell why were these changes, or how another receive headers??
The authors of the sdk, please revert this as before

MY CODE 

FIRST STEP
1. init S3Client
2. create multipart upload
3. sending upload_id and key to client

```php
$client = S3Client::factory(array(
        'key' => AWS_KEY,
        'secret' => AWS_SECRET,
				'region' => AWS_REGION
    ));

/*.......................*/

$model = $client->createMultipartUpload(array(
				'Bucket' => $my_bucket,
				'Key' => $file_key,
				'StorageClass' => STORAGE_CLASS
		));
		
		
		
sendJson(array(
				'uploadId' => $model->get('UploadId'),
				'key' => $model->get('Key'),
		));
```		
		
		
SECOND STEP
1. init S3Client
2. create UploadPart command
3. processing command
4. sending headers to client
5. The client sends own file with our headlines (source not present)

```php
$client = S3Client::factory(array(
        'key' => AWS_KEY,
        'secret' => AWS_SECRET,
				'region' => AWS_REGION
    ));

/*.......................*/

$command = $client->getCommand('UploadPart',
				array(
				'Bucket' => BUCKET_NAME,
				'Key' => $_REQUEST['sendBackData']['key'],
				'UploadId' => $_REQUEST['sendBackData']['uploadId'],
				'PartNumber' => $_REQUEST['partNumber'],
				'ContentLength' => $_REQUEST['contentLength']
		));
		
		
$request = $command->prepare();
$client->dispatch('command.before_send', array('command' => $command));
$request->removeHeader('User-Agent');
$request->setHeader('x-amz-date', gmdate(DateFormat::RFC2822));
$client->dispatch('request.before_send', array('request' => $request));


sendJson(array(
		'url' => $request->getUrl(),
		'authHeader' => (string) $request->getHeader('Authorization'),
		'dateHeader' => (string) $request->getHeader('x-amz-date'),
		'PartNumber' => $_REQUEST['partNumber'],
));
```

**Comment by jeskew** [comment]
2.3 to 2.8 is a big upgrade with some backwards-incompatible changes (we didn't start adhering to strict semantic versioning until 3.0). Are you trying to send an empty body with an `UploadPart` request?

**Comment by Sensirex** [comment]
I trying get 
uploadId and key on first step
headers "Authorization" and "x-amz-date" on second step

send it to client
Client uploads the file yourself using headers (second step), uploadId and key (first step).

After the update, this method stopped working.
In response, i received the error:
-You must specify a non-null value for the body... (first step)
-something about the secret key   (second step)

small changes in SDK have corrected it, but I think there is another way, am i right?

**Comment by jeskew** [comment]
I see. The officially supported way to orchestrate a client-side upload is to use [pre-signed URLs](http://docs.aws.amazon.com/aws-sdk-php/v2/guide/service-s3.html#creating-a-pre-signed-url). Doing so will remove the need to manually dispatch and intercept client events and will also ensure that you don't sign the request with the wrong body.

**Comment by Sensirex** [comment]
Thanks a lot, it work great :)
