### ISSUE TITLE
SDK 3.* S3 Transfer failed to open stream: Too many open files

### ISSUE THREAD

**Issue by torfeld6** [aws/aws-sdk-php#749]
I'm trying to upload a folder with a thousand files in it and the following error is being thrown:
    
    Exception 'RuntimeException' with message 'Unable to open /var/folders/r8/b44k7lxn1f946dym5134flgr0000gn/T/91785_1435731177/iPadOnly/Slide6_tn.jpg using mode r: fopen(    /var/folders/r8/b44k7lxn1f946dym5134flgr0000gn/T/91785_1435731177/iPadOnly/Slide6_tn.jpg): failed to open stream: Too many open files'
    
    in /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/psr7/src/functions.php:275
    
    Stack trace:
    #0 [internal function]: GuzzleHttp\Psr7\{closure}(2, 'fopen(/var/fold...', '/Users/josh/Doc...', 283, Array)
    #1 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/psr7/src/functions.php(283): fopen('/var/folders/r8...', 'r')
    #2 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/psr7/src/LazyOpenStream.php(37): GuzzleHttp\Psr7\try_fopen('/var/folders/r8...', 'r')
    #3 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/psr7/src/StreamDecoratorTrait.php(31): GuzzleHttp\Psr7\LazyOpenStream->createStream()
    #4 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/psr7/src/StreamDecoratorTrait.php(81): GuzzleHttp\Psr7\LazyOpenStream->__get('stream')
    #5 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/aws/aws-sdk-php/src/Middleware.php(202): GuzzleHttp\Psr7\LazyOpenStream->getMetadata('uri')
    #6 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/aws/aws-sdk-php/src/S3/ApplyChecksumMiddleware.php(71): Aws\Middleware::Aws\{closure}(Object(Aws\Command), Object(GuzzleHttp\Psr7\Request)    )
    #7 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/aws/aws-sdk-php/src/ClientResolver.php(475): Aws\S3\ApplyChecksumMiddleware->__invoke(Object(Aws\Command), Object(GuzzleHttp\Psr7\Request)    )
    #8 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/aws/aws-sdk-php/src/Middleware.php(95): Aws\ClientResolver::Aws\{closure}(Object(Aws\Command), Object(GuzzleHttp\Psr7\Request))
    #9 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/aws/aws-sdk-php/src/Middleware.php(79): Aws\Middleware::Aws\{closure}(Object(Aws\Command), NULL)
    #10 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/aws/aws-sdk-php/src/S3/S3Client.php(444): Aws\Middleware::Aws\{closure}(Object(Aws\Command), NULL)
    #11 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/aws/aws-sdk-php/src/S3/S3Client.php(463): Aws\S3\S3Client::Aws\S3\{closure}(Object(Aws\Command), NULL)
    #12 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/aws/aws-sdk-php/src/Middleware.php(53): Aws\S3\S3Client::Aws\S3\{closure}(Object(Aws\Command), NULL)
    #13 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/aws/aws-sdk-php/src/S3/SSECMiddleware.php(59): Aws\Middleware::Aws\{closure}(Object(Aws\Command), NULL)
    #14 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/aws/aws-sdk-php/src/AwsClient.php(208): Aws\S3\SSECMiddleware->__invoke(Object(Aws\Command))
    #15 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/aws/aws-sdk-php/src/S3/Transfer.php(300): Aws\AwsClient->executeAsync(Object(Aws\Command))
    #16 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/aws/aws-sdk-php/src/S3/Transfer.php(284): Aws\S3\Transfer->upload('/var/folders/r8...')
    #17 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/aws/aws-sdk-php/src/functions.php(52): Aws\S3\Transfer->Aws\S3\{closure}('/var/folders/r8...')
    #18 [internal function]: Aws\map(Object(Generator), Object(Closure))
    #19 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/EachPromise.php(168): Generator->next()
    #20 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/EachPromise.php(184): GuzzleHttp\Promise\EachPromise->advanceIterator()
    #21 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/EachPromise.php(150): GuzzleHttp\Promise\EachPromise->step(238)
    #22 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(199): GuzzleHttp\Promise\EachPromise->GuzzleHttp\Promise\{closure}(Object(Aws\Result))
    #23 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(152): GuzzleHttp\Promise\Promise::callHandler(1, Object(Aws\Result), Array)
    #24 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/TaskQueue.php(60): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
    #25 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\Promise\TaskQueue->run()
    #26 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick()
    #27 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(240): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
    #28 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(217): GuzzleHttp\Promise\Promise->invokeWaitFn()
    #29 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(261): GuzzleHttp\Promise\Promise->waitIfPending()
    #30 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(219): GuzzleHttp\Promise\Promise->invokeWaitList()
    #31 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(261): GuzzleHttp\Promise\Promise->waitIfPending()
    #32 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(219): GuzzleHttp\Promise\Promise->invokeWaitList()
    #33 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
    #34 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/EachPromise.php(90): GuzzleHttp\Promise\Promise->wait()
    #35 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(240): GuzzleHttp\Promise\EachPromise->GuzzleHttp\Promise\{closure}(true)
    #36 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(217): GuzzleHttp\Promise\Promise->invokeWaitFn()
    #37 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
    #38 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/aws/aws-sdk-php/src/S3/Transfer.php(153): GuzzleHttp\Promise\Promise->wait()
    #39 /Users/josh/Documents/Workspace/pitcher-zerodrive/models/ExtractedFile.php(151): Aws\S3\Transfer->transfer()
    #40 /Users/josh/Documents/Workspace/pitcher-zerodrive/commands/ExtractController.php(24): app\models\ExtractedFile->extract()
    #41 [internal function]: app\commands\ExtractController->actionFile('91785')
    #42 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
    #43 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
    #44 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('file', Array)
    #45 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('file', Array)
    #46 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('extract/file', Array)
    #47 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('extract/file', Array)
    #48 /Users/josh/Documents/Workspace/pitcher-zerodrive/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
    #49 /Users/josh/Documents/Workspace/pitcher-zerodrive/yii(24): yii\base\Application->run()
    #50 {main}
 
The code is fairly simple:

    $source = "/tmp/folder";
    $dest = "s3://bucket/key/";
    $options = ["concurrency" => 5];

    $manager = new Transfer($s3Client, $source, $dest, $options);
    $res = $manager->transfer(); 

I think the file handlers are not being closed correctly.

**Comment by jeskew** [comment]
Out of curiosity, do you see the same issue of you drop the concurrency to 1 or 2? If so, that would point firmly in the direction of file handles being left open.

**Comment by torfeld6** [comment]
I actually did try dropping the concurrency to one, but same issue.

**Comment by jeskew** [comment]
What appears to be happening is that you're hitting your file descriptor limit before PHP starts a garbage collection cycle. Each of the files handled by the transfer manager gets converted to an instance of `GuzzleHttp\Psr7\Stream`, which takes care of the resource lifecycle with a standard RAII pattern -- the class will [close the handle in its `__destruct` method](https://github.com/guzzle/psr7/blob/master/src/Stream.php#L87). That method will be called when the garbage collector tries to reclaim memory, which doesn't happen automatically until the PHP engine has identified 10,000 zvals as potentially garbage. OS X has a file descriptor limit of 1024, so you'd hit that first if you're running a simple script that just uploads a directory.

I'm looking into how to fix this is the long term, but for now you have two options: 

1. Disable garbage collection, or 
* Trigger it before every file upload.

PHP lets you turn off its cyclic garbage collector by calling `gc_disable()`. This will make PHP use refcounted garbage collection instead, meaning that an object's memory will be freed and its destructor called as soon as it falls out of scope. The danger with this approach is that circular references created while the garbage collector is turned off will not be detected, even if you turn the GC back on after finishing your upload. (If you're running a simple script (or handling a request) that terminates right after the upload finishes anyway, this would probably be your easiest option.)

If you'd rather not turn off the GC or if the upload is the first step of a multi-step workflow, you can have the transfer manager manually trigger garbage collection before initiating each individual upload. Given the code you posted above, that option would look like this:
```php
$source = "/tmp/folder";
$dest = "s3://bucket/key/";
$options = [
    "concurrency" => 5,
    'before' => 'gc_collect_cycles',
];

$manager = new Transfer($s3Client, $source, $dest, $options);
$res = $manager->transfer();
```

You might want to check out [the PHP manual's description of how the GC works](http://php.net/manual/en/features.gc.collecting-cycles.php) before deciding which option makes the most sense for your application.
