### ISSUE TITLE
Use of undefined constant CURLE_COULDNT_RESOLVE_HOST

### ISSUE THREAD

**Issue by dfedde** [aws/aws-sdk-php#75]
I have been working with amazon S3 for media storage for a e-commerce site but I ran into this error and have no idea how to fix it:

Use of undefined constant CURLE_COULDNT_RESOLVE_HOST - assumed 'CURLE_COULDNT_RESOLVE_HOST'

NEW CurlBackoffStrategy 

File: /var/api/vendor/aws/aws-sdk-php/src/Aws/S3/S3Client.php
Line: 188

I'm assuming this is software incompatibility some were but I'm no sure where to look.

This code dose work on my local test environment but when the server gets it, it just fails. I have updated PHP and, curl to the same as my test environment but to no avail.

curl 7.22.0 php 5.4.14-1 are the versions I'm using.

**Comment by eliasdelatorre** [comment]
I was getting the same error after installing PHP 5.6 on Ubuntu 18.04 which, by default, comes with PHP 7.2 I forgot to install php5.6-curl when installing all the required libraries. I was using simple Drupal db_query function that stopped working after the PHP downgrade. Installing cURL worked.
