### ISSUE TITLE
Upgrade Guzzle

### ISSUE THREAD

**Issue by jlestel** [aws/aws-sdk-php#752]
Hi, 

Did you plan to upgrade Guzzle ?

I have got incompatibilities with HHVM and last Guzzle version resolve it : https://github.com/guzzle/guzzle/blob/master/CHANGELOG.md

**Comment by GrahamCampbell** [comment]
The latest version of guzzle IS used.

**Comment by jlestel** [comment]
I still have differences between files in Guzzle last version (https://github.com/guzzle/guzzle) and your last release (https://github.com/aws/aws-sdk-php/releases/tag/3.3.4).

**Comment by GrahamCampbell** [comment]
Not sure why. Ping @jeremeamia @mtdowling @jeskew.

**Comment by jeskew** [comment]
The phar and zip downloads for version 3.3.4 of the SDK include version 6.0.2 of Guzzle, which is the latest stable release. There are some changes in the master branch of Guzzle that have not yet made it into a release yet; those are listed [here](https://github.com/guzzle/guzzle/compare/6.0.2...master).

If you're using the phar, you can verify this by navigating to the folder in which `aws.phar` is located and running `php -r 'require "aws.phar"; echo GuzzleHttp\ClientInterface::VERSION . "\n";'`.

**Comment by jlestel** [comment]
Ok @jeskew !

Thank's for the quick reply.
