### ISSUE TITLE
Renaming large files using PHP StreamWrapper

### ISSUE THREAD

**Issue by lonormaly** [aws/aws-sdk-php#759]
I try to "move" or "rename" large file (>5GB) from one bucket to the other.
The operation succeed on files smaller than 5GB but fails on bigger.
Does the rename operation of the StreamWrapper supports larger files?

rename('s3://'.S3_TEMP_BUCKET_MEDIA.'/'.$tempPath, 's3://'.S3_BUCKET_MEDIA.'/'.$path);

If not, what is the proper way of doing it?

P.S - I started from MultipartUpload but it doesn't seem right...

Cheers

**Comment by jeskew** [comment]
Which version of the SDK are you using?

**Comment by lonormaly** [comment]
Latest - 3.3.4

**Comment by jeskew** [comment]
`rename` should work the way you're using it. Does the operation fail silently, or do you get an error and stack trace?

**Comment by lonormaly** [comment]
Silently I guess... I don't get any notification about its success or failure; I waited more than an hour and checked at the target path and the file wasn't there so I assumed it failed.

Did you try it on large files (I tried on 18GB file)

**Comment by jeskew** [comment]
`rename` would emit warnings and return `false` instead of throwing an exception (similar to what would happen when operating on local files). Did the function return `true` and not send anything to your PHP/Nginx/Apache logs?

**Comment by lonormaly** [comment]
It didn't return anything. 
I waited long time.
Should the operation take few ms or should I expect to wait minutes / (hours?)

**Comment by jeskew** [comment]
It's a blocking operation that always returns a boolean value. On a file system, rename operations can fail for a number of reasons (permissions, nonexistent destination directories, etc), which will cause `rename` to [return false](http://php.net/manual/en/function.rename.php).

Once the function returns, the operation will have either succeeded or failed. You wouldn't have to wait.

**Comment by lonormaly** [comment]
I'm aware of that, still what I described occurred repeatedly...

Did you try to rename large files yourself?

On Friday, September 11, 2015, Jonathan Eskew <notifications@github.com>
wrote:

> It's a blocking operation that always returns a boolean value. On a file
> system, rename operations can fail for a number of reasons (permissions,
> nonexistent destination directories, etc), which will cause rename to return
> false <http://php.net/manual/en/function.rename.php>.
>
> Once the function returns, the operation will have either succeeded or
> failed. You wouldn't have to wait.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aws/aws-sdk-php/issues/759#issuecomment-139417708>.
>


-- 
Thanks
       Shai

**Comment by jeskew** [comment]
I did. I'm asking to figure out where the error originated. If the operation failed without throwing any warnings and without returning a value, that would mean that there's an issue with the stream wrapper. If it did register a warning and return false, that would indicate an issue with the S3Client.

**Comment by lonormaly** [comment]
Thanks for that.

How can I trace it?

On Friday, September 11, 2015, Jonathan Eskew <notifications@github.com>
wrote:

> I did. I'm asking to figure out where the error originated. If the
> operation failed without throwing any warnings and without returning a
> value, that would mean that there's an issue with the stream wrapper. If it
> did register a warning and return false, that would indicate an issue with
> the S3Client.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aws/aws-sdk-php/issues/759#issuecomment-139449407>.
>


-- 
Thanks
       Shai

**Comment by jeskew** [comment]
That will depend on how your system is configured, but running `php -i | grep error_log` should tell you where the file is located.

**Comment by lonormaly** [comment]
Now I get false on the response... but how can I get more info? The php_error.log from MAMP folder doesn't say anything related.

**Comment by lonormaly** [comment]
Another interesting issue - "copy" command never returns a response...

**Comment by jeskew** [comment]
It sounds like this might be related to a fix that went out in yesterday's release (3.3.5). Could you upgrade, try again, and let me know if that solves your issue?

**Comment by lonormaly** [comment]
So sorry but it didn't fix it :(
Thanks for the efforts. Do you know on what version did it work for sure?

**Comment by jeskew** [comment]
This is an issue where either all versions of v3 would work out none of them would. I'll start on a fix.

**Comment by lonormaly** [comment]
You're awesome! thank you so much dear friend :)

**Comment by jeskew** [comment]
Just merged in the fix. Let me know if anything comes up.

**Comment by lonormaly** [comment]
How can I get more info about the reason the rename failed? currently the response is only boolean right?

**Comment by lonormaly** [comment]
Unfortunately the fix didn't fix that error for us. tried to rename file with size 16.5GB. If you want i can get you a specific file

**Comment by jeskew** [comment]
Stream wrappers only respond with booleans, but the wrapper will trigger warning-level errors. Where and whether these are warnings are recorded is controlled by your environment's configuration, as detailed in [here](http://php.net/manual/en/errorfunc.configuration.php). Whether they are recorded is controlled by the `error_reporting` setting and where is controlled by `error_log`. Note that these might be set by your webserver's configuration and might differ between the PHP CLI and a server environment.

With the master branch, I am able to copy files over 5GB. A working example is at https://gist.github.com/jeskew/e23b5ef2ec51da90aff3

**Comment by lonormaly** [comment]
Hey, thanks for that!

The gist is for Multipart upload not use of StreamWrapper with rename command

**Comment by jeskew** [comment]
I updated the gist. Rename calls a multipart copy under the hood.
