### ISSUE TITLE
Multipart Upload failed

### ISSUE THREAD

**Issue by fkizewski** [aws/aws-sdk-php#762]
Hi all.

I've just started to use this sdk.
I would like to upload large file on my bucket, so i use multipart upload described here: http://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-multipart-upload.html

This is my source code:

	<?php
	require 'vendor/autoload.php';
	  
	use Aws\S3\S3Client;
	use Aws\S3\MultipartUploader;
	use Aws\Exception\MultipartUploadException;

	$s3Client = new S3Client([
		'version'     => 'latest',
		'region'      => 'eu-west-1',
		'credentials' => [
			'key'    => 'myKey',
			'secret' => 'mySecret'
		]
	]);

	$source = fopen('/var/www/bigfile.mp4', 'rb');
	$uploader = new MultipartUploader($s3Client, $source, [
		'bucket' => 'mydestbucket',
		'key'    => 'tmp/bigfile.mp4'
	]);

	do {
		try {
			$result = $uploader->upload();
		} catch (MultipartUploadException $e) {
			$uploader = new MultipartUploader($s3Client, $source, [
				'state' => $e->getState(),
			]);
		}
	} while (!isset($result));
	?>

The size of my file is 9.8GB. Sometimes the upload is done with succes, but very often it's fails.
The exception is:

	Fatal error: Uncaught exception 'GuzzleHttp\Promise\RejectionException' with message 'The promise was rejected with reason: Invoking the wait callback did not resolve the promise' in /var/www/vendor/guzzlehttp/promises/src/functions.php:106 Stack trace: #0 /var/www/vendor/guzzlehttp/promises/src/functions.php(490): GuzzleHttp\Promise\exception_for('Invoking the wa...') #1 /var/www/vendor/guzzlehttp/promises/src/Promise.php(199): GuzzleHttp\Promise\{closure}('Invoking the wa...') #2 /var/www/vendor/guzzlehttp/promises/src/Promise.php(152): GuzzleHttp\Promise\Promise::callHandler(2, 'Invoking the wa...', Array) #3 /var/www/vendor/guzzlehttp/promises/src/TaskQueue.php(60): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /var/www/vendor/guzzlehttp/promises/src/Promise.php(228): GuzzleHttp\Promise\TaskQueue->run() #5 /var/www/vendor/guzzlehttp/promises/src/Promise.php(261): GuzzleHttp\Promise\Promise->waitIfPending() #6 /va in /var/www/vendor/guzzlehttp/promises/src/functions.php on line 106

Could you please help me to resolve this problem. I think it's from the sdk.
Thanks.
Regards Fabrice

**Comment by jeskew** [comment]
What version of the SDK are you using?

**Comment by fkizewski** [comment]
Sorry, i forget to put it: 3.3.5

**Comment by jeskew** [comment]
Any information you can provide about your execution environment would be helpful. I'm unable to reproduce using the default HTTP handler with the following stack:

SDK: 3.3.5
PHP: 5.6.12
Guzzle: 6.1.0
cURL 7.43.0
OSX: 10.10.5

**Comment by fkizewski** [comment]
Hi Jonathan.
Thanks to try to help me.

I've just find my error: because it's a stream, it's necessary to rewind in the exception! So now all is ok.

Please close this issue.

Best regards, Fabrice

**Comment by jeskew** [comment]
Well, I think the error message could use some work. Let me see if I can surface the exact issue more explicitly.

**Comment by fkizewski** [comment]
This is a good idea to be more clear :)

**Comment by jeskew** [comment]
The underlying issue was resolved upstream in https://github.com/guzzle/promises/releases/tag/1.0.3 .

Please feel free to reopen if you have any questions or concerns.
