### ISSUE TITLE
InvalidationBatch parameter is missing from CloudFrontClient's createInvalidation request example

### ISSUE THREAD

**Issue by rodrigobendia** [aws/aws-sdk-php#765]
I've got the following error after I tried to create an invalidation request as stated in the docs (http://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.CloudFront.CloudFrontClient.html#_createInvalidation):

InvalidArgumentException: Found 1 error while validating the input provided for the CreateInvalidation operation: [InvalidationBatch] is missing and is a required parameter in /var/www/vendor/aws/aws-sdk-php/src/Api/Validator.php on line 38

After further investigation I've found that the example is incorrect. The correct request would be:

```php
$result = $client->createInvalidation(array(
    // DistributionId is required
    'DistributionId' => 'string',
    // InvalidationBatch is required
    'InvalidationBatch' => array(
        // Paths is required
        'Paths' => array(
            // Quantity is required
            'Quantity' => integer,
            'Items' => array('string', ... ),
        ),
        // CallerReference is required
        'CallerReference' => 'string',
    )
));
```

**Comment by jeskew** [comment]
Thanks for reporting this! I'll make sure to update the docs with the next release. FWIW, [the v3 docs](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-cloudfront-2015-04-17.html#createinvalidation) are brought up to date more regularly and have the same API operations as v2.

**Comment by jeskew** [comment]
Sorry to take so long to update this ticket. The V2 documentation page linked to is correct for V2, but `InvalidationBatch` is a required parameter in V3. We're working on making the differences between v2 and v3 more visible.
