### ISSUE TITLE
400 BAD REQUEST leads to infinity retries using CommandPool | SDK 3.3.5

### ISSUE THREAD

**Issue by sashless** [aws/aws-sdk-php#768]
aws-sdk-php/3.3.5 GuzzleHttp/6.1.0 curl/7.35.0 PHP/5.6.10

I am using the Command Pool like this

```php
         $command = $this->s3Client->getCommand('PutObject', $commandConfig);`

         $pool = new CommandPool($client,[$command], [
            'fulfilled' => function (ResultInterface $result) use (&$results) {
                $this->onUploadSucces($result, $results);
            },
            'rejected' => function (AwsException $reason) use (&$results) {
                $this->onUploadError($reason, $results);
            },
        ]);

        $promise = $pool->promise();
        $promise->wait();
```

The body of the Command is an Image or a PDF File and its working fine except for one file i found on github.

When i try to upload that file the CommandPool gets stuck in between the execution 

The response is 

```
<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.</Message><RequestId>F65194542FABDE8A</RequestId><HostId>xS7b/b/wnGYZJ2CftOzMeEURPIVSyMacP2nt0LQFZ76+kX/Embz4J65DMS2PaJna</HostId></Error>
```

The problem with this is its not calling the `rejected` callback. It is retrying until the end of the world.

```
 User-Agent: aws-sdk-php/3.3.5 GuzzleHttp/6.1.0 curl/7.35.0 PHP/5.6.10#015
Sep 17 11:33:42  Content-Length: 1016315#015
Sep 17 11:33:42  #015
Sep 17 11:33:42  < HTTP/1.1 400 Bad Request#015
Sep 17 11:33:42  < x-amz-request-id: 4FAE8098B6FC8563#015
Sep 17 11:33:42  < x-amz-id-2: Deusx9qYwW24m38gX9MRjk4HWuvWyHYa81JG/PxDNp4f0gfTPeM7IVJNU5H/LFsB#015
Sep 17 11:33:42  < Content-Type: application/xml#015
Sep 17 11:33:42  < Transfer-Encoding: chunked#015
Sep 17 11:33:42  < Date: Thu, 17 Sep 2015 11:33:22 GMT#015
Sep 17 11:33:42  < Connection: close#015
Sep 17 11:33:42  * Server AmazonS3 is not blacklisted
Sep 17 11:33:42  < Server: AmazonS3#015
Sep 17 11:33:42  < #015
Sep 17 11:33:42  * Closing connection 4
```

I can provide more debug output like more verbose network logging etc if necessary

**Comment by sashless** [comment]
In addition i tried to limit the retries ( default is 3 from viewing the docs ) but that has no result..

```
 'credentials' => [
            'key' => 'xx',
            'secret' => 'xx',
        ],
        'region' => 'us-east-1',
        'version' => '2006-03-01',
        'http'    => [
            'connect_timeout' => 5
        ],
        'retries' => 1,
        'debug' => [
            'logfn'        => function ($msg) { echo $msg . "\n"; },
        ]
```

**Comment by jeskew** [comment]
The retry handler should not be retrying 400 responses in any case. Could you provide more verbose output? I've been trying to reproduce with the following script, which returns 400 responses to all S3 commands:
```php
<?php

require __DIR__ . '/../vendor/autoload.php';

use Aws\S3\S3Client;
use Aws\S3\Exception\S3Exception;
use GuzzleHttp\Exception\ClientException;
use GuzzleHttp\Promise\RejectedPromise;
use GuzzleHttp\Psr7\Response;
use Psr\Http\Message\RequestInterface;

$handler = function (RequestInterface $request) {
    return new RejectedPromise([
        'connection_error' => true,
        'exception' => ClientException::create($request, new Response(400)),
        'response' => null,
    ]);
};

$s3 = new S3Client([
    'region' => 'us-west-2',
    'version' => 'latest',
    'http_handler' => $handler,
]);

$command = $s3->getCommand('PutObject', [
    'Bucket' => 'bucket',
    'Key' => 'key',
]);

$pool = new \Aws\CommandPool($s3, [$command], [
    'fulfilled' => function () {
        echo "GREAT SUCCESS!\n";
    },
    'rejected' => function (S3Exception $e) {
        echo "REJECTED: {$e->getMessage()}\n";
    },
]);

$pool->promise()->wait();
```
Running the above always outputs `REJECTED: Error executing "PutObject" on "https://s3-us-west-2.amazonaws.com/bucket/key"; AWS HTTP error: Client error response [url] https://s3-us-west-2.amazonaws.com/bucket/key [http method] PUT [status code] 400 [reason phrase] Bad Request`.

Is there a loop surrounding the code snippet you provided in the original issue?

**Comment by jeskew** [comment]
I saw there was a special case for the particular error message you mentioned and that it would in fact be retried indefinitely. This issue would be solved by cef4687.

**Comment by sashless** [comment]
Awesome,  thanks for working on that! 

What makes me wondering is why this particular file fails to upload with 'Could not read from stream..'  where it works without that error using the old Sdk. 

Should I create another issue?

**Comment by sashless** [comment]
The file in law is https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf

and uploaded like 


```php

$httpClient = new \GuzzleHttp\Client();
$commandConfig = [
    'Bucket' => 'xx',
    'Key' => 'xx',
    'Body' => $this->httpClient->get($pdfUrl)->getBody(),
    'ACL' => 'xx'
];

$command = $this->s3Client->getCommand('PutObject', $commandConfig);

$pool = new CommandPool($client, [$command], [
    'fulfilled' => function (ResultInterface $result) use (&$results) {
        $this->onUploadSucces($result, $results);
    },
    'rejected' => function (AwsException $reason) use (&$results) {
        $this->onUploadError($reason, $results);
    },
]);

$promise = $pool->promise();
$promise->wait();

```

**Comment by sashless** [comment]
Hey @jeskew have you seen my comment above?

**Comment by jeskew** [comment]
I did. I think the best the SDK can do in that case is to limit the number of retries to what's been configured. I was unable to reproduce the issue with the link you provided, but you should open an issue on Guzzle if you routinely encounter errors trying to download something with a Guzzle client.

**Comment by sashless** [comment]
Ah yea, of course. Thank you!

Jonathan Eskew <notifications@github.com> schrieb am Fr., 25. Sep. 2015
00:44:
