### ISSUE TITLE
Unable to get IAM credentials 

### ISSUE THREAD

**Issue by thenetimp** [aws/aws-sdk-php#772]
I am using SDK version 2.8.21 to use KMS.

I have a config.php file that contains

```
<?php

// File saved as /path/to/custom/config.php
require 'vendor/autoload.php';

use Doctrine\Common\Cache\FilesystemCache;
use Guzzle\Cache\DoctrineCacheAdapter;

// Create a cache adapter that stores data on the filesystem
$cacheAdapter = new DoctrineCacheAdapter(new FilesystemCache('/tmp/cache'));

return array(
    'includes' => array('_aws'),
    'services' => array(
        'default_settings' => array(
            'params' => array(
                'credentials.cache' => $cacheAdapter
            )
        )
    )
);
```

The following is test.php file that I am using to do a test encryption.

```
<?php

  require 'vendor/autoload.php';

  use Aws\Common\Aws;

  // Create the AWS service builder, providing the path to the config file
  try {

    $keyId = '<KMSKEYALIAS>';

    $aws = Aws::factory('config.php');
    $client = $aws->get('kms');

    $result = $client->encrypt(array(
      'KeyId' => $keyId,
      'Plaintext' => 'This is the song that never ends...'
    ));

    print_r($result);

  }
  catch (\Exception $e)
  {
    echo $e->getMessage()."\n\n";
  }
```

When I execute php `test.php`  I get "A region is required when using AWS Key Management Service".  

Thinking it may be a server IAM issue we used the CLI tools to test.

```
aws kms encrypt --key-id <KMSKEYALIAS> --plaintext "1\!2@3#4$5%6^7&8*9(0)-_=+" --query CiphertextBlob --output text | base64 --decode > /tmp/encrypt.txt
```

And /tmp/encrypted.txt contained the encrypted data.

I am at a loss and could really use some help in either figuring out if this is a bug in aws or if I am doing something wrong.

**Comment by jeskew** [comment]
Hi @thenetimp,

Are you using a `~/.aws/config` file with the CLI? Files at that location are not loaded by the PHP SDK.

**Comment by thenetimp** [comment]
I am not using ~/.aws/config  We have an IAM role set up.  There are no actual credentials set up on the server.  The server is setup to get temporary credentials from IAM roles.

**Comment by jeskew** [comment]
I ask because the CLI allows users to specify a default region in `~/.aws/config`, while the SDK requires that regions be specified at runtime. [KMS clients must be instantiated with a region](http://docs.aws.amazon.com/aws-sdk-php/v2/guide/service-kms.html#factory-method), as the region is used as a part of the service's authentication scheme.

**Comment by jeskew** [comment]
One of the CLI engineers confirmed that a region is required for performing operations on KMS with the CLI, so your region is likely stored somewhere on your environment. Running `aws configure list` will display the configuration stored on your environment and tell you where each variable is coming from.

You can find more information about CLI configuration [here](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html).

**Comment by thenetimp** [comment]
The IAM policy assigned to the role assigned to server sets the region as 'us-east-1'  and is suppose to be one of the params returned from config.php.   config.php is returning no acceskey, no secret and no region. The issue is not that I am not passing the region, the issue is that the policy/role credentials and region are not being picked up by the code from the php library.

**Comment by jeskew** [comment]
I don't see any of that set in the config file you posted. Do you mean the file that adds a cache to the default settings?

**Comment by thenetimp** [comment]
My understanding is that IAM/Roles allows me to use aws services from an EC2 server without having to define the key and secret and region.  That using the code in config.php somehow gets that information from AWS, but since I have never done this before, I do not know 100% what to expect from the config.php code as it was taken from this aws blog post.

https://blogs.aws.amazon.com/php/post/Tx1F82CR0ANO3ZI/Providing-credentials-to-the-AWS-SDK-for-PHP

So from what is posted here it seems to me that I do not have to define the region, that it would do it for me.

**Comment by jeskew** [comment]
IAM instance roles are a way of managing credentials, not regions. You would still need to set the region on your instance of the client class. The blog post includes an example of how to set a region in a config file:
```php
<?php
 
return array(
    'includes' => array('_aws'),
    'services' => array(
        'default_settings' => array(
            'params' => array(
                'region' => 'us-west-1',
            )
        )
    )
);
```

Because you're using instance profiles, you do not need to provide credentials in this file. If you would like a default region to be set, then you must provide it either in the config file or in your client's constructor.

**Comment by thenetimp** [comment]
I see, thank you.  The documentation was not clear on that imo.  Adding the region to that array resolved the issue.  After your earlier suggestion I had tried adding it other places with failure.
