### ISSUE TITLE
aws_session_token should be used

### ISSUE THREAD

**Issue by ilons** [aws/aws-sdk-php#773]
As stated way back on the (AWS blog)[https://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs], all SDK's should support the same ways to provide credentials.

Currently the PHP SDK looks for aws_security_token rather than aws_session_token.
http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-installing-credentials

This causes confusion and portability problems  when using the SDK.

**Comment by jeskew** [comment]
Thanks for reporting this! Looks like [Java](https://github.com/aws/aws-sdk-java/blob/8397ef2731c9ea57de1a529a2e3991eebb96b257/aws-java-sdk-core/src/main/java/com/amazonaws/auth/profile/internal/Profile.java#L39), [JavaScript](https://github.com/aws/aws-sdk-js/blob/fb0f95f43ea958846d932bb4e79934a4a548155f/lib/credentials/shared_ini_file_credentials.js#L73), and [Ruby](https://github.com/aws/aws-sdk-ruby/blob/3069715d9b894b7ded01dc472966c6df354ccd57/aws-sdk-core/lib/aws-sdk-core/shared_credentials.rb#L10) all use `aws_session_token`.
