### ISSUE TITLE
DynamoDB session handler on HHVM

### ISSUE THREAD

**Issue by maugar** [aws/aws-sdk-php#778]
I was trying DynamoDB session handler with HHVM 3.9.0 and I encountered the following error when loading a page (a very basic hello world test for DynamoDB) with no session cookie.

```
Failed to initialize storage module: user (path: )
```

On the other hand, loading the same page with a valid session cookie, worked flawlessly.

For reference, the session related part is reported below.
```
$dynamoDb = \Aws\DynamoDb\DynamoDbClient::factory(array(
    'region' => 'us-east-1',
    'credentials' => array(
        'key'    => '',
        'secret' => ''),
    'version' => 'latest'
));

$sessionHandler = SessionHandler::fromClient($dynamoDb, [
    'table_name' 			   => 'mysession',
    'hash_key' 				   => 'mysessionID',
    'locking'                  => true,
    'session_lifetime'         => 3600*24*365*10,
    'consistent_read'  		   => true,
    'max_lock_wait_time'       => 10,
    'min_lock_retry_microtime' => 5000,
    'max_lock_retry_microtime' => 50000
 ]);

$sessionHandler->register();
session_start();
```

I could fix this error  by editing the following file:  
```
 https://github.com/aws/aws-sdk-php/blob/master/src/DynamoDb/SessionHandler.php
```

Line 105

from 
```
    public function open($savePath, $sessionName) {
        [...]

        return (bool) $this->openSessionId;
    }
```

to 
```
    public function open($savePath, $sessionName) {
        [...]

        return true;
    }
```

Is this issue related only to HHVM?
What are the drawbacks of `open` function always returning `true`?
So far, everything seems to be working.

**Comment by jeskew** [comment]
From what you describe, it sounds like HHVM does not create a session ID before calling the session handler methods associated with `session_start`. `session_id` is only supposed to return an empty string if `session_start` has not yet been called, but it's actually `session_start` that's calling the `open` method. 

With the change you made, is it possible to start a new session? Returning `false` from `open` should cause `session_start` to fail.

**Comment by maugar** [comment]
With the change I made, the session handler works as expected. New sessions are created the first time, and successfully reopen, from the second request.

I can confirm that when open returns `false`, `session_start` fails with the fatal error reported.

**Comment by jeskew** [comment]
So this change causes the same number of requests to fail, just at the call to `session_start` instead of when the session is written?

**Comment by maugar** [comment]
No, with my modification (`open` function always returning `true`) the call to `session_start` never fails and the session handling works as expected.

**Comment by jeskew** [comment]
Oh I see. Without a session ID (or rather, with a session ID of `''`), how are those sessions saved?

**Comment by maugar** [comment]
New sessions are saved with the correct format `PHPSESSID_0b565957e3977d905a194bedbaacedb7`
I suppose the session ID of a new session is generated (internally by HHVM?) after the call to `open` function.
My first attempt to fix this issue was the following:

    public function open($savePath, $sessionName)
    {
        $this->savePath = $savePath;
        $this->sessionName = $sessionName;
        $this->openSessionId = session_id();
        
        // Create a new session id if session_id() returns ""
        if (!((bool) $this->openSessionId)) {
            $this->openSessionId = session_regenerate_id();
        }
        return true;
    }

But then I tried just returning `true`, without generating a new session ID, and it was working as well.

**Comment by jeskew** [comment]
So it looks like the the runtime will pass in the correct session ID when writing to a session, so this wouldn't affect requests where you were writing data on new sessions. It will, however, affect calls made in the `close` method, where a timestamp is written using the value saved at `$this->openSessionId`.

I think your initial impulse was right and that the `open` method should be rewritten such that `$this->openSessionId = session_id() ?: session_regenerate_id();` (along with a comment that it's to support HHVM and accompanied by a test). I would be open to merging in that pull request.

**Comment by maugar** [comment]
After further tests, I realised that `session_regenerate_id()` does not generate a new session ID unless a valid session ID already exists. Therefore, if `session_id()` returns `''`, also `session_regenerate_id()` will return `''`.

The following version of `open()` works despite the fact that the assignment `$this->openSessionId =session_id()` is skipped.
```php
 public function open($savePath, $sessionName){
    $this->savePath = $savePath;
    $this->sessionName = $sessionName;
    return true;
}
```

I also took a look at the test `https://github.com/maugar/aws-sdk-php/blob/master/tests/DynamoDb/SessionHandlerTest.php`. Since the actual connection with the DynamoDb is mocked, I am not sure how to write a meaningful test for the modification I'd like to propose.

**Comment by jeskew** [comment]
You would need to make that a session ID is sent to DynamoDb even if `write` is never called. You can mock out the entire HTTP handler and call assertion methods there if you'd prefer. A good example of how to do that would be the [`testRetriesConnectionErrors`](https://github.com/aws/aws-sdk-php/blob/master/tests/S3/S3ClientTest.php#L360) in the `Aws\Test\S3\S3ClientTest` class.

**Comment by jeskew** [comment]
Would you be interested in translating what you've done above into a pull request?

I would also encourage you to file a bug report with HHVM, as the behavior you're describing differs from that of the Zend engine.

**Comment by Lansoweb** [comment]
I made some tests with PHP 7.0.0RC6 today and it has the same issue:
```
Failed to initialize storage module: user (path: )
```

And using the return true fixed it too.

**Comment by jeskew** [comment]
@Lansoweb are you using v2 or v3?

**Comment by Lansoweb** [comment]
@jeskew v2 ... will make the same test with v3.

**Comment by Lansoweb** [comment]
@jeskew Updated my project to V3. then opened the browser i get:
```
Fatal error: session_start(): Failed to initialize storage module: user (path: /tmp)
```

If I put the "return true" by the end on open method the session works.

**Comment by jeskew** [comment]
Thanks for trying that out. I opened #812 as a possible fix.

**Comment by Lansoweb** [comment]
@jeskew Glad to help. Great work btw!

**Comment by jeskew** [comment]
#812 was merged into master and will go out with the next release.

**Comment by Lansoweb** [comment]
@jeskew Thanks!!
