### ISSUE TITLE
S3 downloadBucket fails if S3 path doesn't exist

### ISSUE THREAD

**Issue by soukiii** [aws/aws-sdk-php#784]
```php
$s3Client->downloadBucket('/tmp/', 'bucket', 'path-does-not-exist');
```

This code raises warning:
`PHP Warning: Invalid argument supplied for foreach() in .../vendor/aws/aws-sdk-php/src/S3/Transfer.php:232`
... and GuzzleHttp\Promise\RejectionException exception:
`The promise was rejected with reason: Invoking the wait callback did not resolve the promise`

It works as expected if _path-does-not-exist_ is existing S3 folder.

I am using version 3.5.0 (latest)

**Comment by jeskew** [comment]
Would you still want an exception to be thrown when the remote path does not exist?

**Comment by soukiii** [comment]
It should throw exception or download empty directory - I am not sure what is consistent with other methods.

**Comment by jeskew** [comment]
The underlying issue was resolved upstream in https://github.com/guzzle/promises/releases/tag/1.0.3 .

Please feel free to reopen if you have any questions or concerns.
