### ISSUE TITLE
Track multipart upload progress

### ISSUE THREAD

**Issue by lonormaly** [aws/aws-sdk-php#785]
Heya,

Is it possible to track the progress of a multipart upload?

Thanks for time and efforts, you're doing great job! :)

**Comment by jeskew** [comment]
You can pass a callback to as a `before_upload` option to the multipart uploader. Looks from #786 that you found this on your own.

**Comment by lonormaly** [comment]
Thank you!

I can't see how this answers my question. Using `before_upload` I can determine which part is being uploaded but not the overall progress of the upload. We do use concurrency so this is no real indication of the current progress of the upload.

**Comment by jeskew** [comment]
A `before_upload` callback will let you keep track of which uploads have started. It's probably what you want to use if you're looking to make a progress bar or something similar.

Instances of `Aws\S3\MultipartUploader`, `Aws\S3\MultipartCopy`, and `Aws\Glacier\MultipartUploader` have a `getState` method that returns an instance of [`Aws\Multipart\UploadState`](https://github.com/aws/aws-sdk-php/blob/master/src/Multipart/UploadState.php). That object has a [`getUploadedParts`](https://github.com/aws/aws-sdk-php/blob/master/src/Multipart/UploadState.php#L108) method that returns a sorted array of the parts that have been successfully uploaded, on which you can call `count`.
