### ISSUE TITLE
Multipart upload declared finished but didn't finish the upload

### ISSUE THREAD

**Issue by lonormaly** [aws/aws-sdk-php#786]
Hey there,

I used multipart upload to copy 15.7GB file from one bucket to another with concurrency of 5 and part size of 100MB.
The "before_complete" event was fired and the upload was declared as finished after finishing only 5 parts and the final file was only 500MB (!).

Code: https://gist.github.com/lonormaly/3ed36c63963ba7531838

SDK Version: 3.5.0

![image](https://cloud.githubusercontent.com/assets/3742919/10267513/0a015206-6aa0-11e5-9cbd-ad44542173c1.png)

Original file:
![image](https://cloud.githubusercontent.com/assets/3742919/10267517/265fc5c2-6aa0-11e5-9237-58133102d2a9.png)

**Comment by jeskew** [comment]
I would guess that it had something to do with the `$tempSource` parameter you were passing in.  Looks from #787 that you found this on your own.

**Comment by lonormaly** [comment]
Actually nothing in $tempSource was wrong. In fact when using MultipartCopy it works perfectly.
I would suggest to check this one more thoroughly because this is a big deal if this operation cuts one's file for no reason.
