### ISSUE TITLE
Why multipart upload from one bucket to other takes so long

### ISSUE THREAD

**Issue by lonormaly** [aws/aws-sdk-php#787]
Hey there,

Small question: when multipart uploading from one bucket to another from a local webserver it takes more than 5 hours to pass a ~15 GB file while copy paste it using S3 console takes less than 15 minutes.
Any idea why is that?
Does the file / parts are being downloaded first locally before uploading them for some reason?

SDK Version: 3.5.0

Thanks

**Comment by jeskew** [comment]
Using an instance of `Aws\S3\MultipartUploader` will download the copy source and upload it to another key. You can use `Aws\S3\S3Client::copy` or an instance of `Aws\S3\MultipartCopy` to perform a copy operation on S3 instead.  Looks from #788 that you found this on your own.
