### ISSUE TITLE
MultipartCopy InvalidArgument x-amz-copy-source-range

### ISSUE THREAD

**Issue by lonormaly** [aws/aws-sdk-php#788]
Hey again,

Can't seem to use new MultipartCopy object to copy large files...
Tried to copy a 15.7GB file but encountered a repeated error message which endlessly flooded the webserver and eventually made to its complete shutdown.

Code:
https://gist.github.com/lonormaly/b2776e16a95445079e4f

SDK Version: 3.5.0

**Comment by jeskew** [comment]
There was an issue with the way the byte range was being specified on the last chunk of a multipart copy. A fix has been pushed to master and will go out with the next release.
