### ISSUE TITLE
Container interop factory

### ISSUE THREAD

**Issue by bakura10** [aws/aws-sdk-php#789]
Hi everyone,

With more frameworks adopting the ContainerInterface (https://github.com/container-interop/container-interop), do you think we could integrate a built-in factory for the SDK?

A simple implementation:

```php
namespace Aws\Container;

use Aws\Sdk as AwsSdk;
use Interop\Container\ContainerInterface;
use RuntimeException as BaseRuntimeException;

class AwsSdkFactory
{
    /**
     * @param  ContainerInterface $container
     * @return AwsSdk
     */
    public function __invoke(ContainerInterface $container)
    {
        $config = $container->get('config');

        if (!isset($config['aws'])) {
            throw new BaseRuntimeException('Key "aws" is missing');
        }

        return new AwsSdk($config['aws']);
    }
}
```

If you are interested I'd be happy to submit a PR.

**Comment by jeskew** [comment]
I would rather wait for the PSR-11 to land before adopting an interface as a standard. Until then, you could use a thin wrapper around an instance of `Aws\Sdk` as a bridge (like your sample implementation), and that would work just as well outside the SDK (as a small package with a dependency on the SDK) as it would integrated into it.

**Comment by jeremeamia** [comment]
I'm not really for or against this feature, but I did want to weigh in on the PSR-11 status. ZF and Aura have already implemented `ContainerInterface`, but many other FIG peeps are opposed or uninterested in the spec. It will likely be a long time before it is voted on and may not end up getting accepted. `ContainerInterface` will continue to exist regardless of the PSR though.

**Comment by mtdowling** [comment]
I'm -1 on this idea for now.

If/when it becomes a standard then maybe we would use it, but it would have to be backwards compatible with our current implementation, not add any complexity, and provide some added value.

**Comment by jeskew** [comment]
Until container-interop is adopted by a standards body, I don't think integrating it into the SDK is the right move. However, I would encourage you to publish the sample implementation above (or something similar) as a separate package that depends on the SDK, as it doesn't take much code to integrate the `Aws\Sdk` service locator with a simple container interface, and that code works just as well in a third-party package as it would in the SDK itself.

Please feel free to reopen the issue if you have any questions or concerns.
