### ISSUE TITLE
Cross location operations fail on bucket endpoint enabled clients

### ISSUE THREAD

**Issue by phusi0n** [aws/aws-sdk-php#794]
I noticed failures for the `rename` function in the `StreamWrapper` following the changes for #763 but there could be other cases too.

```
$client = new S3Client([
    "credentials" => [
        "key"    => "KEY",
        "secret" => "SIGNATURE",
    ],
    "endpoint" => "https://foo.s3.amazonaws.com/",
    "region"   => "us-east-1",
    "version"  => "2006-03-01",
    "bucket_endpoint" => true
]);

$client->headObject([
    'Bucket' => "bar",
    'Key' => "baz",
]);
```

The above head object results in:

```
* Connected to foo.s3.amazonaws.com (54.231.17.169) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
* Server certificate: *.s3.amazonaws.com
* Server certificate: VeriSign Class 3 Secure Server CA - G3
* Server certificate: VeriSign Class 3 Public Primary Certification Authority - G5
> HEAD /baz HTTP/1.1
Host: foo.s3.amazonaws.com
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20151012T202150Z
Authorization: AWS4-HMAC-SHA256 Credential=[KEY]/20151012/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=[SIGNATURE]
User-Agent: aws-sdk-php/3.8.0 GuzzleHttp/6.1.0 curl/7.43.0 PHP/5.6.13
```

This is problematic in a `rename` because you can only work with 1 configured client that performs a `HEAD` to check existence of the FROM object in the FROM bucket, and then also perform a COPY to the TO bucket.

**Comment by jeskew** [comment]
Is there a reason you need to use an endpoint like `https://foo.s3.amazonaws.com/`? 

If you use the default endpoint, you will only need to establish one SSL connection. If you want to use two clients to perform a `rename` operation, each talking to a different endpoint, you would double the SSL overhead incurred.

**Comment by phusi0n** [comment]
I can probably stop using bucket endpoints as a workaround

**Comment by jeskew** [comment]
I think you'll be happier with the results that way. The advantage offered by virtual-hosted buckets is that you don't need to know the region in which a bucket resides, but since you're already specifying that your bucket is in `us-east-1`, just using one client will increase performance.

Closing, as it sounds like you're comfortable with the proposed solution. Please feel free to reopen if you have any questions or if any blockers come up.
