### ISSUE TITLE
Prefix dynamoDB table?

### ISSUE THREAD

**Issue by bakura10** [aws/aws-sdk-php#795]
Hi,

I'm not sure if this is a good idea or not, but it's often hard to work locally with DynamoDb (of course, there is the local tool but it's often easier to work directly with the real service).

The issue is that it's hard to dissociate production from staging / testing tables. It would be nice if DynamoDB could have a global option like "prefix_table" that would automatically add this prefix to ANY call made to DynamoDB. For instance, the userland could write:

$sdk->putItem(['TableName' => 'mytable']);

If the SDK has been configured to add "production." prefix, then it would hit the "production.mytable" table instead. Therefore it would become very easy to switch between environment tables.

What do you think?

**Comment by mtdowling** [comment]
I'm not sure that the SDK should do things like this in the core SDK package. It's possible though that you could create a middleware for the `init` step that modifies the table name using prefixes. If you thought it was generic enough, it could be open-sourced as a package that depends on the SDK.

See http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/handlers-and-middleware.html#middleware

**Comment by jeskew** [comment]
I agree with @mtdowling that this would be out of scope for the SDK but would be a good complementary project. The difference between development and production environments is more of an application-level concern than a library-level one.

Please feel free to reopen the issue if you have any questions or concerns.
