### ISSUE TITLE
route 53 n/a region

### ISSUE THREAD

**Issue by lesterjanpearson** [aws/aws-sdk-php#797]
How do we specify if there is no specific region?

I tried this code:

$client = Route53Client::factory(array(
    'profile' => 'test1',
    'region'=>'n/a',
    'version' => 'latest'
));

AWS HTTP error: Client error: 403 IncompleteSignature (client): Credential must have exactly 5 slash-delimited elements

I also tried removing region but its required.

**Comment by jeskew** [comment]
Hi @lesterjanpearson,

Route53 requests need to be signed against the 'us-east-1' region. The same applies to anything listed on [the regions and endpoints page](http://docs.aws.amazon.com/general/latest/gr/rande.html) as having a single global region or a region of "N/A."

Hope that helps! Please feel free to reopen if you have any questions or concerns.
