### ISSUE TITLE
The docs for AWS\S3\S3Client\deleteObjects are wrong.

### ISSUE THREAD

**Issue by jbhamilton** [aws/aws-sdk-php#803]
The docs for AWS\S3\S3Client\deleteObjects are wrong.

The docs state that you must pass `Delete` and as a child `Objects`.
 http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#deleteobjects
```
$result = $client->deleteObjects([
    'Bucket' => '<string>', // REQUIRED
    'Delete' => [ // REQUIRED
        'Objects' => [ // REQUIRED
            [
                'Key' => '<string>', // REQUIRED
                'VersionId' => '<string>',
            ],
            // ...
        ],
        'Quiet' => true || false,
    ],
    'MFA' => '<string>',
    'RequestPayer' => 'requester',
]);
```

When I do this Guzzle throws a:
```
Guzzle\Service\Exception\ValidationException' with message 'Validation errors: [Objects] is a required array' in /var/www/app/vendor/guzzle/guzzle/src/Guzzle/Service/Command/AbstractCommand.php
```

but if I pass `Objects` in place of `Delete` everything goes smoothly.

**Comment by jeskew** [comment]
Are you sure you're looking at the right documentation? The docs you linked to are for the current version (v3), but the error reported indicates that you're using version 2. The [v2 docs for the deleteObjects operation](http://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.S3.S3Client.html#_deleteObjects) indicate that this is expected with v2.

**Comment by jbhamilton** [comment]
You are correct my friend. Thanks, you can close this.
