### ISSUE TITLE
S3 ListObjects ETag has quotes around value

### ISSUE THREAD

**Issue by hacfi** [aws/aws-sdk-php#804]
I’m on the latest `3.9.1` and noticed that the `ETag` value is 34 chars and for example `"b71220c3a07c08f32a26cb68c2d70078"`. Not sure when this bug was introduced.

**Comment by skyzyx** [comment]
This is the way that the value is returned by S3 — a string containing quotes around the value.

AFAICT, it has always been there… no? I can say with 100% certainty that it was there in SDK 1.x.

**Comment by hacfi** [comment]
@skyzyx Thanks for the quick response! You’re right..the SDK actually returns it wrapped in quotes. A bit weird but ok :)
