### ISSUE TITLE
Exception while uploading to s3 : "Are you sure you are using the correct region for this bucket?"

### ISSUE THREAD

**Issue by motsmanish** [aws/aws-sdk-php#805]
I have defined in options the 'region' parameter while initiating s3client object, but still getting this error:
"Encountered a permanent redirect while requesting https://s3-us-west-2.amazonaws.com/mybucketname/mykey. Are you sure you are using the correct region for this bucket? "
Code:
```php
$this->s3Client = new \Aws\S3\S3Client([
			'version' => 'latest',
			'region' => 'us-west-2',
			'credentials' => [
				'key' => $this->accessKey,
				'secret' => $this->secretKey
			],
			'debug' => false
		]);
```

**Comment by jeskew** [comment]
In which region is the bucket you're uploading to located?

**Comment by motsmanish** [comment]
'region' => 'eu-west-1'

Thanks & Regards,
Manish Motwani
*http://ManishMotwani.com <http://manishmotwani.com/>*

**Comment by jeskew** [comment]
You'll need to interact with the bucket using a client scoped to the region in which the bucket resides. The error should disappear if you change the region to 'eu-west-1' in the code snippet posted above.

**Comment by motsmanish** [comment]
I tried that as well, but I get the same error.

**Comment by motsmanish** [comment]
us-east-1 worked for me.
