### ISSUE TITLE
Upload file to s3 with PHP on a EC2 instance throw credentials error, but works locally

### ISSUE THREAD

**Issue by jrivera294** [aws/aws-sdk-php#811]
Hi everyone.

I have tested my function to upload images to s3 on my machine, but when I go to production on ec2, by a strange reason, it doesn't work.

This is the error:
CredentialsException in InstanceProfileProvider.php line 79:
Error retrieving credentials from the instance profile metadata server. (Client error: 404)

This is the code:
$destinationPath = 'images/institutions/logos';
    $extension = $data['int_logo']->getClientOriginalExtension();
    $keyname = $destinationPath.'/'.$username.'.'.$extension;
    $bucket = "*****";
    $filepath = $data['int_logo'];

    $s3 = new S3Client([
        'region'  => 'us-west-2',
        'version' => '2006-03-01',
        'scheme' => 'http'
    ]);

    $result = $s3->putObject(array(
        'Bucket'       => $bucket,
        'Key'          => $keyname,
        'SourceFile'   => $filepath,
        'ACL'          => 'public-read'
    ));

    return $result['ObjectURL'];
}

And this is my s3 policy:

{
"Version": "2012-10-17",
"Id": "*******",
"Statement": [
    {
        "Sid": "******",
        "Effect": "Allow",
        "Principal": "*",
        "Action": [
            "s3:GetObject",
            "s3:PutObjectAcl",
            "s3:PutObject"
        ],
        "Resource": "arn:aws:s3:::****/*"
    }
]}

I don't know why it throw an error with the credentials, I'm not using any authentication, everyone can put a file on this bucket. And it works 100% on my machine.

**Comment by jrivera294** [comment]
Solution to establish an anonymous connection:

Change:
        $s3 = new S3Client([
            'region'  => 'us-west-2',
            'version' => '2006-03-01',
            'scheme' => 'http',
        ]);

To:
        $s3 = new S3Client([
            'region'  => 'us-west-2',
            'version' => '2006-03-01',
            'scheme' => 'http',
            'credentials' => false
        ]);

I still don't know why my local machine can establish the connection, but the ec2 server can't do it without this line.

**Comment by jeskew** [comment]
Hi @jrivera294,

The error you're seeing is not being thrown by S3 but by the [EC2 credentials metadata service](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) -- when an `S3Client` can't locate credentials in environment variables or in an ini file at `~/.aws/credentials`, it will attempt to fetch [instance profile credentials](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html#using-iam-roles-for-amazon-ec2-instances). 

What's probably happening is that you have valid credentials in an ini file on your development machine and have not assigned an IAM role to the instance running the code above.  Passing `false` for your credentials will create an [anonymous client](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html#creating-anonymous-clients) and keep the SDK from trying to find credentials.

**Comment by SlightlyCyborg** [comment]
I am getting this same error, but I am passing my root credentials to the Client in PHP.

**Comment by jeskew** [comment]
@SlightlyCyborg Can you post the code that is triggering the error?
