### ISSUE TITLE
Curl 77 error with guzzle and sqs polling 

### ISSUE THREAD

**Issue by calbatron** [aws/aws-sdk-php#817]
using amazon linux ami and aws php sdk -- after looping through a php script multiple times which uses the sdk to read messages from sqs, i get an error from guzzle:

```
PHP Fatal error:  Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 77:  [url] https://sqs.eu-west-1.amazonaws.com/0xxxxxx2/CPS-Live' in /home/ec2-user/Abacus-worker-sqs-php/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:359
Stack trace:
#0 /home/ec2-user/Abacus-worker-sqs-php/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(292): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#1 /home/ec2-user/Abacus-worker-sqs-php/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#2 /home/ec2-user/Abacus-worker-sqs-php/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages()
#3 /home/ec2-user/Abacus-worker-sqs-php/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(224): Guzzle\Http\Curl\CurlMulti->e in /home/ec2-user/Abacus-worker-sqs-php/vendor/aws/aws-sdk-php/src/Aws/Common/Client/AbstractClient.php on line 258
```

it can be fine for a number of minutes -- but eventually it will fail with the above.

I have increased the size of the EC2 incase there was a memory issue and keeping an eye on memory in my app with no obvious leaks.

I have also restarted httpd but can't get to the bottom of this issue.

**Comment by jeskew** [comment]
This looks like the issue reported in #376. Are you using NSS as the TLS backend for cURL? (You can find out by running `var_dump(curl_version());`.) It looks like some users have had to migrate from NSS to OpenSSL in response to similar errors.

**Comment by calbatron** [comment]
Yeah, I was using NSS as that seems to be what the Amazon Linux AMI is compiled with. Since, I recompiled curl with OpenSSL and then PHP and I am not getting the same error. Thanks for the headsup
