### ISSUE TITLE
DynamoDB SessionHandler does not recognised regenerated session IDs

### ISSUE THREAD

**Issue by dhensby** [aws/aws-sdk-php#821]
When calling `session_regenerate_id()` `SessionHandler` does not recognise that the ID has changed.

`SessionHandler::write` doesn't check for a changed session ID and when the session data hasn't changed, it fails to identify that the session data needs to be re-written.

Steps to reproduce:

1. Create session.
2. Write static data
2. Store session.
3. Regenerate session id
4. Access new session
5. Find new session is empty

**Comment by jeskew** [comment]
This appears to be a known limitation of using PHP's SessionHandlerInterface: there's no way to hook into `session_regenerate_id` using the object-oriented version of [`session_set_save_handler`](http://php.net/manual/en/function.session-set-save-handler.php). [This StackOverflow question](http://stackoverflow.com/questions/32555254/php-custom-session-handler-handling-session-regenerate-id) has a bit more detail, including a note that PHP < 5.5 won't be able to hook into `session_regenerate_id` even using the callback-based `session_set_save_handler`.

I think the session handler should keep track of the ID associated with the data it has read. Keeping that context means that the check to see if data has changed will be more reliable.

**Comment by dhensby** [comment]
DynamoDB's `SessionHandler` writing empty session when the ID changes is not a limitation of PHP's `SessionHanderInterface` IMO. It's a limitation of the current implementation of `doWrite` on the `AbstractLockingStrategy`, which attempts to reduce data overhead by only sending session data to DynamoDB *when the session data has changed*.

If the `session_id()` changes, it will create a new record in DynamoDB, but it won't send the data.

The solution is for DynamoDB to detect if either the data OR the session ID has changed. This could be done 1 of 2 ways.

1. Track the originally read session ID and check to see if the written one has changed against it.
2. Ping Dynamo DB to see if a record with the ID exists and, if not, send the whole data set.

1 is more elegant in my opinion because if the session ID changes several times (and the session is written each time) the session data should be sent; we don't really need to know if the session ID has changed against the last regenerated ID we just need to know if it changed at all. It also has the advantage of saving reads against Dynamo DB.

**Comment by jeskew** [comment]
Fixes to v2 (#825) and v3 (#826) have been merged. Thanks for all your help on finding the right solution to this, @dhensby!

**Comment by dhensby** [comment]
Fantastic, thanks
