### ISSUE TITLE
S3 GetObject throwing String could not be parsed as XML

### ISSUE THREAD

**Issue by Halama** [aws/aws-sdk-php#823]
Hello,
we are getting `String could not be parsed as XML` errors from S3 client `getObject` method.
It is happening randomly maybe on 1 of few thousands `getObject` requests to S3. It started few days ago.

Error stack trace:

![image](https://cloud.githubusercontent.com/assets/903531/11121660/61983d1a-8957-11e5-865a-035b2065cc11.png)

The downloaded file is gzipped CSV. You can notice in stack trace that response was 200 and the response body is also present. But for some reason promise was rejected and error handler was started.
On this line https://github.com/aws/aws-sdk-php/blob/7b369751845660edb983edded7e6b3d697baba4c/src/WrappedHttpHandler.php#L142 the XML response is expected.

Another part of stack trace with promise rejection:

![image](https://cloud.githubusercontent.com/assets/903531/11121739/cfb5e22a-8957-11e5-8a50-3a3d3cb72ef1.png)

AWS SDK version: **3.10.0**

thanks

**Comment by jeskew** [comment]
You mention that the errors started appearing a few days ago; did this follow an upgrade? If so, what version did you upgrade from?

And have you found any way to reliably reproduce this error, or does it occur completely randomly?

**Comment by ondrejhlavacek** [comment]
@jeskew It happened in versions 3.9.4 and 3.10.0. It might have started after upgrading from version 3.2.*, I don't recall this happening in 3.2.*. It occurs completely randomly. Series of following attempts to perform the same action didn't throw any error.

**Comment by jeskew** [comment]
Do you have a full trace for the first screenshot above?

**Comment by ondrejhlavacek** [comment]
@jeskew sure, I just blanked out some sensitive params and deleted the 2 parent exceptions that didn't have any aws-php-sdk related info
https://s3.amazonaws.com/keboola-logs/debug-files/2015/11/12/2015-11-12-12-33-35-5644790faa91a-exception-excerpt.html

**Comment by jeskew** [comment]
I see that you're using the 'SaveAs' parameter on the `getObject` call -- is it possible that what's causing the promise to be rejected is a file system error? Just a hunch, but that may explain why the issue is so hard to reproduce.

**Comment by jeskew** [comment]
@Halama @ondrejhlavacek Is there any chance you could try with `dev-master`? #827 should make the underlying error more visible, but it has not yet been included in a release.

**Comment by ondrejhlavacek** [comment]
@jeskew Deployed to our production environment. Will update this issue when it fails again. Thanks!

**Comment by jeskew** [comment]
@ondrejhlavacek Any updates?

**Comment by ondrejhlavacek** [comment]
@jeskew No failures after the update! Keeping an eye on that.

**Comment by jeskew** [comment]
@ondrejhlavacek I'm tempted to just say that no news is good news on this. It's possible that whatever was causing the error parsing error is now just getting retried and succeeding on the second attempt.

**Comment by ondrejhlavacek** [comment]
@jeskew There were two apps running the `3.10.x` version, one got upgraded to `dev-master` on Nov 16, the other to `3.11.3` on Dec 3. We haven't seen similar errors in any of the two apps since mid November. Considering it solved. Thanks a lot!

**Comment by jeskew** [comment]
Glad to hear it! Please feel free to reopen if you have any questions or concerns.

**Comment by ondrejhlavacek** [comment]
@jeskew We had 2 similar errors today (`3.11.4`)

https://s3.amazonaws.com/keboola-logs/debug-files/2015/12/11/2015-12-11-13-40-39-566ac4472ca1c-exception-excerpt.html

**Comment by jeskew** [comment]
That error should be retried, but it looks like it isn't.

**Comment by ondrejhlavacek** [comment]
Thanks, trying out the latest version. Btw I'm seriously impressed how quickly you resolve issues here. Good job!
