### ISSUE TITLE
I am getting [Aws\Exception\CredentialsException]   in Lumen.

### ISSUE THREAD

**Issue by piyushpatil027** [aws/aws-sdk-php#829]
Hi,

Hope you are doing great. I am using lumen framework and I want to integrate aws-sdk-php-laravel.
When I configure and run then i am getting below error.

[Aws\Exception\CredentialsException]

Error retrieving credentials from the instance profile metadata server. (cURL error 28: Connection timed out after 1001 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))

Can i help me What is actual problem ? Where i am doing wrong.

**Comment by jeskew** [comment]
You need to provide credentials through the lavarel package's configuration file, through a ini file at `~/.aws/credentials`, through the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables, or by assigning your instance an IAM role if you're running on EC2. A full rundown can be found [here] (http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html).

By default, the SDK will try all the above, and the cURL timeout is the last attempt failing.

Hope that helps! Please feel free to reopen if you have any further questions.

**Comment by piyushpatil027** [comment]
Hi Jonathan,

Hope you are doing great. Thanks for reply me. Issue has been solved.

Thanks.

On Thu, Nov 19, 2015 at 10:25 PM, Jonathan Eskew <notifications@github.com>
wrote:

> Closed #829 <https://github.com/aws/aws-sdk-php/issues/829>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aws/aws-sdk-php/issues/829#event-469397912>.
>



-- 
Thanks & Regards
Piyush Patil


Software Engineer
Sky Id : piyushpatil27
Email Id : piyushpatil027@gmail.com
Mobile No : 09096871715
