### ISSUE TITLE
Sync S3 bucket

### ISSUE THREAD

**Issue by skynet** [aws/aws-sdk-php#839]
http://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-transfer.html#downloading-an-amazon-s3-bucket

Looks like everything is downloaded again at subsequent run:

```
$source = 's3://bucket/foo';
$dest = '/path/to/destination/dir';
$manager = new \Aws\S3\Transfer($client, $source, $dest);
$manager->transfer();
```

Should there be a configuration option, telling S3 transfer manager to download only modified files?
Otherwise bandwidth usage will be astronomical when trying to sync logs down for parsing.

**Comment by jeskew** [comment]
The intent of the transfer manager is to always blindly download everything within the provided s3 path. The AWS CLI does provide [a sync command](http://docs.aws.amazon.com/cli/latest/reference/s3/sync.html) that provides functionality like what you're describing, and you should use that when you only want to download modified files.
