### ISSUE TITLE
S3: Permission denied to delete file after putObject

### ISSUE THREAD

**Issue by jrivera294** [aws/aws-sdk-php#841]
I'm uploading a file to S3 with this code:

        $result = $s3->putObject(array(
            'Bucket'       => $bucket,
            'Key'          => $keyname,
            'SourceFile'   => $pdfPath,
            'ACL'          => 'public-read'
        ));

It upload smaller pdf files previously generated, then, I need to delete it from my server with the unlink php function. The problem is that it generates a Permission denied error if I upload it to s3 before, it works if I don't upload the file.

Looking the sdk code, it seems to be doing an async upload? (function upload on the Transfer.php file). Maybe the pdf is still open and uploading when I try to delete it, but how I can overcome this problem?

Regards.

**Comment by jeskew** [comment]
The upload will block until it's completed. Do you get the same error if you call `gc_collect_cycles()` before deleting the local file?

**Comment by jrivera294** [comment]
Wow, I had never thought it. It works. Than you very much!

**Comment by jeskew** [comment]
The GuzzleHttp\Stream object holds onto a resource handle until its `__destruct` method is called. Normally, this means that resources are freed as soon as a stream falls out of scope, but sometimes, depending on the PHP version and whether a script has yet filled the garbage collector's buffer, garbage collection can be deferred. `gc_collect_cycles` will force the collector to run and call `__destruct` on all unreachable stream objects.

**Comment by storage1** [comment]
Unfortunately i still get an Internal Sever Error on my EC2, when i tr uo unlink an uploaded file. Even if i call gc_collect_cycles() before. Im using SDK verison 3.*. 

Best regards

**Comment by cjyclaire** [comment]
@storage1 could you provide more information for troubleshooting? Maybe a code snippet for us to reproduce the issue?

**Comment by storage1** [comment]
of course. My function looks like this:

`function moveFileToS3($localDir, $s3Key){
	global $s3client;
    $s3client->putObject(array(
		'Bucket' => AWS_S3_BUCKET_NAME,
		'Key' => $s3Key,
		'ACL' => 'authenticated-read',
		'SourceFile' => $localDir,
		'Metadata' => array()
	));

	gc_collect_cycles();
	unlink($localDir);
}`

**Comment by cjyclaire** [comment]
@storage1, it seems that your issue is caused by uploading a directory with `putOject`, I'd suggest check out [S3 Transfer](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-transfer.html) in uploading directories.

Also, I'd also suggest double check that `gc` is enabled when you do `gc_collect_cycles()` ;)

**Comment by storage1** [comment]
Thanks for the reply. i checked and gc is running as supposed. I'm using the `putObject` because i am always uploading a single specific file.

I investigated further and this is the Error message i am getting from php:

`Fatal error: Uncaught exception 'RuntimeException' with message 'Unable to open /var/app/current/api/media/tmp/post_picture/20658-small.jpg using mode r: fopen(/var/app/current/api/media/tmp/post_picture/20658-small.jpg): failed to open stream: No such file or directory' in /var/app/current/vendor/guzzlehttp/psr7/src/functions.php:285`

**Comment by cjyclaire** [comment]
@storage1, Apology for that's not the case, since single file situation works for me with the code provided. Taking a look into the Error message, it sounds like that stream reader fails to locate the file?

**Comment by storage1** [comment]
Yeah but there should not be an active stream reader, because `putObject` is declared as a synchronous function.  So everything should be released from the file when unlink is called. Also unlink is a php-function and no function handled by guzzle...

**Comment by cjyclaire** [comment]
@storage1, AWS SDK for PHP uses the PSR-7 StreamInterface internally as its abstraction over PHP streams. information can be found [here](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/streams.html). 

I'm unable to reproduce the issue locally with your code, so I'd ask for more information. Could you check  that directory is correct, garbage collection does working correctly, and `putObject` works well without `unlink`?

**Comment by php5developer** [comment]
I've same issue on Windows 7 PHP 5.6.25.
SDK version is 3.36.8.
**gc_collect_cycles()** helped me.

**Comment by kalvinbdr** [comment]
Same issue will occur if the putObject is inside a try-catch block. My function looks like this. In this example, I disconnected my internet connection to have an error.

`function uploadFileToS3()
{
    try {
        $s3Client = new S3Client(
            array(
                'region' => S3_REGION,
                'version' => ACCEPTED_VERSION,
                'credentials' => array(
                    'key' => ACCESS_KEY,
                    'secret' => SECRET_KEY
                ),
                'http' => array(
                    'verify' => CERT_PATH
                )
            )
        );

        $result = $s3Client->putObject(array(
            'Bucket' => BUCKET,
            'Key' => KEY,
            'SourceFile' => SOURCE_FILE,
            'ACL' => PUBLIC_READ
        ));

        gc_collect_cycles();
        unlink(SOURCE_FILE);

        echo "File is successfully uploaded to " . $result['ObjectURL'];         
    }
    catch (S3Exception $e) {
        gc_collect_cycles();
        unlink(SOURCE_FILE);

        echo "Something went wrong uploading the file to S3.";
    }
}`

**Comment by kalvinbdr** [comment]
Same issue will occur if putObject is inside the try-catch block. In this example, I will create a temporary file and delete it after calling this function. I disconnected my internet connection to have an error.

```php
function uploadFileToS3()
{
    try {
        $s3Client = new S3Client(
            array(
                "region" => S3_REGION,
                "version" => ACCEPTED_VERSION,
                "credentials" => array(
                    "key" => ACCESS_KEY,
                    "secret" => SECRET_KEY
                ),
                "http" => array(
                    "verify" => CERT_PATH
                )
            )
        );

        $result = $s3Client->putObject(array(
            "Bucket" => BUCKET,
            "Key" => KEY,
            "SourceFile" => SOURCE_FILE,
            "ACL" => PUBLIC_READ
        ));

        gc_collect_cycles();
        unlink(SOURCE_FILE);

        $res = array(
            "message" => "File is successfully uploaded to " . $result["ObjectURL"]
        );

        echo json_encode($res);
    }
    catch (S3Exception $e) {
        gc_collect_cycles();
        unlink(SOURCE_FILE);

        $res = array(
            "message" => "Something went wrong uploading the file to S3."
        );

        echo json_encode($res);
        http_response_code(400);
    }
}
```

**Comment by Agimovel** [comment]
None of the above solutions worked for me. So instead of lock that file with this process, I throw her on a variable:

```
$my_virtual_file 		= fopen($filepath,'r');
'Body'   		=> $my_virtual_file 		, // Use this instead of "SourceFile"
flose($my_virtual_file);
unlink($filepath);
```
