### ISSUE TITLE
Fetching Cloudsearch numerical field statistics

### ISSUE THREAD

**Issue by ScuzzyAyanami** [aws/aws-sdk-php#843]
Hello, [This developer guide](http://docs.aws.amazon.com/cloudsearch/latest/developerguide/retrieving-stats.html) shows how to build a *?stats.foo=* query string to return statistics on numerical fields, the PHP SDK documentation for the search() method doesn't make mention of this and looking through the cloud search domain PHP I'm not seeing a way that stats can be fetched via the CloudSearchDomain in the 3.11.5 SDK.

It's possible I may have missed something along the way, but if I could get some clarity on this that would be greatly appreciated.

**Comment by jeskew** [comment]
Hi @ScuzzyAyanami,

The statistics operations you linked to are not yet supported in the AWS SDKs. It is on our radar, though.

In the meantime, if you need to access the statistics endpoints immediately, you can use the SDK to sign an arbitrary request. There was some discussion on how to do so [on this ticket](https://github.com/aws/aws-sdk-php/issues/671).

**Comment by ScuzzyAyanami** [comment]
Thanks, I've actually got my own client which I mimic this SDK's behaviors and inputs so when mine breaks I just switch over to the AWS PHP SDK. I'm able to fetch stats through my own code, but in the future id like to align it to behave in the same way as this code base does. :+1:

**Comment by jeskew** [comment]
Support for statistics was added in https://github.com/aws/aws-sdk-php/commit/444c31b0786487ce4e8ae3b1d7c55990221db3c2.

Please feel free to reopen if you have any questions or concerns.
