### ISSUE TITLE
RefreshableInstanceProfileCredentials doesn't attempt to renew after expiration

### ISSUE THREAD

**Issue by ajaygarga** [aws/aws-sdk-php#847]
I have the below code to create Dynamo db client using AWS PHP SDK 2. It uses Zend 2 framework cache to store the IAM role credentials.

               $params ['region'] = 'us-west-2';
		$params = array (
				'validation'=> false,
				'scheme' => 'http' 
		);
				
		
		$cache = StorageFactory::factory ( 
				array (
						'adapter' => array (
								'name' => 'filesystem',
								'options' => array (
										'cache_dir' => '/tmp' 
								) 
						),
						'plugins' => array (
								'exception_handler' => array (
										'throw_exceptions' => false 
								),
								'Serializer' 
						) 
				) );
		$cacheAdapter = new Zf2CacheAdapter ( $cache );
		$params ['credentials.cache'] = $cacheAdapter;
		
		$dynamodbClient = DynamoDbClient::factory ( $params );

On using this Dynamo db client and querying, I noticed the credentials are cache under /tmp/zf-cache-xx/zfcache-credentials-nnnn.dat. 

Intermittently, I noticed that RefreshableInstanceProfileCredentials.refresh() method throw InstanceProfileCredentialsException (somehow not able to connect to Metadata server). Once this happens and the expiration time is reached,  the code never tries to refresh the cache again as per the below in CacheableCredentials.php:

protected function refresh()
    {
        if (!$cache = $this->cache->fetch($this->cacheKey)) {
            // The credentials were not found, so try again and cache if new
            $this->credentials->getAccessKeyId();
            if (!$this->credentials->isExpired()) {
                // The credentials were updated, so cache them
                $this->cache->save($this->cacheKey, $this->credentials, $this->credentials->getExpiration() - time());
            }
        } else {
            // The credentials were found in cache, so update the adapter object
            // if the cached credentials are not expired
            if (!$cache->isExpired()) {
                $this->credentials->setAccessKeyId($cache->getAccessKeyId());
                $this->credentials->setSecretKey($cache->getSecretKey());
                $this->credentials->setSecurityToken($cache->getSecurityToken());
                $this->credentials->setExpiration($cache->getExpiration());
            }
     
           If somehow the refresh logic fails and expiration happens, the code need to attempt to refresh which is the else block in this case.
           
        }

**Comment by jeskew** [comment]
Requests that are rejected for having expired credentials should be retried by the DynamoDB client (as configured [here](https://github.com/aws/aws-sdk-php/blob/2.8/src/Aws/DynamoDb/DynamoDbClient.php#L121)). Could you try adding a retry logger (via the [`client.backoff.logger`](http://docs.aws.amazon.com/aws-sdk-php/v2/guide/configuration.html#client-configuration-options) option) to the DynamoDB client to see if it is retrying?

**Comment by ajaygarga** [comment]
I have added the following code to add the retry logger using Zend 2 framework Logger. Please let me know if this correct.

              $logFilePath = '/tmp/dynamodb.log';
		if (! is_file ( $logFilePath )) {
			Util::putFileContent ( $logFilePath, "AUTOCREATE\n" );
		}
		$writer = new \Zend\Log\Writer\Stream ( $logFilePath );
		
		$filter = new Priority ( ZendLogger::DEBUG );
		$writer->addFilter ( $filter );
		
		$zend_logger = new Logger ();
		$zend_logger->addWriter ( $writer );
		
		$logAdaper = new Zf2LogAdapter ( $zend_logger );
		$params ['client.backoff.logger'] = $logAdaper;
               $dynamodbClient = DynamoDbClient::factory ( $params );

But I could not test it as even if edit the cached credentials file with the past time. 

But why I doubt the expired credentials are not getting refreshed because I see the cached credentials shows ''token.ttd" as past date (say 9th Dec or so). Please refer the stacktrace attached.

[stacktrace.txt](https://github.com/aws/aws-sdk-php/files/62434/stacktrace.txt)

**Comment by jeskew** [comment]
The log captures when requests are retried, not when credentials are refreshed. Even if the first request goes out with expired credentials because the metadata service did not respond, then the [`ExpiredCredentialsChecker`](https://github.com/aws/aws-sdk-php/blob/2.8/src/Aws/Common/Client/ExpiredCredentialsChecker.php#L59) should retry the request. Is that not happening?

**Comment by ajaygarga** [comment]
Yes it seems like the retry is not happening as I see nothing comes up in the backoff retry log. What could be the reason?

**Comment by ajaygarga** [comment]
I figured out the issue why the Zend 2 cache is not updated. The issue is Zf2CacheAdapter of Guzzle doesn't pass the expiration of cache to Zend cache as per this code

public function save($id, $data, $lifeTime = false, array $options = null)
    {
        return $this->cache->setItem($id, $data);
    }

Guzzle doesn't pass the lifetime to Zend cache because Zend cache doesn't support ttl at the item level. Zend support ttl only at the Cache level.

So I modified the code to use Doctrine cache and it worked.

**Comment by jeskew** [comment]
The instance metadata client does not retry by default because the SDK is designed to fail fast when using no valid credentials are available. However, the client is a regular Guzzle client that to which you can add a retry subscriber if that pattern fits your use case. Essentially, you will need to pass in a credentials object on which you have configured the client to your needs:

```php
<?php

require 'vendor/autoload.php';

use Aws\Common\Enum\ClientOptions as Options;
use Aws\Common\Credentials\Credentials;
use Aws\Common\InstanceMetadata\InstanceMetadataClient;
use Aws\DynamoDb\DynamoDbClient;
use Guzzle\Plugin\Backoff\BackoffPlugin;

// Create an instance profile client with custom timeouts
$instanceClient = InstanceMetadataClient::factory(array(
    'request.options' => array(
        'connect_timeout' => 20,
        'timeout'         => 120
    )
));

// Add a retry subscriber to the instance metadata client
$instanceClient
    ->getEventDispatcher()
    ->addSubscriber(BackoffPlugin::getExponentialBackoff());

// Create a cache adapter that stores data on the filesystem
$cacheAdapter = <your-caching-solution>;

// Create a credentials object using the factory method
$credentials = Credentials::factory(array(
    Options::CREDENTIALS_CACHE     => $cacheAdapter,
    Options::CREDENTIALS_CLIENT    => $instanceClient,
    Options::CREDENTIALS_CACHE_KEY => 'shared_iam_credentials'
));

$s3 = DynamoDbClient::factory(array('credentials' => $credentials));
$s3->listBuckets();
```

Hope that helps!

**Comment by jeskew** [comment]
Closing for now, as the above code sample should show you how to enable retries on the InstanceMetadataClient as appropriate for your application. Please feel free to reopen if you have any questions or concerns.

**Comment by ajaygarga** [comment]
Thanks for the suggestion and the sample code. I feel it should be documented as using the ''Using IAM roles for Amazon EC2 instances" is the recommended way to provide the credentials, the InstanceMetadataClient is used only in this case and it is very likely to fail and retry.

**Comment by jeskew** [comment]
That's a good point; this isn't documented in a comprehensive way right now, and I'll open a pull request to address that.

How often is the instance metadata returning an error? It should be a very rare occurrence.

**Comment by ajaygarga** [comment]
We faced issue connecting to instance metadata and InstanceMetadataClient.getInstanceProfileCredentials() throwing an InstanceProfileCredentialsException() 4 to 5 times in two weeks. That was majorly because the credentials cache (Zf2Cache was not getting refreshed as mentioned earlier) and hence the code was hitting the instance metadata for every request to dynamo db.
