### ISSUE TITLE
Route53: UPSERT AliasTarget Fails

### ISSUE THREAD

**Issue by ronneseth** [aws/aws-sdk-php#849]
I'm creating an ALIAS record in Route 53 and I'm running into the following issue (see stack trace below). The AliasTarget record does not require a Value tag, please refer to the documentation:;

http://docs.aws.amazon.com/Route53/latest/APIReference/CreateAliasRRSAPI.html
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html

If I put in a "dummy" Value (either empty or with some string) the actual API throw back a 400 error (Invalid input).

Any help would be appreciated.

PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Found 1 error while validating the input provided for the ChangeResourceRecordSets operation:
[ChangeBatch][Changes][0][ResourceRecordSet][ResourceRecords][AliasTarget][Value] is missing and is a required parameter' in /home/revolution/server-tools/aws_sdk/Aws/Api/Validator.php:37
Stack trace:
#0 /home/revolution/server-tools/aws_sdk/Aws/Middleware.php(78): Aws\Api\Validator->validate('ChangeResourceR...', Object(Aws\Api\StructureShape), Array)
#1 /home/revolution/server-tools/aws_sdk/Aws/Route53/Route53Client.php(28): Aws\Middleware::Aws\{closure}(Object(Aws\Command), NULL)
#2 /home/revolution/server-tools/aws_sdk/Aws/AwsClient.php(208): Aws\Route53\Route53Client->Aws\Route53\{closure}(Object(Aws\Command))
#3 /home/revolution/server-tools/aws_sdk/Aws/AwsClient.php(202): Aws\AwsClient->executeAsync(Object(Aws\Command))
#4 /home/revolution/server-tools/aws_sdk/Aws/AwsClient.php(167): Aws\AwsClient->execute(Object(Aws\Command))
#5 /home/andreas/common/ in /home/revolution/server-tools/aws_sdk/Aws/Api/Validator.php on line 37

**Comment by jeskew** [comment]
Hi @ronneseth,

I'm still looking into this, but in the meantime you can disable client-side validation by passing [`'validate' => false](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#validate) to the Route53Client constructor.

**Comment by ronneseth** [comment]
Hi @jeskew:

Once I do that, the API is now returning an error. Is it easy for me to pull out the actual XML to verify I'm not making some silly mistake? I've successfully added TXT, A, MX, and CNAME records to Route 53 using the API.

PHP Fatal error:  Uncaught exception 'Aws\Route53\Exception\Route53Exception' with message 'Error executing "ChangeResourceRecordSets" on "https://route53.amazonaws.com/2013-04-01/hostedzone/Z17XV3HFQ5R8OG/rrset/"; AWS HTTP error: Client error: 400 InvalidInput (client): Invalid XML ; cvc-complex-type.2.4.b: The content of element 'ResourceRecord' is not complete. One of '{"https://route53.amazonaws.com/doc/2013-04-01/":Value}' is expected. - <?xml version="1.0"?>
<ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>InvalidInput</Code><Message>Invalid XML ; cvc-complex-type.2.4.b: The content of element 'ResourceRecord' is not complete. One of '{&quot;https://route53.amazonaws.com/doc/2013-04-01/&quot;:Value}' is expected.</Message></Error><RequestId>b7ab7e69-a2e8-11e5-9324-27bdc410832c</RequestId></ErrorResponse>'

exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: 400' in /home/revolution/server-tools/aws_sdk/GuzzleHttp/Middleware.php:69
Stack trace:
# in /home/revolution/server-tools/aws_sdk/Aws/WrappedHttpHandler.php on line 152

**Comment by ronneseth** [comment]
Hi @jeskew --

I found my issue. I accidentally had "ResourceRecord" wrapping AliasTarget. I read this post https://forums.aws.amazon.com/thread.jspa?threadID=152380 and realized that the error message is confusing in this case -- it has nothing to do with "Value". Since it didn't find AliasTarget at that level, it assumes that you must specify Value.

Sorry for the premature bug, please close.

**Comment by ronneseth** [comment]
Closing since this is a non issue, just a confusing Validator mesage (ideally it should say Value or AliasTarget required).

**Comment by jeskew** [comment]
Glad you were able to figure that out.

**Comment by cp4r3z** [comment]
5 years later, I'm hitting the same error. The solution for me was to remove an empty `ResourceRecords `array that I was passing into the UPSERT method. Hope it helps someone!
