### ISSUE TITLE
Add separate exception / method for when a signature method is no longer supported.

### ISSUE THREAD

**Issue by gdsdougherty** [aws/aws-sdk-php#860]
When using the 2.8.24 version of the sdk, instead of being informed that the v2 signing method was no longer supported for the us-west-1 / us-west-2 regions for S3, I was met with a signature does not mach exception.  As v2 is default, it seems there should be a specific error regarding this.

**Comment by jeskew** [comment]
The error is returned by the service, not the SDK, so distinguishing between "wrong signature version" errors and legitimate "signature does not match" errors would be error-prone and might break applications that know to listen for signature does not match errors to trigger an upgrade to a v4 signer.

Would you have any objection to just using v4 signatures for all S3 requests? This can be done by [setting the `signature` configuration option to 'v4'](http://docs.aws.amazon.com/aws-sdk-php/v2/guide/configuration.html), and it's what we opted to do in v3 of the SDK.

**Comment by gdsdougherty** [comment]
That's what I ended up doing, but if that's the case this should probably be noted in the documentation somewhere, at the very least on the v2 specific documentation.  New users would definitely have issues, unless this information is more readily available.

**Comment by gdsdougherty** [comment]
Also, the information at the top of this section of the documentation seems to be outdated.

http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html#specify-signature-version

**Comment by jeskew** [comment]
When trying to reproduce this, I was able to make successful requests to both us-west-1 and us-west-2 using v2 signing. Where did you read that those regions were dropping support for that signature version?

**Comment by gdsdougherty** [comment]
Hmm, it could have been an issue on my end, but I was unable to make any requests to us-west-2 with v2, and a day later, unable to make requests to any us-west-1 or 2 using v2.  It was only after changing to v4 this morning that I was able to get any responses other than the signature mismatch.  I guess I was assuming it was being phased out, but it could have been a service issue.  This would be a lot easier to distinguish if AWS let users make general inquiries about services, regardless of payment level.
