### ISSUE TITLE
Cant to use expr.distance

### ISSUE THREAD

**Issue by Dacascas** [aws/aws-sdk-php#861]
Cant to use expr.distance

I need to use distance expression which is described in - http://docs.aws.amazon.com/cloudsearch/latest/developerguide/searching-locations.html 
But code dont support this kind of Expression.

http://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.CloudSearchDomain.CloudSearchDomainClient.html#_search

**Comment by jeskew** [comment]
The CloudSearchDomain client only covers a subset of the API. For more specialized use cases, you can [use the SDKs signers to sign an arbitrary PSR-7 request with your AWS credentials](https://github.com/aws/aws-sdk-php/issues/671#issuecomment-120666137).

Hope that helps!

**Comment by jeremeamia** [comment]
Sounds like this should find it's way to the docs or blog.

**Comment by Dacascas** [comment]
Yes, big thanks I think its help
