### ISSUE TITLE
PHP library (ver 3.12.0) gets parse error(unexpected T_VARIABLE)

### ISSUE THREAD

**Issue by alesi-cloud** [aws/aws-sdk-php#863]
trying to use php library, but it gets error like below.
PHP Parse error:  syntax error, unexpected T_VARIABLE in /<mypath>/Aws/functions.php on line 36
my php is 5.3.29
same result using phar and sources and including aws-autoloader.php.

probabry this was syntax change from PHP 5.3 ?

**Comment by GrahamCampbell** [comment]
php 5.5+ is required for sdk v3

**Comment by alesi-cloud** [comment]
thank you.
I'll try install PHP 5.5 or later then.

**Comment by GrahamCampbell** [comment]
For future reference, most projects define the minimum php version in their composer.json file: https://github.com/aws/aws-sdk-php/blob/master/composer.json#L19. ;)
