### ISSUE TITLE
Using Promises to Send Out HTTP Pings During Large S3 Folder Downloads

### ISSUE THREAD

**Issue by pihish** [aws/aws-sdk-php#865]
I am currently downloading large folders from S3 (250,000+ files per folder) to my local Windows 2012 machine.  I'd like to send out a heartbeat every 30 seconds during this operation - which at the present can take up to 20 minutes.  How would I do this with Guzzle promises?

This is what I envision the code to look like:

```
$source = "c:/my-folder/4";
$dest = "s3://my-folder/4";

$manager = new \Aws\S3\Transfer($client, $source, $dest);

$transferInProgress = true;

$promise = $manager->promise();
$promise->then(function(){
    global $transferInProgress;
    $transferInProgress = false;
});

while($transferInProgress === true){
    sleep(30);
    echo date('Y/m/d H:i:s');
    echo "<br>";
    /// Call my HTTP endpoint until promise is fulfilled
}

$promise->wait();
```

The above just hangs.  I am assuming the script enters the while loop and the promise is never fulfilled.

**Comment by jeskew** [comment]
Hi @pihish,

The code snippet will hang forever, as the condition on the `while` loop will not be false until after the promise is fulfilled, but `wait` won't be called until the `while` loop terminates.

If you just want to see updates, you could try setting the [`debug` option](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-transfer.html#transfer-options) on the transfer manager:
```php
$manager = new \Aws\S3\Transfer($client, $source, $dest, ['debug' => true]);
```

This will write information on which requests have been successfully completed to stdout.

**Comment by pihish** [comment]
@jeskew Thanks, but all this does is write to output notes about the individual files as they are being transferred to S3.  I need to make a HTTP call to my endpoint every X number of seconds.  

A good analogy would be the following JavaScript code using the AWS JS SDK:

    var s3Bucket = new AWS.S3({
        params: {
            Bucket: 'pihishsBucket'
        }
    });

    var uploadRequest = s3Bucket.upload(someParameters, function(){
        // do something when upload finishes
    });

    uploadRequest.on('httpUploadProgress', function(data){
        console.log('progress is ' + data.loaded + ' of ' + data.total);
        // make my custom HTTP call every time upload progress changes
    });

I am essentially trying to mimic the behavior of `uploadRequest.on`.  I want to do something asynchronously as the upload progresses.

**Comment by jeskew** [comment]
You can pass a callback as [the `before` option to the transfer manager constructor](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-transfer.html#customizing-the-transfer-manager-s-commands) if the 30-second interval isn't crucial:
```php
$manager = new \Aws\S3\Transfer($client, $source, $dest, ['before' => function () {
    // make an HTTP request
}]);
```

This would ping your endpoint before the upload of each individual file (several times for files larger than 16 MB).

**Comment by pihish** [comment]
I ended up doing something like this

```
$lastDatetime = time();

$manager = new \Aws\S3\Transfer($client, $source, $dest, ['before' => function(){
    global $lastDatetime;
    $currentDatetime = time();
    if(($currentDatetime - $lastDatetime) >= 30){
        echo date('g:i:s a');
        echo "<br>";
        // call endpoint
        $lastDatetime = $currentDatetime;
    }
}]);
```

Since I am uploading a lot of files from a folder, I didn't want each file upload to trigger a HTTP call and have the sum of calls crash my server.  So I decided to check the current UNIX timestamp and compare it with a reference UNIX timestamp and only make the HTTP call if the difference is more than 30 seconds.
