### ISSUE TITLE
Error retrieving credentials from the instance profile metadata server. (cURL error 7: Failed to connect to 169.254.169.254 port 80: Connection refused)

### ISSUE THREAD

**Issue by nickmeessen** [aws/aws-sdk-php#866]
We're seeing this exception pop up very frequently the past month:

`PHP Fatal error:  Uncaught exception 'Aws\Exception\CredentialsException' with message 'Error retrieving credentials from the instance profile metadata server. (cURL error 7: Failed to connect to 169.254.169.254 port 80: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html))' in libraries/aws-sdk-php-3.12.0/Aws/Credentials/InstanceProfileProvider.php:79`

`#012Stack trace:#012#0 libraries/aws-sdk-php-3.12.0/GuzzleHttp/Promise/Promise.php(199): Aws\Credentials\InstanceProfileProvider->Aws\Credentials\{closure}(Array)`

`#012#1 libraries/aws-sdk-php-3.12.0/GuzzleHttp/Promise/Promise.php(152): GuzzleHttp\Promise\Promise::callHandler(2, Array, 
Array)`

`#012#2 libraries/aws-sdk-php-3.12.0/GuzzleHttp/Promise/TaskQueue.php(60): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()`

`#012#3 libraries/aws-sdk-php-3.12.0/GuzzleHttp/Handler/CurlMultiHandler.p in libraries/aws-sdk-php-3.12.0/Aws/Credentials/InstanceProfileProvider.php on line 79`

We're using 3.12.0 as you can see, like this:

`$s3 = new S3Client([
'version' => 'latest',
'region' => 'eu-west-1'
]);`

`$s3->putObject(['Bucket' => $bucket, 'Key' => $key, 'Body' => $data, 'ACL' => 'public-read']);`

And this will be executed like 10-15 times in one go for different files, running every 15 seconds.

I'm catching `(Aws\S3\Exception\S3Exception $e)`, but it won't even reach this. 

Is there anything we can do about this? I expect dropping the AWS credentials on the system itself will prevent this from happening, but we rather use IAM roles in case of security and flexibility. Or is this an AWS infrastructure problem with the EC2 metadata server?

**Comment by jeskew** [comment]
Have you tried caching the credentials? If you pass in an instance of `Aws\CacheInterface` as [the `credentials` option to a client constructor](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#credentials), the SDK will cache instance profile credentials instead of hitting the metadata service every time.

**Comment by nickmeessen** [comment]
Ahhh, didn't notice this feature it in the docs. I've implemented this yesterday morning and continued to monitoring it. No errors thus far, so it seems to resolve our issue.

Thanks! :)
