### ISSUE TITLE
Uncaught exception - with message 'Errors during multi transfer

### ISSUE THREAD

**Issue by arpan03** [aws/aws-sdk-php#868]
Hi,

I am trying to send a large chunk of 'SendEmail' commands using SESClient and Batchbuilder. 

When I run my script it runs fine for sometime then it throws this error:

    PHP Fatal error:  Uncaught exception 'Guzzle\Service\Exception\CommandTransferException' with message 'Errors during multi transfer
    (Guzzle\Http\Exception\CurlException) /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php line 359

    [curl] 77: error setting certificate verify locations:
      CAfile: /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Resources/cacert.pem
      CApath: /etc/ssl/certs [url] https://email.us-east-1.amazonaws.com/

    #0 /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(292): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
    #1 /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
    #2 /<SNIP>/vendo in /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Batch/Batch.php on line 62

Before using batchbuilder I was getting this error:

    PHP Fatal error:  Uncaught exception 'Guzzle\Service\Exception\CommandTransferException'     with message 'Errors during multi transfer
    (Guzzle\Http\Exception\CurlException) /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php line 359

    [curl] 77: error setting certificate verify locations:
      CAfile: /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Resources/cacert.pem
      CApath: /etc/ssl/certs [url] https://email.us-east-1.amazonaws.com/

    #0 /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(292): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
    #1 /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
    #2 /<SNIP>/vendo in /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Service/Exception/CommandTransferException.php on line 25

I thought using batchbuilder will fix this problem but that was not to be. 

Here is how i'm implementing my logic:

    use Aws\Ses\SesClient;
    use Guzzle\Batch\BatchBuilder;
    use Guzzle\Service\Exception\CommandTransferException;

    //Create array of commands
    $this->commands = array();

    //Logic to fill this array with commands
    $msg = array();

    $msg['Source'] = "$header <noreply@domain.com>";
    $msg['Destination']['ToAddresses'][] = "test@gmail.com";
    $msg['Message']['Subject']['Data'] = "Testing guzzle batching";
    $msg['Message']['Subject']['Charset'] = "UTF-8";
    $msg['Message']['Body']['Text']['Data'] ="";
    $msg['Message']['Body']['Text']['Charset'] = "UTF-8";
    $msg['Message']['Body']['Html']['Data'] ="test data";
    $msg['Message']['Body']['Html']['Charset'] = "UTF-8";

    $client = SesClient::factory(array(
			'key'    => '<KEY>',
			'secret' => '<SECRET>',
			'region' => 'us-east-1'
		));
    $this->commands[]= $client->getCommand('SendEmail',$msg);

    //Create batchbuilder
    $batch = BatchBuilder::factory()->transferCommands(10)->build();
			foreach ($this->commands as $command) {
			    $batch->add($command);
			}
			$batch->flush();

**Comment by arpan03** [comment]
Getting same error after trying automatically flushing a queue autoFlushAt(10)

    $batch = BatchBuilder::factory()
			    ->transferCommands(10)
			    ->autoFlushAt(10)
			    ->build();

Error: 

    PHP Fatal error:  Uncaught exception 'Guzzle\Service\Exception\CommandTransferException' with message 'Errors during multi transfer
    (Guzzle\Http\Exception\CurlException) /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php line 359

    [curl] 77: error setting certificate verify locations:
      CAfile: /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Resources/cacert.pem
      CApath: /etc/ssl/certs [url] https://email.us-east-1.amazonaws.com/

    #0 /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(292): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
    #1 /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
    #2 /<SNIP>/vendo in /<SNIP>/vendor/guzzle/guzzle/src/Guzzle/Batch/Batch.php on line 62

**Comment by jeskew** [comment]
It sounds like the certificate authority is out of date. Could you try setting [the `ssl.certificate_authority` configuration option](http://docs.aws.amazon.com/aws-sdk-php/v2/guide/configuration.html) to either `'system'` (to use your operating system's CA bundle) or to the path of an updated bundle?

See [our FAQ](http://docs.aws.amazon.com/aws-sdk-php/v2/guide/faq.html#what-do-i-do-about-a-curl-ssl-certificate-error) for more information on updating the CA bundle.

**Comment by arpan03** [comment]
For SesClient's factory?

    $client = SesClient::factory(array(
			'credentials' => array(
        		'key'    => 'abc',
				'secret' => '123',
    		),
			'region' => 'us-east-1',
			'ssl.certificate_authority' => 'system'
		));

**Comment by jeskew** [comment]
Exactly.

**Comment by arpan03** [comment]
Ok I will try it and let you know!! Btw I was reading this: http://docs.aws.amazon.com/aws-sdk-php/v2/guide/credentials.html#credential-profiles 

But I can't find ~/.aws/credentials folder under my HOME directory. Do I have to create it?

**Comment by jeskew** [comment]
You would need to create that file.

**Comment by arpan03** [comment]
Thanks!! I'd do that :+1:

**Comment by arpan03** [comment]
Btw if you can answer this then it would be super cool of you. For sending bulk emails would you recommend using batchbuilder or commandpool or something else?

**Comment by jeskew** [comment]
`Aws\CommandPool` is a v3 feature. In v2, `BatchBuilder` is a good way to send requests in batches.

**Comment by arpan03** [comment]
Hi Jonathan,

Now I'm getting this error: 

    PHP Fatal error:  Uncaught exception 'Guzzle\Service\Exception\CommandTransferException' with message 'Errors during multi transfer
    (Guzzle\Http\Exception\CurlException) /var/www/vhosts/specificfeeds.com/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php line 359

    [curl] 35: error:02001018:system library:fopen:Too many open files [url] https://email.us-east-1.amazonaws.com/

    #0 /var/www/vhosts/specificfeeds.com/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(292): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
    #1 /var/www/vhosts/specificfeeds.com/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
    #2 /var/www/vhosts/specificfeeds.com/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages()
    #3 /var/www/vhos in /var/www/vhosts/specificfeeds.com/vendor/guzzle/guzzle/src/Guzzle/Batch/Batch.php on line 62

I suspect this is due to too many concurrent requests. How should I fix this?

**Comment by arpan03** [comment]
Hi Jonathan,

I fixed it by breaking the main commands array in chunks of smaller arrays executing them one at a time and then putting the code to sleep for 15 secs. Do you think this is the right way to do it? 

    $chnkArray = array_chunk($this->commands,500);
   foreach($chnkArray as $command) {
    $client->execute($command);
    sleep(15);
   }

**Comment by jeskew** [comment]
What version of the SDK are you using? It sounds like #101 is describing the same issues you're seeing, and it was solved by upgrading to a then-current version of Guzzle.

**Comment by arpan03** [comment]
Using version 2.8.24 

Installed it through composer a few days back.

**Comment by jeskew** [comment]
@arpan03 What if instead of sleeping for 15 seconds you call `gc_collect_cycles()`?

**Comment by arpan03** [comment]
@jeskew I did read about this during my research did not try it though, now that you have recommended it I would definitely give it a try and let you know the results for the same!

**Comment by jeskew** [comment]
@arpan03 Any luck with `gc_collect_cycles()`?

**Comment by arpan03** [comment]
@jeskew right now this is low on priority since these errors pushed us back quite a bit and now that this is fixed we are focusing on other things. But nevertheless, we will try it out in the coming week and I will let you know the results!

**Comment by jeskew** [comment]
Sounds good. I'll go ahead and close this issue, as it sounds like everything's working. Please feel free to reopen if you have any questions or concerns.

**Comment by arpan03** [comment]
@jeskew Hi Jonathan, I have a question:

If you remember, I am dividing the array which contains 1000s of mails in chunks of 500 each like this -

`$chnkArray = array_chunk($this->commands,500);
foreach($chnkArray as $command)
{
    $client->execute($command);
    sleep(15);
}`

What happens when I get an error from SES, something like this: 

> URGENT: Error in newspaper sending process of hour: 5 Error occured: Errors during multi transfer
> (Aws\Ses\Exception\SesException) /var/www/vhosts/<SNIP>vendor/aws/aws-sdk-php/src/Aws/Common/Exception/NamespaceExceptionFactory.php line 91
> 
>     Illegal address

Now let's say it happened in the first chunk of 500 emails after 250 emails were sent to SES already, how does SES process the remaining 249 emails? Does it stop processing further or does it continue with the rest of the mails in that chunk?

**Comment by jeskew** [comment]
The requests are sent in parallel, and all should be resolved before a multi transfer exception is thrown.

**Comment by arpan03** [comment]
@jeskew Thanks Jonathan, that's a very good news!! (for me), I was worried that I'm not sending out all the emails if I get error for any user. 

Thanks again!!
