### ISSUE TITLE
SqsException: Error executing "ReceiveMessage"

### ISSUE THREAD

**Issue by MiroCillik** [aws/aws-sdk-php#870]
Hello, during last week or so, we are experiencing this error with SQS:

SqsException (0) in WrappedHttpHandler.php line 159:
Error executing "ReceiveMessage" on "https://sqs.us-east-1.amazonaws.com/147946154733/xxxxxx"; AWS HTTP error: cURL error 56: TCP connection reset by peer (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

This error seems to happen randomly 2-3 times per day, we're using few different SQS queues and it's happening on all of them.

We're using aws/aws-sdk-php 3.12.0.

Any idea what could be causing this?

**Comment by jeskew** [comment]
That's a network-level error, so a definitive root cause would be difficult to pin down. Can you catch the error and retry?

**Comment by MiroCillik** [comment]
Isn't there a built-in backoff for these types of errors? I have set 'retries' to 20 in SqsClient, but it seems that it has no effect.

**Comment by jeskew** [comment]
There is a built-in retry mechanism, but it won't be triggered for the particular cURL error you're seeing. The reasoning behind that is that connections can be reset after a connection has been made and work has been started, so it could be unsafe to retry non-idempotent requests. For 'ReceiveMessage,' a connection could be reset *after* a message has been pulled from the queue, which would count towards the 'MaximumReceives' configured on a queue's [redrive policy](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/SQSDeadLetterQueue.html).

**Comment by jeskew** [comment]
@MiroCillik does retrying on your end solve the issue?

**Comment by MiroCillik** [comment]
Yes it helped, thanks!
