### ISSUE TITLE
E_RECOVERABLE_ERROR when invoking Lambda function (v2.8.24)

### ISSUE THREAD

**Issue by nathankurtyka** [aws/aws-sdk-php#874]
I'm encountering the below error when trying to invoke a RequestResponse Lambda function:

```
Argument 1 passed to Guzzle\Service\Resource\Model::__construct() must be of the type array, string given, called in phar:/.../aws.phar/Guzzle/Service/Command/OperationResponseParser.php on line 86 and defined
```

Per the stacktrace below, the error appears to be originating from response processing in the core SDK (where the AWS response is processed).  

```
BACKTRACE:
 [logError(integer,string,string,integer) in file "D:\...\Error.php" at line 196.<br/>
errorHandler(integer,string,string,integer,array) in file "phar://.../aws.phar/Guzzle/Service/Resource/Model.php" at line 20.<br/>
__construct(string,NULL) in file "phar://.../aws.phar/Guzzle/Service/Command/OperationResponseParser.php" at line 86.<br/>
handleParsing(object,object,string) in file "phar://.../aws.phar/Guzzle/Service/Command/DefaultResponseParser.php" at line 39.<br/>
parse(object) in file "phar://.../aws.phar/Guzzle/Service/Command/OperationCommand.php" at line 87.<br/>
process() in file "phar://.../aws.phar/Guzzle/Service/Command/AbstractCommand.php" at line 193.<br/>
getResult() in file "phar://.../aws.phar/Guzzle/Service/Client.php" at line 138.<br/>
execute(object) in file "phar://.../aws.phar/Guzzle/Service/Command/AbstractCommand.php" at line 153.<br/>
execute() in file "phar://.../aws.phar/Guzzle/Service/Command/AbstractCommand.php" at line 189.<br/>
getResult() in file "phar://.../aws.phar/Guzzle/Service/Client.php" at line 76.<br/>
__call(string,array) in file "phar://.../aws.phar/Aws/Common/Client/AbstractClient.php" at line 104.<br/>
__call(string,array) in file "D:\...\AwsManager.php" at line 229.<br/>
invoke(array) in file "D:\...\lib\AwsManager.php" at line 229.<br/>
```

I'm encountering this on PHP 5.4, but from the error I don't believe the PHP version matters.

**Comment by jeskew** [comment]
What value are you passing to `context.succeed` in your lambda function?

**Comment by nathankurtyka** [comment]
@jeskew  Thanks for the quick reply!

I'm using a Java-backed Lambda (so no concept of context.succeed). But my Java Lambda is returning a String.  

The returned string value comes back, but the Model object clearly isn't initialized correctly (eg there's not internal array of values.. only a string value). 

Let me know if I can provide any more info. This will become a bigger problem for us in the near future.

**Comment by jeskew** [comment]
Does everything work as expected if you return [a POJO](http://docs.aws.amazon.com/lambda/latest/dg/java-programming-model-req-resp.html) instead of a string?

**Comment by jeskew** [comment]
A bit of background on this: in JavaScript, Lambda's documentation explicitly states that you should be passing an object to `context.succeed`, and V2's Lambda client was built with this in mind. Obviously, there is no such limitation in the Java documentation, where there are instructions on how to return a POJO, a string, or a byte stream. In V3 of the SDK, we treat the function's return as a PSR-7 stream, which can contain any of those data types.

I'm not sure that v2 could be changed in a backwards-compatible to support multiple return types from Lambda. I believe the issue you're seeing can be avoided either by having your Lambda function return a POJO or by upgrading to V3 of the SDK.
