### ISSUE TITLE
Possible unintended behaviour when using the transfer manager to download a list of objects

### ISSUE THREAD

**Issue by cwhite92** [aws/aws-sdk-php#875]
First, thanks for the SDK!

I'm attempting to use the transfer manager to concurrently download objects under a common prefix in an S3 bucket.

    $manager = new Transfer($s3, $iterator, $tempDir, array(
        'base_dir' => 's3://my_bucket/latest_job/',
        'concurrency' => 50,
        'debug' => true
    ));

    $manager->promise()->wait();

`$iterator` is an instance of a class that implements `Iterator`. As you can see from the var_dump below, it holds the keys to two objects stored on S3:

![Screenshot](http://i.imgur.com/O17UyYd.png)

My understanding is that the above code, used together with the iterator, would download these objects:

    s3://my_bucket/latest_job/photo/logo copy 2.png
    s3://my_bucket/latest_job/photo/logo copy 3.png

However when running the code, more than just those two objects given by the iterator are downloaded. I'm getting _every_ object under the `'s3://my_bucket/latest_job/` location, which includes objects that I don't want downloaded.

I'm not sure if this is intended behaviour or not. The [documentation on the transfer manager](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-transfer.html) states:

> In addition to providing a string value, you can also provide an \Iterator object that yields absolute filenames.

suggesting that I can pick-and-choose exactly which objects get downloaded.

**Comment by jeskew** [comment]
It appears that the supplied iterator is ignored and that the `base_dir` parameter is used instead.

Additionally, the docs on that parameter are confusing: it sounds like you must yield absolute filenames and supply a base directory, and those should be mutually exclusive. Given the way the transfer manager's constructor is validating the semantics of a transfer between `$source` and `$destination`, I would opt for having iterators supply relative paths and requiring a a `base_dir`.

**Comment by cwhite92** [comment]
Thanks for the quick turnaround! The client never has to know I had an ugly hack to manually remove objects that I didn't want to download in the first place. ;)

**Comment by cwhite92** [comment]
@jeskew: Unfortunately I think there may still be an issue with the implementation of this. The new changes allow me to download a subset of objects provided by an iterator, which is great, but the way I have to provide the keys of those objects seems counter-intuitive. I'll use some code from your tests as an example.

    $justOneFile = new \ArrayIterator(['s3://bucket/path/to/key']);

    $downloader = new Transfer($s3, $justOneFile, '/path/to/download/dir', [
        'base_dir' => 's3://bucket/path',
    ]);

It seems redundant that I should be specifying the full path to the object (including the `s3://` scheme and bucket name) in both the iterator and `base_dir`. Would it not be better to do something like:

    $justOneFile = new \ArrayIterator(['photos/christmas.jpg']);

    $downloader = new Transfer($s3, $justOneFile, '/path/to/download/dir', [
        'base_dir' => 's3://bucket/media',
    ]);

The above will translate to `s3://bucket/media/photos/christmas.jpg`. I'm not sure that my iterator should be concerned with the S3 scheme or bucket name?

Regardless, the main issue is now fixed, so thank you. :+1:

**Comment by jeskew** [comment]
The Iterator parameter was already documented as requiring absolute paths (this is how it worked in v2), so changing it to expect relative paths would be a breaking change. You're right that there is a bit of redundancy, but the `base_dir` parameter is really there to indicate what subfolder of a given bucket should be considered the top level folder when downloading. When a user supplies a path string as a source, that string can be used as both a source and a `base_dir`, but iterators are more ambiguous.

You can always use the [`\Aws\map` function](http://docs.aws.amazon.com/aws-sdk-php/v3/api/function-Aws.map.html) to prepend the base dir to each item in an iterator that yields relative paths:
```php
$justOneFile = \Aws\map(
    new \ArrayIterator(['photos/christmas.jpg']), 
    function ($relativePath) {
        return  "s3://bucket/media/$relativePath";
    }
);
```

`Aws\map` is a lazy mapping function, so you can use it for `$justOneFile` or `$overOneMillionFiles` and not have to worry about memory.

**Comment by cwhite92** [comment]
> the base_dir parameter is really there to indicate what subfolder of a given bucket should be considered the top level folder when downloading

Ah! In that case the current implementation does make sense. Just a case of me misunderstanding the role of the base_dir parameter I suppose. Thanks again.
