### ISSUE TITLE
SetValue objects should support set-like behavior

### ISSUE THREAD

**Issue by jeskew** [aws/aws-sdk-php#876]
Currently, instances of `Aws\DynamoDb\SetValue` are simple array wrappers that do little more than tag arrays as sets. Given [how sets are defined in DynamoDB's data model](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DataModel.html#DataModel.DataTypes.SetTypes) (as typed, unordered collections of unique values), the `SetValue` class could support more advanced behavior than just traversal and unwrapping.

Possible models for how sets should behave would include [Ardent\Collection\Set](https://github.com/morrisonlevi/Ardent/blob/master/src/Collection/Set.php) and [java.util.Set](https://docs.oracle.com/javase/8/docs/api/java/util/Set.html).

**Comment by mtdowling** [comment]
Sounds reasonable. I am hesitant to add a fully-fleshed out set data type to the SDK that is specific to DynamoDB, because I don't think we need things like union and difference. Maybe implementing some of the methods of ArrayAccess would be a good start.

**Comment by jeskew** [comment]
Moving to our backlog.
