### ISSUE TITLE
Upload to S3: cURL error 52: Empty reply from server

### ISSUE THREAD

**Issue by ondrejhlavacek** [aws/aws-sdk-php#883]
v3.11.6, attaching stack trace

https://keboola-logs.s3.amazonaws.com/debug-files/2016-01-21-08-23-27-56a0876ff2779-exception.html

**Comment by jeskew** [comment]
It doesn't look like the stack trace attached is using the SDK; rather, a standard Guzzle client is sending an unsigned post request to a bucket URL. An empty 100 response is the server telling you to go ahead and send your payload.

**Comment by ondrejhlavacek** [comment]
Oh, I'm really sorry for this! Closing the issue.
