### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by dadixon** [aws/aws-sdk-php#887]
I'm using was version 3.14.1. I cannot get the credentials to give read right from the server.  Even hard coding the key and secret doesn't work.  I created ~/.aws/credentials.ini file that just has my key and secret in it.  After that I try to call $s3Client = new S3Client([version, region, profile, etc.]).  Doesn't work.  Then I try the same code with my key and secret inside and that works.  Please  help

**Comment by jeskew** [comment]
The credentials file should be in ini format but not have a `.ini` extension. It should have a 'default' section defined with your key and secret:
```
$ less ~/.aws/credentials

[default]
aws_access_key_id = key
aws_secret_access_key = secret
```

Using a [credentials file](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html#using-the-aws-credentials-file-and-credential-profiles) or [environment variables](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html#using-credentials-from-environment-variables) is the recommended way of providing credentials on your own server, but if you prefer to [hard code the key and secret](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/credentials.html#using-hard-coded-credentials), it must be passed in as part of an argument hash, not as positional parameters. For example:
```php
$s3Client = new \Aws\S3\S3Client([
    'version' => '2006-03-01',
    'region' => $yourPreferredRegion,
    'credentials' => [
        'key' => $key,
        'secret' => $secret,
    ],
]);
```

**Comment by dadixon** [comment]
Thanks.  I created a new file that's just credentials with the correct format and I still get errors.

**Comment by jeskew** [comment]
Can you share an error message or stack trace?

**Comment by dadixon** [comment]
Cannot read credentials from /.aws/credentials

**Comment by jeskew** [comment]
Make sure the user your code is running as has permission to read the the file. Also, make sure that you've created the file for the correct user.

**Comment by dadixon** [comment]
should I open it to everyone? www-data?

**Comment by dadixon** [comment]
nvm.  that doesn't do anything either

**Comment by jeskew** [comment]
The file will need to be in the home folder of the user running the code. If your server executes code as `www-data`, then on an Ubuntu server the credentials file would need to be stored as `/home/www-data/.aws/credentials`. The `www-data` user should have access to its own home folder and its contents.

**Comment by dadixon** [comment]
I've moved the folder to my user's home folder and I still get this error.  I changed the mods also to see if that was it but I get the same error.  Thank you for baring with me.

**Comment by dadixon** [comment]
Works locally. :)

**Comment by jeskew** [comment]
Once you move the file into `www-data`'s home folder, you should change the ownership of the file and the `.aws` folder to `www-data` as well. Call `chown -R www-data:www-data /home/www-data/.aws` (this may need a few tweaks depending on your linux distro). You will need to be root or have sudo privileges to do so.

**Comment by dadixon** [comment]
Seems like I'm having this same issue but with s3.
http://stackoverflow.com/questions/31883374/aws-credentials-not-working-aws-credentials

**Comment by dadixon** [comment]
I might just have to go with the hard coded way. :(

**Comment by rtowings** [comment]
For others that find this thread...

The issue is that the sdk uses the environment variable $HOME to establish the users home directory.

You MUST set $HOME to an appropriate value before instantiating a client (otherwise the SDK looks for the credentials in root and will fail).

**Comment by smartsiva** [comment]
@dadixon "Cannot read credentials from /.aws/credentials"
Error itself saying it is looking under "/" not under home folder, so place .aws folder under "/" and give all permissions to www-data user  ( chmod 700 /.aws/ ) ( chown -R www-data:www-data /.aws )

Have Fun,
@smartsiva
