### ISSUE TITLE
SDK not generating correct XML

### ISSUE THREAD

**Issue by mathewpeterson** [aws/aws-sdk-php#889]
I am trying to set a logging bucket on newly created bucket but it doesn't look like the sdk is generating the needed xml for the request.

Here is a gist with some debug info: https://gist.github.com/mathewpeterson/20e8c3c6fbbb3637ed74

Any thoughts?

**Comment by jeskew** [comment]
Could you try with an updated version of the SDK? I see from the wire log that you're using 2.4.10, while the latest v2 release is [2.8.24](https://github.com/aws/aws-sdk-php/releases/tag/2.8.24). If there's a bug in that version, a fix would go out in 2.8.25.

**Comment by jeskew** [comment]
For v2, you will need to remove the `BucketLoggingStatus` array from parameters passed to `putBucketLogging` and place the `LoggingEnabled` array at the top level of the hash:
```php
$s3Client->putBucketLogging([
    'Bucket' => 'this-is-my-super-cool-test',
    'LoggingEnabled' => [
        'TargetBucket' => 'my-super-cool-logging-bucket',
        'TargetPrefix' => 'logs/this-is-my-super-cool-test/',
    ],
]);
```

This is a difference between [v2](http://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.S3.S3Client.html#_putBucketLogging) and [v3](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#putbucketlogging). Make sure you follow the v2 documentation when using version 2.4.10.

**Comment by mathewpeterson** [comment]
I did not realize I was using v2 of the client. I've upgraded to v3 it's working as expected. 

Thank you!
