### ISSUE TITLE
DynamoDB client: inconsistent result types.

### ISSUE THREAD

**Issue by jessegreathouse** [aws/aws-sdk-php#898]
As a user of the PHP SDK DynamoDB client, I expect the results of getItem, and getIterator to return items of the same type. Even though getIterator returns an iterable list, I expect that list to be made of the same type that I get from getItem.

The reality is that when I get the result from client->getItem the type is: "_Guzzle\Service\Resource\Model_" 
whereas when I get the result from client->getIterator, and iterate over the list, each item is just an _associative array_. The problem that this creates is that I have to use a different mapping method depending on the mechanism to retrieve the result. This creates an awkward arrangement in the app that I'm integrating with DDB, where I have to maintain 2 different mappers, concurrently, for every object.

I submit that if the result of getItem is a certain type, then the iterator returned from client->getIterator should be a list of items which are also that same type. The reason is because I expect to use the same mapping mechanism no matter whether I get a single item, or multiple items.

**Comment by jeskew** [comment]
The result of `GetItem` contains additional metadata on how much DynamoDB capacity was consumed by the operation. This information is not available on values yielded by `getIterator`.

**Comment by jeskew** [comment]
I played around with a few ways to get an item in DynamoDB, and, based on the amount of metadata returned by different methods of getting the same data, I believe it's fair to say that we do have a consistent result type: an associative array. 

Where that's located on a response will depend on which operation is called, but `$ddb->getItem($params)['Item']` is identical to `$ddb->batchGetItem($params)['Responses'][$tableName][0]`.

Hope that helps! Please feel free to reopen if you have any questions or concerns.
