### ISSUE TITLE
Outdated version of Composer on Elastic Beanstalk

### ISSUE THREAD

**Issue by thaiphan** [aws/aws-sdk-php#906]
Hey guys,

I've been trying to set up Magento 2 on Elastic Beanstalk. However, I need the use of the Composer's [COMPOSER_AUTH](https://getcomposer.org/doc/03-cli.md#composer-auth) environment variable that was added in a later version than is available on your service.

Would you be able to update Composer on Elastic Beanstalk or at least refer me to someone who can?

Regards,

Thai

**Comment by jeskew** [comment]
I'll reach out to the beanstalk team to see what their upgrade plans are. In the meantime, you can force a beanstalk to upgrade composer with a `.ebextensions` file, as described in [this blog post](https://blogs.aws.amazon.com/php/post/Tx2M04LCN1UEE0E/Reduce-Composer-Issues-on-Elastic-Beanstalk).

**Comment by thaiphan** [comment]
Thanks!

**Comment by jeskew** [comment]
I sent a message to the Beanstalk team, but since the COMPOSER_AUTH support looks brand new, running a composer self-update through a .ebextensions command is your best bet.

Please feel free to reopen if you have any questions or concerns.
