### ISSUE TITLE
"Fatal error:  Cannot use object of type DrupalRemoteStreamWrapper as array in /data/www/drupal/composer/vendor/aws/aws-sdk-php/src/Aws/S3/StreamWrapper.php on line 747"

### ISSUE THREAD

**Issue by PatchRanger** [aws/aws-sdk-php#909]
### Problem
I am using AWS-SDK-PHP library via Drupal module called [AmazonS3](http://drupal.org/project/amazons3).
All Drupal files are served via AWS bucket.
I am using Drupal module called [Filehash](http://drupal.org/project/filehash) in order to avoid file duplication and therefore save bandwidth.
Filehash fails to generate hash for files saved in AWS bucket with such message: "Fatal error:  Cannot use object of type DrupalRemoteStreamWrapper as array in /data/www/drupal/composer/vendor/aws/aws-sdk-php/src/Aws/S3/StreamWrapper.php on line 747".

### Possible reason
According to Guzzle\Stream\StreamInterface phpDocumentor comments, the returned value of getMetaData is "array|mixed|null".
Also http://php.net/manual/en/function.stream-get-meta-data.php notes that wrapper_data is mixed.
Looking into code, I guess there should be considered a use-case when wrapper_data is not an array but an object which implements required interface.
For now all headers treated as arrays thus the code fails with forementioned error message.

Could you please assist in investigating the forementioned issue? Is it really AWS-SDK-PHP bug or Drupal-related bug?

**Comment by jeskew** [comment]
The AmazonS3 drupal module [uses a fork of the SDK](https://github.com/justafish/drupal_amazons3/blob/7.x-2.x/composer.json#L42), and the error reported is being triggered by [a customization not present in the official SDK release](https://github.com/deviantintegral/aws-sdk-php/blob/drupal-amazons3/src/Aws/S3/StreamWrapper.php#L747). You will need to open this issue on [the fork](https://github.com/deviantintegral/aws-sdk-php).

**Comment by PatchRanger** [comment]
Thank you for clarification, it helps!

**Comment by deviantintegral** [comment]
Actually, it looks like the [code does exist in the 2.8 branch](https://github.com/aws/aws-sdk-php/blob/2.8/src/Aws/S3/StreamWrapper.php#L699)?

Here's [current diff of patches I have against the 2.8.27 release](https://github.com/aws/aws-sdk-php/compare/2.8.27...deviantintegral:2.8.27-p1), mostly related to caching that's in the 3.x SDK now.

I haven't tested this, but DrupalRemoteStreamWrapper is a class from [Remote stream wrapper](https://www.drupal.org/project/remote_stream_wrapper) that has nothing to do with the S3 stream wrapper. So how is it's class getting mixed up with wrapper_data in the s3 stream wrapper? Shouldn't that value be controlled by the stream wrapper itself? This is feeling like a bug in either Remote Stream Wrapper or Filehash. If not, perhaps @PatchRanger you could come up with a unit test demonstrating this more clearly?

**Comment by jeskew** [comment]
@deviantintegral Thanks for tracking that down. I was just going by the line numbers, which are not the same between the two versions.

According to [php.net](http://us3.php.net/manual/en/function.stream-get-meta-data.php), the `wrapper_data` returned by `stream_get_meta_data` is meant to be specific to a stream implementation. If users want to override the metadata returned for the S3 stream wrapper, then the wrapper data should be compatible -- either an array or a class implementing `ArrayAccess`.
