### ISSUE TITLE
Occassional uncaught exception when uploading large directory to S3

### ISSUE THREAD

**Issue by bill-s** [aws/aws-sdk-php#912]
When transferring a large directory containing approximately 50 files, an uncaught exception occurs on one of the multi-part transferred files with a message like the following:

Fatal error: Uncaught exception 'Aws\Exception\MultipartUploadException' with message 'An exception occurred while uploading parts to a multipart upload. The following parts had errors: - Part 8: Error executing "UploadPart" on "https://s3.amazonaws.com/FOLDER/FILE.csv?partNumber=8&uploadId=yt3vzoOtdSwDMXMVnvg8P21jxu8.2dwW66CgwVibA6o5gkueeu7ETd99zORc_fsMi5S79Xe15QytMxhOh0IHjR27h7_se.42aGf676CJUFX8njQYBdGCiX.eRPO0prwL" ; AWS HTTP error: Server error: 500 InternalError (server): We encountered an internal error. Please try again. - <?xml version="1.0" encoding="UTF-8"?> <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>43DEB9862AF4B332</RequestId><HostId>fpPSO0oWL+h7UyyEBCJIYB0vsMutY5ZbDyN8OxgG5dgCbjx0PRYvn7S77FN5qPo3</HostId></Error> ' in ... Stack trace: #0 [internal function]: Aws\Multipart\AbstractUploader::Aws\Multipart\{closure}( in C:\FOLDER\services\vendor\aws\aws-sdk-php\src\Multipart\AbstractUploader.php on line 130

Some of the folder/file references have been altered in the above message...

When this message is generated as an uncaught exception, it unfortunately stops the php program.

The BUG is that all exceptions are supposed to be caught in the code as you can see below.  So either something is missing from this simple synchronous upload code request, or there is a bug in one of the underlying class libraries...  Please help since this a daily production run, which then needs to be completed manually.

    $client = new \Aws\S3\S3Client([
                    'region'  => 'us-east-1',
                    'version' => '2006-03-01',
                    'profile' => 'customer_profile',
                    ]);

    // Where the files will be sourced from
    $source = "/temp/final_csv";

    // Where the files will be transferred to
    $d = new DateTime($cday);

    if ($multiday_file) {
        $folderName = $d->format('Ym');
        $dest = 's3://extracts/HistoricalFiles/' . $folderName;
        }
    else {
        $d->modify('+1 day');
        $folderName = $d->format('Ymd');
        $dest = 's3://extracts/DailyFiles/' . $folderName;
        }

    //  Transfer all of the files...
    //  Create a transfer object.
    $manager = new \Aws\S3\Transfer($client, $source, $dest /*, array("debug"=>true) */);
    try {
        // Perform the transfer synchronously.
        $manager->transfer();
        }
    catch (S3Exception $e) {
        $errMsg = 'S3 Error: ' . $e->getMessage();
        log_message(ERROR, AWS_S3_ERROR_CLASS, $errMsg . '[$dest]');
        }
    catch (AwsException $e) {
        $errMsg = 'AWS Error: RequestID=' . $e->getAwsRequestId() . ' Type= ' .
            $e->getAwsErrorType() . 'Error Code=' . $e->getAwsErrorCode();
        log_message(ERROR, AWS_S3_ERROR_CLASS, $errMsg . '[$dest]');
        }
    //  Release the manager (and hopefully all of its resources)
    $manager = null;

Though we haven't thoroughly checked yet, we also believe there might be memory leaks in one or more of the underlying classes.  While this isn't an issue on single day runs, we have difficulty when performing multi-day runs.  Thanks.

**Comment by jeskew** [comment]
The S3 client will retry failures up to three times each, and errors will only be surfaced once all retries have been exhausted. You can increase the number of by setting the [`'retries'` configuration parameter](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#retries) when creating an S3 client.

`Aws\Exception\MultipartUploadException` extends `\RuntimeException`, so you would need to catch that separately from any `S3Exception`s or `AwsException`s.

**Comment by jeskew** [comment]
Closing, as catching `Aws\Exception\MulitpartUploadException` would stop the program from exiting with an uncaught exception. Please feel free to reopen if you have any questions or concerns.

**Comment by bill-s** [comment]
Jonathan,

Thanks.  I would suggest that the AWS S3 documentation’s example be updated to include the information you provided.

The biggest complaint about the SDK is its sparse documentation and examples.

Bill

**Comment by bill-s** [comment]
Simply adding "catch (MultipartUploadException $e) {...}" does NOT catch the exception.  What needs to change to catch the exception?

While increasing the retry count has reduced the frequency, the upload is still failing occasionally on the same large file.

**Comment by jeskew** [comment]
Are you encountering a different exception? The one mentioned in the description of this issue is an `Aws\Exception\MultipartUploadException`.

**Comment by bill-s** [comment]
Yes.  I have added a "catch (MultipartUploadException $e) {...}" immediately after the "catch (S3Exception) {...}" in the code above.  It does not catch the exception.  When doing the multi-part upload, is it running on a separate thread which may not be caught by this "suspended" thread?

**Comment by jeskew** [comment]
The SDK does not use separate threads, as userland multithreading is not available on most PHP installations.

**Comment by bill-s** [comment]
At any rate, it appears that there is bug in the library which is preventing the calling code to catch the exception.  Since I cannot reopen this issue, should I file a new one?

**Comment by jeskew** [comment]
Are you sure you've set up a catch block typed against `\Aws\Exception\MultipartUploadException` and that an instance of `\Aws\Exception\MultipartUploadException` is slipping through that catch block?

One possible source of confusion here is that exceptions thrown in a `catch` block will not be caught by subsequent `catch` blocks in the same `try/catch/finally` statement. For example:
```php
try {
    throw new Exception;
} catch (Exception $e) {
    throw new RuntimeException("Can't catch me!");
} catch (RuntimeException $e) {
    echo "Caught it!\n";
}
```
will terminate with `Fatal error: Uncaught exception 'RuntimeException' with message 'Can't catch me!'`
