### ISSUE TITLE
Getting retry information from a command

### ISSUE THREAD

**Issue by Sazpaimon** [aws/aws-sdk-php#913]
In v2 of the SDK, we had the ability to attach a Guzzle logger that would get run whenever a request had to retry. There currently doesn't exist this functionality in v3, nor any hack to get anything like that. This is actually a hard blocker for us to migrate to v3.

In a Gitter chat, @jeskew brought up the possibility of adding metadata to a response that showed how many retries a particular request took. He also said that an "on_retry" callable could be injected that would allow a user to action off of every retry. The former would be useful, for example, for DynamoDB users as it can assist in autoscaling and giving an idea on the user experience. I'm not sure what the latter would be helpful for, though.

**Comment by Sazpaimon** [comment]
Actually, the latter can be useful if you wanted to take action after the nth retry. For instance, if you have a DynamoDB table where after the 6th retry, you retry the request to another table.

**Comment by mtdowling** [comment]
+1 on looking at adding the number of retries to the result.

I'd prefer that we wait on adding an on_retry. We may be looking to add some kind of idempotency token to requests that would allow you to inject middleware that can group requests together as a single transaction, so on_retry might be unnecessary.

**Comment by jeskew** [comment]
Reporting the number of retries and supporting an `on_retry` callable aren't mutually exclusive. and the former seems more obviously useful. If there's a use case that isn't solvable by inspecting the number of retries reported, we can revisit `on_retry` in the future.
