### ISSUE TITLE
Fatal error (on promise) when trying to use Transfer Manager on S3Client 

### ISSUE THREAD

**Issue by FabioQ** [aws/aws-sdk-php#917]
Hi,
I'm trying to use the Transfer manager to clone an S3 bucket in my local storage.
this is the code I'm using (last sdk version)
```
       try {
            $sourcebucketurl = 's3://' . $sourcebucket['bucket'] . '/' . $sourcebucket['basepath'];

            $manager = new Transfer($sourceS3, $sourcebucketurl , $dumppath, array('concurrency'=>5));

            $manager->transfer();

        }catch (S3Exception $e) {

            $output->writeln($e->getMessage());

        }
```

The bucket contains like 15000 images and after the almost same amount of image downloaded I get a fatal error:
Fatal error: Cannot resume an already running generator in project\vendor\guzzlehttp\promises\src\EachPromise.php on line 173

I guess the manager->transfer stops because the bucket is quite heavy, but I cannot figure out how to solve it and avoid this block, is there something options I should use while creating the new Transfer object? is this a bug?

EDIT: same behavior if I use this code below
```
        //dump bucket on local tmp folder
        try {
            $sourcebucketurl = 's3://' . $sourcebucket['bucket'] . '/' . $sourcebucket['basepath'];
            $manager = new Transfer($sourceS3, $sourcebucketurl , $dumppath, array('concurrency'=>50));
            //$manager->transfer();
            $promises []= $manager->promise();
            $metaPromise = \GuzzleHttp\Promise\all($promises)->wait();
        }catch (\Exception $e) {
            $output->writeln($e->getMessage());
        }
```

Thanks a lot!

**Comment by FabioQ** [comment]
Thanks @jeskew , smooth fix, tested it right now and it solved my problem with iterator.

**Comment by jeskew** [comment]
Glad everything worked out. Please feel free to reopen this issue if you have any questions or concerns.
