### ISSUE TITLE
Allowed memory size memory exhausted

### ISSUE THREAD

**Issue by pelallemant** [aws/aws-sdk-php#921]
Hi,

In case of big uploads, when we use $s3->putObject on files of about 2MB, by the following way, the script crash because of "allowed memory  exhausted" : 

```
$s3->putObject([
   ... ,
   'Body' => fopen($filename, 'r')
]);
```

The error is : 

<b>Fatal error</b>: Allowed memory size of 134217728 bytes exhausted (tried to allocate 826378 bytes) in <b>.../vendor/guzzlehttp/psr7/src/Stream.php</b> on line <b>94</b> 

I didnt get that error while uploading 40.000 files of about 200ko, but with files of 2Mb each, I get that error each 3 minutes if I don't increase the memory allowed in php.ini . 

Best regards

**Comment by jeskew** [comment]
Do you have garbage collection enabled? Running this script, I recorded memory usage cycling from 5 MB to 17 MB and then back again after garbage collection completed:
```php
$s3 = new \Aws\S3\S3Client([
    'region' => 'us-west-2',
    'version' => 'latest',
]);

// Make sure the bucket exists
if (!$s3->doesBucketExist($bucket)) {
    $s3->createBucket(['Bucket' => $bucket]);
    $s3->waitUntil('BucketExists', ['Bucket' => $bucket]);
}

// Create a 3 MB file
$tempFile = tempnam(sys_get_temp_dir(), time());
file_put_contents($tempFile, str_repeat('x', 3 * 1024 * 1024));

for ($i = 0; $i < 15000; $i++) {
    // Put the file 15,000 times
    $s3->putObject([
        'Bucket' => $bucket,
        'Key' => "{$i}.ext",
        'Body' => fopen($tempFile, 'r'),
    ]);

    // Report memory usage following each upload
    echo str_pad($i, 7, ' ', STR_PAD_LEFT) . ': '
        . number_format(memory_get_usage())
        . "\n";
}
```

With garbage collection disabled, memory usage will slowly climb until it reaches the configured limit and a fatal out-of-memory error is thrown.

**Comment by jeskew** [comment]
Please feel free to reopen if enabling garbage collection does not resolve the memory issue for you.

**Comment by worldlyjohn** [comment]
For me it was a permission problem. PHP output shows fatal error, but when I check my custom log I get a 403 Forbidden from AWS.  Make sure the key/secret has the correct permission.  Turns out you need `PutObjectAcl` when doing a `PutObject`

**Comment by tedchou12** [comment]
@Yahampath

Hi Yahampath, have you solved this?
Sorry for bothering.

Ted
