### ISSUE TITLE
No bucket exception message - multipart upload

### ISSUE THREAD

**Issue by techypaul** [aws/aws-sdk-php#923]
Hi,

I kept getting an exception and took me ages to work out what the issue was. My own fault of course, I changed a bucket name but didn't create the bucket (doh!).

The exception message was not very useful however:
`An exception occurred while initiating a multipart upload.`

The first line of the stack trace was:
`$e->getTraceAsString() #0 /var/www/dev.com/sites/all/libraries/aws/GuzzleHttp/Promise/Promise.php(199): Aws\Multipart\AbstractUploadManager->Aws\Multipart\{closure}(Object(Aws\S3\Exception\S3Exception))`

It would be more useful if this provided a better error, e.g. credentials or non-existing bucket.

Thanks,
Paul.

**Comment by jeskew** [comment]
You can inspect the previous exception bound to a MultipartUploadException, which in the case you're describing would be an instance of `Aws\S3\Exception\S3Exception` with a message of `Error executing "CreateMultipartUpload" on "https://s3-<region>.amazonaws.com/<bucket>/<key>?uploads"; AWS HTTP error: Client error response [url] https://s3-<region>.amazonaws.com/<bucket>/<key>?uploads [status code] 404 [reason phrase] Not Found NoSuchBucket (client): The specified bucket does not exist`.

I think it would reasonable to suffix the previous exception message to the MultipartUploadException message, which would then be verbose but helpful.
