### ISSUE TITLE
S3 Async Downloads of Single File Using PHP SDK V3

### ISSUE THREAD

**Issue by pihish** [aws/aws-sdk-php#927]
I am currently able to do async upload / downloads of folders through the PHP V3 SDK using the Transfer Manager (https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-transfer.html).

The Transfer Manager doesn't work for individual files.  Is there something I can use for async transfers for individual files?

**Comment by jeskew** [comment]
Individual files can be downloaded using [the `GetObject` command](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#getobject) or uploaded using [the `upload` method on S3Client](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.S3.S3Client.html#_upload). You could also supply a single-item iterator to the transfer manager, but `GetObject` and `upload` would be more efficient.

**Comment by jeskew** [comment]
Sorry; I missed the word 'async' in your question. You can call `$s3Client->getObjectAsync` and `$s3Client->uploadAsync` to perform the asynchronous equivalent of `GetObject` and `upload`, respectively.

**Comment by pihish** [comment]
Is there documentation somewhere which describes on how to use `getObjectAsync()`?  The only mention of it I see in the documents - or anywhere on the web for that matter - is at https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#getobject.  According to this, it has the same method signatures as `getObject()`.  

Specifically, I'd like to know how I can pass in the equivalent of a 'before' callback function like in the Transfer Manager.  This is what I have using the Transfer Manager that I would like to mimic using the `getObjectAsync()` method:

```
        $lastDatetime = time();   
        return new \Aws\S3\Transfer($this->client, 's3://mybucket/path/to/folder/',
            'c:/path/to/local/', array(
                'base_dir' => '/path/to/folder/',
                'before' => function()use(&$lastDatetime){
                    $currentDatetime = time();
                    if($currentDatetime - $lastDatetime >= 30){
                        // Do something every 30 seconds during the download
                        $lastDatetime = $currentDatetime;
                    }
                }
            )
        );
```

Essentially, I want do something every 30 seconds during a long folder (or in the case of `getObjectAsync()` a long file) download.

**Comment by jeskew** [comment]
Client methods that are suffixed with 'Async' are asynchronous versions of a command. `GetObjectAsync` takes the same arguments as `GetObject` and returns a promise that will be fulfilled with the result documented for `GetObject` or rejected with an `AwsException`. More general documentation on async methods in the SDK can be found [here](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/promises.html#promises-in-the-sdk).

As to the progress question: are you using the default (Guzzle 6) HTTP handler? If so, you can take advantage of the [`progress` request option](https://github.com/guzzle/guzzle/blob/5c12b74e9405c50fb0fd6ab831dd6e9df5560b1f/src/RequestOptions.php#L172), which takes a callable that will be invoked as a request progresses. You could pass that along to the HTTP handler in an operation with the [`http` SDK configuration parameter](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html#http):
```php
$client = new S3Client([
    'region' => 'us-west-2',
    'version' => 'latest',
    'http' => [
        'progress' => function (
            $bytesToDownload,
            $bytesDownloadedSoFar,
            $bytesToUpload,
            $bytesUploadedSoFar
        ) {
            // act on this progress information
        }
```

**Comment by pihish** [comment]
Thanks, I was able to make it work using the progress callback.

Is there a similar progress callback on the Transfer Manager (code example from my initial post)?  I'd like to be able to show real-time download progress on a folder transfer too if possible.

**Comment by jeskew** [comment]
You can use the `before` callback to [modify commands before they are dispatched by the transfer manager](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-transfer.html#customizing-the-transfer-manager-s-commands). You could bind a progress callback to each command like so:
```php
$lastDatetime = time();
return new \Aws\S3\Transfer($this->client, 's3://mybucket/path/to/folder/',
    'c:/path/to/local/', array(
        'base_dir' => '/path/to/folder/',
        'before' => function (CommandInterface $command) use (&$lastDatetime){
            $command['@http']['progress'] = function (
                $bytesToDownload,
                $bytesDownloadedSoFar,
                $bytesToUpload,
                $bytesUploadedSoFar
            ) {
                // do something on progress
            };
            $currentDatetime = time();
            if($currentDatetime - $lastDatetime >= 30){
                // Do something every 30 seconds during the download
                $lastDatetime = $currentDatetime;
            }
        }
    )
);
```

**Comment by pihish** [comment]
This is giving me the total / downloaded progress of each individual file.  Any way, I can get the total size of the folder I am downloading, and the aggregate downloaded size so far for everything within that folder?

**Comment by jeskew** [comment]
`progress` callables on a command report on the progress of individual files, and `before` callables on a transfer manager are invoked before each command is dispatched. There's no transfer-manager level `progress` callable, as that would require walking the source and stating each object before beginning the transfer. You could use the `before` callback to update a running total of bytes to transfer and then refer to that data in the associated `progress` callback, but there would be a performance cost to doing so.
