### ISSUE TITLE
CloudWatch Event Rules in V2

### ISSUE THREAD

**Issue by adam-ut** [aws/aws-sdk-php#928]
Are there plans to provide the ability to manage Event Rules for CloudWatch in the v2 branch?

_This should probably have been placed in the Developer Forum, however, I'm unable to post most likely due to how my SSO is setup where I work._

**Comment by jeskew** [comment]
Not at this time. New services are being added to the most recent version of the SDK, and v2 is continuing to receive bug fixes as necessary.

**Comment by adam-ut** [comment]
Thanks, @jeskew!
