### ISSUE TITLE
S3 putObject incorrectly closes file handle due to GC

### ISSUE THREAD

**Issue by ericnorris** [aws/aws-sdk-php#929]
When calling [putObject](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#putobject) with a bare file resource (i.e. one returned from `fopen()`), the SDK will wrap it in a `GuzzleHttp\Psr7\Stream` (see [here](https://github.com/aws/aws-sdk-php/blob/fa9ac145360/src/Api/Serializer/RestSerializer.php#L115)). Unfortunately, this class has a [__destruct method](https://github.com/guzzle/psr7/blob/a6b5f731c/src/Stream.php#L85-L88) that calls `fclose()` on the wrapped resource.

This means that a valid file handle may be closed at any time when GC decides to call the destructor, and code relying on the stream may suddenly have an invalid file handle.

Here is a reproducible test case:
```php
error_reporting(E_ALL);

$s3_client = new \Aws\S3\S3Client([
    'credentials' => [
        'key'    => 'ACCESS KEY HERE',
        'secret' => 'SECRET KEY HERE'
    ],
    'region'  => 'us-east-1',
    'version' => '2006-03-01'
]);

$handle = tmpfile();

fwrite($handle, "this is a test string");
rewind($handle);

$s3_client->putObject(array(
    'Bucket'       => 'bucket',
    'Key'          => 'dev/test.txt',
    'Content-Type' => 'text/plain',
    'Body'         => $handle
));

// Force garbage collection
gc_collect_cycles();

// Should print out "resource type: stream"
echo "resource_type: " . get_resource_type($handle) . "\n";

// Should work, but doesn't
$result = fclose($handle);
```

The output:
```
resource_type: Unknown
fclose(): 110 is not a valid stream resource at ...
```

Ideally one should not have to guard against a client library going rogue and closing the file handle, as it can cause very subtle bugs.

Let me know if I should instead file this against the Guzzle library, but it seemed more appropriate here - if the AWS library called `detach()` on the wrapped stream before returning it should avoid the issue.

**Comment by jeskew** [comment]
I'm not sure I would classify this as "a client library going rogue." Guzzle takes ownership of- and uses a RAII abstraction over streams because they are not easily sharable. An HTTP client will necessarily modify a resource handle in potentially destructive ways; if a handle is used a part of a request, its internal pointer will be moved to the end of the resource, which would render a non-seekable stream useless and leave a seekable stream in a different state.

You could prevent the file from being closed by wrapping it in a `GuzzleHttp\Psr7\Stream` before handing it to a `PutObject` command. If the input to `GuzzleHttp\Psr7\stream_for` is an instance of `Psr\Http\Message\StreamInterface`, it will be returned unmodified. This will let you keep the stream in scope and ineligible for garbage collection as long as you'd like, though you will need to handle pointer juggling on your own.

**Comment by ericnorris** [comment]
While I understand, I don't think I agree. It seems entirely reasonable to assume that you should be able to close a file handle within the same scope that you opened it. At a minimum, nowhere in the SDK documentation does it mention this particular side effect is possible.

If the SDK simply called detach() on any "wrapped" resource streams, this could be prevented without the caller being responsible for understanding the internals of the black box. Alternatively, the SDK could return the wrapped stream to leave it up to the caller. The latter seems less intrusive, but I can't comment as to how easy that would be to implement.

This created a very subtle bug in the code I had written, and I'd like to spare other developers from the pain of creating dummy stream filters to debug where fclose() was being called.

**Comment by ericnorris** [comment]
Thanks for your amazingly quick responses @jeskew and @mtdowling, I am super impressed! I had already implemented the `GuzzleHttp\Psr7\Stream` solution in my code, but I filed the issue anyway because of my aforementioned desire to spare other developers.

If it's something that can't be changed, then it can't be changed - I'll go ahead and close this issue, but I'd definitely recommend updating the documentation!

**Comment by kbca** [comment]
My God, I just faced exactly the same experience and couldn't find anywhere in documentation, anything related to this. When I was debugging before and after the putObject, and saw it was closing the resource from a different scope, and didn't show in any part of the documentation about this behavior, it got me pissed off. At least I can see now it was not only me. I'll implement the solution suggested by @jeskew, but I'd like to see it mentioned in the docs somewhere, indeed!

**Comment by SamRemis** [comment]
@kbca Thank you for bringing this back to our attention, I will try to get a note added to the PutObject call ASAP.

**Comment by SamRemis** [comment]
I have added a note to the docs with this PR: https://github.com/aws/aws-sdk-php/pull/2202.  It should show up in the docs with the next release by Tuesday.
