### ISSUE TITLE
Error 403 on send email

### ISSUE THREAD

**Issue by IgorDePaula** [aws/aws-sdk-php#932]
I received this error:

```PHP Fatal error:  Uncaught exception 'Aws\Ses\Exception\SesException' with messa                                                                                                                ge 'Error executing "SendEmail" on "https://email.us-east-1.amazonaws.com"; AWS                                                                                                                 HTTP error: Client error: `POST https://email.us-east-1.amazonaws.com` resulted                                                                                                                 in a `403 Forbidden` response:
<ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">
  <Error>
    <Type>Sender</Type>
    <Code>SignatureDo (truncated...)
 SignatureDoesNotMatch (client): The request signature we calculated does not ma                                                                                                                tch the signature you provided. Check your AWS Secret Access Key and signing met                                                                                                                hod. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/

host:email.us-east-1.amazonaws.com
x-amz-date:20160315T202018Z

host;x-amz-date
03ba3e38f29f07d0bf598966062cc5ba3cfd553b025191375f8bfdf8e8544de1'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20160315T202018Z
20160315/us-east-1/ses/aws4_request
68fccd51153f9c5a48435331a44b105955c44e5ff0ee94f4faad7f8ac5291722'
 - <ErrorResponse xmlns="http://ses.am in /home/ubuntu/aws-experiment/vendor/aws                                                                                                                /aws-sdk-php/src/WrappedHttpHandler.php on line 159
```
with script

https://gist.github.com/IgorDePaula/6bb383286990084839c2

executed on ec2 instance.

I tried the smtp credentials, and user with permisstion and policy with full acces to ses.

I tried with last version sdk php and zend mail, and any success. The documentation is confused.

**Comment by jeskew** [comment]
Are you providing an SMTP password to the SES client?

**Comment by IgorDePaula** [comment]
Yes.
Em 15/03/2016 20:09, "Jonathan Eskew" <notifications@github.com> escreveu:

**Comment by IgorDePaula** [comment]
I read again the documentation, and see that for send email from instances ec2, i not need fo credentials. Sorry by confusion.
