### ISSUE TITLE
fix composer guzzle dependencies

### ISSUE THREAD

**Issue by arosenhagen** [aws/aws-sdk-php#936]
This is a very old one and should be fixed someday:

```
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
```

**Comment by GrahamCampbell** [comment]
> This is a very old one and should be fixed someday:

You need to upgrade to aws sdk v3.

**Comment by arosenhagen** [comment]
I refer here to the `composer.json` of the current master branch of this repo.

**Comment by GrahamCampbell** [comment]
> I refer here to the composer.json of the current master branch of this repo.

You can't. Look at it. There are no `guzzle/` packages in there?

**Comment by arosenhagen** [comment]
yes - that's the problem ;-) `guzzlehttp` has been abandoned and is now `guzzle/guzzle`. Therefore I almost always get this warning when installing/updating via composer. 

```
"guzzlehttp/guzzle": "~5.3|~6.0.1|~6.1",
"guzzlehttp/psr7": "~1.0",
"guzzlehttp/promises": "~1.0",
```

**Comment by GrahamCampbell** [comment]
> guzzlehttp has been abandoned and is now guzzle/guzzle. Therefore I almost always get this warning when installing/updating via composer.

I'm, pretty sure you are wrong here. guzzlehttp/guzzle is the new package.

**Comment by arosenhagen** [comment]
*shrgs...shame on me. Had a dependency to another package - so you're right: `guzzlehttp/guzzle`is the current one. sorry!
