### ISSUE TITLE
not able to send mail using aws-sdk-php 

### ISSUE THREAD

**Issue by Poojal123** [aws/aws-sdk-php#941]
in my project 
php 5.6
framwork laravel 5.1
aws-sdk-php :3.17
and i also made changes in my .env file and config/mail.php and config/service.php but getting follwing error while sending mail 

Error executing "SendRawEmail" on "https://email.us-west-2.amazonaws.com"; AWS HTTP error: Client error: 400 InvalidParameterValue (client): Illegal address - <ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">
<Error>
<Type>Sender</Type>
<Code>InvalidParameterValue</Code>
<Message>Illegal address</Message>
</Error>
<RequestId>bfa87383-f573-11e5-b118-e921f7779a13</RequestId>
</ErrorResponse>

**Comment by cjyclaire** [comment]
It looks like a problem of client-side address validation, could you try checking the format of email address and its verification?
1.  http://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.Ses.SesClient.html#_sendRawEmail
2.  http://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-addresses-and-domains.html

Then can you share more of the changes you made in the config files?

**Comment by GrahamCampbell** [comment]
Did you make sure you ran `php artisan config:cache` after making changes to the env/config files?

**Comment by Poojal123** [comment]
my .env file

MAIL_DRIVER=ses
MAIL_HOST=email-smtp.us-east-1.amazonaws.com
MAIL_PORT=587
MAIL_ENCRYPTION=''
MAIL_USERNAME='my uer name'
MAIL_PASSWORD='password'
AWS_ACCESS_KEY_ID='key'
AWS_SECRET_ACCESS_KEY='secret key'
AWS_REGION=us-east-1


and my config/mail.php file

<?php

return [

	/*
	|--------------------------------------------------------------------------
	| Mail Driver
	|--------------------------------------------------------------------------
	|
	| Laravel supports both SMTP and PHP's "mail" function as drivers for the
	| sending of e-mail. You may specify which one you're using throughout
	| your application here. By default, Laravel is setup for SMTP mail.
	|
	| Supported: "smtp", "mail", "sendmail", "mailgun", "mandrill", "log"
	|
	*/

	'driver' => env('MAIL_DRIVER', 'ses'),

	/*
	|--------------------------------------------------------------------------
	| SMTP Host Address
	|--------------------------------------------------------------------------
	|
	| Here you may provide the host address of the SMTP server used by your
	| applications. A default option is provided that is compatible with
	| the Mailgun mail service which will provide reliable deliveries.
	|
	*/

	'host' => env('MAIL_HOST', ''),

	/*
	|--------------------------------------------------------------------------
	| SMTP Host Port
	|--------------------------------------------------------------------------
	|
	| This is the SMTP port used by your application to deliver e-mails to
	| users of the application. Like the host we have set this value to
	| stay compatible with the Mailgun e-mail application by default.
	|
	*/

	'port' => env('MAIL_PORT', 587),

	/*
	|--------------------------------------------------------------------------
	| Global "From" Address
	|--------------------------------------------------------------------------
	|
	| You may wish for all e-mails sent by your application to be sent from
	| the same address. Here, you may specify a name and address that is
	| used globally for all e-mails that are sent by your application.
	|
	*/

	'from' => ['address' => null, 'name' => null],

	/*
	|--------------------------------------------------------------------------
	| E-Mail Encryption Protocol
	|--------------------------------------------------------------------------
	|
	| Here you may specify the encryption protocol that should be used when
	| the application send e-mail messages. A sensible default using the
	| transport layer security protocol should provide great security.
	|
	*/

	'encryption' => 'tls',

	/*
	|--------------------------------------------------------------------------
	| SMTP Server Username
	|--------------------------------------------------------------------------
	|
	| If your SMTP server requires a username for authentication, you should
	| set it here. This will get used to authenticate with your server on
	| connection. You may also set the "password" value below this one.
	|
	*/

	'username' => env('MAIL_USERNAME', ''),

	/*
	|--------------------------------------------------------------------------
	| SMTP Server Password
	|--------------------------------------------------------------------------
	|
	| Here you may set the password required by your SMTP server to send out
	| messages from your application. This will be given to the server on
	| connection so that the application will be able to send messages.
	|
	*/

	'password' => env('MAIL_PASSWORD','' ),

	/*
	|--------------------------------------------------------------------------
	| Sendmail System Path
	|--------------------------------------------------------------------------
	|
	| When using the "sendmail" driver to send e-mails, we will need to know
	| the path to where Sendmail lives on this server. A default path has
	| been provided here, which will work well on most of your systems.
	|
	*/

	'sendmail' => '/usr/sbin/sendmail -bs',

	/*
	|--------------------------------------------------------------------------
	| Mail "Pretend"
	|--------------------------------------------------------------------------
	|
	| When this option is enabled, e-mail will not actually be sent over the
	| web and will instead be written to your application's logs files so
	| you may inspect the message. This is great for local development.
	|
	*/

	'pretend' => false,

];


and my config/service.php file

'ses' => [
		'key' =>  getenv('AWS_ACCESS_KEY_ID'),
		'secret' => getenv('AWS_SECRET_ACCESS_KEY'),
		'region' => 'us-east-1',
              'version' => 'latest',
            
	],


php 5.6
framwork laravel 5.1
aws-sdk-php :3.17
after all this changes getting same error  plz help me to solve this 

Error executing "SendRawEmail" on "https://email.us-east-1.amazonaws.com"; AWS HTTP error: Client error: 400 InvalidParameterValue (client): Illegal address - <ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">
<Error>
<Type>Sender</Type>
<Code>InvalidParameterValue</Code>

**Comment by jeskew** [comment]
@Poojal123 The address supplied is being rejected with an `InvalidParameterValue` exception. Have you verified that the address of the recipient is valid?

**Comment by Poojal123** [comment]
i verified my from email address in ses (IAM) console but then also getting same error as follow

Error executing "SendRawEmail" on "https://email.us-east-1.amazonaws.com"; AWS HTTP error: Client error: 400 InvalidParameterValue (client): Illegal address -

Sender
InvalidParameterValue


plz reply fast....

**Comment by jeskew** [comment]
The "Illegal address" error can refer to the *recipient's* address, as described in [this AWS forum thread](https://forums.aws.amazon.com/thread.jspa?messageID=254059).

**Comment by Poojal123** [comment]
when i use VerifyEmailIdentity method to verify mail address that time getting this error

Error executing "VerifyEmailIdentity" on "https://email.us-west-2.amazonaws.com"; AWS HTTP error: Client error: 403 AccessDenied (client): User: arn:aws:iam::656786582583:user/user name is not authorized to perform: ses:VerifyEmailIdentity - <ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">
<Error>
<Type>Sender</Type>
<Code>AccessDenied</Code>
<Message>User: arn:aws:iam::656786582583:user/user name is not authorized to perform: ses:VerifyEmailIdentity</Message>
</Error>
<RequestId>c5f33708-f7da-11e5-9de4-7d09fc8f79d0</RequestId>
</ErrorResponse>

**Comment by jeskew** [comment]
@Poojal123 Your IAM user does not have permission to use the `VerifyEmailIdentity` method. These questions might be better suited to the SES forum, as the SDK is just surfacing errors from SES.

**Comment by jeskew** [comment]
Closing, as these are not issues with the SDK but instead errors returned by SES and surfaced by the SDK. Please feel free to reopen if you have any questions or concerns.
