### ISSUE TITLE
Presigned requests headers are not lowercase as stated in the docs

### ISSUE THREAD

**Issue by tehscorpion** [aws/aws-sdk-php#951]
Recently i tried to use the aws sdk with minio server, which is a s3 drop in replacement.
Frankly the aws sdk does NOT lowercase the headers before signing (at least the host header). 

minio/minio does implement the following:
http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

> To create the signed headers list, convert all header names to lowercase, sort them by character code, and use a semicolon to separate the header names. The following pseudocode describes how to construct a list of signed headers. Lowercase represents a function that converts all characters to lowercase.
> 
> SignedHeaders =
> Lowercase(HeaderName0) + ';' + Lowercase(HeaderName1) + ";" + ... + Lowercase(HeaderNameN)
> Build the signed headers list by iterating through the collection of header names, sorted by lowercase character code. For each header name except the last, append a semicolon (';') to the header name to separate it from the following header name.
> 
> Example signed headers
> 
> content-type;host;x-amz-date\n

if i change SignatureV4.php line 86 to:
`$parsed['query']['X-Amz-SignedHeaders'] = 'host';` it works.

Any ideas? Bug?

For reference:
https://github.com/minio/minio/issues/1285

**Comment by jeskew** [comment]
Changing the signed header from 'Host' to 'host' appears to be what other AWS SDKs do. I opened a PR to address this.

**Comment by tehscorpion** [comment]
Thanks!
