### ISSUE TITLE
SDK v2.8.* S3 Memory Leak

### ISSUE THREAD

**Issue by pinguo-shenqiang** [aws/aws-sdk-php#956]
Hi GUY, I found a memory leak in the version of 2.8.*, but i have no idea about how to resolve it. please use top and you will see "memory" is still increasing.
could anybody help me? 

Env: php-5.3.28
the code is as below:
<?php
require 'vendor/autoload.php';
use Aws\Common\Credentials\Credentials;

$strBucket = 'album-analysis-cn';
$strKey = '000010ef56fe136bb6b6feba73f4/2/170';

$accessKeyId = '...';
$secretAccessKey = '...';
$credentials = new Credentials($accessKeyId, $secretAccessKey);
$client = Aws\S3\S3Client::factory(
     array(
        'credentials' => $credentials,
        'region' => 'cn-north-1'
     )
);

while ($i++ <= 10000) {
     $arrArgs = array(
         'Bucket' => $strBucket,
         'Key'    => $strKey
     );
     $arrHeader = $client->headObject($arrArgs);
}

**Comment by jeskew** [comment]
I'm unable to reproduce using V2. Memory usage holds steady while executing the script you provided. I'm using PHP 5.6.

Can you check to make sure garbage collection is enabled? If `gc_enabled()` returns `true` and you still see memory usage climbing, there might be differences between how garbage collection is handled in PHP versions. I see that you're using PHP 5.3, which has not been officially supported for some time.

**Comment by pinguo-shenqiang** [comment]
Sorry, I test it again in my PHP5.6 machine. It is still present :( 
My memory usage is still climbing. So comfuse .

There is some information about how to reproduce it. Perhaps it is useful for debug.

I use Composer to install the AWS SDK (follow as http://docs.aws.amazon.com/aws-sdk-php/v2/guide/installation.html)

PHP Version => 5.6.19

    <?php
    require 'vendor/autoload.php';
    use Aws\Common\Credentials\Credentials;

    $strBucket = 'album-analysis-cn';
    $strKey = '0000000456ea6e5781937361ea8b/2/0';

    $accessKeyId = '...';
    $secretAccessKey = '...';
    $credentials = new Credentials($accessKeyId, $secretAccessKey);
    $client = Aws\S3\S3Client::factory(
         array(
            'credentials' => $credentials,
            'region' => 'cn-north-1',
            'client.backoff' => false
         )
    );

    var_dump(gc_enabled());
    $i = 0;
    while ($i++ >= 0) {
         $arrArgs = array(
             'Bucket' => $strBucket,
             'Key'    => $strKey
         );
         $arrHeader = $client->getObject($arrArgs);
         echo $i . "\n";
         gc_collect_cycles(); 
    }

Could you help me to resolve it? Thx

BTW,  php upgrading is a huge project to me. I can not use the latest SDK because of php version.
