### ISSUE TITLE
SDK V2 LambdaClient:  Fix for #580 eventually not included since v2.8.21

### ISSUE THREAD

**Issue by leftdevel** [aws/aws-sdk-php#958]
There was a bug when running LambdaClient::updateFunctionCode, that the 'ZipFile' was not working properly. It got fixed on #580 and merged into v2.8.6. That fix was preserved until 2.8.21, newer releases does not include that fix (from 2.8.22 up to the last release, 2.8.28).

Question is, why it got removed? If it was on purpose then it's fine, I can work with an older sdk version. If it was unintentional then I can create a PR to bring it back. Thoughts?

**Comment by jeskew** [comment]
The fix from #580 has been merged into the 2.8 branch and will go out with the next release. Thanks for reporting this!
