### ISSUE TITLE
Error executing "HeadObject

### ISSUE THREAD

**Issue by zamaliphe** [aws/aws-sdk-php#962]
while the code is very simple just calling do

` 

 $s3 = new \Aws\S3\S3Client([
            'version' => 'latest',
            'region' => 'us-west-2',
            'debug' => true,
            'curl.options' => [CURLOPT_VERBOSE => true],
            'credentials' => [
                'key' => 'sample Key',
                'secret' => 'secret',
            ],
            'http' => [
                'verify' => false
            ],
            'scheme' => 'http'
    
        ]);

        $var = $s3->doesObjectExist('dev.nkforex.com', 'zam.jpg' );
`

Warning: Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "HeadObject" on "http://s3-us-west-2.amazonaws.com/dev.nkforex.com/files/articles/image/40500/%25D8%25A7%25D9%2584%25D8%25AA%25D8%25AD%25D9%2584%25D9%258A%25D9%2584-%25D8%25A7%25D9%2584%25D9%2581%25D9%2586%25D9%2589-%25D8%25B3%25D9%2587%25D9%2585-%25D8%25B3%25D9%2584%25D8%25A7%25D9%2585%25D8%25A9-%25D8%25B3%25D9%2588%25D9%2582-%25D8%25A7%25D9%2584%25D8%25A7%25D8%25B3%25D9%2587%25D9%2585-%25D8%25A7%25D9%2584%25D8%25B3%25D8%25B9%25D9%2588%25D8%25AF%25D9%2589.jpg.temp"; AWS HTTP error: Client error: `HEAD http://s3-us-west-2.amazonaws.com/dev.nkforex.com/files/articles/image/40500/%25D8%25A7%25D9%2584%25D8%25AA%25D8%25AD%25D9%2584%25D9%258A%25D9%2584-%25D8%25A7%25D9%2584%25D9%2581%25D9%2586%25D9%2589-%25D8%25B3%25D9%2587%25D9%2585-%25D8%25B3%25D9%2584%25D8%25A7%25D9%2585%25D8%25A9-%25D8%25B3%25D9%2588%25D9%2582-%25D8%25A7%25D9%2584%25D8%25A7%25D8%25B3%25D9%2587%25D9%2585-%25D8%25A7%25D9%2584%25D8%25B3%25D8%25B9%25D9%2588%25D8%25AF%25 in /home/www/nkforex/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 192

==================================================
  /home/www/nkforex/vendor/aws/aws-sdk-php/src/TraceMiddleware.php:255:
  array (size=13)
    'instance' => string '000000001xczxde40bd100000000414fd3be' (length=32)
    'class' => string 'Aws\S3\Exception\S3Exception' (length=28)
    'message' => string 'Error executing "HeadObject" on "http://s3-us-west-2.amazonaws.com/dev.nkforex.com/zam.jpg"; AWS HTTP error: Client error: `HEAD http://s3-us-west-2.amazonaws.com/dev.nkforex.com/zam.jpg` resulted in a `404 Not Found` response:

 NotFound (client): 404 Not Found (Request-ID: DD90asdasd56asdas36A76EBFDE) - ' (length=296)
    'file' => string '/home/www/nkforex/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php' (length=67)
    'line' => int 192
    'trace' => string '#0 /home/www/nkforex/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(97): Aws\WrappedHttpHandler->parseError

    'type' => string 'client' (length=6)
    'code' => string 'NotFound' (length=8)
    'requestId' => string '7AB6BAB8dfsd75E29Cdfgd09' (length=16)
    'statusCode' => int 404
    'result' => null
    'request' => 
      array (size=5)
        'instance' => string '000000006fdfsdfdsbec404000000005f454dsfsdfa3' (length=32)
        'method' => string 'HEAD' (length=4)
        'headers' => 
          array (size=8)
            'X-Amz-Security-Token' => string '[TOKEN]' (length=7)
            'Host' => 
              array (size=1)
                0 => string 's3-us-west-2.amazonaws.com' (length=26)
            'User-Agent' => 
              array (size=1)
                0 => string 'aws-sdk-php/3.17.5' (length=18)
            'aws-sdk-invocation-id' => 
              array (size=1)
                0 => string '25d5a92cd7dfsdfae849e5806dfsda03a76f1644d' (length=32)
            'aws-sdk-retry' => 
              array (size=1)
                0 => string '0/0' (length=3)
            'X-Amz-Content-Sha256' => 
              array (size=1)
                0 => string 'e3b0c44298fc1c14rweweerw9afbf4c8996fb92427aedfsd41e4649b934ca495991b7852b855' (length=64)
            'X-Amz-Date' => 
              array (size=1)
                0 => string '20160412T103616Z' (length=16)
            'Authorization' => 
              array (size=1)
                0 => string 'AWS4-HMAC-SHA256 Credential=[KEY]/20160412/us-west-2/s3/aws4_request, SignedHeaders=aws-sdk-invocation-id;aws-sdk-retry;host;x-amz-content-sha256;x-amz-date, Signature=[SIGNATURE]
        'scheme' => string 'http' (length=4)
        'path' => string '/dev.nkforex.com/zam.jpg' (length=24)
    'response' => 
      array (size=4)
        'instance' => string '000000006fbecsdfsd41f000000005f4sdfs54fa3' (length=32)
        'statusCode' => int 404
        'headers' => 
          array (size=7)
            'X-Amz-Security-Token' => string '[TOKEN]' (length=7)
            'x-amz-request-id' => 
              array (size=1)
                0 => string '7AB6BcxvxAB875E29C09' (length=16)
            'x-amz-id-2' => 
              array (size=1)
                0 => string 'jY0lBzbXwpdfgdfIgRCr/JDx6oX3WAn4DCgdfgdffdf6MeLdCAVEtsXahZL3axgqMynAyIHKmV3hLMMNWYlJOgrUE=' (length=76)
            'Content-Type' => 
              array (size=1)
                0 => string 'application/xml' (length=15)
            'Transfer-Encoding' => 
              array (size=1)
                0 => string 'chunked' (length=7)
            'Date' => 
              array (size=1)
                0 => string 'Tue, 12 Apr 2016 10:36:16 GMT' (length=29)
            'Server' => 
              array (size=1)
                0 => string 'AmazonS3' (length=8)
        'body' => string '' (length=0)
  

  Inclusive step time: 0.9077479839325

<- Leaving step sign, name 's3.put_object_url'
----------------------------------------------

  no changes
  Inclusive step time: 0.90821695327759

<- Leaving step sign, name 'signer'
-----------------------------------

  no changes
  Inclusive step time: 0.90898895263672

<- Leaving step sign, name 'retry'
----------------------------------

  no changes
  Inclusive step time: 0.91115093231201

<- Leaving step sign, name 'invocation-id'
------------------------------------------

  no changes
  Inclusive step time: 0.9119279384613

<- Leaving step build, name 's3.content_type'
---------------------------------------------

  no changes
  Inclusive step time: 0.91234707832336

<- Leaving step build, name 's3.checksum'
-----------------------------------------

  no changes
  Inclusive step time: 0.91273617744446

<- Leaving step build, name ''
------------------------------

  no changes
  Inclusive step time: 0.91333103179932

<- Leaving step build, name 'builder'
-------------------------------------

  no changes
  Inclusive step time: 0.91417908668518

<- Leaving step validate, name 'validation'
-------------------------------------------

  no changes
  Inclusive step time: 0.91540503501892

<- Leaving step init, name 's3.head_object'
-------------------------------------------

  no changes
  Inclusive step time: 0.91678094863892

<- Leaving step init, name 's3.auto_encode'
-------------------------------------------

  no changes
  Inclusive step time: 0.91714406013489

<- Leaving step init, name 's3.location'
----------------------------------------

  no changes
  Inclusive step time: 0.91753005981445

<- Leaving step init, name 's3.save_as'
---------------------------------------

  no changes
  Inclusive step time: 0.9178729057312

<- Leaving step init, name 's3.source_file'
-------------------------------------------

  no changes
  Inclusive step time: 0.91823601722717

<- Leaving step init, name 's3.ssec'
------------------------------------

  no changes
  Inclusive step time: 0.91914200782776

/plugins/Upload/src/File/Writer/DiskAwsS3Writer.php (line 217)
false

**Comment by zamaliphe** [comment]
it return false but also throw an exception

**Comment by cjyclaire** [comment]
Could you double check the bucket name? In general, for head object, `404 Not found` is returned when no such bucket existed. @zamaliphe

**Comment by jeskew** [comment]
@zamaliphe I'm unable to reproduce. `doesObjectExist` internally catches all S3Exceptions and only propagates 500-level errors.

From the code snippet you posted, it doesn't look like the exception is related to the `doesObjectExist` method call. `$s3->doesObjectExist('dev.nkforex.com', 'zam.jpg' )` would call `HeadObject` on 'zam.jpg', while the exception is encountered when calling `HeadObject` on an object named 'files/articles/image/40500/%25D8%25A7%25D9%2584%25D8%25AA%25D8%25AD%25D9%2584%25D9%258A%25D9%2584-%25D8%25A7%25D9%2584%25D9%2581%25D9%2586%25D9%2589-%25D8%25B3%25D9%2587%25D9%2585-%25D8%25B3%25D9%2584%25D8%25A7%25D9%2585%25D8%25A9-%25D8%25B3%25D9%2588%25D9%2582-%25D8%25A7%25D9%2584%25D8%25A7%25D8%25B3%25D9%2587%25D9%2585-%25D8%25A7%25D9%2584%25D8%25B3%25D8%25B9%25D9%2588%25D8%25AF%25D9%2589.jpg.temp'.

**Comment by zamaliphe** [comment]
yes i hard coded the file name while i was testing 
but i still get the same thing 
i did try to debug the call however the ver 3 OF AWS-SDK is using ASync call and I'm unable to get the server response XML

**Comment by zamaliphe** [comment]
both doesObjectExist() and doesBuckettExist() throw an unhandled exception  

Type  Aws\S3\Exception\S3Exception

Now lets test why ?

my main guess  start with the last line 

 'trace' => string '#0 /home/www/nkforex/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(97): Aws\WrappedHttpHandler->parseError 

the WrappedHttpHandler is checking only for a certain return 
but get something else 
i have no experience with new PSR7 type of request 
but i can try  
you should check only for a valid request then return true 
otherwise you should return false specially on this 2 calls because other plugins 3rd party libs is using them all the time

**Comment by jeskew** [comment]
@zamaliphe Both `doesObjectExist` and `doesBucketExist` catch all `S3Exceptions` [here](https://github.com/aws/aws-sdk-php/blob/master/src/S3/S3ClientTrait.php#L198). If an exception is thrown, they return `false`; otherwise, they return `true`.

**Comment by zamaliphe** [comment]
@jeskew  thanks for your quick reply 
it looks like it should work 
but for some reason the exception are not handled 

i will try again tomorrow  maybe i found something 
but if you can just help me get the server response i would be much appreciated

**Comment by zamaliphe** [comment]
done the following test and all give the same result 
*create new php project ( empty folder )
install aws ver 3 using composer  
 require '../vendor/autoload.php';
 run my code 
same thing

**Comment by jeskew** [comment]
@zamaliphe I'm confused; a method can either return a value or throw an exception, but it cannot do both. If you are able to catch an `S3Exception`, it will have a `getResponse` method that returns the service's response.

**Comment by jeskew** [comment]
Closing, as I'm unable to reproduce. If you can catch an `S3Exception`, then it will have a `getResponse` method that returns a the server's response (as a PSR-7 `ResponseInterface`) or `null` if no response was received.

**Comment by nighthtr** [comment]
@zamaliphe @jeskew was xdebug included? seems a problem in this
