### ISSUE TITLE
Clear PHP cache via "clearstatcache()" for stream wrapper while using "filesize()"

### ISSUE THREAD

**Issue by servocoder** [aws/aws-sdk-php#963]
I use stream wrapper and faced the problem that **filesize()** seems to cache result and I'm unable to clear it. In my case I upload files by chunks. This is exmaple:
```
$path = 's3://bucket/key';
$s3 = Aws\S3\S3Client::factory(/*...*/);
$s3->registerStreamWrapper();
$filesize = filesize($path); // 4000000 bytes

file_put_contents(
    $path,
    fopen($uploaded_file, 'r'), // append new chunk 4000000 bytes length
    FILE_APPEND
);

$filesize = filesize($path); // 4000000 bytes, again!!!
```
As you can see the second call of **filesize()** gives 4000000, but a new chunk have been appended to the file, and it became 8000000 bytes. I am confident that chunk was successfully appended and S3 Console shows correct result, but how could I get correct new filesize right after the file was modified is thus way?

I have tried http://php.net/manual/en/function.clearstatcache.php before invoking **filesize()** the second time, like:
```
if (version_compare(PHP_VERSION, '5.3.0') >= 0) {
    clearstatcache(true, $path);
} else {
    clearstatcache();
}
```
but it had no effect.

**Comment by jeskew** [comment]
Thanks for reporting this. The StreamWrapper class has an internal cache that is not being invalidated when writing to an S3 path; I opened a pull request to correct the behavior.

**Comment by maechler** [comment]
@jeskew This fix seems to only be working for the default protocol scheme. But I would assume it fails for custom protocol names, that can be registered like this (**untested**): 
```php
Aws\S3\StreamWrapper::register($clientA, 's3.a');
```

https://github.com/aws/aws-sdk-php/blob/c72d50d48af52d1331bbc5b43581f96b50fd9ed9/src/S3/StreamWrapper.php#L177

Shouldn't this be changed to respect the registered protocol name?
