### ISSUE TITLE
Using ApcuCache before ApcCache in Aws/Common/Credentials/Credentials.php

### ISSUE THREAD

**Issue by tflin** [aws/aws-sdk-php#968]
As ApcCache api is not enabled in PHP 7 by default, it's better to use ApcuCache now. If the backward compatibility with PHP 5.3 is still a point, then the code in Credentials.php (with Doctrine\Common\Cache\ApcCache) could use ApcuCache first and then use ApcCache if apcu is not available in PHP 5.3.

P.S. The AWS SDK mentioned is 2.8.x.

**Comment by jeskew** [comment]
The 2.8.x needs to continue working with PHP 5.3. The default cache requires that a few optional dependencies be installed, including the APC extension and `doctrine/cache`, and it's only loaded if a cache is not explicitly provided. On a system with PHP 7, you can provide an instance of `ApcuCache` to the client factory.

**Comment by tflin** [comment]
The doctrine/cache has included ApcuCache class(Doctrine\Common\Cache\ApcuCache) with the same interface of its ApcCache. So it does not need us to provide an instance of ApcuCache. It should be very easy to modify the original code using doctrine ApcCache to use doctrine ApcuCache.

**Comment by jeskew** [comment]
Is `ApcuCache` compatible with PHP 5.3? If not, then customers wanting to use the 2.8 branch with PHP 7 will need to supply a concrete cache instead of relying on the default.

**Comment by jeskew** [comment]
On the [APCu documentation page](https://secure.php.net/manual/en/apcu.installation.php), the extension authors mention that they provide a separate module to make the `apc_*` functions compatible with PHP 7. I think it's reasonable to say that if you would like to continue using V2 of the SDK while upgrading your environment to PHP 7, you can either supply a concrete cache or install APCu's backwards compatibility module.

Thanks for reporting! Please feel free to reopen if you have any questions or concerns.
