### ISSUE TITLE
Wrong result of file_exists() of stream wrapper

### ISSUE THREAD

**Issue by servocoder** [aws/aws-sdk-php#969]
I have a file which is exists but closed for "Open/Download" via S3 console, nevertheless I get `false` when check it via **file_exists()** function. I believe this is wrong because I can see this file while listing with **readdir()** function, and most importantly the file is really exists in S3 storage.

**Comment by jeskew** [comment]
`file_exists` just calls the `HeadObject` on an operation and returns `false` if an exception is thrown or `true` otherwise. Could you trying calling `HeadObject` directly and inspecting the error thrown by the service?

**Comment by servocoder** [comment]
Yes, I can see the exception:

Error executing "HeadObject" on "https://s3.eu-central-1.amazonaws.com/my-bucket/image.jpeg"; AWS HTTP error: Client error: `HEAD https://s3.eu-central-1.amazonaws.com/my-bucket/image.jpeg` resulted in a `403 Forbidden` response:
 (client): 403 Forbidden (Request-ID: 2X4CE03AD2B98F56) - 

So, the file exists and could be listed via **readdir()**, but there is exception on "HeadObject". Perhaps the exception should be parsed to define if file is forbidden or not exists. As you can see the exception is different when there is no file:

Error executing "HeadObject" on "https://s3.eu-central-1.amazonaws.com/my-bucket/no-image.jpeg"; AWS HTTP error: Client error: `HEAD https://s3.eu-central-1.amazonaws.com/my-bucket/no-image.jpeg` resulted in a `404 Not Found` response:
 NotFound (client): 404 Not Found (Request-ID: 6B113BC5E2B12153) - 

Another way I see is to check file existence via some other S3 client method. For example `listObjects`, because it lists file in case it is forbidden.

**Comment by jeskew** [comment]
`file_exists` should return `true` [if the error code returned is `AccessDenied`](https://github.com/aws/aws-sdk-php/blob/master/src/S3/S3ClientTrait.php#L211). It looks like [there are a number of error codes that could be provided with a 403 response](http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html); I'll need to look into which definitively indicate a file exists.

Checking via `listObjects` would work, but it would be an inefficient solution for buckets with a large number of objects. The SDK would need to walk the response looking for the correct key; if the bucket was large enough to have a multiple pages of objects, `file_exists` might require sending multiple requests sequentially.

**Comment by servocoder** [comment]
Ok, I have found that there no need to parse exception message. Just check `$e->getResponse()->getStatusCode();` - contains 404 if file not exists or 403 if forbidden. Just check the code to define.

**Comment by servocoder** [comment]
Yea, I see what you are talking about. There is really mess with codes. Hope there is a solution, because now `file_exists()` isn't reliable to check file existence.

**Comment by jeskew** [comment]
There are several 403 responses that would not necessarily indicate that an object exists, such as `SignatureDoesNotMatch`, `InvalidAccessKeyId`, `RequestTimeTooSkewed`, `NotSignedUp`, etc.

You could conclude that an object exists from `AccessDenied`, `InvalidObjectState`, or `InvalidPayer`. Was the error code you were encountering one of those?

**Comment by servocoder** [comment]
I agree with states you listed, but I have got `Forbidden` in `$e->getResponse()->getReasonPhrase();`. In my debug console I can see a list with "reasonPhrase" and it is different from [this list](http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html). I have found the same list of phrases in `GuzzleHttp\Psr7\Response` file. The phrase remains `Forbidden` even when I use wrong access key. Do you know the way I could get error message from the list above?

**Comment by servocoder** [comment]
It seems I have figured out.
To get correct error message from the list you have to call `getObject` insted of `HeadObject` and check for `$e->getAwsErrorCode()`. For example, if I use incorrect access key `HeadObject` returns `null` error code while `getObject` returns `InvalidAccessKeyId`.

There are my cases:
no file - "NoSuchKey"
forbidden via S3 console - "AccessDenied"

**Comment by servocoder** [comment]
I want explain you my case and what I expect to achieve. I have 2 checks for file:
step1 - check if file exists (`file_exists`)
step2 - check file permissions (`is_readable`/`is_writable`)

If file is exists and forbidden via S3 console I expect the validation passes step1, but fails on step2. It seems logical for me and this is consistent with PHP behavior. We have decided to consider file as existing if error code is one of `AccessDenied`, `InvalidObjectState`, or `InvalidPayer`. The second step should check if file exists AND error code is not `AccessDenied`. Do you agree with such process?

**Comment by jeskew** [comment]
`getReasonPhrase` will always return the stock phrase associated with an HTTP status code. The Guzzle PSR-7 library has [a full list of possible reason phrases](https://github.com/guzzle/psr7/blob/master/src/Response.php#L13); they are not related to the error codes returned by S3. 

I ran a few tests and found that the stream wrapper's `url_stat` implementation (used by `file_exists`, `is_file`, `is_readable`, etc) will always return `false` when you do not have permission to read the object. This would be consistent with how `file_exists` works on Windows, SELinux, and other systems where you can restrict file visibility.

For your particular use case, do you need to call `file_exists` at all? Both `is_readable` and `is_writable` check if a file exists as part of their normal workflow.

**Comment by servocoder** [comment]
The stream wrapper is really returns `false` for all cases (either file not existed or permission restricted, etc.), but I don't agree with you in the statement that Windows and Linux have the same workflow. I have checked on Windows and Linux and I can confidently say that `file_exists` returns `true` on both OS regardless of file permissions.

For my case, I could obvious rewrite my code to the specific behavior of `file_exists` of the stream wrapper, but it is very inconvenient to take in consideration such inconsistencies. As I noticed you try to keep PHP stream wrapper most compatible with Windows/Linux workflow, but the current behavior doesn't fit to this.

**Comment by jeskew** [comment]
There are local filesystem permissions that restrict your ability to see which files exist. For example, `file_exists` will return `false` if a file exists in a directory on which your user doesn't have execution/traversal privileges. Try the following from a directory you own:
```
mkdir subdir
touch subdir/file.ext
php -r 'if (file_exists("subdir/file.ext")) { echo "file exists!\n"; } else { echo "file does not exist!\n"; }'
chmod 0644 subdir
php -r 'if (file_exists("subdir/file.ext")) { echo "file exists!\n"; } else { echo "file does not exist!\n"; }'
```

Right now, `file_exists` in the stream wrapper will always return the same result as `is_readable`. This is because PHP stream wrappers map both of those functions to `url_stat`, which requires read access to the S3 object. Permissions in S3 do not map cleanly to permissions on a local filesystem, so this may not be something that can or should change.

**Comment by servocoder** [comment]
I see, it's a bad news. In this case you can close this issue. Thank you for the explanations.

**Comment by servocoder** [comment]
One more note regard this problem.
I have faced that `file_exists` returns different result based on the way it was mapped. If you check key for `file_exists` after it was mapped with `readdir` or an iterator, it returns `true`. But if you check the key for `file_exists` that wasn't previously mapped with listing it returns `false`. As I described before, that happens because listing returns correct metadata regardless of file permissions.

**Comment by jeskew** [comment]
I don't think performing a `ListObjects` operation to rescue a `HeadObject` that failed with a 403 code would be a good solution in all cases. Assume you have a bucket with keys that are sequential integers from 1 to 1,000,000. If you want to call a stat function on the object named '17' that you didn't have permission to read, you would need to call `ListObjects` with a prefix of '1' and then iterate (and paginate!) through the result until you found the object with the desired key. If '17' is the last item in that list, you will have gone through thousands of object records before getting the data you need.

`readdir` populates the stat cache to make recursive directory iteration more efficient. That means that a subsequent call to `url_stat` will be able to return what was cached rather than having to send a `HeadObject` request. Maybe `readdir` shouldn't populate the cache? It would make iteration less efficient but would simplify the behavior of `url_stat`.

**Comment by mtdowling** [comment]
I'd prefer we not remove the caching from readdir. Removing it makes iterating over the contents of a bucket extremely slow.

**Comment by jeskew** [comment]
There's a noticeable performance impact. I think the right solution here is to document that the stream wrapper works most intuitively on buckets and objects to which you have read permissions, given how different S3 permissions are from local FS octal permissions.

**Comment by servocoder** [comment]
I understand and agree with you. Caching from readdir is a good solution, I like it too. You could also want to document `file_exists` behavior, which returns various result based on the way it was cached, as I described in my last message.

It would be great if the wrapper would provide an opportunity to drop cache of specified file. This would allow to fix `file_exists` behavior after it was cached via `readdir`. Such solution also can be used more widely to check the actual state of object after it is changed, deleted, etc.

**Comment by jeskew** [comment]
Unfortunately, the stream wrappers don't offer any way to hook into `clearstatcache`, so that would need to be an instance method or a context option passed in to `file_exists`.
