### ISSUE TITLE
s3/PutBucketReplication Missing Required ContentMD5 Header

### ISSUE THREAD

**Issue by cgltower** [aws/aws-sdk-php#972]
Im using version 3.17.5

Am I doing something wrong with putbucketreplication on a new bucket?:
`
$arn_s3_role = 'arn:aws:iam::[removed]:role/S3Access';
$arn_s3_prefix = 'arn:aws:s3:::';

$resultreplication = $s3client->putBucketReplication([
'Bucket' => $bucket_name,
'ContentMD5' => '',
'ReplicationConfiguration' => [ 
   'Role' => $arn_s3_role, 
   'ContentMD5' => '', // How to do this in PHP for putBucketReplication?
   'Rules' => [
	[
	'Destination' => [
            'Bucket' => $arn_s3_prefix . $destination_bucket_name,
            'StorageClass' => 'STANDARD',
	],
    'Prefix' => 'Repl-'. $project_name . '-',
    'Status' => 'Enabled',
    ],
  ],
 ],
]);
`

resulted in 

Fatal error: Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "PutBucketReplication" on "https://s3.amazonaws.com/mybucket123?replication"; AWS HTTP error: Client error: `PUT https://s3.amazonaws.com/mybucket123?replication` resulted in a `400 Bad Request` response: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>InvalidRequest</Code><Message>Missing required header for this reque (truncated...) InvalidRequest (client): Missing required header for this request: Content-MD5 - <?xml version="1.0" encoding="UTF-8"?> <Error><Code>InvalidRequest</Code><Message>Missing required header for this request: Content-MD5</Message><RequestId>BD7BB00E555AAEAD</RequestId><HostId>[removed]</HostId></Error>' exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `PUT https://s3.amazonaws.com/mybucket123?replication` resulted in a `400 Bad Request` res in /var/www/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 192

The [API doc](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-s3-2006-03-01.html#putbucketreplication) does not specify I require content-md5.  I also started with 'ContentMD5' parameter not being there, with the same results.

Similar bug?:
https://github.com/aws/aws-sdk-go/issues/612

**Comment by cjyclaire** [comment]
Close this issue with PR #976 that resolves it. Thank for catching the bug.
