### ISSUE TITLE
Middlewares not used when using DynamoDb BatchWriteItem

### ISSUE THREAD

**Issue by bakura10** [aws/aws-sdk-php#978]
Hi,

I'm using a middleware that is used to automatically prefix DynamoDB table names. I'm registering it this way:

```php
$dynamoDbClient->getHandlerList()->prependInit(Middleware::mapCommand($tableNamePrefixer), 'prefix-table');
```

The code of this prefixer is pretty simple:

```php
final class TableNamePrefixer
{
    private $appId;

    public function __construct(string $appId)
    {
        $this->appId = $appId;
    }

    public function __invoke(CommandInterface $command): CommandInterface
    {
        $tableName = $command['TableName'];
        $parts     = explode('.', $tableName);

        // For tables that are already qualified, it returns the untouched command
        if (count($parts) > 1) {
            return $command;
        }

        $command['TableName'] = 'app.' . substr($this->appId, 0, 6) . '.' . $tableName;

        return $command;
    }
}
```

This works perfectly when doing inidivudal requests. However, when using the WriteRequestBatch, it seems that those middlewares are never called. Instead, the unprefixed table name is used.

Is there a way to make sure that those are also called when resolving the table name when using batched requests?

**Comment by bakura10** [comment]
I've actually been able to solve this issue by using the "before" option of the WriteRequestBatch. The callable is executed and I can prefix my tables :).

I'm therefore closing.

**Comment by jeskew** [comment]
Glad using the `before` option worked out for you. You might also want to look into modifying the TableNamePrefixer class to handle more of the DynamoDB API. Right now, the class will not effectively map batch actions (like `BatchGetItem` or `BatchWriteItem`), as the shape of the input provided to those commands is a bit different from `PutItem` or `GetItem`. (See the parameter syntax of [`BatchWriteItem`](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-dynamodb-2012-08-10.html#batchwriteitem) for an example. This is the command used by `WriteRequestBatch`.)

**Comment by bakura10** [comment]
For reference if someone has the same issue, here is a prefixer that works for everything:

```php
    public function __invoke(CommandInterface $command): CommandInterface
    {
        $commandName = $command->getName();
        
        // For batch requests, we need to modify the name of all tables within the batch
        if ($commandName === 'BatchWriteItem' || $commandName === 'BatchGetItem') {
            $requestItems = [];

            foreach ($command['RequestItems'] as $tableName => $requests) {
                $newTableName                = $this->resolveTableName($tableName);
                $requestItems[$newTableName] = $requests;
            }

            $command['RequestItems'] = $requestItems;
        } else {
            $command['TableName'] = $this->resolveTableName($command['TableName']);
        }

        return $command;
    }

    private function resolveTableName(string $tableName): string
    {
        $parts = explode('.', $tableName);

        // For tables that are already qualified, it returns the untouched name
        if (count($parts) > 1) {
            return $tableName;
        }

        return 'app.' . substr($this->appId, 0, 6) . '.' . $tableName;
    }
```
