### ISSUE TITLE
sendRawEmail Error

### ISSUE THREAD

**Issue by sattalk** [aws/aws-sdk-php#981]
Hi, 
I am running out of ideas and need your support. 

Issue: 
Unable to send email with attachment using sendRawEmail. There is no issue with my configuration or setup. All normal emails using sendEmail are going through fine. 

Error Message:
Getting the following error message/exception

Next exception 'Aws\Ses\Exception\SesException' with message 'Error executing "SendRawEmail" on "https://email.us-west-2.amazonaws.com"; AWS HTTP error: Client error: `POST https://email.us-west-2.amazonaws.com` resulted in a `400 Bad Request` response:

`<ErrorResponsexmlns="http://ses.amazonaws.com/doc/2010-12-01/">`
`<Error>`
`<Type>Sender</Type>`
`<Code>InvalidPara (truncated...)`
`InvalidParameterValue (client): Header section too long. - <ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">`
`<Error>`
`<Type>Sender</Type>`
   `<Code>InvalidParameterValue</Code>`
   `<Message>Header section too long.</Message>`
`</Error>`
`<RequestId>0f678793-118e-11e6-85bd-77394342cf29</RequestId>`
`</ErrorResponse>`

Attached is a dump of the raw email multi-part string (truncated the attachment data for ease). And yes, I am base64 encoding it before sending. 

Any thoughts/suggestions welcome!

Thanks

[mail.txt](https://github.com/aws/aws-sdk-php/files/247997/mail.txt)

**Comment by cjyclaire** [comment]
As error suggests, I'd recommend double check the header fields in your php code. Also at the end of `mail.txt`, there seems to be an extra "--", of course you can ignore this if it's just a typo in providing information. Meanwhile I'm working on reproducing the issue to see whether some of your headers went wrong.

**Comment by sattalk** [comment]
@cjyclaire Thanks for your response. Yes, the extra "--" is just a typo. I am running out of ideas. Tried through all the options. I am attaching the code snippet - function that generates the raw email string in my code. 


[sample.txt](https://github.com/aws/aws-sdk-php/files/249648/sample.txt)

**Comment by cjyclaire** [comment]
@sattalk , in the return array of your `getEmailRawData()` function, could you try not to `base64_encode` the message? Since the file_content is base64 encode already? It could be a double encoded issue.

According to PHP SDK, [sendRawEmail()](http://docs.aws.amazon.com/aws-sdk-php/v3/api/api-email-2010-12-01.html#sendrawemail), `'Data'` field.

If this doesn't work, I'd suggest double check the `email_data`.

**Comment by sattalk** [comment]
@cjyclaire Thanks mate! that was the issue. 

Its strange; I thought the entire message had to be base64 encoded. From the same documentation: 
> Content must be base64-encoded, if MIME requires it.

I was doing it this way with v2 of the API. When I switched to v3 recently, it stopped working. The documentation is a bit confusing. 

Appreciate your help!! Thanks again!

**Comment by developerphp702** [comment]
SesException in WrappedHttpHandler.php line 152:
Error executing "SendRawEmail" on "https://email.us-east-1.amazonaws.com"; AWS HTTP error: Client error: 400 InvalidParameterValue (client): Illegal address - <ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">
<Error>
<Type>Sender</Type>
<Code>InvalidParameterValue</Code>
<Message>Illegal address</Message>
</Error>
<RequestId>24e8a149-bf62-4c9b-8688-2156c59c0781</RequestId>
</ErrorResponse>

Can anyone help on this
