### ISSUE TITLE
Retrieve contentType from object's metadata with StreamWrapper

### ISSUE THREAD

**Issue by servocoder** [aws/aws-sdk-php#982]
I found that contentType which is provided with object's metadata isn't stored with `url_stat()` / `createStat()`. I suggest to cache contentType of an object and use some php function to retrieve it back from cache. Because currently you have to make a separate HEAD request to get content type.

**Comment by jeskew** [comment]
File type isn't something that's normally returned by [`stat`](http://php.net/manual/en/function.stat.php). I'm not sure if unknown/unsupported values would get stored in PHP's stat cache.

**Comment by servocoder** [comment]
I see, the main idea was to cache ContentType of an object, to read it later without extra HEAD request to S3. Perhaps there is another way to do this.

**Comment by jeskew** [comment]
Is there a PHP function that takes a path and will parse out the underlying resource's content type? [`filetype`](http://php.net/manual/en/function.filetype.php) will only tell you if a path represents a file/directory/symlink/etc.

**Comment by servocoder** [comment]
I guess the [mime_content_type()](http://php.net/manual/en/function.mime-content-type.php) does it. But it was deprecated in PHP >= 5.5, if that fact will affects to the wrapper, then some other function should be used, otherwise I suggest to utilize `mime_content_type()`.

**Comment by servocoder** [comment]
Another option is to use [finfo_open()](http://php.net/manual/en/function.finfo-open.php) in this way:
```
$finfo = finfo_open(FILEINFO_MIME_TYPE);
echo finfo_file($finfo, "path/to/filename.ext");
finfo_close($finfo);
```
But it looks too complicated.

**Comment by jeskew** [comment]
I was unable to get either `mime_content_type` or `finfo_open` to work with any remote stream (as described [here](https://forums.aws.amazon.com/message.jspa?messageID=505342)). `mime_content_type` appears to try to read the stream, so it might not be as efficient as just calling `HeadObject`. You can manually save the result in a cache to get around any limitations of the PHP stat cache.

**Comment by servocoder** [comment]
I see, thank you for putting effort into this
