### ISSUE TITLE
Proposal: have a max retry time in RetryMiddleware

### ISSUE THREAD

**Issue by oberman** [aws/aws-sdk-php#985]
I've been working with AWS support and hit a wall on my options to work around an admittedly transient issue.  The quick of it: I experienced DyanmoDB failures due to having a single bad server in my DNS pool of N servers for a period of a few hours.  The problem during that period of time was any given application server of mine would receive a single ip addresses for the pool with a TTL measured in 10's of seconds (but no more than 60).  During that TTL window if the application server received the bad address the connections would stall.  If the SDK retried long enough to get a new DNS lookup to a good IP the overall request would succeed, otherwise it would fail.  Within the TTL window I had zero ability to have a successful request, making "wait it out" the only option.

My current thought is to lower the connection timeout but increase the number of retries.  The goal being to minimize the wait time but maximize the chance of overall success.  The problem is that the PHP implementation has no upper bound on a 2^N algorithm.  Ideally, PHP would implement the Java algorithms:
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/retry/PredefinedRetryPolicies.java

But, barring that and keeping it simple I was thinking of changing RetryMiddleware::exponentialDelay to:
return min(20000, mt_rand(0, (int) pow(2, $retries - 1) * 100));
with 20 seconds being the Java default for max delay

**Comment by cjyclaire** [comment]
Thanks for point this out with a real case, yet I think for current version for our sdk, we do have a upper bound already with 20sec same with java. Also there is a PR #937 related, and the way we do it is exactly return `mt_rand(0, min(20000, (int) pow(2, $retries - 1) * 100))`.

**Comment by oberman** [comment]
Clearly I need to upgrade to a newer version of the SDK!  This is a duplicate of #937.
