### ISSUE TITLE
V3 SDK error not seen with v2: "cURL error 61: Error while processing content unencoding: invalid code lengths set"

### ISSUE THREAD

**Issue by genomachino17** [aws/aws-sdk-php#986]
Hello,

I am running into a curious error with the v3 SDK when trying to download certain objects from S3. Interestingly, the problem does not occur with the v2 SDK.

So -- as mentioned, I'm using the v3 PHP SDK (using the .phar file) to download files from S3. Most files download without issue, but I receive a cURL 61 error when trying to download certain .bin files encoded as follows:
Content-Type: 'text/plain'
Content-Encoding: 'gzip'

The files have the wrong headers, yes -- that's a separate issue that I need to fix. However -- the cURL error I receive with the v3 SDK is:

    AWS HTTP error: cURL error 61: Error while processing content unencoding: invalid code lengths set (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)  (server): 200 OK

--

To be clear -- this error does not occur when using the AWS CLI, OR with the v2 PHP SDK. It DOES occur with these methods in the v3 SDK:

Aws\S3\S3Client::getObject()
Aws\S3\Transfer::transfer()
    
----

Interestingly, I can "work around" the issue by specifying the "ResponseContentEncoding" parameter in the getObject() function. The following call is successful in v3:

    $result = $s3->getObject([
        'Bucket' => 'my-bucket',
        'Key' => 'my-key.bin',
        "ResponseContentEncoding" => 'binary/octet stream',
    ]);
   

So, my question: is there a reason the v3 SDK runs into problems in downloading these files with incorrect headers, but the v2 SDK does not? I'd very much like to use v3 and the S3\Transfer::transfer() method for ease of use, but I do not wish to strip all of the encodings off my S3 files.

Please let me know if I can provide more information, including debug logs of the call.

Thanks!

**Comment by cjyclaire** [comment]
For Guzzle, the `decode_content` [option](http://docs.guzzlephp.org/en/latest/request-options.html#decode-content) is set to `true` by default. So, the `content-encoding` header will be removed from the response, thus the `content-length` header will has a length of 0 for gunzipped response body, which gives cURL error 61.

For the workaround for this, you could manually set `decode_content` to `false` in `http` options of client config:
```php
$s3 = new Aws\S3\S3Client([
    'http' => [
        'decode_content' => false,
    ],
]);
```
Or add `'@http' => ['decode_content' => false],` in the `getObject` command.

**Comment by mtdowling** [comment]
Should we set this option to be disabled by default? Decoding by default was an oversight on my part and was not intentional in the SDK. This would be a sort of breaking change, but I wonder if anyone is relying on it to decode the response body.

**Comment by jeskew** [comment]
When this behavior came up before in #915, the fix (#916) was scoped to just `HeadObject` commands because I didn't know if anyone was relying on content decoding. Given the case described above and the way this behavior would complicate the behavior of `Aws\S3\Transfer` -- downloading a bucket of compressed tar balls would write `gunzip`'d files to disk -- I think you could make a case that this is a necessary bug fix, even if it could be a breaking change for some users.

Outside of the context of S3, however, compression is a transport-level concern. I think we should make `decode_content` a documented `http` option on clients and set it to `false` in an S3-specific middleware.

**Comment by jeskew** [comment]
@genomachino17 Due to backwards compatibility concerns, the workaround @cjyclaire provided above may need to be the official solution in v3.

**Comment by genomachino17** [comment]
Thanks everyone. That workaround was sufficient.
