### ISSUE TITLE
Support AWS4-HMAC-SHA256

### ISSUE THREAD

**Issue by stephanlindauer** [aws/aws-sdk-php#989]
When trying to to PutObject on eu-central-1 I get: 
```The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256```

I would expect the AWS SDK to handle those kinds of authentication details.

**Comment by cjyclaire** [comment]
Could you tell the SDK version that you are using and parameters that passed in? Since I'm unable to reproduce this issue. Also, for current version, I believe we support SignatureV4 of `putObject` by default.

**Comment by stephanlindauer** [comment]
so i finally figured out that i have to supply region information. if i tell the sdk that i want to access eu-central-1 everything works. thanks for your reply.

**Comment by cjyclaire** [comment]
Nice!
