### ISSUE TITLE
--query support in php also

### ISSUE THREAD

**Issue by pavankumarkatakam** [aws/aws-sdk-php#992]
I Have seen that there is option in aws cli to mentioned jsempath using the query option like shown below

`aws s3api list-objects --bucket BUCKETNAME --output json --query "[sum(Contents[].Size), length(Contents[])]"`

So , im thinking that if this option is also present in php it would be nice.

**Comment by cjyclaire** [comment]
@pavankumarkatakam Good to hear about the suggestion, as PHP SDK V3 is supported with jsempath already. Here is related [docs](https://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/jmespath.html).
