### ISSUE TITLE
Files stay blocked after multipart upload

### ISSUE THREAD

**Issue by saval** [aws/aws-sdk-php#993]
I'm trying to delete file after upload it to the S3, but stuck with error "PHP error, Severity: Warning  --> unlink(/var/www/test_file.zip): Text file busy script.php:19". Below my code to reproduce:

        $s3 = new Aws\S3\S3Client([
            'version'     => '2006-03-01',
            'region'      => 'us-east-1',
            'credentials' => [
                'key'    => 'SOME_KEY_HERE',
                'secret' => 'EVERYONE_WANTS_TO_KNOW_SECRET'
            ]
        ]);

        $file = '/var/www/test_file.zip';
        $uploader = new MultipartUploader($s3, $file, [
            'bucket' => 'YOUR_BUCKET_NAME',
            'key'    => 'test_file.zip',
        ]);

        $attempts = 1;
        do {
            try {
                $result = $uploader->upload();

            } catch (MultipartUploadException $e) {
                if($attempts >= 5) {
                    // State contains the "Bucket", "Key", and "UploadId"
                    $params = $e->getState()->getId();
                    $result = $s3->abortMultipartUpload($params);
                    error_log('Multipart upload canceled for file '.$file);

                } else {
                    $attempts++;
                    error_log('multipartUploadS3Object. Going to attempt #'.$attempts);
                    $uploader = new MultipartUploader($s3, $file, [
                        'state' => $e->getState(),
                    ]);
                }
            }
        } while (!isset($result));

        unlink($file); //here error has a place

It seems that file unlocked only on the script shutdown - next script execution can remove file from the first execution. Please suggest workaround to unlock file, thanks.

**Comment by cjyclaire** [comment]
I couldn't reproduce the issue with the code provided, yet your thoughts about the "Text file busy" error make sense to me. Could you provide more information about this scenario? Why you would need to unlock the file before its shutdown? Is there any thing particular about the file itself?

**Comment by saval** [comment]
Ok, seems it works. Yesterday I have worked on the development workstation with local server, Windows folder with project's code mounted to the Linux and probably issue in this. Today I checked this script on the test server and file was deleted as expected. So, sorry for false alarm, please close the issue. Thanks for your time.

**Comment by cjyclaire** [comment]
No problem! Glad that you worked out!
