### ISSUE TITLE
Typo added on S3SignatureV4 ?

### ISSUE THREAD

**Issue by danguer** [aws/aws-sdk-php#996]
Hi,

I'm getting an error with presigned urls on S3 with last version, I noticed the last change:
https://github.com/aws/aws-sdk-php/commit/0377ccb6988ee12d6a4c86eb1312f3059a63a861
Changed the value to a constant, but the previous value is: 
'UNSIGNED-PAYLOAD';
And the new value is:
'UNSIGNED PAYLOAD';

**Comment by cjyclaire** [comment]
Thanks for notice! New version has been released with fix. Free free to open if you have further questions.
