### ISSUE TITLE
3.18.9 breaks S3 signature generation

### ISSUE THREAD

**Issue by okdewit** [aws/aws-sdk-php#997]
Creating presigned URIs using the following method does not work in 3.18.9, the generated signatures are invalid.
https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-presigned-url.html

Rolling back to our previously installed version (3.18.6) works.

We are using aws-sdk-php through aws-sdk-php-symfony.

**Comment by Halama** [comment]
Same for me. I've just updated to 3.18.9 from 3.18.6 and presigned urls are broken.

**Comment by nodefortytwo** [comment]
It appears 3.18.8 actually broke the generation, 3.18.7 confirmed working for me.

**Comment by cjyclaire** [comment]
Thanks for notice, working on a fix release right now.

**Comment by cjyclaire** [comment]
Thanks to all! The fixed release is out.
